### ISSUE TITLE
document exports

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1001]
The message exports and records exports could use some documentation.

in the words of @mandric 

> gosh i really should have done more documentation.  ok so “Reported Date” or doc.reported_date is when the message was received by our system (it’s generated based on doc.sms_message.sent_timestamp). (edited)
> yeah we might open an issue to document the fields we are exporting.
> and “Sent Timestamp” (pretty sure only exists in messages export) is when the message was marked “sent” by our system.

My particular confusion is figuring out the difference between "Reported Date" and "Sent Timestamp" in message exports using the following filter:
```
/export/messages?startkey=%5B9999999999999%2C%7B%7D%5D&endkey=%5B0%5D&
filter_state=sent&filter_state_from=-90&filter_state_to=+1&dh_name=&tz=0&format=csv&locale=&reduce=false
&columns=[%22_id%22,%22patient_id%22,%22reported_date%22,%22related_entities.clinic.contact.name%22,%22related_entities.clinic.parent.name%22,%22sent%22,%22task.type%22]
```
based on code @abbyad wrote.

**Comment by garethbowen** [comment]
Added documentation: https://github.com/medic/medic-api/blob/develop/API_v1.md
