### ISSUE TITLE
Remove the rest of lucene

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1002]
Remove lucene completely.

- [x] Remove the fti api endpoint - as far as I know it's not used.
- [x] Remove ANC analytics from the UI and a whole lot of controllers from medic-api - apparently it's not used, but if it turns out someone wants it in the future we should rewrite it so it doesn't use lucene.
- [x] Remove the fulltext.js index file
- [x] Modify data exporting in medic-api to use views instead of lucene.
- [x] Check for anywhere else it may be used.
- [x] Remove couchdb-lucene, lucene, and the jre from medic-os.
- [x] Remove the lucene setup info from the README.md.
- [x] Remove the lucene-query-generator dependency in api/package.json

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by garethbowen** [comment]
@SCdF Kindly review the stage 2 PR above.

**Comment by SCdF** [comment]
Back to you young gentleman!

**Comment by garethbowen** [comment]
Leaving this with @browndav to test and merge the above commit to medic-os.

**Comment by garethbowen** [comment]
This has been merged in medic-os here: https://github.com/medic/medic-os/commit/94ae7ad898ca21f6856c574da1a19c124973571c

**Comment by garethbowen** [comment]
For AT make sure you get an updated medic-os build with lucene removed.

**Comment by ngaruko** [comment]
I have spoken to David and he assured me that `lucene` is gone. However, we need to check that there was no feature supported by lucene that has suffered from the change. `[beta.dev`](http://beta.dev.medicmobile.org/) is now currently `lucene-free` and there aren't currently no suspicious behaviors on the instance. I will close this unless there are features that might need more rigorous testing for this @abbyad @sglangevin ?

**Comment by garethbowen** [comment]
@ngaruko beta is running 2.15 and lucene was only removed in 3.0.0 (check the Projects section of this issue). This needs to be tested against an alpha.
