### ISSUE TITLE
Enforce filtered replication when user's permissions change

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1005]
If a user's permissions change (either changes district or role) we need to update the documents available in their local PouchDB. Replication alone doesn't solve this issue as the filter will only be checked for future changes, not already replicated documents.

One solution is to detect when the permissions for the current user have changed and prompt the user to delete their PouchDB and replicate from Couch from seq 0 again.

Any changes not yet replicated will be lost, but we're not sure if the user still has permission to make those changes either. Think about whether to just discard changes, or detect this case and warn users, or allow changes to be replicated. The third option may be the most correct and will require document update validations to be implemented server side to ensure they're not changing docs they no longer have access to.

**Comment by garethbowen** [comment]
This should also cover what we do when multiple users use the same phone. If user a logs out and user b logs in they shouldn't use the same db.

One idea is to modify the local db name to include the username so different users data will be stored separately. If we also included the permissions then they couldn't access the db if their permissions change.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
This is ancient and nobody's asking for it. It's still an area of concern. The workaround for now is to delete the user (or change the password). When you create a new user a new DB will be created on the phone.
