### ISSUE TITLE
Replicate document permissions changes

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1006]
With filtered replication, when a document is moved to another facility it will no longer be replicated to users who can no longer access it. These users will be left with a stale document in their PouchDB and no indication that it's out of date.

To update the local DB we need to make an update (A) that doesn't affect the filtered replication and then make the actual change (B). Users who have permission to view both will get both changes and be shown the latest version (B). Users who have permission only to see the new facility will only get (B). And users who have permission only to see the old facility will only get (A). In this example if (A) had a flag then the UI can check this flag and hide the record.

The most convenient flag for us is to use `_deleted:true` because this will automatically hide the record from all views without requiring any changes to the client side. Because `_deleted` is a special property in Couch this may not be possible but it's a good place to start.

**Comment by SCdF** [comment]
@SCdF please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by SCdF** [comment]
@garethbowen I want to close this. We don't support this can of worms but we are culturally aware of it. I think if it becomes a thing we want to support in the future we can work through these sorts of issues then. Agreed?

**Comment by garethbowen** [comment]
@SCdF Sure - it's fair to say we don't support moving in the hierarchy at all as we inline it in so many places.
