### ISSUE TITLE
Editing a user's language changes your own

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1008]
1. Go to the Configuration > Users screen
2. Edit a user other than yourself
3. Change their language to Spanish
4. Save the user

Your language shouldn't change, but the whole screen gets translated to Spanish.

I suspect it's an overzealous user modified listener.

**Comment by browndav** [comment]
Hey Alex, would you mind taking a stab at acceptance testing this? Just looking for confirmation that it's fixed in the latest development build. Thanks!

**Comment by alxndrsn** [comment]
LGTM
