### ISSUE TITLE
Chrome fails on appcache > 100 items

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1009]
We currently appcache 121 items. @alxndrsn has reported that Chrome fails on the 100th item. I've just had it happen but only in incognito mode.

121 is too many requests anyway and will have a significant performance impact. Look at reducing the number of static files. Templates are by far the most numerous. We should be able to use grunt-angular-template to precompile, minify, and concat the template files into one resource.

**Comment by garethbowen** [comment]
Got it down to around 40 items which should be ok for now.

**Comment by browndav** [comment]
Hey Alex, would you mind taking a stab at acceptance testing this? Just looking for confirmation that it's fixed in the latest development build. Thanks!

**Comment by alxndrsn** [comment]
Looks like we're down to 38 items in the cache, but I now get the following error:

log output|code ref
---|---
...|
`Application Cache Progress event (30 of 38) http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js`|`(index):1`
`2015-06-29 15:25:40.128 (index):1 Application Cache Error event: Resource fetch failed (2) http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js`|`(index):1`

I don't know if this is related.

**Comment by alxndrsn** [comment]
`inbox.js` is served fine if accessed directly, and the page seems to work fine.  I suspect it's failing to save in the cache because of its size (4.3MB).  Looking at `inbox.js`, it doesn't seem to be minified.  Running it through `uglify` gets the size down to 2.4MB.

I've found limited info online about the size limit (e.g. [this SO question](https://stackoverflow.com/questions/6757945/cache-manifest-size-limit-and-web-apps)).

**Comment by alxndrsn** [comment]
There's also a lot of whitespace in the templates which could probably be stripped.

**Comment by garethbowen** [comment]
FWIW it's minified in production, but not in development.

**Comment by garethbowen** [comment]
It looks like it only affects Chrome on Win/Mac which is why I wasn't able to reproduce the problem.

@alxndrsn Would you be able to look at this issue? We could look at minimising what we store, eg:

- trim whitespace from templates - the grunt plugin has an option for this but it won't save us much (10s of KBs) and when I tried it it ran for 2 minutes before I killed it.
- minify js in development - this would require sourcemap generation which I never quite got working

We might end up trying to store more than 5MB anyway especially if PouchDB uses some of it. The [Pouch FAQ](http://pouchdb.com/faq.html#data_limits) implies it uses temporary storage which is a different story, but I don't see how it _can_ use temporary storage without losing docs. So I think we need to [request more storage on Chrome](https://developer.chrome.com/apps/offline_storage#asking_more).

**Comment by alxndrsn** [comment]
On my machine, in Incognito Chromium, it looks like there's a size limit of `1310720 bytes` **for any one file**.  This seems quite arbitrary, so I'd be interested if it's the same for others.

**Comment by alxndrsn** [comment]
I think this is fixed in https://github.com/medic/medic-webapp/pull/1039. However, I think there is probably a better name for the JS file `stuff.js`.

**Comment by garethbowen** [comment]
The branch is not passing so this can't be considered fixed. Working on it now.

**Comment by garethbowen** [comment]
I've fixed the issues with the branch and merged.
