### ISSUE TITLE
Multiple scheduled reports for the same period are not merged as one

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1010]
Previously if a contact resent a scheduled report for the same month/week only the newest one was kept. This allowed a user to update a previously submitted report, as well as avoid duplicates in analysis.

We have not been able to get this to work for a recently updated instance, so either the feature is no longer working, or we are missing something and we need to document the feature. 

I have confirmed the issue on v0.4.5 and v0.5.0-alpha.1502, where the report was set as a `monthly` Scheduled Report in app_settings, and with the following in the form:

```
...
	"fields": {
		"year": {
			"position": 1,
			"type": "integer",
			"labels": {
...
				"tiny": {
					"fr": "y"
				}
			},
			"length": [1,
			1],
			"list": [[1,
			{
				"fr": "2013"
			}],
			[2,
			{
				"fr": "2014"
			}],
...
			[13,
			{
				"fr": "2025"
			}]]
		},
		"month": {
			"position": 2,
			"type": "integer",
			"labels": {
...
				"tiny": {
					"fr": "m"
				}
			},
			"length": [1,
			2],
			"validations": {
				"is_numeric_month": true
			},
			"list": [[1,
			{
				"fr": "Janvier"
			}],
			[2,
			{
				"fr": "Février"
			}],
...
```

**Comment by mandric** [comment]
Upon local testing this seems to work ok.  If I send in a report like `1!ISPF!3#5#2#0#0#3#0#0#30` then followup with one like `1!ISPF!3#5#23#0#0#3#0#0#304` the former is replaced/updated.  Can you provide more details about how you are experiencing the bug?

**Comment by abbyad** [comment]
I was not able to reproduce on our demo instance, running 0.4.7.

Testing on the production instance that was initially reporting the issue, I can no longer reproduce. Closing until we can reproduce again.

@mandric theory was that sentinel fell behind, crashed and restarted but didn't process the old messages. We can start by looking there if this issue resurfaces.

**Comment by juliomalikane** [comment]
Thank you @abbyad  and @mandric  for your support

**Comment by mandric** [comment]
we should consider opening an issue to look at the data on the instance to see if there are existing duplicates  and file an issue to fix backlog processing so it merges/updates these types of failures.
