### ISSUE TITLE
No blank option in the phone number conversion country code dropdown in Advanced Settings in Configuration

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1012]
Can't remove a country code replacement rule completely in Configuration > Settings > Advanced because there is no blank option in the replace country code for: dropdown. This is under the phone number conversion heading, replace country code for _________ with ________.

**Comment by garethbowen** [comment]
I can't add a blank option with the Select2 widget, but I have added a little `x` delete icon which clears the selection.
