### ISSUE TITLE
Update help window text for when MM is OFF - current text doesn't make sense

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1014]
When MM is OFF, the help window says: “SMS cannot be received while OFF. Click the 'ON' to turn get started”. Should say something like “SMS cannot be received while Medic Mobile is OFF. Click 'Turn ON' to continue receiving messages.”

**Comment by abbyad** [comment]
Given the simplicity of the change, moving to Ready. Reopen new issue if more text changes are needed.
