### ISSUE TITLE
Cannot delete a language

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1015]
Once I have created a new language in Config, it cannot be deleted. I clicked on Delete and then confirmed it, but it just said Deleting... and never deleted. I let it sit for at least 10 mins and it never deleted.

**Comment by abbyad** [comment]
I think we should try to fix this for DIY Beta 2, but is lower priority since our first set of users are unlikely to be creating/deleting languages.

**Comment by sglangevin** [comment]
Working well, moving to ready.
