### ISSUE TITLE
Text updates to Concierge for DIY

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1016]
Update the text in concierge to make account creation (username and password) clearer. There are updates to both steps 1 and 2. Store the email and phone number that the user enters for the future - no specific purpose currently, but they will eventually be useful for password reset. This issue does not include password reset.

See pages 5 and 6 of this mockup: https://beta.moqups.com/joshnesbit/5YohdufDGG/view/page/a1fa74951

**Comment by browndav** [comment]
Text is easy; I'll take care of that ASAP.

Is this the e-mail/phone collection a must-have for beta two, or could it wait until beta three? We have more work in the queue currently than we can reasonably accomplish, so I'm trying to trim down the next couple iterations – seems like collecting this information could wait until it has clear side-effects (read: until we're doing something meaningful with it).

**Comment by sglangevin** [comment]
I want to collect the information so that we have it and can see how users respond. That way we can make updates to Beta 3 based on feedback.

**Comment by abbyad** [comment]
For Beta 2 what we will do is add the fields, but will avoid validating the phone number. That will allow us to see how it is used, and by the time we have Beta 3 we will want to create a person in the Contacts tab based on this info too.

**Comment by sglangevin** [comment]
Cool, that sounds great!

**Comment by garethbowen** [comment]
@browndav Should this be Closed or not in acceptance testing?
