### ISSUE TITLE
Update app-settings to include Hindi

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1017]
Add Hindi to app-settings so that it appears as a language option upon install for DIY users.

https://github.com/medic/medic-data/blob/master/data/generic-anc/diy/app-settings.json

**Comment by garethbowen** [comment]
Will we have full Hindi translations available?

**Comment by sglangevin** [comment]
Yep, it's already done - just needs a home :)

**Comment by garethbowen** [comment]
Nice!

**Comment by garethbowen** [comment]
English name: Hindi
Code: `hi`
Localised name: हिन्दी

**Comment by garethbowen** [comment]
Added to default web app configuration and @sglangevin added to the default DIY configuration.

**Comment by sglangevin** [comment]
We've updated app-settings but Hindi doesn't show up as a language option in language preference or under config in the latest DIY build. Is there something else we need to do for that to happen?

**Comment by garethbowen** [comment]
@sglangevin: @mandric has fixed #1094 so please test this again in the next release.
