### ISSUE TITLE
PouchDB: Performance Testing

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1020]
Load as many documents as possible in to PouchDB to attempt to ascertain storage limits. Try lots of small documents, as well as a handful of large documents. Produce some kind of guidance (ideally a number) re: storage limits.

**Comment by btbonval** [comment]
Lots of small documents and a handful of large documents; you might want to
pick your counts using 80-20 rule as Power Law will likely give you a good
real world approximation of lots of small and few large.

So like, add 2 large files for every 8 smaller files for each iteration.
Keep doing that until you hit cap.

Within the smaller 8 files, you could break that into 2 medium files and 6
small files. Within the small 6 files, you could break that into 1 small
file and 5 tiny files. It's a fractal distribution, so its just 80% of the
total and 20% of the total no matter how many you're looking at.

**Comment by alxndrsn** [comment]
N.B. pouchdb can have "unlimited" storage if a javascript-java bridge is available to store directly in the android app's sqlite

**Comment by garethbowen** [comment]
Using local storage would be awesome! Remember that we still need to support browser usage so storage limits need to be tested at least on Chrome and Firefox.

**Comment by alxndrsn** [comment]
https://github.com/didimoo/AndroidLocalStorage project looks very interesting, although perhaps not 100% current.

**Comment by alxndrsn** [comment]
More reading: https://stackoverflow.com/questions/5899087/android-webview-localstorage

**Comment by alxndrsn** [comment]
http://pouchdb.com/faq.html#data_limits makes clear what the limitations of Pouch's capacity are.  @browndav is this good enough?

**Comment by alxndrsn** [comment]
Some meaningless stats from the current version:

Methodology:

1. click [fetch all]
2. click [start]
3. wait for iterations to finish
4. click [fetch all] ten times, waiting for result before the next click
5. click [add doc]

Chromium 44.0.2395.0 (64-bit)

metric | value
---|---
chars_added_this_session |	1023128
doc_count	|10000
fetch_count	|11
mean_fetch|	2846.4545454545455
last_fetch_time	|3130
put_count	|10002
mean_put	|163.9536092781443
last_put_time	|10

**Comment by browndav** [comment]
There are examples floating around that seem to allow instansiators of WebView to programmatically handle storage limit violations / raise the storage limits just-in-time. Might be worth taking a look:

```webview.setWebChromeClient(new WebChromeClient() { 
  public void onExceededDatabaseQuota(String url, String databaseIdentifier, long currentQuota, long estimatedSize, long totalUsedQuota, WebStorage.QuotaUpdater quotaUpdater) { 
    quotaUpdater.updateQuota(5 * 1024 * 1024); 
  } 
});
```

**Comment by garethbowen** [comment]
It'd be useful to also test the performance of a single doc fetch and a view query.

**Comment by browndav** [comment]
Stuff left: (a) test retrieval times for views; (b) test retrieval times for single documents; (c) make sure the quota-disable thing works.

**Comment by alxndrsn** [comment]
In response to (a) and (b), I've updated https://github.com/alxndrsn/pouch-db-capacity-testing to run some tests where the DB is filled, a view is generated to order the docs by content, and then some fetch timing tests are run.  Unfortunately, on my emulator, more than around 200 docs causes pouch to hang when building the db views (with idb).  Not impressive!  I suspect this is due to lack of space on my computer, though.  This leads on to (c) - I don't think there is a quota system for `idb`, but happy to be corrected on that.
I am currently testing on android emulator with `websql`, and will update with those results.

**Comment by alxndrsn** [comment]
On storage size limits:

> In modern Chrome and Android 4.4+, the size is simply ignored. The browser calculates the remaining size on disk and sets a limit based on that.
Aha, but in Android < 4.4, this is actually a hard limit! So if you ask for 5000000, you'll only ever get 5 MB.

http://pouchdb.com/2014/10/26/10-things-i-learned-from-reading-and-writing-the-pouchdb-source.html
