### ISSUE TITLE
Android container: Build initial first-run/login process in to container application

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1025]
1. Allow a mobile user to provide a username, password, and application URL on first run.
1. Allow an application URL to be optionally preloaded in some way (e.g. a list of "available applications" in a drop-down box, with some way to enter a URL if the app isn't in the list).
1. Cache the credentials and URL securely on the device
1. automatically provide these credentials over HTTPS on subsequent launches of the Android container app
1. Provide some indication to the hosted web app that it's running inside of the mobile container (via Javascript).

**Comment by alxndrsn** [comment]
# Progress

1. *DONE*
2. 
3. *DONE*
4. *DONE*
5.

**Comment by browndav** [comment]
Hey Milan, would you mind firing this up on an Android device to test it? Just looking for confirmation that it works and comments/suggestions if you have them.

**Comment by abbyad** [comment]
Self assigning since I want to get an APK out for internal testing anyhow.

**Comment by abbyad** [comment]
Works great, nice job @alxndrsn!

Confirming 1-4. Did not verify 5 from medic-webapp side, and did not test the security of 3 (credentials on the device).

**Comment by alxndrsn** [comment]
nice, thanks for the feedback.  *3* relies on the security of android's [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences.html).

Some discussion of that [on stackoverflow](https://stackoverflow.com/questions/9244318/android-sharedpreference-security):

> Shared Preferences are stored as a file in the filesystem on the device. They are, by default, stored within the app's data directory with filesystem premissions set that only allow the UID that the specific application runs with to access them. So, they are private in so much as Linux file permissions restrict access to them, the same as on any Linux/Unix system.

**Comment by browndav** [comment]
I think SharedPreferences is okay. For an MVP — especially if we're setting up the devices — we can add PINs and turn on the full-disk encryption on the Android devices themselves, I think.

@abbyad: Do you think that'd be a usability issue, or do we think our target CHWs are pretty used to the PIN/lock features on Android?

**Comment by abbyad** [comment]
Given how difficult it is to extract the password from SharedPreferences I think that is sufficiently secure. If a phone is lost/borrowed it is very unlikely that someone would even attempt to extract the password. Even if they did, the policy should be that lost phones get reported and password changed for that user. 

The bigger issue is someone borrowing the phone and accessing/altering the patient info. For now we can train users to set PINs, and see at a later time if we need a in-app unlock as well.

**Comment by browndav** [comment]
IIRC there are GUI apps that can extract preference data from unlocked Android devices pretty trivially. PINs + FDE should prevent both problems, I think. With you on the reporting/deactivation, though, that's probably our best first line of defense.
