### ISSUE TITLE
Design: UI/UX for the Android container's first-run/login process

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1026]
Issue #1025 is producing an initial version of the Android container's "first-run" login screen. In today's iteration kick-off meeting, we decided this would likely need some design work after the first version is done. Build out some quick mockups for the process, focused on interactions and UX.

**Comment by alxndrsn** [comment]
#1025 is in acceptance testing, so this can probably be started

**Comment by abbyad** [comment]
The UX from #1025 is sufficient for now. We can open a new issue at a later date for styling, or for enhanced UX as we add projects post MVP (eg get settings from QR code).
