### ISSUE TITLE
Prevent duplicates for Daily reports

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1028]
Currently only the newest monthly or weekly report for a given period is kept. That means that updated or duplicate reports are hidden. We now have projects that have daily reports that would also like to use this feature.

For monthly reports the required fields are `year` and `month`/`month_num`. For weekly reports `year` and `week`/`week_number` are required. For daily reports we could use `year`, `month`, `day` but it would _also_ be nice to be use a `date` field since it is used in ODK. Collect forms use a calendar or spinners for their date format, which is formatted as `YYYY-MM-DD`.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
We added a view for this but I'm not really sure how it's used. https://github.com/medic/medic-webapp/blob/master/packages/kujua-sms/kujua-sms/rewrites.js#L49
