### ISSUE TITLE
Reporting Rates for Daily Reports

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1029]
The reporting rates analytics are for Monthly or Weekly forms. As we now have projects with daily reports we are often being asked to have Reporting Rates for these daily reports. 

This is somewhat related to #1028 since the daily reports would use the same fields.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment]
Closing.  Please re-open/file again when required by a specific project.
