### ISSUE TITLE
Exporting reports for single district yields reports for all districts

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1031]
As reported in https://github.com/medic/medic-projects/issues/25, exporting reports for a district yields the reports for all districts.

Instance in question is running v0.4.7. Example export for Bhaktapur has 11 records:
![image](https://cloud.githubusercontent.com/assets/789512/8339268/321254aa-1a84-11e5-96e8-eb6007e1706e.png)

**Comment by browndav** [comment]
Clarification: this has regressed in 0.4.7, and we should release a 0.4.8 to fix it. We don't believe it's a problem in the development branch.

**Comment by garethbowen** [comment]
Also, the date filter is hilariously broken.

**Comment by garethbowen** [comment]
Fixed in testing.

**Comment by alxndrsn** [comment]
I can't get the `testing` branch to build - `grunt dev` gives:

```Fatal error: Can’t detect main file for "select2-bootstrap-css" component. You should explicitly define it via bower_concat’s mainFiles option. See Readme for details.```

**Comment by garethbowen** [comment]
You need to `rm -rf bower_components` to get rid of all the dependencies from `develop`.

**Comment by mandric** [comment]
Or little quicker is `rm -rf bower_components/select2-bootstrap-css` when going from a checkout of develop to testing.  

Also adding couple things here for the future... we probably want to do acceptance testing on a VM using the latest stable ISO.  It might also be good if we had ISO builds for master/testing/develop (release/beta/alpha).
