### ISSUE TITLE
Thoroughly test Reporting Rates / Stock Monitoring Analytics

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1032]
The Reporting Rates Analytics tab has changed a lot and hasn't been thoroughly tested for a while. We need to test to ensure we haven't broken or removed features used in older versions of the app.

**Comment by mandric** [comment]
Modified settings to include this but I get no links in the interface to the reporting rates.

```
"kujua-reporting": [
        {
            "code": "ISSN",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISLM",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISSM",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISSA",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISRE",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISPF",
            "reporting_freq": "monthly"
        },
        {
            "code": "ISSS",
            "reporting_freq": "monthly"
        }
    ],
```

**Comment by garethbowen** [comment]
Those forms (`ISSN`, etc) must also exist in the forms config. Then make sure you refresh the page so Angular fetches the settings from the server. Then it should work...

**Comment by mandric** [comment]
Did that then got our friendly 502 message for about 5 minutes.  Pulled the logs out... http://cl.ly/0F211F053e31/download/logs.tar.gz

The Stock Monitoring analytics comes up, but needs CSS work:

![screen shot 2015-07-07 at 4 11 51 pm](https://cloud.githubusercontent.com/assets/25641/8557474/3cf7d1d0-24c3-11e5-8b80-df4483364f34.png)
![screen shot 2015-07-07 at 4 13 03 pm](https://cloud.githubusercontent.com/assets/25641/8557470/39736772-24c3-11e5-952e-290e014c161a.png)

**Comment by mandric** [comment]
Looks like this lacks a design iteration or two.  Pretty sure that layout design came out of a design consultancy firm Free Association, we could probably re-engage for a mobile compatible layout/redesign.

**Comment by abbyad** [comment]
This issue was intended as part of v0.4 testing, and now new testing is being done as part of the v2.x update. I think we can close this issue and reopen a new one if needed following the changes v2.x.

**Comment by alxndrsn** [comment]
Definitely required in 2.x!  I'm filing issues for superficial stuff, but not that familiar with the functionality so it would be good if someone could go over it properly.  @bishwas-medic has also had a look, but not sure if he'd class it as thorough or not.

**Comment by bishwas-medic** [comment]
I wouldn't classify it as thorough :)

**Comment by abbyad** [comment]
I probably should have said _reopen a new one **when** needed following the changes in v2.x_

**Comment by alxndrsn** [comment]
I think we're ready for it!
