### ISSUE TITLE
Update Nepali default translations

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1034]
Add Nepali to app-settings so that it appears as a language option upon install for DIY users.

https://github.com/medic/medic-data/blob/master/data/generic-anc/diy/app-settings.json

I will add Nepali to the default DIY configuration and submit a pull request when ready.

**Comment by garethbowen** [comment]
@sglangevin It already is added, look at this line: https://github.com/medic/medic-data/blob/master/data/generic-anc/diy/app-settings.json#L17

**Comment by sglangevin** [comment]
@garethbowen I need to add the Nepali messages though.

**Comment by garethbowen** [comment]
Ahh ok, sorry!

**Comment by sglangevin** [comment]
@garethbowen I submitted a pull request a while ago for this issue so I bet it can be closed.

**Comment by browndav** [comment]
Bumped over to @abbyad for a quick confirmation.

**Comment by abbyad** [comment]
Merged the changes, @sglangevin if you notice any issues with this in the next release please open a new issue.
