### ISSUE TITLE
fields fail to render with form configuration change

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1036]
1) Configure an instance with forms and settings
2) Send in some test messages/reports
3) Upload new forms with different form codes
4) Refresh reports screen

Fields on the records are not rendered.  I would expect existing records to be mostly unaffected by a configuration change.  This means if I have an instance configured for form XYZ then I remove that form configuration change to ABC the previous records can't be viewed.

**Comment by abbyad** [comment]
This behaviour is different then it was, but it could be perceived to be a feature.

*Pros*
- Minor form updates could be handled gracefully (similar to concept of "version" in ODK)
- Can remove old forms from being shown in filters and exports

*Cons*
- Submissions of forms that have been removed do not have fields rendered in Reports tab
- Submissions for removed forms cannot be exported

I think that what we actually want is likely somewhere between what we had and we have now, and for that we'd need a concept of inactive/active forms. All forms definitions would be exported/imported, but we could mark some as inactive. 

For an *inactive form*, new submissions would be treated as invalid, but any form submission from when it was active would still be rendered in Reports tab and could be exported. 

New submissions of inactive forms could be shown as invalid message that failed a validation, and we can have custom response message in app_settings. Ideally, there would be a response message for any submission of an inactive form, which could be overridden by a form specific inactive form response message.

We may want to wait to tackle this when we are integrating ODK forms as well. In the meantime we can make sure that projects only remove forms from instances when they are sure they do not want to view or export existing submissions.

**Comment by mandric** [comment]
I find it strange to have a record change like that within the interface or suddenly have the data inaccessible or unavailable. 

Form management is still a manual process at this point so the burden could be pushed to that process and through a technical project lead/person.  As more time passes though, especially if we ever want an actual DIY offering we'll need to solve the form management problem and that will take quite a bit of design work.  We might consider starting an issue on form management/documentation to keep tabs on what the current form features are and effects of changing forms.

Inactive/active forms sounds like a good idea, so a specific form and version is never removed from the system so a record rendered one time can be rendered forever.
