### ISSUE TITLE
Rename git branches in line with common names

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1043]
We seem to have two naming schemes for our development streams:

testing/develop/master

vs

alpha/beta/gamma

It would be great if we could use a single consistent scheme.

**Comment by mandric** [comment]
We’ll need to update a few of the travis scripts that check some branch names before pushing to market.

**Comment by mandric** [comment]
Everything merges into `master` now and betas and releases are done based on the git tag see:  https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#branches
