### ISSUE TITLE
Mobile App: Make our Android container build on Travis CI

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1045]
It'd be great if we could do automated builds of the Android container, as well as add unit tests for CI once we get in to stuff like native Javascript bindings (e.g. for SMS or notifications). We should add a `.travis.yml` file and see if we can get CI to churn out APKs.

Speculatively assigning to @alxndrsn.

**Comment by alxndrsn** [comment]
Working: https://travis-ci.org/medic/medic-android

Where do you want the APKs to go?

**Comment by abbyad** [comment]
APKs could go on dev.medicmobile.org/downloads/medic-android/
