### ISSUE TITLE
Concierge: Rename the `vm` system account to match the configured username

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1046]
Currently, the SSH and system user name is always `vm`, regardless of what was entered in to concierge. This is unintuitive. Changing the username to match the named CouchDB account would reduce attack surface and better match user expectations.

**Comment by alxndrsn** [comment]
Moving to backlog as no milestone is assigned.

**Comment by browndav** [comment]
This isn't necessary at this time. Closing as ancient; will file a new more descriptive/encompassing issue related to Concierge and early setup after CouchDB 2.x compatibility is achieved and upgrades are solid.
