### ISSUE TITLE
Automate building of DIY installer

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1049]
The DIY installer is currently built on a Windows machine with a mix of manual and scripted steps. We should automate this build process and publish an exe whenever any component or subproject gets updated.

The main repo is [medic/medic-msi](https://github.com/medic/medic-msi), subprojects are:
- [medic/medic-launchpad](https://github.com/medic/medic-launchpad)
- [abbyad/vmware-helper](https://github.com/abbyad/vmware-helper)
- [abbyad/winsw](https://github.com/abbyad/winsw)

Additional binaries are currently kept locally, but should be loaded at build time. We can host these files on S3.

I am testing a build on an EC2 Windows Server 2012 AMI, but ideally this could be run using a CI platform. Otherwise we can schedule a task on the EC2 instance.

-----

# Steps to automation:
```
[x] install jenkins
[x] automate build: abbyad/vmware-helper
[x] automate build: abbyad/winsw
[x] automate build: medic/medic-launchpad
[x] automate build: medic/medic-msi`
  [x] build `.msi` file
  [x] build NSIS installer `.exe`
  [x] publish built `.exe` to S3
[x] commit jenkins config to version control
[x] document windows server setup in relevant git repo
[x] allow config of `medic-os` version when launching a `medic-msi` build

**Comment by alxndrsn** [comment]
Steps to automation:
```
[x] install jenkins
[x] automate build: abbyad/vmware-helper
[ ] automate build: abbyad/winsw
[ ] automate build: medic/medic-launchpad
[ ] automate build: medic/medic-msi`

**Comment by alxndrsn** [comment]
This is done.  Builds available in `builds/medic-msi` in the S3 bucket.  Suggested next steps:

* make sure that all built commits are tagged in github
* add a job to monitor the jenkins config and warn when it's not synced to git

**Comment by browndav** [comment]
Bumping over to @abbyad for acceptance testing, as he's (much) more familiar with the build process and installer implementation details.

**Comment by abbyad** [comment]
> [x] document windows server setup in relevant git repo

@alxndrsn in which repo is this doc - do you have a link?

**Comment by abbyad** [comment]
The build process works well overall but a couple of outstanding issues:
- The build does not create the complete EXE, but rather the MSI of the Medic components only.
- The URL for the ISO is hard linked to a versioned file name. We should have a symlink to the latest ISO.

**Comment by alxndrsn** [comment]
Have updated so:
* NSIS installer `.exe` is uploaded instead of `.msi`
* `medic-os` version is chosen at build time

**Comment by abbyad** [comment]
Makes sense to choose the medic-os version at run time. 

As for the exe, as mentioned in the [repo's issue](https://github.com/medic/medic-msi/issues/3), the NSIS method is the old way that the installer was built. The EXE should be created with the light.exe from within [makeMSI.bat](https://github.com/medic/medic-msi/blob/12148c7202b3fe9999cd5a5931e3d376ecc87d6d/makeMSI.bat#L34)

Reopening as we should find out why the exe was not being created.

**Comment by abbyad** [comment]
Works better now with the (proper) EXE being pushed to S3. The final issue that I see is that the build number isn't being auto incremented, which would happen if this was built locally. I think we could safely use the build revision for this - ideally bumping the rev past the last publicly used rev (52)

We could also parameterize the build version (eg `0.2`) and type (eg `alpha`), but we can also leave those as files in github. This means that updating the build details requires updating and committing the files in the repo. Whichever method is used, this build process should be documented. Other than that the overall build process looks good.

**Comment by abbyad** [comment]
Removing `Acceptance Testing` as this works well. Possible improvements will be posted in a separate issue since it can be tackle later.
