### ISSUE TITLE
Redesign reporting rates UI

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1056]
Reporting Rates UI needs a mobile compatible layout.  See also https://github.com/medic/medic-webapp/issues/1032

**Comment by mandric** [comment]
If you want to see the current implementation we can configure alpha.dev to show it. https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/analytics/

**Comment by abbyad** [comment]
Sure thing @mandric, can you configure that one (or another) to show it? I just tried but encountered some loading errors.

**Comment by mandric** [comment]
I set something up for the time being on iriscouch since 1) I don't want to mess up alpha and 2) we're looking at beta and v3.  It's not entirely bug free but should hopefully provide enough info for this issue.

v3: http://mandric.iriscouch.com/medic/_design/kujua-lite/_rewrite/reporting
beta: http://mandric.iriscouch.com/medic/_design/medic/_rewrite/#/analytics/
u/p: demo/medic

**Comment by abbyad** [comment]
Thanks for setting that up @mandric. I'm working with @Lesterng and @yembrick on the new designs, and will post them here when ready to share.

**Comment by abbyad** [comment]
Just spoke to @Lesterng and @yembrick, and Lester is looking to have a lightweight UI pass done within about two weeks.

In the meantime, we discussed moving the Form Name and Time Period to the top bar like the filters on the other tabs. This should help simplify the interface, but means that the filters would need to update based on the contents of the previous filter. For instance Form A may be monthly so would have `this month` whereas Form B could need `this week`. Still open to other suggestions.

Overall, we want this to be a relatively lightweight pass as we will look at doing a heavier pass once we start building more complex Analytics into the webapp in the mid-long term.

**Comment by garethbowen** [comment]
Closing this as ancient. A design issue can be raised if this becomes a priority.
