### ISSUE TITLE
facility reference code fails to match when using integers and textforms

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1058]
If the refid field on a record is created as an integer then when the update_clinics sentinel transition tries to query for facilities it gets no results.  There is no match because the reference code is saved as a string on the facility doc.

See https://github.com/medic/medic-sentinel/blob/develop/transitions/update_clinics.js#L63

**Comment by mandric** [comment]
The code fix here is pretty easy, I just need to add a test... then will move it to acceptance testing.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
@mandric looks like this one was completed a long time ago and the only thing missing was a test. I'm closing this issue. Please open a new issue for the test if it's still needed.

**Comment by mandric** [comment]
Looks good, tests are there in the PR.
