### ISSUE TITLE
Exporting yields same result with or without Date Filter

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1059]
As reported by @pkaini [here](https://github.com/medic/medic-projects/issues/27), the data filter is not respected when exporting from `/medic/_design/medic/_rewrite/forms`.

I tested on v4.7 and got the same result.

**Comment by garethbowen** [comment]
I think this is fixed by the same fix as #1031 . We should double check to make sure.

**Comment by garethbowen** [comment]
I'll test this against alpha and make sure.

**Comment by garethbowen** [comment]
This is fixed in beta.

**Comment by mandric** [comment]
@abbyad maybe you should acceptance test this since you opened it?
