### ISSUE TITLE
[enketo] Hide and Prepopulate fields

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1060]
Now that we are rendering Enketo forms (https://github.com/medic/medic-webapp/issues/1053) we want to find a way to hide fields as well as prepopulate fields. 

These are needed when completing a form about a person, because we would want to submit their ID but not show this ID to the user.

Hidden fields can already be done by manually editing the XML to remove the input from the `<h:body>`, but leaving the corresponding element in the `<model>`. ODK has [some ability](https://opendatakit.org/help/form-design/data-preloading/) for populating fields with an .csv, and Smart Paper may have other mechanisms, but either way, we would need to see which mechanism is most appropriate for our use case.

**Comment by alxndrsn** [comment]
@abbyad What are the `,` and the `.` in the OP?

**Comment by alxndrsn** [comment]
Looks like hidden fields should be fairly simple - this is done already to attach a `uuid()` to each form.  We might need to add our own way to bind data to these.

**Comment by abbyad** [comment]
Ha, those were xml tags that weren't rendered. Post aboved edit.

**Comment by abbyad** [comment]
Ideally we could use `appearance="hidden"` to hide a field, which does not (yet) seem to be supported by any renderer.

eg `<input appearance="hidden" ref="/data/patient_id">`

**Comment by alxndrsn** [comment]
## Hiding fields

### Via `meta` fields
Depending on the form editor, it may be possible to add extra `meta` fields to a form.

### Via normal fields
Hiding a field could be achieved via the `appearance` attribute of a standard `<input>` in XForms xml, e.g.:
```xml
<input appearance="hide-input" ref="/data/topsecret_var">
    <label>Top Secret Var 1</label>
    <hint>No clues - this one's secret!</hint>
</input>
```
We would then need a corresponding `or-appearance-<customAppearance>` CSS rule to keep that field hidden, e.g.:
```css
.or-appearance-hidden { display:none; }
```

## Precalculating values
This can be done via a `<bind>` tag in the xforms xml.  See [ODK docs](http://opendatakit.org/help/form-design/examples/#preload_params) and [Javarosa docs](https://bitbucket.org/javarosa/javarosa/wiki/xform#!bindings) for more information.
It will be possible to extend the bindings or calculations that can be performed, but it's unclear how difficult or maintainable different approaches would be.

## Notes
* without knowing which editors we want to use, it's unclear how to apply `appearance` or `bind`ings
* a client could tamper with these precalculated values

**Comment by abbyad** [comment]
Good find on the hidden field. Here is a related blog post: http://blog.enketo.org/geo-hide-inputs/

The intention of the prepopulated field for this issue is different than that of the calculations. We would need to passing a value to the report, such as passing a patient ID to a field on a form. Is that possible via a URL param to the form?

**Comment by alxndrsn** [comment]
> We would need to passing a value to the report, such as passing a patient ID to a field on a form. Is that possible via a URL param to the form?
> _@abbyad_

We'd have to add hooks for this, either in JS, or a combination of JS and xpath functions.  Where is this likely to be triggered from?

**Comment by abbyad** [comment]
We would need to prepopulate fields when we open a report from a task or patient profile. In these cases we would likely pass the patient ID to the report so that we can know who that report is about.

**Comment by abbyad** [comment]
Closing in favor of #1185
