### ISSUE TITLE
Design for login page

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1061]
As part of #1038 I've created a simple login screen (below). This could benefit from a design pass before being forced upon our users.

![login-screen](https://cloud.githubusercontent.com/assets/2064938/8664944/4ffc9df0-2a32-11e5-99f5-b4ed68613dcf.png)

**Comment by abbyad** [comment]
I think that looks good already, and is ok to leave as is for the time being.

Will leave open as part of DIY Beta 3, for which we want to include:
- Forgot username/password
- Show password (see what was typed instead of ******)

**Comment by garethbowen** [comment]
Closing as nobody has complained over the current design.
