### ISSUE TITLE
Standardise on loading spinner

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1062]
We use three different spinners in three different areas of the app.

#### fontawesome spinner in the webapp

![fontawesome](https://cloud.githubusercontent.com/assets/2064938/8666565/8487e452-2a47-11e5-8a19-e97eb63a7f51.png)

This is choppy in some sizes and requires downloading the font so it doesn't render right away and is hard to use, which is why it wasn't used in the login page and concierge.

#### css pulse in login page

![pulse](https://cloud.githubusercontent.com/assets/2064938/8666602/14728996-2a48-11e5-97bf-5b214cfa20f8.png)

This is small vertically and quite attractive and has simple colouring.

#### css spinner in concierge

![concierge](https://cloud.githubusercontent.com/assets/2064938/8666568/8f4f3502-2a47-11e5-9a49-ef5e2ea37c3c.png)

This is too colourful (in my opinion) and a bit large.

Pick one of the above, or something completely different, and implement throughout the stack.

Some resources:
1. http://tobiasahlin.com/spinkit/
2. http://projects.lukehaas.me/css-loaders/

**Comment by abbyad** [comment]
I agree that consistency would be nice... we should also add the spinner to the theme page. 

Personally I prefer single color, and am ok with either horizontal or circle, with a slight preference for the horizontal. Or if this if going with circle:
![image](https://cloud.githubusercontent.com/assets/789512/8677915/c48a9694-2a1f-11e5-8f29-731bcde30c3d.png)

@Lesterng, please weigh in on this conversation, and add the "winning" choice to the theme page.

**Comment by Lesterng** [comment]
I also prefer one simple spinner for everything. Prefer the circle with a simple spin.
![screen shot 2015-08-13 at 2 10 59 pm](https://cloud.githubusercontent.com/assets/5149601/9261819/5eb26ce4-41c5-11e5-9f35-a15f329154cd.png)

**Comment by garethbowen** [comment]
Waiting for the medic-os PR to be merged for this to be closed.
