### ISSUE TITLE
Use Travis build number as Android build number

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1069]
As followup to #1064, the auto-incremented Travis build number should be used as the Android build number (aka `versionCode`).

The versionCode for medic-collect is already at 1069 so we would need to bump Travis build number accordingly, otherwise existing installations requires an uninstall.

Also, we should ensure that we can still build locally since the build number wont be provided by Travis. For local building the versionNumber should not be auto-incremented.

**Comment by alxndrsn** [comment]
Probably worth doing this for medic-android too once we've worked out the config.

**Comment by alxndrsn** [comment]
Crazy coincidence that this is issue #1069 and the `versionCode` is `1069`!

**Comment by abbyad** [comment]
Weird coincidence!

Looks good, removing `Acceptance Testing` label
