### ISSUE TITLE
[android] Login handling for bad URLs is confusing

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1077]
If you specify the URL of your couch instance correctly, but get the db name wrong (or omit it completely):

1. login form is shown, but field labels are not translated (e.g. `{{ translations.username }}` instead of `User name`
2. on submitting the login form, app redirects to a couchdb error:

        {"error":"not_found", "reason":"no_db_file"}

As there is obviously some way of detecting a valid db URL (translations seem to manage!), it would be good if the android app could check this at form validation time to prevent user configuring a bad URL.

**Comment by alxndrsn** [comment]
```$ curl localhost:5988
{"couchdb":"Welcome",...}}

$ curl localhost:5988/
{"couchdb":"Welcome",...}}

$ curl localhost:5988/nonsense
{"error":"not_found","reason":"no_db_file"}

$ curl localhost:5988/medic
{"db_name":"medic",...}
```

It may be sufficient for the settings validation in android to GET the supplied URL, and check that:
1. it's provides valid JSON, and
2. it has a `db_name` field

As an extension, a more helpful error message can be provided or autocorrect can be performed, if the resulting JSON has the `couchdb` field.

**Comment by abbyad** [comment]
Long overdue acceptance testing, but closing the loop to say that it is working well now.
