### ISSUE TITLE
[api] should give 404 when `/login` requested

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1078]
# Observed
requesting `/login` from API will give the login page, without text i18n.

# Expected
should respond with 404

# Notes
The actual login URL is `/<dbName>/login`, usually `/medic/login`

**Comment by alxndrsn** [comment]
Appears to be because `.../login` URL is matched:

```server.js
 81 app.get(pathPrefix + '/login', function(req, res) {
```

and pathPrefix is defined:

```server.js
 40     appPrefix = pathPrefix + '/_design/' + db.settings.ddoc + '/_rewrite',
```

and db.settings are defined:

```db.js
 12   module.exports.settings = {
 13     protocol: parsedUrl.protocol,
 14     port: parsedUrl.port,
 15     host: parsedUrl.hostname,
 16     db: parsedUrl.path.replace('/',''),
 17     ddoc: 'medic'
 18   };```

**Comment by alxndrsn** [comment]
Looks like a lot of stuff depends on `pathPrefix`, and therefore may not work if `db.settings.db === ''`

**Comment by alxndrsn** [comment]
It's not clear to me what the best course of action would be here, e.g.:

1. throw an `Error` in `db.js` if the path suggests that no database name has been provided
2. in `server.js`, don't map `pathPrefix`ed URLs if `pathPrefix` is empty

etc.

**Comment by alxndrsn** [comment]
Or is this just because the `login` folder is being served in `server.js` via

         80 app.use(express.static('./public'));

?

**Comment by garethbowen** [comment]
Now it just forwards `/login` to couch and you get a 404 with `{"error":"not_found","reason":"no_db_file"}`. This is correct for unknown urls.
