### ISSUE TITLE
sign medic-collect builds

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1079]
https://github.com/medic/medic-collect/issues/24

Tasks:
* change travis build to upload debug builds to S3
* generate signing cert on jenkins box
* add jenkins job for building for release

**Comment by alxndrsn** [comment]
Tasks:
* change travis build to upload debug builds to S3
* generate signing cert on jenkins box
* add jenkins job for building for release

**Comment by abbyad** [comment]
Works well, removing Acceptance Testing label
