### ISSUE TITLE
create job to push medic-android builds to appstore

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1081]
Most suitable place to do this is one of
* dev machine
* jenkins

**Comment by browndav** [comment]
From the iteration planning call: we should look in to the Google Play beta track.

**Comment by garethbowen** [comment]
Reference: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

**Comment by alxndrsn** [comment]
@abbyad I think we'll need to upload a release APK manually before we can do it via API.  Any chance you can look at this?  There should be some available on S3, I can point you in the right direction.

**Comment by abbyad** [comment]
Just posted the release APK to "Alpha Testing"

**Comment by abbyad** [comment]
Works well, process documented [here](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md)
