### ISSUE TITLE
create job to push medic-collect builds to appstore

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1082]
Most suitable place to do this is one of
* dev machine
* jenkins

**Comment by alxndrsn** [comment]
Most suitable place to do this is one of
* dev machine
* jenkins

**Comment by alxndrsn** [comment]
Done.

Also made a slight change to `medic-collect` - now different app flavours have different `applicationId` values.  This means that the app store will treat them as different apps and so allow different brands to exist at the same time.  More info at https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/applicationid-vs-packagename

**Comment by abbyad** [comment]
Thanks @alxndrsn, it worked well when I tested the manual push via Jenkins. It's probably worth putting a small note in medic-docs on how do to do this.

The last bit is building with the project files for project flavors (#1097). Will remove Acceptance Testing once that closes.

**Comment by abbyad** [comment]
Retested and the push to the app store did not work automatically. There are no errors in the Jenkins build and the output shows that the APKs were pushed to S3, but no mention of app store.

@alxndrsn was something related to this changed since I tested this two weeks ago?

**Comment by abbyad** [comment]
Nevermind.... there is a separate Jenkins project (`medic-collect-publish`) for pushing the apk to the app store.

**Comment by abbyad** [comment]
Publishing the updated apps works well. The process is documented [here](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md)

Removing from acceptance testing.
