### ISSUE TITLE
Finish conversion to PouchDB

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1084]
Ensure all database calls that should be available offline go through PouchDB. This includes anything a CHW might see.

Go through all TODOs in the DB module and fix or create issues for them.

**Comment by browndav** [comment]
Notes from the milestone review call: we agreed that the analytics and configuration tabs weren't important to convert at the moment.

**Comment by garethbowen** [comment]
I propose we split the user document into two with a new one stored in the medic database which contains all the information that's safe for replication. This would allow offline access and modification to the users language, the first run flag, contact information, etc.

To accomplish this...
- add an api migration task to split users
- modify the users admin controller to modify both objects in the existing UI
- split the current modal for updating your own profile into one for settings, and one for changing your password which requires online access
- update concierge to store details in the two user objects

**Comment by browndav** [comment]
I think this sounds sensible. Just to be clear, we're still planning to only replicate the currently-logged-in user's settings document (as opposed to all of them for all users), right?

**Comment by garethbowen** [comment]
Yeah it'd be part of the replication filtering that you only replicate your own settings.

**Comment by browndav** [comment]
+1 here, I'll spin off an issue for concierge / medic-os.

**Comment by garethbowen** [comment]
PRs ready for review:
- https://github.com/medic/medic-webapp/pull/1113
- https://github.com/medic/medic-api/pull/26
