### ISSUE TITLE
Make Jenkins publicly accessible in a secure way

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1085]

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by estellecomment** [comment]
We use Jenkins?! @alxndrsn throwing it over the wall to you

**Comment by SCdF** [comment]
(we use Jenkins for android builds yeah)

**Comment by alxndrsn** [comment]
Current set up is acceptable.
