### ISSUE TITLE
Embed enketo-core in medic-webapp

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1086]
Include via `browserify`?

**Comment by browndav** [comment]
Quick update: initially, I think we'd like to put Enketo in the right pane of the reports tab, where we currently display an uneditable version of the form submission data. We might consider making this stateful, i.e. being locked for editing by default, and requiring an explicit click of an edit button to start making changes. From there, we can make more wide-reaching decisions about modals and/or more far-reaching user interface changes.

**Comment by alxndrsn** [comment]
Available at: https://github.com/alxndrsn/medic-webapp/tree/1086_embed-enketo-core-with-browserify

# Issues:
* currently embedded in non-modal dialog as per Muvuku
* using [`almondjs`](https://github.com/jrburke/almond) so requirejs structure can be maintained
* code is copy/pasted into `static/enketo`, rather than included through e.g. `bower`
* still including an extra jQuery
* need to hash XSL files to prevent browser cacheing when their content changes (or some other form of cache-busting) - XSL cacheing seems to be aggressive
* using static forms served from `static/dist` and stored in git at `static/enketo`

# Points of happiness:
* js dependency is 190KB - *much* better than expected, and this includes jQuery which is ~80KB minified

# Next steps
* If we want to fully eliminate the requirejs I would appreciate help with this - have tried and it's not obvious
* Do we want to embed in the right-pane as per @browndav's suggestion above, and if so:
  - should it be part of this ticket?
  - do we need some UX done on this?
