### ISSUE TITLE
Implement browser vs enketo XSL transform tests

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1087]
1. Wait for resolution of https://github.com/enketo/enketo-transformer/issues/4
2. Complete transform tests for `enketo-transformer` vs [`enketo-client-side-transformer`](https://github.com/alxndrsn/enketo-client-side-transformer).
3. Add more example forms from our archives

**Comment by alxndrsn** [comment]
Unblocked by https://github.com/alxndrsn/enketo-client-side-transformer/issues/5

**Comment by browndav** [comment]
I fixed the OS X compilation issue and upstreamed the patch: https://github.com/gagern/libxmljs/pull/1. If that works for you on 10.10, can we close this as no-longer-necessary?

**Comment by alxndrsn** [comment]
Nice one.

**Comment by alxndrsn** [comment]
Done at https://travis-ci.org/alxndrsn/enketo-client-side-transformer
