### ISSUE TITLE
medic-collect applicationId

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1089]
Having different `applicationId` values for `medic-collect` flavours has problems detailed in https://github.com/medic/medic-collect/commit/2425a219c31dda6109debb245fbf2716282305b7:

> If the applicationId is changed then all of the explicit intents also
need to be
updated. Otherwise activity calls like
`android:targetClass="org.odk.collect.android.preferences.PreferencesActivity"`
in admin_preference.xml cause a crash: `Unable to find explicit activity
class`

Having flavours share an `applicationId` is also troublesome, as per https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/applicationid-vs-packagename - basically they will all be treated as the same app by the google play store.

**Comment by alxndrsn** [comment]
@abbyad I can't recreate the problem when a different `applicationId` is set

**Comment by abbyad** [comment]
To recreate original `applicationId` issue:
- Set different `applicationId` for each flavor. 
- Install and open app with new id
- Go to Settings > `Admin Settings`, then select the top option for `General Settings`. 
- App will crash.

I will look into a workaround to avoid the crash.

**Comment by alxndrsn** [comment]
Stacktrace:
```
E/AndroidRuntime( 1400): android.content.ActivityNotFoundException: Unable to find explicit activity class {org.medicmobile.collect.android/org.odk.collect.android.preferences.PreferencesActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime( 1400): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
E/AndroidRuntime( 1400): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime( 1400): 	at android.app.Activity.startActivityForResult(Activity.java:3424)
E/AndroidRuntime( 1400): 	at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime( 1400): 	at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime( 1400): 	at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime( 1400): 	at android.preference.Preference.performClick(Preference.java:970)
E/AndroidRuntime( 1400): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime( 1400): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime( 1400): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime( 1400): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime( 1400): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime( 1400): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 1400): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1400): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1400): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 1400): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1400): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1400): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 1400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 1400): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  359):   Force finishing activity org.medicmobile.collect.android.intrahealthsenegal/org.odk.collect.android.preferences.AdminPreferencesActivity```

**Comment by alxndrsn** [comment]
Looks like an example of the bug at https://github.com/sigmabeta/dolphin/commit/0c993ad4a9f153531e544e4fab2fc9e0ea4311da#commitcomment-12302549

**Comment by abbyad** [comment]
Resolved with https://github.com/medic/medic-collect/commit/fd04f30

**Comment by abbyad** [comment]
I ended up using the (lesser voted on) approach [here](http://stackoverflow.com/a/20684784) for its simplicity.

**Comment by alxndrsn** [comment]
Looks nice - maybe you should give them an upvote ;-)

**Comment by alxndrsn** [comment]
LGTM
