### ISSUE TITLE
Support role-specific tab configurations; add empty/stub "resources" tab

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1090]
Part of the CHW Mobile Application design includes a "resources" tab, which would likely contain reference and/or training materials. These materials, at least initially, will be Javarosa forms rendered through Enketo.

In order to make space for this tab, we need to allow tab configurations to be adjusted via some kind of stored configuration. Specifically, we want to hide the messages, analytics, and configuration tabs for CHW mobile app users. This _could_ be achieved based on the type of device accessing the app, but such a solution would likely run in to problems when a clinic worker (like a nurse) uses a phone or tablet to access clinic-centric features at the clinic.

Insert a stub/empty tab after this is achieved to prove it works.

**Comment by garethbowen** [comment]
The configurable permissions should be used throughout the webapp and api, and the default settings should be updated in medic-data.

**Comment by mandric** [comment]
Nice work!
