### ISSUE TITLE
Extend demonstration dataset: provide demo data for the rule-based Tasks system

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#1092]
To give an effective demo of the rule-based tasks tab, we'll need a pile of sample data that triggers an approximately-realistic set of tasks. Extend the demo dataset so that a reasonable set of tasks appear on first run. We can hash out the definition of "reasonable" on Slack or in the comments below.

**Comment by sglangevin** [comment]
Can we include some R forms in the extended demo dataset? They would be really helpful for Analytics testing purposes as I need some pregnancies registered with no LMP to appear in either missed or upcoming appointments to see if the weeks pregnant is accurate and to ensure we are indicating that weeks pregnant is approximate.

**Comment by mandric** [comment]
I have an extended data set in my working tree uncommitted. I need to refactor it a bit and will commit, I'd like to create a "generic" one that exercises most of our features.  It would help to actually write this down (what features to exercise) somewhere and go from there.  Right now it looks like our generic-anc config + additional reporting rates data and maybe a few other things.

**Comment by garethbowen** [comment]
Closing as ancient.
