### ISSUE TITLE
Extend demonstration dataset: provide demo data for Reporting Rates 

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1093]
To give an effective demo of the reporting rates feature, we'll need a pile of sample data that produces a fully-populated dashboard. Extend the demo dataset so that the reporting rates tab is populated reasonably on first run. We can hash out the definition of "reasonably" on Slack or in the comments below.

Important: This is the non-critical one, as we likely won't be demoing/using it for the first September demo. Please pick up #1092 before this one.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by abbyad** [comment]
Closing as we have not needed this demo set. We can open a new issue if this becomes needed again.
