### ISSUE TITLE
Reconcile generic-anc default app settings

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1094]
In the [default generic anc configuration](https://github.com/medic/medic-data/tree/master/data/generic-anc) we have directories for `demos` and `diy`. Currently demo is a DIY install with a bunch of demo data included (`facilities.json` and `messages.json`) so we can show off the app features. We also have configuration in each (`forms.json` and `app-settings.json`) which should be the same for each. Over time the settings have diverged so changes are being added to the DIY configuration which are not showing up in the demo ISO.

Firstly, merge the `forms.json` and `app-settings.json` so DIY and demo get the same settings.

Secondly, find a way to stop this happening again. Maybe we should have the settings in the `data/generic-anc/` directory and if required include a settings patch in `data/generic-anc/demos` to make modifications specific to demo. Alternatively we could link from `demo/app-settings.json` to `diy/app-settings.json`. Or come up with something better.

**Comment by browndav** [comment]
To do: commit a work-in-progress PR today for review.

**Comment by abbyad** [comment]
@garethbowen, I'm assigning this to you for acceptance testing since you were the OP.

**Comment by mandric** [comment]
Thanks Marc.

**Comment by garethbowen** [comment]
Lovely!
