### ISSUE TITLE
[collect] project-forms should be imported at build time for releases

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1097]
TASKS
* check out project forms as part of release build process
* include reference to the version of project-forms that are being used somehow in the APK

**Comment by abbyad** [comment]
I don't think the apk needs the version of the forms, instead we could put a tag in medic-projects. Something like `medic-collect-build1095`.

**Comment by alxndrsn** [comment]
Should be updated now.

**Comment by ngamita** [comment]
Thx can now view the forms. I'll share separate issue with crashes when i
click on send finalized form.

**Comment by abbyad** [comment]
@ngamita I was not able to reproduce the crash that you mentioned. Feel free to create a new issue in [medic-collect](https://github.com/medic/medic-collect/issues) and please post more details.

**Comment by abbyad** [comment]
@ngamita the crash you described is described and fixed [here](https://github.com/medic/medic-collect/issues/1)

**Comment by abbyad** [comment]
Looks good, thanks @alxndrsn.
