### ISSUE TITLE
`medic-collect` build should tag related `medic-projects`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1099]
* allow specifying `MEDIC_PROJECTS_BRANCH` to build from; default to `master`
* tag `medic-projects` with `collect`'s version number
* push tag to remote _before pushing to s3_

Follow-up to #1097

**Comment by abbyad** [comment]
Works really well to see all the branding files for our collect releases.

Removing `Acceptance Testing`.
