### ISSUE TITLE
no recipient information in alerts/replies

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1100]
For example you can setup alerts to go to more than one recipient, this information is not available in the UI.

![screen shot 2015-07-23 at 10 56 53 am](https://cloud.githubusercontent.com/assets/25641/8855317/2f29a75e-312a-11e5-843c-1f219dff434e.png)

**Comment by garethbowen** [comment]
It works for me, and it looks like this was added in [January](https://github.com/medic/medic-webapp/commit/86e4b9c2ce27343b088831568ce6a725eb7845c3). @mandric What version was this on?

**Comment by garethbowen** [comment]
This is what it looks like to me...

![automated-reply-recipient](https://cloud.githubusercontent.com/assets/2064938/9295819/0e8a7cae-44cf-11e5-9596-9d89023445da.png)

**Comment by garethbowen** [comment]
No response since 2015. I'm going to assume this works as in my screenshot and close for acceptance testing to confirm.
