### ISSUE TITLE
Empty contacts shown when a filter is active

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1109]
![empty-contacts-20150731_1024](https://cloud.githubusercontent.com/assets/763977/9015162/e40ef8fc-377b-11e5-9c20-51bcd1551245.png)

I get the above after a push with `grunt dev` to an empty database. @mandric confirmed that the issue also occurs when contact records are present.

**Comment by garethbowen** [comment]
This also affects reports in a similar way. As soon as a filter is applied the list is rendered incorrectly.
