### ISSUE TITLE
Enketo: Code cleanup, cached conversion to JSON

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1121]
As a first step toward an internal forms API, we need to create a (form-type-specific, cached) JSON version of Enketo's XML-formatted report (read: "form submission"). We need this because: (1) we agreed that removing all bare references to `doc.fields` and replacing them with accessors was too big of a task to take on all at once; (2) in the final API, a field accessor shouldn't have to parse the full XML report every time a field is read programmatically; and (3) we need a way for (at least a subset of) fields to be easily-accessible from CouchDB views.

One big upside to this approach: if this cached JSON is placed in `doc.fields`, most existing backend code and views that access doc.fields directly (e.g. in medic-sentinel and medic-api) should work as-is.

We'll file a follow-up issue, including some draft documentation/prototypes, for construction of a proper forms API that wraps this, then a big search/replace/refactor to use it instead of direct references to `doc.fields`. The cached copy will remain so that (a) views continue to function, and (b) programmatic accesses to commonly-used fields are fast.

**Comment by alxndrsn** [comment]
This works, but still requires a matching JSON form for the fields to be displayed nicely when viewing a report.
