### ISSUE TITLE
Concierge: Split user documents

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1122]
Following from #1113, `concierge` needs to be updated to create split user documents instead of monolithic user documents. This isn't necessarily a blocker for hosted mobile application testing, but will cause DIY to break if #1113 is merged before this issue is fixed.

**Comment by alxndrsn** [comment]
@mandric @sglangevin should this issue be assigned to a DIY milestone?

**Comment by abbyad** [comment]
We haven't fully fleshed out the next DIY milestone, but it doesn't hurt to throw it in there now.

**Comment by browndav** [comment]
In `medic-os`'s `master` branch as of b9bff608085c82d2b69355f09c780a93a0aec444.

**Comment by garethbowen** [comment]
@browndav Is that really the right commit? Is this really in code review? If so, maybe it should be reviewed by someone else?

**Comment by garethbowen** [comment]
As there has been no update to this issue I'm going to assume it's ready for acceptance testing and kick it out of the iteration.

**Comment by ngaruko** [comment]
Nothing to AT
