### ISSUE TITLE
API: Path to login assets is sensitive to current working directory

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1123]
The login page is breaking in production due to `medic-api` being sensitive to the value of `process.cwd()`. If the current working directory is not equal to the enclosing directory for `server.js`, things break:

```shell
dave@aircrash (~/medic-api) $ node server.js &>/dev/null &
[2] 58497
dave@aircrash (~/medic-api) $ curl http://localhost:5988/login
Redirecting to <a href="/login/">/login/</a>
dave@aircrash (~/medic-api) $ fg
node server.js >&/dev/null
^C
dave@aircrash (~/medic-api) $ cd ..
dave@aircrash (~) $ node medic-api/server.js &>/dev/null &
[2] 58500
dave@aircrash (~) $ curl http://localhost:5988/login
{"error":"not_found","reason":"no_db_file"}
```

We're seeing this on Medic OS too, because `gardener` sets the current working directory to `working_dir/$UUID`, which is two levels above `server.js`.

I was able to hack it into working on `alpha.dev` by doing this at the top:

```js
process.chdir(path.join(process.cwd(), 'node_modules', 'medic-api'));`
```

We should probably figure out the path to `server.js` at startup, and then do something along the lines of `process.chdir(path.dirname(path_to_server_dot_js))`.

**Comment by garethbowen** [comment]
I should have (and now do) use the `__dirname` variable to make the public files path relative to the `server.js` rather than the `cwd`.
