### ISSUE TITLE
Contact info for sample reports/messages not immediately rendered

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1126]
The sample messages and reports in DIY initially show up as from `[object Object]`:

![screen shot 2015-08-05 at 08 47 48](https://cloud.githubusercontent.com/assets/789512/9086109/3f12c24c-3b50-11e5-8ba3-a632310b2b5c.png)

After several minutes, and after reloading, the contact is properly rendered:

![screen shot 2015-08-05 at 08 56 20](https://cloud.githubusercontent.com/assets/789512/9086119/530f0fa8-3b50-11e5-9109-3a058635c3ae.png)

**Comment by ngaruko** [comment]
This issue was moved to ngaruko/medic-webapp#12

**Comment by sglangevin** [comment]
This seems to have been working correctly for a while now. Re-open if this issue pops up again.
