### ISSUE TITLE
Use Release build of vmware-helper in medic-msi

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1130]
In order to avoid missing VC files with the [Debug vmware-helper](https://github.com/medic/medic-msi/issues/4), build `vmware-helper` with `Release` configuration on Jenkins, and include this in the `medic-msi` bundle.

**Comment by alxndrsn** [comment]
Done on https://github.com/medic/windows-ci/commit/87e82f69ec81f79c3f1e96b8269d279efbda4462

**Comment by abbyad** [comment]
Looks good, thanks @alxndrsn.
