### ISSUE TITLE
enketo.css leaking all over the app

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1134]
The css isn't namespaced at all so styles like `.note {...` apply to our DOM as well.

Solutions...

1. Namespace the css so it only applies to specific wrappers. Then we need to overwrite certain styles (like font) so it matches our stylesheet.
2. Don't include the css and write our own which performs the functional parts (eg: show/hide)
3. Patch enketo to separate the form from the function so we can only include the latter

**Comment by alxndrsn** [comment]
This should work in the less:
```
.enketo {
    @import('path/to/enketo.css');
}
```

**Comment by alxndrsn** [comment]
Took option 1 - namespaced all enketo CSS under class `.enketo`

**Comment by garethbowen** [comment]
The fix hasn't worked - the generated css looks like...

```
.enketo {
  
}@font-face {
```

The first line of `core.css` is being included _after_ the `.enketo` wrapper, so styles are still leaking into the app.
