### ISSUE TITLE
Use HTTP Strict Transport Security (HSTS)

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1140]
In hosted configurations, we should be HTTPS-only. Enable HTTP Strict Transport Security to prevent browsers from ever making an unencrypted connection to a hosted instance. This mitigates simplistic MITM attacks and may improve security of CHW-submitted data, depending upon which mobile applications are being used.

This issue likely depends upon additional SMSSync testing, at a minimum.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
I think this has already been done. @browndav, please reopen if I am mistaken.

**Comment by alxndrsn** [comment]
This is not currently happening on `lg.app` or `alpha.dev`.  I have not checked other domains.  To confirm:

```
curl --head https://lg.app.medicmobile.org 2>/dev/null | grep -i Strict-Transport-Security
```

**Comment by alxndrsn** [comment]
@browndav @henokgetachew I think this is low effort and high impact, hence the priority.  Please triage and confirm my labels.

**Comment by garethbowen** [comment]
Removing from 2.15.0 so it doesn't block the release - the fix is separate from the app code.

**Comment by garethbowen** [comment]
@browndav I found the helmet library which adds the HSTS header and a few others by default and submitted the above PR. Would you mind reviewing it? The defaults are listed here: https://helmetjs.github.io/docs/

**Comment by alxndrsn** [comment]
@garethbowen should this be handled by nginx?

**Comment by garethbowen** [comment]
I'm ambivalent about where it should be handled. Do you have a strong preference?

**Comment by alxndrsn** [comment]
I have a strong preference for nginx, because it's accessed before express, and express isn't guaranteed to handle all requests.

**Comment by garethbowen** [comment]
Yeah that's definitely a pro on the nginx side. I just talked to @browndav and apparently we're not using nginx in Docker any more (the load balancer hits api directly) so traffic is guaranteed to go through api.

**Comment by browndav** [comment]
https://github.com/medic/medic-webapp/pull/4601#pullrequestreview-126354546

**Comment by garethbowen** [comment]
This is a difficult one to AT - work with @browndav to ensure the app has an acceptable level of security.

**Comment by newtewt** [comment]
@browndav can you share some insight on AT for this ticket?

**Comment by newtewt** [comment]
@browndav  

Using curl to check and I'm seeing the STS header. 

curl --head -L beta.dev.medicmobile.org 2>/dev/null | grep -i Strict-Transport-Security
strict-transport-security: max-age=15552000; includeSubDomains
strict-transport-security: max-age=15552000; includeSubDomains
strict-transport-security: max-age=15552000; includeSubDomains

Also, the report from SSLLabs validated HSTS is enabled on the site for beta.dev.medicmobile.org. Is there any further testing we should do for this?

https://www.ssllabs.com/ssltest/analyze.html?d=beta.dev.medicmobile.org&hideResults=on

**Comment by henokgetachew** [comment]
When we provide the docker image to people for self hosting, they are going to use nginx for it. Therefore does it make sense to also have the config change in nginx?
