### ISSUE TITLE
Login page usability improvements

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1141]
## 1. username field should be active on page load
[ DONE in https://github.com/medic/medic-api/pull/27 ]
## 2. login button should accept keyboard navigation
pressing `tab` from the password field should hilight the button
[ DONE in https://github.com/medic/medic-api/pull/28 ]

**Comment by garethbowen** [comment]
Username focus wasn't working in Firefox. I've made a small update to delay execution slightly. @alxndrsn Please review.

**Comment by alxndrsn** [comment]
@garethbowen please review PR to fix firefox issue you are seeing (N.B. I couldn't recreate issue)

**Comment by garethbowen** [comment]
@alxndrsn Why was the patch reverted? It fixed the issue for me. I'm not a fan of arbitrary timeouts...
