### ISSUE TITLE
Parameterise `medic-msi` builds

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1143]
Parameterize the desired build version (eg 0.2) and type (eg alpha) in the Jenkins build. Right now this is done using files in github, meaning that updating the build details requires updating and committing the files in the repo.

May be good to append these version numbers to the build name.

Split from #1127

**Comment by SCdF** [comment]
@browndav please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by browndav** [comment]
Given this targets the DIY installer, and we've deprioritized that at a high level for at least Q1/Q2 2017, I'd recommend closing this issue as unnecessary.
