### ISSUE TITLE
A need for facilities view to be exported to the spreadsheet via middleware 

### ISSUE THREAD

**Issue by MathewJuma** [medic/medic-webapp#1146]
There is an urgent need to have an export of facilities view to the spreadsheet via the middleware. All the facilities information is essential. This is vital in cases where non-reporting facilities and community health workers are being monitored. The current situation is that we can only see information about reporting facilities. Pulling the facilities view will enable us do lots of comparisons.

This case is urgently required by the UMComm Project. Kindly help.

**Comment by abbyad** [comment]
Hi @MathewJuma, given your urgent need, luckily this is already possible. The facilities list is exportable in JSON. For example: https://demo.app.medicmobile.org/medic/_design/medic/_rewrite/facilities/backup
You can then use a JSON to CSV converter, such as [this one](https://json-csv.com/), to have a format usable in Excel. 

Also, if you intend to use it in Analytics, you can import the JSON directly as a Data Source and then do any manipulations that you need to do there.

I have taken note of the feature request and we will discuss exporting a CSV formatted facilities list the next time we prioritize new features and feature requests at the end of the month.

**Comment by btbonval** [comment]
Actually, in the development channel on slack, I had outline the precise steps needed to do the above using our current middleware. I don't see those steps reproduced here, though @MathewJuma said he had tried them and they do not work.

@MathewJuma please list all steps you have taken to make this work in the past and what errors or problems you encountered.

**Comment by abbyad** [comment]
Related to my example export URL from above, we should be using the API URL as per instructions here: https://github.com/medic/medic-api/blob/develop/API_v1.md#contacts

The `format` param seems like an obvious place to (eventually) have a CSV option.

**Comment by btbonval** [comment]
I think we solved this problem in the Middleware by supporting JSON exports with a generic parser.

@MathewJuma Can you close this if it was resolved?

**Comment by MathewJuma** [comment]
This issue was resolved. Thanks team.
