### ISSUE TITLE
`exists` validation fails on some unicode characters

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1147]
See https://github.com/medic/medic-projects/issues/36

Using `exists('द', 'patient_id')` validation fails on a patient visit form.

Example query in sentinel that fails because the form code is encode with encodeURIComponent then querystring.stringify.  We end up querying for form:"e0 a4 a6".

```
validation formatParam form द
validation formatParam patient_id 06968
encodeURIComponent() on name and values
validation exists query form:"%E0%A4%A6" AND patient_id:"06968"
couchdb.createClient options.query { q: 'form:"%E0%A4%A6" AND patient_id:"06968"',
  include_docs: true }
couchdb.createClient options.path after querystring.stringify /_fti/local/medic/_design/medic/data_records?q=form%3A%22%25E0%25A4%25A6%22%20AND%20patient_id%3A%2206968%22&include_docs=true

$ curl http://admin:secret@localhost:5988/_fti/local/medic/_design/medic/data_records?q=form%3A%22%25E0%25A4%25A6%22%20AND%20patient_id%3A%2206968%22
{"q":"+form:\"e0 a4 a6\" +patient_id:06968","fetch_duration":0,"total_rows":0,"limit":25,"search_duration":0,"etag":"13ff1389c4bff","skip":0,"rows":[]}
```

Thinking we take out encoding from [_formatParam](https://github.com/medic/medic-sentinel/blob/master/lib/validation.js#L34) and take a hard look at tests.

**Comment by browndav** [comment]
It looks like `_formatParam` is providing input sanitization for Lucene queries, e.g. around https://github.com/medic/medic-sentinel/blob/develop/lib/validation.js#L114. I don't think we can remove it without employing an alternate escaping method.

**Comment by browndav** [comment]
In any case: shouldn't we be using https://github.com/medic/lucene-query-generator here?

**Comment by mandric** [comment]
I'll have a look at using lucene-query-generator here.

**Comment by mandric** [comment]
@garethbowen have a review here on medic-sentinel when you get a moment, please.

**Comment by garethbowen** [comment]
LGTM
