### ISSUE TITLE
Add credentials to settings file via Jenkins

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1148]
For the Collect builds we have removed the credentials from the repo, but in specific cases want to build the APK with the server username and password built-in to avoid having to enter it manually in the app.

We can inject the password in the collect.json of the medic-collect product flavor prior to build. The password would appear as follows:
```
{
	"general_preferences": {
		...
		"password": qwerty123,
		...
	}
}
```

Ideally we would store these password on the Jenkins server and not as a build parameter to avoid retyping the password every build - which is more likely to lead to typos.

**Comment by browndav** [comment]
This may be what you were intending, but IMO we should consider using a large per-project random string here, along the lines of `dd if=/dev/random bs=4096 count=1 2>/dev/null | shasum -a224 | cut -d' ' -f1`.

**Comment by abbyad** [comment]
If you are talking about `qwerty123` being a bad password, then I agree. I was trying to show something that was obviously a password... which usually means it is a bad password.

**Comment by alxndrsn** [comment]
```
TASKS
[ ] work out how to hook into `process<flavor>Resources` build step (gradle)
[ ] if `System.env.MEDIC_COLLECT_PASSWORD` is set, load the flavour's `collect.json`
    file, and rewrite it with a new value for `general_preferences.password`, e.g.:

**Comment by abbyad** [comment]
Works well!
