### ISSUE TITLE
[android] back button in webview quits app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1150]
https://github.com/medic/medic-android/issues/2

**Comment by alxndrsn** [comment]
Having trouble accessing the webapp in Android emulator.

**Comment by alxndrsn** [comment]
I made some improvements to this, but not currently working on it.

**Comment by garethbowen** [comment]
Works as expected. The back button navigates through visited pages until history is exhausted and then exits the app.

**Comment by abbyad** [comment]
@garethbowen, what phone and version did you use? I cannot get the back button to exit the app in the Tecno Y4, even when the history is exhausted.

Regardless, I think we should revisit this once we have the UX refactor done to determine if going back in history makes sense, or if it should be going "up" a level until you reach the top level tabs and then exit. I will create an issue to retest the back functionality at a later time.

**Comment by garethbowen** [comment]
I was using the Tecno Y4. There is a page redirect that happens early on in the stack probably from `/` to the first tab so something is shown. This means as you navigate backwards you hit that page and get redirected forwards again. If you double tab back you get through the redirect. I'll look at patching the redirect issue.

**Comment by garethbowen** [comment]
I've cleaned up the history stack so it works much more smoothly now. Essentially, going `/` -> `/tasks` -> `/tasks/<first-task-id>` now results in a single history item rather than 3. Furthermore the redirects no longer happen when navigating backwards so you don't get stuck in a history loop.

**Comment by garethbowen** [comment]
@abbyad Please test again.

**Comment by alxndrsn** [comment]
:+1: nice fix

**Comment by abbyad** [comment]
Removing Acceptance Testing as it can now exit app. We will revisit the back functionality in https://github.com/medic/medic-webapp/issues/1265.
