### ISSUE TITLE
Cannot log in with User restricted to a Health Center or Catchment Area

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1152]
For the mobile app we need to restrict mobile users to accessing only data of their own place. This is possible for district users, but this is the first time that we have users at the middle or lowest level of the hierarchy accessing medic-webapp. Trying to assign a "restricted" user to a Catchment Area yields a 403 with this message:
`Sample Catchment Area 1 (id: 'eeb17d6d-5dde-c2c0-62c4a1a0ca17fd20') is not a district hospital. Your admin needs to update the Facility Id in your user details.`

Similar result for a user restricted to a Health Center.

Ultimately we need to make sure that reports and contacts created by users are assigned to their facility, unless they select a sub-facility. Several other issues are fanning out from this testing and will be posted separately.

Using 0.5.0-beta.1629

**Comment by garethbowen** [comment]
This has been removed from the app as part of the recent user overhaul.
