### ISSUE TITLE
Cannot see contacts within restricted place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1153]
As a user restricted to a district I would expect to be able to see the contacts that I create that are assigned to my place. As soon as a contact is created it shows in the right pane but then disappears. 

Switching the user to "Full Access" still does not see the contact. It is only shown in the Contacts tab if I log in with an admin user. 

Using 0.5.0-beta.1629

**Comment by garethbowen** [comment]
@abbyad This is fixed now, right?

**Comment by abbyad** [comment]
Yes, this came up as several issues, and now fixed.
