### ISSUE TITLE
Configurable default filters for the Contacts tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1155]
Based on requests from partners, it would be helpful if the default view for the Contacts tab were configurable. Some projects want to see the places only, others the people only, and there has also been a request for only primary contacts for the places as well.

We should be able to configure this on a per project basis, but there may be value in having this on a per role basis. This configuration does not need to be exposed in the UI; it would be acceptable to leave this in `app_settings` only.

**Comment by SCdF** [comment]
@garethbowen please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by garethbowen** [comment]
@abbyad This is ancient now. Are people still asking for it? Does it need some design work to determine which views we support?

**Comment by sglangevin** [comment]
Filters for the people tab are being explored by the design team. I think we can probably close this issue and open a new issue once design work has been done.

**Comment by garethbowen** [comment]
Agreed!
