### ISSUE TITLE
on/off or unmute/mute requests should respect public_form property on forms

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1159]
If an unregistered/unknown phone number submits a mute/unmute message for a specific patient, honor the request if the form is specified as a public form (the `public_form` property is set to true).  Otherwise we ignore the request if the phone number is not defined in the facilities data.

See https://github.com/medic/medic-projects/issues/16

Assigning to Marc for feature discussion/input.

**Comment by abbyad** [comment]
Who can currently mute/unmute messages?
a) Any number associated to a facility
b) Only the person that registered the patient schedule
c) Both

It sounds like we want B, but currently we have C. Is that correct?

**Comment by mandric** [comment]
I'm not sure.  Need to look at the code and improve the docs.

**Comment by abbyad** [comment]
@mandric any update here?

**Comment by mandric** [comment]
Same issue on patient reports.

**Comment by mandric** [comment]
In registrations we have this logic in the filter:

https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L25

```
return Boolean(utils.getClinicPhone(doc) || (form && form.public_form));
```

I don't see any reason all the transitions shouldn't respect form.public_form in the same way.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
Last commented 2015, unassigned 2016… my prognosis:

![It's dead Jim](http://i3.kym-cdn.com/photos/images/original/000/715/142/f6c.jpg)

**Comment by mandric** [comment]
Wonder if we have any docs around `form.public_form` at all @henokgetachew @abbyad ?  It seems like a really easy fix.  The related issue in medic-projects was closed but with comments like we should revisit this later.  Maybe @alxndrsn can double check if this is an issue for them?  https://github.com/medic/medic-projects/issues/16#issuecomment-132120313

**Comment by bishwas-medic** [comment]
@mandric we think this feature is still essential. We'd expect the ON/OFF report from unknown number to work when we've set the webapp to accept public forms for other reports.

cc @ranjuts

**Comment by SCdF** [comment]
@bishwas-medic how are you working around this issue right now? As in: if the feature is essential, what has the strategy been for dealing with its absence in the past few years?
