### ISSUE TITLE
Error on Enketo form load

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1164]
Errors when showing Enketo form:

![image](https://cloud.githubusercontent.com/assets/789512/9342353/2d38424e-45c9-11e5-9960-2752d6ab4057.png)

And then after submit, which is unsuccessful:
![image](https://cloud.githubusercontent.com/assets/789512/9342375/4794b780-45c9-11e5-9084-372fcea6f289.png)

Running 0.6.0-alpha.1756

**Comment by garethbowen** [comment]
I think this is duplicated by a combination of other issues: #1207 #1178 #1166
