### ISSUE TITLE
Requesting futon does not show basic auth prompt

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1165]
The only way to log in is via the Medic login page. This is problematic because if the login page is unavailable for some reason we need to get access to fix it.

This is probably because all requests are being routed through api. We should make sure that _utils, _users, dashboard, etc are available via basic auth prompt.

**Comment by browndav** [comment]
We should probably include the SMSSync poll/submit endpoints in this list too, if only to verify that basic auth is still functioning there.

**Comment by garethbowen** [comment]
Excellent point. I thought it was just the prompt that was broken, but using basic auth in the URL failed also.
