### ISSUE TITLE
Get sourcemaps working for javascript

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1169]
Debugging remote installations is difficult because we uglify the source and don't use sourcemaps. I've had a go at getting these to work before without luck, possibly because we mix browserify and bower concats, but we should at least be able to sourcemap the resultant javascript somewhere in the uglification process.

**Comment by garethbowen** [comment]
This is now working for development but is stripped out for deployment to production. This is unfortunate but the source map file would add MBs to the ddoc which would get sent to each client whether or not they want source maps. We could store the source map on a different ddoc and then download it on demand but this is quite complicated so I'll leave it for another day.

**Comment by alxndrsn** [comment]
Nice work.  Some queries:

> the source map file would add MBs to the ddoc 

Is there a way to disable this in development?  When testing low-bandwidth stuff (as I am now with pouch), megabytes means many minutes extra per development cycle.

> To fix this I also had to refactor how we do monkey patching which is hopefully now more sane.

1. have you got any suggestions on how to make these patches easily?
2. this looks quite brittle - from what I can see of the `patch` format, it relies on line-numbers.  However, as discussed elsewhere our minor versions of libs can change without developer intervention, which could easily lead to line numbers changing in dependencies.  Which could lead to patches being applied to the wrong place:

> With context diffs, and to a lesser extent with normal diffs, patch can detect when the line numbers mentioned in the patch are incorrect, and attempts to find the correct place to apply each hunk of the  patch.  As a first guess, it takes the line number mentioned for the hunk, plus or minus any offset used in applying the previous hunk.  If that is not the correct place, patch scans both forwards and backwards for a set of lines matching the context given in the hunk.
> – _`man patch`_

The following do not appear to be context diffs, so may vulnerable:

* https://github.com/medic/medic-webapp/blob/f66ef4ab0f45f9995a3a928000e000957749375d/patches/pouchdb-fail-replicate-on-error.patch
* https://github.com/medic/medic-webapp/blob/f66ef4ab0f45f9995a3a928000e000957749375d/patches/pouchdb-increase-bulk-get-timeouts.patch
* https://github.com/medic/medic-webapp/blob/f66ef4ab0f45f9995a3a928000e000957749375d/patches/bootstrap-daterangepicker.patch

**Comment by estellecomment** [comment]
I'm seeing two copies of `static/dist/inbox.js` in dev env. Not sure since when. Is it related to this? Is it on purpose?
![screen shot 2016-04-15 at 12 25 56](https://cloud.githubusercontent.com/assets/911434/14558904/84695e8c-0305-11e6-958c-393b6f2ca5ab.png)

**Comment by alxndrsn** [comment]
@estellecomment surely one is the sourcemap - not sure a browser would store two different files for the same URL otherwise

**Comment by SCdF** [comment]
@estellecomment this happens all the time for me, I just reload and I get one of them. I presume it's a Chrome bug

**Comment by garethbowen** [comment]
@estellecomment No idea why there are two showing up.

**Comment by garethbowen** [comment]
@alxndrsn :

> Is there a way to disable this in development? When testing low-bandwidth stuff (as I am now with pouch), megabytes means many minutes extra per development cycle.

There's no way currently, but you can manually change your Gruntfile to pass `debug:false` to browserify while testing low bandwidth stuff. If it happens a lot we could add a flag or something...

> this looks quite brittle...

Yeah I was worried about that too. My rationalisation was that the regex solution was fragile too. I'll have a look at other patch formats.

> have you got any suggestions on how to make these patches easily?

The way I did it was to copy the file I wanted to make changes to, make the changes, then run `diff` between the two files. I'll add some documentation to the Gruntfile once I decide which format we should use.

**Comment by garethbowen** [comment]
I've switched to using context patches and added documentation.

**Comment by garethbowen** [comment]
Assigning to @alxndrsn for review because @estellecomment is on vacation.

**Comment by alxndrsn** [comment]
> There's no way currently, but you can manually change your Gruntfile to pass `debug:false` to browserify while testing low bandwidth stuff.

Perfect, thanks.

**Comment by alxndrsn** [comment]
:+1: Overall this looks both safer and easier to configure than the old style.

**Comment by ngaruko** [comment]
No AT needed. Debug feature
