### ISSUE TITLE
modify sentinel validations to use lucene-query-generator

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1170]
This lib does a better job of escaping query values.

See _formatParam(): https://github.com/medic/medic-sentinel/blob/develop/lib/validation.js#L35

And: https://github.com/medic/medic-webapp/issues/1147

**Comment by SCdF** [comment]
@SCdF please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by SCdF** [comment]
We want to get rid of lucene and replace it with postgres at some point anyway, don't think this holds relevant 2.5 years later.
