### ISSUE TITLE
White Screen Of Death

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1171]
On first run the bootstrapping process can take a very long time with no spinner just a blank page.

**Comment by garethbowen** [comment]
Looks like we're downloading the entire ddoc (attachments and all) into the local Pouch.

![tgz](https://cloud.githubusercontent.com/assets/2064938/9373988/8d6964dc-4744-11e5-9b4e-149e1543fbda.jpg)

**Comment by garethbowen** [comment]
We do the bootstrapping so settings are available before loading the rest of the app, as most parts of the app need settings in one way or another. The settings are available on the ddoc so we're syncing the ddoc to our local pouch so it can be replicated when it changes.

Unfortunately there's no way to instruct pouch to leave the attachments on the server ([yet](https://github.com/pouchdb/pouchdb/issues/1365)).

Given this, we need to find some other way to access the settings.

**Comment by garethbowen** [comment]
The bootstrapping is much faster now. I've raised #1173 to cover the UX of having a blank white screen while loading.

**Comment by abbyad** [comment]
Works well. Moving to Ready.
