### ISSUE TITLE
Show loading layer while bootstrapping settings

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1173]
Currently while bootstrapping settings there is no progress indicator. Show a spinner or something nice.

**Comment by abbyad** [comment]
@garethbowen I think a spinner (or something nice) is fine here for now. Do we know a percentage value for the download to show along with the spinner so that those with a slow connection know that something is progressing?

Let me know if and when you want us to do a UI pass on it.

**Comment by garethbowen** [comment]
Yes a spinner would be a vast improvement on blank screen. We don't know progress unfortunately but it should be pretty quick now that we're just getting settings and not the entire ddoc.

**Comment by garethbowen** [comment]
Also show an error message when bootstrapping fails - eg: first run has no internet connection.
