### ISSUE TITLE
Double spinners in Messages tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1175]
The Messages tab has two spinners on load, which right now can take some time still:
![image](https://cloud.githubusercontent.com/assets/789512/9383102/53a74456-4714-11e5-8412-99e2a3023fb7.png)

The Reports and Contacts tab show a message on the right until the spinner on the left is done and an item is selected:
![image](https://cloud.githubusercontent.com/assets/789512/9383113/60f68afe-4714-11e5-91e8-07acc0c3fb76.png)

For the Messages tab the right pane could say `No conversation selected` or something to that effect. Following the pattern of the other tabs we could say `No message selected`, but in reality what we are selecting in the left pane is a group of messages with a particular contact, so it is a bit misleading. I'm open to suggestions here.

**Comment by garethbowen** [comment]
Actually there's a difference in how you're loading the pages. In the messages example you're loading a specific conversation by id provided in the URL. What this does is immediately tries to load all conversations in the left, and load the selected conversation in the right in parallel. They are separate operations loading independently. However in the reports example you haven't provided an ID in the URL so it's waiting for the list to load.

However there actually is a bug here if you load messages without an id... so your point is still valid.
