### ISSUE TITLE
Enketo not working on alpha.dev

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1178]
Getting following error on https://alpha.dev.medicmobile.org:

![pasted image at 2015_08_20 02_16 pm](https://cloud.githubusercontent.com/assets/191496/9391754/f067757c-4778-11e5-826a-4050c5d40f95.png)

# Reported by @abbyad 

# Browser: Chrome

**Comment by alxndrsn** [comment]
Closing this while `alpha.dev` is in an unknown state.

**Comment by garethbowen** [comment]
Duplicate of #1207
