### ISSUE TITLE
[enketo] `next` and `prev` buttons are enabled even if there is only one page

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1182]
The buttons become disabled if either is clicked.

This may be an upstream bug.

**Comment by garethbowen** [comment]
I'm happy with this. @alxndrsn please review my slight change which improves the styling of the disabled buttons.

**Comment by alxndrsn** [comment]
Please review my revert :-(

**Comment by garethbowen** [comment]
@alxndrsn This is not how you style a button as disabled. What was wrong with the code?
