### ISSUE TITLE
Submit a prepopulated form from a task

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1185]
1. User sees a new task in the tasks tab
2. User clicks "do task" or similar, and then; 
3. gets taken to a "create new report" screen with Enketo in the "new record" state, maybe with some data populated

```
TASKS
[ ] get task `app_settings` working
[ ] add a button to _visit_ tasks: `[ mark done ]`
[ ] when `[ mark done ]` clicked, trigger enketo editor
[ ] include patient/visitee ID as initial form data
[ ] consider how this data binding might be configurable via task config

**Comment by browndav** [comment]
Moving this over to @garethbowen just in case there's time. This is probably lower-priority than #1199 and #1203.
