### ISSUE TITLE
[enketo] media does not stop playing when modal dialog is closed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1187]
This is quite weird.

**Comment by alxndrsn** [comment]
@garethbowen would appreciate your opinion if there is a better way to bind to the modal dialog's `hidden` event than at https://github.com/medic/medic-webapp/commit/2a36c79d320a9a256de400095a7ffc94605b341b.

**Comment by garethbowen** [comment]
Looks fine to me.
