### ISSUE TITLE
[android] Rotating device reloads the app to the default/Messages tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1188]
If you rotate the device and the screen orientation changes, then the webapp reloads back to the Messages tab.

This means that if you are on the Tasks tab and orientation changes you lose your place in the app, instead of staying on the Tasks tab with whatever context/modals you had open.

**Comment by garethbowen** [comment]
This could be as simple as adding `android:configChanges="orientation|screenSize"` to the manifest, a la http://developer.android.com/guide/topics/manifest/activity-element.html#config

**Comment by browndav** [comment]
Cut/paste from a duplicate issue:

We used the Tecno Y4's "lock orientation" feature for the demo. Currently, turning the device from portrait to landscape mode (apparently) triggers a full page reload, which turns the screen white for a relatively long period of time and makes the application appear (okay, actually-be) unresponsive.

We should be able to switch between portrait and landscape mode on a Tecno Y4 Chromium 30 Webview without major UX disruption.

**Comment by alxndrsn** [comment]
That ^^ did the job :+1:

**Comment by abbyad** [comment]
Works well, moving to Ready.
