### ISSUE TITLE
[enketo] Hide fields with `appearance="hidden"`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1189]
Follow up from #1060, we would like to hide any field in an Enketo form that has the appearance set to "hidden".

**Comment by garethbowen** [comment]
Fields with `appearance="hidden"` get the class `or-appearance-hidden` which I'm hiding via css as @alxndrsn [suggested](https://github.com/medic/medic-webapp/issues/1060#issuecomment-131766702). It's still available if the user hacks the DOM but hidden fields aren't about security so this is ok.

**Comment by abbyad** [comment]
I still see hidden fields, likely a specificity issue:

![image](https://cloud.githubusercontent.com/assets/789512/10020763/a6008d9e-6112-11e5-97a7-c0620da8699e.png)

**Comment by abbyad** [comment]
Works well in 1947. Moving to Ready.
