### ISSUE TITLE
Configurable default view

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1198]
Currently Messages is the default view and will load even if the user doesn't have permission. Have some way to configure the default view, or add a landing page as the default view.

**Comment by abbyad** [comment]
What happens if a user role does not have access to view the "default configured" tab? We may need to do this on a per role basis, or even better yet always default to the left most tab.

We could also solve several issues by making it possible to configure the order of the tabs on a per project basis - although that would likely be more effort at this time.

**Comment by browndav** [comment]
For the demo, simply changing the default view to `Reports` or `Tasks` would probably suffice. Beyond that, I'm wondering if a landing page / home screen (especially on mobile) might be the best way to go.

**Comment by garethbowen** [comment]
The "especially on mobile" bit is potentially tricky, but we could configure the android app to go direct to a `/landing` URL instead of `/` by using the redirect parameter to the login screen.

**Comment by abbyad** [comment]
What are the benefits of a landing page? I don't understand why we would need one in the long term as opposed to properly sorting the tabs.

**Comment by browndav** [comment]
I was thinking additional presentation space (larger icons, ability to show localized text labels), handling future cases where there are simply too many relevant screens for them to ever fit cleanly in to the tab bar, and everything would still be a single tap away. It'd also (possibly) be a nice place for the user to click "Make this the default tab" and/or "Don't show this again".

**Comment by abbyad** [comment]
As mentioned on #740, I don't think we will have more tabs coming soon and we can manage with the tabs that we do have. If and when we get to the point that we will have too many tabs then I think we can consider options such as a landing page as part of a UX review.

Right now a landing page seems to be solving a problem that we don't yet have so I would put off discussion specific to the landing page until we have a need for it.

**Comment by garethbowen** [comment]
The fix picks the first tab the current user is permitted to see. We can extend it to be more configurable or clever later on.
