### ISSUE TITLE
Visit tasks should be resolved once a Visit report is submitted

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1199]
Pass relevant Visit reports in to the Task Generator so rules can be made based on all the information, for example, submitting a Visit report should resolve a Visit task. For now, resolution means it will no longer be shown in the Tasks tab.

Add a Changes listener so the task list is updated automatically as reports are submitted.

**Comment by browndav** [comment]
High-priority for the Monday 8/31 demo in San Francisco.

**Comment by garethbowen** [comment]
This is a completely naiive implementation so far - the first visit report resolves the first visit task, and so on. We can implement a solution which resolves the task nearest the report once we've thought through use use case.

**Comment by mandric** [comment]
Worth noting here in the current implementation we have a `group` field which typically has a number value so when a visit comes in a specific group is targeted for resolution (clearing).  There is also a "window"  time span that gets calculated based on when a visit report is submitted that can be tweaked in settings.  This was originally done mostly ad-hoc by me so I'm sure it could use a re-design or second pass at defining specs.
