### ISSUE TITLE
[enketo] code review

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1201]
1. ~~Don't use tables for non-tabular data, and never use nested tables, eg: [edit-report.html](https://github.com/medic/medic-webapp/blob/develop/templates/modals/edit_report.html#L9). This example should probably be an unordered list.~~
2. ~~Internationalise everything. It's almost as easy to add a translation directive, a key, and an entry in the translation file as it is to add a hardcoded English string. eg: [edit-report.html](https://github.com/medic/medic-webapp/blob/develop/templates/modals/edit_report.html#L13)~~
3. ~~Use the standard spinner when loading content, not static text. eg: [edit-report.html](https://github.com/medic/medic-webapp/blob/develop/templates/modals/edit_report.html#L12)~~
4. ~~Use angular instead of jQuery wherever possible. The two don't play well together, so minimise the use of jQuery as much as possible. eg: [edit-report.js](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/edit-report.js#L218). Instead of using jQuery to show and hide, set a scope property (eg: `$scope.loading = true`) and then use `ng-show="loading"` on the loading spinner.~~
5. ~~Don't generate HTML in JavaScript, eg: [edit-report.js](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/edit-report.js#L196). This is particularly prone to bugs and is hard to read. It's nicer, easier to test, easier to read, and easier to maintain to have MVC separation. As per the above example it would be better to set the list of available forms on the $scope, and then use the `ng-repeat` directive on an element to stamp out the templates.~~
6. ~~Don't use inline event registration, eg: [edit-report.js](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/edit-report.js#L197). It's very hard to maintain. In the angular world you should use `ng-click="loadXmlFrom(...)"` instead. NB: this requires using `ng-repeat` from number 5 above.~~
7. ~~Don't use globals if possible, eg: [edit-report.js](https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/edit-report.js#L212). One exception is if this is a requirement of the enketo library but I can't see that it is in this case.~~
8. ~~Don't use `!important`, eg: [medic.less](https://github.com/medic/medic-webapp/blob/develop/static/css/enketo/medic.less#L15). Unless the style you're overriding breaks this rule, you *never* need to use it. Simply make your selector more specific than the one you're overriding and it'll take precedence.~~ -> Added to #1233
9. ~~Don't commit compiled code, eg: [enketo-core-medic-0.2.1.js](https://github.com/medic/medic-webapp/blob/develop/static/enketo/js/enketo-core-medic-0.2.1.js). Ideally it would be published to a repo, and the installed via npm or bower. At the very least it should be checked out at build time and not committed.~~ filed as #1232

**Comment by alxndrsn** [comment]
Ref *8*, I'm fairly sure `!important` is required to override a style set directly on an element.

**Comment by alxndrsn** [comment]
**8** is likely blocked by #1233; I will make resolving it part of this ticket.

**Comment by alxndrsn** [comment]
Removed globals in https://github.com/medic/medic-webapp/commit/58d6e4f7506bbdcca4ef5e05e593fd83c50c072d

**Comment by garethbowen** [comment]
This is definitely heading in the right direction. There's more that could be done but we can do this in the spawned issues, and gradually over time as we make changes to the code.
