### ISSUE TITLE
Login screen: use the full viewport in mobile mode

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1206]
On both Chrome 30.0 (OEM browser) and Chrome 44.0 (not Webview) on Android, the `/medic/login` page initially appears as scaled-down/zoomed-out content. We should adjust the CSS to make sure the login screen fills the full viewport in mobile mode.

<img width="375" alt="chrome-44-login-zoom-20150825" src="https://cloud.githubusercontent.com/assets/763977/9478810/cb7c431e-4b2e-11e5-8f16-3bc033a79700.png">

**Comment by garethbowen** [comment]
Ouch. I'm on it.

**Comment by abbyad** [comment]
I have a phone connected and see this now on the top and at times on the bottom... and I don't think it is a issue at all. The "missing" part up top is actually the part covered by Chrome's URL bar, and bottom is missing a large portion when the keyboard pops up.

**Comment by browndav** [comment]
I'm referring to the page width and zoom level, not the excluded title bar. I can zoom to a level where the text boxes and keyboard are all visible; IMO it should default to this.

**Comment by abbyad** [comment]
Ah ok, makes sense.
