### ISSUE TITLE
Blocker: Enketo apparently failing to initialize on Chrome for Android

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1207]
I'm seeing the following error with a stock Chrome 44 on Android 4.4.2. The backtrace occurs on any tab, and is pretty easy to catch with the remote debugging tools. I haven't mapped all of the mangled names back yet, but it looks Enketo-related at first glance.

Marking high-priority for the August 31st demo.

![chrome-44-backtrace-20150825](https://cloud.githubusercontent.com/assets/763977/9479037/41f08432-4b30-11e5-96c9-1d67c62b4297.jpg)

**Comment by browndav** [comment]
The W3C spec seems clear enough: `[SameObject] readonly attribute DOMTokenList classList;`

**Comment by browndav** [comment]
The problem is touch-related and is almost certainly right here: https://github.com/medic/medic-webapp/blob/develop/static/enketo/js/enketo-core-medic-0.2.1.js#L8607

**Comment by browndav** [comment]
Believe this should fix at least one of the errors:

```diff
diff --git a/static/enketo/js/enketo-core-medic-0.2.1.js b/static/enketo/js/enketo-core-medic-0.2.1.js
index 9d29f2a..07206ca 100644
--- a/static/enketo/js/enketo-core-medic-0.2.1.js
+++ b/static/enketo/js/enketo-core-medic-0.2.1.js
@@ -8604,7 +8604,7 @@ define( function(require, exports, module){
     // test touchscreen presence
     if ( ( 'ontouchstart' in window ) || window.DocumentTouch && document instanceof DocumentTouch ) {
         features.touch = true;
-        document.documentElement.classList += ' ' + 'touch';
+        document.documentElement.classList.add('touch');
     } else {
         features.touch = false;
     }
```

**Comment by garethbowen** [comment]
It looks like the first error is due to try to register the enketo error. When I use your suggested fix the problem goes away.

**Comment by garethbowen** [comment]
I've merged this patch in but only to our committed copy. I raised #1209 to push the patch upstream.
