### ISSUE TITLE
Merge enketo patches upstream

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1209]
I [patched enketo-core-medic](https://github.com/medic/medic-webapp/commit/2f68a697f31ad591ce5466a6a5ca4d98fdb4983a) in medic-webapp but I can't see any information about where this compiled code came from. Merge this patch back upstream and document (or improve) the process.

**Comment by alxndrsn** [comment]
PR at https://github.com/enketo/enketo-core/pull/294

**Comment by alxndrsn** [comment]
The PRs above are included on the https://github.com/alxndrsn/enketo-core/tree/clientside-4.x branch.

Documentation is at #1232, which requests proper dependency management of this code.
