### ISSUE TITLE
Render summaries/read-only views for Enketo reports

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1211]
Currently reports submitted via enketo look something like this.

![enketo-report](https://cloud.githubusercontent.com/assets/2064938/9485861/98660b1e-4c13-11e5-8e8e-6cc09d0d5ccf.png)

The problem here is that the code that works out which fields to list is looking up the form definition but it looks up the JSON form definition with the same code as the enketo form definition. We need to update the code to be able to find enketo form definitions so we can render the submitted field values.

**Comment by garethbowen** [comment]
This would also be a good time to rework the rendering code for JSON form submissions to get rid of the [makeDataRecordReadable](https://github.com/medic/medic-webapp/blob/develop/packages/kujua-sms/kujua-sms/utils.js#L110) code.

**Comment by browndav** [comment]
This is at least tangentially related to #1275, in that both require the ability to render a read-only summary of an Enketo form.

**Comment by alxndrsn** [comment]
@garethbowen I don't think changes to JSON forms should be included in this ticket.

**Comment by alxndrsn** [comment]
Might require some thought to decide how grouped fields will be displayed in ReportContentView, as fixed in https://github.com/medic/medic-webapp/issues/1446

**Comment by abbyad** [comment]
@Lesterng, can you provide some mockup options for showing grouped fields within a reports page. Currently it is something like this, with one row per field:
![image](https://cloud.githubusercontent.com/assets/789512/10608862/f894b8e8-770e-11e5-8dca-dc7eb64232b2.png)

With our new forms we can group fields together and want to present such related fields together to the user. 

Note that they can also be nested infinitely, so we may want to take that into consideration (eg max 1 or 2 levels).

**Comment by abbyad** [comment]
As part of this issue we want to show a subset of the XML fields so that the rendered report is a summary, not a list of all the fields. This is important because most of our forms include many calculate fields that we do not want to show.

In a call last week we had discussed using an `outputs` group in the model for this purpose; all fields in the `outputs` group would be displayed when rendering the form.

**Comment by alxndrsn** [comment]
Report content view now has different handling for JSON vs XML form submissions.

When saving Enketo report submissions, only those fields in `<outputs>` will be parsed to `doc.fields`, and these are the fields which are iterated to create the report-content view.

Label translations can be provided via `medic-api`, in the form:

```
report.{{form_id}}.{{field_name}}
```

_Raw report content_ was no longer displayed when I started work on this ticket.

**Comment by garethbowen** [comment]
### Code review:

- [] This doesn't support nested `fields` eg: `{ fields: { patient: { name: 'Gareth' } } }`, right? See if it's easy to output nested fields.
- [] Raise an issue to cover the design aspect Marc raised above and assign Lester.
- [] There's a minor comment in the code.

**Comment by alxndrsn** [comment]
@garethbowen nested fields in `<outputs>` are not currently supported.  @abbyad please open a separate ticket if this is required - assuming it's not an immediate priority

**Comment by alxndrsn** [comment]
Issue raised for nested field design and implementation at #1473

**Comment by abbyad** [comment]
Works well, moving to Ready. 

If there is no key defined for the field it would be nice to get the field label from the XForm definition, or some other way to reduce the configuration load.
