### ISSUE TITLE
Native container: Crash on Chrome 30.0.0.0 Webview (Tecno Y4, Android 4.4.2)

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1213]
![chrome-30-oem-tecno-20150825_960](https://cloud.githubusercontent.com/assets/763977/9503931/ae597c64-4bee-11e5-95ff-e2bac845b668.jpg)

I've confirmed that the Tecno Y4 is 4.4.2 running Chromium 30 as a shared Webview component. We crash per the screenshot on Chromium 30 after "Send Report" is selected, but not on Chromium 33 (Webview) or 44 (Chrome) on a Nexus 5.

**Comment by browndav** [comment]
Issue appears to start here: https://github.com/medic/medic-webapp/blob/develop/static/enketo/js/enketo-core-medic-0.2.1.js#L7247

**Comment by browndav** [comment]
Confirmed that `this.data.modelStr` is undefined immediately before the crash.

**Comment by browndav** [comment]
It looks like the transformToDocument instance method of XSLTProcessor (native code) is returning undefined when we're expecting it to return a document. Looking through documentation now to figure out what's right.

**Comment by browndav** [comment]
As best as I can tell, `transformToDocument` on Chrome 30 is returning a valid `Document` object, but `.documentElement.innerHTML` is returning `undefined` on that object. This is odd. I'm going to look at it again first thing tomorrow morning, and look at `.importNode` as a potential workaround.

**Comment by browndav** [comment]
It looks like jQuery's `.html()` also fails to serialize the document object, either returning `undefined`, or throwing an exception from within jQuery with the message `TypeError: Cannot call method 'createDocumentFragment' of null at Function.jQuery.extend.buildFragment`.

**Comment by browndav** [comment]
Have a look at `XMLSerializer` in the morning. If it works properly on Chrome 30 and doesn't regress on the way up to Chrome 44, we should almost certainly use it instead of non-standard `innerHTML` hacks.

**Comment by garethbowen** [comment]
If it's the `.html()` method then this might very well be the same issue as #1215
