### ISSUE TITLE
 [enketo] remove CHP select from report form

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1214]
![edit-report-modal](https://cloud.githubusercontent.com/assets/2064938/9506052/d26ded5a-4c99-11e5-802f-6c210f43005a.png)

The top field above is to select the CHP/facility the report is from/assigned to. Currently it doesn't look like it's part of the form. It should be styled the same, below the header, and have a label.

Ideally it would be part of the form definition with some special handling after submission to pull out the contact. If this isn't possible at least make it look like it belongs.

**Comment by abbyad** [comment]
That dropdown should not actually be with a new report at all... it is a relic from when the "Edit Report" modal was only to change the sender of a report. When completing a new report we do not want to select the sender as it should always be associated to the logged in user.

Somewhat related, editing the sender should only be available to higher level admin/managers.

**Comment by garethbowen** [comment]
Oh, yes, that's even better. Thanks!

**Comment by alxndrsn** [comment]
Update the title to reflect the content of the discussion ^^.  N.B. we probably still need this field for non-enketo forms.

**Comment by alxndrsn** [comment]
I'm doing this as it crosses with the work I'm trying to do for #1228

**Comment by abbyad** [comment]
@alxndrsn to clarify, we do not want that edit submitter field when submitting a form, regardless of it is a XML or JSON form. It should only be there for admins, and only when they edit a form.

**Comment by browndav** [comment]
Should an admin be able to submit a new form on someone else's behalf? It seems weird to allow them to change the submitted on edit but not set it in the first place on create.

**Comment by abbyad** [comment]
Yes it's possible, but depends on the project. Some will have admins submit reports for themselves, others on behalf of another user/worker. We don't have good stats to know which is more common.

Option A: admins can select any submitter, but default is themselves.
Option B: admins can only change submitter on edit.

My preference based on a clean interface for admins that submit their own reports would be for option A, but I would error on the side on flexibility and go with B for now.

**Comment by garethbowen** [comment]
This is all going to change soon when the form is removed from the modal.

**Comment by alxndrsn** [comment]
Will forms still be displayed in modals when initialised from the actionbar or from the header?

**Comment by garethbowen** [comment]
Not with what I'm planning for #1243 . I'll leave editing JSON forms in the modal, but clicking edit on enketo forms will load them in the right pane. The header button will be removed with #1255 .

**Comment by alxndrsn** [comment]
Ok, this ticket can wait for #1243

**Comment by browndav** [comment]
#1243 is closed now; unblocking.

**Comment by garethbowen** [comment]
Editing submitter split off to #1305

**Comment by abbyad** [comment]
Looks good. Moving to Ready.
