### ISSUE TITLE
[enketo] Only move to next "page" if validation passes

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1217]
We should be able to prevent a user from moving forward to the next page if any of the fields on the current page do not pass validation.

This issue is not currently urgent but does lead to a poor UX. Ideally this fix would be done upstream.

**Comment by alxndrsn** [comment]
Recommend filing this bug upstream if we want a fix upstream!

**Comment by alxndrsn** [comment]
Filed upstream at https://github.com/enketo/enketo-core/issues/326.
Depends on #1425.

**Comment by browndav** [comment]
To do: investigate this along with #1327, and see how easy it is to hook the `Next` event in Enketo. If it's easy, do both of these issues this week. If it's not, defer one or both to next iteration.

**Comment by abbyad** [comment]
Nice work @alxndrsn, moving to Ready.
