### ISSUE TITLE
Bring place filter improvements from 0.5+ to 0.4

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1219]
We have heard from users recently that the place filter is difficult to use in 0.4. It seems unsorted and difficult to navigate:
![image](https://cloud.githubusercontent.com/assets/789512/9528165/3bc4da26-4cc1-11e5-994a-73dcc439d6bb.png)

This has been updated and fixed, but has not been pushed to Release. Here is an example of the improved filter:
![image](https://cloud.githubusercontent.com/assets/789512/9528115/00996462-4cc1-11e5-8112-9b3206902847.png)

The Facilities to Contacts change in 0.5 may have made this updated filter possible, but if it is feasible to include this improved filter back in 0.4 then we should do this rather than wait for the 0.5 release.

**Comment by garethbowen** [comment]
We now plan to upgrade everyone to 2.x rather than backport improvements to 0.4.
