### ISSUE TITLE
SMS messages are sent in duplicates or are very delayed

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1220]
Creating an issue for the modem work that @browndav has been doing to troubleshoot duplicate and delayed messages.

**Comment by sglangevin** [comment]
@browndav Anand was having trouble sending and receiving messages at a workshop in India this week, though once he tried again at home the message sent as expected. I have logs from him that I can share, as well as logs from St. Gabriel's in Malawi from July. Let me know if you want to take a look at those.

**Comment by garethbowen** [comment]
Closing this as the gateway has been rewritten. Acceptance testing will occur on the new code.
