### ISSUE TITLE
Multiple report submissions

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1222]
If you click submit on a form multiple times before it goes through then you can end with multiple reports in the Reports tab.

We should disable the submit button after submission, and show a spinner to indicate that something is happening until the modal disappears.

**Comment by garethbowen** [comment]
Use the [modal module](https://github.com/medic/medic-webapp/blob/develop/static/js/modules/modal.js) to do this in a standardised way.

**Comment by browndav** [comment]
This depends on #1243 and may change substantially based upon how that issue is resolved.

**Comment by garethbowen** [comment]
The button (now in the right pane) is now disabled while saving and a spinner shown until save is complete.
