### ISSUE TITLE
[enketo] Implement geolocation type

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1223]
The geolocation type works on Enketo, but not yet in our embedded offline mode.

This is how it shows up in Enketo on a touchscreen laptop, which hides the map, and field in question has `appearance="hide-input"` to hide the input fields:
![image](https://cloud.githubusercontent.com/assets/789512/9539634/2a1de0c2-4d22-11e5-99dc-2cd99dd9db78.png)

Our embedded version defaults to a text field:
![image](https://cloud.githubusercontent.com/assets/789512/9539626/074e6864-4d22-11e5-8fa8-af6b4c04714f.png)

**Comment by alxndrsn** [comment]
@abbyad would be really helpful if you have a link to the example form.  Even more so if there's a link to the enketo instance it can be tested with.

AFAICT, Enketo's supplied `geopicker` widget will also provide a map interface for choosing your location.  Should we go the full way and support the map too, or should we develop a stripped-down location-provided `geopoint` widget?  If the former, then it's not clear to me how we'd support maps when offline.

**Comment by abbyad** [comment]
You can test with our [geolocation test form](https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/geolocation-test.xlsx), rendered [here](https://8kfka.enketo.kobotoolbox.org/webform)

This is using the `geopoint` type, more info on the other types [here](http://blog.enketo.org/geo/).

For our current needs, we do not need to show a map. In fact, on a touch device the map is not shown, only the button. We have been asked to have the geolocation to be tracked automatically upon submitting the form, but for now are planning to show the button so that users explicitly set their location.

**Comment by abbyad** [comment]
Works well moving to Ready.

We are still being requested to have an automated geolocation field - issue to follow.
