### ISSUE TITLE
Update configuration for Delivery form and message schedule

### ISSUE THREAD

**Issue by shayrona28** [medic/medic-webapp#1225]
* Update Delivery form format to D {pregnancy ID} {delivery code}, e.g. D 12345 F, to be more consistent with other forms and current best practice in other programs.
* Update LMP schedule to:
     - Visit reminders at 12, 24, 32, 36 weeks
     - Upcoming delivery alert at 38 weeks
     - Delivery due alert at 40 weeks
     - Reminder to send delivery report at 42 weeks
     - Final reminder to send delivery report at 44 weeks
* Update no LMP schedule to:
     - Visit reminders at 1, 5, 9, 13, 17, 21, 25 weeks
     - Visit reminder + possible delivery alert at 29 & 33 weeks
     - Reminder to send delivery report at 37 weeks
     - Final reminder to send delivery report at 39 weeks
* NOTE: we currently have two messages scheduled to go out at 37 weeks, but I think that issue will be resolved with this new schedule.

* Also, decrease the message silence window to 7 days to avoid clearing subsequent message groups from a V form that was sent in response to a reminder.

**Comment by sglangevin** [comment]
Finished updating and submitted a pull request.

**Comment by mandric** [comment]
Do you have a link to the PR?

**Comment by mandric** [comment]
Oh this? https://github.com/medic/medic-data/pull/11

**Comment by sglangevin** [comment]
Yeah, that's the one @mandric - not sure why the build is failing.

**Comment by mandric** [comment]
Travis mis-configuration.  Would it be too much trouble to re-submit the PR?

**Comment by sglangevin** [comment]
No, that's no problem - can I do that now?

**Comment by mandric** [comment]
Yes please, thanks.

**Comment by sglangevin** [comment]
Is closing then re-opening sufficient? I don't see an obvious way to re-submit.

**Comment by browndav** [comment]
https://travis-ci.org/medic/medic-data/builds/86700515

**Comment by sglangevin** [comment]
I closed and re-opened, that's the new build - is that what you meant, @mandric?

**Comment by mandric** [comment]
Yup, it's rebuilding...

**Comment by sglangevin** [comment]
Cool. It passed!

**Comment by mandric** [comment]
If you need anyone to specifically have a look at this you can use the code review tag and assign to them.

**Comment by mandric** [comment]
Code looks good, moved to acceptance testing.
