### ISSUE TITLE
[Contacts] Submit "new pregnancy" or other form from patient's profile

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1228]
Mobile app users will need to be able to submit reports about patients from their profile page in the Contacts tab. 

The "action bar" on the bottom would have a "submit report" button. With the current UX, this would open a modal with the list of relevant forms for the patient (1).  The selected form would then be completed with certain fields pre-populated. 

For example, on a woman's profile you may want to add a new pregnancy. This will open the "New Pregnancy" form with the XML:
```
        '<pregnancy id="ANCR" version="2015-08-28">
          <group_info>
            <person_note/>
            <g_patient_name>' + patient_name+ '</g_patient_name>
            <g_patient_id>' + _id + '</g_patient_id>
          </group_info>
...'
```
where the `patient_name` and `_id` are taken from the contact profile.

Currently the action bar for people is as follows:
![image](https://cloud.githubusercontent.com/assets/789512/9569654/30e3125a-4f3f-11e5-9b3e-776d14b26e25.png)

We could replace the "Message All" with "Submit Report" button using the report icon for now, and exact label text TBD.

----
(1) Showing the Relevant forms would make it easier to maintain the workflow for users. For instance a 5 year old boy would not have "Add pregnancy" as a form option. The rules for which form to show may be rather complex, so it may be better to show all forms for the first iteration and then break out more issues for the form display rules (eg Woman age 10 to 50, without an outstanding pregnancy)

**Comment by alxndrsn** [comment]
```
TASKS
[ ] change action text from [message all] to [submit report]
[ ] change action icon
[ ] on button-click, launch modal for selecting a form
[ ] when form is selected, open Edit Report modal with specified patient ID

**Comment by browndav** [comment]
Per conversation with LG stakeholders in SF, footnote (1) would be a nice-to-have but isn't strictly necessary for the field test.

**Comment by alxndrsn** [comment]
@abbyad is there any use to including `g_patient_name` as well as `g_patient_id`?

Presumably at some point we'll want an enketo-widget to render `g_patient_id` fields as a contact-selected-dropdown-thingy with all the person-Contacts in.

**Comment by abbyad** [comment]
> is there any use to including g_patient_name as well as g_patient_id?

Yes, because the form may want to use the name within the a note. There may be other profile info that needs to be passed too eg EDD, DOB.

> Presumably at some point we'll want an enketo-widget to render g_patient_id fields as a contact-selected-dropdown-thingy with all the person-Contacts in.

Yes, that would be very useful. That allows for the alternate workflow of selecting form (eg new pregnancy) then person, rather than picking the person then adding a form to them. This alternate workflow is not required for the field test, but should be included at a later date. Its worth opening the issue now as a feature request placeholder.

**Comment by abbyad** [comment]
Looks good, although largely superseded by #1266
