### ISSUE TITLE
Targets/Analytics for mobile app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1230]
The mobile app has a Targets tab, which could likely be implemented within our current Analytics tab, renamed to Targets. This issue is a placeholder for requirements and discussion.

Here is the latest mockup of the values that need to be shown for the Targets tab:
![image](https://cloud.githubusercontent.com/assets/789512/9570405/af89842c-4f58-11e5-94a4-86aa960bc639.png)

The "This month" is the current calendar month, not a rolling month period.

@yembrick can assist with questions related to the calculations.

For our first deployment the non mobile app users will be viewing their dashboards in the standalone Analytics webapp, not the Analytics tab.

**Comment by abbyad** [comment]
Updated targets tab:

![image](https://cloud.githubusercontent.com/assets/789512/9689093/9d681bd0-5301-11e5-8010-d6e67167fde0.png)

**Comment by joshnesbit** [comment]
New mockups from Lester are shown below.

![lg-app-targets](https://cloud.githubusercontent.com/assets/377216/10441555/1898d16c-70ff-11e5-90d5-2c5e17f68682.png)

Additional notes:

- Better to flush left words and numbers
- Icons should always appear top the left
- We could display the tab name in the top color bar (there are implications for other tabs with filters or search)
- Differentiate the goal target from the actual figure with color
- Once the goal is reached the colors could match indicating target reached
- Make pixel height the same for list items

**Comment by garethbowen** [comment]
> Make pixel height the same for list items
This can't be guaranteed because the target names will be configurable and internationalised, and the icons are configurable. We should set a min-height on the items so an optimally configured system has all items same height but we still gracefully handle text overflow and large icons.

**Comment by abbyad** [comment]
Posting the latest mockup from @Lesterng:
![image](https://cloud.githubusercontent.com/assets/789512/10586153/d44e7060-7668-11e5-84f4-d3e04b3c1b00.png)

The feedback that we got from users gives us a good starting point since they want the targets for the current month only. From discussions with users and partners, these are calendar month targets, not a rolling month window.

**Comment by abbyad** [comment]
Closing as the design discussion is complete, moving the final mockup to #1230.
