### ISSUE TITLE
conditional alerts should run after update clinics/facilities transition.

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1231]
In most cases when using the conditional alerts feature you want to run the facilities transition first to have the related data on the doc when you render the alert message.  Example:  https://github.com/medic/medic-projects/issues/38

```
The {{clinic.name}} HP has just reported a suspected outbreak with {{NUM}} of {{DIS}}. Please call them at {{contact.phone}} to follow up.
```

This should be a fairly easy fix on the development branch where we can query on the `transitions` property on the doc to see what transitions have run.  But the release branch doesn't behave this way.  One small thing you can do to accommodate this is modify your message to check if the `contact` object is defined.

```
{{#contact}}The {{clinic.name}} HP has just reported a suspected outbreak with {{NUM}} of {{DIS}}. Please call them at {{contact.phone}} to follow up.{{/contact}}{{^contact}}A suspected outbreak report from {{from}} was just submitted with {{NUM}} of {{DIS}}, please call them to follow up.{{/contact}}
```

**Comment by garethbowen** [comment]
This was done when the order of transitions was hardcoded. Closing.
