### ISSUE TITLE
[enketo] Include via npm/browserify/bower

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1232]
Currently enketo code is included in `medic-webapp` as an unminified blob built from a tag of https://github.com/alxndrsn/enketo-core: https://github.com/alxndrsn/enketo-core/tags.  Instead we should be including it via browserify, bower or npm.

**Comment by alxndrsn** [comment]
@garethbowen I suspect you can tell me exactly how this should be done - would welcome your input

**Comment by alxndrsn** [comment]
Enketo JS is now included via `npm`/`package.json`, and built using `grunt`: https://github.com/medic/medic-webapp/blob/develop/Gruntfile.js#L73

**Comment by garethbowen** [comment]
Acceptance testing passed: this is a step in the right direction.
