### ISSUE TITLE
Clean up enketo bundling

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1235]
0. ~~Remove duplicated fonts~~
6. ~~move enketo fonts to static/fonts~~
4. ~~make sure fonts are included in app cache~~
99. ~~move enketo XSL to static/xsl~~
122. ~~make sure XSL files are included in app cache~~
1. ~~Bundle the enketo js into inbox.js~~
2. Remove the enketo specific grunt tasks and merge these into the type specific grunt tasks, eg: `grunt browserify` not `grunt browserify:enketo`
3. ~~Remove `/static/enketo` directory~~

**Comment by garethbowen** [comment]
My first attempt is in this branch: https://github.com/medic/medic-webapp/tree/1232-enketo-bundling

**Comment by alxndrsn** [comment]
Where do you want the enketo-specific JS to go (e.g. `config.json`, `widgets.js`, custom widgets), if not in `/static/enketo`?

**Comment by garethbowen** [comment]
There's more than that in there now, so remove everything that's not necessary. Anything that's left should be under `/static/js`, so maybe `/static/js/enketo`

**Comment by alxndrsn** [comment]
Is it really desirable to merge the `browserify:enketo` task with `browserify:dist`?  Calling `grunt:browserify` will currently execute both, if that's what you want.  I'm hesitant to merge them because the `enketo` task is significantly more complex than the `dist` task, and it will make it harder to tell what config applies specifically to one or the other if they are merged.

**Comment by garethbowen** [comment]
To me it's a little cleaner to have everything browserified together rather than two browserify steps and a concatenate. However I take your point about the complex browserify configuration for enketo. Hopefully this will get less complex over time and then we can go back to a single browserify.

**Comment by garethbowen** [comment]
Oh man, that's so much better. Good job!

**Comment by alxndrsn** [comment]
:+1:
