### ISSUE TITLE
Branded logo in webapp's login page

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1240]
For some of our partners we want to be able to show their logo instead of ours within the mobile app.

For now the requirement is to have the branded logo in the mobile app (login screen) only, but it is foreseeable that we will be asked to change all Medic logos to the partners'. If possible we should consider a strategy that will be reusable when we need to brand other logo locations as well (eg top left logo in desktop).

When the login screen is branded we should show a small "Powered by Medic Mobile" at the bottom.

**Comment by alxndrsn** [comment]
@garethbowen any thoughts if this this logo should be coming from couch, or should it be packaged with API?

**Comment by garethbowen** [comment]
I think this should be in couch to make it easier to support the next partner and for partners to change logos.

We should do all the logos at the same time, so login page, webapp (small and large), and favicon. By the same logic, we should probably also allow configuration of the app name rather than hardcoding "Medic Mobile" everywhere.

In the webapp we're quite sensitive to logo dimensions so either fix the height in css or be clear about restrictions in the configuration page.

**Comment by alxndrsn** [comment]
@garethbowen it's not clear to me how the logo on the login page can come from couch - surely the user needs to be logged in before data can be fetched from couch?

**Comment by garethbowen** [comment]
@alxndrsn API is initialised with a couch URL with basic auth so API always has access to couch. The first cut is to simply proxy requests through to couch using the admin auth. We can use the existing [configuration listener](https://github.com/medic/medic-api/blob/develop/config.js#L106) to cache the logos if needed, but proxying should be fine for now.

**Comment by SCdF** [comment]
@estellecomment please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by estellecomment** [comment]
@sglangevin Is this a current requirement? If not, I'll close this, and we'll reopen when/if it comes up again.

**Comment by sglangevin** [comment]
This is not currently required. Let's close this for now and re-open if/when it comes up again. I'll add it to our backlog of design ideas so we don't forget about it.
