### ISSUE TITLE
Show Enketo form in the right pane

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1243]
Part of a larger UX refactor, we want to show the Enketo form in the right pane of the webapp, instead of the modal. This will make more sense with the rest of the UX refactor issues to come.

**Comment by garethbowen** [comment]
You can now create and edit enketo reports in the right pane of the Reports tab, and create reports in the right pane of the Tasks tab by clicking the action buttons.

**Comment by abbyad** [comment]
Looks good, moving to Ready. 

One thing to note is that once in the form you cannot easily go back to the originating contact/task in desktop mode.
