### ISSUE TITLE
Refactor EditReportCtrl for unit testing and maintainance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1245]
The EditReportCtrl has the Enketo rendering code embedded in it. This is bad because it cannot be reused, is outside of the concern of the controller, and controllers are difficult to unit test.

Pull as much of the Enketo code out of the controller and into an Enketo service as possible. Then write unit tests.

**Comment by alxndrsn** [comment]
@garethbowen separated the data-centric stuff into Enketo service.  Would value your opinion on what is worth unit testing.

**Comment by garethbowen** [comment]
@alxndrsn Nice one. I think there's still more that should be moved into the service to make it easy to embed an Enketo form in a view other than EditReport, but we can cross that bridge when we come to it. The ideal is to have the controller just init the service with the DOM element to render in and the service does everything else, but I suspect the reality lies somewhere between that and what we have now.

As for testing the gold standard is every user story has at least one e2e test and every code branch has at least one unit test. There is prior art for both e2e and unit tests and I'm happy to help.

I think it's worth testing that each function the service exposes is doing what you think it's doing, ie: calling the expected services with the expected parameters the expected number of times and returning the expected result. I find this particularly helps when I'm refactoring to know that I haven't stuffed something up.

**Comment by alxndrsn** [comment]
```
TODO
[ ] work out interface that service should really have
[ ] modify interface of service to match ideal
[ ] identify an end-to-end test to write
[ ] write end-to-end test
[ ] write unit tests for exported functions:
    [ ] transformXml()
    [ ] withFormByFormInternalId()
    [ ] save()
    [ ] withAllForms()

**Comment by garethbowen** [comment]
@alxndrsn I can see a couple of workarounds for the Blob issue.

1. First there's [the polyfill option](http://www.finallybinary.com/blob-support-in-phantomjs/), which is a little ugly but we can just include the blob.js in our karma tests and ignore it elsewhere.
2. Alternatively you could pull out a tiny service for turning a blob into a URL which you can then mock out in unit testing.

I think the mock approach is my preferred option.

**Comment by alxndrsn** [comment]
Recent changes in `EnketoService` mean most of my work on this is now irrelevant.
