### ISSUE TITLE
Add API endpoint to manage settings

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1250]
Useful in general, and would be good to migrate app_settings package docs into API (medic-api).  https://github.com/garden20/app_settings

**Comment by mandric** [comment]
Easiest way I know right now to get the couchapp's version string is `curl https://username:secret@hostname/medic/_design/medic/_rewrite/app_settings/medic | jq .meta.config.version`.

**Comment by mandric** [comment]
Easiest way to get current settings for an app:
```
curl https://username:secret@hostname/medic/_design/medic/_rewrite/app_settings/medic | jq .settings
```

**Comment by SCdF** [comment]
@SCdF please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by SCdF** [comment]
There is a script to do this for local dev work, and AFAIK there is no pressing need for it to be supported programmatically. I imagine if there was we would have done it in the last 2.5 years.
