### ISSUE TITLE
Android container: Support screen reorientation

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1251]
We used the Tecno Y4's "lock orientation" feature for the demo. Currently, turning the device from portrait to landscape mode (apparently) triggers a full page reload, which turns the screen white for a relatively long period of time and makes the application appear (okay, actually-be) unresponsive.

We should be able to switch between portrait and landscape mode on a Tecno Y4 Chromium 30 Webview without major UX disruption.

**Comment by abbyad** [comment]
I think this is a duplicate of #1188. @browndav, we can close that one in favor of this one if you prefer.

**Comment by browndav** [comment]
Closed; duplicate.
