### ISSUE TITLE
[Tasks] Icons and styling for individual tasks

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1252]
Here is a mockup of tasks with related icons:
![image](https://cloud.githubusercontent.com/assets/789512/9690078/3e05cc4e-5308-11e5-8603-ca4c7bfec26b.png)
**Primary icons:** On the left, relate to the task type. Ideally it would be possible to upload a new set of icons to choose from for each project.

**Secondary icons:** On the right, may relate to a property of the task's entity e.g. the patient a task relates to has danger signs, so show as a high risk pregnancy.

**Secondary label:** The text next to the alert icon should be configurable separately from the choice of the icon. Ideally it would be possible to set the text and color of that secondary text.

_Note that icons may overlap with the ones show in #1230._

**Comment by garethbowen** [comment]
### To test this

1. Go to Configuration > Icons and upload the icons you want to use for tasks. For best results the icons should be the same width and have transparent backgrounds or borders.
1. Update the nools configuration to emit tasks with the new fields
  - `icon`. This replaces the `type` property which is no longer used. Provide a string which refers to the name of the icon you want to render.
  - `priority`. One of "high", "medium", or `null`. This will define the status icon (if any) and styling of the task.
  - `priorityLabel`. A translation array to explain the priority status, eg: `[{ content: 'No visit for aaaaages', locale: 'en' }]`

**Comment by garethbowen** [comment]
Example screenshot:

![example-task-list](https://cloud.githubusercontent.com/assets/2064938/10179973/18a64f42-6766-11e5-8dec-077a54652f4f.png)

**Comment by abbyad** [comment]
Looks good!

With an admin user I see everything properly.
With a restricted user (eg demo on lg.dev) I see everything except the task icon and get the following in console:
`e {status: 404, name: "not_found", message: "missing", error: true, reason: "missing"}`

**Comment by abbyad** [comment]
Working well now with the fix. Moving to Ready.
