### ISSUE TITLE
Remove `+` from top bar

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1255]
The actions available in the `+` in the top bar should be moved to the "floating action bar" in their proper context.

**Submit report:** 
Practically speaking, most reports will be triggered from a task, or from a patient profile. For generic reports not related to a person, place, or tasks, you can `Create New Report` using the button in the action bar in the Reports tab shown here:
![image](https://cloud.githubusercontent.com/assets/789512/9690431/4f700ec0-530a-11e5-9148-00e89dd1eaae.png)

**Send message:** 
It is currently possible to send new messages via a button in the sub top bar of the Messages tab. Ideally that would be moved to follow the same pattern as with _Reports_. Since the Messages tab is not used in the mobile app yet it is suitable to leave it as is for now.

**Comment by abbyad** [comment]
Functionally this works well. Reopening to fix the following:
- From my tests in the mobile app and on computer, the FAB needs a bit more breathing room. It is recommended [here](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button) to have minimum of 16dp in mobile, 24dp in tablet/desktop. Currently it is tight to the corner in mobile-view, and in desktop-view the edge covers the scrollbars:

![image](https://cloud.githubusercontent.com/assets/789512/9854046/b41c7a8a-5ad4-11e5-9bd2-01d457263d5b.png)

- The + options stay visible after going back in mobile app or browser:
![screen shot 2015-09-14 at 11 29 07](https://cloud.githubusercontent.com/assets/789512/9853855/d496aed0-5ad3-11e5-967a-1df4eedef58f.png)

Design-wise I think we find ourselves in a transition point between the old action bar and the FAB, especially noticeable in desktop view. My preference would be to either use the action Bar or Button throughout, and not deploy with a mix of the two. 
However, using the Button throughout breaks the [Don’t have more than one floating action button per screen](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-large-screens) rule in desktop-view. It would also mean further changes to the mobile view which may be incompatible with the desktop view. For instance, having a FAB in a person's profile page could likely mean moving some actions from the FAB to an overflow menu in the toolbar in the mobile view - which doesn't correlate directly in desktop view. Solving this in the long term may resolve some other workflow issues, such as left pane actions in Messages and Reports interacting differently with the right pane.

Given that we don't want to undertake a major overhaul now and that the FAB currently works aside from the two fixes mentioned above, I think that the current viable options are:
a) leave it as it is now until we get more user feedback
b) change the fab to a bar similar to the image in the original comment on this issue

**Comment by garethbowen** [comment]
The action bar has been reinstated. @abbyad please review again.

**Comment by browndav** [comment]
LGTM.
