### ISSUE TITLE
[Contacts] Show search field when tab is loaded

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1256]
Show the full input field on the Contacts tab in mobile view. 

![image](https://cloud.githubusercontent.com/assets/789512/10619625/a015b2a4-7744-11e5-855b-5cc8743b6270.png)

If we do this for all search fields this will have unintended consequences in the Reports tab where the filter bar is already full of filters. We could show the search bar in full only when there is sufficient space, and collapse to the button version if there isn't. Given that this is a requirement only for the Contacts tab, we can take the approach that is most efficient (eg only have the full search bar in the Contacts tab, leave the field as is in the Reports tab).

**Comment by abbyad** [comment]
We have received feedback from groups of users during training that they didn't know what the `q` button (the search button) was for. Rather than having the search open by default as in the original post, having the search show in full, as it does in desktop mode, would help make it easier to use.

![image](https://cloud.githubusercontent.com/assets/789512/10581083/e0dfc87a-764e-11e5-8b5b-1a835863c16b.png)

This will however have unintended consequences in the Reports tab where the filter bar is already full of filters. Ideally the search bar would show in full when there is sufficient space, and collapse to the button version if there isn't.

Either way, we should also consider and test other search icons. The suggestion from users was to use the word `search` or an eye icon. 
Eg. `fa-eye`: ![image](https://cloud.githubusercontent.com/assets/789512/10581391/694108fe-7650-11e5-887d-88bfd48e9702.png)

**Comment by alxndrsn** [comment]
@abbyad where is that screenshot from showing the search bar embedded in the title bar instead of popping up?

**Comment by abbyad** [comment]
@alxndrsn that is a CG screenshot - combining a mobile screenshot with desktop elements

**Comment by garethbowen** [comment]
@joshnesbit @abbyad and I decided that once the search field is shown straight away, then the loupe combined with the "Search" placeholder value is good. eg:

![search](https://cloud.githubusercontent.com/assets/2064938/10682175/99ee6e42-798e-11e5-83db-a68491435e65.png)
