### ISSUE TITLE
[Contacts] Remove place and type filters based on user role

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1257]
In order to keep the workflow and UX cleaner, we have been asked to remove some filters. By making the visibility of the individual filter role based, we solve this problem and also have the benefit of postponing discussion related to the filters until we have feedback from users using them.

**Comment by browndav** [comment]
Clarification: we're talking about removing the drop-down boxes that drive the filtering system (from the UI itself, based on role), not changing the default filter selections or sort order or anything like that.

**Comment by abbyad** [comment]
Correct that this is to be able to remove the drop-down boxes. The default filter selection is going to be another issue.

**Comment by abbyad** [comment]
It would be good to have this done ahead of next week's demos, so moving to this current iteration. If this gets bumped to next iteration we should do it early next iteration.

**Comment by browndav** [comment]
Decision: hide the filters iff you are a leaf node, i.e. if the filters aren't likely to be useful.
