### ISSUE TITLE
[Contacts] Move add place and person buttons

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1259]
Based on feedback to clean up the UX and workflow for mobile users we should move the add place/person buttons to the floating action bar. 

- **Add Place** is within the left pane, see image below.
- **Add Person** is done in the action bar for the place, when it is being viewed in the right pane. This means that a person must be associated to a place. Issue related to this yet to come.
- Prevent the deletion of a place if there are people associated to it. The delete icon should be disabled, and/or if clicked should show an alert message explaining that the people would need to be deleted first.

![image](https://cloud.githubusercontent.com/assets/789512/9690654/c834f6c6-530b-11e5-9e05-d5df0a4c655c.png)

**Comment by abbyad** [comment]
This may be obvious or not, but figured I should point it out: the place that is created using the `+` action button in the left pane should be associated to the logged in user's location. If this place creation is done via a XML form as mentioned in #1260, this can be taken care of in the configuration.

Also, and this is more obvious, adding via the action bar in the "right" tab would add the place/person to that contact.

**Comment by alxndrsn** [comment]
Depends on #1350 (?)

**Comment by browndav** [comment]
Decision: not strictly necessary for the Monday demo (we could live with only #1350 if needed).

**Comment by abbyad** [comment]
Closing as this has been divided into https://github.com/medic/medic-webapp/issues/1375 and https://github.com/medic/medic-webapp/issues/1392
