### ISSUE TITLE
[Contacts] Action bar updates

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1263]
As seen in #1261 and #1262, the action bar has updated actions:

![image](https://cloud.githubusercontent.com/assets/789512/9692644/691ac9f6-5318-11e5-90fa-6310f0b52659.png)

- **Call**: In mobile/tablet view this should be a link to call the primary phone number for the contact (eg `href="tel:+16505551234"`) which we need to then handle in medic-android. In desktop view this can be either disabled, or replaced with the SMS action.
- **Add**: Opens a list of all the possible reports that can be submitted for this person/place. This would also include adding more people to a place, send SMS to the contact, and SMS all where appropriate.
- **Edit**: Edit the current person/place's basic info.
- **Delete**: As expected, deletes the person or place, but only if there are no people/places associated to it. If there are those must first be deleted or reassigned.

**Comment by abbyad** [comment]
The `Add` button is further detailed in #1228.

**Comment by garethbowen** [comment]
It's been decided that the Add button should now be a SMS button as in#1262

**Comment by abbyad** [comment]
Updated action bar:
![image](https://cloud.githubusercontent.com/assets/789512/10232023/2474ca80-6854-11e5-9c5c-0b7e4d86befe.png)

**Comment by garethbowen** [comment]
For health centers we currently have a "message all" button. This should still be available behind a dropdown menu from the message button.

**Comment by garethbowen** [comment]
Quite a confusing range of options here...

*Call*: Invokes the dialer with the "tel:" protocol. Hidden on desktop. Disabled if contact doesn't have a phone number.
*Message*: On mobile invokes a messaging app with "sms:" protocol. On desktop launches the Send Message modal. On desktop if contact is a health center shows a dropdown for Send Message or Message All. Disabled if contact doesn't have a phone number.
*Edit*: Always enabled and displayed on all devices.
*Delete*: Displayed on all devices. Disabled if the contact is a Primary Contact or has Children.

**Comment by garethbowen** [comment]
Reopening - only close when code review has passed.
