### ISSUE TITLE
[Reports] Move top level tab to beneath Menu icon

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1264]
As seen below, the Reports tab should not be accessible as a top level tab. This is to streamline the top level options and avoid confusion with users that rarely need to see the reports tab - which will increasingly be the case for certain types of users.

![image](https://cloud.githubusercontent.com/assets/789512/9692952/a39e29f4-531a-11e5-9f2f-95067ed2d5c1.png)

Given that this requirement is likely to change from one project to another, and even for different types of users within a deployment, we likely want the choice of tabs shown under the Menu icon to be configurable by user role.

_Edit: Changed "settings" to "menu" icon for clarity._

**Comment by garethbowen** [comment]
@abbyad When you say "to beneath Settings" does you mean "to the hotdogs menu"?

**Comment by abbyad** [comment]
Yes, that is exactly what I meant.

I've heard us use "hotdogs", "hamburgers", and "settings" for the font-awesome [bars](http://fortawesome.github.io/Font-Awesome/icon/bars/), aka [menu](https://www.google.com/design/icons/#ic_menu) in Google's Material icons. I will refer to it as `menu` from here on since that's likely a clearer representation.

**Comment by abbyad** [comment]
Moving this to the current iteration so that we avoid visual distractions during the demos/review next week. If this issue gets bumped to the next iteration we should first temporarily move this tab to rightmost position.

**Comment by garethbowen** [comment]
Users without the "can_view_reports" permission will now get the Reports item in the hotdogs dropdown not as a tab.

**Comment by abbyad** [comment]
Thanks @garethbowen, looks good. 
![image](https://cloud.githubusercontent.com/assets/789512/10253837/b9ed4f10-690d-11e5-84b8-036e7f5a87b1.png)

Are the tabs meant to stretch to fill space? If not, we may want to center them.

**Comment by garethbowen** [comment]
They stretch but I added a maximum width because they look weird if they get too wide. I can centre them if you like but it looks a little unbalanced now that the logo is gone.

**Comment by alxndrsn** [comment]
LGTM except for line note

**Comment by garethbowen** [comment]
I split off #1393 to rename the permissions.
