### ISSUE TITLE
Submit reports related to a person or place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1266]
We want to submit reports about a person (eg new pregnancy), or about a place (eg household survey). Currently, followup reports are based on `patient_id`, which is created with a registration form but has no connection to our new contacts.

We likely need to assign people and places a unique ID, and given that contact creation can happen offline, this ID probably needs to be a UUID. This ID could then be discreetly passed to any task and report related to the place/person, and submitted reports would then be associated to the contact.

Reports submitted about a person or place would then be shown on their profile, as described in #1261 and #1262.

**Comment by alxndrsn** [comment]
> We likely need to assign people and places a unique ID

Can we just use their db ID?

**Comment by browndav** [comment]
I think there are possibly two issues here: one is binding a report to a person andor place. That can use the internal UUID, i.e. `doc._id`. There may be another issue here related to auto-assigning smaller human-readable/memorable IDs to patients/contacts. @abbyad: Confirm that we're just talking about the former here?

**Comment by abbyad** [comment]
Yes, we are just taking about something like `doc._id` here, not the human readable ID.

The human readable ID is just a extra non-mandatory field on a profile (eg "external id"), so we cannot rely on that for associating forms to people or places.

**Comment by garethbowen** [comment]
I've added a patient select widget so if a field has `type="medicPatientSelect"` then it's easy for users to select the UUID.

Then I added buttons to submit a form from the contact details page which prepopulate the patient_id field using the contacts UUID.

I'll add Place selection soon.

**Comment by alxndrsn** [comment]
I have similar widgets in #1260; could be interesting to compare.

**Comment by garethbowen** [comment]
I've added a place select widget so if a field has `type="medicPlaceSelect"` then it's easy for users to select the UUID.

**Comment by abbyad** [comment]
I have tested with a `data/patient_id` field as a string and as a `medicPatientSelect`. In both cases the field is not populated with the `patient_id` of the person. The `medicPatientSelect` looks great although it was taking 3-4 seconds to load.

@garethbowen should I be able to see the ID in the form, or is it silently passed with the submitted form?

**Comment by abbyad** [comment]
Testing with `place_id` prepopulates the field appropriately, but still can't get `patient_id` to prepopulate.

**Comment by garethbowen** [comment]
This should work again now.

**Comment by abbyad** [comment]
Works well now. Moving to Ready.
