### ISSUE TITLE
[Tasks] Configurable start and end time

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1268]
Tasks are now shown as soon as they pass a rule. We would want the task to be shown only during a particular time window. This way, a task could be configured to only show up 2 days ahead of an event, and disappear when no longer relevant (eg no point doing the 48hr followup 2 weeks later).

**Comment by garethbowen** [comment]
I've added `start` and `end` properties to the task schedule event configuration, so each event can specify when it should be shown. Then before emitting the event you can use a new Utils function `isTimely`, eg:

```js
Utils.getSchedule('anc-registration').events.forEach(function(s) {
  var due = Utils.addDate(Utils.getLmpDate(r.doc), s.days).toISOString();
  if (Utils.isTimely(due, event)) {
    emit('task', { ... });
  }
});
```

**Comment by abbyad** [comment]
This is working well, moving to Ready.
