### ISSUE TITLE
Error exporting in v0.4.9

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1273]
As reported by @bishwas-medic, exporting reports from the top level menu gives the following error:
`{"error":"query_parse_error","reason":"No rows can match your key range, reverse your start_key and end_key or set descending=true"}`

Manually swapping the start and end key in the URL, or adding `descending=true` do fix the problem.

**Comment by abbyad** [comment]
I am seeing the Code Review tag, but not when it was added in the issue history. Also not seeing the commit in the history for the code review. @mandric what is the status of this issue?

**Comment by mandric** [comment]
Weird not sure what happened here. There is no commit yet and code review is set maybe because of the rename or something?

**Comment by mandric** [comment]
Pushed to rc.dev for testing.

**Comment by abbyad** [comment]
Seems to work well. @bishwas-medic can you test this too?

**Comment by abbyad** [comment]
This should be moved to Ready as soon as the code review is done.

**Comment by abbyad** [comment]
Assigned to @garethbowen for code review.
