### ISSUE TITLE
Extensible Person/Place Profiles via Enketo

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1275]
Allow a special Enketo form type to be paired with each major contact type (e.g. places and people and clinics and CHWs). Call these forms "contact profile forms". If a contact profile form is configured for a particular contact type, prompt users to fill in that form when a contact of that type is created.

When viewing information about a contact, a report submission history will be presented (see #1262). Lift any data pertaining to a contact profile form submission out of this list and to the top level; present the contents of the form submissions (yes, potentially plural) as a human-readable tabular summary. This will almost always a proper subset of the full field set; some ability to mask/hide less-important fields would be required.

**Comment by alxndrsn** [comment]
Big overlap with #1260(?)

**Comment by browndav** [comment]
Big overlap. I think a successful resolution of #1260, at least as we've interpreted it thus far, should resolve this issue as well.

**Comment by browndav** [comment]
Goal: figure out how/if the results of #1260 need to be refactored/modified.
