### ISSUE TITLE
[enketo] missing translation/i18n keys

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1280]
Enketo translations need adding to `messages_en.properties` in `medic-api`

**Comment by garethbowen** [comment]
Also, in [edit_report.html](https://github.com/medic/medic-webapp/blob/develop/templates/modals/edit_report.html#L47-L48) we probably don't want to translate the `<` and `>` symbols, eg: I think `{{'&lt; prev' | translate}}` should be `&lt; {{'prev' | translate}}`.

**Comment by garethbowen** [comment]
Check for existing equivalent labels before adding the new ones, eg: we already have a "Previous" which should be used instead of "prev".

**Comment by alxndrsn** [comment]
:+1:
