### ISSUE TITLE
logging in with a specific URL redirects to /messages

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1286]
# Steps to reproduce
1, Point your browser to [http://localhost:5988/medic/_design/medic/_rewrite/#/reports](http://localhost:5988/medic/_design/medic/_rewrite/#/reports)
2. fill in the login screen
3. observe that you're now looking at Messages tab instead of Reports

**Comment by alxndrsn** [comment]
This looks like a change in `webapp`'s behaviour rather than `api`.

**Comment by garethbowen** [comment]
It looks like the redirect URL isn't working. Either webapp isn't passing it to api, or api isn't passing it back.

**Comment by alxndrsn** [comment]
Both are passing URLs fine, but `webapp` is prefixing the server/host/port, and `api` isn't expecting that.
