### ISSUE TITLE
clicking selected contact blanks the contact list

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1287]
# Steps to recreate

1. browse to *contacts* tab - http://localhost:5988/medic/_design/medic/_rewrite/#/contacts
2. wait for the top contact to become selected
4. click on the selected contact in left column
4. wait for the screen to refresh
3. observe that the contact info is displayed correctly, but the list of contacts now says _No contacts found_

# Screenshot
<img width="1280" alt="screen shot 2015-09-09 at 16 03 13" src="https://cloud.githubusercontent.com/assets/191496/9763899/548a3a74-570c-11e5-9aed-ec92cdb69bde.png">

# Expected behaviour

Clicking on the already-selected contact should either:

1. refresh the right pane to display the same information (this is what e.g. reclicking the selected Message does); or
2. do nothing

**Comment by alxndrsn** [comment]
N.B. the bug *does not occur* on https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/eeb17d6d-5dde-c2c0-62c4a1a0ca17fd18, but a very similar one does:

1. first time select

<img width="1280" alt="screen shot 2015-09-09 at 18 03 34" src="https://cloud.githubusercontent.com/assets/191496/9767180/32fc78d4-571d-11e5-8368-b0ddd0d76030.png">

2. second time select

<img width="1280" alt="screen shot 2015-09-09 at 18 03 38" src="https://cloud.githubusercontent.com/assets/191496/9767181/38744f44-571d-11e5-943e-2b3858fdefe9.png">

**Comment by alxndrsn** [comment]
@garethbowen please check my fix.  It solves the bug, but it looks like the original code was trying to do something clever which wasn't obvious, and may not be happening any more.

**Comment by garethbowen** [comment]
Looks good to me. The old code has been moved around a bit so hopefully what it was trying to do is no longer needed.
