### ISSUE TITLE
Cannot `Message All` to a district or Catchment Area

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1288]
It's only possible to Message All members of a _Health Center_, and not a _Catchment Area_ or a _District_.

**Comment by alxndrsn** [comment]
@abbyad is this by-design?

**Comment by browndav** [comment]
Clarification: you're this as a bug in the current `develop` branch build, and not a problem with UI/UX revisions/mockups that haven't been implemented yet, right?

**Comment by garethbowen** [comment]
Yes that's right Dave. It was certainly by design at the time. For DIY you really didn't want to be messaging an entire District. I suspect that still holds. Messaging isn't handled within app for our current project anyway so I think it's fine to leave it as is.

**Comment by abbyad** [comment]
As @garethbowen mentioned, this was by-design at the time. Even with the mobile app it mostly holds true. 

We can reevaluate this with future FAB work mentioned [here](https://github.com/medic/medic-webapp/issues/1255#issuecomment-140137519).

**Comment by browndav** [comment]
Behavior is by design, moving to `Released`.
