### ISSUE TITLE
cannot open left-list items in a new browser tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1291]
cannot open messages/reports in a new browser tab using any of these methods:

* cmd-click (ctrl-click on non-mac)
* middle-click
* right-click > Open Link in New Tab

Would be nice if this behaved like normal.

**Comment by garethbowen** [comment]
This just got a lot easier now that animations have been removed. We need to remove the ng-click attribute and just use an href to load the item.

**Comment by browndav** [comment]
LGTM.
