### ISSUE TITLE
Only show relevant forms when `Submit Form` action is clicked on a Contact

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1293]
> Showing the Relevant forms would make it easier to maintain the workflow for users. For instance a 5 year old boy would not have "Add pregnancy" as a form option. The rules for which form to show may be rather complex, so it may be better to show all forms for the first iteration and then break out more issues for the form display rules (eg Woman age 10 to 50, without an outstanding pregnancy)
> — _@abbyad_

Split from #1228

**Comment by abbyad** [comment]
For the field test we will do the basic version of this feature, which is to show people forms for people, and place fields for places. This means that only forms that have a `patient_id` field would show on the Person profile (eg mother, child), and forms that have `place_id` would show on Place profile (eg Family).

Further logic can happen inside of the form for now.

**Comment by garethbowen** [comment]
To get forms to show up in the contact profile you need to add a `context` property to the report doc, eg: `context: { "person": true, "place": true }`

**Comment by alxndrsn** [comment]
Looks fine.  Do you have to set `doc.context` manually in futon?  Would be nice to add it to the uploader as well; what do you think @abbyad?

**Comment by abbyad** [comment]
Yes, having it set via the uploader would be ideal @alxndrsn.

**Comment by abbyad** [comment]
Works well, moving to Ready. I'll open an issue for making it possible to set this with the uploader.
