### ISSUE TITLE
Reports Tab: Synchronization only occurs when changes feed activity is present

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1294]
This is an issue that we ran in to during the demo and ended up working around. In most cases, the `Reports` tab will display a spinner until some other unrelated changes feed activity comes in.

To reproduce on lg.dev: pull up the `Reports` tab in `medic-android` using a Chromium 30 Webview, then mark a message verified/unverified using another computer. You'll notice that the verified/unverified change unblocks the mobile app, and allows the `Reports` tab to fully load.

**Comment by garethbowen** [comment]
I didn't manage to replicate the issue but I've found that using the Promise library rather than angular's `$q` service sometimes has this effect. I've switched to using $q. Please reopen if you reproduce it.
