### ISSUE TITLE
Geolocation doesn't work offline

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1295]
When offline the geolocation widget fails to display the world map. 

![geolocation](https://cloud.githubusercontent.com/assets/2064938/9779930/0a773eda-57d6-11e5-98ac-887b08397533.png)

I doubt we should store the world map(s) on the phone but we could clean up the above a little, at least hiding the UI element.

**Comment by abbyad** [comment]
For our current purposes we need "get current location" which doesn't require the map anyhow. Could we create a new widget that doesn't show the map at all, or hide the map similar to how "hide-inputs" is hiding the input fields?

**Comment by garethbowen** [comment]
Duplicate of #1326
