### ISSUE TITLE
No way to create a new report

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1296]
The _Submit Report_ link has been removed from the `+` menu in the header, and the _Submit Report_ action button when viewing a contact no longer works.

**Comment by alxndrsn** [comment]
Is this caused by f930ad1a14834c6d155452a242c67abbd685425d?

**Comment by garethbowen** [comment]
This is by design. Have a read of #1255

**Comment by garethbowen** [comment]
I've removed the form select modal so there's no easy way to go from a person profile to creating a new report. This will be tackled as part of #1262 so I'll just remove the broken button for now. To create a new Report for now go to the Reports tab and click the yellow fab at the bottom of the reports list.

**Comment by alxndrsn** [comment]
The broken button is explicitly requested in https://github.com/medic/medic-webapp/issues/1228

**Comment by alxndrsn** [comment]
Yellow fob works nicely, so this bug is invalid.  But https://github.com/medic/medic-webapp/commit/f930ad1a14834c6d155452a242c67abbd685425d breaks #1228.

**Comment by garethbowen** [comment]
It's been decided to replace the broken Send Report button in the action bar with a list of actions in the page itself as discussed here: #1262
