### ISSUE TITLE
Put titles in filter bar

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1302]
In mobile when viewing the right pane the filters bar is empty except for a back button. We should use this space for the title of the pane to save vertical space.

For example, instead of this:

![task-header-existing](https://cloud.githubusercontent.com/assets/2064938/9920453/3eee3b6c-5d28-11e5-87c2-3045ffd6e858.png)

Have this:

![task-header-mobile](https://cloud.githubusercontent.com/assets/2064938/9920363/96ca28b0-5d27-11e5-8fbe-585d945d6a98.png)

The desktop view should remain as is because the filters bar takes up the full width on some pages, so render the title in both places and show/hide using responsive css.

Some of the code is already in place - check out InboxCtrl $scope.setTitle.

**Comment by abbyad** [comment]
Does this issue cover moving form titles to the filter bar as well?

Eg moving "New Pregnancy" to the top bar
![screen shot 2015-10-07 at 19 24 48](https://cloud.githubusercontent.com/assets/789512/10353958/1652e3ea-6d29-11e5-8c3b-d25bd0dd1cd4.png)

**Comment by garethbowen** [comment]
Yes I think so. It might be better to take the `<title>` out of the form xml (ie: the attachment) and use the name configured in the form document instead.

**Comment by abbyad** [comment]
If you remove it from the XML what happens to the title in desktop mode?

Also, the title with the form document in the db is currently [obtained from the XML's title tag](https://github.com/medic/medic-webapp/blob/a895047cc5d1ad5490796f107dcdea4caee288f0/scripts/upload_xform.sh#L39).

Would it be possible to hide the redundant title in mobile mode instead?

**Comment by garethbowen** [comment]
> If you remove it from the XML what happens to the title in desktop mode?

It's gone. It's not very useful because you just clicked on it to launch the form.

> Also, the title with the form document in the db is currently obtained from the XML's title tag.

That should be updated.

> Would it be possible to hide the redundant title in mobile mode instead?

Yeah it's possible it just leads to duplication both in configuration and in code.

**Comment by abbyad** [comment]
We should work towards reducing the burden of those creating the forms and configurations, since they will likely be using standard XForms created with form builders or XLSform.

Perhaps this is more a question for @alxndrsn, but do you recommend that the upload script strips the title and uses it in the form doc, or for the person uploading the form to strip the title and pass the title (and modified form) to the upload script? Or something else?

**Comment by garethbowen** [comment]
At a later point any title in the xform is completely overwritten by a translated one anyway, so at the moment it's going through a strange loop where the script pulls it out, and then our code sticks it back in.

It needs to be configured outside of the xform for internationalisation reasons, and this can be made easy to do once we have admin pages.

**Comment by abbyad** [comment]
Ok, thanks @garethbowen.
I will create another issue for the upload script to strip the title until we have the admin pages.
