### ISSUE TITLE
Use Node 5.x

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1304]
It's a large upgrade and notably uses a much later version of v8.

Consider dropping support for 0.10, or both 0.10 and 0.12 which would allow us to use a bunch of new language features.

**Comment by estellecomment** [comment]
Medic OS update
App compat, including garden

**Comment by SCdF** [comment]
I think we should make a decision about whether we're doing this before March. `medic-webapp` now relies on node 4.x to run protractor tests, and it would be good if all our node apps were on the same version to avoid bouncing around with nvm

**Comment by browndav** [comment]
Self-assigning for Medic OS update and new build.

**Comment by garethbowen** [comment]
LGTM. Feel free to merge and close this issue.
