### ISSUE TITLE
Edit the submitter of Enketo forms

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1305]
When you click the Edit button in the action bar of a JSON report you get an Edit Report modal which lets you change the submitter. On an Enketo report you get to edit the form contents inline.

Add a new button for "Reassign" or "Edit Submitter" or something which allows you to edit the contact for either JSON or Enketo forms. This should have a new privilege so it can be configured to only show for high level users.

There is only space for 4 buttons in the right hand side action bar so this will need some design work.

**Comment by alxndrsn** [comment]
Please file a new issue or re-open when this is actually a priority.

**Comment by alxndrsn** [comment]
Please file a new issue or re-open when this is actually a priority.

When considering implementing this ticket, pay attention to:
* support for Service Workers on android: http://caniuse.com/#feat=serviceworkers
* support for appcache: http://caniuse.com/#search=appcache

At the time of writing this comment, appcache is still supported by all major browsers except for Opera Mini, whereas Service Workers do not work on Android versions < 5
