### ISSUE TITLE
Generic ANC configuration P form has two position 0 fields

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1308]
https://github.com/medic/medic-projects/blob/master/demo-anc/forms.json#L9-L52

Both "last_menstrual_period" and "patient_name" have position 0.

This has led to the middleware getting the columns in a fairly arbitrary order and is leading to a different arbitrary order as I move these forms to postgres.

**Comment by btbonval** [comment]
Although it is the ANC demo, this problem is shown in at least on production ANC deployment, probably because the ANC demo is copy/pasted or used directly.

**Comment by btbonval** [comment]
The Middleware currently expects (lmp, name). Changing that would be involved. So if we can, lmp is position 0 and name is position 1.

**Comment by garethbowen** [comment]
Code review please @abbyad
