### ISSUE TITLE
Recurring tasks

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1311]
In several existing projects we are sending notifications for users to submit daily/weekly/monthly reports. The requirements for the second part are slightly different since you'd likely want the monthly task/reminder on the same day every month, as opposed to a fixed number of days since the last submission.

**Comment by garethbowen** [comment]
> For our first deployment, a survey must submitted for each household/family every 6 months. We want to configure a task to show up when the previous survey is nearly 6 months old.

This can be done already. Registration can have a schedule with a single task due in 6 months to file a survey report. The survey report can also have a schedule with a single task due in 6 months.

**Comment by garethbowen** [comment]
In discussion with @abbyad we realised that the LG use case can be solved with the existing feature set so this is now on the backlog until recurring tasks are required.

**Comment by abbyad** [comment]
Closing as this hasn't been requested again, and when it is we can first try to solve this with clever task-rules.
