### ISSUE TITLE
Contacts: Scrolling to the bottom of the left pane throws an error

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1314]
If you scroll down past the bottom of the left pane of the contacts screen, the following error is thrown when you run out of items to view:
```
TypeError: Cannot read property 'length' of undefined
    at n.a.controller.b.query (inbox.js:28)
    at inbox.js:28
    at dependencies.js:4
    at e (dependencies.js:2)
    at dependencies.js:2
```

**Comment by garethbowen** [comment]
Fixed in: https://github.com/medic/medic-webapp/commit/3cb7feb169932cf43414a60f2e1e666f5618da7d

**Comment by abbyad** [comment]
Assigning to @joshnesbit for acceptance testing.

**Comment by joshnesbit** [comment]
Looks good to me in Chrome in desktop, tablet, and mobile views. Also looks good in Android.
