### ISSUE TITLE
Contact profile updates

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1315]
UI changes for the person/place profiles using the following general styling:

![image](https://cloud.githubusercontent.com/assets/789512/10033666/c628bc68-6158-11e5-98a8-d369e0ba283e.png)

**Comment by abbyad** [comment]
Here are some additional mockups for a place on the left, a person on the right:
![image](https://cloud.githubusercontent.com/assets/789512/10083690/988e6de0-62cd-11e5-9439-b801f7a2a832.png)

Some extra notes:
- The top section with basic info can remain the same for now, with the noted formatting change. When #1260 is complete, we can review the content and formatting further.
- The boxes do not have rounded corners.
- There would be no difference in the desktop view

Here is a quick pass at what a section could be, as seen in the mobile version:
![image](https://cloud.githubusercontent.com/assets/789512/10080624/a1169668-62be-11e5-9865-8e4e28f8da15.png)

**Comment by garethbowen** [comment]
From talking to @abbyad ...

> There would be no difference in the desktop view

As in, it should look the same as mobile, just wider. Try having the lists in columns to use horizontal space better.
