### ISSUE TITLE
Enketo styling updates

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1316]
Comments from @Lesterng:
> Make the forms on a white background
> Checkboxes should all be squares. Don’t mix with circles.

Styling:
![image](https://cloud.githubusercontent.com/assets/789512/10033742/69528ebe-6159-11e5-8c1e-f92612150ad8.png)

**Comment by garethbowen** [comment]
The checkboxes are all squares. The circles are radio buttons which is consistent and appropriate.

**Comment by abbyad** [comment]
Looks good styling-wise until further user testing.
