### ISSUE TITLE
Difficult to close Contact filter without selecting a contact

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1318]
# Steps to recreate
1. go to _Contacts_ tab
2. select the 'contact type' filter
3. choose a type of contacts you want to see
4. try to click below the popup to see the list of contacts
5. observe that you are now viewing a specific contact, rather than seeing the list that you've just filtered
# Expected behaviour
## Semi modality

I'd expect that clicking an item in the contact list would just close the popup, rather than selecting that contact.  Clicking on a tab or another filter option, it might make more sense for the standard operation to be continued because I can actually see what I'm clicking on.
## Close button

Another option might just be to have a _close_ button on the popup.
# Screenshot

<img width="451" alt="screen shot 2015-09-23 at 13 04 34" src="https://cloud.githubusercontent.com/assets/191496/10043472/b79eccc8-61f3-11e5-9b89-1ed9bafd70c5.png">

> Where do I click to escape from the popup??

**Comment by alxndrsn** [comment]
Moving to backlog as no milestone is assigned.

**Comment by sglangevin** [comment]
Filters have been removed from the Contacts tab.
