### ISSUE TITLE
include_docs=true should be implied

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1319]
when writing the couch2postgres app, this was not the case. I do not believe this holds true for the current production instances either.

The workaround is to leave `include_docs=true` in place.

**Comment by btbonval** [comment]
I wrote the couch2postgres app against a medic-os image, any tips on finding the version of a running system would be helpful. I don't know what version it is running.

**Comment by btbonval** [comment]
This is the only medic-os iso I can find on my computer with the VM.
`medic-os-v1.1.0-20150623-x86-virtual.iso`.

That might be the image I encountered where `include_docs=true` made a big difference. If the handling of `include_docs` has changed since the above image was pressed, I will need to modify the behavior of the couch2postgres adapter to match newer systems. Though the adapter did download all of HealthRight(.app.medicmobile.org) just fine.

**Comment by browndav** [comment]
I'm having trouble understanding if there's still an outstanding issue here. Is it that you're seeing differing export defaults between version 0.4.3 and 0.4.9?

**Comment by mandric** [comment]
Pretty sure this was a bug/regression introduced in 0.4.8 and should be fixed in 0.4.10 and released shortly.  See https://github.com/medic/medic-webapp/issues/1273

**Comment by btbonval** [comment]
I don't think this feature was available in all of 0.4 (ignoring regression). This issue was filed before we realized the disparity of running production versions. This might be closed for the 0.4 code branch as noted above.

The question is whether this issue is about code base or if it is about production systems. I was told this should work on production systems. It does not. Should we keep this open until production systems are upgraded to a version where this works as expected, or assuming this bug is fixed in the mainline, should we consider this issue a spiritual duplicate of #1320 ?

**Comment by btbonval** [comment]
Production systems have been updated. In theory this feature should now be part of all running systems. The newest stable VM for medic-os that I could find is from July, which is still assuming `include_docs=false`.

However, the adapter now explicitly sets `include_docs=false` and `include_docs=true` for all calls to the webapp, further obviating the problem discussed in this issue.

I'm going to close this issue as being no longer relevant.
