### ISSUE TITLE
/api/v1 urls do not work for current production systems

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1320]
I am alternatively told I should be using them, or that maybe those systems haven't been upgraded enough to support it.

Production systems include healthright.app, christianaid.app, etc. basically any production systems which have a dashboard and that I have tried using the `/api/v1/ urls with have not worked. I cannot speak about systems without dashboards or middleware as I don't use them.

Currently the middleware URLs are all of the form: `https://xxx.app.medicmobile.org/medic-api/v0.4/export/`. works fine but I am conflictingly told that's fine or that's not correct.

**Comment by browndav** [comment]
Do you have an example of a non-working instance and API URL that we can start with?

**Comment by btbonval** [comment]
If someone tells me the URL I'm supposed to use in place of the above, I can try to use it and share the details of the problem.

**Comment by btbonval** [comment]
let me get an exact URL to transform into the new API style from a random URL in the middleware chosen at random:
https://healthright.app.medicmobile.org/medic/_design/medic/_rewrite/export/forms/V?startkey=%5Btrue%2C%22V%22%2C%7B%7D%5D%0A&endkey=%5Btrue%2C%22V%22%2C0%5D&include_docs=true&descending=true

This gets all V forms from HealthRight. What is the correct URL I should be using? I will try it.

**Comment by btbonval** [comment]
and a slightly different format URL from a different project. I didn't realize we had different URL styles throughout the Middleware.
https://kilifikids.app.medicmobile.org/medic-api/v0.4/export/forms/ANCR?startkey=%5Btrue%2C%22ANCR%22%2C%7B%7D%5D%0A&endkey=%5Btrue%2C%22ANCR%22%2C0%5D&include_docs=true&descending=true

**Comment by btbonval** [comment]
@mandric provided notes on versions of production systems. A great number are running 0.4.3 (and various flavors of -alpha and -beta). Meanwhile the changelog says api_v1 did not get introduced until 0.4.5.

**Comment by browndav** [comment]
Sounds like we should file an issue for any production upgrades that still need to be performed. There's a monitoring framework in the works (likely based on an existing package like Nagios) that should help keep this stuff straight going forward.

**Comment by btbonval** [comment]
@mandric do we have an issue for actively monitoring production versions and/or upgrading production systems?

This issue seems to be summarized more generally as "problems with production systems when production systems are running older 0.4 versions"

**Comment by mandric** [comment]
Re monitoring we (dev team) are going to have a meeting about it to come up with an action plan.  

For upgrading production systems we should create issues in medic-projects repo (one for each out-dated system since each server involves different parties) and make sure tech-leads and project managers are aware of any upgrades, which means they should be scheduled.  I think if we are doing upgrades for analytics it might be good to know what the specific issues are -- be able to answer the question: why are we upgrading?  I don't think it's the best use of time unless we know what we are fixing by upgrading.

Also if we do decide to schedule any type of maintenance on a server we should do the SSL-only security fix (nginx and SMSSync configuration updates).  This is the minimal update needed.

**Comment by btbonval** [comment]
Okay so this issue is mostly a reminder that I should create tickets in medic-projects for each system that needs an upgrade.

We are upgrading for each system necessarily other than to be at feature parity for when people tell me I'm doing it wrong.

I don't necessarily know the specifics of what feature each system needs, although the api thing would be applicable to all production systems below 4.5. I can write up that list no problem and include "no api" as the reason.

We still haven't nailed down the version(s) where `include_docs=true` is implied for #1319 , because that's another missing feature we'd be upgrading for.

**Comment by btbonval** [comment]
All prod systems have been updated since this last comment. Closing ticket.
