### ISSUE TITLE
Provide an easy way to get version information

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1322]
We should make it easy to collect version information on an installation to help debug issues. `/api/info` currently returns the version of medic-api but it's always `0.1.0` so not very informative. At a minimum return the version of medic-webapp and medic-os. It would also be useful to capture the versions of 3rd party libraries such as node, couchdb, java, etc.

Decide if this endpoint should be restricted (more secure) or open (easier to get to).

**Comment by browndav** [comment]
+1 here. Concierge speaks the same API (so it works before anything is configured), and the Node API would be able to pretty easily grab any file-based information being kept by Medic OS.

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1250

**Comment by SCdF** [comment]
@mandric please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by mandric** [comment]
Should we close this?

**Comment by garethbowen** [comment]
Closing - let's do it when we have a use for it.
