### ISSUE TITLE
Enketo: Mixed/online-required content in geolocation map widget

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1326]
The Enketo lat/long geolocation widget appears to request external OpenStreetMap assets. Two problems: (i) the requests are HTTP, which causes a mixed-content issue when the app is served over HTTPS; and (ii) the requests require internet access, while the app may be offline.

I propose we solve all of these problems by just removing the map portion, and displaying a single "capture location" button or similar.

**Comment by mandric** [comment]
Adding a bit more info here... seeing this on lg.dev simply by opening a task.

```
Mixed Content: The page at 'https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/tasks/4165F54A-97A7-F23C-9727-BADEDDB6721C-register-pregnancy' was loaded over HTTPS, but requested an insecure image 'http://c.tile.openstreetmap.se/hydda/full/1/1/1.png'. This content should also be served over HTTPS.
(index):1 
```

**Comment by browndav** [comment]
The map shouldn't show up on the mobile device, so we've deprioritized the desktop part of this IIRC.
