### ISSUE TITLE
Enketo: Scroll to top when replacing a rendered DOM subtree with another

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1327]
On this week's iteration call, we identified a scenario in which navigating between pages of a form leads to a page being displayed with a non-zero scroll offset. Patch Enketo so that new forms always reset the container's scroll offset to zero (the top).

**Comment by alxndrsn** [comment]
This is `select2` fault - see "bugfix" in `db-object-widget` and `medic-place-widget`.

**Comment by alxndrsn** [comment]
Should already work - https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L422

**Comment by browndav** [comment]
The route to fixing this is probably similar to #1217.

**Comment by alxndrsn** [comment]
Looking like a bug in Enketo's `Form.focusOnFirstQuestion()` method.

**Comment by alxndrsn** [comment]
...a couple of bugs, perhaps.  Filed at: https://github.com/enketo/enketo-core/issues/329, https://github.com/enketo/enketo-core/issues/331; I will port them to our fork now.
