### ISSUE TITLE
Enketo: Display something in the UI if form initialization fails

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1328]
If a malformed or otherwise misconfigured form is added to the system, we should display an error when a user attempts to use it. Currently, clicking straight through a form that fails initialization will create no record and display no error.

**Comment by garethbowen** [comment]
This was added at some point. Now if I upload an invalid xml doc I get a stack trace in the console, and the user sees this:

![form-loading-error](https://cloud.githubusercontent.com/assets/2064938/10808593/1a0ebaba-7e52-11e5-8eb6-f04c3553dc5d.png)

**Comment by abbyad** [comment]
Moving to Ready.
