### ISSUE TITLE
Post-deployment change control and/or versioning for forms

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1329]
Eventually, partners will want to make changes to forms (first priority: Enketo) that add or change fields. They'll want to start using these forms for new data, preserve existing data, and have the ability to manually backfill the new fields in older records using existing user interfaces.

This issue is a placeholder for efforts toward form versioning and support for post-deployment form modifications.

@abbyad: Can we add this to the list for the quarterly and/or monthly prioritization call if it isn't already in there?

**Comment by garethbowen** [comment]
This is also important for the postgres adapter to be able to access historical versions of forms.

**Comment by btbonval** [comment]
+1 above. Really it's great for any kind of post-hoc data quality analysis, but in particular the postgres adapter could make good use.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
couch2pg has been refactored a bunch since this issue was filed. Closing. @michaelkohn please re-open if this is still needed.

**Comment by michaelkohn** [comment]
hi frand @sglangevin, thanks for thinking of analytics.  You are correct... the newer version of `couch2pg` doesn't rely on the form version to parse the data, and we generally hand-write our views, so I don't think this is critical from an analytics perspective.
