### ISSUE TITLE
Provide a user interface for uploading/managing Enketo forms

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1330]
We have an interface for uploading a set of JSON forms and replacing the existing forms. We don't yet have an equivalent or workalike interface for Enketo forms. Design, build, and ship an interface that works for adding/replacing Enketo forms.

**Comment by garethbowen** [comment]
Adding some key words: configuration settings xml xform

**Comment by garethbowen** [comment]
Related: https://github.com/medic/medic-webapp/issues/1330

**Comment by abbyad** [comment]
We should consider accepting the xlsform directly.

**Comment by alxndrsn** [comment]
@bishwas-medic with your upcoming work with enketo forms, please decide if this feature is useful.  If so, we should schedule this ticket; if not, we should close it.

**Comment by sglangevin** [comment]
This would need to be considered with many other issues if we are thinking about going ahead. We have a number of partners who are interested in this feature but we may not be able to get to it immediately as we have quite a number of other needs for projects.

**Comment by bishwas-medic** [comment]
While it will not greatly effect my upcoming tasks, I think this feature is pretty important for users of all level in the long run. And like Sharon mentioned, we already have few partners with their that are interested in building and uploading the forms on their own.

**Comment by sglangevin** [comment]
Yeah, I agree it's important. It is on the list of items that we want to work on this year already and I'll keep in mind that you are also interested in implementing it. For now, we also have other things that are pressing that we need to focus on, so I'd prefer that we put this one off until a bit later in the year.

**Comment by alxndrsn** [comment]
@garethbowen can this be marked **`Done`**?

**Comment by garethbowen** [comment]
I think so. There are many improvements that can be made but these can be done as separate issues. Flagging for AT.
