### ISSUE TITLE
Make it easy to add translation keys

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1333]
Currently we provide all the keys for known translations and provide a nice configuration page for changing the values for these keys.

However we frequently allow configuration of screen elements which should be internationalised, for example form titles, form fields, scheduled messages, auto replies, etc. In these cases we have configuration which includes all values, for example:

```js
"messages": [
    {
        "message": [
            {
                "content": "Please remind {{patient_name}} ({{patient_id}}) to visit health facility for ANC visit this week. When she does let us know with 'V {{patient_id}}'. Thanks!",
                "locale": "en"
            },
            {
                "content": "Tafadhali mkumbushe {{patient_name}} ({{patient_id}}) ahudhurie kliniki kwa ANC wiki hii. Akishafanya hivyo tujulishe na 'V {{patient_id}}'. Asante!",
                "locale": "sw"
            },
            ...
        ],
        "group": 1,
        "offset": "12 weeks",
        "send_day": "monday",
        "send_time": "09:00",
        "recipient": "reporting_unit"
    },
    ...
}
```
This means we have two ways of configuring translations and have to provide complicated configuration pages which mix localisations in with configuration.

Provide a way to add keys to the set of translations so the configuration can reference a key rather than an array of translations.

**Comment by garethbowen** [comment]
Fixed as part of #1706

**Comment by estellecomment** [comment]
@garethbowen What work was done here specifically? cc @ngaruko

**Comment by garethbowen** [comment]
@estellecomment @ngaruko It is now possible to add new translations through the Configuration > Languages > Application Text page. Clicking the "Add translation" button launches a dialog. This is particularly useful when you've configured something that needs translation, for example, form field labels.

**Comment by estellecomment** [comment]
@garethbowen What file does that add to? (I guess I could just read the code :P)

**Comment by garethbowen** [comment]
There are `type: "translations"` docs in the db.
