### ISSUE TITLE
Enketo: Xpath expression evaluation errors

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1334]
Some xforms that work with Enketo proper produce errors within the webapp.

We should correct or document differences between the two environments. 

Some of the differences I have noticed so far:

1. round() taking 1 vs 2 arguments
1. now() gives epoch time, today() gives string date, but should be string for both as per [spec](http://opendatakit.github.io/odk-xform-spec/), although the differentiation here may be beneficial
1. in medic, some valid conditions are not expanded properly eg `(A or B) and C` style conditions produce errors

The last one is the highest priority right now because long calculations can be expanded to be valid, but are much less readable and maintainable.

**Comment by browndav** [comment]
Here's a quick example of one of the `A and (B or C)` expression evaluation failures:

```
Error occurred trying to evaluate: /model/instance[1]/treatments/group_cough/patient_coughs ='yes'and  /model/instance[1]/treatments/group_breathing/fast_breathing ='no' and (selected( /model/instance[1]/treatments/group_cough/coughing_duration , 'Less than a week') or selected( /model/instance[1]/treatments/group_cough/coughing_duration , '1 Week')), message:  [stack=[{"t":"root","tokens":[{"t":"bool","v":false},{"t":"&"}]}]] [cur={"t":"?","v":""}]
```

**Comment by alxndrsn** [comment]
`now()` vs `today()` - would be worth checking exactly what `medic-collect` does with these two, as the OpenRosa documentation reads as follows:
> `today()		` return today's date
> `now()	` return a timestamp for this instant
> — _https://bitbucket.org/javarosa/javarosa/wiki/xform_

**Comment by alxndrsn** [comment]
Round is not working as expected because it's currently not implemented as an openrosa extension - there is also a [`round()` method defined in the XPath specification](http://www.w3.org/TR/xpath/#function-round), which only takes a single argument.

**Comment by alxndrsn** [comment]
Hi @abbyad how are you currently expanding `(A or B) and C` so that it parses successfully?

**Comment by alxndrsn** [comment]
*1* and *3* should be fixed; please test.  If work needs doing on *2*, please state what is expected.

**Comment by abbyad** [comment]
Thanks @alxndrsn, both 1 and 3 work well now.

As for today() vs now(), I see the two links you provided conflicting with each other,  not agreeing: 

> today()		return today's date
> now()		return a timestamp for this instant
https://bitbucket.org/javarosa/javarosa/wiki/xform

> today()	Returns today’s datetime as a string [review]
> now()	same as today() [review]
https://opendatakit.github.io/odk-xform-spec/

I think we are OK leaving it the way it is implemented now, especially given that the second is under review. 

It would be helpful to document the conflicting definition and state the one we've chosen. @alxndrsn do you have place where you are already documenting this, perhaps in https://github.com/alxndrsn/openrosa-xpath-evaluator?

**Comment by alxndrsn** [comment]
Clearest info on what is implemented is here: https://github.com/alxndrsn/openrosa-xpath-evaluator/blob/master/test/integration.spec.js.  Should we aim to follow ODK Collect's implementation?  If that's the case, we should probably port their unit tests and rely on the content of the code rather than the docs.
