### ISSUE TITLE
Search in medicPersonSelect does not yield result

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1336]
Using the search in patient select does not yield any result:

![image](https://cloud.githubusercontent.com/assets/789512/10126008/c43279b6-6555-11e5-9581-8d6cb719daec.png)

![image](https://cloud.githubusercontent.com/assets/789512/10126013/ce92e6b6-6555-11e5-9b36-1374effcb160.png)

I tried search for that known contact using the place name, contact name and even ID number but none yielded a result.

Using 0.6.0-alpha.1966

**Comment by garethbowen** [comment]
I think we should only fetch items when the user opens the element, or possibly when they start typing. It's a little more tricky to provide a query function now that the select element is generic.

**Comment by garethbowen** [comment]
Loading the items when opened also fixes part of #1324

**Comment by abbyad** [comment]
Tested on 3084 and works well, moving to Ready.
