### ISSUE TITLE
Grey bar showing on right pane

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1338]
Grey bar showing on the Contacts tab:
![image](https://cloud.githubusercontent.com/assets/789512/10137138/1713ee4c-65c6-11e5-9a90-d1b77744ad35.png)

Seems to show properly on Reports tab:
![image](https://cloud.githubusercontent.com/assets/789512/10137053/a4977aa0-65c5-11e5-9d93-f14622b8a3a9.png)

**Comment by garethbowen** [comment]
@abbyad Are you ok with the grey below the form or should that be white too?
