### ISSUE TITLE
create ANC calculations in postgres

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1339]
Take the middleware calculations for `ANCR manip v2` and make sure the most relevant calculations are handled.

Reviewing the fields, these pop out as useful:
* Real Registry [not applicable for HealthRight ANC unfortunately]. generalize to "Valid?"
* Conception date
* weeks since conception [is this used anywhere anymore? is this worth calculating as part of a view?]
* EDD
* MDD
* ADD
* still pregnant / child likely born

It might be worth breaking these into separate views like:
* metadata
* Current state
* Projection/delivery

Metadata would primarily contain whether a ANC registry form is valid. Other views could filter for only valid registries, which will cut down on some of the data parsing in useful ways the current middleware does not.

**Comment by btbonval** [comment]
It might be worth combining this with the task of importing ANC Monthly Impact Metrics, since these are all primarily calculations for that. Unfortunately these are also intermediary for klipfolio, and I don't know which fields are used there.

**Comment by btbonval** [comment]
It has been confirmed that dashboards will always require some level of customization in the middleware (Apps Script at present, postgres in the future). I won't know what intermediary calculations still make sense without starting from the goal: monthly and individual metrics.

I have a document which should help with the monthly requirements for guidance.

**Comment by btbonval** [comment]
This is basically done.

The ticket grew in scope to include common manipulations (used by dashboard and by impact calcs) as well as the impact metrics themselves. It also grew to contain CHW calculations, which only apply to ANC and were a bit intertwined for HealthRight. It also grew to contain defining variables, since many calculations (like early registrations) need to know how many weeks since LMP is considered "early". However, this is all pretty much done. There are a few leftovers from CHW to finish up, but anything missing will get found and solved when putting this data into Klipfolio.

**Comment by mandric** [comment]
Would be great if we could find time to do a code review and maybe a call on this.

**Comment by btbonval** [comment]
@mandric Sure I'm happy to go over this or anything I've done, but who would the audience be? This sort of work seems generally more interesting to tech leads. It sounds like you'd be interested, but I'm not sure if other developers would care what I've done here.

**Comment by btbonval** [comment]
Actually the DIY folks might also be interested in a call covering this material.

**Comment by mandric** [comment]
Sounds to me like this is the basis for our analytics platform and the dev team should be aware of how it works, what it solves or the basic design and future plans for it.

**Comment by sglangevin** [comment]
@btbonval if there is a call, I'd be interested in listening in to learn more about how it all works too. We have built-in analytics for the DIY platform, but those widgets are based on dashboards originally designed in Klipfolio. I've been trying to stay up to date with Amanda on the kinds of calculations you're doing but it would be great to learn more!

**Comment by btbonval** [comment]
@sglangevin Yeah, I really think it'd be great for us to synchronize our efforts at some point. Of course we need to have postgres on the medic-os image for DIY before much collaboration can take place, but once we're there, many of the dashboard calculations will be accessible locally through postgres.
