### ISSUE TITLE
Enketo: now() and today() give different results, specification says they should return identically-formatted results

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1340]
The Openrosa specification lists `now()` as being "same as `today()`", but currently one of them returns a Unix epoch timestamp and one returns a Gregorian-formatted date/timestamp. These functions should both return strings that are encoded in the same way. If we need a Unix-style timestamp, we should probably extend the API in a way that doesn't conflict with existing functions.

Split off from #1334, which was moved to Ready with to-do list item #2 still remaining.

**Comment by alxndrsn** [comment]
`now()` vs `today()` - would be worth checking exactly what `medic-collect` does with these two, as the OpenRosa documentation, and ODK's own documentation in another location, read as follows:
> `today()		` return today's date
> `now()	` return a timestamp for this instant
> — _https://bitbucket.org/javarosa/javarosa/wiki/xform_
> — _https://opendatakit.github.io/odk-xform-spec/_

As @abbyad notes, there's not really any benefit to having two identical functions!

**Comment by abbyad** [comment]
Clarifying that the two sources have conflicting specs:

> today() return today's date
> now() return a timestamp for this instant
> https://bitbucket.org/javarosa/javarosa/wiki/xform

> today() Returns today’s datetime as a string [review]
> now() same as today() [review]
> https://opendatakit.github.io/odk-xform-spec/

I will take a look at medic-collect and report back.

**Comment by browndav** [comment]
Sorry, the issue description is lacking a little. IMO they should probably just be explicit in the spec about how the date (for `today()`) and timestamp (for `now()`) are encoded.

**Comment by alxndrsn** [comment]
# Implementations

## Javarosa

### org.javarosa.xpath.expr.XPathFuncExpr
> ```java
import java.util.Date;
...
if (name.equals("today") && args.length == 0) {
	return DateUtils.roundDate(new Date());
} else if (name.equals("now") && args.length == 0) {
	return new Date();
}
```
> — _https://bitbucket.org/javarosa/javarosa/src/8acbd7900f03e554dd49513c28764377a7e0f958/core/src/org/javarosa/xpath/expr/XPathFuncExpr.java?at=default&fileviewer=file-view-default#XPathFuncExpr.java-175_

### org.javarosa.core.model.utils.DateUtils
> ```java
import java.util.Date;
...
public static Date roundDate (Date d) {
	DateFields f = getFields(d);
	return getDate(f.year, f.month, f.day);
}
```
> — _https://bitbucket.org/javarosa/javarosa/src/8acbd7900f03e554dd49513c28764377a7e0f958/core/src/org/javarosa/core/model/utils/DateUtils.java_

### java.util.Date
> Allocates a Date object and initializes it so that it represents midnight, local time, at the beginning of the day specified by the year, month, and date arguments.
>
> Parameters:
>     year - the year minus 1900.
>     month - the month between 0-11.
>     date - the day of the month between 1-31.
> — _https://docs.oracle.com/javase/7/docs/api/java/util/Date.html#Date%28int,%20int,%20int%29_

## Enketo
### engine.js
> ```javascript
today: ... function() {
	var today = new Date();
	return new DateType(
			new Date(today.getFullYear(), today.getMonth(), today.getDate()));
},
now:
	/**
	 * The now function returns the date in seconds between now and the epoch.
	 * 
	 * @see https://bitbucket.org/javarosa/javarosa/wiki/xform-jr-compat
	 * @return {NumberType}
	 */
... function() {
	return new DateType(new Date());
},
```
> — _https://github.com/enketo/enketo-xpathjs/blob/master/src/engine.js#L4449_

### Date (javascript)
> Note: Where Date is called as a constructor with more than one argument, the specifed arguments represent local time. If UTC is desired, use new Date(Date.UTC(...)) with the same arguments.
>
> If at least two arguments are supplied, missing arguments are either set to 1 (if day is missing) or 0 for all others.
>
> — _https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date_

# Conclusions

The two implementations above seem to follow each other closely.  However, in javarosa, dates are UTC; whereas in enketo, dates are local.  It's not obvious if this is deliberate, as the document linked in the enketo comment is not available.

We should update our implementation as follows:
* `now()` and `today()` should both return a `date` type
* `now()` should return the current date & time
* `today()` should return today's date, at midnight at the start of the day

It should be noted that this implementation disobeys one of the specs (the one at https://opendatakit.github.io/odk-xform-spec/), but sounds logical.

**Comment by abbyad** [comment]
Moving out of Acceptance Testing as this conversation is now superseded by https://github.com/medic/medic-webapp/issues/1878
