### ISSUE TITLE
[tasks] Group reports based on Person ID or Place ID

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1344]
In the task-generator, reports related to the same person are grouped based on the generated `patient_id` field. With the new contacts in v0.6, we are moving away from the patient_id and have a unique ID for each person/place (ie `_id`). We therefore need to group all reports based on that contact's ID.

**Comment by garethbowen** [comment]
Grouping is now done by generated fields (`doc.patient_id` and `doc.place_id`) and supplied fields (`doc.fields.patient_id` and `doc.fields.place_id`).
