### ISSUE TITLE
Make it easier to generate tasks for subsequent pregnancies

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1346]
With the current task rules for ANC, visits for a previous pregnancy prevent tasks for future pregnancies from firing. We need to determine the best way to avoid this scenario in future configurations.

**Comment by garethbowen** [comment]
This is an issue now because reports used to refer to a unique pregnancy id but now refer to a contact id which is shared between subsequent pregnancies. It would be worth investigating other areas of the system to ensure we're not making the assumption anywhere else.
