### ISSUE TITLE
On deleting a contact, URL is not updated

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1348]
# Steps to recreate
1. select a contact
2. observe that the URL now contains the contact's ID
3. delete the contact
2. observe that the URL now contains the contact's ID

# Expected behaviour
URL should update to `/contacts/` when the view is returned to the list of contacts.

**Comment by alxndrsn** [comment]
Code looks good!  There's an unresolved TODO; is that deliberate?  Also please squash your commits to a single one - 9 commits seems a lot for 9 lines of code :p

**Comment by alxndrsn** [comment]
Also, these 2 look equivalent to me, could you check?

**Old**
```js
-            pane.done(translateFilter('Error deleting document'), err);
```
**New**
```js
+            if (err) {
+              pane.done(translateFilter('Error deleting document'), err);
+              return;
+            }
+            pane.done();
```

**Comment by estellecomment** [comment]
they are equivalent, but there's the additional statement underneath, $state.go, which is run if no err.

**Comment by estellecomment** [comment]
Ignore the first PR it's a giant mess. The second one is much cleaner.

**Comment by alxndrsn** [comment]
Comments inline at https://github.com/medic/medic-webapp/pull/1803/files

**Comment by alxndrsn** [comment]
Also the tests are broken - might need to rebase against `develop`?

**Comment by alxndrsn** [comment]
LGTM!
