### ISSUE TITLE
Something is swallowing calls to `console.error()` 

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1351]
# Steps to reproduce
1. open a new browser tab pointed at `medic-webapp`
1. open the javascript console
1. make a call to `console.error()`, e.g. `console.error('is anybody there???')`
1. observe that no message is displayed on the console
1. open another tab, but don't browse to `medic-webapp`
1. make a call to `console.error()`, e.g. `console.error('is anybody there???')`
1. observe that message is displayed on the console (you still won't get an answer though)

**Comment by alxndrsn** [comment]
In the meantime, you can 'fix' it like this:
```
console.error = function() { var args = arguments.slice(0); args.unshift('ERROR'); console.log.apply(console, args); }
```

**Comment by garethbowen** [comment]
It works for me. Maybe it matters where you put the log statement?

We do mess with the console functions so we can capture any errors so it could be that this is broken: https://github.com/medic/medic-webapp/blob/develop/packages/feedback/feedback.js

**Comment by alxndrsn** [comment]
Haven't suffered this in a while.
