### ISSUE TITLE
Document medic specific XForm functionality

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1355]
We should document all the new or different functionality now available to Enketo XForms in the webapp.

**Comment by abbyad** [comment]
An example is showing drop downs with contacts from the db, now possible with field type="db:person", and appearance="db-object"

**Comment by SCdF** [comment]
@estellecomment please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by estellecomment** [comment]
Setting this as `Scheduled`, it's still relevant.

**Comment by sglangevin** [comment]
This is definitely still relevant. I'm happy to help with some documentation. @abbyad are you willing to pitch in as well?

**Comment by abbyad** [comment]
Closing now that forms are documented [here](https://github.com/medic/medic-docs/blob/master/configuration/forms.md#xforms) and [here](https://github.com/medic/medic-docs/blob/master/configuration/OVERVIEW.md#app-forms-).
