### ISSUE TITLE
Helpful error message not shown if no contact associated with current user when trying to Submit a Report

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1359]
# Observed behaviour

When attempting to _Submit Report_ when there is no contact assigned to the current user, the form fails to load:

<img width="520" alt="screen shot 2015-10-01 at 10 30 09" src="https://cloud.githubusercontent.com/assets/191496/10216183/6cb91026-6827-11e5-9d44-85c6beb0524c.png">

Checking the console reveals this message:

> `Error loading form Error: Your user does not have an associated contact. Talk to your administrator to 
> correct this.`
# Expected behaviour

The helpful descriptive error message prompting the user to contact their administrator should probably be in a modal, or the main pane.  The current error message suggests the user 'try again', which isn't going to work!
# Steps to recreate
1. go to _Configuration_ > _Users_ 
2. click on the current user
3. wait for the modal to open
4. if the **Associated Contact** field has a value, execute the following in your JS console: `$('input[name=contact][type=hidden]').select2('val', '')`
5. click _Submit_
6. browse to _Contacts_ tab
7. select a Person contact
8. in the _Submit Report_ section, click on a report link

**Comment by garethbowen** [comment]
Back to you @rmhowe

**Comment by rmhowe** [comment]
Thanks @garethbowen, would appreciate a quick re-review when possible

**Comment by garethbowen** [comment]
Nice one @rmhowe . Moving to AT!

**Comment by garethbowen** [comment]
Here's the commit: https://github.com/medic/medic-webapp/commit/d34cfb50f209e22e53116561f71eadbebbd285c9

**Comment by ngaruko** [comment]
LGTM
