### ISSUE TITLE
remove unused packages/showdown lib 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1361]
99% sure it's not used on the backend but just confirm how it's referenced on the ddoc.

**Comment by mandric** [comment]
Actually still used here in configuration workflow: 
https://github.com/medic/medic-webapp/blob/develop/lib/show-includes/configuration.js#L6
https://github.com/medic/medic-webapp/blob/develop/lib/show-includes/configuration.js#L32

**Comment by garethbowen** [comment]
Once we convert that schedules page over to angular there will be a bunch of libraries which we can remove.

**Comment by garethbowen** [comment]
This work was done in #1861
