### ISSUE TITLE
hotdogs menu changes when viewing schedules configuration

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1362]
Navigate to Configuration > Schedules then render dropdown menu.

![screen shot 2015-10-01 at 10 20 04 am](https://cloud.githubusercontent.com/assets/25641/10221686/2fec677a-6826-11e5-86bd-4e8ff1917fb8.png)

**Comment by abbyad** [comment]
Just an FYI that the Configuration>Schedules page is still using our old UI until we implement the updated Workflow mockups.

**Comment by garethbowen** [comment]
This was an attempt to save the effort of copying all of the menu items over into kanso. I had hoped at the time (and still do) that this final kanso page will soon be converted or replaced.

**Comment by mandric** [comment]
Is there an issue for replacing this last page?

**Comment by abbyad** [comment]
It was part of the v4 UI refactor (#712, #737, #738). We have mockups for the Schedule page as a new "Workflow" configuration, but we will want to revisit these to consider the new task schedules.

**Comment by garethbowen** [comment]
This page has been deleted in #1861
