### ISSUE TITLE
Store the creation time with the contact

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1365]
We want to have tasks show based on when a contact was created. For instance, a survey needs to be added to the contact every six months. We can show a task do so for all contacts that do not have a survey, but that task is shown indefinitely since we don't have a time value to base it on.

So far this is relatively low priority, just identifying it since it would be preferable to be able to show these tasks for a limited amount of time - and/or show a higher priority task as time goes on.

Tasks based on reports use the `reported_date` for the same purpose.

**Comment by alxndrsn** [comment]
:+1:

**Comment by abbyad** [comment]
Works well, moving to ready.
