### ISSUE TITLE
Task due date should have daily granularity

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1369]
When displaying a task's due date, show the day it is due, e.g.

10 days
3 days
1 day
Today
1 day ago
3 days ago

Most tasks won't be displayed until 7 days prior to the due date, so daily granularity should work.

Currently, we show more granular times for when tasks are due, e.g. "a few seconds ago". This will be confusing for users. It also takes up valuable real estate in the task card, which presents important information to the user.

![screen shot 2015-10-02 at 5 33 24 pm](https://cloud.githubusercontent.com/assets/377216/10260548/960b9b64-692c-11e5-8fd1-b16eedbaab92.png)

**Comment by browndav** [comment]
Necessary for the Monday (2015-10-05) demo?

**Comment by joshnesbit** [comment]
Not necessary for Monday (2015-10-05) demo, but great to have before the field test begins in November.

**Comment by abbyad** [comment]
Works well with the changes. Moving to Ready.
