### ISSUE TITLE
Replicate reports submitted about contacts you can see

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1370]
As mentioned in #1341 reports aren't replicating as expected. The filtered replication checks to see if the contact who submitted the report is in your permission tree, so for example, a district manager can see reports submitted by all CHWs in their district. The problem is that if you are a CHW and a district manager files a report against one of your patients you won't be able to see it.

Change the filter to replicate reports that have a contact._id, patient_id, place_id, fields.patient_id, or fields.place_id in your hierarchy. This may require some data denormalisation.

**Comment by sglangevin** [comment]
This is no longer an issue - additional work was done related to this when replication depth was implemented.
