### ISSUE TITLE
LastPass reports login form as insecure

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1371]
# Firefox
<img width="1280" alt="screen shot 2015-10-05 at 10 48 26" src="https://cloud.githubusercontent.com/assets/191496/10276269/b0442e64-6b4e-11e5-8def-156997c9b2b3.png">

**Comment by garethbowen** [comment]
This only shows up an option is switched on in Settings > Advanced > Warn before filling insecure forms.
