### ISSUE TITLE
Look up Contact forms in `$scope.formDefinitions`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1376]
# Current behaviour

Currently we check in pouch to see if contact edit/create/edit-create forms are available.  This generates 404 errors on the console when the forms do not exist.

# Desired behaviour

Instead of checking in pouch to see if the forms exist, we should just look in `InboxCtrl`'s `$scope.formDefinitions` object, where a list of the available forms is cached.

**Comment by garethbowen** [comment]
Assigned back to Alex to look at making everything async to fix potential race condition.

**Comment by alxndrsn** [comment]
Good spot.  Should be sorted now.
