### ISSUE TITLE
remove title from New Family form

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1379]
# Observed
<img width="1280" alt="screen shot 2015-10-05 at 15 44 29" src="https://cloud.githubusercontent.com/assets/191496/10281917/0983e25c-6b78-11e5-848c-6f2b619cd388.png">

# Expected

This is not included in the generated forms, so should not be included in the supplied forms.  Subtitles look OK though.

**Comment by abbyad** [comment]
This works as long as the form is manually edited. We will need to revisit this if/when we accept generic XForms for Contact creation.
