### ISSUE TITLE
import messages into postgres for HealthRight in style similar to spreadsheets

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1382]
what it says on the tin.

**Comment by btbonval** [comment]
Need to extract messages for nearly missed visits.

It looks like any data_record that has no form property is a message, however that might be only part of the story. It looks like messages might also be embedded into forms under scheduled_tasks.

```
SELECT * FROM jsonb_each( (SELECT data->'scheduled_tasks' FROM nosql) );
ERROR:  more than one row returned by a subquery used as an expression
```

This is where we get the current message exports that are used in production systems:
https://github.com/medic/medic-webapp/blob/master/packages/kujua-sms/kujua-sms/lists.js#L162

**Comment by btbonval** [comment]
Fallback plan: modularize the list function which creates message exports and then call the module from couch2postgres during import to extract messages. Not there yet, but always good to have a plan B.

**Comment by btbonval** [comment]
`data_record`s which contain `sms_messages` are easy because there is only one message per doc, guaranteed, with no arrays to parse. Each row is one doc, and each doc is easily parsed in `SELECT`.

`data_record`s which contain `tasks` (and the others) become a challenge. Even with a single message in the array, the only way to parse the json array is with `jsonb_array_elements` and that can only run on a single json object. So if I restrict to a single message, `jsonb_array_elements` works fine to get results:
```
SELECT tasks         
FROM jsonb_array_elements( (
  SELECT data->'tasks'
  FROM nosql
  WHERE data ? 'tasks' AND jsonb_array_length(data->'tasks') > 0
  LIMIT 1
) ) AS tasks;
```

However, as soon as we try to process multiple docs (multiple rows) through `jsonb_array_elements`, an error arises:
```
SELECT tasks
FROM jsonb_array_elements( (
  SELECT data->'tasks'
  FROM nosql
  WHERE data ? 'tasks' AND jsonb_array_length(data->'tasks') > 0
  LIMIT 2
) ) AS tasks;
ERROR:  more than one row returned by a subquery used as an expression
```
I might be able to write a PL/pgsql function which runs a FOR loop over rows and then issues a single `jsonb_array_length` to each row. In this case, the results of the function might look and feel like a view (while not at all being a view). Might be worth caching results of this function in a table (and by cache, I mean directly output into a table).

**Comment by btbonval** [comment]
Slight amendment to the above: if 1 message is guaranteed per array, instead of `jsonb_array_elements`, one could simply use `(data->'name-of-list')->0` in `SELECT`. However, no such guarantee is made for any of these types. `sms_messages` doesn't have a list because one is not needed.

**Comment by btbonval** [comment]
`state_history` is going to be problematic. Rather than being a hashmap of `{state1:timestamp1, state2: timestamp2, ...}, it is a list of hashmaps `[ { "state":state1, "timestamp":timestamp1, "state":state2, "timestamp":timestamp2, ... } ]`.

Maybe it's possible for there to be multiple pending states, for example, but I'm not sure what the message's pending timestamp would be in that case. It looks like the list code does indeed build a more sensible `{state1: timestamp1}` dictionary. When doing so, an arbitrary timestamp is chosen (not even necessarily most recent):
https://github.com/medic/medic-webapp/blob/master/packages/kujua-sms/kujua-sms/lists.js#L261-L263

**Comment by btbonval** [comment]
Based on the above, I'm no longer convinced duplicating the logic for all of these edge cases in postgres is a worthwhile venture.

However, I also no longer think the couch2postgres adapter should be the place where message processing is done. couch2postgres is agnostic to the webapp version so far; it simply moves data from couch to postgres. Introducing this feature would change the assumption and require managing different versions of couch2postgres for different versions of the webapp (e.g. 0.4 vs 0.6).

@mandric had brought up an interesting concept that perhaps postgres can call an external program. Perhaps when updating views, one of the postgres functions could call out to an external Node program to process messages.

Alternatively, a separate message processing daemon would need to be managed independently (likel cronned).

**Comment by btbonval** [comment]
PL/pgsql does not support calling external programs.

PL/perl can if it is in unsafe mode. Interestingly, perl offers some kind of system message passing which can be used (even in safe mode). Someone conceived of a solution where a PL/perl function triggers an external daemon (a perl script which listens for the trigger). Any other message passing is done via a table: PL/perl function writes/reads to some table, the perl daemon writes/reads the same table, and the trigger signals when these things should happen.
http://www.postgresql.org/message-id/758d5e7f0710050151v23e30a58yb89d8e1e4e533153@mail.gmail.com

Might be able to pull off something like that using unix signals in any of the langs like PL/perl or PL/python so long as they have access to unix signals in safe mode.

**Comment by mandric** [comment]
What about having some kind of import process that takes the messages export data as JSON (we'd need to add this feature) and creates documents out of them in postgres?  Each message has a uuid so they could use that as the ID of the document.

**Comment by btbonval** [comment]
@mandric it could probably be done that way, but seems to circumvent the point of getting the raw data.

I think it might be good to take a step back and figure out _why_ the message exports are needed in that particular form. I had been systematically converting everything to look and feel like the Google Spreadsheets, and I cannot do so with the messages. But I personally have done no calculations with messages. If I find out what is meant to be done, it's possible I can implement that without using any message export at all. Extracting messages is hard, but I think searching them is easier depending on what is needed.

**Comment by btbonval** [comment]
After discussing this with @yembrick , we're happy to omit the calculations which use messages. It seems these metrics are meant to be more actively utilized, whereas our legacy systems aren't being all that actively utilized.

This issue might come back from the dead if 0.5 exists and we ship postgres with that. For 0.6, I suspect the nools exported messages will be trivial to parse.
