### ISSUE TITLE
Reorder Tabs

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1385]
Based on feedback from @joshnesbit, we want to reorder the top level tabs so that they show as:
Tasks, Contacts, Targets

**Comment by alxndrsn** [comment]
@abbyad not sure what to do - this is my current top-level tabs:

<img width="471" alt="screen shot 2015-10-05 at 18 44 55" src="https://cloud.githubusercontent.com/assets/191496/10287045/3ace1ba2-6b91-11e5-8400-92bc62ce8ef9.png">

**Comment by abbyad** [comment]
Sorry, I was using project-specific terminology... The only change needed is to swap Contacts and Analytics positions.

**Comment by abbyad** [comment]
Moving to Ready.
