### ISSUE TITLE
Hide the Clinic field in the Add Person form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1386]
For CHWs the Add Person form is only accessible under a Family's profile page. This makes it unnecessary and confusing to show the "clinic" select2. We should hide this field for CHWs.

We need to consider what this means for Admins that can still use the similar form from the left pane.

**Comment by alxndrsn** [comment]
@abbyad admins can't use the Add Person form from the left pane.

**Comment by abbyad** [comment]
That simplifies it if no one can "Add Person" from the left pane. In that case we should just hide that clinic field.
