### ISSUE TITLE
Modem stops responding to messages & reports after 30 mins

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1388]
When I leave Medic Mobile running with a modem plugged in, it stops responding after about 30 minutes. It doesn't matter whether or not someone is using the computer in that time, I see the same behavior either way. I also noticed that if I leave the modem plugged in to the point that it stops responding, if I turn Medic Mobile OFF then turn it ON then it starts sending and receiving messages again. There was also one time where I left the modem plugged in and computer on for a few days while I was out of the office. When I got back, the messages that were sent in the interim downloaded into Medic Mobile. Another time I left the computer off and messages that were sent did not get downloaded into Medic Mobile when I started the computer up again (both of these cases were over 3-4 days).

I sent my server logs and user feedback to @browndav. Audit logs couldn't be downloaded because there is a message with an emoji somewhere in there that is breaking the download. See #1389 for more on that.

**Comment by browndav** [comment]
This has been deprioritized for Q1/Q2 2017 at a high level. Closing as ancient.
