### ISSUE TITLE
Audit logs can't be downloaded

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1389]
My audit logs won't download because there is a special character in on of the text messages (an emoji). Here is the error message that I got: 
[audit_logs_error_message.txt](https://github.com/medic/medic-webapp/files/7904/audit_logs_error_message.txt)

**Comment by mandric** [comment]
Sharon, if you tried to attach a debug file I think it failed.  Maybe copy/paste the error message here.

**Comment by sglangevin** [comment]
Server error: Invalid character (�) in string: {"_id":"b9f0362817c1b6e8e1cba4193114b823","_rev":"3-6ea37bfcf2e74af235ed998460a004f8","type":"data_record","from":"+12516801299","errors":[],"tasks":[{"messages":[{"to":"+12516801299","message":"SMS message received; it will be reviewed shortly. If you were trying to submit a text form, please enter a correct form code and try again.","uuid":"87ad4b84-fe0e-4656-acd5-b980284f24fe"}],"state":"pending","state_history":[{"state":"pending","timestamp":"2015-09-03T22:13:07.249Z"}]}],"fields":{},"reported_date":1441318386000,"sms_message":{"message":"😎😎😎","from":"+12516801299","sent_timestamp":"2015-09-03T22:13:06+00:00","type":"sms_message","form":"😎😎😎","locale":"en"},"transitions":{"default_responses":{"last_rev":2,"seq":146,"ok":true},"update_sent_by":{"last_rev":2,"seq":146,"ok":true},"update_clinics":{"last_rev":2,"seq":146,"ok":true}},"sent_by":"Rebecca Willett","contact":{"_id":"b9f0362817c1b6e8e1cba419310b9064","_rev":"2-22f87c58b314a4d96c5eecf9bd7d0742","type":"person","name":"Rebecca Willett","phone":"+12516801299","parent":{"type":"clinic","name":"SoMa","parent":{"_id":"b9f0362817c1b6e8e1cba41931093626","_rev":"2-dc0bcf111d1c325553207036796e49f2","type":"health_center","name":"San Francisco","parent":{"_id":"b9f0362817c1b6e8e1cba4193108a8ab","_rev":"1-99925755353f19f03d71926bf9150806","type":"district_hospital","name":"United States","parent":null},"contact":{"_id":"b9f0362817c1b6e8e1cba4193108fe49","_rev":"2-c7de132d92971f0f5f63055a3cd4fc40","type":"person","name":"Sharon Langevin","phone":"+12032142711"}},"contact":{"type":"person","name":"Rebecca Willett","phone":"+12516801299","_id":"b9f0362817c1b6e8e1cba419310b9064","_rev":"1-299e167f5f2cde07e17de8d1ba2cbff9"},"_id":"b9f0362817c1b6e8e1cba419310bc0d9","_rev":"1-c3bdb0eb2890ca377b49b2b429138136"}}} at index 550

**Comment by garethbowen** [comment]
API error:

```
Server error: 
  detail: Error: Invalid character (�) in string: {"errors":[],"form":null,"reported_date":1445221782679,"tasks":[{"messages":[{"sent_by":"gareth","to":"+64274622636","contact":{"_id":"1E22F57F-5A9A-B6A6-8C56-F49E3810F893","_rev":"3-b897e6937efab99fd600bacc7e72a67f","type":"person","name":"Gareth","phone":"+64274622636","children":[],"contactFor":[]},"message":"😎😎😎","uuid":"ca5c6cbdbe611744ffd9c982fb4537a1medic"}],"state":"pending","state_history":[{"state":"pending","timestamp":"2015-10-19T02:29:42.750Z"}]}],"read":["gareth"],"kujua_message":true,"type":"data_record","sent_by":"gareth","_id":"D84A057D-CF9A-08BB-ACF0-C11AEF6B2E43","_rev":"current"} at index 314
    at XMLStringifier.module.exports.XMLStringifier.assertLegalChar (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLStringifier.js:150:15)
    at XMLStringifier.assertLegalChar (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLStringifier.js:4:59)
    at XMLStringifier.module.exports.XMLStringifier.eleText (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLStringifier.js:27:19)
    at new XMLText (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLText.js:19:35)
    at XMLElement.module.exports.XMLNode.text (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLNode.js:168:15)
    at XMLElement.module.exports.XMLNode.node (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLNode.js:160:15)
    at XMLElement.module.exports.XMLNode.element (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLNode.js:103:28)
    at XMLElement.module.exports.XMLNode.ele (/home/gareth/src/medic/medic-api/node_modules/xmlbuilder/lib/XMLNode.js:271:19)
    at /home/gareth/src/medic/medic-api/controllers/export-data.js:474:25
    at Array.forEach (native)
undefined
```

**Comment by mandric** [comment]
Assuming this also needs to be ported to master/testing?

**Comment by mandric** [comment]
Might make sense for me to do these bug fix ports.

**Comment by garethbowen** [comment]
Yeah it should be ported I guess. I tried to batch 0.4 issues together so it'd be easier to do, but it'll need to be cherry picked to testing and master.

**Comment by browndav** [comment]
Leaving open intentionally for port.

**Comment by garethbowen** [comment]
Assigning to @mandric for merging to testing and master.

**Comment by browndav** [comment]
Is there an update on this one? I'd like to close the previous milestone, and this is the last active-work issue left in there.

**Comment by mandric** [comment]
Not done.  Will get to it first thing tomorrow.

**Comment by mandric** [comment]
Should be fixed in DIY build 2357 or later.
