### ISSUE TITLE
502 error when clicking Open from the launchpad

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1390]
After starting up Medic Mobile, sometimes when I click Open from the launchpad without waiting long enough, I get a 502 error. The Open button seems to be directing me to a temporary IP address instead of medic.local (this is after I have already set up Medic Mobile and used it several times). The error is corrected if I wait a little longer before clicking Open or if I type medic.local into my browser after reaching the 502 error page.

**Comment by SCdF** [comment]
@estellecomment please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by estellecomment** [comment]
@sglangevin Was this from a local DIY install? Can you give more details on how you got there (if you remember)? Is this still relevant?

**Comment by sglangevin** [comment]
This was related to a local DIY install and isn't relevant anymore.

**Comment by estellecomment** [comment]
Ok. Closing. Thanks!
