### ISSUE TITLE
Cannot delete a person/place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1391]
For some places and people they delete button is disabled, even as admin.

**Comment by garethbowen** [comment]
The delete button is disabled if the contact has children or if the contact is a primary contact for a place. Is this what you expected? Can you find an example of a contact where the button is disabled when neither of these is true?

At the very least we should have some sort of hover message or even a click handler to explain why it's disabled.

**Comment by abbyad** [comment]
Ah OK, that makes more sense now... So you can't delete the person because they are the primary contact, and you can't delete the place because there is a person attached to it. How do you go about delete either then?

**Comment by garethbowen** [comment]
You'd have to edit the Place to have a different primary contact then delete the person, or edit the person to have a different parent and delete the place. It's not ideal but it's a workaround...

**Comment by browndav** [comment]
Closing.

**Comment by abbyad** [comment]
I think this is still an issue because a CHW cannot simply delete a family they created.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
@abbyad so it looks like no one cares about this?

@sglangevin has this come up in conversations with partners?

@diannakane how has this kind of thing factored into your designs recently?

IMO: close this, or move into the design queue to be got to when its got to.

**Comment by sglangevin** [comment]
This now works as I would expect it to - you can't delete places that contain people. You have to delete the people first, then you can delete the place. This is good because it prevents leaving orphaned contacts in the app.

**Comment by SCdF** [comment]
Yay! Closing.
