### ISSUE TITLE
tasks loading optimization, requesting redundant data 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1394]
Not sure why we need requests to _all_docs and contacts_by_name, both also have ?include_docs=true, which makes them heavy.  

Load tasks on alpha.dev as admin and view network debug panel:

![screen shot 2015-10-06 at 9 34 09 am](https://cloud.githubusercontent.com/assets/25641/10308672/d1488104-6c0d-11e5-990d-b2ccfb4bf049.png)

**Comment by mandric** [comment]
CORS is also not enabled yet on alpha.dev.

**Comment by garethbowen** [comment]
@mandric I think the key here is the word "may". I think PouchDB is overzealous and emits this warning too much. I think it only actually applies if there's an error emitted just before the warning. As long as everything's working ignore this warning for now.

**Comment by garethbowen** [comment]
To address the issue, we supply all contacts and records to the task generator to generate tasks. I can't think of any way to predetermine the relevant data.

The users who are most interested in the tasks tab are going to be restricted to a subset of contacts and reports, and they'll access from their local pouch so this shouldn't be too bad. We should consider what to do with admins - perhaps they should have a filter to select which CHPs tasks they want to see? Certainly showing all tasks will be too expensive and not very useful.

**Comment by mandric** [comment]
So CORS doesn't need to be enabled on couchdb for pouchdb to work properly? (notice this error was on alpha.dev)

**Comment by garethbowen** [comment]
I'm still unclear on whether or not CORS needs to be enabled in Couch. It's possible that proxying through api means it's considered a local replication. We should test this thoroughly as part of #1317

**Comment by mandric** [comment]
If there is no way straightforward way to consolidate the two requests (_all_docs and contacts_by_name) we can close this.

**Comment by garethbowen** [comment]
Duplicate of #1394
