### ISSUE TITLE
Pregnancies registered with LMP of 12, 24, 32, 36 miss a reminder message

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1396]
When a pregnancy is registered with an LMP date that falls exactly on the week that a visit reminder ("Please remind Jane to visit the clinic") is sent do not receive that reminder. They only receive a reminder that says ("Did Jane visit the clinic?"). This could be confusing for the CHW as they were never instructed to refer the patient to the clinic for ANC, only asked if the visit happened.

**Comment by abbyad** [comment]
@mandric: @sglangevin will ask for your help with the configuration to resolve this.

**Comment by mandric** [comment]
@sglangevin think I just reproduced this on demo.app https://demo.app.medicmobile.org/medic/_design/medic/_rewrite#/reports/5168815d16831617ae3161344cca433e

**Comment by mandric** [comment]
Isn't that just an artifact of the way the messages are grouped/designed/configured?  Can the problem be with creating a schedule where you expect all messages in a group to be sent?  With a schedule based on LMP the schedule can begin at any point right?  How would you expect it to behave?

**Comment by sglangevin** [comment]
@mandric the expected behavior would be to receive both messages from the group, even if the registration comes at 12, 24, 32, or 36 weeks, the weeks corresponding to the first message in the group. Is there a way to make sure that both messages in the group are sent that doesn't compromise clearing the follow-up message if a CHW responds to the first reminder in the group?

It would seem strange to only receive a message saying "Did Jane attend her ANC visit?" when I hadn't been told to remind her to go to the clinic yet. I'm around today so feel free to ping me if I'm not explaining well.

**Comment by mandric** [comment]
Guess what I'm wondering if it's possible to design the schedule messaging to deal with the fact that you don't know when the registration will happen.  So that each message communicates fully regardless whether or not the previous message has been sent.

**Comment by sglangevin** [comment]
So in the current schedule, let's say we have someone register with an LMP of 12. Because the first message in Group 1 was supposed to be sent at 12 weeks after LMP, Medic Mobile skips the message. If there is a way for Medic Mobile to send that message anyway, even though the registration might happen a few days after it was scheduled to be sent but within the 12th week, that would be great.

Since Mustache is logic-less, do you have any ideas on how we might accomplish this?

**Comment by mandric** [comment]
Not really, the schedule is generated based on LMP and the configured messages before the registration date are skipped since they are prior to the registration date.  I'm thinking it's probably easier to design something into the messaging to accomodate for this rather than expect to system to know when to schedule messages prior to the registration date?

**Comment by sglangevin** [comment]
@mandric and I agreed that since there isn't an easy way to infuse logic here that we will leave it as is for now and see if there is a way to accomplish this in the future.
