### ISSUE TITLE
Hide unnecessary Family profile fields

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1402]
Based on feedback from @joshnesbit we should hide the unnecessary fields from the profile pages since they can lead to confusion and make the important info less prominent.

### Family profile
Hide:
- [x] Name (already shown above) 
- [x] Location 
- [x] CHP Area 
- [x] Branch

![screen shot 2015-10-02 at 10 16 49](https://cloud.githubusercontent.com/assets/789512/10287995/3df9b7c8-6b64-11e5-9dfb-c94439cde75d.png)

-----
Split from #1387

**Comment by abbyad** [comment]
This worked well for the field test. Moving to Ready.
