### ISSUE TITLE
Ensure that updates reach the mobile app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1403]
The mobile app doesn't have a refresh button, so if a change listener is missing/broken the user would have a stale webapp. For instance, if a new form is added, the mobile app will not show it until you log back in or do a hard close on the app to force the refresh. 

We should make sure that all aspects of the app are pushed to the mobile app if there is an update. If we find that the update mechanisms fail then we should consider adding a refresh button hidden in the menu.

**Comment by garethbowen** [comment]
Definitely add a refresh button somewhere. Then add Changes listeners for...
[] The facilities - InboxCtrl $scope.facilities and the contact select around line 166
[] The read status - InboxCtrl $scope.readStatus
[] The forms - InboxCtrl $scope.forms and $scope.formDefinitions
[] The current user - InboxCtrl editUserModel

**Comment by garethbowen** [comment]
I've added a refresh button to the About (formerly Help) page, and added Changes listeners everywhere I could see they were needed. Unless I've missed something everything in the UI should now update without having to reload the page.
