### ISSUE TITLE
Display `horizontal` appearance for `select_one` fields

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1407]
In order to avoid having to scroll to see select one/multiple options, we want to use the `horizontal` appearance. It works in Enketo proper, but [not in our webapp](https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/add/AFAM).

### enketo
![image](https://cloud.githubusercontent.com/assets/789512/10355070/2139c86c-6d35-11e5-8c4f-c530162771c1.png)

### medic-webapp
![image](https://cloud.githubusercontent.com/assets/789512/10355146/603ec674-6d36-11e5-8a21-55647b02839c.png)

**Comment by alxndrsn** [comment]
What's the current behaviour in webapp?  Do you have an example form which should work but doesn't?

**Comment by abbyad** [comment]
Current behaviour in webapp is posted above, which is from `AFAM` on lg.dev

**Comment by alxndrsn** [comment]
Is the source for `AFAM` available?

**Comment by alxndrsn** [comment]
https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/add/AFAM

**Comment by alxndrsn** [comment]
@abbyad please let me know if we want `likert` support too.  At the moment that's not enabled.

**Comment by abbyad** [comment]
We aren't currently using it, but I suspect we might with branch forms in the future. If it is as simple to add as the above commit, then we may as well support it now.

**Comment by abbyad** [comment]
Works well, moving to Ready.

@alxndrsn following up on Likert... we are now at the point that it would be useful to have. Issue will likely be created if it isn't included.
