### ISSUE TITLE
[enketo] Note widget that accepts markup

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1414]
We want to show our result pages in the form in a more structured way. This would likely require some kind of font-styling, div or table structure, and background colors.

Here is examples of one of the result pages in the previous app:
![results screen in old app](https://cloud.githubusercontent.com/assets/789512/10377064/2fd18b40-6dcf-11e5-8458-41b5e44d09f4.png)
![scrolling down](https://cloud.githubusercontent.com/assets/789512/10377070/39119c72-6dcf-11e5-9e2c-99f3613cd849.png)

`<marquee>` is not _yet_ a requirement

**Comment by abbyad** [comment]
We should consider making the note field configurable with the appearance field (eg `appearance="html"`). This way we would not downgrade current notes using markdown.

**Comment by alxndrsn** [comment]
Implemented by allowing HTML in the node sections.  HTML should have special characters encoded, specifically:

char | escaped
---|---
> | &amp;gt;
< | &amp;lt;
& | &amp;amp;
" | &amp;quot;
' | &amp;#039;

This makes for some horrible XForms XML, but how horrible for end users this is depends on how XLSForms works:

```xml
<label>*The estimated delivery date is*
<output value=" /pregnancy/edd "/>

  &lt;table&gt; &lt;thead&gt; &lt;tr&gt; &lt;td&gt;col1&lt;/td&gt; &lt;td&gt;col2&lt;/td&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tdata&gt; &lt;tr&gt; &lt;td&gt;val1.1&lt;/td&gt; &lt;td&gt;val1.2&lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td&gt;val2.1&lt;/td&gt; &lt;td&gt;val2.2&lt;/td&gt; &lt;/tr&gt; &lt;/tdata&gt; &lt;/table&gt;
*Remind woman to*
1. Take Iron Folate daily
2. Attend regular ANC visits
...</label>
```

**Comment by browndav** [comment]
Is `<![CDATA[ ... ]]>` an option here for tidying up the XML-embedded-HTML?

**Comment by alxndrsn** [comment]
@browndav I have a hunch that XLSForms will do the dirty work for us, but if it doesn't then it should probably just be done in the XSL transform rather than wrapping in `CDATA`.

**Comment by browndav** [comment]
It'd be nice if the XML files we produced with XLSForm and/or manually (which, I'm assuming, we'll check in to source control and want to diff) were easily human-readable.

**Comment by abbyad** [comment]
### A XLSform with a note:
`<div style="width:100%; background:#ff0000; color:#0000ff">ID: ${patient_id}</div>`

### converted to this in XML:
`<label>&lt;div style=&quot;width:100%; background:#ff0000; color:#0000ff&quot;&gt;ID: <output value=" /pregnancy_follow_up/patient_id "/>&lt;/div&gt; ...`

### and rendered as:
![image](https://cloud.githubusercontent.com/assets/789512/10611919/635918ba-771c-11e5-844f-ad9971b27d46.png)

**Comment by alxndrsn** [comment]
Looks awful to me ;¬p  Is this working as you want, though?

**Comment by abbyad** [comment]
Yes :)
As ugly as that example is, I think this will serve the purposes of https://github.com/medic/medic-webapp/issues/1426#issuecomment-148874174

What is the preferred way to refer to images uploaded with a form, and to the medic-webapp icons?

**Comment by alxndrsn** [comment]
Can #1426 be marked `4 - Acceptance Testing` then?

**Comment by alxndrsn** [comment]
There's an example of a form with an attached image here: https://github.com/alxndrsn/enketo-client-side-transformer/blob/master/xforms/with-media/pictorial-report.xml#L32

Upload using `upload_xform pictorial pictorial-report.xml fish.png picture.png` iirc

**Comment by abbyad** [comment]
Works well for our initial purposes. New issues will be created for any other markdown/up related aspects while implementing the reports page.

**Comment by abbyad** [comment]
Accidentally reopened... closing again.

**Comment by abbyad** [comment]
Works, moving to Ready.
