### ISSUE TITLE
Warn users before leaving a form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1415]
Users should get a warning/alert modal prior to exiting a form, with the option to cancel.

**Comment by alxndrsn** [comment]
@abbyad are you sure this will still be wanted when #1460 is implemented?  User will have to back-up to the first page of the form before he would need to be warned.

**Comment by alxndrsn** [comment]
Relevant discussion here: https://stackoverflow.com/questions/11777890/equivalence-of-window-onbeforeunload-in-angularjs-for-routes

**Comment by abbyad** [comment]
Yes, because we will have a "cancel/exit" button on the left side of the top bar (aka filter bar). It will also be pertinent in desktop mode.

**Comment by alxndrsn** [comment]
### Notes

* on Place form, warning will occur _after_ the place type has been selected
* clicking the back-button-in-header, and then choosing _Cancel_ in the confirmator, will lead to `show-content` class being removed from `<body>`, making the form disappear on small screens.  This should not be an issue, as according to #1459 we'll soon be rid of this button

**Comment by alxndrsn** [comment]
Works too well - currently warns the user before he submits a form as well as when back is pressed.

**Comment by garethbowen** [comment]
@alxndrsn Also native confirm/alert dialogs aren't very nice. We don't use them elsewhere in the app because they have bad usability and design. For example, when deleting a record we show a bootstrap modal confirm dialog.

Replace the native confirm dialog with a custom bootstrap one.

**Comment by alxndrsn** [comment]
:+1:

**Comment by alxndrsn** [comment]
# Ways to catch navigation events

* [`window.onbeforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)
* [`window.onhashchange`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange)
* [angular's `$stateChangeStart` event](https://github.com/angular-ui/ui-router/wiki#state-change-events), although [this may not work as you expect it to](https://github.com/angular-ui/ui-router/issues/1780)

# Ways to navigate away from a form, and how to detect them

navigation | `onbeforeunload` | `onhashchange` | `$stateChangeStart` | should prompt?
---|---|---|---
click back button, going to another page in the app | | ✓ | ✓ | ✓
click back button, going to a page outside the app | ✓  | | | ✓
submit the form | | ✓ | ✓ |
select another item in the LHS | | ✓ | ✓ | ✓
refresh the window | ✓  | | | ✓
select a tab | | ✓ | ✓ | ✓
select item from the royale with cheese menu | | ✓ | ✓ | ✓
logout | ? | | | ✓

**Comment by alxndrsn** [comment]
This looks like i'll be tough to fix, as proper back button behaviour is not currently supported by angular-ui-router.  Ref:

* https://github.com/angular-ui/ui-router/issues/1525
* https://github.com/angular-ui/ui-router/issues/1780
* https://github.com/angular-ui/ui-router/pull/1845

There is a suggested workaround on the first 2 tickets, but these do not work.  We might considering patching ui-router as per [the third ticket (PR)](https://github.com/angular-ui/ui-router/pull/1845).  The patch submitted has a forked `ui-router` repo, which may be a good starting point: https://github.com/arcanis/ui-router

**Comment by alxndrsn** [comment]
@garethbowen want your opinion on this before going further

**Comment by browndav** [comment]
Some requirements guidance from @abbyad or UX guidance from @diannakane might help here. It's distinctly possible that we could warn along one critical path (e.g. hitting the `X` button), and that could be good enough for the field test. Thoughts from the requirements side?

**Comment by abbyad** [comment]
The immediate priority is only those possible in Mobile App, but for desktop users all would apply. We could split the browser/desktop off into a separate issue of lower priority if needed.

**Possible in Mobile App**
- click back (**or close**) button, going to another page in the app
- application update received (which can lead to a refresh)

**Browser only**
- click back button, going to a page outside the app
- click forward button, going from another page in the app (browser only)
- click forward button, going from a page outside the app
- refresh the window

**Desktop-view only** _unlikely in mobile app unless on device with high enough resolution_
- select another item in the LHS
- select a tab 
- select item from the royale with cheese menu
- logout

**Comment by alxndrsn** [comment]
We could go nucular and get the android wrapper to rout back-button presses through a custom JS function (mobile only).

**Comment by alxndrsn** [comment]
@abbyad i'll add that to the table

**Comment by garethbowen** [comment]
Firstly, you're right @alxndrsn. I had forgotten that onbeforeunload is so painful, and didn't know that angular-ui was going to be difficult. It looks like there's no easy and good option for this...

Another thought which is probably harder but better UX is to store drafts automatically. This way users would be able to leave the form and then click the forward button to go back to where they were. These could probably just be stored in a local pouch and probably only allow one draft per form type so we don't have to worry about draft selection or deletion. @abbyad would that be problematic from a UX perspective?

Otherwise I think we'll have to go for the onbeforeunload with the branched angular-ui with native confirm dialogs.

**Comment by browndav** [comment]
The one-draft-per-form concept is interesting. If there were an obvious "No, I don't want to continue this, start over" action, I think it could potentially work.

**Comment by abbyad** [comment]
I like the idea of drafts, but one draft per form may have other problems since it wont always be possible to get back to the same form.

For instance, what happens if you start a pregnancy form on Anna, exit, then go to do a pregnancy on Berta? Do you show the pregnancy form with Anna's details filled out or do you override it with the Berta's fields? If you override, does that mean that the draft with Anna's info is gone?

**Comment by garethbowen** [comment]
Good point. Prepopulation makes things difficult. Maybe it should be one draft per context where context includes the report type. So you can have a Follow Up draft for Anna and a different one for Bob. Then you could either not prepopulate when loading a draft because the prepopulation happened the when creating the draft initially, or you could prepopulate after loading the draft to make sure the data is up to date.

We might also need to have an expiry date on drafts, like, one week after the draft was created?

**Comment by browndav** [comment]
Drafts are starting to sound quite complicated now, relative to the six working days we have left before the freeze. :)

**Comment by browndav** [comment]
Decisions from Monday's iteration call: we should handle three cases for the time being – (1) the close button; (2) the hardware back button; and (3) application update/refresh. We agreed that item #3 could be solved by simply changing the message to communicate "oh, by the way, you're going to lose your work on this form". Item #1 is straightforward. For item #2, I think we have to go the `ui-router` patching route.

**Comment by alxndrsn** [comment]
[ ] add close button to enketo forms
[ ] patch `ui-router`
[ ] intercept hardware back-button press on enketo forms to trigger `prev` button if it's available.  if not available, then don't suppress default behaviour
[ ] update application refresh message to include warning that work may be lost

**Comment by alxndrsn** [comment]
This is not really practical due to:

* difficulty detecting what has triggered navigation making it hard to manually reverse the navigation, and
* restrictions on how `window.history` can be modified preventing a coherent history to be manually created

My recommendation is to work on automagic saving of form contents instead.

**Comment by alxndrsn** [comment]
Here's a potential solution for handling back/forward events in angular: https://stackoverflow.com/questions/15813850/detect-history-back-using-angular

**Comment by joshnesbit** [comment]
I think it's most critical to warn users before navigating away from partially-completed enketo forms. This hasn't been implemented yet, has it?

**Comment by alxndrsn** [comment]
> I think it's most critical to warn users before navigating away from partially-completed enketo forms. This hasn't been implemented yet, has it?
Correct, not yet implemented.
