### ISSUE TITLE
Reorder profile sections

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1416]
Based on the feedback from the demos, we should update the profile order to show Tasks, Actions, Family Members (if Family profile), and then History (aka Data, Reports).

**Comment by abbyad** [comment]
After further discussion, we have settled on the following order for now:
- Basic info card
- Family Members (if Family profile)
- Tasks
- Actions
- History (aka Data, Reports)

**Comment by garethbowen** [comment]
@abbyad I think the order you settled on is exactly the way the page is ordered currently. Could you please check and let me know what should change? [Source code](https://github.com/medic/medic-webapp/blob/develop/templates/partials/contacts_content.html) for reference.

**Comment by abbyad** [comment]
Looks good, moving to Ready.
