### ISSUE TITLE
Exclude Q from enketo.js bundle

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1417]
We are using built-in `Promise` in the rest of the code, so we should shim `Q` in enketo code so it's actually using `Promise` as well.

**Comment by alxndrsn** [comment]
Pouch is also importing a `Promise` implementation, [`lie`](https://github.com/calvinmetcalf/lie/blob/master/dist/lie.js), but this is less significant (8 vs 60 KB, unminified).

**Comment by garethbowen** [comment]
Unfortunately the ES6 Promise spec isn't 100% compatible with the Q library. For example, it's quite likely Enketo will invoke the `finally` function which doesn't exist in [the native spec](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) and will therefore error.

I think we have to use `Q` for Enketo for now.

Perhaps the optimal solution is to contribute a patch to Enketo to use `lie` which can be used browser or server side, and polyfills in the browser so the native implementation is used where available.

**Comment by alxndrsn** [comment]
Changest reverted in https://github.com/medic/medic-webapp/commit/732be164acff49d50ddf954cab1e3115375f0ead.  Filed change request with `enketo-core` to follow Promises/A+ spec: https://github.com/enketo/enketo-core/issues/327

**Comment by alxndrsn** [comment]
Enketo is now using `lie`.
