### ISSUE TITLE
Show ages of people in the family profile page

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1421]
Will make it easier to different between family members

**Comment by abbyad** [comment]
Here is an example showing the ages.
![image](https://cloud.githubusercontent.com/assets/789512/10610636/b663164c-7716-11e5-9c41-5159afdbae31.png)

We'd want to show the age with years and months for children under 2:
**>= 2 years old:** years only (`3 years`)
**1-2 years old:** year and months (eg `1 year and 4 months`)
**<1 year old:** months only (`6 months`)

**Comment by garethbowen** [comment]
This has been implemented slightly differently than above:

>= 2 years old: years only (3 years)
2months to 2 years old: months only (6 months)
< 2 months: days only (20 days)

Please reopen if this is unacceptable.

**Comment by abbyad** [comment]
Looks good, moving to Ready.
