### ISSUE TITLE
Identify the head of family in the family profile page

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1422]
Add a visual indication for the head of family in the family members list. 

Initial ideas were to add a star or label next to or beneath the person's name.

**Comment by abbyad** [comment]
Example with a star icon:
![image](https://cloud.githubusercontent.com/assets/789512/10611697/41524026-771b-11e5-90bc-991ba8300879.png)

@diannakane what are your thoughts on a star vs text label? Any other suggestions for highlighting the primary caregiver (aka head of household)?

**Comment by diannakane** [comment]
I like the star. The HOH concept is reinforced by the name of the house being "Susan Rene's family." 

How would I reassign HOH privileges to another family member?

**Comment by abbyad** [comment]
You will be able to do that by editing the family. We should open a separate feature request for that.
