### ISSUE TITLE
Sort the family members in the family profile page by age

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1423]
Feedback that we got from demos was to sort the family members by age, oldest on top.

**Comment by joshnesbit** [comment]
This ordering by age should include the primary caregiver in addition to children. 99% of the time, primary caregiver will be listed first when sorted by age. I'm logged in as demo on lg.dev in Chrome, and I currently see this family list:

![screen shot 2015-11-05 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/377216/10983305/a8f1c8de-83c6-11e5-885f-9a1c52e5c668.png)

**Comment by garethbowen** [comment]
I think what's happening here is we're sorting on the date but it's not formatted in a way that can be sorted. We might need to change the forms to store the date in a computer friendly format.

**Comment by mandric** [comment]
Seems weird we have a date we can't sort on, regardless of the format no?

**Comment by abbyad** [comment]
Right, the date_of_birth field is "mmm, dd, yyyy" (eg Nov 3, 1992) because the same field was being displayed in the profile. I can save it differently in the XForms now that we show age instead.

**Comment by abbyad** [comment]
Would "yyyy-mm-dd" be suitable?

**Comment by mandric** [comment]
Trying to say that if moment() can parse it then we should be able to sort by it.

**Comment by garethbowen** [comment]
@mandric We're just sorting by string currently. We could convert to Date then sort but the current date format isn't standard enough to do that well either. I think the best approach is as Marc said, storing the DOB in ISO, which can then be sorted as string always format it before display.

**Comment by garethbowen** [comment]
> Would "yyyy-mm-dd" be suitable?

Perfect.

**Comment by garethbowen** [comment]
Assigned to @abbyad to update the configuration, then the code should just work.

**Comment by abbyad** [comment]
@joshnesbit, if you test now any newly created family on dev will have the family members properly sorted.
