### ISSUE TITLE
Enhanced markdown: Design of Reports page for review with LG

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1426]
@Lesterng please provide details :-)

**Comment by abbyad** [comment]
Here is an example that @joshnesbit, @diannakane, and @Lesterng have been worked on:

![image](https://cloud.githubusercontent.com/assets/789512/10556226/befcb5f6-744b-11e5-989b-a4089cb6eafc.png)

**Comment by abbyad** [comment]
Works well for our initial purposes. New issues will be created for any other markdown/up related aspects while implementing the reports page.

**Comment by abbyad** [comment]
Closed the wrong issue. Reopening pending design results from @Lesterng and @diannakane.

**Comment by abbyad** [comment]
This has been implemented based on @Lesterng's mockups. Moving to Ready
