### ISSUE TITLE
Error when opening Contact profile with URL

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1428]
Clicking on a contact from the left pane works, but reloading the page with the contact url fails (eg `/medic/_design/medic/_rewrite/#/contacts/618D033A-1F4D-8CA8-A2B6-990ED0531763`):

```
Error fetching doc 
  e {status: 500, name: "unknown_error", message: "Database encountered an unknown error", error: true}
  error: true
  message: "Database encountered an unknown error"
  name: "unknown_error"
  status: 500
  __proto__: d
    constructor: d(a)
    toString: ()
    __proto__: DefineError.aV
    d.forEach.console.(anonymous function) @ inbox.js:14
    (anonymous function) @ dependencies.js:3
    (anonymous function) @ inbox.js:28i @ dependencies.js:3
    (anonymous function) @ dependencies.js:3
    a.$get.n.$eval @ dependencies.js:4
    a.$get.n.$digest @ dependencies.js:4
    (anonymous function) @ dependencies.js:4e @ dependencies.js:2
    (anonymous function) @ dependencies.js:2
```

**Comment by garethbowen** [comment]
This works for me. Obviously this error message isn't very useful. Can you narrow it down at all? Does it happen with all contacts? With all contact types? On all devices? In all browsers? etc.

**Comment by browndav** [comment]
Theory: this is the same issue as the bootstrap failure / no-content-visible issue in #1341.

**Comment by abbyad** [comment]
I can't reproduce this right now (on a freshly restarted computer).

**Comment by abbyad** [comment]
Closing
