### ISSUE TITLE
Hide form title within form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1433]
Followup to #1302, we want to avoid having the title show up in the form and in the filter bar simultaneously. 
![image](https://cloud.githubusercontent.com/assets/789512/10460607/0dd5dc12-71a3-11e5-9cc9-6544bf29cf80.png)

As recommended by @garethbowen we should remove the title from the XML, and have it in db doc for the form. To make the task for tech-leads easier we should modify the upload script to use the title from the XML file as the title in the db, then strip it from the XML.

**Comment by alxndrsn** [comment]
Comments on https://github.com/medic/medic-webapp/commit/661b15bf73691144bc039af667ef4551263643c7.  Always good to quote your variables :¬)
