### ISSUE TITLE
Container: Use lg.app instead of lg.dev

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1435]
This is a trivial change, but needs to happen this week. The lg.app server should already be cloned and set up and ready to update.

**Comment by abbyad** [comment]
It looks like the change was done [here](https://github.com/medic/medic-android/commit/6d266451fe4907d1a190d31658f47a335e73b7b7). Was this pushed to the play store?

**Comment by abbyad** [comment]
I don't see any updates on the play store so pushed a new version and will test now.

**Comment by abbyad** [comment]
Confirming that the app in the play store is now using lg.app.
