### ISSUE TITLE
font-awesome doesn't load from appcache

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1438]

**Comment by garethbowen** [comment]
FontAwesome's stylesheet automatically includes a cache busting parameter which breaks the appcache spec. I've added a regex to remove this at build time. This should be reverted once FontAwesome fixes [the problem](https://github.com/FortAwesome/Font-Awesome/issues/3286).

**Comment by alxndrsn** [comment]
A couple of comments on the regex.  Also, how will the content of `appcache.manifest` change when the font version changes?

**Comment by garethbowen** [comment]
The content of the appcache.manifest changes every time you build, eg:

```
CACHE MANIFEST
# rev 1405 - 2015-10-15T01:30:27.066Z
```

Changing a comment is enough to force a the appcache to be invalidated, and all resources completely downloaded again.

Fortunately while debugging the offline bug I stumbled across this paragraph in the [MDN appcache documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache):

> Never access cached files by using traditional GET parameters (like other-cached-page.html?parameterName=value). This will make the browser bypass the cache and attempt to get it from network. To link to cached resources that have parameters parsed in JavaScript use parameters in the hash part of the link, such as other-cached-page.html#whatever?parameterName=value.

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by alxndrsn** [comment]
Thanks for clearing that up about how cache manifest gets changed - makes perfect sense.  Do manifest files also go through the traditional browser cache?  Or when the appcache is invalidated, are the corresponding entries in the normal browser cache also discarded?

**Comment by garethbowen** [comment]
It's recommended you don't cache manifest files. From the same documentation:

> It's a good idea to set expires headers on your web server for *.appcache files to expire immediately. This avoids the risk of caching manifest files.

This means the page always tries to get the latest manifest, but fails gracefully when offline. From our api server.js:

```js
  if (appcacheManifest.test(req.url)) {
    // requesting the appcache manifest
    writeHeaders(req, res, [
      [ 'Cache-Control', 'must-revalidate' ],
      [ 'Content-Type', 'text/cache-manifest; charset=utf-8' ],
      [ 'Last-Modified', 'Tue, 28 Apr 2015 02:23:40 GMT' ],
      [ 'Expires', 'Tue, 28 Apr 2015 02:21:40 GMT' ]
    ]);
  }
```

**Comment by alxndrsn** [comment]
Sorry - I obviously wasn't clear!  I don't mean caching `application.manifest` itself, but caching the assets listed inside `application.manifest`.

**Comment by garethbowen** [comment]
The cached files fall back to the standard caching rules so unchanged files won't be redownloaded. However in the server.js we have this section to ensure static resources aren't cached.

```js
if (staticResources.test(req.url)) {
    // requesting static resources
    writeHeaders(req, res, [
      [ 'Cache-Control', 'no-cache, must-revalidate' ]
    ]);
  }
```

This is fairly aggressive but I expect app updates to be infrequent, so erred on the side of caution.
