### ISSUE TITLE
Contact profile looks a bit rubbish if there are no reports to submit

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1439]
Currently, if there are no suitable reports for a contact the "Submit Report" list is shown empty:

<img width="406" alt="screen shot 2015-10-15 at 11 59 34" src="https://cloud.githubusercontent.com/assets/191496/10510822/7d8c33ec-7335-11e5-8ce6-efe5f0f4ca1a.png">

We should either:

1. hide it; or
2. show something nice inside it like _none available_

I recommend **1**, as it's up to the admin if there are reports available, and if there are not then the user probably doesn't need to know about them or be distracted by this empty section.

**Comment by garethbowen** [comment]
I think some of the other sections already check the item length and hide completely when there are none.

**Comment by garethbowen** [comment]
Looks good apart from a small comment in the commit.
