### ISSUE TITLE
When the datepicker gets too close to the top of the screen, you can't access the top of it

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1441]
# Background

The date picker has a very useful feature: when you click on the text _December 2016_ in the screenshot below, it turns from day-choosing-mode to month-choosing-mode:

![with-enough-room](https://cloud.githubusercontent.com/assets/2064938/10748316/c5f4339a-7cc3-11e5-83fb-f231673d3f71.png)

# Problem

If the date picker appears too close to the top of the screen, the top-bar is lost:

![without-room](https://cloud.githubusercontent.com/assets/2064938/10748319/cac69386-7cc3-11e5-887c-b358c8ca6151.png)

# Desired behaviour

If there isn't space for it above the input field, the date picker should either:

1. appear **below** the input field; or
2. shift down a bit and obscure the input field

**Comment by alxndrsn** [comment]
Not sure if this is an improvement - the controls can now be hidden behind the title bar:
<img width="278" alt="screen shot 2015-10-28 at 10 17 54" src="https://cloud.githubusercontent.com/assets/191496/10784235/3df2a61c-7d5d-11e5-8f54-11d69be4dab9.png">

**Comment by garethbowen** [comment]
You're right, if the field is just the right distance from the top the datepicker incorrectly renders it above when there isn't room. I've forced it to render below.

**Comment by alxndrsn** [comment]
Does the job.
