### ISSUE TITLE
Allow client-side caching of static resources

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1442]
The most suitable approach to this seems to be to serve an `etag` header from either `medic-api` or `nginx` containing the hash of the file's contents.

We assume that any asset change will result in a ddoc change, so we should re-calculate hashes when a ddoc change is detected.  Alternatively we could just calculate hashes on `api` startup, and assume that `api` will be bounced when the ddoc changes, at least in prod(?).

Probably this could be applied to anything in `static/dist` (or perhaps just anything in `static`).

**Comment by mandric** [comment]
Is there a reason we don't use/proxy the etag header that is served by couchdb for all attachments?

**Comment by alxndrsn** [comment]
Sounds like a good question!  @garethbowen, any ideas?

**Comment by mandric** [comment]
Just realized that the ddoc is pushed/updated each time so I think using the etag on the attachments on the ddoc would effectively be the same thing as no-cache.

**Comment by alxndrsn** [comment]
Depends how the etags are generated, surely?  If the etag is a hash of the content of each attachment, then pushing a new ddoc won't necessarily change every etag.

**Comment by mandric** [comment]
The etag is the `_rev` value from the doc/attachment.  If you create new attachments with each ddoc change then you will always have a unique _rev value.

**Comment by mandric** [comment]
Might be worth a re-visit. http://docs.couchdb.org/en/1.6.1/api/document/attachments.html

**Comment by mandric** [comment]
Ok I was confusing etag on a doc and etag on an attachment, in the case of attachments it is the MD5 of the content which is saved during attachment creation.  Here's the header output from couchdb and medic-api for an attachment:
```
# medic-api
$ curl -s -D - -o /dev/null  http://admin:secret@localhost:5988/medic/_design/medic/_rewrite/static/img/ico/icon_48.ico 
HTTP/1.1 200 OK
X-Powered-By: Express
server: CouchDB/1.6.1 (Erlang OTP/17)
etag: "4UZXadQKml1zQXH8fc9ycQ=="
date: Thu, 15 Oct 2015 17:55:21 GMT
content-type: image/x-icon
content-md5: 4UZXadQKml1zQXH8fc9ycQ==
content-length: 9854
Cache-Control: no-cache, must-revalidate
accept-ranges: bytes
connection: keep-alive
WWW-Authenticate: Cookie


# CouchDB
$ curl -s -D - -o /dev/null  http://admin:secret@localhost:5984/medic/_design/medic/_rewrite/static/img/ico/icon_48.ico 
HTTP/1.1 200 OK
Server: CouchDB/1.6.1 (Erlang OTP/17)
ETag: "4UZXadQKml1zQXH8fc9ycQ=="
Date: Thu, 15 Oct 2015 17:55:26 GMT
Content-Type: image/x-icon
Content-MD5: 4UZXadQKml1zQXH8fc9ycQ==
Content-Length: 9854
Cache-Control: must-revalidate
Accept-Ranges: bytes
```

**Comment by mandric** [comment]
Should just work as is if we remove the Cache-Control override in medic-api.

**Comment by garethbowen** [comment]
Yeah that looks perfect. It should just work.

**Comment by alxndrsn** [comment]
:+1:

**Comment by garethbowen** [comment]
Looks pretty good. I've commented on the commit with a potential issue.

The caching works well in acceptance testing. Below is a log snippet from appcache requests from updating the `templates.js`. Note the `templates.js` has status 200 and some content and everything else has a 304 and no content.

```
::1 - - [18/Oct/2015:21:04:51 +0000] "GET /medic/_design/medic/_rewrite/static/img/icon-chw-selected.svg HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36"
::1 - - [18/Oct/2015:21:04:51 +0000] "GET /medic/_design/medic/_rewrite/static/dist/templates.js HTTP/1.1" 200 24410 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36"
::1 - - [18/Oct/2015:21:04:51 +0000] "GET /medic/_design/medic/_rewrite/static/fonts/enketo-icons-v2.woff HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36"
```

**Comment by garethbowen** [comment]
Assigned back to @mandric to have a look at the potential issue.
