### ISSUE TITLE
Task generator's Utils.isTimely function doesn't work as expected

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1444]
Perhaps I am using it wrong, but the [isTimely](https://github.com/medic/medic-webapp/blob/194b6b8bd3cb9a251e58c169832fa68bc261fa31/static/js/services/task-generator.js#L16) function is not working as expected. 

With the following:
  `due`: a date 21 days from now
  `event.start`: 7 days
  `event.end`: 28 days
It returns true (21 > -7 && 21 < 28), but should return false.

May be worth having some tests for this too.

**Comment by garethbowen** [comment]
Clearly the variables need a better name. I would expect that configuration to return `true`. eg: the event will show for 7 days before it's due and 28 days after it's due. How do you read it?

**Comment by abbyad** [comment]
It was showing for 28 days before it's due and 7 days after, I was expecting the opposite.
