### ISSUE TITLE
Enketo: Cannot access grouped fields

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1446]
Reported by @abbyad. In several areas, using grouping inside of an Enketo Javarosa Xform compromises the ability to access those fields programmatically. Figure out a way we can use groupings inside of an Xform but retain access to the fields.

**Comment by abbyad** [comment]
Example [doc](https://lg.dev.medicmobile.org/_utils/document.html?medic/8F30C330-6ECF-A095-A75B-292431B6CED9) with grouped fields not being saved with field names:

![image](https://cloud.githubusercontent.com/assets/789512/10588968/d105143c-7676-11e5-9694-2a9930a8af7e.png)


with excerpt:
```
  "patient_age_in_months": "16.21",
   "p_note": "",
   "group_block": "\n            \n            \n            \n            1\n          ",
   "group_cough": "\n            yes\n            c4\n            yes\n          ",
   "group_breathing": "\n            \n            \n            40\n            true\n            \n            \n          ",
   "group_fever": "\n            \n            no\n            \n            \n          ",
   "group_diarrhea": "\n            no\n            \n            \n          ",
   "group_danger_signs": "\n            \n          ",
```

**Comment by alxndrsn** [comment]
This ticket appears to be about serialising enketo form model XML to JSON.  The fix will address that.

**Comment by garethbowen** [comment]
Lovely.
