### ISSUE TITLE
Enketo: Support repetition in/for the Xforms <model> section

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1447]
We have individual Enketo forms that are capable of creating multiple database objects, via the model/instance subtree and the `bind` directive. Extend this facility to support repeated creation of an unbounded-at-form-design-time number of objects.

**Comment by alxndrsn** [comment]
These changes explicitly add support for extra children for contacts.

More generally, the standard xforms/enketo `repeat` tag can be used within `<h:body>` if repeated elements are wanted within a resource.

Currently, repeated sections must be included in `/model/instance/data/repeat`, and optionally made optional via `/model/instance/data/repeat-relevant`.  For an example, please see https://github.com/alxndrsn/enketo-client-side-transformer/blob/afffaa620a7c04c7996cd73b89bf162ac331ea15/xforms/family.xml#L26.

When the issue https://github.com/enketo/enketo-core/issues/336 is resolved, we may be able to do away with the `/model/instance/data/repeat-relevant` and `/model/instance/data/repeat` sections of the model, and the special code to handle them, include `<child>` in the model in in the same way as `<parent>`, and allow the `extras` code to handle all kinds of extra objects.

**Comment by garethbowen** [comment]
Minor comment on one commit, otherwise passed with flying colours.

If the DB.get() thing is bothering you why don't we refactor it system wide so DB is always the 'medic' db and where necessary we can have a UserDB or whatever else we need? It's one of those things that seemed like a good idea at the time but is turning into a pain...

**Comment by abbyad** [comment]
This works well, and its possible to create the necessary XForm using XLSForm as well. 

Moving to Ready.
