### ISSUE TITLE
Add fields to the contact/family creation form

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1448]
On today's call, we discussed the need to produce both built-in objects (e.g. contacts, families) and reports as part of the new unified add person/family workflow. Figure out a UX for chaining reports to the end of the contact/family creation process that's implementable in the time we have before November 1st. Get that UX and interaction diagram approved, visually, by stakeholders in SF. Then, design and implement a configurable way of chaining zero or more report-creation steps to the end of the contact/family creation process.

**Comment by browndav** [comment]
For field test: add "do you have a cookstove?" question, "are you pregnant?" question, "do you have a solar charger?"; make these contact related and clearly presented as an "at-time-of-registration" question – N.B. the information is correct at time of registration, but may diverge later.

**Comment by browndav** [comment]
Renamed this to reflect today's decision: we'll ignore any auto-prompting or chaining of reports/surveys, and add content directly to the contact/family creation forms. Data collected will be accurate at time of registration, but must be manually maintained per-contact if it's to reflect reality continuously.

**Comment by abbyad** [comment]
I have tested this but figure it would be good for @joshnesbit to do acceptance testing to verify the form contents. You can use the "Add Family" on lg.dev for this testing.

**Comment by joshnesbit** [comment]
This looks great.
