### ISSUE TITLE
Enketo: Make individual pages of a form navigable using the browser's back function (e.g. window.history.back or equivalent)

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1449]
Obverved: Edit the contact for a report (which brings up the select2 facilities list) then select back button, the underlying div changes to the previous inbox view but the modal remains.
Expected: Selecting back button on the device should close/destroy the modal and take you back to the record view.

**Comment by garethbowen** [comment]
I think we can hook into bootstraps model open event and register a history item so modals like this become navigable.

Probably the ideal solution is to use modals only for alerts and confirms, so things like editing the facility would have a specific URL and be rendered in the RHS pane.

**Comment by browndav** [comment]
Updating this to clarify intent: we decided on today's call that Enketo forms should be navigable using the browser's back function.

**Comment by alxndrsn** [comment]
@mandric I don't fully understand this ticket - is it saying that `select2` fails to close its dropdown when you press the back button?

**Comment by browndav** [comment]
@alxndrsn: Did you intend for that comment to go on #1395?

**Comment by alxndrsn** [comment]
LOL

**Comment by alxndrsn** [comment]
@browndav nope, definitely meant to be here

**Comment by browndav** [comment]
Yeah, you're right, I think this has changed enough that it's worth refiling. I renamed it to try to clarify the new intent, but it's confusing.

**Comment by browndav** [comment]
Refiled as #1460. I've made updates made to #1459 to reflect the need to cross-check the work on #1395 against the new back button behavior. @mandric: Does this all sound okay?
