### ISSUE TITLE
Replace deprecated appcache

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1451]
The [appcache spec has been deprecated](https://html.spec.whatwg.org/multipage/browsers.html#offline) so we need to find another way to server static files while offline. This is [good thing](http://alistapart.com/article/application-cache-is-a-douchebag).

The deprecation notice suggests using Service Workers but only very recent browser versions support them, so for example, it wouldn't work in the webview in android 4.4. Investigate using [a polyfill](https://github.com/coonsta/cache-polyfill) to implement a service worker cache.

**Comment by garethbowen** [comment]
Also worth investigating: https://github.com/GoogleChrome/sw-toolbox

**Comment by alxndrsn** [comment]
Please file a new issue or re-open when this is actually a priority.
