### ISSUE TITLE
Task generator performance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1452]
Every interaction with the TaskGenerator gets all the contacts and reports from the database, compiles the task rules, and generates the tasks. This is now proving a performance bottleneck.

Some ideas to improve performance:

1. cache results in the task generator and expire the cache every x minutes
2. cache results in the task generator and listen for changes to reports or contacts to expire the cache
3. use a changes listener and keep nools running and provide new facts to the engine on change

Currently the user provided configuration has to decide whether tasks are emitted based on the relevant date. It might be better to have the nools configuration emit all tasks and filter in the task generator. That way items to show could change over time without rerunning the rules which would be particularly useful for option 3.

**Comment by browndav** [comment]
Scheduling this. It'd be worth making sure this is our critical-path performance issue before we go forward with it, but I suspect it is.

**Comment by garethbowen** [comment]
Task generation is now performant. The tasks are generated on load, and then updated and reemitted on contact or report change.

**Comment by browndav** [comment]
@mandric: Assigned for code review.

**Comment by abbyad** [comment]
Returning since the tasks are no longer visibly created/cleared until you refresh the page. 

This means that if you submit an assessment you wont see the "follow up" task until you refresh the page. That task would then show even if a follow up form was submitted - until you refresh again.

**Comment by garethbowen** [comment]
This was caused by the controller only updating unresolved tasks. This means if a task went from unresolved to resolved, the resolve status was never updated in the UI. I moved the filter from the controller into the template so it's always updated, and angular can show/hide based on the task status.

**Comment by abbyad** [comment]
Returning since @joshnesbit is still reporting issues of tasks not clearing until reload.

**Comment by garethbowen** [comment]
Closing. The task generator performance is sufficient. The issue Josh is referring to has been raised as #1562
