### ISSUE TITLE
Disable the Tour for mobile users

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1457]
The tour is not relevant for mobile app users. We should hide it until the content has been updated.

**Comment by diannakane** [comment]
This was on the list for acceptance testing, so should I report that I still see the tour?

**Comment by abbyad** [comment]
This is likely a configuration issue now, as the Analytics has not been fully removed yet via configuration.

**Comment by abbyad** [comment]
Works well for me, moving to Ready.
