### ISSUE TITLE
Search: match the children using the parent/caregiver's name

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1458]
CHPs have reported that they'd like to be able to search for a parent/caregiver's name, but see both the parent and their related children in the search results.

LG staff have proposed modifying the name of the child to include the parent's name in a parenthetical; IMO this is brittle and really not ideal. See if we can accomplish this a different way.

**Comment by alxndrsn** [comment]
The child only has an indirect relationship with the parent, via the Family.  Fortunately the Family has the same name as the parent.  Could we make this more general, and match `contact.parent.name` field as well as `contact.name` when searching?

**Comment by alxndrsn** [comment]
@browndav I think the title of this ticket reads opposite of how it should.  From the ticket text, I understand that if I search for "_some head of household's name_", the result should be e.g.:

* head of household
* child 1
* ...
* child N

**Comment by abbyad** [comment]
Yes, that's right @alxndrsn searching for the head of family shows the children as well. I'll update the title.

**Comment by alxndrsn** [comment]
Looks like this:

<img width="1280" alt="screen shot 2015-10-20 at 21 54 33" src="https://cloud.githubusercontent.com/assets/191496/10619343/6e10daaa-7775-11e5-869c-ddb2d25843a3.png">

**Comment by diannakane** [comment]
Here are screenshots of searching for: 
1) Malia
![screen shot 2015-10-20 at 15 59 50](https://cloud.githubusercontent.com/assets/1675870/10623479/3819affc-7744-11e5-89a0-a02a52f518c6.png)

2) Glory
![screen shot 2015-10-20 at 16 00 29](https://cloud.githubusercontent.com/assets/1675870/10623481/3b984ea4-7744-11e5-9456-c2035124cddd.png)

3) Ngawa 
![screen shot 2015-10-20 at 16 00 39](https://cloud.githubusercontent.com/assets/1675870/10623484/3f6c1286-7744-11e5-907a-8b6faa9fa116.png)

Are they requesting that all searches for #1 will yield the same results as #3? Should #2 (searching for a parent) display children as well?

**Comment by diannakane** [comment]
Search results for #2 could also be enhanced by including a count of family members (or families, in the case of a branch/area) to the main contacts list. 

![screen shot 2015-10-20 at 16 05 44](https://cloud.githubusercontent.com/assets/1675870/10623596/3336d5ea-7745-11e5-9df3-2b2054fbbb98.png)

**Comment by diannakane** [comment]
Search results for #2 could also be enhanced by including a count of family members (or families, in the case of a branch/area) to the main contacts list. 

Could include context "members" or "families" or just the number. 

![family member count](https://cloud.githubusercontent.com/assets/1675870/10623608/4990ba36-7745-11e5-9557-3ff456f8a336.jpg)

**Comment by alxndrsn** [comment]
@diannakane surprising results!  Where were you testing this?  If it's on LG I'll take a look.

**Comment by diannakane** [comment]
@alxndrsn I was on lg.app

What kind of results were you expecting?

**Comment by alxndrsn** [comment]
Aha!  I was expecting `Glory` to show both Glory _and_ Malia.  But I've just checked on `lg.app`, and it's not running the latest code - so I'm no longer surprised.

**Comment by diannakane** [comment]
Right, it makes sense to have it search the family's name (Glory Mgawa)
which is included in Malia's identifying info.

On Wed, Oct 21, 2015 at 9:15 AM, Alex Anderson <notifications@github.com>
wrote:

> Aha! I was expecting Glory to show both Glory *and* Malia. But I've just
> checked on lg.app, and it's not running the latest code - so I'm no
> longer surprised.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1458#issuecomment-149949109>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by diannakane** [comment]
Searching for "Glory" should also result in a contact card for Glory as an
individual, not just as the name of a family. The head of household may be
a pregnant woman that should have her own card.

On Wed, Oct 21, 2015 at 9:40 AM, Dianna Kane <dianna@medicmobile.org> wrote:

> Right, it makes sense to have it search the family's name (Glory Mgawa)
> which is included in Malia's identifying info.
>
> On Wed, Oct 21, 2015 at 9:15 AM, Alex Anderson <notifications@github.com>
> wrote:
>
>> Aha! I was expecting Glory to show both Glory *and* Malia. But I've just
>> checked on lg.app, and it's not running the latest code - so I'm no
>> longer surprised.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/medic/medic-webapp/issues/1458#issuecomment-149949109>
>> .
>>
>
>
>
> --
> P.S. Join our community. Sign up for Medic Mobile's newsletter
> <http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
> .
>
>
> Dianna Kane | Senior Designer
> Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
> @*M*edic <http://www.twitter.com/medic> Facebook
> <https://www.facebook.com/MedicMobile> @diannakane
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by abbyad** [comment]
Works well from my testing, moving to Ready.
