### ISSUE TITLE
Enketo: Make individual pages of a form navigable using the browser's back function (e.g. window.history.back or equivalent)

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1460]
This is required for #1459. On yesterday's iteration call, we agreed that the browser's back function should navigate between individual Enketo form pages, rather than punt the user out of the Enketo form altogether.

**Comment by alxndrsn** [comment]
Doing this by intercepting the change-state event on enketo forms.  If the [*previous page*] button is available, click that instead :¬)
