### ISSUE TITLE
Refactor `DBSrv`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1461]
Currently 95% of the use of the DB service looks like this:

```js
DB.get().<get|post|put>(...)...
```

Separate the DB service so that the `get()` call is not required for the general use case.

**Comment by alxndrsn** [comment]
As suggested by @garethbowen.  Any more background v. welcome.

**Comment by alxndrsn** [comment]
Looks good; shame we still need to _call_ `DB`, i.e. `DB().get(someId)` rather than `DB.get(someId)`.

**Comment by alxndrsn** [comment]
Also was quite hard to review as 4 separate commits.

**Comment by garethbowen** [comment]
Sorry about the four commits. I managed to break it up as three distinct refactorings: split out the watch ddoc service, combine get and getRemote, then actually fix the problem. I thought it would be easier to do in these stages than all in one.

**Comment by ngaruko** [comment]
This looks more like a code refactoring issue. is there anything to AT here @alxndrsn @garethbowen ?

**Comment by garethbowen** [comment]
No AT required.
