### ISSUE TITLE
Make enketo tests reliable

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1462]
An Enketo test on [travis](https://travis-ci.org/medic/medic-webapp/jobs/86429029) fails about 50% of the time, but never seems to fail locally. Investigate why.

```
 SUCCESS (0 secs / 0.365 secs)
 SUCCESS (0 secs / 0.367 secs)
 SUCCESS (0 secs / 0.369 secs)
Firefox 31.0.0 (Linux 0.0.0) Enketo service render return error when form initialisation fails FAILED
	timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Firefox 31.0.0 (Linux 0.0.0): Executed 154 of 329 (1 FAILED) (0 secs / 2.37 secs)
 (1 FAILED) (0 secs / 2.386 secs)
20 10 2015 16:04:43.441:WARN [web-server]: 404: /myobjurl
 (1 FAILED) (0 secs / 2.408 secs)
 (1 FAILED) (0 secs / 2.424 secs)
 (1 FAILED) (0 secs / 2.435 secs)
```

**Comment by garethbowen** [comment]
The root issue is every time we use $q we have to digest the rootscope to have angular resolve the promise. This is fine for simple queries but in the Enketo service we have multiple nested promises. In the test I attempted to digest the correct number of times based on how deep the promises went but I think there was a timing issue on travis.

The solution I've gone with is to use the Q library instead of $q for this one test suite. $q is a subset of Q with the additional feature of integrating with the angular scope which isn't needed in testing.

I think the bottom line is these tests are testing too much. Ideally we would break them down so we didn't have nested promises and the issue would go away and the testing would be much clearer. But this will do for now...

**Comment by garethbowen** [comment]
Ignore those last two commits when code reviewing...

**Comment by alxndrsn** [comment]
Neat fix.  I definitely agree that

> this will do for now...

Do you really want to use `$q.defer(); ...; return $q.promise` instead of `return $q(function(resolve, reject) { ...`?

I think the latter is closer to the standard `Promise` spec.

**Comment by garethbowen** [comment]
You're right, the latter is nicer and more standard, but it's not supported by `Q`. I wish angular provided a mock `$q` service that we could use...
