### ISSUE TITLE
Acknowledge completion/submission of report using a transient flash-style message

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1463]
Users have reported that, after submitting a report from the Techno Y4, they're unclear as to whether or not the operation was successful. Add an explicit acknowledgement that auto-dismisses with no user interaction required.

**Comment by alxndrsn** [comment]
May want to use [toasts on android](https://developer.android.com/guide/topics/ui/notifiers/toasts.html).

**Comment by garethbowen** [comment]
Except probably go for an HTML solution so it helps desktop and mobile web users too!

**Comment by abbyad** [comment]
@diannakane can help with design here too if needed.

**Comment by diannakane** [comment]
I have submitted several forms but haven't seen a submission confirmation message yet.

**Comment by mandric** [comment]
Dianna, can you give the exact steps, also was it on the device or on your desktop?  Did you use a specific instance of LG (lg.dev vs lg.app)?

**Comment by abbyad** [comment]
My understanding is that Dianna was using the mobile app, meaning she was using lg.app which does not have this feature.

@diannakane you can test using lg.dev in a browser.

**Comment by abbyad** [comment]
I have seen this now working in desktop mode. Any UI changes can be dealt with a separate issue.
