### ISSUE TITLE
Find a way for users to efficiently navigate between fields and use the Next button while a mobile device keyboard is active

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1464]
Users have reported that the keyboard obscures the Enketo `Next` button. Investigate ways to resolve this, including adding hints to `input` fields so that the device presents in-keyboard `Next Field` and `Done` buttons.

**Comment by alxndrsn** [comment]
Looks relevant: https://stackoverflow.com/questions/23470439/replace-go-button-on-soft-keyboard-with-next-in-phonegap

**Comment by alxndrsn** [comment]
Issues:
- [ ] next field selects nicely, but keyboard disappears, so the user has to click on it an extra time
- [ ] if followed by a textarea, textarea will start with a blank line
- [ ] if there is a Prev button, this will be hilighted instead of the next button being clicked

**Comment by alxndrsn** [comment]
Fixed https://github.com/medic/medic-api/issues/34 as part of this issue.
