### ISSUE TITLE
Move "Change Password" option to a less-prominent location

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1465]
We've received feedback that users are unlikely to use the `Change Password` function. Move it to a less-prominent place (e.g. a configuration/settings screen) to free up screen real estate.

Related: ensure we have a strategy for generating secure default passwords for each user that are easy to enter. The `gpw` utility does a reasonable job of this (it uses trigraphs to generate meaningless but pronounceable English-looking "words").

**Comment by garethbowen** [comment]
I've split the "related" bit off into another issue: #1472

**Comment by garethbowen** [comment]
I've added a simple crude edit user configuration page. At some point we should include the forms inline in the page rather than just launching a modal but this will do for the LG field test.

**Comment by garethbowen** [comment]
The commit for this issue is: https://github.com/medic/medic-webapp/commit/fd07756cc0b7a320003f56985e2856556c022afc

**Comment by abbyad** [comment]
Looks good, moving to Ready.
