### ISSUE TITLE
Back button behaviour not consistent on Contacts tab

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#1466]
Clicking the back button on a family member's page returns you to the full contacts page, rather than that person's family page.

**Comment by garethbowen** [comment]
Related, or part of: #1459

**Comment by abbyad** [comment]
Even after 1459 that may be the expected behaviour... as it depends where you came from. If you came from the contact list you will go back to the contact list, but if you came from the family you will go back to the family.

**Comment by diannakane** [comment]
I think that's the bug. I came from the family and it takes me back to the
contacts list.

On Tue, Oct 20, 2015 at 4:50 PM, Marc Abbyad <notifications@github.com>
wrote:

> Even after 1459 that may be the expected behaviour... as it depends where
> you came from. If you came from the contact list you will go back to the
> contact list, but if you came from the family you will go back to the
> family.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1466#issuecomment-149737425>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by abbyad** [comment]
Ok, in that case it should be fixed with the work being done for 1459. We can retest once that is complete.
