### ISSUE TITLE
Contacts are not removed from LHS on delete

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1467]
# Config

* chrome
* commit: af4d5eb77a84d2c216728cb73c275c5f1da3149f

# Steps to recreate

## Contacts

1. browse to _Contacts_ tab
1. select a contact
1. in the action bar, click _Delete_ 
1. in the Confirm dialog, click _Delete_
1. observe that you have returned to the contact list, but the contact is still visible
1. curse quietly into your latte

## Reports

1. browse to _Reports_ tab
1. select a report
1. in the action bar, click _Delete_ 
1. in the Confirm dialog, click _Delete_
1. observe that you have returned to the report list, but the report is still visible
1. curse quietly into your cappuccino

## Messages

1. browse to _Messages_ tab
1. select a conversation
1. in one of the individual messages, click the trash can icon 
1. in the Confirm dialog, click _Delete_
1. observe that you are still looking at the same conversation, and no messages have been removed
1. curse quietly into your mocha

**Comment by browndav** [comment]
Seeing this here locally too.

**Comment by garethbowen** [comment]
I think all these screens use the Changes service to get notifications about Pouch updates so the bug is probably in there somewhere.

**Comment by garethbowen** [comment]
An interesting test would be if it happens in Couch _and_ Pouch.

**Comment by alxndrsn** [comment]
I've only tested with couch.

**Comment by garethbowen** [comment]
Keep an eye on the `_changes` requests in the Network panel - if they're not running that's the problem, if they're running but not being completed and recreated on change then that's the problem. Everything else will be in the logic of the Changes service.

**Comment by alxndrsn** [comment]
Not sure how this stuff ever worked before.  Is the `quiet` update of contacts and reports a new feature?

**Comment by mandric** [comment]
Few minor comments in code review. Moved to acceptance testing.

**Comment by garethbowen** [comment]
Reviewed.
