### ISSUE TITLE
Remove the SettingsP service

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1469]
We have a Settings and a SettingsP service, the latter is a Promise based version of the former. The promise version doesn't use the cache so it regresses on #1174.

Fix this by only have one Settings service and ensuring it uses the cache. The optimal solution is to use promises only but this will be a large refactor. If this isn't possible in a reasonable time, support both in one service by returning a promise, and calling a callback (if provided).

It might also be necessary or at least good to rework the Cache service to be promise based.

**Comment by garethbowen** [comment]
NB: The Cache service calls the callback when the cached resource is updated. It's not valid to resolve a promise more than once so if the Cache service is to become promise based we'll have to use events or some other mechanism to pass on the updates.

**Comment by garethbowen** [comment]
I've added a couple of comments to the commit.

I think ideally Settings would return a promise which fires an event on change. This way consumers could get the current settings with the `.then(...)` just as you'd expect. Then if some consumer wants to be notified of changes they can listen to the `.on('change', ...)` function.

I don't think events are part of the spec or part of the `$q` implementation, but they are commonly used with promises, eg: http://pouchdb.com/api.html#changes

If you have a little more time for this issue it might be easier to change the SettingsP service to work as described above, and then rework the Settings service to call the SettingsP service and listen for changes to fire the callback.

**Comment by alxndrsn** [comment]
@garethbowen please review PR at https://github.com/medic/medic-webapp/pull/1482.  Works for `SettingsP`; passes tests; I'm not familiar enough with `SettingsSrv` to know if it's working as expected in-app.

**Comment by garethbowen** [comment]
This doesn't solve the regression as repeated calls to SettingsP will result in multiple db requests, ie:
> The promise version doesn't use the cache so it regresses on #1174.

**Comment by alxndrsn** [comment]
Please see new PR.

**Comment by garethbowen** [comment]
Nice one. A couple of minor comments in the commit, but feel free to merge and send this to acceptance testing any time.

**Comment by garethbowen** [comment]
@alxndrsn I'm getting "Error triggering listener callback. Error: Callback was already called." from the SettingsP service in Chrome. It's possible Chrome is strict about promises being called multiple times, and it looks like the SettingsP service will resolve the promise on change. Is that right? (line 66 in /services/settings.js)
