### ISSUE TITLE
Prompt the user to refresh when settings have changed

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1470]
This is just like when the appcache is updated, except for settings changes.

This would be really annoying if settings are updated frequently for trivial things so check that we don't expect this to happen often in production.

**Comment by browndav** [comment]
:+1: for the field test.

**Comment by alxndrsn** [comment]
Issues:
- [ ] next field selects nicely, but keyboard disappears, so the user has to click on it an extra time
- [ ] if followed by a textarea, textarea will start with a blank line
- [ ] if there is a Prev button, this will be hilighted instead of the next button being clicked

**Comment by abbyad** [comment]
This works well. Moving to Ready.
