### ISSUE TITLE
Prompt users to change password on first login

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1471]
Admins create users with a password and then communicate this password to the user. At this point the password can not be considered private information.

When a user first logs in display a prompt requiring them to change password.

This has implications for #856 so consider this when deciding on implementation.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
I assume this has been superseded.  @garethbowen please re-open if I'm mistaken.
