### ISSUE TITLE
Password strength requirements

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1472]
Exactly what the requirements should be is up for debate, but I can say for sure single character passwords should not be acceptable.

Related: ensure we have a strategy for generating secure default passwords for each user that are easy to enter. The gpw utility does a reasonable job of this (it uses trigraphs to generate meaningless but pronounceable English-looking "words").

**Comment by alxndrsn** [comment]
Moving to backlog as no milestone is assigned.

**Comment by garethbowen** [comment]
Some discussion here: https://docs.google.com/document/d/1VXM8KIJnBBGMVP4O9_IrelBTAUu_6DAqF6n-Ey_9XQQ/edit

**Comment by alxndrsn** [comment]
A fun tool for checking password strength: https://www.grc.com/haystack.htm

Something like this, with a min length 8 and min score 60 looks ok: https://stackoverflow.com/questions/948172/password-strength-meter

We may want slightly different rules depending on a user's role (although this could be worked around - e.g. change password first and then change role).

**Comment by alxndrsn** [comment]
I recommend that this password complexity checker is implemented in the Users configuration UI in webapp.

**Comment by garethbowen** [comment]
> I recommend that this password complexity checker is implemented in the Users configuration UI in webapp.

Agreed. We should also update the users controller in api so users uploaded via a script can be checked.

The only other way users can be added is directly into couchdb. This is hard to protect against. We could check on login but that could be frustrating for the user and potentially regress existing users. I suggest we ignore this for now - it's probably not used much, and we're working on making it harder to access couchdb directly.

The only other thing to decide is what strength requirements we want. I propose we only fail on passwords shorter than 8 characters and common passwords (available on [npm](https://www.npmjs.com/package/common-password)).

We could use [zxcvbn](https://www.npmjs.com/package/zxcvbn) to do a much more advanced check involving repeating characters, different character classes, etc but this increases the bundle size by around 400kB which is too large for a marginal improvement IMO.

**Comment by alxndrsn** [comment]
> I propose we only fail on passwords shorter than 8 characters and common passwords

I propose we use the code from this answer, combined with a minimum length requirement: https://stackoverflow.com/questions/948172/password-strength-meter#answer-11268104

**Comment by garethbowen** [comment]
@alxndrsn @bishwas-medic pointed out that medic-gateway doesn't log in when the password has [certain characters](https://github.com/medic/medic-gateway#passwords). He suggested I forbid those characters when setting a password which makes a lot of sense. However it seems like a bug in medic-gateway. Why do those characters not work? Can't we encode them or something?

**Comment by alxndrsn** [comment]
> Why do those characters not work? Can't we encode them or something?

Try putting one of those characters in an HTTP auth password in your browser's address bar...

**Comment by garethbowen** [comment]
@alxndrsn Yeah but can you encode them or something?

**Comment by garethbowen** [comment]
@alxndrsn For example, this is what Node does:

> Invalid URL characters included in the value assigned to the password property are percent-encoded. Note that the selection of which characters to percent-encode may vary somewhat from what the url.parse() and url.format() methods would produce.

https://nodejs.org/api/url.html#url_url_password

**Comment by alxndrsn** [comment]
I could make `medic-gateway` work with these characters, but still neither `curl` nor Firefox would support them.  I have no idea what `collect` support will be like for these characters.  I think it's probably more helpful to exclude them from allowed characters for API-based accounts.

**Comment by alxndrsn** [comment]
AFAIK percent encoding is not included in the Basic Auth spec, so implementing this encoding would be questionable.

**Comment by garethbowen** [comment]
This needs testing but I'm sure curl and Firefox will work if you percent encode the user/pass. Percent encoding is part of the URL spec not part of basic auth. We should fix collect and gateway and everywhere else to encode properly rather than impose arbitrary limits on password characters.

**Comment by alxndrsn** [comment]
👍

**Comment by alxndrsn** [comment]
Although possibly interesting: https://stackoverflow.com/questions/6718471/escaping-username-characters-in-basic-auth-urls

**Comment by garethbowen** [comment]
Hopefully it's as easy as running the username and password through [URLEncoder](https://developer.android.com/reference/java/net/URLEncoder.html)

**Comment by alxndrsn** [comment]
I hadn't thought of that 😝

**Comment by alxndrsn** [comment]
Note that gateway will still not support any chars outside US-ASCII range.  You may want to impose this restriction when checking password contents.

**Comment by garethbowen** [comment]
Ok - why not?

**Comment by alxndrsn** [comment]
The spec isn't clear about how they would be encoded, and there are various implementations with patchy support.

**Comment by garethbowen** [comment]
URLEncoder will encode those too so maybe it'll just work?

**Comment by garethbowen** [comment]
Definitely worth testing.

**Comment by alxndrsn** [comment]
You're suggesting the URL-encoding should remain before base-64 encoding?  That definitely sounds incorrect.

**Comment by garethbowen** [comment]
I'm suggesting we test various options.

**Comment by garethbowen** [comment]
Two code reviews please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen , just some minor notes, but other than that nice one!

**Comment by ngaruko** [comment]
LGTM. Just find the error messaging a bit less comprehensive(re: #3704)

**Comment by sglangevin** [comment]
@ngaruko changing the error message should be easy. I'd prefer we return this and update the error message to be more comprehensive before we move this to ready.

@garethbowen is the error message something that we can just change in the default translation? What are the actual requirements for the password?

**Comment by garethbowen** [comment]
@sglangevin Yes. There are two relevant translations to change:

> password.weak = The password is too easy to guess. Include a range of types of characters to increase the score.
> password.length.minimum = The password must be at least {{minimum}} characters long.

The actual requirements are complex. The code generates a score based on the number of different types of characters, the number of unique characters, and the number of characters with weightings in that order. I decided that was too complicated to put in a user facing message so just went with a quick suggestion for how to improve the score. Suggestions welcome...

Another solution as mentioned in #3704 is to have a UI widget which shows a simplified score (red = too weak, orange = ok, green = good) and have it update in real time. This will make it clear when the password is good enough without having to submit the whole form to find out.

**Comment by sglangevin** [comment]
I've updated the `password.weak` translation to be more specific. I think that should cover us for now but I like the idea of having a UI widget. Sounds like we already have an issue for that.
