### ISSUE TITLE
Allow nested fields in XML report display

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1473]
As of #1211, XML form content display only includes fields from the `<outputs>` element.

Extend that functionality to allow nested fields in the `<outputs>` element.

**Comment by abbyad** [comment]
@Lesterng, any proposals for this?

**Comment by abbyad** [comment]
Bringing this up into next iteration for design, following #1938

**Comment by diannakane** [comment]
visual example of the problem 

![pasted image at 2016_02_24 03_42 pm](https://cloud.githubusercontent.com/assets/1675870/13332258/f8531e40-dbb5-11e5-82ab-66b10e802356.png)

**Comment by garethbowen** [comment]
I've made some quick improvements here while waiting for design.

![nesting](https://cloud.githubusercontent.com/assets/2064938/13938347/eb16f068-f031-11e5-9202-bfe0433ee250.png)

Now JSON values are listed in name/value pairs with appropriate nesting. The `inputs` field is hidden by default as that'll never be useful. All other fields (even nested ones) can be hidden by modifying the forms `hidden_fields` property, eg: `group_lmp` will hide all fields nested under the `group_lmp` field, whereas `group_lmp.g_lmp_method` will hide just the lmp method field.

The depth maxes out at 3 so it doesn't get too far across the screen.

These labels can (and should) all be translated for the specific project.

**Comment by browndav** [comment]
Finished. We'll open a new issue for additional design work.
