### ISSUE TITLE
[pouch] contact names with accented letters do not turn up in non-accented searches

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1474]
Contacts whose names contain accented characters (e.g. _Roger Mör_) do not appear in search results when the accent is ommitted (e.g. search for _Mor_)
# Expected behaviour

This bug does not occur when logged in as admin, so is pouch-specific.  I would expect pouch to behave the same as couch, i.e. matching results whether or not the accents are included in the search term.
# Helpful screenshot

<img width="1280" alt="screen shot 2015-10-22 at 10 24 08" src="https://cloud.githubusercontent.com/assets/191496/10660401/12127ef6-78a7-11e5-966a-568c06cecc16.png">

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
Seems like now the search doesn't work at all for non-ascii chars, whether pouch or couch. Closing in favor of #3392.

**Comment by estellecomment** [comment]
Actually, it's still there. 
See details in duplicate issue : https://github.com/medic/medic-webapp/issues/3533#issuecomment-307067116

**Comment by alxndrsn** [comment]
New ticket has more relevant info - closing in favour of #3533
