### ISSUE TITLE
Hide some output fields when rendering XForm

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1476]
With #1211 the Enketo form is rendered, but only the fields in `outputs` get attached to the doc. For most forms there are fields that we want attached, but not rendered (eg patient_id, place_id). We want to find a way to designate the fields that we don't want rendered, but still attached to the doc.

**Comment by alxndrsn** [comment]
Two obvious ways to handle this:

## 1. separate XML nodes, mapping to separate JSON objects:

```xml
<outputs>
  <displayed>
    ...
  </displayed>
  <hidden>
    ...
  </hidden>
</outputs>
```
->
```javascript
doc: {
  displayed: {
    ...
  },
  hidden: {
    ...
  }
}
```

## 2. tags in xml model:
```xml
<outputs>
  <field1/> <!-- this will be displayed -->
  <field2 tag="hidden"/> <!-- this will be hidden -->
</outputs>
```
The JSON mapping is not as obvious from here, but perhaps:
```js
doc: {
  field1: ...,
  field2: ...,
  hidden: [ 'field2' ]
}
```

# Notes

Obviously either XML notation could map to either JSON notation (or something else), but JSON notation selected should be compatible with what already exists.

**Comment by alxndrsn** [comment]
Add `tag="hidden"` to items in the form model's `<outputs>` which you want hidden in the reports-content.

**Comment by garethbowen** [comment]
Relevant commit: https://github.com/medic/medic-webapp/commit/558921243a6519c81454a63b7418bae22ee8e4bf

**Comment by garethbowen** [comment]
Minor comment on the commit.

**Comment by abbyad** [comment]
Works well, moving to ready.
