### ISSUE TITLE
Make sure that content is consistent across phones using same account

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1478]
Issue reported from Fred's demo with CHPs:

> Different form views and content of the app were showed on the 2 phones we loaded despite being from the same installation file(apk)- we weren't sure what caused that.

**Comment by abbyad** [comment]
In theory this has been fixed... @sglangevin, please confirm that this has been resolved.

**Comment by sglangevin** [comment]
This was resolved long ago. Closing.
