### ISSUE TITLE
Document configuration for xforms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1480]
As part of getting v0.6 ready for production we need to prepare documentation/guides for tech-leads to configure and deploy instances of medic-webapp.

**Comment by garethbowen** [comment]
Removed task configuration documentation as that's covered by #1345

**Comment by SCdF** [comment]
@abbyad can you talk a bit more about this? Is this still relevant? Has this been done? Do you feel like this is documented enough?

**Comment by abbyad** [comment]
We still need to document this, feel free to assign to me for this iteration.

**Comment by abbyad** [comment]
We have internal documentation [here](https://docs.google.com/document/d/1ntLwHSwkERllHE_VZk4JG85z9mNSytqVTacKBhULcJE/edit#). We can open a new issue when/if we need to provide external facing documentation.
