### ISSUE TITLE
Exporting reports fails with a 404

### ISSUE THREAD

**Issue by yembrick** [medic/medic-webapp#1484]
Our current Middleware accesses data from the webapp by exporting data (through export URLs). 

For the LG field test, before their comprehensive Analytics are available (requiring postgres), we have planned to provide some basic activity monitoring with our existing Middleware. The new forms engine has changed data storage, and hence exports are not currently available. To get the activity monitoring in Middleware up and running, we are going to need to have exports working. 

Ideally we have the monitoring tools set up in time for the CHP launch right after training. Bryan and I ideally need a week to get Middleware up and running and thoroughly tested with their specific metrics. 

cc @browndav @abbyad @joshnesbit @btbonval

**Comment by garethbowen** [comment]
@yembrick Thanks for raising this. Do you have any more information on how exports isn't working for you? Do you know what URL(s) the middleware is requesting? Is the export failing with an error, or is the data incorrect?

**Comment by yembrick** [comment]
@garethbowen heres an example URL

https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/export/forms/HH?startkey=%5Btrue%2C%22HH%22%2C%7B%7D%5D%0A&endkey=%5Btrue%2C%22HH%22%2C0%5D&include_docs=true&descending=true

Im just getting a 404 actually. Theres a chance im not using a valid form name (HH I think is the household form name, but that could be wrong). I looked around on the export screen in config in the web app on the LG instance and didn't see any links to download form data. I would have tried grabbing the URL from there directly. 

Thanks!

**Comment by garethbowen** [comment]
@yembrick Thanks! I get the same error.

That's the old style of export URL. On deployments running 0.5 or later (like LG is) it's better to use the new api. Try this URL instead: https://lg.app.medicmobile.org/api/v1/export/forms/HH?startkey=[true%2C%22HH%22%2C{}]%0A&endkey=[true%2C%22HH%22%2C0]&include_docs=true&descending=true

I'll fix the old URL so it works, but using the "/api/v1" URL will get you up and running right away.

I suspect you'll find more bugs with the download such as fields not populating due to switching to Enketo because it's such a big change.

**Comment by yembrick** [comment]
OK yea Im still used to working 0.4 pretty much, so havent run into that yet. I do get data with this URL so thats great! @btbonval any red flags you see plugging this structure right into Middleware? 

@garethbowen or @abbyad where can I look to get the most up to date forms so I can compare and make sure all fields are exporting? (also is the file live so I can check again when forms are finalized)? 

Along with that, can someone let us know the list of form codes to use?

**Comment by garethbowen** [comment]
Notes for code review: the path needed the leading `/`, but even then it wasn't redirecting correctly because it was stripping off the query parameters. It's not simple to pass through all parameters so I'm using array matching for the route instead of the redirect.

**Comment by btbonval** [comment]
@yembrick made the URL changes and data comes in for HH. No patient IDs, but I'm guessing that is the nature of the form. I don't see any obvious problems but I also don't know what I'm looking at with the HH form.
