### ISSUE TITLE
Placeholder text for Targets tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1492]
Reported by @joshnesbit for the field test:

Update the Targets tab with placeholder text. Eg "Your progress towards your targets will be displayed here." If possible, display number # of families registered as a placeholder along with the above message.

**Comment by garethbowen** [comment]
I've added a feature to hide the analytics module dropdown if there's only one to chose from. The "targets" module is hardcoded to be enabled but this will change when we have some configuration to inspect. To disable the ANC Analytics module unset one of the ANC Forms configurations in app_settings.

**Comment by garethbowen** [comment]
Please forgive the non-internationalised content - this will be removed when we complete the feature.

**Comment by abbyad** [comment]
Looks good, thanks @garethbowen. Moving to Ready.
