### ISSUE TITLE
LG-specific translations have been overwritten in API

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1497]
This commit has removed a lot of LG-specific translations from `medic-api`: https://github.com/medic/medic-api/commit/81ba5965659ce00c7439ea12310733f542ae9bbe

**Comment by abbyad** [comment]
We need to figure out how to maintain both variants (DIY vs project specific). Let me know where we should keep each of these and I can update our translation process accordingly.

**Comment by alxndrsn** [comment]
LG should currently be on `develop`; DIY should have its own branch atm.

**Comment by alxndrsn** [comment]
Would it be sufficient to roll back the recent commits from Medic Translators on the `develop` branch?

**Comment by abbyad** [comment]
It would be sufficient for LG, but breaks our translation process.

**Comment by abbyad** [comment]
For reference: https://github.com/medic/medic-docs/blob/master/md/dev/translations.md

**Comment by garethbowen** [comment]
I don't think we should be changing the DIY ones for LG. They should just be overwritten in  medic-projects/lg-uganda/app_settings.json instead. If this is a problem for integration with POE we could add .properties files to the project folder to integrate with.

**Comment by browndav** [comment]
I think I agree with Gareth here. I guess the proposal is this: make LG-specific changes in `medic-projects/lg-uganda/app_settings.json` for now, and then go back and add `.properties` files to make the translation process work via POE once some time pressure is relieved and we have a couple DIY iterations scheduled.

**Comment by alxndrsn** [comment]
Done in PR - please review https://github.com/medic/medic-projects/pull/61
