### ISSUE TITLE
Unexpected back action from edit mode

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#1498]
Hitting back while in edit mode for a form took me back to the history / reports page. I expected to return to the form page where I originally hit edit. 

1.
![screen shot 2015-10-30 at 11 00 25](https://cloud.githubusercontent.com/assets/1675870/10853895/e34e9ed8-7ef5-11e5-87b4-4823abcc0c3d.png)
2.
![screen shot 2015-10-30 at 11 00 30](https://cloud.githubusercontent.com/assets/1675870/10853897/e445cd52-7ef5-11e5-9e30-90ba3288edd0.png)
3.
![screen shot 2015-10-30 at 11 00 32](https://cloud.githubusercontent.com/assets/1675870/10853939/24392d28-7ef6-11e5-8645-a636111922e2.png)

**Comment by garethbowen** [comment]
Related: #1459

**Comment by garethbowen** [comment]
This is probably fixed by #1459 - closing for Acceptance Testing.
