### ISSUE TITLE
strange representation of age in patient summary 

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#1499]
This page is looking awesome!  However, I am quite confused about how old Jenny is .... 
![screen shot 2015-10-30 at 10 58 46](https://cloud.githubusercontent.com/assets/1675870/10854373/84cc915a-7ef8-11e5-911b-23ac371d186d.png)

**Comment by abbyad** [comment]
Thanks for reporting that @diannakane, this is still in progress :)

The basic structure is there, but the finer elements are not complete yet (eg formatting of age and treatment sections).

**Comment by abbyad** [comment]
The `AASS` in the topbar should be "Assess Patient" though... that seems to be a bug.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
Closing as this has long been resolved.
