### ISSUE TITLE
Form ID showing instead of name

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1501]
The `Assess Patient` label is shown under Actions, but the ID (`AASS`) is shown in History list.

![image](https://cloud.githubusercontent.com/assets/789512/10857125/a73e49ac-7f22-11e5-877a-b96bc10b6c2e.png)

![image](https://cloud.githubusercontent.com/assets/789512/10857205/23d8ec10-7f23-11e5-9816-c5753e70be82.png)

![image](https://cloud.githubusercontent.com/assets/789512/10857184/ff074d0a-7f22-11e5-9350-0a8a32591a22.png)

**Comment by abbyad** [comment]
The form names that do show up are the ones that have JSON forms with the same code. There are probably a couple of other hidden issues if we don't use the JSON form at all - eg the form list in the Reports tab filter contains only JSON forms, not XForms.

**Comment by alxndrsn** [comment]
The form's human-readable name is not attached to individual `report` instances.  Either it should be, or we should look this up when populating `selected.reports` in `ContactsContentCtrl`, likely inside the `getReports()` method.

**Comment by joshnesbit** [comment]
I don't think this is a blocker for the field test.

**Comment by alxndrsn** [comment]
For the field test, could we change the form IDs to match their names?

**Comment by abbyad** [comment]
The form IDs are close to the names, but in general all lower and `_` instead of names. The title is already in the doc and used in some places in the app... so it is probably easier (and better) to just use the title than hacking the ID.

```
{
   "_id": "form:family_survey",
   "_rev": "5-51b0159fbe3ed79b86a2d1b7c4c2aaee",
   "type": "form",
   "title": "Family Survey",
   "internalId": "family_survey",
   "context": {
       "person": false,
       "place": true
   },
   "_attachments": {
       "xml": {
           "content_type": "text/xml",
           "revpos": 5,
           "digest": "md5-BTjGz0pOrL2cnz80rkcMag==",
           "length": 5776,
           "stub": true
       }
   }
}
```
