### ISSUE TITLE
Longpoll requests are being cancelled

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1503]
Logged in to lg.dev as the restricted user.

In my Network all longpoll requests get cancelled at exactly 30 seconds:

![network](https://cloud.githubusercontent.com/assets/2064938/10871509/0f33b42a-814e-11e5-8867-44f0c3cbd939.png)

The requests that get cancelled are:

```
https://lg.dev.medicmobile.org/medic/_changes?timeout=25000&heartbeat=10000&filter=_doc_ids&doc_ids=%5B%22_design%2Fmedic%22%5D&since=6993&limit=25&_nonce=1446409895241&feed=longpoll
https://lg.dev.medicmobile.org/medic/_changes?timeout=25000&style=all_docs&heartbeat=10000&filter=medic%2Fdoc_by_place&id=6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E&since=6991&limit=100&_nonce=1446409916623&feed=longpoll
```
But the following one succeeds. Note the absence of "longpoll" which means it's a single request but otherwise identical to the above:

```
https://lg.dev.medicmobile.org/medic/_changes?timeout=25000&style=all_docs&heartbeat=10000&filter=medic%2Fdoc_by_place&id=6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E&since=6991&limit=100&_nonce=1446409916390
```
We also get a lot of recurring errors in the console (spurious CORS errors omitted for clarity):

```
Error watching for changes on the design doc e
Uncaught (in promise) e
Error watching for changes on the design doc e
Error watching for changes on the design doc e
Uncaught (in promise) e
Error watching for changes on the design doc e
```

It looks like pouchdb expects couchdb should timeout cleanly after 25000 but from [the docs](https://couchdb.readthedocs.org/en/1.4.x/changes.html), if a heartbeat is supplied couchdb ignores the timeout.

> heartbeat: Period in milliseconds after which an empty line is sent in the results. Only applicable for longpoll or continuous feeds. Overrides any timeout to keep the feed alive indefinitely.

On my local machine without nginx these requests remain pending forever which is why I suspect it's nginx that's doing the request cancellation.

Initially I thought this might be part of our replication issues ( #1341 ) but replication appears to work as expected so I think it just causes lots of unnecessary connections and confusing error messages.

The fix is to configure nginx to have a longer (infinite?) timeout on any longpoll request. Also consider patching pouchdb so the timeout header is only included when the heartbeat header is not.

**Comment by garethbowen** [comment]
It turns out pouchdb sets a 30 second timeout on changes feeds, even live ones. I've made a change to override this to 1 hour. If this fixes the issue I'll raise an issue against pouch because it seems illogical to me that live changes feeds would timeout.

**Comment by garethbowen** [comment]
PouchDB 5.1 adds features for setting the heartbeat on changes feeds which solves the issue, but this hasn't been exposed to the replication api, so it's only a partial solution. I've raised a series of issues against pouch to improve this: pouchdb/pouchdb#4538 pouchdb/pouchdb#4539 pouchdb/pouchdb#4540 pouchdb/pouchdb#4541

**Comment by browndav** [comment]
This workaround appears to fix the problem reliably for me on the Y4 and on Chromium 30. Moving to code review.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by garethbowen** [comment]
Assigned to @estellecomment for code review.

**Comment by estellecomment** [comment]
Code LGTM.
All the issues you raised with pouch are fixed now! Does that get rid of the monkeypatch?

**Comment by garethbowen** [comment]
Yes, the monkey patch was removed as part of #1636
