### ISSUE TITLE
Access the children of a place via a task rule

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1504]
We have surveys to ask how many children are under 5 in a family, and want to create a task to register children accordingly. Currently the task rules cannot access the children from a family to know whether to create a task.

**Comment by browndav** [comment]
This was missed in today's milestone retrospective/review call. Proposal: discuss along with the feedback from tomorrow's demo sessions.

**Comment by joshnesbit** [comment]
For the field test, I suggest that we leave the new family form as is. It works and we haven't received feedback that this task is critical. I can see how it'd be useful in the future.

**Comment by abbyad** [comment]
This can be reopened if needed.
