### ISSUE TITLE
Task action to add a person

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1505]
Task actions can call forms, but not create a family or person. For our current needs we need to add a person (`contact:person:create`) and have it create the person (not be submitted as a report)

**Comment by browndav** [comment]
This was missed in today's milestone retrospective/review call. Proposal: discuss along with the feedback from tomorrow's demo sessions.

**Comment by garethbowen** [comment]
For now this can just link through to the Contact context rather than trying to make it work in the Task context.

**Comment by garethbowen** [comment]
Example configuration:
```js
if (c.contact && c.contact.parent) {
  visit.actions.push({
    type: 'contact', // indicates this action is to create a new contact (required)
    label: 'Add new family member', // the button label (required)
    content: {
      type: 'person', // the type of contact to create (required)
      parent_id: c.contact.parent._id // the id of the parent for the new contact (required)
    }
  });
}
```
