### ISSUE TITLE
Data validation is different for "Add Contact" vs "Edit Contact"

### ISSUE THREAD

**Issue by guptasanchay** [medic/medic-webapp#1508]
App accepts information like DOB and phone numbers when contact is first created, but when I go in to edit contact information and then try and hit submit, the system prompts "Value not allowed"

<img width="1098" alt="screen shot 2015-11-02 at 12 35 30 pm" src="https://cloud.githubusercontent.com/assets/15477845/10893625/b32346b2-815e-11e5-9de6-af7e9c47e235.png">

**Comment by browndav** [comment]
Quick question: do you consider the desired behavior to be "accept in both cases" or "reject in both cases"? The phone numbers should be auto-verified with `libphonenumber`, which is a library that knows the numbering rules for every country and locale on Earth (thanks to Google); numbers that aren't actually assignable by a telco should fail to validate in both cases, at least according to our original design.

**Comment by alxndrsn** [comment]
The phone number issue appears to be caused by invalid numbers being entered in the first place, likely courtesy of mis-configured forms.

I will investigate the date issue.

**Comment by alxndrsn** [comment]
I cannot recreate the problem for date:

<img width="1280" alt="screen shot 2015-11-11 at 11 52 34" src="https://cloud.githubusercontent.com/assets/191496/11089529/b8d28506-886a-11e5-92ba-c205637104c1.png">
