### ISSUE TITLE
"New Contact" versus "New Place" ambiguity

### ISSUE THREAD

**Issue by guptasanchay** [medic/medic-webapp#1509]
At the bottom of the contacts tab, there's a button with a building on it that when selected opens up a contact form.  

<img width="361" alt="screen shot 2015-11-02 at 12 53 22 pm" src="https://cloud.githubusercontent.com/assets/15477845/10894021/e5fc7962-8160-11e5-88a4-13036c9e37e2.png">

Should the image on the button be changed to represent a person as opposed to a place?

When I click on the button, it says  "New Place" at the top of the next screen, but the form itself asks for information about a new contact. 

<img width="367" alt="screen shot 2015-11-02 at 12 48 05 pm" src="https://cloud.githubusercontent.com/assets/15477845/10894028/ec59b7a2-8160-11e5-97d3-318dca6e2aa5.png">

 Should the title of the form be changed to "New Contact"?

**Comment by abbyad** [comment]
The labels are out of sync, we are working on fixing this.

**Comment by guptasanchay** [comment]
Sounds good. On a similar note, when you pull up the family contact, the primary caregiver shows up as Last First, while other family members show up as First Last

<img width="412" alt="screen shot 2015-11-02 at 1 17 52 pm" src="https://cloud.githubusercontent.com/assets/15477845/10894566/4ef662e0-8164-11e5-9046-a4bc0045e30e.png">

**Comment by SCdF** [comment]
@garethbowen please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by garethbowen** [comment]
Closing as this was fixed by the people tab refactor: #2341

@guptasanchay Please reopen (or open a new issue) if there's more to do.
