### ISSUE TITLE
Duplication of possible actions

### ISSUE THREAD

**Issue by guptasanchay** [medic/medic-webapp#1510]
In the contacts section, after selecting an individual or family, there is some duplication among possible actions. In this example, a link to the "Assess Patient" form appears twice.

<img width="357" alt="screen shot 2015-11-02 at 1 02 12 pm" src="https://cloud.githubusercontent.com/assets/15477845/10894218/1ddf04c0-8162-11e5-9886-a2f96fc2dbc8.png">

**Comment by abbyad** [comment]
This is the same as https://github.com/medic/medic-webapp/issues/1542.
