### ISSUE TITLE
Naming Conventions 

### ISSUE THREAD

**Issue by guptasanchay** [medic/medic-webapp#1511]
On the contacts page, names should continue to be listed as Last Name, First Name (which I believe is currently happening).  On the forms themselves though, should the First Name Last Name convention be preserved for easy readability?

In this screenshot, references to Alice Nguyen show up as "Nguyen Alice"

<img width="361" alt="screen shot 2015-11-02 at 1 10 04 pm" src="https://cloud.githubusercontent.com/assets/15477845/10894415/4caab5dc-8163-11e5-9cee-19e058dc2c5d.png">

**Comment by alxndrsn** [comment]
If last name always comes first, and first name always comes last, then isn't Last Name actually the first name, and First Name actually the last name?

**Comment by abbyad** [comment]
The convention used in Uganda is to always show "Surname GivenName", so we are using this throughout for this deployment. 

If you see the name differently anywhere for a newly created contact please report!
