### ISSUE TITLE
Phone number validation doesn't work for demo user

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1517]
Right now, when I add a family, I can enter *any* number for the phone number. 

I expect this question to have a validation, checking that it's a number with a country code or a Ugandan number without the country code (format 07xxxxxxx). The second one is most important for the field test.

Below are screenshots for entering "3" as the primary phone number:

![screen shot 2015-11-03 at 9 59 33 am](https://cloud.githubusercontent.com/assets/377216/10916752/e2688ffa-8211-11e5-94bb-acec037f42a4.png)

![screen shot 2015-11-03 at 9 59 41 am](https://cloud.githubusercontent.com/assets/377216/10916756/e6cc6b70-8211-11e5-8dd7-f21f803f89bd.png)

![screen shot 2015-11-03 at 9 59 47 am](https://cloud.githubusercontent.com/assets/377216/10916757/e9a0f1fe-8211-11e5-8c0c-8fbfaa091d30.png)

**Comment by browndav** [comment]
I think we have this filed by Sanchay also; looks like the libphonenumber validation is inexplicably being applied at edit time but not at creation-time.

**Comment by abbyad** [comment]
This works for admin users, but not for restricted users. Possibly because the `tel` validation needs to query the full db to test for phone number uniqueness?

**Comment by alxndrsn** [comment]
@abbyad interesting!  for non-admins it should just be querying via pouch, so i'd expect it to query the locally-available phone numbers...

**Comment by alxndrsn** [comment]
@browndav explicable because create and edit use different forms

**Comment by abbyad** [comment]
We are currently using the `tel` type which does uniqueness and validation for the phone number. Uniqueness requires the full db, hence available only to admin users because they are not using the local db.

In this particular scenario we actually only need to validate the number, not verify uniqueness, so we may need to look at having a `tel` type that does validation only.

**Comment by alxndrsn** [comment]
1. Do we ever need a unique `tel` type?
2. Is there any value in checking uniqueness against the local DB?

**Comment by browndav** [comment]
What about just skipping the uniqueness check if we're not in direct-to-CouchDB mode?

**Comment by abbyad** [comment]
> Do we ever need a unique tel type?

For the field test no, but yes for prior projects where we needed to attribute incoming message to a specific person/place.

> Is there any value in checking uniqueness against the local DB?

Probably not as we dont have an immediate need for it. We may find a use for it down the line, but we can implement it when needed.

> What about just skipping the uniqueness check if we're not in direct-to-CouchDB mode?

That is fine, except when there is an expectation that it is fully unique - and we would need to be able to resolve conflicts that arise after sync.

**Comment by browndav** [comment]
Investigate if the phone number uniqueness check is causing the validation to misbehave. If it is, remove or disable the uniqueness check altogether – per today's call with Josh, it's not needed for the field test.

**Comment by alxndrsn** [comment]
I think the issue here is that the input field is defined as `string` and not `tel`:

```xml
      <bind nodeset="/data/ephemeral_phone/phone1" type="string"/>
      <bind nodeset="/data/ephemeral_phone/phone2" type="string"/>
```
> — _https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/family.xml#L108_

```xml
    <group appearance="field-list" ref="/data/ephemeral_phone">
      <label>Primary Caregiver</label>
      <input appearance="numbers" ref="/data/ephemeral_phone/phone1">
        <label>Primary Mobile Number</label>
      </input>
```
> — _https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/family.xml#L178_

**Comment by abbyad** [comment]
Thanks @alxndrsn, works now with this change ...except as admin in Chrome... will open a new issue for that.
