### ISSUE TITLE
How does one use medic-data to populate a local couchdb as would be seen in medic-os distro?

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1521]
I'm trying to run integration testing on TravisCI.

For my own integration testing environment, I was running a medic-os image. Here's how many records it has and what databases are on it:
```
$ curl http://bryan:password@192.168.56.101/_all_dbs
["_replicator","_users","dashboard","medic","medic-reporter"]
$ curl http://192.168.56.101/medic/_all_docs > docs
$ wc -l docs
3655 docs
```

Travis doesn't have access to my medic-os VM, but it does have CouchDB installed. I've been having problems with Travis using medic-data.

I made a chroot with couchdb in it to try this for myself. I use these settings and run `make install settings gardener load` to populate CouchDB.
```
export DEMOS_COUCHDB="http://localhost:5984"
export PRELOAD_APP_DATA="diy"
export PRELOAD_APP_MARKET="release"
```

I assume the make targets for `compact copy archive` are for packaging the couchdb up for distribution, which is not my intention.

When I check the current state of the `medic` database, there are far fewer docs:
```
# curl -X GET http://127.0.0.1:5984/_all_dbs
["_replicator","_users","dashboard","medic","medic-reporter"]
# curl -X GET http://127.0.0.1:5984/medic/_all_docs > docs
# wc -l docs 
34 docs
```

If I try the demo dataset, I get an error:
```
export DEMOS_COUCHDB="http://localhost:5984"
export PRELOAD_APP_DATA="demo"
export PRELOAD_APP_MARKET="release"
# make install settings gardener load
...
Set Medic Mobile Reporter security to public...
{"ok":true}
DEMOS_COUCHDB="http://demos:secret@localhost:5984" \
	  node ./scripts/load_settings.js \
	    "./data/generic-anc/demo/app-settings.json" \
	    "./data/generic-anc/demo/forms.json" \
	    "./data/generic-anc/demo/before_load.js"
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/medic-analytics/medic-data/./data/generic-anc/demo/app-settings.json'
```

Not sure what else to try here. I just want to populate a couchdb (on Travis) with the same data that is populated on medic-os.

**Comment by browndav** [comment]
There are fully ready-to-go `.couch` files available on the staging.dev server (beneath `downloads`, as `*.tar.xz` files); just extracting those to the CouchDB data directory and then starting CouchDB would probably give you what you want.

**Comment by btbonval** [comment]
If you can tell me where the CouchDB data directory is on a TravisCI system, I can certainly move forward with that solution.

It sounds like the error I'm getting with trying to build the dataset using `demo` is the real problem.

I'm running this out of a submodule. I need to ensure the submodule is up to date, and if the error persists, I'll file an issue about the error building the `demo` dataset. My submodule is probably out of date though.

**Comment by btbonval** [comment]
My submodule is 26 commits behind master. I'll update it and see if that helps.

**Comment by mandric** [comment]
ps. you can also get doc count by querying the db itself:
```
$ curl -s http://localhost:5984/medic | jq .doc_count
282
```

**Comment by btbonval** [comment]
Thanks @browndav and @mandric . Those two pieces go together nicely. That's what I needed.

Offline, I will fetch https://staging.dev.medicmobile.org/_couch/_utils/database.html?downloads and host it on dev.medicmobile.org's web server with a timestamped filename. I'd rather not have my integration testing data change independently of the software being tested.

as a makefile or shell script:
1. fetch timestamped dataset from dev
1. figure out couch's location on disk (http://localhost:5984/_config/couchdb/database_dir)
1. turn off couchdb (`sudo service make me a sandwich start`)
1. replace couchdb directory
1. turn on couchdb

Example of fetching couch location: https://github.com/medic/medic-data/blob/a2c3dc36f95948bc46b758a2e1ca3a59cd20f4e2/Makefile#L45-L49

Have Travis run that and then I don't need `medic-data` as a submodule which is an improvement.

Closing as resolved. I can always reopen or create a new ticket if there's some particular problem.
