### ISSUE TITLE
Sync Issue - Phone and PC Browser

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1522]
There is still an issue with the data sync from different submission sources: phone and the pc browser, see attached screenshots of search results for "spring" - PC browser returns the family and the members, phone returns only family, with no members.

PC (Firefox):
![screen shot 2015-11-04 at 09 31 45](https://cloud.githubusercontent.com/assets/15346836/10931353/bc6b742c-82d7-11e5-9698-550275ce4f95.png)

Phone:
![screenshot_2015-11-04-09-32-07](https://cloud.githubusercontent.com/assets/15346836/10931368/d403639c-82d7-11e5-8464-6ece4ef980d7.png)

**Comment by garethbowen** [comment]
Related: #1341

**Comment by browndav** [comment]
@fredatthehub: Were you logged in as the `demo` user on both the desktop browser and in the mobile application?

**Comment by joshnesbit** [comment]
Note: In the field test, restricted users (CHPs) will use just one device each.

**Comment by garethbowen** [comment]
I can't see the children when I log in as _admin_ on lg.app either.

@fredatthehub Is this on lg.app? Can you still see the children when you log in?

If so, it could be that you're seeing stale data. This can happen for example, if someone deletes the children through `/_utils`. This change doesn't get replicated so any device which has the children will still display them, but any new device will never get them.

If you can no longer see the children then it'll be very difficult to work out what happened. If you find another example of this please let me know so I can investigate further.

**Comment by browndav** [comment]
I'm seeing HTTP `500`s pretty consistently when the app is attempting to replicate back up to the hosted instance. I'll troubleshoot a bit more today and may spin off a more specific issue from there.

**Comment by browndav** [comment]
@fredatthehub: An update would be appreciated here re: Gareth's questions.

**Comment by browndav** [comment]
I've filed #1570.

**Comment by browndav** [comment]
This appears to still be blocked on answers to @garethbowen's questions. @fredatthehub: If you have a moment to clarify, that'd be really helpful. We'll close this issue by end-of-day Wednesday EAT if we don't hear anything.
