### ISSUE TITLE
select2 dropdown remains on screen when form is gone

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1523]
Start a new pregnancy and open the dropdown to select a person then press the (hardware) back button.  the option menu remains on the screen.  Observed this on a Samsung SIII Android 4.4.2; SAMSUNG-SGH-I747 Build/KOT49H.

It should be destroyed along with its parent (the select element).  Not sure if this is an upstream bug or something in the way we destroy forms.

![screenshot_2015-11-04-16-23-39](https://cloud.githubusercontent.com/assets/25641/10951473/dbf97e2c-8324-11e5-88cc-441a1a37a368.png)

**Comment by alxndrsn** [comment]
This is not a regression.

**Comment by alxndrsn** [comment]
This is likely related to where the `select2` attaches its new elements (`.select2-container`) in the DOM, and may be a config option.

**Comment by alxndrsn** [comment]
There may be a trade-off to be had here:

> You are also not limited to displaying the dropdown within the parent container, which means Select2 will render correctly inside of modals and other small containers. 
> — _https://select2.github.io/options.html#dropdownParent_

For instance, the following may no longer work if we attache to e.g. the modal:

<img width="1280" alt="screen shot 2015-11-05 at 17 21 10" src="https://cloud.githubusercontent.com/assets/191496/10974311/cdeef72c-83e1-11e5-952d-901aebe6e087.png">

**Comment by alxndrsn** [comment]
`select2`s in enketo forms should now be attached to the `.enketo` div.

**Comment by garethbowen** [comment]
Nice.
