### ISSUE TITLE
Move Search debouncing into UI layer

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1527]
The Search service debounces identical queries to protect from searching twice when a user double clicks the search button. We've started using the Search service directly from other services (eg: TaskGenerator) which results in incorrectly debounced queries (see #1516 ). Move the debouncing into the UI layer so it only cancels user requests and not queries from other services.

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
Hi @garethbowen, relaying a message from medic-bot...  is this still relevant?

**Comment by garethbowen** [comment]
It's still relevant but really unimportant. Closing.
