### ISSUE TITLE
Cannot filter `select2` options on android

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1534]
# Context

Editing a Family's Primary Caregiver field on `lg.app` on Tecno phone

# Observed

* can scroll the list
* can select an option by poking it
* typing in the filter box -> _No results found_, even if typing something which is visible in the list!

# Expected

Filtering should work.

# Notes

Not a regression ;¬)

**Comment by mandric** [comment]
I can also reproduce this on my samsung sIII.

**Comment by browndav** [comment]
Deprioritized; Josh reports that the select2 Enketo widgets will not be used during the initial field test.

**Comment by garethbowen** [comment]
Related or duplicate of #1534
