### ISSUE TITLE
Demo user should be able to access all contacts created by demo user

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1539]
We have testers logged in as "demo" on multiple devices. I'm seeing "ghost" contacts, specifically primary caregivers. See the screenshot below:

![screen shot 2015-11-05 at 05 30 07](https://cloud.githubusercontent.com/assets/377216/10969634/92cc3c08-837e-11e5-9ac6-cdbd4736385c.png)

Clicking the link for primary caregiver brings me back to the contacts list.

Right now, I am able to create a new family and see the primary caregiver and other family members properly. I am also able to view contacts I created on my own device previously. This is what we need for the field test, as each user will have their own device. I've been encouraged to file this issue anyway, as it might be related to problems with replication.

**Comment by alxndrsn** [comment]
I think someone deleted _Atim Jane_.  Deleting a contact does not remove other contacts' references to the deleted contact.

**Comment by abbyad** [comment]
I think this has been resolved. @sglangevin can you please confirm?

**Comment by sglangevin** [comment]
This was resolved a while ago. Closing.
