### ISSUE TITLE
[select2] patient is not automatically selected on `Assess Patient` form

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1540]
# Observed

When opening _Assess Patient_ form via a person's _Actions_ list, the first question is _Select Patient_, and has no initial value.

# Expected

Field value should default to the current user.

# Notes

This is likely a regression, and would need fixing in the db-object and/or medic-place enketo widgets.

**Comment by alxndrsn** [comment]
@abbyad & @joshnesbit cannot recreate this issue.

**Comment by alxndrsn** [comment]
Does not occur for me on desktop either.

**Comment by mandric** [comment]
Experiencing something similar on the Edit Person form on my samsung:

1) login with demo/medic
2) select person in contacts
3) click edit icon in FAB 

An Edit Person form loads with empty fields.  I would expect it to have the information of the person I just selected.

**Comment by alxndrsn** [comment]
Fixed for edit-person.
