### ISSUE TITLE
Forms deleted from db still appear in app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1542]
We cannot "retract" a form because it is still shown for restricted users in the mobile app and desktop.

**Comment by garethbowen** [comment]
Instead of deleting in futon, add a `_deleted` property with the value `true`. This behaves identically to pressing the delete button, except that it's also replicated.

**Comment by mandric** [comment]
Wait I thought deleting a doc in couchdb just does this automatically?  I don't think there is any way to remove a doc, it just goes into the rev history with a _deleted property and doesn't get returned, eventually being cleaned up by compaction.   http://docs.couchdb.org/en/1.6.1/api/document/common.html#delete--db-docid

**Comment by mandric** [comment]
Sorry if I'm coming in late here.  Have a feeling "forms deleted from db" means something other than using the Delete option in futon on a doc.

**Comment by garethbowen** [comment]
There are two ways to delete things in couchdb: make a request with a DELETE header, or set _deleted to true. Futon does the former, but only the latter replicates properly.

From [the docs](https://wiki.apache.org/couchdb/Replication#Filtered_Replication): 

> Note: When using filtered replication you should not use the DELETE method to remove documents, but instead use PUT and add a _deleted:true field to the document, preserving the fields required for the filter. Your Document Update Handler should make sure these fields are always present. This will ensure that the filter will propagate deletions properly. 

I don't know why the two methods of deletion do different things, and I don't know why futon does the worse option.

**Comment by mandric** [comment]
Gosh.  We should open an issue for updating the doc update handler then?

**Comment by abbyad** [comment]
Just an update that I updated a form with `_deleted:true` and it is still shown in the mobile app several hours later while on a decent connection. We will likely need to test this further.
