### ISSUE TITLE
[select2] dropdown obscures app-update modal

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1543]
# Dropdowns to fix
- [x] send message
- [x] enketo db-obj
- [x] enketo medic-place
- [x] edit-user
- [x] config-basic
- [x] config-advanced

# Screenshot

![screenshot_2015-11-05-14-38-52](https://cloud.githubusercontent.com/assets/25641/10974863/2534e58a-83cb-11e5-8413-e76de5e47431.png)

**Comment by mandric** [comment]
Here's a mobile screen but i think it happens on the desktop too.
![screenshot_2015-11-05-14-38-52](https://cloud.githubusercontent.com/assets/25641/10974863/2534e58a-83cb-11e5-8413-e76de5e47431.png)

**Comment by garethbowen** [comment]
Looks good to me.
