### ISSUE TITLE
Task list should load right away for demo user opening the app

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1544]
Right now, the messages tab (or something that looks like it, with the same bar color and FAB with a +) flashes after the loader and before the task list loads. This is what it looks like, in a browser as well as on Android (logged in as demo):

![screen shot 2015-11-05 at 08 41 01](https://cloud.githubusercontent.com/assets/377216/10975112/26895eba-839a-11e5-8c85-2e830b176566.png)

This may have to do with the initial tab config. Ideally, the first thing the user would see after the loader is the task list.

**Comment by abbyad** [comment]
@sglangevin is this still an issue?

**Comment by sglangevin** [comment]
This is no longer an issue - tasks tab loads immediately. Probably was fixed during some of the work done on initial loading of the app.
