### ISSUE TITLE
Can't Send Message to freetext number

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1546]
The select2 upgrade has regressed so a user can't freetext a phone number in the Send Message dialog (and maybe elsewhere?).

**Comment by mandric** [comment]
Related: https://github.com/medic/medic-webapp/issues/699

**Comment by alxndrsn** [comment]
Current restriction: phone number must be valid before it appears in the dropdown.  This behaviour can be changed easily if not desired.

**Comment by garethbowen** [comment]
Code looks fine - I'll leave the UX review for acceptance testing.
