### ISSUE TITLE
Select2 no longer selects the highlighted option on blur

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1547]
We wrote some hacky code to modify select2 v3 to select the highlighted result on blur. This no longer works for select2 v4 but fortunately they have added the SelectOnClose adapter to do this for us.

This is a regression of #699

**Comment by alxndrsn** [comment]
I have seen this hacky code.  I guess that means it can be removed!

**Comment by alxndrsn** [comment]
Already done in 1bb6a765017e9d62345c420aef3464ae64a8e307 and 7c88de6b5db52fb8b0523152b463876919b12f4a
