### ISSUE TITLE
Task granularity is no longer daily

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1552]
Getting reports from @joshnesbit that the task granularity is not daily as expected after #1369.

![image](https://cloud.githubusercontent.com/assets/789512/11013908/c66b3606-84ee-11e5-8fea-fab4c7079147.png)

**Comment by mandric** [comment]
Only show hours if it's today (same day).

**Comment by garethbowen** [comment]
> Only show hours if it's today (same day).
That's not correct. The original issue was to never show hours. Basically tasks should have dates and not datetimes.

**Comment by garethbowen** [comment]
Task dates should now show: "today", "in a day", "in 2 days", "in 2 months", "in 2 years".

**Comment by mandric** [comment]
@garethbowen thanks for the correction.

**Comment by abbyad** [comment]
Overall looks good, but returning because I am seeing "0 days ago" on lg.app.

**Comment by abbyad** [comment]
![image](https://cloud.githubusercontent.com/assets/789512/11158646/9a48514c-8a27-11e5-9a9b-2d0ba876b002.png)
