### ISSUE TITLE
medic-data export for 0.6 systems

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1555]
I think I have the couch2postgres adapter in a good place.

I'd like to run the import against a dataset that is compatible with a 0.6 system.

It does not appear as though we have any medic-data exports which look/feel like a 0.6 system though.

**Comment by garethbowen** [comment]
Possible duplicate of #1092

**Comment by btbonval** [comment]
Quite possibly. It sounds like the desires of this ticket are covered by Milan's comment at https://github.com/medic/medic-webapp/issues/1092#issuecomment-135117384 but the initial stated reason for the ticket is different.

If that ticket evolves to include a full generic ANC dataset, then this ticket is a dupe. If that ticket remains narrowly focused on a few task tests to show that the rules engine works, then maybe this ticket can represent the concept in Milan's comment.

**Comment by btbonval** [comment]
I think one of the main problems that I can elucidate is that I was automatically creating form schemas from the JSON definitions. However, it looks like forms are now defined using XML.

That also makes me wonder if I can find something in postgres to parse XML. When it was all JSON, using the new postgres 9.4 json funcs worked great.

**Comment by btbonval** [comment]
I think #1764 fully coopts the main rationale for this ticket with the minor exception of not addressing some way to present the new XML configs as JSON for postgres support. That minor issue can always become its own ticket at a later date.
