### ISSUE TITLE
Form layout improvements

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1556]
I think this form could do with a linebreak before **Keep baby Warm**:

<img width="571" alt="screen shot 2015-11-10 at 16 56 59" src="https://cloud.githubusercontent.com/assets/191496/11067275/1bb9377c-87cc-11e5-97ff-8cfcf4e368a2.png">

---

This one could do with a line break before _4. Get good nutrition_

<img width="717" alt="screen shot 2015-11-10 at 17 00 01" src="https://cloud.githubusercontent.com/assets/191496/11067398/95f49446-87cc-11e5-8c8c-e6b55ddf9d2c.png">

---

This one is a bit odd - what's _Chest Indrawing_ doing down there?

<img width="794" alt="screen shot 2015-11-10 at 16 58 45" src="https://cloud.githubusercontent.com/assets/191496/11067421/b23b5216-87cc-11e5-998c-d8b692adca95.png">

**Comment by abbyad** [comment]
The "healthy practices" pages should be redone with the same template from the summary pages. 

@alxndrsn, I presume the `Chest indrawing` danger sign was selected? The Delivery Details page should have had the Danger Signs header and referral/followup note when one is selected. I will fix that and the formatting.

**Comment by abbyad** [comment]
Assigning to @sglangevin to review for this project.

**Comment by sglangevin** [comment]
This has been resolved for the project in question. If we need to update the design of the summary pages, we can open a new issue for that.
