### ISSUE TITLE
sticky date hover tooltip

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1557]
Reproduce by hovering over date then clicking task.  Probably impossible to reproduce on a mobile device because there is no hover.

![screen shot 2015-11-10 at 3 02 54 pm](https://cloud.githubusercontent.com/assets/25641/11069261/6b669086-87bc-11e5-8cb6-61f14b65a1e3.png)
![screen shot 2015-11-10 at 3 03 00 pm](https://cloud.githubusercontent.com/assets/25641/11069271/75665210-87bc-11e5-88b9-93cb535e0d66.png)

**Comment by mandric** [comment]
also looking at these screens i don't see why the icons can't be full height of the container divs with a bit of padding.

**Comment by garethbowen** [comment]
The tooltips are sticky by design, so on mobile you can click to see the full date. There is some code somewhere that's supposed to clear them all on navigation which clearly isn't working. Maybe we need a timeout as well or instead so it disappears after 5 seconds.

**Comment by alxndrsn** [comment]
I don't know specifically how the tooltips work, but if they're attached to the DOM as children of the `ContactContentCtrl` then they should get cleaned up automatically on navigation.  (There were similar issues with `select2` and this solved it.)

**Comment by alxndrsn** [comment]
Looks like these can also hang about when scrolling - screenshots pending (@ngamita)

**Comment by alxndrsn** [comment]
To fix:
- [ ] hide date tooltips on mobile
- [ ] create non-priority ticket to re-instate on mobile but make sure they don't zombify
