### ISSUE TITLE
Forms don't load while offline

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1558]
Reproducible on lg.app. It looks like the enketo stylesheets aren't appcached any more.

```
GET https://lg.app.medicmobile.org/medic/_design/medic/static/dist/xslt/openrosa2xmlmodel.xsl net::ERR_INTERNET_DISCONNECTED
GET https://lg.app.medicmobile.org/medic/_design/medic/static/dist/xslt/openrosa2html5form.xsl net::ERR_INTERNET_DISCONNECTED
```

![from_a_task_360](https://cloud.githubusercontent.com/assets/2064938/11076737/47f0a506-8861-11e5-8543-a0c4dfc654c0.png)

**Comment by alxndrsn** [comment]
LGTM

**Comment by joshnesbit** [comment]
I'm testing this on my Y4. Some forms are loading while offline, but some are not.

Working: New pregnancy form from a person's profile, Assess patient form from History tab.
Not working: New person (from a family profile). See screenshot below:

![new person form while offline](https://cloud.githubusercontent.com/assets/377216/11165880/52268612-8ad2-11e5-9357-8ac20e9312c6.png)
