### ISSUE TITLE
"Families"/"Clinics" is internationalised incorrectly in `lg.dev`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1559]
The list of _Families_ on this page is titled _Clinics_:

https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E

<img width="1280" alt="screen shot 2015-11-11 at 14 20 32" src="https://cloud.githubusercontent.com/assets/191496/11091909/734bfcf0-887f-11e5-8e25-8c89a99e33aa.png">

**Comment by alxndrsn** [comment]
Still an issue.  Likely a text change or out-dated app_settings.

**Comment by abbyad** [comment]
Just updated the label, moving to Ready.
