### ISSUE TITLE
Pregnancy: weird combinations of risk factors

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1560]
Probably not high priority, but I suspect it's illogical to combine all of the following risk factors on the _New Pregnancy_ form:

<img width="623" alt="screen shot 2015-11-11 at 15 47 04" src="https://cloud.githubusercontent.com/assets/191496/11093618/907ea604-888b-11e5-9f10-6f630ae8183d.png">

**Comment by abbyad** [comment]
Fixed this in an earlier commit, moving to Ready.
