### ISSUE TITLE
"How many breaths" field not required

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1561]
On the _Assess Patient_ form, if there are breathing troubles the *_How many breaths per minute?_* field is displayed.  However, the field is not marked `required`.

<img width="589" alt="screen shot 2015-11-11 at 15 59 28" src="https://cloud.githubusercontent.com/assets/191496/11093947/4f8a50a6-888d-11e5-8d5f-44c0d69f5fc9.png">

Should this field be `required`?

**Comment by abbyad** [comment]
@joshnesbit can you please confirm whether the breath count field should be required?

**Comment by joshnesbit** [comment]
Breath count field should be required if breath count screen is shown. We skip the breath count altogether if there is no cough. If there is a cough, this field is required.

**Comment by abbyad** [comment]
Fixed, moving to Ready.
