### ISSUE TITLE
Cannot obtain location on Tecno Y4

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1567]
Cannot get location from a form on the Tecno Y4. I tested with a browser (chrome 44) and the app (chrome 30), with the Location Mode showing "High Precision" and as "Battery saving"

**Comment by mandric** [comment]
Assuming the mobile data connection and wifi is also disabled/off here?

**Comment by abbyad** [comment]
Actually no... didn't matter if the mobile/wifi connection were on or off on the Y4 for these tests.

**Comment by mandric** [comment]
Can you provide more details steps to reproduce this?

**Comment by abbyad** [comment]
- Open app, go to contact page
- Add a contact (or any form with a Location page at the end)
- On the Location page click the location button

If it gets a location you would see the note at the bottom of the page change.

This works on other mobile devices.... so probably best to test on a Y4 since that is what the field test users will have.

**Comment by alxndrsn** [comment]
@abbyad from docs for `setGeolocationEnabled(boolean flag)`:
> Sets whether Geolocation is enabled. **The default is true.**

More likely we are missing the following:
> ...an application must provide an implementation of the `onGeolocationPermissionsShowPrompt(String, GeolocationPermissions.Callback)`

**Comment by abbyad** [comment]
I wasn't able to get this to work after updating medic-android to 105. I was connected to a wifi and tested with the Location mode set to "battery saving" and 'high precision". I am able to get the location using the default browser on the Y4.

@alxndrsn did you see this working?

**Comment by alxndrsn** [comment]
Works on locally-built (debug) apps, but not on version from app store.

**Comment by alxndrsn** [comment]
Potentially confusing as this is, it doesn't actually break the user's workflow and can be easily explained during the trainings, so we are removing the `Priority` label.

**Comment by alxndrsn** [comment]
Suggested next steps:

- [ ] test location in medic-webapp inside Medic Mobile (unbranded) android wrapper app **downloaded from play store**
- [ ] build `gh-pages` demo
  - [ ] detect location setings
  - [ ] display a log of location updates on the page
  - [ ] add a button to request latest location updates
- [ ] test `gh-pages` demo in Medic Mobile android app wrapper supplied from Play Store

**Comment by alxndrsn** [comment]
Testing this with an app which was downloaded from Google Play is essential, so this is blocked by #1585

**Comment by alxndrsn** [comment]
Deprioritised in favour of #1642

**Comment by sglangevin** [comment]
Location data is now being collected via our Android app. Closing.

**Comment by alxndrsn** [comment]
@sglangevin If I understand your comment correctly, this has now been show to work with apps downloaded from the play store.

**Comment by sglangevin** [comment]
Yes, it is working for apps downloaded from the play store.

**Comment by alxndrsn** [comment]
Great :+1:
