### ISSUE TITLE
can't view contact detail again after viewing once

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1568]
1) load lg.dev in browser mobile mode (small width)
2) Load contacts tab and select a contact
3) use chevron to go back 
4) try to select same contact again

nothing happens, expected to load contact again.

**Comment by alxndrsn** [comment]
This is not enough: https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/inbox.js#L103

**Comment by mandric** [comment]
Yeah same thing happens on the other tabs/panels.

**Comment by mandric** [comment]
Another weird observation, when I load a new/different contact the window initially loads with the title of the previously loaded contact.  So maybe angular thinks it's already loaded or something.
