### ISSUE TITLE
Replace bower with npm

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1573]
We use both bower and npm in webapp which causes unnecessary complexity at build time. Switch all the bower dependencies to npm dependencies and `require` the modules so browserify compiles them in. This will make getting sourcemaps ( #1169 ) much easier.

Possible issues:

- Bower flattens the dependency tree so you only get one version of each library. Make sure `npm dedupe` is run as part of the build process which attempts to do a similar thing but less aggressively. Ensure that the final minified file size isn't too much larger than the previous inbox.js + dependencies.js.
- This will result in only a single js import (inbox.js) rather than dependencies.js and inbox.js. We initially split the files because of a bug in Chrome storing large files in the appcache. I think this bug only affected private browsing mode which isn't currently supported. If this is still an issue we can make a dependencies.js but having a separate js file that just requires all the libraries we don't call directly, and browserify that.

**Comment by alxndrsn** [comment]
Another downside to monolithic JS: combining `dependencies.js` and `inbox.js` means that (mobile) clients have to download one large file when any JS changes, instead of smaller, more relevant changesets.

**Comment by garethbowen** [comment]
Using npm for everything doesn't mean everything is bundled together into one js file.

**Comment by alxndrsn** [comment]
I only thought that because you say above:

> This will result in only a single js import (inbox.js) rather than dependencies.js and inbox.js.

**Comment by garethbowen** [comment]
Right but there are ways of splitting this up if it proves problematic.

**Comment by garethbowen** [comment]
I also expect this to reduce the total size of compiled JS.

**Comment by garethbowen** [comment]
To clarify that comment, if a bower dependency and an npm dependency both depend on a given module, it will be included separately in inbox.js and dependencies.js. If we went with npm or bower exclusively the module would only be included once. A current example: underscore.js

**Comment by garethbowen** [comment]
The results without zipping or minification, are...

Before:

inbox.js: 3.17MB
dependencies.js: 3.52MB
TOTAL: 6.69MB

After:

inbox.js: 5.70MB

Total saving of ~1MB. One js download instead of two which has pros and cons. I suggest we wait to see if there's a problem before splitting it up.

**Comment by alxndrsn** [comment]
Looks fine.

> One js download instead of two which has pros and cons. I suggest we wait to see if there's a problem before splitting it up.

We could also consider providing each lib in a separate file, which would make change downloads much smaller.
