### ISSUE TITLE
Error when adding Family Member

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1575]
Got the below error when trying to add a family member in the Bond Mary Family. Got the same for other families as well.

![screen shot 2015-11-16 at 13 05 04](https://cloud.githubusercontent.com/assets/15346836/11179336/b4108476-8c63-11e5-8f89-83b0b5e9e835.png)

**Comment by abbyad** [comment]
Thanks for reporting this @fredatthehub. We have this opened at #1571 already, closing as duplicate.
