### ISSUE TITLE
`Tel` validation not shown in Chrome

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1577]
Logged in as admin on Chrome using 0.6.0-alpha.2347:
![image](https://cloud.githubusercontent.com/assets/789512/11193002/395fbca6-8c72-11e5-8478-e75098d8b4e5.png)

The error comes through to the console, but not to the webapp. It does however show the webapp error as admin in FF, and as demo in Y4.

**Comment by alxndrsn** [comment]
Cannot recreate.  Please re-open if still occurring for you.
