### ISSUE TITLE
Links from profile pages

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1579]
As a restricted user, I can click on my own area (Busia CHP Area1) from a family profile, and I land on a different view of my families. Ideally, this link would take restricted users back to their contacts list.

![screen shot 2015-11-16 at 1 25 58 pm](https://cloud.githubusercontent.com/assets/377216/11195458/e767324a-8c66-11e5-93dc-5e432052d27f.png)

If we must allow users to get to this screen, we could change "Clinics" to "Families".

![screen shot 2015-11-16 at 1 35 43 pm](https://cloud.githubusercontent.com/assets/377216/11195472/f545ec3a-8c66-11e5-9d1e-1035a9344fcc.png)

**Comment by abbyad** [comment]
>  Ideally, this link would take restricted users back to their contacts list.

@joshnesbit, would it be better to hide the CHP Area if it is their own?

**Comment by joshnesbit** [comment]
Yes, that would be even better.

**Comment by garethbowen** [comment]
I've left the parent text for consistency but removed the link if the parent is the user's facility.

**Comment by abbyad** [comment]
From a CHW/CHP's perspective every family they see belongs to that user's area, which means every family will have that text. I think we are better off hiding it completely.

**Comment by garethbowen** [comment]
Showing it makes more sense for a wider set of user stories than just LG CHPs. There isn't much benefit in hiding it.

**Comment by abbyad** [comment]
Works well and we can get more user feedback on this throughout the field test. Moving to Ready.
