### ISSUE TITLE
Fields not populated in a custom Edit person form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1580]
![image](https://cloud.githubusercontent.com/assets/789512/11196862/9f4257da-8c87-11e5-98d9-7920d5ac0769.png)

In this case the same form is used for create and edit person. If this is related to configuration, need to figure out what needs to be done differently. 

This is loosely connected to #1571.

**Comment by alxndrsn** [comment]
Possibly fixed in #1571

**Comment by alxndrsn** [comment]
Re-test on lg.dev once latest build deployed.

**Comment by alxndrsn** [comment]
@abbyad I'm not seeing the custom Edit form on `lg.dev`; should I expect to?

**Comment by alxndrsn** [comment]
(cannot recreate, as per above comment)

**Comment by abbyad** [comment]
Sorry, I missed your comments earlier. The custom form is only on lg.app right now. 

Testing on build 2366 with the fix for 1571, I don't see the fields populated with the custom form, but after removing it I do see the fields in the default form. 

For the field test we can use the default forms to avoid this issue, but it would be preferable to use the custom forms so that adding and editing is more consistent.

**Comment by abbyad** [comment]
The "bug" label was added, but the fix may very well be in the form configuration.

**Comment by mandric** [comment]
Bug still appears for me on latest LG app from play store v 0.1.111.

**Comment by garethbowen** [comment]
It's because the `form:contact:person:edit` form has an unused `inputs` section. This changes where the data is bound so it doesn't match any nodes. This is a silly reason for it to fail, so I'll try and come up with more robust code, but the workaround for now is to remove the `inputs` section.

**Comment by alxndrsn** [comment]
Looks like decent test coverage :+1:
