### ISSUE TITLE
New Contact form asks for child details when there are none

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1583]
First, the form asks _How many children in this family?_.  If you enter *0*, then the next page of the form is still _Would you like to add children now?_

**Comment by browndav** [comment]
Are you seeing "how many children under five", or just "how many children"? IIRC the former is technically correct (you can have zero children under five, and two over five), but I agree it's a little confusing.

**Comment by alxndrsn** [comment]
It is indeed _How many children under 5..._.  Might be room for improvement in the wording.
