### ISSUE TITLE
[android] [unbranded] display toast showing server URL on startup

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1586]
Can be easy to forget what server you've configured for.  Show a toast on startup to remind the user.  This may seem over-technical for general use, but this build is currently only for internal use anyway so seems reasonable.

**Comment by garethbowen** [comment]
Might be a little annoying to show every time Maybe #1596 is a better solution?

**Comment by alxndrsn** [comment]
Closed in favour of medic-android issue - this is just for developers' convenience.
