### ISSUE TITLE
missing translation: /data/contact/last_name

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1587]
On the _Children_ repeat section of the Add Family form, the tooltip for child's surname appears as: `/data/contact/last_name`.

[TODO @fredatthehub screenshot here]

**Comment by fredatthehub** [comment]
![screenshot_2015-11-17-15-12-04](https://cloud.githubusercontent.com/assets/15346836/11220490/5926bc1a-8d71-11e5-9a1c-911d348434d6.png)

**Comment by abbyad** [comment]
Fixed the form, moving to Ready.
