### ISSUE TITLE
In _Children_ section of _Add Family_ form, child's surname has no default

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1589]
Should default to surname of parent(?)

**Comment by abbyad** [comment]
Ya, I think it should... this is related to https://github.com/medic/medic-webapp/issues/1490.

In the meantime it is OK to leave this field blank since you can still find the child by searching their last name.

**Comment by abbyad** [comment]
No longer relevant now that the name fields have been combined into one field.
