### ISSUE TITLE
Submitting follow-up form leads right back to...follow-up form!

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1593]
From the _Tasks_ tab, select a tab, fill the form with valid data and click submit.  You will be taken back to a fresh copy of the same form.

**Comment by mandric** [comment]
Seems a bit strange that resolving a task would leave you with no history or confirmation.

**Comment by garethbowen** [comment]
Good point. I've added a snackbar confirmation to give some feedback.
