### ISSUE TITLE
Radio buttons are *very* unresponsive

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1599]
Some radio buttons are unresponsive to the point of unusable - might take 20 or 30 tries to choose e.g. _Gender_.  Some radios are better behaved.

Possibly related: small problems rendering, or perhaps floating white rectangles on top of the radios:
[TODO @fredatthehub screenshot here]

**Comment by browndav** [comment]
Is the proposal here a larger clickable area? I've noticed that the touchscreen on my Y4 tends to tap a little bit above my finger for reasons that I don't fully understand, but it's (at least subjectively) not as bad as you're describing.

**Comment by abbyad** [comment]
Some more notes from my testing:
- A larger rectangle around the label and radio button is already clickable... but not always consistent since a longer than expected tap is sometimes necessary. 
- I have noticed that the radio button can take 1-2 seconds to show up after tap, especially if a calculation is involved (eg Approx start date of last cycle). 
- If the same radio button is tapped again before it appears checked, it may not show at all, or just blink on then off.

**Comment by garethbowen** [comment]
It seems slow but usable in my testing. 1-2 seconds to select. Reasonable click target. @alxndrsn I tried the New Family gender field on the tecno and it seemed ok. Is that the form you were testing?

I also noticed what seems like a bug where if you click a selected radio button it deselects it. This isn't the standard radio button behaviour and so feels a little unnatural to me.

**Comment by abbyad** [comment]
The Assessment form seems to have the longest delays that I've seen. It also has some of the more complex, and apparently time consuming, calculations.

**Comment by abbyad** [comment]
@alxndrsn do you think it is feasible to show the selection prior to the calculations being computed?

**Comment by alxndrsn** [comment]
* The radio button is "filled in" in the fifth `onclick` listener.  What is happening in the first four click listeners, and the preceding `onmouseout` listeners that takes so long?
* The `onfocus` listener sometimes cancels the click outright - perhaps if it is not long enough?  Certainly it _always_ fails if there is a breakpoint on `onfocus`, and it _feels_ like you have to long-press on android.

**Comment by alxndrsn** [comment]
looks like the touch event needs to be not too short, but also not too long

**Comment by alxndrsn** [comment]
Standalone assessment form is available at https://alxndrsn.github.io/enketo-core/forms/?xform=https://raw.githubusercontent.com/medic/medic-projects/master/lg-uganda/forms/assessment.xml?token=AALsCOzCuFyLxgULPXnUhCKJZYpEw0hhks5WWDIUwA%3D%3D

**Comment by alxndrsn** [comment]
...or point your mobile at http://bit.ly/1NGJtqu

**Comment by alxndrsn** [comment]
According to Chrome Profiler running against the Tecno Y4 and ~20 repeated changes of radio button on Assessment form, 28% of time is spent in this `ondataupdate` handler:

```js
            model.$.on( 'dataupdate', function( event, updated ) {
                that.calcUpdate( updated ); //EACH CALCUPDATE THAT CHANGES A VALUE TRIGGERS ANOTHER CALCUPDATE => INEFFICIENT
                that.branchUpdate( updated );
                that.outputUpdate( updated );
                that.itemsetUpdate( updated );
                // edit is fired when the model changes after the form has been initialized
                that.editStatus.set( true );
            } );
```
<img width="1280" alt="screen shot 2015-11-20 at 14 53 21" src="https://cloud.githubusercontent.com/assets/191496/11299276/9338bb66-8f96-11e5-9a99-53d297bf18c2.png">

However, it doesn't seem difficult to click radios in the enketo/formhub-branded page, so this may be an issue with the size of radio items.

**Comment by alxndrsn** [comment]
Main cause seems to be complicated form calculations and updates.  But #1629 and #1630 makes the radio buttons easier to touch, and make it more obvious when the touch has occurred, which should cut down on frustrating re-presses.
