### ISSUE TITLE
_May lose data_ warning displayed when form has no fields

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1601]
Sometimes a form will not let you fill it in (e.g. _Assess Patient_ for a very old or very young patient).  In this case, the form instructs the user to navigate back to where they came from, but pressing back triggers the "Are you sure you want to go back?" modal.  The modal seems unnecessary.

**Comment by SCdF** [comment]
@mandric please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by mandric** [comment]
Is this still an issue/problem?

**Comment by alxndrsn** [comment]
Yep.  Just an opportunity for improved usability.  The same "Are you sure?" dialog is displayed when navigating back from a "this form failed to load" error.

**Comment by garethbowen** [comment]
Related: #3045

**Comment by garethbowen** [comment]
Review please @alxndrsn
