### ISSUE TITLE
Today's date not valid for new-born report

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1602]
In the _New born visit_ report form, entering a delivery date of today's date fails validation.

**Comment by abbyad** [comment]
This may be timezone related...

**Comment by alxndrsn** [comment]
Possibly, but the bug was seen early afternoon.

**Comment by abbyad** [comment]
I fixed the constraint that was clearly wrong, but oddly it worked as expected for me even without the fix. 

@alxndrsn assigning to you for acceptance testing.

**Comment by alxndrsn** [comment]
Still happening here (`lg.app`).

**Comment by mandric** [comment]
It's a bit hard to reproduce this given the information available here.  If this ends up being reassigned to someone else it would be useful to provide a bit more instructions.

**Comment by abbyad** [comment]
Works, so moving to Ready. May have been somewhat related to #1922.
