### ISSUE TITLE
api exports for 0.6 don't export all fields

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1604]
Using the API like this for pregnancy fields from LG, only the 9 basic fields show up:
https://lg.app.medicmobile.org/api/v1/export/forms/pregnancy?startkey=%5Btrue%2C%22pregnancy%22%2C%7B%7D%5D%0A&endkey=%5Btrue%2C%22pregnancy%22%2C0%5D&include_docs=true&descending=true

These are the fields that can be exported right now for any form:
* Record UUID
* Patient ID
* Reported Date
* From
* Contact Name
* Clinic Name
* CHP Name
* CHP Area Name
* District Hospital Name

We need the fields specific to these forms to be exported. According to @abbyad , it looks like the api exports still expect the old JSON form format.

I'm getting some serious deja vu writing this, but I cannot find an issue with any of these keywords. Sorry if this is duplicated.

**Comment by btbonval** [comment]
`CHP id` field is desired instead of or in addition to `CHP name`.

**Comment by btbonval** [comment]
I just noticed the export `Patient ID` is blank because it isn't looking in the correct place. We'd like this to be the actual patient id.

**Comment by btbonval** [comment]
Generally it looks like we need CHP (uu)id, patient (uu)id, and reported dates. In cases where there is no patient (uu)id, the form (uu)id is desired. It might not hurt to include form uuid in all cases anyway.

**Comment by btbonval** [comment]
Okay and it looks like otherwise we would like to export all `<outputs>` fields. I think this was considered a given, but I'm gonna write it explicitly anyway.

**Comment by btbonval** [comment]
@abbyad I'm not seeing Reported By on any Contacts. You said this was new and I think you had an example of it in the LG system, but they're not coming out.

Originally I tried this URL which uses the Contacts API and filters for "clinic" types:
https://lg.app.medicmobile.org/api/v1/export/contacts?query=%7B%22%24operands%22%3A%5B%7B%22type%22%3A%5B%22clinic%22%5D%7D%5D%7D&format=json

Problem is that Analytics user does not have access, and also the return JSON is vastly different from the couchdb view json which is what we can already parse in the Middleware. Since this is throwaway, I figured I'd not go through the labor of parsing that export.

So now I'm using this URL which is friendly for the Analytics user:
https://lg.app.medicmobile.org/medic/_design/medic/_view/facilities

I have no problem filtering for the clinic type in Spreadsheets.

However, I see found one "ov" and that was for "move" not "Nov" or "November". Searching for "eported" also comes up with nothing.

Can you confirm that reported by is part of contacts, and if so, do we understand why facilities does not package it as part of the json view? It seems to package _everything_ else. I mean, you should see this spreadsheet. Flattening every doc in facilities leads to a whole lot of columns! Nothing we can't work with for this trial though.

**Comment by btbonval** [comment]
@abbyad 

@yembrick just told me we aren't tracking family registries by month so we don't need that date after all. It was in our spreadsheet of needed fields as "date/timestamp" under family registrations, so I thought we did need it. I guess that spreadsheet was incorrect.

reported dates for family registrations (as gotten from contacts/facilities) is not necessary I guess.

**Comment by yembrick** [comment]
I think in the long term (post field test) they will want to look at trends here (as will we for activity/impact monitoring), but the metric we want for the field test is definitely a total count, irrespective of the date/time registered. Thanks for clarifying.

**Comment by btbonval** [comment]
Using strictly the facilities view, I think I can list all families, CHPs, persons, and so forth. However, I cannot seem to correlate them.

For example, I have Brownday Ronda Family. The contact._id is Brownday Ronda's uuid. Otherwise, I have no way to link this family to Brownday June or the Busia CHP Area in the data I've gotten from the facilities view. The front end tells me the Brownday Ronda Family also contains Brownday June and is managed by Busia CHP Area.

The spreadsheet for our calculations suggests that I need to be able to correlate which CHP is registering which family. Otherwise I'm not sure how I can calculate `health workers active` using family registration as an indicator of CHP activity.

I'm fine dropping family registration from `health workers active` calc, but I'm not sure if that is an option on the table.

**Comment by browndav** [comment]
Decision: attempt to refactor data export so that Enketo form fields are included in the output. Priority label added per conversation with Josh this morning. Deadline for providing usable spreadsheet-based reports to LG: Thursday, December 3rd, 2015.

**Comment by garethbowen** [comment]
I think this is achievable without any code changes whatsoever.

Try this URL: https://lg.app.medicmobile.org/api/v1/export/forms/assessment?columns=[ "_id", "contact._id", "fields.patient_id", "reported_date" ]

The magic is in the `columns` parameter which overwrites the default set of columns so you can fetch whatever you like. You had a bunch of couchdb view parameters in your original URL which are ignored as far as I can tell. The [documentation](https://github.com/medic/medic-api/blob/develop/API_v1.md#get-apiv1exportformsformcode) lists the supported parameters.

I've listed the columns you've asked for, but you can get any of the fields on the doc. For example, one "assessment" form is here: https://lg.app.medicmobile.org/_utils/document.html?medic/B50767FC-4ABB-8A95-BED4-7FA7CF6AE64A

The `fields` field lists what was actually entered in the form. The `content` fields has the raw xml which isn't very useful in this case. The `contact` field is the CHP the report was submitted by. All other fields are meta information about the submission such as `reported_date`.

@btbonval : Please let me know if this export is insufficient for your needs.

**Comment by btbonval** [comment]
@garethbowen It looks like that has worked for assessments:
https://lg.app.medicmobile.org/api/v1/export/forms/assessment?columns=%5B%22_id%22,%22contact.parent._id%22,%22contact.parent.type%22,%22fields.patient_id%22,%22reported_date%22,%22fields.patient_dob%22,%22fields.symptom_fever%22,%22fields.symptom_temperature%22,%22fields.symptom_malaria_test%22,%22fields.treatment_follow_up%22%5D

So I guess I'll just write up the specific fields for each form.

I see your link to the assessment example puts me into the Futon browser. I'm not sure how to navigate that to find the form types I desire. Looks like I log into the webapp normally, visit the History, choose which form type I want to look at, grab one, copy its UUID, and paste it into the Futon link above. Is there a simpler way?

**Comment by btbonval** [comment]
Ah, as a followup re: families vs contacts, the contacts export does not support csv (according to docs) and puts its JSON data in a different format from the way views return their JSON. The middleware was written to parse the sort of JSON structure that comes out of views (e.g. `doc.rows.forEach()`). I had tried to parse that but it was faster to simply use the facilities view since I could already parse that.

Unfortunately I've already run into a new level of nesting which has offset columns.

**Comment by btbonval** [comment]
Pretty sure I just finished the required metrics, so I think everything is sorted.

**Comment by garethbowen** [comment]
Closing as it sounds like it's resolved. Feel free to reopen if I've misinterpreted!
