### ISSUE TITLE
cache tasks generated by the webapp

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1605]
A lot of logic is built into the tasks that are generated in the phone or webapp.

This information is hugely useful for analysis, dashboards, impact, etc. Unfortunately it sounds like the tasks exist only in memory, and any trace of their existence is lacking from any database.

One example is reminder schedule. Beforehand, we could look at messages sent and deduce some information about a patient's visit schedule. Now, it is unclear if there is a log of messages, but even if so, it would be great to simply get that schedule that is generated for each patient directly.

I have no doubt we can come up with an example of why each task would be useful to cache and have available for analysis. If we must justify why to cache each particular type of task, a list of those would be appreciated.

**Comment by btbonval** [comment]
Also it sounds like tasks generated offline by phones would probably need to be generated on the webapp to duplicate them. It wasn't made clear whether this happens de facto or not, I got a little lost in that conversation. It sounds like if the webapp does not already duplicate tasks itself, it could do so.

**Comment by browndav** [comment]
We've kicked around ideas for some kind of persistent log of generated and/or completed tasks, but haven't really had a chance to do the (technical) design work given the field test deadline. I'm almost certain that we'll need to run the rules engine in the medic-api backend too (e.g. for things like generating SMS reminders in a hypothetical DIY v0.6), so that may be a decent place to implement the logging.

**Comment by btbonval** [comment]
Yeah, medic-api could certainly do the trick. Instead of caching the rules, at that point it might be just as easy to generate deliver certain tasks in response to a specific API call.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by browndav** [comment]
Closing and marking as ancient. Create a new issue if this or a similar feature/fix is needed.
