### ISSUE TITLE
Unrecoverable 502 Bad Gateway if app is started when Garden is updating

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1606]
If you start the app when Garden is updating, the app sees a 502 Bad Gateway error (from nginx?).  There is no refresh-link on this page, so user must force-close the app.

## Suggested Fixes

1. add a simple self-link to nginx error pages so that the user can try again easily
2. add error handling to the android client so any 5xx status codes display a status message and perhaps automatically retry

**Comment by browndav** [comment]
For item #1: #838.

**Comment by alxndrsn** [comment]
Any movement on that ticket?  Looks like it wouldn't be much work to get the design work moving.

**Comment by alxndrsn** [comment]
Went for the simple option - add a _Home_ menu item to the _Options_ menu on the android app, so there's always a way to force-refresh to the configured URL.

**Comment by mandric** [comment]
Nice.
