### ISSUE TITLE
[android] No easy way to skip past a textarea

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1607]
In a normal textfield, you can press the `Go` key (equivalent to `<enter>` on a computer keyboard) to skip to the next field in an enketo form, without having to close the soft-keyboard.

In a `textarea`, the `CR` key is shown on the android keyboard instead of `Go`, which means there is no obvious way to get to the next field.

### Suggested fixes

1. remove _Notes_ field
1. change _Notes_ to a textfield
1. add a hovering _Next_ button after the caret in textfields on android
1. putting notes on a separate page might solve the issue
1. have a checkbox above the textarea to show/hide it (unchecked and field hidden by default
1. ???

**Comment by abbyad** [comment]
I will make remove the `multiline` appearance for the Notes field, which should make it a regular text input.

**Comment by alxndrsn** [comment]
sounds good, thanks

**Comment by abbyad** [comment]
Tested and it works well now. Moving to Acceptance Testing.

**Comment by alxndrsn** [comment]
Simple, thanks.
