### ISSUE TITLE
Typo in Assess Patient form

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1608]
In the _Asses Patient_ from theirs a typo:

> _Is there chest indrawing?_

should reed:

> _Is their chest indrawing?_

**Comment by browndav** [comment]
It seems to read somewhat correctly both ways. I'm reading "Is there chest indrawing?" as "Is chest indrawing present?", and reading "Is their chest indrawing?" as "Is this person's chest indrawn?". IMO the current text is okay if LG doesn't object.

**Comment by joshnesbit** [comment]
I think it's alright as is for LG. The CHPs read "Is there chest indrawing?" as "Is chest indrawing present?"

**Comment by abbyad** [comment]
I had the same question when I first saw this form a couple months ago and got confirmation to leave it as such.

**Comment by alxndrsn** [comment]
On second reading, I agree.
