### ISSUE TITLE
Cannot add a new person

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1613]
As of today, I'm not able to create a new person using the "add new family member" form. Clicking submit does not submit a form – a spinner appears briefly and then goes away.

![screen shot 2015-11-18 at 8 51 13 am](https://cloud.githubusercontent.com/assets/377216/11247753/4bb551f2-8dd2-11e5-9308-7f0126fbb712.png)

![screen shot 2015-11-18 at 8 54 01 am](https://cloud.githubusercontent.com/assets/377216/11247757/4dda0c0c-8dd2-11e5-9f8d-a81336b2e0dd.png)

**Comment by browndav** [comment]
@abbyad: Do you think this is linked to configuration? It seems otherwise unlikely that this would have regressed in a major way between yesterday and today.

**Comment by abbyad** [comment]
The changes done the last few days on the [family.xml](https://github.com/medic/medic-projects/commits/master/lg-uganda/forms/family.xml) form are all trivial, and were working. 

I am pretty certain that I saw #1571 working, so were any other changes done since then?

**Comment by abbyad** [comment]
So this is now resolved. Using the version exactly as it is [here](https://github.com/medic/medic-projects/blob/2816bffd0aa01ba84011bb3e2768493ca746bfcc/lg-uganda/forms/family.xml) worked.
