### ISSUE TITLE
People aren't showing up in contacts list

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1614]
Yesterday, I created a new family with a primary caregiver and many children (the Abba family). I'm on lg.app as demo in Chrome on my laptop. The people aren't showing up in the contacts list:

![screen shot 2015-11-18 at 8 58 15 am](https://cloud.githubusercontent.com/assets/377216/11247798/87f9d30e-8dd2-11e5-986b-ba1caef4a8b5.png)

![screen shot 2015-11-18 at 8 58 47 am](https://cloud.githubusercontent.com/assets/377216/11247822/9ed22702-8dd2-11e5-9513-952642972baf.png)

I am able to search for and find these people by searching their surname:

![screen shot 2015-11-18 at 8 59 52 am](https://cloud.githubusercontent.com/assets/377216/11247854/c055f9bc-8dd2-11e5-9530-86e259b04c19.png)

As a user, I'd expect people I create to show up in the contacts list. For the field test, we can train that the contacts list shows families and you can find specific people by (a) clicking on a family and selecting a person, or (b) searching for a person or family.

**Comment by abbyad** [comment]
I think we should fix this for the field test given that some of the people are showing in the list. If it is not feasible to fix this for the field test then we should consider (temporarily) setting a filter to only show families in the list.

**Comment by browndav** [comment]
If you search for the missing people, do they show up? We saw a similar bug earlier this week that we haven't been able to nail down; this may be the same issue if they show up when searched for but not in the main contact list.

**Comment by abbyad** [comment]
It seems as though they are showing up when searched (screenshot 3)

**Comment by garethbowen** [comment]
I think pagination is broken (and maybe sorting too). You're seeing the first 50 results and the app is refusing to load more.

**Comment by garethbowen** [comment]
Pagination was broken by excluding the users place before working out if there are any more items to render. The sorting looks strange because a lot of those contacts have a leading space, eg: " John".
