### ISSUE TITLE
User management: Multiple selected items in a single-selection facility drop-down

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1615]
<img width="728" alt="screen shot 2015-11-18 at 11 24 08 am" src="https://cloud.githubusercontent.com/assets/763977/11251740/7decdff4-8de7-11e5-8060-052d9147efc4.png">

On lg.app, it looks like we've somehow managed to get the UI to select multiple items in a single-selection dropdown box. This apparently leads to the latter element being shown through the UI, but the blank element (read: no facility_id) being understood by CouchDB. I suspect this is undefined behavior, but haven't found a good confirmation yet.

This leads to confusion during configuration, and can break the entire application for restricted users.

Goal: Try to figure out how this is happening and fix it.

**Comment by garethbowen** [comment]
I have no idea why this is happening. But it doesn't seem to cause a problem, ie: facility is updated correctly. Putting in the backlog for now. We can reprioritise if it's found to cause a problem.

**Comment by abbyad** [comment]
Closing as it has been reported to not cause a problem.
