### ISSUE TITLE
Two `New Person` forms on `lg.app`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1619]
# Steps to recreate

<img width="268" alt="screen shot 2015-11-19 at 12 50 47" src="https://cloud.githubusercontent.com/assets/191496/11267404/37db3f6c-8ebc-11e5-87fb-08be69196be0.png">

# Obserations

Presumably caused by the `form:contact:person:create` and `form:contact:person:edit` forms:

```sh
$ curl https://demo:medic@lg.app.medicmobile.org/medic/_design/medic/_view/forms
{"total_rows":9,"offset":0,"rows":[
	{"id":"form:assessment","key":"assessment","value":null},
	{"id":"form:assessment_follow_up","key":"assessment_follow_up","value":null},
	{"id":"form:contact:clinic:create","key":"family","value":null},
	{"id":"form:family_survey","key":"family_survey","value":null},
	{"id":"form:contact:person:create","key":"person","value":null}, // <--------
	{"id":"form:contact:person:edit","key":"person","value":null}, // <--------
	{"id":"form:postnatal_care","key":"postnatal_care","value":null},
	{"id":"form:pregnancy","key":"pregnancy","value":null},
	{"id":"form:pregnancy_follow_up","key":"pregnancy_follow_up","value":null}
]}
```

# Notes

1. If these two forms are the same, they could be replaced with a single form at `form:contact:person`.
1. the Edit form's title should probably not be _Add Person_
1. I'm not sure if edit forms will offer a chooser for the person to edit, so the UX could be confusing
1. it looks like the forms have the same internal ID, which means it's not clear which of them is actually in use

**Comment by alxndrsn** [comment]
The implications of this are not entirely clear to me - it could be quite an insidious bug.  Also deleting forms from pouch when deleted from couch is problematic AFAIK, so it might be good to resolve this one quick.

**Comment by garethbowen** [comment]
Remove all add/edit contact forms from this list. Contacts need extra workflow on submission so _must_ be done through the contacts tab.
