### ISSUE TITLE
Form ID is displayed in filter bar instead of title

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1620]
This form's title is _Add Person_:

<img width="1280" alt="screen shot 2015-11-19 at 12 56 46" src="https://cloud.githubusercontent.com/assets/191496/11267573/1fa4b954-8ebd-11e5-87a4-3688907e0284.png">

**Comment by alxndrsn** [comment]
Cosmetic.

**Comment by alxndrsn** [comment]
Looks fine, although surprisingly complicated - `doc.form` maps to `code` which gives us `form.name` which is not translated, but `doc.form` in other cases maps to `internalId` which gives us `form.title` which _is_ translated.

**Comment by garethbowen** [comment]
Yeah, there's no much of a common structure between json forms and xforms unfortunately. Hopefully one day there'll be a clear winner...
