### ISSUE TITLE
App crash on update-available

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1622]
If an update is available before the page has loaded this code:

```js
      if (window.applicationCache) {
        var showUpdateReady = function() {
          $('#version-update').modal('show');

          // close select2 dropdowns in the background
          $('select.select2-hidden-accessible').select2('close');
        };
```

can cause this error:

<img width="621" alt="screen shot 2015-11-19 at 13 39 26" src="https://cloud.githubusercontent.com/assets/191496/11268667/051c7ac6-8ec3-11e5-877d-06276cfbbfe9.png">

which leads to:

app being stuck in gray-screen-with-loading-animation.

**Comment by garethbowen** [comment]
@alxndrsn What do you think about the suggestion in the code?

**Comment by alxndrsn** [comment]
@garethbowen the suggestion in code does not seem suitable to me.  Please re-read the error message in the screenshot above - all jQuery elements have a `select2` property, but the `e.select2('.close')` call throws an `Error` if the selecter is not initialised.  Throwing the error is not acceptable, as it breaks the page, leaving it stuck with the whole page gray, and the loading animation dispayed.

**Comment by garethbowen** [comment]
@alxndrsn Is there no deterministic way to check if select2 was initialised on that element? You just have to try and fail?

**Comment by alxndrsn** [comment]
No documented way that I could find.

**Comment by browndav** [comment]
Wild guess, admittedly without too much thought: can you check if the jQuery result object has a `select2` method? Not sure if they're doing some sort of dynamic dispatch underneath there, but just checking `elt.select2 !== undefined` might be worth a try.

**Comment by alxndrsn** [comment]
@browndav Please re-read the error message in the screenshot above - all jQuery elements have a `select2` property, but the `e.select2('.close')` call throws an `Error` if the selecter is not initialised.

**Comment by browndav** [comment]
Sorry, forgot that jQuery plugins are initialized statically and can't be selective about where methods are added. How about testing `.data('select2')` on the <select> element? That seems to work in a couple quick tests here.

**Comment by mandric** [comment]
Alex, just assigning back to you to have a look next time around, looks like browndav discovered a potential way to check for select2 initialization on an element.

**Comment by alxndrsn** [comment]
I think it's appropriate for anyone to make this change as they see fit.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)
