### ISSUE TITLE
No Follow-Up Task Generated after adding New Pregnancy - lg.app

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1623]
No Followup task was generated after adding a new high risk pregnancy, 

![screen shot 2015-11-19 at 16 39 02](https://cloud.githubusercontent.com/assets/15346836/11272241/859d95cc-8edc-11e5-937e-5d02a35e7e93.png)

**Comment by abbyad** [comment]
This was changed about 3-4 weeks ago... registering a pregnancy is now considered the first visit, so it doesn't prompt you for a followup immediately.

**Comment by fredatthehub** [comment]
How do we test the Pregnancy Followup?

**Comment by abbyad** [comment]
You can change the `reported_date` via futon to a couple months back. You should then see a task show up.
