### ISSUE TITLE
Pagination: Apparent off-by-one error, primarily affecting desktop mode

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1625]
Pagination appears to be working again, but scrolling to the pagination boundary results in a duplicate item (see screenshot). This technically happens in both mobile and desktop mode, but the effects aren't easily visible in mobile mode due to the right-pane transition.

I suspect this is an off-by-one issue in the pagination seek/`offset` code, but haven't confirmed this. Could be worked around for the field test if necessary, IMO.

<img width="485" alt="screen shot 2015-11-19 at 4 52 58 pm" src="https://cloud.githubusercontent.com/assets/763977/11289169/1685a956-8edf-11e5-813f-fa626ba163dd.png">

Observed on `lg.app`, version 0.6.0-alpha.2381, with Chromium 30 on Windows.

**Comment by garethbowen** [comment]
This is probably because we remove the current user's place. This means we get 50 items but only 49 are shown. Then we get items 49-99 so number 49 is shown twice.
