### ISSUE TITLE
app cache failure is unrecoverable

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1627]
Looks like if app cache fails to load on first run, then the app must be force-closed.

I've seen this a couple of times.

<img width="1280" alt="screen shot 2015-11-20 at 13 38 14" src="https://cloud.githubusercontent.com/assets/191496/11297817/00901fa2-8f8c-11e5-9aa3-7034e8c62b1d.png">

# ->

<img width="1280" alt="screen shot 2015-11-20 at 13 36 41" src="https://cloud.githubusercontent.com/assets/191496/11297788/cf6fe092-8f8b-11e5-9735-a85001e81867.png">

Might be useful to have a page-refresh available via the options menu.

**Comment by garethbowen** [comment]
I think it's the last error in the console that's the real issue, without the ddoc we can't do anything and this message is displayed. I don't think we can do much about the appcache error as appcache is handled purely by the browser.
