### ISSUE TITLE
Unwanted redirects can require app restart

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1628]
I just opened the app having run out of mobile credit.  I got a redirect to: http://www.redirect.mtn.co.ug/mtnredirect/mtn-redirect.html.  I guess it's some kind of redirect from MTN.  The page then 404d and an error was displayed.

If this happens to a user, there is currently no option but to force-quit the app and restart

Might be useful to have a page-refresh available via the options menu.

Related: #1627

**Comment by browndav** [comment]
Yeah, crap. It looks like there may be a transparent proxy in place that's only used in out-of-airtime situations.

**Comment by garethbowen** [comment]
Something like this might be useful: http://stackoverflow.com/questions/13447301/restricting-webview-to-one-page-only

**Comment by browndav** [comment]
This shouldn't be possible if we're using HTTPS end-to-end. Can we confirm that we're getting this redirect on an HTTPS URL? If not, it may be that an HTTP `->` HTTPS redirect is what's being intercepted, and we should hard-code `https://`.

**Comment by alxndrsn** [comment]
This bug is documented in more detail at #1754
