### ISSUE TITLE
Change colors of label for active enketo radio button

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1630]
Make the background color a bit darker, and make the text same as the main background color (likely white).  This higher-contrast should show more clearly that something's going on with the radio, even before the click handlers have managed to do their stuff.

**Comment by mandric** [comment]
Looking at this screen I'm just not sure how your description above applies.  Is there a specific screen you're referring to?

![screenshot_2015-11-20-12-44-26](https://cloud.githubusercontent.com/assets/25641/11302449/b3a90e4e-8f84-11e5-8d30-a0b6f3939f7d.png)

**Comment by alxndrsn** [comment]
That's not in our app :p

**Comment by mandric** [comment]
A screenshot or steps to get to a specific screen might help.

**Comment by alxndrsn** [comment]
_Reports_/_History_ > **+** > _Assess Patient_

**Comment by abbyad** [comment]
Checkbox label stays colored after unselecting an item. Is it possible to remove the coloring once the check is removed?

**Comment by garethbowen** [comment]
Returned because Marc raised an issue, and because the colour is a bit over the top. Lester recommends using #A2C8DE instead.

**Comment by alxndrsn** [comment]
Current colour is indeed quite horrible, but please test this new colour on Tecno Y4 before committing the change.

**Comment by garethbowen** [comment]
Closing as ancient (and bike-shedding!)
