### ISSUE TITLE
Age calculations in XForm are approximate

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1632]
Currently our calculations of age in years/months are approximate based on number of days, and as such are not calendar based.

We should find a way to represent calculate age in months via XPath.

**Comment by alxndrsn** [comment]
Hi @abbyad what else needs doing on this?

**Comment by abbyad** [comment]
When trying to use `difference-in-months` in a form I get:

`FormLogicError: Could not evaluate: difference-in-months( /model/instance[1]/pregnancy/patient_dob , today()), message: Function "{}difference-in-months" does not exist.`

**Comment by alxndrsn** [comment]
Is the non-working form available anywhere?  Would be useful for recreating the problem.

**Comment by abbyad** [comment]
@alxndrsn assigning back to you. In case you need the test xform again it is [here](https://github.com/medic/medic-projects/blob/master/lg-uganda/forms/difference-in-months.xml)

**Comment by alxndrsn** [comment]
Looks like we are not currently using the correct xpath library.

**Comment by alxndrsn** [comment]
To calculate age in years-and-months:

```
years: floor( difference-in-months( /difference-in-months/patient_dob , today() ) div 12 )
months:       difference-in-months( /difference-in-months/patient_dob , today() ) mod 12
```

**Comment by alxndrsn** [comment]
Should work on `develop`.

**Comment by abbyad** [comment]
Tested on `0.6.0-alpha.2598` and works well. Moving to Ready.
