### ISSUE TITLE
Forms from Tasks have different behaviour

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1634]
For consistency we should have the same behaviour for forms whether they are opened from a task or action.

Forms opened via a task should:
- [ ] use `x` in filter bar instead of `<`
- [ ] have warning message when exiting the form

**Comment by browndav** [comment]
FWIW, the flowchart has been updated over in Google Docs. I've cleaned it up a tiny bit further; let me know if anything looks out of place. In the original version, we missed labels/colors for a couple of return paths, including this one.

<img width="1660" alt="screen shot 2015-11-20 at 1 14 06 pm" src="https://cloud.githubusercontent.com/assets/763977/11312098/d803093a-8f88-11e5-8e52-3e9875cbf860.png">

**Comment by abbyad** [comment]
Thanks @browndav. One missing aspect is drilling into contacts. Right now we have it as a generic right side, but there are many pages within that (eg family list, family profiles, parent/child profiles). Ideally there would be some obvious way to reverse drilling into a family.

**Comment by abbyad** [comment]
Works well in 2710, moving to Ready.
