### ISSUE TITLE
Only show relevant forms in profile

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1635]
As a follow up to #1293, we are getting a lot of requests to only show the relevant forms. For the field test, the ones in question are:

**Pregnancy Registration**: only show for women over 10 years old
**Newborn Visit**: only show for women over 10 years old. Although we may need to show it only if they only have a previous Pregnancy Registration, current thinking they miss the pregnancy entirely and want to report a Newborn Visit.
**Assessment**: only shown for people under 12 years old.

We could make use context for this (eg `context.sex: 'female'`, `context.min_age: 10`, `context.max_age: 12`).

**Comment by mandric** [comment]
What is `context` is that something defined in the form?

**Comment by abbyad** [comment]
Context is defined on the form's doc in the db
https://github.com/medic/medic-webapp/issues/1293#issuecomment-146733069

**Comment by alxndrsn** [comment]
@mandric example of `.context`:

<img width="436" alt="screen shot 2015-11-27 at 09 16 08" src="https://cloud.githubusercontent.com/assets/191496/11435179/4f714c84-94e8-11e5-964d-9feee7f3c83c.png">

**Comment by alxndrsn** [comment]
I think a simpler and more powerful approach to this would be to supply a `function` for `formDoc.context` instead of a map, e.g.:

```js
// a form only shown for Places:
formDoc = {
  ...
  "context": "function(contact) {
    return contact.type !== 'person';
  }"
  ...
};

// a form only shown for women of childbearing age
formDoc = {
  ...
  "context": "function(contact) {
    return contact.type === 'person' &&
        (!person.sex || person.sex === 'female') &&
        yearDifference(person.date_of_birth, new Date()) >= 10;
  }",
  ...
};
```

We could simultaneously support the `object` configuration of `.context` if a simpler alternative was required.

The main drawback to this approach is that somehow we would need to `eval(doc.context)(contact)`, which may require some care to implement safely.  We would need to protect against code which does not parse properly, and code that throws `Error`s.

**Comment by alxndrsn** [comment]
More specific examples:
```js
// Pregnancy Registration: only show for women over 10 years old
function(c) {
  return c.type === 'person' &&
      (!c.gender || c.gender === 'female') &&
      (!c.date_of_birth || ageInYears(c) > 10);
}

// Newborn Visit: only show for women over 10 years old. Although we may need to show it only if they only have a previous Pregnancy Registration, current thinking they miss the pregnancy entirely and want to report a Newborn Visit.
// ^^ same as for _New Pregnancy_

// Assessment: only shown for people under 12 years old.
function(c) {
  return c.type === 'person' &&
      (!c.date_of_birth || ageInYears(c) < 12);
}
```

**Comment by alxndrsn** [comment]
May be more sensible to use [angular's `$parse` service](https://docs.angularjs.org/api/ng/service/$parse) instead of `eval`.  Util functions such as `ageInYears` would then need to be defined in `webapp`.

**Comment by alxndrsn** [comment]
Implemented on `testing`.  Example `.context` value for _New pregnancy_/`pregnancy` form:
```json
"context": "contact.type === 'person' && (!contact.gender || contact.gender === 'female') && (!contact.date_of_birth || ageInYears(contact) >= 12)",
```

**Comment by alxndrsn** [comment]
Added some doc for the `CONTEXT_UTILS` function definitions.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by abbyad** [comment]
Works well during initial testing using 2612. Moving to ready and will open new issues if any bugs are discovered.

**Comment by alxndrsn** [comment]
:+1:
