### ISSUE TITLE
Depend on the released version of enketo-core

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1637]
We have [our own branch of enketo-core](https://github.com/medic/enketo-core) which is falling behind of the [official version](https://github.com/enketo/enketo-core). Merge our changes into master, get that released to npm, and then depend on the npm release. This will make it easier to keep up to date with new features and bug fixes and get more eyes on our patches.

**Comment by alxndrsn** [comment]
Current dependency is on enketo-core `4.5.5`: https://github.com/medic/medic-webapp/blob/develop/package.json#L26

**Comment by alxndrsn** [comment]
Change to npm dependency building at https://travis-ci.org/medic/medic-webapp/builds/137488296

**Comment by alxndrsn** [comment]
Please review PR
