### ISSUE TITLE
Push enketo-client-side-transformer changes upstream

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1638]
We depend on [enketo-client-side-transformer](https://github.com/alxndrsn/enketo-client-side-transformer/) in production so it needs to be rigorously versioned, tested, and published. Get our changes merged upstream and published to npm.

**Comment by alxndrsn** [comment]
This may not be a realistic aim as our XSLT sheets target XPath `1.?` and https://github.com/enketo/enketo-transformer targets XPath `2.0`.  However, there are definitely things that should be cleaned up in this project, starting with making it a fork of https://github.com/enketo/enketo-transformer and making sure that the directory structure matches up with the parent project to reasonable degree.

**Comment by alxndrsn** [comment]
PR opened.  Changes have not been submitted upstream, but I will create a new ticket to merge latest upstream changes, and begin upstreaming discussions if it seems appropriate.

**Comment by garethbowen** [comment]
Nice one. One small change requested. Merge when ready!

**Comment by ngaruko** [comment]
Any tips how to AT this @garethbowen @alxndrsn

**Comment by garethbowen** [comment]
No AT required.
