### ISSUE TITLE
Hide location widget on android

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1642]
If `window.medicmobile_android`, we should hide the enketo location widget and instead prepopulate the field(s) via the `medicmobile_android.getLocation()` function.

**Comment by alxndrsn** [comment]
You can now access the location in enketo forms via the `<meta>` construction, if it's defined in the form definition, e.g.:
```xml
<model>
  <instance>
    <myForm>
      <inputs/>
      <objectData/>
      <meta>
        <location>
          <lat/>
          <long/>
        </location>
      </meta>
    </myForm>
  </instance>
</model>
```
I would then recommend adding logic to hide the geolocation page if `/myForm/meta/location/lat` and/or `/myForm/meta/location/long` are set.  Or just removing the geolocation page altogether, if that's acceptable.

The meta location fields will currently only be filled when accessing `medic-webapp` via `medic-android`.

**Comment by alxndrsn** [comment]
@abbyad looks like https://github.com/medic/medic-webapp/commit/aab1dbb8593c31ef9cdebeb00a19673360de9131#diff-e76a9763c437fc248cc2d411c0c97519R90 may re-break your forms; perhaps @garethbowen can advise on the new xpath to the `location` data.

**Comment by abbyad** [comment]
Thanks for the heads up @alxndrsn. Oddly the location seemed to still work, but the task inputs seem to be broken (#1697).

**Comment by abbyad** [comment]
The location page has been removed from all forms. Moving to acceptance testing.

**Comment by abbyad** [comment]
Works well as seen in #1724, moving to Ready.
