### ISSUE TITLE
Disallow unselecting of required radio buttons

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1643]
Clicking a checked enketo radio button will unselect it.  This can lead to confusing behaviour when a user double-taps a radio and it does not change.  This feature is conceivably useful for optional radio fields, but we could disable it for those marked as `required`, and save a little bit of frustration.

**Comment by garethbowen** [comment]
Optional radio buttons should have a radio option for "none" or similar, which may be selected by default. This will then behave consistently and as expected for anyone who's ever seen an html form.

**Comment by alxndrsn** [comment]
I'm not sure about requiring a third option.  In our current forms, non-required radios tend to have little or no logic attached to them, so click-handling is much quicker.

**Comment by alxndrsn** [comment]
Filed upstream: https://github.com/enketo/enketo-core/issues/347

**Comment by abbyad** [comment]
Has this feature been removed? I can deselect radio buttons in 2710.

**Comment by alxndrsn** [comment]
Feature no longer working due to https://github.com/enketo/enketo-core/issues/362.  Blocked pending response to that ticket.

**Comment by alxndrsn** [comment]
Fixed in https://github.com/medic/medic-webapp/commit/329b46609638cc63f30b299f89a8cf16005cec56 (commit tagged with wrong issue number).

**Comment by estellecomment** [comment]
LGTM
