### ISSUE TITLE
Add a debug mode

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1647]
Provide a way to toggle a debug flag. Storing it in a cookie might be best. Then use that flag to

- set the angular [log debug enabled](https://docs.angularjs.org/api/ng/provider/$logProvider)
- show information about the local pouch db
- anything else you can think of

**Comment by mandric** [comment]
Gareth, what do you think about surfacing something like this in the app?  http://pouchdb.com/api.html#debug_mode  Idea being that when the app is unresponsive you can enable debug mode then connect the device to chrome://inspect and look at the console.

**Comment by garethbowen** [comment]
Yeah nice! Turn on debug mode and we get our debug statements and those of our libraries.

**Comment by mandric** [comment]
Ok for now just printing in the console is good enough then go from there.

**Comment by mandric** [comment]
Also if we use cookies then the debug setting will be trashed when we close the app/browser, which I assume is fine for now.

**Comment by garethbowen** [comment]
That depends if we set an expiry date on the cookies. We can keep the cookies around for as long as we want. 1 year would be good.

**Comment by mandric** [comment]
Ok sounds like a plan.

**Comment by mandric** [comment]
![screen shot 2015-11-25 at 12 12 21 am](https://cloud.githubusercontent.com/assets/25641/11386534/3ec63c7c-9309-11e5-9dcc-84b1cd674c49.png)

**Comment by garethbowen** [comment]
A couple of missed internationalisations but otherwise, nice!

**Comment by garethbowen** [comment]
Merged!
