### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1648]
We need to make it clear to users what data is collected and what we use it for.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment]
I think this is the responsibility of our implementing partners.
