### ISSUE TITLE
Disable cancel buttons when saving

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1650]
The cancel button (`X`) can be clicked while a report is being saved. Disable it, here and anywhere else where it doesn't make sense. Also look at disabling the back button (`<`) if needed elsewhere.

**Comment by alxndrsn** [comment]
Would it make sense to have a `$scope.disableNavigation` flag in the `$scope` of `InboxCtrl`?  You might want to disable all sorts of stuff while a save is taking place, and for desktop users too.

**Comment by SCdF** [comment]
@browndav please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by browndav** [comment]
Placing this in the current milestone as technical debt. I think we should do this, at least for any save processes that are non-atomic, to minimize the possibility of bad/incomplete data being created.

**Comment by garethbowen** [comment]
Code review please @SCdF 

There are probably other buttons that could be disabled, and other actions which should disable buttons but this takes care of the low hanging fruit of the cancel buttons for enketo forms and modals. Other specific cases can be raised as separate issues.

**Comment by SCdF** [comment]
Merged.
