### ISSUE TITLE
Error loading tasks

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1651]
Sorry, no screenshot.  But picture this - an empty tasks list, a warning message carved in red across the screen:

> Error loading tasks

Other tabs seemed fine.
# Stacktrace

<img width="1280" alt="screen shot 2015-11-24 at 09 54 23" src="https://cloud.githubusercontent.com/assets/191496/11359990/e8d061f2-9291-11e5-9b42-903680154cce.png">
# Fix?

Restarted the app, and everything worked fine again.

**Comment by alxndrsn** [comment]
I rather suspect `SettingsP` service is returning `null`/`undefined`.

**Comment by alxndrsn** [comment]
If the commit above has achieved what I expect, we will now see "no tasks" instead of "tasks failed to load".  It's questionable if this is an improvement.

**Comment by alxndrsn** [comment]
N.B. seems to occur most commonly after a contact-action has been submitted (e.g. _Assess patient_, _New pregnancy_ etc.)

**Comment by alxndrsn** [comment]
Deprioritised in favour of https://github.com/medic/medic-webapp/issues/1702

**Comment by alxndrsn** [comment]
No longer deprioritised in favour of #1702

**Comment by sglangevin** [comment]
Haven't seen this recur unless there is an issue with task configuration. Re-open if it can be reproduced.
