### ISSUE TITLE
Delete button visible in action bar for users who cannot delete data

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1652]
For CHPs, the _delete_ rubbish bin is shown on a contact's action bar.  The button is grayed out, but is distracting because these users can *never* delete anything.  Would be nice if we could just hide it.

**Comment by garethbowen** [comment]
Currently the delete icon enables and disables depending on which contact you select. We should implement a permission for "can_delete_contact" or similar to show/hide the button. I'll do this as part of #1851

**Comment by garethbowen** [comment]
Permission added as part of #1851 which will take care of the code review. Moving this to acceptance testing.
