### ISSUE TITLE
Can't create a new family

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1654]
# Config

`android`: `0.1.111`
`webapp`: `.2407`

# Observed

Cannot create a new contact - on form submit:

<img width="1280" alt="screen shot 2015-11-24 at 10 50 59" src="https://cloud.githubusercontent.com/assets/191496/11360899/b4976590-9299-11e5-8928-fc260629a4df.png">

**Comment by garethbowen** [comment]
My best guess is that your local db doesn't have the contact that's associated with your user. This could be a replication permission issue or just a delayed replication.

**Comment by alxndrsn** [comment]
This instance was likely caused by delayed replication.  Is there anything we can do to delay app use until this `contact` has been replicated?

**Comment by garethbowen** [comment]
There are issues for adding more into the bootstrapping process. Initial syncing can be part of this but it's slightly tricky to know when you're done.

**Comment by alxndrsn** [comment]
Presumably working now.
