### ISSUE TITLE
Unrecognized input type found when trying to reset

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1655]
No idea what this is - worth investigating:

<img width="1014" alt="screen shot 2015-11-24 at 10 57 00" src="https://cloud.githubusercontent.com/assets/191496/11360940/2039a240-929a-11e5-80f7-60303f4f5af7.png">

**Comment by alxndrsn** [comment]
Found when cloning repeated elements in the _Add Family_ form.

`enketo-core` should probably be treating unknown field types as per `text`.

**Comment by alxndrsn** [comment]
This has no observed affects apart from the log message.

**Comment by alxndrsn** [comment]
From reading the source, this may have unobserved effects:

> ```
                switch ( type ) {
                    case 'date':
                    case 'datetime':
                    case 'time':
                    case 'number':
                    case 'search':
                    case 'color':
                    case 'range':
                    case 'url':
                    case 'email':
                    case 'password':
                    case 'text':
                    case 'file':
                        $node.removeAttr( 'data-previous-file-name data-loaded-file-name' );
                        /* falls through */
                    case 'hidden':
                    case 'textarea':
                        if ( $node.val() !== '' ) {
                            $node.val( '' ).trigger( ev );
                        }
                        break;
                    case 'radio':
                    case 'checkbox':
                        if ( $node.prop( 'checked' ) ) {
                            $node.prop( 'checked', false );
                            $node.trigger( ev );
                        }
                        break;
                    case 'select':
                        if ( $node[ 0 ].selectedIndex >= 0 ) {
                            $node[ 0 ].selectedIndex = -1;
                            $node.trigger( ev );
                        }
                        break;
                    default:
                        console.error( 'Unrecognized input type found when trying to reset', this );
                }
```
> – _https://github.com/enketo/enketo-core/blob/4.5.5/src/js/plugins.js#L33_

I.e. it looks like unrecognized field types will not be reset when `form.clearInputs()` is called, which may lead to fields in repeat groups copying their value from the first instance of the group in the current form.  This behaviour has been observed previously in the LG _Add Family_ form's child details section, but I cannot find the relevant issue.

**Comment by sglangevin** [comment]
Here is one issue that is somewhat related: https://github.com/medic/medic-projects/issues/351. I also noticed some strange behavior when creating multiple children using repeat.child as I was trying to test out a new approximation for birthday when the user enters an age. My debug fields always displayed the age from the previous child, not the child I was currently creating. So, if I were using repeat.child to create 3 children, the second child would show a birthdate based on the first child's age. Everything was saved correctly, though.

**Comment by alxndrsn** [comment]
Interesting!  Is that date bug filed anywhere?  If not I think it deserves an issue of its own.

**Comment by sglangevin** [comment]
I didn't file it because when I actually created the children, they all had the correct ages - it was my debug fields that were having an issue. Could be worth fixing. Another tangentially related issue (since we're talking about `repeat`) is that we only support repeat.child and we can't have other repeated person creation in the same form. @henokgetachew ran into this while building BRAC forms - he wanted to have two `repeat` groups - one for children, one for women. The workaround was to combine both for now.

**Comment by alxndrsn** [comment]
OK.  This one's definitely a bug:

> we can't have other repeated person

please file!
