### ISSUE TITLE
Warn users, or prevent them from using android app, when device date is set incorrectly

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1658]
A common problem reported by LG is that CHPs will swap SIMs or battery-out restart their phones, so losing the time & date settings.  When the app is restarted with a date far in the past, _Tasks_ will no longer be correctly calculated.

A suggested way to handle this is record the "previous start time" of the app.  When restarting, if the new start time is less than the last start time, show the user a warning, or block them from using the app.  E.g.

> Your phone's date is set in the past.  Reported date:
>   1 January 1970
> Please update the phone date.
> [ *ignore* ] [ *exit* ]

**Comment by garethbowen** [comment]
Smartphones are supposed to have an internal clock on a separate battery to retain the date even if the battery and sim are removed. So this shouldn't happen unless the phone is left off for a very long time, or the device is faulty. This probably won't happen often enough to warrant the added complexity, but worth looking into.

**Comment by alxndrsn** [comment]
Apparently seen commonly on the old LG app, which is an android app so I don't see why the battery would work better for us.

**Comment by alxndrsn** [comment]
@abbyad how does this look to you?

<img width="322" alt="screen shot 2016-01-11 at 12 38 38" src="https://cloud.githubusercontent.com/assets/191496/12232597/4945d924-b860-11e5-9630-689a9a27e5e2.png">

**Comment by garethbowen** [comment]
No response from @abbyad so proceeding with Code Review.

I've added comments to the PR.

**Comment by alxndrsn** [comment]
* moved to a service (`CheckDate`)
* added warning if server cannot be contacted/server does not respond with expected header
* changed translations to `dot.format` and moved the english values to API
* removed stray `console.log`

**Comment by abbyad** [comment]
Sorry for the late reply on this. Overall this looks good and really useful to avoid issues. 

@diannakane and the design team can help with more formal acceptance testing once it has passed code review. At that time we can also refine the text to make it appropriate for the project. For instance we may want to avoid `date/time` if it sounds too technical for the users, and also tell them to bring their phone to their branch if they aren't expected to change the date themselves.

**Comment by alxndrsn** [comment]
@marc thanks for the feedback.  Messages are configurable through the normal translation config.  We would have to tweak it a bit if the 2 dates are to be hidden for a particular use case.

**Comment by garethbowen** [comment]
@alxndrsn One more comment on https://github.com/medic/medic-webapp/commit/71a8714ae439aba4f1eb9e6965d375cdc1b40fd6 , but otherwise all good.
