### ISSUE TITLE
Disallow phone numbers in Name fields

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1660]
There is concern, especially when registering a Family, that a user may enter a phone number in the name field.  If we could validate the name field to disallow numbers, or disallow phone numbers, then this might prevent bad data being submitted.

**Comment by abbyad** [comment]
We can easily set a regex... but a bigger question is what to restrict this to. Do we want to accept only letters and some special characters, or do we want to exclude series of numbers?

@alxndrsn if you have a suggestion of a regex I can include that in our testing version of the forms.

**Comment by alxndrsn** [comment]
`/^\D*$/` should exclude any digits; `^[0-9+]*$/` should exclude digits and the `+` character.  If we want to exclude punctuation as well, then things would get more complicated, but this seems less important if we're just trying to protect against _name_ and _phone number_ fields being confused.

**Comment by browndav** [comment]
Is this a priority for February 21st? If not, I'd propose that this should be deprioritized for this iteration to allow additional time for form performance improvement, targets, and analytics support.

**Comment by abbyad** [comment]
@sglangevin is this still required?

**Comment by sglangevin** [comment]
@abbyad I think we can hold off on this for now. During our last discussion, we raised the point that CHPs might need numbers to indicate different families with the same name, so we didn't want to limit this field to exclude numbers. I could see limiting the number of numbers that are in this field, but perhaps we should just monitor the data first to see how often this mistake happens? I will confirm this today.

**Comment by garethbowen** [comment]
This can be done as part of xforms validation. Reopen if there's anything we need to do in the app to allow this.
