### ISSUE TITLE
HBB from Assess Patient form is broken

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1662]
Going to the assessment form via a family member's contact page:

> Error loading form.
> Please try again or check with an administrator.

<img width="1280" alt="screen shot 2015-11-24 at 15 22 59" src="https://cloud.githubusercontent.com/assets/191496/11366605/4d23a5d8-92bf-11e5-87e2-303df895077f.png">
<img width="1280" alt="screen shot 2015-11-24 at 15 23 01" src="https://cloud.githubusercontent.com/assets/191496/11366607/5011539e-92bf-11e5-990d-e1fa263e29a9.png">

Pressing HBB again takes you back to the assessment form.  Repeat the circle indefinitely if you wish.

**Comment by garethbowen** [comment]
Closing as a duplicate of #1649
