### ISSUE TITLE
Client side performance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1666]
We recently had 20 users log in and perform regular actions and noticed some performance issues. In particular it could take 15 seconds to load a form on the Y4.

Investigate and benchmark client side performance, attempt to make improvements, and benchmark again.

**Comment by garethbowen** [comment]
It could be that having 20 users all adding documents which are then replicated to the other 19 is the bottleneck. It's known that when pouchdb is under load it blocks enketo and dom rendering. Investigate running pouchdb in a web worker which will split the db work into another thread: https://github.com/nolanlawson/worker-pouch

**Comment by garethbowen** [comment]
Ensure we're not replicated more than is necessary. I _think_ we're replicating audit docs which doubles the bandwidth and processing required, and is completely unused on the client.

**Comment by alxndrsn** [comment]
15s form load is normal.  With 20 clients logged in as same user, these times increase significantly.

**Comment by estellecomment** [comment]
LG phone users complain the app is slow, which makes it hard to use.

**Comment by garethbowen** [comment]
This issue is too generic and is covered by a range of other more specific issues. Closing as duplicate.
