### ISSUE TITLE
When viewing + menu in History, have to press Contacts tab twice to get to Contacts

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1669]
Seen on android.

**Comment by alxndrsn** [comment]
Not very conerning.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
On mobile, when the popup menu for the Actions is open, tapping anywhere outside of it closes the menu, without navigating to anything. So it's the case for the Contacts tab, but also for any other navigation. 

Looks like expect behavior to me, so I'm closing, @diannakane or @amandacilek if that sounds wrong please reopen.

**Comment by alxndrsn** [comment]
If all keypresses are blocked while a menu is displayed, it might help to grey out the rest of the screen a bit while the menu is opened.

**Comment by estellecomment** [comment]
Closing since Actions menu is going to change in upcoming nav redesign so it won't matter.
