### ISSUE TITLE
Black screen pops up on pressing submit button

### ISSUE THREAD

**Issue by ngamita** [medic/medic-webapp#1674]
@alxndrsn Soon as submit button is clicked a number a times app hangs and throws the attached black screen of death. 
![screenshot_2015-11-25-10-58-33](https://cloud.githubusercontent.com/assets/294861/11391604/c4439e66-9364-11e5-8f4b-76c964ce6900.png)

**Comment by browndav** [comment]
Which submit button are you pressing?

**Comment by sglangevin** [comment]
Closing as this is old and has not been reproduced.
