### ISSUE TITLE
Date entry popup in black won't dissapear from screen 

### ISSUE THREAD

**Issue by ngamita** [medic/medic-webapp#1675]
@alxndrsn Continuously happening when a user enters in a date the popup keeps on the screen and in black 
![screenshot_2015-11-25-11-51-52](https://cloud.githubusercontent.com/assets/294861/11392639/1d1fc0b2-936c-11e5-99bb-2bacb7ad8b48.png)

**Comment by browndav** [comment]
Looks like may be covered by #1557. @ngamita: Confirm?

**Comment by alxndrsn** [comment]
Confirmed.

**Comment by browndav** [comment]
You're seeing it on both mobile and on the desktop?

**Comment by alxndrsn** [comment]
Mobile only.  On mobile it's meant to appear on poke, and disappear when u poke somewhere else; on desktop it's just `:hover`
