### ISSUE TITLE
Tasks are often out of sync

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1678]
Sometimes the task list is empty.  Sometimes a task will appear for a user, even though it has been completed.  I think this is due to out-of-date task configuration.  The current fix we are using is to use `Options > Home` option in the android app.

A Trainer has requested a refresh button on every page.

**Comment by alxndrsn** [comment]
Looks relevant: https://github.com/medic/medic-webapp/issues/1678.  In a perfect world, we'd run a wifi AP in our office with deliberately poor connection.

**Comment by garethbowen** [comment]
Should be improved by #1986 . Closing to get acceptance testing. Reopen if you notice this happening again.
