### ISSUE TITLE
can't switch between users in same browser

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1679]
So as an admin I would like to be able to login as a specific user to see what they are seeing mainly to just troubleshoot issues remotely and help them use the application.  It's quite error prone to remember to have a separate browser to accomplish this task and even more difficult to recover from it when the app lets you do it.  The app should either warn before allowing it, not allow it, or support it.

**Comment by garethbowen** [comment]
Related to #1005

**Comment by alxndrsn** [comment]
Need to update local DB name at:

* https://github.com/medic/medic-webapp/blob/develop/static/js/app.js#L396
* https://github.com/medic/medic-webapp/blob/develop/static/js/services/db.js#L31

...and possible other places...

**Comment by alxndrsn** [comment]
It's not immediately clear how to get the username at https://github.com/medic/medic-webapp/blob/develop/static/js/app.js#L396, as we are not inside the angular app at this point.

**Comment by alxndrsn** [comment]
@garethbowen @abbyad this change means existing users will need to re-synch their data.  Unless we want to try writing client-side migrations!
