### ISSUE TITLE
Loading some xforms takes too long to be practical

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1682]
Some very large forms (eg [assessment](https://github.com/medic/medic-projects/tree/master/lg-uganda/forms/assessment.xml)) can take around 15 seconds to load on a Tecno Y4. We should profile the load to see where we can gain time. For instance, it may help to reduce the xml size, the number of fields, or number or size of calculations.

**Comment by garethbowen** [comment]
Caching the transformed xml saves me about 5 seconds on the second load. I'll keep working on it.

**Comment by alxndrsn** [comment]
Caching sounds like it will be a very good improvement.  Current implementation introduced #1716, so have reverted it, but we should look to re-instate when issues can be resolved.

**Comment by abbyad** [comment]
Form performance is still an issue, but better due to other performance work that was done. We will do some speed testing in the field to determine if the caching needs to be un-reverted and fix for further improvements.

**Comment by alxndrsn** [comment]
> determine if the caching needs to be un-reverted and fix for further improvements

AFAIK caching is implemented on `develop` and `testing` already.

**Comment by garethbowen** [comment]
TODO: work out what state this is in and update the issue.

**Comment by garethbowen** [comment]
It looks like the "revert" commit above was reintroducing the code, not reverting it out. As Alex said, it's implemented in [develop](https://github.com/medic/medic-webapp/blob/develop/static/js/services/enketo.js#L55) and [testing](https://github.com/medic/medic-webapp/blob/testing/static/js/services/enketo.js#L54).
