### ISSUE TITLE
Hide logout option from CHPs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1685]

**Comment by garethbowen** [comment]
@alxndrsn Didn't we just talk about this in Slack and decide not to do it?

**Comment by garethbowen** [comment]
Whether or not we hide the logout action, under the current design _all_ CHPs will have to log in again at some point. If you don't bother training them on how to do this, or worse still, don't provide them with their username and password then they will have to call an administrator to get instructions. I strongly disagree with this change.

**Comment by garethbowen** [comment]
@joshnesbit mentioned in Slack that the only issue for CHPs was accidentally hitting the logout button. Given this it seems to me that a confirm dialogue would solve this issue rather than removing the button altogether.

**Comment by alxndrsn** [comment]
@garethbowen please review.  Hopefully this change is not too intrusive and can easily be reversed when we find a more pleasing approach.

**Comment by alxndrsn** [comment]
@abbyad this will require suitable extra permissions to be set up (i.e. `cannot_logout`)

**Comment by garethbowen** [comment]
I'm not happy with the solution as it is. Will discuss with @browndav and fix the code tomorrow.

**Comment by mandric** [comment]
Work was continued for this elsewhere: https://github.com/medic/medic-webapp/pull/1730
