### ISSUE TITLE
HBB in date selecter invalidates date field

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1693]
# Steps to recreate

1. open _New Pregnancy_ form
1. browse until LMP page
1. click the date field
1. observe datepicker has appeared
1. press HBB
1. try opening the datepicker again
1. observe that it does not open [THE BUG]
1. select _date unknown_
1. unselect _date unknown_
1. click the date field
1. observe that the datepicker now opens successfully

**Comment by abbyad** [comment]
In trying to get a screenshot I was not able to reproduce this issue. Using the Add Family Member, the date field ends up blank after unchecking date unknown.

**Comment by alxndrsn** [comment]
Sounds like a separate issue - please file!
