### ISSUE TITLE
Contacts within family are not (always?) sorted by age

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1694]
[TODO @abbyad provide screenshot]

**Comment by abbyad** [comment]
I don't have a screenshot handy, but here is what we did:
- "Add Family" with male as primary caregiver (26 years old) and two children (3 and 5 years old)
- "Add Family Member" for a woman (24 years old).
This last family member showed up on the bottom of the family members list, even after a refresh. We were expecting it to be second from the top.

**Comment by alxndrsn** [comment]
Not surprising, as `doc.date_of_birth` is being stored as a string, but all our code expects a number (presumably a timestamp of some sort).  I'd consider changing the form to save as a number.

**Comment by abbyad** [comment]
After some testing I've confirmed that the date in format `MMM DD, YYYY` is the source of the problem. Switching it to YYYY-MM-DD fixes the problem. Will revise all existing forms, although that won't affect existing contacts.

**Comment by abbyad** [comment]
This should work now for new contacts on lg.dev. @alxndrsn, ready for acceptance testing.

**Comment by ngaruko** [comment]
I assume the main contact is meant to be always top of the list regardless of their age.? Then LGTM.
