### ISSUE TITLE
Replication does not always complete

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1695]
Sometimes replication does not always complete when the app is installed on a new phone.  Most common/obvious symptom is that a couple of forms are missing from _History_ > **action-bar-+**.  Waiting for a few hours may slowly see the forms arriving.

**Comment by alxndrsn** [comment]
I suspect large files (`app_settings`, form attachments) are harder to replicated.  Pouch may have to restart fully a download that fails part way.

**Comment by alxndrsn** [comment]
Looks relevant: https://stackoverflow.com/questions/654915/are-there-any-programs-that-can-simulate-an-unstable-network-connection#655143

**Comment by garethbowen** [comment]
@alxndrsn So the documents do replicate eventually, or do you have to reinstall? Have you noticed any replication errors in console or the network tab?

**Comment by alxndrsn** [comment]
I will try to share screenshots of the Network tab in relevant situations.  Here's one to kick us off - failing to download the appcached app itself:

<img width="1280" alt="screen shot 2015-11-30 at 10 01 36" src="https://cloud.githubusercontent.com/assets/191496/11465422/934048f8-9749-11e5-83bd-f7dacbbf0844.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 02 56" src="https://cloud.githubusercontent.com/assets/191496/11465424/9728f118-9749-11e5-83ce-d364539033c4.png">

**Comment by alxndrsn** [comment]
On my current connection (hotel wifi; not sure of the uplink), this is happening consistently, but at different points of the `ddoc`.  The internet itself is quite usable so far this morning.  Here's another example:

<img width="1280" alt="screen shot 2015-11-30 at 10 07 43" src="https://cloud.githubusercontent.com/assets/191496/11465511/61049fdc-974a-11e5-8521-c4a2d7151003.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 07 45" src="https://cloud.githubusercontent.com/assets/191496/11465512/638e0702-974a-11e5-95fd-60fdb301f23c.png">

**Comment by alxndrsn** [comment]
<img width="1280" alt="screen shot 2015-11-30 at 10 11 38" src="https://cloud.githubusercontent.com/assets/191496/11465626/6f33cc6c-974b-11e5-908e-d6da67ddcc30.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 13 01" src="https://cloud.githubusercontent.com/assets/191496/11465630/73d48a90-974b-11e5-8951-3c6e2e0df144.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 13 38" src="https://cloud.githubusercontent.com/assets/191496/11465632/77ccc5cc-974b-11e5-87ec-6b226482a898.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 14 11" src="https://cloud.githubusercontent.com/assets/191496/11465633/7b3cfb00-974b-11e5-9d49-4a29c4d3076e.png">

<img width="1280" alt="screen shot 2015-11-30 at 10 15 05" src="https://cloud.githubusercontent.com/assets/191496/11465638/7ed04d76-974b-11e5-8ba1-53870b96bce5.png">

**Comment by alxndrsn** [comment]
# Finally, success!

<img width="1280" alt="screen shot 2015-11-30 at 10 27 08" src="https://cloud.githubusercontent.com/assets/191496/11465787/00f7af0a-974d-11e5-9585-7be2ac865a8d.png">

**Comment by alxndrsn** [comment]
HAR uploaded above may be interesting.

**Comment by estellecomment** [comment]
I had a neverending replication, when cloning the lg-dev db to my local server. 
There were 12-ish docs that didn't replicate, one of which was huge : an audit_record of the ddoc, I think. We might not want to generate these giant audit_records, maybe a diff would be enough.

Can't reproduce it though.

**Comment by mandric** [comment]
If you see an audit record of a ddoc that's a bug.

**Comment by estellecomment** [comment]
Interesting. I didn't save it, so not 100% sure. 
I am sure it was a giant audit_record though.

**Comment by alxndrsn** [comment]
I really hope the audit record isn't being cloned to clients...

**Comment by alxndrsn** [comment]
@mandric what's going on with this ticket?  Is it work in progress and should it be in the current miestone?

**Comment by browndav** [comment]
@mandric: What's the status of this ticket?

**Comment by SCdF** [comment]
This cannot be replicated anymore.
