### ISSUE TITLE
Patient info not being passed to a form from the task

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1697]
Opening a task's action form no longer gets the associated content. The effect is that cannot pass the patient info to a form opened from a task. This worked until an update today on lg.app to `0.6.0-beta.2432`

The task generation code has not changed, and has the following:
```
            content: {
              patient: c.contact
            }
```

**Comment by alxndrsn** [comment]
_New Pregnancy_ form can be made to work from _Tasks_ if root node of `instance` is changed from `pregnancy` to `data`.

**Comment by alxndrsn** [comment]
Regression may have been caused by the change at https://github.com/medic/medic-webapp/commit/01de6a0c5fe8e255fbfe973252aa6269a7835a39#diff-26d6a059679f2953a553f097cb2fb1c4L41

**Comment by garethbowen** [comment]
Yes it's definitely that @alxndrsn . I tracking it down now.

**Comment by abbyad** [comment]
This has been working for several months now, moving to Ready.
