### ISSUE TITLE
Submitting standard XForms no longer works

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1698]
<img width="1280" alt="screen shot 2015-11-27 at 22 12 04" src="https://cloud.githubusercontent.com/assets/191496/11447410/bf6b5bec-9556-11e5-87a1-73af5d29ca45.png">

**Comment by mandric** [comment]
Estelle if you think it's useful/relevant can you submit the steps to recreate this?
```
inbox.js:30838 TypeError: Cannot read property 'childNodes' of undefined
    at self.getHiddenFieldList (inbox.js:43401)
    at inbox.js:43814
    at processQueue (dependencies.js:14567)
    at dependencies.js:14583
    at Scope.$eval (dependencies.js:15846)
    at Scope.$digest (dependencies.js:15657)
    at dependencies.js:15885
    at completeOutstandingRequest (dependencies.js:5394)
    at dependencies.js:5666console.(anonymous function) @ inbox.js:30838
2015-12-11 18:31:55.209 inbox.js:30838 Error submitting form data:  TypeError: Cannot read property 'childNodes' of undefined
    at self.getHiddenFieldList (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:43401:34)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:43814:46
    at processQueue (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:14567:28)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:14583:27
    at Scope.$eval (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15846:28)
    at Scope.$digest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15657:31)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:15885:26
    at completeOutstandingRequest (http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:5394:10)
    at http://localhost:5988/medic/_design/medic/_rewrite/static/dist/dependencies.js:5666:7
```

**Comment by alxndrsn** [comment]
@mandric did you want to tag @estellecomment?

**Comment by estellecomment** [comment]
Reproduce : 
Create a district hospital ("My 2nd hospital" in screenshots). As contact person, select new, and create a new Contact. ("Contact Person")
The new hospital doesn't display a contact person. The new contact person has "First Contact for" listed, but is not associated to My 2nd Hospital properly (compare with Estelle Comment and My Hospital)

![screen shot 2015-12-14 at 11 56 59](https://cloud.githubusercontent.com/assets/911434/11779359/c4eecf48-a25a-11e5-84bc-d3d268f2c081.png)
![screen shot 2015-12-14 at 11 57 29](https://cloud.githubusercontent.com/assets/911434/11779360/c4f0da72-a25a-11e5-875f-90fcd15147e6.png)
![screen shot 2015-12-14 at 12 00 08](https://cloud.githubusercontent.com/assets/911434/11779357/c4e9601c-a25a-11e5-9e07-b69a4016abad.png)

Add a form : uploaded this one : 
https://github.com/medic/medic-projects/blob/master/demo-anc/forms/ANC_Delivery.xml
Using this script : 
https://github.com/medic/medic-webapp/blob/develop/scripts/upload_xform.sh
Go to reports, fill in the form, submit -> error.

![screen shot 2015-12-14 at 12 03 04](https://cloud.githubusercontent.com/assets/911434/11779358/c4ec8a1c-a25a-11e5-9387-72cf5cafa32c.png)

-------------------------
DB docs : 
My 2nd Hospital : 
{
   "_id": "279e51d3c2930edd96c86abff22128f2",
   "_rev": "1-daacc108fbb05cc31df7fc4c5b304293",
   "name": "My 2nd Hospital",
   "contact": {
       "_id": "279e51d3c2930edd96c86abff2210508",
       "_rev": "1-a69037c1a77d6b640fb3241d640f983f",
       "last_name": "Person",
       "first_name": "Contact",
       "date_of_birth": "2015-12-14",
       "phone": "+33612345678",
       "alternate_phone": "",
       "notes": "",
       "type": "person",
       "reported_date": 1450090546786,
       "name": "Person Contact"
   },
   "external_id": "",
   "notes": "",
   "type": "district_hospital",
   "reported_date": 1450090546950
}
------------------
Contact Person : 
{
   "_id": "279e51d3c2930edd96c86abff2210508",
   "_rev": "1-a69037c1a77d6b640fb3241d640f983f",
   "last_name": "Person",
   "first_name": "Contact",
   "date_of_birth": "2015-12-14",
   "phone": "+33612345678",
   "alternate_phone": "",
   "notes": "",
   "type": "person",
   "reported_date": 1450090546786,
   "name": "Person Contact"
}
------------------

**Comment by mandric** [comment]
In static/js/services/enketo-translation.js:getHiddenFieldList fails because outputs here is undefined. findChildNode cannot find any 'outputs' nodes.

```
self.getHiddenFieldList = function(model) {
  model = $.parseXML(model).firstChild;
  var outputs = findChildNode(model, 'outputs');
  return withElements(outputs.childNodes)
    .filter(function(n) {
      var attr = n.attributes.getNamedItem('tag');
      return attr && attr.value === 'hidden';
    })
    .map(function(n) {
      return n.nodeName;
    })
    .value();
};
```

the model for the medic-projects/demo-anc/forms/ANC_Delivery.xml form looks like below:
```
<data id="D" version="2015-06-05">
  <delivery_code tag="c">F</delivery_code>
  <pregnancy_id tag="id">234533334</pregnancy_id>
  <notes tag="n"/>
  <meta>
    <start tag="m_st">2015-12-15T18:00:00.000-06:00</start>
    <end tag="m_et">2015-12-15T18:00:00.000-06:00</end>
    <phonenumber tag="m_p">no phonenumber property in enketo</phonenumber>
    <deviceID tag="m_d">no uri:deviceid property in enketo</deviceID>
    <subscriberID tag="m_s">no uri:subscriberid property in enketo</subscriberID>
    <instanceID tag="m_i">uuid:0084fbe9-1731-4512-8d6a-d32f12cd360e</instanceID>
    <instanceName tag="m_n">Delivery: 234533334</instanceName>
  <deprecatedID/></meta>
</data>
```

Any idea what is the proper behavior when no outputs nodes are found?  Does this mean the form is not actually valid/won't work with enketo?

**Comment by alxndrsn** [comment]
Without `<outputs>`, form is still valid with enketo - `<outputs>` is a medic convention.

**Comment by browndav** [comment]
Marc believes this is resolved.

**Comment by abbyad** [comment]
Tested and this works. Moving to ready.
