### ISSUE TITLE
Remove Help pages from `app_settings`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1700]
Help pages should be stored in their own docs in the db.  Currently they are in `app_settings`, adding a lot of size.

**Comment by alxndrsn** [comment]
Fixed in #1792 - please review

**Comment by alxndrsn** [comment]
If this is merged, help pages will no longer be specified in the ddoc.  Instead, an individual doc should be created for each help page, with the following properties:

```
{
  _id: 'help:...',
  type: 'help',
  title: {
    en: 'English title here; any other title translations should be provided in addition.',
  }
  body: {
    en: 'English help text here; any other help translations should be provided in addition.',
  }
}
```

**Comment by alxndrsn** [comment]
Fixed in PR #1793 - please review

**Comment by garethbowen** [comment]
Comments and suggestions added to the PR. Nice work!

**Comment by alxndrsn** [comment]
Any idea how we get the help content into an app at deploy time?  or do we just manually upload later?  not sure how the latter would work for DIY

**Comment by alxndrsn** [comment]
Changes:
* use `Language` service in `AboutCtrl` and `HelpCtrl`
* remove naughty comma


Nothing done about Markdown, because it's not actually an additional lib.  Happy to replace with showdown, although last time I looked showdown was not accessible from angular code.  Perhaps @mandric can advise on this.

**Comment by alxndrsn** [comment]
This is now merged to `develop`.

**Comment by garethbowen** [comment]
@alxndrsn My initial thought is to upload the standard help library when api starts up. Obviously this will increase the size of the ddoc, but that's how couchapps work...

Quite a lot of time and effort was put in to the existing help pages so we should convert them to markdown and get them working before closing this issue off.

**Comment by alxndrsn** [comment]
Re-uploading help pages is quite separate to this implementation work.  It has been filed at #1895.
