### ISSUE TITLE
shows "no tasks" when loading tasks

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1701]
# Observed behaviour
Browser-refresh while on the tasks tab
## 1
<img width="1280" alt="screen shot 2015-11-28 at 11 32 12" src="https://cloud.githubusercontent.com/assets/191496/11450946/c36845da-95c3-11e5-91dd-1328b5555782.png">

## 2
<img width="1280" alt="screen shot 2015-11-28 at 11 32 13" src="https://cloud.githubusercontent.com/assets/191496/11450947/c6f24d40-95c3-11e5-8054-6be096198f5e.png">

## 3
<img width="1280" alt="screen shot 2015-11-28 at 11 31 53" src="https://cloud.githubusercontent.com/assets/191496/11450950/d15a6c36-95c3-11e5-99c7-db03a718c168.png">

## 4
<img width="1280" alt="screen shot 2015-11-28 at 11 32 05" src="https://cloud.githubusercontent.com/assets/191496/11450951/d4dfeeb2-95c3-11e5-9d4f-b8fed3207802.png">

# Expected behaviour

Should show "loading" anim until loading is completed.

**Comment by garethbowen** [comment]
I think this is due to the Task Generator emitting tasks asynchronously, so we never know when it's done.

**Comment by alxndrsn** [comment]
Work done in #1787

**Comment by alxndrsn** [comment]
Nice work, @SCdF
