### ISSUE TITLE
Show *Try Again* option on `Error loading tasks` screen

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1702]
If https://github.com/medic/medic-webapp/issues/1651 cannot be fixed soon, adding a refresh button labeled `Try Again` would be an improvement on the current - right now we have to _Hardware-Options_ > _Home_ on mobile to reload the tasks.

**Comment by alxndrsn** [comment]
I'm concerned that this may not fix the issue - hitting "Try again" does not actually cause `settings` to be reloaded, so if this fails the first time, it may never succeed.

**Comment by browndav** [comment]
Current solution not working. Suggestion: make the "Try Again" button reload the whole page.

**Comment by abbyad** [comment]
Works for now until #1651 is resolved. Moving to Ready.
