### ISSUE TITLE
Increase server session timeout for lg.app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1703]
Server session timeout is currently 24 hours.  Please set to 1 year, as this should cover the duration of the trial.

**Comment by mandric** [comment]
Ok increased couch_httpd_auth timeout value to 31536000.  Should I do the same for lg.dev?

**Comment by alxndrsn** [comment]
@mandric yes please

**Comment by mandric** [comment]
done

**Comment by mandric** [comment]
If we wanted to make it a default on medic-os we'd do that in the couchdb config here: https://github.com/medic/medic-os/platform/packages/medic-core/settings/medic-core/couchdb/default.ini
