### ISSUE TITLE
Store translations in a separate doc

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1706]
Translations are currently stored in the ddocs app_settings. This makes the dashboard settings page very slow to render and difficult to use. We already provide our own translation UI for configuration, import, export, etc.

Consider using two docs, one for the raw translations which keeps track of default values, and one smaller one which just has the "winning" translation. That way we can replicate only the latter which will greatly simplify the client side translation code and send less data to the client.

**Comment by alxndrsn** [comment]
:+1:
Sending less data to the client is a win, but also splitting app settings into multiple docs is a win in itself for clients with poor connectivity.

**Comment by alxndrsn** [comment]
Moving to backlog as no milestone is assigned.

**Comment by garethbowen** [comment]
We could also only replicate the "enabled" languages to save on data.

**Comment by garethbowen** [comment]
Maybe think about storing the properties docs in webapp rather than api. Api works fine but it's a pain to have to commit to both repos, then bump the submodule, for simple UI changes.

**Comment by garethbowen** [comment]
Moving translations out of app settings will make it harder to add translations, so we may also need to do https://github.com/medic/medic-webapp/issues/1333

**Comment by garethbowen** [comment]
Ready for code review in three parts:

1. [medic-webapp](https://github.com/medic/medic-webapp/pull/2441)
  - Modify the translation loader to load from the translation documents instead of from settings.
  - Move the default translation files here from medic-api to save us having to bump api so much.
  - Attach the translation files to the ddoc so api can access them.
  - Rework the configuration pages for the new structure
  - Add a new Add Translation button so new translations can be added. This is the last piece of functionality that required translations to be available through the app-settings management screen.
  - Refactor modals to use the new Modal service so they're initialised when required, not when the app loads
  - Refactor controllers and services to use ngInject
  - Refactor ImportProperties to be promise based
2. [medic-api](https://github.com/medic/medic-api/pull/82)
  - Write a translations migration to turn the old configuration into the new docs
  - Modify the translations startup script to merge translations using the new structure
  - Modify the internationalisation code to use the new structure
3. [medic-sentinel](https://github.com/medic/medic-sentinel/pull/76)
  - Modify the internationalisation code to use the new structure
  - Removed the translation defaults because they were all defaulting to the key value, which is fallback procedure if a translation is not found.

**Comment by mandric** [comment]
Ok a few comments, feel free to merge.

**Comment by garethbowen** [comment]
Acceptance testing:
- Ensure all previously defined translations are preserved
- Check all the Language and Translation configuration features to ensure they work as expected
