### ISSUE TITLE
form modal cancel button does not have enough padding

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1707]
Looks a bit close to the edge of the dialog on the left; hovering shows it maybe doesn't have enough padding

<img width="1280" alt="screen shot 2015-11-30 at 00 11 39" src="https://cloud.githubusercontent.com/assets/191496/11460096/0391ac1c-96f7-11e5-968e-5be98144de11.png">

**Comment by garethbowen** [comment]
I made it consistent with the other buttons (eg: Continue).
