### ISSUE TITLE
Place contact should be a child of the place

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1710]
1. Go to Contacts
2. Click on Add New Place
3. Select the Health Center type
4. Fill in the required details and select "New person" as the contact
5. Click next and fill in the contact details
6. Click submit

#### Expected

The newly created person should be a child of the newly created place. This is important because the contact will probably be used as the associated contact for a user. This user will probably be "restricted to" the new place, which means they can't see anything outside of that tree, which means they can't see themselves. This causes bugs like #1654

**Comment by alxndrsn** [comment]
@garethbowen is this still a conern?

**Comment by garethbowen** [comment]
Yes definitely. This breaks the contact hierarchy.

**Comment by garethbowen** [comment]
This has been reported 3 times now so I'm scheduling it for this milestone. It's obviously something that gets hit a lot.

**Comment by sglangevin** [comment]
Working well in v2.8.0
