### ISSUE TITLE
Pouch may be making unsupported requests (`/medic/_bulk_get`)

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1711]
<img width="1280" alt="screen shot 2015-11-30 at 11 06 19" src="https://cloud.githubusercontent.com/assets/191496/11466516/7650e974-9752-11e5-93b5-adb8f6524b55.png">

**Comment by browndav** [comment]
I read through the PouchDB code a while back; it does this as part of API feature detection – there's an extended API in non-stock CouchDB versions (like Couchbase), and PouchDB tries to detect this and use it if it's available. If it's not, it falls back to looking at `_changes` IIRC.

It would be really nice if it were possible to pass hints to PouchDB on instantiation and avoid the runtime feature detection altogether.

**Comment by alxndrsn** [comment]
That solves that one, then.  @browndav please file upstream if you think it's worthwhile.
