### ISSUE TITLE
Define `cannot_*` permissions in app_settings

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1712]
Seem to be missing definitions in app_settings for:

* `cannot_edit_user_settings`
* `cannot_logout`

Please add.

**Comment by mandric** [comment]
Pretty sure we decided this was unnecessary and probably a bad idea to complicate permissions.

**Comment by alxndrsn** [comment]
Yep, we're using `can_logout` and `can_edit_profile`.

**Comment by mandric** [comment]
Also pretty sure `can_logout` is a bad idea.  It's better put into a setting.  Outlined a bit in this old PR. https://github.com/medic/medic-webapp/pull/1785/files
