### ISSUE TITLE
Figure out what regressed, if anything: Training users can see `Messages`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1713]
Logged in as `training32` on `lg.app`, I can see the _Messages_ menu item in the hamburg hotdog (top-right).

**Comment by browndav** [comment]
Not a priority issue for the field test IMO: consider instructing CHPs to simply avoid using this section.

**Comment by alxndrsn** [comment]
@abbyad can you take a quick look at this?  I suspect it's just a mis-configured `app_settings`.

**Comment by alxndrsn** [comment]
N.B. This does not currently occur on `lg.dev`, which is running `2432`.  Either a regression in `app_settings` or code.

![screenshot_2015-12-01-17-04-26](https://cloud.githubusercontent.com/assets/191496/11503100/b9e4a1be-984f-11e5-879a-fdb0408f8e3c.png)

**Comment by mandric** [comment]
Alex, please have one more look at this and re-assign to me if you don't have time.

**Comment by alxndrsn** [comment]
Please consider this as resolved for the LG trial - I have reverted previous commits, and added `can_` permissions for `can_logout` and `can_edit_profile` instead of the `cannot_*` permissions.

**Comment by mandric** [comment]
Sure a fix is in the PR.  Please close or delete the PR if it is of no use to you.

**Comment by abbyad** [comment]
Haven't seen this issue occur again, moving to Ready.
