### ISSUE TITLE
Everyone should be able to change their password

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1715]
At the moment the user settings can be hidden from users based on permissions. This poses a security risk as they can't change their password from the known one.  Find a way to show the user settings form and make it simple enough for anyone to use safely.

**Comment by browndav** [comment]
I agree 100%. We'll need to allow this in production, so IMO it makes sense to enable it during the field test to observe if any widespread problems arise. From a security and compliance perspective, IMO, it's important that we not retain usable passwords.

@diannakane: Curious what you think of this from a longer-term service design perspective. What would be an ideal way for CHPs to authenticate?

**Comment by SCdF** [comment]
@garethbowen how are you feeling about this? I want to close this simply because we're getting along fine without it. @browndav how are you feeling about this, re: security and compliance?

**Comment by garethbowen** [comment]
I still feel strongly that it should be allowed. It'd be really good to follow up with @diannakane to see if there's a good way to design it so it isn't hit by accident.

> we're getting along fine without it

@SCdF While that's true, as with all security issues you get along fine until you really really don't.

**Comment by SCdF** [comment]
> While that's true, as with all security issues you get along fine until you really really don't.

I was referring more to the general guidelines for closing old issues.

**Comment by diannakane** [comment]
I am not sure if it meets our urgent triage list at the moment. @sglangevin any thoughts? We have some preliminary work done on this which I can refer to should we choose to prioritize it. As an aside, we should add "ability to change password" to our permissions list.

**Comment by sglangevin** [comment]
I'd rather wait and do all of the permissions work together, but if someone feels strongly about adding this now, let's discuss on the call tomorrow.

**Comment by alxndrsn** [comment]
@garethbowen 

> I still feel strongly that it should be allowed.

What threat are we trying to mitigate with this feature?

**Comment by garethbowen** [comment]
It encourages sharing passwords insecurely, for example, if your session expires IT will have to send you the password (by SMS I assume?). We should allow users to change their password and implement a reset password routine so only the user knows the password.

**Comment by alxndrsn** [comment]
Discussion moved to https://github.com/medic/medic-projects/issues/1557

**Comment by SCdF** [comment]
The fate of this ticket should resolved in an upcoming discussion early next week.

**Comment by SCdF** [comment]
@garethbowen so should we close this ticket now? Presuming it will be dealt with in other security-related tickets?

**Comment by garethbowen** [comment]
Good call. Closing.
