### ISSUE TITLE
Problems with forms after exiting mid-form

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1716]
Right now, exiting a partially-completed form causes previously-entered data to show and changes how the questions and screens are organized. I'm currently testing this as demo on lg.app in chrome on my laptop. Steps to reproduce:

- Start filling out a form
- Click the X and continue to exit the form
- Open the same form (for the same person, or even for a different person) and see answers are already entered

Note: I have the same issue with forms accessed via actions on a person's profile, as well as forms accessed through the main task list. If I start filling a form from the task list, exit, hit refresh in the browser, and then re-open the form via the task, the form is blank and looks alright.

Here are two examples of the pre-filled data and form distortions caused by this:

![results showing](https://cloud.githubusercontent.com/assets/377216/11494193/637dd33a-9800-11e5-9d0e-b3e07bb6fa97.png)

![screen shot 2015-11-30 at 8 10 10 pm](https://cloud.githubusercontent.com/assets/377216/11494194/66b6ed98-9800-11e5-97f2-f989e9d38c98.png)

**Comment by alxndrsn** [comment]
Should be deployed now - check for version number `2448`
