### ISSUE TITLE
allow disabling of tour during user creation

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1720]
might be useful to make the tour optional during user creation.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by browndav** [comment]
Closing and marking as ancient. Create a new issue if this or a similar feature/fix is needed.
