### ISSUE TITLE
show information about the local pouch db in about page

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1723]
Show data from http://pouchdb.com/api.html#database_information
 
Related https://github.com/medic/medic-webapp/issues/1647

**Comment by mandric** [comment]
![screen shot 2015-12-02 at 12 38 39 am](https://cloud.githubusercontent.com/assets/25641/11520706/1341ec7a-988d-11e5-807b-b204a4e316fb.png)

**Comment by mandric** [comment]
Wondering if we might need to also make sure auto_compaction is on...

**Comment by alxndrsn** [comment]
Interesting question.  Looks like you're logged in as admin though, so worth seeing if settings are different logged in as a regular user.

If this is meant to be marked `Code Review`, then consider it now marked `Acceptance Testing`.

**Comment by alxndrsn** [comment]
`auto_compaction` is set `true` on pouch.

**Comment by alxndrsn** [comment]
This looks good - marking as `Ready`.  @mandric please move back if there was a reason it was still `Active Work` before.
