### ISSUE TITLE
Verify that location is being saved

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1724]
Placeholder for now

**Comment by alxndrsn** [comment]
Does this need to be checked for each type of form?

**Comment by abbyad** [comment]
Yes, it should be check for each form and family creation as well.

**Comment by alxndrsn** [comment]
# FORMS CHECKED & WORKING:
- [x] assessment / _Assess Patient_
- [ ] _Assessment Follow-Up_
- [ ] _Family Survey_
- [ ] _Newborn Visit_
- [ ] _New Pregnancy_
- [ ] _Pregnancy Referral Follow-Up_

**Comment by abbyad** [comment]
I added Family and Person creation to the list.

**Comment by alxndrsn** [comment]
Do those appear in the _History_ tab?

**Comment by abbyad** [comment]
No, but the documents can be viewed in the db.

**Comment by alxndrsn** [comment]
Blocked by #1731

**Comment by abbyad** [comment]
This is no longer blocked now that #1731 is resolved.

**Comment by alxndrsn** [comment]
@abbyad `geolocation` and `inputs location` nodes not present in _Add Person_ form.

**Comment by abbyad** [comment]
Thanks for spotting that @alxndrsn. The `/data/inputs/meta/location` node is now included in the create person form.

**Comment by alxndrsn** [comment]
Newly-created Person on `lg.app` does not have `geolocation` property set:

<img width="1280" alt="screen shot 2015-12-17 at 12 39 09" src="https://cloud.githubusercontent.com/assets/191496/11868868/396e1678-a4bb-11e5-9a47-be99d2697c95.png">

**Comment by abbyad** [comment]
The person creation form had the geolocation in the data model, but it was missing as an output field. Should be good to go now on lg.dev.
