### ISSUE TITLE
Re-instate help pages

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1727]
Help pages were removed from the app in #1722.  They should be re-instated, and hidden by more valid means when that is required.

**Comment by alxndrsn** [comment]
These should be re-instated as individual docs in the db if #1700 is accepted

**Comment by browndav** [comment]
Moving this to the backlog for now as we didn't identify it as a priority for this iteration.

**Comment by garethbowen** [comment]
Duplicate of #1895
