### ISSUE TITLE
Pregnancy referral follow up tasks aren't clearing

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#1728]
Right now, pregnancy referral follow up tasks aren't clearing after they're completed (responses: in person, pregnant woman went to the facility, hit submit). I see confirmation that the form has been submitted. I tried refreshing and re-opening the browser, but it didn't help. I was trying as demo and as  CHP user on lg.app in chrome on my laptop.

Steps to recreate:

- Create a new family
- Add a pregnancy *with at least one danger sign* (not a risk factor)
- See the task is due in 1 day 
- Click on the task, complete and submit the form
- See that the task is still there, even after refresh or app restart

I can share a screenshot of my task list by PM if helpful.

**Comment by joshnesbit** [comment]
We could re-open this: https://github.com/medic/medic-webapp/issues/1562

**Comment by abbyad** [comment]
Thanks for reporting this Josh. Let's keep this as a separate issue since those in #1562 cleared when the page was refreshed, whereas in this case it doesn't. I will add this to the current iteration.

**Comment by abbyad** [comment]
This seems to be resolved with the update to the task rules. Assigning to @joshnesbit for acceptance testing.
