### ISSUE TITLE
Cannot Add Family Member

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1731]
Looks like the form definition is out of date:

* currently includes 2 separate name fields
* errors on submit

<img width="1234" alt="screen shot 2015-12-02 at 23 25 00" src="https://cloud.githubusercontent.com/assets/191496/11543416/890640a8-994d-11e5-9308-6afca6a49331.png">

**Comment by abbyad** [comment]
@alxndrsn I updated the form. Confirm when you can that this is fixed.

**Comment by abbyad** [comment]
This seems to be broken still... and likely related to the `<parent>PARENT</parent>` not working as it did last week.

**Comment by abbyad** [comment]
This is now working again in lg.app, moving to Ready.
