### ISSUE TITLE
New Pregnancy Form: EDD in Reports Tab post-submission is off by one day

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1732]
To reproduce, register a pregnancy for a new contact from the Pacific Standard Time time zone:

<img width="776" alt="screen shot 2015-12-02 at 12 27 29 pm" src="https://cloud.githubusercontent.com/assets/763977/11543337/e0c235f2-98f0-11e5-951f-187868d493ad.png">

Next, click over to the `Reports` / `History` tab, and observe that the date being displayed does not match what you entered:

<img width="236" alt="screen shot 2015-12-02 at 12 27 58 pm" src="https://cloud.githubusercontent.com/assets/763977/11543371/0d223e9e-98f1-11e5-97e4-8969c3647680.png">

Investigate whether data is being stored incorrectly, or just being displayed incorrectly. I suspect this may be a time zone issue; if so, think critically about how we store dates, and eliminate this entire class of problems in some way.

Likely not achievable for the field test.

**Comment by btbonval** [comment]
Looks like entries by me, Sharon, and Dave are all showing -1 day from what we entered, while Josh's are showing up as the exact day entered.

**Comment by alxndrsn** [comment]
@btbonval josh is in GMT+2; you lot are all GMT-7 or so.

**Comment by btbonval** [comment]
GMT-4 for me but yea. Is the server set to GMT?

**Comment by alxndrsn** [comment]
You'd have to hope so.

**Comment by browndav** [comment]
The server is UTC: ```
$ date -R
Wed, 02 Dec 2015 22:44:37 +0000
```

**Comment by btbonval** [comment]
I might be GMT-5? stupid daylight savings.

**Comment by alxndrsn** [comment]
Looking at these reports, I'd expect anyone on GMT or GMT+ to get the correct date, and anyone on GMT- to get the day wrong by one.  Would be great if you all having problems could switch your timezone to Kampala/Nairobi/East Africa Time and see if that clears things up for now.

**Comment by btbonval** [comment]
further confirmation: estelle's entries have the correct date.

**Comment by alxndrsn** [comment]
@btbonval would also be instructive if the computer you are checking this data on has the relevant timezone set (i.e. GMT+3).

**Comment by btbonval** [comment]
yes, that would help.

I am current at GMT-4/5 (who knows). When I view entries made by people in GMT+?, the dates are exact as shown in our ground truth sheet. When I view entries made by people in GMT-?, the dates are one day early (Aug 7 instead of Aug 8).

Now we need someone who is GMT+? to see if the dates line up. I'd pull a random sampling but I'm concerned about putting names or anything here. We do have a ground truth sheet to check against with names though.

**Comment by alxndrsn** [comment]
Can't you just change your time settings?

**Comment by browndav** [comment]
Yeah, you definitely can.

**Comment by btbonval** [comment]
oh. if I were using Linux I would do that. I'm on Windows right now. Windows is scary and unpredictable I don't like to make changes that might cause my system to BSoD. I can do that from another computer later though.

**Comment by btbonval** [comment]
okay on my linux laptop. set myself to Kampala time (which appears to cover Kenya as well). signed in.

a dave entry is 1 day early.
a josh entry is the correct day.
a bryan entry is 1 day early.
a shreya entry is correct day.

so when I've set my compy to GMT+?, it looks like nothing has changed: entries entered by folks in GMT+? are good and entries by folks in GMT-? are a day early.

**Comment by alxndrsn** [comment]
Thanks @btbonval - very helpful report.

**Comment by alxndrsn** [comment]
Fixed by https://github.com/alxndrsn/openrosa-xpath-evaluator/commit/ca3f6d4bea1051df816b4959288f1bae43545506 ?
