### ISSUE TITLE
re-add help text

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1733]
In Issue https://github.com/medic/medic-webapp/issues/1722 we removed the help pages.  We need to revert that commit and file a feature request to support smaller builds/ddocs for faster replication and mobile device initialization.

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1700

**Comment by alxndrsn** [comment]
#1700 is the feature request to include help pages in a more bandwidth-friendly way.

**Comment by alxndrsn** [comment]
If help docs are re-added, this should not be done in a way which affects the LG trial.

**Comment by alxndrsn** [comment]
Duplicate of #1727
