### ISSUE TITLE
Incomplete profile after edit

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1735]
Sometimes after editing a person the profile only shows some of the details. This is an example missing the Family name and Action forms.
![screen shot 2015-12-02 at 19 44 11](https://cloud.githubusercontent.com/assets/789512/11548888/fd2d5602-992e-11e5-9e69-c7fa245aa236.png)

Other times the complete profile is shown:
![screen shot 2015-12-02 at 19 49 37](https://cloud.githubusercontent.com/assets/789512/11548887/fd2cf626-992e-11e5-95b1-7b355d98f757.png)

**Comment by alxndrsn** [comment]
Odd, but hard to recreate.  Any chance you can get a console output next time this happens?

**Comment by sglangevin** [comment]
Have we seen this again? If not, we should close this issue and re-open if it recurs. cc @abbyad

**Comment by sglangevin** [comment]
Closing. Re-open if it can be reproduced.
