### ISSUE TITLE
Edited text field shows `: text` in profile

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1736]
The field type is shown in the profile page after editing the person.

For example, this notes field:
![image](https://cloud.githubusercontent.com/assets/789512/11548940/9b3a0e80-992f-11e5-9261-cae8d1781ad2.png)

is shown with `: text` after editing the person:
![screen shot 2015-12-02 at 19 49 37](https://cloud.githubusercontent.com/assets/789512/11548929/80376e70-992f-11e5-8002-5f686a4efcca.png)

**Comment by alxndrsn** [comment]
Weird!  Haven't see this happen when editing Person and Family names.

**Comment by alxndrsn** [comment]
Cannot recreate this locally or on dev or app servers.  Please re-open if it's still an issue.
