### ISSUE TITLE
associating LG contacts/facilities with their CHPs

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1741]
This problem was described in another ticket:
https://github.com/medic/medic-webapp/issues/1604#issuecomment-158592067

Summary: when using LG facility view, it looks like the `.parent` is not being exported so that we cannot see what CHP is associated with any family or person. There might be some other fields that do not get exported.

**Comment by btbonval** [comment]
@abbyad

**Comment by btbonval** [comment]
Actually I think the contacts export might have worked, but I couldn't parse it without writing a new parser from scratch for the middleware. It might be faster than fixing this particular issue. I'll have to look into what that would take.

**Comment by browndav** [comment]
Issue janitor post: Is there an action required here?

**Comment by btbonval** [comment]
@abbyad asked me to post it. Marc can you follow up?

**Comment by browndav** [comment]
Are there additional items in this ticket beyond those in #1604 (now closed)? Just trying to figure out if there are actionable items left here.

**Comment by btbonval** [comment]
I NEED AN ADULT!

Seriously though, I was on phone with Marc and this was a tangent and he couldn't write tickets at the time for some reason. I wrote the words as dictation but I really don't know what they mean. Marc will need to take a look.

**Comment by btbonval** [comment]
Based on conversation with @abbyad, it sounds like we can't really recall the reason for this ticket to remain open outside of supporting the LG trial. So if the underlying reason for this issue comes up again, we can probably file it into medic-projects.
