### ISSUE TITLE
when `require_valid_user` couchdb config is false medic-api login redirects infinitely

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1742]

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Can't reproduce it. Closing.
