### ISSUE TITLE
create/add person support

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1745]
People ("type":"person" docs) will typically be automatically created when creating a people user type but it might be useful to have a separate function similar to "Add Place" that can create people and link them to user accounts.

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1709

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
@mandric We have an Add Person button in the FAB which adds a person to the selected area:

![add-person](https://user-images.githubusercontent.com/2064938/27617413-43e6e65e-5c0a-11e7-8a88-e649908d7bb3.png)

It doesn't update the user but you can go and edit the user and then select this person as the contact.

Is this what you meant? Can we close this?
