### ISSUE TITLE
Tighten up enketo prepopulation tests

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1746]
Tests in `tests/karma/unit/services/enketo-prepopulation-data.js` could have more specific URL selecters for where they expect to find `inputs` data, e.g.:

```js
chai.expect(xml.find('data person last_name')[0].innerHTML).to.equal(data.person.last_name);
```
cold actually become:
```js
chai.expect(xml.find('data > person > last_name')[0].innerHTML).to.equal(data.person.last_name);
```

This should make the tests more reliable, and clearer in where they are putting data.  We've had a few regressions in this area, so feels worthwhile.

**Comment by alxndrsn** [comment]
Hopefully this change will make it more obvious when something breaks with form prepop - we had some regressions there during the last month.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by mandric** [comment]
Nice.
