### ISSUE TITLE
Date fields show "months" option even when "specific date" option is chosen

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1747]

**Comment by abbyad** [comment]
@fredatthehub or @alxndrsn, can you provide a screenshot because I cannot reproduce this or see where this would occur. If you can't get a screenshot it would be helpful to know which form this is, and if it is on create or edit.

**Comment by alxndrsn** [comment]
Almost certainly something to do with the `refresh` button code.

<img width="391" alt="screen shot 2015-12-08 at 14 36 26" src="https://cloud.githubusercontent.com/assets/191496/11654768/1e90e74e-9db9-11e5-9a57-ad7bbc7e7dde.png">

**Comment by abbyad** [comment]
Perfect, thanks @alxndrsn. This is due to a missing `relevant` rather than the refresh button.
