### ISSUE TITLE
on first load contacts does not render all i18n strings

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1748]
(experienced on lg.app)

Navigate to any contact then hit refresh (to simulate navigating from a direct link) and you will see the i18n key rather than translated string. 
![screen shot 2015-12-07 at 2 28 11 pm](https://cloud.githubusercontent.com/assets/25641/11632695/43afebee-9cef-11e5-9aab-977b1a0fe08a.png)

**Comment by garethbowen** [comment]
I can't get this to happen any more. Sending for acceptance testing.
