### ISSUE TITLE
Cannot export Xform reports from Report tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1749]
In the Reports tab we get a `414 Request-URI Too Large` when clicking Export after selecting a large number of items from the place filter.

If a smaller number are select an export file is downloaded, but it only contains report that have a JSON representation.

**Comment by mandric** [comment]
We could add POST support to this query.

**Comment by abbyad** [comment]
Ok, I am moving this to Scheduled then since it has low chance of regression, but let me know if I am wrong about that.

**Comment by abbyad** [comment]
On second thought, this is not as pressing because even a "successful" export only has the headers, not the XForm field data - which may be related to #1604.

**Comment by alxndrsn** [comment]
@abbyad can you clarify if this ticket is a priority for working on?

**Comment by abbyad** [comment]
Yes @alxndrsn, this is a priority issue as we cannot export data using the "export" button in lg.dev.

**Comment by garethbowen** [comment]
I've modified the code to use POST so this won't error out, however it still only returns the headers of the xforms reports. Open a different issue to return the full data.

**Comment by estellecomment** [comment]
Code looks good. I looked up that strange invisible download link, that was interesting. Looking it up I found `Content-disposition: attachment`, thoughts about that?

Moving on to Acceptance Testing.
