### ISSUE TITLE
Multiple Search calls in parallel do not all complete

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1752]
On phone, when firing multiple `Search` service queries, only the first one of them is completing.  Others do not trigger the callback method **_AT ALL_** - neither with the result nor with an error!

# Configuration

item | val
---|---
webapp | `0.6.0-beta.2468`
android | `0.1.117`
domain | `lg.app`
user | `muk031`
connectivity | none

# Helpful screenshots

N.B. `D` is an `object`, populated with de-obfuscated variables to make the debug code more easily understood.

<img width="1280" alt="screen shot 2015-12-08 at 10 14 37" src="https://cloud.githubusercontent.com/assets/191496/11649966/a563fa1e-9d95-11e5-9db1-ec942f6023b8.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 16 16" src="https://cloud.githubusercontent.com/assets/191496/11649964/a561d1a8-9d95-11e5-81e2-351e0aa00695.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 16 54" src="https://cloud.githubusercontent.com/assets/191496/11649967/a566aade-9d95-11e5-8ed2-060027ef4568.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 17 26" src="https://cloud.githubusercontent.com/assets/191496/11649965/a563547e-9d95-11e5-9b1d-88b0aa9e8605.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 19 31" src="https://cloud.githubusercontent.com/assets/191496/11649968/a5698cfe-9d95-11e5-9126-4a9b98b2e540.png">

-----

Possibly related: #1751

**Comment by alxndrsn** [comment]
Looks like only the **_final_** call to `Search` will complete:

<img width="1280" alt="screen shot 2015-12-08 at 10 29 39" src="https://cloud.githubusercontent.com/assets/191496/11650083/c1e61dec-9d96-11e5-9c5d-4fb6c70d5f15.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 29 48" src="https://cloud.githubusercontent.com/assets/191496/11650084/c1e7426c-9d96-11e5-9070-46a46c6127c8.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 29 58" src="https://cloud.githubusercontent.com/assets/191496/11650082/c1e59912-9d96-11e5-838a-37d0bb58e68b.png">
<img width="1280" alt="screen shot 2015-12-08 at 10 30 11" src="https://cloud.githubusercontent.com/assets/191496/11650085/c1e7543c-9d96-11e5-9c04-b4329d431a64.png">

**Comment by alxndrsn** [comment]
Looks like only the **_first_** concurrent call to `Search` will complete.

# Concurrent calls

<img width="1280" alt="screen shot 2015-12-08 at 10 35 10" src="https://cloud.githubusercontent.com/assets/191496/11650141/70fb2fc0-9d97-11e5-81a4-9a073f5564c8.png">

# Sequential calls

<img width="1280" alt="screen shot 2015-12-08 at 10 34 40" src="https://cloud.githubusercontent.com/assets/191496/11650146/7496bc44-9d97-11e5-8908-d7bb711d5868.png">

**Comment by alxndrsn** [comment]
This behaviour is likely intentionally caused by `Search` service's `debounce` function.

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by alxndrsn** [comment]
Comment added.

**Comment by mandric** [comment]
Assigning parent ticket #1751 for acceptance testing.
