### ISSUE TITLE
App becomes completely unresponsive when phone runs out of data-credit

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1754]
When credit runs out on MTN Uganda, `http` calls are redirected to http://www.redirect.mtn.co.ug/mtnredirect/mtn-redirect.html.  `https` calls are left to timeout:

<img width="1280" alt="screen shot 2015-12-08 at 12 33 08" src="https://cloud.githubusercontent.com/assets/191496/11652288/e6c45b54-9da7-11e5-996b-185405e730df.png">

When this happens, the android app becomes very slow to respond:
* tasks never load
* contacts never load
* tabs can be changed, but it takes a long time

After restarting the app, it becomes responsive and data is loaded.  Timeouts now seem to be much quicker:

<img width="1280" alt="screen shot 2015-12-08 at 12 37 49" src="https://cloud.githubusercontent.com/assets/191496/11652387/892f8ec2-9da8-11e5-9fd2-06cfcce2fe41.png">

The shorter timeouts _may_ correspond to my visiting http://www.redirect.mtn.co.ug/mtnredirect/mtn-redirect.html on the handset, as I did this before restarting the app.

**Comment by SCdF** [comment]
Hey @alxndrsn,

1) Do we care about redirecting HTTP? Are all our resources HTTPS?
2) Do you have any more data than these screenshots?

I used [Charles](|https://www.charlesproxy.com) to proxy the connections over a connection that never completes. With Charles set to effectively time out (very high round-trip latency) I couldn't reproduce the app running slowly. Note that it's on a Nexus5 and so it could be handset related. It could also be related to exactly what is happening with the HTTPS timeouts, i.e. where and how they fail.

(FYI Charles costs money to use for more than 30 minutes at a time or for longer than 30 days. Not sure if there is a free alternative)

**Comment by SCdF** [comment]
FYI I used this guide to setup Charles, not that there is much to it: http://tech.taskrabbit.com/blog/2015/07/02/android-simulating-network-speed-and-response-codes/

**Comment by alxndrsn** [comment]
> 1) Do we care about redirecting HTTP? Are all our resources HTTPS?

HTTP is only used locally in dev - otherwise all access to the app should be over HTTPS.


> 2) Do you have any more data than these screenshots?

No.  What data might be helpful to collect next time?

**Comment by SCdF** [comment]
> No. What data might be helpful to collect next time?

I'm not sure exactly. One thing that might be useful would be right clicking a failing request and getting the curl-able command, and then using that with `-v` for verbosity. Mostly because I'm wondering if requests can pause at different points in the flow, and those different points cause different styles of issues. Also, if useful, the line of (Medic) code which is waiting for a request, though maybe that's obvious from the URL?

**Comment by alxndrsn** [comment]
> the line of (Medic) code which is waiting for a request, though maybe that's obvious from the URL?

This should be fairly obvious from the URL.  It looks like a `PouchDB.info()` call, but I can't say where that happens off the top of my head.  It may not even be explicit, but part of e.g. `replicate()`.

**Comment by alxndrsn** [comment]
> I'm not sure exactly. One thing that might be useful would be right clicking a failing request and getting the curl-able command, and then using that with -v for verbosity.

This could be interesting, but it's probably important to perform the curl over the same connection as the app is using.  Likely this would require tethering to the out-of-credit phone.

Also will require some care to recreate, as behaviour seems to be different depending if the request starts before the phone runs out of credit or afterwards.

**Comment by SCdF** [comment]
Worth looking at whether or not having requests redirect somewhere: i.e., simulating running out of bandwidth and being redirected to a "top up your data page".

**Comment by estellecomment** [comment]
Can't reproduce this. The requests fail when you run out of data, but Couch doesn't panic and triggers `onPause`, retries happen, and if you get back on network the replication finishes. During all that the app is not slower than its usual slowness.

This is on lg-testing, all requests are https. From trying it out in a browser, http get redirected to mtn page, https not.

So I think we're good.
