### ISSUE TITLE
Message for children over 12years referral 

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1758]
Message for children over 12years referral is appearing in all assessment summaries - should be removed.

![image](https://cloud.githubusercontent.com/assets/15346836/11776359/88b5ccd2-a257-11e5-9612-04a2ce464aae.png)

**Comment by abbyad** [comment]
This should be fixed with other changes in https://github.com/medic/medic-projects/commit/7bb212e2281b635dbed17a5cc22869b370157a7a

**Comment by abbyad** [comment]
@fredatthehub this can be tested on lg.dev.
