### ISSUE TITLE
Referral message should be exact

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1760]
Referral message should be exact as the danger signs noted e.g. Diarrhoea with Blood - See screen shot – The patient had blood in the diarrhoea, this should be show in the referral message.

![image](https://cloud.githubusercontent.com/assets/15346836/11776423/ffee59ea-a257-11e5-9281-17f2b0f16c04.png)

**Comment by abbyad** [comment]
I have updated this for Cough, Diarrhoea and Fever, but not Pneumonia since it is a combination of symptoms.

**Comment by abbyad** [comment]
@fredatthehub this can be acceptance tested on lg.dev.
