### ISSUE TITLE
Letters are ignored in phone validation

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1762]
Reproduce : edit contact or create new. Set phone number to valid format, then add letters after or between numbers. Save.

![screen shot 2015-12-14 at 15 35 15](https://cloud.githubusercontent.com/assets/911434/11783576/4eede1a8-a278-11e5-86d7-add108a0aeba.png)

**Comment by mandric** [comment]
@estellecomment , when coding is done on an issue you can bump the tag  to 3 - code review and reassign to someone.

**Comment by mandric** [comment]
Moving to acceptance testing and adding a note here for @garethbowen  to have a look since he was original author of this lib.
