### ISSUE TITLE
Build user creation API for medic-api

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1764]
As a new developer or project manager we need to create users and people easily to bootstrap/configure an installation.

Also need a way to quickly bulk load reports and messages.  So currently in [medic-data repo](https://github.com/medic/medic-data) we support 0.4 formats.  We should add support for 0.6 style contacts, people and forms.  We need reproducible steps or code to create a 0.6 demo instance.

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1709

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1555

**Comment by browndav** [comment]
Clarification: we need a single-step REST-based API that creates a user, creates a `UserSettings` document, and creates contacts/households/people as necessary. We should then convert the user management interface to use this new API. It's also possible that `concierge` could use this API to simplify its user creation logic.

**Comment by alxndrsn** [comment]
For now, you can also create users with the script at https://github.com/medic/medic-webapp/blob/develop/scripts/create_user
