### ISSUE TITLE
[enketo] XPath calculations are affected by XML node ordering

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1765]
This may be normal, but seems odd for XML. We should find out the circumstances in which the ordering matters because otherwise XPath calculations can give unexpected results.

**Comment by alxndrsn** [comment]
@abbyad please provide an example form where calculations occur in surprising ways, making clear what data will trigger strange calculations and what the expected result would be.

**Comment by abbyad** [comment]
Here is a file that presents odd behaviour: [test_order.xml](https://files.zenhub.io/56736786ff54ff8d331516a5)

From this test it seems as though using a further node that has a calculated or default value will be accurate in a simple assignment, but will have a value of `0` if used in a calculation.


# On first load:
![image](https://cloud.githubusercontent.com/assets/789512/11887249/56181806-a500-11e5-9f14-6235f70d4798.png)

# After changing the input:
![image](https://cloud.githubusercontent.com/assets/789512/11887263/763ede58-a500-11e5-807f-ec0d67d5fe41.png)

**Comment by alxndrsn** [comment]
@abbyad moving this into the iteration - anything causing forms to miscalculate is quite serious IMO!

**Comment by alxndrsn** [comment]
Perhaps more revealingly:

# First Load

<img width="178" alt="screen shot 2015-12-18 at 11 00 18" src="https://cloud.githubusercontent.com/assets/191496/11894304/9f8e4d5e-a576-11e5-9843-518621fcbd8a.png">

# Value Changed, then changed back

<img width="174" alt="screen shot 2015-12-18 at 11 00 27" src="https://cloud.githubusercontent.com/assets/191496/11894303/9f7b97d6-a576-11e5-8fd1-fa9054f7235e.png">

**Comment by alxndrsn** [comment]
# Scenario 1: Going Down

## 1

<img width="340" alt="screen shot 2015-12-18 at 11 20 31" src="https://cloud.githubusercontent.com/assets/191496/11894736/74ef2c3c-a579-11e5-9519-76125d9f9e1a.png">

## 2

<img width="340" alt="screen shot 2015-12-18 at 11 20 44" src="https://cloud.githubusercontent.com/assets/191496/11894734/74ba5548-a579-11e5-992f-de25f584bd67.png">

## 3

<img width="338" alt="screen shot 2015-12-18 at 11 20 51" src="https://cloud.githubusercontent.com/assets/191496/11894735/74cd5a80-a579-11e5-8ed3-59657842beef.png">


# Scenario 2: Going Up

## 1

<img width="337" alt="screen shot 2015-12-18 at 11 23 19" src="https://cloud.githubusercontent.com/assets/191496/11894788/d87b36f6-a579-11e5-8ed6-3883043fbd4c.png">

## 2

<img width="333" alt="screen shot 2015-12-18 at 11 23 26" src="https://cloud.githubusercontent.com/assets/191496/11894789/d89165d4-a579-11e5-95e7-e7b3b71886a2.png">

## 3

<img width="334" alt="screen shot 2015-12-18 at 11 23 31" src="https://cloud.githubusercontent.com/assets/191496/11894790/d8afbb10-a579-11e5-817e-c60588951737.png">

**Comment by alxndrsn** [comment]
Filed upstream at https://github.com/enketo/enketo-core/issues/352

**Comment by alxndrsn** [comment]
Code review at https://github.com/enketo/enketo-core/issues/352 :)

**Comment by abbyad** [comment]
Tested on 2710 and works as expected. Moving to Ready.
