### ISSUE TITLE
Labels "Clinic" vs. "Catchment area" vs. "Family" not standardized

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1768]
From a Health Center page, there is list of "Clinics". To add one, you click "Add Place" and get to a page for creating a "Catchment Area". 

We should use either clinic or catchment, not both.

![screen shot 2015-12-16 at 14 30 48](https://cloud.githubusercontent.com/assets/911434/11842180/3c20165a-a402-11e5-81b9-c43af882d8ee.png)
![screen shot 2015-12-16 at 14 31 00](https://cloud.githubusercontent.com/assets/911434/11842179/3c1d6f40-a402-11e5-83d8-cb62f0854476.png)

**Comment by estellecomment** [comment]
"Family" is also used interchangeably. Updating the Issue's name.
![screen shot 2015-12-17 at 11 15 14](https://cloud.githubusercontent.com/assets/911434/11867357/e79974b4-a4b0-11e5-88ab-a85d72243061.png)

**Comment by abbyad** [comment]
Assigned to @sglangevin to check for consistency in currently deployed app_settings.

**Comment by abbyad** [comment]
@estellecomment, I am closing this as it seems to be superseded by the new People tab work.
