### ISSUE TITLE
Hard to understand what "default language" is (confusing UX)

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1769]
When I change the default language, it doesn't change the language of my UI. I expected it would, because I didn't understand what "default language" is.

Solution : 
Add an short help text like "New users that you create will get the default language. To change the language of an existing user, go to [wherever]".

**Comment by alxndrsn** [comment]
@abbyad removing scheduled, as this issue has no milestone.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment]
AFAICT this dialog would only be seen by tech leads.  They should understand what it means.
