### ISSUE TITLE
Forms save unformatted phone numbers

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1770]
phone-widget.js will check if a number is valid and block submission if not (that's good), but it will not format the number to international format before saving. 
So we are saving '06 77 88 99 00' for instance, as opposed to '+33677889900'.
Which means if the default country code is changed, numbers are messed up.

UX note: within a given country, seeing '06 77 88 99 00' is much more human-readable. If all your project is in France, you don't want to see '+33677889900' everywhere. So we should add a display format.

**Comment by mandric** [comment]
Makes sense to me.  Validate and format all phone numbers before saving, and then have a setting with a nice default for displaying them.

**Comment by mandric** [comment]
Thanks @estellecomment, looks great, nothing major just a few comments in the PR.

**Comment by abbyad** [comment]
It saves properly in international format, so will move to Ready.

There is a side effect of this which was alluded to in the original comment - we should have a display format as well. In the field-test, there is a confirmation page displaying the phone number to make sure it has been entered correctly. When a user enters the phone number without the country code, they then see it with the country code in the confirmation page. They may be confused to confirm a different looking number than the one they typed out ...however, this could be considered a feature :)

**Comment by estellecomment** [comment]
Agreed. Filed #1930 for that. Less urgent obviously, but still nice to have.
