### ISSUE TITLE
Clear button difficult to use on mobile

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1771]
We have had a lot of feedback that the clear-search-button is difficult to use on mobile. We should make it as big as the search button and avoid the overlap between the two.

![image](https://cloud.githubusercontent.com/assets/789512/11853883/88ac5b4e-a40e-11e5-9dea-270cb054d873.png)

If we do an update to field-test instance we should include this with it.

**Comment by mandric** [comment]
Any chance we can get a screen shot here while you have it handy?

**Comment by alxndrsn** [comment]
<img width="453" alt="screen shot 2015-12-17 at 15 32 27" src="https://cloud.githubusercontent.com/assets/191496/11872008/63a8a67a-a4d3-11e5-944a-8ff6080032c1.png">

**Comment by abbyad** [comment]
Assigning to @diannakane and design team for acceptance testing.

**Comment by diannakane** [comment]
Clickable surface area works well. Icon size could be larger, but we will revisit this with other updates.

Approved acceptance testing @abbyad
