### ISSUE TITLE
Breadcrumbs are "backwards"

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1773]
Breadcrumbs are commonly "Big > Medium > Small". 
We use "Small > Medium > Big".

![screen shot 2015-12-17 at 11 11 57](https://cloud.githubusercontent.com/assets/911434/11867421/3aa16626-a4b1-11e5-9fd4-f5b3db91f546.png)

**Comment by alxndrsn** [comment]
I think in this instance _small < medium < big_ is more useful, as the most relevant is usually the most local, and for me is the common form for addresses.  I think a more concrete screenshot would demonstrate this, e.g.

**Fester Addams**
_Addams Family_ > _Westfield Health Center_ > _New Jersey_

vs.

**Fester Addams**
_New Jersey_ > _Westfield Health Center_ > _Addams Family_

**Comment by abbyad** [comment]
I think we originally had them as traditional breadcrumbs but swapped the order because the "Small" was most relevant but often got hidden when it overflowed. Looking at it now maybe we just need to change the delimiter to avoid confusion.

**Comment by estellecomment** [comment]
Thanks for the explanations! I was wondering if it was an accident, but I see it's not at all.

Flipping the delimiters then, yes : 
Small < Medium < Big
Addams Family < Westfield Health Center < New Jersey

**Comment by alxndrsn** [comment]
We could also use a different delimter, e.g.:
_Addams Family, Westfield Health Center, New Jersey_
_Addams Family • Westfield Health Center • New Jersey_
