### ISSUE TITLE
Schedules page is in default language

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1774]
Default language for the app is french. Admin user's language is English. Schedules page should be in English like other pages, but it's in French.

![screen shot 2015-12-17 at 11 33 23](https://cloud.githubusercontent.com/assets/911434/11867554/2429c22a-a4b2-11e5-9d93-bd60fb783d28.png)

**Comment by alxndrsn** [comment]
It looks like this page is templated by kanso instead of angular.  @mandric @garethbowen are these legacy pages that still need converting to angular?

**Comment by garethbowen** [comment]
Correct. Schedules is the last of the pages to convert to angular.

**Comment by garethbowen** [comment]
The Schedules page has been deleted in #1861
