### ISSUE TITLE
Missing menu options in Schedules page

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1775]
The Schedules page doesn't have a "Tasks" tab, and in the dropdown menu the "User settings" and "Icons" options are missing.
Also the "Users" (utilisateurs) option has the wrong icon, it's using the User Settings icon (single person instead of multiple people)

![screen shot 2015-12-17 at 11 38 22](https://cloud.githubusercontent.com/assets/911434/11867686/f00ec4d0-a4b2-11e5-91c3-856a729f900b.png)

**Comment by estellecomment** [comment]
Also missing menu options in Configuration page : the "User Settings" tile is missing.
The icon for "Users" is also wrong.

![screen shot 2015-12-17 at 11 58 27](https://cloud.githubusercontent.com/assets/911434/11868107/db3bb45c-a4b5-11e5-8f7c-18c8deda5a04.png)

**Comment by abbyad** [comment]
The lack of _Tasks_ tab is because the Schedules page is a relic that we plan on replacing - see conversation at https://github.com/medic/medic-webapp/issues/1362#issuecomment-145861874.

As for the _Users_ vs _User Settings_, we should open a separate issue for the cleanup.

**Comment by abbyad** [comment]
Closing in favour of the split off issues.
