### ISSUE TITLE
Profile data/bandwidth usage in mobile application

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1777]
Given the high costs of mobile data we should profile the data usage of the app then make improvements where needed to use as little as possible.

`performance` label added since this relates to resource usage.

**Comment by alxndrsn** [comment]
# MTN UG Bundle costs

http://www.mtn.co.ug/internet/Mobile%20Internet/Pages/Bundles.aspx

<img width="596" alt="screen shot 2015-12-17 at 17 13 32" src="https://cloud.githubusercontent.com/assets/191496/11874786/b2c786aa-a4e1-11e5-9949-cd4f57426689.png">

# TL;DR: 100MB ~= $1 (USD)

**Comment by SCdF** [comment]
So I've looked around a bit, and CouchDB doesn't seem to support any kind of HTTP compression (ie gzip). The only way we could add this AFAICT, bar adding the capability to Couch (I've always wanted to learn Erlang…) would be to put a server in the middle. You'd then have: Browser -> HTTPS+GZIP -> MedicCouch -> HTTP -> CouchDB, which CouchDB no longer being exposed over the internet.

**Comment by SCdF** [comment]
Talking to @alxndrsn we are already set up this way. It looks like we should just be enable compression in the PROD nginx deploys

**Comment by browndav** [comment]
We have deflate turned on IIRC, but only for a whitelist of file types currently: https://github.com/medic/medic-os/blob/dev/platform/packages/medic-core/settings/medic-core/nginx/nginx.conf#L36

**Comment by SCdF** [comment]
`Content-Type: application/json` is what I'm getting, which is not covered by the whitelist. Not sure if that means the whitelist is wrong or the content type is

**Comment by alxndrsn** [comment]
@SCdF that content-type is correct for JSON.  Not sure if there's a reason it's left out of the list.  We should enable it, and make sure to test it doesn't break the changes feed.

**Comment by browndav** [comment]
We've added #1828. @abbyad: Are there any other actions that need to be taken here IYO?

**Comment by abbyad** [comment]
The original goal of this issue was to find out how much data is being used and when/where that happens, so that we can then make decisions on how to reduce it.

I see that we'll gzip/deflate, but I don't see other information that can help to plan data usage reduction. How often is it polling, and how much data is used for that? If a replication fails midway does it retry from the beginning? We may not need to answer that immediately, but that would help us figure out how to reduce the amount of data being used.

**Comment by garethbowen** [comment]
We need to find out how much data is used by continuous replication even if there's nothing to replicate. If it's prohibitive we could only turn on automatic replication when on wifi.

**Comment by alxndrsn** [comment]
Or just not run it 24/7.

**Comment by SCdF** [comment]
Is the concern that it will request data and then close it after N minutes and then request it again? So that people will be charged over and over again for the start of the GET?

**Comment by garethbowen** [comment]
There shouldn't be a timeout but we do issue a heartbeat every 10 seconds to keep the connection alive. Also if the connection is sporadic I imagine we'll attempt to reconnect frequently. This is all just theory until the profiling is done.

**Comment by estellecomment** [comment]
Batch size could also impact : if you try to get a batch of 10 docs and fail after 9 of them because of connectivity, are the whole 10 retried?

**Comment by estellecomment** [comment]
Rummaged through data monitor apps. I like this one : 
https://play.google.com/store/apps/details?id=com.andcreate.app.trafficmonitor&hl=en
![screenshot_2016-02-18-14-19-01](https://cloud.githubusercontent.com/assets/911434/13144441/eba2a6d6-d64a-11e5-8b21-233539b4a01d.png)

You can get breakdown per app, and wifi vs mobile, but couldn't find one that exported data that I wanted.

The apps all start counting bytes from the moment they're installed, and don't get history before, before the [android API](http://developer.android.com/reference/android/net/TrafficStats.html) only lets you get the bytes since device boot. So the apps are basically calling that every so often and storing it.

Could we get a data monitor app installed on a CHW tester's phone? We could pick up the logs when we go to Uganda.

We can also make our own data monitor to get csv logs and the granularity we want, [this project](https://github.com/commonsguy/cw-andtuning/tree/master/TrafficMonitor) is a possible starting point. Don't know if it's worth it.

**Comment by alxndrsn** [comment]
Good idea.  App above looks like it has adverts, so presumably adds its own data-usage overhead.  This is not ideal.

**Comment by estellecomment** [comment]
Hmm free apps tend to do that. Paid apps are more complicated to get on CHW phones.

The problem with extra apps is that if they're never used they get killed by the system, so if we make a separate app it might end up being useless unless woken up every so often by the user. (the alternative is to get a wakelock, but that'll drain the battery and people will complain)

So, add traffic logging to medic app, maybe. Add a traffic-logging class, and trigger it in the [EmbeddedBrowserActivity](https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java) (or somewhere else? I don't know that code)

**Comment by estellecomment** [comment]
![screenshot_2016-02-19-13-40-01](https://cloud.githubusercontent.com/assets/911434/13175952/76009edc-d70e-11e5-98d3-b0a8519868da.png)

**Comment by estellecomment** [comment]
Measured how much background replication costs.
Right now we listen to the `_changes` feed for the ddoc changes, and we have replication both ways.
Will all three, we have:
```timestamp 1456230864647 : {"app":{"tx":5227991,"rx":88686290},"system":{"tx":9407713,"rx":186846377}}
[...]
timestamp 1456234216178 : {"app":{"tx":5262935,"rx":88725254},"system":{"tx":9745328,"rx":197790924}}```

time : 1456234216178 - 1456230864647 = 3351531ms = 56min
tx : 5262935 - 5227991 = 34944 B -> 900,830B/d = **880KB/day**
rx : 88725254 - 88686290 = 38964 B -> 1,004,463B/d = **980KB/d**

So assuming you pay for both tx and rx, you use up your 30MB bundle in 16.5 days. Not good.

**Comment by estellecomment** [comment]
Logs, for records : 
[ddoc changes + replication](https://github.com/medic/medic-webapp/files/142668/ddoc_changes_and_replication_console.txt)
[just ddoc changes, no replication](https://cloud.githubusercontent.com/assets/911434/13253458/75b22a96-da3c-11e5-9e0f-1a6e78302155.png)
[no changes feed (and thus no data spending)](https://cloud.githubusercontent.com/assets/911434/13253490/9692ecbe-da3c-11e5-8006-e682a6333b08.png)

**Comment by browndav** [comment]
It's probably worth repeating this test on lg.dev in light of #1828; I _think_ it makes a pretty major difference, but haven't quantified it yet beyond what's documented in the issue.

**Comment by alxndrsn** [comment]
Good numbers! :+1:

**Comment by estellecomment** [comment]
From lg.dev, with nginx gzip/deflate : 
```1456307596347 {"app":{"tx":6025834,"rx":23691422},"system":{"tx":17331796,"rx":241999914}}
1456308486552 {"app":{"tx":6028174,"rx":23693710},"system":{"tx":17380345,"rx":242078757}}```

delta_t = 1456308486552 - 1456307596347 = 890205ms
delta_tx = 6028174 - 6025834 = 2340B -> 227112B/day = **221kB/day**
delta_rx = 23693710 - 23691422 = 2288B -> 222065B/day = **217kB/day**

You use up your 30MB bundle in 70 days, or 42% it in a month. Better indeed!
But still not great that half your data plan is spent on waiting for data :(

(logs : [lg_dev_nginx_deflate.txt](https://github.com/medic/medic-webapp/files/144341/lg_dev_nginx_deflate.txt))

**Comment by sglangevin** [comment]
Feedback from LG: CHPs are being given 100 MB each month. This has been enough for both CHPs on v1.6 and on v2.0 (our app). From the response we received from their IT team, I didn't see any concern around our app using too much data. There are times where they need to top up a certain CHP's phone mid-month due to various reasons that apply to both their old app and to our app (CHP registering more assessments and follow-ups, uploading images in their app, overuse of other apps like browser or YouTube)

**Comment by estellecomment** [comment]
Closing since the measuring part is done.
