### ISSUE TITLE
Form update causes error in live application

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1779]
Logged in as admin, uploading a new version of form `test`, I see the following error in the browser console:

<img width="903" alt="screen shot 2015-12-18 at 11 17 30" src="https://cloud.githubusercontent.com/assets/191496/11894667/0a58a1c8-a579-11e5-8925-1f15349b7392.png">

Loading the form via the `+` button on the reports screen seems to work without error (and provides the updated form content).

**Comment by abbyad** [comment]
When a form is updated it is deleted then re-uploaded, is this happening when trying to access the form while it is deleted?

**Comment by alxndrsn** [comment]
Not sure!  This can be closed as without context it's not a very useful bug report.
