### ISSUE TITLE
Investigate pouch attachment downloads

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1781]
How is pouch downloading attachments?  Are they coming directly from the changes feed?  If so, it's worth noting:

> Using the `attachments` parameter to include attachments in the changes feed is not recommended for large attachment sizes. Also note that the Base64-encoding that is used leads to a 33% overhead (i.e. one third) in transfer size for attachments.
> –_http://docs.couchdb.org/en/latest/api/database/changes.html_

**Comment by browndav** [comment]
Goal: determine if the `attachments` parameter and/or base64 encoding is in use by PouchDB. If so, determine if it's possible to avoid this. If it is, file another issue for the refactor/removal.

**Comment by estellecomment** [comment]
No, it's not. Pouch gets the documents separately, not from the changes feed (no `include_docs` param):
![screen shot 2016-02-23 at 16 39 36](https://cloud.githubusercontent.com/assets/911434/13256704/1124743e-da4c-11e5-9714-8a80925bfcea.png)

**Comment by estellecomment** [comment]
Attachments are fetched separately.
E.g. for form attachments, `content-type:text/xml` (don't see any trace of either base64 or xml) :
![screen shot 2016-02-23 at 17 35 54](https://cloud.githubusercontent.com/assets/911434/13258691/7a3bac00-da54-11e5-9326-157b5f47fae3.png)
![screen shot 2016-02-23 at 17 41 20](https://cloud.githubusercontent.com/assets/911434/13258738/af252644-da54-11e5-812f-05d241050ba1.png)

**Comment by estellecomment** [comment]
From docs for `GET` in http://docs.couchdb.org/en/1.6.1/api/document/attachments.html:
"The raw data of the associated attachment is returned (just as if you were accessing a static file."
So no base64.
