### ISSUE TITLE
Redesign the Configuration>Schedule (=tasks) page for SMS+android

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1784]
The Schedule page is the last configuration page that has not been converted to angular. We have UX mockups for it to be redone, but these were created prior to `Tasks` being introduced. We need to update these to reflect the schedule configuration in v0.6 - which may be entirely Task-based.

Updating this config page will allow us to make use of the latest config method as well as remove the kanso dependencies and avoid maintaining the v4 UI in multiple places, which causes issues such as #1362 and #1775.

**Comment by diannakane** [comment]
-- look for examples of what configuration wizards could look like, think of similar products that have nice settings/config interactions, but also be realistic about MVP. Marc would implement this as a spreadsheet.
-- Estelle is dev lead on this, she's in Nairobi March 13- March 24
-- Itemize interactions that need to be configured, work with Estelle on how to accommodate these and make it friendly for tech leads

**Comment by garethbowen** [comment]
AFAICT this doesn't apply to LG at all as they're using the smartphone app which uses tasks in place of schedules. This will become important with the DIY and any other SMS based deployments.

**Comment by diannakane** [comment]
I thought the request was for all new v2.6 projects moving forward, to rethink the way that tech leads configure the platform, including tasks. But no, not on the LG timeline.

**Comment by estellecomment** [comment]
Keeping track of some thoughts in this doc : 
https://docs.google.com/document/d/1n7bvLPTfN5k8oSQMgW2NMkYxUtHNO4uN-d-XLef-mYg/edit

**Comment by ranjuts** [comment]
Hey @abbyad, wanted to confirm this with you --- there have been confusions around whether this issue is focused solely on android app enabled configurations (cc @estellecomment ) or would also take into consideration SMS based config/projects or the other way round (as gareth's comment above). I was under the impression that we would be thinking about both cases. We would be configuring in terms of tasks (vs schedules) as it's done in v2.6 but enable doing so for SMS based projects as well. Is that right?

**Comment by estellecomment** [comment]
Cleaner mockups, though still WIP
https://docs.google.com/document/d/1d-buZAjS47jV-VVlG6uSJ1EbQ2UuztJchedWps8StF0/edit#

**Comment by abbyad** [comment]
@ranjuts we want to look at ways to configure all projects moving forward. This means configs for projects where CHW use a mobile app, and those where they communicate exclusively via SMS (TextForms).

**Comment by ranjuts** [comment]
Thanks for clarifying Marc. We've been working w that in mind, so on the right track!

**Comment by alxndrsn** [comment]
Is this ticket referring to Schedules (SMS) or Tasks (nools)?

**Comment by garethbowen** [comment]
This is referring to schedules. The page has since been deleted.

**Comment by alxndrsn** [comment]
Does that mean we can close the issue?  Hard to redesign something that doesn't exist.

**Comment by garethbowen** [comment]
Agreed.

**Comment by estellecomment** [comment]
This is actually still sorta happening, but is better placed in medic-design. Filed https://github.com/medic/medic-design/issues/60 to continue, leaving this one closed.
