### ISSUE TITLE
Improve ng-repeat rendering?

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1795]
>  If you are working with objects that have an identifier property, you should track by the identifier instead of the whole object. Should you reload your data later, `ngRepeat` will not have to rebuild the DOM elements for items it has already rendered, even if the JavaScript objects in the collection have been substituted for new ones. For large collections, this significantly improves rendering performance. If you don't have a unique identifier, track by `$index` can also provide a performance boost. 
> –_https://docs.angularjs.org/api/ng/directive/ngRepeat_

We should probably be using `track by item._id` in most of our ng-repeats

**Comment by garethbowen** [comment]
Closing as replaced by #1862

**Comment by alxndrsn** [comment]
N.B. `track by item._id` did not have noticeable effects in our tests.
