### ISSUE TITLE
report detail link fails to load 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1796]
These two links are not the same report but should be:
https://demo.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/44f17306d96785663156fd8dc0d027d3
https://demo.app.medicmobile.org/_couch/_utils/document.html?medic/44f17306d96785663156fd8dc0d027d3

If the report is not loaded in the left pane then the route fails to initialize properly.  For example this loads correctly: https://demo.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/49c0501411bd2030b1c67f78c60bfe91

**Comment by sglangevin** [comment]
This seems to be working correctly now.
