### ISSUE TITLE
couch2pg adapter needs to have a main loop

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1799]
It is unclear if the import process must be encoded as a shell executable or if a main-equivalent function in JS is fine. The difference trivial.

Regardless, a main loop is required to:
1. call the import process
2. sleep for some predetermined amount of time

Since much of the importer's settings are managed on the environment, it would make sense to maintain the sleep interval in the environment as well.

**Comment by browndav** [comment]
IMO this needs to be shell executable. Gardener `fork`s and `exec`s IIRC, rather than fork and eval in-process.

**Comment by btbonval** [comment]
Good to know. Trivial difference ultimately, as a shell wrapper around the main loop is just another line or two.

**Comment by btbonval** [comment]
Looks like the shell wrapper is pretty standard to NPM, under bin/ with the js under lib/

I'll have to move files around to match the convention.

**Comment by btbonval** [comment]
Shell wrapper component is documented as part of building for NPM which goes into #1800 

This ticket will strictly focus on main loop.

**Comment by btbonval** [comment]
The following works for integration testing (though not called precisely the same way), but as a mainloop function, "Imported successfully" is being returned before the import is actually done.

I'm having a hard time understanding the difference.

Integration:
https://github.com/medic/medic-analytics/blob/764a59facf3f96924e934e82b750ac987da823e6/test/integration/index.js#L100-L102

what I'm trying:
``` javascript
couch2pg().then(function () {
  console.log('Imported successfully at ' + Date());
}).catch(function (err) {
  console.log(err);
});
```

Also weird: if I switch catch/then, the log prints _immediately_, but as shown above, there is at least a brief delay.

The integration test actually waits until the full import process is done using `then()`, so I'm confused.

**Comment by btbonval** [comment]
Okay it looks like the printing actually works okay. I've condensed the then/catch into a single then with two functions for good measure.

The database was up to date, so it took only a moment to decide no action was necessary, thus the immediate print out.

The problem actually appears to be that, once the main set of functions are done, `node` continues running as though waiting on something to complete when there should be nothing left. Dangling functions.

**Comment by btbonval** [comment]
I'm going to leave this running to see if it ever terminates, or if it simply takes a really long time to clean up.

**Comment by btbonval** [comment]
so relevant it hurts.
http://stackoverflow.com/questions/15857568/node-js-program-either-exits-unexpectedly-or-just-hangs

**Comment by btbonval** [comment]
After the update function completes, there are two handles left open. One with looks like a socket with a file descriptor (probably the unix socket to the database?), and one is a socket to the webapp which appears to carry the URL that was requested last.

I'll run three of these in a row and see if I end up with more than 2 dangling connections. If not, these can be ignored. If so, I need to figure out where to close these out.

**Comment by btbonval** [comment]
I added a time delay and only see the one file descriptor dangling.

I need to call `sco.done()` on the database connection to close the command chain.

Doing so, it looks like `node` will eventually terminate. The delay is likely garbage collection at this point.

**Comment by btbonval** [comment]
if Travis says okay, https://github.com/medic/medic-analytics/commit/8dc609dccef74a70af868ff78fa2c2c7ff98971d will close this out.

**Comment by btbonval** [comment]
Travis gives green thumbs up.

**Comment by alxndrsn** [comment]
What status is this ticket?  Presumably not actually **`1 - Scheduled`**.

**Comment by browndav** [comment]
Fixed, thanks.
