### ISSUE TITLE
Bundle PostgreSQL with Medic OS

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1801]
[Moderator edit: PostgreSQL currently builds and ships as part of Medic OS, but lacks startup scripts and initial auto-configuration. Write database setup and startup scripts, and publish working credentials to the appropriate users on the local filesystem. End goal: PostgreSQL is automatically available locally on port 5432 for every up-to-daye Medic OS instance. (DB)]

**Comment by btbonval** [comment]
I will need the help of @browndav or someone familiar with medic-os packaging.

**Comment by browndav** [comment]
Another option suggested at the meetup was to use a hand-installed Postgres for the LG deployment to save time. I think this'll be a priority/timeline-centric decision; consider selecting this issue for discussion during Monday's iteration kickoff call.

**Comment by btbonval** [comment]
We might be able to put this off for the immediate future but it will eventually need to be done.

We'll have a better idea in a few weeks I suspect :)

**Comment by browndav** [comment]
Clarification: add PostgreSQL binaries to a Medic OS package. Write a startup script, `postgresql.conf`, `pg_hba.conf`, and first-run database initialization script. Verify that the server starts up successfully. Verify that the server is not directly reachable from outside of the VM/instance.

**Comment by browndav** [comment]
To-do list:

- [ ] Compile PostgreSQL and its dependencies in-tree.
- [ ] Create skeleton `medic-rdbms` package and build it by default.
- [ ] Add a package installation script for `medic-rdbms` that handles `initdb`, creates an administrative account/database, enables trust authentication in `pg_hba.conf`, and stashes any generated credentials locally in an appropriate place.
- [ ] Verify that PostgreSQL comes up properly after package installation.
- [ ] Add the medic-credentials `authorize-ssh-keys` script to `medic-core` to enable auto-authorization of our SSH keys.
- [ ] Extend the `authorize-ssh-keys` script/process to support the addition/removal/management of system accounts.
- [ ] Verify that a newly-created and authorized system account can access PostgreSQL password-free.

**Comment by browndav** [comment]
In `medic-os`'s `master` branch as of https://github.com/medic/medic-os/commit/b9bff608085c82d2b69355f09c780a93a0aec444.

**Comment by ngaruko** [comment]
Is there anything to AT here @browndav ?
