### ISSUE TITLE
Upgrades are unreliable

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1807]
Upgrades should not depend on browser connection.
Upgrades should work consistently.

**Comment by alxndrsn** [comment]
Which upgrades does this refer to?  Getting new software is always likely to require a working connection...

**Comment by alxndrsn** [comment]
This is referring to deployments via Garden Market.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
Will be fixed by horticulturalist.
