### ISSUE TITLE
Store ddoc + deps in npm

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1808]
Rather than ad hoc

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
If this is still wanted, add to team's Technical Goals list and schedule when it becomes priority.
