### ISSUE TITLE
Remove watches on translations

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1809]
For performance improvement on phones.

**Comment by alxndrsn** [comment]
This should be a simple upgrade of the `angular-translate` lib.

**Comment by garethbowen** [comment]
@alxndrsn Do you have any documentation for the angular translate change or the additional config required?

**Comment by alxndrsn** [comment]
This should give the background: https://github.com/angular-translate/angular-translate/issues/945

**Comment by garethbowen** [comment]
That issue was closed with no fix in place. The workaround seems to be to write your own filter, or rewrite every translate, neither of which are quick fixes. Deprioritising in favour of other issues.

**Comment by alxndrsn** [comment]
https://github.com/angular-translate/angular-translate/commit/dec4bf34b7bb30bba4ca80df263df1858b3e68f5

```js
$translateProvider.statefulFilter(false);
```
?

**Comment by garethbowen** [comment]
Ahh I see. I'll have a look. I think their preferred approach is to use translate directives: http://angular-translate.github.io/docs/#/guide/05_using-translate-directive

> Another way to translate contents within the view layer is to use the translate directive. Using translate filter is great, but using translate directive is better. It turned out that having too many filters in a view sets up too many watch expressions, which is why angular-translate also provides a directive to translate your contents in view layer.

Unfortunately this will take some effort...

**Comment by alxndrsn** [comment]
`$translateProvider.statefulFilter(false)` didn't seem to remove watchers, and upgrading the lib broke the tests.  So I reverted the change.

**Comment by garethbowen** [comment]
I've upgraded the library. I can't see any quick wins here as most translations are only used once. I was hoping to find something translated for every item in a list (or similar). We should try to use the translate directive in future which does register a watcher.

**Comment by alxndrsn** [comment]
> We should try to use the translate directive in future which **does** register a watcher.

Typo?

**Comment by garethbowen** [comment]
Yes. Fixed.

**Comment by alxndrsn** [comment]
@garethbowen is the translate update related to this warning?

<img width="797" alt="screen shot 2016-02-04 at 17 03 09" src="https://cloud.githubusercontent.com/assets/191496/12820988/c3c6ec10-cb61-11e5-9518-1bbbdb102f42.png">
Link: http://angular-translate.github.io/docs/#/guide/19_security

**Comment by garethbowen** [comment]
Probably. I didn't see that. I'll look into it.
