### ISSUE TITLE
Multiple build tools

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1824]
Bower, kanso, npm, grunt. 
 - Remove some? 
 - Build speed?

**Comment by estellecomment** [comment]
Remove bower in favor of npm : #1573

**Comment by garethbowen** [comment]
Bower has been removed.

Removing kanso is infeasible right now - we'd have to rework deployment, dashboard settings, gardener, and probably other bits as well.

npm is the package manager of choice.

Closing this issue.
