### ISSUE TITLE
Better instance deployment

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1829]
- checklist
- automation

**Comment by alxndrsn** [comment]
@browndav please triage and either:
* add detail and schedule, or
* close

**Comment by browndav** [comment]
I'd need additional detail to understand what's being asked here. @estellecomment, can you update?

**Comment by estellecomment** [comment]
@browndav This is a ticket from the dev meetup (not last one, previous one). Your work with Henok probably covers it by now. Closing.
