### ISSUE TITLE
Tests for Couchdb server-side code

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1834]
Views, filters, etc.

**Comment by SCdF** [comment]
To make it clear: writing the test so that it hits Couch (as opposed to just unit testing the JS code) allows us to re-write those filters in other languages, primarily Erlang. This could be useful for performance.

**Comment by alxndrsn** [comment]
Hi @SCdF, can you triage this?  I'd guess now is the time to either do or ditch, as there could be some interesting changes between couch 1.6 and couch 2.

**Comment by SCdF** [comment]
@alxndrsn Hmm. I don't think we're ever going to justify spending time to work backwards and add tests to existing code (as much as I'd like to). I think it's something we should be be conscious to do in the future. i.e., when you create a new view, write tests for it. Now there are integration tests in api this should be much easier than when it was raised.
