### ISSUE TITLE
Deploy Erlang doc_by_place filter 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1835]
As a response to #1782 I re-wrote the doc_by_place filter in Erlang. It has been reasonably-though-not-exhaustively manually tested. The code is here: https://gist.github.com/SCdF/50b69e655595c56f679e

To be able to deploy this we need to do the following:
 - Add an integration test that hits couch for this filter. This should be covered in #1834. It needs to hit couch because once the filter is written in Erlang that is how it must be tested
 - Manually deploy the Erlang code and make sure the tests still pass
 - Work out how to use Kanso to deploy a separate design doc that has its language set to Erlang. This would probably be done by creating a new package (see the `packages` dir) with its own separate `kanso.json` file
 - Determine that there are no security issues with deploying erlang filters (abstract: erlang filters run with pull non-sandbox permissions under whatever user couch runs under. We need to make sure enabling this doesn't allow people to do bad things).
 - Document the changes required to couch deploys to enable erlang filters (ie you need to change a `local.ini` property)

**Comment by SCdF** [comment]
Another better option is to write it as a migration script in medic-api. The tests would be protractor e2e tests in medic-webapp

**Comment by SCdF** [comment]
An update: I've fixed issues with the Erlang filter and optimised it some: it's now ~5x faster than the comparative JS filter. There are opportunities to make it faster still, but they are slightly more time consuming. Up next: Work out how to get this deployed it its own separate ddoc.

**Comment by SCdF** [comment]
Added notes to the ticket about making sure a) there are no security issues with erlang filters and b) documenting how to enable them / that they need to be enabled on couch

**Comment by estellecomment** [comment]
This is not in use any more, so no AT needed.
