### ISSUE TITLE
Write Nools testing framework

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1836]
We want to:
 - Have tests for our current rules
 - Make it easy for other people who write rules to also write tests for those rules

Ideally we'd have a nice framework that boots up nools and provides convenience functions that allow you to push nools facts and expect certain facts out the other end.

**Comment by SCdF** [comment]
Best way to achieve this IMO is for devs to write tests for LG's current tests in such a way that the tests are stored alongside the rules, which will force us to write something (hopefully) that tech leads can easily pick up

**Comment by alxndrsn** [comment]
What do you think of this?  Perhaps we need a separate ticket for fleshing out the lg-ug tests.

**Comment by SCdF** [comment]
Looks good. It's hard to tell without an example honestly, though I understand why you haven't commited one to medic-webapp.

**Comment by SCdF** [comment]
re: another ticket, it was perhaps silly to have this ticket have two goals like I wrote. So yeah, we should split it up, and cap this ticket off with having a script, and then create another ticket for getting LG tests. And I would argue for a third, which is setting up medic-projects with a build that runs these tests.
