### ISSUE TITLE
Ddoc gets loaded by pouch on nearly every user interaction

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1837]
It's unclear if this causes performance issues as Pouch's debug information isn't ideal for performance testing.

If you enable debug logging in pouch (http://pouchdb.com/api.html#debug_mode) and reload the page, you'll get a bunch of fun stuff in the logs. Note that the times at the end of each log message as the ms since the last message.

These debug logs seem to indicate that pouch is called to load the ddoc on nearly every single user interaction (the notable exception being the tasks view, which is generated and doesn't hit the DB).

**Comment by SCdF** [comment]
Here is some example debug output, all from the Tecno, firstly from first boot:
![image](https://cloud.githubusercontent.com/assets/583851/12557239/a44573f8-c381-11e5-9a52-731e7b3a5f2e.png)
What this is saying is that 64ms after pouch boots someone asks it for the ddoc, and then 2 _seconds_ after that it gets asked for again. 210ms after that one answer is given, and 24ms after that the second one is. Why there is two seems to be some kind of bootup bug / feature, because if you run `PouchDB('medic').get('_design/medic')` you'll get two as well, each time. See the last example for how to return just one.

This one is from switching from tasks to contacts:
![image](https://cloud.githubusercontent.com/assets/583851/12557295/f74b1daa-c381-11e5-8b6b-aa9246555d6b.png)
As I read this, it's two interleaving calls, and we could infer from this that getting the user took `281+711=992ms`, while getting the ddoc took `711+269=980ms`.

Lastly, here is one I'm ran manually myself, for performance funzies:
![image](https://cloud.githubusercontent.com/assets/583851/12557492/f4045c0a-c382-11e5-8f73-bd6087771b4c.png)
Showing that it takes ~190ms in this case (running it multiple times seems to range wildly from 110-290ms).

**Comment by browndav** [comment]
Nice catch; seems like we could make a pretty substantial performance win here.

**Comment by alxndrsn** [comment]
`+2ms`?  May not be so bad if that's how long it takes!  I'd hope that PouchDB is caching, but you could probably write a simple in-memory cache yourself that wraps the DB service and see if that makes a difference.

**Comment by SCdF** [comment]
@alxndrsn where are you getting the 2ms from? Remember each number is the number of milliseconds *since the last debug message*, which makes stuff confusing when they interleave.

**Comment by SCdF** [comment]
@browndav what I'm unsure about is what the bug is exactly. For example, is it correct that it loads the Ddoc every time? Is that because we have translations in it for example? I wonder if splitting out ddoc out more would help to reduce the amount of stuff Pouch is having to serialise out of wherever it stores it (indexdb or whatever),

**Comment by SCdF** [comment]
One option is to find the root where the Ddoc is being asked for and manually cache that in JS. This may also negate the (performance) need for splitting the ddoc

**Comment by alxndrsn** [comment]
@SCdF or just cache it in the DB service - then you won't need to work out where it's being requested from, and caching would be app-wide.

**Comment by SCdF** [comment]
@alxndrsn sorry yeah that's what I meant. As in, find the one place that every request for the ddoc ends up and then cache that

**Comment by SCdF** [comment]
This looks like it's due to internal Pouch stuff, e.g. loading views:
![image](https://cloud.githubusercontent.com/assets/583851/12577190/c249ccfc-c410-11e5-96ce-d3f4b3393559.png)

**Comment by SCdF** [comment]
I wrote a gross patch over pouch (that obviously we'd never ship, and doesn't care about updated files etc) just to see what would happen if the ddoc was stored in (JS) memory instead of being parsed out of storage every time it's requested: https://github.com/SCdF/pouchdb/commit/dcf23f85763b0cab92ec1e5539afbf0576b2d846

This drops the time it takes to load the ddoc from 1-200ms to ~10ms. However, it's not visually obvious that app performance has been improved, presumably because the choke point is still Angular.

**Comment by SCdF** [comment]
I don't think there is anything more to do on this: as far as I can tell the code is working as expected. There is a possibility we'd want to patch pouch to be more aggressive with some of its caching, but we'd do that in another ticket.
