### ISSUE TITLE
Detect when pouch has unsynced changes so we can have a simple sync status somewhere

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1842]
It would be useful, even if just for debug purposes, to be able to tell if everything in a user's pouchdb has been replicated into the cloud.

I was hoping that pouchdb replication would provide useful information. So far I've had a super quick look at the event handlers you can add to the replication call: http://pouchdb.com/api.html#replication

Unfortunately they don't seem massively useful by themselves. You effectively have `active`, `paused` and `change` to play with:
 -  `change` fires _when a change has been replicated_.
 - `active` and `pause` are switched between fairly regularly when pouch thinks it might have something useful to do but then realises for whatever reason it doesn't. 
 - `pause` is the end state (since we are continuously replicating) regardless of whether we have changes that need to be duplicated.

Note that there is no obvious indication that you're offline, just that you're not currently actively replicating.

One possibility would be to make sure we funnel all our pouch db put calls through one wrapping function which keeps a list of all the document ids that pass through, and then remove them as they work their way through the change event handler. We could then bind that list (or a count of that list) to the UI and use it to display our sync indication.

**Comment by SCdF** [comment]
Another option would be to just store the last synced seq id somewhere and update it every time the change callback gets hit.

**Comment by garethbowen** [comment]
I think this is a duplicate of #1270 . @SCdF Maybe add the above info to that issue and close this one?

**Comment by SCdF** [comment]
Done.
