### ISSUE TITLE
check for `enketo_contact` before use

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1843]
In this commit we are using the contact information assigned to an enketo form.  

https://github.com/medic/medic-webapp/commit/1445f13281792dc6b639ec862496a89f9686cb85#diff-0b7e26355f34ba7bde6fe48a1ca6e606R52

But there are cases where this information might be undefined.  We might want to handle that case better?

Example stacktrace from lg.dev when you click on "Johnson Jackie follow up" task:
```
TypeError: Cannot read property 'docId' of undefined
    at inbox.js:formatted:60603
    at i (dependencies.js:formatted:3621)
    at dependencies.js:formatted:3631
    at n.$eval (dependencies.js:formatted:4112)
    at n.$digest (dependencies.js:formatted:4045)
    at dependencies.js:formatted:4116
    at e (dependencies.js:formatted:1261)
    at dependencies.js:formatted:1371
```

**Comment by alxndrsn** [comment]
The commit mentioned above does not introduce that code, it just reformats it.

**Comment by alxndrsn** [comment]
Useful info(?): `enketo_contact` should only be defined when editing a contact; the `phonewidget` might be used in e.g. a report form.

**Comment by mandric** [comment]
My bad, here's the right commit reference: https://github.com/medic/medic-webapp/commit/b5618361556a2c32e4e5a6abef36b06e0eb1ad17
