### ISSUE TITLE
CHW sync status indicator - design

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#1849]
MM to clarify -- if the CHPs can be able to see the data they have submitted to the database i.e 12 of 12 records submitted

Clarification - do they mean synching data, or updating the forms, or updating the app itself?

LOW: read as "have docs synced?";  HIGH: per-record sync marker
what should be on the replication status screen? What should it look like?

feasible for dev team to work on in Feb

**Comment by diannakane** [comment]
![screen shot 2016-02-08 at 10 44 24](https://cloud.githubusercontent.com/assets/1675870/13331992/c03ee03a-dbb4-11e5-978a-f5621d4ed872.png)

Working with Estelle to update

**Comment by diannakane** [comment]
After experimenting with several options, we determined that the best place for a CHP to view last sync and sync status would be from the hamburgers menu. States are up-to-date and not up-to-date. "Sync in progress" is needed could be a spinner in place of the sync status icon. We determined that no "start sync" button needed (and wouldn't be appropriate as an action from this menu). 

Additional user story about this issue: Indicating that the phone is syncing would be helpful to a CHP, though. For example, a CHP has been working offline for a few days and then connects to the internet to sync. She would want to know that syncing has started and be alerted when the phone has successfully synced all docs to and from the server. Not sure if that fits in this issue (speaking of #2415), but I do think we should explore further and find a way to provide a visual indicator to a CHP so that she knows when her phone is synced and can be disconnected from the internet.

Lo-fi mockup below; will incorporate this into the next hi-fi mobile mockup we do. @Lesterng 
![last sync](https://cloud.githubusercontent.com/assets/1675870/16247465/bbfe149e-37be-11e6-8bfe-66318f6e6ab2.png)

**Comment by Lesterng** [comment]
@diannakane @sglangevin  This is an interesting thought. Should syncing be a task? If you are a week past your last sync date, it would be added to your task list.

**Comment by diannakane** [comment]
That's a cool idea, Lester! I would add that to our design doc as a
separate issue / feature request. We still need to make the date of last
sync available to CHWs as well as show them that it's complete.

On Tue, Jun 21, 2016 at 3:17 PM, Lester NG <notifications@github.com> wrote:

> @diannakane <https://github.com/diannakane> @sglangevin
> <https://github.com/sglangevin> This is an interesting thought. Should
> syncing be a task? If you are a week past your last sync date, it would be
> added to your task list.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1849#issuecomment-227589226>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXrTDZIwzHWN1JlqmydSp5bIXp5hnks5qOGLugaJpZM4HNHxD>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by sglangevin** [comment]
Closing in favor of #3357.
