### ISSUE TITLE
Decrease pouch replication docs-per-fetch

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1854]
When the changes feed is sparsely populated for a particular filter and connection is not reliable, it may be more likely for a replication cycle completing if [`batch_size`](http://pouchdb.com/api.html#replication) is reduced in the replication options.

**Comment by SCdF** [comment]
:shipit: 

Do we need to think on ways of testing this in the field? It sounds like this will make replication more stable but also increase replication time. How are we going to determine that 1 is the correct number?
