### ISSUE TITLE
Querying a pouch view is very slow

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1857]
PouchDB seems to take a long time to parse our ddoc every time a view is requested, in the order of 1 second per request. Most of this is due to parsing our enormous ddoc. Either reduce the size/complexity of our ddoc, or convince pouchdb to cache the views so it's only expensive on first load.

Props go to @SCdF for discovering this.

**Comment by garethbowen** [comment]
I couldn't find any easy way to reduce the size of our ddoc so going with the pouch patch for now.

**Comment by garethbowen** [comment]
Assigning to @alxndrsn for testing on more devices. If this passes review I'll try and get it merged upstream.

**Comment by alxndrsn** [comment]
Assigning to @SCdF until I get a decent test setup locally.

**Comment by SCdF** [comment]
Talked to @garethbowen, it looks good to me. To be specific: This doesn’t deal with cache invalidation: as in, if the ddoc changes the view won’t be updated. This doesn't affect us because a ddoc change requires a page refresh anyway, but it will hinder its upstream adoption.
