### ISSUE TITLE
Families registered should use map / reduce instead of counting results

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1858]
The current families registered target seems to pull all registered families and then count them: https://github.com/medic/medic-webapp/blob/develop/static/js/services/analytics-modules.js#L224-L227

This seems wildly inefficient, and ideally something that we could use map / reduce for?

**Comment by garethbowen** [comment]
This was a temporary "feature", just so the tab wouldn't be empty in the LG field test. This has been replaced by #1278
