### ISSUE TITLE
Use Tasks for schedule generation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1860]
Replace the schedule configuration with a worker to send reminders based on a task schedule. This is so dumbphone and smartphone deployments can use the same configuration, rather than us trying to support two different implementations.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by abbyad** [comment]
Although there are some benefits to doing this it is not is not required by projects in the near term. We can re-open and schedule when required or we slot time for this as tech-debt.

cc @garethbowen, @sglangevin
