### ISSUE TITLE
Review and merge LiveList to improve rendering performance

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1862]
We've determined that an excess number of Angular watches is hurting our performance while rendering and interacting with lists.

@alxndrsn has a branch (https://github.com/medic/medic-webapp/compare/develop...alxndrsn:cream2?expand=1) that reimplements an `ng-repeat` style list without using Angular, but still uses Angular templates.

Identify any issues with the patch, review, fix, and merge in to `develop`.

# Before merge

## To do

* [x] separate `LiveList` config from `InboxCtrl`
* [x] reports list has wrong names for forms
* [x] separate filters culling from `LiveList` merge
* [x] variable renames unrelated should be in a separate commit (direct to `develop`)
* [x] task list is not sorted correctly
* [x] remove HTML templates from `inbox.html`

## To test

* [x] ~~new task -> task list update~~
* [x] task resolution -> task list update
* [x] contact name change -> task list update
* [x] new contact -> contact list update
* [x] contact delete -> contact list update
* [x] contact name change -> contact name change in list:
  * [x] detail changed
  * [x] correct position in list
* [x] new report -> report list update
* [x] ~~report detail change -> report list update~~ -> separate ticket at #1917
* [x] report delete -> report list update
* [x] selecting a task in the list -> list item hilighted
* [x] selecting a contact in the list -> list item hilighted
* [x] selecting a report in the list -> list item hilighted
* [x] handle change-feed updates in `LiveList`?
* [x] check that new contact created when not on _Contacts_ appears when tab is changed
* [x] check that new task created when not on _Tasks_ appears when tab is changed
* [x] check that new report created when not on _Reports_ appears when tab is changed
* [x] contact search
  * [x] filter by string
  * [x] filter by date etc.
* [x] tasks are sorted correctly
* [x] report filters
  * [x] filter by string
  * [x] filter by date etc.

**Comment by garethbowen** [comment]
I've added a few comments to the merge but nothing major. Nice one!

**Comment by browndav** [comment]
Moved in to current iteration.

**Comment by garethbowen** [comment]
Code review: Most of it was already reviewed so it's mostly good.

There's a todo item I don't understand in the live list service: "// TODO cache activeDom; set it when loading a controller!!". Either fix that or create an issue to fix it or explain it better?

Also the live list service needs unit testing.
