### ISSUE TITLE
Reset filters on tab change

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1866]
Filters are shared between tabs which is by design because any filter settings set on one tab are then kept and automatically applied to the next tab. However this can be confusing for even experienced users who expect each tab to start with an unfiltered view. It's also turned out to be less useful than hoped as most filters are tab specific. Resetting filters when changing tabs will align the UX with user expectations.

**Comment by garethbowen** [comment]
Also, if each tab has it's own set of filters we can clean up filter code and improve performance as we'll only have to manage the filters for the currently selected tab.

**Comment by garethbowen** [comment]
@abbyad Is this a UX win in your opinion?

**Comment by garethbowen** [comment]
Related: #1866

**Comment by garethbowen** [comment]
Marc said to do it, so let's do it...

**Comment by alxndrsn** [comment]
I recommend to hold off on this until #1862 is stabilised

**Comment by garethbowen** [comment]
PR ready for review: https://github.com/medic/medic-webapp/pull/2190

**Comment by SCdF** [comment]
Gosh, this PR is rather large isn't it? It's also perhaps--from a cursory reading--both refactoring filters to be a level lower and also _other stuff_, that you found as you were cleaning (pennies behind the couch, as it were). Or maybe not. It's hard to tell. Which is I suppose the point I'm making.

I am going to give it a read and try to get the gist of it (ie things removed from inbox, things added to other places), but it may require a guided tour to fully comprehend.

**Comment by SCdF** [comment]
(right, so it looks like you've moved downloads down the stack as well?)

**Comment by garethbowen** [comment]
Downloads are context sensitive - ie: they are filtered in the same way that the view is. So changing the filters meant I also had to change Downloads...

**Comment by SCdF** [comment]
So from what I've read it looks good. If you want we can walk through it on a call or something, otherwise we should get merged to reduce that stale taste
