### ISSUE TITLE
Upgrade bootstrap-tour to a more recent cut of the code

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1867]
Bootstrap-tour has not seen a release in awhile (over a year) and to fix some bugs we are currently using a version I've forked which is the last release + the one thing we need. 

Writing this ticket as a reminder because that's terrible, and when there is a proper bootstrap-tour release we should move to that. I've raised a ticket with the bootstrap guys, but afaict no one has been active on that project since mid december.

**Comment by SCdF** [comment]
They have release a new version, we could use that and test everything.

**Comment by garethbowen** [comment]
This was fixed as part of #1573
