### ISSUE TITLE
App hanging on hitting Submit Button

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1868]
Feedback from the field:
"
_**Today i have received complaints from V2 CHPs in Mukono that if  they click on SUBMIT, it is just hanging and this has been so for two days ago**._

![elsie](https://cloud.githubusercontent.com/assets/15346836/12814545/d8ad7b78-cb50-11e5-98a6-1388ddc243e5.png)

**Comment by browndav** [comment]
Hi Fred,

Have you been able to reproduce this on one of your test devices or with a desktop web browser? A set of steps to reproduce the problem reliably would be really helpful here. Thanks!

**Comment by fredatthehub** [comment]
Hello Dave,

The main problem is that its sporadic an as such may not be very easy to reproduce. I have asked the field supervisors to try and get as much information as possible when they experience issues like these.

**Comment by browndav** [comment]
Goal: attempt to reproduce this issue. If this is reproducible, capture a backtrace and file an issue to fix the defect.

**Comment by browndav** [comment]
Not enough information to proceed given the current timeline. Moving to backlog for now. If the problem becomes reproducible or you uncover additional information, please comment and we'll take another look.

**Comment by garethbowen** [comment]
This is a year old and nobody's complaining about it so I'm going to close it. Reopen if it's still happening.
