### ISSUE TITLE
Error Fetching Contacts

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1869]
Feedback from the LG Field Test:

> _Fetching error has occurred is another serious issue to some of them when they try to open the APP. Even when they reload the APP some time it fails._

![error-fetching-contacts](https://cloud.githubusercontent.com/assets/2064938/13159663/dac62cea-d6f7-11e5-8c3f-52078a641319.png)

**Comment by sglangevin** [comment]
@fredatthehub do you know which users are experiencing this issue?

**Comment by garethbowen** [comment]
Closing for insufficient information. If this happens again capture the console log, and record which user and which server this happened on.
