### ISSUE TITLE
Error Loading Form  -  Assess Patient

### ISSUE THREAD

**Issue by fredatthehub** [medic/medic-webapp#1870]
Feedback from the LG Field Test:

![wagaba](https://cloud.githubusercontent.com/assets/15346836/12814610/5eeef9c8-cb51-11e5-97b9-9394ac80a4a9.png)

**Comment by sglangevin** [comment]
@fredatthehub do you have more information? Could you provide the username of the CHP (or CHPs) who are experiencing this and what steps they went through before seeing this screen? I'm assuming they were trying to access this form from a certain contact. If you could get additional details, that would be helpful. If we can't reproduce the error on our end, we won't be able to fix it.

**Comment by alxndrsn** [comment]
Please re-open with more details if this is seen again.
