### ISSUE TITLE
Remove the callback based Settings

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1871]
We have Settings based on callbacks and SettingsP based on promises. Get rid of the callback option and rename SettingsP to Settings.

**Comment by garethbowen** [comment]
Don't worry about reviewing _all_ the changes, but a quick look would be useful I think.

**Comment by estellecomment** [comment]
Two nits, and a bunch of questions for my own information.

**Comment by estellecomment** [comment]
#1526

**Comment by estellecomment** [comment]
LGTM! Thanks.
