### ISSUE TITLE
Integration testing for .6 requires dataset

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1872]
I think this is dependent upon https://github.com/medic/medic-webapp/issues/1764

This was not previously necessary, but the adapter is now incorporating very specific 0.6 code with https://github.com/medic/medic-webapp/issues/1798

**Comment by btbonval** [comment]
Integration testing of XML form definitions would be probably use fixtures in these comments:
* https://github.com/medic/medic-webapp/issues/1798#issuecomment-180241049
* https://github.com/medic/medic-webapp/issues/1798#issuecomment-180243846

Some XML fixture with form data would still be required.

**Comment by btbonval** [comment]
Specifically something portable that can be installed on TravisCI, much like the medic-data releases.

**Comment by btbonval** [comment]
might be related https://github.com/medic/medic-webapp/issues/2238

**Comment by garethbowen** [comment]
Closing as ancient.
