### ISSUE TITLE
Deleting anything returns user to contacts list

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1873]
E.g. delete a report.

This seems to be deliberate:
https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/inbox.js#L658

**Comment by alxndrsn** [comment]
Introduced in #1348

**Comment by alxndrsn** [comment]
Not sure if this is the safest way to determine which view to return to; I also considered using `$scope.filterModel.type` instead of `$state.current.name`.

**Comment by garethbowen** [comment]
`$scope.filterModel.type` feels a bit flakey in my opinion. I much prefer interrogating the $state. It's a shame about the string parsing but I can't see another way to do it...
