### ISSUE TITLE
Restructure the repository to be more standard and logical

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1876]
Most of our JS and CSS is not served statically.  These files should reside in a `src/` directory.  `static/` should be reserved for files deployed directly to the server without modification.

**Comment by garethbowen** [comment]
Good call. Also consider putting all compiled resources in the same directory, eg: `dist` or `build`. Currently we have `static/dist`, `ddocs/compiled`, and `build`.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
ddoc build refactor is related: #3019.  I will look at this too.

**Comment by garethbowen** [comment]
@mandric I'm not sure this is related. Can we kick it out of the milestone for now?

**Comment by mandric** [comment]
I would say this is probably not worth working on until kanso removal/ddoc refactor (#3019) is done.

**Comment by garethbowen** [comment]
Backlogged so removing from milestone.

**Comment by garethbowen** [comment]
Proposal: https://docs.google.com/document/d/1ToR19pbEsXezpBN3vAAa0gt9ZBMsE7jSHN0Vh7oZyik/edit#heading=h.ugxoju33poid

**Comment by garethbowen** [comment]
Merged. Nothing to AT except the usual release testing stuff so moving straight to ready.
