### ISSUE TITLE
`count-selected` not working

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1877]
Some of the forms used in the field test work in build 2508 (lg.dev) but do not work in build 2598 (alpha.dev).

For instance, the `assessment_follow_up` form fails with `The string 'count-selected("")' is not a valid XPath expression."`.

Also, the `assessment` form failed with `The string 'concat("")' is not a valid XPath expression."`. This was resolved by avoiding the use of concat with a single arg (https://github.com/medic/medic-projects/commit/f37311b5fbfc6e446b75d8f6d36aad538140566d), but then the count-selected() error is encountered.

**Comment by alxndrsn** [comment]
I agree that `The string 'concat("")' is not a valid XPath expression.` - `concat()` takes a pair of arguments.

**Comment by abbyad** [comment]
Works well in 2612, moving to Ready.
