### ISSUE TITLE
XForm field with `calculate="today()"` gets wrong date in certain timezones

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1878]
A XForm field with `calculate="today()"` gets yesterday's date for computers in EST and PST, but the correct date for a computer in GMT.

Working theory is that the date value _in the current timezone_ is obtained for today at midnight GMT, which results in yesterday's date for Western timezones.

If the `today()` is used in a calculation (eg `decimal-date-time(today())`) it appears as expected. Also, today() seems to have different behaviour in Enketo proper, which maintains the time information.

## Sample form
```
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test: today</h:title>
    <model>
      <instance>
        <test-today id="test-today" version="2016-02-05">
          <value/>
          <verification/>
          <note/>
        </test-today>
      </instance>
      <bind calculate="today()" nodeset="/test-today/value" type="string"/>
      <bind calculate="decimal-date-time(today())-decimal-date-time(../value)" nodeset="/test-today/verification" type="string"/>
      <bind nodeset="/test-today/note" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/test-today/note">
      <label>**today() set as ../value**: <output value=" /test-today/value "/>

**verify today() in calculation vs standalone value:**
decimal-date-time(today()) - decimal-date-time(../today/) = <output value=" /test-today/verification "/>
_should be 0_</label>
    </input>
  </h:body>
</h:html>
```
## Result in medic-webapp build 2598

![image](https://cloud.githubusercontent.com/assets/789512/12864776/3ecf75f4-cc65-11e5-8327-92549eee2d3b.png)

## Result in Enketo proper

![image](https://cloud.githubusercontent.com/assets/789512/12864774/1aa80286-cc65-11e5-9484-197bf49080d8.png)

**Comment by alxndrsn** [comment]
> which maintains the time information

maintains the time *__zone__*?

**Comment by alxndrsn** [comment]
> which maintains the time information

Ah, I think I understand what this means now...

**Comment by alxndrsn** [comment]
# `today()` vs `now()`

There are seemingly contradictory definitions of what these two functions should be doing:

> `today()`: Returns today’s datetime as a string
> `now()`: same as `today()`
> – https://opendatakit.github.io/odk-xform-spec/

> `today()`: Return today's date
> `now()`: Return a timestamp for this instant
> – https://opendatakit.org/help/form-design/binding/

> `today()`: return today's date
> `now()`: return a timestamp for this instant
> – https://bitbucket.org/javarosa/javarosa/wiki/xform

We are currently following the latter two definitions - `today()` returns a timestamp at midnight UTC of today, whereas `now()` returns a timestamp of the current time in the current timezone.

If we choose to follow the implementation in ODK Collect, which is the first definition above, I am hapy to do that and will document as such.

-----

The above difference between `now()` and `today()` is not directly related to the reported bug.  `today()` should probably return a timestamp for midnight _in the current timezone_.

**Comment by abbyad** [comment]
I think `today()` returning a ISO 8601 date, such as `"2016-02-17"`, would be acceptable for all of those definitions.

The critical aspect for this issue is that the date reported ends up being incorrect in some timezones. I have now also seen this happen in a form with a date picker and then using that date in a calculation within the same form.

This issue also surfaced in #986 as well, but perhaps for a different reason.

**Comment by alxndrsn** [comment]
@marc giving this some more thought, it seems reasonable to make `today()` identical to `now()`.  This has a couple obvious advantages: 

* keep implementation in line with odk-collect and enketo-core
* fix these timezone bugs

**Comment by abbyad** [comment]
Soudns good @alxndrsn. When we want to save or display the date we use `format-date(/path/to/node, '%Y-%m-%d')`?

**Comment by abbyad** [comment]
This now works consistently, so moving to Ready.

Just want to note that we are now back to using the today the way it is in Enketo proper - which is **different than the behaviour in Collect**. From my testing is seems that Enketo's `today()` has date and time, which can make conditions seem wrong, whereas in Collect it is strictly the date value.

For instance, on Feb 24, 2016, `"2016-02-24" >= today()` is `true` in Collect, `false` in Enketo. We should report/fix this upstream. In the meantime, we will document the discrepancy to hopefully avoid frustration while building and testing forms that requires date arithmetic and conditions.
