### ISSUE TITLE
Minimise templated HTML

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1883]
Looks like the following ngTemplate options could be worthwhile:

> ### htmlmin
>
> > Object containing [htmlmin options][2] that will *significantly* reduce
> the filesize of the compiled templates.
>
> Without this, the HTML (whitespace and all) will be faithfully compiled
> down into the final `.js` file.  Minifying that file will only cut down
> on the *Javascript* code, not the *HTML* within the strings.
>
> I recommend using the following settings for production:
>
> ```js
> htmlmin: {
>   collapseBooleanAttributes:      true,
>   collapseWhitespace:             true,
>   removeAttributeQuotes:          true,
>   removeComments:                 true, // Only if you don't use comment directives!
>   removeEmptyAttributes:          true,
>   removeRedundantAttributes:      true,
>   removeScriptTypeAttributes:     true,
>   removeStyleLinkTypeAttributes:  true
> }
> ```
> If you are using SVG, please make sure you set ```keepClosingSlash:true```
>
> – https://github.com/ericclemmons/grunt-angular-templates#htmlmin

[2]: https://github.com/gruntjs/grunt-contrib-htmlmin

**Comment by alxndrsn** [comment]
This won't work until the weird templates are removed by https://github.com/medic/medic-webapp/pull/1884

**Comment by alxndrsn** [comment]
This is waiting for PR/review of https://github.com/medic/medic-webapp/pull/1885

**Comment by garethbowen** [comment]
The code looks fine. Haven't tested it.
