### ISSUE TITLE
Revoke full-database administrative access for admin user

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1888]
Currently, the `admin` user for `medic-webapp` is a full CouchDB administrative user. This makes it possible to perform privileged operations like database deletion, which is undesirable. Switch the initial administrative user over to a database-specific role, and revoke full-database administrative access.

This will have major implications for Medic OS and `concierge`; I'll file a second issue (and mention it here) to cover those downstream changes.

**Comment by SCdF** [comment]
To be clear about language, I'm going to say there are *CouchDB Admins* and *Medic Admins*. Currently Medic Admins are also CouchDB Admins, and we want to change that.

Things to do on this ticket:
- Regression test to make sure that Medic Admins don't need anything else from being CouchDB Admins apart from CRUDing users
- Update documentation (if it exists) that we have about Medic Admins
- Write an upgrade script to move all existing Medic Admins from CouchDB Admins to normal users with the correct role etc, as well as create that roll on `_users` etc

**Comment by SCdF** [comment]
So the strategy here is to not give out admin access to anyone outside of medic / ops. If issues come out where customers need functionality that is only currently available to this user we will look at exposing it in a safe way.
