### ISSUE TITLE
Write migration script to enable Erlang script support

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1891]
There is a setting you need to change to enable Erlang script support. I'm pretty sure you can do it (see: https://github.com/johnko/kanso-manage-couchdb/blob/master/test.sh#L27 ) so we can just write an upgrade script so people don't need to worry about it.

**Comment by alxndrsn** [comment]
@SCdF I assume this should be assigned to you

**Comment by SCdF** [comment]
@alxndrsn I can certainly do it, but I'm working on other stuff right now. Anyone can pick it up

**Comment by SCdF** [comment]
Added it here: https://github.com/medic/medic-api/commit/4744bd98031a7e97d427f6b5b57e4cd121b775dd

**Comment by SCdF** [comment]
Hey @estellecomment can you check this out and see if it makes sense to you? Note that I haven't written a test because I can't work out what I'd test except that the one `db.request` statement I wrote indeed gets called.

**Comment by estellecomment** [comment]
I tried it and it seems to work! LGTM.
