### ISSUE TITLE
Convert help pages to markdown, and upload them

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1895]
Split from #1700; work detailed by @garethbowen:

> My initial thought is to upload the standard help library when api starts up. Obviously this will increase the size of the ddoc, but that's how couchapps work...
> 
> Quite a lot of time and effort was put in to the existing help pages so we should convert them to markdown and get them working[.]

**Comment by alxndrsn** [comment]
@garethbowen do you have any more thoughts on the mechanism of uploading, or where the help text & translations should be stored code-wise?

**Comment by garethbowen** [comment]
I think the markdown files need to be attached to the ddoc.

**Comment by alxndrsn** [comment]
...and then removed again by API?

**Comment by garethbowen** [comment]
I guess so. The api could download them and create the docs and then delete the attachments. Does that make sense?

**Comment by alxndrsn** [comment]
Yep.  To clarify, the help docs would be part of the ddoc at deployment time, but not by the time ddoc is served to end users?

**Comment by garethbowen** [comment]
Sure.

**Comment by browndav** [comment]
Deprioritized on 2/22 iteration planning call; moving to backlog.

**Comment by garethbowen** [comment]
Once this is done remove the help text from the POEditor to make the translations files much smaller.

**Comment by garethbowen** [comment]
Also fix the links in the Dashboard schema: #3088

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by SCdF** [comment]
@garethbowen are these help pages still relevant (I presume they were made for 0.4 so may not be correct for 2.x)? If so we should totally get them back online, it's a waste of effort otherwise.

**Comment by garethbowen** [comment]
They were made for early 2.x. Mostly they should still be useful, but some content may need to be updated or thrown out.

I'm going to just get this done before they get any more out of date...

**Comment by garethbowen** [comment]
I've reviewed the help pages we had in the translations files. Two were configuration pages which isn't necessary to bundle in app and is documented in medic-docs already. The other two were to do with search and export both of which are being greatly simplified so the pages were either out of date or soon to be.

Given this I've removed the help pages feature and deleted the translation terms from POE. We can add it back when and if we need user documentation.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by alxndrsn** [comment]
Code looks fine.  Where is the actual help content removed?

**Comment by garethbowen** [comment]
The content was still in the translations. I've removed it from POE for all languages so it'll be updated in the translation files next time we export.

**Comment by garethbowen** [comment]
To AT make sure the About page works as expected with no "help" section and no errors.
