### ISSUE TITLE
Error in first launch using mobile app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1897]
Launching the mobile app build 120 with lg.dev running 2640 gets unrecoverable errors. The following are the errors logging in with user `demo`, waiting 5 minutes, then switching to the Contacts tab:
```
Uncaught Error: List not initialised for: contacts inbox.js:32
Database has a global failure DOMError {message: "Uncaught exception in event handler.", name: "AbortError"} inbox.js:14
Error fetching form definitions 
DOMException {message: "The database connection is closing.", name: "InvalidStateError", code: 11, stack: "Error: The database connection is closing.↵    at …dic/_rewrite/static/dist/dependencies.js:7:27271)", INDEX_SIZE_ERR: 1…}
 inbox.js:14
2
Error: The database connection is closing.
```

![image](https://cloud.githubusercontent.com/assets/789512/12957786/825f2a0e-cffc-11e5-835a-6d78a093ac47.png)

**Comment by abbyad** [comment]
I am getting the similar behaviour but slightly different errors using the Chrome 48 browser on the Tecno Y4.

![image](https://cloud.githubusercontent.com/assets/789512/12958492/02ed5896-d000-11e5-92cb-9a9a1c41b7b9.png)

**Comment by abbyad** [comment]
I tested using Chrome 48 on desktop in mobile mode, and was not able to reproduce this issue.

**Comment by alxndrsn** [comment]
This is not happening on `develop`; can I just update `testing` in line with `develop`?

**Comment by alxndrsn** [comment]
...or maybe it just doesn't occur for `admin`s...

**Comment by estellecomment** [comment]
I get it every time when I load the contacts tab, with demo user, BUT only on `1278` branch, not on `develop`.
I'd guess whatever you did on `develop` since then fixed it? `1278` branched off a week ago.

![screen shot 2016-02-16 at 18 01 01](https://cloud.githubusercontent.com/assets/911434/13083935/72964a50-d4d7-11e5-8343-d7755a12ace1.png)

**Comment by alxndrsn** [comment]
Code review is prob best done as part of #1862.
