### ISSUE TITLE
Handle ID collisions better

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#1898]
Currently when we generate non-unique patient IDs we try generating again and recurse infinitely.  This causes load on couchdb and prevents sentinel from processing its queue of changes.

I propose instead we:

1) add a warning to the sentinel log 
2) add a limit to the recursion (20 attempts by default)
3) add an error to the record if we reach the limit and fail to generate a patient ID for the record.

Related https://github.com/medic/medic-projects/issues/94

Also see [ids module](https://github.com/medic/medic-sentinel/blob/master/lib/ids.js#L34) for random number generator code and [registration module](https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L252) to see the problematic recursion.

**Comment by browndav** [comment]
Might be worth looking at something like https://github.com/pid/puid. This same requirement shows up in PID generation (e.g. the Linux kernel) and is pretty well-trod ground IIRC.

**Comment by SCdF** [comment]
Or just UUIDs? Or are they not well supported in the JS world?

**Comment by garethbowen** [comment]
UUIDs would work but this is used for identifying a patient by SMS, so shorter is better.

**Comment by SCdF** [comment]
Ahh, makes sense.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
Resolved by #3230
