### ISSUE TITLE
Not getting the Update modal with restricted user

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1899]
After updating app_settings I am not seeing the Update modal when logged in as a restricted user. 

`Error: Failed to execute 'update' on 'ApplicationCache': there is no application cache to update.`

Here is the console for repeated updates of app_settings:
![image](https://cloud.githubusercontent.com/assets/789512/12968444/00a420a2-d040-11e5-913d-2d4f9fed16f7.png)

Using build 2660

**Comment by garethbowen** [comment]
I suspect a corrupt appcache? We should handle this better, maybe by catching the exception and prompting a refresh.

**Comment by garethbowen** [comment]
This can be reproduced by updating settings in incognito mode.

**Comment by SCdF** [comment]
Just one question for @garethbowen but apart from that looks good
