### ISSUE TITLE
Add test for filter security

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1901]
We make sure in `medic-api` that the filter params that are passed are allowed, based on user credentials and so on. Add tests for this.

**Comment by SCdF** [comment]
See: https://github.com/medic/medic-api/commit/9d78e5cb0b2f755c94f4e34bf3c41fd46060cf72

**Comment by SCdF** [comment]
Hey @garethbowen, can you take a gander at this?

**Comment by garethbowen** [comment]
One small change in comment.

**Comment by SCdF** [comment]
Made the change here: medic/medic-api@b0fe558
