### ISSUE TITLE
Enable erlang replication support

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1902]

**Comment by SCdF** [comment]
See: https://github.com/medic/medic-api/commit/ca92ab1cca5224b5b03864a20c229547c024195a

@garethbowen would you like to take another gander?

**Comment by garethbowen** [comment]
One minor comment.

**Comment by SCdF** [comment]
@garethbowen / @browndav how does medic/medic-api@9928c9e sit with you guys? It's certainly more specific about what it's after.

**Comment by garethbowen** [comment]
I like it. Specific is good in this case.

**Comment by garethbowen** [comment]
Code review: :+1: 
Not sure if this is ready to close, so assigning back to Stefan.
