### ISSUE TITLE
Cannot see the datepicker in contact-edit

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1903]
<img width="825" alt="screen shot 2016-02-11 at 18 09 03" src="https://cloud.githubusercontent.com/assets/191496/12983693/a2a99864-d0ea-11e5-90e3-b88860e06492.png">

**Comment by garethbowen** [comment]
This looks like a regression of #1441

**Comment by sglangevin** [comment]
There is no date-picker at all in contact-edit on mobile, from what I saw. Maybe @abbyad can confirm?

**Comment by abbyad** [comment]
The date field is shown differently in mobile. Depending on the device, it can look like a series of spinners (Tecno Y4) or a calendar (Tecno J5).

**Comment by sglangevin** [comment]
@abbyad I am not able to edit the date on mobile in contact-edit. Sorry if that wasn't clear from my earlier comment. Just wondering if you could reproduce.

**Comment by abbyad** [comment]
Sorry @sglangevin, I misunderstood. I can see it on mobile, but havent been able to run the very latest on my Y4. 

That seems like it is worth opening as a separate issue.

**Comment by alxndrsn** [comment]
@sglangevin @abbyad is this filed as a separate issue?  E.g. #1908?

**Comment by abbyad** [comment]
Yes @alxndrsn, looks like it.
