### ISSUE TITLE
Task icons not showing

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1905]
When switching from 2660 to 2671 the task icons are no longer showing in the tasks tab. Tested logged in as admin and a restricted user.

**Comment by alxndrsn** [comment]
Caused by `LiveList`/#1862

**Comment by alxndrsn** [comment]
The work on branch `1905` demonstrates the problem quite well - now that the task list items are static HTML, they cannot wait for the icons to load... even though this is near-instant.  Allowing deferred resolution of the icons for the task-list-items is the obvious fix, but how to do this reliably is not currently clear to me.

**Comment by alxndrsn** [comment]
Try resolving the icons from the TaskController's initialisation code.

**Comment by garethbowen** [comment]
One comment on the commit.

**Comment by alxndrsn** [comment]
Doing this better filed separately at https://github.com/medic/medic-webapp/issues/1952
