### ISSUE TITLE
Cannot add different birthdates for children in the add family form

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1907]
When choosing to add children while filling out the add family form, changing the birthdate for the first child sets the birthdate for the second child and vice versa. (using 2671)

**Comment by alxndrsn** [comment]
This is likely caused by recent updates to our Enketo dependencies.  I will investigate.

**Comment by alxndrsn** [comment]
This may not be a new bug!  Looks like when enketo duplicates nodes for the `repeat`ed child section, this duplicates our android-datepicker, complete with "unique" id!  Simplest fix would be to find a different way to link the datepicker back to the backing `input` field.

**Comment by SCdF** [comment]
Just a minor comment

**Comment by alxndrsn** [comment]
thanks

**Comment by abbyad** [comment]
Seems to work well now using 2710. I will move to Ready, but @sglangevin feel free to test as well.

**Comment by sglangevin** [comment]
Working well for me too.
