### ISSUE TITLE
Actually enable the Erlang filter

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1910]
See the PR: https://github.com/medic/medic-webapp/pull/1909

The Erlang filter now exists and is being pushed, but the JS filter is still being referenced. This ticket deals with referencing the Erlang filter instead.

**Comment by SCdF** [comment]
Hey @estellecomment can you take a look?

**Comment by estellecomment** [comment]
LGTM! Enable away

**Comment by SCdF** [comment]
Mmmmmmmerged
