### ISSUE TITLE
Postgres needs to support Contacts in a sane way

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#1911]
Generally, contacts is JSON and could be parsed using Postgres JSON stuff into views. This would be broken down into a view for CHPs, a view for patients, a view for this or that other kind of contact.

However, it sounds like LG will need to add extra data for CHPs (if not other sorts of contacts), which would be best facilitated by making and populating a table. This would be node work.

Alternatively, make views of contacts could work if there is a table with primary key of UUID for storing only extra parameters. Then create a secondary view which combines this or that contacts view with the extra table information.

This is unique to 0.6 / LG, so there shouldn't be much for backwards compatibility considerations.

Ideally this is done by Feb 15, but realistically it must be done by Feb 19.

**Comment by btbonval** [comment]
Possibly related to https://github.com/medic/medic-projects/issues/90 but only tangentially

**Comment by browndav** [comment]
Contacts and facilities have associated XML form definitions, so it may be possible to reuse a substantial portion of the form conversion/parsing code to handle contacts as well. May be worth opening up a short discussion on Slack.

**Comment by btbonval** [comment]
@browndav That is good to know. Views are entirely out in that case. We definitely need to discuss the contact situation at some point, because I don't know where to find them in the CouchDB. That's a good step 1 :)

**Comment by btbonval** [comment]
A view to find all contact types in one swoop.
```
CREATE VIEW raw_contacts AS SELECT * FROM lg WHERE data->>'type' IN ('clinic', 'district_hospital', 'health_center', 'person');
```

Fields that appear to be common across most/all contact types, put together in a single table.
```
CREATE TABLE contactview_metadata (_id TEXT PRIMARY KEY, name TEXT, type TEXT, contact TEXT REFERENCES contactview_metadata(_id), notes TEXT, parent TEXT REFERENCES contactview_metadata(_id), reported_date TIMESTAMP);
```

Michael provided me this list of fields that are required based on the work he and Sharon did parsing the beforetime analytics. These must all be included somewhere easy to access. It was noted that `chp.chpcode` is generally used as a pseudo PK, but is not otherwise necessary. It's just a placeholder for some kind of primary key.
```
branch.id
branch.name
branch.country <- Dependent upon Dave/Marc’s answer
branch.branch_status

chp.chpcode
chp.branch_id
chp.first_name
chp.surname
chp.supervisor
chp.vmobile

families.id
families.chpcode
families.created
families.recordstatus
```

There was another email sent linking this comment:
https://github.com/medic/medic-webapp/issues/1929#issue-134487260

I need to examine the above comment and see what (if anything) is missing from the above list of fields.

**Comment by btbonval** [comment]
Contacts appear to use JSON, so I could theoretically use VIEWs instead of TABLEs for this stuff.

If I go that route, I'll need one table with contact.uuid as PK and any custom fields that people need to apply to contacts. Possibly I would make one such table per contact type. Also possibly, I could not bother until there was a need, just so long as the plan exists to handle the situation when it arises. It has been noted that there can/will be CHP fields which are not currently in the CouchDB.

**Comment by btbonval** [comment]
Common contact fields as a view:
```
CREATE VIEW contactview_metadata AS
SELECT data->>'_id' AS uuid, data->>'name' AS name, data->>'type' AS type, data#>>'{contact,_id}' AS contact_uuid, data#>>'{parent,_id}' AS parent_uuid, data->>'notes' AS notes FROM raw_contacts ;
```

**Comment by btbonval** [comment]
Looks like the mappings are:

* district_hospital to branch.
* health_center to CHP area and branch. (latter might be test data or outdated)
* clinic maps to Family.
* person maps to CHP and patient.

### Branch view.

* Country is not stored in the database. Since the instance more or less defines the country, I'd have to create a branch table with uuid PK and a country field which defaults to e.g. Kenya for the Kenya instance. When pulling the table across databases for merging purposes, the correct country would be stored. This strongly implies that more data must be pulled than just the CouchDB contents for a partner who has data across instances.
* id and name are in the general contacts area.
* branch_status isn't apparently to me at present. I suspect it has to do with inactive branches, but I don't know how/if that is tracked in CouchDB. Not obviously part of any branch doc in my dataset.

Although trivial, a view might be:
```
CREATE VIEW contactview_branch AS
SELECT cmd.uuid, cmd.name
FROM contactview_metadata AS cmd
WHERE cmd.type = 'district_hospital';
```

This would need to be updated to include country once a table is put in place.

### CHP

* CHP Area has a reference to the branch id in `parent._id`, but otherwise contains little relevant to the CHP stuff.
* name is one thing, not surname/first name.
* supervisor is being done in some temporary way which I do not have access to in my database. I'll have to check on this later.
* there is phone and alternative phone for a CHP, I guess I'll just supply both.
* while I'm at it, there is a date_of_birth for a CHP.

fields specific for CHP:
```
CREATE VIEW contactview_chp_fields AS 
SELECT
data->>'_id' AS uuid, data->>'phone' AS phone,
data->>'alternative_phone' AS phone2, data->>'date_of_birth' AS date_of_birth,
FROM raw_contacts
WHERE data->>'type' = 'person' AND data#>>'{parent,type}' = 'health_center';
```

join the CHP fields with the CHP info and the CHP Area info:
```
CREATE VIEW contactview_chp AS
SELECT chp.name, chpfields.*, chparea.uuid AS area_uuid,
chparea.parent_uuid AS branch_uuid
FROM contactview_chp_fields AS chpfields
INNER JOIN contactview_metadata AS chp ON (chp.uuid = chpfields.uuid)
INNER JOIN contactview_metadata AS chparea ON (chp.parent_uuid = chparea.uuid);
```
(this is very slow)

### Family

* recordstatus isn't clear to me. A thing indicating active/inactive?
* families aren't directly related to CHPs, so they need to be related through the CHP Area.

this one is otherwise trivial and comes straight out of metadata, though CHP Area is retrieved rather than the CHP.
```
CREATE VIEW contactview_family AS
SELECT cmd.uuid, cmd.name, chp.uuid AS chp_uuid, chp.name AS chp_name
FROM contactview_metadata AS cmd
INNER JOIN contactview_chp AS chp ON (cmd.parent_uuid = chp.area_uuid)
WHERE type = 'clinic';
```
(insanely slow due to dependence on the CHP view, like minutes of time)

### other notes

Materialized views almost seem required at very least for the chp view. This dataset is pretty small, but the operations on that take a long time. Adding a few b-trees on this or that would speed this all up tremendously. It might be worth trying to optimize with some JSON indices first, but I'm not sure that's where the slowness comes from. With all these UUID strings floating around, I'd love to toss b-trees on each and every one of them.

**Comment by btbonval** [comment]
Forgot reported date inside of family view.

**Comment by btbonval** [comment]
I'm missing the concept of head of household. It's like CHP in many ways internally, but it is attached to a Family rather than an Area.

Note: I will treat "head of household", "mother", and "pregnant woman" stated below to be the same person for contact phone number purposes. See this comment: https://github.com/medic/medic-webapp/issues/2020#issuecomment-192538608

Field specific for head of household. HoH is defined as the Contact for a Family so far as I can tell.
```
CREATE VIEW contactview_hoh_fields AS 
SELECT data->>'_id' AS uuid, data->>'phone' AS phone, data->>'alternative_phone' AS phone2
FROM raw_contacts
WHERE data->>'type' = 'person'
AND data->>'_id' IN (SELECT contact_uuid FROM contactview_metadata WHERE type = 'clinic');
```

Combine with metadata for head of household view:
```
CREATE VIEW contactview_hoh AS
SELECT hoh.name, hohfields.*, hoh.parent_uuid AS family_uuid
FROM contactview_hoh_fields AS hohfields
INNER JOIN contactview_metadata AS hoh ON (hoh.uuid = hohfields.uuid);
```

**Comment by btbonval** [comment]
Let's see how well we can accomplish these: https://github.com/medic/medic-webapp/issues/1929#issue-134487260

### Family registration: phone number of head of household

```
SELECT phone, phone2
FROM contactview_hof;
```

### Pregnancy registration: phone number of pregnant woman, EDD

```
SELECT hof.phone
FROM formview_pregnancy AS preg
INNER JOIN contactview_metadata AS ppl ON (preg."outputs/patient_id" = ppl.uuid)
INNER JOIN contactview_hof AS hof ON (ppl.parent_uuid = hof.family_uuid);
```

### Newborn visit 1 (delivery): phone number of mother, DOB of child

```
SELECT hof.phone, delivery."outputs/delivery_date" AS dob
FROM formview_postnatal_care AS delivery
INNER JOIN contactview_metadata AS ppl ON (delivery."outputs/patient_id" = ppl.uuid)
INNER JOIN contactview_hof AS hof ON (ppl.parent_uuid = hof.family_uuid);
```

### The rest

```
    Treatment-only: diagnosis, phone number of head of household, age of child
    Treat and refer: diagnosis, phone number of head of household, age of child
    Refer only: diagnosis, phone number of head of household, age of child
    Referral follow-up: diagnosis, phone number of head of household, whether follow-up was done in person or over the phone
```

More of the same. Grab fields out of the desired form, possibly with a WHERE clause looking for particular form fields (e.g. referral in a assessment form or not?), then some relations to grab the head of family phone number.

**Comment by btbonval** [comment]
This might be done. It needs to be reviewed by analytics stakeholders like Astrea and Michael and stuff to know for sure. I'll call that "code review" and close the ticket.

If a devver picks this up by accident and feels code review is inappropriate, do with it as you will.

**Comment by btbonval** [comment]
the JOINs across views are fast enough for `contactview_metadata` because I made that a materialized view, but Michael is seeing a need to join many more tables together in one go. It runs extremely slow.

Materialize all the things! :guy with mop:

```
CREATE MATERIALIZED VIEW contactview_branch AS
SELECT cmd.uuid, cmd.name
FROM contactview_metadata AS cmd
WHERE cmd.type = 'district_hospital';
CREATE INDEX contactview_branch_uuid ON contactview_branch (uuid);

CREATE MATERIALIZED VIEW contactview_hof AS
SELECT hof.name, hoffields.*, hof.parent_uuid AS family_uuid
FROM contactview_hof_fields AS hoffields
INNER JOIN contactview_metadata AS hof ON (hof.uuid = hoffields.uuid);
CREATE INDEX contactview_hof_uuid ON contactview_hof (uuid);

CREATE MATERIALIZED VIEW contactview_family AS
SELECT cmd.uuid, cmd.name, chp.uuid AS chp_uuid, cmd.reported AS created
FROM contactview_metadata AS cmd
INNER JOIN contactview_chp AS chp ON (cmd.parent_uuid = chp.area_uuid)
WHERE type = 'clinic';
CREATE INDEX contactview_family_uuid ON contactview_family (uuid);
```

**Comment by browndav** [comment]
Can you post `EXPLAIN ANALYZE` output for the slow-running query?

**Comment by btbonval** [comment]
I already materialized all the views and posted. Definitely solved that problem and many other potential problems.

I can revert and run more in depth analysis if you'd like, but Astrea needs this last week.

**Comment by browndav** [comment]
Just a suggestion; it'll report on index usage, which is important even for materialized views.

**Comment by btbonval** [comment]
The only indexes were on contactview_metadata, so I already know the usage for indexes: any join with metadata used it, and other joins did not.

**Comment by btbonval** [comment]
I had to materialize views so I could add indexes.

**Comment by browndav** [comment]
Yeah, materialized is fine; if the joins are slow, though, you may just need to add or rework existing indexes (or take a look at clustering and see if that'll produce any gain).

**Comment by btbonval** [comment]
The only real table is the one with all the JSON in it. The JSON indexes are extremely limited in scope.

All joins are effectively across views in this database. Now that I've indexed a ton of stuff using materialized views, I will definitely be analyzing to determine slow points in the future.

It also means I need to write software to keep the materialized views refreshed. I'll add that to the postgres adapter soon.

**Comment by garethbowen** [comment]
Moving to acceptance testing because this has been closed for ages.

**Comment by btbonval** [comment]
Oh, uhm, this is assigned to me for acceptance testing. Contacts handling definitely works in production for at least one project. So I think that means I'm good to switch to Ready. Maybe I should change it to Released since it is in production, but the adapter doesn't have quite the same workflow as the webapp.
