### ISSUE TITLE
Tab stops are broken for enketo forms on desktop

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1916]
Issues:

* [x] _New Family_: tab on _phone number_ field does not change field.  **This may also be a problem on mobile.**
* [x] _New Family_: shift-tab on _Notes_ field changes page, instead of going to _Name_ field
* [x] _New Family_: tab on _Names_ field of child does not shift focus; generally a bit messed up in repeaters

When fixing, be careful not to re-break them on android.

**Comment by alxndrsn** [comment]
N.B. a better fix would be to skip the key handler when not on android.

**Comment by estellecomment** [comment]
So, you did a bunch of things, and then reverted them, right? It's a bit painful for the reviewer, having to go through 5 commits separately.

Next time this happens, could you provide a single diff view? My best solution for this is a compare view (https://github.com/medic/medic-webapp/compare/27d07352d5672aa280447ccda1091566e15980e2...167a812e2afc6be62d6b3424fe527cf9b9dc9a44), but it includes irrelevant commits too, so a comment saying which files are relevant would be helpful too.

Code looks good.
