### ISSUE TITLE
Let administrators choose which version of the app to update to

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1918]
Through the dashboard administrators can see when an update is available and click to update to the latest released version. However there is no way to choose a different version to update to. For example if an instance is on 0.1.0 and the latest is 2.0.0 there is no way for us to distribute the service pack 0.1.1. The only way to get the patch is to update to 2.0.0 which would require much testing and training and may not even be backwards compatible.

Update or replace dashboard version management so we able to distribute patches and features to old versions of the software.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
Solved in horticulturalist.
