### ISSUE TITLE
Check if changing the pouchdb `batch_size` can have positive effects on replication speed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1920]
This is horribly slow now for `demo` on the dev deployment.  Tweak the settings and see if it can be improved at all.

**Comment by garethbowen** [comment]
With replication performance improvements (erlang, removing audit docs, etc) it probably makes sense to raise the batch size again. Serious benchmarking required to prove that any change actually improves performance.

**Comment by alxndrsn** [comment]
:+1: can't wait for the audit change

**Comment by SCdF** [comment]
It's a balance right? We knew it would take longer to run in total but we'd be more likely to make progress with a smaller batch size. Perhaps the definition of done for this ticket should be:
 - Define a maximum amount of time we're willing for replication to take before we get a result back
 - Define a dataset we presume to accurate (eg maybe lg.dev)
 - Add some logging code to log these amounts out, and get an understanding of what they are right now
 - Wait until audit is done and then check again.

_Alternatively_, if someone wants to _really_ learn Erlang, we could add a feature to couch which returns results after N results of after M seconds, whichever comes first.

**Comment by estellecomment** [comment]
Having a batch size of 1 generates a lot more requests, looks like for each doc there's a request to
[_revs_diff](https://cloud.githubusercontent.com/assets/911434/13256533/5aaa0b10-da4b-11e5-868e-7ac44ae0e7fa.png) and one to the [replication status doc](https://cloud.githubusercontent.com/assets/911434/13256584/94581488-da4b-11e5-85bc-1893779eb5ae.png).

**Comment by alxndrsn** [comment]
@estellecomment I predict it would generate around ten times as many requests ;-)

**Comment by garethbowen** [comment]
Is this enough evidence to use the default batch size or is there something more we should test? A batch size of 1 is painful on lg.dev with a good connection  :/

**Comment by alxndrsn** [comment]
@garethbowen which build are you testing on lg.dev with?  batch_size should not be 1 on there at the moment.

**Comment by garethbowen** [comment]
It doesn't matter what version I'm using. What I said was "a batch size of 1 is painful... with a good connection". Do we need any more information or are we happy to close this and go with the default batch size?

**Comment by alxndrsn** [comment]
It doesn't matter which version you're using if the version you're using actually has batch_size set to 1.  I've found either batch_size painful, so I was wondering if your painful experience was definitely with batch_size set to 1.

**Comment by garethbowen** [comment]
It was.

**Comment by SCdF** [comment]
In terms of speed I've added some logging that logs out timings whenever the `paused` event is hit, which is whenever a batch returns (no I don't know why, Pouch is weird).

Unfortunately there is no way to tell when you're _done_ done (that I'm aware of), so I'm just logging each time, but you can just wait awhile and then check the last one.

As a reference, I tested this on my local machine (grain of salt and all that) and I got 124 seconds for no specified batch size, 339 seconds with a batch_size of 1, and 49 seconds with an effectively infinite (65536) batch size.

**Comment by estellecomment** [comment]
With the new code from https://github.com/medic/medic-webapp/commit/5dcdf5f96f27912ed95268895056220ef82c6f3e, now you actually know when it's done!
Tested on Tecno, on MTN network, in Bugolobi mall, with user 2muk029

Batch size 1 : gave up at 1410s (upwards repl was also going on, and firing at each incoming downwards change, so that might make it slower too)
Batch size 10 : 396.625s - 396.853s - 378.295s
Batch size default (100 for pouch) : **206.629s**
Batch size 1000 : 219.821s 215.607s 215.493s 

So the default looks good. 

For connectivity, if the network is spotty then the `_changes` requests could break. Apart from that, the download of docs is done one-by-one, so nothing we can change there.

**Comment by garethbowen** [comment]
> the default looks good

Closing.
