### ISSUE TITLE
Tasks disappearing after closing and reopening and during new task creation

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1923]
My tasks disappear (I see no tasks found) after closing, waiting a while then reopening the app. I also saw a similar issue after submitting an Add Family form where I indicated that the primary caregiver was pregnant - navigating to the Tasks tab I see no tasks found. Clicking Update from the about page to reload the app resolves this issue. Seen on version 2710.

**Comment by sglangevin** [comment]
Did some further testing and this seems to apply only to the register pregnancy task that is created after submitting the add family form. Follow-ups for assessments are working as expected.

**Comment by alxndrsn** [comment]
Icons missing due to #1905

**Comment by alxndrsn** [comment]
Have just created 10 new families with a pregnant head of family and could not recreate the issue.

**Comment by alxndrsn** [comment]
Similarly have just opened 50 new windows on Chrome desktop (simultaneously) and all loaded tasks fine (with a noticeable delay for some of them).  Please give more info on the environment in which you see the reported issue.

N.B. running against alpha.dev, build 2803

**Comment by sglangevin** [comment]
TBH, it was an old build, so I'm not sure I can provide more info. I haven't seen this issue again and task icons are now working so I would say we can close this. I do still see issues loading tasks on first run, but that is a different issue than this one.

**Comment by alxndrsn** [comment]
:+1:

Please give more details here or elsewhere of the other first-run problems.

**Comment by garethbowen** [comment]
I'm seeing this on lg.dev. No tasks shown at all on first load.

**Comment by sglangevin** [comment]
@garethbowen I've seen this consistently on first load - no tasks and no data in targets. I haven't seen any useful error messages in the console and clicking Update in the about page always solves the issue.

**Comment by garethbowen** [comment]
The Settings listener isn't firing on first load even after the settings have replicated.

**Comment by garethbowen** [comment]
This is hiding a much bigger issue to do with how the Changes listener works. I'll create a new issue for that and make sure the fix resolves this issue too.

**Comment by garethbowen** [comment]
This is now working for me. Moving straight to Acceptance Testing because the Code Review will be done in #1986
