### ISSUE TITLE
No contacts found - except for the ones above

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1924]
The contacts list shows "no contacts found" even if there were contacts found.

![no-contacts-found](https://cloud.githubusercontent.com/assets/2064938/13126191/74163f86-d62e-11e5-9e21-b4c7cbce16d9.png)

**Comment by garethbowen** [comment]
@alxndrsn Possibly due to the live list change?

**Comment by alxndrsn** [comment]
What's it meant to say?

**Comment by garethbowen** [comment]
Either nothing at all, or "No more contacts" (or similar) if we're at the end of the pagination. "No contacts found" should only show when the search is complete with 0 contacts returned.

This also affects Reports and Messages tabs (and probably Tasks too).

**Comment by alxndrsn** [comment]
Surprising that this should happen in _Messages_.

**Comment by alxndrsn** [comment]
Fixed for reports & contacts; could not recreate for messages.

**Comment by garethbowen** [comment]
Looks good. Good call on changing the variable name, eg: `$scope.contacts` -> `$scope.hasContacts`
