### ISSUE TITLE
Show certain forms in History based on the type of user who is logged in

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1925]
Currently all forms are available for all users in the History tab which means that, for example, a CHP could submit a Branch Manager form. Need to limit which forms are available based on the type of user so that CHPs cannot access Branch Manager forms.

**Comment by abbyad** [comment]
We currently have a "context" condition for showing the form in a Contacts tab profile based on the doc of the contact in question. We could extend that concept and have a "user" condition that would be fed the logged in user's doc and can be used in a condition to determine if it is shown in the Reports/History tab.

**Comment by garethbowen** [comment]
I've made a few changes to the way a form context is tested which will let configurers have more control over which forms are shown where...

1. Any forms that use an expression must be reconfigured to assign the expression to an `expression` property of the context map, eg: `context: { expression: 'contact.name === "frank"' }`
2. User permissions are now checked so you can provide a permission property, eg: `context: { permission: [ 'national_admin', 'district_admin' ] },`. This will make the form available to all national and district admins.
3. The user is available in the expression logic, for example: `context: { expression: 'user.name === "Frank"' }`

This should give enough flexibility to do the above.

**Comment by garethbowen** [comment]
PR linked above.

**Comment by alxndrsn** [comment]
Looks good; couple of minor comments.

**Comment by alxndrsn** [comment]
@garethbowen you may want to review my latter changes.  They seem trivial, but affect behaviour a surprising amount.

**Comment by alxndrsn** [comment]
@abbyad @garethbowen re-worked the simple type context filter, as it can't cope with `{ place: true, person: true }` (and couldn't in the previous revision either).  I've added more comprehensive unit tests; @marc please look at the test cases for [`filter to place forms`](https://github.com/medic/medic-webapp/blob/1eda54070e588163f4439cce49970eb60c860dd9/tests/karma/unit/services/xml-forms.js#L195) and [`filter to person forms`](https://github.com/medic/medic-webapp/blob/1eda54070e588163f4439cce49970eb60c860dd9/tests/karma/unit/services/xml-forms.js#L115) and make sure they tally with your expectations.

**Comment by garethbowen** [comment]
Looks good.

**Comment by abbyad** [comment]
It is not exactly as I expected but it does make sense!

**Comment by abbyad** [comment]
Works well, moving to Ready.
