### ISSUE TITLE
Reset Filters not working on mobile

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1927]
Try as I might I just can't get the Reset Filters button to work on mobile. I'm not sure if the click target is obscured, too small, or if clicking it does nothing. Clearing the filter and hitting search does nothing either, and switching tabs doesn't clear the filters, so once you search for something you are stuck till you refresh the app.

![reset-filters](https://cloud.githubusercontent.com/assets/2064938/13127361/d1370f4c-d633-11e5-97db-54131f389a63.png)

There's nothing logged in the console. It works as expected on desktop.

**Comment by sglangevin** [comment]
@garethbowen this is currently working on my Y4, version 2710. My reset filters icon has moved over to the right side of the screen and is easier to press.

**Comment by alxndrsn** [comment]
This screenshot doesn't appear to be taken on a mobile.  Is the bug occurring on all thin screens, or only on specific mobile phones?  If the latter, please state which phones you have tested on.

**Comment by garethbowen** [comment]
Yes I took the screenshot on my desktop so it'd be obvious what I was talking about. I tested on the Y4.

**Comment by alxndrsn** [comment]
@garethbowen @sglangevin what user were you logged in as?  Filters display differently for admins and normal users, so this may have an effect.

**Comment by garethbowen** [comment]
Logged in as a restricted user.

**Comment by alxndrsn** [comment]
@garethbowen can you check on lg.dev?  this is what @sglangevin is likely testing on, and code may be different from what you're testing against.

**Comment by sglangevin** [comment]
Yes, I was testing on lg.dev with a restricted user

On Wed, Feb 17, 2016 at 2:49 PM, Alex Anderson <notifications@github.com>
wrote:

> @garethbowen <https://github.com/garethbowen> can you check on lg.dev?
> this is what @sglangevin <https://github.com/sglangevin> is likely
> testing on, and code may be different from what you're testing against.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/1927#issuecomment-185444995>
> .
>



-- 
Sharon Langevin | DIY Lead, Mobile App Deployment Manager
Medic Mobile
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=6911deb493&e=c511575255>
 | @Medic
<http://medicmobile.us8.list-manage2.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=95a573475f&e=c511575255>
 | Facebook
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=7282d6a45d&e=c511575255>


Join our community. Sign up for Medic Mobile's newsletter.
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>

**Comment by garethbowen** [comment]
I tested on 2721, so it could have been added in the last 11 alpha releases.

**Comment by garethbowen** [comment]
Closing as I can no longer reproduce this issue. Will reopen if it occurs again.
