### ISSUE TITLE
Strategy for allowing external access to the Postgres DB

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1929]
Need to be able to export info to be fed into a 3rd-party SMS system that provides follow up directly to families. Broken down by different SMS services:
- Family registration: phone number of head of household
- Pregnancy registration: phone number of pregnant woman, EDD
- Newborn visit 1 (delivery): phone number of mother, DOB of child
- Treatment-only: diagnosis, phone number of head of household, age of child
- Treat and refer: diagnosis, phone number of head of household, age of child
- Refer only: diagnosis, phone number of head of household, age of child
- Referral follow-up: diagnosis, phone number of head of household, whether follow-up was done in person or over the phone

**Comment by browndav** [comment]
Waiting on SSH public keys from LG stakeholders.

**Comment by sglangevin** [comment]
@browndav I can help unblock this, let me check in with LG and see where I get.

**Comment by browndav** [comment]
Marc just sent a note today.

**Comment by browndav** [comment]
SSH key provided, unblocked. To do:

- [ ] Add account for LG stakeholder
- [ ] Ensure account can access all relevant objects and is read-only
- [ ] Distribute credentials to LG stakeholder with password change instructions

**Comment by browndav** [comment]
Done; temporary credentials sent via e-mail. Moving to acceptance testing.
