### ISSUE TITLE
Display format for phone numbers

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1930]
When you type in : 06 77 88 99 00 (local format), the number is saved as +33677889900 (international format). From then on, it's displayed in international format.

Adding a display format would be convenient (if all the numbers are in your home country, it's irritating to see international formats for nothing), and as mentioned by @abbyad in #1770 : 
"In the field-test, there is a confirmation page displaying the phone number to make sure it has been entered correctly. When a user enters the phone number without the country code, they then see it with the country code in the confirmation page. They may be confused to confirm a different looking number than the one they typed out."

**Comment by garethbowen** [comment]
This is now configurable. CR done with #2914.
