### ISSUE TITLE
App doesn't handle authentication invalidating over time gracefully

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1931]
CouchDB authentication is only valid for a (configurable) small amount of time, which is refreshed on every request. I think the default is 10 minutes. If you leave your phone / browser for awhile and come back you will have lost that, and will need to reauthenticate.

Here for example. I opened the app on mah tecno, and then left it for 30 min or so. I then `grunt dev`'d to force a design doc change:

![image](https://cloud.githubusercontent.com/assets/583851/13142900/2877392c-d638-11e5-9077-e953b0f3e175.png)

The most critical upshot of this is that replication can silently fail (in both directions) once you get into this state. For example, if I then try to change a contact on Cptn. Tecno. Everything looks fine on the phone, but in the log I get.

![image](https://cloud.githubusercontent.com/assets/583851/13142939/6af750f2-d638-11e5-9eb1-c53d4481f84a.png)

There are two obvious solutions: 
 - Have the couchdb authentication timeout as effectively infinite. I believe this may be what is happening with some clients now. It's not ideal.
 - Have a log in modal that we pop up and use to refresh credentials
 - Tell the user they have been logged out and then force a a page refresh

**Comment by alxndrsn** [comment]
@SCdF should this be marked **`Priority`**?

**Comment by browndav** [comment]
Additional comments from he 2/22 iteration planning call: We should check what the session timeout is in production. Also, the session timeout is bumped when a request is made, so the timeout doesn't necessarily need to be infinite (just longer than the longest period of user inactivity that we anticipate).

**Comment by SCdF** [comment]
IMO this is super important, but I've been placated before by being told that in production people's creds never time out.

**Comment by SCdF** [comment]
We should at least fix it so that when you're online and you lose auth it redirects you to the login page. We shouldn't log you out while you're offline though, since there would be no way for you to log back in again.

A future thing to think about would be to attach this to whatever sync status we end up building.

**Comment by SCdF** [comment]
I've made some changes which redirects users to the login page when some interactions return a HTTP 401. One of the potential downsides of this is that they can get silently logged out while on a network, and they must be on a network to log back in. We may want to modify this to instead of instantly logging out, prompt the user if they wish to, or do something more usefully stateful so that the user can choose to reauthenticate later when it suits them.

**Comment by SCdF** [comment]
Hey @garethbowen would you like to take a look. I'm still testing and generally playing with it, but it's worth you checking out.

**Comment by SCdF** [comment]
Two more places to handle:
 - If bootstrapping fails due to 401 https://github.com/medic/medic-webapp/blob/develop/static/js/app.js#L450
 - If the app cache fails due to 401:
![image](https://cloud.githubusercontent.com/assets/583851/13315641/d4959418-dba3-11e5-94ea-2426d4e8c60a.png)
and so on

**Comment by SCdF** [comment]
Also:
- [ ] restarting couch causes the following pouch issues:

![image](https://cloud.githubusercontent.com/assets/583851/13317319/a22deab2-dbac-11e5-9061-cad6c7c4b9ff.png)
![image](https://cloud.githubusercontent.com/assets/583851/13317327/ab59d66e-dbac-11e5-9c4f-abba3561c6e4.png)

**Comment by SCdF** [comment]
- [ ] In the above situation, just refreshing the page (where the current URL is http://localhost:5988/medic/_design/medic/_rewrite#/tasks/ ) just returns a raw 401:
![image](https://cloud.githubusercontent.com/assets/583851/13317378/f1e3d788-dbac-11e5-9c10-db50d5856189.png)

Hopefully can fix through `medic-api` redirection.

**Comment by SCdF** [comment]
I'm not able to work out how I got the application cache to 401 like in the screenshot above, but I've added some logging so hopefully we'll be able to catch it at some point and write a case for it. You'd think I'd be able to read the documentation for that event and be able to write code without having to generate the error manually, but there you go.

**Comment by estellecomment** [comment]
I got a giant 401 situation with `admin`. The first 401 is our code is there : 
https://github.com/medic/medic-webapp/blob/9da1a7efedcc4d6295390d1162d314c4e6f07c54/static/js/services/db-view.js#L29

Another one is there : 
https://github.com/medic/medic-webapp/blob/0cf0d9f136fbf359403a1300a17d40fbe693cc7f/static/js/controllers/inbox.js#L400

**Comment by SCdF** [comment]
I've raised #1978 to deal with the admin use case, since we realised that this is an entirely separate bag of cats.

**Comment by garethbowen** [comment]
I've reviewed up to this point and it looks good (one minor comment on https://github.com/medic/medic-webapp/commit/195119401d0af2cf36d1c787099ef36d7bfff750 ). Submit it for review again once the rest is done, or split off other issues for the outstanding work.

**Comment by SCdF** [comment]
Hey @estellecomment I've added this: https://github.com/medic/medic-webapp/commit/9b598173d4e35aeeba2179761083088a4e7bd745

Can you review and get back to me? I think this will be the last change on this ticket, I'm not able to reproduce the other edge cases so easily.

**Comment by estellecomment** [comment]
LGTM, one comment on 9b59817

**Comment by SCdF** [comment]
So I've caught what I'm pretty sure is the vast majority of these and closed them up. Note that there are a few that could in theory occur but I'm unable to write code for because the documentation isn't good enough to do it without being able to reproduce it. I've added logging to those situations. Note also that this only covers restricted (ie offline-first) users. These users are restricted to a manageable subset of network activity. I have raised a ticket (#1978) to deal with admin users, who need a more general approach.

**Comment by alxndrsn** [comment]
Does this code need reviewing?

**Comment by SCdF** [comment]
Hey @estellecomment can you review the last two commits, https://github.com/medic/medic-webapp/commit/cd037093cef43cbaae4f3119bfb2985bedd678cc and https://github.com/medic/medic-webapp/commit/f5024d4380d7df73e427ab21260ccc656f717889

**Comment by estellecomment** [comment]
LGTM! Thanks.
