### ISSUE TITLE
Do not allow CHPs to delete Reports

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1934]
CHPs shouldn't be allowed to delete any forms. They should be able to edit only. The delete button should be grayed out on the history page when a CHP is viewing a previously submitted form.

**Comment by alxndrsn** [comment]
Pedantic question alert!  Shouldn't be allowed to delete forms, or delete reports (form submissions)?

**Comment by sglangevin** [comment]
Forms! Sorry.

**Comment by katanu** [comment]
Maybe the edit function would benefit with more exploration. I am not sure if the CHPs should be allowed to edit a historical record at all or tie it to a time limit and specific fields for which an edition can be made is better. Some editions might make the historical treatment a new assessment with different results and tasks for that patient. May be it is worth the while to look at when and why the CHPs would want to edit an historical record.

**Comment by sglangevin** [comment]
This appears to be a duplicate of #1851 - closing.
