### ISSUE TITLE
Simplify medic specific XForm notation

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1938]
The goal of this issue is to simplify the customization needed to make XForms work within the webapp. We currently use some special notation within the XForm to make it work well with the webapp (eg to assign the form to a contact, or to display only certain fields in the Reports/History tab). 

Here is a proposal for some of the changes, which may help increase performance by reducing field duplication, reduce time to build forms, and make the data more easily accessible for exports as well as for calculations in task/target rules.

### `inputs` group
The fields in this group are currently populated automatically when the form is opened from a Contacts tab profile. Similarly, when form is opened from a Task the fields are populated by the task rule. When opening the form from Reports/History tab we cannot use the same inputs group and also hide it when it is prepopulated. The workaround includes having the patient or place info being selected in a separate group if not already populated, then coalescing these in the outputs. Eg:
```xml
          <inputs>
            <patient>
              <_id/>
              <name/>
              <date_of_birth/>
            </patient>
          </inputs>
          <g_inputs>
            <_id/>
            <name/>
            <date_of_birth/>
          </g_inputs>
          <outputs>
            <patient_id/>
            <patient_name/>
            <patient_dob/>
            ...
          </outputs>
```
The suggestion here would be to use a `inputs/source` field so we can avoid the duplication and simplify the form creation.  `inputs/source` would be one of `contact`, `task`, `user`, with the later as the default if it is not set programmatically by via a profile or task. The resulting data model would be:
```xml
          <inputs>
            <source>user</source>
            <patient>
              <_id/>
              <name/>
              <date_of_birth/>
            </patient>
          </inputs>
```
Aside from populating the source field we would need to check the `inputs/patient/_id` instead of `outputs/patient_id` when associating the report to the person. 

### Person, not Patient
We could also use this opportunity to use the more generic `person` rather than `patient` since reports are not always about patients (eg a report may be about a CHW as completed by their manager).

### Make all the fields accessible
We should assign all the field to json, not just the outputs section as done [here](https://github.com/medic/medic-webapp/blob/167a812e2afc6be62d6b3424fe527cf9b9dc9a44/static/js/services/enketo.js#L233)

Right now we need to duplicate fields into the `outputs` section to have it in the `doc.fields`, which determines which elements are shown in the Reports/History tab, which are accessible programmatically from rules, and which are available for export. This can reduce performance due to extra fields, and makes it difficult to access the data that was initially omitted from the `outputs`. 

By default we would show all fields, and hide those that we don't want to show. This is currently possible with `tag="hidden"` in data model (https://github.com/medic/medic-webapp/issues/1476). Nested fields are not shown elegantly right now because all the subfields are shown as JSON, but we can chose to hide these fields until we display them better via https://github.com/medic/medic-webapp/issues/1473.

**Comment by btbonval** [comment]
It might be nice to reflect the name of the input sources, because "input" and "g_input" are mysterious and a bit confusing because the fields are also inputs. Same for "outputs": what is being output to? That whatever is the target would probably be a better label.

As I mentioned in slack, I'm not sure how much of a win moving to JSON is. The form definitions (`type:form`)would still be base64 encoded XML, so I still need XML parsing capability and it will already be written for the trial's form reports (`type:data_record`) by the time this change is made. However, more JSON is more consistent, so I generally think it's a good idea.

**Comment by btbonval** [comment]
In order to make the best use of JSON, we would need to include the form's version in JSON as well.

**Comment by abbyad** [comment]
@btbonval I agree with the naming suggestions, and that's why the proposal made in this issue would remove `g_inputs` and `outputs` altogether.

As for the benefit of copying all values to JSON, it would make it possible to access any field from a Task or Target rule. Otherwise you are limited to the ones put in `outputs` when the form was created. It would also prevent duplication of fields, hopefully improving performance by reducing the number of elements and calculations.

**Comment by btbonval** [comment]
@abbyad Ah, I must not be reading this issue correctly. It still isn't obvious to me where it is recommended that `g_inputs` and `outputs` go away. I also don't know how this helps pull in Tasks.

Here's what I do know: that all sounds amazing! I'm in favor.

**Comment by abbyad** [comment]
There was a lot in that original post, so to clarify:

- This won't help pull in Tasks, but helps task or target rules use any form data
- Wasn't explicit, but removing `<g_inputs>` would be possible once we make use of a `inputs/source` field.
- We would stop using <outputs> when we "assign all the field to json, not just the outputs section"

We will update the form creation how to guide accordingly once this is implemented.

**Comment by btbonval** [comment]
Gotcha. Those bullet points make sense. I think you were missing `<outputs>` in the last bullet.

**Comment by abbyad** [comment]
Interesting... html gets rendered or hidden if not in code block. Updated comment.

**Comment by btbonval** [comment]
Problem solved. Yeah, I think that's true. It is weird they don't escape HTML since they're using Markdown, but also, Markdown is a superset of HTML so ... maybe it's a bit too true to Markdown?

**Comment by abbyad** [comment]
I'm creating forms with the new format in a branch. Assigning to @alxndrsn for the medic-webapp side of things.

**Comment by alxndrsn** [comment]
# TODO

- [ ] rename `patient` to `person`
- [ ] remove `g_inputs` references from code (should these be remapped to another name?)

@abbyad can you think of any other updates which need to happen code-side?

**Comment by abbyad** [comment]
We would need to use `/inputs/person/_id` instead of `/outputs/patient_id` to determine if the form is about the person. Similar for place.

**Comment by alxndrsn** [comment]
Have a go on https://github.com/medic/medic-webapp/tree/1938

**Comment by abbyad** [comment]
One aspect missing from the todo list: 
- set `inputs/source` as `contact` when populated from contact tab. 

The other sources (`user` and `task`) are set by the form default or from the task rule so doesn't need any webapp code changes.

**Comment by abbyad** [comment]
Sorry, also seems to be missing a todo about assigning the contact's doc to the `inputs/contact`.

**Comment by alxndrsn** [comment]
:+1: have updated the list

**Comment by alxndrsn** [comment]
Fixed the 2 new issues on the TODO list.  @abbyad please review

**Comment by abbyad** [comment]
Good progress @alxndrsn, but noticed two issues:
- When accessing form from Reports/History tab, the dropdown populates the _id field, but not the other contact fields. When accessing the same form from a contact page the full set of `contact` group fields are populated.
- Submitted forms are no longer associated to the contact. Tested with the old and new format and neither gets associated.

**Comment by alxndrsn** [comment]
Investigation:

1. this is also occurring on `develop`, so should be filed as a separate bug
2. in _Add Family_, `/inputs/user/facility_id` is set and looks like `doc.parent` receives the correct value.  `assessment` form does not have a `/inputs/user` section, but is assigned to the relevant contact when triggered via the `ContactsContentCtrl`:
<img width="929" alt="screen shot 2016-02-26 at 08 13 45" src="https://cloud.githubusercontent.com/assets/191496/13345666/fa217540-dc60-11e5-98cf-c8a331e1438d.png">
Filling the `assessment` form direct from the _History_ tab associates the contact by ID only (as expected due to **1**).
3. Looks like the task is setting `action.place`:
<img width="1055" alt="screen shot 2016-02-26 at 08 21 04" src="https://cloud.githubusercontent.com/assets/191496/13345803/06f83ed8-dc62-11e5-8101-aa29bea18fbc.png">
This seems to work fine for `family_survey`:
<img width="582" alt="screen shot 2016-02-26 at 08 25 08" src="https://cloud.githubusercontent.com/assets/191496/13345846/786611e4-dc62-11e5-9749-cc7ce465d785.png">

**Comment by abbyad** [comment]
As suspected, **3** was due to a missing bit of configuration. The contact assignment had been fixed in the task rules for `patient` but not in the one form that required the update to`place`.

It is odd that you saw that working for `family_survey` because that is the one that I would have expected _not_ to assign `contact` from the task as the contact was still being assigned to `place`, as shown in the debug screenshot. Is that last screenshot for a submission from a task?

**Comment by abbyad** [comment]
Issue **2** was a non-issue... I was not noticing the forms on the profile, but looking at it now they are there.

Seems as though the only remaining problem isn't related to this issue at all as we can reproduce it on lg.app and lg.dev.

**Comment by garethbowen** [comment]
This is really difficult to review. Firstly it looks like you've force pushed to modify your commit? If so, it's a really bad idea to force push remotely as it can seriously break other devs. Secondly it would've been much nicer as a PR - please consider this in future.

As far as I can tell, this is fine.

**Comment by garethbowen** [comment]
@alxndrsn Can you please delete the 1938 branch assuming this is all merged now?

**Comment by alxndrsn** [comment]
Apologies, I'd assumed a single commit would be easier to review than multiple work-in-progress steps.

**Comment by abbyad** [comment]
This is working well so far. Moving to Ready.

**Comment by garethbowen** [comment]
@alxndrsn Good thinking. Unfortunately GitHub doesn't render them 4 force pushed commits as a single commit - it renders them as 4 individual commits. It wasn't immediately clear to me why there were 4 commits that looked the same. In retrospect individual commits would have been clearer because GitHub would have rendered them better. Alternatively a PR would have been awesome.
