### ISSUE TITLE
Verify/Unverify button falls out of sync with left pane after being clicked

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1939]
On build 2710 of v0.6: clicking the `Verify` button correctly changes the verified/not-verified indicator in the left pane, but fails to change the button in the right pane from `Verify` to `Unverify`. Expected result: the `Unverify` button becomes immediately available.

The reverse is also true:
<img width="1021" alt="verify-unverify-sync-20160219" src="https://cloud.githubusercontent.com/assets/763977/13188328/b3032d62-d705-11e5-9d3c-d5f95afe45ec.png">

It's been pointed out that the verify/unverify feature isn't being actively used by any partners, so I'd also be open to proposals for removing the feature altogether (and possibly replacing it with a tagging/labelling feature later on).

**Comment by sglangevin** [comment]
@browndav it's funny this issue is coming up because we were talking earlier this week about the potential for using the verify feature for cases where CHP managers are more heavily involved in checking up on CHPs, i.e. they do home visits to verify the information submitted by a CHP.

**Comment by garethbowen** [comment]
Appears to be working now.
