### ISSUE TITLE
Provide an analytics module selection page

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1940]
When you go to /analytics if you only have one module you're automatically redirected to it, but if you have multiple modules you just see a blank page. Instead we should render links to each module.

**Comment by estellecomment** [comment]
The buttons are different sizes depending on how much text there is in them... Still functional, but looks not great. 
![screen shot 2016-02-22 at 09 43 20](https://cloud.githubusercontent.com/assets/911434/13213409/df1aaac0-d948-11e5-9cdc-dab1f7fe2576.png)

**Comment by estellecomment** [comment]
text is not centered vertically on the buttons. (Gonna be the best buttons ever.)
![screen shot 2016-02-22 at 10 11 10](https://cloud.githubusercontent.com/assets/911434/13214050/782c50e8-d94d-11e5-8c25-bec09fdd5439.png)

**Comment by estellecomment** [comment]
Much beautifulness! Thank you!
