### ISSUE TITLE
Targets config UI : needs back button 

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1942]
Once on a given target's config page (`configuration/targets/edit/<targetname>`), you can't navigate back: `Submit` sends you back to the same page after a refresh. 
We need a `Back` or `Cancel` button back to `configuration/targets`.

You can still pick from the dropdown menu though, so doesn't actually block navigation.

**Comment by garethbowen** [comment]
You can use the browser's back button, but a `cancel` would be nice.

**Comment by estellecomment** [comment]
Choice
