### ISSUE TITLE
Get more informative bug reports

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1945]
Can we add logs to the bug reports? 
We keep asking people for more background or how to reproduce, which they might not be able to do.

**Comment by garethbowen** [comment]
On the Configuration > Export page you can export the server logs. If the user contributes their console logs, is that sufficient?

**Comment by abbyad** [comment]
Need to document how to capture a bug report, and share that with users in training.

**Comment by abbyad** [comment]
We should also test that this still works.

**Comment by browndav** [comment]
Deprioritized on 2/22 iteration planning call; moving to backlog.

**Comment by garethbowen** [comment]
We now have an issue template which outlines the information we need an links to [documentation about how to get logs](https://github.com/medic/medic-docs/blob/master/troubleshooting/obtaining-logs.md).
