### ISSUE TITLE
Tasks don't load on first run

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1946]
If you wipe your phone and load the app from scratch, tasks do not load. This includes moving from one tab to another (ie from Contacts back to Tasks).

They will only load once you refresh the page (ie with `location.reload()` or close the app and reopen it.

**Comment by sglangevin** [comment]
I've also seen this many times and I've seen it happen when closing and re-opening the app too (see #1923)

**Comment by alxndrsn** [comment]
@sglangevin any feel for how long you've been seeing this issue?

**Comment by sglangevin** [comment]
The last week or two. I figured it was due to performance work being done and that it might resolve itself.

**Comment by alxndrsn** [comment]
Sounds important.

**Comment by alxndrsn** [comment]
Sounds like #1923
