### ISSUE TITLE
LiveList dates will get out of date

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1947]
Relative dates of reports & tasks will be incorrect after a certain duration.  With the old implementation, angular was watching these values, and constantly updating the text as appropriate.  Now that the HTML for each item is generated statically in `LiveListSrv`, we need to periodically update these elements ourselves.

# Proposal:

## Reports

<img width="519" alt="screen shot 2016-02-22 at 17 18 04" src="https://cloud.githubusercontent.com/assets/191496/13224341/5761684a-d988-11e5-8075-d2c938337878.png">

* change relative dates so they are _today_, _yesterday_, 2 days ago_ etc., rather than more granular values like _just now_, _2 minutes ago_
* rebuild the list's DOM elements daily

## Tasks

<img width="389" alt="screen shot 2016-02-22 at 17 19 09" src="https://cloud.githubusercontent.com/assets/191496/13224352/69b3423e-d988-11e5-85df-76c97572ca23.png">

* rebuild the list's DOM elements daily

# Alternative

We could e.g. attach a timeout to specific list items if we want the date/time to update more frequently than daily.  This sounds complex and unnecessary.

**Comment by alxndrsn** [comment]
@garethbowen @abbyad interested on your thoughts on this one

**Comment by abbyad** [comment]
I think that proposal makes sense from a user perspective. Another option would for today's reports is to show the actual time, not relative.

**Comment by garethbowen** [comment]
The first proposal makes sense I think - regenerate the LiveLists at 12am (or next render) and only have daily granularity.

**Comment by garethbowen** [comment]
Good work. Merged.
