### ISSUE TITLE
Submitting forms does not work when logged in as admin

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1948]
When logged in as `admin`, saving a.g. patient assessment form, or editing a contact, fails on save with the following error:

<img width="709" alt="screen shot 2016-02-22 at 19 00 44" src="https://cloud.githubusercontent.com/assets/191496/13227703/34b6ad54-d998-11e5-8de4-cbb26a99f03a.png">

**Comment by alxndrsn** [comment]
@garethbowen would appreciate your thoughts on this

**Comment by alxndrsn** [comment]
IIRC this was working okay Friday

**Comment by alxndrsn** [comment]
N.B. these actions seem to work on occasion, but mostly not.

**Comment by alxndrsn** [comment]
Looks like getting the original doc, or perhaps one of the related docs (e.g. `doc.parent`) fails during the save process:

<img width="667" alt="screen shot 2016-02-22 at 19 54 04" src="https://cloud.githubusercontent.com/assets/191496/13228831/20b3fdb0-d99e-11e5-90b7-673c8dd606b0.png">

**Comment by alxndrsn** [comment]
ooerr i see the problem

**Comment by alxndrsn** [comment]
ooerr i see the problem

<img width="716" alt="screen shot 2016-02-22 at 19 55 54" src="https://cloud.githubusercontent.com/assets/191496/13228860/4ea1e980-d99e-11e5-82d1-84f93cadcfbd.png">

**Comment by garethbowen** [comment]
Makes sense.

**Comment by garethbowen** [comment]
Whoa... I closed this without merging the PR. Merging now.
