### ISSUE TITLE
Erlang filter failed to deploy properly on lg.dev (HTTP 403 Forbidden)

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1951]
When logging in to lg.dev with a clean desktop version of Chrome 43, I see this:

<img width="1334" alt="lg-dev-erlang-filter" src="https://cloud.githubusercontent.com/assets/763977/13239413/c49576e4-d98e-11e5-9238-b77582ad98fc.png">

It looks like the `Forbidden by design doc validate_doc_update function` message is due to a missing or otherwise-not-working Erlang filter. I've confirmed that removing the filter parameter and reissuing the request via `curl` works, and I've been able to reproduce the error from `curl` as well.

Possibilities: API not bumped before update; API failed to update; unreported migration failure; problem with CouchDB server configuration. Some additional discussion in Slack.

@SCdF: Tossing your way for an initial look, but feel free to bounce this back if you need more information. I'll try to be up.

**Comment by garethbowen** [comment]
lg.dev is on 2710 which is 6 days old. The erlang migration was committed 6 days ago. My guess at this point is the version that's deployed had the webapp changes but not the api changes. If we update it might just work...

**Comment by garethbowen** [comment]
Once you have enough information it might be worth releasing a beta release and updating lg.dev which might just work.

**Comment by SCdF** [comment]
Yep the deployed cut is broken: the api submodule wasn't yet updated to the correct version. Solution would be to cut another build and deploy that.

**Comment by browndav** [comment]
Confirmed: update is successful if gzip/deflate is disabled and a non-weak ETag is served.

**Comment by browndav** [comment]
I temporarily disabled gzip and updated `lg.dev`; it now appears to be functioning normally. I'll get the dashboard update reviewed and deployed to the market ASAP.

**Comment by browndav** [comment]
Footnote: gzip is now reenabled on `lg.dev` so we can proceed with bandwidth measurement/testing.

**Comment by SCdF** [comment]
So @browndav is there anything to actually do here? Or are we done?

**Comment by browndav** [comment]
Code review for ETag patch already passed; moving to acceptance testing.
