### ISSUE TITLE
XForm constraint with `<=` fails unexpectedly

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1953]
The constraint `.<today()` does not allow today or future dates, as expected. Changing it to allow today, eg `.<=today()`, and all dates give the constraint message.

Tested on 2760.

**Comment by alxndrsn** [comment]
> The constraint `.<today()` does not allow today or future dates, as expected.

I would expect this constraint to allow yesterday and prior dates.  If you are trying to allow 'today and future dates', try:

    . > (today() - 1)

**Comment by alxndrsn** [comment]
@abbyad the above should work.  If collect behaves differently, I am happy to work out a fix in-line with the behaviour seen there.

**Comment by abbyad** [comment]
I am trying to get today and prior dates. Are you saying to use `<` instead of `<=` until this calculation issue is resolved?

**Comment by alxndrsn** [comment]
I'm not convinced it's a calculation issue, but if collect behaves differently I will fix as such.

To get today's date or earlier, reverse the example given in my first comment above:

    . < (today() + 1)

**Comment by abbyad** [comment]
The suggested calculation fails too. Date arithmetic is just not working as I'd expect, and perhaps we just need to be aware of that.

The following works as expected: `decimal-date-time(.) <= decimal-date-time(today())`

**Comment by alxndrsn** [comment]
> The suggested calculation fails too.

How is it failing?  Does yesterday's date pass validation, but not today's?

**Comment by abbyad** [comment]
Sorry for not clarifying... what I meant is that all dates fail the constraint.

**Comment by abbyad** [comment]
We need to be aware of current limitations of `today()`, as mentioned here: https://github.com/medic/medic-webapp/issues/1878#issuecomment-188278302

If I see an issue with `<=` elsewhere than with a date I will reopen a new issue.
