### ISSUE TITLE
Merge and release couchdb-audit changes

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1956]
I have made a PR for allowing couchdb-audit to support a separate audit db.

Here is the PR: https://github.com/medic/couchdb-audit/pull/2

Things to do:

- [x] review the code
- [x] release a new version that we can link to correctly

**Comment by SCdF** [comment]
Hey @garethbowen could you do me the honour of reviewing the couchdb-audit changes linked above please? Once you're happy we should chat about how we do a new release of this.

**Comment by garethbowen** [comment]
Very nice. A few comments but nothing serious or difficult. Feel free to merge with or without the suggestions. Then we can get it published!

**Comment by SCdF** [comment]
Release in both NPM and Kanso.
