### ISSUE TITLE
Change medic-api to store audit documents in a separate DB

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1957]
See: #1864.

Things to do:

- [x] Get the tests passing on Travis
- [x] Get the code reviewed. PR: https://github.com/medic/medic-api/pull/45
- [x] Get the code using a proper couchdb-audit version (see #1956)
- [x] Merge

**Comment by SCdF** [comment]
Hey @garethbowen would you be so kind as to do a code review of the linked PR

**Comment by garethbowen** [comment]
Nice one! One comment but otherwise all good.

**Comment by SCdF** [comment]
Merged. This now means that if you update medic-api and run it medic-api will spend three ice ages copying audit docs to another db.
