### ISSUE TITLE
Publish feedback to npm

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#1960]
Currently our `feedback` module is only available through kanso, but we only use it in angular, so we download it from kanso, then use browserify aliases to bundle it into the inbox.js.

This is bad because kanso dependencies are inlined into the ddoc making it larger than necessary. Instead, publish it to npm, and change to using the npm dependency.

**Comment by SCdF** [comment]
I think it looks good. One comment but that's just my lack of JS knowledge.

Out of interest, is `modules` kind of our form of `libs` but ones that we've written?

**Comment by garethbowen** [comment]
Yeah, `modules` are libs that we've written and haven't published to a repository. They're similar to the files in the services directory but don't use angular at all.

**Comment by SCdF** [comment]
Again just one comment because I'm a noob but I think it's probably all good.
