### ISSUE TITLE
Fix Kanso dependencies

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1966]
```
$ kanso clean
Building version tree...

The following directories will be REMOVED:
    packages/feedback
    packages/kanso-gardener

Continue [Y/n]: 
```

**Comment by SCdF** [comment]
Feedback is missing from `kanso.json` but still required due to this #1960. Might as well leave it broken for now and once that ticket is done we can run cleanup.

**Comment by garethbowen** [comment]
Feedback has been removed. Now clean suggests we remove async too.

**Comment by SCdF** [comment]
:shipit:

**Comment by abbyad** [comment]
Seems ready to close, reopen if I am mistaken.
