### ISSUE TITLE
Error finding 'xml' on undefined on fresh startup

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1973]
If you clear pouch and have it reload everything an error you often see in the console is this:
![image](https://cloud.githubusercontent.com/assets/583851/13315158/1e39acd8-dba1-11e5-8b2e-31154ee0b329.png)
This is almost certainly caused by this view: https://github.com/medic/medic-webapp/blob/develop/packages/kujua-sms/kujua-sms/views.js#L499

We should change the view to not break if `_attachments` doesn't exist.

**Comment by garethbowen** [comment]
Error thrown on the server:

```
[Thu, 25 Feb 2016 20:59:34 GMT] [info] [<0.8104.0>] OS Process #Port<0.2704> Log :: function raised exception (new TypeError("doc._attachments is undefined", "undefined", 2)) with doc._id form:jsonform
```
