### ISSUE TITLE
"No <type> selected" message should be handled by parent controller/state

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#1976]
E.g. for contacts : 
When no contact is selected, the "No contact selected" message is that is displayed is actually handled by the `contacts.detail` controller/state, with empty `id` param. 
The parent state doesn't provide any right-hand panel at all.
For that reason, we use links to `contacts.detail`\+ empty id, instead of `contacts`, because of its prettier right-hand panel. That's kinda weird. 
It would make more sense to make `contacts` handle the "No contact selected" message.

Same thing for tasks and messages.

**Comment by garethbowen** [comment]
I don't think this makes sense. The LHS is controlled by the Contacts controller and the RHS is controlled by the ContactsDetail controller. I think having the RHS controlled by both would get really complicated.

**Comment by estellecomment** [comment]
In the `contacts` state, there's no child controller, so `ContactsDetails` can't handle it. That's where the original problem comes from.

**Comment by garethbowen** [comment]
Right, which is why we use the `contacts.detail` state.

**Comment by estellecomment** [comment]
You can still navigate to `contacts` state though, with the URL. Programmatically, too, the original issue came from being redirected there accidentally. And you can't be sure no future programmer (including future Gareth!) won't ever add a link to `contacts` state, so the issue will come up again.

It's also not conceptually obvious why a state with no details would be handled by the controller that deals with details.
