### ISSUE TITLE
Phone number is not unique error in pregnancy followup

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1977]
Upon loading a pregnancy followup task for a patient with a phone number`[1]`, when you click the "By phone" option the following stack trace gets dropped into the console:
![image](https://cloud.githubusercontent.com/assets/583851/13328322/e774ca44-dbe5-11e5-9933-5957b6d54342.png)

It doesn't appear to affect form completion or the user's experience with the form.

Note that you're not entering the number, just displaying it.

`[1]` that may not be unique? Not sure about that one. I'm using Jackie Johnson from lg.dev

**Comment by alxndrsn** [comment]
@abbyad looks like this is caused by fields of `type="tel"` in the `assessment_follow_up` form.  If we are never validating these fields, please set them to type "string".  Also there seem to be _two_ tel fields; perhaps we can now get away with a single one?

**Comment by abbyad** [comment]
This was already changed here: https://github.com/medic/medic-projects/commit/818ccc2d7d54f42371a50eda8acfa939aeaf8523, and should be on lg.app. 

Can this issue still be reproduced?

**Comment by abbyad** [comment]
Assigned to @SCdF to confirm that this is no longer an issue.

**Comment by SCdF** [comment]
Looks to be no longer an issue on lg-testing (which is a clone of prod).
