### ISSUE TITLE
Error when submitting an assessment follow-up report

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#1979]
Seen on lg.dev. I was able to reproduce this by doing an assessment on a child under 1 whose birthdate was recently edited. However, I have also seen some strange behavior on the targets tab related to U1 assessments, so it may be related to that (haven't been able to document any error messages there)
![screen shot 2016-02-25 at 11 30 28 am](https://cloud.githubusercontent.com/assets/1286381/13331731/a693d8e4-dbb3-11e5-8b3c-56a5ad22ba58.png)

**Comment by garethbowen** [comment]
The corresponding line is here: https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/contacts-content.js#L159

**Comment by garethbowen** [comment]
I couldn't quite reproduce this issue, but I'm fairly sure what's happening is the listener is firing after the selected contact is cleared. We should probably be deregistering listeners when navigating away to avoid this sort of thing happening again, but a null check will do for now.

**Comment by alxndrsn** [comment]
The code looks fine, but seems weird that we could be filling a form in a contacts controller without a selected contact.

**Comment by garethbowen** [comment]
The form could be filled in on any controller, but the callback handler is in the contacts controller. So say you go to the contact which registers the listener, then you navigate to the Tasks tab and complete a task, this then fires the listener which may or may not have a contact in context any more...
