### ISSUE TITLE
Error with `difference-in-months` if arg is undefined

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1981]
On a form where the date field is not pre-populated the `difference-in-months` function is failing with:
`Could not evaluate: floor( differe…: Cannot read property 'getFullYear' of undefined"]`

Until this is handled we are very limited in the situations where we can use `difference-in-months`.

**Comment by abbyad** [comment]
A work around for now seems to be to set the default date to `0`.

**Comment by alxndrsn** [comment]
Fixed in 773154aa745e2ba55cb1ae3e62302ac6880a8b47?

**Comment by alxndrsn** [comment]
Fix doesn't seem to be deployed on alpha.dev.  Investigating.

**Comment by alxndrsn** [comment]
Dependencies pushed previously were not up-to-date.

**Comment by abbyad** [comment]
Works well, moving to Ready.
