### ISSUE TITLE
Cannot cancel editing a form in desktop mode

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1984]
In desktop mode there is no way to cancel editing a form or contact. 

![image](https://cloud.githubusercontent.com/assets/789512/13364391/94c9465a-dc9c-11e5-8d3d-4ff26bc87cc4.png)

In mobile there is the `x` in the top bar.

![image](https://cloud.githubusercontent.com/assets/789512/13364418/b0a87c4c-dc9c-11e5-80a0-4a1f247223e9.png)

Likely needs a cancel button in the bottom left, but open to other ideas.

**Comment by Lesterng** [comment]
Form in desktop mode is now in a card. Back button will cancel the form.
<img width="761" alt="screen shot 2016-06-08 at 1 03 51 pm" src="https://cloud.githubusercontent.com/assets/5149601/15909140/d2a9b7ba-2d79-11e6-9666-71f7cb6e86fa.png">

**Comment by sglangevin** [comment]
Mockups available here: https://github.com/medic/medic-design/issues/37

**Comment by sglangevin** [comment]
Link to update mockups: https://github.com/medic/medic-design/issues/37#issuecomment-274173014

**Comment by garethbowen** [comment]
After talking to @diannakane we decided to left align the cancel button and make it a link button so it's consistent with the cancel buttons in the modal dialogs, eg:

![dialog-cancel](https://cloud.githubusercontent.com/assets/2064938/23922512/8b51bd34-0967-11e7-9ba9-5e5e6e1aa31c.png)

**Comment by garethbowen** [comment]
Review please @SCdF https://github.com/medic/medic-webapp/pull/3252

Use ?w=1 because I did a bit of refactoring in there too.

**Comment by SCdF** [comment]
LGTM, merged.
