### ISSUE TITLE
User's branch displays in contact list if user has no contacts

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#1989]
If the user has no visible contacts their branch displays in the right hand pane.

![pasted image at 2016_02_29 04_25 pm](https://cloud.githubusercontent.com/assets/583851/13402524/9a2d9268-df08-11e5-8934-23c8e7238162.png)

**Comment by garethbowen** [comment]
If you refresh do contacts who up in the list?

**Comment by SCdF** [comment]
@garethbowen nope, I think it's that they simply don't have any contacts that are supposed to display.

**Comment by garethbowen** [comment]
All users should be able to see their own contact - otherwise the user is wrongly configured. Their branch is hidden from the LHS so they can't pick it (for some business reason). Not sure why it's showing on the RHS.

**Comment by alxndrsn** [comment]
Cannot recreate on `develop`.
