### ISSUE TITLE
Updating an lg.app clone from build 2468 to build 2848 succeeds but leaves the application in a non-functional state

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#1990]
After updating dashboard to 0.11.6 and updating medic-webapp to build 2848 on lg-testing.app (a clone of production), the first load of the application in a clean browser crashes:

<img width="1017" alt="update-crash-20160229" src="https://cloud.githubusercontent.com/assets/763977/13416214/d06bc7f2-df15-11e5-836d-e1ab60f36689.png">

I have to head out for dinner currently, but can drop back in tonight or very early tomorrow morning PST to look more closely at logs and help troubleshoot.

**Comment by garethbowen** [comment]
I'm not seeing these errors - just different ones. We're planning to fix the errors I'm seeing and re-release beta then update the instance.

**Comment by garethbowen** [comment]
After updating the app I got similar errors as admin but the app worked well as demo. After waiting about 10 minutes and refreshing it now works well for both admin and demo.

**Comment by browndav** [comment]
I saw what looked like `medic-api` repeatedly restarting alongside a second copy when we did the `lg.app` dry-run upgrade; I'm looking at a second private clone to try to work out when/why that's happening.

**Comment by browndav** [comment]
Superseded by #2000; closing as a duplicate.
