### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1993]
Get the following error when updating lg.dev:
`Update failed: could not copy doc from medic to _design/medic?rev=W/615-4a24acc91d6005d2eff410a4196dd094`

![image](https://cloud.githubusercontent.com/assets/789512/13438409/e4bfbd0c-dfb6-11e5-8a8b-7f22199656ce.png)

Refreshing and trying again did not help. alpha.dev was able to update to 2866.

**Comment by garethbowen** [comment]
My guess is it's to do with the gzip change. @browndav Have you had a chance to upgrade dashboard with your gzip patch on lg.dev?

**Comment by browndav** [comment]
I've updated dashboard on `lg.dev`; it appears it was at 0.11.4 before this update. Only 0.11.6 is known to work properly.

**Comment by abbyad** [comment]
Not quite sure how to set this up to be acceptance tested. @browndav any suggestions?

Regardless it seems as though we should just make sure to update Dashboard to latest prior to updating medic-webapp.

**Comment by browndav** [comment]
IMO the release we did was sufficient acceptance testing. Closing; feel free to reopen if you disagree.
