### ISSUE TITLE
Special characters not displaying properly in dropdown lists

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#1994]
Not high priority since we aren't using the apostrophe anymore in the Family name construction, but we will surely run into situations where we'd want this fixed.

![image](https://cloud.githubusercontent.com/assets/789512/13443786/bbbb472c-dfd0-11e5-84c8-61f79ec354f1.png)

**Comment by garethbowen** [comment]
Irish deployments will go horribly!

**Comment by garethbowen** [comment]
@abbyad This works for me. What server were you on? admin or restricted user? How did you get to that page?

**Comment by sglangevin** [comment]
@garethbowen I had seen this before and was able to reproduce by logging into alpha.dev as a restricted user, going to the History tab and selecting the OVC Survey action.

**Comment by garethbowen** [comment]
@sglangevin That worked. Thanks!

**Comment by alxndrsn** [comment]
Not keen on the formatting changes, but looks fine otherwise.
