### ISSUE TITLE
Work out one-liner to test if a Pouch DB is fully synced

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2002]
So we can run it one a phone (linked to a chrome debugger) to make sure that a phone is synced.

**Comment by SCdF** [comment]
Doing this for documentation purposes. Currently I have this:
```
PouchDB('medic').changes({descending: true, limit: 1}).then(function(localChanges) { PouchDB('medic').get(localChanges.results[0].id).then(function(localDoc) { var localId = localDoc._id; var localRev = localDoc._rev; console.log("Local Id, Rev:", localId, localRev); PouchDB('https://XXX:YYY@ZZZ/medic').get(localId).then(function(remoteDoc) {var remoteId = remoteDoc._id; var remoteRev = remoteDoc._rev; console.log('Remote Id, Rev:', remoteId, remoteRev)});});});
```

Replace XXX and YYY with known credentials, and ZZZ with the URL of the remote couch instance.

Note that is presumes the local db is called 'medic'. This won't be true in the latest code, but this is currently written for a situation prior to that code being deployed.

**Comment by SCdF** [comment]
@alxndrsn informs me that while it was very sporting of me that I wrote it in one line, actually I didn't have to. In that spirit, here is the actually readable version:

```javascript
PouchDB('medic').changes({
  descending: true,
  limit: 1}
).then(
function(localChanges) {
  PouchDB('medic').get(localChanges.results[0].id).then(
    function(localDoc) {
      var localId = localDoc._id;
      var localRev = localDoc._rev;
      console.log("Local Id, Rev:", localId, localRev);
      PouchDB('https://XXX:YYY@ZZZ/medic').get(localId).then(
        function(remoteDoc) {
          var remoteId = remoteDoc._id;
          var remoteRev = remoteDoc._rev;
          console.log('Remote Id, Rev:', remoteId, remoteRev);
        });
    });
});
```

**Comment by SCdF** [comment]
A better version that only pulls the HEAD remotely for better performance:

```javascript
PouchDB('medic').changes({
  descending: true,
  limit: 1
}).then(function(localChanges) {
  PouchDB('medic').get(localChanges.results[0].id).then(function(localDoc) {
      var localId = localDoc._id;
      var localRev = localDoc._rev;
      console.log("Local Id: ", localId);
      console.log("Local Rev: ", localRev);
      angular.element(document.body).injector().get('$http')({
        method: 'HEAD',
        url: 'https://XXX:YYY@ZZZ/medic/'+localId
      }).then(function(result) {
        console.log('Remote Rev: ', result.headers().etag);
      });
    });
});
```

NB: a better better version would be to use angular services to get credentials so you don't need to type them in.

**Comment by garethbowen** [comment]
Slightly simpler version using `include_docs`:

```js
PouchDB('medic').changes({
  descending: true,
  limit: 1,
  include_docs: true
}).then(function(changes) {
  var localDoc = changes.results[0].doc;
  var localId = localDoc._id;
  var localRev = localDoc._rev;
  console.log("Local Id: ", localId);
  console.log("Local Rev: ", localRev);
  angular.element(document.body).injector().get('$http')({
    method: 'HEAD',
    url: 'http://gareth:pass@localhost:5988/medic/'+localId
  }).then(function(result) {
    console.log('Remote Rev: ', result.headers().etag);
  });
});
```

**Comment by SCdF** [comment]
Fun note, after sleeping on it I'm not completely confident of this script. My lack of confidence comes from the fact that the changes feed incorporates local changes _and remote ones_. I'm pretty sure that means if you do the following:
 - Go offline and make a bunch of changes
 - Change the ddoc remotely (or any doc really that will sync to them)
 - Go online
 - Run my script

Depending on timing the last changed document may just be indicating that you've pulled down the remote changes, and not that the local ones have been synced.

Clearly we need a better solution for this, but I think this will come from code creating a sync status etc, which is covered in other tickets.
