### ISSUE TITLE
Change medic-api's export-data controller to support the moved audit docs

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2003]
These functions don't know that audit data has moved into a separate DB. We will need to write a special case for `formType.audit` to point at a different DB.

**Comment by SCdF** [comment]
If I find time I'll assign this to myself and take a look, otherwise it's up for grabs. Should not be too hard.

**Comment by SCdF** [comment]
Knocked up something here: https://github.com/medic/medic-api/tree/export-data-audit-support

Haven't tested or even run it...

**Comment by SCdF** [comment]
NB: this is not a high priority, it sounds like at least the audit portion is not really used.

**Comment by garethbowen** [comment]
PR for code review: https://github.com/medic/medic-api/pull/56

**Comment by SCdF** [comment]
Looks good @garethbowen. Can you squash or otherwise rebase the branch to get rid of my WIP commit? Rebasing doesn't look to work (presumably because you merged develop in) so maybe just `merge --squash` it? I didn't want to do it as it would make it look like it was done by me (though I guess that's half true).

**Comment by SCdF** [comment]
I squashed this into one commit: https://github.com/medic/medic-api/commit/38229f9fa96e26aad0835a795920e558b391463b
