### ISSUE TITLE
Pressing HBB on Contacts tab quits app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2006]
...with error `cannot transition to abstract state: tasks`

**Comment by alxndrsn** [comment]
The fix for this and #2007 may be to make root states (`contacts`, `tasks`, `messages`, `reports` etc.) work instead of being abstract.

**Comment by estellecomment** [comment]
Probably introduced by #1900

**Comment by alxndrsn** [comment]
Seems to be fixed...
