### ISSUE TITLE
Recent changes to states may have broken tour

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2008]
The changes to states that caused https://github.com/medic/medic-webapp/issues/2006 and https://github.com/medic/medic-webapp/issues/2007 may have also broken the Tour at:

```
static/js/controllers/tour-select.js:23:          $state.go(route, { tour: name });
```

**Comment by sglangevin** [comment]
The tour seems to be working now. Re-open if this is still an issue.
