### ISSUE TITLE
Contact list contains pointless information for a normal user

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2010]
As a standard user, all my Families will be from the same branch and area, so I don't need to see this information below every family's name in the _Contacts_ list.

<img width="279" alt="screen shot 2016-03-03 at 16 48 28" src="https://cloud.githubusercontent.com/assets/191496/13496183/d3c0f07a-e15f-11e5-8338-1e62b0380837.png">

Everyone's from **_Busia CHP Area1 \* Busia Branch_**!

N.B. Under individual People it will also say the name of the Family, which is more useful.

**Comment by estellecomment** [comment]
Also true in Contacts view, was raised by a CHP : ("Dickson Mtanga's Area • Tula Branch")
![Uploading Screen Shot 2016-03-04 at 17.02.02.png…]()

**Comment by sglangevin** [comment]
This has also been raised by LG HQ and is related to general comments about vertical space that I shared with @diannakane

**Comment by diannakane** [comment]
Contact list hasn't been prioritized yet, I'll discuss with Marc to see if
it makes sense to look at in the next iteration.

On Fri, Mar 4, 2016 at 11:29 AM, sglangevin <notifications@github.com>
wrote:

> This has also been raised by LG HQ and is related to general comments
> about vertical space that I shared with @diannakane
> <https://github.com/diannakane>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2010#issuecomment-192429180>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by sglangevin** [comment]
This view was updated in v2.9. Let's create a new issue if more work is needed.
