### ISSUE TITLE
Age at LMP calculated to be 0

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2011]
This means any new pregnancy would get the U18 danger sign.

**Comment by abbyad** [comment]
`difference-in-months` does not accept time with the date (eg formatted with `%Y-%m-%dT00:00:00.000Z`). Removing the time and this works as expected.

**Comment by alxndrsn** [comment]
@abbyad should difference in months be expecting dates in that format?  `%Y-%m-%dT00:00:00.000Z` is likely an incorrect date format anyway, as the date will be local, but the format implies GMT (`Z`).

**Comment by abbyad** [comment]
@alxndrsn I would think that that date time string is valid since it is in ISO 8601 format. Is some piece of it off?

The question of whether or not to use the UTC time or not is a separate issue. The reason it was being used here was a workaround for https://github.com/medic/medic-webapp/issues/1878 to use all dates in the same timezone.

**Comment by abbyad** [comment]
We can wait to see if other issues come up, but for now it seems fine. Until any further issue arises, it is safe to leave this as low priority to do later - if at all.

**Comment by alxndrsn** [comment]
:+1:
