### ISSUE TITLE
Explore stories and options for a "silence" task function

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2013]
Do we want to allow users to "silence" a task, preventing it from appearing in their task list?  The story here is if a CHP cannot complete the task because the mother or child is away, or for some other reason.

Current thinking is to force users to "complete" the task anyway, and add a question on the form to explain why they were not able to reach that mother or child. 

Leaving this task open to remind us to consider this in our form and task design and configuration.

**Comment by sglangevin** [comment]
Quick note that may be helpful: Muso has a question on their follow-up forms where they ask whether follow-up was possible as the first question. If no, they have options that the CHP can select for why the visit wasn't possible and then they just hit Submit from there. If yes, then the other questions appear as usual. Might be something to consider for other partners.

**Comment by browndav** [comment]
@diannakane: Is this issue still actionable? IIRC we've accomplished some of this via careful rule/form configuration; is there a need to go further within the next six months or so?

**Comment by diannakane** [comment]
Nothing immediately actionable here. As @sglangevin mentioned, we accomplish this for some projects through forms. I'll add it to the design ideas repo to see if we want to develop another way to achieve or standardize this.
