### ISSUE TITLE
App fails disgracefully when device runs out of space

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2015]
One user in Kampala has been recording a lot of videos on device, filling up the storage.  The app then stopped working, although they did not know why.  The fix employed locally is to uninstall and reinstall the Medic Mobile app, which was done a number of times.

If we can detect the lack of storage space and warn the user (even preventing access to the app until more space is available), this would be a big improvement.

**Comment by SCdF** [comment]
Specifically, "not working" was that the loading indicator when you open the app would never go away and be replaced by the actual application, i.e. angular could never complete init. Since we never experienced this ourselves we never got logs to see what was happening.

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-android/pull/18

**Comment by SCdF** [comment]
Looks good, merged.
