### ISSUE TITLE
Retry option for upload_xform script

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2016]
Pushing all forms to an instance requires calling upload_xform for each of the eleven forms, which is a pain when it returns a 409 Conflict. A timeout was added between the delete and upload, which helps for some forms, but not all - even if that timeout is extended to 5 or 10 seconds. Retrying the delete/upload though always works. Retries were successful from a project specific script, but it may be better to do it from the upload_xform script itself.

**Comment by alxndrsn** [comment]
This is very odd - document `PUT` succeeds, but then `GET`ting the same doc reports it as `{"error":"not_found","reason":"deleted"}`.

**Comment by alxndrsn** [comment]
Obvious solution - don't delete docs when you want to update them - just get the `rev` and override.

**Comment by abbyad** [comment]
Haven't had a 409 since this fix. Thanks!

**Comment by alxndrsn** [comment]
Glad to hear it :+1:
