### ISSUE TITLE
Display date of delivery in contact (differently? more obviously?)

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2018]
From UX study March 3 : https://docs.google.com/document/d/1H412gSJ68amsOpW8hRhJrt_df4aLcqV5UoMhCF9P9tA/edit#

Even though there are reminders + tasks, one CHP wanted the delivery date displayed on the contact of the pregnant lady. She said she could see the trimester, but that wasn't enough.

In practice, if the contact is pregnant you can go to the pregnancy form in History, and see the EDD there. Don't know if she didn't find it. She wanted it displayed in the Details. Don't know if that's too LG-specific or ANC-specific to be done.
![screen shot 2016-03-04 at 10 34 47](https://cloud.githubusercontent.com/assets/911434/13520836/c346e4a8-e1f4-11e5-880e-f749b17f1183.png)

**Comment by abbyad** [comment]
The trimester is not shown on the profile either, but we already have this on our radar in https://github.com/medic/medic-webapp/issues/1572. Having the EDD (along with other important info) on the profile page is something that @diannakane and the design team has been investigating.

**Comment by sglangevin** [comment]
Also, note that this feature has been flagged for post-launch. Not required for upcoming branch launches.

**Comment by diannakane** [comment]
Yep, we've got some older mockups exploring the [many] things we could
include on a profile page and are revisiting that along with other
improvements to the profile UI. Great to have this feedback to help us
prioritize what's important to CHPs.

On Fri, Mar 4, 2016 at 10:36 AM, sglangevin <notifications@github.com>
wrote:

> Also, note that this feature has been flagged for post-launch. Not
> required for upcoming branch launches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2018#issuecomment-192400587>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment]
This can now be configured on a per-project basis using #2914
