### ISSUE TITLE
"Cancel" vs "Continue" is confusing when interrupting a form-filling

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2019]
(This has probably been filed before but I can't find it.)

When you're filling a form and cancel (either HBB or "X" icon), you get a dialog which suggests either "Cancel" or "Continue" and that's confusing language (as reported in UX study March 2016)

Something like "Yes, leave" vs "No, continue the form" or something.

**Comment by estellecomment** [comment]
![screenshot_2016-03-04-13-34-12](https://cloud.githubusercontent.com/assets/911434/13524765/4fd394fc-e20e-11e5-964d-1a5652b53849.png)

**Comment by sglangevin** [comment]
There is an open issue in medic-projects for this, with suggested text from @diannakane: https://github.com/medic/medic-projects/issues/107
