### ISSUE TITLE
Allow more flexible family naming

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2020]
@diannakane and @abbyad will find this interesting, and I'm sure there's been some previous discussion about this too.

Naming families by primary caregiver (i.e. mother most times) is not convenient. See description of problem as reported by CHP : https://docs.google.com/document/d/1H412gSJ68amsOpW8hRhJrt_df4aLcqV5UoMhCF9P9tA/edit#bookmark=id.rtmiz6rjb8fh

Either name the families by the husband's name, or just leave a free-form textfield for naming the family, that way CHPs can use whatever is convenient to them (and we'll get data on what's best, since they would know better than us)

**Comment by sglangevin** [comment]
Before we make any changes on this, we have to confirm with LG HQ. I believe there has been quite a bit of past discussion on this and that naming by primary caregiver (mother) was done intentionally. I can add this to my list of things to forward along for approval.

**Comment by diannakane** [comment]
@estelle I hear you. The cultural norm is to identify the husband as head
of household and it's interesting to see that there's a desire to adhere to
this even when the husband is not directly being served by the CHP.  We had
extensive discussions with LG about this and Chuck was clear that each
mother be listed as the head of her own household, regardless of whether
two mothers live in the same physical space and irregardless of the
presence of their husbands. @sharon you can share this feedback with the LG
team, but make a note that a change to this should be approved by Chuck.

We might be able to minimize some confusion by changing the label on this
question field, from "head of household" to "mother's name" while keeping
the naming of the family unit the same.  I could also see us providing a
flexible field for the family's name, and while still labeling the mother
as the "head," though if the CHP searches for the mother's name, then it's
possible that only the mother's record would appear in the results and not
the children's.



On Fri, Mar 4, 2016 at 10:39 AM, sglangevin <notifications@github.com>
wrote:

> Before we make any changes on this, we have to confirm with LG HQ. I
> believe there has been quite a bit of past discussion on this and that
> naming by primary caregiver (mother) was done intentionally. I can add this
> to my list of things to forward along for approval.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2020#issuecomment-192401167>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by estellecomment** [comment]
Good to know the previous discussions about this, thanks.

We could add the husband as a field to help finding the mother. Right now
there's a Notes field, which some use for landmarks that help locate the
family. In that way, there could be an additional optional "husband's name"
field to help with location too. That would leave the mother-centric
organization as is.

**Comment by diannakane** [comment]
I like the idea of a "husband's name" as an optional field in the
mother-family creation process. Could we configure our search criteria to
include that field in search results?

On Fri, Mar 4, 2016 at 9:27 PM, estellecomment <notifications@github.com>
wrote:

> Good to know the previous discussions about this, thanks.
>
> We could add the husband as a field to help finding the mother. Right now
> there's a Notes field, which some use for landmarks that help locate the
> family. In that way, there could be an additional optional "husband's name"
> field to help with location too. That would leave the mother-centric
> organization as is.
> On Mar 5, 2016 3:42 AM, "Dianna Kane" <notifications@github.com> wrote:
>
> > @estelle I hear you. The cultural norm is to identify the husband as head
> > of household and it's interesting to see that there's a desire to adhere
> to
> > this even when the husband is not directly being served by the CHP. We
> had
> > extensive discussions with LG about this and Chuck was clear that each
> > mother be listed as the head of her own household, regardless of whether
> > two mothers live in the same physical space and irregardless of the
> > presence of their husbands. @sharon you can share this feedback with the
> LG
> > team, but make a note that a change to this should be approved by Chuck.
> >
> > We might be able to minimize some confusion by changing the label on this
> > question field, from "head of household" to "mother's name" while keeping
> > the naming of the family unit the same. I could also see us providing a
> > flexible field for the family's name, and while still labeling the mother
> > as the "head," though if the CHP searches for the mother's name, then
> it's
> > possible that only the mother's record would appear in the results and
> not
> > the children's.
> >
> >
> >
> > On Fri, Mar 4, 2016 at 10:39 AM, sglangevin <notifications@github.com>
> > wrote:
> >
> > > Before we make any changes on this, we have to confirm with LG HQ. I
> > > believe there has been quite a bit of past discussion on this and that
> > > naming by primary caregiver (mother) was done intentionally. I can add
> > this
> > > to my list of things to forward along for approval.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/medic/medic-webapp/issues/2020#issuecomment-192401167
> >
> > > .
> > >
> >
> >
> >
> > --
> > P.S. Join our community. Sign up for Medic Mobile's newsletter
> > <
> >
> http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255
> > >
> > .
> >
> >
> > Dianna Kane | Senior Designer
> > Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
> > @*M*edic <http://www.twitter.com/medic> Facebook
> > <https://www.facebook.com/MedicMobile> @diannakane
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/medic/medic-webapp/issues/2020#issuecomment-192538608>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2020#issuecomment-192581983>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by estellecomment** [comment]
A side note about that : I'm curious if the search feature is known or
used. I'll try to figure that out Thu.

**Comment by abbyad** [comment]
Closing as this is configurable per project
