### ISSUE TITLE
"Husband is in the children list", or not there at all

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2021]
A CHP reported it was difficult to find a woman's husband's name (which can be useful to find her house for instance). Either the husband is not registered at all (since he's not a young child or a potentially pregnant woman), or he's in the list of children, so you have to go down the list looking for a middle-aged person that has to be the husband.
https://docs.google.com/document/d/1H412gSJ68amsOpW8hRhJrt_df4aLcqV5UoMhCF9P9tA/edit#bookmark=id.rtmiz6rjb8fh

An an option to register the husband too when registering a family.

**Comment by diannakane** [comment]
@estellecomment Why were they looking for the husband? Were they wanting to treat him? Or did they assume that was the best way to search for a family? If the woman was with the CHP at the time, why did they not search for her or her child's name?

**Comment by estellecomment** [comment]
I'll clarify: finding in the app vs finding the location in the
village/area.

It's related to the conversation about locating families in the area, a CHP
has hundreds and can't remember where all of them are, so they ask people.
The husband's name is more helpful than the wife's when asking around for a
family.

So the CHP we talked to is saving the husband in the family members (don't
know if it's just for that or if there's also other reasons). But she finds
it weird to save it there along with the children, as opposed to saving it
along with the mother's name as family-identifying information.

Or sometimes it's not saved anywhere, in which case it just sucks not
having it.

**Comment by sglangevin** [comment]
Perhaps we can add a field to the add family form where the CHP can enter the husband's name? And for now this could be part of the "Details" section on the family profile page? Not sure if this would count as a feature request or not.

**Comment by estellecomment** [comment]
@diannakane Can you assess if this is a common issue or just a one-time? And if it's fixed in current features or workarounds?

**Comment by estellecomment** [comment]
This is transferred to the design pipeline : https://github.com/medic/medic-design/projects/1#card-1884366
Closing this issue on the dev side.
