### ISSUE TITLE
Phone number validation message is confusing

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2022]
From UX study : https://docs.google.com/document/d/1H412gSJ68amsOpW8hRhJrt_df4aLcqV5UoMhCF9P9tA/edit#bookmark=id.7iqgesq82jog

![screen shot 2016-03-04 at 11 07 48](https://cloud.githubusercontent.com/assets/911434/13521445/94687d90-e1f9-11e5-98c3-329150d73a91.png)

I don't think users would ever enter the international format anyway, so remove it from the message.
It's also too long I think, it's unlikely it'll be read. 
Maybe "Wrong phone number. It should be 07XX XXX XXX." If they enter dashes or spaces they'll be filtered out anyway.

Copying @abbyad who maybe has thoughts/history about why we do things this way?

**Comment by alxndrsn** [comment]
Worth checking how locals normally write phone numbers - dash-separated looks very North American to me.

**Comment by sglangevin** [comment]
This is the error message that was requested by LG. However, as long as we have some sort of hint or error message that makes sense to CHPs, they will be happy, so feel free to recommend something. Having an understandable error message is a requirement for upcoming branch launches.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
This is configured in forms. I'm happy to leave it as whatever was requested by the project.

**Comment by mandric** [comment]
Is it part of a/the "standard" configuration?  Seems like we should incorporate this knowledge somewhere?
