### ISSUE TITLE
Confusion between family page and person page

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2023]
Example : "Diana Price's Family" vs "Diana Price"
![screen shot 2016-03-04 at 11 19 52](https://cloud.githubusercontent.com/assets/911434/13521625/13710f70-e1fb-11e5-8aa0-c6de125fad4c.png) 
![screen shot 2016-03-04 at 11 20 02](https://cloud.githubusercontent.com/assets/911434/13521629/1960a882-e1fb-11e5-825f-dc17095bed2d.png)

It looks to me that CHPs look for actions in both places, and it's not obvious that they really get the difference conceptually between the two. Maybe style the two pages differently or something. Add different icons. Maybe rename the family (https://github.com/medic/medic-webapp/issues/2020)

We need more evidence of this though, in interviews. It's mostly a hunch at this point. Maybe @diannakane  has thoughts on this.

**Comment by diannakane** [comment]
@Lesterng I think our changes to the titles of the family and individual pages will help here, but we may want to take it a step further and use family vs. individual icons to help differentiate. Let's revisit this along with the rest of the profile page UI next week.

**Comment by diannakane** [comment]
@estellecomment have the new designs resolved this issue and can it be closed? They will be implemented in #1572 

![household profile](https://cloud.githubusercontent.com/assets/1675870/16248375/a298d8b8-37c3-11e6-8ef4-5eba11d0db32.png)

**Comment by estellecomment** [comment]
Honestly I don't know @diannakane! I raised the issue after doing the user interviews, and I guess if we want to know for real, we should do a new round of interviews.
Do we have interviews planned, and/or a list of things to look out for, that we could add this to? I'd be happy to help out.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
I think this has been resolved with the contact UI rework. If it turns up in further interviews raise a medic-design issue and we can take it from there.
