### ISSUE TITLE
Go to ABOUT page on first-run of app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2024]
Normally app first-run is (or will be) done by tech staff of Medic or partners, and they will want to check things like android container version, webapp version, and to watch the network activity monitor, all of which are on the _About_ page.

This might be achievable by redirecting from API to ABOUT on login if no other forward URL is supplied.

**Comment by garethbowen** [comment]
We have a Home controller which works out which tab to load first, so it should be added as a condition in there. The About page is quite technical looking and not a very welcoming page to start on. It'd be worth polishing the page to be a little more welcoming.

**Comment by alxndrsn** [comment]
> We have a Home controller which works out which tab to load first, so it should be added as a condition in there.

This would certainly be one place to handle it.  If we only want this redirect after a fresh login though, would it be suitable for API to handle it by setting the `redirect` parameter if none is provided?  Or for `medic-android` to set the `redirect` parameter to `/about` when loading the login page?

> The About page is quite technical looking and not a very welcoming page to start on. It'd be worth polishing the page to be a little more welcoming.

Currently logging in is done by tech leads, so the assumption is that "technical looking" is acceptable.

**Comment by garethbowen** [comment]
>  If we only want this redirect after a fresh login though, would it be suitable for API to handle it by setting the redirect parameter if none is provided?

If I understand correctly you want a first run page for the device so we can show replication status and so on. Unless api starts tracking devices it won't know if it's first run or not.

> Or for medic-android to set the redirect parameter to /about when loading the login page?

That would work, but the benefit would only be on mobile rather than both mobile and desktop, and it would be difficult to test. In my opinion this feature would tie in nicely to the work we're doing on initial replication in the webapp.

> Currently logging in is done by tech leads, so the assumption is that "technical looking" is acceptable.

I agree it's acceptable but there's no harm in trying to present the same information in a more user friendly way.

**Comment by SCdF** [comment]
> Unless api starts tracking devices it won't know if it's first run or not.

Won't it know though, because if there is no redirect parameter attached you can presume it's first run?

**Comment by garethbowen** [comment]
> if there is no redirect parameter attached you can presume it's first run?

I don't think that's always true. For example if the app is closed and reopened I think it'll request the login page without redirect parameter (which then automatically logs you in and sends you to the Home controller). Furthermore desktop users (admins and CHWs at future installations) they will probably go directly to the login page without the redirect param, and not want to see the stats every time.

The option that's guaranteed to be correct and simplest to develop is adding it in the webapp.

**Comment by alxndrsn** [comment]
>  if the app is closed and reopened I think it'll request the login page without redirect parameter

`medic-android` points the WebView at `/medic/_design/medic/_rewrite/`

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
@alxndrsn do you feel strongly about this? I vote close.

**Comment by alxndrsn** [comment]
I don't feel strongly about it because I haven't had to configure any phones recently.

**Comment by SCdF** [comment]
Doesn't sound like a priority
