### ISSUE TITLE
New Family + new pregnancy flow is hard to get right

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2025]
I don't have enough examples for now to really reach conclusions, so more data is needed.

The CHP we interviewed got confused and couldn't find the "New Pregnancy" button (granted, we were staring at her and taking notes which didn't help) See situation : https://docs.google.com/document/d/1H412gSJ68amsOpW8hRhJrt_df4aLcqV5UoMhCF9P9tA/edit#bookmark=id.zcqj61b61ury

Not sure why she didn't see the Task that prompts you to register a pregnancy, in both the person's page and the family's page. (more data needed!)
Interestingly, she went back to Contacts after entering the family, and that could be related to the behavior of LG's previous apps: you would enter people in one app and pregnancies in a separate app. 

About that flow (regardless of this CHP's troubles), I find it confusing that we ask "Is the person pregnant?" and "Are there children under 5?", yet when getting to the end of the form, you still have to register pregnancy + young children. 
I'd see it better either all in the same giant form (it's lots of stuff but you don't have to make choices, just follow the whole flow), or be entirely separate forms (which would be closer to the behavior of the previous apps).

I do get that there's a risk that when the family registration is done, they forget to do the other steps (thus the task generation). But I think if the steps are small and clear, it can work.
E.g. create the family, stop. Create a family member, stop. Create a pregnancy, stop. Create a child under 5, stop. 
Right now we're leaning towards long flows that I think are getting people lost. (again I don't have thaaaat much data so please give your thoughts @abbyad and @diannakane and whoever)

**Comment by estellecomment** [comment]
A thought : should we allow different ways to do the same action? Is that helping because you can do your action from anywhere, or is it hurting because it makes the flows unclear? No clear opinion about this.

**Comment by sglangevin** [comment]
Those two questions: is the primary caregiver pregnant? and are there children under 5? are part of the family survey, which is appended to the add family form and is something that CHPs are supposed to fill out every 6 months (it will appear as a task when it is due). This was a specific request by LG (that it be appended to the add family form).

Children can be added during the add family form or later, it's up to the CHP. Perhaps there might be a hidden training issue here? I do agree that longer flows can be confusing, but I am also hesitant to make this type of change without clearing it with the partner first as they are quite specific about form content and workflow.

**Comment by diannakane** [comment]
What's most confusing to me about this workflow is that it's not
immediately clear that you are creating a person when you are answering
head of household / family description questions. The old app didn't create
a person in this stage, so the CHPs also aren't expecting it.  I think
that's part of why no one is sure what to do when asked to create a
pregnancy, and why they find it strange that they aren't asked to identify
the husband in this phase, too.

On Fri, Mar 4, 2016 at 10:47 AM, sglangevin <notifications@github.com>
wrote:

> Those two questions: is the primary caregiver pregnant? and are there
> children under 5? are part of the family survey, which is appended to the
> add family form and is something that CHPs are supposed to fill out every 6
> months (it will appear as a task when it is due). This was a specific
> request by LG (that it be appended to the add family form).
>
> Children can be added during the add family form or later, it's up to the
> CHP. Perhaps there might be a hidden training issue here? I do agree that
> longer flows can be confusing, but I am also hesitant to make this type of
> change without clearing it with the partner first as they are quite
> specific about form content and workflow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2025#issuecomment-192405673>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
snek snek @nice-snek,
I'd propose we rework the contents of this issue and land it as a slightly higher-level design to-do list itam (e.g. in another project).

**Comment by diannakane** [comment]
Yo @browndav did this issue get transferred to a design issue somewhere else or shall I assess it and do so?
