### ISSUE TITLE
"Actions" looks like a button?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2026]
One CHP pressed "Action" several times, even though it's not a button. (more data needed to be sure, that's just one person)

Maybe we need to think about our visuals : buttons should look like buttons, the rest should not. @Lesterng do you have thoughts about this maybe?

**Comment by diannakane** [comment]
Good to know. I think we've taken care of this in our work on updating the profile page. Will share mockups soon!

**Comment by estellecomment** [comment]
Not relevant any more in new people tab.
