### ISSUE TITLE
Phone validation really slow in New Family form

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2027]
When you register a new family and enter the phone number, and tap Next, there's a long lag before the validation screen.
Seen once, on Estelle's phone, on lg.dev, probably on mobile data. Can't reproduce it.

**Comment by estellecomment** [comment]
Between this : 
![screen shot 2016-03-04 at 13 51 54](https://cloud.githubusercontent.com/assets/911434/13525153/591a7466-e210-11e5-82d4-921f14824858.png)

and this : 
![screen shot 2016-03-04 at 13 52 04](https://cloud.githubusercontent.com/assets/911434/13525158/5fffce52-e210-11e5-980a-6ffce5aab23d.png)

**Comment by estellecomment** [comment]
the CHP pressed the Next button many times. In case that's related.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by abbyad** [comment]
I have not been able to reproduce this with similar forms used in the field. @sglangevin do you know if this has been an issue with any users?

**Comment by sglangevin** [comment]
I don't know of anyone reporting an issue with this. Let's close it and we can open a new issue if we hear this feedback again.
