### ISSUE TITLE
EventEmitter memory leak: recent new warning noticed

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2028]
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. 
```

This occurs often-times on first load. Not sure if it happens at other times as well.

Not labeling it as a bug because it's a warning so I presume it's not actually breaking anything, but feel free to re-label.

**Comment by estellecomment** [comment]
http://pouchdb.com/errors.html#event_emitter_limit
"Check to make sure that you are calling cancel() on any changes(), replicate(), or sync() handlers, if you are constantly starting and stopping those events."

**Comment by estellecomment** [comment]
I can see it happening during app load (first load or reload).
It's the `destroy` event, which we aren't even listening to. Pouch is listening to it internally. 

We could remove the warning buy raising the max number of listeners, but we'd have to do it for all eventemitters, so we could miss possible future memory leaks. 

So, do nothing.
