### ISSUE TITLE
Can't get into app if not logged in

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2029]
Hit the app directly if you're not logged in, and you're hosed:

<img width="1280" alt="screen shot 2016-03-04 at 15 21 52" src="https://cloud.githubusercontent.com/assets/191496/13526999/ec99da68-e21c-11e5-871f-095e7595c014.png">

**Comment by SCdF** [comment]
NB: it's fine for me, there is a chance it's something in Alex's configuration

**Comment by SCdF** [comment]
Ignore my previous comment, it is happening for me. It seems to be an api change in the last ~24hrs. When I pulled medic-api no longer started until i did an npm install, and now when I start it I get:
```
$ TEST_ENV=1 COUCH_URL=http://admin:pass@localhost:5984/medic node server.js
Medic API listening on port 5988
(node) http.createClient is deprecated. Use http.request instead.
```

Which is wrong and weird, because it's not running any migrations or anything either.

**Comment by SCdF** [comment]
Ignore my previous comment again! Turns out I checked out `master` like a fool! The HEAD of develop for both medic-webapp + medic-api work for me.

**Comment by garethbowen** [comment]
Might be a trailing slash issue? I'll try and reproduce.

**Comment by garethbowen** [comment]
I could reproduce this by deleting my userCtx cookie manually.
