### ISSUE TITLE
Make sure users eventually update their app

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2030]
If a user is presented with the update dialog and they hit cancel, there are no more (obvious) opportunities for them to install that update. Note that "install that update" really just means refresh the page.

This is probably important, since I imagine if we deploy an update we want people to be moved to it as quickly as is convenient.

It is also understandable that users can cancel the update dialog at that specific moment, as they may be in the middle of something.

This may require UX design.

Two options that Alex and I discussed:
 - Storing if there is an unapplied update in the `$scope` and folding a refresh into the next action. For example, saving a form would save the form and then trigger a refresh.
 - Storing if there is an unapplied update in the `$scope` and adding an idle timeout. For example, if you needed to refresh and were idle for more than 5min trigger a refresh.

Another that Estelle mentioned would be to re-popup the dialogue every N minutes if the update was not applied.

Note that as long as there is no unsaved data refreshes should be safe in any network situation.

**Comment by estellecomment** [comment]
Another solution to not interrupt users is to have a popup with a countdown that you can stop if you're busy. If you're not busy you just let it countdown and push the update.

**Comment by SCdF** [comment]
Alex has reviewed IRL.
