### ISSUE TITLE
When adding a new person from the family page, date of births between 1974-08-15 and 1997-05-18 do not count as before today (on 2016-03-05)

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2034]
So this one is pretty cool.

This was performed in Uganda, today (2016-03-05), on a tecno, as a restricted user, on lg-testing.app. I confirmed that both the phone's date and the result of `new Date()` in JS on the phone were correct.

To replicate:
 - Open up the contact page, and pick a family.
 - Tap 'Add family member'
 - Tap in Age / Date of Birth and pick one between 1974-08-15 and 1997-05-18 inclusive
 - The validation will claim that the date selected must be before today.

Additional:
 - Be a restricted user on a tecno? (I haven't checked other configurations)
 - I haven't tested on other servers (ie localhost / dev / alpha) yet
 - Picking an actual date in the future also triggers the validation error, so it's still somewhat working.
 - This **does not** occur when you're adding additional family members with the create contact form
 - These dates may move depending on the current date, I also haven't checked that

**Comment by sglangevin** [comment]
I've also seen this on alpha.dev and lg.dev as a restricted user, only on the add family member form though (haven't tested the add family form as thoroughly).

**Comment by abbyad** [comment]
The condition on that `date` field is: `floor(decimal-date-time(.)) <= floor(decimal-date-time(today()))`

We have seen other issues (https://github.com/medic/medic-webapp/issues/1985) in conditions with `<=`.

**Comment by garethbowen** [comment]
I can replicate this in Chrome on the desktop but only if I set my system date back to "2016-03-05". I suspect the calculation isn't doing what we think it is. I'll do some more debugging.

**Comment by garethbowen** [comment]
I don't think `floor` is working as you expect it to here. It's almost as if it's doing a string compare? This calculation works more reliably in my testing:

```
decimal-date-time(today()) - decimal-date-time(.) >= 0
```

This is stolen from the [ODK documentation](https://opendatakit.org/help/form-design/binding/).

@abbyad Can you confirm and find and replace all date comparisons in the form configurations?

**Comment by abbyad** [comment]
Thanks for taking a look. The `decimal-date-time` function is meant to return the number of days since Jan 1, 1970, with the fractional part representing the time of day. The `today()` function that we use has changed from the Enketo way, which includes time, to the Collect way, which does not. Whether you include time or not makes a difference in these calculations.

Given that decimal-date-time is meant to return a numeric value, `floor` should be working. Also, we should make sure that the operator is working properly. If there is a limitation in these calculations I think we are better off fixing them because we are certain to have tech-leads writing up calculations with them.

**Comment by alxndrsn** [comment]
Please try with latest `develop`.

**Comment by abbyad** [comment]
Could not get a constraint error on 2926

**Comment by garethbowen** [comment]
@abbyad I found it really hard to reproduce this and the only way I found in the end was setting my system clock back to the date @SCdF reported he had problems with it. I think that'd be worth doing if you haven't already.

**Comment by abbyad** [comment]
Good to know @garethbowen. I had reproduced this easily the day it was reported, and hadn't realized it was dependent on today's date. Just tested again as March 5th and was not able to reproduce.

**Comment by garethbowen** [comment]
Awesome!

**Comment by alxndrsn** [comment]
This bug is so weird.  Possibly a date format with months & days swapped, or day of the week instead of day of the month??

**Comment by alxndrsn** [comment]
Removed my comment - thought this was another bug which wasn't already fixed!
