### ISSUE TITLE
Use es6 modules and rollup

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2035]
[es6 modules](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import) let you import part of a module instead of the whole thing, eg:

``` js
import {foo} from './helpers';
```

We can then use [rollup](https://github.com/rollup/rollup) to remove unused _parts_ of libraries to reduce the size of our JS files. There is a [browserify plugin](https://github.com/nolanlawson/rollupify) which should output one large commonjs dependency to work with current generation browsers.

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
This is dependant on the new UI framework and will be implemented at the same time.
