### ISSUE TITLE
Hour granularity on task schedule

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2037]
Investigate whether there are any cases that may present in the near future where we would need a task done by a specific time of day, not by end of day

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
Not sure if this is needed. @diannakane let's transfer this to medic-design. Closing.

**Comment by sglangevin** [comment]
Looks like it's already there.
