### ISSUE TITLE
After deleting a message you get to a weird empty page

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2040]
Starting from a conversation, if you delete a message, you get to the page for the contact, I think.

(in these the contact being messaged is called "aaaaaaa")
1 - start in a conversation page
![screen shot 2016-03-08 at 11 13 17](https://cloud.githubusercontent.com/assets/911434/13595880/e5df0e90-e51f-11e5-86f1-7afbcb6ca7b8.png)

2 - delete one of the messages, you get there (url is `<server>/medic/_design/medic/_rewrite/#/messages`)
![screen shot 2016-03-08 at 11 14 09](https://cloud.githubusercontent.com/assets/911434/13595896/ff6aa180-e51f-11e5-8630-ad60806c439f.png)

3 - Tapping the back button gets you back to the messages list.
![screen shot 2016-03-08 at 11 14 18](https://cloud.githubusercontent.com/assets/911434/13595909/1af6b736-e520-11e5-87e9-94e8c3cc76df.png)

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by estellecomment** [comment]
Can't reproduce. Closing.
