### ISSUE TITLE
Potential memory leak with our use of PouchDB

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2041]
I have created heap snapshots, dumps and CPU profiles of all this. I will upload them to drive once I have the bandwidth to do so, and link them here.

To reproduce:
 - (potentially) connect to a remote host like lg-testing
 - Clean your android install
 - Configure the app to point to and log in as someone who has production-levels of data. I.e. more than demo on lg.dev
 - Let the whole thing sync. Feel free to hang out on the about page, which should be doing nothing at all.
 - Once the sync is complete, note that:
 -- The CPU is still doing a bunch of stuff. A pull from the profile I took looks like this:
![image](https://cloud.githubusercontent.com/assets/583851/13597765/493b1abe-e52b-11e5-85c3-c033295a2237.png)
![image](https://cloud.githubusercontent.com/assets/583851/13597788/619030d6-e52b-11e5-9f76-53b87be2287d.png)
-- Moving around the application is incredibly slow. Various tap indicators (the tab icon changing colour, the highlight on selecting a form element) can take many seconds to appear.
 - Force close the app. You can do this by removing it from the task manager or by going into the application settings page and actually force closing it. Interestingly `location.reload()` doesn't seem to be enough, though I should test that more.
- Open the app again. Note that once it's done initial loading it's lightning (ish) fast.

Here is a screenshot of the samples I took. The only interesting thing to note is the heapdump sizes on disk:
![image](https://cloud.githubusercontent.com/assets/583851/13597963/4f4c49d6-e52c-11e5-89dd-82ce29913f96.png)
So we're looking at ~100mb after a sync, ~50mb fresh after re-opening, and ~70mb after clicking around and having it cache forms and what-not.

**Comment by SCdF** [comment]
So I'm not completely sure if this is an issue. It seems to clear up after leaving it running for awhile (in my case a couple of hours). This implies perhaps that Pouch is doing a bunch of work in the background that it eventually gets through, though why it wouldn't restart that work if you refreshed (implying it's not in a queue and isn't actually important) is beyond me. It's also unfortunate because the CHP has no idea why it's running slow, it just is.

The main concern at this point I suppose is whether or not this kind of thing only occurs when we're smashing Pouch that first time, or on normal app usage.

**Comment by garethbowen** [comment]
I imagine the initial replication is a fairly big deal, particularly because it fires a bunch of events throughout the UI. If we can delay bootstrapping until the initial replication is complete it might perform well as soon as you can see the app... 

Yes there are lots of qualifiers in that comment. YMMV.

**Comment by SCdF** [comment]
I'm closing this. I couldn't find anything definitive, and we can always re-open it etc if we come across it again. I think the gist is that Pouch does a lot of work in the background when we first sync. We may be able to make that more optimal by either structuring our replication more cleverly (ie pull then push in the hope that makes push less chatty and Pouch less CPU-a-riffic) or by contributing to Pouch directly. But importantly, it's not actually leaking anything obvious.
