### ISSUE TITLE
FBB button does not work for (missing) contact form on desktop

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2042]
FBB button does not work for (missing) contact form on desktop; this appears to be because `div.bootstrap-layer`:

<img width="1280" alt="screen shot 2016-03-08 at 13 38 31" src="https://cloud.githubusercontent.com/assets/191496/13599284/22b67e8a-e533-11e5-8e99-b9997c6a5f9a.png">

Not yet checked on mobile.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Not sure what FBB is. 
There is a "X" button which enables you to navigate away, that looks appropriate to me until you get your contact form configured, so closing.
