### ISSUE TITLE
Cannot add contact unless a contact is selected

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2043]
The Add Place button only works if you have a contact open. That means that if you go to the [Contacts tab](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/) and click `Add Place`, nothing happens because by default a contact is not selected.

**Comment by abbyad** [comment]
Based on @garethbowen's experience this seems to be a very recent regression as he saw it work, then updated the webapp and it failed.

**Comment by abbyad** [comment]
This is actually a bigger issue than originally thought because in mobile mode you cannot add a family. Adding the Priority label.

**Comment by abbyad** [comment]
Thanks to @sglangevin for the tip to scroll down:
![image](https://cloud.githubusercontent.com/assets/789512/13651808/fd1ff400-e616-11e5-9c53-74ca1f63aff2.png)

**Comment by abbyad** [comment]
And in desktop mode for fun:
![image](https://cloud.githubusercontent.com/assets/789512/13651866/46e49320-e617-11e5-8881-6db7dee3f9ea.png)

**Comment by alxndrsn** [comment]
Is this just for admins?  Likely be caused by #1900

**Comment by garethbowen** [comment]
As @alxndrsn said, this is caused by one of the commits in #1900 . I've reverted it to get this working again.
