### ISSUE TITLE
Create a limited user-editing API for security-sensitive fields in the _users database

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2047]
We need an API for editing users. We need this because access to the `_users` database requires administrative privileges, and we don't want ordinary users to have these privileges.

In a call today, we decided that the API should cover only those security-sensitive fields stored in the user document in the `_users` database. We believe that other documents (e.g. contacts, user settings) can be handled adequately with normal document operations.

We also decided that we should move the untrusted/cached facility and/or role information out of `userCtx` and in to the `user-settings` document if at all possible. This will allow changes in user privileges to affect mobile devices without a logout/login cycle.

Here's our current API design:

```
POST /api/v1/users/{{username}}
Content-Type: application/json

{
  "password": "secret",
  “type”: “district-manager”,
  "place": "eeb17d6d-5dde-c2c0-62c4a1a0ca17e342"
}
```

Changes the password, user type, and/or associated place for a user. If `password`, `type`, or `place` is not provided, that field is not updated. This API should validate that the `place` already exists. This API may enforce password-strength standards.

```
DELETE /api/v1/users/{{username}}
```

Deletes the user document from the `_users` database, and the user-settings document from the `medic` database. Doesn’t touch reports or messages or contacts.

This issue is very related to #2046.

**Comment by SCdF** [comment]
> We need this because access to the _users database requires administrative privileges, and we don't want ordinary users to have these privileges.

FWIW you can add a role for this or a concrete user. You could totally just add a medic_admin role or something like that.

**Comment by garethbowen** [comment]
Comments in the PR.

**Comment by garethbowen** [comment]
Also it _might_ be useful to be able to take more than just sensitive fields? For example if you want to script to update the password and display name it would be a pain to have to call two different APIs. This is also true from the UI where if you're on a laggy connection it's much quicker and easier to send everything in one request.

**Comment by mandric** [comment]
Gareth also agree it seems weird to not be able to update any field.

**Comment by mandric** [comment]
I'm still not happy with error state on validation failure.  We get a 500 instead of a 40x.  Fixing...

```
curl -v -H 'content-type:application/json' -d '{"known": 3}' http://admin:secret@localhost:5988/api/v1/users/henry 

HTTP/1.1 500 Internal Server Error
known is not a boolean.
```

**Comment by mandric** [comment]
FYI two PRs are open here now, one for medic-api and one for medic-webapp.

**Comment by mandric** [comment]
Ok modified medic-api a bit so it respects the `statusCode` and `reason` properties defined in nano. 
HTTP/1.1 403 Forbidden
known is not a boolean.

**Comment by ngaruko** [comment]
Do we need to AT this @mandric ?

**Comment by mandric** [comment]
I don't think so because it's over a year old?
