### ISSUE TITLE
Make a checklist for creating AWS instances for projects

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2049]
We should have a basic checklist to go through when creating AWS instances. Once we have that we can focus on scripting this process, at a later date and in a different issue.

Adding the priority label since this should be verified this week ahead of travel for training session.

**Comment by SCdF** [comment]
@browndav to review doc that @abbyad made and then close

**Comment by ngaruko** [comment]
No AT needed?

**Comment by garethbowen** [comment]
Agreed.
