### ISSUE TITLE
Deleting Reports doesn't work on Microsoft Edge

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#2051]
Browser Version Used:  25.10586.0.0
![image](https://cloud.githubusercontent.com/assets/3198821/13634892/74128eaa-e609-11e5-9862-816eb8e5d35c.png)

**Comment by garethbowen** [comment]
A document update conflict means someone else changed the report at the same time so the delete request was rejected because couchdb wants you to verify that you still want to delete it. @henokgetachew Does this happen every time you try to delete on Edge or just this once?

**Comment by henokgetachew** [comment]
@garethbowen that was also my initial conclusion. However, this was happening every time you tried to delete a report with Edge. The PM responsible had to switch over to Chrome to get through the cleanup.

**Comment by garethbowen** [comment]
Closing as Edge is not currently a supported browser. Please raise a new issue for Edge support if required.
