### ISSUE TITLE
Select patient unbearably slow on tecno

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2054]
Using Add patient (because you're adding a report from History->Actions->Assess Patient etc) is incredibly slow on tecnos. 10s of seconds before you are allowed to select a contact.

This is exacerbated with larger data sets (ie prod), but in general (even with lg.dev data) it's very slow.

**Comment by sglangevin** [comment]
+1!

**Comment by garethbowen** [comment]
It takes about 6 seconds on my tecno on lg.app as the demo user loading the first page of the "assess patient" form. @SCdF Did I test it right?

**Comment by SCdF** [comment]
@garethbowen you'd want to try as a non-demo user unfortunately, as real demo users have a lot more going on.

**Comment by SCdF** [comment]
Looking at the code and timing it, it looks like the vast majority of the time (~5-6s) it's simply in PouchDB, calling the `doc_by_type` to get all the contacts back. This doesn't get faster over multiple calls or anything, this is just how long it takes (AFAICT) for PouchDB to pull that data out of indexdb and create JSON data structures for it. On the surface it's not clear that we could make this any faster without changing the UI. The rest of the time (~1s) is what looks like taking that data and passing it to Enketo to render: https://github.com/medic/medic-webapp/blob/develop/static/js/enketo/widgets/db-object-widget.js#L133

**Comment by garethbowen** [comment]
I think we should change the UI to only start showing results as the user starts typing. Maybe we should only show after 2 or 3 characters. In the real world there are too many results for the full list to be useful anyway.

**Comment by SCdF** [comment]
So the three things I can think of right now would be:
 - Load the raw contacts into memory and cache them. Not sure this is a helpful direction to go in as it's unclear how much this flow (adding a report without already having a contact selected) is used.
 - Somehow refactor the contacts tab to also expose the loaded contacts and use that instead of calling Pouch. This would mean that if the contact tab has loaded this should be in theory instant, but again it's unclear if it's worth having the contacts tab also store the correct information to render this dropdown is worthwhile
 - Change the drop-down to a search combo box. I have no idea how well that plays with pouch (i.e., can it actually usefully reduce it's search results and thus time if you give it a partial search query) or whether we'd have to drop another technology in there

**Comment by SCdF** [comment]
@garethbowen yeah my concern about that is basically two things:
 - Do people actually use this flow? i.e. is it worth making awesome above other things
 - Does Pouch actually get faster with this? If the slow path is running a `doc_by_type` view call how is having a search going to make that faster?

**Comment by SCdF** [comment]
@sglangevin do you know if people / CHPs use this flow? I haven't directly seen any users use it. @estellecomment / @alxndrsn did you peeps see any usage in the field?

**Comment by garethbowen** [comment]
With your second concern it's fairly easy to test - do a `contacts_by_freetext` query instead with a 2 character query and time it. You can do this on the contacts tab by typing in the freetext search box.

**Comment by sglangevin** [comment]
I'm not sure that CHPs use that flow very often, but the slowness of loading that field also affects managers in the web app. E.g. I couldn't load the health_center-edit form in Uganda because it has two fields that load all the people and it was too slow, so the request failed.

**Comment by SCdF** [comment]
> do a contacts_by_freetext query 

Oh wow cool that's using Pouch. OK, I presumed contact search was done purely with Angular in memory.

**Comment by SCdF** [comment]
I've modified the code to a sort of "minimal effort" standard: the select is now populated when you first tap on it, meaning forms like editing a clinic (which loads three of these) will not try to do it all at once. I've also increased reliability by allowing the "tap to load" to be retried if pouch / couch fails for some reason (ie going to couch and the network dies).

**Comment by SCdF** [comment]
So that's step one to making this nicer. Two more options to look at:
 - Attempt to pull this from existing generated locations instead of pouch/couch, such as the contacts tab. The pros here is that this should / could already exist as JS objects somewhere in memory, so we don't have to pull from Pouch or over the network from Couch. The cons is that it's a bit gross architecturally to make the contacts tab a data provider
 - Look at changing the select2 implementation to pull from pouch / couch live based on your query. The pros here is that it makes the whole thing generally more usable, and that in theory you will have to load less data, either from Pouch or over the network from Couch. The cons is that I have no idea in practice if the "less data" bit is true: it may actually be generally more efficient to load the whole thing in one go and then just apply filtering.

**Comment by SCdF** [comment]
So I haven't noticed this before because I primarily use the techno for testing, but these dropdowns _already support searching inside them_, it's just that it doesn't currently work on mobile for some reason.

@estellecomment do you want to review the two commits I've done so far, I might also look into fixing the select on mobile and then probably leaving it at that.

**Comment by estellecomment** [comment]
LGTM

**Comment by SCdF** [comment]
I'm going to close this (since it has code that has been pushed into 2.6) and open a new ticket, in this sprint, for the next step of optimisations we can make to this piece of functionality.

**Comment by ngaruko** [comment]
Can I be assured that the above fixes have resolved the slowness or do I need to wait for a techno to do AT on the 'real' hardware? @SCdF @sglangevin

**Comment by SCdF** [comment]
@ngaruko I wouldn't bother ATing this, you're not going to have a frame of reference for how slow it was before anyway, and if we had regressed and got slower there is no reason to think it would be anything to do with this ticket.
