### ISSUE TITLE
select2 broken

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2056]
Loading an xform with a patient select field fails on initialisation.

![broken-select](https://cloud.githubusercontent.com/assets/2064938/13652120/5569d99e-e6af-11e5-8995-9a16dd8c9af7.png)

```
inbox.js:135649 Uncaught Error: undefined missing select2/dropdown/attachContainer
    main @ inbox.js:135649
    (anonymous function) @ inbox.js:135727
```

Undoubtedly related to removing bower.

**Comment by estellecomment** [comment]
LGTM
