### ISSUE TITLE
Do not block the UI on network access

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2057]
We recently started showing a loading layer until DB sync completes. This works fine when you're online but with a slow/spotty/non-existent connection will cause the app to be unusable until the replication request times out (30 seconds). This is an unacceptably long delay and breaks the offline first design of our app.

We need to remove the dependency on DB sync, and if possible find a way to wait for the app to be warm without network requests.

**Comment by browndav** [comment]
Maybe we could monitor the connection state via the container app, and skip/abort the sync if we're both in a container and the link has gone down?

**Comment by garethbowen** [comment]
Working out if the link has gone down is essentially a halting problem - the request may come back within 1 second or 100 seconds.

First run is a completely different kettle of fish because we know there's no point loading the UI with an empty DB. But every time we open the app after that we should as soon as possible show the current data.

I guess what I'm saying is the state of the network is not a good indication of whether the local DB is warm.

**Comment by alxndrsn** [comment]
We could turn the timeout down to 10s (equal to the couch heartbeat).  You still have to wait for DB warm-up, which takes about 30s on Tecno.

**Comment by garethbowen** [comment]
I'd like to find some other way to detect when the database is warm that is related to the database, and not the quality of your internet. As far as I can tell these two are completely unrelated issues. I propose we remove the blocking on DBSync and leave the blocking on the TaskGenerator. I think that'll prove to be a much more accurate measure of DB warmness.

**Comment by alxndrsn** [comment]
> I'd like to find some other way to detect when the database is warm that is related to the database, and not the quality of your internet.

Currently `TaskGenerator.init` and `DBSyncSrv`'s initial replication run in parallel.

> As far as I can tell these two are completely unrelated issues.

Agreed, which is why they can run simultaneously.

> I propose we remove the blocking on DBSync and leave the blocking on the TaskGenerator.

If there is no connectivity, or no data to sync, then `DBSyncSrv`'s initial replication and `TaskGenerator.init` will take approximately the same amount of time, so making this change would not improve startup speeds.

**Comment by garethbowen** [comment]
> making this change would not improve startup speeds.

It will certainly improve startup speeds with certain CPU/network combinations. I'll do some more investigation and come back to you.

**Comment by garethbowen** [comment]
For an example of how this can degrade performance, on my tecno accessing my desktop with nothing to actually sync I get this:

`Initial sync complete in 82.322 seconds, starting replication listener`

So the loading screen showed for 82 seconds when the db was already completely up to date and ready to go.

**Comment by garethbowen** [comment]
The code in question waits for DbSync and TaskGenerator to initalise. I'm proposing to wait solely on TaskGenerator which doesn't require network access, and is a good approximation for the DB being ready to render the UI. Here are the possible scenarios...

1. DbSync completes quicker than TaskGenerator. In this case the existing code and the proposed code behave identically.
2. TaskGenerator completes quicker than DbSync. In this case the proposed code would render the UI before the current code. I prefer this because syncing the DB doesn't block the UI like DB initialisation does, so there's no need to stop the user being able to use the device. Once exception to this is first run because the app isn't usable until the docs are up to date. This is a special case and we can (and should) block only on first run.

With the proposed code the app will be usable as soon or sooner than the current code.

My concerns with the current code are...

1. Blocking unnecessarily sometimes (as above).
2. If more powerful phones are used then the TaskGenerator will finish much sooner but the app will still be unnecessarily blocked on a poor connection.
3. The current code breaks our offline-first design.
4. This could seriously block users. For example, if a CHP hasn't been online for a while and there's a lot of syncing to do. If they go to visit a patient and want to submit a registration they will be blocked until all the replication is complete which could be a very long time on a dodgy connection. There's no reason why they should be blocked from filling in a registration form just because their DB is behind.

@alxndrsn @SCdF Thoughts?

**Comment by alxndrsn** [comment]
I agree that blocking on `TaskGenerator` only is preferable.

**Comment by SCdF** [comment]
I agree. The only thing I'd say is that it does mean that if there is new data to be synced that would generate tasks (for example), the app will boot (potentially) before those tasks are generated.

Honestly based on how people tell me the app is used this is very unlikely so I don't think this is a concern for now. I would love it though, if the users could easily tell visually (red / green or yellow / invisible dot for example) whether or not the expectation is that everything is downloaded and ready for them to use).

**Comment by garethbowen** [comment]
I did a bit of a refactor while in there to try and clean up InboxCtrl a bit. Hopefully it makes sense.
