### ISSUE TITLE
Add a CHW role

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2058]
We have roles for national admin, district admin, data entry, analytics, and gateway. Until we developed the mobile app we didn't have CHWs logging in so this was sufficient. Now we should add another role for CHWs so they can have different permissions than their supervisors.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
This can wait until we do a refactor of roles and permissions. Currently planning to do that next quarter.

**Comment by garethbowen** [comment]
Closing so it can be done as part of the refactor.
