### ISSUE TITLE
Network problem during Application Cache fetching -> app stuck

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2059]
On first load, I disconnected the network during the application cache fetching. It errored and stopped and the app got stuck on the splash screen. 
Swiping app fixed it, the app cache resumed properly.

![screen shot 2016-03-10 at 10 58 58](https://cloud.githubusercontent.com/assets/911434/13664853/8ce1d2ea-e6ba-11e5-92e6-5ffa9428aa0e.png)

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
I haven't heard this reported by any users so far. Closing, we can re-open if it becomes a bigger issue.
