### ISSUE TITLE
Strange error when not logged in

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2060]
# Steps to recreate

1. check out latest api (c1b5eeb09ee6e809566409bfee3499a55ba761b1) & webapp (040f55772a666c316295dfd01910cc22cd1719aa)
2. open a fresh browser and open the javascript console
3. point browser to http://localhost:5988/medic/_design/medic/_rewrite#/tasks/
3. observe error:
<img width="609" alt="screen shot 2016-03-10 at 11 07 18" src="https://cloud.githubusercontent.com/assets/191496/13663124/723362b0-e6b0-11e5-8a49-333f36f65608.png">

**Comment by garethbowen** [comment]
Doesn't happen for me. It might be fixed, or a race condition?

**Comment by alxndrsn** [comment]
Can't recreate here either.
