### ISSUE TITLE
Filter bar missing

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2061]
Seen on latest webapp (040f55772a666c316295dfd01910cc22cd1719aa):

<img width="1280" alt="screen shot 2016-03-10 at 11 09 27" src="https://cloud.githubusercontent.com/assets/191496/13663155/b6a6fa60-e6b0-11e5-83b9-839182c91462.png">

**Comment by garethbowen** [comment]
Have you seen this again? Any replication steps?

**Comment by alxndrsn** [comment]
No, haven't seen this again.
