### ISSUE TITLE
Dates on Reports list are one day different from reports-content

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2063]
Look at the date a report was submitted in the _History_ tab, and then look at the date the report was submitted in the `ReportsContentCtrl` - they seem to be a day out:

N.B. We saw this on a live app v `2872`, but not on latest `develop`.  May be a timezone issue!

**Comment by SCdF** [comment]
Specifically, today (March 10th) the main page said today for this report, whereas inside the report it says it was filed on `Wed, Mar 9th, 2016 at 2:32PM`

**Comment by garethbowen** [comment]
I think this is fixed at the same time as #1757 - essentially it'll now say "yesterday" instead of "today" in the example Stefan cited.
