### ISSUE TITLE
It is not clear to users that targets are calculated on the server side

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2064]
Some feedback we have received. 

Fun fact: some CHPs (~50% of test group) turn off data while they are working, and then turn it on again to sync at certain times.

This has led them to see their targets not updating (because you need to sync to the server), which is confusing.

Once they understand it seems fine, but it sounds like **we should make it clearer that only reports that have made it to the server are taken into account for targets**.

There are umpteen ways this could be achieved, from a note, to an indication that there are N reports that haven't yet been taken into account, etc.

**Comment by estellecomment** [comment]
Interesting! 
Why do they turn off data?
Where/how do they turn it off? I thought the settings were password-locked.
How often do they sync? Does it depend on where they are, or on something else?

**Comment by alxndrsn** [comment]
N.B. we're not actually sure where the targets get generated, but there are some weird bugs in there.

**Comment by sglangevin** [comment]
I have also seen some weird bugs in targets but haven't been able to pin them down. I see them sometimes and not others and had trouble reproducing them reliably. It seemed like when I submitted certain reports the targets would clear or change.

**Comment by abbyad** [comment]
> we should make it clearer that only reports that have made it to the server are taken into account for targets

If we are talking about the Targets tab, then this is done *completely local*, as it is done by the rules engine. The Analytics Dashboard that the Branches use need the data to be sync'd to the server.

**Comment by abbyad** [comment]
Also, I think users turning off data unless they want to sync is a workflow we want to support. It can save battery life, and it is likely how they have been using their phones with the previous version.

**Comment by alxndrsn** [comment]
@abbyad thanks for the background.  Sounds like the rules engine may be misbehaving, as we also have some example of weird tasks turning up, or not turning up at all.

**Comment by SCdF** [comment]
OK as I misunderstood the issue I'm going to close this one and open a bug talking about how targets are not always being calculated correctly.
