### ISSUE TITLE
Update available message doesn't always show

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2067]
I can't get the "update available" dialog to show on my tecno any more.

**Comment by garethbowen** [comment]
This was due to comparing revs as strings, eg:

`"1138-3e55907c37e928ef94550bea51c0e9a8" >= "946-8bad4ec15b9a0caeb1698ef84bbdfc6d"`

This should return true because `"1138" > "946"` but of course because it's comparing strings returns false because `1 < 9`.

I considered parsing out just the bit before the "-" and doing an integer compare, but we shouldn't rely on the rev being sequential as this is an implementation detail (and I think it's going away in 2.0) so I switched to using `===`.

**Comment by browndav** [comment]
LGTM. Probably best to follow the server in the rare event we roll a server back to a previous build, too.

**Comment by ngaruko** [comment]
Was this a 'tecno' specific bug  or was it happening on other phones?

**Comment by garethbowen** [comment]
It was happening on all phones and even the desktop.
