### ISSUE TITLE
Unbranded container, first-run URL input: Once an invalid URL is tested, subsequent valid URLs fail

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2069]
If I install the unbranded container and get the server address right the first time, I see a request to `/setup/poll` that results in an HTTP 200, and all is well.

If I purposely input a server name that exists but responds to `/setup/poll` with a 404, I'll be told that it's not a valid application URL. Great so far.

If I _then_ try a known-valid server name after the failure immediately above, it too gets flagged as invalid despite the fact that it's a real `medic-webapp` server. On the server side, I see an HTTP 401:

```
127.0.0.1 - - [11/Mar/2016:00:49:49 +0000] "GET /setup/poll HTTP/1.0" - - "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 6 Build/MMB29Q)"

==> /srv/storage/medic-core/couchdb/logs/couch.log <==
[Fri, 11 Mar 2016 00:49:49 GMT] [info] [<0.5997.0>] 49.xxx.xxx.220 - - GET /setup/poll 401
```

An easy workaround it to just uninstall and reinstall the APK, but we should figure out what credentials are riding along with that `/setup/poll` request, if any, that are leading to the 401.

**Comment by abbyad** [comment]
A quicker workaround may be to clear the app data in Settings > Apps. It may also be sufficient for the app to reopen the app after a hard close (eg close it via the app switcher).

**Comment by alxndrsn** [comment]
Cannot recreate.

**Comment by browndav** [comment]
Easily recreated here; I'll provide specific reproduction steps and screenshots once I'm back from being sick.

**Comment by alxndrsn** [comment]
@browndav logging the full requests & responses server-side would be very helpful.  I can't recreate by sending a junk `Authorization` header to `/setup/poll`.  If the two servers you are using both have the same URL, then perhaps a cookie is getting set by the first request.

**Comment by browndav** [comment]
Haven't seen this happen again, and the UI is already much improved since this report. Closing.
