### ISSUE TITLE
Thousands of document GET requests when logging in as admin

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2073]
When logging in as admin we make thousands of GET requests to the server which is painfully slow.

![1k-requests](https://cloud.githubusercontent.com/assets/2064938/13692648/50ced26e-e7a8-11e5-8716-38f744c4771d.png)

**Comment by garethbowen** [comment]
This is because of the switch to using the worker-pouch adapter. Deep inside pouch it checks to see if the adapter type is "http" and if it's not it makes individual requests. I'll raise an issue against worker-pouch to fix this.

**Comment by garethbowen** [comment]
The worker-pouch doesn't play well with remote dbs, so I've turned it off for admins.

**Comment by browndav** [comment]
LGTM.
