### ISSUE TITLE
LiveList ordering functions must not return undefined

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2078]
The comparators defined in the LiveList service sometimes return undefined. This means all the ordering fails. I think this is because we have an expectation of what is valid input. The comparators should handle invalid input more gracefully.

Example result:

![random](https://cloud.githubusercontent.com/assets/2064938/13764701/144477c4-eab7-11e5-9ead-29b6b55d942f.png)

**Comment by alxndrsn** [comment]
:+1:

**Comment by alxndrsn** [comment]
On reflection, I don't understand why returning `undefined` from a live list's `orderBy` function would cause the error shown above.

**Comment by ngaruko** [comment]
May I ask what input generated the 'undefined' displayed above. Or in other words, how to reproduce the issue. Thanks @garethbowen

**Comment by garethbowen** [comment]
AT: Generate tasks with no due date and ensure ordering works as expected.
