### ISSUE TITLE
Can delete reports even when `can_delete_reports` permission is not granted

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2080]
# Observed

(Logged in as `admin`, who I _assume_ has the **Full Access** role.)

<img width="1280" alt="screen shot 2016-03-15 at 10 44 54" src="https://cloud.githubusercontent.com/assets/191496/13770872/14056730-ea9b-11e5-89a0-3524c52c7060.png">
<img width="1280" alt="screen shot 2016-03-15 at 10 45 03" src="https://cloud.githubusercontent.com/assets/191496/13770873/140a0ed4-ea9b-11e5-88f6-336db212907f.png">
<img width="1280" alt="screen shot 2016-03-15 at 10 45 07" src="https://cloud.githubusercontent.com/assets/191496/13770874/141628b8-ea9b-11e5-9f48-0b35c6c8e303.png">

# Expected

I would not expect the `Delete` button to appear in the action bar if the user does not have the `can_delete_reports` permission.

**Comment by garethbowen** [comment]
DB admin is higher level of permissions again. The Auth service checks if you have the `_admin` permission and then immediately lets you through.
