### ISSUE TITLE
Deleting report forwards to a blank screen

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2081]
# Observed

On deleting a report, the new page is blank:

## Mobile

<img width="572" alt="screen shot 2016-03-15 at 10 47 55" src="https://cloud.githubusercontent.com/assets/191496/13770982/acee65fa-ea9b-11e5-933c-82ffa5f58179.png">

## Desktop

<img width="1280" alt="screen shot 2016-03-15 at 10 48 48" src="https://cloud.githubusercontent.com/assets/191496/13770979/a9f968e0-ea9b-11e5-8bea-a6a946314840.png">

# Expected

## On mobile

Should return to the list of reports.

## On desktop

Right pane read say _No report selected_.

# Notes

Related: #1900

**Comment by SCdF** [comment]
NB: CHPs are not able to delete reports, only admins.

**Comment by estellecomment** [comment]
LGTM, thanks!

**Comment by estellecomment** [comment]
Actually, this fixes mobile but not desktop. Still see a blank right pane. Reopening.

**Comment by garethbowen** [comment]
Closing this as a duplicate of #1900
