### ISSUE TITLE
Loading app sometimes fails!

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2082]
App sometimes fails to load on alpha dev:

<img width="1280" alt="screen shot 2016-03-15 at 11 08 11" src="https://cloud.githubusercontent.com/assets/191496/13771365/3db8d74e-ea9e-11e5-9cd3-dbfadff368e8.png">

URL does not seem important:

<img width="1280" alt="screen shot 2016-03-15 at 11 09 36" src="https://cloud.githubusercontent.com/assets/191496/13771379/73232164-ea9e-11e5-875d-230e41953ff2.png">

**Comment by garethbowen** [comment]
I haven't been able to replicate. The only thing I can think of is the inbox.js isn't being completely downloaded or the appcache is corrupt. Did you check the network tab?
