### ISSUE TITLE
On thin screens, can scroll off bottom of tasks list

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2083]
# Observed

Sometimes it's possible to scroll off the end of the tasks list.  This appears to only happen if the screen is thin enough:

<img width="380" alt="screen shot 2016-03-15 at 11 12 59" src="https://cloud.githubusercontent.com/assets/191496/13771439/f96dd25a-ea9e-11e5-9f19-f9d2315a08ab.png">

# Expected

Should never be able to scroll off the bottom of the list.

**Comment by browndav** [comment]
I thought I fixed this in https://github.com/medic/medic-webapp/commit/739137a1a99e26880f4065b56d95d62510eb8aea; were you testing against `develop`?

**Comment by alxndrsn** [comment]
Was testing on alpha.  Looks good on `develop`, thanks.
