### ISSUE TITLE
Show version of app_settings on _About_ page

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2084]
Show the version (`date_created`?) of app_settings/ddoc on _About_ page so that tech leads can compare two phones and check they are running the same version of app settings (and therefore same configs for Tasks and Targets).

**Comment by garethbowen** [comment]
One small comment on each PR.

**Comment by alxndrsn** [comment]
I'm not convinced the ddoc's `_rev` property will actually be the same across different devices.  @SCdF any chance you can review this?

<img width="475" alt="screen shot 2016-03-16 at 09 45 14" src="https://cloud.githubusercontent.com/assets/191496/13804182/f3800a30-eb5b-11e5-849f-286918eb2ea4.png">
<img width="374" alt="screen shot 2016-03-16 at 09 45 23" src="https://cloud.githubusercontent.com/assets/191496/13804183/f3d65a84-eb5b-11e5-8c19-808e9ad08509.png">

**Comment by garethbowen** [comment]
Oh you're right - I think you want `ddoc.remote_rev` which is where we store the revision of the ddoc on the server.

**Comment by garethbowen** [comment]
@alxndrsn Try that version.

**Comment by alxndrsn** [comment]
LGTM, thanks!
