### ISSUE TITLE
Images and other media are not working in enketo forms

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2089]
The substitution of images is happening before the HTML is cloned.

**Comment by alxndrsn** [comment]
This could be more efficient, e.g.

1. could cache the DB id along with the xmlCache
2. could substitute loaders before clone, and images after
3. could make internal and couch IDs identical

I think long-term 3 would be a useful improvement.

**Comment by garethbowen** [comment]
LGTM. Could this also be the cause of #2053 ?

**Comment by alxndrsn** [comment]
Good call.  Need to investigate #2053 anyway.
