### ISSUE TITLE
Cannot use Private Browsing mode in Firefox

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2090]
# Observed

<img width="1280" alt="screen shot 2016-03-16 at 11 00 01" src="https://cloud.githubusercontent.com/assets/191496/13806038/06b11118-eb6a-11e5-9612-9ebac5b664db.png">
# Expected

I would expect webapp should work in incognito mode for admins.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by alxndrsn** [comment]
Still broken:

<img width="1271" alt="screen shot 2017-04-18 at 18 54 03" src="https://cloud.githubusercontent.com/assets/191496/25142779/6edc86c2-2468-11e7-9071-64385d1ed966.png">

**Comment by SCdF** [comment]
Pretty sure incognito breaks as well? IIRC this is browser-level, because incognito modes don't allow you to properly use client-side databases. It should work with admin.

Also what is the reasoning around the security tag? Private Browsing or Incognito don't provide security benefits, they basically just delete cookies and local history when you close the tab.

**Comment by alxndrsn** [comment]
> Pretty sure incognito breaks as well?

You mean in Chrome?  I do most of my testing in Chrome private windows - thankfully it still works!

**Comment by alxndrsn** [comment]
Ref: https://github.com/pouchdb/pouchdb/issues/5641

**Comment by alxndrsn** [comment]
Looks like there are two potential workarounds for this:

1. detect firefox private browsing and use `pouchdb-adapter-localstorage` – _https://github.com/pouchdb/pouchdb/issues/4010_
2. "using PouchDB in a worker/sharedworker" – _https://github.com/pouchdb/pouchdb/issues/5641_

**Comment by alxndrsn** [comment]
This now locks up firefox so it has to be killed.

Nothing is shown in the console:

<img width="1274" alt="screen shot 2017-09-01 at 13 49 54" src="https://user-images.githubusercontent.com/191496/29968575-8f7925a6-8f1c-11e7-8a55-5d569adf9fd5.png">

**Comment by alxndrsn** [comment]
N.B. Pouch 6.3.4 itself appears to fail more gracefully in Firefox private browsing mode:

<img width="1271" alt="screen shot 2017-09-01 at 14 18 33" src="https://user-images.githubusercontent.com/191496/29969461-82aae69e-8f20-11e7-810e-3ddc79a952f9.png">

I guess we're doing something pathological in the DB service or bootstrap when the couch object fails to create.  Hard to put a breakpoint in for a page which never loads, though!

**Comment by alxndrsn** [comment]
<img width="640" alt="screen shot 2017-09-01 at 14 51 32" src="https://user-images.githubusercontent.com/191496/29970565-6e50f2e2-8f25-11e7-94bd-ece183cd21f7.png">

**Comment by alxndrsn** [comment]
May only be a problem in dev mode - 2.13.x deployed instances work OK.
