### ISSUE TITLE
Filter bar goes weird if you browse manually from form to About

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2091]
Filter bar goes weird if you browse manually from a form to the _About_ tab.

# Steps to recreate

9. open browser in "mobile mode"
1. Browse to a form, e.g. http://localhost:5988/medic/_design/medic/_rewrite/#/reports/add/postnatal_care
2. Browse to http://localhost:5988/medic/_design/medic/_rewrite/#/about by pasting it into your browser
7. observe weirdness in filter bar:

<img width="388" alt="screen shot 2016-03-16 at 11 29 01" src="https://cloud.githubusercontent.com/assets/191496/13806085/52413f0e-eb6a-11e5-9bdc-de58f35f0844.png">

**Comment by garethbowen** [comment]
Probably just need to clear it when loading About. It'd be worth checking the other controllers (Error, Configuration, etc).

**Comment by estellecomment** [comment]
Or have the reports ctrller clean it up before leaving.

**Comment by estellecomment** [comment]
Code looks good! Passing to acceptance testing, that's a bunch of changes.
(We need to write more tests to rely less on acceptance testing...)
