### ISSUE TITLE
Reports do not sort correctly when created after list has loaded

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2093]
# Steps to recreate

1. go to _History_ tab
2. create a report via Contact > Assess Patient
3. go to _History_ tab
4. observe reports are in wrong order:
<img width="1280" alt="screen shot 2016-03-16 at 12 29 59" src="https://cloud.githubusercontent.com/assets/191496/13807610/0a9a5358-eb73-11e5-9503-b9221cba65a9.png">

5. refresh the page and observe reports are now sorted correctly:
<img width="1280" alt="screen shot 2016-03-16 at 12 30 07" src="https://cloud.githubusercontent.com/assets/191496/13807614/0e96c7c0-eb73-11e5-8047-23a828c08029.png">

**Comment by alxndrsn** [comment]
Incorporates the fix from #2078, but fixes the bugs introduced by it :-)

**Comment by garethbowen** [comment]
@alxndrsn I don't see any code for review?

**Comment by alxndrsn** [comment]
Sorry, push failed!  Should be there now.
