### ISSUE TITLE
Local install stuck in bad state

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2095]
I can no longer load my local webapp in non-incognito Chrome:

<img width="1280" alt="screen shot 2016-03-16 at 15 56 12" src="https://cloud.githubusercontent.com/assets/191496/13812901/a15d9b1c-eb8f-11e5-9ddd-692d7e8fa4a7.png">

**Comment by SCdF** [comment]
Loads for me, pulled latest from develop for api and webapp, grunt dev'd webapp.

**Comment by alxndrsn** [comment]
Good.  I assume there's something wrong locally with the app-cached version.

**Comment by garethbowen** [comment]
For some reason it's requesting dependencies.js which no longer exists, which means your manifest is bad. Delete any dependencies.js you may have and then run `grunt dev` to rebuild and push the manifest?

**Comment by alxndrsn** [comment]
Seems to have fixed itself now.  I hope this can't recur for real users.
