### ISSUE TITLE
Cannot submit family survey after validation failure

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2097]
<img width="1280" alt="screen shot 2016-03-16 at 16 28 10" src="https://cloud.githubusercontent.com/assets/191496/13813719/29b97e78-eb94-11e5-8587-9f120d1f9dec.png">

**Comment by alxndrsn** [comment]
Looks like a missing `scope.$apply()`.  Would be nice if the enketo service wrapped its Promises properly.

**Comment by garethbowen** [comment]
Nice solution.
