### ISSUE TITLE
Contact history can get very long

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2098]
<img width="425" alt="screen shot 2016-03-16 at 16 30 38" src="https://cloud.githubusercontent.com/assets/191496/13813782/74558274-eb94-11e5-9d0f-92d1b45874bd.png">

**Comment by alxndrsn** [comment]
I think it's safe to worry about this later.

**Comment by garethbowen** [comment]
Closing. There's a design issue in the pipeline that will resolve this.
