### ISSUE TITLE
don't emit docs in views

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2099]
It bloats the indexes.  See `packages/kujua-sms/kujua-sms/views.js` and check other views.  Use `include_docs` instead in the queries.

**Comment by garethbowen** [comment]
medic-data is broken but I think it was broken before my commit. I only committed to develop but the beta build is also broken. Everything else should work.

**Comment by mandric** [comment]
Should i fix medic-data before we close this?

**Comment by mandric** [comment]
Nevermind I see the commit is innocuous.

**Comment by mandric** [comment]
Skipping acceptance testing here since I see no way to define testing it other than just get the app in general use.
