### ISSUE TITLE
Display: block in or-appearance-h2 is overriding the disabled class

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2101]
This causes elements to appear on the page that should be disabled. See screenshot. Should only see either Cough or Pneumonia. 
![image](https://cloud.githubusercontent.com/assets/1286381/13874035/4b041e80-ed06-11e5-834a-53411e28371b.png)

**Comment by alxndrsn** [comment]
@sglangevin is this issue still current?  If so, should it be higher priority?

**Comment by sglangevin** [comment]
This is no longer an issue. Closing.
