### ISSUE TITLE
Support b and em in the appearance column

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2102]
Add or-appearance classes for b and em so that these can be used in the appearance column in xls forms.

**Comment by alxndrsn** [comment]
@sglangevin a couple of queries about this one:

1. do you still want this?
2. iirc, tags listed in `or-appearance` will convert to a style rule called e.g. `.or-appearance-em`, which we would then define in https://github.com/medic/medic-webapp/blob/develop/static/css/enketo/medic.less.  Would it be more complicated to use the HTML for `<em>` or `<b>` in the label content in the XLS?

Also I'm not sure what our app supports in terms of `strong`, `em`, `i`, `b` right now, but I suspect the combination would be either `strong` and `em`, or `b` and `i`.

**Comment by sglangevin** [comment]
@alxndrsn I ended up just including these in-line, which I think is fine for now. We can look into adding this later, but I don't think it's necessary.

**Comment by alxndrsn** [comment]
Closing this as it doesn't sound like it's required.  If this was for a `label`, you should be able to include markdown such as `**bold**`.
