### ISSUE TITLE
Updating the primary contact's phone number doesn't update the phone number associated with the family

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2104]
Since we display the phone number in follow-up forms, this means that if a CHP doesn't add the phone number at the time of registration, then the phone number for the family isn't stored in the DB. If I update the phone number from the primary contact's profile page, the phone number is associated to that person but not the family. This means that the CHP will not be able to call a parent to follow up on an assessment unless she added the mother's number during registration.

**Comment by abbyad** [comment]
This seems to be resolved by https://github.com/medic/medic-webapp/issues/2635. 

@sglangevin can we close this in favor of the other?

**Comment by sglangevin** [comment]
Sure @abbyad - closing now.
