### ISSUE TITLE
Language selection modal appears when loading lg.dev

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2107]
Haven't seen this one in a while but the language selection modal seems to have reappeared. It needs to be removed.

**Comment by sglangevin** [comment]
From further testing, seems like the language of users wasn't set during creation via the API. I believe that has been fixed or will be fixed by @mandric.

**Comment by garethbowen** [comment]
@sglangevin Can we close this now?

**Comment by sglangevin** [comment]
Yes - we can close this, though I'd like to open another issue for a similar problem, which is that creating users with the UI doesn't set `known = true` so the tour pops up when you log in on. This isn't a big deal on the web app, but it is a pain on the mobile app because clearing tour on mobile doesn't update the user doc so the tour keeps coming up.

**Comment by mandric** [comment]
Shit still need to do this: https://github.com/medic/medic-webapp/issues/2048

**Comment by sglangevin** [comment]
Ah ok, so we have an issue for that already then - I'll close this one in favor of #2048.

**Comment by garethbowen** [comment]
Raised #2423 to cover the tour always popping up.
