### ISSUE TITLE
Initial replication has status: failed on lg.dev

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2108]
Seeing this when logging in as totxx users. However, everything loads normally. It might be related to the below error messages. Reloading I don't see any errors.

![image](https://cloud.githubusercontent.com/assets/1286381/13900209/c48bfad2-ee11-11e5-920d-b47507c99ef3.png)
![image](https://cloud.githubusercontent.com/assets/1286381/13900212/d7358d9c-ee11-11e5-90ff-675e14c410ca.png)

**Comment by garethbowen** [comment]
This is not necessarily a bug - for example if the internet connection dropped then the initial replication will fail.
