### ISSUE TITLE
Put Low Fidelity Stats On Facility Reporting Selection Page

### ISSUE THREAD

**Issue by wombleton** [medic/medic-webapp#211]
It should be possible to show low fidelity stats for each facility/form combination on this page: 

![auzf0-0g3ifgxgb-sy1pbdg1g65qslikeo5cqkycmwo](https://cloud.githubusercontent.com/assets/25641/2863150/3d4e2c2c-d200-11e3-8318-e0ee857a3096.png)

**Comment by SCdF** [comment]
@SCdF please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by SCdF** [comment]
Confirmed with @browndav, this is only relevant to an ancient version of our software, so it's totally closable.
