### ISSUE TITLE
app-settings GUI is bad

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2112]
There are plenty of sub-issues in that one. The app-settings editing GUI in Dashboard is useful for smaller tweaks. Bigger changes are often done in the json, because the GUI sucks (and also probably out of personal preference for code vs. GUI, that's something we should vote on.).

There's also a question of whether Dashboard/Gardener will go away - but I'm guessing there will still be settings somewhere, so the GUI still needs fixing. (if that's not true speak up)

Quick list : 
- [ ] Make the sections collapsible
- [ ] Provide a Table of Contents (TOC) at the top of the page
- [ ] Save button is waaaaaay down, that's a lot of scrolling
- [ ] Make hierarchy clearer, it's hard to tell what's the next section vs. a child section : bigger indentation and clearer UX
- [ ] For repeated fields, the `remove`/`add`/`clear` buttons aren't clear, you delete sections by mistake
- [ ] Allow editing of sub-sections directly in JSON : e.g. schedules are convenient to copy-paste because messages are often repeated, so editing the JSON is convenient. Avoid having to download the whole settings, and allow in-place JSON editing and saving for the sub-sections. (that one is more work and may or may not be priority)

**Comment by estellecomment** [comment]
- [ ] Jumping to a setting would be nice

Tabs could also be an alternative to collapsible sections.

**Comment by garethbowen** [comment]
My vote is to do more and more configuration in custom built UIs until nobody needs to use the Dashboard app settings UI any more. As far as I'm concerned a feature is not "done" until it has an easy way for tech leads to configure it, and I don't consider the Dashboard app settings UI or scripts to be easy.

**Comment by alxndrsn** [comment]
Seems foolish to suggest, but a couple of potential solutions:

> Jumping to a setting would be nice

Can this be achieved with `ctrl-f`/`command-f`?

> Save button is waaaaaay down, that's a lot of scrolling

Does the `end` key help here?

**Comment by estellecomment** [comment]
Yes, in practice that's what people do. I would `ctrl-f` the `Save` button for instance. 
The one's I'd prioritize are making the hierarchy clearer and repeated fields buttons.

**Comment by mandric** [comment]
Possibly related https://github.com/garden20/dashboard/issues/13

But I also agree with Gareth, unless we want to get into the business of maintaining a json-schema editor.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
@estelle @marc pretty sure nobody manages their settings via dashboard anymore or expects it to work properly so we can close this?

**Comment by garethbowen** [comment]
@mandric My understanding is actually surprisingly many people still use dashboard app settings.

**Comment by abbyad** [comment]
Although it is possible that some people use the GUI, I dont think that we need to improve it right now. We are currently reviewing our config processes and I haven't yet seen a case for making the edits in dashboard. The app's configuration pages are sufficient for users that need a UI, and tech leads are trained to use our scripts with JSON files to update app_settings. Although it is handy to occasionally view the app settings GUI, I don't think we need to work on improving it right now. 

I would close this and reopen new issues once we decide which features/changes are needed for those doing configuration moving forward.

**Comment by SCdF** [comment]
> I would close this and reopen new issues once we decide which features/changes are needed for those doing configuration moving forward.

Agree. I think in general big bucket issues are far too easy to constantly put off, and this one is no different. Closing,
