### ISSUE TITLE
Editing forms is painful

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2114]
We save forms to github in medic-projects, for version-control.

We save the .xlsx, because that's the root source of both JSON and XML formats. 
We also save the xml and/or json, because github stores xlsx as raw format and won't do diffs on it, so we need the xml/json to get the diffs.
That means you have to reupload several formats of the same data when you edit, and watch out to keep the different formats in sync. Not sure which format is the reference if they get out of sync.

For JSON, you can't change a single form in the webapp : you have to download the big file of all forms, edit the one form you want, and reupload the whole file of all the forms. 
It happens once in a while that you upload a single form by mistake (instead of whole list), and thus erase the instance's other forms. So you have to make sure you download a backup first, or that the lastest version is the github version. 
Single-form editing would be nice.

**Comment by SCdF** [comment]
A tl;dr; of feedback I got back was: being able to bulk upload is great, not being able to single CRUD afterwards is not great.

**Comment by alxndrsn** [comment]
Is this issue a direct consequence of https://github.com/medic/medic-webapp/issues/2115?

**Comment by estellecomment** [comment]
Not really, 2115 is about creating forms the first time, this is about editing them.

**Comment by alxndrsn** [comment]
Ah, I had read #2115 as being about the difficulty of getting a spreadsheet form into an application instance, which would presumably make both initial creation and later edits to a form cumbersome.

**Comment by estellecomment** [comment]
Oh I see. Yes, it's related in that way.
Additionally, this issue is about tracking changes, and small edits which are harder than necessary.

**Comment by estellecomment** [comment]
Open for too long. Closing.
