### ISSUE TITLE
User configuration UI doesn't correctly load the attached contact / locale

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2116]
**Edit:** Keeping the original description for history, but the actual issue is that the contact configuration UI doesn't seem to load some values correctly (attached contact / locale) so that when you make changes those values get unset. FWIW I think we should check password as well, because I think that might have similar issues.

----

To create a user, each user needs:
- _users/org.couchDb:ExampleUser
- medic/org.couchDb:ExampleUser
- medic/someRandomContactId

It looks like (@sglangevin can provide more info) the contact is created **but not attached to the medic user**. This makes the user invalid wrt creating forms.

The default language is also not set correctly.

cc. @mandric

**Comment by SCdF** [comment]
Talking to @abbyad it sounds like there may not be a bug with the script / code for user creation. The actual issue is that the contact does not correctly attach in the UI, so when @sglangevin updated the locale in the UI the contact wasn't attached, and so it saved the user and detached the contact.

**Comment by sglangevin** [comment]
Thanks for adding that, @SCdF - I realized this when I updated all of the associated contacts and their languages became unset :)

**Comment by mandric** [comment]
@SCdF I fixed one bug in the user creation process in develop, where the person type was not being set. https://github.com/medic/medic-api/commit/049957ce2df46decce3613766bfc3cc07ea5c982  But haven't merged that to testing (beta) yet... maybe we should do that now and then you can update and test again on lg.dev if you want.

@sglangevin I was editing users fine in the UI, maybe open another issue since these two things might have got conflated.

**Comment by mandric** [comment]
@SCdF I just merged that fix to testing (beta) you can update if you want when the build is finished.

**Comment by sglangevin** [comment]
Can you guys please not update lg.dev this week?

**Comment by mandric** [comment]
Roger

**Comment by garethbowen** [comment]
I think this is fixed now. Closing for acceptance testing.

**Comment by ngaruko** [comment]
Moving this to ready. User creation issues will be further addressed in #3067 and #3066
