### ISSUE TITLE
When configuring triggers, you can't know if it works until you see messages

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2117]
When the user sends in a form, actions are triggered : generate a reply message, generate user ID, generate schedule of future followup messages, etc.

These triggered actions are configured in [app-settings](https://demo.app.medicmobile.org/dashboard/_design/dashboard/_rewrite/settings#/apps), while the forms are defined in JSON and uploaded into [forms tab](https://demo.app.medicmobile.org/medic/_design/medic/_rewrite/settings#forms). 
The two have to match for the triggering to work : the fields in the form have to match the fields in the trigger settings (fields have to be present and the names have to be the same). 
If they don't match, your trigger will fail silently, there is no validation in the GUI and there is no error message when trigger fails. The only way to know whether your config is good is to trigger the workflow and watch for messages. If you don't see the expected messages, edit the config and repeat the process. That's long and painful.

Would be nice to avoid having to re-specify the form fields in the triggers config. Since the form name is specified already, we could fetch the necessary fields from the form, that way they'd match every time.

Alternatively, at least displaying a validation message when the fields don't match or are missing.

**Comment by estellecomment** [comment]
Priority : 3/5
PMs are supposed to test this, but TLs are nervous that it hasn't always been tested properly, and that if there's a problem at month 6, we won't know until a pregnancy hits month 6. So quality control issue.

Manual testing process : 
For auto-replies, it's easy to see. 
For schedules, you need to change the synthetic date in the settings, and if there's 5 messages for each of the 9 months of pregnancy, have fun doing that.
Alternatively, below each report, there's a list of messages scheduled to go out. They have dates, so you can look through that to check the schedules work. It would help tremendously to add date format like "30 days from LMP".

More automated testing would also be smart.

**Comment by estellecomment** [comment]
@ngamita also confirms automated testing of configs would be helpful.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by browndav** [comment]
Proposal: mark this issue as superseded by https://github.com/medic/medic-webapp/issues/2503, which will provide a testing framework for Nools rules in general. Please reopen if you disagree or have questions.

**Comment by browndav** [comment]
@estellecomment: Assigning over to you quickly just in case I forget to mention it on the call. If you agree with the approach, feel free to just unassign.
