### ISSUE TITLE
What fields can you use in message templates?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2118]
When creating scheduled messages, you can use existing fields like `{{patient_name}}` or `{{patient_id}}`.

Eugene and myself ran into a situation where `patient_id` wasn't appearing in the sent message, but we didn't know why. 
We should specify what the list of available fields is, and where they come from, right now it's a black box.

It's also unclear if some field names in forms have to match the pattern : should your patient name field in your form always be `patient_name` for it to work? What about `patient_id`? `lmp_date`? Other fields?

**Comment by mandric** [comment]
The list of available fields is based on the form fields and the generated fields.  So fields like `patient_id` and `edd_date` are hard coded, if you have the same field names in your forms there will be a conflict.  We don't handle conflicts yet.  

Wherever you are editing the schedule data there should be some documentation on what the generated field names are.  If you look at the raw document any property name on the doc or in the fields property should be accessible from a schedule message/template.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Documented in https://github.com/medic/medic-docs/blob/master/configuration/variables_in_messages.md#variables-you-can-use-todo
