### ISSUE TITLE
SIMapp file building only works on Windows

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2119]
To generate the .trb file to push on the SIMapp, you need an old version of gcc (because the whole simapp is not supported any more by Bladox). The official supported tools are on windows.

PMs are on windows. TLs are on linux or macos or windows. 

The workflow right now is to download the tools, and then : 
- on windows, run [cygwin](https://www.cygwin.com/) (basically linux tools for windows), and build.
- on linux, run a windows VM, run cygwin in the windows VM, and build. (linux on windows on linux! True story.)
- on mac, you can try using old versions of gcc, Eugene tried to get that to work and got stuck. Otherwise go the VM way too.

Another option is to run a VM with medic-os in it, because the appropriate tools are all packaged in it. However, we ran it in VirtualBox (because it's free), which doesn't get the USB ports right, so we couldn't push the files to the simapp. Fail.

Note that the simapp is probably going to be discontinued, in favor of medic collect or full android app. We should assess how much work we should be putting into this workflow.

**Comment by estellecomment** [comment]
Note : 
- @browndav 's instructions for the process are here : https://github.com/medic/bladox-macosx/blob/master/README.compiler
 - @abbyad and @henokgetachew 's instructions for windows : https://docs.google.com/document/d/1ktVpR-Xzg4AEAUbQAmU1oyOc1Gm5M6MNK6Vc0Fh8eq4/edit

**Comment by SCdF** [comment]
@browndav do you still build them successfully on OSX?

**Comment by estellecomment** [comment]
Priority : 4/5
@bishwas-medic especially needs this, he works a lot on SIMapps, and has to ask Henok to build the file, so that he can load it to the SIMapp.

**Comment by alxndrsn** [comment]
> Another option is to run a VM with medic-os in it

Building on `medic-os` seems like the logical solution.  If it actually works, then I think the issue title is misleading.

**Comment by estellecomment** [comment]
We also talked about building on an AWS machine somewhere. That way we could set up the environment once and for all, and share it for everyone.

**Comment by alxndrsn** [comment]
> We also talked about building on an AWS machine somewhere. That way we could set up the environment once and for all, and share it for everyone.

...as long as internet is available :-)

**Comment by estellecomment** [comment]
Most of the time it is. All Tech Leads have internet, and with phone tethering and dongles you can get crappy internet in most places.
Whereas all Tech Leads don't have a functioning environment for building SIM apps : @bishwas-medic mentioned having to ask @henokgetachew for files every time the partner changed their forms, which added delays (+ time zone issues) and was a pain for both of them. And required internet, ironically!

**Comment by browndav** [comment]
Flashing parallel SIMs on Medic OS currently works. What doesn't currently work on Medic OS (and what I think Bishwas is probably reporting) is that there's no `avr-gcc` cross-compiler on there, so you can't actually build from source on that VM.

It seems like a reasonable first step would be to come up with a checklist for converting a bog-standard Debian install into something that has the proper GCC cross-compilation toolchain on it. Then we could (in approximate order of difficulty): (a) just have people use that checklist; (b) create an AMI and instance that's been set up with the checklist; (c) create an offline VM that's all ready to go; or (d) get the toolchain running on Medic OS so there's be a single VM for compilation and flashing/loading.

This is all complicated by the fact that the Bladox runtime libraries seem to need an older avr-gcc to not spew horrible warnings and errors. There's a Crosspack-AVR version for OS X that works out of the box, but that's not an ideal option at all for general use.

Want me to take a stab at (a) and then we could regroup?

**Comment by bishwas-medic** [comment]
Yeah, we'd be glad if you took a stab at option (a). That would make the current workflow for SIM apps much more efficient.

**Comment by erwagasore** [comment]
Here is a document complementary to the "Bladox for mac README" https://docs.google.com/document/d/1s59_P5dSczVWRsj6k5gMnV0EweXZX-lMhZQTvBBXsmw

I managed to build on mac once before I fried my board(tsim board) :(

**Comment by henokgetachew** [comment]
@erwagasore that's pretty cool!  I think we should move the document to github.com/medic/medic-docs repository so it's easily accessible.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
Yeah let's do it.

**Comment by sglangevin** [comment]
Closing for now. We're able to build on Windows and that is sufficient for us.
