### ISSUE TITLE
More complex test data is needed

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2121]
There are a couple scripts to upload test data to a 0.4 instance.
However the data is too simple, more is needed. 

@bishwas-medic mentioned you can’t upload dummy phone numbers for facilities.
Eugene asked about more complex data set : a woman who gives birth to a child who is then immunized

**Comment by bishwas-medic** [comment]
To elaborate on my point:
The reports without phone numbers attached to them are marked as Invalid Reports and Invalid Reports are not imported into the Google Sheet by the import scripts. So we'll have to assign a facility to each report manually. The test data ideally should be in hundreds atleast and assigning facility to each of them manually beats the whole purpose of having the test data and the import script.

**Comment by estellecomment** [comment]
Priority : 3/5
It's not so hard to fix the data-generating script to add phone numbers, you can provide them as arguments.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
There doesn't seem to be a great need for this, and it is for 0.4 which we are wanting to move away from. Closing.
