### ISSUE TITLE
If a CHP registers the same woman as pregnant twice, this counts as two registrations in Targets

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2123]
Ideally, Targets should only count registrations for unique women.

**Comment by estellecomment** [comment]
I guess you shouldn't be able to register a woman as pregnant twice, either? (unless I'm missing something about human biology)

**Comment by sglangevin** [comment]
Yeah, the second registration actually overwrites the first, and is a way that an EDD (estimated delivery date) can be updated. So you'll only ever have tasks for one pregnancy.

**Comment by garethbowen** [comment]
It looks like Tasks for pregnancies are overwritten by checking if the report is the most recent pregnancy in configuration, eg:

```
var newestPregnancyTimestamp = getMostRecentTimestamp('pregnancy');
...
c.reports.forEach(function(r) {
...
  visit.resolved = r.reported_date < newestPregnancyTimestamp
...
});
```

We should modify the Task configuration to remove these duplicates in a similar way. So something like...

```
        if (r.form === 'pregnancy') {
          if (r.reported_date === newestPregnancyTimestamp) {
            emitTarget('pregnancy-registrations', r, true);
          }
        }
```

This will solve the first part of the problem where on first load multiple pregnancies for a single contact will only count as 1 towards your target. However if after first load another pregnancy were registered, then the newer pregnancy target would be emitted and therefore count twice again, which leads me to the next part of the solution.

The target id should be based on the contact not the report. This means if another target is emitted it will have the same id and therefore overwrite the previous task.

These two changes made together will remove duplicates.

**Comment by sglangevin** [comment]
This was fixed a few weeks ago. Moving to acceptance testing.
