### ISSUE TITLE
Ensure .4 support for the adapter

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2125]
The XML forms parser might have become incompatible with .4 once contact support was added.

Prior to that, on a .4 system, the XML forms parser would iterate all 0 XML forms and trivially succeed.

I do have a kanso version check in place in one part of the contacts handling code. I probably just need to ensure it exists in all places contacts are handled.

**Comment by btbonval** [comment]
This might not be a hard requirement. Until it is, I'm going to backlog this.

**Comment by btbonval** [comment]
It looks like this is more important than previously thought. However, as a workaround, instead of running `/index.js`, run `/libs/couch2pg/mainloop.js`.

`/index.js` is a copy/paste of `/libs/couch2pg/mainloop.js` which also calls `/libs/xmlforms/index.js` to handle Contacts and XML Forms. For a .4 project, `/index.js` probably won't work, but `/libs/couch2pg/mainloop.js` will do all the same stuff and entirely skip all the 2.6 stuff.

**Comment by btbonval** [comment]
Generating tables and so forth is not done by the adapter for the .4 systems. We would need to automate the by-hand process documented in this README:
https://github.com/medic/middleware/tree/master/postgres

**Comment by btbonval** [comment]
Additionally, the old .4 systems still have masses of audit_records hanging around which slow the process down considerably. It might be worth adding this diff into the mainline to permanently skip audit docs.
```
--- a/libs/couch2pg/couchiter.js
+++ b/libs/couch2pg/couchiter.js
@@ -5,7 +5,7 @@ exports.extractFromCouchDump = function(dataString) {
     var data = JSON.parse(dataString);
     return resolve(data.rows.map(function (row) {
       // add placeholder for UUIDs with no doc (should such a thing exist)
-      if (row.doc === undefined) {
+      if (row.doc === undefined || row.doc.type === 'audit_record') {
         // placeholder in postgres to not fetch it every time.
         return { '_id': row.id, '_rev': row.value.rev, 'type': 'no doc' };
       } else {
```

**Comment by garethbowen** [comment]
This doesn't seem relevant any more. @SCdF Is there anything of value left in this issue or should it be closed as ancient?

**Comment by SCdF** [comment]
No good catch, we've supported 0.4 for awhile
