### ISSUE TITLE
Create script to extract pregnancies from existing v1.x MySQL database and create families/contacts/registrations appropriately

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2128]
LG has an existing system that tracks pregnancies, but does not provide a clear link between these pregnancies and person/family registrations. Write a script to extract all pregnancy data from the existing v1.x MySQL database, reformat it into a coherent set of documents that describes a pregnant person and their family, and add those documents to a properly-configured version of `medic-webapp`.

This script does not need to handle incremental loads, and will likely only be run against production once.

**Comment by alxndrsn** [comment]
@browndav where can i get a dump of this data?

**Comment by browndav** [comment]
On it.

**Comment by alxndrsn** [comment]
Should this script be creating CHP contacts and CHP area contacts?  If not, it will need to be able to look them up by `chpcode`.

**Comment by alxndrsn** [comment]
First bash at script done.

# Limitations:

It does not currently link data to specific `medic-webapp` users.  Although I expect this to be a requirement, it's not clear if this script should also be creating the user docs, the user place docs, and the user user docs.

The script currently assumes that the mysql database is on `localhost` at port `3306`.

No XML is generated for fake `pregnancy` form submissions.

Data is imported for pregnancies which should be completed by now.

The data is not uploaded by the script - it just outputs a mammoth JSON array, each element of would become a couch doc.

**Comment by browndav** [comment]
This looks good. Given that it's a one-off, using Groovy probably isn't a big issue IMO. A couple comments:

  - I think we can defer to the new [user creation API](https://github.com/medic/medic-api/blob/develop/API_v1.md#post-apiv1users) for creating CHP contacts and users.

  - Caveat: the new users API doesn't currently create the CHP area (reopened ticket: #2048).

  - Absent a quick fix for #2048, one option would be to resurrect the [sh-based user creation script](https://github.com/medic/medic-webapp/blob/develop/scripts/create_user#L66), and defer to the new users API in there for everything _but_ CHP area creation.

  - I don't think we want to create users/contacts or use the user creation API from within the Groovy script, since we'll definitely have cases where we're importing data for already-existing users. Wondering if it makes sense to just separate out the user/contact creation to another script (still using the v1.6 MySQL instance as a data source).

  - If we could assume all of the user/contact creation was done up front, we'd just need to provide the Groovy script with a username mapping (or equivalent naming convention) AFAICT, then pipe the generated JSON that refers to those already-existing users right in to CouchDB.

Any objections to a two-step process like this? @mandric, what do you think about the proposed addition to #2048?

**Comment by abbyad** [comment]
> Caveat: the new users API doesn't currently create the CHP area (reopened ticket: #2048).

The reopened ticket is #2046

**Comment by browndav** [comment]
Fixed, thanks.

**Comment by SCdF** [comment]
We should wait for #2046

**Comment by alxndrsn** [comment]
Is this blocked by #2046?

**Comment by mandric** [comment]
Blocking is probably a strong word here because the import script could easily do the things that medic-api isn't doing yet, namely also assigning a contact to the place/facility.  If this needs to happen today we can start work on it now because I am still finishing up #2046.

**Comment by browndav** [comment]
I'd prefer that we use the API for this rather than create another one-off scripted implementation.

**Comment by mandric** [comment]
You can still use the API. Just make an additional tweak. The script  ishandling several extra things anyway. I am saying if there is a time crunch it is easy to tweak the script to do whatever is needed.

**Comment by alxndrsn** [comment]
Continuing without #2046.

**Comment by mandric** [comment]
WIP #2046 is in beta now, you can fulfill 90% of user creation needs by using it.

**Comment by alxndrsn** [comment]
@alxndrsn N.B.:
* branches etc. should not be duplicated if they already exist in the DB
* make sure that test runs have been made on non-prod servers THIS WEEK

**Comment by mandric** [comment]
I made some decent progress on this. Should have it done today (monday).

**Comment by fredatthehub** [comment]
@here, LG are unable to load all the forms for the newly created Mukono users. My chrome inspect is not working when I the phone is downloading the forms, its only working if am running the Chrome browser, so not sure which forms are failing or at what point the process is failing.

**Comment by fredatthehub** [comment]
Some comments from LG, kindly assist.

=======================================================================
Hello ,
 
I have been trying to check the status of data migration, unfortunately , the data appears on the phones( there are contacts and pregnancies) but the same are missing in the postgres database.
Quick questions then are:
1.       Am I reading the correct database? Am currently reading lgapp database.

2.       Sample basic query I have run is one trying to find a contact / hof from an active pregnancy in mysql

a.       For now it didn’t return any results.

Query

select * from contactview_hof where "name" ILIKE '%Nakibrtu%'

                Nakibrtu being a name of the currently active pregnancies for the set of chps shared

b.      What I noticed again is that the list of users shared over slack shows same uuid , double checking this shows that the uuid indicated is the id for the branch. Can a separate list be shared with the right ids?

Victor.
=============================================================================

**Comment by mandric** [comment]
See `medic-import` repo https://github.com/medic/medic-import

**Comment by ngaruko** [comment]
Does this need any AT? Is it a utility that is still being used or just a once-off thing? @mandric @alxndrsn

**Comment by alxndrsn** [comment]
This was orginally for a one-off migration, but it looks like @mandric's work is more generic and so likely to be useful in the long-term.

**Comment by ngaruko** [comment]
Hi @mandric. Do you think we need to AT this?
