### ISSUE TITLE
Make sure lg's Android app has the HBB fix

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2129]
@alxndrsn made this commit: https://github.com/medic/medic-android/commit/2bb32ee534af321adc0f362b462d91d1b111394b

This is a really useful thing for LG to have in their build, because it removes an avenue for the CHP to restart the app. This in turn reduces the negative impact of "first-run" style issues (not to belittle it, but #2126 is an example).

We should make sure that the play store is up-to-date with a version that contains this commit.

**Comment by alxndrsn** [comment]
Built in https://travis-ci.org/medic/medic-android/builds/115078379; uploaded to app store March 16.

**Comment by sglangevin** [comment]
@alxndrsn - I thought we only uploaded to the app store for the unbranded app? We also need to make sure this change is available on the LG-branded app. Has that already happened?

**Comment by ngaruko** [comment]
@SCdF @sglangevin @alxndrsn Difficult to tell what the HBB fix was? and if anything was done? Any details , someone?

**Comment by sglangevin** [comment]
Pressing the HBB was hard-closing our Android app. This should now be fixed.

**Comment by ngaruko** [comment]
Thanks @sglangevin
