### ISSUE TITLE
Sentinel can causes couchdb record conflicts

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2130]
See this slightly sanitised diff from production, between two conflicting versions of the same document:
```diff
--- 0150B131-3F9D-17A9-AFF0-D66071F3BD6D-lost.json	2016-03-21 19:20:18.000000000 +0300
+++ 0150B131-3F9D-17A9-AFF0-D66071F3BD6D-won.json	2016-03-21 19:20:15.000000000 +0300
@@ -1,6 +1,6 @@
 {
     "_id": "0150B131-3F9D-17A9-AFF0-D66071F3BD6D",
-    "_rev": "2-0676e633096313b5eda3699ea8d47122",
+    "_rev": "3-b46fec27bf3c0ea83d30f7004759d446",
     "contact": {
         "_id": "59227435f7a418ac32ddce2d362944e0",
         "_rev": "2-7c386cbf03d2230f09f3dfd646930559",
@@ -53,12 +53,15 @@
     "form": "assessment",
     "from": "XXX",
     "hidden_fields": [],
+    "read": [
+        "YYY"
+    ],
     "reported_date": 1453106628787,
     "transitions": {
         "default_responses": {
-            "last_rev": 2,
+            "last_rev": 3,
             "ok": true,
-            "seq": 75582
+            "seq": 75588
         }
     },
     "type": "data_record"
```

Two things to note:
 - The conflicts, not `+` and `-`, are important here. The winner is picked based on hash ordering
 - The main conflict of interest is that both documents have gone through sentinel (because they have the `transitions` key), and one of them is indicating that the document has been read by someone (in this case a CHP).

It's not clear exactly what's happening here, but presumably sentinel is managing to edit two documents (the original and the read), and push one but not the other.

**Comment by garethbowen** [comment]
Some thoughts...

1. Investigate what the "default_responses" transition is doing - can we disable this for LG?
2. We need to display, somewhere, somehow, all the conflicts in the db and allow an admin to resolve them. It's relatively simple to query a db for all conflicted docs, and resolve the conflict by picking a winner, but providing a UI to compare or merge the versions is tricky.
3. Can we provide a default conflict resolution strategy? In the above example we know that these fields are unrelated so we can apply one then the other without any risk. I suspect we can resolve 90% of conflicts automatically like this.
4. Should we store things like "transitions" and "read" in separate meta documents so they don't result in replications and potential conflicts?

**Comment by SCdF** [comment]
OK so I'm guessing it's because of this: https://github.com/medic/medic-sentinel/blob/testing/transitions/index.js#L284

My guess as to what's happening goes like this:
 - CHP creates report, then reads report. This creates `v1` and `v2` in Pouch, which then sync'd to Couch, which is then picked up by the linked code in Sentinel
 - Sentinel runs code async, which means it takes and processes `v1` and `v2` without and understanding that they are related, and presumably as well in an arbitrary order. 
 - Sentinel then creates two completely valid additions of the `transitions` key for each, and one of them (depending on the ordering) will conflict:
   - `v1` -> `v2` -> `v2+sentinel` -> `v1+sentinel` (conflict)
   - `v1` -> `v2` -> `v1+sentinel` (conflict) -> `v2+sentinel` (no conflict?)

**Comment by browndav** [comment]
A modest proposal for discussion: temporarily remove sentinel entirely from develop/testing.

**Comment by garethbowen** [comment]
Are we confident sentinel is doing absolutely nothing of value for LG?

Rather than removing it I'd be better if there was a configuration option (or similar) to turn it off. I'd like to keep 0.4 and 0.6 as close as possible.

**Comment by browndav** [comment]
That's a really good idea and would be useful for the RDBMS replica process too.

**Comment by mandric** [comment]
You can enable/disable transitions for sentinel via configuration. I'm not quite sure that is the same thing as turning it on/off.

**Comment by garethbowen** [comment]
Yes in the short term I think we should just turn off any transitions LG don't need (probably all of them). In the longer term it'd be good to not even start sentinel if it doesn't do anything for a particular instance.

**Comment by mandric** [comment]
If we add a `transitions` property to the ddoc that looks simliar [to this](https://github.com/medic/medic-sentinel/blob/develop/defaults.js#L118) you should be able to enable/disable transitions.

```
    transitions: {
        accept_patient_reports: {
            disable: true
        },
        conditional_alerts: {
            disable: true
        },
        default_responses: {
            disable: true
        },
        update_sent_by: {
            disable: true
        },
        ohw_counseling: {
            disable: true
        },
        ohw_emergency_report: {
            disable: true
        },
        ohw_notifications: {
            disable: true
        },
        resolve_pending: {
            disable: true
        },
        registration: {
            disable: true
        },
        twilio_message: {
            disable: true
        },
        update_clinics: {
            disable: true
        },
        update_notifications: {
            disable: true
        },
        update_scheduled_reports: {
            disable: true
        },
        update_sent_forms: {
            disable: true
        }
    }
```

**Comment by mandric** [comment]
I think this involves just editing/committing the right project files and then pushing to the server.

**Comment by mandric** [comment]
We could also make the defaults in sentinel to be all disabled and then we'd have to add configuration to enable transitions.  We'd just need to be careful about not breaking support projects.

**Comment by mandric** [comment]
Do we want to make this the ticket for disabling transitions by default?  If so I'm happy to take it.

**Comment by garethbowen** [comment]
Issue created to cover defaulting to no transitions.

**Comment by sglangevin** [comment]
Looks like all that was done is to add a `transitions` property to `app_settings`. That's been working for a while. Moving to ready.
