### ISSUE TITLE
configuration->forms doesn't show anything

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2132]
See here now
![image](https://cloud.githubusercontent.com/assets/583851/13954426/c0900044-f051-11e5-9b37-8006bdc4c2f1.png)
This is an issue in 0.6, where the way we store forms is different and the UI hasn't changed to reflect that.

We should make it work.

**Comment by SCdF** [comment]
@browndav thoughts on priority? Is this something we want to do in the next two weeks, or directly after, or...?

**Comment by sglangevin** [comment]
To me, this is not a requirement to deploy the LG project, but it's definitely important as we move toward using 0.6 for other projects. I would do this after, but will leave it to @browndav to make the final call.

**Comment by garethbowen** [comment]
Duplicate of #1330

**Comment by SCdF** [comment]
Closing cause it's a dupe (apologies if that's nor the protocol)
