### ISSUE TITLE
Scope the $scope variables

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2133]
The `$scope` is inherited by child and grandchild controllers. So methods from `inbox.js` are visible in e.g `contacts.js` and `contact-content.js`. 

This gets confusing because functions with similar names are defined at each level, and do pretty different things. For instance in `contact-content.js`,  `$scope.setSelected` and `$scope.clearSelected` are not the opposite of each other : one is at the `contacts` level and the other at the `inbox` level.

Scoping would help with this : we'd have `$scope.clearSelected` vs `$scope.contacts.setSelected`. At the grandchild level, `$scope.contacts.details.whatever`. 

(main goal right now is stability, so I'll do this refactoring later)

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
Closing as this should be inherently dealt with by moving to Angular 2
