### ISSUE TITLE
Monitoring + alerting : we need to know if our instances are healthy

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2143]
This is related to Sentinel going down (#2111), but wider in scope and more long-term. @ngamita raised this, and @henokgetachew may be helping out too.

We don't have an easy way to know the health of our own instances, so it's hard to guarantee quality. Partners are often the ones who report breakages (like Sentinel).

Dashboards of statuses and stats would be nice, across instances, and email/SMS alerting when stuff goes down.
Easy and centralized access to logs also helps (don't know how we get them right now)

What systems do we want to monitor?
 - Sentinel
 - Medic-api
 - nginx
 - SMSSync
 - CouchDB server
 - other?

There are 3rd parties that do monitoring, like http://newrelic.com/. Does anyone have experience with this, any favorites?

**Comment by henokgetachew** [comment]
One other thing to monitor is the backup process.  I have started a bit on this.  Having notifications on email + slack as well when things fail.  I have used newrelic before.  It's pretty cool but I think what we're looking for is much more custom.  I think we should probably have a medic-monitoring repository which does a lot of the monitoring.  I can start that off.

**Comment by estellecomment** [comment]
Closing in favor of https://github.com/medic/medic-projects/issues/127
