### ISSUE TITLE
Too many angular watchers

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2144]
[This blog post](https://www.airpair.com/angularjs/posts/top-10-mistakes-angularjs-developers-make) thinks that more than 2000 watchers will decrease performance.
We have 3200+, according to their code snippet.

Here are the most watched things from Batarang : 
![screen shot 2016-03-30 at 16 14 31](https://cloud.githubusercontent.com/assets/911434/14145295/9ce3531a-f693-11e5-8ffb-0f169ad802db.png)
What's `regularInterceptedExpression`?

One possible solution : They suggest not watching variables that you know won't change, with [bindonce](https://github.com/Pasvaz/bindonce#filters). (kinda hilarious to have 203 watchers on `'indent' + facility_depth`, as if the facility depth was going to change suddenly, who knows)

**Comment by alxndrsn** [comment]
`'indent' + facility_depth`s are likely caused by various modal dialogs containing a contact-selecter which are permanently in scope due to being defined in `InboxCtrl`, but should not be.

Also watcher count is specific to the page you're on, so it's useful to include this information.

**Comment by estellecomment** [comment]
> watcher count is specific to the page you're on, so it's useful to include this information.
Good point. I went through all the tabs and they were all above 3200. This was on a clone of lg.dev from March 29, with `demo` user.

**Comment by garethbowen** [comment]
`'indent' + facility_depth` is used for the contact dropdown filter. This probably goes for the other 3 items with 203 watchers too. So if we fix that filter that'll remove 800 or so watchers.

When I've run it as a restricted user in the past I get about 1500 watchers. I assume you ran this as admin?

**Comment by garethbowen** [comment]
I think I've removed those 800 watchers. Most of the other watchers are on translate expressions with very low bang for buck. We should continue replacing these as we come across them.

Combine this with #1863 and #2155 and we'll have made good progress.

Assigning to @estellecomment to review the progress so far. Can you see any other low hanging fruit?

**Comment by estellecomment** [comment]
Nice! 8 characters for 800 watchers, good ratio.

Another big one is `templates/partials/filters_facility_items.html`, because of the ng-include I guess, 600 watchers. 
It's in the dropdown for the facilities filter. Maybe we could do lazy loading for it, watching all the time when you rarely use it is not great.

**Comment by estellecomment** [comment]
Was easier than I thought :)
Then the translations would add up to a hundred per page at least.

**Comment by estellecomment** [comment]
Next : time the difference these couple commits made, on tecno, to know if it's worth trying any more.
`/messages` has the most watchers right now, but it's an admin-only page.

**Comment by garethbowen** [comment]
Unfortunately my change was effectively admin only too, so potentially neither of these changes will make any difference on a tecno with a restricted user.

**Comment by garethbowen** [comment]
@estellecomment You've made some great improvements here. I propose we close this off so it's not a perma-issue and raise specific issues for any problem areas in future?

**Comment by estellecomment** [comment]
ok!
