### ISSUE TITLE
Canceling a report created from the history view has to be done twice

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2145]
To reproduce:

History view:
![screenshot_2016-03-30-15-27-45](https://cloud.githubusercontent.com/assets/583851/14145636/7be04666-f68c-11e5-94bd-a3d86e0b211a.png)
Open family survey:
![screenshot_2016-03-30-15-28-08](https://cloud.githubusercontent.com/assets/583851/14145637/7c003ba6-f68c-11e5-9903-554207001579.png)
Hit X and then click confirm, gets you to weird future laser eye:
![screenshot_2016-03-30-15-28-33](https://cloud.githubusercontent.com/assets/583851/14145644/8011e7e4-f68c-11e5-889f-c20705fd56eb.png)
Hitting X again gets you back to history view.

**Comment by estellecomment** [comment]
Maybe caused by current work https://github.com/medic/medic-webapp/issues/1963? Maybe.

**Comment by SCdF** [comment]
This looks to be fixed in the latest develop pulled this morning.
