### ISSUE TITLE
Investigate using 2.x for all projects

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2147]
We want to make sure that all future projects are using the same webapp version, whether CHWs are using the mobile app or interacting via SMS. Currently CHW app projects are using 2.6, whereas all other projects are using 0.4. Select existing projects will also need to be upgraded/migrated. This issue is intended to cover the first step of getting 2.6 ready for all our new projects, which is to find out what features have regressed or are missing in 2.6. We can open subsequent issues for any work that results from this.

**Comment by abbyad** [comment]
Planning doc [here](https://docs.google.com/spreadsheets/d/1hAbKklTZ4HPPAuUyWoflGlJMgCgIkIl3jn4Kh2SH874/edit#gid=0).

**Comment by garethbowen** [comment]
@abbyad Surely the investigation stage is over?

**Comment by abbyad** [comment]
Ya, it's been an ongoing process but think we've fleshed it out sufficiently. We've created issues for all known areas of work, and anything else that is discovered at this point will be opened as separate issues.
