### ISSUE TITLE
Move common task utility functions from medic-projects to medic-webapp

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2149]
Functions and constants in nools are created for each `fact` which may have [performance implications](http://jsperf.com/function-creation-performance). Functions and constants that are useful in other projects should be extracted out to the `utils` module that is passed in to nools to simplify configuration.

@abbyad has identified some to move from the lg-uganda task-rules.js into the utils:

* getMostRecentTimestamp
* getMostRecentReport
* isFormSubmittedInWindow
* isFirstReportNewer
* createTask
* emitTask
* isDateValid
* MS_IN_DAY = 24*60*60*1000;  // 1 day in ms

**Comment by garethbowen** [comment]
I couldn't do `createTask` or `emitTask` because they both rely on having nools scope, and I didn't want to get into tricky scope manipulation. Also I had to modify most of the functions to take in `c.reports` as the first parameter. Other than that it should be a direct replacement.

**Comment by abbyad** [comment]
Works well and tested, moving straight to Ready.
