### ISSUE TITLE
Bump the version

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2150]
We're about to release the-bundle-formerly-versioned-as-0.6 and need to decide on a new version.

1. Stick with 0.6. This doesn't communicate to people conversant in semver that this is a breaking change.
2. Bump to 1.0. This is semver correct but doesn't line up with the external version number for this release.
3. Bump to 2.6. This is semver correct and lines up with the external version number.

Vote now!

**Comment by garethbowen** [comment]
My vote is for option 3 - we have to be semver correct, and should use the external version number where possible.

**Comment by mandric** [comment]
Can you explain a little what is the external version business?

**Comment by mandric** [comment]
Is it necessary?

**Comment by garethbowen** [comment]
@abbyad has decided this will be the versioning:

> Kujua Export and Kujua Lite​: 0.1
​> Kujua​: 1.0
​> Medic Mobile​: 2.0
​> In use across current sites​: 2.4
​> In use by DIY testers only​: 2.5
> ​Version with mobile app, tasks, old way of scheduling​: 2.6
> ​Version with mobile app, tasks, new and improved scheduling (not backwards compatible)​: 3.0

This is what makes sense from a management perspective for communication outside the company. It's not what makes sense from a technical perspective because we can't change the past. But we can align with that in future if we choose.

**Comment by abbyad** [comment]
Those version numbers are the result of many conversations with teammates dating back several months. It wasn't a quick decision, or one taken lightly, as we want it to be logical across our team and stakeholders, as well as avoiding any potential technical consequences.

As an aside, we'll find out with https://github.com/medic/medic-webapp/issues/2147 how much of a breaking change, if any, it is to upgrade from to .4 to 2.6.

**Comment by SCdF** [comment]
Vote is also for 3: I think the re-versioning from an external perspective makes sense, and it's a pita to have to map versions so we should get on the reversion hype train :bullettrain_front:

**Comment by alxndrsn** [comment]
:+1: for option 3

**Comment by garethbowen** [comment]
DECISION: 2.6.0
