### ISSUE TITLE
Iterative steps can overlap in time causing redundancies

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2151]
I had the sleep interval set for 1 minute and doc size set to 3000.

The design doc didn't get pulled in until the very last set, so during the last iteration, all the XML data was being parsed and it took longer than 1 minute.

Meanwhile, the 1 minute timer went off to start the next iteration, which amazingly happened in parallel instead of waiting. Then that iteration, too, began parsing all the data.

In the end, this resulted in duplicate copies of all the parsed form data.

I need to block the next iteration timer from going off until the previous one is done. In fact, I didn't think this was possible but apparently it is.

**Comment by btbonval** [comment]
In the meantime, just increase the sleep interval as a workaround.

**Comment by SCdF** [comment]
This has been fixed by the recent refactor for #2124 .
