### ISSUE TITLE
Remove some stuff from $scope

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2153]
There's a couple functions that I spotted that could be moved out of $scope and kept private instead. Filing this issue to keep track of it.

**Comment by garethbowen** [comment]
This looks fine, but it's really hard to test scope changes. Maybe we defer merge until after LG is merged to testing.

**Comment by garethbowen** [comment]
Merged.

**Comment by ngaruko** [comment]
Do we need to AT this?

**Comment by garethbowen** [comment]
@ngamita Nah it's fine - it's just moving code around. Any bugs will be found in exploratory/release testing.

**Comment by estellecomment** [comment]
Wrong guy, that's Richard! :D @ngaruko
