### ISSUE TITLE
Modals : don't preload them

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2155]
We create and render modals at app startup, and then hide them. 
Instead, instantiate them when you need them.

**Comment by SCdF** [comment]
Just for clarity, what are the pros and cons of preloading models?

**Comment by garethbowen** [comment]
Currently we render the dom and run some initialisation (eg: get all contacts from the db) on first run. I suspect this slows down first render noticeably. Furthermore many of the modals will never be opened (eg: admin only modals) so memory usage would improve. We could also clean up the modals on close to free up more memory if necessary.

**Comment by estellecomment** [comment]
Not done, but take a look if you like, @garethbowen

**Comment by garethbowen** [comment]
Looks pretty good.

I think it would be better to have one controller per modal and remove the ModalCtrl if possible?

It'd also be a big win if you could render the template on open, rather than include it from the inbox template so it has to render on load.

**Comment by estellecomment** [comment]
> I think it would be better to have one controller per modal and remove the ModalCtrl if possible?

I'm going with single controller + service, different templates. So you just specify your template url as an argument to the service, and it's all dealt with for you, as in https://github.com/medic/medic-webapp/commit/447b9d00089f10bfc84e5eba4b18b4a633abdea1#diff-c6f758d977305f269bb1c9d02cd160cdR212

> It'd also be a big win if you could render the template on open

It does! See, it's gone from inbox.html : https://github.com/medic/medic-webapp/commit/996c794331b73f923b3e17ae7b1581dd821fde2f#diff-92f8375985dd637e05f70743548173e4L41

**Comment by garethbowen** [comment]
> I'm going with single controller + service, different templates.

I get that, but I'm sure in some modals we'll want to have some scope (eg: filling out a form) and it'd be nice to have that scope bound to a controller specific to that modal.

> it's gone from inbox.html 

Ahh awesome! I missed that.

**Comment by estellecomment** [comment]
> in some modals we'll want to have some scope (eg: filling out a form)

I could pass the scope in through the Modal service, I'm pretty sure. But I'm going to try NOT to as much as I can, and pass the relevant data only. I'm going through modals to find a tricky one like that and figure it out, which one(s) did you have in mind?

**Comment by garethbowen** [comment]
Looks good. I've added comments inline. IMO the biggest issue is having one controller for all modals, but I notice that the modals you've converted so far have been quite simple so don't really need a controller. How about taking the name of the controller as a parameter and both of these simple examples can use ModalCtrl? That'll make it more obvious how to use the service for non-trivial modals.

**Comment by estellecomment** [comment]
I've started on a more complicated one, and the single-controller thing is indeed breaking down.
So I'm going to keep this single controller for all ConfirmModals (yes/no modals) and start new controllers for other types.

I'd seen somewhere that it was a good idea to make modules around features, and I can see it happening here. E.g. could do a `modals` module, containing modal controllers + services together.

**Comment by estellecomment** [comment]
Merged the branch. 
Work still ongoing for the other more complicated modals.

**Comment by SCdF** [comment]
@estellecomment I'm reasonably confident this has caused (at least on my machine) tasks to no longer load.

Clicking on any task gets 'No task selected'.

**Comment by estellecomment** [comment]
New PR, please review!

**Comment by garethbowen** [comment]
Nice one. Comments in the PR.

**Comment by ngaruko** [comment]
Can we AT this?

**Comment by estellecomment** [comment]
nope! :)
