### ISSUE TITLE
Form title disappears on page reload

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2156]
1. Go to a form, e.g. http://localhost:5988/medic/_design/medic/_rewrite/#/reports/add/family_survey
   ![screen shot 2016-04-04 at 10 17 47](https://cloud.githubusercontent.com/assets/911434/14241894/86788762-fa4e-11e5-99ba-c828cdb14f73.png)
2. Reload page. Form title is gone.
   ![screen shot 2016-04-04 at 10 17 31](https://cloud.githubusercontent.com/assets/911434/14241897/8a5ecb0c-fa4e-11e5-9e82-3628cc7952e0.png)

**Comment by estellecomment** [comment]
Because after form rendering, a `query` event is fired, which causes a `$scope.selectReport()` (clears selected report), which clears the `$scope.title`.
https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/reports.js#L175

**Comment by ngaruko** [comment]
It looks like some of this fix did not propagate through all forms. A number of forms still behaves the same (ie title disappears on refresh). Do we reopen this or rather file another issue?@gareth

On open form


On Refresh

Steps to reproduce
1. login as demo (alpha.dev)
2. People
3. Abdou Kane Family
4. Click one of the action buttons (New Family, New Person or Edit)
6. Form opens with title (on mobile/small screen)
7. Refresh the page (F5 or?)
8. Title gone.

![image](https://cloud.githubusercontent.com/assets/6979995/22184961/3663ee26-e141-11e6-953e-2c27d57afe90.png)

**Comment by garethbowen** [comment]
The original issue was for the Reports tab and the reopen is for the People tab - we might just need to copy the fix over to the other tab.

**Comment by garethbowen** [comment]
Yup. Same issue different tab.

**Comment by estellecomment** [comment]
LGTM!
Exciting to see the cycle of acceptance testing at work :)
