### ISSUE TITLE
Delete via bulk docs can incorrectly report OK

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2157]
Updates with `"_deleted":true` result in an OK response for the doc with a rev +1 as expected... however a small amount of the docs remain with a rev -x.

On a first pass 13 of 965 remained. On a second pass 1 of 13 remained. The third pass deleted the remaining one. I have a snapshot just prior to running this script, and need to test if it's reproducible.

**Comment by abbyad** [comment]
I retested this after recreating the instance from the snapshot and got the exact same result, so this is likely due to the data in some way and not an intermittent issue.

Looking at it further, all of the docs that "reappeared" were previously in conflict. Further tests via Futon on a single doc that had a conflict yielded the same result; after deleting the doc, one with a lower rev remained.

Should we be doing something to deal with or expose conflicts?

**Comment by garethbowen** [comment]
This issue covers exposing conflicts: #1838 

It sounds like couchdb is behaving exactly as expected and your delete script is essentially resolving the conflict.

**Comment by abbyad** [comment]
Sounds good, closing as duplicate.

**Comment by abbyad** [comment]
Just a note that we should keep this in mind when implementing #1000.
