### ISSUE TITLE
Can't hold it back anymooore

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2158]
Turn around and slam the doooooor
https://www.youtube.com/watch?v=moSFlvxnbgk

**Comment by SCdF** [comment]
Recording of bug:
![ewww](https://45.media.tumblr.com/41664ddd71900691fbf8b3bba0b1dd7b/tumblr_mxigr4adtF1rrdfajo1_500.gif)

I think we need a re-render folks, someone call Disney.

**Comment by estellecomment** [comment]
I actually love that song. Great song.

**Comment by ngaruko** [comment]
Passed Acceptance Testing. Back to Code Review.

**Comment by bishwas-medic** [comment]
Suggesting the following rewrite of the original code:
https://www.youtube.com/watch?v=zSyGRut7T0s

cc @estellecomment

**Comment by estellecomment** [comment]
I agree this is a clear improvement on the prior version. Good job @bishwas-medic .

@ngaruko can you reproduce this behavior with your own local resources, and send us a recording?
