### ISSUE TITLE
Medic OS: Provide a simple update mechanism

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2160]
We need a way to deploy security updates that doesn't require a custom script for each update. Make package updates work – at least well enough to apply simple security updates for shared libraries. This should be a `package-update` script that takes a path to a package as an argument, applies it to the running system, and then optionally restarts the updated services.

**Comment by browndav** [comment]
Finished as of https://github.com/medic/medic-os/commit/83de0b7466afb2780fded56f20e660514c637361. Release information coming this week.

**Comment by alxndrsn** [comment]
Is `some_script &> some_file` equivalent to `some_script > some_file`?

**Comment by browndav** [comment]
@alxndrsn: Replying a half-year late, naturally: it's equivalent to `some_script > some_file 2>&1`, i.e. redirects both the `stdout` and `stderr` of `some_script` to `some_file`

**Comment by browndav** [comment]
@henokgetachew: I co-assigned you to this issue; I figure it'd make sense to acceptance test this upgrade process by at (the very least) making me explain it to someone. Seems like it'd fit in pretty naturally with devops discussions and OS build/deploy walkthroughs.

**Comment by ngaruko** [comment]
Hi @henokgetachew  , this looks like a relatively old issue. Can safely assume that it now working as expected and remove the AT label? Thanks
