### ISSUE TITLE
Improve db-object-widget performance

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2161]
The current implementation of the [db-object-widget](https://github.com/medic/medic-webapp/blob/ordered-data-binding/static/js/enketo/widgets/db-object-widget.js) is sub-optimal when the DB is remote (ie users are admin). It currently loads every record returned from the configured view on click. To use LG as an example, that is (currently, with our very small trial) ~500 contacts, at 1.3mb compressed.

We should change our widget to dynamically load data instead of front-loading all of it, and we should only load 20 records instead of all of them.

We could then additionally try to refactor the widget so so that the view it queries only returns what we need to render the select. I think this would be a judgement call based on how much data we think we can save with this, as well as the complexity of no longer having the full document (because presumably we actually need the full document to store against the report).

This issue was spawned from #2054

**Comment by SCdF** [comment]
Things that need to be done:
 - [ ] Use the `ajax.transport ` hook to actually use PouchDB / CouchDB instead of jQuery's ajax functions
 - [ ] Profile to see how much data gets pushed around for each search, realistically, to see if we need to optimise the actual CouchDB view called
 - [ ] Make sure that initial values get correctly selected on render. This is minor and probably involves a single doc GET for that ID, since we won't have the data. This is a little bit minor because I'm not convinced this code actually gets fired at any point: I can't see a place where we currently use this widget that allows for loading this widget against existing data (ie it's only used as patient pre-selection thing on new documents and isn't then visible when you edit the report later).

**Comment by SCdF** [comment]
I have realised building this that I need to break backwards compatibility with the existing code, because I need to change the view that it points to, and thus the value that is in forms to configure the widget. I'll get the thing built and working, but I guess we might end up duplicating and having two so we can migrate over cleanly.

**Comment by SCdF** [comment]
Actually I've managed to not need to break current forms, so disregard that last comment!

**Comment by SCdF** [comment]
Things still to do:
 - [ ] Make it clear that you might be missing results since there are more than 20
 - [ ] Make it work on mobile
 - [ ] Make the selection on desktop not wonky

**Comment by garethbowen** [comment]
It'd also be good to switch all the other contact search select2s (eg: Send Message modal) over to using the same mechanism you use here. It may also be possible to pull out the entire select2 configuration into a module/service so we can keep all these select2s in sync.

**Comment by SCdF** [comment]
I thought they all would be! Do you mean we use select2 outside of enketo? The current code I'm modifying has weird hacks for enketo in it (which I in no way understand) and will probably require more to fix it working completely on desktop and at all on mobile. Could definitely pull out the search component, but if I end up moving it to the search service there presumably wouldn't be much to pull out

**Comment by SCdF** [comment]
OIC, there is also the [place widget](https://github.com/medic/medic-webapp/blob/develop/static/js/enketo/widgets/medic-place-widget.js#L107-L129) that uses a similar setup, as well as [send message](https://github.com/medic/medic-webapp/blob/develop/static/js/modules/send-message.js#L172-L181).

**Comment by SCdF** [comment]
@garethbowen so I think the place widget isn't used, but honestly widget attachment seems like black magic to me. Let me drop this logic bomb on you (no not [that type](https://en.wikipedia.org/wiki/Logic_bomb)):
 - db-object-widget.js exports a selector property as `.or-appearance-db-object`, and nothing else particularly self-identifying
 - When people use the db-object-widget they add `appearance="db-object"` to the input.
 - So I'm guessing that magically attaches because `appearance="db-object"` gets turned into the `or-appearance-db-object` somewhere along the way
 - medic-place has its selector as `input[data-type-xml=medic-place]`
 - There is nowhere interesting in our codebase, or in LG Uganda's project definition, that contains the phrase `medic-place`
 - So if the selector is used to attach widgets, and medic-place as a phrase isn't used anywhere, then the widget is also not used!

**Comment by garethbowen** [comment]
Slight naming suggestion, but looks good. Feel free to close.
