### ISSUE TITLE
Our use of the select2 widget doesn't allow text entry in the mobile app

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2162]
How it should work:
- Log on with Chrome (either desktop or latest mobile), go to history, click the +, add any report that is attached to a contact (eg Assess Patient()
- Note that the dropdown widget, once loaded, allows you to enter arbitrary text to filter it.

What is broken:
- Same instructions as above, but in the mobile app.
- Note that the dropdown widget looks like it selects the text entry box, but your keyboard never appears, and it's impossible to tap the area and have it appear.

Since this works in mobile chrome, it makes me think it's potentially a chrome 30 issue. But, navigating to the select2 examples page inside our app (ie using chrome 30) does work, so I guess something more subtle is going on.

This is not a super high priority because we don't think CHWs use any forms that have this widget (ie the contact is already pre-selected for them) and admins who do use it will be using desktop chrome.

Spawned from #2054

**Comment by garethbowen** [comment]
This could be related to #1395

Maybe our fix for that caused this when we updated to select2 4.0?

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by abbyad** [comment]
Closing as the select2 works properly in my tests with our current versions (medic-android 0.1.149, webapp 2.12.0).
