### ISSUE TITLE
Make data binding to forms only bind when the path matches exactly

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2164]
See #2146 and the conversation on that ticket.

This ticket is about changing the code so that we correctly find the right base node in the XML to start with, and then from then on only bind to the direct children instead of searching down the tree and picking anything that matches.

This will need to tested with each existing LG form to make sure that none of them are relying on the current behaviour.

**Comment by SCdF** [comment]
From looking around it looks conceivable that we can just bind the data to `xml/inputs` and that should map perfectly. It certainly seems like the intention as well (it's called "inputs" after all).

**Comment by SCdF** [comment]
So the current structure is a bit more complicated when you start editing entities (ie contacts). We now have two situations:
 - `data.contact` JSON maps to `bindRoot.inputs.contact` 
 - `data.clinic` (and friends presumably) JSON maps to `bindRoot.clinic` (and friends presumably).

Looking into a few options:
 - Allow the first layer of binding to search arbitrarily deep. Might work, but is not as stringent as I'd like
 - Determine if the first layer can always either bind directly or inside `inputs`, which is a nice clean rule.
 - Change the data to fit the XML better (lame, would require migrations etc)

**Comment by SCdF** [comment]
Hey @garethbowen can you review this: https://github.com/medic/medic-webapp/issues/2208 ?

Ended up going with allowing callers to optionally pass a selector fn that only applies to the first layer, allowing a bit more flexibility in finding the initial data structures to bind to.

NB: I changed some of the tests in a way that I _presume_ is OK, because I couldn't find evidence that it wasn't, but I'm not (and never am) 100% sure. Would be good for you to weigh in. I've commented in the PR where relevant.

**Comment by garethbowen** [comment]
Looks good. I'm never 100% sure in this area either, mostly because there are lots of form configurations and lots of different inputs depending on whether the user loads the form from Contacts, History, or Tasks.

I've added a few readability comments but otherwise go for it.

**Comment by SCdF** [comment]
Merged.
