### ISSUE TITLE
Update pouchDB to latest to incorporate replication fix

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2166]
# Update PouchDB dependency

We have submitted two alternative PRs to PouchDB to fix https://github.com/medic/medic-webapp/issues/2134 / https://github.com/pouchdb/pouchdb/issues/4963:

1. https://github.com/pouchdb/pouchdb/pull/5029 - retry entirety of failed batch
2. https://github.com/pouchdb/pouchdb/pull/5033 - retry remainder of failed batch

When either of these has been accepted upstream and released, we should upgrade to this version of pouch.

# Remove monkey patch

In `Gruntfile.js`, remove the `monkeypatchpouchtoretryfaileddocreplication` task.

**Comment by garethbowen** [comment]
PRs for #2134 and #2167 have now been merged into pouchdb, so as soon as they release we're good to go.

**Comment by garethbowen** [comment]
Update from pouch...

> typically we do releases around the first of the month, but we’ve been kinda lax recently mostly because me and dale have been on vacation slash doing other stuff but I was planning on doing a release soon-ish after most of the open PRs were merged

**Comment by alxndrsn** [comment]
When we upgrade pouch we need to:
* remove relevant monkeypatches (I think details have changed from the original ticket)
* make sure we're setting `options.ajax.timeout` to `30000` on `PouchDB` instances passed to `replicate()` calls
* consider merging these changes to `testing` and deploying for LG

**Comment by garethbowen** [comment]
Pouch released: https://github.com/pouchdb/pouchdb/releases/tag/5.3.2

**Comment by garethbowen** [comment]
This was released too late to make it into 2.6.1 for LG. We're planning a 2.6.2 for them in the next couple of weeks so we can get it in then once we've had a chance to test it out.

**Comment by alxndrsn** [comment]
Shame, but I agree it's sensible to play it safe.

**Comment by alxndrsn** [comment]
(Despite semver ;¬) )

**Comment by alxndrsn** [comment]
If https://github.com/medic/medic-webapp/blob/625ef6ef071b9242e3d62f5380539e3c66a67216/static/js/services/db.js#L30 means that `options.ajax.timeout` is set for connections to the server when replicating, then this looks good.

**Comment by garethbowen** [comment]
I've verified (by debugging the JS) that the timeout is 30000.

**Comment by sglangevin** [comment]
I throttled my connection to the max and it took a while, but eventually all the forms and docs downloaded, so I'd say that's a success! Multiple tries to download form definitions and other items that initially failed.
