### ISSUE TITLE
Replication doc request timeout is too low

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2167]
When pouchdb replication finds a change it issues a request for the latest revision of the doc. On slow connections this often timesout after 10 seconds.

This is because the replication get request [doesn't pass a timeout parameter](https://github.com/pouchdb/pouchdb/blob/master/src/deps/bulkGetShim.js#L85) which means their [ajax module uses the default 10 second timeout](https://github.com/pouchdb/pouchdb/blob/master/src/deps/ajax/ajaxCore.js#L17).

Patch pouch to either 

1. Pass through a larger timeout from the bulkGetShim (about 30 seconds should suffice)
2. Or, have the bulkGetShim pass through the replication timeout. The problem with this option is sometimes you might pass a huge timeout to continuous replication but if individual requests have a huge timeout it could hang the replication, when it should give up and retry. We could max it out at 60 seconds or something sensible.

**Comment by alxndrsn** [comment]
The above commit will fix the problem for us.  If a patch is required for PouchDB, we should use this monkeypatch in the interim.  However, I am working to find a better fix.

**Comment by alxndrsn** [comment]
It seems like we may be setting up our replication incorrectly:

> The `remoteDB` can either be a string or a `PouchDB` object. If you have special ajax options on a remote database, you will want to use `PouchDB` objects instead of strings, so that the options are used.
> – _https://pouchdb.com/api.html#replication_

**Comment by alxndrsn** [comment]
Filed upstream at https://github.com/pouchdb/pouchdb/pull/5042; PR at https://github.com/pouchdb/pouchdb/pull/5043

**Comment by garethbowen** [comment]
PR has been merged so this can probably be closed now.
