### ISSUE TITLE
Update angular to 1.5.x

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2168]
Angular 1.5 has quite a few performance improvements over the 1.4.3 we use now. It also has some breaking changes but I don't think any apply to us. This is a very risky change but it's a good time to do it. Also update all angular plugins. [release notes](https://github.com/angular/angular.js/blob/master/CHANGELOG.md)

**Comment by SCdF** [comment]
Is this also a good time to go through all of our libraries and push them to the latest version (since we are directly after a release)?

**Comment by garethbowen** [comment]
@SCdF Yeah go for it!
