### ISSUE TITLE
re-design display of records in history tab

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2169]
Complaints that summary / list view of records do not show information relevant to the role viewing them. e.g. the CHW does not need to see their name on every record. Reconsider how these are displayed, potentially showing different information in list view depending on who's logged in.

**Comment by estellecomment** [comment]
Similar issue for contacts : https://github.com/medic/medic-webapp/issues/2010

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
I'm sure this is covered with design's tickets already.
