### ISSUE TITLE
When contact or report is deleted by replication, it stays in the LiveList

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2176]
If you delete a contact or report on another client, it stays displayed in the livelist on your client.
Tapping/clicking it will get a 404 in console (i.e. it's really deleted).
A refresh will clean up the livelist.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by mandric** [comment]
Is this still an issue?

**Comment by estellecomment** [comment]
It's a bug, so if it's still happening, yes. We need to reproduce it.

**Comment by garethbowen** [comment]
I've tested this and it's working for me. Reopen if it happens again.
