### ISSUE TITLE
Display "not_found" error to user

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2177]
If a 404 happens, the error is logged but nothing is displayed. It looks like nothing happened. 
Display "Document was not found" to user.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by estellecomment** [comment]
Hmmm. Don't remember in what use case I was seeing a 404. 

That seems like basic functionality we should have, though no one has complained about it so i guess it's low priority. Leaving open.

**Comment by estellecomment** [comment]
Quick fix, @garethbowen can you review PR? https://github.com/medic/medic-webapp/pull/3460
