### ISSUE TITLE
When documents are edited/deleted by replication, they are silently updated

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2178]
Example 1 : you are on a contact page. The contact you are viewing gets remotely deleted. You will get kicked back to contacts list, without any error displayed (404 is logged though).

Example 2 : you are viewing a report. The report is edited remotely. You see the fields change without warning.

**Comment by SCdF** [comment]
I think this is a feature? At least, example 2 is.

In any case, it isn't causing us any known production issues. Closing.
