### ISSUE TITLE
Tasks and Targets for deleted persons still show up

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2179]
For Tasks

1. Create a new family, with pregnancy, but don't report the pregnancy yet. A task gets created to register the pregnancy for the person.
2. Delete the person from admin.
3. The person deletion is replicated to client, but the task stays up. (you can still fulfill the task, too) (and then if you undelete the person, you have two pregnancies for the same person, fun)

For Targets

1. Declare a bunch of pregnancies
2. Delete the person and form.
3. The person deletion is replicated to client, but the targets don't update.

Reloading page will fix it though : tasks disappear, targets update to lower numbers (at least the pregnancy one does, not tested for others)

The replication events are probably not coming in right to the TaskGenerator...

**Comment by estellecomment** [comment]
WIP update : 
RulesEngine.js is getting the change from the Changes service, all good there. 
BUT then, it sets the `fact`'s `contact` field to null (https://github.com/medic/medic-webapp/blob/develop/static/js/services/rules-engine.js#L210) which is not so helpful: the rules are (probably) rerun, but ignore the facts with no contacts (facts with no contacts can actually happen normally : https://github.com/medic/medic-webapp/blob/develop/static/js/services/rules-engine.js#L232, so it makes sense to ignore them.)
So the task for the deleted contact stays up in the UI. Bad.

What we would need to do is emit an "untask" when a contact changes to deleted, which prompts the UI to remove the displayed task.
Figuring out if this should be in the RulesEngine.js, or in the configured rules in app_settings, or some mix of both.

Note : reloading page does indeed fix it, because facts with `contact == null` don't emit tasks in the first place.

**Comment by estellecomment** [comment]
LivList reacts nicely to contact updates, here : https://github.com/medic/medic-webapp/blob/develop/static/js/services/live-list.js#L160
We could modify to `if (task.resolved || task.deleted) { LiveList.tasks.remove(task); }`
Then figure out how/where to output a task with a deleted field.

**Comment by estellecomment** [comment]
Fix in both the rules config and the rules-engine.js code.
Applying only one or the other will have no visible effects (tasks will be emitted twice for nothing, but livelist will update the existing task invisibly). When both are applied, then it happens!

Diffs for review : https://github.com/medic/medic-webapp/compare/e2fb50a08b2a03ae6e3f0ecbe2200ef25245eb23...develop
and https://github.com/medic/medic-projects/compare/a3b300369acee1862b249f987aca58de8db747a8...master

Assigning to @garethbowen, but maybe @abbyad would like to take a look at config changes too.

Next up : targets, same deal.

**Comment by abbyad** [comment]
Thanks for the heads up. The config changes look reasonable and still allow for tasks that are not based on a report so we should start using this once fully tested.

cc @sglangevin

**Comment by sglangevin** [comment]
Looks good to me - let me know when I can help test. I'm guessing this will be pushed to develop only, so I'd test on alpha.dev?

**Comment by garethbowen** [comment]
One comment about some logging, but otherwise looks good.

**Comment by estellecomment** [comment]
@sglangevin the code part is already in develop, so should be in alpha.dev. The config may get there by magic, but I'm not sure :)
Assigning to @abbyad to push the config changes if necessary (and inform me on how it's done for next time)

**Comment by abbyad** [comment]
@sglangevin is now doing the config updates, so will let her push them as needed.

**Comment by sglangevin** [comment]
Pushed this a while back, should be working now, moving to Ready.
