### ISSUE TITLE
Publish the openrosa-xpath-evaluator

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2181]
We depend on [openrosa-xpath-evaluator](https://github.com/alxndrsn/openrosa-xpath-evaluator) in production so it needs to be rigorously versioned, tested, and published.

- [x] Fork to [medic](https://github.com/medic) so event integrations work as expected (slack, travis, etc), permissions are consistent, etc and everyone has permission to update it
- [x] Publish to npm so versioning and caching work reliably.
- [x] Update our package.json to depend on the packaged version.

**Comment by alxndrsn** [comment]
# publishing to `npm`

This should be done by travis for any tagged build.  More details on setting this up are available at https://docs.travis-ci.com/user/deployment/npm/

**Comment by garethbowen** [comment]
One small comment. Otherwise, good job!

**Comment by alxndrsn** [comment]
Please review PR - looks awful to me!

**Comment by garethbowen** [comment]
Something has gone horribly wrong, eg: `"resolved": "http://127.0.0.1:5080/tarballs/aws4/1.4.1.tgz"`

5080 happens to be the port that `local-npm` runs on, so maybe this is messing with it? Can you try reverting the change, stopping local-npm, and trying again?
