### ISSUE TITLE
Document 2.6 DB data structures ("schema")

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2182]
It would be nice to have a gold standard of what our data types are: what fields they should have, and how they're linked together (by id, or by full copy).

Right now we look at existing data, but there's malformed data in there too, and it's hard to know what should be ignored as spurious vs. what's on purpose. 
@btbonval will find this helpful for his work
And we eventually want to have a standard test dataset, based on this.

I'd started a doc there with my own investigations, if it's useful (whatever the final version is, in a repo or in a doc) : https://docs.google.com/a/medicmobile.org/document/d/1iJ17IwlM9mcrolnStN1sIv4V-PCLTep_G7Mp3pyHX1M/edit?usp=drive_web

**Comment by btbonval** [comment]
Standard test dataset would be amazing. I need that much more than the documentation itself, but all is useful!

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
This has been started and the current doc is located here: https://github.com/medic/medic-webapp/blob/master/doc/db_schema.md

@estellecomment does the info that exists in the current doc satisfy this issue? If not, we should schedule this and complete the documentation to a satisfactory point.

**Comment by estellecomment** [comment]
Yup! Closing.
