### ISSUE TITLE
Set ajax timeouts for remote pouch dbs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2183]
Make sure `ajax.timeout` is being set when initialising remote PouchDB databases. Also ensure remote db instances are cached by removing the `DB.getRemoteUrl` function.

**Comment by garethbowen** [comment]
Initially this didn't warrant an issue but it turns out there are some bugs in the DB service. Add unit testing and fix bugs.

**Comment by alxndrsn** [comment]
:+1:

**Comment by garethbowen** [comment]
No AT required.
