### ISSUE TITLE
Extract etag regex into reusable module

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2184]
We have at least two places which use a magic `etagRegex` to extract a rev from a resource's etag header. It's poorly documented (it's only needed for gzipped resources), untested, and copy-and-pasted. Pull it out as a service, add unit tests, and use it everywhere.

**Comment by estellecomment** [comment]
LGTM! Optional comment.

**Comment by garethbowen** [comment]
Nothing to AT here.
