### ISSUE TITLE
Monitor hosted instances

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2189]
Implement some way for the dev team to be notified when a hosted instance is unavailable. For example, #2076 results in a 500 response which is really easy to detect and clearly a fatal error so we shouldn't have to wait for our customers to let us know it's down.

For now this could be a simple ping to an API endpoint and email devs (eg: pingdom, aws?).

Sometime in the future we could have a much more comprehensive monitoring system (eg: nagios) to warn when the system is getting close to failure (eg: low resources, bad configurations, etc).

**Comment by estellecomment** [comment]
Monitoring ticket in medic-projects : https://github.com/medic/medic-projects/issues/127

**Comment by garethbowen** [comment]
Implemented with statuscake:

> You have ​0​ Tests Down, ​30​ Tests Up and ​3​ Tests Paused.
​> All Your Tests are Currently Up!

Let's call this done!
