### ISSUE TITLE
Promisify services

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2194]
A couple services would be nice with promises instead of callbacks. 
Non-exhaustive list, will add to it as I run into them :
- [x] `DeleteDoc`
- [x] some of the services in `services/user.js` (some have been done already)
- [x] `UpdateContact`
- [x] `UpdateFacility`
- [x] `UpdateSettings`
- [x] `Verified`

**Comment by garethbowen** [comment]
@estellecomment I think it would be better to raise one issue per service, otherwise this issue will live on for a very long time, and never actually progress to Code Review.

**Comment by garethbowen** [comment]
#2442 raised to cover UpdateSettings

**Comment by estellecomment** [comment]
Yay promises! :batdance:
Couple comments on https://github.com/medic/medic-webapp/commit/ec53880eb79123422143ec961cd78527791f3d06 and https://github.com/medic/medic-webapp/commit/f6019602a06d85d2ef039f6e846c0bbddb7864c6, and then it's cool.
