### ISSUE TITLE
Editing forms no longer skips the select patient dropdown

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2197]
If you add a new form raw, without context of a patient, you're given a dropdown to select the patient. I have recently been monkeying with in #2161 

Previously, when you edited an existing form it would skip this page of the form and present you with the next page (ie filling in real data about that patient)

Now, it goes to the select patient page and has an empty select patient dropdown.

---

From what I can tell this is due to how the data is being saved since I changed the dropdown. Old forms (ie created with the old widget) still load correctly. There is still a patient id, but I imagine it's something along the lines of me linking the ID but not the whole object.

**Comment by SCdF** [comment]
This seems to be broken from before my code changes, which is weird and concerning. It might be that it works for certain contacts and not for others?

**Comment by SCdF** [comment]
OK so maybe this is not a bug. @abbyad / @garethbowen / whoever else would know the answer to this, does this functionality sound intentional to you?:
 - If a form is created via a task (ie a CHP clicks a task and completes the loaded form) editing the form skips the select patient dropdown
 - If a form is created manually (from the + button on the history page) the select patient form is shown again

**Comment by garethbowen** [comment]
This sounds like a form configuration issue to me. The context must be ending up different between those two examples. Assigning to @abbyad as this will probably be obvious for a man of his abilities...

**Comment by abbyad** [comment]
That seems to be working as designed, but I understand how it could seem odd.

Here are the two situations:
- From the Task or Contact the person is preset, and you cannot later edit to change the person the form is about.
- From the Reports tab you need to specify who the form is about, and you can edit the person later if needed

@SCdF do you still think something needs to be done differently?

cc @sglangevin

**Comment by SCdF** [comment]
Yeah nah this is fine I think. It was just my misunderstanding.
