### ISSUE TITLE
Can't edit some user-settings in lg.app

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2199]
(accidentally created by https://github.com/medic/medic-webapp/issues/2047)
We requires a `roles` array when updating user-settings. But some user-settings don't have a `roles` field, and so fail validation, so you can't save edits.

It's a problem for all the `2mukXXX` users, `admin`, `demo` and `trainingXX` users.

Screenshot from lg.app : 
![screen shot 2016-04-15 at 13 03 50](https://cloud.githubusercontent.com/assets/911434/14559679/c4c7ebc4-030a-11e6-9dce-d3b20da6a016.png)

**Comment by garethbowen** [comment]
Assigning @mandric as it looks related to #2202

**Comment by mandric** [comment]
I think whatever is editing the user docs should add a roles property to the user-settings doc.  This would be fixed when the User editing code is updated to use medic-api in #2048.

**Comment by garethbowen** [comment]
It looks like adding the `roles` to the user settings was added to an old migration, which won't work on installations where it has already been executed. I've added a new migration to set the `roles` for all installations.

Also the user editing in the webapp had to be updated to set/update the roles.

**Comment by abbyad** [comment]
Worked well in `2.6.2-alpha.3226`, moving to Ready.

**Comment by abbyad** [comment]
@estellecomment, I did acceptance testing based on a duplicate issue that I had opened, but please feel free to also do more acceptance testing and reopen if needed.
