### ISSUE TITLE
User's fullname is not showing up in /configuration/users

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2200]
Demo user has a `fullname set` : 
https://lg.dev.medicmobile.org/_utils/document.html?medic/org.couchdb.user%3Ademo
```
{
   "_id": "org.couchdb.user:demo",
   "_rev": "12-138f60143f96047860607ed230e8af33",
   "type": "user-settings",
   "name": "demo",
   "fullname": "Demo User",
   "known": true,
   "facility_id": "6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E",
   "contact_id": null,
   "roles": [
   ]
}
```
Going to edit user page, the field is not populated : 
https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/users
![screen shot 2016-04-15 at 13 50 42](https://cloud.githubusercontent.com/assets/911434/14560598/14845a3e-0311-11e6-8958-6d709128a0ed.png)

If you write something and save though, it does get saved.

**Comment by SCdF** [comment]
Types!

But seriously, there looks to be only one thing using this service, so as long as you tested it for them it looks good to me.
