### ISSUE TITLE
extract-user-settings migration should preserve roles field

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2202]
With the latest `validate_doc_update` changes user-settings docs cannot be created without a `roles` field.

**Comment by garethbowen** [comment]
The code looks fine, but why do we need roles in UserSettings? I think up until now we've only used the one in the cookie. I'd like to store it in as few places as possible. It might be that it's best in the UserSettings so it's updated even if the session is maintained. So maybe look at removing it from the cookie and modifying the webapp to check the UserSettings doc?

**Comment by garethbowen** [comment]
Note that the validation change has also caused this bug: #2199

Does this mean we need another migration just for roles?

**Comment by mandric** [comment]
We decided having the roles in the user-settings doc, rather than cookies, is more useful in the long run.  But you're right we aren't actually using it yet.  Should we open another feature request for actually using the new roles property instead of cookies?   Then on that ticket we would also add a new migration to add the roles property.

**Comment by mandric** [comment]
I'm thinking we leave validate_doc_update as-is (requires roles on user-settings docs) and fix any bugs related to that, like anything editing users that is leaving it out.
