### ISSUE TITLE
List spinner lingers

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2205]
The loading spinners are shown for a few seconds after the list is rendered and then mysteriously disappear.

![lingering](https://cloud.githubusercontent.com/assets/2064938/14591267/5234af20-0562-11e6-8cc8-f4241dc06c4d.png)

This happens on each tab, and even on unrelated pages like Configuration > Users

This affects version 2.6.0-alpha.3152 but not 0.6.0-alpha.3054

**Comment by garethbowen** [comment]
This was caused by adding the ngAnimate module in https://github.com/medic/medic-webapp/commit/b2e68a69307cd3caebc8ce71b55ba8b672f36138

**Comment by garethbowen** [comment]
I think it was added so the bootstrap modals would animate in and out, but they animate even after removing this. I think that's because we're including the bootstrap javascript too. So ngAnimate is unnecessary and causing issues.

**Comment by estellecomment** [comment]
LGTM
