### ISSUE TITLE
Create a client side ddoc

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2206]
Currently we have one ddoc for everything which is great because we can deploy a new version by updating that one ddoc and everything just works (woo couchapps!). However it's massive which has caused a bunch of performance issues:

1. Slow parsing of the ddoc for view compilation in pouch
2. Because we don't replicate the ddoc a separate connection must be kept alive for watching for remote ddoc changes which doubles the total number of connections to the server and increases data usage even when idle
3. When the ddoc does change we download much more than we need to
4. We have lots of views on the phone that are never used client side

Instead we should copy specific parts of the ddoc and publish a new ddoc ("medic-client"?). This can be replicated to the client just like any other document which removes the separate connection (2), and slims down the ddoc to just what's required (1, 3, 4).

Some parts of the ddoc we could filter out:

1. `api` and `sentinel` attachments
2. The entire `packages` codebase
3. Lots of individual views and functions

The downside is the added complexity:

1. If add a new view we have to remember to think about whether or not it should be available client side
2. How will we keep the second ddoc up to date with the first? Have `api` listen for ddoc changes and update the doc?

**Comment by garethbowen** [comment]
It looks like my pouchdb caching patch is going to get reverted as it causes a performance reduction with small ddocs. This makes fixing this issue more pressing.

**Comment by garethbowen** [comment]
### Code review

Four PRs today...

* [medic-webapp](https://github.com/medic/medic-webapp/pull/2471)
  - Added a grunt task to compile the medic-client ddoc and attach it to the medic ddoc
  - API then extracts the medic-client ddoc
  - The phone can then replicate the ddoc like any other doc so we don't need the WatchDdoc service any more
  - You can probably ignore all the view code - it's almost completely copy + paste
  - I've removed kujua-reporting because there was very little left in it - the css has been moved to /static/css and the last two views have been merged into /lib/views.js
  - I've merged the kujua-sms views into /lib/views.js because it's confusing not to have all views in one place
  - Then there's a whole bunch of switching calls from using `medic/my_view` to `medic-client/my_view`
* [medic-api](https://github.com/medic/medic-api/pull/86)
  - Write code to extract the client side ddoc
  - Update replication filtering to allow the ddoc through
  - Replace `medic/my_view` to `medic-client/my_view`
  - Make ddoc extraction run and complete successfully before migrations or server start.
* [medic-sentinel](https://github.com/medic/medic-sentinel/pull/78)
* [medic-data](https://github.com/medic/medic-data/pull/15/files)

Don't worry about merging - I'll do that once this passes code review.

**Comment by alxndrsn** [comment]
In API, is there any danger that migrations can be run before the `medic-client` ddoc has been extracted?

**Comment by alxndrsn** [comment]
Looks fine - the `medic-webapp` PR is as you say mostly just code moved, and the string change of `medic -> medic-client`.  Good job - I look forward to feeling the improvement!

I'll let you merge though, as it looks like it might be fiddly :)

**Comment by garethbowen** [comment]
> In API, is there any danger that migrations can be run before the medic-client ddoc has been extracted?

As mentioned somewhere else I made a change to ensure the ddoc extraction completes before the migrations start.
