### ISSUE TITLE
Change sentinel to have all transitions disabled by default

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2207]
As discussed in #2130 we should change the default sentinel configuration to do nothing and have projects configured to opt in to transitions they need.

**Comment by mandric** [comment]
I would like to see this in the next release (sooner than later) because sentinel can muck up records at the moment since 90% of transitions are not used in 2.6.  We should have a config to have an enable flag per transition, the opposite of what we have now.  Should be easy and save us headache later.

**Comment by garethbowen** [comment]
Agreed. Adding to this iteration.

**Comment by mandric** [comment]
I can take this one.

**Comment by mandric** [comment]
@garethbowen when you have some time would like to discuss this.

**Comment by mandric** [comment]
@garethbowen actually just have a look at the PR when you get a chance and we can discuss more if it doesn't make sense.

**Comment by garethbowen** [comment]
:+1: Love it.

It would be good to get rid of the test env flag as it's easier to mock it now, but it's ok as is.

**Comment by garethbowen** [comment]
Merge when ready.

**Comment by mandric** [comment]
@garethbowen or @estellecomment please have one more look here when you get a minute, I refactored a bit, thanks.

**Comment by garethbowen** [comment]
LGTM

**Comment by estellecomment** [comment]
Is this in acceptance testing then? All good?

**Comment by estellecomment** [comment]
I'm cool! Thanks, looks great!
