### ISSUE TITLE
We request facilities from the server over and over again

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2210]
I then left the window open on prod, as an admin, on the contacts page, for ~20 min or so, and this happened:

![image](https://cloud.githubusercontent.com/assets/583851/14613127/d2c4e648-0592-11e6-8daa-011b0c205849.png)

For some reason we re-request all facilities over and over again. This is probably pretty bad.

**Comment by garethbowen** [comment]
I only get one request for the facilities view (lg.app, admin, contacts page). It's possible changes were being made to the contacts while you were viewing it which invalidate the cache so it has to be fetched again.

Regardless, the request size is still too large. It also doesn't seem useful to list quite so many contacts in the dropdown.

![too-many-contacts](https://cloud.githubusercontent.com/assets/2064938/14625743/d53903c6-0639-11e6-98c7-b87c0e700b63.png)

Maybe we should only request districts and health_centers and leave the clinics (aka families) behind.

**Comment by sglangevin** [comment]
@garethbowen FWIW, I agree that having all of the families in the drop-down is not very useful. If families aren't in the drop-down, would that mean they don't appear when you select a particular CHP area?

**Comment by SCdF** [comment]
@sglangevin we'd only be removing them as checkable items from the drop down, the left hand size collection of contacts would still show them (if they should show them based on your filtering etc)

**Comment by sglangevin** [comment]
Cool, then I would remove them. I find it quite cumbersome to have to scroll through the whole list when I'm trying to filter by Branch.

**Comment by SCdF** [comment]
So this ticket was raised over the refreshing of the cache. In terms of increasing performance by removing families from the dropdown, I'm going to do that against #2209 (or perhaps another ticket if I create it, but regardless it will be linked from #2209)

Once I've done that we can revisit whether or not the current cache invalidation strategy (which is causing re-requests) is the correct one, based on how much data is now being pushed around. We could look at disabling the invalidation, or only doing it on tab change, or requiring the user to click something, etc.

**Comment by SCdF** [comment]
Once #2218 closes we should close this with it: both the download size and frequency has been massively reduced.
