### ISSUE TITLE
Understand admin bandwidth concerns and optimise accordingly

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2211]
We have generally been of the impression that admins had great internet, and fast computers. This has led to a design where admins don't have a local DB, and everything is pulled over the network. This is potentially looking like it may not really pan out.

For example, in LG PROD (which is a small dataset in the grand scheme of things, they're just getting going) here is what my machine downloads when I refresh the page:

![image](https://cloud.githubusercontent.com/assets/583851/14612566/a0416a78-058f-11e6-84ee-6ebba7b690c1.png)

Things you will notice:
 - gzip is super important for us
 - We download a huge amount of stuff, and there is a reasonable chance that we download the same thing multiple times

It ended up totalling ~12mb or so, which is either OK if you have great internet, or utterly terrible if you are on mobile internet.

This ticket is for us to answer these questions:
 - What are the bandwidth expectations of admin users? Will they have unlimited bandwidth or should we be trying to target a rough amount used per day / month?
 - What is the expected internet quality, re: fiber vs. broadband vs. 3g?

Which in turn helps us understand how much we care about this. Note: LG's dataset right now is presumably nowhere near as large as it will get when they start deploying to new locations, so these numbers will all go up quite a bit over time.

**Comment by SCdF** [comment]
This issue is somewhat blocked on design: there are currently conversations happening about how we want to more usefully present the admin view. Both this and #2209 may be improved by optimising #2210 .

**Comment by SCdF** [comment]
Now blocked specifically on #2218

**Comment by abbyad** [comment]
Using build 3084 logged in as Admin, on a fresh load of the Contacts tab on I see the icons being downloaded about 1100 times:
![image](https://cloud.githubusercontent.com/assets/789512/14712883/ec75e954-07ac-11e6-8db3-ac1fc9458d72.png)

I was able to reproduce this on another 3084 build, but not on 3169. I am guessing this has already been resolved, but thought it would be useful noting here.

**Comment by mandric** [comment]
Any reason you're not testing on 2.6.1-beta.3181?

**Comment by abbyad** [comment]
Tested on 3084 since it is on a production instance.

**Comment by SCdF** [comment]
So @abbyad unless PROD has the build which disables nools I'd expect to see this. Note that you're not actually downloading anything, it's from the cache. For some reason I don't understand (because I haven't looked into it) we convert images into base64 inline images and use them on each task. So what you're seeing is your massive task list loading in the background. Unless PROD has the new build, in which case hmmmmmm

**Comment by SCdF** [comment]
I'm happy closing this for now, I think there are specific tickets now that we can raise as we see them (ie if we ever want to enable admins seeing all tasks again)
