### ISSUE TITLE
Schedule not assigned to registration form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2213]
The associated scheduled was not attached to a registration form that was valid and properly parsed.

_Note, this is running .4 config on a 2.6 instance._

**Comment by estellecomment** [comment]
I'm doing the opposite, running a .4 db with .6 webapp code, and it works fine.

**Comment by abbyad** [comment]
You seem to be doing the same thing as me but got there in a different way. We should figure out what is the appropriate way to upgrade from 0.4 to 2.x

**Comment by estellecomment** [comment]
Also working for me

**Comment by estellecomment** [comment]
(note that i haven't tested that the messages were sent out, but they are displayed in the report, and appear in the scheduled_tasks in the data_record doc)

**Comment by garethbowen** [comment]
I installed the base generic-anc settings and forms and schedules worked as expected. Closing for acceptance testing.

**Comment by abbyad** [comment]
Tested on v2.9 and works.
