### ISSUE TITLE
Forms not showing in filter

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2214]
Our JSON forms are not showing in the Reports tab filter.

Note, this is running .4 config on a 2.6 instance.

**Comment by abbyad** [comment]
Perhaps related to work done in #1409.

**Comment by estellecomment** [comment]
That works for me. 
Assigning @abbyad to confirm we're cool (and we should talk to compare our setups and be sure that we are indeed cool)

**Comment by garethbowen** [comment]
JSON forms are shown correctly in the filter and filtering on JSON forms works as expected.

**Comment by abbyad** [comment]
Works well in v2.9
