### ISSUE TITLE
Form recognized, but label in list not updated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2215]
Form was recognized and fields processed, but form id is shown instead of the label.

![image](https://cloud.githubusercontent.com/assets/789512/14617132/198739e0-057b-11e6-98cf-1283e5c8b2f0.png)

In medic-reporter the form label shows up properly:

![image](https://cloud.githubusercontent.com/assets/789512/14617197/5a2dfb78-057b-11e6-81c0-7d646f959193.png)

**Comment by estellecomment** [comment]
Hmm I'm getting a different messup, but a messup also :

**Comment by estellecomment** [comment]
Turns out it's actually right : the layout was changed for select mode.

**Comment by garethbowen** [comment]
I think this might be fixed by #2100 . Closing for acceptance testing.

**Comment by abbyad** [comment]
Works nicely in v2.9, moving to Ready.
