### ISSUE TITLE
Paginate tasks rendering

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2221]
We recently turned off task generation for db admins because they had too many tasks and generating/rendering those tasks made the browser hang for minutes. This indicates a scaling issue with tasks which may come up again once CHPs have more data.

Because of the way we use nools we can't paginate the task generation, because we don't know the due date of the task until it's been generated. However we can paginate the rendering of tasks which I suspect is a large part of the performance problem.

Paginate tasks rendering in the same way as we paginate reports so we only have to render the 50 tasks with the earliest due date then autoload the next 50 on scroll.

**Comment by SCdF** [comment]
It's worth doing this regardless, but FWIW feeding nools and having it spit out tasks and targets looked to take the vast majority of the time when I investigated it.

**Comment by SCdF** [comment]
I think we can cross this bridge post angular 2.0, or if partners report badly performing task lists that are of a large concern. Closing.
