### ISSUE TITLE
When editing a CHP Area, previously set values for CHP, Branch and Supervisor do not show up

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2223]
![image](https://cloud.githubusercontent.com/assets/1286381/14692265/d9801dbc-070a-11e6-8f63-a6bcd1bd2af0.png)

Values have been set and will appear once you click on a dropdown, but when you load the form for editing, it appears as though nothing has been set other than the CHP Area name.

**Comment by SCdF** [comment]
FWIW this was probably me breaking the db-object-widget

**Comment by SCdF** [comment]
Fixed it by loading the existing value from the DB before init-ing the dropdown.

FWIW I tried to do it async (start with just showing the ID and then loading in the formatted result later) but I couldn't get that to work, so instead we delay the display of the select box entirely. If we fail to load it once we just display the ID and move on with our lives.

**Comment by SCdF** [comment]
_(specifically: I couldn't get select2 to recognise that I'd changed the `text` of the selected option and get it to re-render)_

**Comment by garethbowen** [comment]
Minor naming suggestion, but otherwise makes sense!

**Comment by SCdF** [comment]
NB: this is only in develop. It's not clear if the priority label means it should be merged individually into testing as well, or it's just indicative of ordering.

**Comment by sglangevin** [comment]
Looks great!
