### ISSUE TITLE
Run nools in a web worker

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2224]
We recently fixed a problem where the browser would lock up for minutes when first logging in as an admin due to the massive amounts of data being crunched to generate tasks and targets. While this is now fixed by disabling tasks for admins, it's likely restricted users will being to notice a delay as they accrue more data.

Run the rules engine in a web worker so it runs in a separate thread from the UI so users can use the app as per usual while the tasks load in the background.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment]
Closing as ancient. Given that maintainership of nools is in flux and this issue is a bit old, IMO we should reassess if this is still needed and refile if so.

**Comment by alxndrsn** [comment]
Related:
* https://github.com/medic/medic-webapp/issues/2066
* https://github.com/medic/medic-webapp/issues/2314
* https://github.com/medic/medic-webapp/issues/2797
* https://github.com/medic/medic-webapp/issues/2625

**Comment by garethbowen** [comment]
Reopening as this has been triaged as part of our technical goals.

**Comment by alxndrsn** [comment]
Considering the performance problems introduced by running PouchDB in a worker thread, please properly benchmark this for offline users with large datasets before merging to `master`.

**Comment by garethbowen** [comment]
I suspect it's not worth doing. It made some sense originally if it was going to be in the same worker as pouch because then the data between pouch and nools didn't have to get serialized to go between. But now that pouch isn't in the worker it will. Consider revisiting this if/when pouch is ever back in a worker. Maybe service workers are better? Maybe later Chrome is better? IDK...

**Comment by alxndrsn** [comment]
This no longer seems relevant.  Please re-open if that changes.
