### ISSUE TITLE
Dropdowns in CHP Area create and edit forms have no blank option

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2227]
This means that once you click to load the dropdown for Branch or Supervisor (or CHP, if you are editing), you have to click on a person or place. If you click and load a dropdown accidentally, you have to leave the form without saving and re-open it to clear the selection. 

Related: #1984

**Comment by SCdF** [comment]
@garethbowen made a comment on the commit. We should use just one of these techniques, so whichever works best on both desktop and tecno should be kept and the other one removed.

**Comment by sglangevin** [comment]
Works well on web and on mobile. The "x" is very small on mobile and hard to press. It can be done, but could use improvement. We can deal with that UI change at a later time.
