### ISSUE TITLE
CouchDB is not authorized to return `_all_docs` listed from POST but can return docs listed from GET

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2229]
The couch-to-postgres adapter uses `_all_docs` first to fetch all UUIDs in the system using `include_docs=false`.

Once all UUIDs are fetched, only the necessary UUIDs are requested from `_all_docs` by sending a POST with a list of UUIDs and using `include_docs=true`.

With the analytics user, I am able to GET `_all_docs` even with `include_docs=true`, but I cannot get a subset using POST `_all_docs` (regardless of `include_docs`). I guess POST might be used for other purposes so the entire verb is blocked from analytics?

Is there a way we can resolve this so the adapter does not need admin access? It might not be possible without fully rewriting the adapter to use a changes feed or something.

**Comment by btbonval** [comment]
If the only solution is to change how the adapter works with a major overhaul to use something like a changes feed, we should make a ticket to do that and close this.

**Comment by alxndrsn** [comment]
@btbonval I don't see why `POST` should be blocked if `GET` is allowed - from https://wiki.apache.org/couchdb/HTTP_Bulk_Document_API it seems like `POST`ing to `_all_docs` doesn't allow changes to be made.

Are you accessing the db directly, or via API?

**Comment by btbonval** [comment]
@alxndrsn Directly using CouchDB's API. I don't know why there is a problem, but I know that there is one. Try it for yourself sometime if you're bored. I think there are analytics and demo users which are not admin.

As @SCdF noted out of band, this might be a non-issue now.

**Comment by SCdF** [comment]
I'm going to close this: we've changed how we talk to couchdb significantly, and if we have any issues in production with production credentials over this we can raise new tickets
