### ISSUE TITLE
Incoming message not attributed to contact

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2230]
Messages received via medic-reporter are not attributed to a contact, even though one exists with the same phone number.

**Comment by abbyad** [comment]
The incoming message has `sys.facility_not_found`

**Comment by mandric** [comment]
Marc, did you need this resolved today? I have a feeling it's likely because the contact is not of type `clinic`?

**Comment by mandric** [comment]
The fix might be to update the `update_clinics` transition to include type `person` contacts.

**Comment by abbyad** [comment]
Ah, that makes sense. I found a workaround for what I needed to do today (populate messages for a screenshot), and we can fix this is due time.

**Comment by estellecomment** [comment]
Sentinel does that part, and is probably expecting the old-style contact format, so not finding the contact in the new-style db? That's a guess.

**Comment by estellecomment** [comment]
This is working on my local instance.
I'm running the latest sentinel, which could be what was going wrong for you @abbyad ...

Let me know if you have more thoughts about this, otherwise we can close it.

**Comment by garethbowen** [comment]
Working for me too. Closing for acceptance testing.

**Comment by abbyad** [comment]
Works on v2.9
