### ISSUE TITLE
Establish a template for creating new databases

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2233]
Right now we have two schemas. three roles, and a set of default permissions for two of the users.

These can be created inside a template and then `CREATE DATABASE x WITH OWNER y TEMPLATE z` where z is the template containing all that nifty stuff.

This is all stuff that needs to be done by the postgresql superuser. So it can't be done by the adapter, it really needs to go at a level closer to #1801 

It might be nice if we can find a way to version control these settings so that they get deployed reliably.

**Comment by SCdF** [comment]
I think this has been overridden by our support for migration scripts, combined with our simpler rules for permissions (there is one user with read/write permissions that the app uses).
