### ISSUE TITLE
Error creating new User using UI

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2235]
Cannot create a User using `beta.3181`:

`Forbidden by design doc validate_doc_update function`

![image](https://cloud.githubusercontent.com/assets/789512/14750919/3f51d6ae-0895-11e6-9587-efc4e24d9c06.png)

**Comment by abbyad** [comment]
It looks like the User was partially created since I see a user with the right user name, but missing the Full name field. Replication fails when logging in with that user (404 on `medic/org.couchdb.user:manager`), and manually adding that doc seems to fix things.

**Comment by garethbowen** [comment]
Looks like a duplicate of #2199
