### ISSUE TITLE
Search refactor broke select2 dropdowns

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2237]
As they weren't refactored along with it. This causes them to fail to load any data and generally be useless.

**Comment by alxndrsn** [comment]
Not really sure what the code change does, but if it works then that's good(?)

**Comment by SCdF** [comment]
Basically:
 - The Search service was refactored so you pass different things in.
 - Probably due to timing of when changes to the widget were made, it wasn't changed as well
 - I found out when I tried to fix something else.
