### ISSUE TITLE
Create Contacts (People or Places) via API

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2239]
As part of creating Users (#2046), the corresponding Person is created, but the Places need to be [created manually](https://github.com/medic/medic-projects/issues/190#issuecomment-214368830) for now. Although the Users API endpoint will eventually create all the necessary Contacts we also need to be able to create Contacts independently of Users. This could be for testing the postgres adapter (#1872), e2e testing, or creating demo data sets, as detailed in #2238.

_As a review, we are using the term Contacts to mean both Places and People, and both are shown in the Contacts tab. In terms of their relationships, People may or may not have a single parent Place, and each Place may or may not have a primary Person. That means that a Place acts as a grouping of People with a primary contact who may or may not be part of that group._

**Comment by abbyad** [comment]
This seems to be fully covered by https://github.com/medic/medic-api/pull/59. This issue should be moved to Acceptance Testing once merged.

**Comment by abbyad** [comment]
Some notes from testing:
- Creating a Place with a Contact that belongs to that place requires three API calls: 1) create place 2) create person with place as parent 3) update contact of place to be the newly created contact.
- Multiple places/places can have the exact same name and parents. Eg you can several "Demo Branch", or several children with same name in a single family. It would be more intuitive and easier for scripting if the parent field would use an existing place of same name if it exists within the same ancestry line. The work around is to get the ID of the place first before adding subsequent people, but that is not very efficient, or easy if the place was created outside of the script.

**Comment by abbyad** [comment]
I haven't found anything major in testing, but noticed that the `reported_date` is not set automatically. It is set when a person or place is created using the UI, and is used in our task rules as well as in our delete script, so it would be good for the API to set them by default.

In the meantime, for users the `reported_date` can be specified as:
`place.reported_date` for the place
`contact.reported_date` for the person

**Comment by garethbowen** [comment]
Closing as the bug @abbyad raised should be covered by the linked issue.
