### ISSUE TITLE
Refactor api auth module to use high level request module

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2241]
Post hoc issue to cover the code review of a refactor that's a little risky: https://github.com/medic/medic-api/commit/4528cb2ff3b6ec33a728e8f7d9ff2e52e13256cf

Instead of using the low level `http` module we should use the `request` module which is easier on the eye.

**Comment by SCdF** [comment]
@garethbowen It looks good from my look at it, but I'm not particularly well acquainted with either API. What makes these changes risky? Simply because it's auth and that's always risky, or is there more going on we can look into in more detail?

**Comment by garethbowen** [comment]
Simply because it's auth. I'll progress it to acceptance testing.

**Comment by garethbowen** [comment]
No AT required.
