### ISSUE TITLE
X to close form on mobile no longer works

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2242]
Hitting the hardware back button still works, but tapping the X just selects it and doesn't open the model confirm close dialog.

**Comment by garethbowen** [comment]
This doesn't affect 2.6.1 so it's not a priority and doesn't need to be included in 2.6.2. This is probably a regression due to the refactoring of modals. @estellecomment Can you have a look at this as part of your work on the modals?

**Comment by estellecomment** [comment]
Hmm, probably a leftover from filters refactoring.

**Comment by garethbowen** [comment]
Looks like it was introduced here: https://github.com/medic/medic-webapp/commit/b2e68a69307cd3caebc8ce71b55ba8b672f36138#diff-c6f758d977305f269bb1c9d02cd160cdL210

LGTM.

**Comment by estellecomment** [comment]
ok ok I get the blame fine :P 
Thanks!

**Comment by garethbowen** [comment]
I'll take the next one
