### ISSUE TITLE
Make filtered views shareable by URL : add URL params for filter values

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2243]
e.g. `http://localhost:5988/medic/_design/medic/_rewrite/#/reports/62DD2C79-5104-07B4-ADB7-7F333CCBA02C?datefrom=123456&dateto=654321&facilities=[aaaaaaa,bbbbbbb]`

So that the URL reflects the filter state.

**Comment by sglangevin** [comment]
@estellecomment I'm not sure what this issue is about. If you could take a look, that would be helpful.

**Comment by estellecomment** [comment]
What I mean is make filtered report lists shareable by url.

E.g. I go to report page, I filter by "bob" in freetext search. Now I want you to see the reports submitted by Bob, so I send you the url `http://localhost:5988/medic/_design/medic/_rewrite/#/reports/?freetext="bob"`, you paste it in the browser and see the same list I'm seeing.
(currently you can't do that because the url stays `http://localhost:5988/medic/_design/medic/_rewrite/#/reports/` regardless of the search you do)

Does that make sense? 
IMO it's a common feature of a search page, but if no one needs it... I'll let you judge. :)

**Comment by sglangevin** [comment]
Yeah, definitely a common feature, though we haven't had a request for this. I'd lean toward closing for now because the report page is likely to change, but I'd will note this down to be something we include during the next update of the reports tab. I'm going to close for now.
