### ISSUE TITLE
Cannot create a Person not associated to a Place (aka Cannot immediately create a District on a new instance)

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2245]
You can only create a person that is associated to a place, and you must select a person as a contact when creating Districts. This means that it is rather difficult to build a contact list from scratch. For instance, starting from an empty contact list and creating a District with a primary contact that belongs to that facility you have to create a family with that new person, create the district, assign the person to new district, then delete the original family. We should prioritize the generic "add person" button to the UI.

In https://github.com/medic/medic-webapp/issues/2044 it was mentioned that there is no way in the UI to add a person - but it can be done from a page where the URL was manually edited. This issue is slightly different because it is not possible to directly create a person (or District for that matter) at all when starting from a empty list, and we cannot do so from a manually edited URL either.

Some possible options, of which we may choose to do several:
1. Add a button to add person in the LHS FAB, accessible only to admins.
2. Make `contacts/add/person` work, similar to using `contacts/$FACILITY_ID/add/person` as per #2044
3. Add the option of creating a Person in the Add District form.
4. Modifying the Add/Edit Person forms to make it possible to change the parent, or leave it blank (currently that field is hidden)

**Comment by sglangevin** [comment]
@abbyad I would advocate strongly for option 3. Similar to the CHW area and family forms, we should be able to create the primary contact for a District while we create the district. 

I would also add a 5th option, which would be to be able to configure whether or not primary contacts are required. This could be an all or nothing (all primary contacts are required or none are required) or it could be set by the level in the hierarchy (primary contacts are not required for districts but are required for families, for example).

Curious to hear @diannakane's thoughts on this.

**Comment by abbyad** [comment]
Optionally creating the person via the District form seems like a lightweight solution until we have the redesigned Contacts and profiles.

**Comment by diannakane** [comment]
In principle, Places can exist without People, even a Primary Contact, but People cannot exist without Places. The redesigned contacts would work as Sharon describes, that you will have the option to create a Person while you are creating a Place to simplify the process or if this is required by the project.  

These principles should work the same for every level of the hierarchy, with the option to configure the requirements for each level.

**Comment by garethbowen** [comment]
We should definitely do 3 to make it consistent with the other forms. This will alleviate the issue in the short term.

@sglangevin I'm not sure about your 5th option. I'd want to have a look through the code and remember why we need primary contacts. But the gist is you want to know who to contact if there's an issue at a specific clinic/CHP area.

It's been discussed before and I haven't been keeping up with the latest designs, but I think it might be useful to have some sort of visual distinction between workers (CHPs, managers, etc) and patients (forgive the lack of PC terminology). Then if you could search for "workers at CHP Area 1" you would get a shortlist and might not need a primary.

**Comment by diannakane** [comment]
@garethbowen "type of contact" will be a new field that will allow us to filter or search for a patient vs. CHW, etc. The other visual distinction is that the people belonging to an Area will be separated from the people belonging to a Household so you won't have a mixed list of family members and CHWs.

**Comment by garethbowen** [comment]
Sounds great!

**Comment by abbyad** [comment]
This has been resolved with the People tab work, as used by the new Standard configuration.
