### ISSUE TITLE
allow-new appearance in Enketo doesn't make the "New" option appear

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2251]
Tested on 0.6.0-beta.3027 as @SCdF said that this was implemented a while ago, also tested on 2.6.2-alpha-3226 which has recent db-object-widget updates and I'm not seeing "New" as an option in the dropdown when I use the allow-new appearance.

**Comment by garethbowen** [comment]
If this affects the beta we should make sure it's fixed in the release.

**Comment by SCdF** [comment]
I'm going to merge some work today which I'd like to merge before we fix this, since it's refactoring that area of the code and it will be a pain to merge in the future. Once I've done that I'll unassign it from myself and it can be picked up.

**Comment by SCdF** [comment]
I've merged https://github.com/medic/medic-webapp/commit/da0d81f320b9c0e2c80aac62a81ee2c381017aa2 into develop, which was what I was concerned about being hard to merge later. This ticket can be worked on.

**Comment by garethbowen** [comment]
It works for me on develop, but only after typing in 3 characters to execute a search. I think it should show immediately.

**Comment by garethbowen** [comment]
The only way I can see to get the New option to show up right away is to remove the 3 character minimum, which may cause performance issues.

@sglangevin Can you please test and and confirm that it shows up when you type enough to fire off a search?

@SCdF I _think_ removing the 3 character limit would be ok given that we have pagination now. What do you think?

**Comment by sglangevin** [comment]
@garethbowen I can confirm that I see the New option on alpha.dev when I type enough to fire off a search. I agree with you that the New option should appear immediately.

**Comment by SCdF** [comment]
Yeah that’s OK I think. We also have a (500ms?) delay before the search fires, so unless you’re a really slow typer it should probably only fire when you want it to anyway.

**Comment by sglangevin** [comment]
Working well.
