### ISSUE TITLE
Make single Modal service

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2253]
Instead of one per modal type. Something that you'd use like : 
```
        Modal({
          templateUrl: 'templates/modals/user_language.html',
          controller: 'UserLanguageModalCtrl',
          resolve: {
            enabledLocales: function () {
              return enabledLocales;
            }
          }
        })
```

Right now there's one service per modal (`ConfirmModalService`, `UserLanguageModalService`), that only launches the modal's controller. Not worth having a separate service for each.

**Comment by SCdF** [comment]
IMO It would be helpful to put the pros / cons / reasons on the ticket.

**Comment by estellecomment** [comment]
Sorry, kinda making a note to myself. Edited.

**Comment by SCdF** [comment]
Assigned back to @estellecomment with some comments. I also assigned #2274 to you, which currently fails because of the `Promise` usage noted in my comments. Once you've fixed this ticket that one should pass! :-)
