### ISSUE TITLE
First-run setup modals would be better as pages

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2254]
On first app run, we display several modals in a row : welcome, guided setup, setup user language. Meanwhile the app is visible underneath the modals. The user is being interrupted before even starting. 

It would be better in actual pages, which cover the whole screen, and only get to the usual app after than. 

(labeling tech debt because this was done mostly because it was faster and easier at the time)

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by garethbowen** [comment]
Closing. This is low priority but nice to have. We can reopen if first run experience becomes a priority.
