### ISSUE TITLE
Filters appear in UI with delay

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2255]
Seen in contacts tab, on page reload : the search box is the only one in the bar, and ~20 seconds later, the two filter boxes appear. 
On local env (macbook air), desktop, admin user, db is a clone of lg.app from Apr 27.

Maybe the initialization is taking place? And/or the tasks generation is slowing it down? @SCdF could this be related to your work on select boxes?

![screen shot 2016-04-29 at 14 12 03](https://cloud.githubusercontent.com/assets/911434/14915596/8820f638-0e14-11e6-9c90-25352d49133a.png)

Wait 20 seconds or so...

![screen shot 2016-04-29 at 14 12 49](https://cloud.githubusercontent.com/assets/911434/14915603/8d2ce948-0e14-11e6-9f4c-0ddc42bc4226.png)

**Comment by SCdF** [comment]
Yeah this will hopefully be fixed / ameliorated by the refactoring I'm doing. Basically, right now it's pulling down every single Contact from couch into JS.

**Importantly** this is possibly *worse* locally, since locally you are not running gzip, and what is ~42mb locally is ~3mb with gzip

**Comment by SCdF** [comment]
Hey @estellecomment check out the latest develop and close if you're happy, should be instant now. Download has dropped from ~50mb locally to a few hundred kb. It's also invalidated much less frequently.

**Comment by SCdF** [comment]
(FYI changes are here: https://github.com/medic/medic-webapp/compare/0b677ef4cd4376a44921f6b50e3a024f96520669...08339a5fa192a6bacde5c8fbbd9f8bd9f6a812b5 )

**Comment by estellecomment** [comment]
indeed! Thanks, closing.

**Comment by estellecomment** [comment]
Doesn't need acc. testing any more, since filters got removed from People tab.
