### ISSUE TITLE
select2-ajax doesn't integrate correctly with the search service refactor

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2256]
.

**Comment by SCdF** [comment]
@garethbowen re: our conversation looks like I had the integration wrong. Can you take a look at the commit plz? A conversation we need to have should stand out to you :P

**Comment by garethbowen** [comment]
Comments on the commit.

**Comment by SCdF** [comment]
@garethbowen made some changes based on your comments, get that in ya'
