### ISSUE TITLE
Webapp freezes often while editing contacts

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2258]
Seen on lg.app and lg.dev. When I'm editing contacts, the app crashes after I edit a few contacts. Seems  to be getting worse as more data is added to lg.app. The only way I know to reliably reproduce is to use the UI to edit several contacts. After 2-3 it usually crashes.

![image](https://cloud.githubusercontent.com/assets/1286381/14921487/267b539a-0df8-11e6-8970-9053077bcec1.png)
![image](https://cloud.githubusercontent.com/assets/1286381/14921496/3354a4e0-0df8-11e6-815b-ca33dde7739f.png)
![image](https://cloud.githubusercontent.com/assets/1286381/14921515/41ae7020-0df8-11e6-8edd-4450f57ddc8c.png)

**Comment by SCdF** [comment]
This _may_ be mitigated by the refactoring work I'm doing, because that particular request should get much smaller and be trigger much less, at least in some situations.

FWIW I've seen this when a Couch view is re-indexing, but as I push databases around a lot I haven't noticed whether or not it's doing it an abnormal amount lately.

**Comment by sglangevin** [comment]
I can try testing on the updated lg.dev and see what happens, but that server has a lot less data on it than lg.app, so might be worth re-cloning lg.app to lg-testing.app prior to updating there and then doing some additional testing since then it would have a more realistic amount of data.

**Comment by SCdF** [comment]
There is a fairly good chance I've solved this issue[1] with the crop of refactoring I've pushed in https://github.com/medic/medic-webapp/compare/0b677ef4cd4376a44921f6b50e3a024f96520669...08339a5fa192a6bacde5c8fbbd9f8bd9f6a812b5

The only way to tell would be to put the code in develop onto a server that was having this issue though.

[1] Not the issue specifically, which is that we're timing out after 10 seconds, but we should not perform this request anymore, certainly not while editing and adding contacts.

**Comment by garethbowen** [comment]
@SCdF It looks like some of these changes will make it in to 2.6.2 is that right? If so, we can test this again on lg.app once that is released.

**Comment by sglangevin** [comment]
It would be great of those changes made it into 2.6.2 as I'd like to start handing over some of the editing to LG. With their slower connection, it would probably be incredibly frustrating to try to edit lots of contacts without improved performance.

**Comment by garethbowen** [comment]
Setting to acceptance testing so Sharon can test if it's resolved by the performance improvements @SCdF added to 2.6.2

**Comment by ngaruko** [comment]
LGTM. @sglangevin  did you have another to see if this was resolved, particularly on lg.app?

**Comment by sglangevin** [comment]
This was resolved - we made some performance improvements to lg.app and now have the partner making these edits.
