### ISSUE TITLE
Redesign Send Message (sending SMS)

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2263]
With 2.6 it has a few problems:
 - With large datasets (ie LG) it downloads *insane* amounts of data just to fill a dropdown.
 - It's got a lot of dead code. Here is a [patch](https://gist.github.com/SCdF/b4ef336bc1535a756e0195346d8938cd) with a bunch of code deleted that it doesn't use (ie it's all noop for various reasons) (the `//!` comments is me working out how it can fit with [select2-ajax](https://github.com/medic/medic-webapp/blob/develop/static/js/modules/select2-ajax.js))
 - It uses the same amount of insane data to validate phone numbers afterwards
 - It's not clear why it's invalidating the data, or if that can result in different contacts being affected
 - **The concept of `everyoneAt` no longer works for 2.6**, because while in 0.4 all contacts were CHWs, in 2.6 many contacts are normal people, for whom you wouldn't want to mass spam (or would you?)

It needs:
 - technical work to make it less terrible
 - design work to determine how features like "everyoneAt" are supposed to work (ie what happens if you select a health center? who gets sent an SMS?)

**Comment by garethbowen** [comment]
Related: #2500 #2547

**Comment by SCdF** [comment]
I believe this is being completely taken care of in the tickets that Gareth linked.
