### ISSUE TITLE
Non-XML form view support

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2264]
For 2.6 systems with XML forms, each form gets a table called `formview_{FORMNAME}_{FORMVERSION}`. Although they are tables, the `formview` predates working on 2.6.

For 0.4, each `formview_{FORMNAME}` is actually a view of the table containing all the JSON. As I work on an old 0.4 system, I realized this process of generating formviews automatically from JSON is not build into the adapter, but rather remains as a pl/pgsql function called `build_formviews()` in this file:
https://github.com/medic/middleware/blob/master/postgres/formviews.sql

For the old 0.4 systems, a bit of doing-this-by-hand is going to be required, and such support requests will be finite/limited. I'm not concerned about automating `build_formviews()` for them.

For 2.6 systems which might have forms that are _not_ XML, we should have some solution. If those forms end up looking like the 0.4 forms, then the above `build_formviews()` function should make its way into the adapter itself at some point.

If all forms, regardless of ODK and other considerations, end up being in XML for some reason, then no action is necessary.

**Comment by btbonval** [comment]
This might be a child ticket of https://github.com/medic/medic-webapp/issues/2125 depending on a number of considerations above.

**Comment by SCdF** [comment]
@garethbowen / @browndav can you see any reason why 2.6+ wouldn't have their forms as XML?

FWIW I'd like to investigate removing the XML parsing completely and replacing it with parsing the JSON, but that will come later.

**Comment by garethbowen** [comment]
@SCdF Yes we have to support both XML and non-XML forms at the moment. XML only works with web submissions, and JSON only works with SMS submissions. Submitting via SMS is still a supported workflow. Hopefully one day we'll write an adapter to bind SMS submissions into Enketo forms.

However both submissions should end up as JSON on the doc so your "FWIW" should still be achievable?

**Comment by SCdF** [comment]
Whoops you're right I always forget about our potential SMS friends.

The JSON will end up in the same place yeah? In the `fields` key? 0.4 appears to hold that data elsewhere.

**Comment by SCdF** [comment]
Should be fixed / made no longer relevant by #2432.
