### ISSUE TITLE
 Register-pregnancy task doesn't reappear when pregnancy report is deleted

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2266]
When you create a family, if the primary caregiver is pregnant, you get a task to register the pregnancy.
If you register it, the task disappears (good!)
If you delete the registering report, the task doesn't reappear (bad!)

I'm guessing it's because the `pregnant_at_registration` flag is not reset, maybe? 
https://github.com/medic/medic-projects/blob/master/lg-uganda/tasks/task-rules.js#L216

**Comment by sglangevin** [comment]
What use cases do we have for the pregnancy registration being deleted? Are you thinking that a CHP might delete the report and not re-register the pregnancy? Or that a manager might accidentally delete the report from the webapp? Or would this handle the case where we were only deleting reports and not family registrations during a routine data deletion?

For LG, CHPs cannot delete anything, but that is configurable so we might have projects in the future where CHWs could delete reports.

**Comment by estellecomment** [comment]
Good questions. I was thinking of users deleting reports (any type of user), since it's possible, but I don't know the use case for it. Why do managers delete reports? What kind of reports? 

For data deletions, I expect a training report would be made on a training contact/family ideally, but in practice nothing stops you, for instance, from registering a training pregnancy on a real person.

**Comment by sglangevin** [comment]
A manager might delete a report in the case where a CHW created a report and wants to delete it, but doesn't have access to delete themselves. There are probably other use cases, but that's the one that comes to mind.

Yeah, I'm thinking about the case where CHPs are migrating from the old LG app to our app. What happens if they create a training report on a real family?

**Comment by estellecomment** [comment]
> What happens if they create a training report on a real family?

The training report gets deleted by the `delete_training_data` script, and the woman is un-pregnant again. But the "register pregnancy" task doesn't reappear, until you refresh the page/app.

I don't understand how it's more likely to happen when they're migrating from old LG app? We migrate first, then do training after, so they could be sending training reports on the real migrated data? If yes, then we could avoid that by hiding the real data when we're in training mode... More thoughts for https://github.com/medic/medic-webapp/issues/2267

**Comment by alxndrsn** [comment]
@ngaruko can you confirm if this bug is still occurring?

**Comment by sglangevin** [comment]
This should be working in v2.10.

**Comment by ngaruko** [comment]
LGTM
