### ISSUE TITLE
Use ng-annotate to reduce boilerplate

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2269]
We use [explicit dependency injection annotation](https://code.angularjs.org/1.5.5/docs/guide/di) for angular because it doesn't break during minification but this means we have to declare dependencies twice and in the same order. This is ugly and fragile. Use [grunt-ng-annotate](https://www.npmjs.com/package/grunt-ng-annotate) between browserify and uglify to automatically extract the explicit annotation.

**Comment by estellecomment** [comment]
I breathe a sigh of relief. And of pleasure from seeing alphabetical ordering. Glad to be rid of that, thanks!

I suppose we'll go through all the controllers and services, as we modify files for other reasons.
