### ISSUE TITLE
Disable debug data

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2270]
According to the [angular production guide](https://code.angularjs.org/1.5.5/docs/guide/production) 

> you can disable [debug data] in production for a significant performance boost

This data is needed for development and end-to-end testing so only disable it in production.

**Comment by garethbowen** [comment]
It's a fairly crude method to detect if running in production - I'm open to suggestions.

**Comment by alxndrsn** [comment]
Tis indeed fairly crude, but seems alright really.

An alternative would be to pre-process it into the code at build time.  In some languages this would allow all the debug stuff to get stripped out of the angular files.  Seems unlikely if this would be possible in JS, but perhaps worth a look.

**Comment by garethbowen** [comment]
Fixed. Thanks.
