### ISSUE TITLE
support offline builds

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2271]
Example of cutting network during the npm install step of `grunt dev` on develop... npm just sits here waiting for a very long timeout, I didn't wait it was over 5 mins:

fetchMetadata → network   ▄ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by garethbowen** [comment]
Good thinking. Also have a look at [local-npm](https://www.npmjs.com/package/local-npm) which is a local node proxy which will respond immediately.

**Comment by garethbowen** [comment]
Duplicate of #2679
