### ISSUE TITLE
Remove kanso uber issue

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2276]
This is a long term issue tracking all components that need to be changed to remove our kanso dependency.
## What?
- [ ] Deployment. Without Dashboard and markets we have to work out how to update the software ourselves. Use a repo (npm?) to publish the built app and install from there.
- [ ] Gardner. Work out how to run api and sentinel (and couch2pg?) and monitor them.
- [ ] App Settings. Some app settings can only be configured through dashboard currently. We need to have a catch all method for updating configuration. This could be as simple as a JSON import/export api. #1250
## Why?
- kanso is poorly supported including many website outages
- the market system is holding us back from being able to easily release minor patches
- the market system is forcing us to have non-standard repo branches
- it's heavy weight for what we use it for
- it's one of the slowest parts of the build

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Definitely something we intend on doing, marking Scheduled.

**Comment by garethbowen** [comment]
This has been broken up into parts and is being worked on separately including #3019 and Horticulturalist. Closing.
