### ISSUE TITLE
Tasks do not clear in 2.6.2-beta-3278

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2278]
Another blocker for release #2240 - tasks are not clearing after being completed. Seen when logged in as a restricted user in a web browser. Might be related to #2277

**Comment by garethbowen** [comment]
This may be fixed by #2277. Assigning to @sglangevin to test.

**Comment by sglangevin** [comment]
Tasks are clearing properly in 2.6.3-beta.3291. Moving to ready.
