### ISSUE TITLE
First login with user has errors

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2280]
Not sure if these are related, but replication fails on first login, and we get the following errors:
`inbox.js:6 Uncaught (in promise) Object {error: "not_found", name: "not_found", reason: "missing", message: "missing", status: 404}`

![image](https://cloud.githubusercontent.com/assets/789512/15073387/310df0a0-1367-11e6-93a2-72308cd80462.png)

**Comment by SCdF** [comment]
I'm seeing this in prod too, so it's in 2.6.1

**Comment by garethbowen** [comment]
This looks like a race condition buried deep inside worker pouch: https://github.com/nolanlawson/worker-pouch/issues/15

**Comment by garethbowen** [comment]
This is fixed in most cases by replication before angular start.
