### ISSUE TITLE
Data migration script performance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2281]
After doing a data migration for LG the production server became slow and the CPU usage of beam.smp jumped to 100% for a long time (ie: days). [medic-projects issue](https://github.com/medic/medic-projects/issues/317).

Investigate and fix.

**Comment by fredatthehub** [comment]
Added priority label, as our partner starts training in couple of hours, some forms have not completed downloading yet.

**Comment by garethbowen** [comment]
One theory is that when replicating the local pouchdb doesn't update the seq unless something has changed. If none of these new docs pass the filter for the user then none will be replicated. This would cause the phones to request a replication from the same point, and the replication filter to run over the migrated docs multiple times. We attempted to work around this by bumping the revision of a doc that always passes the replication filter. After two hours the CPU usage reduced to a sensible number. I'm going to try and reproduce this locally.

**Comment by fredatthehub** [comment]
We discovered that LG had the 30+ phones connected and this could have contributed to the replication issue. We advised that they have only 4 phones connected at a go and it did help.
I think this is a good recommendation moving forward for all other downloads.

**Comment by garethbowen** [comment]
We have a few avenues of investigation: #2286 #2287 #2288

The workarounds in the meantime are:
- restrict the number of phones doing the initial replication.
- after a bulk migration or deletion make a minimal change to a form so all phones get an updated checkpoint.

**Comment by garethbowen** [comment]
The three issues listed above should cover this issue, so there's no need for this one any more.
