### ISSUE TITLE
Bootstrapping postgres tends to have different behavior than keeping postgres updated

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2282]
In practice, I found out that bootstrapping postgres from couch tend to operate differently than running the adapter on a populated database. So far, these differences have been acted on by the way in which the adapter is called: the adapter does not make any such distinction.

Technically, there doesn't have to be a difference, but practically there probably should be.

Let's use an example of a CouchDB database with between 50,000 and 300,000 docs (both are actual use cases I've dealt with already). Postgres is being freshly applied, so it has 0 docs in it.

node has limited system memory available. The following link talks about some of this, including the `--max-old-space-size` workaround I've had to use for dealing with audit logs. Any large docs, or any large enough set of small docs, can crash node with out of memory error.
https://bugs.chromium.org/p/v8/issues/detail?id=847

There is a balance between fetching enough data from couch in a single call to not run out of memory, but reduce the overall number of HTTP requests sent to the CouchDB server. We probably don't want a separate GET for each of 50,000 to 300,000 docs. There is a related balance in the interval between HTTP requests sent to CouchDB. If we did call a separate GET for each doc, we'd probably not want to do so in a very short interval of time.

Both the maximum number of docs fetched per interval and the interval itself are settings for the adapter. When actually running the adapter, we can get away with 100 docs every 15 minutes pretty safely (both staying on top of new data and not hitting out-of-memory when audit logs or very large docs come in). However, if we used that combination when there are 0 docs in postgres, we're talking about at least 5.2 solid days to get to 50,000 until we're "caught up" (which, by five days later, we probably aren't caught up).

So for bootstrapping, we might want to crank that up to 4000 docs every 3 minutes. We certainly don't expect that kind of throughput in normal use, so we wouldn't want that to be the normal settings after we've bootstrapped.

The problem is that when there are very large docs (audit_logs in 0.4 systems, possibly some kind of doc that might happen in 2.6 sometime in the future), we'll hit an out of memory and the adapter outright crashes when pulling 4000. So for some systems, babysitting the adapter is required while bootstrapping.

Perhaps there is some way to see how large the next batch of X docs is before downloading them, which can help generate a dynamic doc threshold when bootstrapping (or anytime really). Regardless, it might be worthwhile to consider the bootstrapping case and how we can incorporate it into the adapter (rather than babysitting or running with two different sets of settings).

**Comment by btbonval** [comment]
This might be a non-issue if/when postgres deploys concurrently with couchdb so that there is no data backlog to bootstrap in.

**Comment by SCdF** [comment]
So here's what I'm thinking about this, long term:
 - Every time PROCESS runs, it asks for the `_changes` feed *without* including the docs, from `lastSeq` to now. This will *hopefully* be small enough for node to handle: if not I'd suggest we either tweak node or look at some other optimisations. For example, current LG prod is an 8.5Mb response with ~73 lines, which I'd hope node would be able to deal with.
 - split that into two lists, deletes (where `deleted=true`) and create / updates
 - Do all the deletes in one go (presumably that works for postgres)
 - In N-sized batches work through the other list, where N is probably the number that you'd worked out in the past.

Ideally as well we could create a view that we can use over 2.4 and 2.6 that only returns the docs that we need (ie not audit docs, and more ideally only reports etc). In fact (and this is a bit off-topic to this ticket) it would be cool if you knew which docs we need?

**Comment by SCdF** [comment]
So I think this is mostly dealt with by the #2124 refactor, because now:
 - The `_changes` feed runs and generates a list of IDs that it should download
 - It then downloads `N` of them in a batch, where N is configurable. This is the value you can make smaller for 0.4 and larger for 2.6+ if audit docs are causing you issues.
 - Once it's finished it waits `M` minutes, where M is configurable (and defaults to 10 I believe).
 - GOTO 10.

So as long as you can twiddle the batch-size this should not be an issue.

In the future, once we decide if we do or do not care about audit docs in analytics we could consider running `_changes` through a filter that only returns the types we've decided we care about (ie maybe just reports).

A more extreme approach if this continues to be an issue would be to look into not using PouchDB for the document fetch portion of logic and using raw(er) HTTPS, and so never actually ask node to parse the JSON in the first place.
