### ISSUE TITLE
Architecture without filtered replication?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2283]
What if filtered replication just isn't a high-performance feature, and we should do without? 

Not clear that we should, but I started jotting down thoughts, so I'll share. Draft here : https://docs.google.com/document/d/18t3_7yx3_kxM_zNfuhOBsfsf4QJuS9it_dKfYcbUBQw/edit

**Comment by estellecomment** [comment]
Or with less filtered replication, easier to setup : 
https://docs.google.com/document/d/1WL1g19S6IPj8oF9Dp0I7y262w1SzxSxxUoGTsqn2UO4/edit

**Comment by estellecomment** [comment]
One-db-per-user, according to Nolan Lawson:
https://github.com/nolanlawson/pouchdb-authentication#some-people-can-read-some-docs-some-people-can-write-those-same-docs
Interesting point : "Don't be scared: databases are cheap, and Cloudant says 100k databases per account is not uncommon."

This explains access controls, but not how our use case would work. Access to our docs is not that siloed (see the doc in the first post)
How does a user get docs that belong to another user,  e.g. for district supervisors? (make a copy in their own db? Access the other user's db? How to manage writes?)
Or how to get all the docs of the district, also for district supervisors? (do you query across several dbs and merge, or do you make copies in a central db and query that?)

**Comment by garethbowen** [comment]
This is probably resolved by #2286 which replaces the filter for all replication not just first load.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by abbyad** [comment]
@estellecomment, sending this back your way for reevaluation.

**Comment by estellecomment** [comment]
not relevant any more.
