### ISSUE TITLE
Investigate the high number of connections in production

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2287]
Milan noticed a surprisingly high number of connections (~7000) in production. This may or may not be a performance issue but it deserves some investigation.

**Comment by mandric** [comment]
High numbers of tcp connections (like in `netstat -tan` output) are normal for our app, there are just a lot of connections on production environments.  One for device -> nginx, nginx -> medic-api, medic-api -> couchdb and medic-sentinel -> couchdb.  Then within medic-api we have auditing enabled so the majority of changes going through medic-api will result in more http requests to the audit database.  So each client request can generate 3 or more tcp connections, and that adds up, I don't think these numbers are that off considering how things work.

Number of tcp connections on the SSL port:
```
$ sudo netstat -tan | grep $IP:443 | wc -l 
1970
```
Number of tcp connections:
```
$ sudo netstat -tan | wc -l
9682
```

**Comment by garethbowen** [comment]
LGTM
