### ISSUE TITLE
Pouch doesn't update seq unless something has changed

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2288]
If we get a changes response with no results the local seq isn't updated which means subsequent changes start from the previous seq. This is a problem because filtering the changes feed is expensive so we only want to do it once per user per doc.

This happens frequently for us because the filter excludes irrelevant docs from CHPs which happens to be most docs.

A workaround is to make a minimal change to a doc that passes the filter so all users receive a change, but this creates unnecessary downloads.

Investigate the issue and submit a PR to pouch as required.

**Comment by garethbowen** [comment]
Pouch issue: https://github.com/pouchdb/pouchdb/issues/5145

**Comment by garethbowen** [comment]
Skipping over code review, as it's being reviewed in pouch.

**Comment by alxndrsn** [comment]
:+1

**Comment by garethbowen** [comment]
AT is being handled by the 3rd party library.
