### ISSUE TITLE
Navigating straight to `medic/_design/medic/_rewrite/#/configuration/user` breaks editing 

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2294]
Apparently for admin only...

1. Navigate to http://localhost:5988/medic/_design/medic/_rewrite/#/configuration/user, click 'Edit User Profile'
2. See non-populated form : 
![screen shot 2016-05-13 at 17 09 43](https://cloud.githubusercontent.com/assets/911434/15252368/c9a60796-192d-11e6-89d5-151d1616db3b.png)
3. Whether or not you enter stuff, when you try saving, you get as error (doc update conflict).

It comes from the `editUserModel` kept by inbox.js not being populated : https://github.com/medic/medic-webapp/blob/develop/static/js/controllers/inbox.js#L527

(Which is great because I wanted to get rid of it anyway!)

**Comment by garethbowen** [comment]
Fixed as part of #2444
