### ISSUE TITLE
Ability to set a user to access app in "online-only" mode

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2296]
_"As a potential partner testing out our app I want to start using the app immediately when I log in so that I don't become distracted/disinterested/discouraged waiting to figure out when the app is ready to use"_

Having an online-only mode seems contrary to what we have been doing, but this is so that a user testing out the app for the first (and perhaps only) time does not have to wait 5-10 minutes for the app to load, especially given that it is not clear when the app is ready to use (#2295).

cc @joshnesbit

**Comment by garethbowen** [comment]
All "online-only" users have full access to the database. This is because we rely on replication to filter down to only docs the user has access to. Allowing for online access for restricted users is a big job.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
@abbyad Is this still needed?

**Comment by abbyad** [comment]
Given that the loading happens behind a spinner now, I don't think this is as critical. We can close this and open new issue if needed.
