### ISSUE TITLE
Show places in hierarchical order when selecting a user's place

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2297]
When creating a user, restricted users can only be associated to a family (`type: clinic`) or CHP Area (`type: health_center`). In order for branch managers to use the app effectively, they should be able to be associated with a particular branch (`type: district`) so that they see a list of CHP Areas when they log in but aren't able to see places outside of their branch.

**Comment by abbyad** [comment]
> restricted users can only be associated to a family
What is preventing the selection of a branch as the "Place"? Can you give some more details on what didn't work?

**Comment by sglangevin** [comment]
The `place` drop-down in the UI only lists families and CHP areas, not branches.

**Comment by abbyad** [comment]
They are out of order... look for branches in the middle

**Comment by sglangevin** [comment]
Cool, found it. Why is this drop-down different from all of the others?

**Comment by abbyad** [comment]
No clue why that one is different... but they happen to be sorted alphabetically based on type (`clinic`, `district_hospital`, `health_center`). That may be a coincidence though.

We should rename this issue to show Places in hierarchical order:
 `district_hospital` > `health_center` > `clinic`
aka Branches > CHP Areas > Families

**Comment by sglangevin** [comment]
Updated issue name - the dropdown for selecting a user's place is different from all other dropdowns. Seems like we should use select2 for that one as well.

**Comment by mandric** [comment]
Is this still an issue/problem?

**Comment by sglangevin** [comment]
This was fixed a while ago, it looks like. Closing.
