### ISSUE TITLE
Make it possible for a user to see a subset of contacts within their place

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2298]
_"As a CHP/CHW supervisor I want to see only the CHP Areas/CHW Areas or CHPs/CHWs that I manage when I log into the app"_

This one probably has lots of overlap with design work currently being done on the contacts tab (cc @diannakane) but having a way to configure which CHPs or CHP Areas are displayed when a given user logs in based on a characteristic of those areas would be helpful. For example, each CHP Area has a supervisor. When that supervisor logs into the app, she should see only the CHPs/CHP Areas that she manages (supervisor field for those CHP Areas = name of the supervisor who has logged in).

**Comment by diannakane** [comment]
We are designing with this expectation, so if this isn't currently
feasible, I'd add it to our top priority list.

On Fri, May 13, 2016 at 3:48 PM, Sharon Langevin <notifications@github.com>
wrote:

> *"As a CHP/CHW supervisor I want to see only the CHP Areas/CHW Areas or
> CHPs/CHWs that I manage when I log into the app"*
>
> This one probably has lots of overlap with design work currently being
> done on the contacts tab (cc @diannakane <https://github.com/diannakane>)
> but having a way to configure which CHPs or CHP Areas are displayed when a
> given user logs in based on a characteristic of those areas would be
> helpful. For example, each CHP Area has a supervisor. When that supervisor
> logs into the app, she should see only the CHPs/CHP Areas that she manages
> (supervisor field for those CHP Areas = name of the supervisor who has
> logged in).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2298>
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by abbyad** [comment]
This increasingly sounds like we need a group concept, as opposed to a strict tree hierarchy.

**Comment by diannakane** [comment]
@abbyad, I agree but I'm curious as to what you read in this issue that
reinforced that?

On Fri, May 13, 2016 at 4:42 PM, Marc Abbyad <notifications@github.com>
wrote:

> This increasingly sounds like we need a group concept, as opposed to a
> strict tree hierarchy.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2298#issuecomment-219184478>
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by abbyad** [comment]
If we had unlimited levels in the hierarchy we could handle this by having a level for supervisors. Otherwise having users see a subset of users implies forming a group of some kind.

**Comment by mandric** [comment]
Also been thinking it might not be that hard to modify our hierarchy structure to be more configurable so you can define as many levels as you want.  There would be more configuration, likely a schema to define a hierarchy so on the db-level we can validate hierarchies and contacts.  Instead of type=clinic etc we might change to `type="place:levelN"` where N is a number 0-N, zero being the top of the hierarchy.  So anytime a place is added if N > 0 it requires a parent of level N - 1.  This might get us a more flexible hierarchy without bringing another concept into play.

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by diannakane** [comment]
Resolved with Contacts tab update.

**Comment by mandric** [comment]
Assigning to Sharon because I don't know what to do with this.

**Comment by sglangevin** [comment]
This wasn't resolved with the Contacts tab update, this is a different issue. This can be resolved once we refactor the contact hierarchy as we would be able to have a level for CHW supervisors. Alternatively, we'd want some kind of "grouping" concept. I'll close this in favor of the more flexible hierarchy, which is going to be scheduled soon.
