### ISSUE TITLE
`known` shouldn't be in _users

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2305]
The `known` field is stored both in the `_users` db and in `user-settings`. It's not used in security, and needs to be accessed offline, so it should be in `user-settings` only.

**Comment by mandric** [comment]
Pretty sure when I tested it the tour was affected by the change in _users also. So if we update this we need to test that.

**Comment by estellecomment** [comment]
Ah, good to know. Ok.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by alxndrsn** [comment]
Doesn't sound like it has any negative effects.  Feel free to fix if it bothers anyone especially.
