### ISSUE TITLE
Snackbar showing all the time

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2306]
@sglangevin has found on 2.6.3.beta on the Tecno the snackbar is showing all the time.

![screenshot_2016-05-17-13-22-03_720](https://cloud.githubusercontent.com/assets/2064938/15340865/d1205aac-1cdf-11e6-8eca-625a285824ad.png)

**Comment by garethbowen** [comment]
When I inspect the styles for the element I only see the modern styles which the webview on the Tecno doesn't understand. The autoprefixer should be adding extra styles for backwards compatibility.

**Comment by garethbowen** [comment]
Autoprefixer was using 'last 2 browsers' which is great for evergreen browsers but not so good for browsers stuck on android 4.4 webview (like ours). I presume because a new major version of android is being released 4.4 suddenly became < 'last 2 browsers' and got dropped. I've added 4.4 explicitly so it won't be dropped again.

**Comment by mandric** [comment]
Magic!

**Comment by sglangevin** [comment]
Looks good in beta-3331, moving to ready.
