### ISSUE TITLE
add `reported_date` to required fields in validate_doc_update for type:person records

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2307]
Maybe for contacts in general?

**Comment by mandric** [comment]
Related #2239

**Comment by mandric** [comment]
Thinking every doc should have a `reported_date` or a `created_date`, maybe reserving `reported_date` for form submissions.  Or docs that have forms.

**Comment by mandric** [comment]
This should include `user-settings` docs.

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/2449

**Comment by alxndrsn** [comment]
PR for review at https://github.com/medic/medic-webapp/pull/2767

**Comment by garethbowen** [comment]
Fixed some tests and reviewed ready for acceptance testing.
