### ISSUE TITLE
Confirm with Enter, Cancel with Escape

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2309]
For desktop users doing repetitive tasks like deleting many users it would be useful to confirm a modal dialogue with Enter, and cancel it with Escape.

![image](https://cloud.githubusercontent.com/assets/789512/15365044/c14f3302-1cec-11e6-9f82-ee2daa6970f4.png)

This is not high priority, but could help improve the desktop experience for power users as well as less technical users expecting it to work like their desktop applications.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment]
This is completely valid; keeping. Is it worth asking design to do one big pass re: keyboard accessibility in general?

**Comment by browndav** [comment]
Tagging @diannakane, @amandacilek for input.

**Comment by diannakane** [comment]
This sounds completely reasonable to me. Any concerns, @amandacilek? 

If agreed, we can take care of it as a small issue and add keyboard accessibility to our list of audits to be done in Q3/Q4.

**Comment by amandacilek** [comment]
Makes sense. Keyboard accessibility is not something I know much about but happy to learn more and help. Something we should strive for.

**Comment by vimemo** [comment]
@garethbowen, please review again. Have verified that we can unbind the event after escaping, clicking outside the modal or just closing the modal.

**Comment by garethbowen** [comment]
@vimemo Good work - I just thought of one problem which I've documented on the PR...

**Comment by ngaruko** [comment]
LGTM
