### ISSUE TITLE
support `external_id` property on user-settings docs

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2310]
When users are imported from another system, let there be a way to save the id from that system on the user.  So when the data is exported this is also included and makes it easier to integrate with another database.

**Comment by mandric** [comment]
Probably should also update webapp (the UI) before closing this.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
Closing as this hasn't been touched in months. We can reopen when there's a need to expose it in the UI.
