### ISSUE TITLE
Not able to register a new family

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#2311]
On lg.dev on 2.6.3-beta.3320 in Chrome on my desktop, I'm not able to register a new family. Screenshot below shows console details and the error message presented to me when I click "Submit" at the end of the New Family form.

![screen shot 2016-05-18 at 3 14 13 pm](https://cloud.githubusercontent.com/assets/377216/15376785/150bcc02-1d0c-11e6-9335-73ec21157405.png)

**Comment by joshnesbit** [comment]
More info:

![screen shot 2016-05-18 at 3 26 08 pm](https://cloud.githubusercontent.com/assets/377216/15377092/0bed08dc-1d0e-11e6-95f0-f94df78ecc36.png)

**Comment by sglangevin** [comment]
This was a config issue and has been resolved - closing.
