### ISSUE TITLE
Update worker-pouch

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2314]
#2277 was found to be caused by https://github.com/nolanlawson/worker-pouch/issues/16 . If the PR is accepted and worker-pouch released bump the version we're using in develop and testing and remove our monkeypatching in testing. If it doesn't get released, then convert the monkeypatch to the new format and commit to develop.

**Comment by garethbowen** [comment]
The recommendation is to update to 1.1.0 and use the custom code to provide our own worker wrapper.

**Comment by garethbowen** [comment]
Sorry for the multiple commits but I needed to deploy it to a remote server to test for the "console not defined" error ( #2277 ).

**Comment by SCdF** [comment]
I think it's OK? I made some comments. Exactly what this is doing is reasonably out of my wheelhouse…

**Comment by garethbowen** [comment]
This is a more stable fix for the "console not defined" bug in #2277, so to test this it needs to be installed on a remote server and then accessed with a Tecno. Then refresh a few times. If you see "console not defined" at any point then this patch has failed...

**Comment by garethbowen** [comment]
ATed as part of #2277
