### ISSUE TITLE
Searching in send message dialog is broken

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2315]
If you open the dialog you see contacts, but then when you start typing it never returns any results. There are no errors in the console.

![send-message](https://cloud.githubusercontent.com/assets/2064938/15469722/41170694-2140-11e6-97a1-03f676da4071.png)

**Comment by garethbowen** [comment]
This is a bit of an ugly solution but it works. It'll be awesomer when converted to use the Search service.

**Comment by SCdF** [comment]
Uhm… that is so weird? Did we update select4 and broke it or something? That (the pre-change code) doesn't look modified from when I was mucking around there and it was working fine (you know, for a definition of fine) for me…

**Comment by SCdF** [comment]
(code looks fine btw)

**Comment by garethbowen** [comment]
Yeah I have no idea when it broke. It might need an e2e test...
