### ISSUE TITLE
See if COUCH-1874 affects us negatively

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2317]
See: https://issues.apache.org/jira/browse/COUCHDB-1874

Original mailing list issue is here: https://mail-archives.apache.org/mod_mbox/couchdb-user/201308.mbox/%3C22EF1AC0-CEDA-483B-A7A3-048C15E6D489%40baaz.fr%3E

**Comment by estellecomment** [comment]
If the issue is the 'continuous' flag, we can run one-time replications instead, one after the other. 
(It would also allow to know better when your sync is done, and optionally to sync less often, to sync on demand...)

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
Is this still an issue?

**Comment by SCdF** [comment]
We haven't looked into it yet, so nothing has changed.

Having said that, this ticket is badly formed (no definition of done or action to be performed) so I'm to just close it.

**Comment by SCdF** [comment]
(Also @mandric my understanding is that the backlog tag is dead)
