### ISSUE TITLE
Standardize table and column for the adapter

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#2318]
When the adapter was first written, there were very few absolutes. It was meant to be very flexible.

The table and column are extra variables which allow someone to _potentially_ add a new column to an existing table.

So we have two variables which need special handling and a bunch of testing for various cases (is there a table? if there is a table, is there a column?).

The analytics stuff, in many cases, does not have access to those variables.So making them variable _really_ messes with analytics.

In practice we've been using the table `couchdb` and column `doc`.

If the table doesn't exist, then we should add it with the column. No other logic should be required for initialization of `lib/couch2pg`, so that excess can be removed from the code and the unit and integration testing. We can remove the table and column variables entirely and hard code couchdb and doc.

The reduced variables might also ease configuration stuff related to #1800

**Comment by SCdF** [comment]
I'm going to remove the config options of this as part of the refactor to support deletes and updates correctly

**Comment by SCdF** [comment]
Note that existing installations use `couchdb` and `doc` for the table and column name respectively.

**Comment by SCdF** [comment]
Closing this, it's done by #2124
