### ISSUE TITLE
See if we can cancel an existing search if search terms change

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2321]
Check this [select2-ajax.js](https://github.com/medic/medic-webapp/blob/develop/static/js/modules/select2-ajax.js) code out:

``` js
var query = function(params, successCb, failureCb) {
      currentQuery = params.data.q;

// <snip>

      Search('contacts', filters, options)
        .then(function(documents) {
          if (currentQuery === params.data.q) {
            return successCb({
// <snip>
```

We store the 'current' query so that when we get a search result back we know if we can discard it (because it's not the latest).

What would be better–for this and maybe even for all interactions with the Search service–is if we stored the promise and then invalidated it (if it were pending). To the point where the socket closes. This would reduce pointless network traffic, and ideally as well indicate to CouchDB that it can stop running through the view or whatever.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by abbyad** [comment]
@SCdF, is this still relevant?

**Comment by SCdF** [comment]
I'll take a 10 minute look in the next day or two, and either do it or just close it. I don't think it's a big deal either way.

**Comment by SCdF** [comment]
Looked at it for 10 minutes. Currently impossible, because PouchDB doesn't support cancelling requests.
