### ISSUE TITLE
Branch manager level permissions level needed

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2322]
A branch manager is bound to the same permissions as a CHP because they are a user restricted to seeing only their place, yet we may want to configure their permissions differently than a CHP.

**Comment by abbyad** [comment]
Good point. We should do a larger review of our user types (aka roles) given the new functionality in the app.

**Comment by garethbowen** [comment]
May be done as part of #2583

**Comment by garethbowen** [comment]
Done as part of #4525

**Comment by ngaruko** [comment]
Closing this. To be tested in #4525
