### ISSUE TITLE
Use DB migration tools in medic-analytics

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2323]
To support #2124 we'll be changing the schema in a few ways:
 - Adding a meta table, that will contain the seq we are up to (so we can follow the changes feed)
 - Adding a new column (or JSON index) to the json table that contain the rev of the document so that we can find it again

Currently the code attempts to query tables and if that fails it tries to create them. This doesn't really scale past the one table and the one version, as it gets more and more complicated as more possible states could exist. We should solve this with a migration tool, such as https://www.npmjs.com/package/db-migrate

**Comment by SCdF** [comment]
Also, with #2318 we're getting rid of the option to pick your own table and column names, which makes this more possible.

**Comment by SCdF** [comment]
To deal with existing installations along side new ones we're probably going to write migrations something like this:
 - simple sql to create tables with new names
 - js migration to attempt to move existing data over (if it / the table exists) to accommodate existing installations
 - simple sql to delete existing tables and rename new tables to the old names

**Comment by btbonval** [comment]
for rev, you just need a new index.

That'd get added to this line:
https://github.com/medic/medic-analytics/blob/master/libs/couch2pg/pgsql.js#L12

`CREATE INDEX %I ON %I ( (%I->>\'_id\'),  (%I->>\'_rev\');` and add a bunch more attribs at the end, one being `[c.jsonTable, c.jsonCol, 'uuidrev'].join('_') for the index name, the others being the table and column multiple times.

**Comment by btbonval** [comment]
We also need a new table for migration management, but that is handled by the migration software.

**Comment by SCdF** [comment]
I've done a large amount of this for #2124. There is more we could do on the xmlforms side, and I will talk to Bryan about it to make sure I understand which bits can be put into migration scripts and which can't (ie ideally all of it can be).

**Comment by SCdF** [comment]
Hey @garethbowen check out the following PR: https://github.com/medic/medic-analytics/pull/32 . This adds migration support to xmlforms and removes our manual checking.

Note that it's a branch off a branch so don't merge it: once you're cool with it (and 31, and 30) I'll merge them all into master :-)

**Comment by SCdF** [comment]
Merged.
