### ISSUE TITLE
Create repo for COUCHDB-3021 so it will hopefully get picked up

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2324]
https://issues.apache.org/jira/browse/COUCHDB-3021 has not been picked up by the couch guys, so maybe we should make it easier to understand by writing a minimal case repo they can use to reproduce the problem:
- project that pushes a ddoc into couch
- and generates ~10,000 documents with some data you could filter on
- that ddoc would have two erlang filters
  - one that simply checks for the data and filters on it
  - one that does the above but also has a lot of extra pointless erlang cruft that will never get executed (eg switch on true and then have a bunch of other cases for things that will never match) to increase the erlang size

With that we should be able to provide 'nix `time curl ...` commands that show that the first filter goes significantly faster than the second, even though the same code executes.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
We're not using Erlang filters any more. Closing.
