### ISSUE TITLE
Long delay between completing request for documents of type person and the dropdown actually displaying anything

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2326]
The request for this URL (https://lg.app.medicmobile.org/medic/_design/medic/_view/contacts_by_type?keys=%5B%5B%22person%22%5D%5D) completes in less than 5 seconds but it takes at least 30 seconds for those results to be displayed in the dropdown. @SCdF said that the search improvements that @garethbowen did recently should help with this. Can we consider testing and merging those changes into LG's beta? Currently search performance is quite bad on lg.app.

**Comment by garethbowen** [comment]
I'd quite like to stabilise the develop branch and release 2.7.0 which has lots of little improvements like this. Can you wait a couple of weeks?

**Comment by sglangevin** [comment]
@garethbowen sooner is better because this is preventing me from using the UI to edit contacts, which I need to do to add supervisors. Currently I'm doing that in CouchDB directly to save time. That's fine for me but it means that I won't be giving LG access to the web app for another few weeks - I'd like to hand over the supervisor work to them.

To make a long story short, I am willing to wait and will do my best to hold LG off from wanting access to the web app for a little while longer. Please let me know how I can help with acceptance testing as 2.7.0 is being prepared for release.

**Comment by garethbowen** [comment]
I'll have a look and make sure it's fixed in alpha first. Then we can make a call about another service pack release or waiting for 2.7.0.

**Comment by garethbowen** [comment]
This isn't fixed in 2.7.0 on lg-testing. Needs more investigation.

**Comment by garethbowen** [comment]
I thought I had a clever solution but it turns out I was wrong. Sorting by value isn't possible so you can't paginate on the view. We _could_ paginate in a list so at least it happens server side. I'll raise a separate issue for this.

I think the current performance improvements are probably sufficient.

@sglangevin Which dropdown specifically were you using? Can you try the alpha on lg-testing and let me know if it's acceptable or still too slow?

**Comment by sglangevin** [comment]
@garethbowen I tested this on lg-testing.app and found that the drop-down loads in 7-8 seconds, the next page loads in a similar amount of time, and a search completes in a similar amount of time as well. I view this as borderline acceptable - less then 5 seconds would be ideal for people who are editing contacts, particularly since we don't have bulk edit for contacts. This is a vast improvement, though - should we put a new issue into the backlog for improving this later or is there something that's low-hanging fruit that we can do to improve performance a bit more?

**Comment by garethbowen** [comment]
@sglangevin I think this would be further improved by https://github.com/medic/medic-webapp/issues/2370 I don't think there's any particularly low hanging fruit left.

I'll let you decide whether this is good enough for 2.7.0 as is or if this is still a blocker.

**Comment by sglangevin** [comment]
Let's call this good enough for 2.7.0 and then put #2370 on the list for the next release. Moving to ready.
