### ISSUE TITLE
Expose conflicts in DeleteDocs

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2329]
Since #1000 , `DeleteDocs` uses `bulkDocs`, which doesn't throw when a conflict happens (as opposed to `put` for single-doc version). Thus conflict errors are being swallowed silently.

E.g. when trying to doc `bulkDocs([doc, doc])` (which is a conflict because the rev is going to be wrong on the second update), it returns :
```
[ { [conflict: Document update conflict]
    status: 409,
    name: 'conflict',
    message: 'Document update conflict',
    error: true,
    reason: 'Document update conflict.',
    id: '000000000000testdoc',
    ok: true },
  { ok: true,
    id: '000000000000testdoc',
    rev: '13-54d0296f51d4e56c88792b6d0a1733ab' } ]
```

**Comment by garethbowen** [comment]
Related: https://github.com/medic/medic-webapp/issues/1838

**Comment by estellecomment** [comment]
@garethbowen please review
