### ISSUE TITLE
Support `DeleteReports`, not `DeleteDocs`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2330]
In #1000 , we created a `DeleteDocs` service, which doesn't support deletion of _any_ list of docs. It does support deletion of a list of reports however.
Either 
- fix it for all types, or 
- keep `DeleteDoc` (singular) for all docs and have `DeleteReports` which refuses non-reports.

Example of fail :

```
    var clinic = {
      _id: 'clinicId',
      _rev: 'clinicRev',
      type: 'clinic',
      contact: {
        name: 'sally',
        phone: '+555'
      }
    };
    var person = {
      _id: 'personId',
      _rev: 'personRev',
      type: 'person',
      phone: '+555',
      name: 'sally',
      parent: {
        _id: 'clinicId'
      }
    };
DeleteDocs([person, clinic])
```

will send this to `bulkDocs` : 

```
[{_id: 'personId', _rev: 'personRev', _deleted: true},
{_id: 'clinicId', _rev: 'clinicRev', _deleted: true},
{_id: 'clinicId', _rev: 'clinicRev', type: 'clinic', contact: null}]
```

and return a conflict.

A fix would be to check for repeats and send to `bulkDocs` :

```
[{_id: 'personId', _rev: 'personRev', _deleted: true},
{_id: 'clinicId', _rev: 'clinicRev', _deleted: true}]
```

In case of conflict, it can leave the data in an inconsistent state, but then again so does `DeleteDoc` (singular) in the first place.

**Comment by estellecomment** [comment]
Though actually, we don't allow editing persons who are contacts for places from the UI. 
So I'm not sure where that contact-checking code is used.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek
