### ISSUE TITLE
DeleteDoc service breaks replication

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2331]
Trying to be clever I modified the DeleteDoc service to post a minimal doc. However because this removes all the details of the doc it not longer passes the replication filter and so the deletion will never replicate to the client.

Change it back to preserve the details of the deleted doc and merely set `_deleted:true`.

**Comment by garethbowen** [comment]
@estellecomment I've made a few readability and functionality changes to the DeleteDoc service as well as fixing this specific issue and commented them in the compare view. These are things I should have picked up in the code review. Sorry!

**Comment by estellecomment** [comment]
thanks for the review! 
One comment about an extra test, should be quick.

**Comment by garethbowen** [comment]
AT: Delete docs as an admin and ensure they disappear from a client.
