### ISSUE TITLE
New person and new place buttons should add person/place to the part of the hierarchy in which they are clicked

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2335]
New person and place buttons are contextualized throughout the app. Creating a new person or place autofills the new place form with the place in the hierarchy where you selected to add it from. The “reports to” field in the place and person creation form will be automatically filled out with this information, and can be changed during creation or in edit mode.

**Comment by diannakane** [comment]
Related issues: 
Ability to select where places and people are being added #2193 
Create person in any place #2044 
Creating a Catchment Area without a Health Center is impossible (confusing UX) #1767

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by estellecomment** [comment]
Oh, I fixed this one without knowing it!
https://github.com/medic/medic-webapp/issues/2703

Note that this works for the default forms (the ones generated when there are no contact forms uploaded). If it doesn't work with e.g. LG's forms, then it becomes a form issue!
