### ISSUE TITLE
Remove all filters in Contacts

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2336]
Remove all filters in contacts for restricted release; only have a search bar. 

Search bar should say “search everything” to make it clear that it will return all matching results, not just those from the default list you’re presented with. We reserve the option to introduce advanced filters for power users in future versions. for now, we are wiping the slate clean and keeping it simple, so when we reintroduce filters in full version, we can do what we like.

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by garethbowen** [comment]
I've updated the translations which will need @abbyad to export from POE at some point before release.

**Comment by SCdF** [comment]
@garethbowen this ticket seems to be in a weird state. Should it either:
 - be closed because it's a standard ticket and tickets are closed before acceptance testing
 - be assigned to @abbyad because he yet has work to do

**Comment by abbyad** [comment]
Exported latest `en` translations in https://github.com/medic/medic-webapp/commit/842e862b09765faefd0332f4b83aec5c218786e3. We can open another ticket for exporting further translations prior to release if needed.
