### ISSUE TITLE
Remove export and import buttons from left FAB in Contacts

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2338]
Part 1 - Remove export/import from Contacts left FAB. This will be done from Configuration. 
Part 2 - Add import/export places from Configuration

**Comment by garethbowen** [comment]
The FAB lets you export _just_ the places that match a given filter so this change will reduce the functionality.

**Comment by diannakane** [comment]
that is correct. we don't know of anyone using it as such right now. we
will reintroduce it when we bring the filters back.

On Wed, Jun 1, 2016 at 3:04 PM, Gareth Bowen <notifications@github.com>
wrote:

> The FAB lets you export *just* the places that match a given filter so
> this change will reduce the functionality.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2338#issuecomment-223139129>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXiYgcBGPtWpyk8RnrFqesjh7aHJsks5qHgH7gaJpZM4IsBVI>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by garethbowen** [comment]
I've created a new configuration page for Contacts which has the Import/Export functionality. In lieu of a design for this page I've done something functional but not perfect.

**Comment by estellecomment** [comment]
- I got "Failed - Network Error" on download, so couldn't test it. I do have lucene running. Is it a local-only problem?

 - What is this importing/exporting exactly? Places and People? Are we still using the word "Contact" from now on? @diannakane please advise, so the UI can make sense.

 - There's already an "Export" configuration page, so it's clashing with this new page, I find it hard to know where to go. 
I suggest reusing the Export page: rename it to Import/Export, and add the contact import/export to it.
Or alternatively, add a separate Import page for contact import, and reuse the Export page for contact export. Either way.

- Help text on what "Overwrite existing records" means would be nice. 
  - what are duplicates? (docs with same `_id` I suppose? Not so obvious to non-devs)
  - If it's unchecked, then what happens to duplicates, since they're not overwritten? Ignored? Saved with other id?

**Comment by garethbowen** [comment]
> I got "Failed - Network Error" on download, so couldn't test it. I do have lucene running. Is it a local-only problem?

No idea - I'll look into it.

> What is this importing/exporting exactly? Places and People?

Yes.

> Are we still using the word "Contact" from now on?

I'm using the same translation key as the "Contacts" tab so when we update that one this one will change too. Consistency!

**Comment by estellecomment** [comment]
> I got "Failed - Network Error" on download
Got as far as the download system popup, clicked download, AFAICT the data to send was still there as far as here: https://github.com/medic/medic-webapp/blob/master/static/js/modules/ajax-download.js#L25 
No network requests failed in Network tab, nothing in Console.

**Comment by garethbowen** [comment]
Anything in the api log?

**Comment by garethbowen** [comment]
@estellecomment Please raise that as a separate bug - it no doubt existed on the old modal based system too.

**Comment by garethbowen** [comment]
@estellecomment Other than that bug I think this commit ticks off all your other comments.

**Comment by diannakane** [comment]
> What is this importing/exporting exactly? Places and People? Are we still using the word "Contact" from now on? @diannakane please advise, so the UI can make sense.

What @garethbowen said! 

> There's already an "Export" configuration page, so it's clashing with this new page, I find it hard to know where to go. I suggest reusing the Export page: rename it to Import/Export, and add the contact import/export to it. Or alternatively, add a separate Import page for contact import, and reuse the Export page for contact export. Either way.

We have multiple types of things to import / export so we might not want to get too granular in our break-downs. Import: records, contacts. Export: records, contacts, messages. I could see us re-integrating export into the tabs once we get our filters re-designed, but import will likely stay as a config-only option, so maybe we break it down along those lines?

**Comment by garethbowen** [comment]
The admin page has been broken down by type which is good enough for now. We can review again when exporting is added back to the FABs.

**Comment by garethbowen** [comment]
That last commit removes the Export button from the FABs on Messages and Reports as discussed with @diannakane

**Comment by estellecomment** [comment]
Filed separately : 
Exporting messages crashes API : https://github.com/medic/medic-webapp/issues/2694
"Failed - Network Error" when exporting Contacts : https://github.com/medic/medic-webapp/issues/2695
Both issues with excessive data size.

**Comment by estellecomment** [comment]
UI looks great, I like the tabs!

One last thing : the icon for Import/Export should have arrows going both up and down. 
And then LGTM!

**Comment by garethbowen** [comment]
I looked for one in Font Awesome but couldn't find one. I could stack but it's a PITA. Do you recommend one?

**Comment by estellecomment** [comment]
There's this one, and maybe stack on a circle :
http://fontawesome.io/icon/arrows-v/

Or that one, that you can rotate with `fa-rotate-90` (90deg), would look better maybe:
http://fontawesome.io/icon/exchange/
