### ISSUE TITLE
Only show places you directly manage in LHS, unless searching

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2339]
Part 1: The left pane defaults to only show you the hierarchy of places that you directly manage. e.g. District manager sees only branches, Branch Manager sees only Area, CHWs see only households. 
Part 2: This list only changes with search results; when search results are cleared, it reverts back to this default list of “places I manage.” 
Note: In the future, we may introduce a filter to control your default view in the left pane, such as a “People / Places” toggle.

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by SCdF** [comment]
So I think this translates into:
 - Take the facility id of the current user
 - Take that facilities type
 - Go one type "down" (woe betide you if you're already at the bottom: not something that can happen right now I don't think)
 - Set that as the default internal filter configuration

**Comment by SCdF** [comment]
@diannakane so let's say that I am a CHP. Prior to this change I can go to contacts and scroll and scroll, and I will see all of my families and people in those families. After this change if I scroll and scroll, I only see families.

What happens if I type something in the search box? Should that only be searching families, or searching everything? In other words, if I want to find Alice who is in Bob's family, do I need to first search for Bob, and click that family, or should searching search people as well, allowing me to type Alice and find her directly?

**Comment by SCdF** [comment]
To re-quote that question more technically, are we:
 - setting a particular type as the base filter and adding to that when we do a text search, or
 - either doing a raw text search OR filtering by a calculated type

**Comment by SCdF** [comment]
I've created two PRs, one for each of those possibilities (I'm guessing it's the latter so I did the work anyway):
 - There is a default base filter that all searches work from: https://github.com/medic/medic-webapp/pull/2689
 - There is *either* a default base filter *or* you are doing a text search: https://github.com/medic/medic-webapp/pull/2690

**Comment by SCdF** [comment]
@estellecomment review for you. I'd suggest you just review https://github.com/medic/medic-webapp/pull/2690 , I doubt the first PR is going to be used (this one is the first one plus more anyway)

**Comment by diannakane** [comment]
@SCdF Your search results would still return a person, then default back to households when you clear. The LHS list is a pre-filtered list of places you manage, but any person or place you can see can appear here. 

Another scenario is, if you are manager, your LHS list will be the CHP Areas you manage, but if you search for "Kane" you will return "Dianna Kane, CHP" (person) "Dianna Kane Area" and "Kaney Household"

We'll be evolving to better ways to navigate among "mixed lists" in the future; this is a short-term fix to minimize the noise in the LHS for the places you need to see most often.

**Comment by SCdF** [comment]
So @estellecomment the above comment for reviewing is accurate!

**Comment by estellecomment** [comment]
Comments about how to get the place below you. Filed https://github.com/medic/medic-webapp/issues/2697
But looks good otherwise!

**Comment by SCdF** [comment]
Merged.
