### ISSUE TITLE
Update LHS FAB

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2341]
Only button in LHS FAB should be “New Place” of the place type that is shown in the list only (i.e. places you manage). For district managers, this would be “new branch;” for branch managers, this is “new area;” for CHWs, “new household.”

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by garethbowen** [comment]
@diannakane District managers can see and manage branches, areas, and households depending on the configured replication depth. With this proposal how will district managers add a new area? What will administrators see?

**Comment by estellecomment** [comment]
Full description, according to mock linked in https://github.com/medic/medic-webapp/issues/2344: I'm missing pieces, @diannakane and @Lesterng could you fill in the gaps please?

LHs FAB, depending on the logged-in user:
 - For admin view (home place is root, branches are listed in LHS) : "New Branch" 
 - For CHW supervisor view (home place is a branch, CHW Areas are listed in LHS): "New CHW Area" is always displayed in the LHS. (confirm @diannakane or @Lesterng ?)
 - For CHW view (home place is a CHW area, Households are listed in LHS) : "New Family" is always displayed in the LHS. (? @diannakane or @Lesterng )

@garethbowen: adding other places is done from FAB in the RHS, see https://github.com/medic/medic-webapp/issues/2344

**Comment by estellecomment** [comment]
Extra question @diannakane or @Lesterng : when I search in Contacts/People, the LHS now shows places of different levels in the hierarchy. 
What does the "New <Place>" button in LHS say? Is it shown at all?

**Comment by diannakane** [comment]
> LHs FAB, depending on the logged-in user:

> For admin view (home place is root, branches are listed in LHS) : "New Branch"
For CHW supervisor view (home place is a branch, CHW Areas are listed in LHS): "New CHW Area" is always displayed in the LHS. (confirm @diannakane or @Lesterng ?) For CHW view (home place is a CHW area, Households are listed in LHS) : "New Family" is always displayed in the LHS. (? @diannakane or @Lesterng )

Yes, right on all counts. 
If you click on the squares in the Invision FAB, you can see all of the mockups depending on user logged in. In our hierarchy, district=admin so there's no "my place" locked to the LHS. For the others, you can see who is logged in based on what places is locked at the top (branch or area). https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906822


> @garethbowen: adding other places is done from FAB in the RHS, see #2344

Correct

> When I search in Contacts/People, the LHS now shows places of different levels in the hierarchy. What does the "New " button in LHS say? Is it shown at all?

It stays as the default. The search lets you jump to a specific place or person's card, but this won't change the LHS FAB.

**Comment by estellecomment** [comment]
@SCdF please review! 
PR : https://github.com/medic/medic-webapp/pull/2708

Trying out a new controller testing approach, @garethbowen you're probably interested : https://github.com/medic/medic-webapp/pull/2708/files#diff-e2552baf6a41cfedb5e41ed972a7efefR190
It gets rid of the crazy setTimeouts and makes for clean tests, but it introduces test-specific code in the prod code. Choose your lesser evil :)

**Comment by SCdF** [comment]
@estellecomment LGTM, bar the one comment. I also took the liberty of changing labels to code review, apologies if you're in some flow state that I've mis-documented.
