### ISSUE TITLE
RHS UI updates as per mockup (no FAB, no CSS)(no Tasks, no History)

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2343]
e.g. 
— Breadcrumbs improved at top of right pane. 
-- Place and person cards UI
-- With the exception of “your place,” place cards include places that belong to them. (for “your place,” these places are already displayed on the LHS).

@Lesterng please provide details

**Comment by Lesterng** [comment]
@diannakane 
Breadcrumbs in upper left of RHS is now just a back button. Breadcrumb trail will be in the persons card under "Reports to:
-- Place card
https://invis.io/XA7CTCBGU#/159906666_District-branch
https://invis.io/XA7CTCBGU#/159906822_Branch
https://invis.io/XA7CTCBGU#/163504202_Area

**Comment by Lesterng** [comment]
Here are the specs for the updates
[Contacts-specs-dimensions.pdf](https://github.com/medic/medic-webapp/files/305746/Contacts-specs-dimensions.pdf)
[Contacts-specs-type.pdf](https://github.com/medic/medic-webapp/files/305747/Contacts-specs-type.pdf)

**Comment by Lesterng** [comment]
Link to Icon folder for right and left FAB. .svg files
https://drive.google.com/a/medicmobile.org/folderview?id=0Bz9vY9IxAz2PbTJkYktIR21zdlU&usp=sharing

**Comment by abbyad** [comment]
This should be considered along with #1572

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by estellecomment** [comment]
Filed https://github.com/medic/medic-webapp/issues/2709 to do all the CSS in one go across the whole page.

**Comment by estellecomment** [comment]
@diannakane please confirm : the new People tab displays no reports and no tasks, anywhere.

**Comment by estellecomment** [comment]
@diannakane : questions about edge cases.
If there are no People in this place, do we display the People section with nothing in it? Or no section?
Same thing for child places of the place, if there are none do we display empty section or nothing?

**Comment by estellecomment** [comment]
@diannakane 
In the lists of places and people belonging to a place, in what order do we display people and places? Is it the same order for all places?
E.g. two supervisors in a branch vs. two family members.

Right now: 
 - Places are sorted by name.
 - People are sorted by date of birth, then by name (which makes sense for family members, but less so for the several supervisors of a branch.). No special sorting for Primary Contacts (they don't show up on top).

**Comment by diannakane** [comment]
>  the new People tab displays no reports and no tasks, anywhere

Which view are you looking at? For mobile app projects, we have both tasks and reports on household and family member profiles. Eventually, this will show up on CHW and manager profiles as well in the manager view we are designing. SMS projects with v0.4 config won't have tasks or reports since we aren't dealing with "patients as people" yet. SMS projects on v2 config will show reports on a patient's profile but tasks are not applicable.

> If there are no People in this place, do we display the People section with nothing in it? Or no section? Same thing for child places of the place, if there are none do we display empty section or nothing?

I think showing empty sections, be it People or tasks and history on a person's profile, is instructional because it shows the user how the program might be used and may prompt them to "add a person" and understand that when a task is scheduled, it will show up there. 

> In the lists of places and people belonging to a place, in what order do we display people and places? Is it the same order for all places?
> E.g. two supervisors in a branch vs. two family members.
> 
> Right now:
> Places are sorted by name.
> People are sorted by date of birth, then by name (which makes sense for family members, but less so for the several supervisors of a branch.). No special sorting for Primary Contacts (they don't show up on top).

I am a fan of showing the Primary Contact at the top of the list, with the rest sorted alphabetically by name beneath (for staff members) and by date of birth (for family members). Is there a reason we wouldn't want to write different rules for ordering of people in different places? Note that in new SMS projects on v2, family members will all belong to the same CHW Area, not to households. Following this rule, the Primary Contact (CHW) would be at the top and all family members would be organized alphabetically by name. Where there are multiple CHWs, it would be useful to differentiate them from family members in this list, either by using the sub-title space to list their role type ("CHW", though that's related to #2693) or by sorting them all to the top.

**Comment by estellecomment** [comment]
>> the new People tab displays no reports and no tasks, anywhere

> Which view are you looking at?

The ones linked at the top of the issue!
Person card, no tasks or report : https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906719
But I see that the mocks for Family and Family Member were done since then, in https://github.com/medic/medic-webapp/issues/2346
I'm going to remove tasks and history from this issue then, and tackle them in that one.

**Comment by estellecomment** [comment]
@SCdF please review! (so far)

**Comment by SCdF** [comment]
LGTM

**Comment by diannakane** [comment]
@estellecomment Ohhhh, that's because it's a CHW profile. See #2346 "Tasks and History show up on Household and Family Member profiles only"

**Comment by estellecomment** [comment]
Filed off separately, in an attempt to chop up work into understandable segments : breadcrumbs and navigation https://github.com/medic/medic-webapp/issues/2731

**Comment by estellecomment** [comment]
@SCdF please review PR : https://github.com/medic/medic-webapp/pull/2738/files

**Comment by estellecomment** [comment]
@SCdF is in a park.
@alxndrsn please review!

**Comment by estellecomment** [comment]
Closing, since the rest of the work is described in other issues.
