### ISSUE TITLE
Updates to RHS FAB

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2344]
Add “New Action” to RHS FAB. The list of actions will be contextualized to the place or person card you are viewing on the RHS.  Note: In household / family member view, this removes “actions” from its place in the right pane and puts it into the FAB on the same page.

**Comment by Lesterng** [comment]
All FAB updated. Contextualized in RHS.
https://invis.io/XA7CTCBGU#/159906705_District-area

<img width="724" alt="screen shot 2016-06-08 at 2 33 34 pm" src="https://cloud.githubusercontent.com/assets/5149601/15911772/09a899fa-2d86-11e6-8f1e-651814d81cde.png">

<img width="424" alt="screen shot 2016-06-08 at 2 34 28 pm" src="https://cloud.githubusercontent.com/assets/5149601/15911784/219d2256-2d86-11e6-8f06-8912607b69c0.png">

**Comment by abbyad** [comment]
This is for consideration as part of the work in #1572

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by estellecomment** [comment]
Ok! Here's a full description from the linked mock, though I have missing pieces. @diannakane or @Lesterng, could you help fill in my gaps please?

RHS FAB, depending on what is displayed in the RHS:
- "New < Place >" where place is directly below in hierarchy (e.g. if a branch is displayed in RHS, "New CHW area")
-  "New Person" : 
   - if a Branch or CHW area is displayed in RHS : creates a Primary Contact person for to the currently displayed place. (You can also change the place with dropdowns in the modal, in which case you end up creating a primary contact for that place you selected in the dropdowns.)
    - if a Household is displayed in RHS : creates a Family Member with option to be Primary Contact (? @diannakane or @Lesterng )
- "New Action" : unchanged, lists actions relating the the place or person in the RHS (? @diannakane or @Lesterng )
- "Edit" edits the place or person in the RHS.

LHS FAB is covered in https://github.com/medic/medic-webapp/issues/2341.

**Comment by estellecomment** [comment]
Just an extra check : "Send Message" button is gone from the Contacts/People tab, at all levels. Does that sound right @diannakane ?

**Comment by estellecomment** [comment]
Other check : "Delete" button is gone from Contacts/People tab, at all levels. Is that right too? @diannakane

**Comment by diannakane** [comment]
Thanks, @estellecomment ! Comments in-line below. Feel free to ping me to discuss anything.

> RHS FAB, depending on what is displayed in the RHS
Yes!

> "New < Place >" where place is directly below in hierarchy (e.g. if a branch is displayed in RHS, "New CHW area")
Correct

> "New Person" :
> if a Branch or CHW area is displayed in RHS : creates a Primary Contact person for to the currently displayed place. (You can also change the place with dropdowns in the modal, in which case you end up creating a primary contact for that place you selected in the dropdowns.)
Currently, a place must have a primary contact, so this gets created in the "New Place" stage. Any new people subsequently added to that place are not the primary contacts. Primary contact can be edited from the Place by selecting a new primary contact from the drop-down.

> if a Household is displayed in RHS : creates a Family Member with option to be Primary Contact (? @diannakane or @Lesterng )
Primary contact works same as above -- the first person created is the PC by default and can be changed from the Edit Household. If a household is displayed in RHS, person will be a family member by default.

> "New Action" : unchanged, lists actions relating the the place or person in the RHS (? @diannakane or @Lesterng )
Correct

> "Edit" edits the place or person in the RHS.
Correct!

> "Delete" button is gone from Contacts/People tab, at all levels. Is that right too?
Delete button now found within the "edit" box or three vertical dots drop-down (in the case of mobile), and is actually disabled for most users.

> "Send Message" button is gone from the Contacts/People tab, at all levels. 
"Message" only in web, "Call" only in mobile. Should appear in the RHS Fab when on a person card. For instance, "Alison Jones" not "Alison Jones Household." https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906719

**Comment by sglangevin** [comment]
@diannakane I didn't realize we were going to remove the ability to send a message to a contact from the mobile view. Is there a way to fit that? I'm not sure that I have a specific user request for it off the top of my head, but it seems like it could be useful.

**Comment by diannakane** [comment]
@sglangevin and I just confirmed the confusion. 

In mobile, ability to "call" and "message" from a person card (sorry I misspoke above), both of which launch the phone's native call/message applications.
https://projects.invisionapp.com/share/QD7ML6T7C#/screens/166359152

In web, ability to "message" from a person card, though this doesn't appear to be working. We would expect it to launch the messages tab or a modal to send a message from Medic. @garethbowen 
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/163504603

**Comment by estellecomment** [comment]
@SCdF please review! https://github.com/medic/medic-webapp/pull/2698
(tests are flaking but nothing related is failing.)

Not done yet, will do after, ignore for this review :  
- [ ] Translations not working
- [ ] Send Message button is not aligned
- [ ] When you click on the buttons, the forms don’t look like the mocks. But the urls should look right (e.g. create a person in clinic ‘abcde’ : `abcde/add/person`)
- [ ] Actions button is missing

**Comment by SCdF** [comment]
@estellecomment reviewed! Left some style comments, but that's it. I thought I'd check out it and have a look around. Should I expect to see `New Action` in the FAB?

**Comment by estellecomment** [comment]
Nope, no New Action yes, it's in the todo list above. Just wanted to get this part merged in before launching into new adventures. 

Thanks!

**Comment by estellecomment** [comment]
- [ ] Icons match the old hierarchy (District, Health Center, Clinic) while labels match the new (Branch, CHW Area, Family)

**Comment by estellecomment** [comment]
Filed https://github.com/medic/medic-webapp/issues/2705

**Comment by estellecomment** [comment]
Filed https://github.com/medic/medic-webapp/issues/2706

**Comment by estellecomment** [comment]
@SCdF please review again!
https://github.com/medic/medic-webapp/commit/451ded7524628869453824b36189ca1c6fc8598b
https://github.com/medic/medic-webapp/commit/c587f2eb71ddb16b9fc855463fa3a1ba44b9cb59
https://github.com/medic/medic-webapp/commit/49fe19ff435f82bd7af42cbca15337f42d964c13

**Comment by SCdF** [comment]
Made some test comments, otherwise LGTM

**Comment by estellecomment** [comment]
Translations filed separately : #2710
