### ISSUE TITLE
When creating a person on lg.app, I intermittently get Error updating contact

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2349]
![image](https://cloud.githubusercontent.com/assets/1286381/15755312/fb15eb2e-28b0-11e6-9d68-8b866f176b19.png)

As admin, trying to add people has become progressively more difficult. The 10 second timeout makes it impossible to know that you have successfully created a person in the UI. Despite the error message, the person is getting created and can be found if you search for the UUID in Couch. For this example, see the resulting document here: https://lg.app.medicmobile.org/_utils/document.html?medic/4f990cce0a989ac7319c19b1bb462c9f

Admin performance is starting to reach a critical point - we should consider prioritizing admin performance issues if possible.

**Comment by alxndrsn** [comment]
Looks like a direct consequence of https://github.com/medic/medic-webapp/issues/2325 - can probably be treated as a particular case of that ticket.

**Comment by alxndrsn** [comment]
@sglangevin how did you get to the _Add Person_ form for _Masajja_?  I could only do this by hacking the URL, after which it looks like it created ok.

**Comment by alxndrsn** [comment]
I can create a person without error: https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/65bba0958df604ed40b941389437fa31

The title of this issue implies that creating a person _always_ fails for you, @sglangevin.  Is that the case, or can the ticket title be changed to reflect that the issue is intermittent?

**Comment by sglangevin** [comment]
@alxndrsn I've updated the title. I hack the URL for adding people. It always creates the person, but if the server is under heavy load, I get an error message in the UI because of the famous 10 second timeout.

**Comment by alxndrsn** [comment]
Should be working on `develop`.

**Comment by ngaruko** [comment]
Hi @sglangevin . I am not clear if this issue was fixed and it seems to be hard to reproduce since it is intermittent...Are we satisfied with the current performance?

**Comment by sglangevin** [comment]
@ngaruko as far as I know, the current performance is acceptable, but I haven't tested this recently so I'm not sure how it is working at the moment. I can test again and give you my opinion, if that would help - let me know.

**Comment by ngaruko** [comment]
@sglangevin  I think we will move on and raise an issue if that happens again.
