### ISSUE TITLE
No `resources` doc in .4 db

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2354]
In 2.6 the custom-uploaded icons are fetched as attachments to a `resources` doc.
They are used by `liveList`, so it breaks Tasks. 
Edit : contacts and reports are actually fine, they don't use resourceIcon.

**Comment by estellecomment** [comment]
There's a migration for it : 
https://github.com/medic/medic-api/blob/develop/migrations/add-resources-doc.js

**Comment by garethbowen** [comment]
@estellecomment The migration should run on api startup and create this doc. Is it not working or can we close this?

**Comment by estellecomment** [comment]
Was waiting to see it happen properly. It does. Closing.
