### ISSUE TITLE
Check national-admin works

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2355]
LG want to have administration access with separate logins which equates to having users with national-admin role. We haven't used this in ages so test to ensure it works sensibly.

Some thoughts

* does it try to replicate locally?
* does it try to generate tasks for all?
* can you edit things as expected?

**Comment by alxndrsn** [comment]
| 
---|---
    does it try to replicate locally? | no 👍 
    does it try to generate tasks for all? | no 👎
    can you edit things as expected? | no 👍 

-----

I set up a user:
<img width="1280" alt="screen shot 2016-06-07 at 12 22 53" src="https://cloud.githubusercontent.com/assets/191496/15854531/b34b43a4-2caa-11e6-920b-464dcbb251c4.png">

Some tabs are missing:
<img width="1280" alt="screen shot 2016-06-07 at 12 21 34" src="https://cloud.githubusercontent.com/assets/191496/15854537/b74de3a8-2caa-11e6-8d6f-39eecefaed86.png">

Tasks are disabled as expected:
<img width="1280" alt="screen shot 2016-06-07 at 12 26 10" src="https://cloud.githubusercontent.com/assets/191496/15854611/0ae4c96e-2cab-11e6-8a80-e5ddfbeb28da.png">

I think the DB is remote:
<img width="1280" alt="screen shot 2016-06-07 at 12 21 34" src="https://cloud.githubusercontent.com/assets/191496/15854537/b74de3a8-2caa-11e6-8d6f-39eecefaed86.png">

Cannot edit a contact:
<img width="1280" alt="screen shot 2016-06-07 at 12 29 53" src="https://cloud.githubusercontent.com/assets/191496/15854736/c6efb3d0-2cab-11e6-843e-4c9d9f8fe737.png">
...but I don't think this is directly related to being a `national_admin`

**Comment by garethbowen** [comment]
@alxndrsn There are some broken characters in the table that summarises the results - I assume they were all thumbs up?

**Comment by alxndrsn** [comment]
<img width="270" alt="screen shot 2016-06-07 at 23 04 33" src="https://cloud.githubusercontent.com/assets/191496/15874602/39fa5cba-2d04-11e6-9e07-e7e90d0368ba.png">

**Comment by garethbowen** [comment]
@alxndrsn Thanks for that.

I think "no" is the desired outcome for generating tasks. If it tried to generate tasks it would hang their machine.

I think "no" is the incorrect outcome for "edit things as expected", surely? Is that a typo?

**Comment by alxndrsn** [comment]
Yeah, definitely some confusing thumbs there...

**Comment by garethbowen** [comment]
> Yeah, definitely some confusing thumbs there...

@alxndrsn What are they supposed to be? Is it working or not?

**Comment by alxndrsn** [comment]
The text is correct: 

*    does it try to replicate locally? NO
*   does it try to generate tasks for all? NO
*  can you edit things as expected? NO

**Comment by garethbowen** [comment]
Can you explain what things you couldn't edit as expected?

**Comment by alxndrsn** [comment]
I could not edit a contact.  I would expect this to work for a `national_admin`.  When trying to save a contact from the edit form, I received validation errors, as shown in this screenshot:
<img src="https://cloud.githubusercontent.com/assets/191496/15854736/c6efb3d0-2cab-11e6-843e-4c9d9f8fe737.png"/>

**Comment by garethbowen** [comment]
Raised #2395 to address this.
