### ISSUE TITLE
Create replica of v2.6.x LG production instance specifically for administrative users

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2357]
As a temporary measure to improve performance for LG administrators, create a new and/or cloned instance, and enable continuous replication between that instance and the current instance. This should have the effect of isolating the high-CPU replication filter workload from ordinary interactive use by an `admin`.

**Comment by browndav** [comment]
Instance created. Based on a conversation just now in Slack, this may not be needed after all. I'll leave the instance around but stopped until at least the end of this iteration, so it's ready to go if we end up wanting it after all.

**Comment by garethbowen** [comment]
This has been around for a month now - I vote we drop the instance and close this issue. @browndav What do you think?

**Comment by browndav** [comment]
I agree, closing as unnecessary.
