### ISSUE TITLE
Improve AWS EC2 tagging: add administrative and technical contacts to all instances, document tags

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2359]
Add partner administrative and technical contacts to each instance. Consider adding a Medic Mobile regional contact to all instances. Document the meaning of these tags in a Markdown document.

These are useful for communicating downtime to partners, coordinating updates, and in some cases troubleshooting unexpected behavior or performance problems.

**Comment by browndav** [comment]
Toward #2359: https://gist.github.com/browndav/731346a73a41bc6f8e4f9e929b5eb24d

**Comment by estellecomment** [comment]
Maybe it's just me, but I understand `Backup` as 'this is a backup machine, not a real prod machine' (like `backup.dev.MM.org`), which is the opposite of what you mean.

If the important thing is to not discard the data, then maybe `Production` (vs testing and backup)? Or if the important thing is that there's a backup mechanism for it, `hasBackup` or `needsBackup`? 

Or just `ifYouDiscardMePartnershipsPeopleWillHaveSomeSeriousExplainingToDo`. Fully descriptive.

**Comment by SCdF** [comment]
_(FWIW the use of backup makes sense to me, but to avoid confusion it could be renamed to `requiresBackup` or something like that)_

**Comment by browndav** [comment]
Good point; I'll fix it today.

**Comment by browndav** [comment]
Addition: I'd propose that we always back up any instance tagged as `Environment: production`, and use the `Backup` tag (or, rather, what we rename it to) for exceptions, e.g. when we explicitly want to back up a development instance. Minor change, but I think it'll reduce error.

**Comment by browndav** [comment]
Update: talking with the right people today to get accurate data and fill in the admin/technical contact tags.

**Comment by browndav** [comment]
Hey @mandric, would you mind reading over https://gist.github.com/browndav/731346a73a41bc6f8e4f9e929b5eb24d and letting me know if it sounds reasonable? I'll incorporate suggestions and move it into a more permanent location this week.

**Comment by browndav** [comment]
Documentation now lives at https://github.com/medic/medic-servers/blob/master/docs/aws-tags.md.
