### ISSUE TITLE
Fix changes proxy to support heartbeat

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2363]
When requesting changes through pouch we use two related parameters to manage keeping the connection alive.

`heartbeat`: Couch sends a `\n` character at this frequency which keeps the connection alive.
`timeout`: Couch ignores this if `heartbeat` is provided so the request will be kept alive. However Pouch will forcibly cancel the request if `timeout` is provided and it doesn't hear a heartbeat.

In API for watching the design doc and any admin changes requests we proxy the request directly to couchdb to handle.

In production we're seeing design doc watch requests get cancelled by pouch which indicates the heartbeat isn't working. I can't reproduce this locally which makes me think it's something to do with nginx.

![changes-timeout](https://cloud.githubusercontent.com/assets/2064938/15876779/8f2b6314-2d63-11e6-9149-7c4214824eac.png)

I've mitigated this by increasing the timeout to 1 hour, but the better solution is to fix the heartbeat and use the default timeout so the request is killed if the server stops beating.

**Comment by alxndrsn** [comment]
Issue confirmed.  Looks like it should be fixable with [`client_body_timeout`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout).  The value for `client_body_timeout` should be related (but greater than) the time after which pouch will kill the `_changes` request voluntarily.  But does it _ever_ do this?  Setting an unlimited timeout in nginx seems dangerous, but perhaps the only option if we expect `_changes` longpoll requests to continue indefinitely.

**Comment by alxndrsn** [comment]
Observation: going to couch direct or via `medic-api` locally, `{"results":[` is written immiediately, whereas on a live server with nginx, nothing is written until a db change occurs.

**Comment by alxndrsn** [comment]
i.e.:
```
user@test-server:~ $ curl 'admin:pword@localhost:80/medic/_changes?feed=longpoll&since=12811'
^C
user@test-server:~ $ curl 'admin:pword@localhost:5984/medic/_changes?feed=longpoll&since=12811'
{"results":[
^C
user@test-server:~ $ curl 'admin:pword@localhost:5988/medic/_changes?feed=longpoll&since=12811'
{"results":[
^C
```

**Comment by alxndrsn** [comment]
From which it seems clear we need to set `proxy_buffering` to `off` for api.

**Comment by alxndrsn** [comment]
PR for review.

**Comment by alxndrsn** [comment]
Oh yeah I might have just read this in the couch docs: https://wiki.apache.org/couchdb/Nginx_As_a_Reverse_Proxy#Continuous_Replication_through_nginx :¬)

**Comment by garethbowen** [comment]
I'm not 100% comfortable with this, mostly because I'm not nginx guru. I'm trying to work out what affect it might have on other requests. I think I'd feel more comfortable if the buffering was only disabled on the proxied longpoll requests by [setting the `X-Accel-Buffering` response header](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering) in medic-api which is more of a scalpel than a sledgehammer.

Did you find the buffering was eating up all the heartbeat characters?

**Comment by alxndrsn** [comment]
> Did you find the buffering was eating up all the heartbeat characters?

I doubt it's eating them – more likely just buffering them for later.  But I didn't wait around long enough to find out :p

**Comment by alxndrsn** [comment]
And yes, setting `X-Accel-Buffering` does sound neater.

**Comment by garethbowen** [comment]
> I didn't wait around long enough to find out :p

Right, but before this flag was set you weren't getting the heartbeat in the browser, and after it's set you were?

**Comment by alxndrsn** [comment]
Fixed in api at https://github.com/medic/medic-api/commit/2307f3c74e3eb177dce11476dce58e0e40d6dc43

**Comment by garethbowen** [comment]
Looks good.

**Comment by garethbowen** [comment]
AT: Watch the network tab and ensure the _changes request doesn't timeout after 30s - it should stay alive as long as the client and server are both online.
