### ISSUE TITLE
Investigate apparent medic-api / medic-webapp version mismatch on the gateway-testing server

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2364]
Filing as unassigned since it's in my queue and I'm holding people up.

We need to take a look at the gateway-testing development server and figure out why the Reports tab is throwing errors. The web app appears to be requesting https://gateway-testing.dev.medicmobile.org/api/v1/fti/data_records, which the installed version of `medic-webapp` returns a 404 for.

Current thinking: Compare the installed version to git to rule out versioning issues, configrm that Lucene is actually running, and take a look at the nginx configuration to figure out if we're missing a `proxy_pass` entry or something like that.

**Comment by alxndrsn** [comment]
Deployed webapp version:

<img width="499" alt="screen shot 2016-06-08 at 12 10 05" src="https://cloud.githubusercontent.com/assets/191496/15891480/f8e354cc-2d74-11e6-8c2a-3736150999de.png">

Which corresponds to:

https://travis-ci.org/medic/medic-webapp/builds/60898141

Which corresponds to:

https://github.com/medic/medic-webapp/commit/f90590eb27e5b801803e5ad60257ea2c2c0ea7cc

**Comment by alxndrsn** [comment]
Errors seen in webapp console:

<img width="541" alt="screen shot 2016-06-08 at 12 36 46" src="https://cloud.githubusercontent.com/assets/191496/15891609/b8ab27f8-2d75-11e6-8ab9-5251dc9ea128.png">


There do not appear to be any `fti` endpoints defined in `medic-api`'s `master` branch: https://github.com/medic/medic-api/blob/master/server.js

**Comment by alxndrsn** [comment]
...although there's something that looks very relevant at https://github.com/medic/medic-api/blob/master/controllers/utils.js#L28

**Comment by alxndrsn** [comment]
Looks like it would help a lot to use 0.4.x instead of this 0.5.0-alpha version of webapp on the gateway-testing server.
