### ISSUE TITLE
Migration "extract-user-settings-roles" failed

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2367]
On lg-testing (using the current alpha) the `extract-user-settings-roles` migration is failing with

```json
{
  "message":"missing",
  "stack":"Error: missing\n    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/nano/lib/nano.js:248:15)\n    at Request.self.callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:200:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:1067:10)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/request/request.js:988:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickDomainCallback (node.js:381:11)",
  "name":"Error",
  "error":"not_found",
  "reason":"missing",
  "scope":"couch",
  "statusCode":404,
  "request":{
    "method":"GET",
    "headers":{
      "content-type":"application/json",
      "accept":"application/json"
    },
    "uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/org.couchdb.user%3Anakiguddegl"
  },
  "headers":{
    "date":"Wed, 08 Jun 2016 21:16:49 GMT",
    "content-type":"application/json",
    "cache-control":"must-revalidate",
    "statusCode":404,
    "uri":"http://XXXXXX:XXXXXX@localhost:5984/medic/org.couchdb.user%3Anakiguddegl"
  },
  "errid":"non_200",
  "description":"couch returned 404"
}
```

**Comment by garethbowen** [comment]
This is also failing on lg.app

**Comment by estellecomment** [comment]
(chiming in because I'm looking at migrations these days)
Don't we want to know if there aren't any user-settings docs? This change skips the record silently. 

`extract-user-settings` migration should have created the user-settings (why didn't it?), and that user is going to be seriously messed up without user-settings. 
Or is this a different type of user or something?

**Comment by mandric** [comment]
Is there any documentation on what this migration is supposed to do, seems like we're supposed to understand the purpose of the migration based on the name of the migration?  It's hard to complete this code review without having this information.  It might be good to have a comment block in each migration that explains what the purpose of it is?

**Comment by garethbowen** [comment]
The migration copies the roles from the _users database into the user-settings doc in the medic database so the app knows what features to show to the user while offline or without access to the _users db.

> Don't we want to know if there aren't any user-settings docs?

Yes probably, but I don't want to block all other migrations because of one user that's already broken. Currently migration failures aren't noticed in production, they're just quietly logged every time the api starts up. So having this migration fail is not a good way to let us know about the issue.

I'm tempted to not start up api until the migrations have finished which would make this failure obvious, but it would also cause longer outages.

Whatever we pick is outside of the scope of this bug.

**Comment by estellecomment** [comment]
+1 for documentation :)

Issue about migration failures is here : https://github.com/medic/medic-webapp/issues/2201

Logging the problem would be good though, otherwise we'll really never know.

**Comment by garethbowen** [comment]
No AT required.
