### ISSUE TITLE
Map out user types

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2368]
With the confluence of v0.4 and v2.6 we are discussing user types that can mean different things in the previous versions. For instance "district managers" are at different levels of the hierarchy in v0.4 and v2.6 (eg #2339, #2341). To clarify this we should map out all of the roles along with their access to serve as a reference, as well as help us discover if new user types need to be created.

**Comment by SCdF** [comment]
@abbyad since 0.4 is now (completely?) gone, does this ticket have any relevance anymore? Presumably with all of those migrations we have already solved this issue..

**Comment by sglangevin** [comment]
It does still have relevance, but only in the sense that we'd like to have more role types from the user perspective, as our role based administration capabilities aren't as robust as what we need. I think we can close this issue for now, though.
