### ISSUE TITLE
Lowercase all user ids

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2369]
It's confusing to have users whose ids only differ by case, eg: "Sam", "sam", "SAM".

Instead we should normalise user ids to all be lowercase. Make sure everywhere where users can be added or edited (UI, API, etc) user ids are lower cased. This includes user in the _users db _and_ the user-settings docs in the medic db. We already have document update validation which enforces this, but we should protect the configurer from getting that far.

Now we need a migration to lowercase all ids. This must run before the migrations which already exist which modify the users or user-settings because these migrations currently fail on the aforementioned validation so the new migration will never be run. Migrations are run in date order so predate the migration before all the existing user migrations and it should work.

Then change the login page to lowercase the username.

**Comment by estellecomment** [comment]
Doing that! In #2361. That issue is a better description though.

I'm actually editing the `extract-user-settings` migration, instead of creating a separate one. Guess I could do either. Do you have strong thoughts about this?

**Comment by estellecomment** [comment]
@garethbowen please review

**Comment by garethbowen** [comment]
Looks pretty good. It's usually not a good idea to add functionality to an existing migration. This is because any server that has already executed the migration will never execute it again and so won't be in a known state. This case is a little special because the previous migration may have already created a document that no longer validates. Given this I think it's ok to modify the migration this time. It just means that I'll have to do a manual migration for the uppercase user on lg.app (but I was planning to do this anyway).

**Comment by garethbowen** [comment]
@estellecomment What state is this in?

**Comment by estellecomment** [comment]
? What do you mean what state? Are you complaining that it's been open too long, since I'd had a full minute to acknowledge your code review? :D 

Closing it.

**Comment by garethbowen** [comment]
@estellecomment I mean "acceptance testing", "code review", etc. It was sitting in Scheduled.

**Comment by estellecomment** [comment]
Ah ok. Yes. Thanks :)

**Comment by estellecomment** [comment]
Missed a piece! Rereview?

**Comment by garethbowen** [comment]
LGTM

**Comment by estellecomment** [comment]
@ngaruko can you create a user with a capital letters? You shouldn't be, from the UI.

**Comment by ngaruko** [comment]
@garethbowen @estellecomment There is an ongoing conversation on Slack on how this user id/username capitalisation may be improved. I will file a different issue on that.
