### ISSUE TITLE
Use server side pagination for Search service

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2370]
The Search service is used in a variety of ways from populating the LHS of the Contacts and Reports tabs, to populating people dropdown fields. If applying any filters (eg: if you only want people in your contacts result like the dropdowns do), then we use views which we need to sort by value. As couch only allows views to be sorted by key we end up fetching all view results to the client and sorting there. Fortunately we don't `include_docs` so the results aren't too big, but we can do better!

If we use a couch list we can instead fetch, sort, and paginate on the server and save that bandwidth.

This only really applies to admin because restricted users are only accessing everything locally anyway, but to keep the codebases the same we could use the [pouch-list plugin](https://github.com/pouchdb/pouchdb-list).

This follows on from #2237

**Comment by estellecomment** [comment]
Would `startkey_docid` help you there?
http://docs.couchdb.org/en/1.6.1/couchapp/views/pagination.html
(I ran into it when paginating my deletion scripts, but couldn't get it to work. Not sure why. So might not be great.)

**Comment by garethbowen** [comment]
No I don't think that helps us here. The problem is in the view definition. All couchdb views are sorted by the key and can only be filtered by the key, but we need the sort order and the filter parameter to be different things.

For example we use the `contacts_by_type` view to return results when the user sets the type filter on the Contacts page. The key for this view is the `doc.type`, eg: "clinic". This is used for filtering, eg: `?key=[['clinic']]`. But we want to sort by the name of the clinic, so we return a value of `doc.name`. Then when we get all the view results we can sort, then paginate, then fetch the data for those clinics.

The current solution involves sorting on the client side which means shipping all the view results to the client. The proposed change will operate in basically the same way except do the sorting on the server, so we only send the page of data back to the client.

**Comment by alxndrsn** [comment]
Work so far on https://github.com/medic/medic-webapp/tree/search-with-lists - this converts all searches to use server-side filtering via couchdb lists.

From discussion with @garethbowen, recommended direction for this is:

1. use the list-based search when filtering contacts by a single field, but keep the old search when filtering by more than one field
2. write a new list specifically for free-text search within a specific type or types of contacts.  This would be particularly useful for speeding up contact-dropdowns in enketo forms for admins, as it would allow a decrease of the number of characters required before searching in `select2` boxes, i.e. select2's `minimumInputLength` at https://github.com/medic/medic-webapp/blob/search-with-lists/static/js/services/select2-search.js#L120.  This may be filed as a separate issue (@sglangevin?)

It's worth checking how the above apply to _Reports_, but likely only point **1** is relevant, and the same optimisations will be applied as for contacts, as they both share the `Search` service.

**Comment by sglangevin** [comment]
@alxndrsn I hadn't filed that as a separate issue. Ideally, the minimum input length would be 0, so that when you click on a drop-down, you see the first page of results and can then type in a search term to filter. I'll be filing another issue for the New Contact option not appearing without a search.

**Comment by alxndrsn** [comment]
This ticket does not seem to be a priority - removing from current milestone.

**Comment by garethbowen** [comment]
Reprioritising as requested by @sglangevin

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
This is good but it's ancient so I'm closing it until server side search performance becomes a priority.
