### ISSUE TITLE
Contacts pagination is broken

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2373]
As an admin viewing the contacts list doesn't show districts at the top as you'd expect. If you scroll down more and more contacts load in and are shuffled into the right place. Eventually districts will get added to the top.

**Comment by garethbowen** [comment]
This is usually caused by the server side sorting of the view not matching the sorting in the UI.

**Comment by garethbowen** [comment]
Mostly this was resolved by #2371 but I fixed some additional edge cases for when filters were returning view results in a different order than that used in the UI.

**Comment by SCdF** [comment]
LGTM

**Comment by sglangevin** [comment]
This is working as expected - moving to ready.
