### ISSUE TITLE
`setup_complete` is set too fast, so setup wizard is likely to be skipped

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2376]
When you get to the setup wizard, we set the `setup_complete` field in app_settings as you start.
Because you're watching the ddoc, you get an update prompt on top of the wizard.

![screen shot 2016-06-09 at 17 01 59](https://cloud.githubusercontent.com/assets/911434/15934531/393fa2ce-2e64-11e6-8409-6b9e4ad2b04e.png)

That in turn is likely to make you click around to get rid of all these popups and miss the wizard.

Would be better to set the `setup_complete` var on modal close (regardless of the cause of closing)

**Comment by garethbowen** [comment]
Fixed as part of https://github.com/medic/medic-webapp/issues/3078
