### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2377]
Seen in v2.7.0-alpha-3425 on Tecno
![image](https://cloud.githubusercontent.com/assets/1286381/15939981/edc2c770-2e2e-11e6-8c96-964f9aa211d1.png)
![image](https://cloud.githubusercontent.com/assets/1286381/15940010/0508ac6a-2e2f-11e6-8f76-d5caeeaa4976.png)

**Comment by garethbowen** [comment]
@sglangevin Thanks for including the screenshot to the source, but it's not highlighting the correct line (it's just showing line 1). I think after you turn on pretty print the line numbers in the error should update and then if you click the error again it'll take you to the correct line.

**Comment by sglangevin** [comment]
@garethbowen thanks, forgot that last step - so close! Let me try and reproduce and then I'll post a new screenshot.

**Comment by garethbowen** [comment]
Thanks!

**Comment by sglangevin** [comment]
![image](https://cloud.githubusercontent.com/assets/1286381/15950711/2a1ada96-2e66-11e6-9c3c-fe004072c52c.png)

**Comment by garethbowen** [comment]
This is caused by attempting to JSON parse the "Forbidden" result. This is partly the fault of #2379 and poor handling of the replication retry in pouchdb (https://github.com/pouchdb/pouchdb/issues/5325).

**Comment by garethbowen** [comment]
I've worked around this issue by fixing #2379 and returning valid JSON on forbidden. I'll also see if I can patch pouch to handle failures better.

**Comment by garethbowen** [comment]
It looks like the recursion loop is in the pouchdb clone utility which implies we were passing an argument with an object loop. I haven't managed to reproduce this.

**Comment by SCdF** [comment]
:shipit: !

**Comment by sglangevin** [comment]
AT'ed a while ago. Moving to ready.
