### ISSUE TITLE
Contacts tab takes forever to load on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2378]
2.7.0-alpha-3425

I get a spinner for a long time (minutes) when trying to load the contacts tab. I haven't successfully loaded it yet. Doing a manual reload from About page seems to resolve the issue.

**Comment by garethbowen** [comment]
Are there any errors in the console?

**Comment by sglangevin** [comment]
@garethbowen no relevant-seeming errors, though I'm wondering if this is related to #2377 because contacts loaded normally after a reload and I no longer saw those errors in the console. Let me get on reproducing that one now.

**Comment by SCdF** [comment]
I've assigned this to you @sglangevin to make it clear there is no dev work available to do on this right now. Let us know if you still have issues with it post #2377 or if there is anything for a dev to look into for you :-)

**Comment by sglangevin** [comment]
Post- #2377 I haven't seen this occur again.
