### ISSUE TITLE
Replication error on reload

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2379]
2.7.0-alpha-3425 on Tecno. Data seems to load fine, though - I was able to see tasks, contacts and history.
![image](https://cloud.githubusercontent.com/assets/1286381/15940308/58f8a374-2e30-11e6-9524-00e6e8be4df8.png)
![image](https://cloud.githubusercontent.com/assets/1286381/15940313/61267c10-2e30-11e6-9d25-9c404f19b543.png)

**Comment by garethbowen** [comment]
I wonder if you got "Forbidden". Viewing the network tab would be really useful here.

Did this just happen once?

**Comment by garethbowen** [comment]
I'm getting it too. Repeatedly. Looking into it.

**Comment by garethbowen** [comment]
Yes the changes feed is returning "Forbidden" which should only happen if you're asking for changes on a doc you're not allowed to see.

**Comment by garethbowen** [comment]
I made a small change to help me debug the issue and now I can't reproduce it. I don't _think_ I fixed it. More likely it's an issue that comes and goes. I'll leave it running for a while and see if it comes back.

**Comment by garethbowen** [comment]
Steps to reproduce this...

1. Log in
1. Go to Menu > Report Bug (ironically)
1. Fill in a bug report and submit
1. Wait for the report to be submitted
1. Refresh the page

What's going on is the feedback type doc isn't listed in the filter, but it does exist in the local db, which means we're requesting updates on it, but the server doesn't think we're allowed.

This will probably happen with other types too, but feedback types are easy to create.

We can either modify the view to allow feedback docs but that will share your feedback with everyone else which is, at best, a waste of bandwidth.

I think the correct solution is to query the doc_by_place view locally as well so you're only requesting IDs that you're allowed to see. That has a nice symmetry to it as we'll use the same view on both server and client.

**Comment by sglangevin** [comment]
Adding this here as this happened again for me - just a reference in case it's useful at some point. 
![image](https://cloud.githubusercontent.com/assets/1286381/15950941/7bee3ae6-2e68-11e6-82c0-1ca0dbb71b39.png)

**Comment by SCdF** [comment]
Looks good

**Comment by sglangevin** [comment]
This was AT'ed a while ago. Moving to ready.
