### ISSUE TITLE
Dashboard can't handle installing new versions of node modules

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2380]
If you change a version in the package.json of a kanso node module then Dashboard doesn't stop the old node module and just attempts to install the new one as well.

![update](https://cloud.githubusercontent.com/assets/2064938/15947379/4f475f36-2eef-11e6-931d-4ffef51380fb.png)

In the case of api this means the new api doesn't start:

```
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    ....
```

It seems to base uniqueness on the name of the file which in our case includes the version. Either patch Dashboard to use the name in the package.json, or modify our bundling to exclude the version from the attachment name.

**Comment by garethbowen** [comment]
The workaround for now is to leave version numbers the same - they're largely symbolic at this point...

**Comment by mandric** [comment]
I wonder if we can just pass gardener a github or npm url instead of bundling code on the ddoc.

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
Since we are planning to replace dashboard, I'm going to close this one. Please re-open if needed.
