### ISSUE TITLE
Report-sending from UI is broken in upgraded .4

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2383]
.4 projects have medic-reporter to send reports.
.6 projects send forms from the Actions FAB and Actions lists in the Contacts RHS.

Upgraded to .6, the Actions menu is empty, it probably can't find the JSON forms. 
So no form-sending at all!

**Comment by sglangevin** [comment]
Is this related to #2100?

**Comment by estellecomment** [comment]
No, this is an issue that happens when you upgrade a .4 project to .6 code. Probably because the JSON forms are stored differently internally than the xform ones. 
Nothing surprising, and not urgent for now, since no one upgraded yet.

**Comment by sglangevin** [comment]
Yeah, I also saw this issue when testing an upgrade - nothing to do with xforms - and I think that issue I mentioned was the issue that was filed, but I could have been wrong about that. Either way, installing JSON forms wasn't working properly with upgrades and I know there was an issue filed somewhere about that a little while back.

**Comment by estellecomment** [comment]
So, the JSON forms are not shown in the Actions menu in the reports tab, because only xforms are fetched.

So I'm going to add them in, and when you click the name in the menu, you get to a modal containing medic-reporter in an iframe, for filling in the form (vs. XForms which get a real page, no change there.). 
So it'll be similar to 0.4 with its "+" menu.

**Comment by estellecomment** [comment]
@mandric I made a small add to medic-reporter, could you review please? (the rest of the code is coming later)

**Comment by mandric** [comment]
👍

**Comment by estellecomment** [comment]
@mandric can you review again please? It's basically just this last commit : 
https://github.com/medic/medic-webapp/commit/12462665c3aaf99962580443d18e43a95b404e0c

The e2e tests are looking more and more complicated, so that'll come later.

**Comment by mandric** [comment]
👍

**Comment by estellecomment** [comment]
@garethbowen here are the missing bits... They're home now! Please review last commit.

**Comment by garethbowen** [comment]
Looks good. Won't you also need the trailing slash on the iframe not just the test url? It's a little more tricky but if you add the slash to the uri before passing it to the getTestUri function then you'll get the trailing slash for both.

**Comment by estellecomment** [comment]
Ha! Good point, it breaks it!
Wanna review again, or is that enough reviewing for this one?

**Comment by garethbowen** [comment]
Nice.

**Comment by estellecomment** [comment]
No Acceptance Testing needed since this got removed by https://github.com/medic/medic-webapp/issues/2988.

**Comment by ngaruko** [comment]
No AT needed
