### ISSUE TITLE
Some projects will need a renaming migration for CHW areas

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2384]
In .4, the CHW areas (`clinic`) are named by the "town" field in the Facilities table : 
![image](https://cloud.githubusercontent.com/assets/789512/15970167/5675963a-2f01-11e6-9843-d8219bf4380e.png)

But some projects like ChristianAid2 don't use that field, i.e. the CHWs don't have a specific town/village that they are assigned to, they are assigned to the bigger health_center. So they chose to reuse the name of the health_center for that field.

The result after upgrading is a list of CHW areas all called with the name of the parent health_center, which is not what we want. 
![screen shot 2016-06-10 at 17 04 07](https://cloud.githubusercontent.com/assets/911434/15968845/bd008cc6-2f2d-11e6-81f3-a927894d2eff.png)

We should rename CHW areas to i.e. "CHW 2's Area". That would be done by a custom migration for ChristianAid2 (lucky them!)

**Comment by alxndrsn** [comment]
> That would be done by a custom migration for ChristianAid2 (lucky them!)

Is custom migrations a new feature?  Could we just make a general migration which checks for `person`s whose `.parent` field points to a `health_center`, and moves them into a new 'CHW area'?  Is there only one CHW per `health_center`?

**Comment by estellecomment** [comment]
So that's not the issue : the `person` corresponding to the CHW has a `parent` of type `clinic`. The issue is that the `clinic` has the same name as its parent `health_center`, which is unhelpful.

You could check for `clinic.name` being the same as `clinic.parent.name`, and renaming `clinic.name` to "`clinic.contact.name`'s Area".

In CA2'a case it would work: it's the case for al CHWs so finding a name for all areas would be too much work.
If there's only a few CHWs that have this though, it could be done on purpose (i.e. a CHW lives close to the health_center, and their area is the area of the health_center.). So modifying it would mess things up.

Meh, yeah, automate it. It's cool.

**Comment by alxndrsn** [comment]
> Meh, yeah, automate it. It's cool.

Confused now - this definitely now sounds quite specific to one project, as I presume we wouldn't set up areas in this way in the future.  So maybe not a good case for a standard migration.  Or was the original plan to update all the clinics by hand?

**Comment by estellecomment** [comment]
I didn't automate it because I don't know how much it's going to happen, outside of Christian Aid 2. Thus the original point : custom one-off migration for CA2. 

If you want to automate it that also works.

**Comment by alxndrsn** [comment]
Done on branch; not clear if this should be in `master`.

**Comment by garethbowen** [comment]
@alxndrsn Where's the code? How will it run if not in master?

**Comment by garethbowen** [comment]
This is the branch: https://github.com/medic/medic-api/tree/2384_rename-chw-areas

**Comment by garethbowen** [comment]
Temporary views are really slow. I don't know how many records Christian Aid has but this would take LG offline for maybe an hour. But I can't think of any decent workaround. Maybe this should just be run as a one off node script on a case by case basis?

**Comment by garethbowen** [comment]
@alxndrsn What's the status on this?

**Comment by garethbowen** [comment]
Clearly nobody cares about this. Closing.
