### ISSUE TITLE
[.4 compat] Contact `person`s don't show up in their places

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2385]
CHPs are `person`s attached to a `clinic`. They should show up in the `clinic`'s CHP list.

Clinics are empty : (ignore the label, "Family Members" instead of "CHPs")
![screen shot 2016-06-10 at 15 36 00](https://cloud.githubusercontent.com/assets/911434/15966051/9a283ad4-2f21-11e6-84d7-56baf252d826.png)

**Comment by estellecomment** [comment]
Actually, that's true at every level of hierarchy, the contact person for the place doesn't show.

**Comment by sglangevin** [comment]
A contact normally shows up in the place that is their `parent`. So if you choose a primary contact for a place and that contact's `parent` is a different place, they will not show up in the place for which they are the primary contact, the will show up in the place that is their `parent`.

**Comment by estellecomment** [comment]
Actually, probably caused by https://github.com/medic/medic-webapp/issues/2387

**Comment by estellecomment** [comment]
@mandric can you review please?

**Comment by mandric** [comment]
Is there a branch for this or only this one commit for tests?

**Comment by garethbowen** [comment]
@mandric It looks like this is the other commit: https://github.com/medic/medic-api/commit/316eb8f2fc6229bf54cc588fb961095ecc356cc4

**Comment by estellecomment** [comment]
yes it is, sorry @mandric! I closed #2387 and forgot I had a commit in it.

**Comment by mandric** [comment]
Ok thanks, minor comment on medic/medic-api@316eb8f.

**Comment by estellecomment** [comment]
Ready for re-review @mandric!

**Comment by mandric** [comment]
@estellecomment skipped to Ready since it looks like you already acceptance tested this.

**Comment by estellecomment** [comment]
I didn't acceptance-test it on lg though, and it depends on the data in the db. So I'd rather leave it as Acceptance Testing.

**Comment by ngaruko** [comment]
Created new district and assigned a contact. Still does not show in the RHS.
![image](https://cloud.githubusercontent.com/assets/6979995/21761862/a0e77984-d6ba-11e6-9350-392abadeeed1.png)


expected: https://app.zeplin.io/project.html#pid=57d311edb055084578d006ec&sid=57e422c6536da7187eefa167

**Comment by ngaruko** [comment]
Tested on alpha.dev >>Version 2.10.0-alpha.4715

**Comment by SCdF** [comment]
@ngaruko is this related to creating users and contacts incorrectly like we discussed? Do you think if you created the user and contact correctly (ignoring the UI allowed you to create it incorrectly in the first place) it would work?

**Comment by estellecomment** [comment]
Ok, I know what this is.
1. Create Place A with new primary contact Person A.
2. Create Place B with existing primary contact Person A.
Expected : Person A is displayed as primary contact for Place B.
Result : no primary contact displayed for place B.
(reproduced : https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/4ec99abeef859c206acbd885b189d95a)

It's because the `parent` for Person A is still Place A, so it's not found within Place B.

It's kindof a weird case to have though. @sglangevin do you see this case used in practice? @diannakane will we need this use case in the future?

**Comment by diannakane** [comment]
If I'm understanding the question right, then yes, I think being able to
have the same primary contact for 2 places is useful to support.

**Comment by sglangevin** [comment]
I don't know of anywhere this is currently needed as most of the projects that were using v2.x last year don't really use the primary contact for anything, but that is very likely to change as we start deploying projects using SMS workflows on version 2.x.

**Comment by estellecomment** [comment]
Can you review @SCdF ? https://github.com/medic/medic-webapp/pull/3064

**Comment by SCdF** [comment]
Made some comments @estellecomment , back to you.

**Comment by estellecomment** [comment]
Commit : https://github.com/medic/medic-webapp/pull/3064/commits/359d8c9fc03628e2b7bc87be25b2d6322777a7ca
Rereview please!

**Comment by SCdF** [comment]
@estellecomment looks good to me. I made a comment but it's minor and style / preference. As you left yourself assigned to this I'll leave you to merge / whatever.

**Comment by estellecomment** [comment]
AT : 
 - [ ] normal case works
 - [ ]  this weird case works : https://github.com/medic/medic-webapp/issues/2385#issuecomment-271665652
