### ISSUE TITLE
Targets tab doesn't show correct progress

### ISSUE THREAD

**Issue by joshnesbit** [medic/medic-webapp#2388]
As a restricted user on demo.dev in a normal Chrome browser, I'm seeing different displays of numbers and progress bars on the targets tab. Specifically, U1 Sick Child Assessments and U5 Sick Child Assessments are showing differently on first load vs. after refreshing the targets tab.

Here's a screenshot of the target tab on first load – it looks the same after I click reload on the about page and go back to the targets tab:
![first load and after reload from about page](https://cloud.githubusercontent.com/assets/377216/16020139/596499d8-3161-11e6-89a4-c2a87633adb6.png)

Here's a screenshot after refreshing on the targets tab:

![after refreshing on targets tab](https://cloud.githubusercontent.com/assets/377216/16020152/6da111b0-3161-11e6-822d-070d419862a4.png)

I don't know an easy way to refresh this tab specifically on Android, so Android users may not have a way to force correct calculations. It's important for these numbers to be updated and correct each time a user goes to the targets tab.

**Comment by estellecomment** [comment]
Looks like https://github.com/medic/medic-webapp/issues/2065
demo.dev is on 2.6.3. like lg.app, but looks like its tasks config hasn't been updated, which is the second half of the fix that @abbyad did.

**Comment by abbyad** [comment]
I'll update the config and we can retest.

**Comment by abbyad** [comment]
I have updated the config and from my quick tests it seems to resolve this issue. Thanks @estellecomment for reminding us that this was already solved!

@joshnesbit, I will close but feel to reopen if you are still experiencing issues.
