### ISSUE TITLE
New Place form doesn't set person.parent

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2390]
If you create a place from the LHS "Add place" menu, the place created has a `contact` field set right, but conversely the contact `person` doesn't have a `parent` field linking to the place.

(I suspect this is not specific to .4 Compat, too)

**Comment by estellecomment** [comment]
Probably the same as https://github.com/medic/medic-webapp/issues/2327

**Comment by estellecomment** [comment]
And https://github.com/medic/medic-webapp/issues/1710

**Comment by garethbowen** [comment]
Closing as duplicate of #1710
