### ISSUE TITLE
Add New Place is broken

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2391]
![screen shot 2016-06-14 at 16 58 29](https://cloud.githubusercontent.com/assets/911434/16047826/f07194a2-3251-11e6-930c-04ed409f32d6.png)

**Comment by abbyad** [comment]
You haven't added the custom forms for people/place, right? Also, what is the error in the console?

**Comment by estellecomment** [comment]
It should generate one if I don't have one. 
I've actually found the fix I think, it's because admin doesn't have a facility_id so needs to be processed differently. Once fixed, you get the form ok. 

It's weird that it wasn't showing up in existing 2.x systems though, because it's before you get to the form, so custom or no it should be the same problem. Hmm. Will do more poking around.

**Comment by abbyad** [comment]
There are default forms built in if you dont use the custom one. I was just making sure it wasnt a problem with a custom form.

**Comment by estellecomment** [comment]
Oh I see, sorry. 
Yes, I'm using the default forms, so it's not a custom form problem.

**Comment by sglangevin** [comment]
In existing systems, the admin has a facility_id.

**Comment by estellecomment** [comment]
yeah that's what I was thinking, but I can't see a `facility_id` for admin in LG's db. There's a `contact_id`, but no `facility_id`. And the contact is a CHP `person`, its `facility_id` is a `health_center`, so that's kinda strange.

**Comment by estellecomment** [comment]
Aaaaactually, LG's admin gets a "Add New Family" button, not a "Add New Place" (of any type) button. So I guess it's adding Families in that contact's area? 
Contact_id is `eeb17d6d-5dde-c2c0-62c4a1a0ca17fd16`
![screen shot 2016-06-15 at 10 58 54](https://cloud.githubusercontent.com/assets/911434/16073939/7d076fa4-32e8-11e6-9690-df2d97f14af5.png)

@sglangevin I guess I don't really know how places we created on lg.app up to now. Was it with admin?

**Comment by estellecomment** [comment]
@garethbowen can you review?

**Comment by sglangevin** [comment]
@estellecomment yes, it was with admin. And I think I misspoke - admin has a `contact_id` and that's enough to create people and places. The reason you're seeing Add Family is because you didn't successfully load the Contacts tab. When it loads successfully, that will change to Add Place. The `person` that is the contact is within the hierarchy but the place that used to be the `facility_id` was deleted at some point. Sort of a weird setup!

**Comment by estellecomment** [comment]
Hehehe indeed!

Well, that change will remove the need for a `facility_id` or `contact_id` in admin (at least for this case, the Add Place form, can't talk for other things). Having the `admin` role is enough.

For acceptance testing we should make sure that the `org.couchdb.user:admin` docs, in `_users` and `medic`, match in the testing and prod instance. (at least the contact_id and facility_id)

**Comment by garethbowen** [comment]
I've added a couple of readability comments. Otherwise LGTM.
