### ISSUE TITLE
medic-webapp installation bug

### ISSUE THREAD

**Issue by waqar-ah** [medic/medic-webapp#2392]
**Getting this error while installing medic-webapp?**

```
183190 warn optional Skipping failed optional dependency /chokidar/fsevents:
183191 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.12
183192 verbose stack Error: sqlite3@3.1.3 install: `node-pre-gyp install --fallback-to-build`
183192 verbose stack Exit status 1
183192 verbose stack     at EventEmitter.<anonymous> (C:\Users\Waqar ahmad\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:245:16)
183192 verbose stack     at emitTwo (events.js:106:13)
183192 verbose stack     at EventEmitter.emit (events.js:191:7)
183192 verbose stack     at ChildProcess.<anonymous> (C:\Users\Waqar ahmad\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
183192 verbose stack     at emitTwo (events.js:106:13)
183192 verbose stack     at ChildProcess.emit (events.js:191:7)
183192 verbose stack     at maybeClose (internal/child_process.js:852:16)
183192 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
183193 verbose pkgid sqlite3@3.1.3
183194 verbose cwd C:\medic-webapp-develop
183195 error Windows_NT 10.0.10586
183196 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Waqar ahmad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
183197 error node v6.2.1
183198 error npm  v3.9.5
183199 error code ELIFECYCLE
183200 error sqlite3@3.1.3 install: `node-pre-gyp install --fallback-to-build`
183200 error Exit status 1
183201 error Failed at the sqlite3@3.1.3 install script 'node-pre-gyp install --fallback-to-build'.
183201 error Make sure you have the latest version of node.js and npm installed.
183201 error If you do, this is most likely a problem with the sqlite3 package,
183201 error not with npm itself.
183201 error Tell the author that this fails on your system:
183201 error     node-pre-gyp install --fallback-to-build
183201 error You can get information on how to open an issue for this project with:
183201 error     npm bugs sqlite3
183201 error Or if that isn't available, you can get their info via:
183201 error     npm owner ls sqlite3
183201 error There is likely additional logging output above.
183202 verbose exit [ 1, true ]
```

[npm-debug.txt](https://github.com/medic/medic-webapp/files/314451/npm-debug.txt)

**Comment by estellecomment** [comment]
Hello Waqar-ah,

First two lines are a warning, looks like the chokidar/fsevents dependency was skipped (as it should since it's optional and I don't think you'll need it on windows : https://github.com/npm/npm/issues/9204#issuecomment-174223597)

And then sqlite3 wouldn't install. I see you're already at the latest versions of both npm and node. Not sure what's going on. For the record, I have node v5.0.0, npm 3.8.9.

I'm not sure the webapp is easy to build and run without support from our team, which we don't really have the bandwidth to provide. I think you'll have a hard time doing it on your own. 
Are you doing this to contribute to the code, or because you're interested in using the software?

**Comment by waqar-ah** [comment]
Thanks for comment , 
Right now i am getting started with it , First i will use this system to understand its working and code, then i love to contribute after understanding the system..

First of all i have to install it , which is not happening.

as you said i am running latest versions of both npm and node.. now i will try with  the versions you mentioned  and if there are some important instructions for installing it feel free to share.

**Comment by waqar-ah** [comment]
why i cant label my issue?

**Comment by SCdF** [comment]
Hey @waqar-ah just a note, I'm not aware of anyone building medic-webapp on Windows (it's all linux or OSX). Since you're having problems at the `npm install` stage I'm wondering if that has something to do with it? I don't have access to a a Windows environment, so you may have to do some digging here. I suggest you try to get sqlite3 (the package that is failing) to just install globally with npm to isolate that particular package: `npm install -g sqlite3`, or create a small package.json with just that in it and `npm install` that if you'd rather not install it globally.

**Comment by waqar-ah** [comment]
Thanks, 
           will try this , if not succeeded  , will move to Linux then... can i do this on Kali Linux or do i have to use Ubuntu?

**Comment by waqar-ah** [comment]
@estellecomment We are Team of Developers in Pakistan , Developing this system for Local market and we will contribute in future for enhancments. Right now we need a guidance to Start working on it

**Comment by estellecomment** [comment]
@waqar-ah that's interesting. What's your organization called? What use cases are you interested in? Maybe you could try our DIY release, which doesn't need any of this building step, it's ready to use : http://medicmobile.org/diy

**Comment by waqar-ah** [comment]
@estellecomment We are Seronic Group, ICT company with expertise in Process Re-engineering and Change Management. We are doing a CSR in Sindh Region of Pakistan and we found Medic Mobile could be perfect fit for us to implement in our process.

We are interested for TB Surveillance use case in remote areas of Pakistan.

**Comment by shreyakb** [comment]
Hi @waqar-ah. I am the India Country Lead with Medic Mobile, and I also support our ongoing work in Asia. I'd be happy to connect with you to learn more about the TB surveillance use case you are envisioning in Pakistan, and explore how our tools may support your work. Is there an email address I can reach you at to continue this discussion? I'm at shreya@medicmobile.org. Looking forward to connecting soon.

**Comment by revolutionflame** [comment]
Hi Shreya, we connected together in past for Medic Mobile implementation. But the project here was delayed. We are now main execution partners with Seronic Group to implement this solution. You can write me email at ceo@revolutionflame.com Let me share the TB surveillance use case at your email and need your kind guidance in how we can best optimise Medic Mobile for use.

**Comment by garethbowen** [comment]
We don't support development on Windows at this point. My understanding is that node on Windows is challenging. I'd really appreciate any pull requests to get us towards supporting Windows, but otherwise I recommend using any linux distro (I'm using Ubuntu here) or OSX.
