### ISSUE TITLE
national-admins should be able to edit contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2395]
<img src="https://cloud.githubusercontent.com/assets/191496/15854736/c6efb3d0-2cab-11e6-843e-4c9d9f8fe737.png"/>

It's possible that user doesn't have a contact associated, but that doesn't explain the validation errors.

Getting national-admins to work is important to allow people admin access without giving them DB admin rights.

**Comment by alxndrsn** [comment]
Now it doesn't seem possible to even edit a contact of any type:

<img width="1280" alt="screen shot 2016-06-15 at 16 40 42" src="https://cloud.githubusercontent.com/assets/191496/16084146/f26cc06c-3317-11e6-8fdf-e22b8cf8e9b1.png">

**Comment by garethbowen** [comment]
Related to (and possibly duplicated by) #2386

**Comment by alxndrsn** [comment]
Works for me.

**Comment by garethbowen** [comment]
Me too...
