### ISSUE TITLE
New documents aren't replicated

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2396]
The new replication endpoint gets a list of relevant IDs for the user and watches the changes feed for any changes to those. If a new document is created then its ID won't be in the list so the change won't be picked up.

**Comment by garethbowen** [comment]
Assigning for review: https://github.com/medic/medic-api/pull/81

**Comment by SCdF** [comment]
OK, I have read this. I think it's not too bad, though yeah, it's getting into minor magicks.

Essentially if I were to describe it would say that we run a continuous application-wide changes feed that includes documents which we _filter_ over, effectively looking for a relationship between currently ongoing continuous replications and documents that are relevant to those replications but aren't currently known about. If we find one we restart their continuous changes feed for a user, which will mean their new feed will contain the new document that we found.

One wonders ironically how well medic-api will deal with this extra load both on CPU and memory (`include_docs=true`) but then again I have no idea how well node deals with anything really, and it will be a blessing to see something other than beam.smp doing something on the server for once.

**Comment by SCdF** [comment]
(back to you with minor naming convention questions, otherwise good to merge)

**Comment by garethbowen** [comment]
AT: Get a client running, as another user create a new doc that the client should be able to see, make sure it syncs down to the client.
