### ISSUE TITLE
0.4 -> 2.x : upgrade checklist

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2400]
Make a list of things to check when upgrading, to make sure it happened properly.
Probably google doc or sheet while drafting, and github when finalized.

**Comment by estellecomment** [comment]
https://docs.google.com/document/d/1F0tldo2XDqCRwcITe054aLB6k1uZYaLNbGN37d1RwrM/edit

**Comment by alxndrsn** [comment]
Related: https://github.com/medic/medic-webapp/issues/2586

**Comment by estellecomment** [comment]
Actually, now the doc with the most stuff is this one : 
https://docs.google.com/document/d/1kYUEX08slCivSmP5D1Cbl602ho2g89V1_WbGJZSiSeY/edit#

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by garethbowen** [comment]
Checklist:

1. Take a snapshot of production so you can thoroughly test without breaking production
2. Run the update
3. Watch the api log for any migration issues. Take note of any issues found and let development know and wait for a patch or custom script.
4. Repeat 1-3 until there are no migration issues.
5. Test the snapshot thoroughly
6. Schedule an update on production.

**Comment by estellecomment** [comment]
@abbyad is this the most complete and latest checklist we have, or is there another one? (cc @ngaruko )

**Comment by abbyad** [comment]
I haven't seen a newer checklist, but we may want to add steps for user testing to verify that the app + config continues to work as expected. This was covered for select configs, as part of our v2.9 testing. Notes on that process are [here](https://docs.google.com/document/d/1HjUjj6Hth3NZgK_7QPfZJMoxTBYNrhIpV6GtGt76fIg/edit#heading=h.677i0zz2c3tk).
