### ISSUE TITLE
Cannot load forms on 2.7.0-alpha.3431

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2403]
When trying to open forms (both contact forms and regular forms) I get this error. I have seen this logged in as admin and as a restricted user. The Add Family form seems to work, but the add/edit forms for `health_center` and `district_hospital` do not. None of the regular forms are loading - same error.

![image](https://cloud.githubusercontent.com/assets/1286381/16159876/0bef0a3c-347a-11e6-852a-90da1ba79356.png)

![image](https://cloud.githubusercontent.com/assets/1286381/16159838/d2a4f192-3479-11e6-8f39-05c6ee193459.png)

**Comment by garethbowen** [comment]
Assigning to @estellecomment for review. Caused by one missed refactor while doing #1461

**Comment by estellecomment** [comment]
LGTM

**Comment by sglangevin** [comment]
This is working again.
