### ISSUE TITLE
Replication since gets reset when new documents added

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2404]
Every time the local db gets a new doc we update the doc_ids parameter we submit for replication. Unfortunately changing parameters means the checkpoint hash changes so the checkpoint isn't found and the `since` parameter is set to 0.

Find some way to keep the since value.

**Comment by garethbowen** [comment]
With the new replication replicating from 0 with no actual changes if quite quick and easy on the CPU so this isn't a blocker.

**Comment by garethbowen** [comment]
#### Acceptance testing

We make a number of requests to a URL with `_changes` in it. There are two flavours - ones with the `doc_ids` parameter set to `["_design/medic"]` and ones with it set to a long list of IDs. The ones we care about here are the latter.

1. load a page
2. wait for replication to complete
3. on the network tab record the `since` parameter of the latest `_changes` request
4. create a new document
5. reload the page
6. make sure the first relevant `_changes` feed doesn't have `since=0`

**Comment by SCdF** [comment]
So I get the merge and it appears to work from my limited testing.

Obviously patching Pouch to (arguably) remove functionality isn't ideal. As far as I can tell though this shouldn't negatively affect us, because we only have one replication per database anyway.

**Comment by garethbowen** [comment]
AT: Watch the network tab as new docs are replicating down and ensure the _changes request `since` parameter keeps increasing and doesn't reset back to 0.
