### ISSUE TITLE
Logout option no longer works on the MM Android app

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2407]
Using 2.7.0-beta.3454 on lg-testing.app, I can no longer "logout" from the Android app. This feature was added for easier testing, otherwise we have to clear all app data to log out.

**Comment by garethbowen** [comment]
I'm getting this error in the console.

> Uncaught TypeError: Cannot call method 'logout' of undefined 

@alxndrsn It looks fine on the webapp side - could you have a look at the android app please?

**Comment by alxndrsn** [comment]
Logout's calling `angular.element(document.body).scope().logout()`; presumably something changed.

**Comment by alxndrsn** [comment]
`angular.element(document.body).scope()` now returns `undefined`, but looking at the DOM, I'd expect `InboxCtrl` to be attached to it.

**Comment by alxndrsn** [comment]
In fact, `.scope()` doesn't seem to return a scope from _any_ DOM elements that I can find.

`.scope()` is also used in a couple of places in the `medic-webapp` code, so I'd expect them to be broken too:
* https://github.com/medic/medic-webapp/blob/develop/static/js/modules/tour.js#L39
* https://github.com/medic/medic-webapp/blob/develop/static/js/enketo/widgets/phone-widget.js#L52

**Comment by alxndrsn** [comment]
Looks like this is a direct result of setting `$compileProvider.debugInfoEnabled(false)` in https://github.com/medic/medic-webapp/commit/d4e08373f78e236fd77acab36a89820fe523610b:

> Call this method to enable/disable…reference to the current scope on to DOM elements.
> – _https://docs.angularjs.org/api/ng/provider/$compileProvider#debugInfoEnabled_

**Comment by alxndrsn** [comment]
Options:

1. manually attach the scopes we require to elements via `data()`
2. manually delete the cookie and refresh the page
3. provide a logout endpoint
4. `angular.element(document.body).injector().get('Session').logout()`

I think **4** is probably the correct solution, although should be used with care – it will not be possible to tell from the webapp code that this function is being used externally.  It will also work to fix the other expected bugs mentioned above, although these may require creation of dedicated Services to provide the required functionality.

**Comment by alxndrsn** [comment]
Fixed with method **4**.

**Comment by alxndrsn** [comment]
@sglangevin v0.1.151 should be available from the app store with the fix

**Comment by garethbowen** [comment]
Nice catch. I copied the JavaScript into the console and it worked, but of course we're setting debugInfoEnabled to true on `localhost`...

**Comment by sglangevin** [comment]
@alxndrsn I haven't gotten the update from the app store yet. Will check again tomorrow.

**Comment by sglangevin** [comment]
No update has come through the play store - reopening.

**Comment by alxndrsn** [comment]
Version `0.1.151` for the unbranded app was uploaded to the google play store (version code `151`) on ﻿﻿Jun 21, 2016 8:16 AM (GMT) for the "alpha release track".  @sglangevin are you also talking about the unbranded app, and are you using the alpha release track?  What version are you currently seeing in the play store?

**Comment by sglangevin** [comment]
I am also talking about the unbranded app, but I don't know if I am using the alpha release track. I see version 0.1.148 in the play store. @alxndrsn maybe we need to upload to a different track? Or tell me how I can access the alpha release track?

**Comment by alxndrsn** [comment]
@sglangevin can upload to any track you choose – I don't see it makes much difference for the unbranded app, as it's (currently) for internal use only.  Do you know what track you're on?

**Comment by sglangevin** [comment]
@abbyad do you know which track I'm on? I think it must be beta, not alpha, but I'm not sure what the options are. I used the link to become a tester that we've shared with other partners.

**Comment by abbyad** [comment]
@sglangevin, Beta is on 148, Alpha is on 151, so it seems as though you are on Beta. I just promoted 151 to Beta so you should see it soon.

**Comment by sglangevin** [comment]
thanks @abbyad - got the update and confirmed that logout is now working again.
