### ISSUE TITLE
Pass user's info to rule to customize Tasks per user type or location

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2408]
The goal is to enable a tech lead to configure different tasks for different people, based on where they are in the hierarchy, what branch they report to, etc.

**Comment by abbyad** [comment]
This will also be helpful to customize Task rules accordingly.

**Comment by SCdF** [comment]
FWIW we would still want to disable tasks for admins for performance reasons

**Comment by abbyad** [comment]
@SCdF would we want to control that via the rules? What would happen if we need to create (a small number of) tasks or targets for the admin?

**Comment by abbyad** [comment]
Change the title to reflect the actual outcome of this change, which is to control which Tasks are shown based on user's info.

Having different Targets for different users will be possible with #2409.

**Comment by SCdF** [comment]
@abbyad I'm not an expert but I'd suggest that no, rules are just things you don't enable for admins. This is because even if you're only going to generate a couple of tasks the---currently client-side JS---rules engine has to load and parse every single report to find that out.

**Comment by sglangevin** [comment]
@SCdF we're thinking more about CHW supervisors here, who might have their own tasks and not want to see any of the tasks of the people that report to them. CHW supervisors are similarly restricted to a specific place (a branch or health facility) and are not necessarily admins. They may have their own tasks, and would need the rules engine to generate those, but wouldn't want their Tasks tab to be cluttered with other people's tasks (i.e. tasks that need to be completed by people they manage).

**Comment by SCdF** [comment]
@sglangevin / @abbyad right yeah sorry I'm talking about capital A Admins: as in, people for whom we disable PouchDB replication and so on.

**Comment by garethbowen** [comment]
@sglangevin Two questions...

1. In the issue description you say "The goal is to enable a tech lead to configure different targets...". I think this is meant to say "tasks" instead of "targets", right?
2. In your opinion, which information would be useful? eg: the user's contact (where they are in the hierarchy), the user's role (chp, manager, etc), the user's facility (what they're allowed to see).

**Comment by sglangevin** [comment]
@garethbowen: yes, that was a typo. We originally had tasks and targets in one issue, then split the targets part into #2409 and I didn't come back to update the original comment. 

I think the contact and role would be useful - is that what we have available for form context currently? If we have the same information that is available for forms, that should suffice for now, though I haven't sat down and thought through all of the potential use cases.

**Comment by garethbowen** [comment]
Roles are complicated. We decided in a conversation on Slack to just include the user contact for now. This is consistent with forms and tasks context.

**Comment by sglangevin** [comment]
@garethbowen this seems to be working on alpha.dev. I'll do some additional testing when I get back from vacation - I want to make sure that I'm testing it the right way. But initial tests look good!

**Comment by sglangevin** [comment]
This is working well on v2.8.0-beta.8
