### ISSUE TITLE
Add context to target types and goals

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2409]
Enable different targets for different types of users. First, make it so that two different CHPs can see the same metrics but with different goals for those metrics, based on which branch they report to. For example, LG Kenya has two types of branches: endemic and non-endemic to Malaria. These two branch types have different goals for their targets, such as  number of assessments for children under 1 and under 5 - the branches serving areas endemic to Malaria have higher goals for these two targets compared to the branches serving areas non-endemic to Malaria.

One CHP would see a goal of, say, 6 under-5 assessments, because they report to a non-endemic branch while another CHP would see a goal of, say, 9 under-5 assessments, because they report to an endemic branch.

In addition, we'd like to be able to have different target metrics for different users, e.g. a branch manager sees different targets and goals than a CHP. A manager might see a target like "# CHP visits completed this month" while a CHP would see "# of pregnancies registered".

**Comment by garethbowen** [comment]
Related to #2408

**Comment by sglangevin** [comment]
A note that LG Kenya needs this to deploy. Backup plan is to deploy on two instances, which is probably not ideal. Deployment is planned for September.

**Comment by sglangevin** [comment]
Here is an example of how this might be configured:
```
{
      "type": "count",
      "id": "assessments-u1",
      "icon": "infant",
      "goal": {{ "number": 4, "expression": "user.parent.name === 'New Branch'"}, { "number": 8, "expression": "user.parent.name === 'Old Branch'"}},
      "name": [
        {
          "locale": "en",
          "content": "U1 Sick Child Assessments"
        },
      "expression": "contact.type === 'health_center'"
      ]
    },
```

**Comment by alxndrsn** [comment]
@sglangevin in your example, what's the meaning of `"expression": "contact.type === 'health_center'"` and is it already supported?

**Comment by sglangevin** [comment]
@alxndrsn that is similar to the context that we are setting for forms. That is not supported for targets currently but we'd like it to be supported so that we can have different target metrics and different goals for different types of users. Take a look at any of the .json files in the forms folder for LG, BRAC or Muso in medic-projects for some examples. Basically you have access to the contact and the user and can use that info to limit who sees a particular form. Does that make sense?

**Comment by alxndrsn** [comment]
It does make sense, but it seems like you could achieve everything requested in this ticket with the `target.expression` field, without also needing multiple `target.goal*.expression` fields

**Comment by sglangevin** [comment]
I don't think we need to have both, necessarily, as long as we can achieve these two things:
1. Sharon and Alex have different metrics listed on their targets tabs. e.g. Sharon has a metric for total # of households registered and Alex has a metric for # of pregnancies registered.
2. Sharon and Alex have different goals for the same metric. e.g. both have a metric for under-5 assessments, but Sharon's goal is 10 and Alex's goal is 12.

If we can do both of those things, I'm not tied to any one solution, just shared the snippet as a way to illustrate.

**Comment by alxndrsn** [comment]
I think the basic functionality should be covered by https://github.com/medic/medic-webapp/commit/326998dfc9d975aa291860bfb7d307c96b722402, but would like to go over this with someone who understands the requirements and where it would be configured.

**Comment by sglangevin** [comment]
@alxndrsn I know the requirements and would be happy to go over this. I can give more info on where this would be configured.

**Comment by alxndrsn** [comment]
# TODO
* change the `user` object to be called `contact`?  this may be closer to other implementations
* clone the objects before passing to scope to prevent modification
* add a `user` object containing the user's settings? (sounds unnecessary...)

**Comment by sglangevin** [comment]
@alxndrsn agreed that the third bullet is not necessary for now. First bullet would be great, and actually I would add that if we called it `expression` instead of `context` that would also be more in line with how we do form context config.

Also, this is working correctly on alpha.dev, very exciting!

**Comment by garethbowen** [comment]
@alxndrsn The other implementations use `user` as the context property name for the UserContact object. It's probably not the best name, but what do you think about changing this to use `user` instead of `userContact`. It's bound to trip us up if they're inconsistent...

**Comment by garethbowen** [comment]
@alxndrsn I've code reviewed your commits and my only comment is about the naming of the `UserContact` content property.

I've also added a unit test, did some refactoring, and fixed a small bug.

We need this issue for the 2.8.0 release - would you mind reviewing my commit?

**Comment by alxndrsn** [comment]
Thanks for doing this - was already half way through unit tests, but saves me the bother.  

> The other implementations use `user` as the context property name for the `UserContact` object. It's probably not the best name, but what do you think about changing this to use `user` instead of `userContact`. It's bound to trip us up if they're inconsistent...

Seems fine to me.  That's what it was called originally, but I was worried that it might be confusing, or clash if we decided to also include the user's doc from the `_users` db.

**Comment by garethbowen** [comment]
@alxndrsn This is now ready for review. Thanks!

**Comment by alxndrsn** [comment]
Some simple questions inline.

**Comment by sglangevin** [comment]
Looks good on v2.8.0
