### ISSUE TITLE
Restructure git branches

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2410]
### Master

Have a `master` branch as the default github branch. Commits are made directly into this branch or via PRs to this branch. Travis builds and publishes an alpha release every time a commit is made.

### Release branches

Have release branches which branch of `master` and are named `<major>.<minor>.x`, for example "2.6.x". This will gradually diverge from `master` so don't plan to merge this back in, but ensure all changes in the release branch are also in master (either by cherry-picking or merging in either direction). Travis builds and publishes a beta release every time a commit is made to a branch with this form.

### Final releases

Tag a release branch when it's ready for production named `<major>.<minor>.<servicepack>`, for example: "2.6.3". Travis builds and publishes a final release every time a tag is made in this form.

**Comment by garethbowen** [comment]
Some conversation regarding this is [in Google drive](https://docs.google.com/document/d/1miVxHOrqZIgVAbg286jrbGWxkoqBJNP_zvvALuOImvM/edit#).

**Comment by garethbowen** [comment]
Consider using tags to kick off a beta release too.

**Comment by garethbowen** [comment]
Also look at cleaning up sentinel and api to be consistent. Make sure commits to deleted branches are merged first, eg: #2449

**Comment by mandric** [comment]
Sentinel update: https://github.com/medic/medic-sentinel/pull/80

**Comment by mandric** [comment]
Sentinel updated, everything should merge into `master` now, deleted `develop`. 

To update your local clone:

```
git fetch origin
git reset --hard origin
git checkout master
git branch -d develop
```

**Comment by garethbowen** [comment]
Idea from @mandric on #2514 
> Maybe also double check diy branch is there and delete that as well? https://github.com/medic/medic-api/compare/diy

**Comment by garethbowen** [comment]
I've manually checked the code in develop and it does contain all of the changes made to the diy branch.

**Comment by garethbowen** [comment]
API updated, everything should merge into master now, deleted develop.

To update your local clone:

```
git fetch origin
git reset --hard origin
git checkout master
git branch -d develop
```

**Comment by garethbowen** [comment]
Webapp updated.

**Comment by garethbowen** [comment]
The last thing to do is update the CI scripts in the release branches so they behave consistently. I'll wait for a code review before doing that...

**Comment by garethbowen** [comment]
Assigned to @mandric for code review.

**Comment by mandric** [comment]
@garethbowen two things I'd like to bring up, hopefully they are relevant:

1) I think it's better to continue doing alpha -> beta -> rc -> release. It looks like you're skipping the RC phase.  We have the infrastructure (rc.dev and RC Market) I think it helps keep a more stable release process.  It's also confusing to tag a commit `2.8.0-rc` and it goes to the beta market.

2) We have a 0.4.12-rc that should probably get released, people can optionally update to it, it has support for the new gateway and also has an analytics patch. I propose we release it and whenever a new RC is pushed (likely a v2), those subscribed to the RC Market are basically our first candidates (bleeding edge users) that can test the upgrade process.  I think there is only one production instance currently subscribed to RC Market, but we can confirm this.  We could probably even use RC for both v0 and v2 if it really comes down to it since people can only upgrade to higher version numbers in dashboard.  Once we have an RC of v2 ready which includes the upgrade path I don't see much risk of releasing it to the RC Market.

**Comment by garethbowen** [comment]
We've been using betas as release candidates and skipping the rc stage for all 2.x releases so far, so it's more like I'm skipping the beta stage and going straight to rc. What's the benefit of having a beta?

I can definitely switch rc -> beta in the tagging system if that'd make more sense to you, but I don't think having 4 stages gives us any more stability than 3.

The publishing script I updated didn't have any mention of an RC market: https://github.com/medic/medic-webapp/commit/04b48e313c9de2e545c1230403e6d56b7edf1da1 . How did we publish to this previously?

**Comment by mandric** [comment]
I don't really count Alpha as a release stage it's mainly just a point to merge and review code, so it's still 3 stages.  Acceptance testing is done on Beta and RC.  If we don't think we need this then we can skip Beta or RC but either way tagging something `-rc` or `-beta` should go to the right market.

**Comment by mandric** [comment]
To answer your last question I was doing that with the `rc` branch https://github.com/medic/medic-webapp/blob/v0.4/scripts/ci/after_success.sh#L37

**Comment by mandric** [comment]
Also maybe we should prune more branches in that repo?

**Comment by mandric** [comment]
It would be nice before we close this ticket that we document each branch in the repo and what purpose it serves?

**Comment by mandric** [comment]
Sweet!

**Comment by mandric** [comment]
@garethbowen pretty sure this also means 0.4.x has replaced v0.4, I will confirm/merge and delete.

**Comment by mandric** [comment]
I merged `v0.4` and `rc` branches to `0.4.x` then deleted them.

**Comment by mandric** [comment]
@garethbowen Cleaning up branches I think I found a couple patches hiding in the DIY branch: https://github.com/medic/medic-webapp/compare/diy  

Should we port these over to?

**Comment by garethbowen** [comment]
So many branches... :(

Yes I think we should port those over to "0.4.x" and "master" and then delete the diy branch. I don't think we need a diy market do we? I'd much rather diy used the same version and market as everyone else (0.4.x now, and 2.8.x soon) so we don't have too many variants of the same product.

**Comment by mandric** [comment]
Right, my understanding is once we get v0.4 compatibility we're on the road to the next DIY release!

**Comment by mandric** [comment]
Apologies for not opening a new issue, PR attached.

**Comment by mandric** [comment]
@alxndrsn , please have a look here and let me know the status of these branches:

https://github.com/medic/medic-webapp/compare/master...styled-enketo-summary

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...styled-enketo-summary-or-appearance
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...splash-screen

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...no-admin-login

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...initial-sync-status-without-batch-size-change

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...firefox-upgrade

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...enketo-spike

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...better-uploads,perhaps

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2409-add-context-to-targets

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2262

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2167_monkeypatch

- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1947
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1905
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1700_remove-help-from-app-settings
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1513-back-button
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1456-automated-geolocation-field
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1415-events-demo
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1260
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1086_embed-enketo-core-with-browserify
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

**Comment by garethbowen** [comment]
Deleting dead branches is outside the scope of the original issue and it's holding this issue open too long so I've created #2634 to track it.

**Comment by mandric** [comment]
Thanks
