### ISSUE TITLE
Using "select all" when attempting to bulk delete, the number of records on the RHS doesn't match the LHS

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2411]
On lg-testing.app (2.7.0-beta.3454), I filtered the History tab to Iganga branch, with dates 1 Apr - 17 Apr. I then clicked "select all" and the UI says there are 61 records selected. Counting the records on the LHS, I got a total of 50. Perhaps this is related to the date filter issues in History? #2185 

Now I'm not sure what I'll be deleting - the 61 records on the RHS? Or the 50 records on the LHS?

**Comment by garethbowen** [comment]
The LHS is paginated to 50 items. If you scroll down on the LHS it should load the next 11 items. Maybe this is a UI issue rather than a Bug?

**Comment by sglangevin** [comment]
It doesn't load the next 11 items - it says No more Reports. What is the difference between a UI issue and a bug?

**Comment by garethbowen** [comment]
> It doesn't load the next 11 items - it says No more Reports.
Definitely a bug then!

IMO a "bug" issue is when the app doesn't do the right thing, a "UI/UX" issue is when the user is left unsure of what the right thing is, eg: "Now I'm not sure what I'll be deleting".

**Comment by sglangevin** [comment]
Ah, ok, makes sense. I guess I confused the issue a bit in my description, but the main problem is a bug which is that I don't load the 11 items that should load.

**Comment by garethbowen** [comment]
Ok I can reproduce this issue, but only with the last page. It also happens in single select mode, not just multi select.

**Comment by garethbowen** [comment]
Curiouser and curiouser... also only when a filter is chosen.

**Comment by garethbowen** [comment]
TIL:
```javascript
[1,2,3].slice(0,1);
// [ 1 ]
[1,2,3].slice(-1,1);
// [ ]
```

**Comment by sglangevin** [comment]
@garethbowen I know this hasn't been code reviewed yet, but I'm reviewing the others anyway so I thought I'd chime in. This is closer, but still off by a few reports, which is odd.

**Comment by garethbowen** [comment]
@sglangevin So that I can replicate the issue, can you tell me which server, which user, and which filters you've selected? Or does it just happen all the time?

**Comment by sglangevin** [comment]
I've been testing on lg-testing. I selected 3-4 CHPs in the HQ area, no other filters. I think I then deleted some of the reports from 1-2 of those CHPs, so it would be hard to reproduce exactly. I made sure that there were > 50 reports selected, then counted what I saw on the LHS (59) to what was displayed on the RHS (61).

**Comment by garethbowen** [comment]
> I think I then deleted some of the reports from 1-2 of those CHPs, so it would be hard to reproduce exactly.

@sglangevin Did you do that through the UI in the same session, or through the UI in another session (logged in as someone different), or directly in the DB (eg: futon)?

**Comment by sglangevin** [comment]
All was done through the UI, same session

**Comment by garethbowen** [comment]
I'm unable to reproduce this latest variant...

**Comment by alxndrsn** [comment]
Looks fine; couple of comments inline.

**Comment by sglangevin** [comment]
I can no longer reproduce it either, looks fine to me.
