### ISSUE TITLE
Consider moving "Select All" to the left side of the LHS's FAB

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2413]
Currently, we have, from left to right: Clear selection, Select all, Close. I'm proposing that we consider swapping Clear selection and Select all as I find myself almost accidentally clicking Clear selection every time I want to Select all.

@diannakane @Lesterng just an idea, feel free to close this issue if you disagree.

**Comment by diannakane** [comment]
I agree; the designs were a single checkbox which toggles select all /
clear all. Split up like this, "select all" should be aligned with the list
of checkboxes.

On Mon, Jun 20, 2016 at 4:42 PM, Sharon Langevin <notifications@github.com>
wrote:

> Currently, we have, from left to right: Clear selection, Select all,
> Close. I'm proposing that we consider swapping Clear selection and Select
> all as I find myself almost accidentally clicking Clear selection every
> time I want to Select all.
>
> @diannakane <https://github.com/diannakane> @Lesterng
> <https://github.com/Lesterng> just an idea, feel free to close this issue
> if you disagree.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2413>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXtriWHeCiaho4UXQZqSna0wEg34gks5qNyV9gaJpZM4I6PB9>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by sglangevin** [comment]
LGTM.
