### ISSUE TITLE
After clicking "delete" on the RHS of bulk delete, reports do not disappear from the LHS

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2414]
After deleting, I end up with "no report selected" on the RHS and a list of the reports that I just deleted on the LHS, though none of them are checked. If I try to check one, the check box doesn't check and I still see "no report selected" on the RHS.

Seems like the user should be directed somewhere where they don't see the reports they just deleted. I see a couple of options:

1. They end up with the same filters selected but with "No reports found" on the LHS and "No reports selected" on the RHS.
2. Then end up back at the History tab, unfiltered, with a toast that says: "deletion successful" or some other helpful message.

There are probably lots of other options too! cc @diannakane @Lesterng

**Comment by diannakane** [comment]
Thanks for calling this out. A temporary pop-up confirming "xx reports
successfully deleted" seems reasonable. After deleting a selection (whether
some or all), you should remain in select mode with the filters in place.
If there are no records left after deleting, the LHS should say "no records
found." The RHS should be empty in either event.

Agree that deleted records should disappear from the LHS. This sounds like
a bug.

On Mon, Jun 20, 2016 at 4:59 PM, Sharon Langevin <notifications@github.com>
wrote:

> After deleting, I end up with "no report selected" on the RHS and a list
> of the reports that I just deleted on the LHS, though none of them are
> checked. If I try to check one, the check box doesn't check and I still see
> "no report selected" on the RHS.
>
> Seems like the user should be directed somewhere where they don't see the
> reports they just deleted. I see a couple of options:
> 1. They end up with the same filters selected but with "No reports found"
> on the LHS and "No reports selected" on the RHS.
> 2. Then end up back at the History tab, unfiltered, with a toast that
> says: "deletion successful" or some other helpful message.
>
> There are probably lots of other options too! cc @diannakane
> <https://github.com/diannakane> @Lesterng <https://github.com/Lesterng>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/medic/medic-webapp/issues/2414>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABmSXjoEKjFhNv-lX5M4XaXa4KSipAdXks5qNylWgaJpZM4I6Phl>
> .
>



-- 
P.S. Join our community. Sign up for Medic Mobile's newsletter
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>
.


Dianna Kane | Senior Designer
Medic Mobile <http://www.medicmobile.org/> +1 216 262 2204
@*M*edic <http://www.twitter.com/medic> Facebook
<https://www.facebook.com/MedicMobile> @diannakane

**Comment by garethbowen** [comment]
We currently have a Snackbar that pops up and says "x items deleted".

The items not disappearing from the LHS is a bug. This only happens when one or more filters are selected.

**Comment by garethbowen** [comment]
We have two left hand sides - one which is shown when there are no filters, and one which is shown when at least one filter is selected. Unfortunately we were only updating one list when the data changed (eg: deletion). This change updates both lists.

**Comment by sglangevin** [comment]
Looks good to me!
