### ISSUE TITLE
DeleteDocs fails if the parent's contact is null

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2416]
Say you have a Contact (P) which has two children Contacts (C1 and C2) and that C1 is the primary contact for P. If you delete C1 then DeleteDocs clears the contact on P. Then if you delete C2 it tries to check the parent's contact but the null contact isn't handled and the service errors.

```
Error: parent.contact is null
require<[272]</</</getParent/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:167480:1
processQueue@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:34050:28
scheduleProcessQueue/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:34066:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:35318:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:35134:15
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:35357:15
completeOutstandingRequest@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:23958:7
Browser/self.defer/timeoutId<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:24234:7
```

**Comment by garethbowen** [comment]
I also changed the parent check to use `_id` instead of `phone`. I'm not sure why we were using phone instead, but now it's quite possible the contact won't have a phone so it doesn't make sense any more.

**Comment by estellecomment** [comment]
> I'm not sure why we were using phone instead

I'm guessing it's from 0.x era, where contacts weren't proper docs, and were just name + phone in the parent doc, so they didn't have an id.

**Comment by estellecomment** [comment]
LGTM

**Comment by garethbowen** [comment]
AT: as described in the summary.
