### ISSUE TITLE
DeleteDocs modifies the given array

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2417]
If you call DeleteDocs with an array of Contacts the service may add other docs to the array, for example, when deleting a contact it helpfully updates the contact's parent to keep the database consistent.

Unfortunately if you then count the length of the array you passed in to DeleteDocs it'll be larger than you expect. In particular if you display how many docs have just been deleted it may alarm users, eg:

```javascript
var docs = [ { _id: 1 } ];
DeleteDocs(docs).then(function() {
  Snackbar(docs.length + ' docs deleted permanently');
});
// could output "2 docs deleted permanently"
```

**Comment by estellecomment** [comment]
LGTM

**Comment by garethbowen** [comment]
AT: Bulk delete docs and make sure the snackbar message shows the right number of docs deleted.
