### ISSUE TITLE
Move read-status of reports and messages into a separate document

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2418]
If you mark a document as read that shouldn't require that the entire document get changed to a new version, with all the replication etc that entails.

Options:
- Have a separate tiny document for each view status
- Have a `_local` document that is a map of what documents you've read
- Same as above, but make it not local so it replicates up

There are pros and cons to each approach, not sure what's best.

**Comment by estellecomment** [comment]
Is there a case where userB need to know whether userA saw a doc? 
Can't think of one, so 2nd option? What are the cons?

**Comment by garethbowen** [comment]
This has been discussed at length in a [Google Doc](https://docs.google.com/document/d/1_bwML_WA_tuaxxxElNUcs-MTxd6f_u15J-Ak03kkIc4/edit#).

The TL;DR is to have a per user meta database which stores a doc for each doc the user has read. This is replicated to the server so if they switch device the information is retained.

**Comment by garethbowen** [comment]
Code review the above two PRs please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
Care for another review @SCdF ? I've made (I think) all the changes requested. The biggest one was using a view with a reduce for the read docs which meant having to add a ddoc to the users meta db so that's definitely worth a look...

**Comment by SCdF** [comment]
Back to you @garethbowen. Just some minor stuff, but I think it's basically ready for AT!

**Comment by garethbowen** [comment]
Merged.
