### ISSUE TITLE
Expected bug in tour on mobile

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2419]
Angular's `.scope()` function is not available on production systems, but is used in the tour at https://github.com/medic/medic-webapp/blob/develop/static/js/modules/tour.js#L39.

To debug this problem, you can run the app locally, but access it via http://192.168.0.1:5988 as it detects if it's in production mode by checking if the domain is `localhost` – https://github.com/medic/medic-webapp/blob/33f84e8fb80d27db72df41af66a27571728b36bc/static/js/app.js#L65

Ref https://github.com/medic/medic-webapp/issues/2407

**Comment by garethbowen** [comment]
Patched that bug. The tour is still really out of date but #2212 should fix that.

**Comment by alxndrsn** [comment]
1 comment inline.

**Comment by ngaruko** [comment]
Moving it to ready. Tour to be updated as in #2212
