### ISSUE TITLE
Expected bug in enketo phone widget

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2420]
Angular's `.scope()` function is not available on production systems, but is used in the enketo phone widget at https://github.com/medic/medic-webapp/blob/develop/static/js/enketo/widgets/phone-widget.js#L52.

To debug this problem, you can run the app locally, but access it via http://192.168.0.1:5988 as it detects if it's in production mode by checking if the domain is `localhost` – https://github.com/medic/medic-webapp/blob/33f84e8fb80d27db72df41af66a27571728b36bc/static/js/app.js#L65

Ref https://github.com/medic/medic-webapp/issues/2407

**Comment by alxndrsn** [comment]
LGTM 👍

**Comment by sglangevin** [comment]
This is now working as expected.
