### ISSUE TITLE
extract-person-contacts migration only edits with depth=1

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2421]
`extract-person-contacts` migration creates the `person` docs. Because we keep the full `parent` field for places and persons, if you just update the first layer you get inconsistent data.

E.g. you get docs like this : 
```
{
   _id: clinic1
   contact: { _id: contact1, ... } // 2.x contact
   parent: {
      _id: healthcenter1
      contact: {name : Alice, phone: 1234} // 0.x contact
   }
}
```
while the healthcenter1 doc is this : 
```
{
   _id: healthcenter1
   contact: { _id: contact2, name : Alice, phone: 1234 } // 2.x contact
}
```

We might as well get clean data once and for all! Make the migration edit at infinite depth of parents.

**Comment by estellecomment** [comment]
@SCdF please enjoy the async waterfalling and review 
(you can ignore the first commit, though there's promise waterfalling in it, just saying)

**Comment by SCdF** [comment]
OK I've read this code, and it's pretty darn complicated! Probably because I'm missing quite a bit of context here. I _think_ I understand it, but I agree with @mandric's comment on the ticket, it might be worthwhile tagging @garethbowen into this one :-)

**Comment by estellecomment** [comment]
@garethbowen you're up

**Comment by estellecomment** [comment]
Hopefully clearer with more documentation, @SCdF lemme know if it helps or if some bits are still unclear.

**Comment by garethbowen** [comment]
Ugh... inlined contacts are hurting.

Signing off on code review because it's the right thing to do.
