### ISSUE TITLE
The tour keeps popping up on mobile

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2423]
If a user is unknown and they load the app on mobile the tour pops up. This is good. Unfortunately every subsequent time they load the app the tour pops up again.

When the close the tour they should be marked as "known" and the tour shouldn't pop up any more.

**Comment by garethbowen** [comment]
Confirmed. Error on tour render:

```
angular.js:13550 ReferenceError: user is not defined
    at Object.startupModals.render (inbox.js:511)
    at showModals (inbox.js:531)
    at inbox.js:583
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at angular.js:17268
    at completeOutstandingRequest (angular.js:5869)
    at angular.js:6145
```

**Comment by garethbowen** [comment]
I can't reproduce this. The tour shows on the first load but immediately updates the user so `known:true` and then it doesn't show again. Assigning to @sglangevin to test.

**Comment by ngaruko** [comment]
Hi @sglangevin  Is it still happening. Was something done to fix?

**Comment by sglangevin** [comment]
I don't think this is still happening, not last I checked anyway. We now create most users (all created with the user creation script) with `known: true` to prevent the tour from popping up at all, and I've not seen this issue with users created via the web app.
