### ISSUE TITLE
Find a better way to ignore doc_ids when generating replication ids

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2424]
In #2404 we introduced a pouchdb patch so the replication checkpoint would work properly. It doesn't make sense to contribute this back to pouchdb, but we don't want to be stuck with a patch forever.

Find a nicer way to achieve this.

**Comment by garethbowen** [comment]
One possibility is to use the custom builds in pouch 5.4+ so we could build in our own replication id generator.

**Comment by SCdF** [comment]
LGTM

**Comment by garethbowen** [comment]
No AT required.
