### ISSUE TITLE
Editing Reports in the History tab is broken

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2427]
lg-testing.app, version 2.7.0-beta.3468

Here's what I did:

1. Go to the History tab
2. Open a report
3. Click Edit
4. Make an edit to the report and click Submit.
5. You'll see a notification that the report was updated, but you'll be taken to a "no report found" screen.
6. If you click on the same report again to open it, you'll see that the edit you made didn't stick. 

I didn't see any useful errors in the console.

**Comment by garethbowen** [comment]
Possibly relevant: `Data node: /pregnancy/meta/deprecatedID with null-based index: 0 not found. Ignored`

**Comment by garethbowen** [comment]
It looks like editing also removes the `form` property so something is going horribly wrong.

**Comment by sglangevin** [comment]
Editing now works, but it goes to a "No report selected" page for a second after you Submit edits or when you switch from viewing one report to another.

**Comment by garethbowen** [comment]
Getting a "No report selected" page for a second sounds like a separate bug.

**Comment by sglangevin** [comment]
Ok, I will file that separately.
