### ISSUE TITLE
Cannot login as admin in fresh browser

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2428]
lg-testing.app, admin, Chrome, version 2.7.0-beta.3468

Logging in as admin with a clean browser gives...

`inbox.js:57 Uncaught (in promise) ReferenceError: callback is not defined(…)`

**Comment by garethbowen** [comment]
This is coming from the initialReplication method in the bootstrap.

**Comment by SCdF** [comment]
Winner.

**Comment by sglangevin** [comment]
This is now working. If you had tried logging in and still see this issue, clear your cache and try again.
