### ISSUE TITLE
Increase stability by looping over changes 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2430]
While it takes `curl` ~20 seconds to download an entire changes feed it can take node / the pouchdb library significantly longer, presumably because it's also parsing the JSON.

In fact, I've noticed that while trying to run the code in a production environment `curl` works fine but node can sometimes be affected by timeouts or (if you disable timeouts) errors in couchdb / medic-api. It's unclear why this is the case, but in an effort to increase stability we should call `_changes` multiple times with a `limit` instead of just once.

**Comment by SCdF** [comment]
Note that it sometimes *does* work: it's not constrained by an actual knowable timeout (ie if it takes longer than 60s you get booted out). It just seems to be really flakey, presumably as a function of how stressed the server is. Hopefully decreasing the amount of effort CouchDB has to perform to give us a chunk of changes will reduce that flakiness.

**Comment by SCdF** [comment]
@estellecomment another review for ya!

**Comment by estellecomment** [comment]
LGTM
