### ISSUE TITLE
If couch2pg fails we can lose delete / edit data required for xmlforms

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2431]
The current rough structure of medic-analytics is this:
 - download all couchdb changes since last time
 - _then_ download a batch of those documents and store them in pg, and store the highest seq so we don't repeat ourselves
 - _then_ download the next batch, _loop until no more changes_
 - _then_ pass a summary of all those changes to xmlforms and have it delete any documents in that summary (since they represent either a deleted document, or an edited document you need to regenerate, or a new document which makes the delete a no-op)
 - _then_ find all couchdb docs that haven't and their xml extracted and do the extraction
 - if anything goes wrong in any of the above steps _catch_ the error, skipping all steps, log it and wait N minutes for the next loop attempt

If, for example, downloading a batch fails (eg due to timeout, which is quite likely), the edits / deletes from any previous successful batches get lost and never get sent to the xmlforms code.

This is handicapped a bit by the current design: the couch2pg code (the first 3 steps above) is intentionally set apart and independent from the xmlforms code.

Ways we could solve this:
 - remove the xml processing altogether, instead have code that searches for form name / version combinations it doesn't know about and generates views (that hook into the JSON, which was extracted by the XML anyway). This code would run after a couch2pg run regardless of whether it was successful. *This is preferred IMO*
 - store the list of changed docs in the DB so that if subsequent batches fail we don't miss out on successful batches.

**Comment by SCdF** [comment]
Actually @garethbowen don't review this: after talking to @michaelkohn in more detail about how they use the data I'm pretty sure we can do #2432, which honestly renders this pretty revertable.

**Comment by SCdF** [comment]
Actually actually @garethbowen, do review this. I've looked through it and I don't think it's worth reverting, there are useful refactors, fixes etc in there as well, and it's still something I can build the next step on quite cleanly.

**Comment by garethbowen** [comment]
Makes sense. One unused function?
