### ISSUE TITLE
Remove XML parsing and replace it with JSON views

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2432]
medic-analytics currently parses 2.6+ XML reports and uses that to generate tables. 

After looking into the medic-webapp codebase we discovered it doesn't need to do this, because we extract everything relevant out of the XML and put it into JSON anyway.

This means that it is possible to simply generate a view into the JSON instead of copying data from XML into tables.

This is much preferable:
 - It makes the importer faster
 - It makes the importer more stable (see #2431 and #2430 and sort of #2264)

It may reduce performance in actual analytics, but if this is the case we can change those views to be materialized and regenerate them at the end of every run.

**Comment by SCdF** [comment]
So a fly in this particular ointment is that the current data_record structure looks like this:
```json
{
  "_id": "blah",
  "_rev": "1-blah",
  "content": "<data id='FORM' version='A_DATE'>...</data>",
  "form": "FORM",
  "type": "data_record",
  "content_type": "xml",
  "fields": {...}
}
```

So if we want to generate a bunch of views based on form and version (as we currently do with tables) we still need to parse the XML to get the version.

I was hoping I'd be able to just do
```sql
SELECT doc->>'form' AS form, doc->>'version' AS version, doc->>'fields' AS fields
FROM couchdb
WHERE doc->>'type' = 'data_record'
GROUP BY form, version;
```
or whatever. This would mean we wouldn't need to specifically inspect new documents.

I haven't worked out what to do about this exactly. One option would be in couch2pg extract the version out of all `data_record`s into the `couchdb` table so that we can query it. The downside of this is that it's no longer generic (there will now be medic logic in there), though honestly that's probably not a massive deal.

**Comment by SCdF** [comment]
So I've talked to @michaelkohn about how the data is currently used in 2.6+ projects (ie what the xmlforms stuff has been written for). We are pretty confident we can get rid of the xml extraction stuff, and replace it with directly talking the `couchdb.doc` json. This will also solve the #2436, and in general simply the code base.

This is because the way the `formname_version` tables are currently used is by hiding them behind a (sometimes materialised) view, which is a union against all of the various version tables. There should be no reason we can't replace that (sometimes materialised) view with one that talks directly to the data in `doc->'fields'`.

The plan would be:
 - Delete all the code required to extract xml and generate `formname_version` tables
 - Delete all the code required to populate the `form_metadata` table
 - Replace the `form_metadata` table with a materialised view that pulls the same data directly from the `couchdb.doc` json.
   - NB: The form version column of this table is not currently being used. If we'd like to use it later though, we can deal with it then, by writing some code that extracts just that value out of the xml and puts it either on another table or directly as a column on the `couchdb` table.
 - Make sure that at the end of each run the update materialised view code still runs and is not deleted, as this is important both to the `form_metadata` mat view, but also important to all the 3rd party mat views that are used.

I'm going to take a quick crack at converting one of these views to talk to the couchdb table directly.

If for some reason we realise this isn't going to work and we need the xml extraction, the plan would be:
  - Change the code that generates the `CREATE TABLE IF NOT EXISTS` statements to instead
  - Attempt to get all columns from that table in the DB
  - If it doesn't exist generate the `CREATE TABLE` statement
  - If it does check that it has every column we need
  - If it doesn't generate an `ALTER TABLE foo ADD COLUMN bar TEXT DEFAULT NULL` for each missing column

**Comment by SCdF** [comment]
PR for the primary plan is here: https://github.com/medic/medic-analytics/pull/33

I've attempted to convert one of the views and it looks promising. More work to be done on that front though.

**Comment by SCdF** [comment]
Update: I've converted the view and handed it to @michaelkohn so he can take a gander and see what he thinks.  I'm reasonably confident that we can proceed with this branch, but I'll talk to Michael about it when he's around.

**Comment by SCdF** [comment]
Hey @garethbowen if you give this a once over that would be appreciated.

**Comment by garethbowen** [comment]
So much deletion :heart: 

I've added a few comments to the review, mostly stylistic, but it would be good to get the name of the "legacy mode" sorted before shipping this because that's an api.

**Comment by SCdF** [comment]
Merged.
