### ISSUE TITLE
We assume the presence of `patient_id` field

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2437]
Several places in the code assume that forms/data_records have a `patient_id` field. 
We use it to connect the `data_record` to the `person`.

If a form has no `patient_id` I think your instance will be messed up. For DIY it's a real problem. 

AFAIK, there is no validation when creating forms to make sure that this field is present. Add it.

(not quite sure if it's relevant to 0.4, but we need it fixed in the merged 2.x version)

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by abbyad** [comment]
Closing, but we can consider this as part of our tests of configurations.
