### ISSUE TITLE
Cannot load `users` page

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2444]
Seen on lg-testing.app, v2.7.0-beta.3497. Reproduce by trying to load https://lg-testing.app.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/users

Seems like we are trying to load all of the `clinic` records. I think this is because one of the drop-downs (Place drop-down) in the Create User modal has a full list of all facilities instead of using the new select2 drop-down, the way the Associated Contact drop-down does.

![image](https://cloud.githubusercontent.com/assets/1286381/16455109/08f11404-3dc8-11e6-8c7e-e3b69b5210c7.png)
![image](https://cloud.githubusercontent.com/assets/1286381/16455141/24317de4-3dc8-11e6-8cfb-06df744d7fe3.png)

**Comment by garethbowen** [comment]
There are two requests failing - one to load the users and one to load the facilities. You're right about using the new select2 instead of a plain dropdown with all facilities. Also LG has around 1100 users so this configuration page isn't going to perform well anyway so I'm considering adding pagination.

**Comment by garethbowen** [comment]
Acceptance testing:
- administrators can add, edit, delete on the Configuration > Users page
- all users can edit their own password and settings on the Hotdogs > Edit User Settings page

**Comment by SCdF** [comment]
LGTM. You left yourself assigned so I'm not closing this or de-assigning you in case you did that intentionally.

**Comment by sglangevin** [comment]
This is working well - moving to ready.
