### ISSUE TITLE
App takes minutes to load a `person` dropdown

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2445]
I got stuck here when trying to edit a CHP Area on lg-testing (v2.7.0-beta.3497):
![image](https://cloud.githubusercontent.com/assets/1286381/16463897/b233f0ee-3dec-11e6-8d46-7a123624c3c8.png)

When I clicked on the drop-down for Branch, I saw 2 requests, one for `contacts_by_type` and one for `doc_summaries_by_id`, but when I clicked on the drop-down for CHP or Supervisor, it seems to get stuck on the `contacts_by_type` request for a long time. Eventually, after 2-3 mins, I saw the `doc_summaries_by_id` request appear, along with `Error fetching facilities`:
![image](https://cloud.githubusercontent.com/assets/1286381/16463975/018752c6-3ded-11e6-8c07-fffa975fb6e0.png)

When trying to load the next bunch of contacts (by scrolling down in the drop-down), it again took a long time to respond with the summaries, but I didn't see any errors in the console. Here is more info on the console error - similar to the one reported in #2444:

![image](https://cloud.githubusercontent.com/assets/1286381/16464150/b0341c64-3ded-11e6-9ba2-6633652a15b1.png)

This no longer meets our goal of acceptable performance for select2 drop-downs.

**Comment by SCdF** [comment]
Looks good

(another day, another view…)

**Comment by sglangevin** [comment]
This seems to be working well on lg-testing.app. The use case of editing contacts works well, as long as I don't type the search term in too slowly as I've seen this cause the web app to get stuck on a request, though perhaps my internet connection dropped for a second as I'm now having trouble reproducing that. I am able to get the app to freeze momentarily, but it recovers. This happens if I type a search term, then delete some letters, then add more, and do that a few times. Is there anything that we can do to improve this further? If not, then I'm happy to move this to Ready and continue testing in production to see if we run into any issues.

**Comment by garethbowen** [comment]
There are still specific words that will cause your browser to hang trying to sort them all but they're not very common. The only solution I can think of is to get the database to do the filtering and sorting but this isn't possible with couch as it is.

**Comment by sglangevin** [comment]
Sounds good. Let's move this to Ready and see how it goes in production.
