### ISSUE TITLE
Sentinel is adding transitions to XML data_records

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2458]
If there's two types of `data_record`s, Sentinel should only add transitions to the JSON `data_record`s, and not mess with the XML ones. 
(ultimately we'll merge both systems and have medic-api process the SMS forms and remove Sentinel.)

Right now it's adding `transitions.default_responses` for instance (don't know what that is yet) and maybe others.

**Comment by estellecomment** [comment]
Actually, does sentinel post-process xml reports sent from medic-collect? 
If yes, we have to sort through the different types of xml reports. Hmm.

**Comment by estellecomment** [comment]
I used the field `content_type`, since it's there in the 2.x forms and absent in all the various report formats in 0.4 (not in textforms, not in medic-collect). 

Assigning @mandric for review, let me know if that's not a good way to check.

**Comment by mandric** [comment]
What is wrong with sentinel post processing  records/forms submitted with xmlforms again?

**Comment by estellecomment** [comment]
So, it depends. 
If it's an xml form submitted by medic-collect, then it's cool, it SHOULD be post-processed.
If it's an xml form sent by android (LG-style), then there's not schedules, contact-adding, id-generation, all of that. LG doesn't use sentinel at all. 

Notes:
 - there may be other transitions or types of docs that need to be filtered like this
 -  I'm moving towards getting the SMS features working only, for now without android features. We won't need both to work on the same instance for a while.

**Comment by mandric** [comment]
I think we might need to figure out what transitions/features we need in 2.x and which ones can be removed.  Sounsd like we need to do an "audit" of some kind of sentinel and prune what is not relevant to 2.x and fix what conflicts.

**Comment by mandric** [comment]
I don't think we want to skip all transitions?  Also can we please have major changes in a branch if they need to be reviewed?

**Comment by estellecomment** [comment]
Sorry about the lack of branch, I've done it a couple times in a row now, I'll watch out to not do it again! I'll also try to talk before implementing weird newness, that would probably be a smoother process.

For 2.6-7 data_records, I'm sure we want to skip all transitions: 2.6-7 doesn't use sentinel.
The question is, are there other types of docs that need finer granularity, e.g. a new clinic is created from android, it doesn't need sentinel post-processing, but how does sentinel know it's not an SMS-created clinic? (or whatever)
Agree that this needs a full review of sentinel transitions and how they're used.

**Comment by estellecomment** [comment]
filed https://github.com/medic/medic-webapp/issues/2463

**Comment by estellecomment** [comment]
(also what's with the thumbs-down @browndav, not sure which of the two statements it's about, feels a bit aggressive!)

**Comment by estellecomment** [comment]
reverting this, since it's too simplistic.
We should review transitions more generally, and see which ones apply, in https://github.com/medic/medic-webapp/issues/2463
