### ISSUE TITLE
Language select modal is blank

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2459]
<img width="512" alt="select-no-language" src="https://cloud.githubusercontent.com/assets/2064938/16569339/86f761bc-4289-11e6-921d-01216db4deb6.png">

**Comment by alxndrsn** [comment]
👍

**Comment by sglangevin** [comment]
@garethbowen can we add this to the 2.7.1 release?

**Comment by garethbowen** [comment]
This shouldn't affect 2.7.1. This was caused by https://github.com/medic/medic-webapp/issues/1706 which wasn't included in that release.

**Comment by sglangevin** [comment]
I'm seeing this same issue on 2.7.1, should have said that.

**Comment by garethbowen** [comment]
I'll have a look.

**Comment by garethbowen** [comment]
@sglangevin This is what it looks like on lg-testing for me:

![populated-select-language](https://cloud.githubusercontent.com/assets/2064938/16600390/f2d999b4-435a-11e6-934e-556f461da732.png)

Can you grab a screenshot of the bug you're seeing in 2.7.1?

**Comment by sglangevin** [comment]
@garethbowen sorry, I misread the issue title. The place where I'm not seeing the languages is when creating or editing a user. I can open a new issue for that.
