### ISSUE TITLE
Create a fresh instance with 0.4 app_settings and 2.x latest code

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2460]
Fresh instance for testing the 0.4 features are working properly with latest code for webapp, api, sentinel and medic-reporter.
No android users, just SMS features.

Then push it on some shared instance so that Acceptance Testers can check the features are working.

**Comment by mandric** [comment]
@browndav @abbyad please assist, my quota appears to be limited on AWS.

**Comment by mandric** [comment]
@browndav @abbyad nevermind!

**Comment by mandric** [comment]
Actually still having problems.  For some reason the instance (i-020ba6ad) can't get a public IP.

**Comment by estellecomment** [comment]
Creating fresh instance : howto, locally
 - Create empty db
 - Grunt dev : that creates the ddoc.
 - Use `script/update_settings.js` to push the DIY settings.
 - Make sure you have an admin user in _users (copy it from another instance)
 - Run api : the migration will create user-settings.
 - Run sentinel.
Make sure you have medic-reporter, it's handy.

**Comment by estellecomment** [comment]
More instructions to get started : there's descriptions for all fields in the app_settings, if that's useful : https://github.com/medic/medic-webapp/blob/develop/kanso.json#L83

**Comment by estellecomment** [comment]
Will get a VM snapshot ready tomorrow. I'm using http://dev.medicmobile.org/downloads/medic-os/20150623/, x64 version (gave up on trying to get x86 to work). 
Which means no Simapp charging, but should be fine for development, we can use medic-reporter for testing anyway.

**Comment by abbyad** [comment]
Feel free to use diy.dev for this testing.

**Comment by browndav** [comment]
We're probably bumping up against AWS' region-specific resource limits. I'll request an increase and see what we can recover from existing instances.

**Comment by mandric** [comment]
I will fix this.

**Comment by mandric** [comment]
![screen shot 2016-07-18 at 5 03 48 pm](https://cloud.githubusercontent.com/assets/25641/16928539/a2f0379c-4d09-11e6-9a69-f13c5b9a3651.png)

Unfortunately the app doesn't support this right now.  Mainly because of issues in gardener/dashboard when the db name is not `medic`.  To clear this up I will delete all the instances of webapp then install again.

**Comment by mandric** [comment]
Ok there is a fresh alpha on diy.dev now.  I haven't pushed any settings there though.  We can work that out as we do our testing.

**Comment by sglangevin** [comment]
@mandric I think the intention was to push the DIY app_settings and some forms so that others can support testing.

**Comment by ngaruko** [comment]
No longer relevant according @estellecomment .
