### ISSUE TITLE
Investigate if sentinel transitions break smartphone users

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2463]
For systems that have both SMS users and smartphone users, we'll need sentinel for the SMS users, but it shouldn't get in the way of smartphone users.

Look at the list of transitions and what they're for, and decide how to edit them.

**Comment by SCdF** [comment]
So @estellecomment looking at this ticket and then looking at Sentinel, I'm not really sure what you're asking for. Are we looking to delete transitions we don't think anyone uses anymore? Or that we don't want to support in 2.x for <some reason />? Are we saying that transitions required for SMS don't work with 2.x? Or that we're not sure if they work? Or if we need them at all?

I mean, we could write a paragraph or two about what each transition does, but I'm not clear about what that's achieving.

**Comment by estellecomment** [comment]
In the case where you have both SMS and smartphone users, transitions could be modifying things for nothing, and we should check that they don't break things.

E.g. for reports : reports will be coming from both SMS users (need transition) and smartphone users (don't need transition), and transitions could be applied to both. Will the smartphone users' forms be messed up accidentally by transitions?

The point of the issue is to remember to check if this is happening, for all transitions, preemptively. And file issues if there are some. 
(Alternatively, we could just click around the UI randomly to see if features are working, but it seems smarter to me to check things methodically)

Renaming the issue (hopefully it's clearer, let me know if it's not @SCdF ) and kicking out of the milestone, because we don't have both types of users for now.

**Comment by alxndrsn** [comment]
@estellecomment @SCdF what's the status of this ticket?  Does it need fixing before 0.4 instances upgrade to 2.x?  Can it be closed?

**Comment by SCdF** [comment]
@alxndrsn I'm pretty sure it's fine (ie these sorts of issues would come out in testing), but check with @estellecomment

**Comment by estellecomment** [comment]
yeah we're good, closing.
