### ISSUE TITLE
Creation of users who need direct access to query Brac's DB

### ISSUE THREAD

**Issue by Enock1990** [medic/medic-webapp#2465]
&lt;emptied&gt;

**Comment by michaelkohn** [comment]
@browndav, can you please set up these users with access to the `brac` database (read_only) on rdbms.dev.medicmobile.org? (sorry, I don't have access to actually assign this issue).  Also, feels like this should be in medic-projects.

**Comment by estellecomment** [comment]
side-note @Enock1990 : medic-projects is private, only Medic folks see it, while medic-webapp is public to everyone.
I would not like it if my email was posted on the internet publicly :)

**Comment by Enock1990** [comment]
hey Guys am sorry....no wonder i didn't have permissions. i didn't realize that i posted in medic-webapp

**Comment by henokgetachew** [comment]
@Enock1990 it's a good idea to edit the above post and make it empty and create the issue in `medic-projects`

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek
