### ISSUE TITLE
Login page not translated

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2466]
![login-translation](https://cloud.githubusercontent.com/assets/2064938/16637651/b6646b1e-4434-11e6-8396-c8b481ac3262.png)

**Comment by garethbowen** [comment]
I recently changed the doc_by_type view to emit `['translations', enabled]` as the key for translations docs. Unfortunately I forgot to update all the view queries so they were returning 0 rows. This change fixes that.

**Comment by alxndrsn** [comment]
I don't get what the `enabled` field in a translation's key is for (surely if they're not enabled, they shouldn't be emitted?), but this code looks fine.
