### ISSUE TITLE
Select2Search service overwrites previous instances

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2467]
If you use two Select2Searches then the first ones settings overwrite the second ones because the state is shared. This includes page size and types.

For example, in the Configuration > Users > Edit User modal we have one select for the user's facility and one for the user's contact. The contact select no longer works because the settings have been overwritten and now instead of searching for people it searches for places.

**Comment by garethbowen** [comment]
The diff is quite horrible because I changed indentation, but now all variables are declared inside the service function so nothing is shared between instances.

**Comment by estellecomment** [comment]
Trick : ignore whitespace in diff! https://github.com/blog/967-github-secrets

**Comment by SCdF** [comment]
🐝 🚚 🅰️ 🃏
