### ISSUE TITLE
Diff the app_settings in 0.4 vs. 2.x, and see what changed

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2470]
I'm taking the DIY app_settings as the basic 0.4 app_settings (yes I know it's 0.5, but it's what's being used as a base for seeding new projects) : 
https://github.com/medic/medic-projects/blob/master/diy/app-settings.json

And diffing against BRAC. Are some fields missing in DIY, and does it matter?

**Comment by estellecomment** [comment]
Some fields are missing in DIY app_settings, but most are covered by defaults : https://github.com/medic/medic-webapp/blob/develop/packages/kujua-sms/views/lib/app_settings.js

The ones that aren't covered by defaults are  "setup_complete", "statistics_submission", "statistics_submission_number". Figure out what they are.

("transitions" also doesn't have a default, but the default will be disabled, see #2207.)

**Comment by estellecomment** [comment]
for records : 
[app_settings_brac_sorted.txt](https://github.com/medic/medic-webapp/files/352304/app_settings_brac_sorted.txt)
[app_settings_diy_sorted.txt](https://github.com/medic/medic-webapp/files/352305/app_settings_diy_sorted.txt)
(there's what looks like useless SMS-related fields in the BRAC config, but I guess it doesn't hurt)

**Comment by garethbowen** [comment]
Setting | Explanation | Ok?
----- | ---- | ----
setup_complete | Decides whether or not to show the welcome modals. Is null until it's set on first render. | :heavy_check_mark:
statistics_submission and statistics_submission_number | Used for collecting and submitted anonymous statistics. Null means don't submit | :heavy_check_mark:
district_admins_access_unallocated_messages | Whether or not district admins can see messages with no contact. Default is correct | :heavy_check_mark:
forms | These are just JSON forms which we don't ship by default any more. All forms can be imported after install | :heavy_check_mark:
locale_outgoing | Default is correct | :heavy_check_mark:
tasks | We don't ship a default. Tasks can be imported after install. | :heavy_check_mark:
some transitions | If they're not needed it's fine not to include them in config. | :heavy_check_mark:
translations | Are pulled out in a migration. | :heavy_check_mark:

**Comment by garethbowen** [comment]
@estellecomment I think that covers all the properties in the diff. I think it'll all just work. Is anything else required to close this off?

**Comment by estellecomment** [comment]
all good thanks!
