### ISSUE TITLE
Document medic-reporter

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2472]
Needs description and intro text, and screenshots and url to use it.

![screen shot 2016-07-08 at 10 53 24](https://cloud.githubusercontent.com/assets/911434/16682386/bba1a6d4-44fa-11e6-8778-ad002703c1c6.png)

![screen shot 2016-07-08 at 10 51 46](https://cloud.githubusercontent.com/assets/911434/16682400/ca616f24-44fa-11e6-8b21-f13c6dec875f.png)

**Comment by estellecomment** [comment]
@mandric is there doc about the different report formats? I left "?" links.

**Comment by mandric** [comment]
See comments in the commit above https://github.com/medic/medic-reporter/commit/8913ff281db7b8f8b8b4b46b88ef6ae38d4fae46

**Comment by estellecomment** [comment]
Thanks!
