### ISSUE TITLE
Finish documenting app_settings schema

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2473]
It's almost done, but some parts are still missing, and it'll help me understand and memorize : there's questions I've already asked several times. 

Edit the settings_schema here: 
https://github.com/medic/medic-webapp/blob/develop/kanso.json#L83

**Comment by estellecomment** [comment]
@mandric I've done my best by I have gaps! Can you take a look and help fill them please? I've tagged you in the descriptions, look for "@mandric". (I won't submit that, I'll remove them as I go)

Also, you may how noticed how I'm doing my mess in a BRANCH now. :)

**Comment by mandric** [comment]
@estellecomment Ok thanks also filled in a few gaps and opened a PR.  Let me know if you need anything else here.

**Comment by estellecomment** [comment]
Thanks @mandric ! This is all very satisfying to me.
