### ISSUE TITLE
API connection refused

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2476]
We're occasionally getting connection refused trying to connect to lg.app on 2.7.1.

**Comment by garethbowen** [comment]
In the nginx error log:

> 2016/07/11 01:09:43 [error] 19985#0: *5901 connect() failed (111: Connection refused) while connecting to upstream, client: 111.69.85.204, server: _, request: "GET /medic/ HTTP/1.1", upstream: "http://127.0.0.1:280/medic/", host: "lg.app.medicmobile.org", referrer: "https://lg.app.medicmobile.org/medic/_design/medic/_rewrite/"

I'm not sure what port "280" is used for?

**Comment by garethbowen** [comment]
I think the changes handler might have a connection leak - if the incoming request is aborted by the user then we need to stop the outgoing changes feed request and clean up the request store.

**Comment by garethbowen** [comment]
Confirmed locally. Loading the app creates about 20 connections:

`netstat -an | grep 5984 | wc -l` => 20

Refreshing adds about 20 more. About a minute later most of these are cleared up but 4-6 remain.

**Comment by garethbowen** [comment]
PR submitted: https://github.com/medic/medic-api/pull/87

**Comment by SCdF** [comment]
LGTM

**Comment by mandric** [comment]
Did we forget to merge the PR here?

**Comment by SCdF** [comment]
No, Gareth knows to do it, which is why it's still assigned to him and not closed. I suppose you could argue it shouldn't be under Acceptance Testing, but you could also argue it shouldn't be under Code Review either, so <insert your shrug shoulders meme here>.

**Comment by estellecomment** [comment]
restarted medic-core, was happening again on lg.app (but I guess we haven't pushed the fix, so unsurprising)

**Comment by browndav** [comment]
LGTM. There's probably a way to use a map and avoid `_.indexOf`, but changind a minimum amount under these circumstances is good IMO.

FWIW, port 280 is the failover from the first-run application; nginx happily logs errors for every request even though we expect them to fail. I'll file an issue for this (to at least silence the log messages), and/or see if there are failure-remembering options for nginx in those situations.

**Comment by browndav** [comment]
@gareth: That accrual across restarts is (I think) `TIME_WAIT` connections, but screening them out with something like `set -o pipefail; watch 'sudo netstat -an 2>/dev/null | grep ESTABLISHED | grep 5984 | wc -l'` still shows the connections piling up / being leaked.

**Comment by estellecomment** [comment]
restarted medic-core, without actually checking if it was the same issue.

**Comment by garethbowen** [comment]
No AT required.
