### ISSUE TITLE
Update to node 6.3+

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2478]
We currently use node 5.x which has reached end of life. Ensure we can run on the latest node and upgrade the medic-os image then update production instances.

**Comment by SCdF** [comment]
@garethbowen intentional dupe of #2448 ?

**Comment by garethbowen** [comment]
Hah, no, I must be tired.

**Comment by garethbowen** [comment]
Seems to work fine. I need to update node on a production instance to test this fully.

**Comment by garethbowen** [comment]
To test this in production we need to update medic-os which will build a new medic-core package that we can then push on to an existing medic-os instance (eg: alpha.dev) to test it out properly.

**Comment by garethbowen** [comment]
medic-os is already running node 6.2: https://github.com/medic/medic-os/commit/d0f08bf059d78c01a693e9be2811e74cc94111bc#diff-53a8cc55c5052f5357c843385678ec1b

**Comment by garethbowen** [comment]
lg.app is running node 0.12 - we should update node next time we update the app.
