### ISSUE TITLE
Update to pouchdb 5.4+

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2479]
Don't let the name fool you, 5.4 should have been a major, so this may not be straightforward.

**Comment by garethbowen** [comment]
As part of this we can probably remove the explicit inclusion of leveldown in package.json.

**Comment by SCdF** [comment]
So is what you've done with the replication id matching stuff the new recommended way of monkey patching?

Other than that, LGTM

**Comment by garethbowen** [comment]
> So is what you've done with the replication id matching stuff the new recommended way of monkey patching?

I think it's another tool in the toolbox. It won't be appropriate in all cases but it seemed to work here.
