### ISSUE TITLE
Can we do all config through config UI pages, for SMS features?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2480]
There's always the app_settings dashboard page to fall back on, but would be good to not depend on it.
File issues for any missing pages.

**Comment by garethbowen** [comment]
Related:
https://github.com/medic/medic-webapp/issues/1784
https://github.com/medic/medic-webapp/issues/1397
https://github.com/medic/medic-webapp/issues/1330

**Comment by alxndrsn** [comment]
Related: #2481?

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
This is not currently needed and the design team is planning to do a review of config pages so I'm going to close this one for now in favor of the other, more specific issues that are mentioned here.
