### ISSUE TITLE
Bump depedencies

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2482]
Check and update dependencies in packages.json and kanso.json

**Comment by garethbowen** [comment]
Mislabelled commit: https://github.com/medic/medic-api/commit/dbfed0886bfe546923d68053887d0e87bcce0676

**Comment by alxndrsn** [comment]
All the numbers got bigger :+1:  
Looks like there's one new dependency (`grunt-contrib-jshint`).  If this is deliberate, then this is all fine.
