### ISSUE TITLE
Use sass importer option instead of custom grunt copy and paste

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2484]
enketo-core uses relative sass imports which [fail with npm v3+](https://github.com/enketo/enketo-core/issues/346). Until now we've had to [copy and paste the resources](https://github.com/medic/medic-webapp/blob/develop/Gruntfile.js#L161-L178) where we need them. Replace this with the slightly nicer [sass importer feature](https://github.com/enketo/enketo-express/commit/af07c20c7cf4d671252292c0899f420f26571dae).

**Comment by garethbowen** [comment]
Also had to update the shrinkwrap - it was still resolving from git. To fix the shrinkwrap, use `npm install <package>@<version>` and npm will fix it for you.

**Comment by estellecomment** [comment]
Didn't run it but LGTM.

Acceptance testing : check Enketo forms (i.e. all forms for LG/Brac) load, and fill one in.

**Comment by garethbowen** [comment]
No AT required.
