### ISSUE TITLE
Make a list of SMS features

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2487]
So that we know what to test against for regressions.

@abbyad, you said you have a starter list, based on the app_settings? Can you share?

(cc @sglangevin)

**Comment by abbyad** [comment]
The SMS in the webapp come from the following parts of the configuration:
- **`Registrations`**: Validation + response messages following a registration form 
- **`Schedules`**: Series of SMS triggered by a registration
- **`Patient Reports`**: Validation + response messages following submissions about patients
- **`Notifications`**: validations &  response messages when turning notifications on and off 
- **`Alerts`**: Condition based SMS that can look at prior form submissions (_non localized_)
- **`Scheduled Report Reminders`**: Cron based SMS for scheduled reports (_non localized_)

Some extra detail in [this doc](https://docs.google.com/a/medicmobile.org/document/d/112CIX6T0iji2ztRfbjYNbzTzITbeC2_zEUtJaW-WQDA/edit?usp=sharing)

**Comment by abbyad** [comment]
@estellecomment feel free to re-open if you need more info for this list.

**Comment by estellecomment** [comment]
Thanks @abbyad good work!
I have a couple clarifying questions (I can also comment on doc if you give me permissions) : 
 - What are Notifications? Are they the same as the Response Messages for Patient Reports and Registrations?
 - for Alerts, what are "rules" exactly? 
 - what's concatenation of messages?

**Comment by estellecomment** [comment]
Ah sorry, just realizing you explained the first point in your github comment above. 
Could you add the content of that comment to the doc so that it's self-explanatory? I'm happy to do it too if you like. (no permissions!)

**Comment by garethbowen** [comment]
Assigned to @abbyad

**Comment by abbyad** [comment]
I added more context in https://github.com/medic/medic-webapp/issues/2487#issuecomment-242805025 and fixed the permissions in the doc for further questions - although if anything is unclear we should make sure to clarify it in this issue too.

**Comment by estellecomment** [comment]
I updated the doc to reflect the changes : https://docs.google.com/a/medicmobile.org/document/d/112CIX6T0iji2ztRfbjYNbzTzITbeC2_zEUtJaW-WQDA/edit?usp=sharing

Thanks!
