### ISSUE TITLE
Make medic-docs usable again, and accessible where it's needed

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2488]
1. I think it's good to have offline docs for medic developers (maybe for contributors, like DIY users), so serving them from couch makes a lot of sense. However it's broken right now.
2. It's also good to have online docs! I'm looking into couscous.io for pushing pretty docs to http://medic.github.io. That would be our dev docs.

I'd like to get the two systems working on the same set of .md files. Any objections to this plan? 

It would also be helpful to know who medic-docs is for, to know where to display it. Is it for the same audience as the github READMEs? If medic-docs is for users not developers, then maybe the github READMEs need to go to http://medic.github.io, while medic-docs is shipped to be used offline from couch. @browndav @abbyad @mandric please advise. 

---

Details about the break:
When I `kanso push` locally I get this:

```
Error: Error: No such module: evals
    at Error (native)
    at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-docs/packages/modules/node_modules/kanso-utils/utils.js:12:21)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/estellecomment/dev/medic/medic-docs/packages/modules/node_modules/kanso-utils/modules.js:8:13)
    at Module._compile (module.js:425:26)
Failed
```

I think it's related to updating the `kanso-utils` package? https://github.com/kanso/kanso/issues/422
I don't really get how the dependencies work, npm or kanso? They are checked in to the repo.
So stuck there. @mandric, you're my reference for kanso things! Can you give pointers?

**Comment by garethbowen** [comment]
In my opinion medic-docs/md should be part of medic.github.io and the rest is of little or no use. We used to have user documentation as part of the translation files but this was removed to make the settings smaller: #1895

**Comment by estellecomment** [comment]
Additional info: these user docs are now in the DB, and not on github anywhere. They are .md files as well.

Put them online somewhere, too. Not necessarily the same spot as the dev docs in medic-docs/md.

Also consider how to make them accessible outside of the webapp, to troubleshoot your install (if you need webapp to access the docs to troubleshoot webapp install, well...)

**Comment by mandric** [comment]
I could see us moving the medic-docs/md/ directory (or the useful parts of it) into a webapp docs/ directory.  And just manage the docs as linked markdown files. Similar to https://github.com/electron/electron (see docs and docs-translations).  The docs could be used as-is on github (online) like they are now in medic-docs.  We can also add a build step that creates the  creates couchdb docs, and bundles PDFs or mini-html sites (as zip files) for offline use/further distribution on the website as part of the DIY package.

**Comment by estellecomment** [comment]
👍

**Comment by garethbowen** [comment]
medic-docs has been reworked so it's no longer an app. Offline user documentation is covered by #1895.

@estellecomment Can this issue be closed now?

**Comment by estellecomment** [comment]
yeah, closing. Thanks for cleaning up!
