### ISSUE TITLE
Mark deprecated repos as such

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2489]
I don't know if all of the repos in https://github.com/medic are used. Mark the deprecated ones, or delete them.

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
This is valid and we should do it. Scheduling for this iteration.

**Comment by garethbowen** [comment]
Important but not a priority. There's no way were getting to this this milestone. Removing.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
Clearly no one cares about this.

My advice: if you come across a repo that is deprecated, mark it as such. It's very low effort to change the README, you can do it inline in github these days.
