### ISSUE TITLE
Can't auto-complete phone number in auto-complete wizard

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2491]
![image](https://cloud.githubusercontent.com/assets/583851/16772981/1148646e-484e-11e6-9950-907e087f62b5.png)

I should be able to type into that white box. OSX / Chrome.

**Comment by garethbowen** [comment]
Wow: http://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal

**Comment by SCdF** [comment]
Yay another select2 issue crushed! Good job!

**Comment by SCdF** [comment]
Yay another select2 issue crushed! Good job!
