### ISSUE TITLE
Remove maxSockets limit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2492]
We added `http.globalAgent.maxSockets = 100;` to api because in the old days (node 0.10) it defaulted to 5 which wasn't enough. Since 0.12 node has defaulted it to Infinity. This limit is potentially contributing to #2476.

**Comment by garethbowen** [comment]
Mislabelled commit: https://github.com/medic/medic-api/commit/24c0af9e47b516da53c05514f77308041684a45f

**Comment by browndav** [comment]
LGTM.

**Comment by garethbowen** [comment]
No AT required.
