### ISSUE TITLE
Send Message doesn't work

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2494]
When you click the send message button no modal is shown.

**Comment by garethbowen** [comment]
The problem was the Contact service was trying to use the UserDistrict service with a callback which does nothing. I converted the Contact service to be promise based while I was in there.

**Comment by estellecomment** [comment]
Promises everywhere! Crush the callbacks! :kublai_khan:
Check out comments, I think there's a missing `return`.

**Comment by garethbowen** [comment]
Good spotting! Fixed.
