### ISSUE TITLE
Update README.md to be clearer as to what you need to run

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2497]
I’d like to rewrite the section about what you need to install / run / etc to basically say:
- You need couchdb, and medic-webapp which you push to couchdb, and medic-api which sits in front of couchdb
- You need medic-senintel if <REASONS>
- You need couchdb-lucene if <REASONS>
- etc

I guess it comes down to who we expect to be reading the readme. My thought is that it’s someone like me (obviously, because I have no imagination) who would want to know the minimum to get something working in my browser, so I can find a tiny bug that has been backlogged that I can chip away at and fix.

**Comment by estellecomment** [comment]
+1 to making that clear.

I added a separate file, architecture.md, in which I specify what you need in which case (it's linked from the Overview section at the top), but agree that the "what you need" info should be available in the "How to build/run" of the README. Knock yourself out moving stuff around.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
It was easier to just re-read the readme and fix it where necessary.

Lucene is optional, but I'd argue sentinel is now required since we need system transitions to run, so all that needed to be changed was the lucene section.

**Comment by SCdF** [comment]
@estellecomment please take a look at some minor readme changes: https://github.com/medic/medic-webapp/pull/3417
