### ISSUE TITLE
Split medic-analytics into couch2pg and medic-specific repositories

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2499]
medic/medic-analytics currently does two main things:
- Syncs a couchdb database with postgres
- Creates some views that only medic (or people who use our data format) care about

In the spirit of creating useful open source we should split the first part off into a standalone tool / library. This is helped by the initial codebase being written with this future in mind.

I'm not overly familiar with npm etc, but I imagine the steps to take would be:
- Split this code off into its own repo
- Expose a code-level API you can call that passes in the various parameters required
- Expose a command-line tool that does the same thing
- Publish to npm
- Use this published package in the original repo

IMO It would make sense if the new repo that could be used by all was just `medic/couch2pg`, and the one that pulls the library in is `medic/medic-couch2pg`. Unless ya'll think that's too confusing.

**Comment by mandric** [comment]
+1 Also since each project might have specific analytics needs (views) you might consider having a `medic-projects/lg-uganda/analytics` that integrates libs. Or even a `medic-projects/generic-analytics` or `medic-analytics` with different profiles in it.

**Comment by SCdF** [comment]
Hey @garethbowen, can you check out as much that you think is relevant of:
 - The PR which removes couch2pg stuff from medic-couch2pg and uses a library instead: https://github.com/medic/medic-couch2pg/pull/34
 - The actual library code (mostly copy / paste, though the cli stuff is new): https://github.com/medic/couch2pg
 - Note that it's also published to NPM: https://www.npmjs.com/package/couch2pg

Current version is `0.1.1` for good reason: Both the library and cli are pretty rough around the edges, but the gist is there and they are both usable.

**Comment by garethbowen** [comment]
@SCdF It looks like the tests have been moved to couch2pg but the grunt task to run the tests hasn't been. Otherwise it looks good.

**Comment by SCdF** [comment]
Whoops, that was my overzealous deleting of medic-specific stuff. I've added it back.

**Comment by SCdF** [comment]
Fixed, tests work now, merged.
