### ISSUE TITLE
couch2pg doesn't appear to be honouring constraints

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2506]
Running it against LG I'm getting the following when trying to regenerate materialised views:

```
XMLForms support failed
error: duplicate key value violates unique constraint "contactview_metadata_uuid"
    at Connection.parseE (/home/stefan/medic-analytics/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/home/stefan/medic-analytics/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/home/stefan/medic-analytics/node_modules/pg/lib/connection.js:105:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
```

**Comment by SCdF** [comment]
Turns out we don't have a unique constraint on `couchdb.doc->>'_id'`, just a regular index. That's pretty wrong.

It's currently not clear though, how duplicates are making it in, since AFAICT before any document insertion we send a delete for that specific document first.

**Comment by SCdF** [comment]
So there is one document that is in there twice, and it's the same document (md5 of both are identical).

I'm going to stare at the code a little more, but I'm really not seeing how this could happen, unless somewhere along the way couchdb is sending us the same id twice, which seems weird.

**Comment by SCdF** [comment]
If you request the same document twice in bulk get (`allDocs` in PouchDB) you get the same document back.

**Comment by SCdF** [comment]
NB: FWIW I have no idea how you'd get the same document in there twice. AFAIK (and from mucking around testing) `changes` should only contain one value for each document.

**Comment by SCdF** [comment]
I think I'm going to attempt to solve this by:
 - Putting a unique constraint on `couchdb.doc->>'_id'`. Apart from being more correct, this could give us more detail if it happens again.
 - Uniqifying ids before they go into the `allDocs` call

**Comment by SCdF** [comment]
Hey @garethbowen, may I suggest you use this white-space hiding link: https://github.com/medic/medic-analytics/commit/76973afb478fa2b09f17c79c3ab8e3525ac03445?w=1 when reviewing. Otherwise, I apologise.

**Comment by garethbowen** [comment]
Looks good. Is it worth reviewing other indexes to see if they should be unique too? Any other data integrity constraints?

**Comment by SCdF** [comment]
re: existing indexes, I looked through the ones we create and all the ones that should be unique are.

In terms of adding new ones: none spring to mind for me. Are there any you can think of?

I'm pretty sure the only one CouchDB guarantees is that there is only one document for a particular `_id`, right (ignoring conflicts)?

We could probably add more in the "xmlforms" side (that needs to be renamed…) for specific Medic constraints, though that would be more down the schema validation road. Are there any ones that you'd particularly want?
