### ISSUE TITLE
window.PouchDB.utils doesn't exist (using a different db name from medic, loading 0.4 data in)

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2507]
I've created a new DB called `medic04` locally, which I:
 - Created in couchdb
 - Pushed medic to by changing my kanso.rc to point to it, and then running `grunt dev`
 - Ran medic-api over it by altering the `COUCHDB_URL` parameter I pass to it to be `http://.../medic04` instead of `http://.../medic`.

I then logged in at `http://.../medic04` as the couchdb admin user.

*What should happen*
The app should load!

*What does happen*
The app gets stuck in initial replication (showing just a spinner) because in [this code](https://github.com/medic/medic-webapp/blob/develop/static/js/bootstrap.js#L45):

```js
  var initialReplication = function(db, username) {
    if (utils.isUserAdmin(getUserCtx())) {
      return window.PouchDB.utils.Promise.resolve();
    }
```

`PouchDB.utils` is `undefined`.

*Additional notes*
 - If I log in as a normal user I get further, to the actual app.
 - ~~I can log in with my existing 2.x database, even after I've run grunt build again.~~

**Comment by SCdF** [comment]
OK so I double checked and did a full re-pull and re `npm install` of both webapp and api, and now this is happening for both 2.x and 0.4 databases.

**Comment by SCdF** [comment]
```
scdf at SCdF in ~/Code/Medic/medic-webapp on develop*
$ grep -r "PouchDB.utils =" *
node_modules_backup/pouchdb/dist/pouchdb.js:PouchDB.utils = utils;
node_modules_backup/pouchdb/lib/index-browser.js:PouchDB.utils = utils;
node_modules_backup/pouchdb/lib/index.js:PouchDB.utils = utils;
static/dist/dependencies.js:PouchDB.utils = utils;
```

So if I'm reading this right, nothing in actual `node_modules` provides this anymore, but it's still in our dependencies, but it's not getting run (or `utils` is undefined) for admins.

**Comment by SCdF** [comment]
Right, so `dependencies.js` is an old file that we don't use anymore.

**Comment by SCdF** [comment]
Two options:
 - use `window.Promise`, which is either already polyfilled, or I can make it so
 - use `require('pouchdb-promise')`

I'd rather use the former, will test it and make sure it works on the Tecno when I'm near one later today.

**Comment by garethbowen** [comment]
I think a better solution would be to avoid using a promise library at all. If you look at the code you can move this

```
    if (utils.isUserAdmin(getUserCtx())) {
      return window.PouchDB.utils.Promise.resolve();
    }
```
down into the modules.exports block and just call the callback.

Thinking about it some more I think admins could shortcircuit before they've even looked for the ddoc in db.local. I can't remember why we stored the ddoc locally for admins now, but it's not working any more. Work out whether we still need it, and shortcircuit earlier if we don't.

**Comment by SCdF** [comment]
@garethbowen the first commit was to get `develop` working correctly for the time. The rest solve the actual ticket, as well as clean up the split between local and remote ddocs.

**Comment by garethbowen** [comment]
Nice addition to the watch list. A few comments inline to work through.

**Comment by SCdF** [comment]
Made some changes based on your feedback, will chat to you when you're around on your Monday about the other comments

**Comment by garethbowen** [comment]
Happy to close now. Nice work.
