### ISSUE TITLE
ENOENT errors running grunt dev

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2510]
Sometimes I get the following when running `grunt dev`

```
>> watch /Users/scdf/Code/Medic/medic-webapp/api_working ENOENT
>> watch /Users/scdf/Code/Medic/medic-webapp/api_working/ ENOENT
```

Not sure if this is a real problem or not, and it only happens sometimes. Need to investigate.

**Comment by garethbowen** [comment]
Yeah I've seen those too. It's some sort of timing issue with (I think) grunt watch looking at kanso's temporary api_working directory. It's safe to ignore it but it would be good to get to the bottom of it.

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
@garethbowen @SCdF any thoughts on this one? This is a pretty dev-specific issue.

**Comment by garethbowen** [comment]
It doesn't get in my way much - it just looks bad when you're compiling. Happy to close. @SCdF ?

**Comment by SCdF** [comment]
Yeah whatevs. The whole thing is kind of unstable (mine randomly fails on `kanso push` now sometimes), but it's not causing major issue. Maybe we can be cool and move away from grunt entirely at some point…
