### ISSUE TITLE
Fix bad medic-api merge

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2514]
`handleApiCall` is undefined.

Work out why jshint didn't detect it.

Also, is getUserCtx being called twice?

**Comment by mandric** [comment]
Maybe also double check `diy` branch is there and delete that as well? https://github.com/medic/medic-api/compare/diy

**Comment by garethbowen** [comment]
Thanks @mandric . I'll do that as part of #2410 rather than this.

**Comment by garethbowen** [comment]
### Code review

- Our jshint configuration was anaemic so I've beefed that up to catch similar errors in future
- That meant I had to fix a bunch of errors that jshint found
- When in doubt use `serverUtils.error` instead of `serverUtils.serverError` - the former tries to detect what kind of error it is (eg: not logged in) and handles that nicely, before falling back to the latter. This probably needs documentation or better naming or something...
- `auth.check` throws a not logged in error when there's not userCtx so you don't need to manually check that again.

**Comment by garethbowen** [comment]
No AT required.
