### ISSUE TITLE
'New Contact' option does not appear without a search

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2516]
In order to use the 'New Contact' option when creating a place (such as a district), the user has to type in "new" into the search bar. This option should automatically appear when the user clicks on the dropdown for the primary contact.
![image](https://cloud.githubusercontent.com/assets/1286381/16962230/9623e0f8-4da5-11e6-813b-cea74a688cd6.png)

**Comment by garethbowen** [comment]
I couldn't find a way to add it as a list item, so I added a separate button beside the label which does it. Not the best UI but we really have our hands tied here...

**Comment by SCdF** [comment]
Is this just my eyes being crazy, or is it not aligned properly?
![image](https://cloud.githubusercontent.com/assets/583851/17171356/44d22e0a-53e8-11e6-867c-4ec79f365851.png)
It doesn't look like it fits in the UI correctly, that it's a little too high.

Apart from that, all good!

**Comment by alxndrsn** [comment]
Looks like 1 pixel too high:

<img width="672" alt="screen shot 2016-07-27 at 11 57 09" src="https://cloud.githubusercontent.com/assets/191496/17171512/4a71e040-53f1-11e6-99b7-71293819589b.png">

**Comment by garethbowen** [comment]
Depends on your browser.

![alignment](https://cloud.githubusercontent.com/assets/2064938/17171552/473f951c-5445-11e6-9a76-eba3062cca5c.png)

**Comment by sglangevin** [comment]
Working well on v2.8.0
