### ISSUE TITLE
I crashed my browser

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2517]
i was afk for a while, and I came back to the update notification and clicked _Update_.

Page constantly tries to refresh itself, then gets in a tizz because `User must reauthenticate`:

<img width="1280" alt="screen shot 2016-07-20 at 11 39 24" src="https://cloud.githubusercontent.com/assets/191496/16982160/b350f084-4e6e-11e6-9bf9-bbfbd5ddbda3.png">

**Comment by garethbowen** [comment]
I guess you cleared it, but it'd be useful to see what the response body looks like. It's probably doing something like redirecting to the login page and returning that when JSON is expected.

**Comment by alxndrsn** [comment]
The browser was unresponsive, so I could not get more information.

**Comment by garethbowen** [comment]
I've found a similar bug with probably the same cause. My replication is failing:

```
angular.js:13708 SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
...
```

This is caused by `_bulk_docs` being redirected to the login page...

```
Request URL:http://localhost:5988/medic/_bulk_docs
  Request Method:POST
  Status Code:301 Moved Permanently
  Location:/medic/login?redirect=%2Fmedic%2F_bulk_docs

Request URL:http://localhost:5988/medic/login?redirect=%2Fmedic%2F_bulk_docs
  Request Method:GET
  Status Code:302 Found
```

This is caused by the audit proxy returning unauthorized. I'm investigating further...

**Comment by garethbowen** [comment]
My "bug" was caused by the user having insufficient permissions to update docs.

Firstly, I think this was caused by editing the user which wiped out a bunch of fields including their type.

Secondly, when api is about to report an error we should investigate if the request wants JSON (ie: `Accept: application/json` header) and respond with an error in JSON instead of a redirect to the login page which errors confusingly and crashes browsers...

**Comment by garethbowen** [comment]
Thirdly, it would be even more betterer to avoid the error in the first place by checking permissions before initiating the replication request.

**Comment by garethbowen** [comment]
I've split off the user editing portion of this to #2539

**Comment by garethbowen** [comment]
I'm not 100% sure that I fixed the same issue that @alxndrsn found but we can reopen or open another issue if this happens again.
