### ISSUE TITLE
Errors error in extract-person-contacts migration script

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2520]
Happens because the errors that are being created contain references to the very objects that couldn't be accessed and generated the error creation.

**Comment by SCdF** [comment]
PR is here: https://github.com/medic/medic-api/pull/89

**Comment by alxndrsn** [comment]
d'oh!

**Comment by SCdF** [comment]
@alxndrsn I don't think you meant to close this? The linked code is a PR, with a specific question about whether or not changing existing migrations are OK, which AFAICT has not been answered.

**Comment by alxndrsn** [comment]
d'oh!
