### ISSUE TITLE
Rewrite the couch2pg portion of medic-analytics in TypeScript

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2524]
TypeScript may be worthwhile. It may not be. If we ever move to Angular 2 our main framework will be written in it.

In #2499 we want to split the couch2pg section out into a generic publishable model, `medic/couch2pg`. Concurrently to this we could consider rewriting the code (which is not particularly large) in TypeScript. This could be a useful experiment, and help us understand what the pros and cons are of TypeScript.

Things to think about:
- Does the process of converting JS to TS find bugs?
- Does it allow us to use generative testing (see: QuickCheck and clones) in a useful way?
- How much of a pita is it to integrate with libraries that are not written in TS (e.g. PouchDB / underscore)
- Do we often fall back on the `Any` type, which IMO renders the experience somewhat pointless (I may be misunderstanding)

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
@SCdF how would you like to proceed with this issue?

**Comment by SCdF** [comment]
I would proceed by closing it :-)

I really want to do this, but it is very much in the spirit of At Some Point™, is covered by the tech debt document, and has no place as a github ticket
