### ISSUE TITLE
On upgrade, was asked to choose my language

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2527]
On upgrading from 0.4 to 2.x, the language selection modal is displayed on first login, despite having logged in previously on 0.4.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
The modal should only show if the user language isn't set. It's possible this user dismissed the set language modal when shown originally and so was prompted again. They will be prompted every load until they set a language. I think this is probably ok.

@abbyad Did you notice this happening during your upgrade testing? Are we ok with prompting users to select a language every load until they pick one?

**Comment by abbyad** [comment]
Doesn't seem unreasonable to ask until they pick it.
