### ISSUE TITLE
On upgrade, setup wizard is displayed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2528]
For an `admin` user who has previously logged in to 0.4, on first login after upgrade to 2.x, the setup wizard modal is displayed, even asking to configure a modem.

**Comment by garethbowen** [comment]
That may be reasonable if there's new information we'd like to gather.

**Comment by alxndrsn** [comment]
@garethbowen I'm surprised it would be shown at all for non-DIY projects.

**Comment by garethbowen** [comment]
@alxndrsn Fair enough. Currently we don't have a flag to say "diy" or "not-diy". But that wizard could be helpful in first run even for non-diy. It's supposed to get the critical information required for all installations. It very well may need a refresh though...

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Nobody has complained about this and the 0.4-2.x upgrades are basically complete so this shouldn't be an issue any more. Reopen if I'm wrong!
