### ISSUE TITLE
There is no link to medic-reporter in 2.x

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2529]
On a server with `medic-reporter` installed and visible in dashboard, there is no in-app link to `medic-reporter`.  It can be accessed directly at `/medic-reporter/_design/medic-reporter/_rewrite`.

**Comment by estellecomment** [comment]
From discussion in https://github.com/medic/medic-webapp/issues/2457, we should add a link to it in Configuration pages somewhere.

**Comment by alxndrsn** [comment]
There's no obvious place to put this link in configurations.  I will put the link in the hamburger/hotdog menu, where it should only be visible for users with the correct permission.

**Comment by estellecomment** [comment]
I don't see a permission linked to it?

Not convinced by the hamburger menu. All the Tech Lead / admin stuff is in Configuration, so I don't think adding one-off elements to the hamburger menu is a good organisation, it'll end up cluttered. 

How's this : 
![screen shot 2016-08-11 at 11 12 05](https://cloud.githubusercontent.com/assets/911434/17584143/4a229484-5fb5-11e6-885b-ad7f5813a397.png)

**Comment by alxndrsn** [comment]
> I don't see a permission linked to it?

I haven't finished yet?

> How's this:

Yes perfect - I'll go with that.

**Comment by alxndrsn** [comment]
I've created a new ticket for sorting out the layout: #2633

**Comment by estellecomment** [comment]
cool!

**Comment by abbyad** [comment]
_Looks_ good in v2.9:

![image](https://cloud.githubusercontent.com/assets/789512/18605761/5f6fad7e-7c69-11e6-83b3-212b27925fd1.png)

But with the [URL set](https://diy.dev.medicmobile.org/medic-reporter/_design/medic-reporter/_rewrite) it gets stuck on this:
![image](https://cloud.githubusercontent.com/assets/789512/18605767/87f21a8e-7c69-11e6-9435-560bf75ff381.png)

**Works however if you add a [trailing slash](https://diy.dev.medicmobile.org/medic-reporter/_design/medic-reporter/_rewrite/)!**

**Comment by estellecomment** [comment]
LGTM!
