### ISSUE TITLE
Send button doesn't work in messages modal

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2533]
Could be related to #2531 and could / should be dealt with in #2500.

When you try to use the send message modal against a contact that is just a phone number:

![image](https://cloud.githubusercontent.com/assets/583851/17022745/a0132986-4f47-11e6-8a21-95f949f9ea23.png)

Nothing happens, except you get the following errors and warnings in the console:

![image](https://cloud.githubusercontent.com/assets/583851/17022758/b116c0e4-4f47-11e6-81b3-7a9efcf87d3b.png)

**Comment by SCdF** [comment]
FWIW: the warning declares that the facility service is being used in a "legacy" way, where to work out who to actually send this message to it must load every single contact in existence. Which is obviously horrible for admins.

**Comment by alxndrsn** [comment]
Related: #2536

**Comment by alxndrsn** [comment]
Works when sending to a known contact.

**Comment by alxndrsn** [comment]
Current behaviour:

1. to a know contact, modal seems to work fine
2. an unknown contact, modal looks like it worked, but message never appears in _Messages_

**Comment by alxndrsn** [comment]
Feels a bit bizarre that we have to cater for so many different options in `mapRecipients()`.

**Comment by SCdF** [comment]
Choice chips. I'm going to raise something about fixing the code so we don't get that warning as well, in case it gets forgotten.

**Comment by abbyad** [comment]
Worked in v2.9, moving to Ready
