### ISSUE TITLE
sentinel duplicate views

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2534]
This view is probably a duplicate of something in the main ddoc.  I'm wondering if I should do a quick audit of sentinel's views and see if we can use views from the `medic` ddoc instead.  It also emits docs which is wasteful.  The query should use `include_docs` instead.

In designs/lib/views.js:

```
exports.person_by_phone = {
    map: function (doc) {
        if (doc.type === 'person') {
            emit([doc.phone], doc);
        }
    }
};
```

**Comment by garethbowen** [comment]
Is this ready for code review? Should it be assigned to someone?

**Comment by mandric** [comment]
Yeap should have assigned it.

**Comment by mandric** [comment]
Also will probably be part of a bigger sentinel views refactor/consolidation #2537

**Comment by garethbowen** [comment]
Looks good.
