### ISSUE TITLE
medic-api doesn't seem to correctly expose all pending messages

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2535]
Steps to reproduce:

Sent in two registrations (the ones in [the user guide](http://medicmobile.org/assets/downloads/Medic-Mobile-users-guide-ANC_v4.pdf)) using curl. This creates two pending SMS messages:
```
$ curl -s "http://admin:pass@localhost:5988/api/v1/messages?state=pending" | jq
[
  {
    "message": "Thank you for registering Jane. Their pregnancy ID is 22550, and EDD is Sun, Apr 2nd, 2017",
    "to": "+447765902019",
    "id": "0163fe14-cda6-4000-94b0-02a1f904192e",
    "state": "pending",
    "state_history": [
      {
        "state": "pending",
        "timestamp": "2016-07-20T17:04:36.551Z"
      }
    ],
    "_record_id": "5601e25b8a333337f168beedb2001914",
    "_record_reported_date": 1469027346891
  },
  {
    "message": "Thank you  for registering Janet. Pregnancy ID is 91601.",
    "to": "+447765902019",
    "id": "8099f9dc-19e0-4826-b198-690143c68101",
    "state": "pending",
    "state_history": [
      {
        "state": "pending",
        "timestamp": "2016-07-21T10:59:48.178Z"
      }
    ],
    "_record_id": "5601e25b8a333337f168beedb202f328",
    "_record_reported_date": 1469098787950
  }
]
```

I used `synthetic_date` to advance the date to after one of the report's scheduled tasks, so it now looks like this:
![image](https://cloud.githubusercontent.com/assets/583851/17027377/87780f22-4f5b-11e6-925c-8e79611515f0.png)

As I understand it, I should now have three messages when I call the messages api, but I still only have the above two.

**Comment by SCdF** [comment]
This is because the `messages` under `scheduled_tasks` do not have a `uuid` value, while tasks, which is correctly represented in the view, does:

![image](https://cloud.githubusercontent.com/assets/583851/17053456/f72490ea-4ff9-11e6-878a-82ad435423a3.png)

**Comment by SCdF** [comment]
Hey @mandric, take a look at the above commit. With these changes scheduled messages which have been moved to pending show up in the view medic-gateway etc use.

**Comment by alxndrsn** [comment]
LGTM.  Is this likely to be creating problems in current 0.4 projects?

**Comment by mandric** [comment]
I doubt it's creating problems in 0.4 projects because: 

- 0.4 projects don't use /api/v1/records 
- smssync doesn't expect or use message uuids atm
- pretty sure the view is different and doesn't require uuids
- if scheduled messages were stuck in pending state forever we'd know about it
