### ISSUE TITLE
Cannot send messages to unknown numbers

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2536]
From the _Messages_ tab, it's possible to send a message to an existing contact.  But if you reply to a message from a phone number which is not associated with a contact, then `formatRecipients()` filters out the recipient's number.

**Comment by SCdF** [comment]
Hey @alxndrsn there should probably be a test for this right?

**Comment by SCdF** [comment]
Hey @alxndrsn if I run that test without your code change (ie `git co be61484 -- static/js/services/send-message.js && grunt karma:unit` it still passes, so I don't think it's testing what it should be.

**Comment by alxndrsn** [comment]
Fails for me with the old code:
```
  SendMessage service
    ✓ create doc for one recipient
    ✗ create doc for non-contact recipient
	AssertionError: expected 0 to equal 1
	    at tests/karma/unit/services/send-message.js:88:38
	    at _fulfilled (tests/karma/q.js:834:54)
	    at self.promiseDispatch.done (tests/karma/q.js:863:30)
	    at Promise.promise.promiseDispatch (tests/karma/q.js:796:13)
	    at tests/karma/q.js:604:44
	    at runSingle (tests/karma/q.js:137:13)
	    at MessagePort.flush (tests/karma/q.js:125:13)
```

**Comment by SCdF** [comment]
OK there is clearly something going on with my dev env.

**Comment by abbyad** [comment]
Works on v2.9, moving to Ready
