### ISSUE TITLE
Editing your own user settings wipes out security settings

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2539]
If you go to `/configuration/user` and click Edit User Profile, then don't change anything and hit save, you will then have trouble replicating from the server, eg:

> Error fetching sync options - using with minimum options Error: No district assigned to district admin.

If you check the user-settings object for your user you'll noticed the contact, facility, and roles fields have been wiped.

**Comment by SCdF** [comment]
Looks good. Out of interest: which mechanism prevents a user from editing their permissions? Something in api or couchdb or?

**Comment by garethbowen** [comment]
Security critical information (facility id and permissions) are stored in the _users db as well as the medic db. The information is in the medic db so we can replicate it locally and show different parts of the UI depending on what the user is permitted to do. We cannot stop users changing data in their own pouchdb so theoretically they could make themselves full access users and see the full UI.

However they cannot access or modify their information in the _users db and that's the one we use for validating permissions on the server.
