### ISSUE TITLE
medic-webapp sending message issue

### ISSUE THREAD

**Issue by waqar-ah** [medic/medic-webapp#2544]
i am using medic-webapp with **SMSsync app** for sending and receiving messages... i am able to receive messages and messages are showing in medic-webapp inbox but when i send message it always be in pending state and nothing happens...

and **medic-gateway** is not connecting with medic-webapp showing error

`URL is not responding in the expected way`

URL which i am using in Both apps is:

`http://admin:pass@localhost:5988/medic/_design/medic/_rewrite/add`

Please is there any documentation which guides me with the procedures of sending messages... and reporting process.

  @estellecomment @SCdF

**Comment by garethbowen** [comment]
medic-gateway is documented here: https://github.com/medic/medic-gateway . It looks like you need to reconfigure the URL in medic-gateway.

**Comment by waqar-ah** [comment]
Thanks for the replay , The medic-gateway Document was updated with link after i posted this issue , so its resolved now. Sorry for not closing the issue .. most of the documents are not complete to understand the complete working of medic-webapp.. i am trying strugling to understand it Thanks Again . How to Close this Issue?

**Comment by garethbowen** [comment]
Documentation is definitely something that needs more attention. We have a few ideas in the works which will hopefully make this easier in future.
