### ISSUE TITLE
Send message uses a badly performing API

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2547]
![image](https://cloud.githubusercontent.com/assets/583851/17061400/3b720030-5026-11e6-8b50-f1db4899efe6.png)

It should not rely on this old way of doing things to load people, because it requires downloading all contacts of type person, just to send an SMS.

**Comment by waqar-ah** [comment]
its a week now i am facing this problem

**Comment by mandric** [comment]
What is the API call?

**Comment by waqar-ah** [comment]
when i click on send message option it displays this message and forms appears when i fill and send that form message goes to pending state and never sent... how message sending works what is the Procedure .. so that i can track the code

**Comment by SCdF** [comment]
Hi @waqar-ah, the main branch (master) is currently in transition, merging functionality from the old`0.4` into the newer `2.x` releases. 2.x previously did not need any form of SMS support, so the messages tab has been broken for awhile. It will be fixed in the coming weeks, as we make sure that existing 0.4 setups work correctly in the newer codebase.

**Comment by alxndrsn** [comment]
Last stable `0.4` release is tagged at https://github.com/medic/medic-webapp/tree/0.4.12.

**Comment by waqar-ah** [comment]
ok Thanks waiting for the new release

**Comment by SCdF** [comment]
Hey @garethbowen a code review for you. The linked code above is in a branch I probably won't merge until all the various todos are fixed, which will be under #2263.

**Comment by garethbowen** [comment]
Nice cleanup. A few minor comments inline.

It looks incomplete like some uses of send message will no longer work. Is this intentional?

**Comment by SCdF** [comment]
Yeah it's intentional. Like I said I won't merge it until other things are done (which should be today hopefully), I just wanted someone to look at it separately to everything else.

**Comment by SCdF** [comment]
Blocked on #2500, can be moved to acceptance testing once that one is.
