### ISSUE TITLE
By default gateway users don't have the can_access_gateway_api permission

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2549]
Steps:
 - Created a completely fresh DB
 - Imported 0.4 diy config (probably not required to replicate this)
 - Created a new user of type gateway
 - This user didn't have the correct gateway permissions

**Comment by alxndrsn** [comment]
Not a regression.

**Comment by garethbowen** [comment]
I think the import overwrites the defaults.

**Comment by waqar-ah** [comment]
i am facing this error on both gateway user and reporter user:

`Error fetching sync options - using with minimum options Error: The administrator needs to give you additional privileges to use this site`

Page Shows 404 Error and no menu displays

**Comment by alxndrsn** [comment]
@waqar-ah please file a separate issue at https://github.com/medic/medic-webapp/issues/new

**Comment by waqar-ah** [comment]
reported

**Comment by SCdF** [comment]
Yep that looks to be the case. I'll make sure the gateway user has the right permissions in the diy config.

**Comment by SCdF** [comment]
Hey @garethbowen  check out : https://github.com/medic/medic-projects/pull/566

As well as the permission fix noted above.

For me working through this raises the question of how we deal with this kind of merging now? For example, how does this scenario play out:
 - We setup client Foo
 - We then make some permissions changing to client Foo due to their requirements (1)
 - We add a new permission and update webapp to support that
 - client Foo upgrades to the new webapp version (2)
 - client Foo then makes *more* permissions changes (3)

Do we have a consistent way of dealing with the interactions between 1, 2 and 3?: For example, is (1) lost when we upgrade to (2), or vice versa (ie permission changes aren't applied in upgrades)?

**Comment by garethbowen** [comment]
Your changes look good. No we don't have a nice way of dealing with your scenario. Currently administrators have to add the new permission manually. This is usually ok because usually it's for a new feature that they may not want to switch on right away anyway.

If we're changing permissions (eg: renaming) or similar we should probably write api migration scripts to handle it.

**Comment by SCdF** [comment]
@abbyad would @ngaruko acceptance test this against the `medic-projects/diy` config, or is that no longer relevant, and would he be checking the new `standard` config?

**Comment by sglangevin** [comment]
I think it would be great to check against the new `standard` config which can be found here: https://github.com/medic/medic-projects/tree/master/default-sms-workflow/standard

**Comment by ngaruko** [comment]
Is a 'gateway user' able to login standard.app @sglangevin @SCdF ? ie from the UI: https://standard.app.medicmobile.org/medic/login?,  like any any other user? I am trying this and getting errors: 
![image](https://user-images.githubusercontent.com/6979995/28289697-b6af1520-6b97-11e7-9b45-82be868c6d71.png)

**Comment by garethbowen** [comment]
@ngaruko No, the gateway user is just for API access, not for UI access.

**Comment by ngaruko** [comment]
Thanks @garethbowen

**Comment by ngaruko** [comment]
Is this A/Testable from my end @sglangevin ?

**Comment by sglangevin** [comment]
If I had to guess, I would create a `gateway` user then check the Permissions page to ensure that user has the `can_access_gateway_api` permission.

@SCdF created this issue so he'd be the one to advise further.
