### ISSUE TITLE
Error sending messages

### ISSUE THREAD

**Issue by waqar-ah** [medic/medic-webapp#2551]
When i try to send SMS from medic-webapp using medic-gateway it shows Errors:

`TypeError: Cannot read property 'push' of undefined`
`Error fetching contact conversation TypeError: Cannot read property 'push' of undefined`

and on the medic-gateway side it shows:

`Failed to save WO message` in event Logs

is this a Bug or i am doing something wrong?

**Comment by SCdF** [comment]
Hi @waqar-ah, there isn't too much to go on here. Do note that the code in `master` probably does not work well with SMS right now, and will be fixed in the coming weeks.

**Comment by waqar-ah** [comment]
Thanks for the response ... tracking **medic-webapp** issues for the resolve...

**Comment by garethbowen** [comment]
@waqar-ah I think there are two problems here. I think I can track down the TypeError issue. I'm not sure about the medic-gateway issue.

Could you please raise a separate issue for that one and try and gather more information?

**Comment by garethbowen** [comment]
I've created #2588 to cover the TypeError.

Thanks for reporting these issues!
