### ISSUE TITLE
gateway user and reporter user errors

### ISSUE THREAD

**Issue by waqar-ah** [medic/medic-webapp#2552]
i am facing this error on both gateway user and reporter user:

`Error fetching sync options - using with minimum options Error: The administrator needs to give you additional privileges to use this site`

Page Shows 404 Error and no menu displays

**Comment by alxndrsn** [comment]
Are you seeing the same error for admin users?  Can you share a screenshot of the error in context?

**Comment by waqar-ah** [comment]
no its not showing user with full access .  its showing with  gateway user and reporter user  ... screenshot attached
![screenshot from 2016-07-25 14-51-54](https://cloud.githubusercontent.com/assets/19934353/17097472/604d321e-5277-11e6-80c4-9947c1f4be4f.png)

**Comment by alxndrsn** [comment]
I suspect this behaviour is expected - reporter and gateway users are meant to access the app through the API rather than the GUI.

**Comment by waqar-ah** [comment]
ok, its not the biggest concern for me right now. closing the issue
