### ISSUE TITLE
Analytics location/clinic selector looks awful

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2553]
# 2.x

<img width="1280" alt="screen shot 2016-07-25 at 12 32 42" src="https://cloud.githubusercontent.com/assets/191496/17098698/1df851b8-5264-11e6-8a29-8b5bf3cd6738.png">

# 0.4

<img width="376" alt="screen shot 2016-07-25 at 12 35 02" src="https://cloud.githubusercontent.com/assets/191496/17098719/3b528328-5264-11e6-9081-8cae08ffa99f.png">

**Comment by garethbowen** [comment]
### Code review

PR: https://github.com/medic/medic-webapp/pull/2637

I've reworked the filters as below. I've also added carets so it's clear when something is expandable. Finally I added more routes to fix the back button #2565
