### ISSUE TITLE
Analytics screen has no information on it

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2554]
<img width="1280" alt="screen shot 2016-07-25 at 12 37 11" src="https://cloud.githubusercontent.com/assets/191496/17098819/b9a524c4-5264-11e6-8c5c-051212395ebf.png">

**Comment by alxndrsn** [comment]
The code throwing this exception is at https://github.com/medic/medic-webapp/blob/master/static/js/controllers/analytics-stock.js#L174, which seems unsurprising – [from the pouch docs, the result of `DB().query()` should be of the form](https://pouchdb.com/api.html#query_database): 
```
{
  "rows": ...
  ...
}
```
i.e. no mention of `.results` at all.

**Comment by alxndrsn** [comment]
Possibly caused by switching from `DbView()` to `DB().query()`

**Comment by alxndrsn** [comment]
Data is now displayed!

**Comment by SCdF** [comment]
Just one question for Mr. @alxndrsn

**Comment by SCdF** [comment]
lgtm
