### ISSUE TITLE
Cannot choose one of the analytics modules in 2.x

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2556]
In 0.4, I had two analytics modules available:

<img width="249" alt="screen shot 2016-07-25 at 13 04 51" src="https://cloud.githubusercontent.com/assets/191496/17099403/65b0fb8c-5268-11e6-8006-0974a57db12e.png">

In 2.x, there is now no option to choose which module I use - it is fixed to VPD:

<img width="204" alt="screen shot 2016-07-25 at 13 05 24" src="https://cloud.githubusercontent.com/assets/191496/17099410/784fe2e4-5268-11e6-886a-5c2b00483ab0.png">

**Comment by estellecomment** [comment]
Can you navigate to it by URL? Is it just the dropdown option missing?

**Comment by alxndrsn** [comment]
From discussion with @bishwas-medic it looks like the bug is actually in 0.4 - _VPD Weekly Report_ should never have been shown in _Analytics_ in the first place.
