### ISSUE TITLE
Analytics page should not show menu if there is only one module

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2557]
# Observed

<img src="https://cloud.githubusercontent.com/assets/191496/17061266/f5dc0658-502d-11e6-952c-65128e7d760c.png"/>

# Expected

If there is only one analytics module, we should be taken directly to that module instead of being shown a choice.

# Workaround

The problem seems to be resolved by enabling and then disabling _Targets_ via `/medic/_design/medic/_rewrite/#/configuration/targets`.

**Comment by garethbowen** [comment]
I managed to reproduce this by loading the analytics page which redirected me to the module then hitting the back button took me to this page.

**Comment by ngaruko** [comment]
UI has changed.
