### ISSUE TITLE
If build fails first time, it won't be available for install from Dashboard unless whole matrix is re-run

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2558]
E.g. [travis#3683](https://travis-ci.org/medic/medic-webapp/builds/147163796) failed on Node 0.12 first time round.  I triggered a rebuild, which passed OK, but I don't see the build available in Dashboard:

<img width="939" alt="screen shot 2016-07-25 at 14 07 38" src="https://cloud.githubusercontent.com/assets/191496/17100813/30240fb4-5271-11e6-8eec-bd648aafbe28.png">

**Comment by alxndrsn** [comment]
N.B. I have since restarted this build in the hope that it will upload the build to Dashboard.

**Comment by alxndrsn** [comment]
Re-running the entire build sorted this out.

**Comment by garethbowen** [comment]
@alxndrsn I'm not sure what we can do about that - raise an issue against travis?

**Comment by alxndrsn** [comment]
Might be the answer.  Is the problem that Travis does not execute the `after_success` step except when all builds pass _when run together_?

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
Pretty sure @garethbowen has this in his sights with travis build stages.

**Comment by garethbowen** [comment]
I'm not sure how build stages will work. I don't think this is high priority for us. @alxndrsn If this is still an issue either raise an issue against travis or explore build stages as a potential workaround.

**Comment by alxndrsn** [comment]
This is almost certainly still an issue, but not high priority.
