### ISSUE TITLE
Analytics stock widget breaks on error

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2561]
If there is an error loading data, this is not presented to the user.  Instead they just see a broken data screen:

<img width="1280" alt="screen shot 2016-07-25 at 12 37 11" src="https://cloud.githubusercontent.com/assets/191496/17098819/b9a524c4-5264-11e6-8c5c-051212395ebf.png">

**Comment by alxndrsn** [comment]
Related: #2560

**Comment by garethbowen** [comment]
Nice one. Added a few style comments.

**Comment by alxndrsn** [comment]
I think the changes you suggest have value, but are unrelated to this ticket.  I will make the changes in https://github.com/medic/medic-webapp/issues/2592
