### ISSUE TITLE
stock widget shows time-period selecter before a place has been selected

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2564]
<img width="716" alt="screen shot 2016-07-25 at 16 52 06" src="https://cloud.githubusercontent.com/assets/191496/17105660/6f5f29a4-5288-11e6-97cc-390720990cb8.png">

**Comment by garethbowen** [comment]
I assume this is the relevant commit? https://github.com/medic/medic-webapp/commit/6382751a108a723b284777821e8e592163115ad2

Don't forget to include the issue number in commit messages...

**Comment by garethbowen** [comment]
Looks good.
