### ISSUE TITLE
Back button is broken on analytics stock widget

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2565]
# Observed 

After browsing to the analytics stock widget and selecting a place, pressing the browser back button take you to the previously-viewed tab, or even off medic mobile completely (if that was the previous history item).

# Expected 

I would expect the browser button to return to the place-selection screen from the report screen.  This expectation might change if the place selection becomes a drop-down again as it was in 0.4.

**Comment by garethbowen** [comment]
To be reviewed with: #2637

**Comment by ngaruko** [comment]
LGTM
