### ISSUE TITLE
No loader shown when loading locations on Analytics Stock widget

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2566]
# Observed

On browsing to the Stock Monitoring widget, there is a noticeable lag while different parts of the sceen load:

## 1
<img width="521" alt="screen shot 2016-07-25 at 17 01 36" src="https://cloud.githubusercontent.com/assets/191496/17105926/8d9e930e-5289-11e6-987d-851ed670b0c8.png">

## 2
<img width="523" alt="screen shot 2016-07-25 at 17 01 42" src="https://cloud.githubusercontent.com/assets/191496/17105927/8d9f812e-5289-11e6-98fb-80277a6109ac.png">

## 3
<img width="484" alt="screen shot 2016-07-25 at 17 01 46" src="https://cloud.githubusercontent.com/assets/191496/17105974/b0ca7fdc-5289-11e6-87e3-e556a5ded53a.png">

-----

# Related

* #2564
* https://github.com/medic/medic-webapp/issues/2559
* https://github.com/medic/medic-webapp/issues/2560

**Comment by garethbowen** [comment]
Looks good.
