### ISSUE TITLE
Add datestamps to medic-analytics logging

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2567]
We use loglevel, and there is a plugin that will allow us to add datestamps at the front, which would be swell. It would also mean we can get rid of some parts of log messages where we log out the date.

**Comment by mandric** [comment]
Fwiw this is how we do it in [sentinel](https://github.com/medic/medic-sentinel/blob/master/lib/logger.js).

**Comment by SCdF** [comment]
I opted to just add ts logging using the existing framework instead of moving to winston, since winston has nothing we need, it was really easy to add ts logging to loglevel, and it's only logging.

**Comment by mandric** [comment]
Cool.  Just a minor question on the commit...

**Comment by SCdF** [comment]
Fixed the erroneous parameter.
