### ISSUE TITLE
Muso: Data Import Procedure

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2568]
Determine if any changes to `medic-webapp` or `medic-api` are needed to satisfy the requirements of https://github.com/medic/medic-projects/issues/562. If so, create a checklist below. If not, follow https://github.com/medic/medic-projects/issues/562 and close this when it completes.

**Comment by mandric** [comment]
@browndav when is this due?  And do we have the data to import?

**Comment by sglangevin** [comment]
@mandric by the end of this iteration (August 19th) we should have a script ready based on the sample data in https://github.com/medic/medic-projects/issues/562. I am available to answer any questions you have about what needs to be imported. Let's follow up on this when you are back.

**Comment by mandric** [comment]
Ok this should be ready for review see PR: https://github.com/medic/medic-import/issues/7
What looks like PII has been replaced with fake data.

**Comment by garethbowen** [comment]
Mostly looks good. The setTimeout() stuff looks like a bug but I might be reading it wrong.

**Comment by garethbowen** [comment]
@mandric Back to you.

**Comment by garethbowen** [comment]
If this is in acceptance testing is should be closed.

**Comment by ngaruko** [comment]
Is this testable on any instance or is it only for Muso Project? @mandric @sglangevin .

**Comment by mandric** [comment]
Testing this issue would involve testing the import-contacts project template in https://github.com/medic/medic-bulk-utils/ which is somewhat technical still (probably best tested by a tech lead).

**Comment by ngaruko** [comment]
Hi @henokgetachew . Are you able to test this one and confirm that it is working as expected?
