### ISSUE TITLE
Store the doc transition status in a separate doc

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2569]
Currently we store the status of transitions in the doc (as noted in #2521), but this causes performance issues with users having to replicate docs when the change is useless to them. It also makes the docs prone to conflict.

Store this information in a separate doc.

Related: #2418

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
Scheduling!

**Comment by SCdF** [comment]
I duped it with #3423 , closing this as that has more info against it.
