### ISSUE TITLE
Fix twilio_message transition to retry on error

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2570]
Currently an error marks the doc as being transitioned (as noted in #2521). If the twilio server is unavailable that means the messages from this doc will never be sent, unless the doc is modified later on.

Modify the twilio_message transition to retry when an error occurs.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
@sglangevin @madric Do you know if this transition is used anywhere? I can't see [any uses in medic-projects](https://github.com/medic/medic-projects/search?utf8=%E2%9C%93&q=twilio_message).

Are we actually supporting this?

**Comment by sglangevin** [comment]
Not that I know of. As far as I know, we don't support Twilio. @abbyad @mandric?

**Comment by abbyad** [comment]
The only project that would have used it is done, and we don't seem to have any active projects using it. Can it be useful for sending messages via other SMS aggregators?

**Comment by estellecomment** [comment]
Alright. So what I think makes most sense is removing the transition since it's not used. 
@abbyad It's a simple enough piece of code, basically calling the twilio api, so we can resurrect it easily (or rewrite if necessary) when needed.

Closing this, and opening another to remove the transition.
