### ISSUE TITLE
Garden market release notes are in wrong order

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2571]
Looks like it can't cope with ordering `0.4` vs `2.x`, or it sorts by date:

<img width="579" alt="screen shot 2016-07-26 at 12 52 12" src="https://cloud.githubusercontent.com/assets/191496/17135386/d6f0846c-532f-11e6-9ad2-744b48c08c99.png">

Either way, I'm not sure 0.4 and 2.x builds should both be available on this server so it's a little confusing!

**Comment by garethbowen** [comment]
It just loads the changes doc: https://github.com/medic/medic-webapp/blob/master/Changes.md

We can define it in any order we like.

**Comment by alxndrsn** [comment]
Presumably the 0.4 release doesn't exist on the 2.x branch and vice versa, so perhaps that file should only contain relevant releases.

**Comment by alxndrsn** [comment]
Any objection to the release notes only relating to the current branch?

**Comment by garethbowen** [comment]
@alxndrsn Dashboard fetches this information straight from GitHub, as that's the only way to get the information for the new version without actually downloading everything yet. AFAICT Dashboard doesn't know which branch the release was built on, so it can't just fetch the Changes.md for `0.4.x` or whatever. However it does know the version number so it could look at the tag of `0.4.12` and fall back to `master` if not found. That would then work for us and anyone else following our tagging pattern. This would be a small change to dashboard.

Alternatively, we could attach the Changes.md to the ddoc, have Dashboard download the entire app before displaying this screen, and then pull the Changes.md out of the ddoc and display that. This would be a large change to dashboard.

The third option is to wait until we replace dashboard (maybe this year?) and do something different at that point.

**Comment by alxndrsn** [comment]
I like option 3.
