### ISSUE TITLE
No title shown for analytics stock table

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2573]
# Observed

<img width="1169" alt="screen shot 2016-07-25 at 16 35 48" src="https://cloud.githubusercontent.com/assets/191496/17105069/ed43f82a-5285-11e6-8913-6528197325e0.png">

# Expected

<img width="1174" alt="screen shot 2016-07-25 at 16 36 38" src="https://cloud.githubusercontent.com/assets/191496/17105109/0f165ac4-5286-11e6-8a19-7743c77d4696.png">

**Comment by garethbowen** [comment]
@alxndrsn It's unclear what's missing here. Are you talking about the labels on the big numbers, or the "show reports from" bit at the bottom of the expected screenshot, or the column titles on the expected screenshot? Or all of the above?

**Comment by garethbowen** [comment]
I added titles to the columns and someone else had already added labels to the icons. If this wasn't what you meant please assign back.

**Comment by garethbowen** [comment]
Commit: https://github.com/medic/medic-webapp/commit/dcff08cd329c5d14e42c9396bf1da624dca53ff8 (dsylixa strikes again).
