### ISSUE TITLE
Rename "stock" widget to "reporting rates"

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2574]
_Reporting Rates_ seems to be a more generic name for the _Stock Monitoring_ analytics widget.  In `0.4` it was called _Reporting Rates_ and found at `/analytics/reporting`, but in `2.x` it is not called _Stock Monitoring_ and it found at `/analytics/stock`.  It seems like the old name is more suitable and should be reverted.

**Comment by alxndrsn** [comment]
@mandric @abbyad any ideas which name is correct?

**Comment by abbyad** [comment]
I don't know where "stock" came from. We have generally only referred to this as "reporting rates" in the past. Some of the monthly or weekly forms could be stock reports, but often are service reports too.

I would stick to the more generic _Reporting Rates_ until we officially decide to change it.

**Comment by alxndrsn** [comment]
PR @ https://github.com/medic/medic-webapp/pull/2579

**Comment by garethbowen** [comment]
One comment regarding modifying translation keys and values. Otherwise all good.

**Comment by alxndrsn** [comment]
Confirm translations are properly deleted before closing this.

**Comment by alxndrsn** [comment]
@abbyad I need your help deleting relevant translations from POE.

**Comment by abbyad** [comment]
4 deleted with `analytics.stock.*`
1 deleted with `Stock\ Monitoring`

**Comment by abbyad** [comment]
Assigning to @bishwas-medic for Acceptance Testing.
