### ISSUE TITLE
Missing "district" selector in Reporting rates Analytics in v2.x

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#2575]
The older version of webapp had a dropdown menu with the list of "districts" that was useful for quickly switching to different "districts".
<img width="740" alt="screen shot 2016-07-27 at 4 51 43 pm" src="https://cloud.githubusercontent.com/assets/13689284/17173465/c0bde360-541a-11e6-8890-78ea67b85808.png">

This will be a better option UX wise instead of putting a back button.

**Comment by abbyad** [comment]
This may be related to a previous discussion on https://github.com/medic/medic-webapp/issues/1030#issuecomment-134804149

**Comment by alxndrsn** [comment]
Very related - thanks @abbyad

Are we deliberately avoiding the drop-downs as per this screenshot, or should we just be re-implementing the same?

<img src="https://cloud.githubusercontent.com/assets/789512/9209538/0d090ffa-4045-11e5-9007-249020483ce7.png"/>

**Comment by garethbowen** [comment]
Fixed as part of #2553

Now it looks a little different but should function the same.

![reporting-rates-updated](https://cloud.githubusercontent.com/assets/2064938/17843039/92013c08-687d-11e6-89ff-96a30442ac18.png)

**Comment by mandric** [comment]
I actually liked the index of districts on a separate page as opposed to a dropdown because then (in the year 3000) we can add pies of all the districts so you could see more "birds eye view" and drill into problematic regions.

**Comment by garethbowen** [comment]
We can cross that bridge when we come to it.

**Comment by ngaruko** [comment]
'select district' option available. Thanks @bishwas-medic
