### ISSUE TITLE
Missing option to change time unit in reporting rate analytics

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#2576]
Option to change the time unit to week/month/quarter/year is missing in the v2.x version of the webapp.

Screenshot of the feature in the older version:
<img width="1120" alt="screen shot 2016-07-27 at 4 51 00 pm" src="https://cloud.githubusercontent.com/assets/13689284/17173742/547eb7fe-541c-11e6-84d1-7366b92d8778.png">

**Comment by alxndrsn** [comment]
@bishwas-medic i'd noticed this too, but assumed it was meant to be an improvement - the new UI shows 5 otions from 1 month to 5 years. 

It would be good to get feedback on what is actually recommended here rather than blindly reverting to the old functionality.

**Comment by bishwas-medic** [comment]
Giving the option to users to select the unit would be better in my opinion. And since this project follows weekly reporting format...weekly denomination, which is missing right now, is a must. 

Bigger year denomination like "3 years", "5 years" may not be required though. This was recommended by the partner officials in a meeting last week. Also, IIRC the old functionality was built specifically for this particular project 3 years back.

**Comment by mandric** [comment]
There's still bugs for weekly reports. #2429 is one that should be ported and I'm working on.

**Comment by alxndrsn** [comment]
@mandric related tickets all seem to be closed, so it looks like this is the one to follow for getting this working in 2.x

**Comment by mandric** [comment]
Yes there is quite a bit lacking in the 2.x UI.

@garethbowen I believe you did the first round of the built-in analytics (reporting rates) refactor for 2.x.  Do you have any opinion about where this time unit select dropdown should go in 2.x.  Should we just  follow along with how 0.4 looks, filling in the gaps?  Including the filters in the top bar?  Other thoughts?

![screen shot 2016-07-28 at 9 02 21 pm](https://cloud.githubusercontent.com/assets/25641/17233497/b39468ac-5506-11e6-84fa-19900100d446.png)
![screen shot 2016-07-28 at 9 06 21 pm](https://cloud.githubusercontent.com/assets/25641/17233564/340779d4-5507-11e6-8408-70dc3f80d17b.png)

**Comment by garethbowen** [comment]
It should go right beside the "last 1 month" | "last 3 months" bit just like in 0.4. I don't think we should spend much time on design but just make sure it's functionally equivalent and correct. Pretty can come later.

**Comment by garethbowen** [comment]
Added a couple of comments.

**Comment by mandric** [comment]
Code Review Round 2...

**Comment by garethbowen** [comment]
@mandric I'm confused - that commit looks identical to the first one?

**Comment by mandric** [comment]
Look at the PR.

**Comment by garethbowen** [comment]
Ahh thanks!

**Comment by garethbowen** [comment]
Awesome work! Merge when ready.

**Comment by ngaruko** [comment]
'change time unit ' now available. Thanks @bishwas-medic
