### ISSUE TITLE
Sort out Reporting Rates/Stock analytics CSS

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2578]
Old styles were in `static/css/kujua-reporting.less`, but these were not properly tied to the current DOM structure.  Those styles mostly should be resurrected, and the DOM may need changing, e.g. to put tabular data in `<table>`s.

Related: #2577

**Comment by alxndrsn** [comment]
N.B. style changes may have been made to make the stock/reporting rates screens more mobile-friendly.

**Comment by garethbowen** [comment]
I think the styles have been copied over where appropriate but really as the HTML has had a significant rewrite (for mobile friendliness) most of the styles needed to be rewritten too.

If there are specific stylistic concerns with the current UI we should raise specific issues to fix them, but I couldn't find anything salvageable in the old styles.
