### ISSUE TITLE
Once viewing a stock report, clicking the area name makes area stats disappear

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2580]
# Steps to recreate

1. open analytics tab
1. choose stock report (if not already selected)
6. choose a facility
3. click on the facility's name/stats at the bottom of the screen
1. observe that the facility has disappeared

**Comment by alxndrsn** [comment]
Wow this does make the thing disappear, but since #2572 you can tell that the app is fetching data, and if you wait a while then a crazy list of facilities appears!  Not sure what this is meant to mean, but each can expand to show a list of months like this:

<img width="602" alt="screen shot 2016-07-27 at 16 38 40" src="https://cloud.githubusercontent.com/assets/191496/17179210/a6fb793a-5418-11e6-89bd-a3325db945b7.png">

**Comment by garethbowen** [comment]
It's a breakdown of how many reports have been received for each of those months. It would make more sense if more than zero reports had been received...

**Comment by garethbowen** [comment]
This should be more sensible now that we have loading spinners and carets.
