### ISSUE TITLE
Upgrade to tough-cookie >=2.3.x

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2582]
When running `npm install`:
```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

Not sure yet where this dependency comes from, may be easy or hard to upgrade.

**Comment by SCdF** [comment]
(priority IMO, though depending on who uses it and how it may not be)

**Comment by SCdF** [comment]
```
$ npm ls tough-cookie
medic@2.8.0 /Users/scdf/Code/Medic/medic-webapp
├─┬ angular-pouchdb@4.3.0
│ └─┬ pouchdb@5.4.0
│   └─┬ websql@0.4.4
│     └─┬ sqlite3@3.1.4
│       └─┬ node-pre-gyp@0.6.28
│         └─┬ request@2.72.0
│           └── tough-cookie@2.2.2
├─┬ grunt-couch@1.5.1
│ └─┬ request@2.70.0
│   └── tough-cookie@2.2.2
└─┬ karma@1.1.2
  └─┬ chokidar@1.4.3
    └─┬ fsevents@1.0.14
      └─┬ node-pre-gyp@0.6.29
        └─┬ request@2.73.0
          └── tough-cookie@2.2.2
```

**Comment by SCdF** [comment]
`request@2.74.0` and above has the correct package.

It's weird that `angular-pouchdb` uses the full `pouchdb` package, and not `pouchdb-browser` (not that it helps us if they did, tough-cookie is also used by that package).

@garethbowen what are your thoughts? How horrible is it to just edit `npm-shrinkwrap` to have the newer version of request in it (or just the newer version of tough-cookie)? Or fork all the things? Or just ignore it?

**Comment by garethbowen** [comment]
I don't like the idea of editing npm-shrinkwrap because the edit will get overwritten silently by npm. We could set it as a build task.

I don't like forking either for obvious reasons.

Another option is to explicitly depend on the updated version but that won't work in this case because our dependencys' dependencies are too locked down so won't accept the 2.3.0 version required to resolve this issue. If only they'd pushed a 2.2.3 instead...

I think the correct thing to do here is to raise an issue and submit a PR.

Then we need to assess the risk. I'm not too concerned about webapp dependencies because it's authenticated access only. It'd be good to check api as it's exposed to the public.... FWIW:

```
~/src/medic/medic-api$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by garethbowen** [comment]
The minimatch warning will be fixed in the next release of jshint: https://github.com/jshint/jshint/commit/05d7a317f910e2565f079df544030c87512cdd58

Then we need to get grunt-contrib-jshint to use that release and we're golden...

**Comment by SCdF** [comment]
@garethbowen does that mean for the minmatch issue it's all dev-side anyway? (ie if it's part of jshint and grunt then that's not exposed on the server anyway right?)

**Comment by garethbowen** [comment]
Good point regarding dev dependencies. Not an issue...

**Comment by SCdF** [comment]
So this is no longer a priority, looking at it with my eyes this time, none of those dependencies are actually used in production (two of them are dev dependencies, and the other is under sqlite which we don't use)

**Comment by SCdF** [comment]
I will still raise tickets / PRs with the various packages though, but it is not urgent

**Comment by SCdF** [comment]
FWIW we're also getting the minimatch warning in medic-webapp, which is lousy with its dependency. They are mostly dev side though, and the only unpatched one I'm aware of is again under pouchdb->sqlite, which we shouldn't be executing.

**Comment by SCdF** [comment]
So I took a crack at changing angular-pouchdb to use pouchdb-browser instead of pouchdb. The way they have their tests setup is not something I'm too familiar with and I couldn't get it working with my changes, but I've spent enough time on it so I'm dropping it. AFAICT none of the bad stuff actually makes it into production anyway, so it's not a big deal.

**Comment by SCdF** [comment]
Closing because it's not enough of a priority to solve via either shrinkwrap or mass forking.

**Comment by garethbowen** [comment]
@SCdF Can you link to any issues in other repos so we can track them from here?

**Comment by SCdF** [comment]
I only raised one, https://github.com/angular-pouchdb/angular-pouchdb/issues/106, about using pouchdb-browser instead of pouchdb.

When I actually went to raise issues about upgrading request to 2.74, it seemed like a lot of effort for something that doesn't look to be a security issue for us:
 - Raise that dependency N use request 2.74
 - Wait until there is a release, and then raise that dependency N-1 use N'
 - Wait until there is a release, and then raise that dependency N-2 use N-1'
 - and so on
