### ISSUE TITLE
Sort out roles

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2583]
Our implementation of roles is complicated. In the UI we only allow configurers to pick one role for a user. Then behind the scenes we [map this to an array of roles](https://github.com/medic/medic-webapp/blob/master/static/js/controllers/edit-user.js#L48) and store that instead. Then, each of these roles maps to a set of permissions.

Instead, store a single role for the user which maps to a set of permissions.

As part of this refactor update the set of available roles with better names.
- "full access"/"national-manager" should be "admin" (or similar) and probably shouldn't be configurable: https://github.com/medic/medic-webapp/issues/2079
- "district-manager" should be "regional-manager" (or similar) as they can operate at any level of the hierarchy.
- "facility-manager" should be removed and existing users migrated to "regional-manager"
- all references to "kujua" should be removed.

Ensure all changes have a migration for existing users both in the _users db and the medic db.

**Comment by diannakane** [comment]
There's an issue for this in #2368 and initial work done by @sglangevin @abbyad and I. It's being bundled within our "manager views" milestones which we will begin design work on this quarter, so will be revisited soon. 

Requirements are being explored here: https://docs.google.com/a/medicmobile.org/spreadsheets/d/1_3jOJaNyFoNYlkR22V22sWmAmBI5II4iCBHenYb5SgE/edit?usp=sharing

**Comment by mandric** [comment]
Having default roles is good, but also envision a screen allowing you to define your own roles. Then permissions screen includes those new role strings you created and lets you assign permissions.  The result gets saved to app_settings.roles_permissions_map or something and then can be used in the frontend/backend like `user.hasPermission('can_configure`)` and that function would check the new permissions map setting.

**Comment by garethbowen** [comment]
I think #2368 and adding configurable roles are out of scope for this issue. All we need to accomplish in the short term is fixing the many to many relationship of roles. This is purely technical debt.

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
This was already triaged before. I'm not sure if this is still worth doing before we invest more time into our roles and permissions next year. @garethbowen what do you think? Feel free to close if you think this will be achieved by the work we are planning around permissions.

**Comment by sglangevin** [comment]
We'll be getting to work on this shortly. I've added a priority tag in the meantime.

**Comment by garethbowen** [comment]
This has been fixed as part of #4525

**Comment by ngaruko** [comment]
see #4525
