### ISSUE TITLE
TypeError on Messages tab

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2588]
@waqar-ah reports:

When i try to send SMS from medic-webapp using medic-gateway it shows Errors:

```
TypeError: Cannot read property 'push' of undefined
Error fetching contact conversation TypeError: Cannot read property 'push' of undefined
```

**Comment by garethbowen** [comment]
I think this error has to be coming from https://github.com/medic/medic-webapp/blob/master/static/js/services/message-contacts.js#L25-L35 but I can't see how.

@waqar-ah Can you provide a little more information? What browser are you using? What version of medic-webapp are you running? Can you get any more of the stack trace?

It would be great if you could find the line of code that was creating this error, and possibly debug to find what parameters it's been given. If the code is minified you can use the pretty print option in chrome to make it slightly more readable.

**Comment by waqar-ah** [comment]
OK.. i will look to it more deeply and update here

**Comment by waqar-ah** [comment]
Error While Sending Message, message status " Scheduled "  

![screenshot from 2016-08-02 13-59-10](https://cloud.githubusercontent.com/assets/19934353/17322976/818bf76a-58b9-11e6-9e8a-5b408353e512.png)

**Comment by garethbowen** [comment]
@waqar-ah Thanks for that stacktrace - it should be fixed now. It's possible it was a timing bug my commit fixes it, but I think it's more likely there's some other bug that caused it to get into an inconsistent state. It would be great if you could update to the latest commit and see if that resolves your issue or just exposes the real problem.

**Comment by waqar-ah** [comment]
I will update and test it

**Comment by SCdF** [comment]
LGTM

**Comment by garethbowen** [comment]
@waqar-ah We're in the process of setting up a Slack channel for providing better support to external contributors. It'd be great to hear about your project and see how we can help, but I can't find any contact information for you. If you'd like an invite to our Slack channel please send your email address to: gareth@medicmobile.org

**Comment by garethbowen** [comment]
For acceptance testing make sure you can create messages on the Messages tab.
