### ISSUE TITLE
Reduce lg.app server size

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2589]
Now that lg.app is stable in terms of CPU load, let's reduce the server size since we don't need as large of a server to handle the new way of replication. Assigning to Dave, who can probably add more info. Ideally we would make this change on Monday so that we can assess through next week.

**Comment by browndav** [comment]
Instance size cut in half on Monday, August 1st, 2016. Reassess next iteration using performance data to see if further reductions are necessary.

**Comment by sglangevin** [comment]
No AT needed. This was reduced a while back and is working fine. Moving to ready.
