### ISSUE TITLE
medic-webapp takes a long time to start on Chrome 53.0.2785.34 beta (64-bit)

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2594]
Chrome.

When loading or reloading medic-webapp the app sits and the loading animation for a long time while Chrome pegs a CPU. 

Could just be my computer, could be something has changed in master recently.

**Comment by SCdF** [comment]
So this is slow for me in Chrome, but not in Chromium or Firefox. It's not clear what it's doing: I'm thinking it's a bug in Chrome (I am on the Chrome dev channel).

@alxndrsn / @estellecomment you're both on OSX: do you have this problem with the code in master?

**Comment by alxndrsn** [comment]
No problem here (Chrome 51)

**Comment by SCdF** [comment]
FWIW I'm on 53.0.2785.34 beta (64-bit).

**Comment by garethbowen** [comment]
@SCdF Based on your Chrome version alone it could be related to this: https://github.com/nolanlawson/pouchdb-authentication/issues/111

Although we don't use pouchdb-authentiation it looks like it's caused by an underlying couchdb bug.

**Comment by SCdF** [comment]
It's not a couchdb issue I don't think, the issue still happens (as either admin or restricted) against localhost when couch / api is not running.

**Comment by SCdF** [comment]
Huh, it looks like the issue doesn't occur me in PROD, so that suggests either my chrome is broken for a particular URL / localhost, or it's a code change we've introduced?

Also:
 - The pause is not waiting for a request or any kind of data, Chrome actually often complains that the page is unresponsive, and the Chrome pegs a CPU, so it makes me think it's runaway JS
 - Here is a CouchDB log, annotated by me as to where the pause occurred:
```
[info] [<0.667.0>] 127.0.0.1 - - GET /medic04/_design/medic/static/dist/manifest.appcache 304
... the big wait... 
[info] [<0.711.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.666.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.668.0>] 127.0.0.1 - - GET / 200
[info] [<0.669.0>] 127.0.0.1 - - GET /medic04/6850E77F-5FFC-9B01-8D5B-3D6E33DFA73E? 404
[info] [<0.672.0>] 127.0.0.1 - - GET /medic04/_local/m9JYAhZUJupgnMsz2FsnVw%3D%3D? 200
[info] [<0.673.0>] 127.0.0.1 - - GET /medic04/_local/m9JYAhZUJupgnMsz2FsnVw%3D%3D? 304
[info] [<0.671.0>] 127.0.0.1 - - GET / 200
[info] [<0.670.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.675.0>] 127.0.0.1 - - GET /_users/org.couchdb.user:demo 200
[info] [<0.677.0>] 127.0.0.1 - - GET /medic04/_local/GzI4QNg5VcZKJw_S1.ddDQ%3D%3D? 200
[info] [<0.680.0>] 127.0.0.1 - - POST /medic04/_bulk_docs 201
[info] [<0.681.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.679.0>] 127.0.0.1 - - GET /_users/org.couchdb.user:demo 200
[info] [<0.678.0>] 127.0.0.1 - - POST /medic04/_design/medic-client/_view/doc_by_place 200
[info] [<0.676.0>] 127.0.0.1 - - POST /medic04/_changes?style=all_docs&heartbeat=10000&since=246&limit=100&filter=_doc_ids 200
[info] [<0.674.0>] 127.0.0.1 - - GET /medic04/_local/GzI4QNg5VcZKJw_S1.ddDQ%3D%3D? 304
[info] [<0.753.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.754.0>] 127.0.0.1 - - GET /_users/org.couchdb.user:demo 200
[info] [<0.755.0>] 127.0.0.1 - - POST /medic04/_bulk_docs 201
[info] [<0.757.0>] 127.0.0.1 - - GET /_session 200
[info] [<0.756.0>] 127.0.0.1 - - GET /medic04/ 200
[info] [<0.758.0>] 127.0.0.1 - - GET /_users/org.couchdb.user:demo 200
[info] [<0.759.0>] 127.0.0.1 - - POST /medic04/_design/medic-client/_view/doc_by_place 200
[info] [<0.760.0>] 127.0.0.1 - - POST /medic04/_changes?style=all_docs&heartbeat=10000&since=246&feed=longpoll&limit=100&filter=_doc_ids 200
```
After saying I don't think it's couchdb (and it still breaks without couchdb running, so it can't _really_ be that), that log does look weird, especially around where it's trying to GET a session. Note the timestamps.

**Comment by SCdF** [comment]
![image](https://cloud.githubusercontent.com/assets/583851/17331526/3a6f1588-58c3-11e6-9b77-25f88102f1c5.png)

Something to do with fonts maybe?

**Comment by SCdF** [comment]
It may be a case of some pathologically bad parsing of inbox.js? I tried creating a test HTML page that just imports inbox.js and nothing else:
 - In Chrome is pegs a CPU for a long time (though not as long as a real install would I think), and then errors out due to illegal characters in some d3 stuff
 - In Firefox it *instantly* errors out at the same place as Chrome does.

I'm not sure why it's erroring, since the identical file should be used when loading normally, and neither Chrome nor Firefox have issues loading it in that instance. For specificity, here is the bad line:
```js
var ε = 1e-6, ε2 = ε * ε, π = Math.PI, τ = 2 * π, τε = τ - ε, halfπ = π / 2, d3_radians = π / 180, d3_degrees = 180 / π;
```
It specifically doesn't like π = Math.PI, though it's not clear why.

**Comment by SCdF** [comment]
I'm dumb, it's because I didn't set my charset to utf8!

**Comment by SCdF** [comment]
OK so now I fixed the charset issue, what I did was put this file in the dist dir, and hosted it with `python -m SimpleHTTPServer`:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Index loads test</title>
  <script type="text/javascript" src="./inbox.js"></script>
</head>
<body>
  <script type="text/javascript">
    alert('after inbox.js');
  </script>
</body>
</html>
```

On Firefox that loads near instantly. On Chrome it takes forever. If you're thinking that it's actual code that's executing: it doesn't appear to be. If you add:
```js
console.log('HELLO THERE'); alert('HELLO THERE'); throw new Error('Stop right there, thank you very much');
```
_(which logs, alerts, then **halts the execution of the script**)_

To the top of inbox.js it takes forever for Chrome to execute those as well.

**Comment by SCdF** [comment]
There is where I'm going to stop for the day I think: I currently don't have internet fast enough to jump around installing different Chrome versions. If anyone has Chrome 52 installed it would be helpful if you could do the example noted above and report back if it's fast or slow.

**Comment by SCdF** [comment]
Yay, it looks like it's fine on Chrome 52 (stable), and is just an issue with the beta. I'll install a nightly and see if they've already fixed it.

**Comment by SCdF** [comment]
Sweet, it looks to be fixed in Chrome Canary, so it was either a Chrome regression, or my install was screwed up. Regardless of which that was, consider the issue closed!
