### ISSUE TITLE
extract-person-contact migration creates self-referential data

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2595]
AFAICT the `extract-person-contact` "creates loops", and it shouldn't as per https://github.com/medic/medic-api/blob/master/migrations/extract-person-contacts.js#L41:

```
  {
    _id: 'abc',
    type: 'district_hospital',
    name: 'myfacility',
    contact: { name:'Alice', phone:'+123' },
  }
```
when migrated creates a self-referential `district_hospital`:
```
  {
    "_id": "abc",
    "type": "district_hospital",
    "name": "myfacility",
    "contact": {
      "_id": "af6aba74ae247934454faef07000b34d",
      "_rev": "1-3c8722fefca1e3d4297b659ffed176a5",
      "name": "Alice",
      "phone": "+123",
      "type": "person",
      "reported_date": 1470060870402,
      "parent": {
        "_id": "abc",
        "_rev": "2-f7f0dcaf5f58df2315a1b865816c4ceb",
        "type": "district_hospital",
        "name": "myfacility"
      }
    }
  }
```

**Comment by garethbowen** [comment]
@alxndrsn I think that's the correct behaviour. You'll notice the `contact` is missing from the `contact.parent` to avoid creating an infinite loop.

**Comment by estellecomment** [comment]
It's self-referential but not infinitely so! That's what I mean by no loops.

I.e. `districtHospital._id` and `districtHospital.contact.parent._id` are the same, but it stops there : `districtHospital.contact.parent.contact` doesn't exist.

It's unclear if that's already too much... I copied the data format in LG and BRAC, to avoid breaking existing UIs. 
Agree that it's kinda weird, but storing related entities in docs is kinda weird in the first place, so I left it at that.

**Comment by alxndrsn** [comment]
Thanks for the background - I guess the fix is to update the documentation in the migration to be clearer about what "no loops" actually means.

**Comment by alxndrsn** [comment]
PR for review at https://github.com/medic/medic-api/pull/94

**Comment by estellecomment** [comment]
👍
