### ISSUE TITLE
Audit views, remove ones that aren't being used, consolidate where possible

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2596]
There seems to be a lot of views that aren't used by the code, or are perhaps very similar to others that are also being used. Views aren't free, so we should remove ones that aren't being used, and consolidate where possible.

FWIW I'm going to be checking usages in webapp, api, sentinel and data. If there are other repos or usages then I guess we'll find out later…

**Comment by SCdF** [comment]
So I've deleted a bunch of views. We're also going to use this opportunity to rename views for consistency. Looking at what we have now:

```
_design/medic
  delivery_reports_by_district_and_code
  delivery_reports_by_year_month_and_code
  data_records_by_year_month_form_facility
  visits_by_district_and_patient
  data_records
  usage_stats_by_year_month
  data_records_by_district
  facility_by_phone
  clinic_by_phone
  clinic_by_refid
  tasks_messages
  tasks_pending
  duplicate_form_submissions
  facilities_by_parent
  due_tasks
  sent_reminders
  registered_patients
  data_records_by_form_year_week_clinic_id_and_reported_date
  data_records_by_form_year_month_clinic_id_and_reported_date
  data_records_by_form_and_clinic

_design/medic-client
  contacts_by_freetext
  contacts_by_name
  contacts_by_place
  contacts_by_type
  contacts_by_type_freetext
  data_records_by_contact
  data_records_by_form_year_month_facility
  data_records_by_form_year_week_facility
  data_records_read_by_type
  doc_by_place
  doc_by_type
  doc_summaries_by_id
  facilities
  facilities_by_contact
  facility_by_parent
  feedback
  forms
  help_pages
  person_by_phone
  reports_by_date
  reports_by_form
  reports_by_freetext
  reports_by_place
  reports_by_subject
  reports_by_validity
  reports_by_verification
  total_clinics_by_facility
```

Renaming that I think we want to do, as I understand it:
 - drop the use of `facility` or `faciliites`
 - `contacts` (or change to `contact`?) for emitting all contact types (`[ 'district_hospital', 'health_center', 'clinic', 'person' ]`)
 - `person` (or `people`?) for just the `person` type
 - `place` for contacts that are not people

Additionally, I've found that `reports` and `data_records` seem to be confused:
 - `reports` always means `doc.type == 'data_record' && doc.form` (ie xml form)
 - `data_record` _sometimes_ means a data_record *without* a form (eg `data_records_by_contact`), and sometimes *with* a form (`data_records_by_form_year_(month|week)_facility`), or *sometimes either* (eg `data_records_read_by_type`, where type here is actually whether or not `form` exists)

We should probably decide a naming scheme for that as well. My proposal off the top of my head would be:
 - `data_record` is any doc with that type
 - `report` is an instance of an xmlform, thus a data_record with a form object
 - `message` is a data_record without a form

But I'm not really sure that makes sense either. Thoughts?

**Comment by SCdF** [comment]
On to renaming. 
Renaming that I think we want to do, as I understand it:
 - drop the use of `facility` or `faciliites`
 - `contacts` (or change to `contact`?) for emitting all contact types (`[ 'district_hospital', 'health_center', 'clinic', 'person' ]`)
 - `person` (or `people`?) for just the `person` type
 - `place` for contacts that are not people

Additionally, I've found that `reports` and `data_records` seem to be confused:
 - `reports` always means `doc.type == 'data_record' && doc.form` (ie xml form)
 - `data_record` _sometimes_ means a data_record *without* a form (eg `data_records_by_contact`), and sometimes *with* a form (`data_records_by_form_year_(month|week)_facility`), or *sometimes either* (eg `data_records_read_by_type`, where type here is actually whether or not `form` exists)

We should probably decide a naming scheme for that as well. My proposal off the top of my head would be:
 - `data_record` is any doc with that type
 - `report` is an instance of an xmlform, thus a data_record with a form object
 - `message` is a data_record without a form

But I'm not really sure that makes sense either. Thoughts?

**Comment by SCdF** [comment]
Ongoing PR: https://github.com/medic/medic-webapp/pull/2599

**Comment by SCdF** [comment]
@garethbowen handing over to you just to confirm naming so I only have to do it once. We can talk your morning / my night (if I have internet at home, which I may not)

**Comment by mandric** [comment]
Yes, this makes perfect sense to me and follows along with what's published in [medic-api](https://github.com/medic/medic-api).  Also `data_record.form` can be any form (xmlform or jsonform), when it's an xmlform there is an additional property `content_type: 'xml'`, otherwise it's a JSON form.

**Comment by estellecomment** [comment]
I'd vote for avoiding `report`, it's more of a UI term, and using `xml_data_records`

**Comment by garethbowen** [comment]
`report` is a term used throughout the system to denote a doc that is bound to a form, either JSON or XML, so I'd keep using it here.

**Comment by SCdF** [comment]
Another thing to consider while we're here is plurals: many of them use plurals (eg reports_by_date), but some do not (eg doc_by_type).

IMO we should remove plurals, what do you people think?

**Comment by SCdF** [comment]
I've presumed a lack of plurals in my changes, but I haven't made note of ones where just a plural changes. If we want to rename to remove plurals there will be lots more, but they're clear just from reading the name.

_design/medic existing | changes to
-----------------------|-----------
delivery_reports_by_district_and_code |
delivery_reports_by_year_month_and_code |
data_records_by_year_month_form_facility | data_records_by_year_month_form_place
visits_by_district_and_patient |
data_records | data_records
usage_stats_by_year_month |
data_records_by_district |
facility_by_phone | place_by_phone
clinic_by_phone |
clinic_by_refid |
tasks_messages |
tasks_pending |
duplicate_form_submissions |
facilities_by_parent | place_by_type_parent_id_name
due_tasks |
sent_reminders |
registered_patients |
data_records_by_form_year_week_clinic_id_and_reported_date | report_by_form_year_week_clinic_id_reported_date
data_records_by_form_year_month_clinic_id_and_reported_date | report_by_form_year_month_clinic_id_reported_date
data_records_by_form_and_clinic | report_by_form_and_clinic

_design/medic-client existing | changes to
------------------------------|----------------
contacts_by_freetext | 
contacts_by_name | contact_by_ordered_name
contacts_by_place | 
contacts_by_type | 
contacts_by_type_freetext | 
data_records_by_contact | message_by_contact_date
data_records_by_form_year_month_facility | report_by_form_year_month_places
data_records_by_form_year_week_facility | report_by_form_year_week_places
data_records_read_by_type | data_record_read_by_user_type_district_hospital
doc_by_place | 
doc_by_type | 
doc_summaries_by_id | 
facilities | contact_by_type !!
facilities_by_contact | place_by_contact
facility_by_parent | contact_by_parent_name_type
feedback | 
forms | 
help_pages | 
person_by_phone | 
reports_by_date | 
reports_by_form | 
reports_by_freetext | 
reports_by_place | 
reports_by_subject | 
reports_by_validity | 
reports_by_verification | 
total_clinics_by_facility | ??

Regarding !! it's clear we need to think about this naming scheme more: two views with the same keys but different data outputs.
Regarding ?? I'm not sure if the reduce should be taken into account or not re: total

**Comment by garethbowen** [comment]
I'm happy with plurals. Really I'm on the fence, but making fewer changes sways me.

**Comment by alxndrsn** [comment]
I vote for plurals, unless a view is expected to return only a single doc.

**Comment by alxndrsn** [comment]
Favourite view name: `report_by_form_year_month_clinic_id_reported_date`

**Comment by alxndrsn** [comment]
What is `total_clinics_by_facility` used for?!

**Comment by SCdF** [comment]
https://github.com/medic/medic-webapp/blob/master/static/js/services/child-facility.js#L22

**Comment by alxndrsn** [comment]
I don't understand the use of `ordered` in `contact_by_ordered_name`.

**Comment by SCdF** [comment]
After discussion, renamed `contact_by_ordered_name` to `contact_by_type_index_name`, which is hopefully clearer. It's a weird view…

**Comment by SCdF** [comment]
Relating to `facilities` being renamed to `contacts_by_type` and thus conflicting with an existing view (but with different returned values):
 - I'm pretty sure the only place that view is used is in medic-api, in [users.js#getFacilities](https://github.com/medic/medic-api/blob/master/controllers/users.js#L79)
 - That call has `include_docs:true`, and only exposes the included docs from that function, and so doesn't actually care about the view values
 - And that function is never used.

I'll delete the view and corresponding dead code.

**Comment by SCdF** [comment]
Hold on it looks like it actually is used, initially it looks like it was only used in tests. It's just confusingly written.

**Comment by SCdF** [comment]
@garethbowen , here are some PRs for you:
 - https://github.com/medic/medic-webapp/pull/2599
 - https://github.com/medic/medic-api/pull/91
 - https://github.com/medic/medic-sentinel/pull/83
 - https://github.com/medic/medic-data/pull/16

Some notes about the webapp PR:
 - You may want to check out each commit individually, as re-ordering the views in lib/views.js makes that file somewhat unreadable. I was at least polite enough to isolate the reordering to its own commit. In hindsight I should have probably made that the very last commit, or done it in a separate PR.
 - the api and sentinel submodules point to the branches in their respective codebases represented by the other PRs above. Once we merge this to master we'd want to update the api and sentinel submodules to point back to master

Also, the medic-data PR is failing right now. This is (AFAICT) because for the tests to pass all of the above code needs to be in the release, beta, alpha and diy markets. Not sure what to do about this one: could change the code so that it tries the new view and if it 404s try the old view, or could leave the tests failing until the code has made it through all of those markets.

**Comment by SCdF** [comment]
Talking to @mandric about medic-data:
![image](https://cloud.githubusercontent.com/assets/583851/17409528/9517ff68-5a67-11e6-83f9-7cc4cb3e913b.png)

So no worries about the broken build! :-)

**Comment by garethbowen** [comment]
Looks pretty good. One bug commented in the medic-webapp PR.

Through no fault of your own it's really hard to review, but I'm sure we'll find any mistakes in acceptance testing... Merge when ready.

**Comment by SCdF** [comment]
Merged.

**Comment by SCdF** [comment]
Whoops, missed one.

**Comment by SCdF** [comment]
@garethbowen I missed one!
