### ISSUE TITLE
Create migration to remove obsolete ddocs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2597]
We have recently deleted the `kujua-sentinel` and `erlang-filters` ddocs, however these won't be deleted in production. This means the views will continue to use CPU cycles even though no code executes them any more. Write a migration to remove these unneeded ddocs.

**Comment by SCdF** [comment]
Nice one!

**Comment by garethbowen** [comment]
AT: Make sure there are only two ddocs - medic and medic-client.
