### ISSUE TITLE
Android back button doesn't work as expected

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2600]
Hitting the back button always closes the app.

This error is in the console:

```
Uncaught TypeError: Cannot call method 'handleAndroidBack' of undefined
```

This comes from trying to access the angular scope the wrong way [in the android app](https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L95) as explained in #2407.

This can't be reproduced locally because angular includes additional code to allow this locally.

I'm not sure why the app closes altogether but it might be due to the unhandled exception.

Webapp version: 2.7.2
Android app version: head
Server: lg-testing

**Comment by garethbowen** [comment]
The back button integration was using `scope` which doesn't exist, which was then throwing an exception, which handed back handling back to the app, which closed the app thinking the webapp was at the top level.

#2407 solved this same problem by calling a service directly, but the code invoked here was embedded in a controller so this couldn't be done easily. I ended up pulling the code into a new service called AndroidApi which provides a backwards compatible API for the android app to invoke.

**Comment by alxndrsn** [comment]
This looks very nice 👍

**Comment by sglangevin** [comment]
This is working well in v2.8.0
