### ISSUE TITLE
Determine if AutoCompaction is working in latest code

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2603]
Discovered while debugging https://github.com/medic/medic-projects/issues/592.
A user had large amounts of data, and running compaction by hand reduced it to half the size (320MB to 143MB)
```
var db = new window.PouchDB("_pouch_medic-user-okellowa");
db.compact().then(function (info) {
  // compaction complete
  console.log('complete');
  console.log(info);
}).catch(function (err) {
  // handle errors
  console.log('error');
  console.log(err);
});
```

We should have autocompaction on : https://github.com/medic/medic-webapp/blob/master/static/js/services/db.js#L43

Related : https://github.com/medic/medic-webapp/issues/2434

**Comment by estellecomment** [comment]
If it requires a temp fix, we could add a "Compact" button on the About page (suggestion by @mandric )

**Comment by garethbowen** [comment]
It would be good to test this with the latest alpha as we updated to the latest pouchdb which fixed some bugs in this area.

**Comment by estellecomment** [comment]
Ok. The problem above was on lg.app, webapp v.2.7.2

**Comment by garethbowen** [comment]
Yeah, it would be good to test on 2.8.x

**Comment by estellecomment** [comment]
Ha. 
My 328MB of app data is now 150MB, a couple hours later, without me having done anything.

Either compaction is happening but slowly, or App Manager reports wrong app size.

**Comment by estellecomment** [comment]
(or installing storage-usage branch of medic-android compacted the data, but that seems unrelated)

**Comment by alxndrsn** [comment]
What's the status of this ticket?  From the comments it looks like it may be a non-issue.

**Comment by estellecomment** [comment]
Looks like the replication is using different params for PouchDB, which don't have autocompaction on. That explains why the data size goes back down after replication is done!
https://github.com/medic/medic-webapp/issues/2625

**Comment by alxndrsn** [comment]
Looks like this is covered more clearly by #2625
