### ISSUE TITLE
App can run out of allowed disk space, even when there's free space left on phone

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2604]
Discovered during https://github.com/medic/medic-projects/issues/592

There are space limits for offlined apps. One user with 1200 families (which is 3-4 times more than usual) hit it. 
Others may hit it later?

Looks like with our old webview, we can't request more quota. Googling results here:
https://github.com/medic/medic-projects/issues/592#issuecomment-237182409

**Comment by estellecomment** [comment]
Ran the experiment of running out of space, and then freeing space back again, logs here : https://github.com/medic/medic-projects/issues/592#issuecomment-237570399

The one thing we can do is spot the "Database connection is closing" errors, and prompt the user to do something. 
This error happens in other situations though, so you'd need to check for free space to decide if that's the problem.
But anyway I don't think I've ever seen the app recover from this error (you need to restart it), so detecting it can't hurt.

**Comment by estellecomment** [comment]
Error thrown when you go over quota!
On Chrome 51, on tecno y4, android 4. (not webview :( )
 
![screen shot 2016-08-09 at 11 23 01](https://cloud.githubusercontent.com/assets/911434/17511688/5bd6b5f8-5e24-11e6-8bdf-7d41a964a8a4.png)

**Comment by garethbowen** [comment]
@estellecomment Given that we can't increase our quota and we can't even detect errors what more is left to do on this issue?

**Comment by estellecomment** [comment]
Closing in favor of https://github.com/medic/medic-webapp/issues/2623 (testing similar things on firefox)
