### ISSUE TITLE
<deleted>

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2606]

**Comment by SCdF** [comment]
To be clear right, Y4s are still being used by CHWs right? As in, if there is a new feature in a later webview we're not able to rely on it?

**Comment by estellecomment** [comment]
Yeah, I suppose the first wave of CHPs have Y4s, and then they ran out and switched models. Something to figure out!
 - how many L5s and W3 vs. Y4? 
 - are they on android 5+ ?

**Comment by garethbowen** [comment]
@estellecomment What can the dev team to do achieve this?

**Comment by estellecomment** [comment]
nothing. Filed https://github.com/medic/medic-projects/issues/650, removing this issue.

**Comment by garethbowen** [comment]
Replaced by: https://github.com/medic/medic-projects/issues/650
