### ISSUE TITLE
Allow chrome-inspecting on prod medic-android

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2607]
We only allow chrome-inspecting the webview on debug build of medic-android : 
https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L52

This means partner's apps are not debuggable. We can't diagnose their problems. Change that.
(unless there's some security implication I'm not thinking of)

**Comment by alxndrsn** [comment]
Will this impact application performance?

**Comment by estellecomment** [comment]
Just downloaded the LG app, whose URL is on https://github.com/medic/medic-projects/issues/189
And I can debug it just fine. 
So I'm confused what that DEBUG flag is then.

**Comment by estellecomment** [comment]
Nope, was using wrong app (not sure what I did). LG prod app is not debuggable.

**Comment by estellecomment** [comment]
LGTM! Thanks!

**Comment by estellecomment** [comment]
@sglangevin will test this maybe? Check that the webview is inspectable in `chrome://inspect`

**Comment by sglangevin** [comment]
@estellecomment @alxndrsn I need to have the new version of the Android app on the Play Store for testing, though that would then push the update to all the CHPs. Perhaps someone can help me get set up to do this testing another way?

**Comment by alxndrsn** [comment]
Should be available in the app store for beta testers.  Please let me know if this is not working.

**Comment by sglangevin** [comment]
@alxndrsn I haven't seen an update available this week. Last time, @abbyad had to promote the app so that I could test it. I'd rather not side-load as that would prevent me from updating from the app store later, wouldn't it?

**Comment by estellecomment** [comment]
@ngaruko FYI, how to inspect the android app : http://medicmobile.cloud.answerhub.com/questions/177/how-to-see-console-errors-on-a-phone.html

**Comment by estellecomment** [comment]
AT : download a production android app (LG's version for instance), and check that it's debuggable/inspectable (instructions in previous post)

**Comment by ngaruko** [comment]
Do we have a demo account for production intances @estellecomment @sglangevin ?

**Comment by ngaruko** [comment]
This works on alpha.dev. Does this satisfy the requirements for this issue? 
![image](https://cloud.githubusercontent.com/assets/6979995/22909721/9c14fac8-f2ba-11e6-83e2-6cfac0d42c89.png)

**Comment by estellecomment** [comment]
Depends, was this on a phone, with a production version of medic-android? If yes, then yes!
