### ISSUE TITLE
Display "about" stats on first-load wait page

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2608]
Otherwise if you have a problem with your first load, you are stuck on the spinner, and you can't see for instance how many docs you have in DB.
Useful for debugging.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
Is this still an issue?

**Comment by estellecomment** [comment]
We now have little update messages (number of docs etc) displaying while loading, so this is fixed..
