### ISSUE TITLE
refactor medic-data

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2609]
Pretty sure most of medic-data should be replaced with sets of data that is saved in medic-projects/diy or elsewhere and imported with medic-import.  
- Some of the builds take longer than an hour to run and reach the travis limit so they fail
- Written in interest of time so lots of one-off code that can be replaced with more generic code now
- medic-sentinel, medic-api and medic-webapp have changed quite a bit since it was written, update it to use newer api calls
- Remove couchmark related code

**Comment by mandric** [comment]
After this do: https://github.com/medic/medic-webapp/issues/2621

**Comment by mandric** [comment]
Prioritize https://github.com/medic/medic-webapp/issues/2621 as much as possible.

**Comment by garethbowen** [comment]
This is not a priority to moving out of this iteration.

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
Sounds like this is a useful cleanup to keep medic-data up to date, but since medic-data is only used to create MedicOS builds it's not used much; so it's not a high priority until it breaks.
