### ISSUE TITLE
Disable Erlang support

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2611]
We no longer use it, and it's kind of a security hole.

**Comment by SCdF** [comment]
@alxndrsn as discussed.

**Comment by alxndrsn** [comment]
Glad this is in medic-projects!

**Comment by alxndrsn** [comment]
Should there be an associated change to `local.ini`?  https://wiki.apache.org/couchdb/EnableErlangViews

**Comment by SCdF** [comment]
That's exactly what this code is doing. Why yes, you *can* change local.ini via the HTTP API! WHY WOULD THAT BE A BAD IDEA!?!?!

**Comment by alxndrsn** [comment]
> Why yes, you can change local.ini via the HTTP API!

Standard webscale feature, AFAIK
