### ISSUE TITLE
Investigate using persistent storage so we can increase the available storage

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2615]
https://developer.chrome.com/apps/offline_storage#persistent

**Comment by garethbowen** [comment]
Ugh: https://github.com/nolanlawson/cordova-plugin-sqlite-2

**Comment by estellecomment** [comment]
Can you use it as Pouch backend? 

Aw crap persistent storage is just for Files API, not indexedDB :(

**Comment by garethbowen** [comment]
Yes you can use it as a Pouch backend so it would actually work. It's not recommended for the above reasons.

**Comment by estellecomment** [comment]
@garethbowen 's report : https://docs.google.com/document/d/1dvX6zalt-nqcu3-uvTh1OZyOwkvwo4lSPjZpJb39I8Q/edit#

**Comment by garethbowen** [comment]
Replaced by https://github.com/medic/medic-webapp/issues/2623
