### ISSUE TITLE
Error handling in medic-gateway

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2617]
Errors in processing messages through the sms-gateway endpoint are not reported so messages cannot be retried.

Examples:
1. If gateway submits new messages but couchdb is unavailable the error is logged but gateway isn't notified and the message is lost.
2. If gateway submits a message status update but couchdb is unavailable the error is logged but gateway isn't notified and the update is lost.
3. If api responds with a list of messages to send it also marks them as scheduled. If the connection then fails and gateway doesn't receive the list then those messages won't be returned again and will never be sent.

To solve the first two examples we need to modify the medic-gateway api so processing errors are returned so they can be resubmitted next time. We might have to include some sort of retry limit.

To solve the last example we need to include an ACK or some other way to confirm the message has been received. For example the update to scheduled could be included as an update in the next request. This opens up the possibility of sending the message twice so some careful consideration will be needed to minimise this, but given the choice it's probably better to send it twice than not at all.

**Comment by alxndrsn** [comment]
I'm confident these issues have been addressed by recent improvement work to gateway and its controller in medic-api.
