### ISSUE TITLE
Use bulk docs instead of update function for sms gateway

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2618]
In the sms gateway controller we use a couchdb update function to change the status of messages. This has to be done serially to avoid Document Update Conflicts with two update requests occurring on the same doc at the same time. This is chatty and inefficient.

Modify this to make a single bulk docs request to update all docs in a single request.

Investigate ways to share the status update code between couch and api (and sentinel?) to maintain code reuse.

**Comment by mandric** [comment]
Using bulk docs API also means something would need to pull the entire documents in, modify them and then send them back.  Wanted to note that bulk docs request should happen from medic-api not the gateway.  The bandwidth/throughput needed by the gateway needs to be minimal to support low connectivity settings.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Yes! Done!
