### ISSUE TITLE
Branch Manager is not getting forms downloaded

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2620]
A test user with BM config couldn't download forms. It may be separate from the data size issue, since it has no CHPs in the branch.

Raised in medic-projects, for LG. Follow the original issue : https://github.com/medic/medic-projects/issues/630

**Comment by garethbowen** [comment]
My guess is the forms are downloading just fine, but the form is configured not to show for this user.

**Comment by sglangevin** [comment]
See testing report on the original issue: https://github.com/medic/medic-projects/issues/630

**Comment by garethbowen** [comment]
@sglangevin From the testing report it looks like you were unable to reproduce this issue. Can we put it down to a bad/incomplete replication?

**Comment by sglangevin** [comment]
I think so - I was able to download forms successfully, though I was having issues with initial sync timing out. Even with that, I eventually was able to download everything.

**Comment by garethbowen** [comment]
Closing as replication problems (space, etc) are covered by other issues.
