### ISSUE TITLE
Always use the same pouchdb configuration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2625]
The bootstrap code connects to the local db without passing any options. This means during initial replication auto_compaction is off and the db grows larger than needed until the app starts and compaction is turned on. Getting out of sync on other options would be much more significant (eg: `storage` which would replicate to one place, then try to connect to a different one).

A possible exception is the web worker adapter as we may not want to use it during initial replication.

Use the same configuration everywhere PouchDB instances are constructed. Find a way to ensure the configuration remains consistent, maybe a unit test, or publishing the configuration as a constant, or publishing to resultant PouchDB instance so we only ever make one for local and one for remote.

**Comment by estellecomment** [comment]
@garethbowen why not use the webworker during the initial replication? Does it actually hurt? If not, it would be easier to just have the same params in both places.

**Comment by garethbowen** [comment]
Yeah I'm not sure... It's probably fine, it just won't help much because nothing else is going on during initial bootstrap. In actual fact it'll slightly hurt performance because everything we receive will have to be serialized and deserialized to go to the web worker. Also I didn't want to introduce any fragility to the first run process. But as you say the code is cleaner if we can just use the same `options` object.

Consider the options and test the performance difference when deciding on a solution.

**Comment by garethbowen** [comment]
I opted to keep the web workers solely for the app as it doesn't help us during bootstrap and may hurt us in terms of reliability and performance. Furthermore the registration code uses a couple of angular services which aren't available while bootstrapping. To keep the code in sync I'm using an angular constant which is passed to the bootstrapper and injected into the db service.

**Comment by estellecomment** [comment]
LGTM
