### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2626]
Get the browser to accept us as a PWA. This will improve the appearance of the app greatly if we decide to go with #2623

**Comment by estellecomment** [comment]
thanks!

Acceptance testing : open this from a browser on a phone (both Firefox and Chrome should work yes @garethbowen ?), and check that it looks nice.

**Comment by garethbowen** [comment]
Acceptance testing: use "add to desktop" (or similar) to add the MM icon to the desktop, and launch from that. It should appear similar to a true mobile app: no address bar, a splash screen, and the MM theme on the status bar.

**Comment by ngaruko** [comment]
LGTM. Assuming we are not supporting 'admin' on mobile as @garethbowen mentioned.
