### ISSUE TITLE
Remove empty parents migration scalability

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2629]
The remove-empty-parents db migration attempts to download all contacts including docs and then process them one by one. On a large data set I expect this will crash.

Do some sort of batching instead (`limit` and `skip`), and use bulk docs to do the insertion.

**Comment by garethbowen** [comment]
Assigning to @alxndrsn because I _think_ I saw him talk about this issue on Slack...

**Comment by alxndrsn** [comment]
Now using a temp view, similar to `migrations/convert-bad-dob-format.js`.

**Comment by alxndrsn** [comment]
No limit or skip, and no bulk update, but should now only be getting a few docs per project, instead of _ALL_ the contacts.

**Comment by garethbowen** [comment]
Can you link the commit/PR?

**Comment by garethbowen** [comment]
Original issue: #2436

**Comment by garethbowen** [comment]
One comment in the commit. Also there are a few jshint errors to fix.

**Comment by garethbowen** [comment]
I've fixed jshint to unblock `master`.

**Comment by garethbowen** [comment]
No AT required.
