### ISSUE TITLE
"Empty" user has 22MB of data, that's a lot

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2631]
Created a user, assigned it to a district with nothing in it, and to a contact.
Synced it.
`Initial sync received 573050B of data` = 560KB
Network tab says `535KB transferred`

App data in App Manager : 22.26MB. 
Edit : that's for app data only, not app itself (116KB). It's zero before you start the app.

22MB for an empty user seems like a lot.

**Comment by estellecomment** [comment]
This is run on a db with 76589 docs, 0.5GB, so a big one.

**Comment by estellecomment** [comment]
Appcache :
![screen shot 2016-08-12 at 16 34 49](https://cloud.githubusercontent.com/assets/911434/17625893/280587f2-60ab-11e6-957f-38ad8e9f8fda.png)

Add it all up : 18206.5 KB = **17.78 MB**!
16MB for inbox.js.

**Comment by estellecomment** [comment]
Then again, it's development : unminified inbox.js. 
Assuming inbox.js is 4MB (from prod server), then it's 5713.7 KB = 5.58 MB.
Run it again on prod webapp...

**Comment by garethbowen** [comment]
That (~5.5MB) seems about right. There's not much low hanging fruit here.

**Comment by garethbowen** [comment]
Using a production db I get 4MB in the appcache. This is large but acceptable IMO. The big win would be separating the admin code into a separate module as most users don't need it.

@estellecomment Do you agree that 4MB is acceptable? Can we close this now? Perhaps open a new backlog issue for some specific solution?

**Comment by estellecomment** [comment]
Yeah. Thanks for checking!
