### ISSUE TITLE
Legacy v0.4.x instances: remove socket limit in medic-api

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2632]
In https://github.com/medic/medic-api/blob/0.4.x/server.js#L31, we limit the maximum number of Express.js server sockets to 100. This proved unnecessarily low in the 2.8.x/master branch and was removed entirely, effectively making the limit infinite, which worked out okay. We never did the same for the older v0.4.x instances.

Symptom: nginx is timing out while attempting to connect to the local `medic-api` on port 5988. This repeats regularly for a while and then dies down:

```
2016/08/12 18:22:03 [error] 30226#0: *404098 upstream timed out
  (110: Connection timed out) while reading response header from upstream,
  client: 127.0.0.1, server: _, request: "GET /medic/_design/medic/_rewrite/add HTTP/1.1",
  upstream: "http://127.0.0.1:5988/medic/_design/medic/_rewrite/add", host: "localhost"
```

Theory: under heavy load, the pool of 100 sockets is exhausted and requests start getting dropped on the floor with no response.

Push an update to v0.4.x that removes `http.globalAgent.maxSockets = 100;` from the bundled Medic API, and does nothing else.

**Comment by garethbowen** [comment]
@browndav Is this happening on a specific instance?

**Comment by browndav** [comment]
It was; it came out of a minor August 12th production downtime incident (instance details in #downtime on Slack). IIRC we applied this change to `medic-api` during the `0.6.x` series IIRC but hadn't addressed the issue (or experienced the issue) on a `0.4.x` instance.

**Comment by garethbowen** [comment]
This should be left (or changed to Infinity) on Node 0.10 which defaulted to 5, but removed for Node 0.12 where the default was increased to Infinity.

**Comment by garethbowen** [comment]
@browndav Please review this change.

**Comment by garethbowen** [comment]
The relevant documentation about maxSockets: [0.10](https://nodejs.org/docs/v0.10.0/api/http.html#http_agent_maxsockets) & [0.12](https://nodejs.org/docs/v0.12.0/api/http.html#http_agent_maxsockets)

**Comment by browndav** [comment]
LGTM.
