### ISSUE TITLE
Forms Config page needs better CSS

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2633]
`/medic/_design/medic/_rewrite/#/configuration/forms` layout needs improving:

<img width="752" alt="screen shot 2016-08-13 at 17 47 18" src="https://cloud.githubusercontent.com/assets/191496/17644123/0d0130f4-617e-11e6-9a0b-a6ca5c15f7dd.png">

&

<img width="1271" alt="screen shot 2016-08-13 at 17 47 27" src="https://cloud.githubusercontent.com/assets/191496/17644120/07dee6ca-617e-11e6-9bae-605621d850ba.png">

**Comment by garethbowen** [comment]
I've added some padding and tidied some bits up to improve the appearance of the forms page:

![forms](https://cloud.githubusercontent.com/assets/2064938/18116015/4b113f2e-6f98-11e6-9a5c-5002ae86fb02.png)

@alxndrsn Is this sufficient or is there something else I'm missing?

**Comment by alxndrsn** [comment]
LGTM
