### ISSUE TITLE
Remove dead branches

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2634]
(Split off from #2410 )

@alxndrsn , please have a look here and let me know the status of these branches:

https://github.com/medic/medic-webapp/compare/master...styled-enketo-summary
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...styled-enketo-summary-or-appearance
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...splash-screen
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...no-admin-login
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...initial-sync-status-without-batch-size-change
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...firefox-upgrade
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...enketo-spike
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...better-uploads,perhaps
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2409-add-context-to-targets
- [ ] Dead
- [x] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2262
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...2167_monkeypatch
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1947
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1905
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1700_remove-help-from-app-settings
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1513-back-button
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1456-automated-geolocation-field
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1415-events-demo
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1260
- [ ] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

https://github.com/medic/medic-webapp/compare/master...1086_embed-enketo-core-with-browserify
- [x] Dead
- [ ] WIP
- [ ] Needs PR submitted
- [ ] Other, please explain

**Comment by alxndrsn** [comment]
As far as I'm concerned these branches are all ancient and can be deleted.

**Comment by garethbowen** [comment]
Done.
