### ISSUE TITLE
Remove nested contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2635]
We include the contact hierarchy in all data records and contacts. This duplicates the data which means updates don't propagate. It also means each record and contact is approximately double as big as it should be requiring more data to be replicated and more disk space on the device.

Investigate using [joins with views](http://docs.couchdb.org/en/1.6.1/couchapp/views/joins.html) to get all the required data in one query without duplicating it.

**Comment by abbyad** [comment]
Given that nested contacts are not updated when the original contact is updated, I think this is more than technical debt because users expect a change to a contact's info to be reflected in all related contacts. We should aim to get to this as early as feasible.

**Comment by sglangevin** [comment]
Related: https://github.com/medic/medic-webapp/issues/638

**Comment by sglangevin** [comment]
Related: https://github.com/medic/medic-webapp/issues/947

**Comment by garethbowen** [comment]
After talking with @sglangevin we agreed that this isn't the top priority in terms of technical debt or the top priority bug to be fixed, so I've bumped it out of this iteration. It's still important and will still be done.

**Comment by michaelkohn** [comment]
This may have some impact on analytics.  Curious what level of nesting we will be removing.

In the example below where `type = 'person'`, would we be...
(a) Removing all contents in the curly brace (just leaving the `_id`); or 
(b) Would we just be removing the element pointed at by the arrow (`{parent,parent}`)

If (b), would we remove that element altogether? Or would we replace it with the `_id` of the parent's parent?  Sorry, not sure how best to represent / explain this.

<img width="582" alt="person" src="https://cloud.githubusercontent.com/assets/10096985/24910414/5e2583da-1ed0-11e7-8b88-9837d547fe53.png">

**Comment by mandric** [comment]
Pretty sure any parent or contact properties would just be a string with a UUID in it.

**Comment by SCdF** [comment]
@michaelkohn Gareth can give the most correct answer as he's doing the work, but as I understand it we'd be effectively doing option `a`, except that the entire value of `parent` would be the id (ie not `parent: { _id: 'foo' }` but instead `parent: 'foo'`).

**Comment by garethbowen** [comment]
@michaelkohn @SCdF @mandric I'm still prototyping but I think we'll have to have a list of all ancestors, so `parents: [ "a", "b", "c", ... "x" ]`. The structure may change from this but IDs of all ancestors will be available in the doc.

**Comment by michaelkohn** [comment]
@garethbowen I recognize this is still WIP... but I'm curious what the current thinking is in terms of updates that happen higher up in the hierarchy.  So if you move a `health_center` from one `district_hospital` to another or one `clinic` to a different `health_center`, those updates would cascade down and update the `parents: [ "a", "b", "c", ... "x" ]` for all `person` docs, correct?

**Comment by garethbowen** [comment]
@michaelkohn No, unfortunately each doc will have to hold a reference to their entire hierarchy, so a report will store the IDs for its contact, its contacts parent, grandparent, etc. This is because couchdb views cannot recursively fetch other docs. Any other field will be updated automatically however.

My recommendation is that changing a hierarchy is part of a separate api that searches for and updates all affected contacts and reports. This is potentially an expensive operation, but I can't see any technical solution that's still efficient for querying.

**Comment by michaelkohn** [comment]
Thanks @garethbowen ... so without that separate API, the `parents` array on a `data_record` would always just be a snapshot of the hierarchy at the time the `data_record` was submitted.  

From what I can tell, when you transfer a CHW to a different place, the hierarchy stored on the CHW's `person` record is already getting updated properly.  This is actually more important to me than the `data_records` hierarchy because my queries always join the `contact` on the `data_record` with config data (hierarchies derived from contacts) to determine which places the CHW belongs to.

**Comment by garethbowen** [comment]
@mandric @estellecomment Would you do me the honour of review this enormous PR?

Now when creating reports instead of inlining the entire contact we just store the IDs required to hydrate the contacts later.

Primarily this means that contact information will always be up to date (with the one exception of contact hierarchies), so if a contacts phone number or name is changed then this will be reflected throughout the UI without having to update all docs.

It also means we store and transfer much less data which in turn improves database performance.

The expected contact information is stored as contact: { _id: 'a', parent: { _id: 'b' } }. This is a slightly clunky style but means the feature is backwards compatible so any existing documents that have inlined contacts will work, and the obsolete inlined data will be ignored.

I recommend reviewing in this order...

* [sentinel](https://github.com/medic/medic-sentinel/issues/132)
* [webapp](https://github.com/medic/medic-webapp/issues/3485)
* [api](https://github.com/medic/medic-api/issues/153)
* [data](https://github.com/medic/medic-data/issues/17)

**Comment by garethbowen** [comment]
Doc explaining the concept: https://docs.google.com/document/d/1cqBKCrIHQiVOzY5IX5ONQ3aUHoQ1pBD4X0NgXSNRapE/edit#

**Comment by garethbowen** [comment]
Merged! Thanks @estellecomment and @mandric for fantastic and detailed reviews. If I missed some feedback in that epic review I'm happy to change in master but I needed to merge for my sanity...

**Comment by derickl** [comment]
@garethbowen does this change affect how will be accessing nested elements from within an xform? If yes, what is the suggested way?

**Comment by sglangevin** [comment]
Yes, this will affect that. You'll be able to access any fields about the selected contact the normal way. For any fields you're using from the `parent`, you'll need to pull those field via the contact-summary and make them available to the form, the same way you'd be making any other data available to the form via contact-summary. I'm planning to write up some info about this for projects that are moving from v2.12 (or earlier) to v2.13.

**Comment by abbyad** [comment]
The lineage in the contact-summary for places and people does not work on an instance upgraded to `2.13.0-beta.4`. Normally the parent places are listed as links in the **Belongs to** field.

![image](https://user-images.githubusercontent.com/789512/29335300-2d97da54-81d8-11e7-90d7-3f20e6e27a36.png)

**Comment by sglangevin** [comment]
@abbyad I tested that and it was working in beta.3, perhaps this regressed?

**Comment by sglangevin** [comment]
You have to change the configuration of your contact-summary for it to work.

**Comment by abbyad** [comment]
Is the only change to have `return result;` instead of just `result;` at the end?

**Comment by sglangevin** [comment]
No. You also have to update the "Belongs to" field.

`label: 'contact.parent', value: lineage, filter: 'lineage'`

**Comment by abbyad** [comment]
Aha, the value of `value` changes from `contact.parent` to `lineage` . Works now. 

Is everything else sufficient acceptance tested to move back to Ready?

**Comment by sglangevin** [comment]
Yeah, I think so. I've done a fair amount of testing already and filed several bugs which have been fixed that are related to this change.

**Comment by abbyad** [comment]
Ok, closing and returning to Ready.
