### ISSUE TITLE
JavaRosa Parser should give a better error message when form definition on the web app is mismatched with the submitted message using medic collect

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#2638]
Example: the form definition in `app_settings.json` contained this:

```
      "": {
        "position": 92,
        "type": "string",
        "labels": {
          "tiny": {
            "en": ""
          },
          "short": {
            "en": ""
          },
          "description": {
            "en": ""
          }
        },
        "list": []
      }
```

The JavaRosa parser code [here](https://github.com/medic/medic-webapp/blob/64cc8074ad2811be701cc1b38a20e7d99fb2ac1a/packages/kujua-sms/views/lib/javarosa_parser.js) fails with the error:

```
 {"error":"render_error","reason":"function raised error: (new TypeError(\"vals[i] is undefined\", \"views/lib/javarosa_parser\", 53)) \nstacktrace: ([object Object],\"\",[object Object])@views/lib/javarosa_parser:53\n([object Object],(function (field, key) {if (!field.labels || !field.labels.tiny) {return;}var label = sms_utils.info.getMessage(field.labels.tiny);for (var i = 0; i < labels.length; i++) {if (labels[i].match(new RegExp(\"^\" + label + \"$\", \"i\"))) {obj[key] = vals[i].replace(/\\\\#/g, \"#\");}}}))@underscore:86\n([object Object],[object Object])@views/lib/javarosa_parser:45\n([object Object],[object Object])@views/lib/smsparser:205\n(null,[object Object])@kujua-sms/updates:276\n(null,[object Object])@kujua-sms/updates:196\n((function (doc, request) {utils.info = info.getAppInfo.call(this);req = request;if (req.form && typeof req.form.message !== \"undefined\") {return add_sms(doc, request);}return add_json(doc, request);}),null,[object Object],(function (err, res) {r = res;}))@duality/core:873\n(null,[object Object])@updates.add:1\nrunUpdate(function (doc, req) {var core = require(\"duality/core\");var fn = require(\"kujua-sms/app\").updates.add;var r;core.runUpdate.call(this, fn, doc, req, function (err, res) {r = res;});return r;},[object Object],[object Array])@/srv/software/medic-core/current/default/share/couchdb/server/main.js:961\n(function (doc, req) {var core = require(\"duality/core\");var fn = require(\"kujua-sms/app\").updates.add;var r;core.runUpdate.call(this, fn, doc, req, function (err, res) {r = res;});return r;},[object Object],[object Array])@/srv/software/medic-core/current/default/share/couchdb/server/main.js:1033\n(\"_design/medic\",[object Array],[object Array])@/srv/software/medic-core/current/default/share/couchdb/server/main.js:1517\n()@/srv/software/medic-core/current/default/share/couchdb/server/main.js:1562\n@/srv/software/medic-core/current/default/share/couchdb/server/main.js:1573\n"}
```

We should may be compare `def.fields.length` and `parts.length` and throw a `Form definition mismatch error` if the two lengths are not equal.  Since collect sends all the fields even when they are not filled in, I think this could be a good solution.  
The other option could be to check if `parts[i]` is defined before doing `vals.push(parts[i]);` [here](https://github.com/medic/medic-webapp/blob/64cc8074ad2811be701cc1b38a20e7d99fb2ac1a/packages/kujua-sms/views/lib/javarosa_parser.js#L35). As this would silently ignore the mismatch, I think I'd prefer the first approach (throwing the error).

**Comment by mandric** [comment]
Yeah I agree throwing a nicer error is an easy change and probably the right thing.

**Comment by garethbowen** [comment]
@mandric PR please: https://github.com/medic/medic-webapp/pull/2992

I went a slightly different way with this. The only way I found to reproduce the problem was if the message given had an odd number of parameters, ie: the number of labels was greater than the number of values. eg: `J1!T!one#two#odd`

I thought the best way to handle this would be to treat the missing value as `undefined` which may or may not fail validation depending on the configuration.

**Comment by mandric** [comment]
To reproduce did you try passing in empty strings as labels and values?  Just curious...  

@henokgetachew can you have a review here if you get a chance?

**Comment by garethbowen** [comment]
> To reproduce did you try passing in empty strings as labels and values?

In the def? Yeah I did. Then I read through the code and realised that specific error could only happen if the length of `labels` was greater than the length of `vals`.

**Comment by abbyad** [comment]
>  Since collect sends all the fields even when they are not filled in, I think this could be a good solution.

@henokgetachew, from my previous testing this is not true. Collect completely omits fields that are not relevant, whereas Enketo includes all fields. We had to include a special javarosa parser because of this.

**Comment by sglangevin** [comment]
@henokgetachew @mandric what is the status of this issue?

**Comment by garethbowen** [comment]
This has been sitting in code review for weeks, so I'm just going to merge it and move it to acceptance testing.

**Comment by ngaruko** [comment]
Hi @henokgetachew , are we satisfied that this issue was fixed? Can we move it to 'Ready' or do we need any AT?

**Comment by henokgetachew** [comment]
I just looked at the code change @garethbowen made and yes I'm satisfied that this solves it.  At the time this issue was filed, I simply fixed it by removing the additional node in the definition.
