### ISSUE TITLE
Branch manager appears alphabetically in Branch's contacts list

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2639]
# Observed

<img width="447" alt="screen shot 2016-08-17 at 12 57 28" src="https://cloud.githubusercontent.com/assets/191496/17734068/4f99346c-647a-11e6-80c5-428111525aad.png">

# Expected

Feels like the `.contact` for a place should be top of the list, or even listed separately.

**Comment by sglangevin** [comment]
@alxndrsn there is already a new design for this page. See #2343 for more information.

**Comment by garethbowen** [comment]
This appears to be done. Reopen if you find another example where it doesn't work.
