### ISSUE TITLE
Sometimes changes feed is told the wrong ID for user doc

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2640]
Sometimes the `doc_ids` entry for the user doc looks correct:

<img width="277" alt="screen shot 2016-08-17 at 16 15 28" src="https://cloud.githubusercontent.com/assets/191496/17739603/f7750c86-6495-11e6-9c1f-b96524d4e097.png">

Sometimes it looks like it's missing the prefix `org.couchdb.user:`:

<img width="177" alt="screen shot 2016-08-17 at 16 15 51" src="https://cloud.githubusercontent.com/assets/191496/17739602/f772e8d4-6495-11e6-8e1b-1c5cd0e09baf.png">

This seems weird!  There is no doc called `xalex` in this db:

<img width="809" alt="screen shot 2016-08-17 at 16 18 46" src="https://cloud.githubusercontent.com/assets/191496/17739729/54e6f190-6496-11e6-9cc2-bd157303dede.png">

**Comment by ngaruko** [comment]
Is there anything to AT here @alxndrsn ?

**Comment by alxndrsn** [comment]
@ngaruko doesn't look like there are clear steps to demonstrate the bug as a user, so AT is probably not useful.
