### ISSUE TITLE
Request for *ageInDays* function to use in form context

### ISSUE THREAD

**Issue by erwagasore** [medic/medic-webapp#2650]
In the past we usually only use `ageInYear` function to help us define the context expression

for example:

```javascript
{
  "place": false,
  "person": true,
  "expression": "!contact || (contact.type === 'person' && (!contact.date_of_birth && ageInYears(contact) <= 5))"
}
```

With #Muso-Mali we have contexts which require us to use days and months and we tried to use just vanilla javascript to solve the issue `(new Date() - new Date(contact.date_of_birth))/(24*60*60*1000)` but failed with `Syntax Error: Token 'Date' is unexpected, expecting [)]`.

It would be great if we have other util functions like `ageInDays` and `ageInMonths`

**Comment by abbyad** [comment]
Looks like we could add them like [ageInYears](https://github.com/medic/medic-webapp/blob/a6b15968b793835d14e96b7438f82053b959fc4a/static/js/services/xml-forms.js#L14-L25).

@garethbowen given the upcoming deployment for this project, would it be feasible to fit this in before the 2.8.0 release?

**Comment by garethbowen** [comment]
I've merged this in to 2.8.x so it'll be acceptance tested in parallel with code review.

**Comment by sglangevin** [comment]
@garethbowen for ageInDays I am getting a result that is off by one day. I put in my context a condition that `ageInDays(contact) >= 29` but the form appears for the child when they are 28 days old and disappears when they are 27 days old. Could be an issue related to how birthdates are stored vs. displayed in the app, not sure.

**Comment by garethbowen** [comment]
Details...

Henrietta DOB: `"2016-07-25"`
Form context expression: `!contact || (contact.type === 'person' && (!contact.date_of_birth || (ageInYears(contact) <= 5 && ageInDays(contact) >= 29)))`
Today's date: August 22nd (US TZ)

It's showing up as expected in NZ.

**Comment by garethbowen** [comment]
It was decided to make the ageIn functions timezone sensitive so they are consistent with the other age calculations in the app. This means that a child may be shown as 29 days old and a form shown for one user, and shown as 28 days old and the same form not shown.

**Comment by SCdF** [comment]
Tiny minor stuff, otherwise LGTM

**Comment by garethbowen** [comment]
@SCdF I don't quite follow one of your comments - we can chat about it after the standup. Closing so acceptance testing can be done.

**Comment by sglangevin** [comment]
@garethbowen tested this and it's working well now. Moving to ready.
