### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2651]

**Comment by sglangevin** [comment]
Created in the wrong repo by accident - see https://github.com/medic/medic-projects/issues/659

**Comment by garethbowen** [comment]
@sglangevin It'd be great to get a comment about why you deleted this. Could you not reproduce it? Was your phone slow for other reasons? etc. Share the knowledge!

**Comment by abbyad** [comment]
Looks like this issue was moved to another repo: https://github.com/medic/medic-projects/issues/659

**Comment by sglangevin** [comment]
Thanks @abbyad - not sure what happened, but I had a comment in here that I had moved it to another repo, that must have been removed.
