### ISSUE TITLE
trim spaces from usernames and passwords on login page

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2653]
If you submit "john " in the username box the space at the end is submitted in the POST.  We should `String.trim()` that off since it's easy on mobile devices to get junk in there.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
Seems like an easy win to include this in the current iteration and next release.

**Comment by SCdF** [comment]
Merged. NB: I'm changing the title of this ticket to reflect that we're only trimming the username, not the password. Talked to Estelle, the consensus was that while trimming usernames make sense, trimming passwords does not. Also, the specific issue here (that mobile adds junk sometimes) should not be the case in PW fields.

**Comment by SCdF** [comment]
Oh whoops, I closed this @estellecomment, didn't notice you were still assigned. Back to you :-)

**Comment by garethbowen** [comment]
@SCdF Should this now be in AT?

**Comment by SCdF** [comment]
@garethbowen sure, I moved it.
