### ISSUE TITLE
Test LG Branch Manager setup

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2654]
We need to:
 - Branch on 2.8.0
 - Take the view change in #2648 and cherry pick it in, tag as 2.9.0
 - Push that to lg-testing
 - Notify the cavalry / @sglangevin

**Comment by garethbowen** [comment]
NB: #2648 isn't ready for testing yet.

**Comment by garethbowen** [comment]
NB 2: We might try to get this in to 2.8.0 which is almost ready rather than creating a new release.

**Comment by garethbowen** [comment]
This has been included in 2.8.0 so will be tested as part of that.
