### ISSUE TITLE
Rename kujua_message to outgoing_message

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2656]
We use `kujua_message` to mean this is a message that is being sent from the app. That doesn't make sense anymore. It should be renamed to something more meaningful and obvious.

See: https://github.com/medic/medic-webapp/blob/master/static/js/services/send-message.js#L35-L36

This could break some things. @garethbowen could maybe say some interesting things about this. Or not, the ticket taker-upper may just have to investigate).

**Comment by garethbowen** [comment]
Alternatively it might make sense to change the `type` to "message" (or something) and have an `incoming:(boolean)` property. We have a lot of logic in a log of places to try and work out if a "data_record" is a report or a message and it'd be great to see it disappear!

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
This seems like something that we should do, though perhaps not immediately. @garethbowen @SCdF does this need to be prioritized and done now? Or can it wait?

**Comment by garethbowen** [comment]
It would be great to clean up our data structures but I don't think it's a top priority. We're getting by with what we have...

**Comment by SCdF** [comment]
Yeah this is an interesting one.

What do you think @garethbowen? This is the first one of these tickets where I don't clearly want it "gone", but I also don't think it should sit around as a ticket. I say this because it is unlike "it would be nice to re-write X in Y", it is more "this code is misleading / wrong, will confuse people in the future, but it currently functions". I'm tempted to suggest the possibility of a backlog again…

**Comment by garethbowen** [comment]
If we can't decide I guess just leave it in the backlog and it'll come up for triaging again next time?

**Comment by sglangevin** [comment]
I'd leave this in the backlog of tech debt and the next time you all are prioritizing tech debt you could also review things labeled tech debt and backlog?

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
I think we need to consider this as part of a wider `type` refactor. This has been added to our [technical goals doc](https://docs.google.com/document/d/1ObwEkVj3Yx_ImQ2YzMPxQeA7PDhYX8aG_coFuHm7-0Q/edit). The only thing holding us back is the enormous migration required to fix all the old data. Closing for now.
