### ISSUE TITLE
Convert send-message to new modal style

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2657]
Send message functionality currently sits like this:
 - send-message.html, the modal dialog
 - modules/send-message.js: contains logic for dealing with the modal dialog, as well as some validation logic hooks
 - services/send-message.js: takes input from the module and stores them as tasks to be sent later
 - Misc: inbox.js inits the module for the whole app, various bits of HTML have a class that means clicking that element will summon the modal

We should refactor this:
 - Using the new modal style
 - Pulling the logic that deals with display of the modal out of modules/send-message and putting it in a new controller
 - Pulling the logic that deals with validation out of modules/send-message and putting it in the service so it can be reused

**Comment by garethbowen** [comment]
Wait for #2645 - it's an even newer modal style!

**Comment by SCdF** [comment]
#2645 has been completed, this ticket can go ahead when we think it's worthwhile to do so.

**Comment by garethbowen** [comment]
Five commits to review. The first two are simple and only tangentially related, but they're things I found while working on this. The third is where the actual change is. The last two probably don't even need review.

**Comment by SCdF** [comment]
Some minor comments, otherwise looks good!
