### ISSUE TITLE
Clean up send-message.js e2e to not use browser.sleep so much

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2660]

**Comment by SCdF** [comment]
@garethbowen OK I took a crack at this. See the commit above (it's in [a branch](https://github.com/medic/medic-webapp/compare/2660_ill_sleep_when_im_dead)).

Here is where I got to:
 - Some of them could be replaced quite easily I think, though I'm not certain
 - Some of the select2 stuff is really flaky and I'm not sure what to wait for
 - Even though I'm in theory waiting for a promise to complete for `sendKeys`, I occasionally get failures because the keys aren't all sent. I have no idea why
 - The last sleep in the second two tests, I am unable to get rid of it. Even though I did it in the first one.

All in all, these tests are hopefully more correct, but they are now much more flaky. They pass maybe 50% of the time locally (hence the branch). And it's really hard to tell why.

I think a lot of it comes down to the fact that technically every single Protractor command returns a promise which we dutifully ignore, which makes the process really unintuitive. Add that it all sometimes passes and you'd need to run each test a few times with any particular change to be sure.

**Comment by SCdF** [comment]
We can talk about it at the next standup, or if you want you can take a crack at making it awesome.

**Comment by SCdF** [comment]
NB: that branch is now out of date as I've refactored that code to re-use more of its elements. When attempting this we'd need to start again from master.

**Comment by SCdF** [comment]
I cleaned up as much as I could, and the commit was squashed into the add recipient work.

**Comment by ngaruko** [comment]
Is there a need to AT this? I had a look at the 'send-message.js' e2e test file, it still has 2 x  'browser.sleep'. Ideally 'sleeps' are not a good idea in automation, but in the real world, sometimes there is nothing to 'wait for' and 'sleep' is the only option. Removing the AT tag.

**Comment by SCdF** [comment]
@ngaruko no need to AT this. If it sounds like internal dev stuff you almost certainly never need to bother.  We should really just mark them as ready ourselves.
