### ISSUE TITLE
Create API endpoint for replacing whole app_settings with new object

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2662]
Right now we have:
- an endpoint for getting app_settings:
  [GET /medic/_design/medic/_rewrite/app_settings/medic](https://github.com/garden20/app_settings#retrieve-settings)
- an endpoint for merging existing app_settings with an object, in different ways:
  [PUT /medic/_design/medic/_rewrite/update_settings/medic](https://github.com/garden20/app_settings#update-settings)

But none for replacing the whole app_settings with a new object. I suggest
PUT /medic/_design/medic/_rewrite/app_settings/medic

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
So far, the current version of replacing/merging seems to be working fine for projects. Closing for now, we can file a new issue if this is a challenge for tech leads.
