### ISSUE TITLE
`GET /medic/_design/medic/_rewrite/app_settings/medic` returns unexpected `schema`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2663]
`GET /medic/_design/medic/_rewrite/app_settings/medic` returns

```
{
  schema: { ... },
  settings: { ... }
}
```

I got surprised by this, I find it unexpected that GETing `app_settings` would also return other stuff. (it also caused a bug in e2e `utils.js` for that reason). It would be a nicer API to return only app_settings.

Note : We'd need to update all the callers of the API.

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
This is probably worth a quick discussion – I suspect that extra data is used by a caller somewhere. Moving into the current sprint; feel free to remove if we determine that no action is required.

**Comment by mandric** [comment]
It follows this API https://github.com/garden20/app_settings and it's always been that way so I'm not sure why you would expect anything else?  We should add an endpoint for settings in medic-api though and that can be designed as nicely as we like?

**Comment by mandric** [comment]
Related https://github.com/medic/medic-webapp/issues/1250

**Comment by garethbowen** [comment]
Leaving this scheduled but removing from the milestone as it doesn't fit within one of the goals.

**Comment by garethbowen** [comment]
I agree with @mandric - this isn't unexpected, it's exactly as designed. Closing as not a bug.
