### ISSUE TITLE
Document `PUT /medic/_design/medic/_rewrite/update_settings/medic`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2664]
It's tricky to understand.

**Comment by garethbowen** [comment]
What's missing in [the documentation](https://github.com/medic/medic-webapp/tree/master/packages/app-settings)?

**Comment by estellecomment** [comment]
It's not missing, it's just tricky to understand. It wasn't enough for me to get what it was doing, so I'm making it clearer.

**Comment by estellecomment** [comment]
@mandric can you review the PR please? (and merge it, I don't think I have permissions)

**Comment by mandric** [comment]
Merged!  You also might consider updating the local copy in medic-webapp since that's maintained in git.

**Comment by estellecomment** [comment]
Thanks!
