### ISSUE TITLE
Improve application performance for high-utilization CHPs

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2665]
In testing, @sglangevin has been experiencing major application performance problems with a newly-replicated set of documents from a high-performing CHP (total database size: 3430 documents). Operations that fetch data were taking on the order of 10-15 seconds, leading to lags in the UI and general un-usability.

In analysis, we noticed that `allDocs` was outperforming `query` for this IndexedDB database, which led us to a major performance problem in PouchDB's `cacheUpdateRequired` (part of a changeset that is now reverted).

Tasks:
  - [x] Get a patch in to the `v2.8.x` branch for immediate testing
  - [ ] Figure out whether production is being impacted by this performance problem
  - [ ] Produce a point release with the patch for the `2.7.x` series, or decide it's unnecessary (e.g. we're confident CHPs won't hit the problem, or LG is being upgraded directly to `2.8.0`)

**Comment by garethbowen** [comment]
Patch: https://github.com/medic/medic-webapp/commit/153aec454f3148265b8a4b34dfd0246668adfa91

**Comment by garethbowen** [comment]
My understanding is everyone on 2.7.x will get on to 2.8.x soon so the backport to 2.7.x shouldn't be necessary.

**Comment by browndav** [comment]
Performance increase confirmed.

2.7.2:
<img width="573" alt="view-perf-2 7 2" src="https://cloud.githubusercontent.com/assets/763977/18062826/4fdbf52e-6ddd-11e6-8f14-8a0535c558ae.png">

2.8.0 beta 6:
<img width="575" alt="view-perf-2 8 0-b6" src="https://cloud.githubusercontent.com/assets/763977/18062830/57d79fc6-6ddd-11e6-84be-796bcc61e982.png">

**Comment by browndav** [comment]
Performance increase confirmed.

v2.7.2:
<img width="573" alt="view-perf-2 7 2" src="https://cloud.githubusercontent.com/assets/763977/18062890/8f9063f8-6ddd-11e6-97ef-b62b18e26164.png">

v2.8.0-b6:
<img width="575" alt="view-perf-2 8 0-b6" src="https://cloud.githubusercontent.com/assets/763977/18062901/977faa88-6ddd-11e6-90a9-bd861c95f42d.png">

**Comment by sglangevin** [comment]
This was AT'ed already. Moving to ready.
