### ISSUE TITLE
`revertSettings` in e2e tests doesn't work

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2667]
It's not using medic-api in the proper way, so it's saving the schema by accident, and then not actually reverting all fields.

**Comment by estellecomment** [comment]
@mandric can you review please?

**Comment by garethbowen** [comment]
@mandric is right - we have to revert both `medic` and `medic-client` settings. API listens for ddoc changes and extracts the settings from `medic` to `medic-client` so if some test changed the server settings this would cause instability in the tests.

This raises an interesting question - if API is indeed watching for settings changes and updating medic-client then why is this necessary? It'd be a good idea to check that API is working as expected. It may just be a race condition in which case updating both is fine.

**Comment by estellecomment** [comment]
Interesting, I was wondering which of `medic` and `medic-client` to edit. 
I tried both in turn, and my forms showed up the same in the UI. So I suppose API was copying from `medic` to `medic-client` appropriately.

Is anything actually using the settings in `medic` then? The `Settings` service gets them from `medic-client` (which is why I went for it).

If I edit both, then API will copy the new settings over to `medic-client`'s for nothing I suppose. Which may trigger an Update modal, which may or may not mess up the test... Will try it out.

Alternatively I can also edit `medic` and wait for it to get to `medic-client`.

**Comment by garethbowen** [comment]
As mentioned https://github.com/medic/medic-webapp/issues/2676#issuecomment-243074035 the update modal won't show while e2e testing. API (and probably Sentinel) load their settings directly from `medic`. Also remember that we only ship the `medic` ddoc - the `medic-client` ddoc is an attachment with no settings yet, so on first run the settings only exist on `medic`.

**Comment by garethbowen** [comment]
One style comment. Feel free to close.

**Comment by estellecomment** [comment]
Thanks!
