### ISSUE TITLE
e2e test for sending JSON reports from Action button

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2669]
Requires medic-reporter. 
Might be better to just e2e test medic-reporter...

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by estellecomment** [comment]
DOOOONNNNNEEEE

@SCdF please review: https://github.com/medic/medic-webapp/pull/2685

**Comment by SCdF** [comment]
Made some comments on the PR. I'd be a massive fan of not requiring the internet each time you want to run e2e tests (the first time would be fine). Apart from that minor stuff.

**Comment by alxndrsn** [comment]
👍 tests shouldn't require internet

**Comment by SCdF** [comment]
(oh, and travis currently doesn't pass, which is not the best :P )

**Comment by estellecomment** [comment]
Feel free to pick this up, if not I'll get back to it later

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
We remove that feature, so this is not needed any more.
