### ISSUE TITLE
Integration testing for the replication handler

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2673]
The replication handler is a critical piece of our security model and it's only covered by unit tests. Write integration or e2e tests for replication covering unassigned documents, depth, changes after the request is established, and requesting unauthorized docs.

**Comment by alxndrsn** [comment]
* [ ] write the tests
* [ ] make them work on travis

**Comment by garethbowen** [comment]
We definitely need to rethink unit testing of the changes handler. I want to break the changes handler into small pieces that will be easier and more sensible to unit test rather than what's there now which has a large overlap with the e2e testing.

**Comment by garethbowen** [comment]
Excellent addition to the test suite. It'll be great to be able to test the server.js as well which we haven't been able to do up till now.

I feel really uncomfortable with using grunt to call shell scripts to set up for node tests - it means there's a lot of context and language switching. Personally I'd rather do as much in JavaScript as possible as it's cross-platform and a language we know every developer feels comfortable in. Obviously don't go and rewrite all the scripts right now, but it's something to think about for the future. Try node scripts instead?

I've added a few comments to the commits and then this can be closed.

**Comment by alxndrsn** [comment]
Thanks for the review.  Will look at converting those scripts to node.

**Comment by garethbowen** [comment]
No AT required.
