### ISSUE TITLE
Convert medic-reporter from erica to a better build tool

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2677]
One fewer build tool!

**Comment by garethbowen** [comment]
Actually, you know what, kanso is legacy now. Use grunt.

**Comment by garethbowen** [comment]
Not a priority and not trivial to do. Putting it on the backlog.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
@garethbowen can you provide some insight here? Or just close it.

**Comment by garethbowen** [comment]
@SCdF medic-reporter is currently using a couchapp builder called erica, which is even worse than kanso (eg: we've committed the erica binary because it's so hard to find/build now). Initially I'd hoped it would be a quick change to switch it out for kanso which would make it easier to deploy beside medic-webapp but that turned out not to be the case. Now that we're dropping kanso medic-reporter should go straight to the best build tool in our arsenal. However, we don't need to patch it very often so it's not a high priority. I'll leave it for you to triage so it gets a second opinion but I'm happy for this to be closed as low priority.

**Comment by SCdF** [comment]
Closing this. Once we've made a move with webapp we can look at it again, but since we don't mess with it much it's not causing direct pain atm.
