### ISSUE TITLE
Remove packaging of api and sentinel by `kanso push` for local dev

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2678]
When you run `grunt dev`, it calls `kanso push`, which packages api and sentinel for gardener. That's not necessary for dev environment, and it's long. 

It's done by the `kanso-gardener` package, which you can disable by removing [this line in kanso.json](https://github.com/medic/medic-webapp/blob/master/kanso.json#L52).

Find a way to do this more cleanly so that I don't have to edit the kanso.json file.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
@estellecomment, is this still relevant and important? In the words of @nice-snek, please close or schedule before the end of this sprint.

**Comment by SCdF** [comment]
NB: this would be fixed by our eventual intention to move away from Kanso entirely, but that is a long way away / never. IMO if this was an hour of someone's time to make it faultlessly not happen with `grunt dev` then I think it's a worthwhile friday ticket. Could be gross rabbit hole though, IDK.

**Comment by estellecomment** [comment]
Pain level is beareable :)

This could be done clean or dirty.

*Clean*
Add fields in the .kansorc file that would list the packages to skip (`kanso-gardener` in this case) for dev env. Requires adding that functionality to kanso.

Basically, when you're [loading the settings from kanso.json](https://github.com/kanso/kanso/blob/master/lib/settings.js#L7)
 - call [kansorc.load](https://github.com/kanso/kanso/blob/master/lib/kansorc.js#L47)
 - get the list of packages to skip from it
 - remove them from the list in kanso.json settings.

*Dirty*
Have grunt dev edit `kanso.json` to remove the bits we don't want, then kanso push, then reset the kanso.json to its original value.

This is already done by [the CI script for Travis](https://github.com/medic/medic-webapp/blob/master/scripts/ci/setup.sh#L16) to add that config, so do the reverse to remove it. (I think?Is that what this script is? Why is it doing this since that config is already in the kanso.json by default? What is the  [`dependencies_included` arg](https://github.com/kanso/kanso-gardener/blob/master/build/compile.js#L119) that it's adding, that's not in the master kanso.json? @mandric could you advise please?)

Alternatively, another grunt dev edit that would work is removing/emptying [the `node_module_folders` arg](https://github.com/medic/medic-webapp/blob/master/kanso.json#L37) that kanso-gardener uses to know where the deps to package up are.

**Comment by mandric** [comment]
I think literally all we have to do here is remove the one `kanso-gardener` line in `kanso.json`.  The [deploy scripts](https://github.com/medic/medic-webapp/blob/master/scripts/ci/setup.sh) are the only place we need them and that looks like it's already setup?

**Comment by estellecomment** [comment]
Oh. So remove `kanso-gardener` in the `master` version you mean? 
I'd rather fiddle with the dev env than the prod env, to be sure we don't accidentally ship without api or sentinel...

**Comment by mandric** [comment]
`master` is the "dev env" though?  The [deploy scripts](https://github.com/medic/medic-webapp/blob/master/scripts/ci/setup.sh) make final adjustments before a release like bundling the gardener managed services.

**Comment by garethbowen** [comment]
This will probably go away (or at least be much easier) with #3019

**Comment by mandric** [comment]
I would tweak this for the time being since it's such an easy fix and increases dev build time significantly.  When removing `kanso-gardener` from `kanso.json` my `grunt deploy` goes from 59s to 11s.
