### ISSUE TITLE
Add option to not run npm-install in grunt dev

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2679]
Because it takes a lot of time, and you're fetching the same dependencies over and over again, most of the time.

**Comment by garethbowen** [comment]
I've added a couple of comments.

This will lead to bugs where build fails because npm is out of date. I think the ideal solution would check to see if the shrinkwrap has changed somehow and only run npm when needed, but if this is useful for you that's fine.

**Comment by estellecomment** [comment]
Yeah I know, it becomes up to you to run `npm install` once in a while...
Right now I have the npm task commented out, so it's the same situation anyway for me. I got fed up with having an edited Gruntfile all the time so decided to make it real. 

Added comment about "default"

**Comment by garethbowen** [comment]
LGTM
