### ISSUE TITLE
medic-reporter ignores _forms_list_path

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2681]
The value passed into _forms_list_path is ignored.

**Comment by alxndrsn** [comment]
Is there a reason this is not labelled **`1 - Scheduled`**?

**Comment by estellecomment** [comment]
@mandric can you review please?

**Comment by estellecomment** [comment]
AT : 
 - get a working medic_reporter, pulling JSON forms from the default place in medic-webapp (i.e. have a medic-webapp on the same server, with JSON forms on it). Check the forms are showing up in your medic reporter.
 - get another medic-webapp instance somewhere, with other JSON forms (you can reuse whatever existing instance, it's not going to be edited)
 - add something like `?_forms_list_path=<other instance server>/<`[default form path](https://github.com/medic/medic-reporter/blob/master/js/app.js#L43)`>` to your medic-reporter URL (you'll need to escape the paths properly), and check that the forms from the other instance are now showing up, instead of the forms from the instance on the same server.
