### ISSUE TITLE
Have a mechanism to push a branch to a server

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2684]
Currently it's a real pain if you have a branch you want to test somewhere other than locally. There should be a way, ideally with one command, of getting any particular branch running on any particular server that you have admin privileges over.

**Comment by mandric** [comment]
Couchapps are pretty portable?  No reason the ddoc can't be PUT with http on any server that is running gardener?  Each developer might have their own server they can push stuff to for acceptance testing rather than merging with master (alpha).

**Comment by SCdF** [comment]
That doesn't work right now. Or at least, kanso push onto a server doesn't work. I don't understand the details, but something about the deployment (ie also correctly deploying api etc)

**Comment by mandric** [comment]
kanso push to a local or remote couchdb is the same thing...

**Comment by mandric** [comment]
that would be the mechanism, maybe it's broken though.

**Comment by estellecomment** [comment]
If the server runs gardener, right now you can click the button on the market to deploy, but if you want a random branch I don't know how to do it.
If it doesn't run gardener you need to push api and sentinel to it. (does nginx matter in this case?)

In either case, you also need data (though you can achieve that by replicating your local db to the remote one, if you have admin access to the remote db.).

**Comment by mandric** [comment]
Anything you have running locally should be trivial to setup/copy to any couchdb server.  The same way you push to a local couchdb you can push to a remote one.  It gets a little tricky with the submodules/processes that also need to run (handled by gardener) and might also need patches but that just means you also patch the submodule before you build/package it with the ddoc.  

For data/other docs you can replicate those but it's probably outside the topic of this conversation, which is just how to get the app code in place.  Another trick is to install (copy) the .couch file onto the new server too.

**Comment by garethbowen** [comment]
@mandric Yes it's all possible, but right now it's difficult because you need to manage api and sentinel separately. I think what this issue is asking for is a simple (one command) way of pushing the ddoc and telling gardener to extract the node modules and restart them. Definitely a good idea IMO.

**Comment by mandric** [comment]
I guess I"m not seeing the point of that because gardener is already listening to any ddoc changes.  So if it sees a new ddoc it looks for the attached modules and installs them.  You don't need to tell gardener anything, if the md5 of the module is different than it will get reinstalled.

**Comment by garethbowen** [comment]
There must be a bug then, because `kanso push` remote definitely doesn't work as expected.

**Comment by mandric** [comment]
Ok maybe gardener is only listening to changes to dashboard...

**Comment by mandric** [comment]
It's a command line flag to make it listen to any ddoc change.  That might be the issue...

**Comment by browndav** [comment]
FWIW: https://github.com/medic/medic-os/blob/master/platform/packages/gardener/scripts/gardener/run/gardener#L33

**Comment by mandric** [comment]
Yeah this is also relevant then: https://github.com/garden20/gardener/blob/master/examples.md#dashboard-style
https://github.com/garden20/gardener#advanced-usage

**Comment by mandric** [comment]
Is there a particular server we want to test this on?

**Comment by garethbowen** [comment]
alpha.dev I guess? It's one we can break without anyone else caring.

**Comment by mandric** [comment]
Ok, I just updated `/srv/scripts/gardener/run/gardener` on alpha.dev I added `--include=medic` to the command line args settings and restarted.

**Comment by SCdF** [comment]
@mandric are you saying that it works now and this ticket can be closed?

**Comment by mandric** [comment]
It hasn't been tested, was thinking either you or Gareth can confirm pushing a dev build to alpha.dev works as expected.  But we could close the issue and put in acceptance testing.

**Comment by garethbowen** [comment]
@mandric I just made a trivial change to medic-webapp/api (console.log statement in server.js) and kanso pushed. It completed successfully and looks to have restarted api, but the log statement didn't appear.

**Comment by mandric** [comment]
Ok will have to debug it then...

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
This is going to be solved by Horti, as it supports deploying branches.

That won't spin up new boxes on AWS or anything like that, but it will allow any branch to be deployed to any server. We can start with some testing instances, and if we need more / need it to be more flexible we can look at that later.
