### ISSUE TITLE
Find a failsafe way to always run `_view_cleanup` after a design document update

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2687]
Using a 45GiB production-like dataset, updating from `medic-webapp` version `2.7.2` to `2.8.0-b6` fills a 1 terabyte disk and eventually leads to `502 Bad Gateway` errors. CouchDB reports `{error,enospc}`.

Current understanding: when `medic-webapp` is updated via the Garden dashboard, the `medic` design document is modified. This potentially changes view code, which leads CouchDB to assume the worst and perform a full view regeneration procedure in the background. This procedure eventually fills the disk. One of the newly-generated `.view` files is approximately 40GiB; another is 10GiB.

Expected behavior: Naively, it seems like the space requirement for a full view regeneration should be no more than two times the size of the largest pre-rebuild view. At the very least, it seems like the required space should be no more than two times the total size of all pre-rebuild views (15GiB in this case). How we're regenerating more than 60GiB after a simple design document update is currently outside of my understanding.

To do: figure out why we're using so much space after an update to 2.8.0, then make it stop.

**Comment by mandric** [comment]
Ok I will do the first test which is just to delete and query the views so they regenerate and see if that succeeds/sizes are comparable to production...

**Comment by browndav** [comment]
I think we understand this now. Some facts first.

Fact 1: If you query the Apache CouchDB `_info` endpoint, you'll get a `view_index.signature` property back. This is an MD5 digest of all of the map/reduce view code, the language the map/reduce view code is written in, and a couple of other details. If you append `.view` to that digest, you have the name of the view index – a file on disk, stored beneath `$COUCHDB_DATA_ROOT/.${DDOC_NAME}_design`. Yes, singular: every design document has at most one view index file, and every single view's backing b-tree index is somewhere in that file.

Fact 2: CouchDB regenerates the entire view index when the design document's `_rev` changes, i.e. the design document is updated. Relatively uncontroversial.

Fact 3: CouchDB does not automatically clean up after itself when regenerating the view index. It leaves the old view index exactly where it was, and starts using the new one when it's finished. The old index will remain on disk forever or until `_view_cleanup` is explicitly invoked, which ever comes first.

Opinion 1: Fact three is balls-to-the-wall insane.

Next steps: We need to ensure that `_view_cleanup` is *always* invoked after a design document update and/or full view rebuild operation. Documentation is here: http://docs.couchdb.org/en/1.6.1/api/database/compact.html#db-view-cleanup. Figure out when/where to run this: it needs to run after the design document update *and* after views have been successfully rebuilt, the latter of which Garden's `dashboard` doesn't currently wait for. Confirm that the `autocompaction` daemon isn't affected.

**Comment by garethbowen** [comment]
Sounds like a daily cron job would do the trick?

**Comment by browndav** [comment]
Yeah, +1 here: if we can confirm that excess runs are fast and not destructive, just running it every day is way easier.

**Comment by browndav** [comment]
Forgot to mention: we've run `_view_cleanup` on a production clone and confirmed it decreases the space usage considerably (thanks @mandric). We also regenerated all of the views from scratch, and confirmed the final size was similar to our `_view_cleanup` test (also thanks @mandric).

**Comment by estellecomment** [comment]
Additional documentation : https://en.wiktionary.org/wiki/balls_to_the_wall

**Comment by SCdF** [comment]
> Fact 2: CouchDB regenerates the entire view index when the design document's _rev changes, i.e. the design document is updated. Relatively uncontroversial.

It has been suggested somewhere on the tubes that an optimisation is to have many ddocs to reduce the pain of this, even to the point of one ddoc per view. Not sure if it's something we're interested in thinking about for a general pain reduction.

**Comment by mandric** [comment]
So first thing I realized was that we were doing our tests on lg-testing using 2.8.0-beta.6 and the view changes are significant between the two.  I'm guessing the latest 2.8.0 won't have this issue, where the view generation never finishes and fills up the disk.  Testing that now to confirm...

While that is going on figured I would try to see if we can figure out why view generation in 2.8.0-beta.6 is broken.  So here's the diff of lg production 2.7.2 which does not have the problem and 2.8.0-beta.6 which does.  Pretty sure the only changes that concerns us are is `lib/views.js` and the only view that
changed is `doc_by_place`.

If anyone can see a bug in this view that would cause this please let us know:

https://github.com/medic/medic-webapp/compare/2.7.2...2.8.0-beta.6

I also pulled down the ddocs from both servers and confirmed it's the same change:
```
$ curl $LG_PROD/medic/_design/medic > medic-prod
$ cat medic-prod | jq .kanso.config.version
"2.7.2"
$ cat medic | jq --raw-output .views.doc_by_place.map > doc_by_place-2.7.2.txt
$ curl $LG_TESTING/medic/_design/medic > medic
$ cat medic | jq .kanso.config.version
"2.8.0-beta.6"
$ cat medic | jq --raw-output .views.doc_by_place.map > doc_by_place-2.8.0-beta.6.txt
$ diff doc_by_place-2.7.2.txt doc_by_place-2.8.0-beta.6.txt
```
```diff
4,7c4
<       if (!place) {
<         emit([ '_unassigned' ]);
<         return;
<       }
---
>       var depth = 0;
10a8
>           emit([ place._id, depth ]);
11a10
>         depth++;
14d12
<       return;
17c15
<     if (doc._id === 'resources') {
---
>     if (doc._id === 'resources' || doc._id === 'appcache') {
31c29
<                   doc.tasks[0].messages[0].contact
---
>                   doc.tasks[0].messages[0].contact;
36c34,39
<         emitPlace(place);
---
>
>         if (!place) {
>           emit([ '_unassigned' ]);
>         } else {
>           emitPlace(place);
>         }
38a42
>       case 'translations':
```

**Comment by mandric** [comment]
Thinking to edit out some views and keep retrying until we pinpoint which view is causing it...

**Comment by mandric** [comment]
Also browndav Fact 2 above is false. View index is only generated when *any* of the views change.  Otherwise we'd have a serious problem because settings live on the ddoc.

**Comment by browndav** [comment]
Fixed. Typed `_rev` and meant `signature`, thanks for the catch.

**Comment by mandric** [comment]
Woke up to a full disk and couchdb attempting a compaction on the reports_by_freetext view:
```
vm@medic:~ $ ls -alh /srv/storage/medic-core/couchdb/data/.medic_design/mrview/b544af96370780957d56f421fb55c98d.view
-rw-r--r--    1 couchdb  couchdb    33.7G Sep  2 11:50 /srv/storage/medic-core/couchdb/data/.medic_design/mrview/b544af96370780957d56f421fb55c98d.view
vm@medic:~ $ ls -alh /srv/storage/medic-core/couchdb/data/.medic_design/mrview/b544af96370780957d56f421fb55c98d.compact.view
-rw-r--r--    1 couchdb  couchdb    21.8G Sep  2 11:50 /srv/storage/medic-core/couchdb/data/.medic_design/mrview/b544af96370780957d56f421fb55c98d.compact.view
vm@medic:~ $ curl http://admin:secret@localhost:5984/medic/_design/reports_by_freetext/_info 
{"name":"reports_by_freetext","view_index":{"signature":"b544af96370780957d56f421fb55c98d","language":"javascript","disk_size":36143097547,"data_size":1971734703,"update_seq":1203799,"purge_seq":81,"updater_running":false,"compact_running":true,"waiting_commit":false,"waiting_clients":0}}
vm@medic:~ $ df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                    3.7G    159.5M      3.5G   4% /
tmpfs                     3.7G         0      3.7G   0% /dev/shm
/dev/xvdb2               89.0G     85.1G     49.8M 100% /srv
vm@medic:~ $ curl http://admin:secret@localhost:5984/medic/_design/reports_by_freetext
{"_id":"_design/reports_by_freetext","_rev":"1-3313f1259cdcccf07344e77cbc5a46de","views":{"reports_by_freetext":{"map":"function (doc) {\n\n    var skip = [ '_id', '_rev', 'type', 'refid' ];\n\n    var emitField = function(key, value, reportedDate) {\n      if (!key || !value) {\n        return;\n      }\n      key = key.toLowerCase();\n      if (skip.indexOf(key) !== -1 || /_date$/.test(key)) {\n        return;\n      }\n      if (typeof value === 'string') {\n        value = value.toLowerCase();\n        value.split(/\\s+/).forEach(function(word) {\n          emit([ word ], reportedDate);\n        });\n      }\n      if (typeof value === 'number' || typeof value === 'string') {\n        emit([ key + ':' + value ], reportedDate);\n      }\n    };\n\n    if (doc.type === 'data_record' && doc.form) {\n      for (var key in doc) {\n        emitField(key, doc[key], doc.reported_date);\n      }\n      for (var key in doc.fields) {\n        emitField(key, doc.fields[key], doc.reported_date);\n      }\n      if (doc.contact && doc.contact._id) {\n        emit([ 'contact:' + doc.contact._id ], doc.reported_date);\n      }\n    }\n  }"}}}
```

**Comment by mandric** [comment]
This moved mostly to the slack dev channel: https://medic.slack.com/archives/development/p1472841966001827

**Comment by browndav** [comment]
Superseded by #2716, closing.
