### ISSUE TITLE
Unique "add person" forms to a place

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2693]
We want to the ability to load different "add person" forms depending on the type of place you are adding them to, such as a "family member" form when adding a person to a household vs. a "CHP" form when adding a CHP to an area.

**Comment by diannakane** [comment]
@abbyad Can this be added to this iteration?

**Comment by garethbowen** [comment]
To achieve this I think we want to have a new type of contact (`type:"user"` or something). We'll need to migrate existing users to this type.

This will work for SMS users, but smartphone users will need a couchdb user and a user_settings doc created. At some point in the future we should make it so smartphone users can be created on the People tab without having to also go to the Configuration > Users page.

**Comment by estellecomment** [comment]
For clarity @diannakane : Family Members, who don't log in to the site, are easier to create, but CHWs, who log in as users, are more complicated.

Note that in currently-0.4 projects, CHWs are not site users, so they're in the easy case.

**Comment by abbyad** [comment]
@diannakane is this still required?

In the meantime moving it to the backlog so it doesn't get lost with no milestone

**Comment by sglangevin** [comment]
We had agreed this was not required, but it's a feature that we should include in a later version. It's mostly applicable to Android projects, but could be used for SMS projects at some point in the future.

**Comment by diannakane** [comment]
I wasn't expecting this to be done for this release. We'll keep it as a
feature request for future releases.

**Comment by abbyad** [comment]
With #2911 it is now possible to get a person's parent place's `type`. This means that we can use a single XForm with different fields based on the type of place the person belongs to.

An example of getting the type will be seen in the forms created for #2828.
