### ISSUE TITLE
ContactSchema vs. CONTACT_TYPES

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2697]
We have a [ContactSchema](https://github.com/medic/medic-webapp/blob/master/static/js/services/contact-schema.js) service, used for generating contact forms, and [CONTACT_TYPES and PLACE_TYPES constants](https://github.com/medic/medic-webapp/blob/master/static/js/app.js#L79).
Hopefully they don't give different info.

We should merge it all into ContactSchema service.

**Comment by estellecomment** [comment]
Also PLACE_TYPES, same deal.

**Comment by estellecomment** [comment]
@mandric please review!

**Comment by mandric** [comment]
👍  One suggestion over here https://github.com/medic/medic-webapp/commit/d76371808d9c79f0a973fba1fe8c0c20639a87f2#comments

**Comment by estellecomment** [comment]
@mandric Refactored to include your comments, see PR : https://github.com/medic/medic-webapp/pull/2832
Please rereview!

**Comment by mandric** [comment]
$0.02 over here https://github.com/medic/medic-webapp/commit/980f67669c2936970de2950bed4b6b28a711899a#commitcomment-19417675

**Comment by estellecomment** [comment]
Replied on the PR, lemme know if it works for you : https://github.com/medic/medic-webapp/commit/980f67669c2936970de2950bed4b6b28a711899a#commitcomment-19424895

**Comment by mandric** [comment]
Ok added a final suggestion.  Feel free to merge!

**Comment by estellecomment** [comment]
merged! Thanks!

**Comment by estellecomment** [comment]
skipping acceptance testing, since this is refactoring, nothing to look at from the outside.
