### ISSUE TITLE
Reported Date is show in ms since epoch

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2699]
In the Reporting Rates page the _Reported Date_ field is being shown in ms since epoch:

![image](https://cloud.githubusercontent.com/assets/789512/18169898/2d0a9aba-702a-11e6-9bdf-deb5bae2a38e.png)

It would be nice to display it using the `DateTime Format` from app_settings.

**Comment by garethbowen** [comment]
This was fixed at some point in the past...

![reported-date-formatted](https://cloud.githubusercontent.com/assets/2064938/18369258/c7410d18-7678-11e6-9454-e283b4acd80f.png)

**Comment by ngaruko** [comment]
Just wondering. Is it supposed to be fixed in all production instances? @garethbowen @abbyad 
This screenshot is from ipd-nepal. or do they have an older version installed?
![image](https://cloud.githubusercontent.com/assets/6979995/21834406/b2169298-d819-11e6-9752-bdd42e3ce702.png)

**Comment by abbyad** [comment]
They have v0.4 installed, so I am guessing it was fixed in v2. If we can re-confirm that it doesn't show as ms in v2 (as per Gareth's screenshot) then that's fine for moving this out of acceptance testing.

**Comment by ngaruko** [comment]
@abbyad Do we have any V2 instance where we have Reporting Rates configured. Where did @garethbowen get the screenshot from?

**Comment by garethbowen** [comment]
@ngaruko I probably got the screenshot from my dev instance (~2.9).
