### ISSUE TITLE
Allow for people-centric SMS workflows

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2700]
Existing projects with SMS workflows are case-based, exemplified by having a new ID for each new pregnancy for the same person. Actions in the app are now about contacts, as used by mobile app users, and we’ll want the SMS workflows to be person-centric as well. Having consistency between the two types of workflows will be easier for our team to design deployments and will improve how managers of SMS projects can interact with the webapp (eg view patient profiles, have tasks).

The goal of this issue is initially to raise any potential problems with this approach, then flesh out the features for implementation in the very short term (eg next 1-2 iterations), while highlighting those that can wait for a later milestone (eg in 2017).

## Proposal
To make this patient-centric we’d need to have the registration form create a person, and assign them a ID. This could be configured in app_settings like the other `Registrations`>`Events` (as of v2.9 this is `Report Actions` > `Events`). The newly created `person` contact would be within the same place as the CHW that sent the SMS, and viewing the patient’s profile in the webapp would show the unique ID. 

The CHW would use the 5 or 6 digit ID in subsequent messages about this person, similar to how the UUID is submitted with every form in the mobile app. They would not have an ID for each case eg pregnancy. 

## Acceptance Testing
- [x] A registration form can create a person within the reporting person's place, and generate a short `person_id` that corresponds 1-to-1 with the person UUIDs which can be sent with the auto-response.
- [x] The short `person_id` can be seen on the patient's profile.
- [x] Submitting a report with the short `person_id` would associate the report with the appropriate person. This means that when viewing the person's profile you would see all reports submitted about them under the history portion of their profile. 
- [x] From Registrations and Patient Reports we'd want to be able to access fields from the person's profile. _This is currently possible in case management eg `Thank you {{contact.name}}, visit for {{patient_name}} ({{patient_id}}) has been recorded.` With a patient-centric approach this would be something like `Thank you {{reporter.name}}, visit for {{subject.name}} ({{subject.patient_id}}) has been recorded.` I used `reporter` and `subject` here to avoid confusion between who is sending the report and who it is about, which may be the case if either contact or person is used. Open to other suggestions for labels._
- [ ] A Patient Report form _clears_ all associated scheduled messages for a patient ID for the silence window (eg Delivery report prevents messages from going out for silence window)
- [ ] An OFF Notification form _mutes_ all outstanding scheduled messages for a patient ID
- [ ] An ON Notification form _unmutes_ all outstanding scheduled messages for a patient ID

## Features not implemented now
- Search for person's ID to avoid creating multiple profiles for the same person
- Update profile fields via SMS. For now this will be done by asking a manager to do it via the app.
- Manage families via SMS
- Updates to the ANC Dashboards to be patient-centric. This can be done at a later time using new widgets in Targets, which would be much more flexible and powerful.

## Background
Currently we use one and two step registrations for pregnancy or immunization reminders and follow up forms about a patient are submitted using the ID:

_One Step_
```
--> R Maxine 16
<-- Thank you, you have registered Maxine for pregnancy reminders. Her ID is 12345.
--> V 12345
<-- Visit for patient 12345 has been recorded.
```

_Two Step_
```
--> R Maxine
<-- You have registered patient Maxine. Their ID is 12345.
--> P 12345 16
<-- Thank you, you have registered patient 12345 for pregnancy reminders.
--> V 12345
<-- Visit for patient 12345 has been recorded.
```

Going over the workflows for existing priority use cases and we can complete them in similar or simpler ways using patient-centric approach. Below is a sequence diagram showing patient-centric interactions with both 1 and 2 step registrations as well as the continuity between use cases. PNC is not completely fleshed out as it is still being (re)designed (also subject to #2756).

![person-centric anc pnc immunization workflows 1](https://cloud.githubusercontent.com/assets/789512/18605498/a6473c7e-7c61-11e6-8c17-5b70f3a3b92f.png)

_[**Edited** to transition from planning to feature request]_

**Comment by garethbowen** [comment]
Sounds good.

We will have to add a sentinel transition (or more likely, modify an existing one) to attach the patient UUID to the new report so it will show up under the patient history.

**Comment by estellecomment** [comment]
I think we have setups in immunization where a child is created and assigned an ID. Is a parent-child relationship stored?
If yes, then that starts to look like a family.

**Comment by diannakane** [comment]
That's true, we have implemented forms where you report the mother ID in the child registration form, and we also invented a L "link" form with [mother ID][child ID] should you want to do this later (though no project has used that to my knowledge). This lets you identify the mother child relationships in search results and outcomes are analyzable (word?) in exports.

**Comment by abbyad** [comment]
I have edited the original post to specify the issue further as it is now ready for the design-dev handoff. Feel free to continue in this issue or split it up as needed.

**Comment by garethbowen** [comment]
@abbyad Is a migration that creates patients for existing registrations required or is it acceptable to just create patients for new registrations?

**Comment by abbyad** [comment]
I think a migration could be nice for projects that have longer duration or more facility based users (eg immunization projects) -- but this is not required or expected.

If it were a small amount of dev effort needed then it is worth doing because it makes all projects patient centric which greatly simplifies our training and mindset. Otherwise we can deal with it on a case by case basis for projects that do want to "upgrade" to patient centric workflows and take advantage of the features that it enables.

**Comment by garethbowen** [comment]
### Code Review

Two PRs to review: [medic-sentinel](https://github.com/medic/medic-sentinel/pull/85), [medic-webapp](https://github.com/medic/medic-webapp/pull/2783)

### Acceptance Testing

To create the person you configure an event for "Create and assign a patient" to run after the "Add patient ID" event. This will create a person with the name of the "patient_name" field in the registration. To use a different field, enter the name of the field as a param to the event.

The response messages can access all fields in the report _or_ the associated registration, so a Visit report can respond with "Thanks for visiting {{patient_name}}" using the `patient_name` from the registration report.

![patient-centric-sms](https://cloud.githubusercontent.com/assets/2064938/18822498/03e0661e-840d-11e6-911d-5b41cfc361d1.png)

**Comment by estellecomment** [comment]
Code reviews (I like the new features!!):
 - https://github.com/medic/medic-sentinel/pull/85#pullrequestreview-1525183
 - https://github.com/medic/medic-webapp/pull/2783#pullrequestreview-1534613

Resetting to "Active work" because of that one : https://github.com/medic/medic-sentinel/pull/85#discussion_r80470449 (the rest is smaller things, or out of scope things)

**Comment by estellecomment** [comment]
+1 for migration, less variation between projects makes for easier support

**Comment by abbyad** [comment]
Decided on call that migration of data or configuration wont be done automatically, but can be done manually via import scripts.

**Comment by garethbowen** [comment]
Thanks @estellecomment ! I've implemented most of the changes you proposed and commented on the rest.

**Comment by estellecomment** [comment]
I *think* I saved all my comments, hopefully you can actually see them... (mostly [this one](https://github.com/medic/medic-sentinel/pull/85#discussion_r80637463))
LGTM, cool change, thanks!

**Comment by estellecomment** [comment]
Tests look flaky, rerunning the broken one... 
Said : 
```
  1) extract-person-contacts migration should create a new Person from facility.contact:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by estellecomment** [comment]
yup passed, flaky! @garethbowen

**Comment by garethbowen** [comment]
As far as I can tell that failure has nothing to do with this change - it's testing a migration in API and I didn't touch API.

**Comment by abbyad** [comment]
Nice work @garethbowen, works like a charm!

**Comment by abbyad** [comment]
I hadn't completed step four of the acceptance testing and just noticed that it passes for _Patient Reports_, but not for _Registrations_ (now called _Report Actions_). Returning for fixes.

**Comment by garethbowen** [comment]
Just the [last commit](https://github.com/medic/medic-sentinel/commit/9d10a71b229c3f4b5f92d4b77ec08be0cb1231e2) to review please @SCdF

**Comment by SCdF** [comment]
@garethbowen one minor style comment, other looks good.

**Comment by abbyad** [comment]
Confirming the fix. Thanks for the quick turnaround!

I noticed that I failed to include muting/cancelling schedules as Acceptance Testing items. I will add them to the original post as I think they are required as part of this issue as opposed to new functionality. @garethbowen, if you prefer this as a separate issue let me know.

![image](https://cloud.githubusercontent.com/assets/789512/19680796/bd9695ca-9aaf-11e6-9359-0ab21b17fe33.png)

**Comment by abbyad** [comment]
As noted in https://github.com/medic/medic-webapp/issues/2700#issuecomment-255990586, the Patient Forms and Notification forms do not clear, mute, or unmute scheduled messages.

In terms of timing this is not urgent and we do not need to move our next planned release (beta2) forward for this.

**Comment by garethbowen** [comment]
@SCdF PR: https://github.com/medic/medic-webapp/pull/2863

The problem was with the view that's used by sentinel to determine which registrations the mute/unmute/clear should apply to. Previously it only supported the 1 phase registration where patient and pregnancy are registered in the same message, and the `doc.patient_id` is correctly populated. The 2 phase registration means the pregnancy registration form has the `doc.fields.patient_id` field populated instead.

Sentinel already iterates through all returned registrations so this will now set the status on all registrations for the given patient.

**Comment by SCdF** [comment]
LGTM--merged.

**Comment by abbyad** [comment]
Nice work -- works incredibly well and passes all acceptance testing. This is closed for good now!
