### ISSUE TITLE
Import/Export page : tabs are wrapping

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2702]
Leftover from #2338.

In a narrow window (or mobile), the tabs wrap to a new line, which looks weird. I'd expect them to get narrower and squeeze in. 

![screen shot 2016-09-02 at 14 10 05](https://cloud.githubusercontent.com/assets/911434/18203449/6b66753e-7117-11e6-8cf1-c1c60890e257.png)

**Comment by garethbowen** [comment]
We don't really support configuration on mobile. It'll technically work but it's not recommended. Let's deprioritise this.

**Comment by SCdF** [comment]
@garethbowen / @estellecomment I'm going to take "deprioritise" to mean "take out of the sprint". Apologies if I got that wrong, and obvs feel free to add it back :-)

**Comment by ngaruko** [comment]
Actually down to a certain screen size, the configuration icon disappears altogether .( Just in case we decide to work on this in the future)
![image](https://cloud.githubusercontent.com/assets/6979995/21668567/ef7c83ce-d367-11e6-8a3f-e536ac9de333.png)

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
The tabs are compressed only in tablet view, which is not ideal but still usable. I am bringing to the current iteration in case there is a quick CSS fix to this. One option is squeezing on same line, another is to make them button-like not tab-like when overflowing to a second row. 

If it not a quick fix lets send it to the design team as part of a larger redesign conversation.

**Comment by garethbowen** [comment]
There is no quick fix that I can find. These are standard bootstrap tabs styling.

I think it's highly unlikely anyone will import or export from a tablet because you don't have traditional file storage. As there's currently enough space on PC this is acceptable.

The workaround if needed is to update the translation with a truncated value.

Please reopen if this is an issue for users.
