### ISSUE TITLE
select2 form fields are not being prepopulated

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2703]
Example, when editing a user, its "Place" field should be prepopulated, and is not: 
![screen shot 2016-09-02 at 14 43 13](https://cloud.githubusercontent.com/assets/911434/18204184/a758c674-711b-11e6-8c2e-6cff254a0eca.png)

The HTML does have the value though (in the selected line, the value is `9ebb72a1-8341-67a4-83b2e3b1a8a152fc`)
![screen shot 2016-09-02 at 14 40 46](https://cloud.githubusercontent.com/assets/911434/18204205/c4f5b78c-711b-11e6-8459-1726d3d87faa.png)

I suspect we are not passing the value to Select2Search, which should be able to handle it.

**Comment by SCdF** [comment]
Looks good.
