### ISSUE TITLE
Create icons for new People tab

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2705]
Icons currently come from fontawesome and match the old hierarchy:
District : http://fontawesome.io/icon/building/
Health Center : http://fontawesome.io/icon/hospital-o/
Clinic : http://fontawesome.io/icon/users/

while the design for the new People tab match the new hierarchy : Branch, CHW Area, Family. 
And they're not in fontawesome, so we need a proper set of icons. (or find appropriate fontawesome ones!)

**Comment by Lesterng** [comment]
@estellecomment I am building a Medic Mobile icon font that will include all the Font Awesome icons we use and all the Medic mobile ones I have created. I will only include the Font Awesome ones in the app to decrease the load. Going forward you will be able to add to it and version the font. I will provide links and instructions. Monday is a holiday here. Let me see if I can get you something to test on Tuesday.

**Comment by estellecomment** [comment]
Thank you :) 
It's not blocking my work, so no pressure on my side.

**Comment by medic-translators** [comment]
Are we still thinking that these icons will be configurable based on the
type of facilities/places in the hierarchy?

**Comment by estellecomment** [comment]
We'll need to, yes.
CA2 uses Clinic for CHW areas, while LG uses them for families. Can't have same icon for both.

**Comment by estellecomment** [comment]
Here is a zip file of the custom Medic Mobile Icon font
https://github.com/medic/medic-design/blob/master/mm-icon.zip
@Lesterng will put together a guide for adding font awesome icons and material design icons.

**Comment by Lesterng** [comment]
@estellecomment @garethbowen @diannakane @sglangevin  New icon font mm-icon-v1.0 for deployment. Minor adjustments for deployment. I will version all updates.
https://github.com/medic/medic-design/blob/master/mm-icon-v10.zip

**Comment by Lesterng** [comment]
Renamed file:
https://github.com/medic/medic-design/blob/master/mm-icon-v1.0.zip

**Comment by sglangevin** [comment]
Quick note that we are currently using font awesome icons in most of our xforms. If we are going to remove font awesome and that will affect xforms too, I'd propose that the first release with the MM icon font still have font awesome support so that we can make sure all xforms get switched over correctly before removing font awesome completely. Or we could have some other way of transitioning, just something to keep in mind.

**Comment by estellecomment** [comment]
This issue is about creating the icons, which is done. Closing it.
I'll open a new one for dev work.
