### ISSUE TITLE
RHS buttons are not aligned

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2706]
On a Person page : 
![screen shot 2016-09-03 at 19 04 33](https://cloud.githubusercontent.com/assets/911434/18226410/4e087c2e-7209-11e6-936b-8ef56969b0d1.png)

**Comment by garethbowen** [comment]
"Bug" is when something doesn't function correctly, so it doesn't apply here.

**Comment by estellecomment** [comment]
It's a CSS bug! The CSS doesn't function correctly!
LGTM
