### ISSUE TITLE
CSS for new People tab

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2709]
Doesn't really make sense to fix the CSS in little pieces, so filing this issue to do it in one go across the whole UI.

Update Oct 10 2016 : 
Check out the zeppelin mocks for styling reference: https://github.com/medic/medic-webapp/issues/2709
This includes
 - [ ] font sizes
 - [ ] font weights
(icons are covered in https://github.com/medic/medic-webapp/issues/2730)

**Comment by estellecomment** [comment]
Specs :
[Contacts-specs-dimensions.pdf](https://github.com/medic/medic-webapp/files/305746/Contacts-specs-dimensions.pdf)
[Contacts-specs-type.pdf](https://github.com/medic/medic-webapp/files/305906/Contacts-specs-type.pdf)

@Lesterng if I forgot some specs (or other relevant info) please share!

**Comment by garethbowen** [comment]
We really need the mobile designs to this.

We prefer em as units for fonts rather than pt and px - the latter two are usually only used for print media. Please update the specs.

The colours and font sizes must be kept consistent throughout the app. Has this been thought through?

**Comment by Lesterng** [comment]
Working this out this week. The type specs does affect the entire app. I have some of them in em as a unit, but I need to finalize them.

**Comment by estellecomment** [comment]
related : https://github.com/medic/medic-webapp/issues/2816

**Comment by garethbowen** [comment]
This has been blocked too long and we're out of time. I'll do this to the best of my design ability and further improvements can be made in subsequent releases.

**Comment by estellecomment** [comment]
Actually, maybe it CAN be unblocked, I don't know. 
@Lesterng ? How far along are the zeppelin mocks, regarding visual styling?

**Comment by Lesterng** [comment]
@estellecomment @garethbowen I will get to the type specs today. The Zeplin mockups are all correct. Let me clarify the Type and Icon font specs. More coming soon.

**Comment by garethbowen** [comment]
This is reasonably close now. I diverted from the zeplin mocks where there were inconsistencies or specific issues ( eg: #2816 ).

**Comment by garethbowen** [comment]
IMO this is now good enough for the beta release in 3 days time. Submit specific issues for any further changes required.

**Comment by Lesterng** [comment]
@garethbowen @estellecomment I went through a the zeplin mockups to make sure the font sizes were consistent. Zeplin will give you the less style in px. This is what I came up with for em conversion with the default set at 12px. Feel free to come up with your own em conversions if you want to use a different default size or different H1, h2, etc values.

https://docs.google.com/a/medicmobile.org/document/d/1oIc4iBPgILlbtnAMEHvsHoNSF7Q8wGOLxNhbaGrw5TE/edit?usp=sharing

**Comment by Lesterng** [comment]
@garethbowen @estellecomment @diannakane I add specs for the Medic Mobile icon font to the Web app type specs. It includes Medic Mobile icons plus Font awesome and Material design fonts in one font stack. you can add icons to the document with the span tag and the class name of the icon.
https://docs.google.com/a/medicmobile.org/document/d/1oIc4iBPgILlbtnAMEHvsHoNSF7Q8wGOLxNhbaGrw5TE/edit?usp=sharing

**Comment by estellecomment** [comment]
For the design folks, here's a screenshot : 
![screen shot 2016-10-12 at 10 04 36](https://cloud.githubusercontent.com/assets/911434/19302263/a5e79bdc-9063-11e6-9b9c-6917e473daee.png)

Looks good!
 - I don't have thoughts about bold vs. not bold.
 - I think it would increase readability to have more vertical whitespace in list elements (people, tasks, reports). The scribbled space is the one I'm talking about:
![screen shot 2016-10-12 at 10 13 00](https://cloud.githubusercontent.com/assets/911434/19302515/c024979c-9064-11e6-81f5-059eb82879eb.png)

Right now the `<a>` has 5px of padding, where the zeppelin mocks have 12-15px of whitespace, so maybe just increase that.

 - It would also help readability to have all list elements the same height, whether they contain one line or two. E.g. the "no reports" is shorter in height, or the People with no title ("A's little sister" in screenshot above).

Thanks!

**Comment by garethbowen** [comment]
> It would also help readability to have all list elements the same height, whether they contain one line or two.

Unfortunately we can't know how big the biggest row is (due to wrapping, fonts, icons, etc).

**Comment by estellecomment** [comment]
> we can't know how big the biggest row is (due to wrapping, fonts, icons, etc).
Can you set a minimum height though, ballpark? Then if there's more wrapping it can go over?

**Comment by Lesterng** [comment]
@estellecomment 
Note: 
1. Area name above area card, People, Households, Reports above list items should be in "regular" NOT "bold"
2. Household list items: "**Name family**" should be bold
Refer to Zeplin mockup: https://zpl.io/28Bjam

**Comment by garethbowen** [comment]
@estellecomment I don't think it's a good idea to add arbitrary minimum heights as we want to get as much on the tiny mobile screen as possible. For example if an installation doesn't have an age field in registration forms then none of the children will have the second line and it would be a waste to insert all that whitespace.

I've added bolding for the name of the children as per the comment from @Lesterng
