### ISSUE TITLE
Translations broken for FABs in new People tab

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2710]
Both RHS and LHS.
Figue out if it's just me locally or what.

**Comment by estellecomment** [comment]
Doesn't translate : 
`<p translate>action.{{actionBar.left.userChildPlace.type}}.add</p>`

Translates: 
`<p>{{ ("action." + actionBar.right.selected[0].child.type + ".add") | translate }}</p>`

My guess is that 
 - the label is `action..add` until the controllers are done initializing actionbar
 - `action..add` is not a known label.
 - the `<translate>` directive only translates once, and then doesn't watch for updates to the label, so never gets `action.health_center.add`.

Either re-trigger the translating, or just use the `{{ blah | translate }}` version which has watchers.

**Comment by estellecomment** [comment]
(I added a `action..add` label, and it did NOT get picked up. Hmmm.)

**Comment by garethbowen** [comment]
Couple of comments.

**Comment by estellecomment** [comment]
rereview?

**Comment by garethbowen** [comment]
Looks good!
