### ISSUE TITLE
Remove unused keys from translations

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2711]

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
If there are known keys that are not used, please remove.

Might be handy to have e.g. a grunt task to check for unused keys.

**Comment by estellecomment** [comment]
I'm pretty sure there are some, and there is nothing to spot them right now
AFAIK. That's the point of the issue.
