### ISSUE TITLE
e2e tests got flake

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2714]
![if only!](http://blog.boschpackaging.com/wp-content/uploads/2014/07/PA_CS_Cadbury_Flake-Bar_704x251-704x251.jpg)

E2E tests now successfully run locally, nearly every time. Unfortunately they break a bunch on Travis. This is bad: Travis should only be whinging when there is something actually wrong.

Investigate!

**Comment by SCdF** [comment]
A failure I've seen a lot:
![image](https://cloud.githubusercontent.com/assets/583851/18277670/2ade3d98-7447-11e6-9392-f629fb15af85.png)
This is probably caused by our `browser.sleep()`, [here](https://github.com/medic/medic-webapp/blob/master/tests/protractor/e2e/send-message.js#L98). We could either increase this timeout, or possibly convert the `expect` assertions below into a `browser.wait` condition. That way we can wait for multiple things (the correct number of results with the correct values) without having to know when it finishes. The downside is that we no longer assert and so the error just turns into a timeout.

**Comment by SCdF** [comment]
A failure I've seen a lot a lot:
![image](https://cloud.githubusercontent.com/assets/583851/18277870/e56bc428-7447-11e6-8236-c1e7b09a7a8e.png)
This one seems to happen *a lot*. This is not limited to new e2e tests, the sms-gateway ones will have this one as well. In fact, you usually spot this particular failure in large groups. It might be that the browser state is getting into a funky state and just breaking for the rest of the e2e test.

**Comment by SCdF** [comment]
We also don't tend to run Firefox locally, whereas Travis does. We should try to get Firefox working.

**Comment by SCdF** [comment]
So FF 38+ is known to not work with Selenium. FF 37 actively crashes on loading!

I'm downloading the version that Travis uses, which is the "Extended Service Release" or ESR.

**Comment by SCdF** [comment]
OK FF ESR (currently at 35) does work locally pretty stabily, at least with the few runs I've tried.

Unfortunately we can't expect devs who use FF as their actual browser to downgrade. Time to look at the forward moving step, which is using the Marionette driver, which AFAICT is the way forward with FF and webdriver.

**Comment by SCdF** [comment]
My brain is slow! This error:
![image](https://cloud.githubusercontent.com/assets/583851/18277870/e56bc428-7447-11e6-8236-c1e7b09a7a8e.png)
Is almost certainly a knock-on error from a send-message error occurring. I'm going to look at adding a post test run for send-message tests that tries to reset the browser back into a useful state (ie maybe just a refresh, or refresh to a useful base url).

**Comment by SCdF** [comment]
Part one complete!

@garethbowen can you review: https://github.com/medic/medic-webapp/commit/4d5eea062b1a5c934884bb06042f3db77728d733 https://github.com/medic/medic-webapp/commit/922e3eb28497b244cd9116c83448e961c7feec18 and https://github.com/medic/medic-webapp/commit/6bd69b65eb66317de9abc8c0b986b0d5c29bafae

Not sure how you want to deal with this ticket. I'm happy to leave it open and assigned to me, and if I see build failures that are due to e2e I'd document and try to fix them here.

**Comment by garethbowen** [comment]
Code looks good. I'll leave it assigned to you. Good work!

**Comment by garethbowen** [comment]
I guess I ended up closing it... Leaving you to acceptance test. Feel free to open or change status as required...

**Comment by SCdF** [comment]
Bah! https://travis-ci.org/medic/medic-webapp/jobs/158406496

**Comment by SCdF** [comment]
Weirdly these seem to be all the same issues I thought I'd fixed. Clearly I didn't!

**Comment by SCdF** [comment]
@garethbowen check out the above commit, oh I've bet we've got it this time! (probably not)

**Comment by garethbowen** [comment]
Nice.

**Comment by SCdF** [comment]
Nope.

![image](https://cloud.githubusercontent.com/assets/583851/18384632/8f862434-7683-11e6-943c-4803e29c95da.png)

Looks to be situations where loading doesn't show? Or we're not fast enough to catch it showing? Infuriating.

**Comment by SCdF** [comment]
On the plus side, the refresh trick worked, so this test breaking didn't break other tests in the suite. I'm going to expand the refresh so it happens between every test to further isolate issues.

**Comment by SCdF** [comment]
OK so AFAICT the loading indicator always shows. It might be the case that it only shows for very short time because the DB is so small the search is over very quickly (indeed the view will only have 2 entries in it). **However**:
 - The check should begin occurring straight after we've completely sent all the keys to select2
 - select2 should be waiting 250ms before firing off the ajax call

This seems like we should be in with a grin here, but clearly we aren't.

I'm going to muck around with this a bit and see what I can come up with, but the next step may have to be telling the test exactly what you expect to be able to select in the dropdown and just waiting until that thing is selectable, which sucks.

**Comment by SCdF** [comment]
Mis-labled a commit, this one is relevant to this ticket: https://github.com/medic/medic-webapp/commit/4c263585808e8bde97e5264ecacd6de2bd6677e9

**Comment by SCdF** [comment]
@garethbowen more reviews plz, the above two commits if you don't mind.

**Comment by garethbowen** [comment]
One comment. It's a difficult diff to read but looks ok.

**Comment by estellecomment** [comment]
![image](https://cloud.githubusercontent.com/assets/911434/18514129/992fba66-7a90-11e6-8d1e-39293a260f0d.png)

![screen shot 2016-09-14 at 15 18 47](https://cloud.githubusercontent.com/assets/911434/18514155/af54bba2-7a90-11e6-932a-c725d74312db.png)
![screen shot 2016-09-14 at 15 19 01](https://cloud.githubusercontent.com/assets/911434/18514156/af570c36-7a90-11e6-83ed-5ab1c8a9859b.png)
![screen shot 2016-09-14 at 15 19 10](https://cloud.githubusercontent.com/assets/911434/18514157/af5876c0-7a90-11e6-9f3f-09cb0f8b7606.png)
![screen shot 2016-09-14 at 15 19 32](https://cloud.githubusercontent.com/assets/911434/18514154/af532cf6-7a90-11e6-85af-a9251fec918d.png)

**Comment by estellecomment** [comment]
More! 
https://travis-ci.org/medic/medic-webapp/builds/159875880
[4120.1_travis.txt](https://github.com/medic/medic-webapp/files/472161/4120.1_travis.txt)
[4120.2_travis.txt](https://github.com/medic/medic-webapp/files/472162/4120.2_travis.txt)

**Comment by SCdF** [comment]
From your pictures: the first one is the problem, the rest are either not problems (I'm tweaking output to make that clearer) or are due to the first problem.

And yeah, not sure about that first one. I'm tempted to just push the timeout out further.

**Comment by SCdF** [comment]
Not sure why this was still open.

**Comment by estellecomment** [comment]
Send-message rears its ugly head again.
[send-message-flake.txt](https://github.com/medic/medic-webapp/files/503229/send-message-flake.txt)

**Comment by SCdF** [comment]
Key issue here (from a guess) is that we're refreshing too fast after we've clicked send and we're losing the change. This is really hard to fix, because currently there is no useful UI indication (in an e2e test) that the message has been sent.

I'll take another look at it. Possibilities:
 - Fix the UI so that the send-message modal only closes once everything has been saved correctly (this might even be true already with the new modal model?)
 - Query couchdb in a `browser.wait`  block and hold until the data we expect to exist in a view is there.

**Comment by SCdF** [comment]
@estellecomment check out the above commit

**Comment by estellecomment** [comment]
kewl
