### ISSUE TITLE
Create a script that invokes `_view_cleanup` for all CouchDB databases

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2716]
This issue supersedes #2687, and is required for medic/medic-projects#743.

Build a script that connects to the local CouchDB database using gardener's stored administrative credentials, and uses `curl` to request `_view_cleanup` for every design document in any database.

**Comment by browndav** [comment]
Is the intent to run this from cron? There's no `bash` on our production images, but Busybox's `ash` can probably run this as-is IIRC (it's not `dash`-level bad, it supports a bunch of Bashisms and useful stuff like `pipefail` and `$PIPESTATUS`).

**Comment by alxndrsn** [comment]
> Is the intent to run this from cron?

No idea what the intent is - all I know is written on this ticket :¬)  If it's for automated use, it might benefit from better handling of non-2xx response codes (IIRC `curl` will often return a status `0` when a HTTP request fails).

**Comment by browndav** [comment]
Looks like the linked medic/medic-projects#743 is clear re: cron but this issue isn't. It is for automated use; the idea was to just run it once per day automatically since it's inexpensive and nondestructive.

**Comment by browndav** [comment]
I'd probably (i) add `-f` to `curl`, and (ii) fix up the `#!` and test it with Busybox `ash` to make sure everything runs okay there.

**Comment by alxndrsn** [comment]
I'm not really convinced about the value of using `-f`, in part because:

> This  method  is  not  fail-safe  and  there  are occasions where non-successful response codes will slip through, especially when authentication is involved (response codes 401 and 407).

Also, what are we going to do if this script fails?  Presumably just log it, which we'll achieve anyway if we redirect the current standard output to a log file.

---

If you have any suggestions for testing on `ash` locally, let me know.  Otherwise, I guess I'll just change the shebang to `/bin/sh`, and run it on alpha.dev.

**Comment by alxndrsn** [comment]
The main issue is actually that `jq` isn't available on medic-os.  I can effectively re-implement that part in node (at which point... maybe the whole script should be rewritten in node), or we could add `jq` to the image.  Let me know which is preferred.

**Comment by browndav** [comment]
I've added `jq` to the `master` branch of Medic OS and will be testing upgrades to that latest release this week. `$PATH` issues have been fixed independently as well, so this should run properly on our production images post-upgrade.

**Comment by garethbowen** [comment]
Randomly choosing @alxndrsn for code review.

**Comment by alxndrsn** [comment]
Randomly choosing @garethbowen for code review, as @alxndrsn wrote the code ;¬)

**Comment by garethbowen** [comment]
LGTM.

AT: Execute this script against a database and make sure it works. Something like... `COUCH_URL=... scripts/compact_all_local_dbs`

**Comment by ngaruko** [comment]
Can you please elaborate on how to AT this @browndav ? Thanks.

**Comment by garethbowen** [comment]
@ngaruko Did you see my AT instructions above?
