### ISSUE TITLE
Document lessons-learned re: CouchDB database compaction, view compaction/rebuilding/cleanup

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2717]
We recently learned a bunch of potentially-troubling things about how CouchDB manages disk space and on-disk view indexes. Since the upstream documentation isn't spectacular, document the limitations we discovered and come up with a set of best practices for managing disk space and index rebuilds.

**Comment by estellecomment** [comment]
Blog! Post! Blog! Post!

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Ancient. Closing.
