### ISSUE TITLE
`grunt unit_continuous <my file>`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2720]
I usually edit `karma-unit.conf.js` to only test the file that I'm working on. And of course it happened, I committed the change by mistake.

I need to do `grunt unit_continuous <my file>` without editing config files.

**Comment by SCdF** [comment]
Are you aware of `only`? So `it.only` or `describe.only` basically does what you want.

You still have the commit issue where you can commit that by mistake (which I've done many times before) but it's worth knowing.

**Comment by alxndrsn** [comment]
Also mocha has a `--grep` option, which might be applicable to karma.

**Comment by garethbowen** [comment]
Not a priority - removing from this iteration.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
It looks like the above workarounds will do the trick. We've also recently added a check so `.only` will fail the build if committed accidentally.
