### ISSUE TITLE
Quick filters for Tasks and Reports on the People tab

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2721]
Add filters for the lists of Tasks and Reports on the People tab as below.

![filter](https://cloud.githubusercontent.com/assets/2064938/18344964/858946da-760d-11e6-859e-33768fab71a3.png)

**Comment by SCdF** [comment]
^^ this commit is not for this ticket, it is for #2714 . This is what I get for multi-tasking.

**Comment by SCdF** [comment]
@garethbowen so in adding this feature I noticed that tasks for users don't show up for admins. This completely makes sense: for performance reasons we disabled nools. When the page reaches for tasks it comes up empty handed.

Is this a problem? If so, it's a hard one to solve without moving to a tasks as documents system.

**Comment by SCdF** [comment]
Mostly done, in the above commit.

No filtering:
![image](https://cloud.githubusercontent.com/assets/583851/18431257/1560af96-78d4-11e6-956e-58291e9ca16c.png)
Filtering:
![image](https://cloud.githubusercontent.com/assets/583851/18431282/263f2590-78d4-11e6-8a9b-05755e0e44bd.png)

Three things:
 -  I haven't done any particular styling of the links at this point: not sure if there are specific colours that I should be using or I just color-pick the screenshot above, but color-picking on small fonts is sketch. I'm also not sure what the most web n.0 approach is to theming those stabily (ie manually set all three link themes on each click, or radio button theme hacks, or… etc). Keen to talk to @garethbowen about that one 
 - I really don't like having to make `setReportMonthsBack` and `setTaskWeeksBack`, it seems dumb, but it works
 - Translations are similarly dumb, but AFAICT we aren't doing proper pluralisation anywhere else and it's a reasonably large step up to start caring about that kind of thing, so I didn't bother introducing it.

**Comment by SCdF** [comment]
@garethbowen interested in your thoughts so far

**Comment by garethbowen** [comment]
I've added some comments to the commit.

**Comment by estellecomment** [comment]
@SCdF reference for colors and fonts and pixels and things is the Zepelin project (request access from Dianna if necessary): https://app.zeplin.io/project.html#pid=57d311edb055084578d006ec&dashboard

**Comment by SCdF** [comment]
OK @garethbowen I've made some more changes (see the styling commit above). I've merged them into master because they're not so crazy that they need to be in a branch.

Note that I haven't fixed the pluralisation yet. I've created a branch that I'll link on #2712. If we end up really struggling we can come back and do the half-good version on here (as opposed to replacing it with the awesome).

**Comment by garethbowen** [comment]
Two minor comments. How does it wrap if you switch to French (or just fake it by editing the source)? Do the filters drop down below the header?

**Comment by SCdF** [comment]
Oh yeah whoops forgot to fix the wrapping. Meant to. Need more todo lists.

**Comment by SCdF** [comment]
@garethbowen just a minor style change so it looks right with longer text. I'm not really happy with it because it's magic pixel peeping to make things line up, but I don't think there are a huge number of options with this kind of thing.

**Comment by garethbowen** [comment]
LGTM
