### ISSUE TITLE
Mock updates: no parent place dropdown in forms

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2724]
When adding a child place or child person, the form that shows up should display the parent place, but not a dropdown allowing to change it.
(from decision in https://github.com/medic/medic-webapp/issues/2704#issuecomment-245773575)

Example (click New Person or New Area):
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906666

@Lesterng please update the mocks accordingly.

**Comment by Lesterng** [comment]
@estellecomment  I saw this reference. I will change the mockups to reflect the change with no dropdown to change the parent place.

**Comment by garethbowen** [comment]
@Lesterng Any update on this?

**Comment by sglangevin** [comment]
Sounds like this was moved to #2828, where we have full information on default person and place forms. Updates to mocks can be made to satisfy all requirements in the other issue. Closing in favor of #2828.
