### ISSUE TITLE
Default forms for creating child Persons should display the parent place 

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2726]
In the new People tab, you create a Person from its parent place. 
The creation form should show what parent you're creating it in.

Currently, no parent field : 
![screen shot 2016-09-09 at 11 50 17](https://cloud.githubusercontent.com/assets/911434/18383075/130308ae-7684-11e6-9d61-03b81eb191c9.png)

Blocked on mocks for forms (to make sure we're actually displaying the parent place in the end!) : https://github.com/medic/medic-webapp/issues/2724

**Comment by sglangevin** [comment]
This is no longer blocked as there is now a spec for default place and person forms (#2828). I think we can close this issue in favor of #2828.
