### ISSUE TITLE
Update mockups : places should be listed in alphabetical order

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2728]
Child places and people should be sorted in alphabetical order (except Family Members, who are sorted by age)

This mock sorts differently, please update :
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906666

**Comment by Lesterng** [comment]
Yes, you are correct, alphabetical order. Future mockups we are working on getting the data more accurate.

**Comment by estellecomment** [comment]
Since we're not using Invision mocks for dev-design interaction, I'm closing this.
