### ISSUE TITLE
New icons : use them for webapp and forms

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2730]
Icons were produced in #2705, yay!
https://github.com/medic/medic-design/blob/master/mm-icon-v1.0.zip
We are going to switch to these away from fontawesome.

Dev work : 
Figure out how to use the new font, feedback to design if something is wrong or it needs more explanations.
Figure out how it impacts xforms, who were using fontawesome up to now. Find a solution if there's a problem (keep fontawesome around?).

**Comment by garethbowen** [comment]
Once the new font is integrated we should also write a quite "updating the font" readme so designers can do it themselves when they generate a new font.

**Comment by abbyad** [comment]
Given the ripple effects of this change for forms, moving this to backlog to be tackled post v2.9 release.

**Comment by garethbowen** [comment]
The icons are currently being redeveloped again so we shouldn't use this font. A new issue will be created once the new icons are ready.
