### ISSUE TITLE
Hide phone number for Family members in lists?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2732]
The default way of displaying people in a list shows the phone number (see the CHW person) : 
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/159906705

Family members are displayed differently (which is cool). 
One such difference is that phone number is not displayed : (see Allison Jones)
https://projects.invisionapp.com/share/XA7CTCBGU#/screens/163504245

Is this on purpose? Should we hide phone numbers for family members in lists?

**Comment by estellecomment** [comment]
@diannakane

**Comment by diannakane** [comment]
@lesterng I think we should consider changing this to handle CHWs the same as family members, and display their phone numbers on their cards, but not as a list. 

This would help resolve:
1) issue #2737 about screen size 
2) set us up for supporting future manager views which may require us to list number of tasks a manager must complete next to the CHWs name, in the same way a CHW sees the number of tasks they must complete for a family member.

I'll make the change in Sketch -- shout if you see a problem with this.

CHW in a list
![image](https://cloud.githubusercontent.com/assets/1675870/18488820/f1111c2a-79af-11e6-80ec-356b8695698f.png)

Family members in a list
![image](https://cloud.githubusercontent.com/assets/1675870/18488852/0b0d693a-79b0-11e6-94d8-97e1f7fee7a4.png)

**Comment by estellecomment** [comment]
@diannakane Trying to clean up issues. Are the screenshots above final? If this issue is out of date, please just close it. (if not continue :) )

**Comment by diannakane** [comment]
Updated: no phone numbers in any level. Makes space for tasks for all people (future). Currently tasks only in level 3. https://zpl.io/28Bjam

**Comment by estellecomment** [comment]
sg! Closing, i've filed #2812 to implement it
