### ISSUE TITLE
Any user can read any other's user-doc

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2733]
Shadow ticket for https://github.com/medic/medic-projects/issues/753

**Comment by nice-snek** [comment]
hi frand @mandric, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
Security!

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
Leaving open as per comments on medic-projects

**Comment by garethbowen** [comment]
I think this is fixed by #2734

**Comment by dianabarsan** [comment]
This is fixed by #2734 .

**Comment by ngaruko** [comment]
Tested on alpha.dev. Only admin user can access other users docs, including other admin users'. Otherwise, the request returns a `403 Forbidden` error (which is expected) 
`{"error":"forbidden","reason":"Insufficient privileges"}`

**Comment by derickl** [comment]
Given medic/medic-projects#753 was reopened, should this ticket be open? @alxndrsn ?

**Comment by garethbowen** [comment]
@ngaruko Please check the linked issue for additional acceptance testing required.

**Comment by ngaruko** [comment]
LGTM
