### ISSUE TITLE
Changes feed filtering can be avoided

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2734]
Shadow ticket for https://github.com/medic/medic-projects/issues/752

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
Still an issue.

**Comment by garethbowen** [comment]
Code review please @SCdF 

It's a heavy handed solution that may cause issues where we were relying on restricted users having couchdb access, but having to open up endpoints explicitly makes more sense given couchdb's relaxed security model...

**Comment by garethbowen** [comment]
I think this resolves

- medic/medic-projects#752
- medic/medic-projects#753
- medic/medic-projects#1809

It reduces the attack surface to just admins and national admins which is probably ok - they have full access to everything by design.

AT all three before marking this Ready.

**Comment by garethbowen** [comment]
My proposed solution doesn't work... PouchDB needs direct access to replicate attachments, so I'll need to do some sort of check to allow direct access if the doc can also be replicated.

**Comment by garethbowen** [comment]
The correct solution is something like...

1. Write a function that takes a doc and a user as parameters and returns whether or not that user has permission to see that doc. This must be reasonably performant as it will be called a lot.
2. Apply the above function when reading or writing a doc for every non-admin request.
3. Only proxy requests to couchdb if the user is an admin (as per my closed PR).
4. Test thoroughly to ensure restricted users still have access to all the APIs they need, and all those APIs are protected at a doc level using the function in 1 (or similar).

I'm unassigning this from myself so anyone can pick it up.

**Comment by garethbowen** [comment]
AT: As well as plenty of other parts, make sure restricted users cannot access `/_utils` as requested here #4609

**Comment by garethbowen** [comment]
This could be a destabilising change so I'm bumping it to 3.1.0 to give us more time to test it fully.

**Comment by dianabarsan** [comment]
Apparently, PouchDB 7 soemtimes requests attachments without using `rev` query parameter, which proves a problem especially for deleted documents. Working on it.

**Comment by ngaruko** [comment]
LGTM ....
![image](https://user-images.githubusercontent.com/6979995/43565186-f8b62a5a-967d-11e8-92ee-2c208513a4a9.png)

**Comment by alxndrsn** [comment]
Ticket in `medic-projects` is still open; @ngaruko your example above does not seem to relate to the issue as reported in the parent ticket.  As this is security-related, ideally discussion would take place there.
