### ISSUE TITLE
Targets tab is blank on first access

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2739]
When logging in as a restricted user on v2.8.0, the first time I access the Targets tab it is blank. Subsequent times it appears normally, but first access seems to have an issue. I logged in as demo1 - PM me for the password.

First access:
![image](https://cloud.githubusercontent.com/assets/1286381/18445773/036f1354-78d4-11e6-84ad-386e6bb835c2.png)

Clicked the contacts tab then the targets tab:
![image](https://cloud.githubusercontent.com/assets/1286381/18446058/5e6aadbc-78d5-11e6-9069-01ff3c0501ac.png)

**Comment by garethbowen** [comment]
`master` has been refactored so this is no longer an issue for 2.9.0+

**Comment by sglangevin** [comment]
Working well in v2.8.1-beta.2
