### ISSUE TITLE
API changes feed unit tests are invalid

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2740]
In `/tests/handlers/changes.js`, `longpoll` has been misspelt `longpole`.  Correcting this spelling breaks the build on Travis (https://travis-ci.org/medic/medic-api/jobs/159551894), although tests pass on my machine with this change.

It's not clear if this represents a serious problem for the changes feed or not.

**Comment by garethbowen** [comment]
This was by design. "longpoll" and a couple of other options specifically cause different behaviour. Anything else (eg: "longpole") does not. I'll change it to be "not-longpoll" or something.

**Comment by alxndrsn** [comment]
Thanks!
