### ISSUE TITLE
Tasks on family members should show up in Household's tasks

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2742]
E.g. task about on "Allison Jones" should show up in "Allison Jones' Family" Task list.
(and also in "Allison Jones" task list)

**Comment by estellecomment** [comment]
@garethbowen please review!

**Comment by garethbowen** [comment]
A couple of small comments on the commit. Looks good!

**Comment by estellecomment** [comment]
No changes so I'm closing, but happy to reopen if needed.
