### ISSUE TITLE
replication-depth may behave inconsistently if set to zero

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2749]
From the `getDepth()` function, it appears that there should be a difference between depth values of `0` and `null`: https://github.com/medic/medic-api/blob/master/handlers/changes.js#L32

However, the `bindSubjectIds()` method  appears to treat `0` and `null` equally: https://github.com/medic/medic-api/blob/master/handlers/changes.js#L52.  `hasNewApplicableDoc()` behaves similarly: https://github.com/medic/medic-api/blob/master/handlers/changes.js#L214

Double check if this is handled correctly, as it's possible the code in `bindSubjectIds()` is only reached when the depth value is actually a `Number`.  If this behaviour is deliberate, then `getDepth()` should probably return `null` for values `< 1`.

**Comment by garethbowen** [comment]
Good spotting!
