### ISSUE TITLE
Validations and Auto-Replies not triggered for Notifications

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2755]
Notifications (OFF/ON forms) are not generating validation or auto-reply messages. This is using our DIY ANC config on diy.dev with `v2.9.0-alpha.4133`. 

![image](https://cloud.githubusercontent.com/assets/789512/18600329/1500edae-7c2b-11e6-9ec1-6625b55e9421.png)

![image](https://cloud.githubusercontent.com/assets/789512/18600359/2a92e91a-7c2b-11e6-8792-22f8380741ad.png)

Registration and patient reports generate validation and auto-response messages. I couldn't find a problem in the config, and the list of transitions are as follows:
```
"transitions": {
       "accept_patient_reports": {
           "load": "./transitions/accept_patient_reports.js"
       },
       "conditional_alerts": {
           "load": "./transitions/conditional_alerts.js"
       },
       "default_responses": {
           "load": "./transitions/default_responses.js"
       },
       "update_sent_by": {
           "load": "./transitions/update_sent_by.js"
       },
       "registration": {
           "load": "./transitions/registration.js"
       },
       "update_clinics": {
           "load": "./transitions/update_clinics.js"
       },
       "update_notifications": {
           "load": "./transitions/update_notifications.js"
       },
       "update_scheduled_reports": {
           "load": "./transitions/update_scheduled_reports.js"
       },
       "update_sent_forms": {
           "load": "./transitions/update_sent_forms.js"
       }
   }
```

**Comment by garethbowen** [comment]
All properties submitted as part of the form are stored in the `fields` property. This is a change from 0.4 where they were stored directly on the doc.

**Comment by abbyad** [comment]
Working, moving to Ready.
