### ISSUE TITLE
Option to set birthdate using days old instead of weeks

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2756]
The "Add Birth Date" event works using weeks old (since it was designed for immunizations) but for the PNC use case the message schedule can be 1, 3, 7 *days* after delivery. We should provide an option to add a birthdate using the age in days.

There are three upcoming projects launching in October that can use this feature. Without this feature they are opting to not using PNC reminders in their workflows, which is not ideal. The feature seems to have a relatively low level of effort (eg copy and modify the week functions and tests) so seems worthy to be included for the next release of v2 compatible with SMS workflows (presumably v2.9) and, if feasible, it would be ideal to backport to v0.4 as well.

Spawned from https://github.com/medic/medic-projects/issues/666, and similar to #992.

**Comment by abbyad** [comment]
Moving to the current iteration. If it does not get attention this iteration we should complete it by the following iteration.

cc @bishwas-medic

**Comment by alxndrsn** [comment]
Couple of queries on one of the backport commits; they should apply similarly to the corresponding commit to `master`.

**Comment by bishwas-medic** [comment]
Acceptance testing completed! It works great. This feature will be very helpful, thanks Dev team.
