### ISSUE TITLE
Should not allow access to medic-reporter settings from webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2757]
We should not allow a user to change the settings in medic-reporter when submitting a new form:
![image](https://cloud.githubusercontent.com/assets/789512/18605624/c32f1ed0-7c64-11e6-8b97-14787ad25238.png)

We have previously controlled which medic-reporter view to use by setting the `_embed_mode` param to `2` in the URL set in `app_settings`:
![image](https://cloud.githubusercontent.com/assets/789512/18605628/d7b73b1c-7c64-11e6-8813-af766ea3181f.png)

**Comment by garethbowen** [comment]
Two commits to review. The configured uri was being ignored and parameters weren't being passed correctly to reporter. This also fixes #2758 and #2759.

**Comment by estellecomment** [comment]
One comment about documenting the new service which caught me by surprise. 
LGTM, thanks for fixing!
