### ISSUE TITLE
Correct form not displayed when going to Submit Report

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2758]
This may still be under development, but thought I'd point out that it doesn't matter which form is chosen in the Submit Report; all will show up in the medic-reporter's form selection list and the first one will be shown.

![image](https://cloud.githubusercontent.com/assets/789512/18605666/1fbe5912-7c66-11e6-8d17-90c35537aee9.png)

From within app the url is `https://diy.dev.medicmobile.org/medic-reporter/_design/medic-reporter/_rewrite/?_embed_mode=1&amp;_show_forms=V&amp;_locale=en`

It looks like it should be: `https://diy.dev.medicmobile.org/medic-reporter/_design/medic-reporter/_rewrite/?_embed_mode=2&_show_forms=V&_locale=en#/V`

- Set the desired form in path, not param
- Changed `&amp;` to `&`
- Changed the embed mode (as per #2757)

Even with these changes, the `_show_forms` is not respected by `medic-reporter` which is a separate issue.

**Comment by garethbowen** [comment]
Fixed in #2757
