### ISSUE TITLE
Forms in Submit Report menu aren't sorted

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2760]
![random](https://cloud.githubusercontent.com/assets/2064938/18619393/00b2831e-7e4f-11e6-9bb3-3bcd9c827eec.png)

**Comment by garethbowen** [comment]
It turned out to be more complicated than I'd hoped. JSON forms shouldn't be sorted because they're shown in the order they're defined in the app_settings which allows configurers to sort them sensibly.

I have applied alphabetical sorting to xforms only which should be sufficient because not many installations will have xforms and json forms together.

I also added a "track by" expression which should be declared for every ng-repeat.

**Comment by estellecomment** [comment]
LGTM
