### ISSUE TITLE
Improve sms-gateway startup time on well-used installations

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2761]
As per https://github.com/medic/medic-gateway/issues/19, the event log takes a long time to load when there are a lot of log messages in the database.  In turn this means that it can take a while for the GUI to load on starting medic-gateway.

Steps to fixing:
* [x] don't load the event log at startup - this should immediately fix the slow startup issue
* [x] release and share with @bishwas-medic for testing
* [x] load log messages _asynchronously_, and show a spinner while loading - it currently seems that the UI is blocked when loading messages
* [x] re-instate loading of event log at startup now that a nice spinner is shown
* [x] release and share with @bishwas-medic for testing
* [x] introduce use of `Loader`s for the message lists
* [x] release and share with @bishwas-medic for testing

**Comment by estellecomment** [comment]
Some class names are shorter than 15 characters, which was so shocking I stopped reviewing.
@bishwas-medic is acceptance-testing, hooray!

**Comment by estellecomment** [comment]
Apart from shortening names LGTM!

**Comment by ngaruko** [comment]
Are you able to test this @bishwas-medic ? or shall we sick more insight from @alxndrsn on how to acceptance-test it?

**Comment by bishwas-medic** [comment]
Yeah, this feature is already been tested and released. Huge improvement in app load time.
