### ISSUE TITLE
People list filters default to smallest time unit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2766]
Currently the list filters on the people tab default to "view all". Change this to default to the smallest time unit for each list so only the most relevant items are displayed initially.

**Comment by garethbowen** [comment]
Fixed the defaulting. Also fixed a bug where tasks filter was filtering out overdue tasks when it should be filtering out tasks that aren't due for ages (future vs past).

**Comment by SCdF** [comment]
LGTM.
