### ISSUE TITLE
Review translations for People tab to ensure consistency

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2768]
Not sure which of the conventions to use : `Branch > Catchment Area > Household` (currently android projects) or `District > Branch > Catchment Area` (currently SMS projects)?

Discussion on design ticket:
https://github.com/medic/medic-design/issues/4

**Comment by SCdF** [comment]
Decision looks to be using SMS structure.

**Comment by SCdF** [comment]
OK so my looking through the existing translations on poeditor things don't line up right now.

Let's make a table to make things clear. shall we:

Internal Type | Current | Proposed
-------------|------|----------
district_hospital | District, sometimes Branch | District
health_center | Health Center | Branch
clinic | Sometimes Catchment Area, sometimes Clinic | Catchment Area

Can someone confirm ( @estellecomment / @diannakane / @abbyad ) that is correct?

Looking around the PO editior it's not clear that it's currently being used consistently. Or I'm reading it wrong.

**Comment by diannakane** [comment]
Hi @SCdF, does this help? 
![img_4244](https://cloud.githubusercontent.com/assets/1675870/19387269/d20566c6-9221-11e6-8cdf-8847d81cb4ec.JPG)

**Comment by sglangevin** [comment]
@diannakane that diagram implies that the default should be District, Branch, Area. Is that what you want for SMS projects? Earlier discussions had District, Branch, Catchment Area, so I'm just double checking.

**Comment by diannakane** [comment]
Our mockups show Area so let's keep it as Area. Everyone will recognize it
as the same thing.

**Comment by sglangevin** [comment]
Can we combine this issue with #2813? Then this issue could include a review of the default translation and updating those translations to be consistent.

#2813 was just to change the LHS button for admins to be "New Branch".

**Comment by garethbowen** [comment]
Done: https://github.com/medic/medic-webapp/commit/1fcf4b7d1a47dfb5e1614270664517feabe0d268
