### ISSUE TITLE
Adding a space to a select2 search term creates a request that returns > 150MB

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2769]
To reproduce (make sure you have the network tab visible first):

1. Go to a CHP Area
2. Click Edit
3. Click on the supervisor dropdown to bring up the search box
4. Type in the name of a branch, then wait until you see the `contacts_by_type_freetext` view request.
5. Type in a space.
6. You should see a second `contacts_by_type_freetext` view request with no key. If you keep waiting (about 4 minutes in production), it will download what appears to be every contact (about 190 MB in production), and the window might freeze.

Can we add in some sort of protection so that adding a space to the end of a search term can't start a whole new search (`contacts_by_type_freetext` request)? This may not fit in with how other searches work, but this can cause some annoying performance issues, including the web app freezing and search results taking a long time to be returned.

**Comment by garethbowen** [comment]
I've made the change to exclude empty queries.

It will still issue queries for single character searches which will perform better but not very well. The worst possible example of this is "a b" where the overall term meets the 3 character limit, but the term is split into two requests for one letter. While it's unlikely a user will type that, they are likely to type "sample c" which won't perform very well either. In other words I've improved the worst case but it's still fairly bad.

The only real solution for all possible queries in my opinion is to implement server side searching. @sglangevin please consider reprioritising #2370 if you think further improvements are required in this area.

**Comment by alxndrsn** [comment]
Nice bug, nice fix!

@garethbowen from the following I assume that we definitely want to support single-letter searches:

> It will still issue queries for single character searches which will perform better but not very well.

Is that the case?

**Comment by garethbowen** [comment]
@alxndrsn Currently for administrators we only search when 3 characters are provided, but that is controlled by select2 and without patching it we can't do a trim first. We could short circuit in the Search service itself but I couldn't think of a nice way to communicate back to the user that their term wasn't long enough, because again, the rendering is handled by select2. So admittedly this is a less than perfect solution but it gets rid of some simple edge cases before we get server side searching done.

**Comment by alxndrsn** [comment]
:+1: I'm very happy with it as an improvement over what we had previously.  Out of interest, what happens if an admin enters three spaces?!

**Comment by garethbowen** [comment]
Hah, yeah I was just wondering the same thing. I'll test.

**Comment by garethbowen** [comment]
Not good:

> contacts_by_type_freetext?startkey=["health_center",""]&endkey=["health_center","￰"]

**Comment by alxndrsn** [comment]
What would happen if you returned zero results from the service?  Does the user then see a _No results_ message?

We can probably just ignore this as a weird edge case anyway, unless this causes serious problems server-side.

**Comment by garethbowen** [comment]
It's mostly a client side problem in downloading and parsing all those results. It only affects admins so we don't hit any scalability limits.

**Comment by sglangevin** [comment]
Working well in v2.8.1-beta.2. Planning to do more acceptance testing on a server with lots of data.

**Comment by sglangevin** [comment]
Tested on lg-testing.app (recent clone of production) and search speed has greatly improved.
