### ISSUE TITLE
If initial sync fails without syncing anything subsequent syncs get no results

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2770]
If you only have the ddoc in your local db then the changes request is [incorrectly determined to be a app status watcher](https://github.com/medic/medic-api/blob/2.8.x/handlers/changes.js#L326) instead of a data replicator meaning it only watches for ddoc changes. This affects 2.8.0 and master.

The workaround is to clear your IDB and try again, but with some users the initial sync is likely to fail again, leaving them unable to use the app.

**Comment by garethbowen** [comment]
In master we no longer watch for ddoc changes because medic-client ddoc is replicated along with everything else, so referenced line can be safely removed.

In 2.8.0 we'll need to find some other way to determine if it's a ddoc change watcher or a sync (maybe a custom query param?).

**Comment by SCdF** [comment]
@garethbowen So if I understand these changes right, when we're watching just the ddoc we're skipping the medic-api magic time layer, and asking to proxy. Can non-admins do that? I thought that would allow bad stuff like bypassing our filter checks where we make sure you're not doing a full replication and getting data you're not allowed.

**Comment by SCdF** [comment]
@garethbowen nevermind my coffee hasn't sunk in yet, that's literally the code that you're changing!

**Comment by SCdF** [comment]
@garethbowen OK a fresh coffee in my hand, yeah this is fine. You're pairing proxying with the doc_ids filter and with just the ddoc, so the absolute best anyone can get out of this is changes to the ddoc and nothing else. LGTM!

**Comment by sglangevin** [comment]
Seems to be working in 2.8.1-beta.2, moving to Ready.
