### ISSUE TITLE
Gardener log rotation is hot garbage

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2776]
**edit** apparently it's gardener. So Gardener should just not rotate logs and leave it to logrotate

It's really really broken. I can't even work out what the rules are honestly, but here are my best guesses:
- `foo.log` is sometimes the latest log you should look at, as you'd expect
- but not always the latest, sometimes it's a random `fooXX.log`, where XX is a number that might be related to other numbers, but I'm not smart enough to work it out
- It is not clear, once a log file is full, what the next log file is going to be called
- It is not clear how long log files are kept for
- It is not clear why log files are deleted. I have been tailing a log file, which is the one being currently written to, only to have it completely deleted out from under me. Maybe it got moved or renamed? Who knowwwwsssssss
- Logs from ~12-24hrs ago are dropped, while logs from 6 months ago remain
- For some reason log files aren't called `sentinel.log`, or maybe `medic-sentinel.log`, but are instead called `medic_medic_medic-sentinel.log`.

I needs to be gone awayed. 

Instead, we should have standard normal every day human logging I feel like everyone else has had since the dawn of logging:
- `foo.log` is the current log file that is being written to. It is always this file, never any other file. You can `tail -F foo.log` and always follow the log output for that program
- Once this log file gets "full" it gets compressed and put in `foo.log.1.tgz`. If there is already a `foo.log.1.tgz` it gets renamed to `.2.`, and so on
- We could also rotate every day as well, if that excites people
- At some `foo.log.XXX.tgz` number that is sufficiently high that we're worried about diskspace usage, they get deleted.

_Or something_.

Here are some random examples off the internet: http://www.thegeekstuff.com/2010/07/logrotate-examples/

**Comment by mandric** [comment]
FWIW gardener does it's own log rotation, so that's probably what you're talking about.  The medic-api and medic-sentinel logs are handled by gardener.  Usually what I do is just list the logs sorted by last modified `ls -altr` in the gardener log directory to find relevant logs.  Also sometimes just do `tail -f /srv/storage/gardener/logs/*.log` when I'm lazy.  But yeah I agree the gardener log rotation is confusing.  But I think the medic-os log rotation just uses `logrotate`.

**Comment by SCdF** [comment]
Point taken. I've updated the title to reflect that.

**Comment by SCdF** [comment]
> Also sometimes just do tail -f /srv/storage/gardener/logs/*.log when I'm lazy.

Yeah this works sometimes, but I've had it freeze my ssh session for some reason.

The rest of the points, especially the one where we're dropping recent logs but keeping logs from 6 months ago, are still very important.

**Comment by browndav** [comment]
Yeah, gardener is the one service that doesn't use bog-standard `logrotate`, as the logs come out of `winston` pre-rotated and completely incompatible. We could either (i) disable rotation inside of gardener (`winston` constructor probably) and add a `logrotate` configuration, or (ii) fold this into a larger issue related to repairing/replacing a bunch of faults in gardener. I'm leaning toward the former for this one.

**Comment by SCdF** [comment]
@browndav agree on the former: while cleaning up / replacing Gardener is nice, it is presumably a long way away.

Having said that: let's say that I fixed this in Gardener right now, and push that to GH. What is the process for usefully getting that onto servers, including 0.4.x servers?

If it's a one click thing where we can upgrade existing servers that's great, if not then maybe we make cleaning up / replacing gardener as a 2.x goal and have it as another great reason to migrate everyone.

**Comment by garethbowen** [comment]
Replacing gardener made in on to our 2016 Q4 goals so hopefully it's happen in the next few months.

A patch would have to be manually pushed to the servers to fix them - it's not one click but should be simple enough. You'd also have to back up the existing logs I guess?

The more I think about it the more I'd like logs shipped to a log management server, eg: [AWS](https://aws.amazon.com/blogs/aws/cloudwatch-log-service/), [Raygun](https://raygun.com/). This would mean all logs are in one place, and we could get alerts on errors that are currently obscured. But this is a long term goal...

**Comment by SCdF** [comment]
> The more I think about it the more I'd like logs shipped to a log management server, eg: AWS, Raygun. This would mean all logs are in one place, and we could get alerts on errors that are currently obscured. But this is a long term goal...

I like the dream, but in the one instance I've seen that done in production it didn't actually help, and you ended up not using it (put an ineffective ui in front of an effective unix, you rarely care about logs from more than one server at once, etc). Sample size of one, ymmv, objects in mirror are closer than they appear etc.

(Also, agree it's scope creep, if we wanted to look into it would be separate ticket etc)

**Comment by estellecomment** [comment]
Seeing rotation keeping 9 old log files for no reason, and only 3 recent ones which is not enough. Annoying. (sindhuli)

**Comment by mandric** [comment]
In the meantime add this to your medic-os shells (~/.profile).  So when you type `logs` it gives you recent logs from api, sentinel and couchdb:
```
alias logs='tail -f `ls -1tr /srv/storage/gardener/logs/medic_* | tail -2` /srv/storage/medic-core/couchdb/logs/couch.log'
```

**Comment by SCdF** [comment]
@mandric your tip does not bring old deleted logs back unfortunately.

Just ran into this trying to solve an issue. Thought I'd get to the bottom of the logging system. Behold:
```
medic_medic_medic-api1096.log
 - 2017-03-29T20:04:50.383Z - 2017-03-29T20:44:18.334Z
 - 977kb

medic_medic_medic-api1097.log
 - 2017-03-29T20:44:18.337Z - 2017-03-29T21:23:59.820Z
 - 977kb

medic_medic_medic-api1098.log
 - 2017-03-29T21:24:00.149Z - 2017-03-29T21:39:06.060Z
 - 384kb

<855hr logging gap>

medic_medic_medic-api20.log
 - 2017-05-04T12:58:15.373Z - 2017-05-04T13:36:45.800Z
 - 977kb

medic_medic_medic-api21.log
 - 2017-05-04T13:36:46.441Z - 2017-05-04T14:16:26.901Z
 - 977kb

medic_medic_medic-api22.log
 - 2017-05-04T14:16:27.715Z - 2017-05-04T21:30:01.055Z
 - 709kb

<132hr logging gap>

medic_medic_medic-api6.log
 - 2017-05-10T09:36:00.601Z - 2017-05-10T10:01:37.847Z
 - 977kb

medic_medic_medic-api7.log
 - 2017-05-10T10:01:39.129Z - 2017-05-10T10:38:27.799Z
 - 977kb

medic_medic_medic-api8.log
 - 2017-05-10T10:38:28.792Z - 2017-05-10T14:30:00.718Z (NOW)
 - 147kb
```

So it seems like it keeps the latest 3 of a set of logs, and for some reason changes that set?

It makes no sense. It's really really dumb.

**Comment by mandric** [comment]
No my tip is just an easy way to tail the latest logs, sorry.

**Comment by SCdF** [comment]
This will be solved by Horti once that is rolled out. There is no specific work to do here, closing.
