### ISSUE TITLE
JSON forms don't show up in new People tab's action buttons

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2777]
Only XML forms show up.

**Comment by estellecomment** [comment]
This is actually not so simple. And it doesn't make a lot of sense until we have patients as Persons.

Todo, when we have patients as Persons:
 - [ ] show "create person" JSON forms on "CHW Area" pages (e.g. `clinic` level), and prefill medic-reporter's sender number with the Area's CHW's phone number (`clinic.contact.phone`)
 - [ ] show other JSON forms (i.e. forms which have a patient ID field) on patient's Person pages (patient ==  `person` whose parent is a `clinic`). Pre-fill medic-reporter's with:
  - [ ] sender number with the Person's CHW's phone number (`person.parent.contact.phone`)
  - [ ] patient ID (`person.short_id` or whatever that field is called)
 - [ ] don't show any forms on non-patient Person (e.g. branch manager, CHW) pages, or on non-clinic place  (e.g. Branch) pages.

Note: when we switch to xforms, we'll use Enketo webforms to fill in reports instead of medic-reporter, but the general approach still holds.

Question : 
 - When creating a Person by SMS, how is the parent place determined? I'm assuming it's by the sender's phone number, which we resolve to the CHW, and thus to the parent area. 

Problems when implementing the todo list above: 
 - Is there always a separate "create person" form? Are there other forms that create people? (e.g. create this person and mark her as pregnant) How can we get all of them? (for xforms, this would be the role of context, so maybe just switch to xforms)
 - When you send a report with someone else's number, the validation and error messages go to that number. So a CHW will get "Thank you for registering Mary as pregnant", out of the blue, when their manager registers Mary. Maybe we should have a separate form used by managers for creating Persons.

@garethbowen since you're doing the patient-centric stuff, do you have thoughts?

**Comment by garethbowen** [comment]
@estellecomment Yeah I have thoughts. Let's talk when we're both online next.

**Comment by estellecomment** [comment]
Alright! Much talking, and decision making!

In the current SMS-only setup, only managers are logged-in users. So any form-filling would mean that managers are sending reports on behalf of CHWs.
That type of action is currently doable in v0.4, but not really well supported and designed (it's hackable rather that comfortably doable). 

@diannakane is working on manager workflows for an upcoming redesign, that is out of scope of the current People tab redesign. We need more design work on this before jumping into implementation.
@garethbowen is the dev resource assigned to this redesign. (would be nice to link the medic-design issue here if/when there is one)

Closing!
