### ISSUE TITLE
Medic OS: cron.daily and related directories are broken and/or confusing

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#2778]
Our OS images currently maintain two sets of `.d` directories for `cron` – one ephemeral directory beneath `/etc` intended to be used programmatically by packages, and one beneath `/srv/settings/system-services/cron` that is persistent. This is confusing.

Make `/srv/settings/system-services/cron/*.d` the sole set of user-accessible `.d` directories, and symlink the `/etc` versions to the real ones. If the packaging system needs its own ephemeral `cron.daily` directory, create a new one and bury it somewhere where an SSH session doesn't mistake it for human-accessible configuration.

Finally, ensure that all of the cron `.d` directories are present beneath `/etc`. On current instances in production, only `/etc/cron.daily` is present.

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by estellecomment** [comment]
@browndav Is this still relevant?

**Comment by garethbowen** [comment]
Dave's not here man. Assigning to @henokgetachew for triage.

**Comment by garethbowen** [comment]
Closing this as I think it's no longer relevant.
