### ISSUE TITLE
If couch2pg fails when refreshing materialized views, updates may exist in couchdb that aren't reflected in the matviews

### ISSUE THREAD

**Issue by michaelkohn** [medic/medic-webapp#2780]
In the example below, 10 new documents were successfully inserted based on change feed 1826888, but then there was an error refreshing materialized views.  Since there was an error, couch2pg immediately tried to run again, but since the 10 new documents were successfully inserted, and the next feed (from 1826898) had nothing to process, it didn't try to refresh matviews again.  The matviews successfully refreshed when the next change feed had something to process, but there was a period of about an hour where there were records in couchdb but not reflected in the matviews.  

This is not happening super often, but in lower volume situations (ie lower refresh frequency and fewer docs being submitted/updated), the issue is actually exacerbated because data will be missing from matviews for longer.

```
Beginning couch2pg and xmlforms run at Thu Sep 22 2016 21:24:10 GMT+0000 (UTC)                                [263/2000]
Performing an import batch of up to 10 changes
Downloading CouchDB changes feed from 1826888
There are 10 changes to process
There are 0 deletions and 10 new / changed documents
Pulled 10 results from couchdb
Clearing any existing documents from postgresql
Inserting 10 results into postgresql
Batch completed with 10 changes
Performing an import batch of up to 10 changes
Downloading CouchDB changes feed from 1826898
There are 0 changes to process
Import loop complete, 10 changes total
Refreshing materialised views
XMLForms support failed
error: canceling statement due to statement timeout
    at Connection.parseE (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/var/adapter/{redacted}/medic-analytics/node_modules/pg/lib/connection.js:105:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
Run errored. Next run at Thu Sep 22 2016 21:29:10 GMT+0000 (UTC)
Beginning couch2pg and xmlforms run at Thu Sep 22 2016 21:29:10 GMT+0000 (UTC)
Performing an import batch of up to 10 changes
Downloading CouchDB changes feed from 1826898
There are 0 changes to process
Import loop complete, 0 changes total
Run complete. Next run at Thu Sep 22 2016 21:59:10 GMT+0000 (UTC)
Beginning couch2pg and xmlforms run at Thu Sep 22 2016 21:59:11 GMT+0000 (UTC)
Performing an import batch of up to 10 changes
Downloading CouchDB changes feed from 1826898
There are 0 changes to process
Import loop complete, 0 changes total
Run complete. Next run at Thu Sep 22 2016 22:29:11 GMT+0000 (UTC)
```

(cc: @SCdF @derickl @ngamita )

**Comment by SCdF** [comment]
@michaelkohn are you saying they are never represented, or they are just not represented this time around?

Them not being represented this time around is intentional. If there is a failure, it should run the whole process again immediately, and then if it keeps on failing with longer and longer delays up until the delay you configured. If refresh matviews is run and it succeeds then it should represent everything.

If refresh matviews is becoming too much of a performance burden then we need to think about:
 - Getting away from matviews, and extracting JSON ourselves in code
 - Reducing the frequency (which we can't do for LG, because of how they use it)

**Comment by michaelkohn** [comment]
@SCdF I'm saying they are not represented until the next time there are changes to process (and therefore tries to refresh matviews).  In this situation, the batch size was 10.  It successfully inserted 10, looked for the next batch of 10 but there were none, failed refreshing matviews, then didn't have any changes to process for another hour so matviews didn't try to refresh again until there were more changes to process.

My interpretation of this error log is as follows

**Thu Sep 22 2016 21:24:10 GMT+0000 (UTC)**
- `Change feed from 1826888` pulled 10 new records and successfully inserted them into PostgreSQL
- `Changes feed from 1826898` had nothing to process.
- Refresh matviews ran and failed.
- Since that refresh failed, `couch2pg` ran again immediately

**Thu Sep 22 2016 21:29:10 GMT+0000 (UTC)**
- Since `Changes feed from 1826888` was successful, it didn't need to be processed again so `couch2pg` started with `Changes feed from 1826898`.
- Since `Changes feed from 1826898` had no changes, `couch2pg` did not try to refresh matviews again

**Thu Sep 22 2016 21:59:11 GMT+0000 (UTC)**
- Since `Changes feed from 1826898` had no changes, `couch2pg` did not try to refresh matviews again

**Next run at Thu Sep 22 2016 22:29:11 GMT+0000 (UTC)**
- Refresh matviews has not been run since before the 10 records were inserted as a result of `Changes feed from 1826888`.  So 10 records were inserted at **Thu Sep 22 2016 21:24:10 GMT+0000 (UTC)** but we are at **Thu Sep 22 2016 22:29:11 GMT+0000 (UTC)** and matviews still don't have these 10 records.

**Comment by SCdF** [comment]
@michaelkohn right, so the problem could be summarised as: if an error occurs during matview refreshing, matviews refreshing is not attempted again until there is new data.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
@michaelkohn so to fix this I think we'd be breaking another request of yours right, which is to have errors result in the app exiting, so that upstart / whatever catches them? It also potentially changes some performance dynamics.

How would you like this to work? Should any error exit out, but also any successful pull of new changes results in running refresh as well?

We should chat on slack about implications etc.

**Comment by SCdF** [comment]
(Oh, I think we should fix this. It's almost certainly really easy to do)

**Comment by michaelkohn** [comment]
To add some context to future readers, `couch2pg` retries (indefinitely?) when certain errors happen.  These errors are logged in the .log file, but we don't have an easy way to notify someone if there is an error.  Since we are now running `couch2pg` in Upstart, we can surface errors to Slack if `couch2pg` dies, the problem is, `couch2pg` seldom/never dies, it keeps retrying.

If `couch2pg` comes across ***any*** error, we would like `couch2pg` to retry X amount of times and then kill itself so Upstart can surface the error, where X is an environment variable that we can set.

**Comment by SCdF** [comment]
I added a  `COUCH2PG_RETRY_COUNT` env var you can use, which will indicate how many times we want to successively fail before giving up on retrying and exiting.

I also changed how we determine whether or not to run the extra mat view code to include situations where we're not 100% sure if the prior run was successful. Specifically, first run, and if this run follows a run that errored.

**Comment by SCdF** [comment]
@michaelkohn these changes can be found in the 1.1.1 release.

**Comment by michaelkohn** [comment]
Thanks @SCdF .  @derickl And I will test this and hopefully upgrade on rdbms Monday.

**Comment by garethbowen** [comment]
Closing this for acceptance testing.

**Comment by ngaruko** [comment]
Has this been tested @michaelkohn and @derickl ?
