### ISSUE TITLE
The week/month is off by 2 in the Reporting Rates analytics dashboard

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2781]
Shadow ticket for https://github.com/medic/medic-projects/issues/699

**Comment by alxndrsn** [comment]
Does using `isoWeek()` in place of `week()` make a significant difference, or is it just neater somehow?  I'd have thought combining `isoWeek()` and `year()` (instead of `isoWeekYear()`) in the same code would lead to weird bugs some Januaries...

**Comment by garethbowen** [comment]
Good call regarding `isoWeekYear()`! I'll make that change.

> Does using isoWeek() in place of week() make a significant difference, or is it just neater somehow?

The reports are submitted with an integer for the week in EPI week format, which is poorly defined and non-standard, but fairly close to the ISO week standard. I think the only difference is EPI weeks start on Sunday and ISO weeks start on Monday. When searching for reports for "last week" for example, we need to use a standard that's as close as possible to the one the reports were submitted in, and `isoWeek()` is much closer than `week()`

**Comment by alxndrsn** [comment]
I don't understand the significance of the following, but it sounds bad:

> I think the only difference is EPI weeks start on Sunday and ISO weeks start on Monday.

**Comment by garethbowen** [comment]
@alxndrsn I think everyone uses a different week standard. The tech leads have signed off on using ISO week for their reporting. We could have the week standard be configurable but that's probably outside the scope of this issue.

@abbyad Does that match your understanding?

**Comment by abbyad** [comment]
Yes, that is my understanding too. We can have the design team chime in if further confirmation is needed, but believe that was already done in https://github.com/medic/medic-projects/issues/699.

**Comment by bishwas-medic** [comment]
Acceptance testing completed by me and Pawan. The issue is solved and everything looks good. Thanks team.
