### ISSUE TITLE
ContactsContent controller modifies doc on render

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2782]
The ContactsContentCtrl has lines like this: `selected.doc.isPrimaryContact = isPrimaryContact;`

This modifies the db doc so if we ever save the doc it will now accidentally contain an `isPrimaryContact`. `selected` was designed so that transient data like this could be stored _without_ modifying the underlying doc in any way.

Change the `isPrimaryContact` field to be directly on the `selected` model, and audit the controller for any other bugs like this.

**Comment by garethbowen** [comment]
Found another: `selected.doc.icon`

**Comment by garethbowen** [comment]
Might be a good idea to move `$scope.showParentLink` into `$scope.selected.showParentLink` where it makes more sense.

**Comment by estellecomment** [comment]
Did NOT think about that, good catch!

**Comment by garethbowen** [comment]
Accidentally committed to the wrong branch - ignore the first and last commits, and just review the second one (the one to master).

**Comment by estellecomment** [comment]
Cool thanks!

**Comment by garethbowen** [comment]
No AT required.
