### ISSUE TITLE
SMS not going out for `Scheduled Report Reminders`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2784]
I have configured Scheduled Report Reminders but never received any SMS.

Here is a sample of my test config on `diy.dev.medicmobile.org`:
![image](https://cloud.githubusercontent.com/assets/789512/18854147/6d161520-8417-11e6-94e3-ff2a766806fc.png)

**Comment by SCdF** [comment]
That same configuration in futon:
![image](https://cloud.githubusercontent.com/assets/583851/19037577/f166b828-896e-11e6-9d47-a937d699af14.png)

**Comment by SCdF** [comment]
@abbyad the code looks OK. Upon debugging your situation a little more, I noticed you don't have any clinics with phone numbers! Or at least, there are none in the `clinics_by_phone` view. In the current code, this determines who gets reminders sent to them.

Let me know if that code is wrong, if it should be looking somewhere else etc. But it looks like maybe you just need to finish configuring your test install with users

**Comment by abbyad** [comment]
I have one place with a real phone number (mine) because i had used it to test receiving reports. I can't confirm right now what level of the hierarchy it is, but regular forms have been associated to that facility so I would expect alerts should go out to it too.

**Comment by SCdF** [comment]
Sorry for the delay, just got time to look at this again.

So looking at what you've setup, you have a district hospital and a health centre (with the dh as its parent) setup with contacts attached to both.

@abbyad , what do you think the expected behaviour is? Currently we are just checking clinics with phone numbers attached (ie clinics with contacts with phone numbers). Do you think it should be to every "place", regardless of where that sits in the hierarchy? I presume this would be wrong for LG et al, because families are considered a place and are a part of that hierarchy.

**Comment by garethbowen** [comment]
I was working on the related issue #2779 so I had a quick look at this too. We have to be a little careful - if we relax this to send to all places then existing 0.4 instances will start sending messages to districts and health centers to submit forms which make no sense.

We could add a filter expression to determine if the place should get the message, eg: `place.type === 'clinic'`, and even have a migration to modify the config so it behaves consistently with 0.4, but this is a new feature request and not a bug so we should remove it from this iteration.

@abbyad Thoughts?

**Comment by SCdF** [comment]
I agree with what Gareth is saying.

Assigning to @abbyad for his thoughts.

**Comment by abbyad** [comment]
Thanks for figuring this out. It definitely makes sense to only send messages to the `clinic` level for now. If/when we need to send SMS to other levels we can open a feature request for that. 

I now have a `clinic` contact and will tested this successfully.
