### ISSUE TITLE
Tasks and History : display "No Tasks/History" message when empty

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2785]
See design spec about this, for History : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.m66hvcpz62q6

and for Tasks : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.kp0gezjp86z7

**Comment by estellecomment** [comment]
@alxndrsn please review! (you're the only one left on board)

**Comment by alxndrsn** [comment]
Some little comments on the commits.

**Comment by estellecomment** [comment]
Integrated all the comments. Refactored a bunch of things @alxndrsn, thanks for the detailed comments.

(first commit was in master, so I pushed to that, and the two others were in a branch, so I pushed to that, which makes things complicated, I will not do that again)

Rebasing the branch and merging.
