### ISSUE TITLE
Use default revs_limit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2787]
I recently changed the revs_limit to 1 to try and save a little space, but apparently that's a bad idea...

> the revs_limit determines how many historical revs are tracked (note that it is just the revs, not the content/body of each rev). If you set the value very low, Pouch/Couch may not be able to figure out whether a new revision it receives via replication is related to any it currently has so you could end up with conflicts

**Comment by SCdF** [comment]
Choice.

**Comment by garethbowen** [comment]
No AT required.
