### ISSUE TITLE
Log a warning when a translation value is missing

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2790]
Use the [$translateMissingTranslationHandlerLog](https://angular-translate.github.io/docs/#/guide/16_error-handling) to record to console when a missing translation value is requested.

**Comment by garethbowen** [comment]
Added a module to log a warning to the console if a translation value is missing. This revealed a missing translation value so I added that. But upon closer inspection it looked like the "back" and "close" titles were switched, so I fixed that too.

**Comment by garethbowen** [comment]
@estellecomment This should make it more obvious if we remove a translation that's still in use.

**Comment by estellecomment** [comment]
Awesome! Thanks!
