### ISSUE TITLE
Show number of Tasks per Person in Person list

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2791]
Right now it always says 0.
![image](https://cloud.githubusercontent.com/assets/911434/18952856/eb89d726-864b-11e6-9fc6-20298ba1ce81.png)

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-webapp/pull/2818

**Comment by SCdF** [comment]
@estellecomment please review :-)

**Comment by SCdF** [comment]
@garethbowen plz review :-)

**Comment by garethbowen** [comment]
Changes requested on PR.

**Comment by SCdF** [comment]
@garethbowen back to you

**Comment by garethbowen** [comment]
Done.

**Comment by diannakane** [comment]
Per user feedback, there's a change to this issue: if there are no tasks, don't show "0" bubble; show nothing.

**Comment by garethbowen** [comment]
I've split that change off as #2901

**Comment by ngaruko** [comment]
Not sure if we should reopen this to reflect #3028 or just make reference to it.

**Comment by ngaruko** [comment]
Sure. I will mark this as A/Tested and keep #3028 as is.
