### ISSUE TITLE
Release 2.9.0-beta.1

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2793]
### Release steps

* [x] Update app version (kanso.json, package.json, npm-shrinkwrap.json)
* [x] Merge to the release branch (use master for now)
* [x] Tag a beta release

**Comment by garethbowen** [comment]
@estellecomment I don't know what I'm supposed to do with this...

**Comment by estellecomment** [comment]
I'm trying to keep track of that work item above, which needs to be done along with the People tab redesign release. I assigned it to you because you've been doing releases so far.
Don't really know how to keep track of it, if this makes no sense close it.

**Comment by garethbowen** [comment]
Ok. Leave it as is and we'll add it to the release notes for 2.9.0. Anybody can (and should) do releases so I'll leave it unassigned.

**Comment by garethbowen** [comment]
I've fleshed out the todo list so this is no longer a placeholder.

**Comment by garethbowen** [comment]
Released.
