### ISSUE TITLE
Add icons to forms

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2794]
Make it possible to associate an icon to a form.
It's needed for the new People tab:
![image](https://cloud.githubusercontent.com/assets/911434/18984632/f3ef1ac2-86f3-11e6-9f1b-8a216884d6b3.png)

Question : do it for JSON forms as well?

(out of scope : add icons to existing projects)

**Comment by estellecomment** [comment]
If this is not priority enough, do kick it out of the milestone.
@garethbowen @abbyad

**Comment by garethbowen** [comment]
TODO:

* Refactor CSS for reuse in all lists and headers. At the moment it's scattered throughout the code.
* Refactor templates to use directives where code is duplicated.
* Fix the xforms upload script to set the icon value in the form doc.

**Comment by garethbowen** [comment]
I've split off the upload script patch as #2838

**Comment by garethbowen** [comment]
Code review: https://github.com/medic/medic-webapp/pull/2839

Screenshots:

The content of the people tab:
![people-content](https://cloud.githubusercontent.com/assets/2064938/19420932/8ec7c326-9452-11e6-8ad9-e3d033f243c6.png)

The content of the report tab (icon)
![report-header-with-icon](https://cloud.githubusercontent.com/assets/2064938/19420931/8ec75f08-9452-11e6-95e6-cdf14080f8fa.png)

The content of the report tab (no icon)
![report-header](https://cloud.githubusercontent.com/assets/2064938/19420930/8ec7876c-9452-11e6-9c20-6da4475d326e.png)

The report list (icon)
![reports-list-with-icon](https://cloud.githubusercontent.com/assets/2064938/19420934/8ec98fc6-9452-11e6-9351-edaa4cb785dc.png)

The report list (no icon)
![reports-list](https://cloud.githubusercontent.com/assets/2064938/19420933/8ec94fac-9452-11e6-89f0-7defa0d998ea.png)

The submit report menu
![submit-report](https://cloud.githubusercontent.com/assets/2064938/19420941/b7e8bbca-9452-11e6-946c-75ddda8c42c2.png)

Note that if going with forms, all reports should have forms. And as always, all icons should be square and the same size.

**Comment by SCdF** [comment]
@garethbowen added some comments, but otherwise looks good!.

Also just to confirm, I need to upload forms with icons locally before I see anything right?

**Comment by garethbowen** [comment]
Sorry I should have written some documentation about how to get them to show up...

For JSON forms: add an `icon` property to the `meta` property of the form. eg:

```json
...
"forms": {
       "P": {
           "meta": {
               "code": "P",
               "icon": "registration-lmp",
               "label": {
                   "en": "Pregnancy Registration LMP"
               }
           },
           "fields": {
...
```

For Enketo forms: add an `icon` property to the form doc, eg:

```json
{
   "_id": "form:assessment",
   "_rev": "60-998bd70217890111538f491a5398b34b",
   "internalId": "A",
   "title": "Assessment",
   "type": "form",
   "icon": "assessment",
}
```
