### ISSUE TITLE
If no permission to view Tasks, hide the section from People tab

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2796]
Since SMS projects don't have tasks, no use showing empty Task section.
(not sure how you figure out what type of project it is, maybe check if there's a tasks config? Or check if the RulesEngine is enabled? Not sure.)

Design spec about this : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.qizvdryusfeg

**Comment by SCdF** [comment]
AFAICT we already have this functionality via permissions:

![image](https://cloud.githubusercontent.com/assets/583851/19036821/40d53f6a-896a-11e6-817a-06d17fc50130.png)

While we could add a layer of automatically hiding it if there is no configured rules / no rules engine, but:
 - if you can't see the tasks tab maybe you don't have permission or maybe there is a configuration problem. Confusing!
 - Tasks / rules are used for more than tasks, maybe some people use targets but not tasks etc. Complexity!

We can set the default diy config to be unchecked if that helps.

@estellecomment IMO we should close this as `no action needed`, but I don't want to close a ticket with that response that I didn't raise.

**Comment by estellecomment** [comment]
Yeah that sounds good to me, thanks for checking!

There is work needed to do it though : if !can_view_tasks, don't show the tasks section in People tab. (right now it still does). Renaming the issue to describe that piece of work.

Not sure about the difference between can_view_tasks and can_view_tasks_tab. I don't really see why you would have one but not the other. 
Right now afaict can_view_tasks isn't used anywhere.

**Comment by estellecomment** [comment]
@garethbowen what did you have in mind for can_view_tasks vs. can_view_tasks_tab? When would each one be used? Is there a case for having one but not the other?

**Comment by SCdF** [comment]
IIRC the `can_view_tasks` vs `can_view_tasks_tab` is the difference between whether you can view it in the dropdown, or whether it is a tab. Could be wrong on that…

**Comment by sglangevin** [comment]
Yes, you are right, @SCdF. `can_view_tasks` means it will appear in the hamburger menu. If you want to view the tab, you have to have both permissions enabled. If you only have `can_view_tasks_tab` but not `can_view_tasks` then you'll see nothing.

**Comment by estellecomment** [comment]
Thanks for the input! So the work is : 
 - [ ] if `!can_view_tasks`, don't show the tasks section in People tab.
 - [ ] edit the default config to have `!can_view_tasks`

**Comment by garethbowen** [comment]
Done. I also hid the Reports section if the user doesn't have "can_view_reports".

**Comment by estellecomment** [comment]
LGTM!

**Comment by diannakane** [comment]
This will be improved in the new permissions config. Labels for permissions will be clearer and dependencies will be taken into account (you shouldn't be able to check both -- to have it in the hamburger menu and in the tabs)

**Comment by diannakane** [comment]
Two questions:

I'm logged in as Admin and neither "can_view_tasks_tab" nor "can_view_tasks" are checked in "full access" yet I see it in the Tabs. Is that what we expect? 

Another question: In "restricted to their place," both are checked. Do we expect one to supersede the other?

**Comment by sglangevin** [comment]
@diannakane for your first question, that is expected. Full Access doesn't apply to admins, admins are above full access users (at least the admin that we have set up on alpha.dev)

For your second question, you need both checked to see the tab. Checking "can_view_tasks" shows in the hamburger menu, if you also check "can_view_tasks_tab" then you'll see the tab, outside of the hamburger menu.

**Comment by diannakane** [comment]
OK, it sounds like this isn't a functional problem as much as it's a
usability one.

**Comment by ngaruko** [comment]
Wondering if a consensus has been reached here. As it is, there are two tabs that seem to lead nowhere (alpha.dev: tasks and targets). I understand it is because admins do not have neither tasks nor targets. Then, is there a reason why these tabs are displayed at all? Or are there cases maybe where admins can be configured to have (and/or be able to view) tasks and targets? Any thoughts @diannakane

**Comment by diannakane** [comment]
@ngaruko as far as I can tell, these tabs should be hidden. I've been reworking the permission profile settings so that these dependencies could be applied (e.g. if no tasks, no task tab shown).
