### ISSUE TITLE
Breadcrumbs (aka "Belongs to" field)

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2802]
Breadcrumbs in the "Belongs to" field in RHS. 
Description in design spec:
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.lx8wv35f2w1v

**Comment by garethbowen** [comment]
[PR](https://github.com/medic/medic-webapp/pull/2824)

Introduced a CSS only way of listing parents and refactored other places where the parents are shown to use the same technique.

**Comment by SCdF** [comment]
LGTM

**Comment by diannakane** [comment]
LGTM2
