### ISSUE TITLE
LG Device Storage Problem

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2805]
This is the meta issue for the mobile device storage problem.  We are attacking this problems in two ways: 
- minimize contacts, see https://github.com/medic/medic-projects/issues/592 
- find a way to use all the storage available on the device, see https://github.com/medic/medic-webapp/issues/2801

**Comment by alxndrsn** [comment]
Working on via https://github.com/medic/medic-webapp/issues/2801

**Comment by browndav** [comment]
Is there anything remaining in this issue that hasn't been split out?

**Comment by garethbowen** [comment]
@alxndrsn Can we call this done now?

**Comment by alxndrsn** [comment]
Seems reasonable.
