### ISSUE TITLE
Cannot view contacts on mobile due to new api usage

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2806]
To reproduce:
 - Use the mobile app
 - Open up contacts
 - Once it loads, tap on a contact

What should happen:
 - Contact view should be displayed

What actually happens:
 - Screen goes white with top bar displayed, with loading throbber
 - After a few moments you get punted back to the contact list
 - The following error is in the logs:

![image](https://cloud.githubusercontent.com/assets/583851/19085151/3a557220-8a61-11e6-850c-ed7470a6f410.png)

Notes:
 - Happens because `findIndex` needs Chrome 45 or higher

**Comment by estellecomment** [comment]
Thanks for the fix!
