### ISSUE TITLE
Tasks filter translations throw console error 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2807]
To reproduce:
 - Open a contact view, ideally one with tasks and reports associated with that contact

What should happen:
 - No errors in the logs, all translations should work

What happens:
 - Week translations look wrong:

![image](https://cloud.githubusercontent.com/assets/583851/19086423/fbaf64d6-8a65-11e6-8160-0b7a6286e448.png)
 - Errors occur in the logs:

![image](https://cloud.githubusercontent.com/assets/583851/19086442/0c2fee66-8a66-11e6-9223-f4e3a08a6f2d.png)

**Comment by SCdF** [comment]
So I cannot work out why months works but weeks throw this error. It appears to be a problem in the translation code itself, but weeks and months are identical:
```
n.week = {WEEKS, plural, one{1 week} other{# weeks}}
n.month = {MONTHS, plural, one{1 month} other{# months}}
```

**Comment by SCdF** [comment]
Ohhhhhhkaaayyyyyyyy.

So for funzies I changes `n.week`, `n.month`, `WEEKS` and `MONTHS` to `n.wek`, `n.mnth`, `WEKS` and `MNTHS` respectively. And now all the translations work.

I am guessing this is some kind of weird caching issue on my end?

@estellecomment / @alxndrsn can either of you confirm that this looks fine for you? If so I'll chalk it up to weird caching on my side and move on.

**Comment by estellecomment** [comment]
I'm not seeing any logged errors. I clicked on the filters, navigated away and back.

I fixed a problem like that (not sure it was this one though...) recently, there were extra `{{` that were producing errors. https://github.com/medic/medic-webapp/commit/2aef38cb5492e01c4124a645355f80d795d7a337#diff-b259c456057dd9b09be9a7f05704a0dcR195
Could that be it?

**Comment by SCdF** [comment]
I have the latest code, so IDK. I'm putting it down to something being cached locally on my system that I'm not clearly, possibly because translations are magic. It's clearly just My Problem™ though, so closing.
