### ISSUE TITLE
Task and Report filters don't seem to work anymore?

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2808]
![image](https://cloud.githubusercontent.com/assets/583851/19087242/378cff38-8a69-11e6-85d2-133855423848.png)

^ This seems to be the opposite of what I'd expect. If I have 3 months selected I'd only expect to see the last three months of reports.

**Comment by SCdF** [comment]
@garethbowen sorry this review is a long one!

**Comment by garethbowen** [comment]
Should have been done in a feature branch, and broken up into multiple commits. Code looks ok though.
