### ISSUE TITLE
Titles on mobile : swap header and page titles

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2811]
Final design for mobile : header says "<Place type>" for places, "Profile" for persons.
Place/Person name is at top of page, below header.
Primary contacts have "Primary Contact"/"Head of Household" on second line.

See design spec with screenshots : 
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.pq8c85f5su8t

**Comment by estellecomment** [comment]
This is almost done (see [branch](https://github.com/medic/medic-webapp/pull/2826)), except I just couldn't get the two-line titles ("Allison Jones \n Primary contact") to display next to the icon, not underneath, thus the WIP. (I did get it to work with flexboxes, but flex isn't supported in the old webview, so backed out of that.)

Also maybe tests.

Unassigning myself if someone wants to finish it up, otherwise I'll get to it.

**Comment by garethbowen** [comment]
I've requested a couple of changes - nothing major. Good job.

This is what it looks like now:

![household-header](https://cloud.githubusercontent.com/assets/2064938/19326028/45c997c4-9125-11e6-973f-3cfb31aea75c.png)
![contact-header](https://cloud.githubusercontent.com/assets/2064938/19326027/45c47f0a-9125-11e6-919a-08867f061c38.png)

It looks a little weird to me that the name of the person/place you're viewing is so tiny and hard to read, but it's consistent with the design, so not part of this review.

**Comment by estellecomment** [comment]
Ok, how's that? Cleaned things out a bit.
https://github.com/medic/medic-webapp/pull/2826

**Comment by garethbowen** [comment]
I've added a few more comments.

**Comment by estellecomment** [comment]
done!

**Comment by garethbowen** [comment]
Nice. There's a conflict now, but feel free to merge when ready.

**Comment by diannakane** [comment]
Looks good! Issue to center these titles is open under #2888
