### ISSUE TITLE
People list : same layout for mobile and desktop

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2812]
Final design for people list: same for mobile and desktop.

See design spec and mocks : 
For levels 1-2 : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.cyra4xy2ri3r
For levels 3 : https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.g64a4bnb085w

**Comment by estellecomment** [comment]
@SCdF please bestow the Stefan-approval.

Level 3 (Households) : 
![image](https://cloud.githubusercontent.com/assets/911434/19190798/ca22da24-8c9f-11e6-9418-7dad0417ad79.png)


Level 1-2:
![screen shot 2016-10-07 at 15 08 01](https://cloud.githubusercontent.com/assets/911434/19190839/fc385d36-8c9f-11e6-911b-c2ae3e7d0776.png)


I gave up on the little vertical bar separating the tasks : I couldn't get it to stretch all the way in height, or to get it to stay at a specific distance of the number. Trying to fix it was messing with bootstrap layout. I thought it wasn't worth the trouble.

**Comment by estellecomment** [comment]
wooops messed up places list nevemind don't review fixing

**Comment by estellecomment** [comment]
Both commits : https://github.com/medic/medic-webapp/compare/b0a45b5343c3342853928382c101794eb498bab0...master

**Comment by SCdF** [comment]
Cool beans

**Comment by diannakane** [comment]
Layout looks consistent to me. Other issues have been opened to deal with the translations and fields displayed.
