### ISSUE TITLE
Admins : LHS button should be "New Branch"

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2813]
Right now it's the generic version, "Add Place". 
See design spec:
https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit#bookmark=id.1anytbstx6by

**Comment by sglangevin** [comment]
@diannakane @estellecomment I thought you both decided that SMS projects would be the default configuration. If so, then this button should say "New District" instead of "New Branch".

**Comment by diannakane** [comment]
Right. SMS = district > branch > area 

(branch being synonymous with clinic)

**Comment by sglangevin** [comment]
I think you meant branch is synonymous with health_center (clinic is at the bottom of the hierarchy, so it's either area or family).

**Comment by diannakane** [comment]
Yes, thanks.

**Comment by sglangevin** [comment]
This is just a quick change to the default translation, right? Seems like we could combine this with #2768 and just do a final pass on all translations to make sure everything is correct.

**Comment by sglangevin** [comment]
Closing in favor of #2768.

**Comment by estellecomment** [comment]
It's not a translation issue : the issue is that it uses the generic term "Place", instead of the specific term for level 1 places (the translation part is picking between "Branch" and "District" or whatever, for that level 1 place label.). 
It also sends you to a generic "Create Place" form, without selecting the type of place.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2873

**Comment by SCdF** [comment]
Just one comment, back to you

**Comment by garethbowen** [comment]
Replied in the PR.

**Comment by diannakane** [comment]
This issue is still not resolved. Admin log-in should allow adding a “new district” on the main people tab page. 

![screen shot 2016-11-03 at 12 11 17](https://cloud.githubusercontent.com/assets/1675870/20060819/acd596ae-a505-11e6-93b9-ed993c89c91e.png)

**Comment by garethbowen** [comment]
This is now covered by https://github.com/medic/medic-webapp/issues/2890
