### ISSUE TITLE
Don't show Primary Contact label if no configured primary contact

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2815]
![no-primary-contact](https://cloud.githubusercontent.com/assets/2064938/19226115/3c686bb6-8f03-11e6-9813-e591b43c71fd.png)

**Comment by estellecomment** [comment]
thanks!

**Comment by diannakane** [comment]
One of our rules is that we must have a primary contact for every place. I thought this was a tech requirement, but if not then we can leave it as optional as you have done. @abbyad

**Comment by abbyad** [comment]
I don't think this is a technical requirement, unless we set it to be so in the creation/edit forms.

**Comment by diannakane** [comment]
In that case, I think it may be useful to show the empty Primary Contact
field if none has been selected yet. It shows you that this place has no
listed primary contact, which may prompt you to assign someone.

**Comment by garethbowen** [comment]
That makes sense. The label should be something like "No primary contact" instead of "Primary contact: ". We could show that label in the "Primary contact" field of the place card too.

**Comment by diannakane** [comment]
How about "Primary Contact: none"

**Comment by garethbowen** [comment]
Translation change: https://github.com/medic/medic-webapp/commit/38ba78c4c4c08ea4d08f08b53f5053bec5325b4a

**Comment by garethbowen** [comment]
![primary-contact-none](https://cloud.githubusercontent.com/assets/2064938/20124163/4b2a0702-a689-11e6-8107-5f3292d088fa.png)

**Comment by diannakane** [comment]
@garethbowen I don't see it listed here under "John Luck's Area"

![screen shot 2016-11-09 at 14 35 26](https://cloud.githubusercontent.com/assets/1675870/20138577/d4521dda-a689-11e6-8c51-3a15d4ae91fe.png)

**Comment by garethbowen** [comment]
@diannakane If you're looking at alpha.dev it looks like it's about 30 revisions behind so doesn't include this change yet. I strongly recommend you only test on released betas so you know it's reasonably stable. Also I recommend testing on your local machine in a vm so you can set up and test a configuration without anyone else messing with it.

**Comment by ngaruko** [comment]
If there is a case for #3042 that @estellecomment raised, then we expect this to be a non-issue: 
![image](https://cloud.githubusercontent.com/assets/6979995/21908942/c806185a-d97a-11e6-9ae8-47b74d380e6d.png)

**Comment by diannakane** [comment]
Reviewing the comment thread, it appears that we dont need to require
primary contacts and will include "none" where one hasn't been selected.
