### ISSUE TITLE
Inconsistent styling and overuse of bold on People tab

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2816]
The three sections of the People tab are inconsistent and use **bold** for almost all labels. This is visually overwhelming and confusing and makes it very hard to ready the important information. Redesign this so the important information is bold and supplementary information is more subtle.

Examples:

Reports:
![report](https://cloud.githubusercontent.com/assets/2064938/19226284/b077e688-8f05-11e6-8491-49032bc010b2.png)

Children:
![people](https://cloud.githubusercontent.com/assets/2064938/19226285/b07c1302-8f05-11e6-9fbd-5f7d1b46b702.png)

Tasks:
![tasks](https://cloud.githubusercontent.com/assets/2064938/19226286/b07df244-8f05-11e6-9000-99c5748f7f9e.png)

**Comment by garethbowen** [comment]
@diannakane Design input appreciated here!

**Comment by estellecomment** [comment]
@garethbowen The current implementation doesn't reflect the mocks (yet). Check out the Zeppelin mocks for styling : zpl.io/Z6oDCH

I filed this issue : https://github.com/medic/medic-webapp/issues/2709
It's probably not detailed enough, so just added detail to the original post, feel free to add more, and to rename the issue if needed, it's helpful.

**Comment by garethbowen** [comment]
Working on this as part of #2709
