### ISSUE TITLE
People attributes are missing horizontal separators in mobile

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2817]
When in mobile on the People tab all fields should be separated by a 1px border. Currently this isn't happening:

![missing-separators](https://cloud.githubusercontent.com/assets/2064938/19226319/22bfdc0a-8f06-11e6-997b-2b9c4b0369ac.png)

**Comment by estellecomment** [comment]
dammit that's probably me

**Comment by SCdF** [comment]
lgtm

**Comment by diannakane** [comment]
This appears to be displaying properly now.
