### ISSUE TITLE
Android dev: unable to access app menu with newer phones

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2821]
Our development android app has an app menu that allows you to logout, change URL, stuff like that.

On older Android phones (Tecno Y4) there is a dedicated hardware menu button (the hamburger button on the left)

On moderner Android phones that button is gone.

On phones with soft buttons (Tecno W4) it should appear as a soft button, as three vertical dots on the far right.

On phones without a menu button but also without soft buttons (Tecno L5)… I'm not sure what should happen. I presume there is an answer on the internet though.

**Comment by sglangevin** [comment]
@SCdF FWIW, I have found that on some newer phones, holding down one of the hardware buttons for a few seconds will make that menu appear. Not sure if that works for many or all phones, so having the three vertical dots on the far right is a better solution, but might be a workaround for now.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment]
Closing as ancient. Please reopen or recreate if this is still an issue on current builds of the Android container.
