### ISSUE TITLE
Test Chrome 52+ persistent storage using an Origin Trial key, report results

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2822]
We need to determine (i) if the Google Chrome Origin Trial keys for persistent storage work, and (ii) if successfully enabling persistent storage using an Origin Trial key removes storage quotas or provides additional flexibility.

**Comment by browndav** [comment]
Initial results: I'm seeing the origin trial key get picked up from a `<meta>` tag, and `navigator.storage.persist()` being made available, but actually calling `persist` seems to always return false (indicating that the request for persistent storage was not granted).

**Comment by browndav** [comment]
E-mail to the Google Origin Trials support team follows.

**Comment by browndav** [comment]
We've been testing out persistent storage for IndexedDB on Chrome 53, and have run into some trouble.

I have an HTTPS-only test site with a apparently-correctly-configured Origin Trial key (using the <meta> tag method), but am unable to get `true` back from the promise returned by navigator.storage.persist() – it's denied with `false` every time. If I remove the Origin Trial key, `navigator.storage.persist` is no longer available, so I have some measure of confidence the key itself is being picked up correctly.

I'm seeing this behavior on Chrome 53.0.2785.143 (OS X desktop and mobile), on an older Chrome Dev 53.0.2785.21 (Android 6.0.1, Nexus 6, MOB30I), and on the latest Chrome Canary (56.0.2887.0). My origin trial key was issued today at 10:29am, and expires on 11/22.

The test page is a multithreaded IndexedDB abuser that creates a bunch of large documents, and is publicly available at https://scri.pt/hacks/excessdb/. Here's essentially what's failing – after DOM ready on the main thread, I never get `true` back for `_is_granted`:

 <script type="text/javascript">
     document.addEventListener('DOMContentLoaded', function (_ev) {
       if (navigator.storage && navigator.storage.persist) {
         navigator.storage.persist().then(function (_is_granted) {
           if (_is_granted) {
             console.log('Persistent storage enabled');
           } else {
             console.log('Persistent storage was denied');
           }
         });
       } else {
         console.log('Persistent storage is unavailable');
       }
     });
 </script>

Does anything look obviously wrong with this setup? Is there any kind of CORS configuration or app manifest required beyond just calling `navigator.storage.persist()`?

I think I've ruled out any local browser setting issues (full reset with `rm -rf ~/Library/Application SUpport/Google/Chrome`), and have tried forcing the Origin Trial support to `Enabled` in chrome://flags to no avail.

**Comment by garethbowen** [comment]
@browndav This might be the reason why you always got `false`..

> Beginning with Chrome 55, Chrome will automatically grant the persistence permission if any of the following are true:
> The site is bookmarked (and the user has 5 or less bookmarks)
> The site has high site engagement
> The site has been added to home screen
> The site has push notifications enabled

From: https://developers.google.com/web/updates/2016/06/persistent-storage

I'm thinking we should start requesting persistent storage. It probably won't give us any more quota but it'll make it less likely to be cleared, and hopefully it'll magically start working soon. Maybe we can add another hack to Chromium to return true for one of the above...

**Comment by garethbowen** [comment]
Closing this as we've worked around the space issue by bundling with crosswalk.
