### ISSUE TITLE
PWA doesn't work because our manifest requires authorisation

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2823]
It looks like manifests can't require http authorisation for PWAs to work correctly.

To replicate:
 - Open our app in Chrome on your mobile phone
 - Open dev tools
 - Tap the "Add to home screen" button
 - Note that Chrome attempts to load the manifest, which fails with a 401
 - follow through with your add to home screen attempt
 - Note that only a normal link get created, not one that represents a PWA

**Comment by garethbowen** [comment]
I think the 401 was a red herring - the real problem was the manifest URL was incorrect, which meant it wasn't found. Now it works without firing another request to the server (ie: offline first).

**Comment by SCdF** [comment]
Awesome, nice one!
