### ISSUE TITLE
Extract getInitialData function from ContactsContentCtrl into service

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2825]
A lot of the logic in the controller is to do with generating the model object for the given contact id. Currently this isn't well tested because testing controllers is hard. Pull it out into a service and write unit tests to ensure it's working as expected.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by garethbowen** [comment]
Definitely worth doing and probably an easy win. Anyone can pick this up.

**Comment by garethbowen** [comment]
Actually, you know what, this is conflicting with the linked contacts refactor. Let me queue it up.

**Comment by garethbowen** [comment]
This is being reviewed as part of #2635

**Comment by garethbowen** [comment]
No AT required.
