### ISSUE TITLE
When resources change all icons disappear

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2830]
1. Go to the analytics > targets page and see the icon is displayed for a target (may need some configuration)
2. In another tab, as admin go to the configuration > icons page
3. Add a new icon
4. Go back to the analytics > targets page and the icon should still be there

For bonus points you can change the icon of the target and it should automatically update on the targets page (no refresh required).

**Comment by garethbowen** [comment]
The problem is that ng-sanitize strips out the `name` attribute - not sure why and not sure when this changed. Using `title` instead fixes the issue.

**Comment by SCdF** [comment]
LGTM
