### ISSUE TITLE
Restricted User without a home place downloads all contacts

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#2833]
That's not very restricted, would be better to show no contacts.

Unless it's being used for something? @sglangevin @abbyad ? 
(But if you want to see all contacts, then what you want is an admin user, of type "Full Access", rather than "Restricted Access" with no place)

**Comment by estellecomment** [comment]
Edit : the contacts aren't shown in People tab. But they're downloaded.

**Comment by sglangevin** [comment]
This isn't currently being used for anything - all restricted users have a home place - but wouldn't we want to have the ability for a user to store all this data offline? I'm thinking of the use case of a clinic with intermittent connectivity that is logged in as a restricted user so that they can view and manipulate their data offline on the clinic's computer. "Full access" users have to be online, so it seems like we should have an option for that type of user to have offline access.

**Comment by estellecomment** [comment]
That makes sense as a use case, yeah. If we want that though, I'd rather implement that type of user, than reuse the restricted user. It's pretty surprising and a potential privacy/security problem to have a restricted user that's not restricted.

All right, it's a bug! Thanks!

**Comment by SCdF** [comment]
So @estellecomment to be clear about what's happening, let me try to write the bug report and you can fill in the blanks / correct my mistakes. Note the (?) which are my big guesses:

--
Steps to reproduce:
 - Create a user that does not have a facilityId (?) set, or remove the facilityId from an existing user
 - On a fresh browser / app, start the app, so replication happens

What should happen:
 - All the documents that are relevant to the user are downloaded

What actually happens:
 - All the documents that are relevant to the user are downloaded, **as well as** all other documents of type `contact`

Notes:
 - The extra contacts are not displayed in the people and places view, are not searchable (?). They are in the underlying PouchDB instance though.

**Comment by garethbowen** [comment]
I think this is "by design". The other alternatives are don't download anything, or throw an error on login, neither of which are very user friendly.

For DIY there may only be one clinic and it would make sense to have CHPs able to view anything.

**Comment by garethbowen** [comment]
@estellecomment Get in touch - I'd like to close this as "by design". If the administrator has decided a certain CHP should see all information then there's no reason why we shouldn't support that use case.

**Comment by estellecomment** [comment]
As discussed : this is probably not great for DIY, but that'll come later, so closing.
