### ISSUE TITLE
First load: briefly displays "No people found" on the people and places tab even if you have contacts

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2835]
To reproduce:
 - Refresh browser etc, so you've got a cold instance
 - Navigate to the People and Places view

What you'd expect:
 - The page contains a loading throbber which after a time is replaced by your list of contacts

What actually  happens:
 - The page reports "No people found.".
 - After a time (occasionally multiple seconds, even on a fast phone) this text is finally replaced by a loading throbber, as expected

**Comment by garethbowen** [comment]
@SCdF Can you be more specific? Device? User type? etc...

**Comment by sglangevin** [comment]
I've also seen this on first load logging in as admin on desktop. I'd have to check to see if it's happening on mobile as well - can't remember.

**Comment by SCdF** [comment]
Wow OK, I swear I wrote a detailed description for that, with reproduction steps, **including a video** I recorded on my phone. Not kidding. I'll write some stuff again

**Comment by garethbowen** [comment]
Also results from the focus groups please.

**Comment by SCdF** [comment]
(interestingly this seems to be a GitHub bug!? I found the tab: I never actually submitted the ticket because I wasn't done with the description, but it looks like it submitted bits of it for me…)

**Comment by SCdF** [comment]
OK updated. Can't find the video, I have too many phones. Can always record again if it's not clear.

**Comment by SCdF** [comment]
_(Oh but you fixed it anyway, I didn't even notice!)_ No video recording needed!

**Comment by SCdF** [comment]
LGTM!
