### ISSUE TITLE
Targets tab doesn't go to the edge of the screen on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2836]
Seen on alpha.dev (2.9.0-alpha.4250), logged in as a restricted user.
![image](https://cloud.githubusercontent.com/assets/1286381/19417966/9619e996-93c2-11e6-9e60-70277adaceb8.png)

The gray pane containing the targets should go to the edge of the screen,

**Comment by SCdF** [comment]
LGTM!
