### ISSUE TITLE
Forms appear on the History page when they shouldn't, based on configuration

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2837]
Seen on alpha.dev (2.9.0-alpha.4250):
![image](https://cloud.githubusercontent.com/assets/1286381/19418015/01dd00ae-93c4-11e6-8f07-c52bc5ff6775.png)

For example, the Assessment Follow-up action shouldn't appear, based on it's configuration. Here is the context:
![image](https://cloud.githubusercontent.com/assets/1286381/19418021/21676c02-93c4-11e6-8c8a-41d947eb7b9e.png)

Based on the context, this form should appear only on person profiles where the person is under 12 years old (or has no birthdate recorded). Several other forms appear in this list that shouldn't be there, based on their config.

Has the way we configure context changed?

**Comment by garethbowen** [comment]
@sglangevin Are these forms hidden on 2.8.x?

The way it's designed at the moment is the context is only evaluated if there is a doc (eg: a person) selected. Obviously that doesn't apply in this case. It is expected that forms that require a person will have a person select field which is empty when invoked from the "Submit Report" menu and populated (and maybe readonly or hidden) when invoked with the patient in context.

As a user I think it would be confusing if only some forms were available through this menu and I can't see any technical reason for this requirement. What's the use case here?

**Comment by abbyad** [comment]
Although there may be cases that forms should be hidden from specific types users, I think what we are dealing with now are forms that only make sense with input fields populated based on prior form submissions. For instance, without the cause for a visit a followup form on its own does not make sense. Right now, the only way to populate those fields is from our task rules, which means the form should only be accessed as a Task.

**Comment by garethbowen** [comment]
@abbyad So do you think that all forms with a configured context should be hidden from this menu, or should we add an option to show/hide the form? (eg: `{ context: { required: true, expression: "" } }`

**Comment by abbyad** [comment]
I thought we already had a way to show/hide by putting the appropriate expression with `!contact`. If I am wrong about that I'll need to update [this answer](http://medicmobile.cloud.answerhub.com/questions/72/what-determines-how-we-set-the-context-json-file-f.html).

**Comment by sglangevin** [comment]
We did have that ability - I have this exact same configuration for this form on 2.8 and it does not appear on the History page. So this is a regression that should be fixed.

**Comment by SCdF** [comment]
LGTM
