### ISSUE TITLE
Upgrade LG to 2.8.2

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2842]
- [x] Review the LG upgrade checklist (and revise, if necessary)
- [x] Find a more permanent home for the checklist in Git
- [x] Perform a test upgrade using a cloned instance; characterize required runtime/effort
- [x] Schedule downtime for LG production
- [x] Perform actual production upgrade during off-hours (EAT)

**Comment by browndav** [comment]
Current upgrade checklist is located at https://gist.github.com/browndav/6eda2e77a8039c77514b2211db2e4d8b.

**Comment by SCdF** [comment]
FWIW I did a quick check and I'm pretty sure there are no view changes between 2.8.0. and 2.8.2

**Comment by browndav** [comment]
The `lg.app` production server is now at version `2.8.2`.
