### ISSUE TITLE
Should CHWs be able to edit their own area?

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2844]
As a CHW you can currently edit your area, which has the branch ID, which CHW is attached, who the supervisor is etc.

It seems like allowing people to edit the area they're attached to, to do stuff like detach themselves or what have you, could cause problems.

**Comment by sglangevin** [comment]
Can we create a permission for this? We don't want CHWs editing their own areas most of the time - it would be ideal to have a user permission for this as opposed to blocking it for everyone. If creating a permission is too much work, then it might be fine to block editing of your own place for all users as an interim solution.

**Comment by garethbowen** [comment]
We're unable to check permissions in the server side security check so I had to choose between the permission and the increased security of a server side validation. I chose the latter. We can look at how to implement the permission at a later date when it's needed.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2905

**Comment by SCdF** [comment]
Just one question, otherwise LGTM
