### ISSUE TITLE
Editing a report from a person doesn't pre-populate the person

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2845]
To reproduce:
- Be a restrictied user
- Navigate to a person / family / etc
- Tap on a report in the report section
- Hit edit

What should happen:
- The person gets prepopulated, and you skip past the first page where you select the person into the first "data" page

What actually happens:
- Either
  - You're on the first page, and the person gets prepopulated in the select2 dropdown
  - You're on the first page, and the person does not get prepopulated in the select2 dropdown
- Either way the first page is still part of the flow, and you can still edit the value and change it to someone else

Notes:
- This seems to work fine for admins for some reason
- If it doesn't get prepopulated this makes it really confusing and dangerous because to actually edit the form safely you'd have to get the patient name exactly right again, and you've lost context of where you are so it's not written on the page anywhere
- Not sure why select2 is sometimes populated and sometimes not, I imagine that's a select2 issue
- This is probably related to #2763, as it's presumably something to do with some kind of context not being set right

**Comment by sglangevin** [comment]
@SCdF this is also a regression as this was working properly for CHWs before.

**Comment by garethbowen** [comment]
@sglangevin Is the regression just that the person should be prepopulated, or that the person select page should be skipped, or that that person select should be readonly?

**Comment by sglangevin** [comment]
Previously, the person select page was skipped and we'd get right into the form when editing a report.

**Comment by garethbowen** [comment]
Related: #2197

**Comment by SCdF** [comment]
Reproduced: using lg.dev data locally, this URL results in a broken report edit http://localhost:5988/medic/_design/medic/_rewrite#/reports/edit/B8FA1743-0A51-48B6-8F22-53141C6AD1E6, or https://lg.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/edit/B8FA1743-0A51-48B6-8F22-53141C6AD1E6 in the wild (ish).

**Comment by SCdF** [comment]
This looks to be a form configuration issue: In the form used above, the convention for where the contact was stored changed, from `inputs>place>_id` in the old forms, to `inputs>contact>_id` in the new. This means that the newest version of the form doesn't attach the db-object (aka select2) widget to the correct node, and so select2 doesn't find the right data.

@sglangevin / @abbyad to fix this I imagine you'd have to change the form definition, or just conceded that old forms (from 2015-11) are broken. I imagine this is probably true for a lot of forms.
