### ISSUE TITLE
On mobile, from people and places tab, back button on creating a new place goes "back" to the user's home place

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2846]
To reproduce:
- Be a CHW on a phone
- Open people and places list
- Tap the + to create a new place
- Hit back, confirm that yes you want to close the form

What should happen:
- You should be back where you were: looking at the people and places list

What actually happens:
- Your home place (probably just whatever is first on the list) gets displayed.

Notes:
- This is due to how enketo form dismissal current works I think. Specifically, `$rootScope.$broadcast('HideContent');` staying on the RHS instead of potentially going back to the list view.

**Comment by sglangevin** [comment]
@SCdF you should only be able to add a person from a place page. So you'd have to be on an area or family page to add a person. If you hit back while you are editing the form, then you should be back on the place page where you came from. For example: go to People tab, click on CHW Area #1, click Add Person in the FAB, then hit back, confirm you want to leave the form and you should end up back at CHW Area #1.

**Comment by SCdF** [comment]
@sglangevin so right now on master I can see a + button at the bottom of the people and places search, as both a CHW and an admin. Are you saying that button shouldn't be there?

**Comment by sglangevin** [comment]
The + button at the bottom of the LHS (where search results appear) should only be for adding places, not people. If you want to add a person, you'd have to navigate to a place first, either your home place or another place you have access to.

**Comment by SCdF** [comment]
Oh **sorry**, I actually meant place. In my mind those are the same things (because they are on the technical record storing level).

I'll update the ticket to be clearer.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
I'm going to close this one. It was a huge amount of back and forth, with no clear resolution, and the entire conversation would really need to be re-thought and re-started. I think we're getting along for the moment.
