### ISSUE TITLE
Home place always shows even when searching for something that shouldn't show it

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2847]
This might be intentional and I'm just not the target audience, but it seems wrong to me:

![image](https://cloud.githubusercontent.com/assets/583851/19487366/6d92b216-955a-11e6-808f-76b1f44db090.png)

I would expect no results, but I always get the home place.

**Comment by sglangevin** [comment]
@diannakane @Lesterng any thoughts on this one? To me, seems like we would remove "my place" when searching but wondering what you had in mind.

**Comment by Lesterng** [comment]
@sglangevin @diannakane I agree with Sharon. This should return nothing.

**Comment by SCdF** [comment]
OK sounds like a bug, putting it in the sprint.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2865

**Comment by SCdF** [comment]
LGTM
