### ISSUE TITLE
Test SMS workflow in v2: Christian Aid

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2848]
Test the [Christian Aid configuration](https://github.com/medic/medic-projects/blob/master/christian-aid-2/app_config.json) running on `master` and raise any issues.

**Comment by SCdF** [comment]
Not really sure what I need to do to test this, but I figured I've give it a crack anyway.

So far:
 - Clean `medic` DB
 - Installed code from master
 - Used Christian Aid config and installed forms

![image](https://cloud.githubusercontent.com/assets/583851/19767337/41c59b8e-9c4a-11e6-8f07-1c0134c19db1.png)
Missing translation on branch view, area view etc.

![image](https://cloud.githubusercontent.com/assets/583851/19767396/8cdd9ff4-9c4a-11e6-8ca8-90d8e70052af.png)
 - Location widget doesn't look like it's styled right.
 - It also (intentionally?) doesn't fill in location from geo, just centres the map. I wonder if it's supposed to fill it in automatically.
 - Is probably a nightmare on mobile (not sure if this matters, don't know if CA would have CHPs creating households on phones)

![image](https://cloud.githubusercontent.com/assets/583851/19768817/e749ba30-9c50-11e6-85a5-de005e1cbd6d.png)
Default permissions look very wrong (Presumably this is a result of me uploading their app settings, but I figured I'd mention it anyway).

**Comment by SCdF** [comment]
Last thing I had issues with but didn't resolve was that restricted users were unable to load their contact. I'm not sure if this was due to a misconfiguration (maybe todo with depth), a bug, or both.

**Comment by sglangevin** [comment]
@SCdF this is an SMS project, so CHWs would not be using that form on their phones. They might register a person via SMS, but that would not involved viewing that registration form that you screen-shotted on mobile. That form is also just the default form and can be overwritten for any project, so I wouldn't focus on it so much.

I think we'll need to use medic-reporter to test SMS reports to make sure everything functions as it was functioning in v0.4. We may need to get the sequence diagram or form documentation to better understand how to test this.

**Comment by abbyad** [comment]
Does pushing a v0.4 `app_settings` to a 2.x instance automatically make the config compatible with v2? Are any manual steps needed?

**Comment by garethbowen** [comment]
@abbyad I think that works but testing that should be part of this issue. It comes down to if any migrations should be run on the configuration. The safer approach would be to upgrade an existing 0.4 instance because that ensures the migrations are run. You could then export the configuration from the 2.x instance and compare with the original.

**Comment by abbyad** [comment]
To test SMS in v2 we tested the following:
- DIY ANC config using TextForms
- Person-centered ANC workflow
- Assessment + service reporting with Collect
- ANC+Immunization workflow using SIM app
- Nurse enabled workflow, aka dual workflow with combination of SMS + app workflows
- Upgrade of v0.4 project to v2.9

Spawned off numerous issues that have been fixed and retested. In this process we've also come up with some steps needed for configuring SMS projects:

## To upgrade an existing instance
- Update via Garden Dashboard
- Add transitions (https://github.com/medic/medic-webapp/issues/2969#issuecomment-265628951)
- Upload people/place forms (#2828)
- Add `fields.` prefix in `app_settings` to form keys eg in conditions for a Conditional Alert (https://github.com/medic/medic-projects/issues/1133#issuecomment-264524722)

## To start a new SMS workflow project
- Fresh install from Garden Dashboard
- Add transitions to `app_settings` (https://github.com/medic/medic-webapp/issues/2969#issuecomment-265628951)

**Comment by garethbowen** [comment]
It looks like this is already ATed.
