### ISSUE TITLE
It's hard to tell between labels that are clickable/selectable vs those that are just labels

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#2852]
![screenshot_20161024-154927](https://cloud.githubusercontent.com/assets/3198821/19646440/0b076f54-9a02-11e6-9b55-f1b0c709175f.png)
Perhaps there should be a difference between the labels that are clickable and those that are not.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment]
THis is an older issue, but may still have some validity for design. Many aspects may already be resolved. Passing over to @diannakane to get a design team call before closing.

**Comment by diannakane** [comment]
We have a design that solves for this. Moving over to medic-design to track there until implemented: https://github.com/medic/medic-design/issues/61
