### ISSUE TITLE
Improve free text search views

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2853]
There are some inefficiencies in the free-text search views where they generate more data than they need to.

We should look at reducing the amount output produced, so save disk space, increase indexing speed and search speed / correctness.

**Comment by SCdF** [comment]
I also want to look at why we have two freetext views for contacts, I'm pretty sure that's not required anymore.

**Comment by SCdF** [comment]
Hey @garethbowen I've created two PRs:
 - https://github.com/medic/medic-webapp/pull/2861 tweaks how free-text views generate stuff to reduce cruft (as well as skipping a bit more, or in the case of reports, a lot more)
 - https://github.com/medic/medic-webapp/pull/2862 removes two views and their associated logic. Due to the massive simplification of the contact search UI I don't see how we can get to these pieces of logic anymore, but I could be wrong.

Let me know your thoughts.

**Comment by SCdF** [comment]
@garethbowen reminded me of select2s etc: I'm going to take another look to see if those two views are *actually* not used, and ideally see if we can add some e2e tests around it

**Comment by SCdF** [comment]
@garethbowen I dropped the second PR, comments on it. I made some changes to the first and it's back to you!

**Comment by garethbowen** [comment]
Beautiful!
