### ISSUE TITLE
Medic OS: Update to CouchDB version 2.x

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2857]

**Comment by alxndrsn** [comment]
I think this is blocked by:
* #2855 
* #2933 
* #2934
* #2935

**Comment by SCdF** [comment]
@alxndrsn there is a super ticket that is dealing with the various things that need to be done: **https://github.com/medic/medic-webapp/issues/2854**

It's not blocked AFAICT, it's upgrading medic-os so it runs CouchDB 2.0. There is no need to involve any of our code, just having medic os boot and have CouchDB 2.0 on 5894 is all that is needed.

**Comment by alxndrsn** [comment]
Tasks:
* [ ] update couchdb version in `platform/source/manifests/medic-core`
* [ ] remove or update couchdb-lucene version in `platform/source/manifests/medic-core`
* [ ] determine if `platform/source/medic-core-1.6.1/patches/couchdb-fix-user-properties.diff` needs updating or removing

**Comment by alxndrsn** [comment]
Blocked by https://github.com/medic/medic-os/issues/9

**Comment by alxndrsn** [comment]
@browndav could use some help with the above

**Comment by browndav** [comment]
On it. I'm thinking I'll merge this one-liner to `dev` so that medic-os/master will be a CouchDB 1.x branch and `dev` will be the next-gen CouchDB 2.x branch, since there are almost certainly other changes (e.g. concierge). I'll do this now and get a test build running. Will probably update Erlang simultaneously.

**Comment by browndav** [comment]
Taking this out of the current milestone in order to focus on production upgrades for now.

**Comment by browndav** [comment]
In sprint. Decision: Henok should be involved in this at all stages, both to assist (N.B. decreased productivity for me due to outside factors) and to maximize experience/knowledge transfer.

**Comment by alxndrsn** [comment]
Please fix https://github.com/medic/medic-webapp/issues/3387 as part of this work.

**Comment by garethbowen** [comment]
CouchDB2 is not prioritised for this milestone - removing.

**Comment by browndav** [comment]
This now works and fully bootstraps to our login screen on Docker. Moving to code review but holding off on an assignment until we do a quick demo.
