### ISSUE TITLE
Can't change the label on the first tab within Facilities for v0.4

### ISSUE THREAD

**Issue by smbuthia** [medic/medic-webapp#2859]
The partner would like the tabs within facilities to be relabeled from 'Districts' to 'Country' like is done for the other tabs using translation. There doesn't seem to be a translation for this.

![cb-districts-tab](https://cloud.githubusercontent.com/assets/1491710/19673318/402efe7e-9a87-11e6-8d0a-0c9d7f5d334b.png)

**Comment by garethbowen** [comment]
From reading through the code I think if you supply a translation key of "Facilities" it should just work: https://github.com/medic/medic-webapp/blob/0.4.x/lib/shows.js#L658

**Comment by garethbowen** [comment]
@smbuthia Can you please try modifying your configuration and see if it works?

**Comment by smbuthia** [comment]
@garethbowen I've tried that but this only changes the parent tab 'Facilities', what I'm trying to change is that tab that's currently labeled 'Districts' within the facilities.

**Comment by garethbowen** [comment]
@smbuthia Sorry I misread. Have you tried supplying a translation for "Districts"? Again, looking at [the code](https://github.com/medic/medic-webapp/blob/0.4.x/templates/facilities.html#L4), this should work...

**Comment by smbuthia** [comment]
@garethbowen I somehow still can't find this translation. Is it possible to provide a bit of direction or share a screen shot of where I can perform this translation? I've also asked the rest of the Tech lead team and the consensus seems to be that this tab cannot be translated.

**Comment by bishwas-medic** [comment]
@smbuthia this is a known issue as discussed here:
https://github.com/medic/medic-projects/issues/50

The workaround is changing one of the labels to "Districts" and assign the translation for it in the Advanced Configuration page.

**Comment by smbuthia** [comment]
This works, thanks @bishwas-medic 
cc @garethbowen
