### ISSUE TITLE
Transitions do not run for XForms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2864]
Based on a test that Sharon and I did, a XForm did not trigger a transition (act like a registration or patient report) despite being configured to do so. Use case is a nurse at a facility submitting form via app, which has come up often lately.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-sentinel/pull/86

Configuration is just like for JSON forms - put the form internal ID as the "Form" in the "Report Actions" section of the config. I chose not to configure any validations or response messages.

![config](https://cloud.githubusercontent.com/assets/2064938/19707904/4ff65c58-9b77-11e6-8227-1b48915e6608.png)

Configure the "Schedule" as you would for a JSON form. The "Timestamp Property Name" should probably be something like: `fields.lmp_date_8601`

![schedules](https://cloud.githubusercontent.com/assets/2064938/19707959/c0119552-9b77-11e6-9e3a-6fbe0c5f3b5b.png)

**Comment by SCdF** [comment]
LGTM. I've also updated medic-webapp to pull the latest sentinel.

**Comment by sglangevin** [comment]
Fields are picked up from within the message, e.g. `{{patient_name}}` but @abbyad and I were not able to get the messages to be sent to a number other than the sender. We had a field in the xform called `patient_contact_phone` and we listed the recipient of our SMS auto-reply as `fields.patient_contact_phone` but no luck.

**Comment by garethbowen** [comment]
@sglangevin Can you please try specifying the recipient as `patient_contact_phone` (ie: without the "fields." at the front)?

**Comment by sglangevin** [comment]
@garethbowen thanks, it's now working! Since there were no code changes, I think this can go straight to acceptance testing again.

**Comment by garethbowen** [comment]
Thanks Sharon!

**Comment by abbyad** [comment]
Tested in build 4373 and works well. Moving to Ready.
