### ISSUE TITLE
Text re-size within medic -Web app

### ISSUE THREAD

**Issue by jaymedic** [medic/medic-webapp#2866]
Text within the Web app on Android /Chrome was resized to Large without user changes upon login.

**Comment by garethbowen** [comment]
@jaymedic Can you give any more information? Was it "normal" first, and then on subsequent login became "large"? Can you take a screenshot of the UI?

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
Closing. We can re-open if anyone sees this again / we get more information.
