### ISSUE TITLE
Non admins can edit translations

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2868]
A restricted user (district manager or CHW) that has permission to see the Configuration tab can make changes to the translations for all users -- but probably shouldn't. They can see the other settings but cannot change them since they are not couchdb admins. This probably changed when translations was moved out of the app_settings.

**Comment by garethbowen** [comment]
Correct. We should modify the replication to server filter to exclude translations and anything else they shouldn't be able to change (eg: xforms).

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2872

**Comment by SCdF** [comment]
Merged.

Questions:
 - Is there still work to be done to stop users from being able to edit translations in the UI?
 - Is there still work to be done to stop this replication at the medic-api level?

**Comment by garethbowen** [comment]
> Is there still work to be done to stop users from being able to edit translations in the UI?

We have permissions that stop the UI from showing. The bug seems to be only if permissions are set incorrectly.

> Is there still work to be done to stop this replication at the medic-api level?

Good call. I'll create a new PR.

**Comment by garethbowen** [comment]
PR #2: https://github.com/medic/medic-webapp/pull/2877

This is a little difficult because we can't check permissions in the validate_doc_update - we can only check roles. This change allows db admins or national admins to change the core docs.

I also removed a function that wasn't used anywhere.

**Comment by SCdF** [comment]
I Strunk and White'd, back to you

**Comment by garethbowen** [comment]
Fixed and merged.
