### ISSUE TITLE
Dual login on medic Web app on Android

### ISSUE THREAD

**Issue by jaymedic** [medic/medic-webapp#2869]
-Upon entering link into Chrome on Android, 2 different login windows appear 
- one is in the browser window
- one is on the phone 

-Hardware Samsung Galaxy 4
-Android v 5.0.1

**Comment by browndav** [comment]
Are you able to grab a screenshot? Curious if it's an HTTP basic authentication popup overlaying the page area on the phone (e.g. http://i.stack.imgur.com/PNsXB.jpg) or something different.

**Comment by jaymedic** [comment]
![screenshot_2016-10-26-19-46-45](https://cloud.githubusercontent.com/assets/23031331/19736906/f8a7a78e-9bb9-11e6-8d4f-0632f42837ef.png)

**Comment by jaymedic** [comment]
The dual login occurs about 90% of the time

**Comment by alxndrsn** [comment]
Chrome version: `56.0.2924.87`

Cancelling the login screen doesn't seem to cause a problem.

The response headers for https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/ are:

```
HTTP/1.1 302 Unauthorized
Server: nginx/1.7.11
Date: Mon, 20 Feb 2017 11:51:17 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 61
Connection: keep-alive
X-Powered-By: Express
WWW-Authenticate: Cookie
cache-control: must-revalidate
Location: /medic/login?redirect=%2Fmedic%2F_design%2Fmedic%2F_rewrite%2F
X-Frame-Options: SAMEORIGIN
```

I would _guess_ that Chrome is misinterpreting the `WWW-Authenticate: Cookie` header...

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by estellecomment** [comment]
On chrome Chrome version: 56.0.2924.87, android 6.0, I don't see this happening. 
Closing, reopen if it happens again.
