### ISSUE TITLE
Deregister Changes callbacks

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2870]
Our controllers use the Changes service to register listeners for changes to specific documents. These listeners should be deregistered when the controller is destroyed. This will improve performance and also avoid bugs where we attempt to update the $scope after it's dead.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2871

I'm not 100% happy with the API here - if you have any feedback let me know.

I'm deregistering all callbacks registered in controllers on the $destroy event. Other uses of Changes (eg: from other services) will still run in the background. Services are not destroyed the way that controllers are so I think this is the correct behaviour.

**Comment by SCdF** [comment]
So the code looks fine as is, though I think at least maybe pull the changes keys out into a const instead of repeating them.

However, is it possible to change the `Changes` service to optionally take the `$scope`, and add the destroy logic written in the Changes service instead? Then the only code change for the callers would be passing the `$scope` when they init their changes watcher.

**Comment by garethbowen** [comment]
I really dislike passing $scope around because it couples the service to the entire angular model.

The other thing I thought about doing is having the Changes method return an object representing the listener which has a `unsubscribe` function, so you would hold on to that reference and then...

```javascript
$scope.$on('$destroy', function() {
  changesListener.unsubscribe();
});
```

@SCdF Is that better?

**Comment by SCdF** [comment]
So IMO ideally the Changes service would detect when it's being canned and unsub itself, but if there isn't the ability to do that you're not comfortable passing $scope around what you're proposing looks good.

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by SCdF** [comment]
Merged.

**Comment by garethbowen** [comment]
Nothing to AT.
