### ISSUE TITLE
Excessive whitespace in Contact select dropdowns

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2874]
![dropdown](https://cloud.githubusercontent.com/assets/2064938/19760469/66d704be-9c8e-11e6-9225-bd020e18da09.png)

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2875

Updated to look like...

![dropdown-fixed](https://cloud.githubusercontent.com/assets/2064938/19760585/dd2cb08c-9c8e-11e6-8392-3922694ff9c2.png)

**Comment by SCdF** [comment]
Merged.
