### ISSUE TITLE
Cannot fully replicate dbs behind medic-api due to badly named document

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2876]
We create a document to store whether or not the first install stuff should run:
![image](https://cloud.githubusercontent.com/assets/583851/19768009/748de942-9c4d-11e6-97f3-e4bfb2f57d19.png)
Because we hide CouchDB behind medic-api, and medic-api has an endpoint called "login", this value can never be replicated externally (e.g. you use admin credentials to completely replicate a DB from one place to another). The replicator sees it needs to download a document called "login" and then gets confused when it gets HTML back from `https://blah/login`.

We should fix this by changing the name of this document to something else.

**Comment by garethbowen** [comment]
@SCdF The only setup_complete reference I can find is in the ddoc app settings. Do you have any idea where this doc came from?

**Comment by SCdF** [comment]
@garethbowen This is from a completely fresh install.

Exact steps:
 - Nuke `medic`
 - Re-create `medic` to be an empty db
 - Run `grunt dev` over it
 - push Christian Aid's app config over it: 
```
scdf at SCdF in ~/Code/Medic/medic-projects/scripts on master
$ COUCH_URL=http://admin:pass@localhost:5984/medic ./upload_app_settings.sh ../christian-aid-2/app_config.json
```
 - Run medic-api to completion
 - Open the app as admin and click through all the steps that get thrown at you

**Comment by garethbowen** [comment]
Ok. It doesn't exist in my db, and I'm pretty sure it's being created by accident (maybe a redirect to login or something?). It'd be interesting to do each of those steps again to work out which one is creating the doc...

**Comment by SCdF** [comment]
I'm already mucking around in that area, I'll do it now

**Comment by SCdF** [comment]
OK those steps don't re-create it locally for me? I have no idea how I created it…

**Comment by SCdF** [comment]
I'm going to close this unless I can actually work out what I did...
