### ISSUE TITLE
Make medic-audit's view generation 8-∞ times faster

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2879]
# Problem

We are currently having performance problems in LG, **including being unable to write documents.**

This looks to be due to `medic-audit`'s single view taking far too long to generate. While it is a simple view:
- as audit logs get continually larger the efficiency of this view gets worse and worse
- because writing to `medic` must have a successful write to `medic-audit` first
- and because writing to `medic-audit` requires a successful read of the view
- and because a stale view blocks a view read

... we are rejecting writes.
# Fantastic solutions and where to find them
## Allow stale view reads

Difficulty: simple
Improvement: unknown
Caveats: unstable

If we allow for stale view reads for just that view (ie not for the whole DB), it may slightly improve performance, as writes can occur without the view completing generation. **HOWEVER**, this is almost certainly a bad idea, because it may result in multiple audit docs being created for the same document, causing all sorts of madness.

Suggestion: **NOT RECOMMENDED**
## Replace JS view with an Erlang one

Difficulty: simple
Improvement: 7-8x
Caveats: large initial view regen time

Here it is:

``` erlang
fun({Doc}) ->
  case proplists:get_value(<<"type">>, Doc) of
    <<"audit_record">> -> Emit(proplists:get_value(<<"_id">>, Doc), 1)
  end
end.
```

Re-enabling Erlang views, and replacing the existing view with this one, made the view generate 7-8x faster on my laptop (~10000 docs, ~35s vs. 4.5s). I imagine this improvement will increase as the JSON gets larger, because a key performance benefit is dropping JSON parsing.

Suggestion: **GOOD SHORT TERM FIX MAYBE**
## Drop the view completely

Difficulty: moderate
Improvement: ∞
Caveats: requires large migration

We don't actually need the view anymore. Because `medic` and `medic-audit` are separate, and because there is only one audit doc for any given real doc, we can massively simplify the process, and just use the same id for the audit record as we do for the real one. This also makes matching these documents up later more natural as well.

Doing this completely removes the need for a view, which removes the need to generate it, and block on its generation. I presume a direct GET is also much faster than a view query that returns one result, so it's a winner all round.

The obvious downside is that you would need to write a migration script that
- Creates `medic-audit-v2` database
- For each document in `medic-audit`, store it in `medic-audit-v2` with its `_id` changed to that of the document its auditing
- Drop and re-create `medic-audit`
- Replicate `medic-audit-v2` to `medic-audit`
- .... and now medic-api can start

The other downside to note is that you can no longer audit special docs, like ddocs or local docs. I'm not convinced we wanted to audit those anyway tbh, but we really do we could think up a naming convention for them (ie put "audit" in front of the name).

Suggestion: **RECOMMENDED LONG TERM FIX**
## Drop couchdb completely

Difficulty: moderate-high
Improvements: unknown
Caveats: unknown

We could also investigate no longer pushing to couchdb at all. A much simpler solution might be logging to disk an ensuring it's backed up, or picking a different technology that is much more optimal with its writes than its reads.

CouchDB is currently advantageous for us because a) if we ever wanted to access audit docs from the web it would be trivial to do, and b) we already have the dependency in our infrastructure.

Suggestion: **COULD BE LOOKED AT, BUT IMO WE SHOULD STILL DO AN ABOVE IDEA BEFORE THAT**

**Comment by alxndrsn** [comment]
IIUC, `audit` is a stream of events which is never read in real-time/"online".  If that's correct, for the long-term **Drop couchdb completely** gets my vote.

**Comment by garethbowen** [comment]
I like "Drop the view completely".

**Comment by garethbowen** [comment]
I think we can drop the view with a much simpler replication - because api blocks on startup we can:

1. drop the view
2. query all docs in batches and for each doc
  1. save a new doc using the `record_id` as the `_id`
  2. delete the old doc

Using bulk edits this could be reasonably performant.

**Comment by garethbowen** [comment]
I'm going with the "drop the view" option for now as it has a good balance of risk vs reward.

Steps:

1. Release a new version of couchdb-audit which assumes it's using a different db and make it clear this breaks backwards compatibility. I don't know of anyone else using it so this is probably no big deal.
2. Write a migration to change all the audit record IDs
3. Release 2.8.3-beta.1
4. Test on lg-testing to ensure auditing still works and the migration completes in a reasonable time

**Comment by garethbowen** [comment]
More detailed steps...

- [ ] release couchdb-audit 1.0.0 to use alldocs instead of the view
- [ ] update api with a migration to update the audit data and using couchdb-audit 1.0.0
- [ ] code review api ( @browndav )
- [ ] update sentinel to use couchdb-audit 1.0.0
- [ ] update webapp to use the new api and sentinel
- [ ] backport api, sentinel, and webapp changes to 2.8.x branch
- [ ] release 2.8.3-beta.1
- [ ] test the release on lg-testing and time how long it takes the migration to run
- [ ] release 2.8.3 final

**Comment by garethbowen** [comment]
The migration seems to have a couple of issues. Firstly it's slow, possibly due to enormous traffic_stats docs. Secondly the total docs in the database goes down when it was designed to delete precisely as many docs as it creates. More work needed.

**Comment by garethbowen** [comment]
@browndav Can I get a review of the latest commit, but also the concept in general? I think maybe we push this out to 2.9.0 and release #2886 in 2.8.3 mitigate the issue in the meantime.

**Comment by sglangevin** [comment]
@garethbowen how long will #2886 mitigate? 2.9.0 is a big update and it may not be pushed to production for active mobile app projects for a little while because it will require re-training of CHWs. I just want to make sure that we feel confident that 2.8.3 will work for the next few months before we move forward with splitting off this issue for later.

**Comment by garethbowen** [comment]
@sglangevin Good question! At this point we don't know of any docs that can cause this issue other than the traffic stats docs that were removed in #2886 so it should mitigate the problem for the foreseeable future.

**Comment by browndav** [comment]
I'm currently trying to work out the root cause, and hope to have some better collection of triggers/circumstances by Thursday or Friday. This might give us some margin of safety, i.e. some assurance that mitigation is viable.

**Comment by browndav** [comment]
This all looks good to me after a couple read-throughs. Should we figure out a way to test this migration on a production clone before we push 2.8.3?

**Comment by garethbowen** [comment]
Talking with @browndav we decided to push this migration back to 2.9.0. He's going to do some more investigation to ensure no other documents are close to the ~32MB limit to confirm nothing more is needed in the short term.
