### ISSUE TITLE
Compress form-content

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2882]
We store the raw report xml in the data_record so we can edit the report at a later date. In a randomly selected report from production I found the record is 18.4kb of which 5.6kb (~30%) is the form content.

However this is the raw size, not the size on disk, so firstly confirm the size of the record on disk in couchdb and pouchdb to see if they're doing any compression.

If they're not, experiment with compression options to save disk space on phones and the server. Simply removing whitespace reduced the size of the form content to 3.7kb. As we don't use the field for indexing (as far as I'm aware) we could zip the field to reduce the size to 1.2kb.

If you decide to zip the field we need to manage backwards compatibility. We probably can't migrate every single record to the new format, so we'll need to detect at runtime whether the content needs to be unzipped or not.

**Comment by garethbowen** [comment]
Scheduling for 2.9 as this should be a fairly quick win.

**Comment by garethbowen** [comment]
I created 1000 docs in pouchdb with various levels of compression...

Method | IDB size (MB)
-----|------
Original |          14.0
Stripped |     12.8
Compressed |    13.3
Stripped and compressed |     13.1

[fiddle](https://jsfiddle.net/za3qaqrv/)

I'm surprised that whitespace stripping is the best option, but possibly that indicates IDB is doing some compression in the background.

It works out quite well for us because whitespace stripping is valid xml, readable, and backwards compatibly so it's the easiest to implement. So I'll go ahead and implement whitespace stripping...

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2883

**Comment by garethbowen** [comment]
@alxndrsn code review please!

**Comment by alxndrsn** [comment]
mmmm `xmlString.replace(/>\s+</g, '><');` is the whitespace stripping?  Looks likely to introduce nasty little problems.  _Ideally_ this would be done specifically on the context of text nodes.

**Comment by mandric** [comment]
Are you sure those sizes are based on compressed data?  How do you know the IDB is compressed?  And what level of compression?  Afaict we have no way to query this information.  IDB is still somewhat of a black box to us.  https://rawgit.com/google/leveldb/master/doc/impl.html

**Comment by garethbowen** [comment]
@alxndrsn What it's doing is stripping the whitespace from between xml tags. For some reason the xml we get is formatted so it has indentation and new lines between tags. What nasty problems are you concerned about? Just doing regex on xml in general?

@mandric I don't know anything about IDB compression because as you say it's a black box. If you look at the fiddle all I'm doing is asking pouch to store 1000 documents and then seeing how much space that takes up. I ran the tests in the latest Chromium. I expect it does some compression of the data and that's why my manually compressed version performed poorly. Stripping whitespace from between xml tags will help any compression and should be safe and quick to use. What's your concern? That this actually makes things worse?

**Comment by alxndrsn** [comment]
> What nasty problems are you concerned about? Just doing regex on xml in general?

I guess the latter.  It looks like it only strips whitespace from tags with nothing else in between them, so there are probably some improvements that can be made - e.g. trimming whitespace from start and end of text.  It doesn't look like it would handle `CDATA` properly, which may be a surprise if we include binary data such as photo submission in forms.

**Comment by mandric** [comment]
@garethbowen my concern is this introduces added complexity without much of a win.  I think just running the fiddle doesn't compress anything, it's likely writing to a log (level 0) which is uncompressed at the IDB level iirc.  I think chrome does the level db compression in spare cycles, idle time or when resources are low, similar to browser memory garbage collection.  I don't know of a way yet to test the actual storage usage of IDB data fully compressed.

**Comment by garethbowen** [comment]
Updated stats:

The execution time is per doc averaged over 1000 executions, on the Tecno Y4 using the latest Chrome. Updated [fiddle](https://jsfiddle.net/za3qaqrv/1/).

Method | IDB size (MB) | Execution time (ms) |
-----|------|-----
Original |          14.0 | 2.3
Whitespace stripped via regex |     12.8 | 2.5
Whitespace stripped via xml walking | 12.8 | 12.0 
Compressed |    13.3 | 36.5
Whitespace stripped via regex and compressed |     13.1 | ???

**Comment by garethbowen** [comment]
@alxndrsn @mandric @browndav : I've updated the results with the XML walking option and included an execution time column. I didn't test Alex's alternate regex - I'm confident it'll get very similar numbers for both size and execution time as original regex. Feel free to edit the fiddle if you want to try it out.

Regex is almost free (0.2ms penalty) and gives the best equal results. XML walking is moderately expensive (9.7ms penalty) and also gives the best equal results. The XML walking code isn't trivial but it's not that complicated either and it's probably quite a lot safer than regex. I'm leaning towards regex because it's cheap and appears to work well.

Thoughts?

**Comment by mandric** [comment]
Hrm on the fiddle I'm getting about 1.5 seconds (1500 ms) to parse 1000 docs.  Doesn't that mean 1.5 ms to strip whitespace from a doc via XML parsing?

**Comment by mandric** [comment]
Ok that test was on desktop version of chrome.  My bad, ignore that comment.

**Comment by garethbowen** [comment]
It turns out removing the whitespace from the form definition removes it from the submitted form, so it'd better to modify the form upload script to strip the whitespace.

**Comment by garethbowen** [comment]
Deprioritising as it's not longer a quick win and it's not a priority. This is difficult to do in the bash script so we should do it as part of https://github.com/medic/medic-webapp/issues/2900

**Comment by SCdF** [comment]
NB: CouchDB [does compress a lot of stuff including XML by default](http://docs.couchdb.org/en/2.0.0/config/misc.html#attachments/compressible_types), and IndexedDB gets compressed in [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=81384) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=715019#c1).

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-webapp/pull/3036

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
This is not a priority right now and it seems like the decision was to implement this as part of #2900. Closing in favor of #2900.
