### ISSUE TITLE
Can't create new person as primary contact to existing place

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2884]
It appears that I'm not able to create a new person when assigning a primary contact to an existing place, only to a new place. 

Existing place:
![image](https://cloud.githubusercontent.com/assets/1675870/20003996/472c98ea-a292-11e6-8c6b-a42ccf77cb26.png)

New place: 
![image](https://cloud.githubusercontent.com/assets/1675870/20004004/53a3d14c-a292-11e6-8458-ae8f430814d9.png)

**Comment by garethbowen** [comment]
@alxndrsn PR for you please: https://github.com/medic/medic-webapp/pull/2887

**Comment by SCdF** [comment]
LGTM
