### ISSUE TITLE
Nginx: `worker_connections` are not enough while connecting to upstream

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#2885]
We're frequently hitting the currently-configured `worker_connections` limit of 1024. Understand this setting, pick a more appropriate value, and update `medic-os` to ensure that the new setting will be applied to all instances on update.

**Comment by garethbowen** [comment]
[We've hit this before](https://github.com/medic/medic-webapp/issues/2076) on lg.app and decided 10240 would be fine. We've been running with 10240 in production for over six months with no known issues, so my recommendation is to bump it to 10240 in medic-os.

FWIW 2.9.0 will roughly halve the number of connections established.

**Comment by garethbowen** [comment]
I've set it to 10240 which is production tested as sufficient with no known negative side effects.

**Comment by garethbowen** [comment]
@browndav Review please.

**Comment by browndav** [comment]
LGTM, moving to ready.

**Comment by ngaruko** [comment]
I will assume this issue has been sorted (by bumping the number of connections on lg.ap), unless I hear otherwise.
