### ISSUE TITLE
Improve traffic stats performance

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2886]
Every time the app is started on android we record the data usage in a `traffic_stats` document. This looks something like...

```json
{
   "_id": "326241E2-D309-FC17-A0A8-8F9F53C66803",
   "_rev": "47-5ceff167159e69220c0d7e4783470959",
   "type": "traffic_stats",
   "user": "districtadmin",
   "traffic": [
       {
           "app": {
               "tx": 3470353,
               "rx": 75593264
           },
           "system": {
               "tx": 7393910,
               "rx": 131266433
           },
           "timestamp": 1464577835042
       }
   ]
}
```

Each user has only one of these docs which is continuously updating by appending the latest data to the `traffic` array. This is then replicated to the server and the change is audited. Auditing permanently stores each revision. This means the traffic_stats doc has n traffic entries, _and_ the audit doc has n revisions the last of which has n traffic entries. In other words we're storing `n^2 / 2` entries where n is the number of times the app has been started by the user.

This caused problems recently where one user had restarted the app 600 times which created a 32MB audit doc which crashed the couchdb view builder. This solution does not scale.

### Solutions

1. **Stop auditing the `traffic_stats` doc**. Currently we audit everything but we could add a filter that ignores docs of certain types. This solves the immediate problem. The `traffic_stats` doc will still grow without bound so it'll continue to take up more and more space on the phone. It'll also get replicated to the server every change using increasingly more of the data cap.
2. **Stop replicating the `traffic_stats` doc**. This also stops auditing as above, with the additional benefit of not using up any of the data cap. This means we cannot query the data on the server but can query and display the information somewhere locally in the app.
3. **Stop updating the `traffic_stats` doc**. This also stops replication and auditing as above, with the additional benefit of not using disk space on the phone. The data could still be logged to console but we would lose any ability to look at historical data usage.
4. **Record each traffic item in a separate `traffic_stats` doc**. This means we'll get lots of small docs instead of a few very large ones the former being preferred by couchdb. This reduces the auditing space requirements because docs will be effectively immutable. This also reduces the replication cost because we'd only replicate the latest stat, not the entire history. The downside is that in order to query the data we'd have to add another view which is bad for performance.
5. **Limit the length of history recorded**. We could store the last n stats by continually dropping the oldest one when the limit is reached. 
6. **Don't update the traffic stats as often**. Clearly some users restart the app frequently (600 times over 6 months is roughly 3 times a day!). We could reduce this to recording the history once a month at most.
7. **Record traffic as a running total**. Depending on what this information is used for we could record aggregate data only, eg: we could only record average data usage per month.

We need to decide what aspect of this information (if any) is useful. Is it being used currently? If not, why not? What use case are we trying to solve?

As this affects a production instance it is to be fixed in the upcoming 2.8.3 release.

Please vote for your preferred option (or options) below!

**Comment by estellecomment** [comment]
> What use case are we trying to solve?

See https://github.com/medic/medic-webapp/issues/1777 : we were trying to assess how much data we are using and whether it's a problem. We've measured it already for a "stable internet" case. This `traffic_stats` doc was meant to get measurements in the real-life shaky internet case.

> Is it being used currently?

I don't think we've ever used the data so far. 

Partners haven't complained so far about data usage, that I know of (@sglangevin ?).

I'd vote : snapshot the `traffic_stats` docs we have collected so far and store the data somewhere, and then stop collecting it (solution 3 above), it's not worth the trouble it's causing right now. 
We can set it back up later if needed when we want to address the data usage problem (and collect it differently if the way it's done now isn't optimal for replication).

**Comment by SCdF** [comment]
I also vote for dropping it. I also think if we care about it in the future it would be a good excuse to look at developing our injectable stats collection doo-dad, as we've talked about on and off (https://github.com/medic/medic-webapp/issues/2031)

**Comment by garethbowen** [comment]
In today's iteration planning meeting we decided to go ahead with option 3, stop recording traffic stats. We'll leave existing ones on the server so we can retrospectively look at traffic usage if required.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2896

If/when this passes Code Review it needs to be backported to 2.8.x

**Comment by SCdF** [comment]
Merged.

**Comment by garethbowen** [comment]
AT: start the app on mobile, wait for sync, repeat a few times, ensure that no docs of type `traffic_stats` are updated on the server.
