### ISSUE TITLE
Households appearing at the wrong level in hierarchy 

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2889]
Households are appearing as belonging to the branch, not areas. I'm not sure if this was user error in the demo data creation or confusion about what place types belong in the default config. Note that households don’t belong in the default SMS config at all. Related: #2888 

Should I fix this manually by deleting the families and relabeling all of the places to bring them line with the labels? (e.g. "branch" listed under district, "areas" listed under branches)

![screen shot 2016-11-03 at 12 32 58](https://cloud.githubusercontent.com/assets/1675870/20060512/2d8729ae-a504-11e6-808c-2fb0775018aa.png)

**Comment by sglangevin** [comment]
This appears to be due to the user who added the household. As in, if the admin is logged in and goes to an Area, then clicks Add Household (or Family), the Household is added to the user's place instead of at the appropriate place in the hierarchy (Area from which Add Household/Family was clicked).

**Comment by abbyad** [comment]
We should keep an eye out for avoiding this situation when building the default forms in #2828.

**Comment by diannakane** [comment]
The type of place you are adding should be restricted to the appropriate
type of place, depending on where you are adding it from in the hierarchy.
That will solve this problem.

From the spec:

Adding a new place of the type I manage is in the LHS FAB, below the list
of places of this same type.
e.g. for CHWs this is households (mockup), for Branch Managers this is
areas (mockup). For admins, it’s the top-level place (see mockup).

If you are a user that views multiple levels of places, you can add a
sub-place to a place  you manage in the RHS FAB (e.g. for a Branch Manager,
you add Areas on the LHS, because you directly manage these, and add a
household to a specific area on the RHS). The sub-place will be added to
the Place whose card is showing on the RHS.

**Comment by garethbowen** [comment]
This seems to be working on 2.10 alpha, tested by creating a [family](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/4ec99abeef859c206acbd885b155ba7e) by clicking the add family button on the RHS action bar after selecting an area as admin.

Closing so this can be acceptance tested and reopened if I've missed something.

**Comment by abbyad** [comment]
I have retested and this is fine with the new SMS workflow forms. The issue as reported was due to the form configuration for that project since places were created relative to the logged in user's place.

@diannakane if you see this problem on a SMS workflow project please open a new issue.
