### ISSUE TITLE
"Up" button at bottom of place/person pages

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2894]
Include an “up” button at the bottom of the page to help with scrolling, as described in:

Zepelin mocks -- see comments: https://zpl.io/2tsIvg
People tab spec -- https://docs.google.com/document/d/1UwSe8H3xykvOUwu65KxJYgBTxv40Y_9b3CPgRbcXOH0/edit?disco=AAAAAz9B4nY

**Comment by sglangevin** [comment]
Duplicated in #2937 - closing this one as that one has more discussion.
