### ISSUE TITLE
Calling the `doc_summaries_by_id` view results in an audit record being created

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2895]
Weird one.

I deleted my audit db to clear it out, and then-- without recreating my db-- went to view the history page as admin.

This resulted in a request to `medic_client/doc_summaries_by_id`, which returned a 500.

In `medic-api`'s logs, there was the following error:
```
ERROR { Error: no_db_file
    at Request._callback (/Users/scdf/Code/Medic/medic-api/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/scdf/Code/Medic/medic-api/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
  name: 'Error',
  error: 'not_found',
  reason: 'no_db_file',
  scope: 'couch',
  statusCode: 404,
  request:
   { method: 'POST',
     headers:
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/medic-audit/_bulk_docs',
     body: '{"docs":[{"_id":"659a34eff4c50c56f158 ... blah blah, the docs I requested ...
```

It looks like for some reason calling that view results in medic-api trying to create an audit document. If I re-create the audit db, it does just that, creating a weird non-sensical audit trail for my view request:

```json
{
   "_id": "659a34eff4c50c56f158f8dd5600949f-audit",
   "_rev": "1-6ca83f1ff0e2d937097dd269ae4fa977",
   "type": "audit_record",
   "history": [
       {
           "action": "create",
           "user": "admin",
           "timestamp": "2016-11-07T18:15:04.035Z",
           "doc": {
               "keys": [
                   [
                       "D873ACFC-7A2A-CD5F-8488-CD34CA18EAFA"
                   ], ["...AND THE OTHERS..."]
               ],
               "_id": "659a34eff4c50c56f158f8dd5600949f",
               "_rev": "current"
           }
       }
   ]
}
```

**Comment by SCdF** [comment]
I also think, while we're on the subject, that medic-audit should be created by medic-api if it doesn't already exist. It presumably used to do this when there was a ddoc to deploy, but it should continue doing it even when it's just a dumb db.

**Comment by SCdF** [comment]
This is occurring because the `doc_summaries_by_id` call is POST, presumably to make sure the arbitrary number of document ids we pass all make it through OK. It doesn't look like we're doing it specifically, looks like PouchDB is choosing.

Worth considering what rules we can think of to avoid auditing reads even if they are POST requests. It might be enough to know that because we block all ddoc writes elsewhere, we can allow un-audited POST requests on anything that contains `/_design/[^/]+/`.

**Comment by SCdF** [comment]
Also worth noting that presumably this is not a result of the recent changes to Auditing, but has actually been happening for yonks. If it's possible to work out when this has happened and delete them from the audit db that would be ideal, though I suppose not required.

**Comment by garethbowen** [comment]
I noticed a few audit trails like that in the LG prod server but hadn't had a chance to track them down. Good catch.

**Comment by SCdF** [comment]
PR (with some explanatory comments from me) here: https://github.com/medic/medic-api/pull/101

**Comment by garethbowen** [comment]
Overall good improvements. I've added some clarity suggestions but otherwise LGTM.

**Comment by SCdF** [comment]
@garethbowen minor changes we talked about, thought I'd just get you to confirm this one instead of insta-merging.

**Comment by ngaruko** [comment]
Does this need AT'ing @SCdF ?

**Comment by SCdF** [comment]
@ngaruko I'm guessing you decided it didn't based on your tag change. Let me know if I misunderstood.
