### ISSUE TITLE
Messages, People, and Targets tab headers snap to the RHS when scaled down from web to mobile

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2898]
Logged into alpha.dev as admin on my desktop. When I drag the browser into mobile size, the Messages, People, and Targets tab snap to the RHS view, losing the tab header. The other tabs maintain the tab header as expected.

Furthermore, this only happens SOMETIMES! I just did it again and it maintained the tab headers. Then did it again a second later, and it snapped to RHS. No pattern I can identify.

**Comment by estellecomment** [comment]
Could you share screenshots? I'm having trouble understanding what's going on exactly.

**Comment by diannakane** [comment]
I wanted to upload a video but couldn't find an easy way to record my screen. 

It basically goes from both panes: 
![screen shot 2016-11-09 at 14 10 21](https://cloud.githubusercontent.com/assets/1675870/20137966/6673d84c-a686-11e6-9780-3a8ef04916e4.png)

to the RHS when resizing the window:
![screen shot 2016-11-09 at 14 10 25](https://cloud.githubusercontent.com/assets/1675870/20137970/6ac880f0-a686-11e6-925c-500d1a988e94.png)

It should go to the LHS.

I can screen share on our call this afternoon if that helps!

**Comment by SCdF** [comment]
@diannakane on OSX you can use Quicktime to record your screen! Open up Quicktime Player, and go File -> New Screen Recording. HTH :-)

**Comment by diannakane** [comment]
Oh, I knew that trick and forgot it!! Thanks for the reminder. 
[#2898.zip](https://github.com/medic/medic-webapp/files/580676/2898.zip)

**Comment by abbyad** [comment]
That looks like what I'd expect to see, so I am not sure this is a bug. When you have something selected on the LHS in mobile you would be seeing that item in the RHS - which is what happens when you go from desktop to mobile view.

**Comment by diannakane** [comment]
@estellecomment and I figured this out. It acts this way if something has been selected on the LHS and is displaying on the RHS. Closing the issue.
