### ISSUE TITLE
When the Primary Contact for a place belongs to another place, it doesn't appear on the place page

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2899]
In alpha.dev, logged in as admin. I am viewing Dave's family, which appears to have no primary contact. 
![screen shot 2016-11-08 at 16 28 10](https://cloud.githubusercontent.com/assets/1675870/20102991/d08e53e4-a5d0-11e6-87c0-f714d80b5535.png)

I click on "edit place" to assign the primary contact and see that one is already selected. "Janet Jones" belongs to another household so we don't expect to see her on the list of Family members. 
![screen shot 2016-11-08 at 16 27 58](https://cloud.githubusercontent.com/assets/1675870/20102981/c1b9748e-a5d0-11e6-89ad-b43234d8dd9d.png)

She is listed as the Primary Contact in the list view for Dave's Family, but nowhere on Dave's Family Place page. 
![screen shot 2016-11-08 at 16 34 36](https://cloud.githubusercontent.com/assets/1675870/20103127/6437cfb2-a5d1-11e6-9906-50f3480bb617.png)

Some ideas for how to handle this:
-- list Janet Jones as the Primary Contact at the top of the Family page and link to her person page from there, similar to how we include the "primary contact" designation at the top of a person's page. 
-- list Janet Jones as the Primary Contact in a field within the place card and link to her page from there. 
-- list Janet Jones' name and Phone number in a field within the place card so you can dial her direct from there, without navigating to another page.

Any thoughts? 
cc: @Lesterng

**Comment by estellecomment** [comment]
Before figuring out how we want to do this, is this something we want to support?
What's the use case for having a Primary Contact that doesn't belong to the place it's contact for?

**Comment by diannakane** [comment]
Good question. This will be an edge case but I'm confident that we'll get
requests for it. Some examples: a neighbor being the primary contact for a
child-headed household; a CHW or other person being primary contact for a
household that doesn't have a phone; a manager as the primary contact for
multiple health facilities, or a CHW responsible for multiple areas.

We could probably buy ourselves some time from implementing a solution to
this, but in the meantime we could prohibit listing a primary contact who
does not belong to the place to eliminate the confusion.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by estellecomment** [comment]
This is working now. Closing.
