### ISSUE TITLE
add support for creating forms like POST /api/v1/forms 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#2900]
This might also include some basic validation (it is valid XML and our parser can parse it) and optimization (remove unnecessary whitespace).

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
No current use case.  Please re-open when required.
