### ISSUE TITLE
Don't show task count bubble if person has no tasks

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2901]
Per user feedback if there are no tasks, don't show "0" bubble; show nothing.

cc @diannakane

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2902

**Comment by estellecomment** [comment]
Comment on commit : https://github.com/medic/medic-webapp/commit/5297d488918f115641a42088abcd4a53d7ed5e96#commitcomment-19769270
