### ISSUE TITLE
Upgrade did not migrate the app_settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2903]
Going from v0.4.13 to v2.8.2 the app_settings was not migrated as expected. Only changes were the addition of `forms` and `_id` and the change to the value of `_version`.

Would have expected the `translations` to be removed, `permissions` added, and likely some other changes too.

**Comment by garethbowen** [comment]
My guess is that [passing `null` into update_settings](https://github.com/medic/medic-api/blob/master/migrations/extract-translations.js#L67) doesn't work as expected.

**Comment by garethbowen** [comment]
My bad - that migration doesn't run for 2.8.2. Should've read more clearly...

**Comment by abbyad** [comment]
Seems to be as expected when moving to v2.9.
