### ISSUE TITLE
Upgrading does not remove translations from app_settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2904]
Going from `2.8.2` to `2.9.0-beta.3` the translations were updated, but not removed from app_settings.

**Comment by garethbowen** [comment]
It's working in the integration test... will have to try and replicate an actual upgrade.

**Comment by garethbowen** [comment]
I can't reproduce this and I can't work out how it could happen looking at the code. It might be due to the double upgrade (0.4 -> 2.8 -> 2.9) doing something illogical. We can check the meta doc to see if the upgrade completed successfully. When we test the upgrade again we should check this...

**Comment by alxndrsn** [comment]
> When we test the upgrade again we should check this...

Please re-open if the problem recurs.

**Comment by abbyad** [comment]
Just did an upgrade from `0.4.13` to `2.9.0-alpha.4553` and the translations are now `"translations": null` - so it seems to be working fine now.

As Alex said, we can re-open if problem recurs.
