### ISSUE TITLE
`db-object` fields show as editable when `readonly="true()"`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2910]
When a field has `readonly="true()"` it should be disabled so that the user cannot edit it - but db-object fields still _appear_ to be editable. 

![image](https://cloud.githubusercontent.com/assets/789512/20271573/3aec3698-aa59-11e6-9d3d-b7b4dc455ef5.png)

![image](https://cloud.githubusercontent.com/assets/789512/20271596/4d9712c2-aa59-11e6-829e-23b5390519f0.png)

String fields are properly disabled, as shown in the second field.

**Comment by garethbowen** [comment]
@alxndrsn Code review: https://github.com/medic/medic-webapp/pull/2918

**Comment by alxndrsn** [comment]
Probably good enough for our current usage, but will the `disabled` attribute be updated if the value of `readonly` changes?

**Comment by garethbowen** [comment]
You're right - it won't update. I went in to try and fix that but couldn't get readonly to toggle on a string field either and almost all the examples I could find showed `readonly=true()`. In medic-projects we only ever have `readonly=true()` so like you say this should do for now...

**Comment by abbyad** [comment]
Works well to disable the field -- moving to Ready.

Without Read Only
![image](https://cloud.githubusercontent.com/assets/789512/20364042/b7142e62-ac0f-11e6-9987-9851fcc706ca.png)

Ready Only Mode:

![image](https://cloud.githubusercontent.com/assets/789512/20364096/e52428fc-ac0f-11e6-92c5-aa333b54509e.png)

The field label looks different, but that is consistent with other disabled fields in Enketo.

**Comment by alxndrsn** [comment]
Label looks the same in your screenshot.  If you mean the field itself, I think it would be quite confusing for users if appearance did not change for read-only fields...

**Comment by sglangevin** [comment]
I think he's talking about "Belongs To" which is bold without read-only and not bold when in read-only mode.

**Comment by alxndrsn** [comment]
Thanks, Sharon!  I guess in CSS it's related to the text `Marc District` being bold when the field's enabled - I'd guess the de-boldening is being applied at the wrong level.
