### ISSUE TITLE
Data binding does not occur if `db-object` field is pre-populated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2911]
Selecting a value from the the select2 of a db object field binds associated fields accordingly, but if the db object field is pre-populated there is no binding to the associated fields.

This is required for #2828 and #2333.

**Comment by abbyad** [comment]
Labelled as priority because it will unblock creation and testing of Person/Place forms.

**Comment by garethbowen** [comment]
PR: https://github.com/medic/medic-webapp/pull/2917

@alxndrsn If you'd be so kind.

**Comment by alxndrsn** [comment]
LGTM - merge away

**Comment by abbyad** [comment]
Works well! Moving to Ready.
