### ISSUE TITLE
Support additional context for hiding/showing actions

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2913]
Our context for displaying actions is currently limited to the information that is collected during person or place registration. Ideally, we should enable information from report/action forms to be used as context. For example, only show the New Pregnancy action for a woman who has not recently been registered as pregnancy (has an EDD in the future). Other examples would be showing an Update EDD action for women who are currently pregnant and only showing the Newborn Visit action for women who are currently pregnant.

There are many more examples of this that will be coming up in the next year as we look at more context-aware actions.

**Comment by garethbowen** [comment]
Do not merge this into `master` until the `2.9.x` branch is created.

**Comment by alxndrsn** [comment]
Would it make sense for the extra profile data mentioned in https://github.com/medic/medic-webapp/issues/2914 to be attached directly to the contact doc?  This would seem to make implementing context-aware actions mentioned in this ticket much simpler.  Having some more examples beyond EDD would help to evaluate implementation options.

**Comment by sglangevin** [comment]
Another example that is upcoming: we will be doing family surveys to determine the family's wealth quintile and we may want to use that result as context for specific family or person actions. For example, families in lower quintiles might get additional follow-ups for pregnant women or we might ask extra questions during registration for immunizations for children.

The key is being able to pass information from a report to the contact so that we can have additional context for future actions and bring in additional information to other forms.

**Comment by abbyad** [comment]
Yes, as mentioned in https://github.com/medic/medic-webapp/issues/2914#issuecomment-260469273 saving the info to the contact's profile is a good approach to make it part of the context for a contact's actions.

**Comment by garethbowen** [comment]
This is now configurable. CR done with #2914.

**Comment by ngaruko** [comment]
Refer to #2914. Moving it to 'Ready'.
