### ISSUE TITLE
New place doesn't show on LHS after creation

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2919]
A newly created place at the same level of the LHS should show in that list immediately after creation, but only does so after a full page refresh

**Comment by abbyad** [comment]
This is an intermittent error, because I have just seen this working properly. Not sure yet under what conditions it fails.

**Comment by SCdF** [comment]
You may wish to try admin vs. restricted, it could be something to do with that

**Comment by abbyad** [comment]
I'll keep note of that. I was still logged in as admin when it failed and then later worked. Will provide more info if I can reproduce.

**Comment by abbyad** [comment]
I've seen it occur again. Once in this state I can reproduce it consistently, but I still don't know how to get into this state where it doesnt show in the LHS.

No errors in console when creating the new place, but have these errors from before which may help - especially relevant seems to be the `Error watching for db changes`.

![image](https://cloud.githubusercontent.com/assets/789512/20314807/79a0a02e-ab29-11e6-82da-28ff032e858c.png)

After that there is: 
```
inbox.js:9 Error watching for db changes 

Application Cache Checking event /medic/_design/medic/_rewrite/#/contacts//add/district_hospital:1

Application Cache NoUpdate event /medic/_design/medic/_rewrite/#/contacts//add/district_hospital:1

Failed to load resource: the server responded with a status of 502 (Bad Gateway) https://v2-test-person-centered-anc.app.medicmobile.org/medic/69829c4c3c318e258878839efc6eb2e2? 

inbox.js:9 Error setting up ContactsContentCtrl Object(anonymous function) @ inbox.js:9

2x Failed to load resource: the server responded with a status of 502 (Bad Gateway) https://v2-test-person-centered-anc.app.medicmobile.org/medic/org.couchdb.user%3Aadmin? 

inbox.js:9 Error fetching user settings Object(anonymous function) @ inbox.js:9
```

**Comment by SCdF** [comment]
It's not 100% clear from the docs, but it sounds like if the changes feed errors out it will just drop it. I'm going to try to confirm that, but the fix would be that on error we above we attempt to reestablish the connection after a short period of time.

**Comment by SCdF** [comment]
Hey @estellecomment take a look at the PR: https://github.com/medic/medic-webapp/pull/2923

**Comment by estellecomment** [comment]
Cool! See comments.

**Comment by SCdF** [comment]
Hey @estellecomment I updated the PR, take another look.

**Comment by garethbowen** [comment]
Reviewed and merged.
