### ISSUE TITLE
Item in LHS remains selected when creating new place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2920]
When clicking New District the previously selected place on the LHS remains highlighted:
![image](https://cloud.githubusercontent.com/assets/789512/20294700/24f2bc98-aace-11e6-9fcd-dc5b845d4758.png)

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-webapp/pull/2924

@alxndrsn if you would be so kind.

**Comment by alxndrsn** [comment]
LGTM

**Comment by SCdF** [comment]
@ngaruko and I AT'd this.
