### ISSUE TITLE
Errant select2 dropdown

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2927]
If you are in a select2 dropdown and go back to another page the dropdown remains on the page until you do a full page refresh.

![image](https://cloud.githubusercontent.com/assets/789512/20364369/e8ae82d2-ac10-11e6-82ad-6864f52b7383.png)

**Comment by garethbowen** [comment]
@estellecomment PR for you please: https://github.com/medic/medic-webapp/pull/2928

**Comment by estellecomment** [comment]
If there's any way to do that in the enketo code, as a cleanup function of some kind, rather than add more setup stuff in inbox.js, that would be nice... But this works.

**Comment by garethbowen** [comment]
This bug affects _any_ page with a dropdown, not just Enketo ones, eg: Configuration > Settings > Default country code, then click back:

![not-just-enketo](https://cloud.githubusercontent.com/assets/2064938/20466079/103f072c-afd1-11e6-8721-a43ed33f577b.png)
