### ISSUE TITLE
CouchDB2.0 API version check

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2931]
As 1.x and 2.0 are not compatible, add a check to the start of API to make sure that the CouchDB that they're connecting to is the right version.

This is mostly important for our transition to CouchDB2.0 (in medic-webapp 3.0), though we could also backport this code to block usages of couchdb 2.0 on existing code as well.

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-api/pull/105

**Comment by SCdF** [comment]
@garethbowen review plz. Note that this PR intentionally merges into the meta ticket's branch

**Comment by garethbowen** [comment]
Cleanup, aisle 2!

**Comment by SCdF** [comment]
@garethbowen  Take it to the bridge!

**Comment by garethbowen** [comment]
Lovely!
