### ISSUE TITLE
Test Couch2PG with CouchDB2.0

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2932]
Make sure it works as expected. It should, it's not doing anything fancy. Only concern is if seq numbers have changed in format.

**Comment by SCdF** [comment]
Sequences are now strings, so couch2pg is broken, though the fix is easy.

**Comment by SCdF** [comment]
Commit medic/couch2pg@417f547 adds support: we just needed to support strings where we store sequences, the rest works fine.

**Comment by garethbowen** [comment]
LGTM
