### ISSUE TITLE
Get Travis using CouchDB2.0

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2933]
Our tests should run in Travis on CouchDB 2.0.

Some options:
 - Get travis to support CouchDB 2.0 as a service (much like they support 1.6)
 - Build it ourselves once, zip it and host it somewhere, and have our travis builds pull it down and execute it
 - Built it from source each time, and cry

**Comment by alxndrsn** [comment]
Done and merged.

**Comment by garethbowen** [comment]
@alxndrsn I've added a comment on the PR. Feel free to close.
