### ISSUE TITLE
Determine and document CouchDB 1.6 -> 2.0 migration strategy

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2934]
It looks like we can just turn off 1.6 and copy its DB files to the new install location. We should check that this works as expected.

If we have to use replication to migrate, work out what happens when seq numbers change from PouchDB's perspective, does it:
 - Completely not realise the server has changed and lose data
 - Realise the server has changed and start from 0 again, which means all of our phones are going to pull their entire changes feed again (thankfully they won't pull docs they already have, they'll just process the changes feed)

**Comment by SCdF** [comment]
https://blog.couchdb.org/2016/08/17/migrating-to-couchdb-2-0/

**Comment by SCdF** [comment]
Tested this strat locally:
 - Had a replicating user already cached on my Chrome (demo / medic)
 - changed `/usr/local/etc/couchdb/local.ini` to boot on port 598**5**
 - Booted the standalone MacOS couchdb2 app (which boots on 5984 as standard)
 - Replicated `_users`, `medic` and `medic-audit` between them
 - Hit some views to warm them
 - Booted api (now against 2.0)
 - Loaded the app with the replicating user again

According to the network logs PouchDB tried to find its `_local` doc against CouchDB 2.0, failed (obviously) and then re-replicated, downloading the `_changes` feed from `0` again. It didn't download any new docs, just the changes feed, as expected.

**Comment by SCdF** [comment]
@garethbowen just to confirm that we're on the same page, I'm happy with the above statement (ie migration via replication), but if you could "review" it and close the ticket if you're happy that would be choice.

**Comment by garethbowen** [comment]
@SCdF Did you try just copying the v1 DBs into v2? I'm just wondering about the pros and cons of the two approaches.

**Comment by SCdF** [comment]
@garethbowen oh yeah true, I did not try that. Let me work out how to do that (OSX is weird) and I'll get back to you.

**Comment by garethbowen** [comment]
@SCdF Also I think you put this in the wrong milestone?

**Comment by SCdF** [comment]
@garethbowen whoops… yeah def

**Comment by SCdF** [comment]
So here is the migration guide I'm using: https://blog.couchdb.org/2016/08/17/migrating-to-couchdb-2-0/

Their "copy the files" migration is actually still replication: you copy the files to your local node, and then replicate them into the "clustered" setup (with shards and all that jazz), so AFAICT it will present the same. It does work as advertised though, but it's basically the same as running both couch's at the same time.

**ALSO, one thing I missed but is made clear this time: migrating from CouchDB 1.6 to 2.0 **logs users out**.

This is a royal pain in the arse, but it makes sense: we rely on the CouchDB instance for auth, and that instance is changing. Would be good to understand this more and see if we can avoid it.

**Comment by SCdF** [comment]
OK @garethbowen, so our two options are:
 - Reconfigure 1.6 to run on another port, run them both at the same time and replicate over
 - Shut down 1.6, then copy the .couch files we want into the non-shard dir on 2.0, then replicate them from 5986 -> 5984

Both involve replication, both involve wrecking the seq, and both result in the clients being logged out and then subsequently downloading changes feed again once they log in.

The logging in thing is a real pain, not sure what our strategy for large clients is going to be wrt that one. Either:
 - We find a way to migrate session data over (no idea how)
 - We get every CHP to coordinate being at the branch at the same time and have all their phone's logged into again at the same time
 - We run two servers side by side, with CouchDB 1.6 constantly replicating to 2.0, and let clients move phones over manually at their leisure. This would mean for clients using custom apps we'd have to update the app to a new URL and have them update them at the branches. Not sure what other knock-on effects changing the URL would have.

**Comment by garethbowen** [comment]
I read that documentation a little differently...

> Alternatively, if you don’t want to run both in parallel (and have even more storage capacity), you can copy the database file ... to the data directory of one of the nodes of the cluster... The database will then appear on the node’s local port (normally 5986 instead of 5984, other ports depend on your setup). You can fully use the database on the local port, but it’s not clustered yet. In order to get it clustered, you can use replication...

I read that as it works for a single node setup (which is how low we've set the bar thus far). 

Having said that, it would be better to have a clustered setup when we're done, and replication sounds like the _correct_ approach, and it should be reasonably quick so long as it's local and bypasses api. 

I don't like the idea of having two versions running and replicating in production - it sounds like a support nightmare, so this might need some more thought. It might be ok for everyone to get logged out and contact their IT person for support if we manage it correctly. This might also tie in with other updates that may need return to base training (eg: 2.9 UI changes) or support (eg: updating to the crosswalk android app).

**Comment by garethbowen** [comment]
@SCdF Any further thoughts?

**Comment by SCdF** [comment]
@garethbowen I agree we could run in local mode, though I'd rather not, just because it adds a layer of confusion. I.e, would that be how we ship to new clients, or would new installs be on 5984 and old on 5986, and how would that affect URLs that we use in code etc.

No other thoughts apart from that unfortunately. I guess medic 3.0 will have to have big red flags on it about upgrading and we'll have to just trial it client to client.
