### ISSUE TITLE
Show parent place after deleting a place/person

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2936]
When you delete a person or place you are brought to the blank `No person selected` page. We should return to the parent place after deleting a place. When deleting top level places there is no parent so it is OK to show the blank RHS.

**Comment by garethbowen** [comment]
Not a bug. Removing from this milestone.

**Comment by sglangevin** [comment]
I would argue that this is a UX bug. Getting to a blank screen after deleting something means that you no longer know where you are in the hierarchy, which is jarring to the user.

**Comment by garethbowen** [comment]
@sglangevin It's not a bug because it's working as it was intended to.

**Comment by garethbowen** [comment]
@SCdF PR please: https://github.com/medic/medic-webapp/pull/2947

**Comment by SCdF** [comment]
LGTM, merged.
