### ISSUE TITLE
If a user navigates away from the People tab while a person/place is selected, that place will be selected on the LHS upon returning to the People tab but the RHS is blank

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2939]
Seen on v2-alpha.app, version 2.9.0-alpha.4490, logged in as `tester` (full access user).

To reproduce:
1. Go to the People tab
2. Select a branch/district
3. Navigate to the History/Reports tab
4. Navigate back to the People tab
5. Notice that the branch/district is selected on the LHS but the RHS say "No person selected"

![image](https://cloud.githubusercontent.com/assets/1286381/20450159/1d290ad0-ada3-11e6-87e1-8dc3b55d3523.png)

**Comment by mandric** [comment]
What would you like the behavior to be?  Should the LHS stay selected and the right display the detail?  Or should the selection be reset?

**Comment by sglangevin** [comment]
If the LHS has a selection, then it seems like the RHS should display the detail. I'm not sure whether the user would expect to come back to the tab and find the selection reset or of they would expect to find the place or person they viewed most recently. It seems like resetting the selection would be cleanest. Thoughts @diannakane?

**Comment by SCdF** [comment]
That's quite weird: I'm pretty sure there is code that deals with exactly this scenario. [Here is the contacts example](https://github.com/medic/medic-webapp/blob/master/static/js/controllers/contacts.js#L268-L272):

```js
$scope.$on('$stateChangeStart', function(event, toState) {
  if (toState.name.indexOf('contacts') === -1) {
    $scope.unsetSelected();
  }
});
```

I wonder if we've broken it recently somehow.

**Comment by diannakane** [comment]
This is an interesting question and is relevant to how long before we clear search results as well. Posting to the design channel to get some quick team input.

**Comment by garethbowen** [comment]
This only happens for users without a place. For CHPs their home place is selected when returning to the People tab. To make it consistent I've patched it so the previous place won't be selected in the LHS. The RHS will still be blank. This means switching to the People tab the second time behaves identically to switching to it the first time.

PR please @alxndrsn : https://github.com/medic/medic-webapp/pull/2949

**Comment by alxndrsn** [comment]
This change looks like it makes things much simpler 👍

**Comment by diannakane** [comment]
Hey guys, we've been having some discussion in the design channel about this. It seems that the consensus is that we would expect the previously selected place to be selected. @abbyad summed it up well: 

> we are currently sending people to the other tabs without them selecting them from the top bar... so I think it is better to keep the selection for now until that issue is resolved (eg doing a task directly from the person's profile)

The ideal scenario would be for the user to come back to the place they were previously viewing, even if it is a level below the one selected in the LHS. For CHWs who only see one level below them, they will always land on the household they had previously viewed. Even if they were previously viewing a person in that household, I think it's acceptable that they land on that person's household page.

**Comment by garethbowen** [comment]
I've raised #2954 to cover the UX improvement.
