### ISSUE TITLE
Change "branch" to "health center"

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#2941]
Based on team feedback, please change the middle level of the hierarchy from "branch" to "health center" in the default config for SMS projects. This means that the hierarchy labels should be district > health center > area

**Comment by garethbowen** [comment]
@diannakane Just to be clear, this is a change from a month ago when we switched all translations for the hierarchy to "district > branch > area"? ( #2768 )

**Comment by abbyad** [comment]
That is correct. In #2768 we had incorrectly shown SMS workflows as using Branch as the middle level, when to date no SMS projects has used the term Branch. Sorry for not having cleared this up prior to the work on 2768.

**Comment by garethbowen** [comment]
Ok, I'm on it.

**Comment by garethbowen** [comment]
Done: https://github.com/medic/medic-webapp/commit/ab8718bed1d1d047dfa4e05171de24645ef86b4f
