### ISSUE TITLE
Show better error if your user's contact person is deleted

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2944]
If your user's contact is deleted there are several strange behaviours in the webapp
1) LHS of History tab never loads
2) There is no FAB on a Person profile:
![image](https://cloud.githubusercontent.com/assets/789512/20578635/4c7ceb8e-b196-11e6-8914-fd0c7eb4ee38.png)

Ideally we would show an error in the UI so that the person can correct the situation or know to contact their admin. We should also provide some clearer info in the console, rather than:
![image](https://cloud.githubusercontent.com/assets/789512/20578681/75a6200c-b196-11e6-9d44-807ad3d7c484.png)

Steps to reproduce:
1) Assign your user to a contact
2) Delete the contact
3) Load History tab - see that LHS never loads and gives error:
`GET https://v2-test-dual-workflow.app.medicmobile.org/medic/807c6fc8c84985266b35dbcd2531c244? 404 (Object Not Found)`
`Error fetching user contact Object {error: "not_found", reason: "deleted", status: 404, name: "not_found", message: "deleted"}`

**Comment by garethbowen** [comment]
I wonder if we should just treat it like not having a contact. IIRC that shows an error message as expected.

**Comment by abbyad** [comment]
Ya, that seems reasonable. Not having a contact only shows the error when trying to complete a form, since that is the only action that requires it.

**Comment by garethbowen** [comment]
@alxndrsn PR please: https://github.com/medic/medic-webapp/pull/2946

**Comment by alxndrsn** [comment]
Looks fine.  Surprised this is a PR; do you have doubts?

**Comment by garethbowen** [comment]
@alxndrsn We're trying to PR (just about) everything in order to keep master stable. Docs: https://docs.google.com/document/d/1SrW4bOxdD3kAWZ9WvJtftyrfQBpZiA5HTJydpe43CeY/edit

I'll update the workflow doc to reflect this new reality.
