### ISSUE TITLE
Refreshing the People tab often doesn't display the search results

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2948]
1. Go to the People tab
2. Hit reload
3. Some of the time the spinner never clears and the action bar never populates:

![infinispin](https://cloud.githubusercontent.com/assets/2064938/20585139/83a24646-b25d-11e6-9662-10ba3e048228.png)

**Comment by garethbowen** [comment]
There seems to be a race condition in `$translate` if it's not ready to go when it's called. In this case it sometimes wasn't resolving which blocked the `search` and other times it was resolving the translation key instead of the value. It turns out we don't need it and can just set the label and get the translate directive to do the work for us. This greatly simplifies the promise chain.

PR please @estellecomment https://github.com/medic/medic-webapp/pull/2950

**Comment by SCdF** [comment]
LGTM, merged.
