### ISSUE TITLE
Consider switching from Crosswalk to Crosswalk Lite

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2952]
Switching from [Crosswalk](https://crosswalk-project.org) to [Crosswalk Lite](https://crosswalk-project.org/documentation/crosswalk_lite.html) for our `WebView` implementation could potentially reduce the APK size by ~10MB and installed size by ~15MB.

**Comment by alxndrsn** [comment]
From the [list of disabled features in Crosswalk Lite](https://crosswalk-project.org/documentation/crosswalk_lite/lite_disabled_feature_list.html), it is missing the following which we may depend on:

* **ICU** - this appears to be used for rendering non-latin charactersets, and problems rendering Hindi are specifically mentioned
* **XSLT** - we rely on this (via enketo) for converting XForms from XML to HTML
* **Indexed DB** - this is likely used by PouchDB
* **Web Database** - this is likely used by PouchDB

From this list, it's clear we can't use stock Crosswalk Lite, but if we need to reduce the size of the APK and installed app it looks like we can include flags when building our crosswalk `.aar` to remove specific features, and potentially make large size reductions.

**Comment by ngaruko** [comment]
Did we do anything on this issue @alxndrsn ? Is there anything to AT?
