### ISSUE TITLE
Show the previously selected item when navigating to a tab 

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2954]
From @abbyad 
> we are currently sending people to the other tabs without them selecting them from the top bar... so I think it is better to keep the selection for now until that issue is resolved (eg doing a task directly from the person's profile)

From @diannakane 
> The ideal scenario would be for the user to come back to the place they were previously viewing, even if it is a level below the one selected in the LHS. For CHWs who only see one level below them, they will always land on the household they had previously viewed. Even if they were previously viewing a person in that household, I think it's acceptable that they land on that person's household page.

**Comment by sglangevin** [comment]
I agree with @abbyad on this one - makes sense to come back to where you were if you are being directed away by the app.

Seems like we would ideally land on the person or place page that we were on when leaving the People tab as opposed to trying to work out the place they belong to and display that.

Is this change going to be applied to all tabs? Would that include keeping the same filters on the History/Reports tab or keeping the search until it is cleared by the user?

**Comment by diannakane** [comment]
I thought @abbyad and I were saying the same thing :)

In any event, I agree.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by mandric** [comment]
Any updates here @garethbowen?

**Comment by garethbowen** [comment]
No. But obviously nobody cares. Closing.
