### ISSUE TITLE
The heading "Tasks" is cut off on mobile view

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#2958]
![image](https://cloud.githubusercontent.com/assets/1286381/20692377/5b3d7edc-b58c-11e6-9352-2544b529b7a6.png)

Tasks should be moved over slightly so that the full word is visible.

**Comment by sglangevin** [comment]
@garethbowen is this being backported to 2.9 or it's waiting until 2.10? I had filed it as part of 2.9 testing, but wanted to confirm as I'm currently doing acceptance testing on this issue.

**Comment by garethbowen** [comment]
@sglangevin Sorry, I don't know how that got missed. I've backported it now. Thanks.

**Comment by sglangevin** [comment]
Acceptance testing on hold until new beta is released.

**Comment by sglangevin** [comment]
Working well in v2.9.0-beta.9
