### ISSUE TITLE
Make sure Concierge and CouchDB2.0 work correctly together

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#2960]
Concierge is used to bootstrap medic-os (I think?) and sets some things up with CouchDB. We need to make sure that all works with 2.0.

Obvious pain points will be that `_config` no longer exists, and `_node/couchdb@localhost/_couchdb` is the new hotness.

**Comment by browndav** [comment]
Taking this out of the current milestone for now – CouchDB 2.x support is in progress, but needs additional testing/packaging work before this issue is actionable.

**Comment by SCdF** [comment]
@browndav I went through the concierge script and added some comments / todos. Check out this PR: https://github.com/medic/medic-os/pull/12

This should give you a good idea of what's going on. In summary though:
 - Lucene is no longer accessed via `5984/_fti`, but `5985/`. We should also drop the setup to add the `_fti` proxy.
 - Any calls to the `_config` DB should be made to the local node, because `_config` is per node. This could be done by either specifying the node in question `_node/name/_config` or by changing the port to 5986, though the latter is deprecated / legacy.

**Comment by browndav** [comment]
Placing in sprint. This can be difficult to debug in some cases, and I've found that VMware and snapshots is a huge speedup. If anyone picks this up, I'm happy to help get software licenses and walk through how I've been doing debugging on this module, for better or worse.

**Comment by SCdF** [comment]
Hmmm. I'm now wondering if we want the default to be single node or cluster, and how that potentially affects how we've made changes. I've had my head in the clouds of large partners, so I've been defaulting to clustered, but perhaps that is wrong.

**Comment by SCdF** [comment]
I've made the changes my PR recommended and updated the PR: https://github.com/medic/medic-os/pull/12

I need to talk to @browndav about some concierge-specific stuff, which is unfortunately going to block me progressing on this one I think.

**Comment by SCdF** [comment]
More more additional information.

In asking about if there are any instructions for automated setups and was linked to these examples:
 - https://github.com/afiskon/install-couchdb
 - https://github.com/kafecho/ansible-couchdb2

So we can look at these for examples of what to change in Concierge

**Comment by SCdF** [comment]
The changes to concierge are blocked on us understanding single node vs clustered setup of couchdb: https://github.com/medic/medic-webapp/issues/3257

**Comment by garethbowen** [comment]
CouchDB2 is not prioritised for this milestone - removing.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
NB: we'll re-evaluate when we hit 3.0 dev, but we can probably just close this as it's likely we'll drop concierge completely for 3.0

**Comment by browndav** [comment]
Dropping concierge completely, confirmed. Closing.
