### ISSUE TITLE
Reports not assigned to person or place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2961]
We have had several tech leads reporting this in their v2.9 testing.

**Comment by abbyad** [comment]
Seems related to transitions not being enabled.

**Comment by abbyad** [comment]
Setting the transitions fixes the reported issues. 

Removing the _Bug_ label and adding a _Documentation_ label instead so that we are aware of this issue and know how to set them properly.

**Comment by garethbowen** [comment]
@abbyad This is on a fresh install, right? Do we have any configuration documentation to add this to?

**Comment by abbyad** [comment]
I will check next clean install that I do.

May also be useful to document what each transition is in [medic-sentinel](https://github.com/medic/medic-sentinel) to know which ones can be disabled - @mandric says performance is better requiring the minimal set. We can then mention it in [medic-docs](https://github.com/medic/medic-docs/blob/master/md/config) unless @ngamita has a better place for it.

**Comment by ngamita** [comment]
It's ok to be in medic-docs and we communicate to techleads.

**Comment by garethbowen** [comment]
Documented here https://github.com/medic/medic-docs/blob/master/md/config/transitions.md

@abbyad please review.

**Comment by abbyad** [comment]
Looks good, thanks @garethbowen! Added a comment to commit for a small clarification.

**Comment by garethbowen** [comment]
Improved based on feedback.
