### ISSUE TITLE
Not all API endpoints are documented

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2963]
We should document all API calls in `medic-api`'s [readme](https://github.com/medic/medic-api/blob/master/README.md), or at least all potentially public facing ones eg `sms`.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
Documentation for `sms` has been added to the readme. Closing. @abbyad please re-open if there are other sections that are still missing.
