### ISSUE TITLE
Don't start api-integration tests if required env vars are not set

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#2964]
If one of `COUCH_URL` and `API_URL` is not set, errors such as:
```
  1) drop-audit-doc-index migration should change id to match doc id and remove unnecessary fields:
    TypeError: db.use is not a function
   at Object.initDb (tests/integration/migrations/utils.js:149:17)
   at Context.<anonymous> (tests/integration/migrations/drop-audit-doc-index.js:11:18)
```
are seen when running the api integration tests.

These env vars should be checked for before starting the tests, and a clearer error message reported.

**Comment by alxndrsn** [comment]
Also check that `COUCH_NODE_NAME` is set

**Comment by ngaruko** [comment]
Does this need any AT @alxndrsn ?

**Comment by alxndrsn** [comment]
Well, I think it works... ;¬)
