### ISSUE TITLE
Enable all transitions by default in migration

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2969]
From testing it seems as though transitions were enabled by default in v0.4, and now are disabled by default in v2.9.

Since our default config should be for SMS workflow projects we should enable the transitions if `transitions` is not present in app_settings when upgrading.

Here is what I used for testing, but there are a couple more [here](https://github.com/medic/medic-sentinel/tree/master/transitions) that may need to be added: 
```
    "transitions": {
        "accept_patient_reports": {
            "load": "./transitions/accept_patient_reports.js"
        },
        "conditional_alerts": {
            "load": "./transitions/conditional_alerts.js"
        },
        "default_responses": {
            "load": "./transitions/default_responses.js"
        },
        "update_sent_by": {
            "load": "./transitions/update_sent_by.js"
        },
        "registration": {
            "load": "./transitions/registration.js"
        },
        "update_clinics": {
            "load": "./transitions/update_clinics.js"
        },
        "update_notifications": {
            "load": "./transitions/update_notifications.js"
        },
        "update_scheduled_reports": {
            "load": "./transitions/update_scheduled_reports.js"
        },
        "update_sent_forms": {
            "load": "./transitions/update_sent_forms.js"
        }
    }
```

**Comment by abbyad** [comment]
Transitions were removed for https://github.com/medic/medic-webapp/issues/2207

**Comment by mandric** [comment]
We don't want to enable transitions by default, pretty sure we need a way to migrate a 0.4 configuration to a 2.9 configuration.

**Comment by abbyad** [comment]
All projects that use SMS workflows need these transitions, whereas projects that _exclusively_ use app workflows do not need transitions. Two of four exclusive app workflow projects have transitions disabled in the config (eg [LG config](https://github.com/medic/medic-projects/blob/master/lg-uganda/app_settings.json#L21743-L21785)) whereas the other two do not specify.

**Comment by abbyad** [comment]
Seems as though a enable/disable transitions checkbox in the UI config would help deal with this.

**Comment by abbyad** [comment]
Since we won't have transitions enabled by default and don't have a control for them in the config pages, we need to add the following to `app_settings` for all SMS projects: 

```
"transitions": {
  "accept_patient_reports": true,
  "update_clinics": true,
  "conditional_alerts": true,
  "default_responses": true,
  "update_sent_by": true,
  "registration": true,
  "update_notifications": true,
  "update_scheduled_reports": true,
  "update_sent_forms": true
}
```

To improve sentinel performance unnecessary transitions can be marked as `false` or removed from the list.
