### ISSUE TITLE
On upgrade existing reports are not associated to person/place

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2970]
When upgrading from 0.4 to 2.9 existing reports are not associated to places, whereas reports submitted after upgrade ([and setting transitions](https://github.com/medic/medic-webapp/issues/2969)) show the person/place accordingly.

**Comment by abbyad** [comment]
I cannot reproduce new reports being associated properly. Now even new reports are not properly associated and give the error `sys.facility_not_found`. Messages sent from the same number are recognized as the appropriate person in the Messages tab.

**Comment by mandric** [comment]
Something is not associating places correctly because there is a `related_entities` deprecated (not used in 2.9) property on the new records, like b9fca774a28c2dc23df631442771ddb2 but I don't know where that is coming from, so the interface does not read that as a contact.  Sentinel also is not using `related_entities` anymore either https://github.com/medic/medic-sentinel/blob/2.9.x/transitions/update_clinics.js...

**Comment by abbyad** [comment]
Hmm, should those `related_entities` have been changed during an upgrade migration? That one you mention is from before the upgrade though. Looking at a new one (eg [c7f97e339cd41c8c0afcdfd34d6bd22a](https://v2-test-ipd-nepal.app.medicmobile.org/_couch/_utils/document.html?medic/c7f97e339cd41c8c0afcdfd34d6bd22a)) it doesnt have the `related_entities` but still doesn't resolve.

This config uses a form field `reporting_id` to associate to the person/place's `rc_code`... and that is what seems to be failing after upgrade because the new contacts do not have the `rc_code` field. Leaving the `reporting_id` field blank makes it possible to associate the report to the right person, although not the intended person. 

**It seems as though we need to carry over the `rc_code` to the appropriate place in one of the migrations from v0.4.**

**Comment by abbyad** [comment]
@mandric do you have a fix in place for this? To get v2.9 to Final by the end of this week we'd want to fix and test this in the next couple days - should we reassign to @alxndrsn or @garethbowen?

**Comment by mandric** [comment]
No fix, all I did was poke around. I think this is a bug with how records are created via the backend (couchdb update)?  Getting on a plane right now but should be available tmrw.

**Comment by abbyad** [comment]
Thanks for the update, and have a good flight! Given the time crunch I'll reassign to Gareth since he has a bonus NZ day on us. He can reassign by the end of his day if doesn't get to it by then.

**Comment by abbyad** [comment]
From testing on v2.9.0-beta.7, to properly assign the facility using a reference code the `rc_code` key needs to be `{place}.contact.rc_code`. It does not matter if it is on `{person}.rc_code` and/or `{place}.rc_code`. 

A short term fix would be:
1) fix migrations to put the rc_code with all persons (and nested contacts)
2) have `rc_code` on the person form for projects wanting to associate reports to a place using a code instead of identifying by the sender's phone number

However, doing this does not seem right. The rc code is meant to refer to place, not a person. And we already have a short code that can refer to a person (`patient_id`, which should now really be called `person_id` but that is a conversation for another time).

Ideally we would have the short rc_code associated directly to the place, and labelled as such eg `{place}.place_id`. Doing this may have design repercussions on what is displayed on the LHS in the Reports tab, so may be better to leave this part to a future release.

**Comment by garethbowen** [comment]
@abbyad You're absolutely right. `place_id` is where we expect the `rc_code` to be in all other parts of the code, we just don't have any migration to put it there. I'll modify the migration that overwrites it to store the `rc_code` in `place_id` before overwriting. This actually solves a few other bugs that we haven't found yet (replication of reports with a place_id, showing the rc_code on the place profile, and on and on...).

**Comment by garethbowen** [comment]
@mandric PRs for you please:

- https://github.com/medic/medic-api/pull/114
- https://github.com/medic/medic-sentinel/pull/90
- https://github.com/medic/medic-webapp/pull/2985

There's two bugs fixed here:

1. The place.contact.rc_code was being overwritten by the new contact. We decided above that this wasn't the right place for it anyway, and lots of webapp code looks for it at place.place_id. So I've modified this migration to copy the rc_code to place_id.
2. The migration to associate people with reports was giving up too easily. If the report didn't have a `related_entities.clinic.contact._id` it just ignored it. The change is to fall back to get the primary contact of the clinic instead using `related_entities.clinic._id`. This makes it more likely to succeed in finding the correct contact person.

After this is merged we'll need to bump the submodules in webapp and backport everything to 2.9.x - I'm happy to do this bit if you sign off on the changes.

**Comment by mandric** [comment]
One minor comment re documentation.  Merge away!

**Comment by abbyad** [comment]
Works well now. Tested upgrade of same project from v0.4 to v2.9.0-beta.9 and places are resolved according to the field which refers to the `place_id`.

Moving to Ready.
