### ISSUE TITLE
Bump dependencies for 2.10

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2973]
Now's a good time to bump all our npm dependencies in preparation for the new release.

**Comment by garethbowen** [comment]
Still need to do api and sentinel.

**Comment by garethbowen** [comment]
3 PRs:
* https://github.com/medic/medic-webapp/pull/2977
* https://github.com/medic/medic-api/pull/111
* https://github.com/medic/medic-sentinel/pull/89

**Comment by SCdF** [comment]
@garethbowen looks like moving to Protractor 4.x broke the Node 5.x build because it's uses ES6, specifically the spread operator. Either revert back to 3.x or decide that we're dropping support for Node 5.x

**Comment by garethbowen** [comment]
I didn't check the log, then I re-ran the build, then it passed, and now I can't see the log, so IDK? But it's green now so I guess it's all good... Maybe in the last 2 days they've patched protractor or something.

**Comment by garethbowen** [comment]
Seems to work now. Closing...
