### ISSUE TITLE
Cannot access person/place forms

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2974]
The person and place create/edit forms get loading errors on an instance that was upgraded from `0.4` to `2.9.0-alpha.4553`. `Error loading contact form. Error: Syntax error, unrecognized expression: $promise`

Here is the full stack:
![image](https://cloud.githubusercontent.com/assets/789512/20804652/be921a9c-b7c1-11e6-81e5-7419098ae595.png)

I can see the forms in the DB:
![image](https://cloud.githubusercontent.com/assets/789512/20804758/117f50ee-b7c2-11e6-85a6-7411f3c728e1.png)

The same forms loaded on a fresh install of the same version work fine.

This issue is on [same instance](https://v2-test-ipd-nepal.app.medicmobile.org) reporting #2970, in case they are some how connected.

**Comment by abbyad** [comment]
The error occurs in `bindJsonToXml`, specifically [this line](https://github.com/medic/medic-webapp/blob/db7ca855f88f958c0bf157eb10d7b07e93611594/static/js/services/enketo-translation.js#L340)

**Comment by abbyad** [comment]
Error occurs because the user has a `$promise` key:
![image](https://cloud.githubusercontent.com/assets/789512/20805653/8e49bee0-b7c5-11e6-936c-d70f9c07673f.png)

**Comment by abbyad** [comment]
The forms load properly once the `$promise` (and `$resolved`) keys are removed.

**Comment by SCdF** [comment]
Those are some super weird keys…

**Comment by abbyad** [comment]
Indeed! Some, but not all, user docs have these keys.

Looking at the instance that this was cloned from, the original user doc in the `_users` db has those fields too:
![image](https://cloud.githubusercontent.com/assets/789512/20805905/aa5d4bd2-b7c6-11e6-9150-5ba7834d9df9.png)

I imagine we are importing these directly when creating the medic user doc

**Comment by garethbowen** [comment]
Yeah that looks like a migration bug. Good debugging @abbyad !

**Comment by garethbowen** [comment]
Ok. As far as I can see this probably occurs when using the angular $resource service, which we haven't used in ages. @abbyad Do you still have a copy of the original instance somewhere so we can see if those properties exist on the old user too?

**Comment by abbyad** [comment]
Yes, it is still an active project with a live instance. I had already checked and some (not all) of the users do have those properties.

**Comment by garethbowen** [comment]
Ok. I think the bug is fixed, but we might need to think about a migration to fix these users.

**Comment by garethbowen** [comment]
PR please @alxndrsn : https://github.com/medic/medic-api/pull/113

I'm satisfied that the code that caused this has been fixed so we just need a migration to fix the data on upgrade.

**Comment by alxndrsn** [comment]
LGTM

**Comment by abbyad** [comment]
Works well! Repeated the same upgrade procedure as done before but now from v0.4 to v2.9.0-beta.9.

Moving to Ready.
