### ISSUE TITLE
Transition order matters

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2978]
@bishwas reported in https://github.com/medic/medic-projects/issues/1133 that conditional alerts were not working in v2.9 test - but it turns out that the ordering of the transitions was the culprit. Moving the `update_clinics` to above the `conditional_alerts` transition fixed the problem.

According to the [Sentinel Transitions API](https://github.com/medic/medic-sentinel#transitions-api) the ordering should not matter.

Including in this milestone as this should be considered for v2.9.

**Comment by garethbowen** [comment]
I'm not sure it makes sense to allow the transitions to run in any order. If one transition adds a field (eg: the clinic) and another uses that field (eg: alerting the clinic) then the order absolutely matters. @mandric What do you think?

It may be that each pass through the transitions causes a change which triggers another pass through the transitions so with careful coding of the transitions it could succeed the second time through, but it's still more desirable to succeed on the first pass rather than requiring a second.

Investigate the `conditional_alerts` transition to see why it didn't fire on the second pass (maybe it was marked as done?), and update the documentation to reflect reality.

**Comment by mandric** [comment]
> It may be that each pass through the transitions causes a change which triggers another pass through the transitions so with careful coding of the transitions it could succeed the second time through, but it's still more desirable to succeed on the first pass rather than requiring a second.

Eventually all transitions ignore a change or make a change that allows them to be ignored on the next change.

**Comment by mandric** [comment]
> Investigate the conditional_alerts transition to see why it didn't fire on the second pass (maybe it was marked as done?), and update the documentation to reflect reality.

It's possible `conditional_alerts` or any transition isn't following the rules either.  I'll take a look.

**Comment by garethbowen** [comment]
I like being able to define the order because if we can get all transitions to success on first pass then we only have 1 update to the doc rather than n thus keep our changes sequence as short as possible. But I agree that if someone configures it in any other order it should get the same result eventually, but require more updates to do so. Thanks for looking into it @mandric

**Comment by mandric** [comment]
Yeah it's a trade off for ease of use.  I already see too much complication in configuration as is so I can't see adding ordering here helping much, typically there is just two changes since all transitions run on one change.  Unless one transition depends on another then it's 3 passes.

**Comment by garethbowen** [comment]
There's no real trade off here - it'll work either way just like it always has. This just allows for some performance optimisation if desired.

**Comment by mandric** [comment]
I see a trade off that's not really worth it, you save one look at change feed entry (not even saving a write)?  And you need to be aware of order during configuration or writing of transitions, which is different from right now which says write transitions so order of transition execution does not matter.

**Comment by mandric** [comment]
All the transitions run in memory and build on each other there is not a write per transition.

**Comment by garethbowen** [comment]
If a transition A depends on transition B and A runs first then...

* A will fail
* B will succeed
* DB will update
* A will succeed
* B will skip
* DB will update
* A will skip
* B will skip

If instead they are defined the other way around...

* B will succeed
* A will succeed
* DB will update
* B will skip
* A will skip

That saves you one write per doc. This is the situation that's described in this issue description, except my assumption is there's a bug in the A transition so it doesn't succeed the second time through (perhaps it doesn't even execute?).

As far as I know we have _always_ defined transitions in an ordered array and executed them serially so there is no added complexity. We do not require any specific order but some orders will naturally be more efficient than others. The only problem here is we should ensure that A executes and succeeds on the second run through even if it is defined after B.

**Comment by mandric** [comment]
Ok you're right, that is potentially twice as many writes probably worth defining and I don't think it would need to affect configuration either.

**Comment by garethbowen** [comment]
I guess the optimal solution would be to have each transition list the transitions it depends on then we can sort all the configured transitions in code...

**Comment by mandric** [comment]
Yeah each transition could optionally define a dependency list and those can always get ordered first so at least that reduces chances of performance hits pretty quickly.

**Comment by mandric** [comment]
So transition order currently does not matter unless a transition is broken.  But considering the discussion above we should probably open another issue for adding that feature to sentinel.  The conditional_alerts transition is broken on 2.9 and there is a PR above.  We should probably apply the PR above, release a new 2.9 beta, update and test again.

**Comment by garethbowen** [comment]
@mandric I wrote a couple of functional tests and made the change we discussed in the channel for comparison. My PR: https://github.com/medic/medic-sentinel/pull/92

Let me know what you think.

**Comment by mandric** [comment]
I'll raise you a PR @garethbowen https://github.com/medic/medic-sentinel/pull/93

**Comment by mandric** [comment]
Note we still need to open another issue for adding support so each transition could optionally define a dependency list, the PRs don't cover that.

**Comment by garethbowen** [comment]
I've merged and backported to 2.9.0 for release. We can make further changes in a service pack if required.

**Comment by abbyad** [comment]
Given this was tested in https://github.com/medic/medic-projects/issues/1133#issuecomment-269795672 I think this issue passes acceptance testing.
