### ISSUE TITLE
Cannot see reports as a district admin

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2979]
Using 2.9.0-beta.3, the admin can see [reports](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/02a2c7eba7e4f4a92aa04ff5c201aaae), but restricted users are not able to see them. I have tested with and without replication depth set, but doesn't seem to make a difference. Also checked that the reports permissions were set accordingly. Leaving this issue open as a placeholder for now until I find more info.

## Logged in as Admin
![image](https://cloud.githubusercontent.com/assets/789512/20868883/d06a12e0-ba34-11e6-93e6-7436b1156961.png)

## Logged in as District Manager
Does not see the reports above Mika that the admin can see.
![image](https://cloud.githubusercontent.com/assets/789512/20869046/121eb710-ba38-11e6-9e62-77f83f2b9c26.png)

**Comment by garethbowen** [comment]
This looks to be a fairly major bug related to replication of JSON reports.

**Comment by garethbowen** [comment]
PRs please @alxndrsn 

- https://github.com/medic/medic-webapp/pull/2981
- https://github.com/medic/medic-api/pull/112

The replication filtering is done in two parts. Firstly `contacts_by_depth` is queried to find people the user is allowed to see. Secondly `docs_by_replication_key` is queried to find docs about those people. The second query was already checking patient_id and place_id fields, but the first was never returning the `patient_id` or `place_id`, only the `_id`. This changes the first query to return the `_id` _and_ the `patient_id` or `place_id`

**Comment by alxndrsn** [comment]
One small query at https://github.com/medic/medic-webapp/pull/2981/files#r90907139

**Comment by abbyad** [comment]
Works well, thanks! Moving to Ready and if I see any problems through further testing will open new issues.
