### ISSUE TITLE
The Home page is not found

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2982]
When logging in fresh as a restricted user you see this page:

![error](https://cloud.githubusercontent.com/assets/2064938/20878265/d6779dac-bb32-11e6-8709-f5965ea5f87f.png)

Going directly to another URL works.

There is nothing in the console log.

**Comment by garethbowen** [comment]
PR please @alxndrsn https://github.com/medic/medic-webapp/pull/2983

I've also tidied the controller up so the diff is a big ugly - try ignoring whitespace. The problem was caused by breaking changes to `async.filter` between v1.x and v2.x.

**Comment by alxndrsn** [comment]
Diff at https://github.com/medic/medic-webapp/commit/ee6856657ecddf48eb5ab259aecbd3c17ef09a9f?w=1

**Comment by alxndrsn** [comment]
LGTM

**Comment by abbyad** [comment]
Works well in `2.9.0-beta.9`, moving to Ready.

**Comment by garethbowen** [comment]
@abbyad This never affected 2.9 - we need to test in 2.10.

**Comment by abbyad** [comment]
Ah, I missed that! I retested and works well in `2.10.0-alpha.4644` (this fix was in build 4628).

Moving to Ready.
