### ISSUE TITLE
Consider setting nginx worker_processes to auto

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2984]
@derickl asks...

> could [worker_processes] be set to 'auto' so that nginx automatically 'scales' based on the number of available cores?

[Documentation](http://nginx.org/en/docs/ngx_core_module.html#worker_processes).

Work out how much benefit this would give, and ensure core detection works on our setup.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by SCdF** [comment]
Just did it: https://github.com/medic/medic-os/pull/16

**Comment by SCdF** [comment]
Done.
