### ISSUE TITLE
Cannot create Task or Target based on reports using short `patient_id` format

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2986]
Due to the work done in #2700 for person-centered SMS workflows it would be desirable for web users to have tasks and targets based on the SMS reports they see. However, when trying to create tasks or targets using a person's reports, only reports using the `patient_id` in UUID form are accessible in `Contact.reports`.

**Comment by abbyad** [comment]
We are testing nurse-enabled workflows in v2.9 so it would be good to include in this upcoming v2.9 release. 

The relevant code seems to be the [here](https://github.com/medic/medic-webapp/blob/d76371808d9c79f0a973fba1fe8c0c20639a87f2/static/js/services/rules-engine.js#L58), where a crude edit would be changing:
`return fact.contact && fact.contact._id === factId;`
to:
`return fact.contact && ( fact.contact._id === factId || fact.contact.patient_id === factId || fact.contact.place_id === factId );`

**Comment by abbyad** [comment]
I hesitated to put the `bug` label on this issue because it was never actually relevant before, nor was it requested as part of #2700. I did include in this milestone since it would unblock me on setting up the tasks and targets on `standard.app` (the new DIY config).

**Comment by garethbowen** [comment]
@alxndrsn PR please: https://github.com/medic/medic-webapp/pull/2987

**Comment by alxndrsn** [comment]
Looks fine, but slightly confused by the original post - it says that:
> only reports using the `patient_id` in UUID form are accessible

However, the original code checks `contact._id`, and the _new_ code checks `contact.patient_id`.  Was the initial report mistaken?  Is it possible that only one of `_id` and `patient_id` should be checked?

**Comment by abbyad** [comment]
I understand the confusion because on the contact the UUID is stored as `_id` whereas the short ID is stored as `patient_id`, yet on the submitted report `patient_id` field is used to refer to the person, regardless of whether it is the short ID or UUID. 

All contacts must have `_id` (UUID), and some may have `patient_id` or `place_id` (short ID). We should be able to associate a report with either of these to the contact.

**Comment by abbyad** [comment]
Works well, but putting the Code Review label back on so this can be backported to 2.9. When that is done it can go straight to Ready.
