### ISSUE TITLE
Hide ability to submit JSON forms from Reports tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2988]
Even though a project has SMS workflows, if the forms are to be used in the webapp we would create XForm equivalents where possible. Using an XForm in the webapp is preferable to using the JSON version because it is better integrated, has better validation and more field types (eg search for person). By also having XForm equivalents we'd then have two of each form in this list:
![image](https://cloud.githubusercontent.com/assets/789512/20940233/03c8e08a-bbc0-11e6-9229-9b48963b2f63.png)

A couple options:
1) include context for each json form, similar to the way it is done with our XForms
2) a permission for showing JSON forms in the Reports tab. We can then choose to turn this off for all users as needed by projects.

Although option 1 is more versatile to show/hide individual forms, my preference would be for option 2 for the sake of simplicity and ease of configuration. Also, this doesn't prevent us from doing Option 1 at a later time if we do in fact need finer control -- although right now I cannot think of a situation in which we'd need to show only some JSON forms.

**Comment by estellecomment** [comment]
Sounds like there's no use case for displaying the JSON forms, so I'd be in favor of just hiding them, rather than add configurability that's not used. Lemme know.

**Comment by abbyad** [comment]
The use case is if we haven't bothered setting up the equivalent XForms - but you are right, we can just hide them for now.

**Comment by abbyad** [comment]
LGTM, merging and moving to Acceptance Testing

**Comment by abbyad** [comment]
I'll stick around to do the Acceptance testing once it builds.

**Comment by abbyad** [comment]
Thanks @estellecomment for the quick work on this!

Works well, moving to Ready.
