### ISSUE TITLE
Cannot render xform after updating enketo-core dependency

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2989]
After updating enketo-core in `master` form rendering is broken. I think this is due to https://github.com/alxndrsn/enketo-client-side-transformer being out of date with https://github.com/enketo/enketo-transformer . The error is...

```
Error loading contact form. Error: ["FormLogicError: Could not evaluate: /model/instance[1]/*//*[@template] | /model/instance[1]/*//*[@jr:template], message: The expression is not a legal expression."]
require<[346]</</renderFromXmls/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:184767:30
processQueue@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:35534:28
scheduleProcessQueue/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:35550:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36841:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36655:15
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:36880:15
completeOutstandingRequest@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:24963:7
Browser/self.defer/timeoutId<@http://localhost:5988/medic/_design/medic/_rewrite/static/dist/inbox.js:25242:7
```

**Comment by garethbowen** [comment]
I've got it working again by reverting enketo-core (and jquery).

@alxndrsn Any ideas on this bug?

While we're in there we should consider publishing enketo-client-side-transformer to npm - it looks like it's ready to go and just needs an npm publish? Having everything in npm means we can consider using [yarn](https://code.facebook.com/posts/1840075619545360) and get rid of that damned shrinkwrap.

**Comment by garethbowen** [comment]
Changes requested - back to you!

**Comment by garethbowen** [comment]
@alxndrsn I'm getting this error again after your merge. Can you have another look?

**Comment by alxndrsn** [comment]
I think the error's correct - `concat('NEW')` is invalid because `concat()` takes two arguments.

**Comment by garethbowen** [comment]
Yeah totally my fault. I thought I was using a default form but I was using a broken custom form...
