### ISSUE TITLE
Display of count widget with no goal

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2990]
As we start using our "Targets" more widely for in-app analytics, it would be good to have the `count` widget to simply display a prominent count value (and icon + title) when there is no goal value. This will help us show plain counts like total births or number of active pregancies as part of an Analytics dashboard.

For example, it could look like this:
![image](https://cloud.githubusercontent.com/assets/789512/20951928/d7415a92-bbf6-11e6-9235-c025a8e53775.png)

_(shown with font-size of 5em)_

**Comment by garethbowen** [comment]
@alxndrsn PR please: https://github.com/medic/medic-webapp/pull/2991

**Comment by alxndrsn** [comment]
Looks fine.  Intrigued to know what a goal of 'zero' would achieve though.

**Comment by abbyad** [comment]
Works well in 4668, moving to Ready.

Here is what it looks like for real, not just hacked like in the OP:
![image](https://cloud.githubusercontent.com/assets/789512/21020251/babea7e8-bd41-11e6-843a-ecd2588aa3d3.png)

**Comment by garethbowen** [comment]
> @alxndrsn Intrigued to know what a goal of 'zero' would achieve though.

I thought it could be used if you want to set a goal of say "0 missed appointments". Currently this wouldn't work well because "1" would be styled as a success not a failure, but using "-1" makes it future proof.

**Comment by alxndrsn** [comment]
Good thinking.
