### ISSUE TITLE
Submit button stays disabled after failed validation

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2993]
The Submit button can get stuck disabled

1) Create a user leaving all fields blank
2) Click submit button ...it gets disabled and shows _Submitting_
3) See validation message on password field (may be out of view if not already seeing the field)
4) See that submit button is never re-enabled until you close and restart the user creation modal
5) No console error messages

![image](https://cloud.githubusercontent.com/assets/789512/20980755/d4f1df8a-bc7f-11e6-9c73-5302b8ce2265.png)

**Comment by garethbowen** [comment]
@alxndrsn PR please: https://github.com/medic/medic-webapp/pull/2997

I also removed an unused map and function.

Consider backporting this to 2.9.x as it's annoying and a simple fix.

**Comment by garethbowen** [comment]
I've merged to get it in to the 2.9 release. Bypassing the review just this second time.
