### ISSUE TITLE
Missing radio buttons

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#2995]
The radio buttons were not showing:

 ![image](https://cloud.githubusercontent.com/assets/789512/20985644/4ff16792-bc93-11e6-841e-4a3a3d3abae7.png)

![image](https://cloud.githubusercontent.com/assets/789512/20985661/61f579ec-bc93-11e6-9f98-ec52af1281bd.png)

No errors are in the console, and on reload they showed up again. Experienced this on Chrome in Windows.

This only occurs very intermittently (I recall seeing something like this 6 months ago) and likely related to the browser and not our code, but creating issue in case we see this again.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Closing as this is quite old. If it happens again and you have time it'd be great to inspect the element and see if the radio button is missing from the DOM or just hidden. That would give us a clue for what the issue may be...
