### ISSUE TITLE
Add details page for user configuration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#2996]
Currently the Configuration > Users page shows a list of all users and when you select a user pops up a modal dialog. This means some detail (eg: email) is only shown in the edit user modal dialog.

Change this so when a row is selected the detail of the user is shown in a readonly page. This page has two buttons: Edit and Delete.

The Edit button is to go to an edit page (not modal).

This gives us more space in the list, reveals all data without having to edit, and removes a modal, thus solving three problems in one.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by browndav** [comment]
This is recent and seems valid. Would like to pass it to @diannakane for a call on prioritization or if the issue has been addressed in some other way/design already.

**Comment by garethbowen** [comment]
I'm working in this area so it makes sense to fix this too.

**Comment by diannakane** [comment]
As @slangevin said in #3604, we are planning to redesign this completely later this year. @garethbowen do you have a quick fix in mind?

**Comment by garethbowen** [comment]
@diannakane No quick fix no. I found a whole lot of GH issues in the user configuration section so thought I'd redo the whole lot, but once I found out it was on the list for redesign I decided to wait for that. I've marked all the issues I found with the "Users" label so you can see what people don't like in the current screens.

**Comment by SCdF** [comment]
I don't think interest in this is high. @garethbowen I'm going to close this since this is our new SOP with tickets like this. Feel free to re-open if you think you should, or start a discussion about how our current system falls down for tickets like this.
