### ISSUE TITLE
sentinel is logging the date twice

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3002]
```
2016-12-08T17:19:35.630Z - info: 2016-12-08T17:19:35.630Z - info: transitions: processing enabled
 
2016-12-08T17:19:35.878Z - info: 2016-12-08T17:19:35.877Z - info: startup complete.
```

**Comment by estellecomment** [comment]
@garethbowen where do you see this happening? I don't see it locally with the latest master, which is also the version of the submodule checked in by medic-webapp. (https://github.com/medic/medic-sentinel/commit/c5c4a9908f7c21d7d3b52c6af00222819432f986)

**Comment by garethbowen** [comment]
That log was taken from standard.app which is a recent version. If it's working perfectly locally I suspect it's gardener (which we don't use in a dev environment) adding the extra date.

**Comment by garethbowen** [comment]
Check if API is too.

**Comment by estellecomment** [comment]
Ha! It is gardener. 
Gardener logs timestamps, sentinel logs timestamps, api doesn't log timestamps.
So we see two timestamps in sentinel + gardener logs.

**Comment by garethbowen** [comment]
Let's just remove the timestamps from sentinel and let gardener do it.

**Comment by garethbowen** [comment]
One small change requested.

**Comment by estellecomment** [comment]
Gareth is out tramping, @alxndrsn can you review https://github.com/medic/medic-sentinel/pull/94 please?

**Comment by garethbowen** [comment]
@estellecomment I think this can be merged now, right?
