### ISSUE TITLE
Deleted message persists until refresh

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3003]
When deleting the last message from a contact it remains in the RHS until a refresh

![image](https://cloud.githubusercontent.com/assets/789512/21034790/67d66d62-bd88-11e6-820d-f736c9a9b689.png)

You can see here that it is removed if it is not the last item, but remains if it is.
![delete message](https://cloud.githubusercontent.com/assets/789512/21035016/22f07e20-bd8a-11e6-82ef-7681088bf511.gif)

Testing using build 4668

**Comment by garethbowen** [comment]
Possibly related: #3001 

Check the other tabs too to ensure we're listening to changes correctly.

**Comment by garethbowen** [comment]
CR please @SCdF : https://github.com/medic/medic-webapp/pull/3164

**Comment by SCdF** [comment]
Looking good G'dog.
