### ISSUE TITLE
Action button items get lost in RHS

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3005]
Feedback that we got during training was that the Action button's items can be lost in the RHS content, as seen in this image:
![image](https://cloud.githubusercontent.com/assets/789512/21035232/931dd124-bd8b-11e6-912b-23ab8af49278.png)

From the design issue (https://github.com/medic/medic-design/issues/16) update the look of those items to stand out more, using icon, `>`, border, and drop shadow:
![image](https://cloud.githubusercontent.com/assets/789512/21035250/b106deba-bd8b-11e6-91b1-025724dbfaba.png)

~~Note that although we do set the icon for tasks, we do not currently do so for forms so we'll have to take that into consideration.~~ _edited based on https://github.com/medic/medic-webapp/issues/3005#issuecomment-265927764_

**Comment by sglangevin** [comment]
Icons are already available for forms (see issue #2794). So perhaps this issue should just be for the other UI elements.

**Comment by estellecomment** [comment]
Screenshots:

<img width="322" alt="screen shot 2016-12-09 at 4 23 39 pm" src="https://cloud.githubusercontent.com/assets/911434/21069135/ee9e52e4-be2b-11e6-97b5-78340bba54d7.png">
<img width="930" alt="screen shot 2016-12-09 at 4 23 56 pm" src="https://cloud.githubusercontent.com/assets/911434/21069136/eea1c4e2-be2b-11e6-8ca3-70012d15a439.png">



If very long form name or tiny screen or both, you get this : 
<img width="239" alt="screen shot 2016-12-09 at 4 25 32 pm" src="https://cloud.githubusercontent.com/assets/911434/21069169/3114f0d8-be2c-11e6-89e0-1c14c84d9576.png">
