### ISSUE TITLE
Extract XML forms into attachments

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3009]
Instead of storing the xml form data on the report's json document we should store it as an attachment. This would greatly reduce the amount of data pushed through view generation, which would help with ram usage and presumably view generation speed.

Because the migration for this will be quite disruptive (it will take awhile and clients will need to re-download their reports) we should consider:
 - Not migrating, changing writing of reports to write attachments, and change reading of reports to support reading inline XML (the current way) as well as reading XML
 - Bundle this change up with deploying the Crosswalk and CouchDB 2.0 changes, which is going to necessitate they download all of their data again anyway.

**Comment by garethbowen** [comment]
Consider doing this at the same time: #2882

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-webapp/pull/3036

**Comment by SCdF** [comment]
@estellecomment would you like to take a look at the PR linked above?

This change supports reading both the old way and the new way, and writing the new way. It can be merged into master once we're happy with its quality.

I'm also going to write a separate PR for a migration script, which we may or may not want to merge at some time of our choosing, when we're OK with lots of data churn occurring. For example, with the CouchDB2.0 merge.

**Comment by estellecomment** [comment]
LGTM!

**Comment by estellecomment** [comment]
Leaving it in Active Work because of one comment, but do what you want.

**Comment by SCdF** [comment]
I've merged the code that deals with loading and storing xml as an attachment. Not closing this ticket until we've had a conversation about whether or not we want to merge the migration.

**Comment by SCdF** [comment]
Actually closing, I'll create a new ticket and have it link here.

**Comment by garethbowen** [comment]
@SCdF This should not be "active work" any more, right?
