### ISSUE TITLE
Scheduled messages not being sent

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3010]
As reported in https://github.com/medic/medic-projects/issues/1168, scheduled messages are not always being sent. We may want to consider making the SMS API idempotent to tolerate potential gateway issues.

Auto replies to SMS are being sent, as are outgoing messages from the Messages tab.

**Comment by abbyad** [comment]
This _may_ be related to https://github.com/medic/medic-webapp/issues/2535 :)

**Comment by garethbowen** [comment]
This should be solved now. @abbyad ?

**Comment by abbyad** [comment]
Indeed, just tested. Thanks!
