### ISSUE TITLE
SMS API sets messages to `scheduled` on POST

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3011]
When Medic Gateway gets the list of outgoing messages it POSTs the SMS API, which changes the state from `pending` to `scheduled`. This leads to confusion and may contribute to https://github.com/medic/medic-webapp/issues/3010

**Comment by garethbowen** [comment]
Consider documenting the message status transitions as part of this.

**Comment by alxndrsn** [comment]
Ref https://github.com/medic/medic-projects/issues/1243

**Comment by alxndrsn** [comment]
Fixed on `master` in https://github.com/medic/medic-api/commit/c6c661d02098887a61c2dfbc9ee90caf62c1dbb2

**Comment by garethbowen** [comment]
Fixed and documented. Will be tested in #3047
