### ISSUE TITLE
Migration for incorrectly generated scheduled messages

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3015]
As reported in https://github.com/medic/medic-projects/issues/1168 scheduled messages aren't being sent. The root cause was fixed in https://github.com/medic/medic-webapp/issues/3010 and released in 0.4.14 however any messages generated prior to upgrading will still be missing the required uuid field.

Write a migration to add a uuid to all scheduled messages which don't already have it. This migration should only be applied to messages that aren't overdue as overdue messages may no longer be relevant (eg: a visit from 3 months ago).

Consider performance implications:

- batch the requests so we don't try and download the entire DB in one go
- only save a report if one or more messages were fixed
- if possible query a view for recent reports/messages instead of all
- perhaps don't do anything when no schedules are configured (eg: LG)

Apply the change to `master`, `2.9.x`, and `0.4.x` branches, and schedule testing and release for a new 0.4 and 2.9 service pack so anyone upgrading and using medic-gateway will work as expected.

**Comment by garethbowen** [comment]
Code review please @alxndrsn https://github.com/medic/medic-api/pull/116

If/when this is accepted we need to backport to 2.9.x and 0.4.x and then bump the submodules in the respective branches of medic-webapp.

**Comment by alxndrsn** [comment]
If there are multiple messages assigned to a single `scheduled_task`, I think only one will be updated.  I will submit a PR with a test case.

**Comment by alxndrsn** [comment]
Extended test seems to fail in two ways:

1. No `uuid` added to the second `messages` item when multiple entries in `messages`
2. No `uuid` added to single `messages` item in the following `scheduled_tasks` entry

**Comment by garethbowen** [comment]
You're absolutely right... *facepalm*

Fixed in the original PR.

**Comment by garethbowen** [comment]
@SCdF This has been merged in https://github.com/medic/medic-api/commit/8abf9b39fb484f25499e9b2367b2ac22b3c1770e . The api submodule needs to be bumped and the patch backported for release. I'll leave this up to you. Thanks!

**Comment by SCdF** [comment]
I've cherry-picked this into the various branches that need it, as well as updated webapp master to contain it.

**Comment by garethbowen** [comment]
No AT required.
