### ISSUE TITLE
Replace gardener

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3017]
Gardener has some major flaws such as log rotation, log spam, reporting.
Use supervisord directly, or some other well supported 3rd party service
Make our node modules top level in the supervisor

**Comment by garethbowen** [comment]
Related: #3018 #3019

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
This is high on our prioritised tech wishlist so I'll schedule it.

**Comment by SCdF** [comment]
Can we close this? I feel like this is superseded by the horti tickets and work

**Comment by garethbowen** [comment]
Yes definitely.
