### ISSUE TITLE
Replace dashboard and markets

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3018]
Dashboard has some major flaws: upgrades are executed from the client so it’s badly affected by poor internet, you can only upgrade to the latest version in the given market, and it’s dead.

- Write custom node app for provisioning
  - Has minimal UI for picking which version to install
  - Knows which version is currently installed
  - Extracts api and sentinel and notifies supervisor
- Publish build artefacts to the same central server (3rd party? http://dev.medicmobile.org/downloads/ ? GH releases?)
- Provide simple admin UIs for anything that can currently only be edited through dashboard settings. 
- Dashboard features to reimplement:
  - Import/Export app_settings
  - Add/Edit custom roles to users
  - Setting “application access” to “Public” (concierge should set automatically)

**Comment by garethbowen** [comment]
Related: #3017 #3019

**Comment by sglangevin** [comment]
Consider https://github.com/medic/medic-projects/issues/32

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
yup, that's still a thing

**Comment by garethbowen** [comment]
Duplicate of #3582
