### ISSUE TITLE
Label not always displayed

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3021]
A label that can be hidden does not show the value of another field, yet an exact copy of the note field that is always `relevant` does show the value:
![image](https://cloud.githubusercontent.com/assets/789512/21393290/c63b7e8c-c761-11e6-9f16-08f6447bc3b3.png)

The field that does not display the label properly does have a line break instead of the referenced value:
```html
<span lang="" class="question-label active"><em>Conditional label:</em> Type in a short note to be sent to <span class="or-output" data-value=" /pregnancy_visit/chw_name "><br>            </span> .</span>
```
vs the working version:
```html
<span lang="" class="question-label active"><em>Always shown:</em> Type in a short note to be sent to <span class="or-output" data-value=" /pregnancy_visit/chw_name ">Mili</span> .</span>
```
I haven't distilled this down to a tiny form. @alxndrsn if you know how to solve this quickly without a test form I can retest quickly on standard.app, otherwise let me know and I'll create a sample test form.

Tested on 4668. Saw similar results for labels of other types of fields.

**Comment by abbyad** [comment]
Here is the relevant xform snippet:

```xml
      <input ref="/pregnancy_visit/more_info/chw_note2">
        <label>*Conditional label:* Type in a short note to be sent to <output value=" /pregnancy_visit/chw_name "/> .</label>
      </input>
      <input ref="/pregnancy_visit/more_info/chw_note3">
        <label>*Always shown:* Type in a short note to be sent to <output value=" /pregnancy_visit/chw_name "/> .</label>
      </input>
```

**Comment by abbyad** [comment]
Based on @alxndrsn suggestion, showing it with a editable text field as the source data:


## Sample text set by default, not shown in conditional field:
![image](https://cloud.githubusercontent.com/assets/789512/21394390/713526a4-c766-11e6-851e-f6ad01e5042e.png)



## Changing the default text the value is displayed properly, regardless of if it was shown or hidden when the change was done:
![image](https://cloud.githubusercontent.com/assets/789512/21394415/90545d84-c766-11e6-8758-57e4ec38875e.png)

**Comment by alxndrsn** [comment]
Looks like a bug in enketo - if the encompassing `<input>` has _never_ been relevant, embedded `<output>` values are not inserted.  If the `<input>` subsequently becomes relevant, the `<input>` value will be blank.  If the bound value is later changed, the `<output>` will be updated as expected.

However, in the following case, the `<output>` is updated as expected:

1. make the `<input>` relevant
2. make the `<input>` irrelevant
3. modify the value
4. make the `<input>` relevant

**Comment by alxndrsn** [comment]
@marc is there an example form for this bug?

**Comment by abbyad** [comment]
Testing on 2.10 and I cannot reproduce this anymore... Is it possible it was resolved in Enketo?

**Comment by alxndrsn** [comment]
Enketo has just been updated on `master`, but in 2.10 it was not updated since 7 Dec 2016.  However, still possible you tested with an older version.

Either way, I'm sure we're all happy that the bug is resolved :¬)  Please re-open if you find it again.
