### ISSUE TITLE
Option to compare against the translation keys

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3022]
We should have the option to select the "Translation key" in the drop down list here:

![image](https://cloud.githubusercontent.com/assets/789512/21411822/6ccfe006-c7b9-11e6-863e-c76260b17241.png)

That way we can compare the text to the translation key, which is useful when looking for those without a translation. It is also helpful when comparing an English label to the key, and also if the label was left blank:
![image](https://cloud.githubusercontent.com/assets/789512/21411909/1323442a-c7ba-11e6-9b6a-729b4390ae10.png)

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
Looks actionable, useful, and straightforward. Scheduling.

**Comment by garethbowen** [comment]
Not a priority - leaving scheduled but kicking out of the iteration.

**Comment by vimemo** [comment]
hi @abbyad, 

Do we want 
two columns: Translation keys | Languages
or 
three columns: Translation keys | Languages | Languages

Should we filter the list of translations by the selected key option?
This would imply having an empty entry key to re-list all translations.

Thanks.

**Comment by garethbowen** [comment]
@vimemo I think we want just two columns still. Add "Translation key" as one of the options in the left hand dropdown. I think it should also be the default option. The default option for the right hand side should be the configured default language.

**Comment by abbyad** [comment]
Ya, that's how I was thinking of it too. Thanks for clarifying.

**Comment by vimemo** [comment]
@garethbowen, please review again. It looks cleaner now with your suggestions.

**Comment by garethbowen** [comment]
Merged. Nice one.

**Comment by sglangevin** [comment]
Tech leads will be grateful for this one! cc @ngamita @derickl

**Comment by ngaruko** [comment]
LGTM
