### ISSUE TITLE
Medic OS: Create manual page packages, i.e. make `man` work

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3023]
Create installed-by-default packages that supply documentation via the `man` command. This will make troubleshooting easier, especially for members of the team who aren't familiar with the limitations of `busybox` or `ash`.

Use a `<packagename>-docs` convention, and supply the `man` command as part of the base system image.

**Comment by browndav** [comment]
I've identified a point in the build process where we can grab and package the manual pages. Each package currently has a `prepare-dist` script that does all of the size-optimization/trimming/deleting; I've tested that this is indeed the case, found an easy a way to stop the build prior to the `prepare-dist` execution, checked that `man ` exists and seems to work in Busybox, and thought through how to package the documentation. Today: do it.

**Comment by garethbowen** [comment]
@browndav When setting to Code Review we assign someone to review it - can you pick a volunteer please?

**Comment by garethbowen** [comment]
Randomly picking @SCdF to code review.

**Comment by SCdF** [comment]
@browndav I get the code changes you've made, and I see that this provides the *ability* to make `man` work. I'm not seeing that it actually *does* though.

Come chat to me when you're around.

**Comment by garethbowen** [comment]
@browndav @SCdF Any updates on this?

**Comment by browndav** [comment]
You're totally right – I dropped the ball here. Left a changeset out and then lost track of the issue. I'll punt this back to active work, put it in the current iteration, and get it addressed and documented this week.

**Comment by browndav** [comment]
This is fun: the Busybox implementation of `man` requires a troff-compatible `nroff`, but doesn't ship with one. I'll figure out how to get this compiled and added to the `core` package. Then we should just need a `profile.d` script to configure `$MANPATH` (likely shared by all documentation packages).

**Comment by alxndrsn** [comment]
Would it be more optimal (time & space) to just have a link to the relevant ash & busybox manpages online somewhere in the medic-os docs (e.g. on the github README)?

**Comment by alxndrsn** [comment]
Would it be more optimal (time & space) to just have a link to the relevant ash & busybox manpages online somewhere in the medic-os docs (e.g. on the github README)?

**Comment by garethbowen** [comment]
Clearly not a priority - moving out of the iteration.

**Comment by alxndrsn** [comment]
@browndav PR at https://github.com/medic/medic-os/pull/15
