### ISSUE TITLE
Ensure various $PATH variables are sane, backport fix if needed

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3024]
By default, a Medic OS system should have binaries from installed packages like `medic-core` (e.g. `nginx`) in the `$PATH`, with all appropriate dynamic libraries also available via /etc/ld.so.conf or `$LD_LIBRARY_PATH`.

It's likely this fix has already been made. Check that it works with a new build, and make sure whatever failure mode is at work won't bite us again.

**Comment by garethbowen** [comment]
Duplicate of https://github.com/medic/medic-webapp/issues/2750 ?

**Comment by browndav** [comment]
For sure, good catch. Added the more detailed one to the milestone; closing this.
