### ISSUE TITLE
Medic OS: Provide symbolic links for logs beneath /var/log

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3025]
Most Linux administrators are accustomed to finding *something* useful beneath `/var/log`. We currently store our logs on a per-package basis beneath `/srv/storage`. Provide some automatic way to type something useful along the lines of `ls /var/log/medic-core/nginx/*.log`.

**Comment by browndav** [comment]
Didn't mean to do that quite yet.

**Comment by garethbowen** [comment]
Randomly assigning @SCdF for CR

**Comment by SCdF** [comment]
@browndav it all looks fine. What's up with all the duplication? Is that something we can look at solving? I also noticed we had `node_modules` checked in, in at least one place. Is that also something we would want to look at fixing?

**Comment by browndav** [comment]
The duplication is ugly and I'm embarrassed by it. Each of the painfully-identical helper scripts is in a separate package, but they could surely be factored out into the base set of package/service scripts (i.e. in the root filesystem `initrd` image). I wasn't quite sure how to factor it at the time when I was going through each package, but it's pretty clear now. I'll file.

The inclusion of `node_modules` is definitely something we can fix – the place where I'm seeing it is in the `concierge` first-run/setup app at https://github.com/medic/medic-os/tree/master/platform/packages/concierge/software/concierge/v1.1.0/node_modules. What I'd really like to do is spin `concierge` off to a separate repository, and then have the OS build process fetch it from an `npm` release of that repo. I'll file an issue and mention it here.

**Comment by SCdF** [comment]
@browndav OK well I think we can move this to AT now.

**Comment by SCdF** [comment]
@browndav if you don't think this has any merit in being AT'd then move it to ready :-)
