### ISSUE TITLE
Character not properly rendering in Windows.

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3027]
![image](https://cloud.githubusercontent.com/assets/6979995/21624501/346d8020-d26c-11e6-90bd-3df4ec94f1b5.png)

**Comment by SCdF** [comment]
This is how it looks in MacOS:
![image](https://cloud.githubusercontent.com/assets/583851/21624540/5ff97316-d26c-11e6-8a05-72a7140c20ee.png)

**Comment by garethbowen** [comment]
Related to, or duplicate of: #3020

**Comment by ngaruko** [comment]
Duplicate.
