### ISSUE TITLE
Bubble task count not showing on browser refresh

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3028]
1. Steps to reproduce:
Find a family with a member that has a task >> Bubble shows
![image](https://cloud.githubusercontent.com/assets/6979995/21625257/a88ac00a-d26f-11e6-96f5-d2511190b23f.png)

Then refresh the page  >> Bubble does  not show when the browser loads.
![image](https://cloud.githubusercontent.com/assets/6979995/21625312/eeb7b8d0-d26f-11e6-975d-78803309d7b6.png)

Navigate away from the page and come back  >>the bubble shows again.

>> Running app on Windows 10, with Chrome 55.

**Comment by garethbowen** [comment]
PR please @SCdF https://github.com/medic/medic-webapp/pull/3080

It turns out ng-init is evil...

> This directive can be abused to add unnecessary amounts of logic into your templates. There are only a few appropriate uses of ngInit, such as for aliasing special properties of ngRepeat, as seen in the demo below; and for injecting data via server side scripting. Besides these few cases, you should use controllers rather than ngInit to initialize values on a scope. 
https://docs.angularjs.org/api/ng/directive/ngInit

**Comment by SCdF** [comment]
Huh, TIL.

LGTM. Merged.
