### ISSUE TITLE
"Targets" tab blank for admin users

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3029]
On the web app from page, the targets tab is blank. This is due to the fact that admin users may not have targets configured. Instead of leaving the page blank, it would be nice to show a message that explains the case.
![image](https://cloud.githubusercontent.com/assets/6979995/21630299/bf131154-d294-11e6-809f-858652e2b2d3.png)

**Comment by garethbowen** [comment]
I think this is the case for all users. There are 3 types of targets and IIRC the default configuration is for all of them to be disabled.

**Comment by garethbowen** [comment]
PR please @estellecomment https://github.com/medic/medic-webapp/pull/3079

**Comment by estellecomment** [comment]
LGTM.
Not closing because it also needs the translation string added.

**Comment by estellecomment** [comment]
nvm it's already in. Cool.

**Comment by estellecomment** [comment]
Looks like admins do have analytics module `targets`, so the message isn't being displayed. (but no targets are coming out of the rules engine, so nothing to display).
@ngaruko flagged this. 
So back to you @garethbowen !

**Comment by ngaruko** [comment]
I saw the message when it first loaded/upgraded. Then I wandered a couple of clicks away and back to the Targets tab, now there was no message.

![image](https://cloud.githubusercontent.com/assets/6979995/22435631/a8c668b4-e785-11e6-9407-9275209f0d64.png)

**Comment by garethbowen** [comment]
Ok, that's a different case again. Fixed now.

**Comment by garethbowen** [comment]
@estellecomment Code review please (no PR, just committed straight to master).

**Comment by estellecomment** [comment]
LGTM! Passing along the chain to Bede :)
