### ISSUE TITLE
Travis passes tests, but `"cat nohup.out" exited with 1`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3035]
Travis completes tests, then runs `cat nohup.out`:
![screen shot 2017-01-05 at 13 26 55](https://cloud.githubusercontent.com/assets/911434/21680550/b6dd1064-d34a-11e6-822f-fc7e94bfef5f.png)

End of log : 
![screen shot 2017-01-05 at 13 25 56](https://cloud.githubusercontent.com/assets/911434/21680521/8c7a4f30-d34a-11e6-8881-3d07a9a9d4b4.png)

Full log : 
[travis_job_4707.2.txt](https://github.com/medic/medic-webapp/files/687231/travis_job_4707.2.txt)

Maybe the nohup file just disappeared from underneath `cat` because stuff shut down? Don't know why all that stuff is in the nohup file in the first place (it's the case also in successful runs...)

🐱 📁

**Comment by SCdF** [comment]
@estellecomment I got this as well, for the Node 7.x build. Do you remember if that was the same situation for you?

The reason we cat it out is if anything fails we can see the log. We could potentially change it to only cat out if there has been a failure, we'd have to look into if we can detect that.

**Comment by estellecomment** [comment]
No, v6. From log, says
```
$ node --version
v6.3.1
$ npm --version
3.10.3
$ nvm --version
0.32.0
```

**Comment by mandric** [comment]
```if [ -f nohup.out ]; then cat nohup.out; fi```

**Comment by estellecomment** [comment]
Again! This time node 6.3, node 5 and node 7 pass.
Full log : [travis_193832825.txt](https://github.com/medic/medic-webapp/files/720265/travis_193832825.txt)

**Comment by estellecomment** [comment]
Again, node 6 fails, node 5 and 7 pass
[travis_194507754.txt](https://github.com/medic/medic-webapp/files/724225/travis_194507754.txt)

**Comment by SCdF** [comment]
I presume @mandric's suggestion was something to implement and not just idle musings, so I did. We'll see if it helps.

**Comment by estellecomment** [comment]
Again
Job 204512948, PR 3148
[log.txt](https://github.com/medic/medic-webapp/files/796037/log.txt)

**Comment by SCdF** [comment]
@estellecomment so I implemented @mandric 's suggestion and it clearly didn't help. Someone is going to have to actually put their back into it and look into this.

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
Reads `cat nohup.out || true`.  I don't think this is likely to fail.

**Comment by SCdF** [comment]
@alxndrsn this actually still fails all the time, even with that `|| true`. It's really weird. I don't think we need a ticket for it lying around though, it clearly doesn't happen frequently enough for it to be a concern.
