### ISSUE TITLE
backup partition full on backup server

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3038]
```
/dev/xvdb2     1004G 1004G     0 100% /srv/backup
```
We should also add some kind of monitoring for this but probably a separate ticket.

**Comment by mandric** [comment]
@browndav any updates here?

**Comment by browndav** [comment]
Please go ahead and schedule/perform the drive resize. Suggest a factor of two increase. Coordinate with Henok if necessary; this is something he's done on other instances IIRC and could assist with.

**Comment by mandric** [comment]
@browndav I've never done a volume resize on AWS.  Can you handle this?

**Comment by browndav** [comment]
Sure, can we hit the SSL/TLS cert issue at the same time?

**Comment by henokgetachew** [comment]
I can take care of this tomorrow if you guys need to focus on other stuff.

**Comment by henokgetachew** [comment]
I can't see this instance listed anywhere in EC2.  What's the name of the instance?

**Comment by henokgetachew** [comment]
This looks like it's already been fixed by @browndav.
```
/dev/xvdb2      2.0T  1.1T  824G  58% /srv/backup
```
We should close this issue.

**Comment by mandric** [comment]
Not sure if we need any code review or AT here, thoughts anybody?

**Comment by browndav** [comment]
No AT needed. Marking as released and closing.
