### ISSUE TITLE
'Access denied error' when signing in as restricted user 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3039]
Steps:

Login as admin

Create a user (restricted to a place) >> Configuration >>Users >>Add User
Log out
Login as the created user
>>Access denied error message as in screenshot
![image](https://cloud.githubusercontent.com/assets/6979995/21785067/ea9c7698-d722-11e6-81ad-437d37f440fe.png)

Note: This is in Chrome, normal mode. alpha.dev version 2.10.0-alpha.4715

In firefox (similar to another closed isssue- couldn't get my finger on it): 
![image](https://cloud.githubusercontent.com/assets/6979995/21785083/f810dc2e-d722-11e6-9382-c7324c73f589.png)

**Comment by SCdF** [comment]
This was because @ngaruko created the user "incorrectly", as in without a linked contact and with a place that didn't make sense.  I believe Bede will be instigating a conversation around the creation of users to see if it can be done in a more intuitive and less flaky way.

**Comment by ngaruko** [comment]
I guess we need to have a conversation around some UI validation and error messages. I understand most of it is done during configuration, but we still need to investigate ways the UI interaction and workflows can be more reliable, more intuitive and less prone to invalid entries.

**Comment by SCdF** [comment]
Quite a bit of it yeah. I'm not sure if you can configure the create user stuff, but if not there is at least defaults there that we should be using correctly.
