### ISSUE TITLE
Invalid user should not be allowed to be created.

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3041]
At the moment, when creating a user (Configuration >> Users >>Add User), the 'Place' and 'Associated contact' fields are optional. But when those are left out, the created user is 'invalid' for all intents and purposes. I would suggest this to be compulsory. And ideally, once a place has been selected, the 'Associated contact' selection/choices should be limited to those contacts that are associated to the place selected. That way, it would prevent the user to be associated to a contact that is not in the place selected.  
![image](https://cloud.githubusercontent.com/assets/6979995/21868742/297137ea-d8b9-11e6-9830-7a1403ac3f80.png)

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by ngaruko** [comment]
I guess this 'feature' has been implemented (not sure if it was covered by another issue). 
![image](https://user-images.githubusercontent.com/6979995/30456329-437f980c-99f7-11e7-8e34-700fe42124ec.png)
The only thing that was raised by #3561 is marking `Place` and `Associated Contact` (asterisk or otherwise) as required when the user select `Restricted to their place` for `User type`.  I am going to close this unless there is an objection @garethbowen @estellecomment .

**Comment by garethbowen** [comment]
Sounds good. I'll triage the other one. Should be trivial...
