### ISSUE TITLE
Updating password logs out user?

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3046]
Steps to replicate:

1. logged in as admin on alpha.dev (with a 'Full-Access' created user)
2. Configuration >> User settings >>Update password
3. The browser goes back to the login page with the follow console errors:
![image](https://cloud.githubusercontent.com/assets/6979995/21925760/b6a64db4-d9e3-11e6-9f7e-426c8a54bdf2.png)

Is that expected behavior?

**Comment by SCdF** [comment]
That's interesting.

Does that happen with restricted users as well? I'm wondering if that is simply a limitation of us using CouchDB as the holder of authentication, and so when we change the password everything invalidates. I presume if you then log in again everything's fine?

We could look at making this a smoother process. However, the advantage of how we currently deal with not being authenticated (kicking you to the login page) has far fewer side effects and edge cases than dealing with authentication "in app".

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
Seems like this is being discussed in other venues and is related to other password management discussions happening. Closing for now, but we can revisit as part of password management.
