### ISSUE TITLE
API's sms-gateway controller is misusing message statuses

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3047]
The `sms-gateway` controller is picking up all `pending` messages, and forwarding these to `medic-gateway`.  This is correct.

After this, the controller changes the status of these messages to `scheduled`.  This is **incorrect**.  `scheduled` in fact means that the message will, at some point in the future, be changed to `pending` by `sentinel`.

Identify a different state to mark a message as having been forwarded to the gateway.  A suitable status might be: `forwarded-to-gateway`.

**Comment by abbyad** [comment]
Looks like a good approach to me.

**Comment by mandric** [comment]
If something is set to forwarded-to-gateway and never sent (gateway dies for example), what happens?

**Comment by alxndrsn** [comment]
I'll be dealing with that today in https://github.com/medic/medic-projects/issues/1243, which will render this quick fix for the project teams no longer useful.

**Comment by alxndrsn** [comment]
Can I move this to Acceptance Testing, now that the PR has been approved?

**Comment by mandric** [comment]
Sure, but I don't think anyone knows how to do acceptance testing but you Alex?  Or how would we proceed with acceptance testing? Or maybe it's not never necessary?

**Comment by garethbowen** [comment]
This has been fixed in 0.4 and 2.10

**Comment by ngaruko** [comment]
Any clue how to AT this @alxndrsn ?
