### ISSUE TITLE
require `type` property on docs

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3049]
Add this minimum requirement to validate_doc_update.

**Comment by garethbowen** [comment]
If this is added to validate_doc_update we'll also need to add a migration to ensure all existing docs have a type, otherwise editing the docs will fail.

Why do we need to enforce this? Surely it should be decided on a case by case basis?

NB: ddocs don't have a type...

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
Closing as per my previous comment.

**Comment by mandric** [comment]
Most of our validation or any type of validation we do in the future will be based on the `type` property.  It's a good starting point to adding more sanity to the database.  I don't see a migration as much of a blocker especially since there shouldn't be any normal docs (not design docs) that do't have a `type` property, if there are then they are probably not used?

**Comment by garethbowen** [comment]
@mandric I think it's valid to have docs without a type. For example, if we have a singleton doc that stores stuff like what migrations have run it can be uniquely identified by the id so there's no need for a type too (this isn't the way that particular example works now but it could do...) If future validations are based off the doc type they can ignore docs without a type.

Why do you think all docs must have a type?

**Comment by mandric** [comment]
All docs should have a type because that's how we validate docs, by looking at the type and then checking if we have required properties.  There might be an exception or two but that's the general rule.  I know it's not required but I think we've developed a nice convention around it and should go the extra step and have a list that we support.  It doesn't have to be `type` but I'm pushing for a way to add constraints where possible for sanity in the db.  It could be `type` or we can also look at `_id` and confirm we recognize it and have some documented constraints/expectations for the docs we store.

**Comment by garethbowen** [comment]
Reopening. Perhaps this is part of a larger discussion about data validation. I'll add it to the list of things to discuss at next week's tech talk.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
@garethbowen did it ever get discussed? 

FWIW I can't imagine it ever being scheduled, because it's not clear what point or value it provides, especially given that it's use is directly proportional to the pain of the required migration.

**Comment by garethbowen** [comment]
It didn't really get discussed. From what I recall there's a general feeling that all documents should have a type (except for ddocs which can't) but nobody could state a use case for the type. I don't think the migration would be too painful because almost all docs have a type already so it'd only be modifying a few docs.

For me this is very low priority - it'd be much more useful to split the `data_record` type into `report` and `message`, and to merge the 3-4 place types to just `place`.

I'll leave it up to you to triage as you see fit...

**Comment by SCdF** [comment]
@mandric did you have any strong opinions. My thought is close.

**Comment by mandric** [comment]
I'd like to add more strictness to the database so you can't just add any doc willy-nilly.  I'd like to see a check for known "types" either using the `type` property or the `_id` property.  Either one should allow us to link to a schema later and know what a document's purpose is and its expected structure.  Can't think of any better way to start adding more meaning to our database.  That's the value add and I've stated this a few times already, but happy to repeat myself or reflect on the past again.  

Also agree with Gareth it's a low priority and I see no issue with the db migration (would be small if you compare to most others).  I'm pro this idea especially as we continue to add more different types and meta docs, so we are certain we understand (and write documentation on) each doc type that is in the database.

**Comment by SCdF** [comment]
Cool, we'll leave it around for another round then. If there is enough interest it can be pushed to be done, or at least scheduled / architected out / planned, if there's not then it can't be that important and we can close it.

**Comment by dianabarsan** [comment]
@garethbowen , @SCdF 

Have there been any updates / discussions on this?

**Comment by SCdF** [comment]
Nope. I'm happy to close this as low priority / low interest.
