### ISSUE TITLE
add documentation for medic-gateway protocol

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3053]
Related:
https://github.com/medic/medic-api/pull/117
https://github.com/medic/medic-projects/issues/1243

This API module has no documentation: https://github.com/medic/medic-api/blob/master/controllers/sms-gateway.js
Maybe just document the protocol in medic-gateway and then link to it from medic-api for time being?  The documentation would not only help us understand how the gateway processes messages and handles all the different states and behaves when requests or responses fail, but also allow someone to potentially build a gateway using a different language or platform.

**Comment by alxndrsn** [comment]
Is https://github.com/medic/medic-api/blob/master/controllers/sms-gateway.js#L3 sufficient?

**Comment by garethbowen** [comment]
I've added some documentation. Handing over to @mandric to finish it off (if necessary).

**Comment by estellecomment** [comment]
added more things : https://github.com/medic/medic-docs/pull/11

**Comment by garethbowen** [comment]
@estellecomment It looks like the comments in your review have been fixed - can you please rereview the PR and if good merge and close this issue?

**Comment by estellecomment** [comment]
It's waiting on rereview by @alxndrsn

**Comment by garethbowen** [comment]
Looks like this has been reviewed. Closing.
