### ISSUE TITLE
Write documentation for migrations

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3055]
We don't have any documentation for migrations!

 - [ ] what's a migration?
 - [ ] what runs the migration, and when? 
 - [ ] `meta` doc that stores previously run migrations
 - [ ] how to run a migration "by hand" for testing?
 - anything else?

**Comment by SCdF** [comment]
@estellecomment I wrote up something in the README, let me know if that's what you were looking for: https://github.com/medic/medic-api/pull/120

**Comment by estellecomment** [comment]
![43863709](https://cloud.githubusercontent.com/assets/911434/22649995/a7141ad2-ec7d-11e6-86a6-ecfd45fe45b8.jpg)

**Comment by estellecomment** [comment]
Thank you! Couple comments on commit, for extra detail : https://github.com/medic/medic-api/commit/295fcc8e7c66abed302af85621c0c4ced06688be

**Comment by estellecomment** [comment]
@SCdF : https://github.com/medic/medic-api/commit/c9f92869a049e17dc3a353c394e44f02bfaafa19
