### ISSUE TITLE
Support `required_message` and `required_message` translations in Enketo

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3056]
Enketo does not support `required_message` or translations of `required_message` by default, according to the xlsform reference table (http://xlsform.org/ref-table/). This is a challenge for projects operating in languages other than English (e.g. Muso). Their CHWs are getting an English message ("This field is required") because we are not able to provide a translation. In fact, we aren't even able to customize the English message. For projects in other languages, we'll need to be able to support translation of all form fields, labels and messages, which includes translation of the required message.

**Comment by alxndrsn** [comment]
This is a javarosa extension - `jr:requiredMsg`.  Enquire if support is planned in enketo.

**Comment by alxndrsn** [comment]
Related: #1373

**Comment by alxndrsn** [comment]
Translation of `jr:requiredMsg` will depend on #3174

**Comment by alxndrsn** [comment]
`requiredMsg` support should be introduced by #3228

**Comment by alxndrsn** [comment]
@sglangevin do you have any examples when we would want to customise English required message?

**Comment by alxndrsn** [comment]
There are a few issues here:
1. enketo has a built-in translator, currently used for a very limited set of messages, which needs re-implementing and overriding in browserify
2. we need to scan forms for `data-i18n` attributed nodes and translate these at form display time
3. do we actually need support for custom require messages??  This should work out of the box, but only worth checking if we actually need this feature

**Comment by alxndrsn** [comment]
Fixed for standard required messages.  This change adds at least three new translation keys:
```
enketo.form.required = required
enketo.constraint.invalid = Value not allowed
enketo.constraint.required = This field is required
```
These values were previously hard-coded in English for all languages.

**Comment by garethbowen** [comment]
One small change please.

**Comment by sglangevin** [comment]
@alxndrsn I'm not sure if you are still looking for an example, but we wanted to be able to translate "This field is required" and "Required" into the language that the form is being rendered in. So for a project where the users are loading forms in French, we wanted to customize those messages so they would appear in French. This applies to all forms in the Muso Mali project - here is a link to an example:
https://github.com/medic/medic-projects/blob/master/muso/forms/tori/patient_assessment.xml (XML)
https://github.com/medic/medic-projects/blob/master/muso/forms/tori/patient_assessment.xlsx (XLSX)

**Comment by alxndrsn** [comment]
@sglangevin these should now be translatable via the standard translations, using the following keys:
```
enketo.form.required = required
enketo.constraint.invalid = Value not allowed
enketo.constraint.required = This field is required
```
