### ISSUE TITLE
Meaningful error on creating/updating user

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3060]
Steps to replicate:
1. Login as admin
2. Configurations
3. Users
4. Add User
5. use invalid 'username' (say Capitals for example, ie :MYUSERNAME)
6. Add password >> Click update
7. Current behavior: Goes 'Submitting', then 'Error updating user'
8. Expected: An error message in the lines of "the username must be all lowercase, so many characters, no space, whatever", preferably without attempting to submit (as it is if one skips password for example) or better yet validate as the user types (?)
![image](https://cloud.githubusercontent.com/assets/6979995/22087826/1864e726-de45-11e6-9278-b5e94d27c0e0.png)

**NOTE**: The issue of 'capitalization' of user name is still under discussion and this issue takes the current state of affairs as given. Should a decision be made to allow case insensitive input, that will be another issue altogether.

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
Seems useful, but not related to current sprint goals. Marking as Scheduled.

**Comment by rmhowe** [comment]
Appears to have been fixed as part of https://github.com/medic/medic-webapp/issues/3778
