### ISSUE TITLE
code review open PRs in medic-server

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3061]
https://github.com/medic/medic-servers/pulls assigning to browndav, but anyone who needs to maintain servers occasionally can review it.

**Comment by garethbowen** [comment]
@browndav What state are these PRs in?

**Comment by browndav** [comment]
I've not had time to code review https://github.com/medic/medic-servers/pull/2. Assignment was unsolicited, so I've removed in hopes that someone else can pick it up.

**Comment by mandric** [comment]
Sorry @browndav multiple solicitations here: https://github.com/medic/medic-webapp/issues/821#issuecomment-241423714

**Comment by SCdF** [comment]
Both linked code reviews have been done @mandric, I'm guessing this ticket is just closable but I'll leave it to you
