### ISSUE TITLE
When changing password, the old password is not requested

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3065]
![screen shot 2017-01-20 at 17 54 31](https://cloud.githubusercontent.com/assets/911434/22163333/87e64cbc-df39-11e6-8eef-36ae2d53f46a.png)

Doesn't ask for the old password. So if I get a hold of your session when you left your laptop/phone open and went to pee, I can change your password on you.

**Comment by abbyad** [comment]
That seems like a feature to me! :)

**Comment by estellecomment** [comment]
Like... really? I can't tell written irony @abbyad :D

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Marking as a duplicate of #3910 .
