### ISSUE TITLE
When creating a "restricted to a place" user, the "place" field should be required

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3067]
![screen shot 2017-01-20 at 18 02 39](https://cloud.githubusercontent.com/assets/911434/22163616/aa062ec4-df3a-11e6-97e5-4853453a6f8a.png)
If you create a "restricted to their place user" with an empty "place" field, you get a messed up situation. We shouldn't allow it.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
Happy Friday @alxndrsn ! You get a code review!

**Comment by alxndrsn** [comment]
@estellecomment is there a commit missing from the PR?  I don't see any of the fixes which you say you've done :thinking:

**Comment by estellecomment** [comment]
forgot to push!! :woman_facepalming: Sorry about that, done, PTAL!

**Comment by estellecomment** [comment]
thanks!

**Comment by ngaruko** [comment]
LGTM. @estellecomment  I am just thinking (maybe more for consistence than anything else), are we able to mark those 'required' marked with an asterisk (*)?

**Comment by estellecomment** [comment]
Yeah @ngaruko, I thought about that. They're only required for restricted users, not the other kinds of users. I'm not sure what the standard is in this case. Would you only display the asterisk when the selected type is restricted user?

**Comment by sglangevin** [comment]
I think that would be ideal @estellecomment - show the asterisk if "restricted user" is selected.

**Comment by estellecomment** [comment]
Filed https://github.com/medic/medic-webapp/issues/3561.

**Comment by ngaruko** [comment]
Sounds good @estellecomment , @sglangevin
