### ISSUE TITLE
medic-api migration to remove couchmark

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3068]
I think we forgot to add a migration to remove couchmark after [it was removed in sentinel](https://github.com/medic/medic-sentinel/commit/ddbad07a4e709f69ded2d0eb8c8194abc8581dc1).  The couchmark database and views are a space hog and we should remove it in 2.x.  

In [testing 2.x migration](https://github.com/medic/medic-projects/issues/1249) the space filled up on the drive during medic-api migrations and one way to help to avoid that is deleting couchmark.

**Comment by garethbowen** [comment]
Maybe set the date on the migration so it runs before all/most of the other migrations.

**Comment by garethbowen** [comment]
CR please @mandric https://github.com/medic/medic-api/pull/121

AT: ensure the migration hasn't yet been executed (if it has, find the `type:"meta"` doc and delete the "drop-couchmark-db" entry from the list of migrations), create a couchmark db if you don't have one already, start the api, ensure the db is deleted.

**Comment by mandric** [comment]
I can AT this if you want.

**Comment by garethbowen** [comment]
Yeah fair call. I think we're going to need to find a way to stop sentinel during API migration but I'm not sure how to do that...

**Comment by mandric** [comment]
Maybe just test a bit, see what happens in a real world scenario and if anything we add a note to shutdown sentinel before upgrading 0.4.x -> 2.x?  For a 2.x migration though we could add something in sentinel that looks at the migrations meta doc?  The easiest way I can imagine these two processes communicating is by using a special doc.

**Comment by ngaruko** [comment]
I guess this does not any more AT @mandric ?
