### ISSUE TITLE
Cannot access all fields for contact in select2

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3069]
We are seeing issues now that the select2 for contacts returns a summary and not the entire contact's doc. For instance, [age cannot be calculated](https://github.com/medic/medic-projects/issues/1259). This is increasingly important as custom fields may be added to contact's docs with #2913.

Excerpts from a conversation with @garethbowen Nov 14, 2016:
> The widget uses the Search service which gets summaries of the docs where possible for performance reasons
> That means not all fields are available for binding
> This is a change from 2.8 to 2.9 so it may cause regressions in existing forms
> I hit it on a form where it was doing some validation on the DOB but the DOB field isn't included in the summary
You can see the summaries here: /_utils/database.html?medic/_design/medic-client/_view/doc_summaries_by_id
> eg: `{_rev: "4-b6c6b1d61b1cfee453155ac0fbd6b5b4", name: "Dave", phone: "+64277777777", type: "person", place: ["Sample Area 3", "Sample Center", "Sample District"]}`

**Comment by garethbowen** [comment]
We have to be very careful when increasing the amount of information returned as it can have a massive performance impact. Ideally we'd only fetch the full doc when an item is selected.

**Comment by abbyad** [comment]
> Ideally we'd only fetch the full doc when an item is selected.

I was hoping that would be possible... use the summaries for the Select2 list, then get the full doc only for the selected item.

**Comment by abbyad** [comment]
Perhaps a grey area but I would call this a Regression, not a Feature Request, since it was working in v2.8.

**Comment by SCdF** [comment]
So the feature request would be: once you click on a entry in the select2 dialogue, asynchronously load the entire document?

**Comment by sglangevin** [comment]
Yes, we need the rest of the document so that when we fill in the form, the other fields in the document are available for form logic. Things like age, sex, etc.

**Comment by SCdF** [comment]
@garethbowen take a look at https://github.com/medic/medic-webapp/pull/3101

Check out how `db-object-widget` works, it currently does the heavy lifting to automatically convert select2 data into Enketo data. All this code does is hydrate on change and then re-fire the change event (we do a similar thing when we set the initial value in select2 if you're loading existing data).

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by SCdF** [comment]
Talked to Gareth, we're all good in the good. Merging.

**Comment by SCdF** [comment]
To AT this, you may want to talk to @sglangevin to confirm the specific use case they have (ie the form that they're building) now works as they'd like.
