### ISSUE TITLE
Update Password should be disabled for admin users?

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3071]
Steps to reproduce;
1. Login as admin
2.Configuration, User settings, Update password 
3. Type in some 'password' 
4. At the moment, nothing happens.... well it looks like it has been submitted but the password is not actually updated.

Speaking to @garethbowen , ' we dropped support for changing admin password because it's complicated in couchdb 2'. So we need to disable the feature.
Alternatively, if we think we might change our mind around this in the future, we may display some message when an 'admin' tries to update password.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
I don't really want to fix this.

Instead, I want to disable admins from signing in at all.

That way, anyone who has access to the web app should be able to change their password, because none of them are magic special case users.

Closing,
