### ISSUE TITLE
Add gateway message delivery statuses 

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3073]
Change the status of messages to `forwarded-to-gateway` in medic-api before returning them to the gateway. Modify the view query to request all messages in either `pending` or `forwarded-to-gateway` state. This means messages may get sent to gateway twice (which gateway handles) but won't get lost if the request fails. This will give us more information for what's going wrong if messages aren't being sent. Currently the view doesn't support querying by multiple statuses but as far as I can tell the sms-gateway controller is the only consumer of the view, so we can probably modify the view to return exactly what we need.

Modify medic-gateway to call medic-api and change the status of received messages to `received-by-gateway` after they have been successfully written to the database. This will stop them being sent again next query and reduce the bandwidth requirements.

This is an improvement for the code written to solve https://github.com/medic/medic-projects/issues/1243

**Comment by estellecomment** [comment]
To be sure I get this right : @garethbowen is this what you mean? Changes from [current version](https://github.com/medic/medic-docs/blob/master/user/message-states.md) are in italics.
cc @alxndrsn 

Event | webapp state | gateway status
------|---------------|---------------
Report comes in | scheduled | ---
Due date to send the message passes | pending | ---
Gateway polls webapp **~and gets the message~** | pending | ~pending~ ---
**Webapp sets status of message to  forwarded-to-gateway** | **forwarded-to-gateway** | **---**
**Webapp replies to gateway's poll with message to send** | **forwarded-to-gateway** | **---**
**Gateway saves message in its DB** | **forwarded-to-gateway** | **pending**
**At next poll, Gateway confirms it saved the message from webapp** | **received-by-gateway** | **pending**
Gateway sends the message | received-by-gateway | unsent
Gateway reports having sent the message | sent | sent
Gateway gets report that message is received by recipient | sent | delivered
Gateway reports to webapp that message is received by recipient | delivered | delivered

If so, then webapp would only be sending "forwarded-to-gateway" messages to gateway, since it changes pending -> forwarded-to-gateway before sending to gateway?

**Comment by garethbowen** [comment]
@estellecomment Yeah that looks good. Just an FYI that it's `api` that is polled and sets the status and replies and so on, not `webapp`, but that's a technical detail.

**Comment by estellecomment** [comment]
> Change the status of messages to forwarded-to-gateway in medic-api before returning them to the gateway. 

Done

> Modify the view query to request all messages in either pending or forwarded-to-gateway state.

Done

> Modify medic-gateway to call medic-api and change the status of received messages to received-by-gateway after they have been successfully written to the database. This will stop them being sent again next query and reduce the bandwidth requirements.

Wait for it...

**Comment by estellecomment** [comment]
Ok, so the timeline above, and what we currently have in documentation, is wrong. This is *what actually currently happens* (before the changes in this issue/branch) for WO messages : 

Note : Gateway only sends a status update for a message only if the "needs forwarding" flag for the message status is true, and then sets it back to false. So it only sends status updates once.

Event | webapp state | gateway status | gateway "Needs forwarding" flag
------|---------------|---------------|-----
Gateway polls and gets a new WO message | pending | --- | ---
Gateway saves message in its DB | pending | UNSENT | false
Gateway sends the message | pending | PENDING | true
Gateway reports PENDING status for the message | forwarded-by-gateway | PENDING | false
Gateway gets confirmation the message left | forwarded-by-gateway | SENT | true
Gateway reports SENT status for the message | sent | SENT | false
Gateway gets confirmation the message arrived | sent | DELIVERED | true
Gateway reports DELIVERED status for the message | delivered | DELIVERED | false

**Comment by estellecomment** [comment]
Extra note : If api sends the same WO message again, then gateway sets its `needs forwarding` flag to `true`, and so sends the status at the next poll. 

So if line `1` above happens twice for some reason, then at the next poll gateway will share UNSENT, which will set webapp state to `received-by-gateway`.

**Comment by estellecomment** [comment]
Splitting off to another issue (#3408), since it can be done independently :
>  Modify medic-gateway to call medic-api and change the status of received messages to received-by-gateway after they have been successfully written to the database. This will stop them being sent again next query and reduce the bandwidth requirements.

So it's all done! 🎆

@garethbowen please review :
api : https://github.com/medic/medic-api/pull/145
webapp : https://github.com/medic/medic-webapp/pull/3406
docs : https://github.com/medic/medic-docs/pull/16

**Comment by garethbowen** [comment]
Nice one! One regression with the view, but otherwise looks all good to me.

**Comment by estellecomment** [comment]
The sorting by date is tricky when you want to also filter by more than one state.
AFACIT you can't query `[<’pending’ || ‘forwarded’> , <any date>]`

Options are : 
 - index by pairs of states, and query `['pendingorforwarded', {}]` -> lots of emitting, crazy big view, don't like this
 - query once for `['pending', {}]` and a second time for `['forwarded', {}]`, and merge on client -> queries are slow, I don't like this
 - give up on sorted query, query `keys=[ 'pending', 'forwarded']`, and sort by date on client -> we already limit query to 1000 messages, and messages are only 5ish JSON keys so not that big -> sg

So I'm sorting on the client.

api_e2e tests coming...

**Comment by estellecomment** [comment]
@garethbowen can you re-review? Added sorting.
Same PRs : 
api : medic/medic-api#145
webapp : #3406

e2e testing exposed that timestamps are sometimes ISO strings, sometimes number of millis, so the sorting was messing up... Yay testing!

**Comment by garethbowen** [comment]
Some comments on the API PR.

**Comment by estellecomment** [comment]
FIxed! 
@garethbowen some of your comments about `constants.js` and `utils.js` didn't apply, because this is api e2e tests, not webapp e2e tests :) But I refactored stuff into the `utils.js` so it's equivalent to what you were suggesting.
Merging, TFTR!

**Comment by sglangevin** [comment]
Working well in 2.12.0-beta.5. Moving to ready.
