### ISSUE TITLE
Patients reports accepted even if no person has the `patient_id`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3075]
Patient reports in a person-centered SMS workflow are accepted even if there is no person with that `patient_id`. You can see in this screenshot the second auto-reply which is from the `patient_reports` section:

![image](https://cloud.githubusercontent.com/assets/789512/22307118/d46a7462-e30f-11e6-9f57-501adb136f06.png)

_There are two auto-replies because one is coming from from the `registrations` sections, the other from `patient_reports`... which is related to https://github.com/medic/medic-webapp/issues/3074#issuecomment-275183846, but not the main problem being reported in this issue._

**Comment by mandric** [comment]
Is this on 0.4.x?  Because it would be a production bug if so.

**Comment by abbyad** [comment]
Person-centered workflows were introduced in v2.9... and although I don't any projects are currently affected they will be within weeks.

**Comment by abbyad** [comment]
Closing in favour of https://github.com/medic/medic-webapp/issues/3082 which has more info.

**Comment by abbyad** [comment]
Ok, so 3082 _is_ different... 

The basic aspect of the `person_reports` section is to validate that the patient_id exists. However, a report in patient-centered workflow is accepted if it passes the extra validation, even if the ID does not match the ID of an existing person.

**Comment by abbyad** [comment]
In checking whether a patient report has the ID of an existing person it [looks for any registration report with that same ID](https://github.com/medic/medic-webapp/blob/417c8a5be7cf6ba306f7df2535dd90349bd6875d/lib/views.js#L337). Unfortunately in person-centered workflows, the patient id is sent as a field in the report that is at the same time a patient report, and a registration since it is used to start schedules. As a result, a report with an unknown patient ID gets incorrectly considered as a preexisting person with that ID. 

A fix would be to ignore the `fields.patient_id` when looking for registrations. We should only consider the top level one which is auto-generated as the `patient_id` for the person.

**Comment by abbyad** [comment]
Note that removing `fields.patient_id` from `registered_patients` view alone would cause regressions, like no longer being able to clear schedules in person-centered workflows.

**Comment by SCdF** [comment]
Holding this one open because I'm about to change the patient contact document (the thing that exists if the patient exists) to be easily queryable by the patient's numerical id. Once I've done that this ticket will be easier I imagine.

**Comment by SCdF** [comment]
So I've taken a partial stab at this: https://github.com/medic/medic-sentinel/pull/102

Tests don't pass because I'm not 100% sure how errors work. I'm also not sure if I'm on the right track, in terms of relying on these patient person documents.

@mandric / @garethbowen interested in your feedback.

(not ready to merge obviously)

**Comment by garethbowen** [comment]
Comment added to review - let's talk...

**Comment by SCdF** [comment]
OK @garethbowen, take a look at:
 - https://github.com/medic/medic-webapp/pull/3124
 - https://github.com/medic/medic-sentinel/pull/104
 - https://github.com/medic/medic-api/pull/122

This should fix #3075, #3115 and part of #3082[1].

[1] I will (or you can on your Monday if you want) look into this second bit next.

**Comment by garethbowen** [comment]
@SCdF A bunch of mostly small changes requested. It's looking good! We can talk when you get in about this or the 2nd half of #3082

**Comment by abbyad** [comment]
While testing another issue I got an `invalid_report` error for a [patient report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/4e58614166f2e006f4f7cb418db5d842) that had a valid ID. I tried to reproduce to reproduce but all were accepted as valid patient reports.

**Comment by SCdF** [comment]
@abbyad did u want to reopen?

**Comment by abbyad** [comment]
Not yet, I was waiting to see if fix to https://github.com/medic/medic-webapp/issues/3082 before doing more testing.

**Comment by abbyad** [comment]
In testing 3082 saw another case of a valid ID being rejected. On standard.app instance, id `0713c7986f5017fa8e182e5a6c0eb24d`.

Still cannot reproduce reliably, so perhaps a race condition.

**Comment by garethbowen** [comment]
As far as I can tell from the code any time there is a rejection message there should also be an error on the report. In this doc there is a pending message but no error. I can investigate more later...

**Comment by garethbowen** [comment]
The two examples are completely different - one's the regex failing, and one's the existing patient shortcode check failing. Both are completely inexplicable.

**Comment by garethbowen** [comment]
Ok... The second example is a configuration error. Under the `P` form you have two response messages (messages which are sent when a valid report is accepted) - one of which is the "messages.generic.registration_not_found" key. This is exactly what we're seeing.

![bad-config-is-bad](https://cloud.githubusercontent.com/assets/2064938/23254076/a6718cb2-fa1b-11e6-8eca-e06f36eb3505.png)

This doesn't explain what happened with the first report.

@abbyad Reopen this (or preferably open a new issue) if it happens again.

**Comment by abbyad** [comment]
Thanks for looking at that Gareth. The second one was caused because the registration transition now can send a message with event type of `registration_not_found`, but the code was still sending all messages regardless of type, as noted in https://github.com/medic/medic-webapp/issues/3082#issuecomment-282051384.

**Comment by abbyad** [comment]
I tried _and failed_ to reproduce the error by sending in rapid succession 15 reports for three different patients. @ngaruko let's keep an eye out for this intermittent error, but in the meantime moving to Reay.
