### ISSUE TITLE
Convert guided setup to new style modal

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3078]

**Comment by garethbowen** [comment]
PR please @estellecomment https://github.com/medic/medic-webapp/pull/3085

This is the last old style modal!

**Comment by estellecomment** [comment]
comments in PR, back to you

**Comment by garethbowen** [comment]
Fixes committed. Back to you @estellecomment !

**Comment by estellecomment** [comment]
Consider removing that modal completely, if it's not being used... 

LGTM!
