### ISSUE TITLE
Load messages script fails to use https

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3081]
The `load_messages.js` script does not work with https.

Trying to use https gives
```
Protocol "https:" not supported. Expected "http:".
```

Providing a URL with http returns:
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.7.11</center>
</body>
</html>
```

**Comment by abbyad** [comment]
Reopening for what should be a simple code review

**Comment by garethbowen** [comment]
LGTM

**Comment by abbyad** [comment]
@ngaruko this is a useful script to learn about, so I'll let you do acceptance testing.

Can be run like as shown here, and we should test connecting over http and https for AT:
> node /path/to/medic-webapp/scripts/load_messages.js [p-test-messages.csv](https://github.com/medic/medic-projects/blob/fa489bbf6268e065a016ced2a59c098adc9c1779/default-sms-workflow/standard/test/p-test-messages.csv) https://user:password@instance.medicmobile.org/medic
