### ISSUE TITLE
SMS reports do not show name in summary

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3084]
From what I can tell:

## SMS forms
- The "New Person" form is the only SMS form that shows the person in the summary
- All other SMS forms do not show the person's name in the summary

## App forms
- All app workflow forms show the person's name in the summary

-----------
Reported by @shreyakb while testing Standard config 
https://github.com/medic/medic-projects/issues/1283
> On the CHW profile page, some of the new pregnancy, pregnancy visit, and delivery reports are missing the patient name, while some show patient name. Also happens on Patient's profile.
>
> CHW profile:
> ![new reports missing patient name in chw profile and patient profile](https://cloud.githubusercontent.com/assets/7915295/22238227/5ef5401a-e236-11e6-82a1-11128925e732.JPG)

> Patient profile:
> ![new reports missing patient name in chw profile and patient profile 2](https://cloud.githubusercontent.com/assets/7915295/22238359/ef333470-e236-11e6-8e2b-a3c9bc924357.JPG)
>

**Comment by SCdF** [comment]
Here is the offending code: https://github.com/medic/medic-webapp/blob/master/templates/partials/contacts_content_report.html#L13-L14

```html
<div>{{report.fields.place_name}}{{report.fields.patient_name}}</div>
<div class="name">{{report | summary:forms}}</div>
```

So I'm guessing the name is just not always there, and we should be getting it from another location.

**Comment by abbyad** [comment]
Ok, that makes sense since the `place_name`/`patient_name` is not sent with that form.

I suppose we need to decide whether we pull in the contact's info for "patient reports"?

**Comment by SCdF** [comment]
So I'm thinking there isn't necessarily any work to be done on this ticket. The "real" work would be sort of on #3075. Specifically, when we process SMS messages we should attach the patient content as you would if it were an Enketo report. This is useful in lots of ways, but in the case of this ticket it will mean that the name is always against the report in the right place.

**Comment by SCdF** [comment]
OK so what I'm going to do is:
 - Change the code that generates the patient contact from SMS to use the patient's ID as the document id, e.g. patient `12345` will have a contact document with `_id: "patient-12345`
 - Change the rendering code for the contact page so it pulls patient names from existing patient documents. Ideally this will be just from documents already loaded into memory, though if I'm wrong we can fall back on loading the actual documents

**Comment by SCdF** [comment]
Okey dokey. Before:
![image](https://cloud.githubusercontent.com/assets/583851/22741748/2d06d19a-ee0c-11e6-9b95-f413ffb74ab9.png)
After:
![image](https://cloud.githubusercontent.com/assets/583851/22741757/36ae93cc-ee0c-11e6-96a7-3c3c91eaf330.png)

@estellecomment would you do me the honour of reviewing this changes here: https://github.com/medic/medic-webapp/pull/3109

While I was there I also changed Sentinel to create patient documents with the patient id as the actual id, because it will make things easier in the future (we can probably get rid of the `patient_registration` view for example, though I need to look into it more). PR here: https://github.com/medic/medic-sentinel/pull/99

**Comment by estellecomment** [comment]
code LGTM.
Does this need a migration for previously created patients whose _id is just a normal uuid?

**Comment by SCdF** [comment]
@estellecomment nah talked to Gareth about that. Since we're still in testing an no one is live with this we don't need to migrate anyone.

**Comment by abbyad** [comment]
Works well. All reports have a patient info, as seen in screenshot of same reports as OP:
![image](https://cloud.githubusercontent.com/assets/789512/23084752/f569215c-f531-11e6-8b96-12609ae17ab5.png)
