### ISSUE TITLE
Edit function not working for reports sent by unknown number

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3087]
As reported by @bishwas-medic in https://github.com/medic/medic-projects/issues/1305

> In previous versions (V0.4.x), we could assign a known contact from the system to any reports that was sent in from numbers not assigned to any facilities or contacts. In v2.9.1, the dialog light box that appears after pressing the `Edit` button for these type of reports, doesn't have the search and dropdown field to select another contact from.
><img width="1193" alt="screen shot 2017-01-27 at 4 39 41 pm" src="https://cloud.githubusercontent.com/assets/13689284/22368573/5b55ba90-e4af-11e6-9128-6bc425b7ab21.png">
>
> To replicate:
> - Goto to the `Reports` tab
> - Click on any report sent from number `+13125551212`
> - Click on the `Edit` button on the report details screen
> - The lightbox appears but the facility/person dropdown is in minimized state and cannot be used

Confirmed from testing that it works when editing reports submitted by a known person, but editing a report from an unknown sender it gives the following errors in console, probably because it is trying to get the sender's info when there isn't a person assigned:
```
TypeError: Cannot read property '_id' of undefined
    at inbox.js:61
    at g (inbox.js:10)
    at inbox.js:10
    at o.$eval (inbox.js:10)
    at o.$digest (inbox.js:10)
    at inbox.js:10
    at f (inbox.js:8)
    at inbox.js:8
(anonymous) @ inbox.js:9
(anonymous) @ inbox.js:9
g @ inbox.js:10
(anonymous) @ inbox.js:10
$eval @ inbox.js:10
$digest @ inbox.js:10
(anonymous) @ inbox.js:10
f @ inbox.js:8
(anonymous) @ inbox.js:8
```

**Comment by SCdF** [comment]
@abbyad can you help me reproduce this locally? Or provide me with a link to an example where it fails online? @bishwas-medic talked about a lightbox opening when he hits edit. This is not something that happens when you edit a report AFAIK, so I'm wondering if I'm looking in the wrong place / doing the wrong thing?

**Comment by abbyad** [comment]
> This is not something that happens when you edit a report

If you try to edit a XForm it opens the form itself for editing, but if you try to edit a JSON form the only thing you can edit is the Sender - which is useful for when a CHW uses someone else's phone to submit a report.

In this case, you can recreate the issue if you try to edit a JSON report sent from an unknown number.

**Comment by SCdF** [comment]
@abbyad how would you like this to work? If someone edits a report with just a phone number would you expect to see a blank dropdown that only supports them editing and adding a real user? Or would you expect to see the dropdown containing the phone number, with saving working (ie it just resaves the existing document as is)? Or would you expect that people could put in any real user, or any phone number, that they liked?

**Comment by abbyad** [comment]
> expect to see the dropdown containing the phone number, with saving working (ie it just resaves the existing document as is)

Option B, seeing the original number and list of all other people as well. As you've said, saving it with the same number just re-saves as is.

**Comment by SCdF** [comment]
PR created: https://github.com/medic/medic-webapp/pull/3103

Things that happen now:
 - If you edit a JSON report that doesn't have a proper contact yet the select2 dropdown will just show the phone number
 - You can then type into the select2 dropdown to attach a real contact
 - If you leave the phone number there and hit save it will just minimise the popup (since no saving needs to take place)

@garethbowen let me have it

**Comment by garethbowen** [comment]
@SCdF Looks good. Perfect in fact!

The tests are failing but I think that's due to a change in angular because I hit the same thing with my PR and hopefully this will fix it: https://github.com/medic/medic-webapp/commit/2e4b3adc6a5a092fed6417560e752a7b9212f1bd

**Comment by abbyad** [comment]
Repeated the steps to replicate and it works well. Tried to break it, but couldn't. Moving to Ready.
