### ISSUE TITLE
Broken links in app settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3088]
Due to #1700, the links to help pages in Dashboard's app settings page are broken:
<img width="819" alt="screen shot 2017-01-27 at 7 31 10 am" src="https://cloud.githubusercontent.com/assets/13689284/22357803/bb433c90-e462-11e6-973b-7856dcd0bb1a.png">

Replacing the help pages seems to be part of #1895

**Comment by garethbowen** [comment]
Removed for now. Can be put back when the help documentation is restored.

**Comment by ngaruko** [comment]
@abbyad  @garethbowen Maybe we need another issue (more like a reminder) to restore those links (if they are important)

**Comment by garethbowen** [comment]
I added a comment to #1895 to add them back: https://github.com/medic/medic-webapp/issues/1895#issuecomment-275947448
