### ISSUE TITLE
Form exits on Refresh/Reload in Tasks tab

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3090]
Steps to reproduce

1. login as demo (alpha.dev: version 2.10.0-alpha.4744)
2. Tasks tab
3. Open one of the family surveys on LHS.
4. Refresh page
5. >>>The whole form disappear and we are back to the list of tasks...

Note sure if it has anything to do with #2156 

Logs:
![image](https://cloud.githubusercontent.com/assets/6979995/22410153/0211a25e-e6f9-11e6-9fdf-5015818ff2d7.png)

**Comment by SCdF** [comment]
@ngaruko just to be clear: can you add to the ticket what the expected path would be here?

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
I just reproduced this bug. If you open a task the task's URL is shown (eg `medic/_design/medic/_rewrite/#/tasks/0713c7986f5017fa8e182e5a6cb9ee46-postnatal-missing-visit-4`), and if you reload the page it goes back to `medic/_design/medic/_rewrite/#/tasks/` instead of staying on the original URL.

**Comment by abbyad** [comment]
This isn't a situation that would happen often, nor be terribly problematic when it does, so not high priority.

**Comment by garethbowen** [comment]
Code review please @mandric
