### ISSUE TITLE
HBB should ‘cancel’ Report Bug modal.

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3091]
Steps to reproduce:

1. Log into Medic Mobile
2. Go to ‘People’s’ tab or ‘Targets’
3. Settings >> Report bug
4. Report bug modal pops up
5. Press the HBB

**Expected** : Report bug modal should close and app be back to whatever screen/tab was open
**Current behaviour:** The Report bug modal does not close, until the app goes back to ‘Tasks’ tab

**Comment by garethbowen** [comment]
This goes for all modals.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by mandric** [comment]
Any updates here @ngaruko?

**Comment by garethbowen** [comment]
@ngaruko Can you try this again? I expect it to work...

**Comment by garethbowen** [comment]
Closing as cannot reproduce.
