### ISSUE TITLE
Document how translations work

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3094]
Because I've forgotten myself within 6 months.

**Comment by SCdF** [comment]
@estellecomment do you mean something that isn't covered by https://github.com/medic/medic-docs/blob/master/md/dev/translations.md ?

**Comment by estellecomment** [comment]
yes, translations.md explains how to use them, not how they work inside. (I might add/clean translations.md along the way, if it's relevant, I find it not 100% clear)
