### ISSUE TITLE
Configure the max number of SMS in multipart SMS

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3095]
Now that we can have multipart SMS with #3083, we should be able to set a configurable limit to the number of messages in multipart SMS. This may be needed to avoid issues with a local MNO.

**Comment by garethbowen** [comment]
Code review please @mandric : https://github.com/medic/medic-sentinel/pull/100

Once this is done I'll commit the simple kanso.json change to webapp.

Acceptance testing: make sure small messages aren't truncated, and large messages are. Messages that have any unicode characters have a max length of 70 characters, whereas messages with "common" English characters only have a max length of 160. If you configure the `multipart_sms_limit` setting to 2, then the limit is two messages of 70 or 160 characters each.

**Comment by abbyad** [comment]
@ngaruko, this can be acceptance tested by setting a Multipart SMS Limit value in [Dashboard](https://standard.app.medicmobile.org/dashboard/_design/dashboard/_rewrite/settings#/apps/9538d78451cbb66260555d23df0841ac/settings) (as seen below) and attempt sending messages that are below and above that threshold, keeping note that we'll need to test messages with only GSM alphabet characters separately from messages with non-GSM alphabet chars.

![image](https://cloud.githubusercontent.com/assets/789512/23084004/68cb37ce-f52e-11e6-9621-64351143dce8.png)

We should test sending messages from the UI as well as auto-replies/scheduled messages.

**Comment by ngaruko** [comment]
Just wanted to make sure I am doing it the right way. @abbyad or @garethbowen correct me if I am doing it wrong:

Go to [Dashboard](https://standard.app.medicmobile.org/dashboard/_design/dashboard/_rewrite/settings#/apps/9538d78451cbb66260555d23df0841ac/settings)

Set the  Multipart SMS Limit value above, say to 2 
Go to Medic-Reporter to send message 
Type more than 160 characters
![image](https://cloud.githubusercontent.com/assets/6979995/23149083/667ac980-f84e-11e6-8b46-3e2d61c40292.png)

Go to Medic UI >> Messages
![image](https://cloud.githubusercontent.com/assets/6979995/23149112/aa899b56-f84e-11e6-9d2e-52c9b32f4910.png)

What should we expect?

Also, if we send the message (that exceeds the limit) from the Medic UI, whet is expected, as in:
![image](https://cloud.githubusercontent.com/assets/6979995/23149221/62fd8e22-f84f-11e6-93ef-11b6ed651d3b.png)

**Comment by garethbowen** [comment]
@ngaruko Updating the send message UI is covered here: #670

This issue only affects outgoing messages, and medic-reporter is for sending incoming messages.

To AT this issue send an outgoing message (as in the last screenshot) and then check that the message is in fact truncated to 2 SMS. Test that the truncation length is reduced when sending unicode (~70 chars per message instead of ~160).

**Comment by abbyad** [comment]
Gareth beat me to it, but I'll add that medic-reporter is only for testing incoming messages, so we won't be truncating messages there.

If it is helpful, all places where outgoing messages are generated via config are highlighted in [this doc](https://docs.google.com/document/d/112CIX6T0iji2ztRfbjYNbzTzITbeC2_zEUtJaW-WQDA/edit#heading=h.naezy6uqe8n). For AT I would test a variety of those.
