### ISSUE TITLE
Add date of birth to person created by SMS

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3100]
When an incoming SMS report creates a new person we should set the person's `date_of_birth` field if the registration also added the `birth_date` field to the report. The `birth_date` field is generated if registration event is set, and the age in weeks or days is provided in the form.

**Comment by abbyad** [comment]
Simple change, but apologies for the lack of tests. Ready for code review, and quite possibly tests!

**Comment by garethbowen** [comment]
LGTM

**Comment by abbyad** [comment]
Works, moving to Ready
