### ISSUE TITLE
db lib can return `err=undefined, result=undefined`

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3102]
In sentinel/master the way we handle our db library calls could be improved.  I don't think crashing is really the problem, because the process by design is monitored and restarted and the backlog processing kicks in.  There is no better way atm to reprocess a change (try again) when a dependent resource fails.  But crashing specifically this way on an undefined error is not ideal.  We can throw a more descriptive error like Error("Database returned undefined") or something.

Example of poorly handled db call, these can be found throughout the sentinel code.  We expect `data` to have a `rows` property without checking if data is defined.  When calling our db lib (nano) we should expect both `err` and `data` can be undefined, and just throw a slightly better exception or wrap the calls similar to the [PR against 0.4.x](https://github.com/medic/medic-sentinel/pull/95).  I'm on the fence whether it's better to wrap all the db calls or handle each case where we call nano directly.

From beta.dev sentinel log:
```
2017-01-20T17:30:59.404Z - info: 2017-01-20T17:30:59.403Z - info: saved changes on doc 30e68a9de589d827e5a802d9e7f555b7 seq 897855
 
2017-01-20T17:30:59.999Z - error: 2017-01-20T17:30:59.998Z - error: Error updating metaData Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:293:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
 
2017-01-20T17:31:01.514Z - error: /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/update_clinics.js:87
                if (!data.rows.length) {
                         ^
TypeError: Cannot read property 'rows' of undefined
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/update_clinics.js:87:26
    at Request._callback (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/node_modules/nano/lib/nano.js:199:16)
    at self.callback (/srv/storage/
```

**Comment by mandric** [comment]
Thinking about this a little more brings up questions:

What is the proper error handling for unhandled exceptions inside a transition?

Should sentinel ever crash because of an unhandled exception in a transition?

When a transition returns an error, is it ever retried, how?  What are the effects of returning an error from a transition?

Currently the documentation states below, but I don't know how the re-run is handled exactly.

```
* callback(err)

  The document is saved and `ok` property value is false if `err` is truthy.
  Use this when a transition fails and should be re-run.
```

We should figure this stuff out too and document.

**Comment by estellecomment** [comment]
About the db lib returning neither error nor result: ultimately it would be nice to move from nano/felix to pouch. It's more stable and has a promise api, so there's no ambiguity there : a promise either finishes or throws. So we get rid of that case.
I'm more in favor of spending time moving to pouch than fixing all the existing db calls (which also wouldn't fix future db calls).

**Comment by mandric** [comment]
Moving to pouchdb sounds cool, but regardless of how we access the db, I think the answers above (error cases) still need to be defined/documented and potentially fixed (handled properly).

**Comment by estellecomment** [comment]
yes, definitely, the thoughts about how sentinel should handle errors, generally, are interesting. 
I was thinking about the smaller problem of this `err = null, result = null` situation.

**Comment by mandric** [comment]
But it doesn't matter whether you return nulls or not, you still have to throw an exception or not.  Either case we need to define what happens.  Pretty sure that is the crux of this issue.

**Comment by estellecomment** [comment]
Ok, I opened https://github.com/medic/medic-webapp/issues/3122 about how to handle exceptions in general, and refocused this issue on the  `err=undefined, result=undefined` case.

**Comment by mandric** [comment]
Poorly handling the undefined case is not the issue, it only put focus on the issue.  The issue is how to handle uncaught exceptions inside a transition.  Afaict these are duplicates.

**Comment by estellecomment** [comment]
I disagree. We should handle the `err=undefined, result=undefined` without freaking out and crashing. I think it's a separate discussion. 
But it can totally wait around until decision happens on #3122, in case it does solve it.

**Comment by mandric** [comment]
We should probably handle any uncaught exception within a transition without freaking out and crashing.  More importantly we need to understand and define how we are handling it.  Using `data.rows` without checking `data` first is just one example of a programming error.  I would actually leave it in while we work on the larger problem because it's just a test that we're handling it well.

**Comment by mandric** [comment]
I'm pretty sure this is still an issue in sentinel, just deprioritized.

**Comment by SCdF** [comment]
@mandric why did you backlog this?

**Comment by garethbowen** [comment]
Closing. This is ancient, and the solution is to switch from nano to pouchdb.
