### ISSUE TITLE
Sometimes patient_id's do not reference patients on some form submissions

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#3105]
This is a shadow ticket of issue medic/medic-projects#1254.

In a nutshell, there are documents where the patient_id references:

1.  a data_record from a different branch
2. a feedback document. There's an error message about `handleAndroidBack`.

There are around 50 documents that are affected. More details in the medic-projects issue.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
Somewhat perplexing, worth having a dev look at this.

**Comment by derickl** [comment]
Possibly also related to  medic/medic-projects#2135

**Comment by dianabarsan** [comment]
Hi @derickl! Is this still relevant? I see that the related issues: medic/medic-projects#1254 and medic/medic-projects#2135 have been closed. Thanks!

**Comment by derickl** [comment]
It can be closed for now @dianabarsan
