### ISSUE TITLE
Exporting feedback crashed api and it didn't come back

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3107]
Exporting feedback on lg.app crashed api with this error. The error occurred about 5 minutes after the initial feedback request and even after the initial request had 502ed.

```
#
# Fatal error in ../deps/v8/src/handles.h, line 48
# CHECK(location_ != NULL) failed
#
 
2017-02-08T03:28:14.491Z - error: 
==== C stack trace ===============================

 1:  
2017-02-08T03:28:14.492Z - error: V8_Fatal
 2:  
2017-02-08T03:28:14.492Z - error: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int)
 3: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding)
 4: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: ??
 7: ??
```

This could be a node bug, or something else.

Also concerning was that the process didn't exit, so gardener didn't restart it. It had to be manually killed.

**Comment by browndav** [comment]
This is a V8 bug that ultimately resulted in https://github.com/nodejs/node/issues/649. It was fixed late in the 0.12.x series. Medic OS is now on Node v6.95 (LTS) and the bug should be long gone post-upgrade.

**Comment by ngaruko** [comment]
Are you able to confirm that this was fixed @garethbowen ? Is there a need to AT this?

**Comment by garethbowen** [comment]
@ngaruko Yes this needs AT.

**Comment by sglangevin** [comment]
This needs to be AT-ed on a server with updated Medic OS.
