### ISSUE TITLE
Family Members section header shows on person's profile

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3108]
As discovered by @joshnesbit, a person's profile should not have the `Family Members` section

![image](https://cloud.githubusercontent.com/assets/789512/22724754/56b4803a-ed96-11e6-826d-ad858dfc15b6.png)

Tested on 2.10.0-alpha.4810

**Comment by sglangevin** [comment]
Possible regression.

**Comment by garethbowen** [comment]
CR please @SCdF https://github.com/medic/medic-webapp/pull/3117

**Comment by SCdF** [comment]
After careful deliberation, I APPROVE!

**Comment by abbyad** [comment]
Noticed that this is resolved in 4829, moving to Ready.
