### ISSUE TITLE
Test upgrades from 0.4 to 2.9.x

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3110]
Now that we have released v2.9, we'd like to get started moving all of our projects that are on v0.4 to v2.9.x. Before we do that in production, we need to test the upgrades and make sure that there are no technical issues during the upgrade and then test the configurations once the upgrades are complete. 

This issue is to handle the first step: cloning and upgrading instances. We will need to engage with project teams to test the configurations once the cloned instances are ready.

Based on our prioritized list of instances for upgrades, we should start with the following 3 projects:

Partner Name | Location | Instance Name
---------------  |  ---------  |  ----------------
StrongMinds | Uganda | Production: Strong Minds
Kilifi Kids | Kenya | Testing: Kilifi Kids Makueni
Kilifi Kids | Kenya | Production: Kilifikids Kaiti

To complete this issue:
1) Clone each of these instances
2) Upgrade Medic OS
3) Upgrade from v0.4 to v2.9.x
4) Hand over to project teams for testing

**Comment by browndav** [comment]
On it. Here's the temporarily location of the system-level upgrade checklist: https://gist.github.com/browndav/a42e1267ede1c7375ae66e3d79742e61. Local tests have all passed.

**Comment by browndav** [comment]
OS upgrades have been done for clones of these three instances. I'll file per-instance issues in `medic-projects` today for the remaining app upgrades/testing and link them here.

**Comment by browndav** [comment]
Update: All high-priority February instances have been cloned and are ready for a very-unthinking mechanical execution of the upgrade process (save for some carefully-collected timings for the `view_index` rebuild and migrations).

**Comment by garethbowen** [comment]
@browndav This has been hanging around for ages and from what I hear we've finished testing and are on to actual upgrading. Can this be closed?

**Comment by browndav** [comment]
Upgrades are fully tested. Closing.
