### ISSUE TITLE
medic-reporter breaking on 404 `config.js`

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3112]
Gets stuck on this error : 
![screen shot 2017-02-09 at 16 39 08](https://cloud.githubusercontent.com/assets/911434/22790429/76d03ea8-eee6-11e6-991f-33eef1c71b79.png)

I see it happening on a bunch of prod servers, but not lg.dev for instance...
Not locally either, with the same medic-reporter version replicated to my local server.

**Comment by estellecomment** [comment]
Looks like the 404 is because of calling
GET /medic-reporter/_design/medic-reporter/js/config.js 404
instead of
GET /medic-reporter/_design/medic-reporter/_show/config 304

There's a rewrite that should point from /js/config to /_show/config. Maybe not working??

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by estellecomment** [comment]
Working on 5 randomish prod servers. Didn't try the others. Closing.
