### ISSUE TITLE
Patient contact creation should happen if a patient contact doesn't already exist

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3115]
So I'm not sure the current code works correctly in regards to generating a `person` document for each new SMS patient.

Currently [the code](https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L309):
 - We check to see if there are any registrations for a particular patient. A registration [is defined as](https://github.com/medic/medic-webapp/blob/master/lib/views.js#L335-L347) finding a document that:
   - Has a patient id
   - Has a form
   - Has passed through the `registrations` transition successfully (this is the transition that our create patient logic is inside also)
   - In turn, to pass successfully through the `registrations` transition a document must be configured as a registration document (in `app_settings`)
 - If there are any "registration"--which as configured in standard are any documents of type "C", "P", "D", "pregnancy" or "N"-- then **don't create a patient contact document**
 - If there are no registrations then create one.

This seems wrong to me. We either:
1. shouldn't care about looking up registrations at all, and just concentrate on creating a `person` document if one doesn't already exist for that patient
2. Should look up registrations to confirm the patient is real, but then still check for the `person` document before creating one

I've written code for `1.` already, against this PR: https://github.com/medic/medic-sentinel/pull/101

My reasoning is that if you've got this far into the registrations transition you already presume the patient id is valid.

Can you two, @garethbowen and @mandric, look over these assumptions and the associated PR please? I'm not sure I am exactly right here, looking for your feedback :-)

**Comment by garethbowen** [comment]
Comments added to the PR
