### ISSUE TITLE
OS image updates: ensure `medic` user gets created for `medic-couch2pg`

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3120]
During OS image upgrade testing, I discovered that the `gardener` PostgreSQL role – which `medic-couch2pg` needs to properly start its services – isn't created properly under some circumstances. It's present in `pg_hba.conf`, but not in the users database itself. This should be a quick fix.

**Comment by ngaruko** [comment]
Are you able to confirm that this works as expected @henokgetachew ? Thanks.

**Comment by sglangevin** [comment]
@henokgetachew currently assigned to you for AT.

**Comment by henokgetachew** [comment]
I don't think this is relevant anymore with all the docker stuff that we're doing.  Reopen if it's still relevant @browndav
