### ISSUE TITLE
Use reference to translation keys in app_settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3127]
As a configurer I want to refer to translation keys from app_settings rather than writing out all the values in app so that I can manage translations more easily. This will also drastically reduce the size of app_settings, and reduce errors when editing duplicate messages.

Here is what this would mean for a segment of app_settings:

# Before
```
      "messages": [
        {
          "message": [
            {
              "content": "Thank you {{contact.name}} for registering {{patient_name}}. Their ID is {{patient_id}}.",
              "locale": "en"
            },
            {
              "content": "Asante {{contact.name}} kwa kusajili {{patient_name}}.ID namba yake ya Kujua ni {{patient_id}}.",
              "locale": "sw"
            },
            {
              "content": "Merci {{contact.name}} pour avoir inscrit {{patient_name}}. Leur code d'identification est le {{patient_id}}.",
              "locale": "fr"
            },
            {
              "content": "धन्यवाद {{contact.name}}, {{patient_name}} को दर्ज करने के लिए |  गर्भावस्था पहचान नंबर है {{patient_id}} |",
              "locale": "hi"
            },
            {
              "content": "नमस्ते! {{contact.name}} {{patient_name}}  लाई दर्ता गरेकोमा धन्यबाद! उहाँको दर्तानं {{patient_id}}.",
              "locale": "ne"
            },
            {
              "content": "Gracias {{contact.name}} por inscribirse {{patient_name}}. El numero de ID de embarazo es {{patient_id}}.",
              "locale": "es"
            }
          ],
          "recipient": "reporting_unit"
        }
      ]
```

# After
```
      "messages": [
        {
          "message": "{{report.c.autoreply}}",
          "recipient": "reporting_unit"
        }
      ]
```

In the Standard configuration there are currently 219 messages sections like the one above, many of which repeat the exact same text. For example, there are 39 immunization forms which have identical messages to the other 38 immunization forms. Making this change to those forms alone reduces the JSON configuration of those forms from 217KB to 28KB.

**Comment by garethbowen** [comment]
Formatting it as proposed is nice, but won't work with the app_settings schema because the message could be an array or a string. This means either the new config or the old won't work with the dashboard app settings screen. This isn't used much any more but it's nice not to break it if we can avoid it.

Instead I propose the key for the translation key is different from `message` so tech leads can specify one or other. This will make migration easier and keep the UI working as much as possible.

```
      "messages": [
        {
          "translation_key": "report.c.autoreply",
          "recipient": "reporting_unit"
        }
      ]
```

OR

```
      "messages": [
        {
          "message": [
            {
              "content": "Thank you {{contact.name}} for registering {{patient_name}}. Their ID is {{patient_id}}.",
              "locale": "en"
            }
          ],
          "recipient": "reporting_unit"
        }
      ]
```

**Comment by garethbowen** [comment]
This will really help the standard configuration so I'm going to schedule it for now, but it's not top priority.

**Comment by garethbowen** [comment]
Code reviews please @mandric : https://github.com/medic/medic-sentinel/pull/106 and https://github.com/medic/medic-webapp/pull/3137

**Comment by mandric** [comment]
👍

**Comment by abbyad** [comment]
Did a quick test and this works in 4869. @ngaruko if you need help with acceptance testing of this one please let me or Gareth know.

**Comment by abbyad** [comment]
Our test instance on standard.app is fully converted to using `translation_key` and it seems to be working well. All keys are translated properly, including expansions of mustache fields.

**Comment by garethbowen** [comment]
To test this, configure a message to use a translation_key, eg:

```
    {
      "messages": [
        {
          "translation_key": "report.c.autoreply",
          "recipient": "reporting_unit"
        }
      ]
    }
```

Then go to `Configuration > Languages > Application Text > Add translation` and add `report.c.autoreply` as whatever you like.

Now when you trigger that message to fire the correct translation should be resolved.

Test that you can use markup in the translation value, eg: `{{patient_name}}`.
