### ISSUE TITLE
Ability to delete a translation key

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3128]
As a configurer I want to be able to delete unused translation keys so that they don't bloat the instance.

Once a translation key has been added it is not possible to remove it. This makes it not only difficult to correct mistakes, but also difficult to remove labels that may have been included with the default configuration that are not being used.

We could have an UI for removing individual keys, but there are occasions that we'd want to delete multiple keys at once, which could perhaps be done by re-importing the translations with the unused keys removed.

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by mandric** [comment]
Wonder if you can set it to `null` or something that will evaluate to false as a temporary workaround?  @abbyad can you give an update here?

**Comment by abbyad** [comment]
Setting them to null would help reduce bloat, but we should still support removing keys.

**Comment by abbyad** [comment]
Removed the Triaged label since this issue is not in a Project.

**Comment by garethbowen** [comment]
@abbyad All issues need some Status label or they will come up for triage again. IMO it doesn't need to be in a project to be triaged.

**Comment by garethbowen** [comment]
@wtekeu I've merged those PRs. This means custom translations can be deleted via medic-conf, right? Do you think we also need a button in the admin app to delete a translation?

**Comment by wtekeu** [comment]
Yes that's correct, custom translations can be deleted using medic-conf. I agree that this functionality should be made available in the admin app. How do we currently pull admin changes made to translations using medic-conf? I want to keep the local translation files in sync with couchdb so that next time I push custom translations using medic-conf I don't overwrite my admin changes. Is that something that we need to plan for?

**Comment by garethbowen** [comment]
For AT:

- add a translation key, click on edit the translation, click the delete button, make sure it's gone.
- make sure the translation keys we ship cannot be deleted.

**Comment by ngaruko** [comment]
Would you like to have a second look at this on your local @wtekeu . This is what happened when I tested this. I added a new translation and when I deleted it, there were errors both in the UI and in the console. I clicked delete again and translations were deleted but the key stayed. Then I tried to edit that translation and lo and behold the app crash - and it is down as I type this. Whether it is related or a rather unfortunate coincidence, I cannot tell! Might be also related to #5062 ... Didn't take any screenshots or error logs as a was expecting to repeat this a couple of times to confirm.
Some errors in logs:
```
TypeError: Cannot read property 'replace' of null
Dec 13 13:59:39 gamma-dev gamma-dev-medic-api-logs:  (gamma-xxxxxx) | [2018-12-13 06:59:38] 2018-12-13 06:59:38 INFO: Merging translations… 
Dec 13 13:59:39 gamma-dev gamma-dev-medic-api-logs:  (gamma-dev-xxxxx) |     at result.rows.forEach.row (/srv/software/medic-api/md5-G0JZAWK5AjbNNcsCThkzQ==/src/config.js:86:57)
```

**Comment by ngaruko** [comment]
LGTM.
Added key can be deleted. 
Translation keys we ship cannot be deleted. Just a nitpick, maybe we should grey out or hide the `delete` button on these un-deletable keys, but let us close that and suggest the idea in a different issue if needed, unless you think it is that important or an easy-win @abbyad? 
![image](https://user-images.githubusercontent.com/6979995/49983819-7c93b680-ff97-11e8-82d1-dd532bdfe2d7.png)

**Comment by garethbowen** [comment]
@ngaruko Yes we should definitely disable the delete button if you can't delete it. What happens currently? Just nothing?

@wtekeu Can you have a look at this improvement at some point?

**Comment by ngaruko** [comment]
Thanks @garethbowen . At the moment, for shipped translations, the `edit translation` modal disappear `onDelete`, sort of same behaviour as the `Cancel` button.

**Comment by ngaruko** [comment]
LGTM...
Closing...
