### ISSUE TITLE
'Edit Report' doesn't  seem to make sense

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3129]
Steps to reproduce:

1. Log in https://v2-test-ipd-nepal.app.medicmobile.org
2. Click 'Reports' tab
3. Select one of the 'reports' on the LHS
4. Click Edit button on the RHS FAB

Expected :some 'editable' table/control
Current behaviour: a 'select2' control with nothing to edit...with a 'Submit' and a 'cancel' buttons

![image](https://cloud.githubusercontent.com/assets/6979995/23106175/5ed41886-f74e-11e6-8605-8c27f716fcdc.png)

**Comment by garethbowen** [comment]
The Edit button spawns two different workflows. For Enketo reports you can edit the form content itself, but for JSON forms you can only change the contact. We should change the text on the button to be something better ("reassign"?), modify the modal title, and add a label to the dropdown field.

**Comment by garethbowen** [comment]
Review please @estellecomment https://github.com/medic/medic-webapp/pull/3170

**Comment by estellecomment** [comment]
@diannakane What's the appropriate word to use here, what are you using in Standard? Person? Sender? Contact? Something else? Here's a screenshot of what we're talking about, editing the sender of an SMS report :
![screen shot 2017-02-28 at 14 26 31](https://cloud.githubusercontent.com/assets/911434/23407326/b81054b6-fdc3-11e6-8b6c-f9103a8a6c86.png)
Click the button and you get:
![screen shot 2017-02-28 at 14 27 53](https://cloud.githubusercontent.com/assets/911434/23407339/c077ae06-fdc3-11e6-8785-e222638ca4f8.png)

**Comment by diannakane** [comment]
"Edit sender" feels more accurate and intuitive to me, since we aren't using "contacts" to refer to people anymore and furthermore "contact" could be interpreted in different ways. 

button: "edit sender" or just "edit"
title of box: "edit sender"
description: "Please select a person to reassign as the sender of this report" (let me know if this is too long)

**Comment by garethbowen** [comment]
Fixed the default translations here: https://github.com/medic/medic-webapp/commit/d7b757286c295f6529ed31a15692b929aae6fcf7
