### ISSUE TITLE
Couchdb's startup.log does not include timestamps

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3131]
In `medic-os`, there are no timestamps included in the log file at `/srv/storage/medic-core/couchdb/logs/startup.log`.  This makes it hard to tell when messages in the log date from (!), although the file's last-updated time helps a little.

**Comment by garethbowen** [comment]
This would require a change to couchdb: https://issues.apache.org/jira/browse/COUCHDB-1401

@alxndrsn Can we close this and revisit if/when couchdb make it possible to do?

**Comment by SCdF** [comment]
@garethbowen / @alxndrsn alternatively we change the way we start couch so that we pipe it's output through something that adds timestamps, but that seems like a lot of effort.

**Comment by alxndrsn** [comment]
@SCdF if this is a common utility, it doesn't sound like it would be a lot of effort...

@browndav any thoughts?

**Comment by browndav** [comment]
Yeah, a reusable timestamping utility (e.g. even something as simple as a wrapper around `awk '{ print strftime("%Y-%m-%d %H:%M:%S"), $0; fflush(); }'`) would be incredibly useful to have in the base image. I'll toss this in the new iteration, and will take care of it this week along with one Medic OS release blocker (and two other nice-to-haves).

**Comment by browndav** [comment]
I can definitely hit all of the `startup.log` files in one shot, using the pipe method. Currently, CouchDB duplicates its log output – it goes to standard output (which we're redirecting to `startup.log` and can easily pipe), plus couch.log (which is managed by CouchDB and can't easily be piped IIRC).

**Comment by browndav** [comment]
@mandric: I think this one is ready for code review. Do we want to grab a time when you me and @henokgetachew are free, and I can walk you through what was done here (and how it fits in to the larger pieces)?

**Comment by browndav** [comment]
Bad news: returning this to myself after self-code-review and discovery of a particularly nasty bug. Good news: fixing it will close three issues. See above for details.

**Comment by browndav** [comment]
This should be resolved in https://github.com/medic/medic-os/commit/ea8b6703eb0d09f0741e26d25c09b9084689c675.

**Comment by browndav** [comment]
If nobody objects, code review can happen in #3274.
