### ISSUE TITLE
New Household button missing

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3132]
Seen today on `demo.dev` (username: `derick`):

![pasted image at 2017_02_20 04_02 pm](https://cloud.githubusercontent.com/assets/191496/23122421/276b34d8-f78a-11e6-9927-7043040cb2ac.png)

**Comment by sglangevin** [comment]
Cannot reproduce this one. I logged in on demo.dev as a few different users at the same level as `derick` and all had the button, as expected.

**Comment by alxndrsn** [comment]
Steps to reproduce:

1. log in as `derick`
2. go to _People_ tab
3. click _New Action_ (in right-hand pane)
4. select any action from list
5. observe _New Household_ button has disappeared

Reproduced on: Firefox, Chrome

**Comment by garethbowen** [comment]
Code review please @alxndrsn : https://github.com/medic/medic-webapp/pull/3167

One commit fixes the bug, and one reformats the controller, so I suggest reviewing the commits individually.

**Comment by alxndrsn** [comment]
Change looks good.  Refactor probably is fine too, although github's diff is making it tricky to review!  Let me know if you have any secret request params which would make that simpler.

**Comment by garethbowen** [comment]
@alxndrsn The magic parameter you're looking for is `?w=1`

**Comment by garethbowen** [comment]
Adding keywords: lhs, fab, clear, empty
