### ISSUE TITLE
pregnancy follow-up task for yesterday created for new pregnancy

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3133]
instance: `demo.dev`
user: `richard`
bug: task for pregnancy follow-up created with due-date _yesterday_ immediately on registering a new pregnancy

steps to create:
1. register a new, pregnant head of household (Sharmila Bhattarai, 19 years, LMP 2 months ago)
2. go to _Tasks_ page and do the _register pregnancy_ task
3. go back to _Tasks_ page - there is/may now be a task for _pregnancy follow-up_, due yesterday

**Comment by sglangevin** [comment]
@alxndrsn this is due to task rules and the fact that we haven't been able to have an ad hoc pregnancy visit action. These are LG task rules - not ideal but that's how they work currently.

**Comment by garethbowen** [comment]
@sglangevin Can this be closed?

**Comment by alxndrsn** [comment]
@garethbowen it still needs fixing...

**Comment by garethbowen** [comment]
Moved to medic/medic-projects#1565
