### ISSUE TITLE
Newly-registered children have the wrong age

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3134]
instance: `demo.dev`
user: `richard`
bug: if you register two children for a new Household and enter the age in years/months, the age of the second child seems to be random

**Comment by sglangevin** [comment]
@alxndrsn this has been resolved in later versions of the add person and add family forms. It was a form calculation error.

**Comment by alxndrsn** [comment]
Does the demo instance get updated with fixes periodically?

**Comment by abbyad** [comment]
Will respond in DM.

**Comment by garethbowen** [comment]
@sglangevin Can this be closed?

**Comment by alxndrsn** [comment]
@garethbowen it still needs fixing...

**Comment by garethbowen** [comment]
Moved to https://github.com/medic/medic-projects/issues/1566
