### ISSUE TITLE
newly-registered head of family is sometimes saved as a year younger than specified

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3135]
instance: `demo.dev`
user: `richard`
bug: newly-registered head of family is sometimes saved as a year younger than specified

On creating a new head of family as 25 years old, and then viewing her card in the contacts tab, her age is shown as 24.

**Comment by sglangevin** [comment]
@alxndrsn this was also a form calculation error that has been resolved in later versions of the same form.

**Comment by alxndrsn** [comment]
Does the demo instance get updated with fixes periodically?

**Comment by sglangevin** [comment]
I'm not sure who is responsible for updating demo.dev. Maybe @abbyad? We could put some updated contact forms there if the ones we have aren't working properly.

**Comment by garethbowen** [comment]
@sglangevin Can this be closed?

**Comment by alxndrsn** [comment]
@garethbowen ist still needs fixing...

**Comment by garethbowen** [comment]
Moved to https://github.com/medic/medic-projects/issues/1564
