### ISSUE TITLE
Cannot edit contact age on demo.dev

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3136]
The person edit form has no option for changing a person's age.

**Comment by sglangevin** [comment]
@alxndrsn this is a form configuration issue, not a bug.

**Comment by garethbowen** [comment]
@sglangevin Can this be closed?

**Comment by alxndrsn** [comment]
@garethbowen it still needs fixing...

**Comment by garethbowen** [comment]
Moved to https://github.com/medic/medic-projects/issues/1567
