### ISSUE TITLE
Futon login is broken

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3140]
https://github.com/medic/medic-projects/issues/1412

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by sglangevin** [comment]
Closing - comment made on corresponding medic-projects ticket.
