### ISSUE TITLE
Updating all dependencies breaks enketo

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3143]
```
npm update
npm shrinkwrap
grunt dev
```

First the `node_modules/bootstrap-daterangepicker` patch breaks in a minor way, which is no big deal.

Unfortunately after that enketo breaks because it expects a scss file to exist in `bootstrap-datepicker/dist/css` and it doesn't.

**Comment by SCdF** [comment]
Added this in as it's probably not too hard to fix, and it's important that we keep this stuff up to date and working.

**Comment by sglangevin** [comment]
Related? https://github.com/medic/medic-webapp/issues/2989

**Comment by garethbowen** [comment]
Yeah, dupe.

**Comment by SCdF** [comment]
@garethbowen / @sglangevin I wouldn't consider this a dupe. If you update npm the app doesn't even *build*, let alone run.

**Comment by garethbowen** [comment]
Right, but after fixing that, you hit #2989
