### ISSUE TITLE
The tour tends to lose meaning when a feature is not enabled for the user. Example: Tasks for admins?

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3144]
Steps:

Log in as admin
Menu >>> Guided Tour
Select tasks and follow the wizard

![image](https://cloud.githubusercontent.com/assets/6979995/23192268/6767d7d4-f907-11e6-8337-3ac1025a615d.png)

Maybe we need to disable the tour altogether for admin or at least hide tours for features that are not enabled for admins. Like Tasks

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by garethbowen** [comment]
It's fairly easy to disable the Task tour for admins and it makes sense to me. Let's do it.
