### ISSUE TITLE
Text overflows the button on tour (Family members)

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3145]
Steps
Logged in
Open mennu
Guided tour
>>The 'Mamily Members' text overflows the coloured button

![image](https://cloud.githubusercontent.com/assets/6979995/23196048/10a139bc-f91c-11e6-992a-682193c557cc.png)

**Comment by garethbowen** [comment]
Nice easy code review for you @estellecomment : https://github.com/medic/medic-webapp/pull/3168
