### ISSUE TITLE
Person phone number disappeared?

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3149]
On alpha.dev (and locally for me)
Only the name is left, the phone number disappeared.
![image](https://cloud.githubusercontent.com/assets/911434/23252516/611397ec-f9b1-11e6-9393-ecf5559b14f4.png)

Locally I get `contact summary eval result undefined`.
Is it a config issue with the new profiles?

**Comment by garethbowen** [comment]
It's configurable now, so this is a config problem. Try the default config (in kanso.json).

Caused by #2914
