### ISSUE TITLE
"gateway" user does not have required permissions for medic-gateway by default

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3150]
Seen on: alpha.dev

**Comment by sglangevin** [comment]
Related issue: https://github.com/medic/medic-webapp/issues/2951

This also seems to be a duplicate of https://github.com/medic/medic-webapp/issues/2549, but it could be that 2549 only applied to upgraded instances and not on instances that start afresh on v2.9+

**Comment by garethbowen** [comment]
Yeah I think this is a dupe. Defaults are only applied on fresh installs so unless we've wiped alpha.dev lately it's probably just running with the old defaults.
