### ISSUE TITLE
API is picky about trailing slashes for SMS endpoint

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3152]
Currently medic-api responds as expected for `/api/sms` url, but not for `/api/sms/`.  This seems unhelpful.

Seen on: alpha.dev

**Comment by SCdF** [comment]
Here is the PR: https://github.com/medic/medic-api/pull/125

**Comment by SCdF** [comment]
@alxndrsn some minor changes requested, back to you! :-)

**Comment by alxndrsn** [comment]
Now that gateway has a specific UI, it's hard to misconfigure this.  Because of this, I think the fix for this should be changed to forward `/api/sms/` to `/api/sms`.

**Comment by garethbowen** [comment]
Back to you @alxndrsn
