### ISSUE TITLE
Labels not translated for generated report fields

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3154]
The labels for generated report fields like `patient_id`, `birth_date`, `expected_date` are not translated. 

![image](https://cloud.githubusercontent.com/assets/789512/23272981/590d6496-f9cb-11e6-8412-a148f1641d00.png)

Adding them to the translations did not help either (eg `report.n.patient_id = ID` ).

**Comment by garethbowen** [comment]
Whoops
