### ISSUE TITLE
Add validation option for ISO week date

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3155]
Per the outcome of #3051, filing a feature request to add validation for ISO week dates to avoid submissions of reports for invalid weeks.

From original issue filed by @bishwas-medic: https://github.com/medic/medic-projects/issues/1423

"ISO week format (https://en.wikipedia.org/wiki/ISO_week_date) and it's variations (WHO uses a similar format called EPID week) are used widely in disease surveillance reporting. Our IPD project(ipd-nepal.app.medicmobile.org) also follows this date format. The reports have a Week number field to identify which ISO week the report is sent for. The max number of weeks in ISO format is either 52 or 53 and currently we are manually updating the validation for the week field to check for wrong weeks using the max() validation.

Having a separate validation like maxISOweek() for checking the week would be a much simpler and better solution to this and can be useful for other areas like analytics dashboards."

**Comment by nice-snek** [comment]
hi frand @estellecomment, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by ngaruko** [comment]
Any idea how to AT this @dianabarsan ?

**Comment by dianabarsan** [comment]
To  AT, you'll need a form that has a field that uses this validation:

Example form: 

```
"ISO": {
  "meta": {
    "label": {
      "en": "ISO Weekly Report"
    },
    "code": "ISO"
  },
  "fields": {
    "week": {
      "position": 2,
        "type": "integer",
        "labels": {
        "tiny": {
          "en": "wkn"
        },
        "short": {
          "en": "ISO week"
        },
        "description": {
          "en": "ISO week"
        }
      },
      "length": [
        1,
        2
      ],
        "required": true
    },
    "year": {
      "position": 3,
        "type": "integer",
        "labels": {
        "tiny": {
          "en": "yr"
        },
        "short": {
          "en": "Current year"
        },
        "description": {
          "en": "Current year"
        }
      },
      "required": true
    }
  },
  "use_sentinel": true,
  "public_form": true
}
```

Example registration:

```
{
  "form": "ISO",
  "fields": [
    {
      "field_name": "",
      "title": ""
    }
  ],
  "help": "",
  "events": [],
  "validations": {
    "join_responses": true,
    "list": [
      {
        "property": "week",
        "rule": "isISOWeek('week', 'year')",
        "message": [
          {
            "content": "The ISO Week format is wrong. Please correct and resend the report. Thank you.",
            "locale": "en"
          }
        ]
      }
    ]
  },
  "messages": [
    {
      "message": [
        {
          "content": "Thank you for submitting ISO report for the year {{year}} and week {{week}}.",
          "locale": "en"
        }
      ],
      "recipient": "reporting_unit"
    }
  ]
}
```

**Comment by newtewt** [comment]
Seeing valid and in valid ISO weeks getting checked as part of this.

**Comment by garethbowen** [comment]
Configuration documentation: https://github.com/medic/medic-docs/blob/master/configuration/app-settings-validations.md#medic-mobile-validation-functions
