### ISSUE TITLE
Add scripts to upload project files

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3156]
For technical admins setting up or configuring an instance is easiest and quickest via command line. Most but not all of the setup and configuration for a project can be done via the command line. We should add scripts to fill the gaps:

- [x] All settings and JSON forms - [script](https://github.com/medic/medic-projects/blob/master/scripts/upload_app_settings.sh)
- [x] Task, Target, and Contact summary - [script](https://github.com/medic/medic-projects/blob/master/scripts/update_tasks.sh)
- [x] XForms to add/edit People - [script for SMS projects](https://github.com/medic/medic-projects/blob/master/default-sms-workflow/process_person_forms.sh)
- [x] XForms to add/edit Places - [script for SMS projects](https://github.com/medic/medic-projects/blob/master/default-sms-workflow/process_place_forms.sh)
- [x] XForms for actions - [script](https://github.com/medic/medic-projects/blob/master/scripts/convert.sh)
- [x] Translations - [script](https://github.com/medic/medic-projects/blob/master/scripts/upload_translations.js)
- [x] Icons - [script](https://github.com/medic/medic-projects/blob/master/scripts/upload_icons.js)

**Comment by abbyad** [comment]
The two holdouts for scripts (Translations, Icons) are now ready, and will be included in the documentation for loading the entire configuration from the command line.

**Comment by ngaruko** [comment]
Do we need to AT this @abbyad ?
