### ISSUE TITLE
Bulk delete selection incorrectly resets

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3158]
The selection of reports in bulk delete gets accidentally reset (eg none selected) if you click on any of the place names in the LHS ( `Chris' Area • Toronto • Marc's District` in the screenshot below)

![image](https://cloud.githubusercontent.com/assets/789512/23287609/78649990-fa0c-11e6-8417-0d24a3f6061f.png)

Clicking anywhere else on the item works as expected except

**Comment by garethbowen** [comment]
This was fixed as part of this commit: https://github.com/medic/medic-webapp/commit/149020ed49e74456e97fe1e6ebba3c4c365aec5e
