### ISSUE TITLE
New reports for same time period do not replace previous ones

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3160]
As reported in https://github.com/medic/medic-projects/issues/1426, the transition that replaces existing scheduled reports when a new one comes in for the same time period is not working in v2.

**Comment by sglangevin** [comment]
This was previously working in v0.4 and is needed for projects that are upgrading.

**Comment by garethbowen** [comment]
Waiting for this to be confirmed.

**Comment by garethbowen** [comment]
Code review please @SCdF https://github.com/medic/medic-webapp/pull/3222

When we switched to using doc.fields this view must've been missed. These views are the heart of the [update_scheduled_reports transition](https://github.com/medic/medic-sentinel/blob/master/transitions/update_scheduled_reports.js#L74-L94), and this bug meant it was never finding any matching scheduled reports.

**Comment by SCdF** [comment]
@garethbowen I'm going to be that guy: can we have an integration test please? View code is super important and should be tested. I know we haven't done it in the past but we have to start somewhere…

**Comment by garethbowen** [comment]
I managed to convince @SCdF to split the e2e test off into another issue: https://github.com/medic/medic-webapp/issues/3229
