### ISSUE TITLE
medic-reporter sends `[object Object]` if there's a space in form field name

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3165]
It's possible to have spaces in JSON form field names (probably not what you want... but possible.). In that case medic-reporter sends `[object Object]` instead of the field.

Here with the field `patient_ name`. Same thing for trailing spaces : `patient_name `
![image](https://cloud.githubusercontent.com/assets/911434/23354636/7b6da1a4-fcd2-11e6-9fa0-f0d9c961a5e2.png)

**Comment by SCdF** [comment]
@estellecomment is this intended to be a bug report, or something else?

If it's a bug report, what would you say the correct functionality is here? I.e., how would you consider this ticket "done"?

_(the two obvious choices being not allowing spaces in fields, or correctly serialising output with spaces in it)_

**Comment by nice-snek** [comment]
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍 🐍

**Comment by estellecomment** [comment]
I don't care enough to fix this. I don't think anyone does. Closing.
