### ISSUE TITLE
Recording Dates in V2 of Webapp

### ISSUE THREAD

**Issue by jaymedic** [medic/medic-webapp#3169]
Using the demo account for the Webapp V2, when entering age in the fields for a new patient/family member, when you enter months or years the fields are not recorded accurately . In some cases the number of months is off by one or the months are deleted and you just see `years` captured.

This is happening across multiple versions of Android and multiple devices: Samsung, Huawei, Motorola.

**Comment by sglangevin** [comment]
@jaymedic this is a configuration issue related to the particular forms that you are using. We now have the ability to configure how ages display in contact profiles. There is an issue for this in medic-projects, so you can follow along here: https://github.com/medic/medic-projects/issues/1566 and here: https://github.com/medic/medic-projects/issues/1564
