### ISSUE TITLE
Exporting server logs doesn't work

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3172]
![server_log_export](https://cloud.githubusercontent.com/assets/3198821/23406541/7dfc8af8-fdd0-11e6-9d4c-d7a58edc7b96.png)
It gives the same result via curl as well.

**Comment by browndav** [comment]
This looks like a duplicate of #3089.

**Comment by henokgetachew** [comment]
Oops.  Closing as duplicate.
