### ISSUE TITLE
AWS EC2 AMI Regression: Does not currently boot

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3173]
Something has regressed within the AWS EC2 Amazon Machine Image (AMI) building process. Currently, when I boot an AMI generated on any host (locally, on Ubuntu on EC2, or otherwise), I get the following in the system log at boot:

```
******************* BLKFRONT for device/vbd/2064 **********

backend at /local/domain/0/backend/vbd/4301/2064
67108864 sectors of 512 bytes
**************************

Press `ESC' to enter the menu... Booting 'Medic OS'

root (hd0)
 Filesystem type is ext2fs, using whole disk
kernel /boot/kernel console=hvc0
initrd /boot/image.xz

============= Init TPM Front ================
Tpmfront:Error Unable to read device/vtpm/0/backend-id during tpmfront initialization! error = ENOENT
Tpmfront:Info Shutting down tpmfront
close blk: backend=/local/domain/0/backend/vbd/4301/2049 node=device/vbd/2049
close blk: backend=/local/domain/0/backend/vbd/4301/2064 node=device/vbd/2064
```

Figure out what's going on here and fix it.

**Comment by browndav** [comment]
Okay, it looks like this is normal output followed by an immediate reboot (before the Linux kernel banner is printed). Will continue investigating.

**Comment by browndav** [comment]
Things to try today:

  - [ ] Boot and test other versions of PV-GRUB
  - [ ] Insert a new kernel in an old xen image, see if it boots
  - [ ] Insert a old kernel and old image.xz in a newly-build AMI, see if it boots
  - [ ] Compare ext2fs volume flags between old Xen image and new Xen image

N.B. This isn't a blocker for instance testing or for gathering `view_index` rebuild times and migration run times. Will continur this effort concurrently.

**Comment by browndav** [comment]
👀
https://github.com/medic/medic-os/blob/master/platform/config/kernel/x64/dot-config-3.14.42-grsec#L307

**Comment by browndav** [comment]
This is resolved in Medic OS `master`. Additionally, we've upgraded the kernel in https://github.com/medic/medic-os/commit/4b5441404e9328732c9afc4b1d0f0eab44c5a6e9.

**Comment by henokgetachew** [comment]
I haven't been able to get time this week to get to this.  Reassigning you @browndav

**Comment by garethbowen** [comment]
Nothing's happening here - moving to AT.

**Comment by sglangevin** [comment]
@browndav @henokgetachew I'm moving this to Ready. Please shout if you disagree.
