### ISSUE TITLE
Tasks page blank for admins

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3175]
This page used to have some message along the lines of 'tasks not configured? for admins'?

![image](https://cloud.githubusercontent.com/assets/6979995/23436969/40d8203c-fe71-11e6-94a2-cca3ebf8b5c8.png)

**Comment by garethbowen** [comment]
Fixed by https://github.com/medic/medic-webapp/commit/9ebc6c5b0526d3df09b96d28a60066ce459c5d1c
