### ISSUE TITLE
Reports do not appear in History/Reports without a refresh

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3176]
This can be reproduced consistently when logged in as a restricted user, and sometimes when logged in as admin (online user). I was testing on v2.10.0-beta.6 on lg.dev logged in as a restricted user.

To reproduce:
1. Go to any patient profile
2. Fill in a report (assessment, new pregnancy, etc.) about that patient
3. Notice that you see the report you just submitted in the history section of the patient's profile
4. If you did an assessment, notice that you see a task both in the tasks section of the patient's profile and on the tasks tab
5. Go to the History tab and notice that you do not see the report you've just submitted.
6. Do a refresh on the History tab and notice that you can now see the new reports.

This is a blocker for releasing v2.10.0 final.

**Comment by garethbowen** [comment]
Review please @alxndrsn https://github.com/medic/medic-webapp/pull/3178

When navigating back to the Reports tab we were just refreshing the dom not querying for reports again. This meant that when a change happened while on another tab it didn't update the list. Now it searches every time the tab is loaded which is a little worse performance, but is consistent with other tabs and more what a user would expect I think.

**Comment by garethbowen** [comment]
This needs to be backported to `2.10.x`.

**Comment by alxndrsn** [comment]
I think to maintain performance with LiveList, we should be manually adding the new report to the live list using `livelist.insert()`.

**Comment by sglangevin** [comment]
Looks good!
