### ISSUE TITLE
When navigating to the targets tab, I see a flash of the "no analytics modules configured" message

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3177]
This happens every time when logged in as a restricted user on lg.dev (2.10.0-beta.6). I'm seeing it when logged in via a browser on my laptop, but it's much worse on a Tecno Y4 because the message is visible for longer.

**Comment by garethbowen** [comment]
@sglangevin Is this a blocker for 2.10.0?

**Comment by sglangevin** [comment]
Yes

**Comment by garethbowen** [comment]
Review please @estellecomment : https://github.com/medic/medic-webapp/pull/3179

**Comment by garethbowen** [comment]
Needs to be backported to `2.10.x`

**Comment by sglangevin** [comment]
Looks good!
