### ISSUE TITLE
Set `Secure` setting on AuthSession cookie for HTTPS pages

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3182]
This should be done in api's login controller.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by mandric** [comment]
@alxndrsn please triage (close or schedule)

**Comment by garethbowen** [comment]
Scheduling - this should be a quick win.

**Comment by garethbowen** [comment]
Code review please @SCdF 

Once this is merged leave it open and assign it back to me so I can test on an actual server using https.

**Comment by SCdF** [comment]
Back to you @garethbowen. Mostly fine, just a comment about implementation and security therein.

**Comment by garethbowen** [comment]
Yeah good call. I've changed it to use the NODE_ENV environment variable which I think we're setting to [production in medic-os](https://github.com/medic/medic-os/tree/master/platform/packages/gardener/settings/gardener/env). It's another thing I'll test when this gets merged.

Please re-review @SCdF

**Comment by SCdF** [comment]
LGTM @garethbowen, back to you to test etc

**Comment by garethbowen** [comment]
Tested on alpha.dev works as expected. Leaving in AT so another pair of eyes can check it.

For AT:

1. Log out and log in again
2. Check your cookies in the dev console. In Chrome it's in the Application tab, in Firefox it's in the Storage tab.
3. Find the AuthSession cookie, and ensure it's "httpOnly" and "secure", eg:

![cookie](https://user-images.githubusercontent.com/2064938/28396249-5679ae3c-6d4e-11e7-822f-5ab08a36436a.png)
