### ISSUE TITLE
Organise documentation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3186]
We have documentation in two places: [medic-docs](https://github.com/medic/medic-docs/) and [medic-webapp/doc](https://github.com/medic/medic-webapp/tree/master/doc) - we should only have one place.

Decide which place is best (my vote is medic-docs) and merge these places together.

Restructure the folders wherever it ends up to be more logical.

**Comment by abbyad** [comment]
Good idea. Looping in @ngamita and @derickl since it may affect tech lead docs too.

**Comment by ngamita** [comment]
Thx Marc. I go for medic-docs. Adding @smbuthia who leads and manages all tech documents techleads and can support with this.

**Comment by smbuthia** [comment]
@garethbowen we'd like to start adding a number of the tech-leads docs by end of this week. I've been looking through the repo and I am not quite sure where to begin. Would it make sense to have a tech-leads folder specifically for tech-leads docs?

**Comment by garethbowen** [comment]
@smbuthia Yeah that's sort of what I was thinking, except maybe "configuration" instead of "tech-leads"? I'll get on to this one soon so you have a structure to put docs in, and you can let me know if the new structure works for you or not.

**Comment by smbuthia** [comment]
Yeah, that works. Thanks @garethbowen

**Comment by garethbowen** [comment]
@smbuthia Sorry I didn't get around to this this week. Feel free to start adding documentation to https://github.com/medic/medic-docs/tree/master/md/ and I'll get on to the reorganisation next week.

**Comment by garethbowen** [comment]
@smbuthia I've updated the repo now so hopefully it's much easier to find things!

**Comment by smbuthia** [comment]
@garethbowen awesome. Thanks!
