### ISSUE TITLE
Consider supporting both CouchDB1.x and 2.x in production

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3187]
See how feasible this is.

**Comment by SCdF** [comment]
Results:
 - Supporting both in travis looks hard, because their ports would conflict, and it would mean we are running 6 builds instead of the already kind of slow 3. I'm not sure how we feel about supporting both in general if we decide to only support 2.0 in travis. I think this would be a blocker honestly.
 - Supporting both in dev looks mostly fine, we'd just need to change Grunt a little to detect which you're running before trying to run an admin command
 - API looks to be a little annoying: migration scripts would need to check first and then support both Mango and temporary views, or both admin URLs in some cases

**Comment by SCdF** [comment]
@alxndrsn do you have any thoughts about supporting both in travis?

**Comment by alxndrsn** [comment]
Not specifically.  Sounds like it could be fiddly to set up, and slow to run.  But perhaps not!  I guess you'd just run 2 parallel builds - one with the old style config, and one with the new.

**Comment by SCdF** [comment]
@alxndrsn chiggidy check this out https://github.com/medic/medic-webapp/pull/3193

**Comment by alxndrsn** [comment]
Changes look fine, but one of the build jobs failed (https://travis-ci.org/medic/medic-webapp/jobs/207412686).

**Comment by SCdF** [comment]
Yeah, it looks like `initDb()` is flaky somehow? It must be exasperated by the 2.0 build process (eg docker etc) because it doesn't happen in the 1.x builds. I'm going to merge anyway, and then add some logging, since initDb is too complicated for me to see the problem straight away.
