### ISSUE TITLE
Use translation keys for all labels in app settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3190]
Following the success of #3127, we should add the option to use `translation_key` to replace all explicit translation labels in `app_settings`.

- `tasks.targets.items[].name`
- `tasks.schedules[].events[].title`
- `tasks.schedules[].events[].description`
- `forms`

The first three use "content", whereas `forms` are structured differently. We should allow for `translation_key` for all to make translations easier to manage and less error prone for tech leads and PMs. We will still need to maintain support for the old style of translations to not force previous configurations to be updated, and so that forms can still be used directly by SIM app and Reporter.

Here is an example of the label structure for `forms`, which is different than the rest:
```
"OPV0": {
      "meta": {
        "code": "OPV0",
        "icon": "immunization",
        "label": {
          "en": " OPV0 Oral polio"
        }
      },
      "fields": {
        "patient_id": {
          "labels": {
            "description": {
              "en": "Patient ID"
            },
            "short": {
              "en": "ID"
            },
            "tiny": {
              "en": "D"
            },
          },
```

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
This is very pertinent, will mark as scheduled.

**Comment by garethbowen** [comment]
Also update transition messages such as `notifications.messages`

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by garethbowen** [comment]
Code review please @alxndrsn - I missed a couple of places where translation is needed.

**Comment by alxndrsn** [comment]
Who is this feature for?

**Comment by garethbowen** [comment]
@alxndrsn It makes life easier for configurers so they can reuse keys, and change translations easily. It also deprecates our old translation strategy which means one day we can have simpler translation code.

**Comment by sglangevin** [comment]
It also makes it possible for PMs to update translations easily, which means less work for tech leads.
