### ISSUE TITLE
Support for Nepali number characters

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#3192]
In our projects in Nepal, the reporters have to use the English number for sending numerical values like Weeks since LMP, Days Since Birth, Patient ID in the textforms, while rest of the forms are in Nepali. This is confusing to users and has been a constant cause of errors in reports. Thus the need of support for Nepali numbers.

It is also a major requirement for our government adoption plans for projects, as we are always questioned about the lack of support for the numbers during various meetings and presentation with government agencies and other stakeholders.

Nepali numbers follow the same 10 digit numeral system as the English one and so can be easily mapped 1:1 
```
० -> 0 
१ -> 1
२ -> 2
३ -> 3
४ -> 4
५ -> 5
६ -> 6
७ -> 7
८ -> 8
९ -> 9
```

**Comment by SCdF** [comment]
Is there an official way of translation numbers, a library based on a configured language or something? i.e. as opposed to us writing a regex?

**Comment by bishwas-medic** [comment]
Couldn't find any useful libraries for translating the Nepali/Hindi or Arabic numbers.

**Comment by alxndrsn** [comment]
for converting different numeral systems to Western Arabic: https://github.com/medic/eurodig

**Comment by alxndrsn** [comment]
N.B. script is called _[Devanagari](https://en.wikipedia.org/wiki/Devanagari#Numerals)_.

**Comment by alxndrsn** [comment]
@mandric I am working more on this to stop message content being changed - please hold off on your review!

**Comment by alxndrsn** [comment]
@mandric ready for review again at https://github.com/medic/medic-webapp/issues/3220 :¬)

The message is modified in-place, but the original text is stored in `doc.raw_message`.

**Comment by ngaruko** [comment]
@bishwas-medic  are you able to test if this works for you now, on your instances?

**Comment by bishwas-medic** [comment]
Yes @ngaruko , we've already tested this feature successfully in our instances.

**Comment by ngaruko** [comment]
Thanks @bishwas-medic

**Comment by ashish-medic** [comment]
It's working for Weeks since LMP, Days Since Birth but not for Patient ID. Is this accepted? @alxndrsn @ngaruko @sglangevin
