### ISSUE TITLE
Difficult to switch between meta and context files

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3194]
When uploading XForms we can now set the meta file instead of just the context. This was done to accommodate icons. From https://github.com/medic/medic-webapp/issues/2838
> In #2794 we modified the UI to display a custom icon beside forms and reports. For Enketo forms this is set as a string property on the form doc. We use a custom upload_xform script to create form docs and set metadata such as the context. Modify this script to also set the icon string.

> The context metadata is stored in a separate file which is read and save to the doc. It might make sense to make it more generic so that file is a JSON blob with context and icon properties. This could then be used to add any future metadata without updating the script further.

Some forms still use the context values as opposed to a meta file. Switching between the two currently requires manual changing the [convert script](https://github.com/medic/medic-projects/blob/master/scripts/convert.sh) to use either the `m` option or the `c`. Also, to use the meta file the [upload_script.sh](https://github.com/medic/medic-webapp/blob/97b5278fd213a32cddc5a6ceb0881a5ba30e5cba/scripts/upload_xform.sh#L101) needed a manual edit to fix a typo that prevented the use of meta files. 

We should accommodate both context and meta files automatically, and fix the typo.

**Comment by abbyad** [comment]
This is now fixed, ready for a light code review.

**Comment by alxndrsn** [comment]
A couple of minor comments inline.

**Comment by abbyad** [comment]
Thanks @alxndrsn, assigning back for another quick review

**Comment by alxndrsn** [comment]
Looks fine 👍   Any chance of removing the `cat`?

**Comment by abbyad** [comment]
I thought I had here: https://github.com/medic/medic-projects/commit/8c116068201ddc36b919cf565d8468b4e401d498#diff-09f12b64128201380c6d369ab5056e56R124

Anywhere else?

**Comment by alxndrsn** [comment]
@marc apologies yes - looks like you fixed it already
