### ISSUE TITLE
Cannot see contacts list in other (non fully translated) languages

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3195]
When changing a user's language they cannot access their contact list:

```
TypeError: Cannot read property 'substr' of null
 on <span ng-show="!reportsTimeWindowMonths" translate="">
```

![image](https://cloud.githubusercontent.com/assets/789512/23571236/135b9e1a-0036-11e7-941f-f85ad5853f4a.png)

We are missing some translations for that language, but it likely shouldn't break this bad.

Going to the other tabs doesn't break as badly because the content shows, but there are still errors in console: `TypeError: Cannot read property 'substr' of null`

Tested on 2.10.0-alpha.4895

**Comment by abbyad** [comment]
From testing on standard.app, `fr`, `id` show the errors above, but `es`, `hi`, `ne`, `sw` (and `en`) do not.

**Comment by garethbowen** [comment]
I think this is caused by https://github.com/angular-translate/angular-translate/issues/665

Bumping the dependency fixes it.
