### ISSUE TITLE
The scroll bar not visible on add user form

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3198]
Steps:
Login as admin
Configurations
Users
Add user

Observed: There is no scrolling bar
Expected: If the whole form does not fit on the user's screen, there should be a scroll bar to go up and down the page

![image](https://cloud.githubusercontent.com/assets/6979995/23591970/575a5348-025e-11e7-9063-89be4ff62660.png)

**Comment by garethbowen** [comment]
@ngaruko What browser/OS/device is this?

I wonder if it's a OSX thing? Can you two-finger scroll it?

**Comment by sglangevin** [comment]
This works for me on OSX on the latest beta. The scroll bar appears when I scroll using my mouse/trackpad.

**Comment by ngaruko** [comment]
Yes. It looks like it has to do with some settings on my machine. I can see the same pattern with other pages as well. Will mark it 'No Action Required' and close it.

**Comment by ngaruko** [comment]
Ah! Was to do with my settings on the machine!
![image](https://cloud.githubusercontent.com/assets/6979995/23827869/7782de64-0723-11e7-91ea-759c4ef14154.png)
