### ISSUE TITLE
Update contact reports and children on change

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3199]
When viewing a contact if the contact's details or tasks change the UI is updated automatically. However if the reports or children change it does not. The most common example of this is filing a new report for the contact.

The workaround is to refresh, or click a different person/tab and then click back.

Extend the changes listener to respond to additions, changes, and deletions in children and reports.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
@garethbowen this doesn't seem that old to me.  You might have more idea if this is pertinent or not.

**Comment by garethbowen** [comment]
Still pertinent. Not urgent however.

**Comment by garethbowen** [comment]
Duplicate of #3530
