### ISSUE TITLE
Audit log export only returns first 1000-ish docs

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3204]
The query in audit log export has `limit=1000` : https://github.com/medic/medic-api/blob/master/controllers/export-data.js#L155

In practice I can't get the whole 1000 (https://github.com/medic/medic-webapp/issues/1789), but `limit=100` gives me 460 `<Row>` tags in the xml, and `limit=50` gives me 247. So definitely a variable number.

Is that on purpose? I'd expect the whole db to come out. If it is, then we need to change the UI to make that clear.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Yeah it's on purpose to stop someone crashing the server accidentally... The perfect solution would batch and stream somehow.

However, I suspect nobody is actually using the export audit api as auditing is usually just to investigate a specific document. Let's ask around and see if we can drop the api altogether.

**Comment by sglangevin** [comment]
Can we remove this API altogether? I guess we should touch base with @ngamita and perhaps a few tech leads to see if this is being used for support purposes.

**Comment by SCdF** [comment]
IMO it's worth going through all those obscure exports and working out if people care: once we drop them from the UI we can drop them from the api in the major after that one.

**Comment by sglangevin** [comment]
Ok - here's what I've heard so far: user feedback logs are useful and actively being used, including in the UI. No one has spoken up to say that they use the audit logs export or the server logs export in the UI or via API but I'm waiting a little longer to be sure about those.

**Comment by garethbowen** [comment]
This feature is being removed in #3391
