### ISSUE TITLE
Targets aren't updated when no longer relevant

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3207]
Targets are considered relevant to the UI if their date is within the current month. Currently if a target is updated to no longer be relevant the change notification is ignored and the UI is left in the incorrect state. When the page is refreshed the UI shows the correct state.

Steps to reproduce:

1. Set up your nools rules like so:
  ```
  define Target {  _id: null,  deleted: null,  type: null,  pass: null,  date: null}
  define Contact {  contact: null,  reports: null}
  define Task {  _id: null,  deleted: null,  doc: null,  contact: null,  icon: null,  date: null,  title: null,  fields: null,  resolved: null,  priority: null,  priorityLabel: null,  reports: null,  actions: null}
  rule GenerateEvents {  when {    c: Contact  }  then { 

      var newestAss = Utils.getMostRecentReport(c.reports, 'A');
      var instance = new Target({
        _id: c.contact._id + '-ass-count',
        deleted: !newestAss,
        type: 'ass-count',
        pass: true,
        date: newestAss ? newestAss.reported_date : new Date()
      });
      emit('target', instance);

      emit("_complete", { _id: true });
   }}
  ```
2. Set up your targets to have an "ass-count" target.
3. Create an assessment report (any report with `form: 'A'`) dated before the start of this month (UTC)
4. Create an assessment report this month
5. Refresh and view the Targets tab and ensure the assessment count is 1
6. Delete the assessment from this month through the UI

Expected: The assessment count is now 0
Actual: The assessment count is still 1

Update the Target Generator to not ignore target instances which have been modified to be no longer relevant.

**Comment by garethbowen** [comment]
Review please @alxndrsn https://github.com/medic/medic-webapp/pull/3208

This is a blocker for 2.10

**Comment by sglangevin** [comment]
Looks good @garethbowen - deletes are now being reflected correctly in targets. Moving to Ready.
