### ISSUE TITLE
Prevent users from being automatically logged out

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3215]
On 2.x, we set the login timeout for one year in order for users to be authenticated by something they have (a session key on their phone) rather than something they know (the password). Coordinate with @sharon to find a suitable solution for extending the session timeout and avoiding uncommanded logouts. A better solution should be found for password management and account security, but this issue is time-sensitive and should probably be handled separately.

**Comment by browndav** [comment]
To do: perform a test with an artificially low session expiry duration; figure out what (if any) information about active sessions we can get from CouchDB.

**Comment by sglangevin** [comment]
@browndav has this testing been done?

**Comment by browndav** [comment]
Testing is complete. The short answer: we shouldn't have to do anything, provided `allow_persistent_cookies` and `require_valid_user` are enabled (and they are).

The long answer: CouchDB will automatically reissue a `Set-Cookie` header with a different token if (i) a `Cookie` header with a valid still-valid session token was received; *and* (ii) a non-trivial amount of time has passed since the last request (read: the token is old enough to refresh).

If you set `timeout` to `30` seconds, the following one-off test script will demonstrate that the both the cookie and session expiration time are advanced by CouchDB automatically:

```shell
#!/bin/sh

set -o pipefail

USER='user'
PASSWORD='password'
HOSTNAME='localhost:5984'
URL="http://$USER:$PASSWORD@$HOSTNAME"

print_cookie()
{
  grep '^Set-Cookie: '
}

cookie_cutter()
{
  print_cookie | cut -d' ' -f2 | sed 's/;$//;'
}

# Dump configuration
curl -s "$URL/_config/couch_httpd_auth/timeout" &&
curl -s "$URL/_config/couch_httpd_auth/require_valid_user" &&
curl -s "$URL/_config/couch_httpd_auth/allow_persistent_cookies" &&
\
# Start session
cookie="`
  curl -si "$URL/_session" \
    -d "name=$USER" -d "password=$PASSWORD" | cookie_cutter
`"
echo "$cookie"
sleep 10
\
# Repeatedly refresh session
for i in `seq 1 5`; do
  output="`curl -si "http://$HOSTNAME/" -H "Cookie:$cookie"`"
  cookie="`echo "$output" | cookie_cutter`" &&
  echo "$output" | print_cookie &&
  sleep 20
done &&
\
# Expiration
sleep 45 &&
echo 'Should fail' &&
curl -s "http://$HOSTNAME/" -H "Cookie:$cookie"
```

The output, with the cookie and session expiration times clearly advancing:

```
"30"
"true"
"true"
AuthSession=YnJvd25kYXY6NThEMDUzQjk6nRZxG9ueXLlTzjg0nreh052LHu0
Set-Cookie: AuthSession=YnJvd25kYXY6NThEMDUzQzM6LIaaulJPZ9_GlhQVdJgMg0BTsMo; Version=1; Expires=Tue, 21-Mar-2017 05:12:49 GMT; Max-Age=30; Path=/; HttpOnly
Set-Cookie: AuthSession=YnJvd25kYXY6NThEMDUzRDc6EJLkqcnp54NNX4Blj3CFsogpDqo; Version=1; Expires=Tue, 21-Mar-2017 05:13:09 GMT; Max-Age=30; Path=/; HttpOnly
Set-Cookie: AuthSession=YnJvd25kYXY6NThEMDUzRUI6axq3TvqnKYGEjO_3vXrWYEKPVw8; Version=1; Expires=Tue, 21-Mar-2017 05:13:29 GMT; Max-Age=30; Path=/; HttpOnly
Set-Cookie: AuthSession=YnJvd25kYXY6NThEMDUzRkY6skDjtm2YWMDNzqga29v0RIevxSc; Version=1; Expires=Tue, 21-Mar-2017 05:13:49 GMT; Max-Age=30; Path=/; HttpOnly
Set-Cookie: AuthSession=YnJvd25kYXY6NThEMDU0MTM67XTeTZ369t5zHOSeA-Kxeangtw8; Version=1; Expires=Tue, 21-Mar-2017 05:14:09 GMT; Max-Age=30; Path=/; HttpOnly
Should fail
{"error":"unauthorized","reason":"Authentication required."}
```

Proposed issue resolution: no action needed.
