### ISSUE TITLE
Error flagged in webapp upon submitting outreach form

### ISSUE THREAD

**Issue by SMurithi** [medic/medic-webapp#3216]
Hey @smbuthia I get the error below upon submitting the outreach form. With it the webapp does not send an autoreply. This is the v2 instance
![image](https://cloud.githubusercontent.com/assets/19404632/23793642/60056efa-059d-11e7-92ff-0e8af7f53a91.png)

**Comment by smbuthia** [comment]
@SMurithi this should be under medic projects.

**Comment by SMurithi** [comment]
Noted @smbuthia. I have transferred as advised
