### ISSUE TITLE
Supplies form in CB-HIPP- v2 instance

### ISSUE THREAD

**Issue by SMurithi** [medic/medic-webapp#3217]
@smbuthia please check the supplies form as it generates an error SMS "sys.registration_not_-found". Also it does not hit the webapp even though the gateway marks it as forwarded.
Also the validation for MMID in the form is 5 characters. Please change to 7 characters.
Asante

**Comment by smbuthia** [comment]
@SMurithi this should be under medic projects.

**Comment by SMurithi** [comment]
Noted @smbuthia. I have transferred as advised
