### ISSUE TITLE
Common issues in CB-HIPP v2 testing

### ISSUE THREAD

**Issue by SMurithi** [medic/medic-webapp#3218]
@smbuthia here is the breakdown of issues;
- SF, RF, RVCF, ANCR, ANCV IMMV hit the gateway and marked as forwarded to webapp but never hit the webapp. The SMS autoreply for all is "sys.registration_not_-found"

For Child birth, ON, OFF forms no autoreply is received, they do not hit the webapp even when marked as such in the gateway and no autoreply is sent.

**Comment by smbuthia** [comment]
@SMurithi this should be under medic projects.

**Comment by SMurithi** [comment]
Noted @smbuthia. I have transferred as advised
