### ISSUE TITLE
Decide if we want to enable validation of patient id correctness via checksum

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3223]
We currently generate patient ids (short codes) with the last digit as a checksum. This is potentially pretty cool because it helps us to verify that the correct id was actually entered, and someone hasn't entered an incorrect ID by mistake. This is already technically covered by the fact that we hard check the id to link it, but it does allow us to check without having to talk to the DB, and potentially allows us to check in other situations.

We currently don't actually use it for anything though.

Should we:
 - Leave it in, but don't use it, because maybe we will want it later (YAGNI be damned!)
 - Allow it to be configurabley attached to patient_ids somehow. NB: we can't just blindly apply it to patient ids because the partner may be using external ids
 - Realise we don't care and drop it, which a) simplifies the code, and b) gets us an order of magnitude more ids out of the same length (because the last digit can be random like the rest)

**Comment by mandric** [comment]
> We currently don't actually use it for anything though.

But since we've been using these types of IDs in the past haven't we technically been using them then?  I thought the point of the check ID was just to limit/help avoid typos from IDs entered manually which is what is happening on SMS.

**Comment by SCdF** [comment]
Oh I think I understand what you're saying. To confirm: are you saying that it's not that we should use the checksum to validate, but more that it's an intentional non-random digit at the end, to confirm that you aren't mis-typing the id? So while `12348` is valid, `13248` can never be a valid id, because we'd generate `13249` for this (based on our current checksum algorithm).

**Comment by mandric** [comment]
Correct!

**Comment by mandric** [comment]
By removing the check digit you are changing behavior which could result in a potential regression that is hard to detect...

**Comment by SCdF** [comment]
Cool. I'll document that against the code, because it confused me!

**Comment by mandric** [comment]
Yeah was thinking a test would do the trick too/even better.
