### ISSUE TITLE
Write an e2e test that involves a sentinel transition

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3229]
Our e2e test framework doesn't start sentinel so we're lacking coverage on any SMS workflows. This issue is mostly about getting the framework working to remove the inertia for writing SMS e2e tests. Pick any simple workflow that requires a transition and ensure when a message is received the UI is eventually updated to show the doc with all transitions performed successfully.

**Comment by SCdF** [comment]
This comment should not derail this ticket or expand the scope in any way. I just want to note that I think this is pretty important, and contributes so a collection of work we should be slowly improving (incl. mobile css e2e tests, supporting the changes feed, supporting non-admin users) to bring our e2e tests in line with real use, and give them a lot of bang for their buck. So, +1.

**Comment by garethbowen** [comment]
Review please @SCdF https://github.com/medic/medic-sentinel/pull/118

Don't close this issue when done - this is step 1 towards getting an e2e test for transitions.

**Comment by SCdF** [comment]
Back to you @garethbowen , just made some style comments re: ES6

**Comment by garethbowen** [comment]
Round 2 please @SCdF https://github.com/medic/medic-webapp/pull/3266

**Comment by SCdF** [comment]
Back to you @garethbowen , all ES6 stuff
