### ISSUE TITLE
Work out id_length efficiency

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3231]
We just change the code to auto-lengthen ids if required. However, I just realised we never really looked into the random numbers we plugged into that algorithm. Write a little script to work out a good proportion to use (ie how many ids to check etc), and change it to that.

**Comment by SCdF** [comment]
Looks like a round size of `20` is pretty good, but I'm still testing. I really feel like there should be some maths that just answers this question, but I do not know what it would be. Oh well.

**Comment by SCdF** [comment]
PR: https://github.com/medic/medic-sentinel/pull/117

After talking with @garethbowen we settled on a better strategy:
 - We start with an empty in-memory cache, and a id length of 4 (i.e. `0000` -> `9999`)
 - When an id is requested, we pull one from the in-memory cache and use that, with no I/O required. This is OK because we are the only ones creating IDs.
 - If we run out of cached ids then we refresh the cache, by generating `100` random IDs of the correct length, and querying the CouchDB view to determine if they are already used or not
 - The valid IDs are added to the cache, and used to return ids
 - If all 100 of the random ids are already used in CouchDB, we increment the default id length from 4 to 5 (and from 5 to 6, 6 to 7 etc), and reboot the process

@garethbowen please take a look. Note that this is based off the other PR that you reviewed, I'll make sure it all merges properly.

**Comment by garethbowen** [comment]
Couple of comments. Back you to.

**Comment by SCdF** [comment]
@abbyad BTW having a dynamically increasing ID length means that validations like this (and their associated hard-coded messages) are no longer valid: https://github.com/medic/medic-projects/blob/master/default-sms-workflow/standard/app_settings.json#L483-L487

I imagine you'd just want to change it to `[0-9]{5,13}`, which is the min and max valid range at the moment.

**Comment by SCdF** [comment]
@garethbowen I uh… I changed it a little. You may just want to read [ids.js](https://github.com/medic/medic-sentinel/blob/3231_id_efficiency/lib/ids.js) by itself and then check out the rest of the diff.

I rolled back some changes where I got rid of a local function that nothing but null check and then call the real function, because it turned out the tiny null-check--- which AFAICT is never useful in production and could arguably hide bugs in config--- caused a bunch of unit tests to break because they expected it (yay unit tests), and my Friday is only so long.

**Comment by abbyad** [comment]
Thanks for the heads up @SCdF, we'll have to do this change on many instances upgrading to this version.
cc @ngamita

**Comment by sglangevin** [comment]
@ngamita this is the issue I was talking about last week related to validation of IDs. Since the web app will automatically increase the ID length if we run out of IDs, we'll need to update the validations in the config for all projects upgrading to v2. I'll leave a note about this on Slack as well.

**Comment by garethbowen** [comment]
@SCdF Back to you...

**Comment by ngamita** [comment]
@sglangevin noted as this affects several projects. I'll communicate this to techleads and mention in our weekly call. I'm assuming this change comes in in v2.11

**Comment by SCdF** [comment]
@ngamita yep. The devs should have a conversation about how to add upgrade notes into release notes in a consistent way that doesn't involve trolling all tickets

**Comment by SCdF** [comment]
@garethbowen I made some changes, made some discussion. NB: I also added a check at the start of sentinel to make sure your node version is good enough. I think it's important since the app will explode if the version is too old.

**Comment by garethbowen** [comment]
Don't forget to update the Changes.md with any required configuration change.

**Comment by SCdF** [comment]
Merged into the #3166 feature branch. I'll close this ticket once _that_ branch has been merged into master.
