### ISSUE TITLE
Replication isn't working

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3236]
If I change a doc on the server it appears to replicate to the client but nothing actually changes.

For example, in the console I get...

> EVALUATED FUNCTION LOGS: medic-client validate_doc_update passed for User "null" changing document "form:assessment"
> Replicate from server successful with 75.39 seconds since the previous successful replication.

But no

> Change notification firing Object {id: "form:assessment", changes: Array[1], doc: Object, seq: 78}

It's not just the changes listener because even if I refresh the page the form isn't updated.

**Comment by garethbowen** [comment]
@SCdF If I comment out the pouchdb validations it works so it looks like it was caused by #2222 

I don't have time to look at it right now so unassigning from myself...

**Comment by SCdF** [comment]
This would be a blocked to releasing 2.11

**Comment by SCdF** [comment]
OK I've disabled this while keeping the splitting / refactoring work I did: https://github.com/medic/medic-webapp/pull/3298

I'm going to re-open #2222 and we can re-look into it later.
