### ISSUE TITLE
Make authentication more secure

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3238]
Patch the vulnerabilities outlined in [medic-projects](https://github.com/medic/medic-projects/issues/1638)

**Comment by garethbowen** [comment]
Scheduling as per the planning meeting. Put together a proposal and share it with the team for discussion.

**Comment by alxndrsn** [comment]
Issue created:
* https://github.com/medic/medic-webapp/issues/3373

**Comment by garethbowen** [comment]
Looks good to me. @SCdF Any thoughts?

**Comment by SCdF** [comment]
I'm a bit lost with these tickets honestly. It's cool they exist, but is the purpose here to prioritise them, schedule them etc?

**Comment by alxndrsn** [comment]
> is the purpose here to prioritise them, schedule them etc?

Yes.
