### ISSUE TITLE
Accessing webapp without logging in is possible

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3239]
Stub for medic/medic-projects#907

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Yeah... we should fix this. Adding to 2.14.0.

**Comment by garethbowen** [comment]
@SCdF Code review please.

The only part I'm not 100% comfortable with here is checking if unit tests are running in the app.js. Without this all unit tests were being redirected to the login page. Ideally the app.js wouldn't execute at all but I don't know how to easily separate it from the rest of the bundle.

**Comment by SCdF** [comment]
LGTM, merged.

**Comment by sglangevin** [comment]
@ngaruko assigned to you for AT.
