### ISSUE TITLE
Sending a message from the Messages tab creates a message with uuid equal to database URL

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3242]
https://github.com/medic/medic-projects/issues/1643

The guilty code: https://github.com/medic/medic-webapp/blob/master/static/js/services/send-message.js#L166 -> https://github.com/medic/medic-webapp/blob/master/static/js/services/send-message.js#L133-L143

**Comment by garethbowen** [comment]
worker-pouch issue created: https://github.com/nolanlawson/worker-pouch/issues/34

**Comment by ngaruko** [comment]
Does this need AT @alxndrsn . How do you reproduce/check this?
