### ISSUE TITLE
Enketo report summary screen looks messed up

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3248]
![summary](https://cloud.githubusercontent.com/assets/2064938/23977362/96c11548-0a52-11e7-9b9e-fce67e3eb86b.png)

This may be due to recently bumping the enketo version.

**Comment by alxndrsn** [comment]
Out of interest, any idea how this CSS got lost?

**Comment by garethbowen** [comment]
@alxndrsn I tracked it down to being removed in around enketo-core 4.5. It turns out depending on their css is quite fragile - it's probably worth some investigation some time about how to define our own "theme" or something.

**Comment by ngaruko** [comment]
LGTM
