### ISSUE TITLE
Re-upgrade travis firefox to `latest-esr`

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3250]
Because of incompatibility between Firefox 52, protractor 4 and JDK7, I have forced the Firefox version on Travis to `45.0`, which was the last [Extended Support Release](https://www.mozilla.org/en-US/firefox/organizations/faq/) to be compatible with our current config.

We _need_ to get Travis working with latest Firefox ASAP, as otherwise our e2e tests will grow stale.  I have begun [work on this on a branch](https://github.com/medic/medic-webapp/tree/marionette), but [not yet managed to make it work](https://travis-ci.org/medic/medic-webapp/branches).

**Comment by garethbowen** [comment]
@alxndrsn I've switched the build to run on Chrome only - Firefox was too fragile. I'm going to close this unless you know of a reason to try again?
