### ISSUE TITLE
V2 Schedules Configuration: "recipient": "parent" doesn't work

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3253]
With 0.4.x versions, it is possible to do this: `"recipient": "parent"` to send messages to the supervisor of the CHW.  With v2 however this doesn't map to the supervisor's phone number (The parent).  Other options that don't work but that have been tested include: `"recipient": "contact.parent.parent.contact.phone"` and `"recipient": "doc.contact.parent.parent.contact.phone"` 

![d3a0c43e-0a59-11e7-94cc-61dc9d56fdc8-redacted](https://cloud.githubusercontent.com/assets/789512/24010348/fe82316c-0a4d-11e7-968c-57e6815d6cc8.png)

When migrating 0.4.x instances to v2, this is going to be a major one as sending to the supervisor of the CHWs when they haven't been as responsive is included in projects.  Unless there is a specific wording we can use here that already works I think this is a blocker for the migrations.

*Side note* : Once we have managed to get this working, this needs to be a part of the migrations process:
We need to update the configs of instances to change `"recipient": "parent"` to the format that will work.

**Comment by abbyad** [comment]
The issue here is likely because the form submitter is connected to a `health_center` (middle level), not a `clinic` (lowest level). If the form submitted belongs to a `clinic` then setting the recipient as the parent/grandparent works properly, as long the number has not changed (pending #2635).

**Comment by sglangevin** [comment]
@henokgetachew will this project need for this feature to work for a `health_center`? Or will real users be connected to a `clinic`?

**Comment by henokgetachew** [comment]
Real users are connected to the `clinic` in this case.  What I haven't understood is how the fields are picked from the doc and like why {{contact.parent}} above for example didn't work.. We're still fleshing things out here and there are still issues I'm working on.. I will resolve the issue when that's done.

**Comment by sglangevin** [comment]
Sounds good @henokgetachew - let us know if there is a bug here that needs attention and we'll get it fixed.

**Comment by sglangevin** [comment]
@henokgetachew any update on this one? Wondering if we need to pull this forward into the next milestone or if we will likely be closing this issue.

**Comment by garethbowen** [comment]
Descheduling this issue waiting for more information from @henokgetachew

**Comment by henokgetachew** [comment]
I will respond to this by tomorrow.

**Comment by henokgetachew** [comment]
An example of one that still fails: https://github.com/medic/medic-projects/issues/1748

**Comment by JenniferMuli** [comment]
@henokgetachew  not sure why this works sometimes and fails at other times.

We have just submitted a new Pregnancy Registration form now and its works perfectly
https://christianaidisiolo.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/f107cc9ef2f01e605d482c48c13a4a90

**Comment by henokgetachew** [comment]
I will look at the different CHWs and compare the hierarchies.  I think the most likely cause is that the two CHWs are at different levels of the hierarchy.

**Comment by JenniferMuli** [comment]
@henokgetachew we are doing a clean up of the instance today since they are going live next week .

However we can leave the 2 CHWs so that you can do the comparison first and see what might be the issue.

**Comment by henokgetachew** [comment]
Thanks @JenniferMuli.  Yes, that would be great.

**Comment by sglangevin** [comment]
@henokgetachew I would also look into the contact docs of the CHWs for which reminders are not going to the supervisors. I saw one example on this instance where the problem was that the supervisor didn't have a phone number at the time that the CHW was created. It's possible that issue is affecting multiple CHWs.

**Comment by henokgetachew** [comment]
@sglangevin we were looking at just the report doc thinking that the `{contact}.{parent}` was getting picked from it.  I didn't know it was actually going to the contact's doc to look for the parent. @JenniferMuli let's make sure that all supervisors have phone numbers filled in before creating the CHWs under them.
Do you guys think it makes sense to have a way of updating the CHW docs when the supervisor docs are updated to force referential integrity? cc: @garethbowen

**Comment by sglangevin** [comment]
@henokgetachew we have an issue for that. https://github.com/medic/medic-webapp/issues/2635

We should be getting that done within the next few iterations so that we can avoid similar issues. For now, the best thing to do is to make sure supervisors have phone numbers before creating CHWs.

**Comment by henokgetachew** [comment]
The standard contact forms have fixed the hierarchy issue.
