### ISSUE TITLE
Document the `tasks` section used for Tasks and Targets

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3256]
The `contact_summary` section is [well documented in kanso](https://github.com/medic/medic-webapp/blob/e4330e08d9b2bd3b351b534751cf32ef1c299b04/kanso.json#L328), linking to further documentation for that section. We should document the [`tasks` section](https://github.com/medic/medic-webapp/blob/e4330e08d9b2bd3b351b534751cf32ef1c299b04/kanso.json#L1035
) in a similar fashion, linking to more complete documentation in `medic-docs`. The documentation is primarily intended as a resource for tech leads configuring instances.

**Comment by nice-snek** [comment]
hi frand @browndav, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
Agreed.

**Comment by garethbowen** [comment]
@abbyad I've linked to the existing documentation. Please check that it's sufficient!

**Comment by ngaruko** [comment]
Are you able to confirm that the documentation is sufficient @abbyad  and move this to 'Ready'? Thanks
