### ISSUE TITLE
Auth rejection message is wrong for disallowed non-admins

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3259]
```
return Settings().then(function(settings) {
  if (check(requiredPermissions, roles, settings, true) &&
      check(disallowedPermissions, roles, settings, false)) {
    return $q.resolve();
  }
  return authFail('missing required permission(s)');
});
```
– https://github.com/medic/medic-webapp/blob/master/static/js/services/auth.js#L78

Looks like `missing required permission(s)` will be returned if `check(disallowedPermissions, ...)` fails.

**Comment by garethbowen** [comment]
Code review please @alxndrsn - it's trivial so I just committed straight to master.
