### ISSUE TITLE
clone-christianaid2.app: Contact edit and delete button missing label

### ISSUE THREAD

**Issue by erwagasore** [medic/medic-webapp#3263]
On any contact page we have both edit and delete button showing only their icons but missing the label. See attached image below for clarity

![screen shot 2017-03-21 at 8 39 27 am](https://cloud.githubusercontent.com/assets/1290048/24135679/e60754e0-0e13-11e7-8b94-21db37f127c1.png)

**Comment by sglangevin** [comment]
Note: this was moved to medic-projects.
