### ISSUE TITLE
Detect access configuration errors and notify the user

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3264]
The ["too many redirects" issue](https://github.com/medic/medic-projects/issues/1668) was found again today due to the medic app being configured as "Admins Only" instead of "Public". This has been hit several times and it's not obvious what's going wrong (unless you've hit it before and can still remember the solution).

Work out some way to detect this issue and let users know.

**Comment by garethbowen** [comment]
My initial thought is to check in the background when the login page is loaded and show a big error somewhere that the app is configured for admins only.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by estellecomment** [comment]
@garethbowen I don't understand the point of this setting. We have users that have permissions, why do we need an overarching public/private setting? Can't we just remove the setting?

**Comment by garethbowen** [comment]
This is baked in to dashboard somewhere so I don't think we can just remove it. Instead what we should do is the same thing we do now for "admin party" mode - check it in API and refuse to start if it's set to "admins only".

Scheduling.

**Comment by sglangevin** [comment]
Is this still relevant once we have Horti? If not, I think we can close this issue.

**Comment by garethbowen** [comment]
Agreed. Closing.
