### ISSUE TITLE
Be able to pass ANC Group Number into CHW SMS (for pregnancies with LMP)

### ISSUE THREAD

**Issue by jillrshah** [medic/medic-webapp#3270]
As discussed with @marc, it would be helpful to pass the ANC Group Number into contextualized SMS to CHW. Might only make sense to do for pregnancies where LMP != null.

**Comment by sglangevin** [comment]
@abbyad or @jillrshah can you add some additional detail to this ticket? I don't understand what the request is.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
I'm not sure what this ticket is either. I'm wondering actually if it was opened by mistake, and should be an internal ticket? I'm going to close this: @jillrshah / @abbyad if we want to re-open it we can, it's just really not clear what it's for.

_(Also, @jillrshah it's @abbyad not @+marc, that would be someone else)_
