### ISSUE TITLE
sms-gateway should mark scheduled tasks which are missing uuid as failed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3271]
ref https://github.com/medic/medic-projects/issues/1645#issuecomment-288587948

**Comment by alxndrsn** [comment]
DIFFICULT to implement, as `messageUtils.updateMessage()` identifies the message using... it's ID!

I guess we don't need to fix this if we promise never to have another message without a `uuid` field...

**Comment by alxndrsn** [comment]
@garethbowen any thoughts?

**Comment by garethbowen** [comment]
Sounds good to me.
