### ISSUE TITLE
New District form can no longer be opened after being cancelled

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3280]
Steps to recreate:

1. browse to http://localhost:5988/medic/_design/medic/_rewrite/#/contacts/
2. click _New district_ in action bar
2. observe that the form loads as expected
3. click _Cancel_ or FBB and confirm
4. click _New district_ in action bar
2. observe that the form does not load

**Comment by alxndrsn** [comment]
@garethbowen introduced by the new Cancel button (#1984)?

**Comment by garethbowen** [comment]
This works for me. @alxndrsn Do you have any more details? Were you logged in as admin or restricted user? Any console output? Any UI update at all? Does it happen with other contact forms or just district? What about when cancelling out of reports?

**Comment by alxndrsn** [comment]
Can't recreate.
