### ISSUE TITLE
Relative times are not translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3282]
We are translating dates that are explicitly translated like `today` and `yesterday` but not relative dates, as seen in list of reports and contact summary.

![image](https://cloud.githubusercontent.com/assets/789512/24323219/f394586e-1148-11e7-8d58-b22b745a3447.png)

![image](https://cloud.githubusercontent.com/assets/789512/24323169/3b30654c-1148-11e7-8753-18a3d9fd8c34.png)

**Comment by garethbowen** [comment]
Added additional moment locales: id, hi, sw

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by abbyad** [comment]
Looks great, moving to Ready.
![image](https://cloud.githubusercontent.com/assets/789512/24532454/af57a404-158e-11e7-9c09-4fccead7fbcb.png)

**Comment by alxndrsn** [comment]
Looks like that's a Greogrian date written in Nepali; @bishwas-medic is my reading correct, and if so is this date format helpful?  We could reasonably easily be converting these to BS dates, but perhaps that's for another ticket.

**Comment by bishwas-medic** [comment]
@alxndrsn Those are Gregorian dates written in Hindi. I think this was for a standard project in India. They follow the Gregorian calendar there, so no need of BS dates.

**Comment by alxndrsn** [comment]
Silly me!  How could I get Nepali and Hindi confused o_O
