### ISSUE TITLE
Schedule titles are not translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3283]
The label shown for schedule titles are taken directly from the report doc, and correspond to `app_settings.schedules.name` for which we cannot translate:

![image](https://cloud.githubusercontent.com/assets/789512/24323434/7cdfdfe2-114b-11e7-87f7-ea2ef9d29089.png)

Since the schedule names are used to identify the schedule in app settings, it seems as though we'll have to keep the `name` property and add a `translation_key` property for each schedule. I tested with it following the format of other translation keys with no luck.

Marking as a bug from the user perspective and, unlike https://github.com/medic/medic-webapp/issues/3190, there is no other way to translate these labels.

Initially reported by @shreyakb

**Comment by garethbowen** [comment]
Code review please @SCdF : https://github.com/medic/medic-webapp/pull/3291 and https://github.com/medic/medic-sentinel/pull/123

**Comment by SCdF** [comment]
LGTM, merged.

**Comment by abbyad** [comment]
Works great! Moved to Ready.

Helpful hint:
> The group number can be accessed in the translation value as `{{group}}`


![image](https://cloud.githubusercontent.com/assets/789512/24532888/eb1b18b0-1591-11e7-835e-b6789a9d49eb.png)


Otherwise you end up with a series of same title for each group


![image](https://cloud.githubusercontent.com/assets/789512/24532843/88a102f8-1591-11e7-8038-dc8d00485a81.png)
