### ISSUE TITLE
Gateway stops polling sometimes

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3285]
Seen on sindhuli. No gateway logs, and no api logs :(

Maybe because of lack of activity? The project is not started yet so there were no messages to send/receive.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by estellecomment** [comment]
Can't really do anything without logs. Closing.
