### ISSUE TITLE
Invalid and existing phone number have same error message

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3286]
When entering a phone number when creating a contacts, you will get the error "Invalid phone number" for invalid number or for existing number, and you can't know which is which. 
Add a separate "Number already exists" message.

**Comment by sglangevin** [comment]
@estellecomment this issue has been filed and closed a few times. Enketo limits us to one error message per field, so we have to put in an error message that encompasses all potential errors. This can already be configured within all contact forms. If we want to file a feature request to add the option to include more than one error message in an Enketo form, we should do so.

**Comment by alxndrsn** [comment]
Closing as per @sglangevin comment.
