### ISSUE TITLE
Write an e2e test for Enketo

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3288]
Write an e2e test to fill in a simple Enketo report and ensure it renders as expected. The purpose of this is to ensure we integrate with Enketo correctly and don't regress.

**Comment by garethbowen** [comment]
This works locally but fails in travis, probably because of #3354

**Comment by garethbowen** [comment]
Code review please @SCdF 

I made a change to utils to be more strict WRT error reporting which broke a bunch of tests so please check that my fixes make sense.

**Comment by SCdF** [comment]
Back to you @garethbowen
