### ISSUE TITLE
Document supported software

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3292]
We have a complicated array of software in our stack and not all pieces are compatible with all others. Document which versions of the app depend on what, including:

* node (sentinel in 2.10 introduces a hard dependency on 5 or 6)
* couchdb (v1 for now, v2 soon?)
* browsers (firefox & chrome only, chrome 30+, chrome latest soon?)
* sms-sync (< 0.4 only)
* medic-transport (2.x + only)
* android (4.4+)
* medic-android (any version now, crosswalk and above soon?)

Consider introducing a node version check in api so we fail early, rather than only in sentinel where we may not realise it's failed for a while.

**Comment by SCdF** [comment]
> Consider introducing a node version check in api so we fail early, rather than only in sentinel where we may not realise it's failed for a while.

I have a version check in API in an existing PR, so that should be in master soon. Same code as Sentinel, helpfully copy pasted (if we merge repos we can make that nicer)

**Comment by garethbowen** [comment]
Documentation review please @SCdF

**Comment by SCdF** [comment]
Merged.
