### ISSUE TITLE
Migrate the `meta` doc to have a predictable id

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3294]
Currently info about our app such as "which migrations have been run" are stored in the `medic` db against a doc with a UUID.  This doc should have a predictable `_id` value such as `meta`.

We'd have to write a migration to fix this, which could get interesting!

**Comment by garethbowen** [comment]
It's ok for this to be a migration but the api code that finds the doc will have to look for the ID and then fall back to looking by type as it does now. This way migrations will work before and after this migration has run. It's a bit annoying to have to have the fallback code indefinitely but I can't see any way around that.

**Comment by alxndrsn** [comment]
> indefinitely

We can delete when we're confident every live instance has migrated.

**Comment by garethbowen** [comment]
Code review please @alxndrsn
