### ISSUE TITLE
Barefoot instance - Analytics tab Hindi text is not aligning properly 

### ISSUE THREAD

**Issue by shreyakb** [medic/medic-webapp#3297]
Instance: barefoot.app.medicmobile.org

(Standard ANC)

In Hindi Analytics, the format is slightly off (the top part of all hindi text like the dots and accents have gotten chopped off).

For example, "Active Pregnancies" should appear as "मौजूदा गर्भावस्था" but the accents on top can't be seen.

![image](https://cloud.githubusercontent.com/assets/7915295/24358050/6bc54afc-131d-11e7-80b8-c7882d6eb0e1.png)

**Comment by garethbowen** [comment]
This doesn't happen on my machine but I can see what's happening - if the font is slightly too large for whatever reason the overflow is hidden. I'll make this more tolerant.

**Comment by garethbowen** [comment]
Code review please @estellecomment

**Comment by estellecomment** [comment]
Merged

**Comment by abbyad** [comment]
This has been tested by @Anandpriyadeo, and (re)opened [here](https://github.com/medic/medic-projects/issues/1760) ...but it looks like it is because it was not included in 2.10.3.

**Comment by abbyad** [comment]
@shreyakb can you please test this and report back here?

**Comment by shreyakb** [comment]
Top accents/dots are still cut off on barefoot.app.medicmobile.org (FWIW, its fixed and looks good in the clone instance - screenshots below) @abbyad :

Barefoot:
![image](https://cloud.githubusercontent.com/assets/7915295/24784717/177866c0-1b72-11e7-9d15-ac3161c66265.png)



Clone:
![image](https://cloud.githubusercontent.com/assets/7915295/24784711/08d3b8c2-1b72-11e7-9b0f-6c183163ee84.png)

**Comment by abbyad** [comment]
Thanks @shreyakb, moving this issue to Ready.
