### ISSUE TITLE
Enketo throwing errors when displaying forms

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3301]
On both admin and restricter user. 
All forms I've tried failed, but not with the same error.

Creating a district_hospital does : 
![image](https://cloud.githubusercontent.com/assets/911434/24396481/17b2678c-13c3-11e7-9e42-d833464fa6a3.png)

After that, any creating of district_hospital or health_center will do : 
![image](https://cloud.githubusercontent.com/assets/911434/24396518/353283a0-13c3-11e7-8fb8-e7e63c8a33d0.png)
(district_hospital and health_center use the default creation form)
Once you reload, when you retry you get the first error again (something different is happening on the first try after reload)

Creating a clinic : 
![image](https://cloud.githubusercontent.com/assets/911434/24396773/1ee58416-13c4-11e7-9407-b25f2653893c.png)
Retries give the same error.
Custom create form : [clinic_create.xml.txt](https://github.com/medic/medic-webapp/files/875046/clinic_create.xml.txt)

Same error for the CHP visit form from a `clinic`. 

I've tracked clinics/CHP visit one and it's `dbobjectwidget` that can't be initialized, though I don't know what's wrong with it :
`enketo-core/src/js/widgets-controller.js`
![image](https://cloud.githubusercontent.com/assets/911434/24396400/cbc5e740-13c2-11e7-9559-a123c8415b4a.png)

**Comment by estellecomment** [comment]
I get it on a fresh install.

Reproduce : 
 - git clone webapp, npm install
 - new medic db
 - grunt dev latest code
 - upload app_settings : I used standard : medic-projects/default-sms-workflow/standard/upload_all.sh, l.66
 - log is as admin
 - click add place button : form fail.

**Comment by alxndrsn** [comment]
Caused by https://github.com/medic/medic-webapp/issues/3311

**Comment by estellecomment** [comment]
:yay: Winner!!
Thanks!

**Comment by abbyad** [comment]
Wasn't able to reproduce with 2.11.0-beta, so moving to Ready.
