### ISSUE TITLE
Release 2.10.3

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3304]
Follow [the instructions](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#webapp)

Issues to include:

- [x] #3281 (if ready in time)
- [x] #3282 
- [x] #3283 
- [x] https://github.com/medic/medic-projects/issues/1624
- [x] Update Hindi translations (export from POE)

Release must be done before COB (PDT) on Friday, March 31st. Ideally we would wait as long as we can to try and get #3281 in. If that will not be done in time, we should proceed with the release, omitting that issue for now.

**Comment by garethbowen** [comment]
Project: https://github.com/medic/medic-webapp/projects/4
