### ISSUE TITLE
Corrupted translation strings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3305]
Of the 850 translations in 2.10, two Hindi labels were corrupted on one instance. These translation labels seem OK in github, and on another instance with the same version installed. The two translations in question were not locally modified, but others were. This is somewhat similar symptom to #2906 but perhaps different cause.

## English
`reports.none.n.months = {MONTHS, plural, one{No reports in the last month.} other{No reports in the last \# months.}}`

## Hindi 
In Github [file](https://github.com/medic/medic-webapp/blob/7eea04d27b8242612fcaee17ab30c9bffd98eaee/translations/messages-hi.properties#L740)
`reports.none.n.months = {MONTHS, plural, one{पिछले महीने की कोई रिपोर्ट नहीं है.} other{पिछले \# महीनों में कोई रिपोर्ट नहीं है.}} `

In webapp:
`reports.none.n.months = {MONTHS, plural, one{पिछले महीने की कोई रिपोर्ट नह���ं है.} other{पिछले # महीनों में कोई रिपोर������ ���ह�������������ं है.}}`

also:
`messages.schedule.postnatal.day_0_overdue = क्या {{patient_name}} {{patient_id}} अपने गर्भावस्था के ब���थ�� की दिन-0 जांत�淚�� के लिए आये? हमें बताए 'V {{patient_id}}' भेज कर | धन्यव���द !`

**Comment by abbyad** [comment]
The first corruption happened between these two revs:

[rev2](/_couch/_utils/document.html?medic/messages-hi@2-210e94776672f1f8c6e09916cd623f52): `{MONTHS, plural, one{पिछले महीने की कोई रिपोर्ट नहीं है.} other{पिछले # महीनों में कोई रिपोर्ट नहीं है.}} `

[rev3](/_couch/_utils/document.html?medic/messages-hi@3-027c59b8eda7cea1cf8fc8d59c9ec961): `{MONTHS, plural, one{पिछले महीने की कोई रिपोर्ट नह���ं है.} other{पिछले # महीनों में कोई रिपोर्ट नहीं है.}} `

Further revs just corrupted it further

**Comment by garethbowen** [comment]
I wonder if something is splitting the characters based on a packet boundary or something...

@abbyad do you know what happened when rev3 was saved? Was someone updating translations, or updating the app?

> The two translations in question were not locally modified, but others were.

How were they being modified? Through the app, or via Dashboard, or through a script, or something else?

**Comment by abbyad** [comment]
Not sure, but trying to put `{MONTHS, plural, one{पिछले महीने की कोई रिपोर्ट नहीं है.} other{पिछले \# महीनों में कोई रिपोर्ट नहीं है.}} ` into the configuration page and it corrupts immediately.

**Comment by garethbowen** [comment]
My guess is it's a bug in the way api combines the streaming request body.

**Comment by garethbowen** [comment]
The workaround is to edit the translation file directly in couch.

**Comment by abbyad** [comment]
I didn't have a surefire way to reproduce before, but after best effort I could not reproduce in 2.10.3-beta.2. Moving to Ready.
