### ISSUE TITLE
In person profiles SMS reports do not show name in summary

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3309]
Summary info is missing from reports in person profiles. This is similar to #3084, but in patient profiles instead of place profiles.

### Person's profile is missing the summary
![image](https://cloud.githubusercontent.com/assets/789512/24433712/789e9efa-13f8-11e7-8f0e-a62eb33baea5.png)

### Summary shows when looking at same reports in their parent's place
![image](https://cloud.githubusercontent.com/assets/789512/24433698/62d18696-13f8-11e7-98a7-aff1ca52ef80.png)

**Comment by abbyad** [comment]
This may be a quick fix given the work already done for https://github.com/medic/medic-webapp/issues/3084. If so it would be good to have this in 2.10.3, but not as high priority as the other blocking bugs marked `Priority`.

**Comment by sglangevin** [comment]
Marked as priority to see if we can get to this before the end of the week.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Merged.

**Comment by abbyad** [comment]
Example from original post shows up well now, moving to Ready.
