### ISSUE TITLE
`pyxform` doesn't respect spacing after reference at the beginning of label

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3324]
If a label starts with a `${value}` the space that follows it is not respected.

A label such as `${input} <-- Test without preceding text, **space is ignored**` has the space ignored after ${input}. The spacing is fine if there is text prior to `${input}`.

This can be seen with this [form](https://github.com/medic/medic-webapp/files/883769/issue-3324.xlsx), resulting in the following XForm snippet.
```
    <input ref="/issue-3324/note1">
      <label><output value=" /issue-3324/input "/>&lt;-- Test without preceding text, **space is ignored**</label></input>
    <input ref="/issue-3324/note2">
      <label>.<output value=" /issue-3324/input "/> &lt;-- Test with preceding text, spacing is correct</label>
    </input>
```

Filing here for now since https://github.com/SEL-Columbia/pyxform/issues hasn't had activity in over two years.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
Still relevant but not high priority.

**Comment by abbyad** [comment]
@alxndrsn is this resolved by your latest work in pyxform?

**Comment by alxndrsn** [comment]
Should be!

**Comment by alxndrsn** [comment]
Fixed in medic-conf 1.5.0

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by abbyad** [comment]
Confirmed using the XLSForm from the original post and medic-conf v1.5.6
