### ISSUE TITLE
Use enketo xml cache for contact forms too

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3325]
We have an xml cache which greatly improves rendering time for forms but we don't use it for contact forms. Use it!

**Comment by garethbowen** [comment]
As part of this, refactor to increase reuse between `Enketo.render` and `Enketo.renderFromXmlString`

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

Mostly minor refactoring but the big thing is when rendering a non-generated contact form we use `Enketo.render` instead of `Enketo.renderFromXmlString` which means it gets translated and cached just like report forms.

**Comment by alxndrsn** [comment]
I can't work out if media loading will now be broken.  If you've checked it already then these changes are probably good; if not, then worth some thought.

**Comment by garethbowen** [comment]
My reply is in the PR. Thanks!

**Comment by garethbowen** [comment]
For AT: check that rendering enketo forms works as expected for creating and editing, on the tasks, reports, and contacts tabs.
