### ISSUE TITLE
Date picker widget is not translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3327]
![image](https://cloud.githubusercontent.com/assets/789512/24532313/8bc57044-158d-11e7-85dd-34dc2df54502.png)

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by SCdF** [comment]
@abbyad I presume this is still a problem?

Is this something that is causing deployments problems? Should this be something that we look at fixing in the next minor release (2.15 / 3.1?)

**Comment by abbyad** [comment]
Still a problem. I'll let @sglangevin decide on priority.

**Comment by SCdF** [comment]
@sglangevin if you want to chuck this into a project now is the time! :-)

**Comment by sglangevin** [comment]
How much effort is this one - minimal? If so, I'll add it to one of our near-term releases.

**Comment by kennsippell** [comment]
Started looking at this issue today. But I also found related issue #2272, which might suggest a broader experience change for this date picker. I am all ears if any of you design folk have concrete plans for the date picker! Otherwise, I'll just localise the existing experience. @sglangevin @diannakane

**Comment by diannakane** [comment]
@garethbowen what is needed here? cc: @amandacilek

**Comment by garethbowen** [comment]
@diannakane Do you have any suggestions to make the Enketo widget better, or are you happy for it to be translated as is for now?

**Comment by diannakane** [comment]
@garethbowen it looks like the issue itself is only about translation, but usability of date pickers has come up time and again. In one design issue, the feedback is: "Some phones' native interfaces for entering date of birth are tedious. Are there better options?"

@amandacilek would you like to take a look at this? If we want to make more significant improvements to this, we'll probably want to open a separate ticket, but it sounds like there's an opportunity to make the current experience at least a bit better.

**Comment by amandacilek** [comment]
I'll add this to my list for future work. In the meantime it looks like this particular ticket is in AT already, and the translation alone would definitely improve things in the interim, so no need to hold up this ticket. Thanks for flagging me!

**Comment by ngaruko** [comment]
Fixed in #4832 . I guess we can close this ticket and open a different one for the UX part of the date picker, if not yet open @diannakane @amandacilek
