### ISSUE TITLE
`.hidden_fields: []` property on data_record is weird

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3329]
What is this for?  You can see examples on cic-guatemalav2.app.

**Comment by sglangevin** [comment]
Is that different from `hidden_fields`? We have a place to list the fields that should be hidden from view in Reports/History.

**Comment by browndav** [comment]
Assuming we're not proposing a specific change or thinking this is a bug, Answerhub may be an ideal place for these sorts of questions.

**Comment by mandric** [comment]
Sorry @sglangevin that's what I meant!  Fixing...

**Comment by mandric** [comment]
@browndav if it has to do with defining our records schema I'd prefer we discuss it in github.

**Comment by sglangevin** [comment]
Yeah, that was a workaround to allow us to hide certain fields from the user's view in Reports/History so we don't see a laundry list of form fields there. You set those by setting the appearance to hidden for a field or group in the XML form.
