### ISSUE TITLE
Set user-agent header in Medic Collect

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3334]
`medic-collect` does not currently set the `User-Agent` header in HTTP requests made to servers.  This issue has recently been fixed upstream (https://github.com/opendatakit/collect/issues/167), and we should backport this fix into our builds of Collect.

Support should also be added in [`medic-api`'s `is-client-human` tester](https://github.com/medic/medic-api/blob/master/is-client-human.js)

**Comment by alxndrsn** [comment]
Open pull requests against medic-api and medic-collect; blocked by https://github.com/medic/medic-api/pull/134

**Comment by alxndrsn** [comment]
Cross-platform multilinguistic review, please!  @garethbowen I think the JS code should be fairly obvious after your review of #3118; @abbyad you're the collect maestro.

**Comment by garethbowen** [comment]
LGTM
