### ISSUE TITLE
Localization for Hindi using European numerals

### ISSUE THREAD

**Issue by shreyakb** [medic/medic-webapp#3335]
Hindi users need to see all numbers and dates in regular European/Western Arabic numerals (not in Devanagari).

![image](https://cloud.githubusercontent.com/assets/7915295/24618701/908ef4e4-18b5-11e7-92bc-f77e2bda0d1d.png)

**Comment by alxndrsn** [comment]
As far as I can tell, this is only happening for numbers within dates.

**Comment by sglangevin** [comment]
Yes, this is a request to have the numbers within dates in Arabic numerals, not Devanagari.

**Comment by abbyad** [comment]
That is correct @alxndrsn. I have explained in a bit more detail in #3336. 

Can we tell momentjs to use a specific numeral system? For instance instead of passing `hi` we pass `hi-u-nu-latn`?  ([reference](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat))

**Comment by garethbowen** [comment]
LGTM, thanks @alxndrsn .

**Comment by abbyad** [comment]
Seems to work well for numbers across the app, except for labels like this one:
```
reports.none.n.months = {WEEKS, plural, one{अगले सप्ताह में कोई कार्य नहीं है.} other{अगले # सप्ताहों में कोई कार्य नहीं है.}}
```

![image](https://cloud.githubusercontent.com/assets/789512/24766600/f4c61eae-1ac9-11e7-9bb7-cb7a0f1f354b.png)

If this is an unrelated problem I can open a new issue.

**Comment by abbyad** [comment]
This is a translation issue as that label should be `MONTHS`.

**Comment by abbyad** [comment]
This seems to work well. Will get our Hindi readers to test as well before moving to ready. cc @shreyakb

**Comment by shreyakb** [comment]
Looks good in 2.11.0 on the clone instance @abbyad 

Clone:
![image](https://cloud.githubusercontent.com/assets/7915295/24784962/c4c9563a-1b73-11e7-9481-df5865f00cf5.png)

Barefoot:
![image](https://cloud.githubusercontent.com/assets/7915295/24784884/3c3f6c0a-1b73-11e7-9442-53b709ccf0a2.png)

**Comment by abbyad** [comment]
Thanks @shreyakb, moving to Ready.
