### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3341]
Now that 2.11.0 has been branched we can bump the npm dependencies of webapp, api, and sentinel.

**Comment by alxndrsn** [comment]
Not so simple!!

* https://travis-ci.org/medic/medic-webapp/jobs/223508220
* https://travis-ci.org/medic/medic-webapp/jobs/223508079
* https://travis-ci.org/medic/medic-webapp/jobs/223508221
* https://travis-ci.org/medic/medic-webapp/jobs/223508080

**Comment by garethbowen** [comment]
Review please @alxndrsn 
API: https://github.com/medic/medic-api/pull/154
Webapp: https://github.com/medic/medic-webapp/pull/3489

Nothing in sentinel was outdated.

I hit a problem with protractor so I left it outdated and spawned this issue: #3490

Everything else should work.

**Comment by alxndrsn** [comment]
All looks fine to me.  Shame we're still stuck on Firefox 45 :~\
