### ISSUE TITLE
Confirm logout in CouchDB 2.0, in medic-os, works properly

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3343]
Locally, I did the following:
 - Boot CouchDB 2.0
 - Close the Fauxton login page that automatically starts (on MacOS at least) without logging in to it
 - Opened Medic, logged in as admin, then clicked logout

What followed was a constant loop between `GET _session` and `DELETE _session`. It looked like this code: https://github.com/medic/medic-webapp/blob/master/packages/session/session.js#L137-L157 was constantly being called and infinitely looping. It's hard to tell exactly why.

I managed to fix it locally by logging into the fauton interface. I could not get this situation back, even by restarting CouchDB.

**Work out if this happens in real life. Logging out should work properly.** It may be a real issue / difference between 1.x and 2.0, or it may have been an oddity of my local environment.

**Comment by nice-snek** [comment]
hi frand @abbyad, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
I can't reproduce this. The session management code got overhauled when kanso was removed so it's possible this bug was fixed. My first thought is it might have something to do with the `require_valid_user` config option which if false (which is the default) means calls to `_session` return 200 rather than 401. However in api and webapp we check the `userCtx.name` not just the response status so it should work fine. Furthermore in medic-os this gets set to `true` so it won't be affected.

I think we should modify API to check `require_valid_user` on startup, just like we check for admin party mode, to protect PHI and also to avoid issues like this in the future.

**Comment by garethbowen** [comment]
Actually the current admin party check also checks for `require_valid_user` by making a request with no credentials and expecting a 401 so no work needed.

I'm going to set this for AT to get another pair of eyes on it and we can reopen it if it happens again.

**Comment by browndav** [comment]
This should be set as part of the Docker image bootstrap process, but having a failsafe sounds like a great idea.

**Comment by browndav** [comment]
This should be auto-configured as part of the Docker image bootstrap process, but I can't argue with having failsafes. +1.

**Comment by garethbowen** [comment]
Yeah. The big concern for me would be if someone accidentally unconfigured it after bootstrap.

**Comment by ngaruko** [comment]
Just checking @garethbowen 
>I'm going to set this for AT to get another pair of eyes on it and we can reopen it if it happens again.
Did you want this to be tested on a local install or are there ways to test on test instances/docker ?

**Comment by garethbowen** [comment]
@ngaruko Definitely test on a docker instance... 

1. Set `require_valid_user` couchdb configuration option to false
2. Restart API and make sure it fails to start with a useful error

**Comment by ngaruko** [comment]
Set `require_valid_user` couchdb configuration option to `false` and upgraded instance (`alpha`). Results - see screenshots — no error in UI — alpha.dev now error (`502`). Is this expected @devs @gareth ?
![image](https://user-images.githubusercontent.com/6979995/41758826-3a6b572c-763f-11e8-979e-fc855bd06bad.png).

**Comment by garethbowen** [comment]
@ngaruko Did you read the comment above?

> Restart API and make sure it fails to start with a useful error

That's absolutely expected. Reset `require_valid_user` to true and API should magically boot right up.

**Comment by garethbowen** [comment]
The API log says:

```
[2018-06-24 21:08:08] Node Version: 8.9.1 in development mode
Expected a 401 when accessing db without authentication.
Instead we got a 200
Fatal error initialising medic-api
Error: CouchDB security seems to be misconfigured, see: https://github.com/medic/medic-webapp#enabling-a-secure-couchdb
    at ClientRequest.net.get (/srv/software/medic-api/md5-cEDe7MGKZRKN+6oB+9Fl9Q==/server.js:61:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by garethbowen** [comment]
I set it back to `true` and the instance is back up.
