### ISSUE TITLE
Improve Gardner's Log file size for API

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3346]
Here's the current configuration for gardener logging: https://github.com/garden20/gardener/blob/master/lib/logger.js#L56-L57.  
Maximum files of 3 and maximum size of 1MB is very low.  Specifically for Medic API, we've been losing logs because of this.  In one instance the 1MB was getting filled up in 15 minutes.  We should increase the maximum size to the hundreds of MBs.

**Comment by SCdF** [comment]
Or, if possible / easy, just log absolutely everything (ie just standard out) and leave it to the OS to do rotation / zipping / cleaning.

**Comment by SCdF** [comment]
We are getting rid of Gardener, so let's just drop this.
