### ISSUE TITLE
Improve gardener's log rotation

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3347]
Instead of deleting the files, the logs should be compressed and stored for a specific period (e.g. 30 days).  Since it's a text file, the files would not take that much space and it would make sense to keep logs for at least a month.

**Comment by SCdF** [comment]
IMO it should be the OS' job to do this, we should just be able to push to standard out and let linux deal with it

**Comment by browndav** [comment]
This is obsolete, as gardener is being replaced. Closing with no action required.
