### ISSUE TITLE
Create smoke tests for Android app

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3348]
On travis, start the android app in emulator and start webapp.  Run through a/some scenarios, e.g.

1. log in to the app
2. check that the tasks screen is displayed

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by mandric** [comment]
This looks like it should be done at some point, just a low priority.  We mostly do smoke tests using humans and the beta or alpha store?

**Comment by garethbowen** [comment]
I think this should be done as part of a comprehensive test plan but we have no plans to do it in the short or medium term. Closing.
