### ISSUE TITLE
The value from `jr:choice-name()` can be stale (again)

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3352]
Resurgence of https://github.com/medic/medic-webapp/issues/3281 in 2.11 after working in 2.10.3. Tested using the same form as original issue.

**Comment by alxndrsn** [comment]
Tested locally, or on a deployed server?  I _suspect_ this is due to stale `node_modules/` caused by re-use of version numbers in the enketo lib :~(

**Comment by abbyad** [comment]
Tested on a clone of a production server that was upgraded to `2.11.0-beta`. Will DM you the details.

**Comment by alxndrsn** [comment]
Out of date node_modules is still possible.  I will check on the affected instance.

**Comment by abbyad** [comment]
Seen to be working again in 2.11.0-beta.2. Moving to Ready.
