### ISSUE TITLE
Cannot render form in Firefox

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3354]
Rendering any form fails with

```
Error loading form. Exception { message: "", result: 2153775105, name: "", filename: "http://localhost:5988/medic/_design…", lineNumber: 193110, columnNumber: 0, data: null, stack: "require<[418]</</getProcessor/<@htt…" }
```

That line number corresponds to this [XSLT service line](https://github.com/medic/medic-webapp/blob/master/static/js/services/xslt.js#L24):

```
processor.importStylesheet(response.data);
```

**Comment by garethbowen** [comment]
The current [medic-enketo-xslt](https://github.com/medic/enketo-xslt) build is [failing on travis](https://travis-ci.org/medic/enketo-xslt/jobs/216954087) with

```
./scripts/generate-browser-xml Firefox
[generate] Cleaning build/ dir...
[generate] Cleaned.
[generate] Generating XML with enketo-transformer reference implementation...
[generate] Transforming XML in browsers...
[generate] Generating XML in Firefox...
make: *** [generate] Error 1
```

**Comment by garethbowen** [comment]
@alxndrsn Can I hand this one over to you? My best guess is the error in the build is the same as the browser but I can't find a decent error message in either...

**Comment by alxndrsn** [comment]
(Already merged.)

**Comment by garethbowen** [comment]
Works for me!
