### ISSUE TITLE
only show app Update dialogue when specific design doc is changed

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3355]
When I'm doing bulk edits or manual migrations I will temporarily install a view (and a unique design doc) to help manage the data that I need to update.  When I do this the app triggers the app Update dialogue even though I didn't change the design doc the app uses.  The listener should be tweaked to only show the update dialogue when specific doc ID's are changed:
```
['_design/medic', '_design/medic-client']
```

**Comment by garethbowen** [comment]
The client side only prompts to refresh if the doc _id is one of : '_design/medic', '_design/medic-client', 'appcache'. Source: https://github.com/medic/medic-webapp/blob/master/static/js/controllers/inbox.js#L593

The `medic-client` ddoc is automatically updated if the `medic` ddoc is updated. This is done in api to keep the app_settings in sync. Source: https://github.com/medic/medic-api/blob/master/config.js#L140

@mandric I don't know why you're being prompted. Needs more investigation.

**Comment by garethbowen** [comment]
Cannot reproduce.
