### ISSUE TITLE
Add sync status indicator for offline users (mobile and web)

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3357]
Add an indicator to the hamburger menu so that users know when they last synced data and whether or not they have any data that needs to be synced. No specific count of documents is required at this time. More information in design spec here: https://docs.google.com/document/d/1fHrXcZZexM4DiXlEvABsYnM8upHN0IKBxMNkkXj8n8E/edit

Zeplin Files:
https://app.zeplin.io/project.html#pid=57d311edb055084578d006ec&sid=58e423770a9098e50f30e1b2
https://app.zeplin.io/project.html#pid=57d311edb055084578d006ec&sid=58e423780e7731f75cfe8ec8
https://app.zeplin.io/project.html#pid=57d311edb055084578d006ec&sid=58e423778617e25de61d283e

Original design issue: https://github.com/medic/medic-design/issues/48

**Comment by sglangevin** [comment]
This is required for an upcoming deployment and a long-standing feature request from our active deployments.

**Comment by alxndrsn** [comment]
<img width="326" alt="screen shot 2017-04-12 at 18 14 13" src="https://cloud.githubusercontent.com/assets/191496/24967908/dcfe8022-1fab-11e7-913b-ec1c8f50eea7.png">
<img width="322" alt="screen shot 2017-04-12 at 18 14 03" src="https://cloud.githubusercontent.com/assets/191496/24967907/dcfd1ade-1fab-11e7-83d0-dad34fccc366.png">
<img width="324" alt="screen shot 2017-04-12 at 18 27 44" src="https://cloud.githubusercontent.com/assets/191496/24968518/c0f48410-1fad-11e7-8179-08a03915c7ec.png">

**Comment by alxndrsn** [comment]
- [ ] provide service, or method in appropriate controller, to get sync status
  - [ ] last sync time
  - [ ] current status
- [ ] implement status service to report real values
- [ ] add translation values for different statuses
- [ ] configure colours and icons CSS for different statuses

**Comment by alxndrsn** [comment]
```
setInterval(function() { angular.element($('body')).scope().updateSyncStatus() }, 1000);
```

**Comment by alxndrsn** [comment]
This adds a new state not shown in the screenshots - when the last sync time is unknown.

Sync time does not persist between runs of the application - if you restart your phone, "last sync" will appear as _Unknown_.

**Comment by sglangevin** [comment]
Did some quick acceptance testing: "Currently syncing" and "All reports synced" are cut off on all screen sizes.
![image](https://cloud.githubusercontent.com/assets/1286381/25763945/666c7fd0-319a-11e7-9a34-ec55fc63d79a.png)

Returning so that the font size can be changed.

**Comment by sglangevin** [comment]
Back to you @alxndrsn!

**Comment by alxndrsn** [comment]
@sglangevin How about shorter strings?  E.g.

* _Required_
* _Syncing…_
* _Synced_

**Comment by abbyad** [comment]
In the current implementation the icons are clickable which is confusing since clicking does nothing about syncing, just closes the menu.

From the spec:
> The text and icons are informative-only meaning they are not clickable. For this reason, the sync information is separated from the above clickable links as much as possible. The 1px horizontal grey line and the lightly tinted background color help visually set these elements apart from the rest of the drop down menu.
>
> ![image](https://cloud.githubusercontent.com/assets/789512/25772727/f5ab285a-3225-11e7-9de4-75329334a242.png)

**Comment by garethbowen** [comment]
> How about shorter strings?

@alxndrsn We can't really rely on shorter strings due to internationalisation, different devices, and different fonts (not to mention zooming in in the browser). 

* Fix wrapping so the browser makes the best attempt at fitting everything.
* Make the menu wider on mobile (90%?) - there's no reason for it to be so skinny.
* Fix the hover so it doesn't look clickable (as @abbyad pointed out).

**Comment by sglangevin** [comment]
That makes sense, @garethbowen. @alxndrsn I agree with Gareth on this one so let's go with his suggestions.

**Comment by alxndrsn** [comment]
@sglangevin I agree that Marc's change and Gareth's should be done.   Would the proposed text changes also be beneficial?

**Comment by sglangevin** [comment]
Now I get the question :)

I like the text that we had in the designs and would stick with that unless @diannakane or @amandacilek have other suggestions.

**Comment by sglangevin** [comment]
@alxndrsn sounds like we should stick with the text in the designs for now so I think we can proceed with the changes agreed upon above.

**Comment by alxndrsn** [comment]
- [ ] wrap menu item text
- [ ] make menu wider on small screens (without it looking rubbish)
- [ ] remove hover effects (this already does not affect mobile users)

**Comment by sglangevin** [comment]
Looks good! Moving to Ready.
