### ISSUE TITLE
can_logout permission no longer works as expected

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3358]
Seen on v2.10.3. Restricted users were given the `can_logout` permission but they cannot access the logout button from the Android container. Using container version 0.2.3. Not sure if this is a web app issue or an Android container issue (cc @alxndrsn)

**Comment by alxndrsn** [comment]
Is the logout option available for the same user when accessing via web?

**Comment by sglangevin** [comment]
It was always available when accessing via web - we weren't able to block it there.

**Comment by garethbowen** [comment]
As far as I can tell `can_logout` is never used, instead we detect whether the user is on android or in the webapp.

Related: #1714

**Comment by sglangevin** [comment]
It's possible that it was because I was using the unbranded Medic Mobile app and not a partner-branded app, but I'm not sure. We'll probably need to fix this before LG upgrades to v2.10+, otherwise all CHPs will be able to log out.

**Comment by garethbowen** [comment]
> all CHPs will be able to log out.

I don't think so. My understanding (and the description of this issue) is that nobody in android can ever log out. This was done for LG and I'm fairly sure hasn't regressed. This issue is about allowing some users on android to log out via a permission.

**Comment by sglangevin** [comment]
Right, sorry, got distracted from the issue at hand.

**Comment by sglangevin** [comment]
I'm going to close this issue and open a new one for allowing users on Android to log out if they have permission to do so.
