### ISSUE TITLE
Futon privilege escalation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3360]
Shadow ticket for https://github.com/medic/medic-projects/issues/1807

**Comment by browndav** [comment]
Proposal from call: block access to Futon entirely, and provide simple SSH tunneling instructions for Tech Leads and Developers (e.g. `-L5984:localhost:5984`). Does anyone disagree with this approach?

**Comment by alxndrsn** [comment]
Please proceed with proposed approach immediately.

**Comment by henokgetachew** [comment]
@browndav: PR submitted.

**Comment by garethbowen** [comment]
This has been reviewed by Dave - setting labels correctly.

For AT: make sure the patch is included in your medic-os, then test that

1. you cannot access futon or dashboard through nginx
2. you can access futon or dashboard using a tunnel
3. creating users in the app still works
4. updating configuration in the app still works
