### ISSUE TITLE
The `update_notifications` transition is not working as expected

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3362]
Reported in https://github.com/medic/medic-projects/issues/1813, the `ON` and `OFF` forms are not getting auto responses, nor are they muting/unmuting schedules.

I was hoping this was a simple config issue but was not able to find the source of the problem. I have put further notes in the original issue.

**Comment by garethbowen** [comment]
Related to #3190

**Comment by abbyad** [comment]
This is in fact (partly) a config issue, and medic/medic-projects#1813 can be resolved for the time being by reverting to the older way of defining messages with `message`, not `translation_key`. 

The larger issue of ON/OFF forms not working as expected is still valid, and not fully resolved by #3190.

## Messages appear as deprecated, but are in fact required
![image](https://cloud.githubusercontent.com/assets/789512/24911990/cc525788-1e9a-11e7-97dc-d435ab7728cd.png)

## Report shows as valid when it isn't
If the notifications section is missing the `messages.message` field, or even the whole `messages` object, the transition [detects that](https://github.com/medic/medic-sentinel/blob/ce8e2858f515262ea05a28a62f84a69af7e8ddc0/transitions/update_notifications.js#L28-L32) and [stops processing the form altogether](https://github.com/medic/medic-sentinel/blob/ce8e2858f515262ea05a28a62f84a69af7e8ddc0/transitions/update_notifications.js#L110-L114). As a result, the form:
- does not have any outgoing messages (which is expected since there isn't a message!)
- does not provide any of the validation errors
- does not provide any ID not found errors
- provides no error in Sentinel logs
- provides no error in UI (on the contrary, it shows a valid green circle)
- does not do the mute/unmute action even though it appears as valid

To avoid this we will make sure projects have notifications with `messages` (or `translation_key` after 3190). I am removing the priority label and marking as a bug because although it could be considered a feature request to mute/unmute without messages, it is a UX bug to not do the mute/unmute action while not providing any errors.

**Comment by bishwas-medic** [comment]
@abbyad regarding the validations and ID not found errors not showing up, it is happening even when the `message` object is present: https://github.com/medic/medic-projects/issues/1825

**Comment by abbyad** [comment]
Thanks @bishwas-medic, just tested that and you are right, that is a problem. I will update the comment above to include that as another way the forms don't behave as expected.

**Comment by garethbowen** [comment]
Closing as @abbyad reports it's a configuration issue - details in medic/medic-projects#1813

Reopen if this is incorrect!

**Comment by abbyad** [comment]
Although it can be partly mitigated in configuration, it is problematic to show a notification report as valid when the intended mute/unmute action is not taken. Because of that we should:
1) make necessary change so that reports are completely processed even if outgoing messages are missing
OR
1) document that the notification messages are required in app_settings and config docs

If we chose the latter option we should also consider proper handling when messages are missing (eg reports marked as invalid, and errors in Sentinel logs), or as part of a more comprehensive error handling of the configuration.

**Comment by dianabarsan** [comment]
@garethbowen not yet, I did not change that part of the behavior. Working on it.

**Comment by ngaruko** [comment]
LGTM
