### ISSUE TITLE
Triage script : pick issues by last action date

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3367]
Anything that hasn’t had a comment for X months gets triaged : close if irrelevant, otherwise the triage bot has refreshed date by commenting, so leave it.

**Comment by garethbowen** [comment]
Be sure to limit to `y` issues per user per iteration.

**Comment by estellecomment** [comment]
@SCdF can you review?

**Comment by SCdF** [comment]
@estellecomment back to you. I've recommended some changes, and I've closed it because I've forked the code into medic, where it should live now we're making changes for medic (and it's no longer some dinky thing I did in my spare time): https://github.com/medic/github-issue-roulette

**Comment by estellecomment** [comment]
Thanks for the cleanup! Merging in the medic repo.
