### ISSUE TITLE
The `sys.missing_fields` label is not being translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3368]
The export of the translations shows `sys.missing_fields = Missing or invalid fields: {{fields}}.` yet the app shows `sys.missing_fields`:
![image](https://cloud.githubusercontent.com/assets/789512/24929458/f844d9c2-1ed3-11e7-9546-cd870fc91a2f.png)

Tested on 2.11.0-beta.2

**Comment by garethbowen** [comment]
@abbyad What's the config? `translation_key` or `messages`? The former is probably not supported yet.

**Comment by garethbowen** [comment]
Actually that comment doesn't make sense. Ignore me.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.
