### ISSUE TITLE
Write e2e test for medic-collect api integration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3370]
We [recently regressed on medic-collect](https://github.com/medic/medic-webapp/issues/3118) by changing the way we do auth. This is easy to do because we don't use medic-collect a lot in development.

Write and e2e test to exercise the medic-collect use case so we don't regress further.

**Comment by alxndrsn** [comment]
Test scenarios:
- [ ] request list of forms
- [ ] request specific form
- [ ] submit a form

**Comment by garethbowen** [comment]
Some changes requested but overall, very nice!
