### ISSUE TITLE
In the create-patient-contacts migration provide a more complete list of potential patient_name locations

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3372]
In `medic-api/migrations/create-patient-contacts.js` at https://github.com/medic/medic-api/blob/master/migrations/create-patient-contacts.js#L105, we have:

```js
            name: registration.fields.patient_name ||
                  registration.fields.full_name,
```

On a very small number of instances waiting for upgrade, `patient_name` is stored outside of `.fields`, causing an `undefined` error when accessing `.fields` that blocks migrations from completing.

After following the advice in the `TODO` comment, I think we have a more appropriate set:

```js
            name: (registration.fields || {}).patient_name ||                 
                  (registration.fields || {}).full_name ||
                  registration.patient_name ||
                  registration.full_name,
```

Add this change and a couple simple unit tests to `medic-api` via a PR.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
LGTM. Merged.

**Comment by garethbowen** [comment]
Reopening so it can be backported.

**Comment by sglangevin** [comment]
I'm going to consider this acceptance tested during the upgrade of Kilifi Kids Kaiti this week. Please shout if that is a bad assumption.
