### ISSUE TITLE
Couch2 may not require a valid user by default

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3387]
https://github.com/medic/medic-projects/issues/1886

**Comment by garethbowen** [comment]
Nobody has picked this up in a while - moving out of the milestone.

**Comment by garethbowen** [comment]
I'm scheduling this for 3.0 because it should be fixed before we release.

**Comment by garethbowen** [comment]
This has been marked for AT in the medic-projects issue so moving to AT here too.

**Comment by ngaruko** [comment]
Tested in [medic-project(#1886](https://github.com/medic/medic-projects/issues/1886)
