### ISSUE TITLE
Favicon doesn't work on dark background

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3389]
<img width="120" alt="screen shot 2017-04-17 at 10 19 33" src="https://cloud.githubusercontent.com/assets/191496/25083452/7708942e-2357-11e7-9a37-54608d22768a.png">

Not sure what the answer to this is; perhaps a lighter outline or shadow?

**Comment by sglangevin** [comment]
@alxndrsn where is this screenshot from? Needs more context.

**Comment by alxndrsn** [comment]
It's from the Chrome bookmarks bar.

**Comment by Lesterng** [comment]
Here is a white favicon. It is a .png need to change to .ico
![favicon-white](https://cloud.githubusercontent.com/assets/5149601/25095894/780d7f10-2352-11e7-81c4-093a0efddb06.png)

**Comment by alxndrsn** [comment]
@Lesterng That one doesn't look like it'll work on a white background:
<img width="160" alt="screen shot 2017-04-17 at 19 59 16" src="https://cloud.githubusercontent.com/assets/191496/25098321/5c9f6c42-23a8-11e7-9dd6-53481983d958.png">
Ideally we need something which is good for both - it's the favicon, so we have no control over what colour background it's displayed against.

**Comment by Lesterng** [comment]
@alxndrsn Try this
![favicon-gray](https://cloud.githubusercontent.com/assets/5149601/25099522/78528f56-2361-11e7-9300-f95da15c53f0.png)

**Comment by alxndrsn** [comment]
In the end I converted one of our PNG icons, as the supplied one is the wrong dimensions.

Here's how the new (left) and old (right) look in Chrome:

Normal:
<img width="540" alt="screen shot 2017-04-19 at 14 42 45" src="https://cloud.githubusercontent.com/assets/191496/25180526/a5af361c-250e-11e7-9536-3afc732f62bf.png">
Incognito:
<img width="532" alt="screen shot 2017-04-19 at 14 42 38" src="https://cloud.githubusercontent.com/assets/191496/25180527/a5b1a64a-250e-11e7-8838-54b5d184e1dc.png">



If we are worried about how we handle `.ico` files, this SO thread is worth a read: https://stackoverflow.com/questions/2268204/favicon-dimensions#23734416.

**Comment by garethbowen** [comment]
How did you generate the ico? How many sizes of icons are included? How does it look when you make a shortcut say on the desktop (IIRC this uses the favicon)? Have you tested on android? Can we just copy the one from medicmobile.org?

I can help with this testing next week when I'm back home if you like.

**Comment by alxndrsn** [comment]
> @alxndrsn How did you generate the ico? How many sizes of icons are included?

It's only 48x48.  I assumed from the name that this was all we were using.  My mistake!

> How does it look when you make a shortcut say on the desktop (IIRC this uses the favicon)?

Pass.  That may or may not come from the PNGs.

> Have you tested on android?

No.

> Can we just copy the one from medicmobile.org?

That favicon has exactly the same problem.

> I can help with this testing next week when I'm back home if you like.

That would be really helpful - I may have time to regenerate tomorrow with 16, 32 and as-big-as-possible; I assume it's reasonable to use the pngs for this.

**Comment by garethbowen** [comment]
> That would be really helpful - I may have time to regenerate tomorrow with 16, 32 and as-big-as-possible; I assume it's reasonable to use the pngs for this.

Yeah don't worry about IE support.

**Comment by alxndrsn** [comment]
> >    I assume it's reasonable to use the pngs for this.
> Yeah don't worry about IE support.

I meant: I assume it's reasonable to use the PNGs for generating the `.ico`.  But I see these can also be generated from an SVG.

Looking at the PNGs vs what I see in Chrome, I suspect the whole favicon declaration is broken.

**Comment by alxndrsn** [comment]
Incumbent `.ico` is only 48x48 too:

https://realfavicongenerator.net/favicon_checker?protocol=https&site=alpha.dev.medicmobile.org


medicomobile.org is slightly worse, but not much different:

https://realfavicongenerator.net/favicon_checker?protocol=http&site=www.medicmobile.org

**Comment by alxndrsn** [comment]
Looks like the new `.ico` has all the problems of the old one, except for the transparent background.  So I guess it's an improvement!

**Comment by ngaruko** [comment]
LGTM

**Comment by Lesterng** [comment]
@alxndrsn Here is a favicon of our logo that will work on multiple backgrounds. You can change the suffix from .png to .ico. If you need another size, let me know the dimensions.
![favicon](https://user-images.githubusercontent.com/5149601/27698855-3024e802-5cad-11e7-96dc-5de4795a8537.png)
