### ISSUE TITLE
Include a couch2pg user in standard configuration by default

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3393]
We currently generate PostgreSQL replicas, and these replicas communicate with instances by using a special CouchDB account. Currently, we're making this account manually. Patch concierge and the user backfilling script to add this account, and then check the script that backfills accounts into `git` so that other people can see/use it.

**Comment by garethbowen** [comment]
Follow-up to medic/medic-projects#1779

**Comment by garethbowen** [comment]
Related: #3151 - these should probably be done at the same time.

**Comment by garethbowen** [comment]
This should be done, but it's not a priority right now. Moving out of the milestone.

**Comment by abbyad** [comment]
@browndav is this now obsolete? Please close if that is the case.

**Comment by browndav** [comment]
This is obsolete in that it's actually complete. Closing, thanks.
