### ISSUE TITLE
The user needs an associated contact to create a contact

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3394]
A recent refactor caused a regression whereby the logged in user must have an associated contact in order to create a contact. This is how filing reports works, so the resultant report can be assigned to the correct person. However there is no need for contacts to be assigned to a person so this is not required. Furthermore it creates a chicken and egg problem where the first user (root admin) cannot create a person because they don't have a contact person assigned.

**Comment by garethbowen** [comment]
Written and reviewed by @ngaruko and I in peer programming.

**Comment by abbyad** [comment]
Just discovered that admins cannot create contacts even with a contact set in 2.11.0. We should test if this is resolved as part of this fix.

**Comment by sglangevin** [comment]
Working well for admin and full access users.

**Comment by sglangevin** [comment]
This is working on v2.11.1-beta.1. Tested on lg.dev using a full_access user with no contact and no place associated.
