### ISSUE TITLE
`/api/v1/messages` returns messages twice

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3400]
`/api/v1/messages` returns each message returned twice. 

That's because the [`tasks_messages` view emits twice per message](https://github.com/medic/medic-webapp/blob/master/lib/views.js#L439), once to emit the message id and once to emit the message state. Which is because we use the view to query messages both by id and by state.

So for an unfiltered query, we return all view results, which outputs everything twice. 

Either 
 - split that view into two different views (are more views a good thing?), or
 - in the endpoint for `/api/v1/messages`, add a query param of `state=[<all the possible states>]` so that only the `emit`s by state are used and the `emit`s by id are ignored.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
As far as I can tell, no production code uses this endpoint.  @garethbowen @bishwas-medic @ngamita are any of you aware of a use for this endpoint?

**Comment by ngamita** [comment]
thought i had seen this in collect but not sure. @henokgetachew have a clue?

**Comment by henokgetachew** [comment]
Thought I had seen it somewhere too but can't find it now after doing a search in medic-projects..

**Comment by bishwas-medic** [comment]
The `/api/v1/forms` endpoint is used for submitting reports through Medic Collect. Haven't used `/api/v1/messages` on any of my projects.

**Comment by ngaruko** [comment]
The `/api/v1/messages ` endpoint has been officially removed [#3971](https://github.com/medic/medic-webapp/issues/3971). So no need to work on this.
