### ISSUE TITLE
Allow users to enter Bikram Sambat dates in Enketo forms in the web app

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3404]
The date widget available in Enketo currently supports only the Gregorian calendar. In order to support facility-based users in our Nepal deployments, nurses using the web app need to be able to enter dates using the Bikram Sambat calendar. Make it possible for Enketo forms to display a widget that allows Bikram Sambat date entry.

cc @ranjuts @bishwas-medic

**Comment by alxndrsn** [comment]
@sglangevin is this for mobile, desktop or both?

**Comment by sglangevin** [comment]
I believe this was requested for desktop, but I'd like us to implement it for both unless @ranjuts confirms that it's not going to be needed for mobile in the future.

**Comment by alxndrsn** [comment]
Probably makes sense to work on as separate tickets.  medic-android and medic-collect can share the bulk of the date picker code, and there will be some smaller overlap between medic-android and medic-webapp, where the enketo widget is defined.

**Comment by sglangevin** [comment]
There is a ticket for medic-collect here: https://github.com/medic/medic-webapp/issues/3405

Let's use that ticket for medic-android and medic-collect and this one for the webapp?

**Comment by alxndrsn** [comment]
Yes, saw that - I think we want 3 tickets, ultimately 😄

**Comment by alxndrsn** [comment]
Should there be a bikram-specific input field type, or should the bikram selecter be displayed instead of the regular date picker for a form displayed in Nepali?

**Comment by ranjuts** [comment]
We would ideally want the latter.

**Comment by alxndrsn** [comment]
@ranjuts when you have a minute it'd be good to go through some ideas for how this could work

**Comment by sglangevin** [comment]
@alxndrsn ok let's use this issue for the webapp. I've created a new issue for Android (#3513) so now we have 3 tickets. I've also changed the title of this issue to reference the web app.

**Comment by sglangevin** [comment]
From @ranjuts:
- Option to enter date in Nepali Date (Bikram Sambat) format : DD/MM/YYYY or pick from calendar (display Bikram Sambat Calendar  in date picker)

**Comment by ranjuts** [comment]
Had a chat w Alex re this and here's the gist. @alxndrsn please add/correct if anything. 

**Best option in terms of LOE + usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display the name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार  if form language is Nepali). 

**Best option in terms of usability:** 3 separate dropdowns for DD, MM (name of month) and YY. Typing the date would be the default option. For month, when typing enter as integer but display name of month in text once done entering (eg: Baisakh, Jetha, Asar etc or बैशाख, जेठ, असार etc if form language is Nepali). 
AND 
Pick from Bikram Sambat Calendar. User has the option to choose.

**Comment by alxndrsn** [comment]
Bootstrap bikram sambat date picker: https://medic.github.io/bikram-sambat/

**Comment by alxndrsn** [comment]
We may want to extend the bootstrap datepicker for bikram sambat.  Relevant source for the fork that we use is at https://github.com/uxsolutions/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js.

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by sglangevin** [comment]
Tested this on 2.13.0-beta.2. The date-picker itself seems to be working well. However, we now have an issue with the form because we are validating for dates that are within the last 42 weeks when we're entering LMP. Is there a way of converting from Bikram Sambat date back to Gregorian date in the form? Without that, I'm not sure how to proceed. I don't know if it's possible to change or remove the validation only for people viewing the form in Nepali.

@alxndrsn any ideas?

**Comment by alxndrsn** [comment]
@sglangevin bikram datepicker is display-level only, so the underlying data format should still be the same as normal.  If validation appears to be affected, please send me the affected form and I will work out what's going on.

**Comment by sglangevin** [comment]
Turns out the Standard forms had a small bug which has now been fixed. Moving this to ready.
