### ISSUE TITLE
Doc for gateway<->api SMS protocol is wrong

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3407]
That's not what the code does.

Discovered when working on #3073 .

**Comment by estellecomment** [comment]
@alxndrsn please review : https://github.com/medic/medic-docs/pull/15

(cc @garethbowen )

**Comment by garethbowen** [comment]
@estellecomment That `forwarded-to-gateway` status in the documentation was added prematurely - that's what I expect you're adding in #3073. Happy for you to remove that but remember to add it back when you're done.

**Comment by estellecomment** [comment]
yup @garethbowen I have a medic-docs PR along with my code changes for #3073.

**Comment by estellecomment** [comment]
Changes already checked in as part of #3073 .
