### ISSUE TITLE
Make it possible for CHWs to receive SMS notifications when a nurse confirms a visit or delivery via SMS

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3412]
Currently, when an SMS report is received, the contact information, including the hierarchy of the person who sent the report, is attached. This allows for sending of auto-replies and schedules to the sender and anyone above them in the hierarchy. This works well when the CHW is sending in all of the reports because they can get scheduled messages.

However, we have many nurses in our projects who are currently sending in SMS reports to confirm visits, but the CHW cannot be informed of the nurse's activity. When the nurse sends in a visit report or delivery report, we should be able to send an SMS to that patient's CHW to inform them that the patient went to the clinic.

Now that we have person-centered workflows (and are creating contact docs for all patients), it would be ideal to be able to access the hierarchy info starting from the patient and going up from there as opposed to starting from the person reporting. One thought is that we could attach the contact doc to the SMS report similar to how it is being done for xforms, though we'd only want to do that for person-centered workflows and not for case-based workflows (which are still being supported on v2).

**Comment by abbyad** [comment]
Just to summarize... we should add to patient's info to the incoming report eg `doc.patient`. This is similar to the way we add the submitter's info as `doc.contact`.

@garethbowen, given the work done as part of #2635, should we be putting the whole patient doc or just a reference to it?

**Comment by garethbowen** [comment]
Definitely just a reference to it. There are utility functions for turning a doc with hierarchy into a reference with hierachy and back to a doc when needed.

**Comment by SCdF** [comment]
> One thought is that we could attach the contact doc to the SMS report similar to how it is being done for xforms, though we'd only want to do that for person-centered workflows and not for case-based workflows (which are still being supported on v2).

How do we determine if we are in a case-based workflow or a person-centered one? Should we just be doing this via a configurable transition, and so configurers make this call?

**Comment by abbyad** [comment]
I think the idea is that if a report has a `patient_id` field, and there is a person with that ID in the DB, then add the contact's UUID to the report doc. We then need some way to hydrate that doc where it is used, such as from SMS replies done with transitions.

**Comment by abbyad** [comment]
Ideally we would access this from `patient_reports.messages` or `registrations.messages`, as shown in this example:
```
      "messages": [
        {
          "translation_key": "messages.v.report_accepted",
          "event_type": "report_accepted",
          "recipient": "reporting_unit"
        },
        {
          "translation_key": "messages.v.report_received_about_your_patient",
          "event_type": "report_accepted",
          "recipient": "parent.contact.phone",
          "bool_expr": "patient.parent.contact._id !== contact._id"
        },
        ...
      ]
```

Note that this example uses a `bool_expr` field which does not yet exist for `messages`, but some equivalent would be needed as part of this user story.

**Comment by SCdF** [comment]
@garethbowen please check out the PR. There is one bit of refactoring I wanted to do, but it was getting complicated enough so let's go for a partial review! Each commit in the PR is probably readable on its own, or you can read them together

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen, on a shiny new PR

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by SCdF** [comment]
Fixed and merged into master

**Comment by sglangevin** [comment]
@ngaruko re-assigning to you for AT.
