### ISSUE TITLE
minor medic-api startup tweaks

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3421]
If we still support CouchDB 1 on medic-api, can we  set a default for `COUCH_NODE_NAME` since it doesn't mean anything?  

Also do we really need an error message for nodejs < 6.10 (e.g. 6.9)?  I also wince at "may not be supported" can we make it supported or not supported?  Can we just have a minimal travis test env run against 6.0.x and latest nodejs?

```
mandric in ~/dev/medic-api on master
$ COUCH_URL=$LOCAL_COUCH/medic node server
Node Version: 6.9.5
This node version may not be supported
Fatal error initialising medic-api At least one required environment variable was not set:
COUCH_NODE_NAME must be set. For example: COUCH_NODE_NAME=couchdb@localhost
```

**Comment by SCdF** [comment]
> If we still support CouchDB 1 on medic-api, can we set a default for COUCH_NODE_NAME since it doesn't mean anything?

Sure, if you can find a default you think is good. I quickly looked and couldn't fine one.

> Can we just have a minimal travis test env run against 6.0.x and latest nodejs?

Sure. I added that notice precisely because we are *not* testing on 6.0.x, but on 6.10.x. If we, as a team, want to agree to lower the version on travis we can definitely do that.

**Comment by SCdF** [comment]
Also, why is this marked scheduled?

**Comment by mandric** [comment]
> Sure, if you can find a default you think is good. I quickly looked and couldn't fine one.

The example works for me. COUCH_NODE_NAME=couchdb@localhost

> Also, why is this marked scheduled?

Because I don't think it belongs in backlog.

**Comment by mandric** [comment]
> Sure. I added that notice precisely because we are not testing on 6.0.x, but on 6.10.x. If we, as a team, want to agree to lower the version on travis we can definitely do that.

I think it makes sense to have a travis config to build to latest node and the supported major version? I think we can probably get away with supporting node 6.0 or 5.0 and above?  

Example .travis.yml config (replace stable with whatever latest version of node):

```
  matrix:  
  - NODE_VERSION=stable COUCH_VERSION=2
  - NODE_VERSION=stable COUCH_VERSION=1
  - NODE_VERSION=6.0.0 COUCH_VERSION=2
  - NODE_VERSION=6.0.0 COUCH_VERSION=1
```

**Comment by SCdF** [comment]
> The example works for me. COUCH_NODE_NAME=couchdb@localhost

Yep that one works for me too but I believe that wasn't the one that @alxndrsn had? I'm sorry I'm not much help, it was awhile ago. Might as well just do it anyway and if it ends up causing issues we can change it later :-)

> I think it makes sense to have a travis config to build to latest node and the supported major version? I think we can probably get away with supporting node 6.0 or 5.0 and above?

Totally. We're trying to cut down on the versions of node we test on because it takes so long, which is why we only have 1. According to http://node.green/ I'd be a bit leary about anything below 6.5, since 6.4 is missing some functions I'm pretty sure we're using. We could always find that code and re-write it, but I don't think continuing to support old versions is that worth it.

**Comment by mandric** [comment]
https://github.com/medic/medic-api/pull/148

**Comment by SCdF** [comment]
LGTM. I've also changed sentinel (since changing just one doesn't make any sense) with the same changes you made and merged it.

**Comment by mandric** [comment]
Thanks!
