### ISSUE TITLE
`i18n` and `utils.translate` are doing the same thing, in sentinel

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3422]
[i18n.js](https://github.com/medic/medic-sentinel/blob/master/i18n.js) is only used in one spot, for reminders. AFAICT it does the same thing as [utils.translate](https://github.com/medic/medic-sentinel/blob/master/lib/utils.js#L415) which is used everywhere else. 

Remove i18n.js.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
@estellecomment is this still needed? Seems like it probably is. Marking as triaged, feel free to change if need be.

**Comment by garethbowen** [comment]
i18n.js has been removed as part of #3627
