### ISSUE TITLE
Stop maintain_info_doc transition from writing sentinel metadata

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3424]
The maintain_info_doc transition does not change the document (it changes its own doc) and so it shouldn't return true to the sentinel transition framework, and so transition metadata shouldn't be written.

**Comment by SCdF** [comment]
Please review @estellecomment : https://github.com/medic/medic-sentinel/pull/130

**Comment by estellecomment** [comment]
cool!
One suggestion for the comment, otherwise go ahead and merge.

**Comment by sglangevin** [comment]
Any tips on how to AT this @SCdF?

**Comment by SCdF** [comment]
@sglangevin basically when you write any document to CouchDB the info document for that doc is created (`id-info`, where `id` is the doc id). This shouldn't also result in the original document getting an entry in the `transitions` property for the `maintain-info-doc` transition.

**Comment by sglangevin** [comment]
Got it. Tested and this is working well. Moving to ready.
