### ISSUE TITLE
Delete or deprecate unused sentinel transitions

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3425]
Currently most projects are being migrated to v2, and when that's done the configs will contain exactly which transitions are used. 

Wait until migration is done, then use [this script](https://github.com/medic/medic-projects/blob/master/scripts/transitions_counter.js) to survey usage, and then delete unused transitions if they exist.

**Comment by garethbowen** [comment]
```json
{
 "update_clinics": 51,
 "registration": 50,
 "accept_patient_reports": 49,
 "generate_patient_id_on_people": 36,
 "default_responses": 50,
 "update_sent_by": 18,
 "update_sent_forms": 28,
 "death_reporting": 1,
 "conditional_alerts": 29,
 "multi_report_alerts": 1,
 "update_notifications": 50,
 "update_scheduled_reports": 19,
 "resolve_pending": 0
}
```

`death_reporting` and `multi_report_alerts` are new so the low usage is expected.

`resolve_pending` is used in testing so it's worth keeping.

There are no unused transitions.
