### ISSUE TITLE
medic-api forms controller should use appropriate protocol

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3427]
From @mandric

In `medic-api`:
> controllers/forms.js:80 should use http or https depending on the request.  We should probably check the `X-Forwarded-Proto` header which can be expected from the ssl proxy/nginx config?
>
>    ```template = 'http://%s/api/v1/forms/{{id}}.xml'.replace('%s', headers.host);```

**Comment by garethbowen** [comment]
AT: Check that the medic-collect APIs work in development (using http) and production (using https). Connect a medic-collect android app to ensure the APIs still work as expected.

**Comment by ngaruko** [comment]
LGTM.
