### ISSUE TITLE
select2 in a repeat group does not work as expected in an Xform

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#3430]
With a select2 in a repeat group, only the first instance allows selection. Subsequent instances are selectable with much difficultly (long clicking the mouse, if at all) and the selected option is reflected on the first instance.

I've attached a stripped down xml to reproduce this issue.

This was tested on v2.11.0
cc @alxndrsn 
[repeat.xml.zip](https://github.com/medic/medic-webapp/files/966021/repeat.xml.zip)

**Comment by sglangevin** [comment]
@alxndrsn assigning to you to see if you can take a look. LG needs this for one of their supervisor forms so I'm wondering if there is a simple fix.

**Comment by SCdF** [comment]
@alxndrsn left some comments on the commit. You didn't make a PR. Don't know if that's intentional.

I don't really get how the code fixes the problem titled in the commit. This may be because I don't understand when destroy gets called.

**Comment by alxndrsn** [comment]
Thanks for the review; lack of PR was unintentional.

> This may be because I don't understand when destroy gets called.

That'll be exactly why you don't understand.  I don't entirely understand either, so clearly I should research a bit more and document it.  The basics is that when a repeated group is requested, all the HTML gets cloned (including listeners), and then all widgets in the cloned HTML get `destroy()`ed and re-`init()`ed.

**Comment by alxndrsn** [comment]
@SCdF updated per your comments.  PR at https://github.com/medic/medic-webapp/pull/3483

**Comment by sglangevin** [comment]
@derickl I've upgraded lg.dev to v2.12.0-beta.2 for testing. Can you test the form you were working on there and confirm that it is now working as expected?

**Comment by derickl** [comment]
@alxndrsn @sglangevin 

Some comments on the issue/fix:

1. The UI implementation when submitting a new forms was fixed
2. On saving, only the last item in the repeat is saved

**Comment by alxndrsn** [comment]
I'm happy for any dev to pick this up.

**Comment by garethbowen** [comment]
It looks like no repeats work for reports, only contacts.

**Comment by garethbowen** [comment]
What we get in XML:

```xml
        <repeat xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" delimiter="#" id="repeat_bug" prefix="J1!repeat_bug!" version="2017-03-28 00:00:00">
          <group_test>
            <other_chps>yes</other_chps>
            <delimiter/>
            
          <chp>
              <other_chp>9134bf920fac08ffa4dc18bf240fed3c</other_chp>
            </chp><chp>
              <other_chp>3f98d501a8fee5efde01a3796696bf78</other_chp>
            </chp>
          </group_test>
          <meta>
            <instanceID>uuid:3849e0b4-593e-4a3f-bc2b-6b6042cf4bc8</instanceID>
          <deprecatedID/></meta>
        </repeat>
```

This is what we convert this to in JSON:

```json
{
   "fields": {
       "group_test": {
           "other_chps": "yes",
           "delimiter": "",
           "chp": {
               "other_chp": "3f98d501a8fee5efde01a3796696bf78"
           }
       },
       "meta": {
           "instanceID": "uuid:3849e0b4-593e-4a3f-bc2b-6b6042cf4bc8",
           "deprecatedID": ""
       }
   }
}
```

There's nothing in the XML that indicates it's a repeating field unless there happen to be more than one item so we need to pass more down to the service that creates the JSON than the XML alone.

**Comment by alxndrsn** [comment]
> we need to pass more down to the service that creates the JSON than the XML alone

Agreed.  The model from the original form would be one option.  In this case:
```xml
        <repeat delimiter="#" id="repeat_bug" prefix="J1!repeat_bug!" version="2017-03-28 00:00:00">
          <group_test>
            <other_chps/>
            <delimiter/>
            <chp jr:template="">
              <other_chp/>
            </chp>
          </group_test>
          <meta>
            <instanceID/>
          </meta>
        </repeat>
```

**Comment by garethbowen** [comment]
@alxndrsn I don't think that gives us enough either. Slightly confusingly the `<repeat>` node in your example is just the name of the instance so it could be anything.

The bit I think we need is in the body of the form definition:

```xml
  <h:body class="pages">
      <group ref="/repeat/group_test/chp">
        <label></label>
        <repeat nodeset="/repeat/group_test/chp">
          <input appearance="db-object" ref="/repeat/group_test/chp/other_chp">
            <label>CHP Name</label>
          </input>
        </repeat>
      </group>
    </group>
  </h:body>
```

While iterating through the XML we check the current elements path to see if we can find a `<repeat nodeset="<path>">`. If that exists it's a repeated element.

**Comment by alxndrsn** [comment]
I think you know from the `jr:template=""` attribute.

**Comment by alxndrsn** [comment]
@garethbowen reportedly pyxform always adds `jr:template` to repeat groups, so we could actually rely on that.  But I'm not sure if the behahviour is documented or not...

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by sglangevin** [comment]
@derickl do you have a place where you can test this on alpha? You could try alpha.dev. It would be great to confirm this is now working well with the original form.

**Comment by derickl** [comment]
@sglangevin submitting my original form on `alpha.dev` yields the same results. Picked 2 CHP's; only the last was saved.

Currently broken on `2.13.0-alpha.6177`. I'll test it on the most current build. @garethbowen

**Comment by derickl** [comment]
@garethbowen - seems to still be broken but in a different way. Closing two CHP's, It saves two instances of the second one. Testing this on `2.13.0-alpha.6254`.

**Comment by garethbowen** [comment]
It looks like it's just the names that are wrong - the chp id is correct and if you edit the report it works as expected. I'll have a look at why the rest of the data is wrong.

**Comment by derickl** [comment]
Editing the report didn't fix it for me.

**Comment by garethbowen** [comment]
Editing won't fix it, it just shows that the IDs are correct. 

![ids-used](https://user-images.githubusercontent.com/2064938/27862607-20563a8e-61da-11e7-8986-12cde4bc5211.png)

I can see the problem and I'll look into it. Thanks.

**Comment by derickl** [comment]
Choice! (Stefan gave a lesson)

**Comment by garethbowen** [comment]
Code review please @SCdF - just do this one https://github.com/medic/medic-webapp/pull/3617 as the others have been reviewed already.

**Comment by SCdF** [comment]
LGTM, merged.

**Comment by sglangevin** [comment]
@derickl - you up for another try with AT? This change is now in alpha.

**Comment by derickl** [comment]
@sglangevin AT was in progress before alpha.dev went down

**Comment by sglangevin** [comment]
Yep - I saw that. Thanks for noting that here.

**Comment by ngaruko** [comment]
Are you able to give it another go now that alpha.dev is 'up' again @derickl ?

**Comment by derickl** [comment]
@sglangevin @sglangevin Looks good to me in terms of saving and reloading the form.

@garethbowen: I tried looping through the items selected in the repeat group but it just does not work: using indexed-repeat or concating the nodeset. Curious if this has been attempted before.

**Comment by derickl** [comment]
I can raise a separate issue if deemed necessary.

**Comment by sglangevin** [comment]
@derickl can you explain in more detail what it is that you are trying to do? It's unclear whether it's the same issue or a new one.

**Comment by derickl** [comment]
@sglangevin I wanted to loop through the items created in the repeat and list them on the summary page

**Comment by sglangevin** [comment]
@derickl you probably can't loop through but you can access values from each repeat group if you use the correct xpath. What is the maximum number of people that a manager can input? If you know that, you can use xpath to access the value for each repeat group (1, 2, 3, etc.). There may also be a way to do that if you know how many people a manager is going to select - you can decide how many times to do a repeat. I think that is a separate issue from this and we can file something if there is a bug. Give it some more testing to see if you're able to access the variables.

**Comment by ngaruko** [comment]
Will move this to ready and if the 'looping through' that @derickl mentioned is an issue, we might need to raise a new one.
