### ISSUE TITLE
edit-user controller has 3 different entry points and 2 different templates

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3436]
You can use the `edit-user.js` with 
 - `model === aUserObject` : you want to edit a given user
- `model === undefined`: you want to edit the current user
- `model === {}` : you want to create a new user

And with templates : 
 - `edit_user.html` : to edit the whole user. Though depending on your permissions, not all fields might display.
 - `update_password.html` : to edit only the password.

That's a lot of possibilities, it's hard to read the code and hard to test properly.

Refactor the common stuff into a service, and have only one template per controller, and possibly one controller per entry point.

**Comment by alxndrsn** [comment]
`EditUserPassword` as a separate controller seems very sensible 👍

**Comment by garethbowen** [comment]
This has been greatly improved by splitting the admin tab out, so I'm going to call this done.
