### ISSUE TITLE
UpdateUser service should enforce matching user and usersettings edits

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3441]
Currently you have to call `UpdateUser` service with both user updates and usersettings updates. 
The caller should figure out which is which and how to make a consistent update.

That's a difficult API to use : make `UpdateUser` service get a list of fields, and make it split between what's in user and what's in usersettings, and what should be in both (otherwise you get a messed up user...)

**Comment by SCdF** [comment]
Will be resolved by #3910
