### ISSUE TITLE
Config tab missing when screen gets too small

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3442]
When the screen gets too small, the _Configuration_ tab disappears.  This is mildly irritating.

<img width="435" alt="screen shot 2017-05-04 at 16 49 43" src="https://cloud.githubusercontent.com/assets/191496/25696439/c64391d4-30e9-11e7-97f9-56094c85cb35.png">
<img width="409" alt="screen shot 2017-05-04 at 16 49 52" src="https://cloud.githubusercontent.com/assets/191496/25696441/c76afbba-30e9-11e7-85a8-b6a6802a61ed.png">

**Comment by alxndrsn** [comment]
This appears to be deliberate: https://github.com/medic/medic-webapp/blame/master/static/css/inbox.less#L1590-L1592

@garethbowen any ideas?

**Comment by alxndrsn** [comment]
N.B. there is an option _Configuration which appears in the fast food menu:

<img width="391" alt="screen shot 2017-05-04 at 16 54 32" src="https://cloud.githubusercontent.com/assets/191496/25696621/6cd540f6-30ea-11e7-823c-7d1f263d2d25.png">

However, this actually opens the first-time config wizard:

<img width="400" alt="screen shot 2017-05-04 at 16 54 37" src="https://cloud.githubusercontent.com/assets/191496/25696619/6c3330ea-30ea-11e7-9407-c981772238f7.png">

**Comment by garethbowen** [comment]
It's deliberate. The configuration screens don't really work on mobile resolutions so I decided there wasn't much point taking up space in the tab bar. Is this needed?

**Comment by alxndrsn** [comment]
> Is this needed?

> >  This is mildly irritating.
