### ISSUE TITLE
Error after canceling and re-opening any contact creation form

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3448]
Seen on v2.11.1-beta.1 on lg.dev. A fix is required for v2.11.1 final as this is occurring for both full access/admin users and for restricted users for both adding places and adding people. Note that all edit forms are working correctly.

To reproduce: 
1. Log in as a full access user or admin.
2. Click on New district. See that the form opens.
3. Click Cancel to close the form.
4. Click New district again. See an error.

![image](https://cloud.githubusercontent.com/assets/1286381/25728459/141f2536-30e4-11e7-92e1-b05c139c02dd.png)

**Comment by garethbowen** [comment]
IIRC that usually means we forgot to unload the form (ie: `Enketo.unload(formInstance)`) after it was first rendered.

**Comment by sglangevin** [comment]
@estellecomment this is the last item we are waiting for to release 2.11.1 final.

**Comment by garethbowen** [comment]
Also happens with restricted users creating a health centre so I suspect any Enketo contact form is affected.

**Comment by garethbowen** [comment]
Reports don't appear to be affected.

**Comment by garethbowen** [comment]
Unminified stacktrace:

```
Error loading contact form. Error: ["TypeError: Cannot read property 'classList' of undefined"]
    at enketo.js:175
    at processQueue (angular.js:16843)
    at angular.js:16887
    at Scope.$digest (angular.js:17982)
    at angular.js:18211
    at completeOutstandingRequest (angular.js:6274)
    at angular.js:6554
```

**Comment by garethbowen** [comment]
It looks to be a race condition where now that contact forms are cached they render super fast and are ready to go before angular has rendered the page.

**Comment by sglangevin** [comment]
This is working well on v2.11.1-beta.3. Moving to ready.
