### ISSUE TITLE
Resolve repeat-relevant TODO

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3449]
There's a TODO in EnketoTranslation here: https://github.com/medic/medic-webapp/blob/master/static/js/services/enketo-translation.js#L267

The issue it references has been resolved in March: https://github.com/enketo/enketo-core/issues/336

Looks like we need to start passing `{ irrelevant: false }` to calls to `getDataStr()`, and then we could drop `repeat-relevant`.

There's a unit test for it, so i guess we can change the test and see if it breaks.

**Comment by alxndrsn** [comment]
@garethbowen I wrote this up with text that you have me.  I don't really know what it's about, and the issue's been dragged through milestones for 4 months now.  Is it really a priority?

**Comment by garethbowen** [comment]
@alxndrsn @abbyad After reading the code, the issues, and searching on Google and I still have no idea what the `repeat-relevant` node is for. It's mentioned a few times in our medic-projects forms but not in standard. Can either of you explain to me why it's used? If I remove the special handling of `repeat-relevant` will we need to change affected forms to use the `relevant` attribute?

**Comment by alxndrsn** [comment]
I _suspect_ we have a boolean value in our forms called `repeat-relevant` to prevent the first repeated item being included when it hasn't had any data filled in.  Which means we probably need to:

1. start passing `{ irrelevant: false }` to calls to `getDataStr()`
2. remote the `repeat-relevant` field from our forms

**Comment by sglangevin** [comment]
Yes, you're right @alxndrsn. We are using `repeat-relevant` in the `clinic` (Add family) forms for LG to determine whether or not to display the repeat group that allows the user to add children. This model is being copied and used by other projects so we probably need to continue supporting it (or something similar).

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

I've tested this with the LG add clinic form and it works with the old code or with the new flag without changing the form.

**Comment by sglangevin** [comment]
I'm not exactly sure what is expected here. I was able to successfully rename the `repeat-relevant` group to another name and the form works as expected. However, when trying to move everything into the same group so that there is one group containing the question "Do you want to register other family members" and the repeat group for registering in them, the form loaded but didn't create the children. Can someone confirm whether my second test was out of scope for this issue? I didn't go too deep into it to figure out whether I had a misconfiguration in my form.

**Comment by sglangevin** [comment]
@garethbowen or @alxndrsn can you help me understand what was expected here? I'm not sure whether or not this passed AT.

**Comment by garethbowen** [comment]
I guess make sure you can create forms that do what you needed repeat-relevant to do before.

**Comment by sglangevin** [comment]
Right, so the only improvement I saw here was that I don't have to call that group `repeat-relevant`, I can call it whatever I want. But the group still has to exist. So if that was the intention of this issue, it passes.

**Comment by garethbowen** [comment]
Sounds good to me!
