### ISSUE TITLE
Reports list showing when user doesn't have proper permission

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3452]
When a user doesn't have permission to see reports the Reports header is removed but the list remains:

![image](https://cloud.githubusercontent.com/assets/789512/25774157/1d95c546-323f-11e7-996b-051b0b8bf366.png)

For comparison, here is what it is like when they do have they `can_view_reports` permission

![image](https://cloud.githubusercontent.com/assets/789512/25774191/ae829cf0-323f-11e7-97de-feddc92c82ed.png)

This is only relevant in cases where users will only have access to Messages tab, which is not a common occurrence. In the meantime I have restored the  `can_view_reports` permission so that the profiles are easier to read, even if it is displaying an unnecessary section.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Nice. Merged.
