### ISSUE TITLE
Add format-date-tr() to our custom xpath functions to support translations of days and months in xforms

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3459]
Spawned from discussion here: https://github.com/medic/medic-projects/issues/2019

Currently, the ODK spec (and therefore, Collect and Enketo) always uses English when rendering `%a` and `%b` options. @alxndrsn suggests that for the short term we add a custom xpath function so that we can translate `%a` and `%b` options into the language in which the form is being rendered.

In the longer term, the hope is that ODK will accept this change into its spec: https://github.com/opendatakit/xforms-spec/issues/122

**Comment by alxndrsn** [comment]
Support added in [enketo 4.35.0](https://github.com/enketo/enketo-core/blob/250bb5b91949a98949f7ac14c0c8cc1077203591/CHANGELOG.md#4350---2017-05-26), so we should now be able to support this to.

**Comment by sglangevin** [comment]
@alxndrsn if you're intending to work on this, could you please add it to one of the Github projects we're using to track releases? It's helpful to see all of the different work items in one place for transparency purposes. This one can go in 2.14.0.

**Comment by alxndrsn** [comment]
Blocked by https://github.com/medic/medic-webapp/issues/3487

**Comment by alxndrsn** [comment]
Re-opened for acceptance testing.

**Comment by sglangevin** [comment]
Assigning to myself for AT.

**Comment by sglangevin** [comment]
Getting the following error in the console when trying to translate the date. Seen on alpha.dev, v2.14.0-alpha.7610, logged in as a restricted user.
![image](https://user-images.githubusercontent.com/1286381/31093581-fbefd13c-a766-11e7-806b-e315b34ad0ed.png)

**Comment by sglangevin** [comment]
Any ideas @alxndrsn?

**Comment by sglangevin** [comment]
I'm still getting a similar error on 2.14.0-alpha.7682. This is happening for all languages on a form that used to be working. If you log in to alpha.dev as a restricted user and try to register a pregnancy, when you enter the LMP the form should display the EDD (that's what I've been using to test).
![image](https://user-images.githubusercontent.com/1286381/31198817-687739f4-a90a-11e7-9b94-f27616974f31.png)
![image](https://user-images.githubusercontent.com/1286381/31198833-71bdd39c-a90a-11e7-95a5-476bd760172b.png)

Back to you @alxndrsn

**Comment by garethbowen** [comment]
@sglangevin The fix wasn't included in `2.14.0-alpha.7682` - you need 7683 or above. 7683 never published because the build failed on a flakey e2e test. I've restarted it and will let you know when it gets published.

**Comment by garethbowen** [comment]
@sglangevin 7683 just published so it's ready for you to AT again! Sorry about that.

**Comment by sglangevin** [comment]
LGTM!
