### ISSUE TITLE
HBB not working correctly on Android for (some?) modal dialogs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3461]
HBB on Guided Tour, Edit User Profile, Edit Password should close the dialogs.  It actually causes the back action to be performed on the screen displayed behind the dialog.

I have not checked the behaviour with other modals.

**Comment by sglangevin** [comment]
That's weird. Pinging @diannakane and @amandacilek as this relates to app navigation work they are doing.

**Comment by diannakane** [comment]
@slangevin do you want to fix this as a bug or close in favor of fixing alongside the nav update in September?

**Comment by alxndrsn** [comment]
This is a large regression in the current implementation and likely very simple to fix.  I suggest prioritising this in the short term.

**Comment by alxndrsn** [comment]
I suspect this is caused by a conjunction of changes related to android wrapper and the webapp code supporting it:

1. https://github.com/medic/medic-android/commit/c9739964085fdb9dbfe95774bc848e46f0f05cb1
2. https://github.com/medic/medic-webapp/commit/ce93efb5527ca9ded79fbdd4b83e2db6c6c1084a

**Comment by SLangevin** [comment]
Mentioning the wrong user guys :)  I'm not too bad with Android dev tho haha

**Comment by sglangevin** [comment]
@diannakane make sure you use @sglangevin please.

@alxndrsn if this is easy to fix, let's fix it. We can put the bug fix in 2.14.0 (or a point release after 2.13 goes out) as I'd like us to focus on finishing up 2.13.0 features for now.

**Comment by diannakane** [comment]
Sorry about that! Responded from my email and took a guess...

**Comment by alxndrsn** [comment]
Actually because `XWalkView` does not delegate `onBackPressed()` to the parent activity in the same way that `WebView` does.  Possibly a bug in Crosswalk.
