### ISSUE TITLE
Predictive Text does not work in form text fields or text areas

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3464]
This may be deliberate(?)  I think predictive text should at least be available for multi-line textareas, if not for all text input.

Seen on: Samsung Galaxy V2

**Comment by sglangevin** [comment]
Predictive text works for me on my Tecno Y4 in text fields and text areas of forms.

**Comment by garethbowen** [comment]
Closing as can't reproduce - it looks like it depends on the specific handset being used which probably puts it outside of the realm of things we can fix.
