### ISSUE TITLE
On small screen, cannot re-open date filter in history tab

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3467]
After using the date filter to search reports once, it cannot be opened again.  Other filter dialogs seem to re-open fine.  Seen on Android/Galaxy V2 and desktop Chrome.

![screen shot 2017-05-12 at 00 57 39](https://cloud.githubusercontent.com/assets/191496/25961766/02927b90-36ae-11e7-8520-7258d6e28b77.png)

**Comment by sglangevin** [comment]
This issue goes beyond not being able to re-open the filter. The selected dates also don't seem to filter the list. This feature isn't commonly used on Android in the projects that have deployed already. Is there an upcoming deployment that needs this fix?

**Comment by alxndrsn** [comment]
> Is there an upcoming deployment that needs this fix?

Not that I know of.  Can we hide the functionality for this screen size if it's not going to be fixed?

**Comment by sglangevin** [comment]
We have been leaving it alone since the plan is to revamp the history tab filters anyway. If hiding it is important, then I'm ok with it, though the longer-term plan is to re-do the filters.

**Comment by garethbowen** [comment]
This is the exception thrown when trying to open the dialog the second time:

```
Uncaught TypeError: Cannot read property 'clone' of null
    at DateRangePicker.show (daterangepicker.js:1117)
    at DateRangePicker.toggle (daterangepicker.js:1154)
    at HTMLSpanElement.proxy (jquery.js:496)
    at HTMLSpanElement.dispatch (jquery.js:5206)
    at HTMLSpanElement.elemData.handle (jquery.js:5014)
```

I suspect this is probably because of [the patch](https://github.com/medic/medic-webapp/blob/master/patches/bootstrap-daterangepicker.patch) we apply to the datepicker to make it work on small screens. Or alternatively somewhere [in the code](https://github.com/medic/medic-webapp/blob/master/static/js/services/search-filters.js#L189) that listens to that event.

**Comment by alxndrsn** [comment]
@garethbowen good sleuthing.  As Sharon said above, this is not prioritised.  If you can fix it without effort, then please do, but I'm unlikely to get round to it.

**Comment by garethbowen** [comment]
@alxndrsn Review please!

**Comment by alxndrsn** [comment]
:+1:

**Comment by ngaruko** [comment]
LGTM with V2.13.0-alpha.5898
