### ISSUE TITLE
[Requirement] Simple group messaging

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#347]
We can incorporate full group messaging when we refactor the facilities module, but in the meantime many partners and users are expecting to be able to send message to multiple users. @diannakane, this will require some UX thought here, but some possibilities are to multi-select individuals from the drop down, or a check box to send the message to all sub facilities of the selected facility?

Relates to #90

**Comment by ngaruko** [comment]
This issue was moved to ngaruko/medic-webapp#11
