### ISSUE TITLE
if no data connection, app gets stuck

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3470]
If there is no data connection (data connection and wifi switched off) when the app is started, a toast is issued saying something like `ERR::Domain name unknown`, and the webview screen stays blank.

To get out of this, a user needs to click _Home_ in the app menu.  However, on recent versions of Android this menu can only be accessed by holding down the HBB, as the hardware menu button has been removed.

It would be helpful, as well as displaying a toast, to prompt the user to check their data connection and then try reloading the page.

As part of this, check if/why the app is not displayed when it's already in the app cache.

**Comment by sglangevin** [comment]
Is this for a user who was previously logged in? Or on first run?

**Comment by alxndrsn** [comment]
Seemed to happen for both, but I will confirm.  If only the latter, then less of a concern.

**Comment by alxndrsn** [comment]
Fixed in 0.3.10.
