### ISSUE TITLE
Ensure CouchDB `secret` configuration parameter is left unmodified after Medic OS upgrade

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3472]
Ensure that we preserve the `secret` configuration parameter in the CouchDB `*.ini` set of files during upgrade if one is already present. This secret is used as part of session management, and changing it will invalidate sessions post-upgrade, which we do not want.

Also, ensure that the session timeout is set to the CouchDB default value consistently for normal instances. Preserve the existing session timeouts for all LG-related machines. Test for ad-hoc configuration changes prior to upgrade on all instances. All future couchDB configuration modifications _must_ use `.d` directories.

**Comment by garethbowen** [comment]
@henokgetachew Can you update this at all? Do we overwrite `secret` on upgrade?

**Comment by henokgetachew** [comment]
@garethbowen we overwrite `secret` on upgrade right now yes.  However, what we're doing with the larger instances is copy this value to preserve it and put it back in after the upgrade.  It has worked fine for lg.app and lg-kenya.app instances.  The `.d` folders are available now after the upgrade and we could just copy those files from now on and paste them on the new instances as well.  Preserving the `secret` value has been clearly stated in the upgrade checklist as well.  We also have to keep track of settings like session expiry duration etc.  I think this is good enough for now? Closing this.  Reopen if you disagree.

**Comment by garethbowen** [comment]
Ok sounds fine. We should definitely solve this at some point.
