### ISSUE TITLE
File chooser for importing translations should filter for .properties files

### ISSUE THREAD

**Issue by bishwas-medic** [medic/medic-webapp#3474]
Currently allows you to choose any kind of file.  Would make finding files easier if it filtered just for .properties files.

This is likely a one-line fix.

cc @alxndrsn

**Comment by sglangevin** [comment]
Is anyone besides tech leads needing this? I'm assuming that people on our team are uploading the correct type of file. This can be grouped with future work we will be doing to improve the ease of configuration for partner organizations.

**Comment by alxndrsn** [comment]
No, but it wasn't hard to fix!

**Comment by garethbowen** [comment]
LGTM!
