### ISSUE TITLE
Investigate and use travis build stages

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3476]
We currently have [a complicated script](https://github.com/medic/medic-webapp/blob/master/scripts/ci/travis_after_all.py) which we copied from some guy on the internet which tries to determine if all travis builds in one run have finished successfully, and then pushes the app to the market. This is really useful so we can test against different versions of node or different version of CouchDB.

This has been made obsolete by a new feature in travis called [Build Stages](https://docs.travis-ci.com/user/build-stages).

Investigate replacing the custom script with the generic build stages configuration.

It might be that we can split out more stages, for example, our ideal build might be:

1. Run sanity checks (jshint)
2. Build the app and pass on as an artefact (is this even possible?)
3. Run unit tests with one instance per for Chrome and one for Firefox
4. Run integration tests with one instance for CouchDB1, CouchDB2, Chrome, and Firefox. (Maybe also Chrome at mobile resolution but this will likely require a different test suite.)
5. Publish to the market

**Comment by alxndrsn** [comment]
Without modifying the build to upload a binary bundle somewhere, we'll have to re-run the packaging steps for each part of each stage: https://docs.travis-ci.com/user/build-stages#Data-persistence-between-stages-and-jobs

**Comment by garethbowen** [comment]
Right. Ideally we'd jshint, build, and upload somewhere, then run tests, then publish. In the short term we could leave it as is, or go with a slightly slower but cleaner strategy of building for each step.

**Comment by rmhowe** [comment]
@garethbowen is this something that will be looked at in the near future? Perhaps as a devops task for 3.0?

**Comment by garethbowen** [comment]
Yeah I think this is still relevant and Horti may make it easier. What we have is a Horti repository for all the successful builds which can then be installed. We need some way to push to a repository but mark it as not ready for deployment but make it available for Travis build stages to install it.

**Comment by alxndrsn** [comment]
> We need some way to push to a repository but mark it as not ready for deployment but make it available for Travis build stages to install it.

A couple of suggestions for this:

1. separate staging server/build db specifically for travis, with builds identified by travis build number.  This would mean that at the end of a successful build, the built artifact has to be uploaded a second time.
2. store these builds in the same db as the rest of the builds, but with doc IDs such as `travis-12345`.    This might cause some bloat in changes feed and view generation on the staging server (unlikely an issue in the medium term), but would mean we can deploy artifacts for failed builds from horti without needing to support multiple staging dbs.

**Comment by rmhowe** [comment]
So is this triaged with low priority?

**Comment by garethbowen** [comment]
Sounds good to me.
