### ISSUE TITLE
Update enketo dependency to latest release

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3487]
Update enketo to latest master.  Give the change log a close read, and apply all required changes to our enketo widgets.  This may just extend to deleting the `widget.prototype.destroy()` functions.

-----

Old text, which prompted this issue:

For some reason, in the db-object-widget's `Dbobjectwidget.prototype.destroy()` function, we need to destroy _and then recreate_ the select2 jquery plugin for the `<select>` element.

Understand why this is, and if there is a more correct approach that should be taken.

**Comment by sglangevin** [comment]
Just a note to make sure our CSS styling still works after the update since we ran into an issue with that after the last update.

**Comment by alxndrsn** [comment]
We forked from: `commit 8785499e69d6b555c661cc65371567095aa42b64 (tag: 4.27.2)`

Need to resolve three patches that we did:
* af67ca7cf8aa1b975bccfc1244ada7fb033fef1e - Trigger calcUpdate() calls for changes to option labels
* 9715efc981e4ed77e8943f01fcf9c57a0694d0b6 - Reference the translator module consistently from widgets and Form.js
* c1fceb6aa64d790b2751e105e25f56f45a5a78bf - Add support for `tel` type in clearInputs()

At least one of these will likely require re-patching.

**Comment by garethbowen** [comment]
@alxndrsn Back to you.

**Comment by alxndrsn** [comment]
No, to you!

**Comment by alxndrsn** [comment]
To me!

**Comment by alxndrsn** [comment]
Repeat `+` button appears to be missing.

**Comment by alxndrsn** [comment]
## Old

<img width="444" alt="screen shot 2017-08-26 at 20 33 03" src="https://user-images.githubusercontent.com/191496/29744093-d3968342-8a9d-11e7-825a-5dbeb7702060.png">

## New 

<img width="412" alt="screen shot 2017-08-26 at 20 33 09" src="https://user-images.githubusercontent.com/191496/29744094-d399c2e6-8a9d-11e7-83fb-c27ff192315d.png">

**Comment by alxndrsn** [comment]
We need to add support for `or-repeat-info` to our XSLT sheets.

**Comment by alxndrsn** [comment]
Fixed.

**Comment by garethbowen** [comment]
One more time!

**Comment by sglangevin** [comment]
Assigning to myself for AT.

**Comment by sglangevin** [comment]
Getting the following error when testing the New Pregnancy form on alpha.dev. Logged in as user sharon, ping me for the password.

![image](https://user-images.githubusercontent.com/1286381/30459030-082311ec-9963-11e7-844c-38bc90617ce4.png)

![image](https://user-images.githubusercontent.com/1286381/30459017-f512302e-9962-11e7-9cc7-9133267306cf.png)

**Comment by garethbowen** [comment]
This should be fixed now. Setting for AT.

**Comment by sglangevin** [comment]
The error I was seeing previously is now fixed. Will do some more testing on Chrome 30 this week to make sure everything looks good.

**Comment by sglangevin** [comment]
Did more testing on Chrome 30 and all looks good to me. Moving to ready and we'll do additional testing during release testing of 2.14.
