### ISSUE TITLE
Build hangs with no error if password is incorrect

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3491]
If the password in .kansorc is incorrect when [building the app](https://github.com/medic/medic-webapp#build-the-webapp), then `grunt dev` hangs on the following with no error message:

```
[...]
postprocessor modules/cleanup
postprocessor kanso-app-settings/cleanup
Credentials are needed to access previous app_settings:
Please provide credentials for: http://localhost:5984/medic/_design/medic
Username: 
```

Typing `admin` and pressing Enter doesn't help. It would be nice to have an error message, especially since passwords can go stale with password rotation.

**Comment by mandric** [comment]
Not really sure this is much of an issue for local development environments?  If you had the .kansorc setup according to the instructions you should get a decent error, like 401 not authorized.

**Comment by mandric** [comment]
Actually I think you're right if .kansorc has the wrong username/pass it prompts and fails?

**Comment by abbyad** [comment]
Ya, I was running this locally from an AWS instance, and the only sign that something was not right was it asking for my username again. I don't think that 401 is surfaced.

**Comment by mandric** [comment]
Ok assuming this is a bug with the kanso push retry prompt then...

**Comment by abbyad** [comment]
Closing as no longer relevant, especially as we plan to move beyond Kanso.
