### ISSUE TITLE
In update_markets.sh: multiple runs against `release_v2` produce invalid URLs

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#3492]
Each successive run of `./update_markets.sh "$COUCH_URL" release_v2` appends another `-v2` to the URL, creating invalid market source URLs. These operations should be repeatable; an invalid URL should never be created provided `"$COUCH_URL"` is valid.

**Comment by mandric** [comment]
Unassigning this because I don't know when I will get to it.  Also @alxndrsn  started a new project for CLI tools and this issue should be moved to that project IMO.

**Comment by garethbowen** [comment]
I don't think this is a high priority so I'm removing it from the sprint.

**Comment by SCdF** [comment]
Also (though I'm not 100% sure what the script is for) it sounds like it will be rendered not needed by the Horticulturalist, as it does not use markets.

**Comment by garethbowen** [comment]
Market is being replaced by Horti.
