### ISSUE TITLE
Add support for the Bambara language

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3496]
The Muso Mali project is going to use the Bambara language. Translations are being compiled and the first cut of the translation file is committed. We need two more changes to completely support Bambara from the code side.

Firstly, add a `bm` property to the [LOCAL_NAME_MAP in api](https://github.com/medic/medic-api/blob/master/translations.js#L10). This is to show the name as native speakers would understand it, followed by " (Bambara)" for us English speakers. @abdoufata Can you let us know how native speakers refer to the Bambara language?

Secondly, the moment library doesn't ship translations for "bm" for months, days, etc. That means it'll fall back to English. Is this ok? Should it fall back to another language? Or should we [contribute](https://github.com/moment/moment/blob/master/CONTRIBUTING.md) a language file for "bm" through to the moment library?

**Comment by estellecomment** [comment]
Adding bambara to Moment would be awesome! Then anyone on the internet could have dates in bambara 😎  @abdoufata would you be interested? We would need your help to produce a file like this : https://github.com/moment/moment/blob/master/src/locale/fr.js (this one is for french)

**Comment by abdoufata** [comment]
Hi @garethbowen Bambara language is **Bamanankan** in the local language.

**Comment by estellecomment** [comment]
We are drafting the Moment.js localization file. 
I've asked @abdoufata questions in this doc so that I can write the file (sorry, in French, private language😛 ): 
https://docs.google.com/document/d/1MzgouhvngbycE9Uk6EKj3pDdml9_ytc-XtZluoTx2aE/edit

**Comment by sglangevin** [comment]
Cool! This will be a nice contribution back to the internet!

**Comment by garethbowen** [comment]
@estellecomment Nice one! NB when contributing back the PR will only be accepted if the translations have associated testing. Read the contributing link above for details.

**Comment by garethbowen** [comment]
@estellecomment I've updated [the documentation](https://github.com/medic/medic-docs/blob/master/development/translations.md#adding-new-languages) about how to add a new language. Note the last step about including the language file into our app.

**Comment by garethbowen** [comment]
@estellecomment Any update on this? I don't know what the turnaround time for momentjs releases is but I suspect we need to get this PR in to them ASAP.

**Comment by estellecomment** [comment]
Yup, I agree!
@abdoufata gave me all the info I need to write the file, so now I have to write it.

**Comment by estellecomment** [comment]
PR LGTMed! Leaving this issue open until moment releases Bambara.
https://github.com/moment/moment/pull/4001

**Comment by garethbowen** [comment]
@estellecomment There's a comment on that moment issue that we can include it locally, which might be good for the 2.12.0 release.

**Comment by estellecomment** [comment]
De-assigning myself to focus on other things, but this is not finished.

**Comment by estellecomment** [comment]
@garethbowen please review : 
api : https://github.com/medic/medic-api/pull/169
webapp : https://github.com/medic/medic-webapp/pull/3589

**Comment by garethbowen** [comment]
Merged. Good work. Hopefully moment will merge it soon.

**Comment by ngaruko** [comment]
@estellecomment If I understand correctly form this [discussion](https://github.com/medic/medic-webapp/issues/3596), the feature/language is not merged yet in Moment and we are using the local copy. Shall we AT this atm or wait for the issue to be merged? Or did I get it correct in the first place?

**Comment by estellecomment** [comment]
We are using a local copy, yes. Here's the issue for using the moment.js copy when it's released : https://github.com/medic/medic-webapp/issues/3588

Please AT it now though, so we can release the feature safely without waiting for moment.js. The feature will work exactly the same once we use the moment.js copy, it's the same code, so it's fine.
