### ISSUE TITLE
Integrate travis-ci.com with Slack

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3497]
Give us some build notifications!

**Comment by ngaruko** [comment]
Can I get some context here @alxndrsn . Do we need to AT this?

**Comment by alxndrsn** [comment]
Check that medic-project build reports from travis are appearing in a suitable channel in slack where people responsible for those builds will look.

**Comment by ngaruko** [comment]
Navigating through Slack unsuccessfully, are these reports appearing in `tech-leads` channel or elsewhere? Any clue @alxndrsn @henokgetachew ?

**Comment by sglangevin** [comment]
I've seen these in slack but don't remember which channel they were in.
