### ISSUE TITLE
Bad error message when associated contact is not available in the local DB

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3499]
i see the following error message  if my user _does_ have an associated contact, but the contact is not in the local db:
> Your user does not have an associated contact. Talk to your administrator to correct this.

**Comment by garethbowen** [comment]
I've merged it. This got missed for a while. @alxndrsn I think it'd be easier to find if it was marked for code review and assigned to the reviewer.

**Comment by garethbowen** [comment]
No AT required - it's a console error message only.
