### ISSUE TITLE
Somehow expose conflicts to technical people to deal with

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3502]
We should expose conflicts, somehow, at least to technical staff, so we know to act on them.

First step would be to add a view that exposes all conflicting documents. The simplest way of doing this would be to add a new ddoc (to avoid view re-generation on all others) and write a simple view inside it:
```js
function map(doc) {
  if (doc._conflicts) {
    emit(); // or emit(doc._conflicts), or something else if you think it's helpful
  }
}
```
The result of that view should be exposed somewhere.

Since conflicts are rare (~100 in 2.5 million, 0.00004%, if LG is typical) there is probably little point building a UI in-app for this. My recommendation would be to attach this to @henokgetachew's Slack integration, and make a conflict be a critical notification in that.

I imagine the standard flow for our interaction with this would be:
 - Conflict comes in, view gets updated with 1 item in it
 - Slack integration fires N minutes later, contains the conflict.
 - Someone investigates, and resolves the conflict[1] by hand. 
 - Once resolved, they potentially raise a ticket if you think that the conflict was something we could have architected around (e.g. mark as read is an architectural problem we are solving, after which it cannot conflict)

@henokgetachew I'd be interested in your perspective here. I want to make sure that however this notification happens, the right people see it and can act on it promptly. If your slack integration is not the right choice there then email may be more appropriate.

[1] Resolving a conflict goes like this:
 - Look at the N different leaf nodes with `medic/${docId}?open_revs=all`
 - Combine them together if it's clear what the intention was, or escalate the problem (the audit trail may be useful here) if it isn't
 - Once combined, delete the leaf nodes that aren't the main one. You can confirm you've done this completely when `medic/${docId}?conflicts=true` does not return a `_conflicts` property

**Comment by SCdF** [comment]
In addition: the upshot of doing this is the expectation that all existing conflicts get resolved in the process of adding and testing out this flow.

**Comment by SCdF** [comment]
Here are some non-standard (ie not easy to categorise) conflicts in lg-testing (that are presumably also in production), and additional notes about them:

- **F0ECD2A5-2103-650D-8620-F1767CFB1A2B** : edit to change form data + mark as read vs. transition. Interstingly transitions didn't run again on that doc, even though they should have? **This may be a sentinel bug**
- **F0ECD2A5-2103-650D-8620-F1767CFB1A2B** : as above, but the *other* `_rev` won that time: **here we lost form data**
- **org.couchdb.user:2muk045** : impossible to tell now, so `_rev` is `3` vs `369`
- **2364854f-fbd7-41a3-a9c1-92ba2b428125** : geolocation different, and one is missing reported_date. No idea.
- **32a90825-4d1d-4d26-8431-860a3e149236** : Looks like a genuine instance of two people editing the same doc (a few weeks apart)

**Comment by SCdF** [comment]
Added a conflict view, review please @alxndrsn : https://github.com/medic/medic-webapp/pull/3526

**Comment by alxndrsn** [comment]
👍

**Comment by henokgetachew** [comment]
Added a conflict monitoring plugin to medic bot.  Review please @SCdF: https://github.com/henokgetachew/medic-bot/commit/306160d924b81d8861945a43e8178d2f4b0e0686

**Comment by henokgetachew** [comment]
Update based on our slack convo: Next step is to upload that ddoc into instances.  I'll do this and post an update here so we don't have to wait until every single instance has been upgraded.  I have also made the code fix correcting the view url.  I don't think I have the rights to fork the medic-bot repo to medic. But I'll do PRs once it's under medic.  It's under my account right now.

**Comment by SCdF** [comment]
@henokgetachew has this been done yet?

**Comment by henokgetachew** [comment]
This is done. `medic-coflicts` is now uploaded to instances and view endpoints have been accessed through curl so that they warm up.

**Comment by henokgetachew** [comment]
Moving to AT.  @SCdF I assume you would want to see the weekly notifications at the end of the week before marking this completed?

**Comment by SCdF** [comment]
@henokgetachew yeah. Are we expecting that on Friday / Sunday?

**Comment by henokgetachew** [comment]
Yup Friday/Saturday depending on your time zone.

**Comment by SCdF** [comment]
This didn't fire AFAICT. @henokgetachew let me know when I can take a look at this again.

**Comment by henokgetachew** [comment]
@SCdF, I have just tagged you in the slack channel for this notification.

**Comment by SCdF** [comment]
Sweet, conflicts are now being reported!
