### ISSUE TITLE
Work out how traffic_stats can conflict with itself

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3503]
Here are two examples from lg-testing, the lg clone: `4493C9C9-7C9C-2266-A828-DA3D34DF24C4` and `62DEB922-7397-2250-912C-0056B5F40F68`.

These documents need to be looked into. They are conflicting. However, they should be only generated from one client (specifically, a CHW's phone).

We need to investigate ways this could be happening. My top guess at the moment is the user has two devices, though it needs to be investigated.

Once done, fix it so it doesn't happen again:
 - Make sure it's scoped per device.
 - Or, if there is a bug in the code that generates these documents that is causing conflicts (unlikely), fix that bug.
 - Or, potentially, consider some kind of automatic merging if required (even more unlikely)

**Comment by alxndrsn** [comment]
> Make sure it's scoped per device

:+1: Seems important whether or not this is the cause of conflicts.

**Comment by garethbowen** [comment]
Note that traffic stats are no longer collected or replicated so it can't happen again with that specific document. https://github.com/medic/medic-webapp/issues/2886

**Comment by SCdF** [comment]
Cool, one less thing to deal with. Closing.
