### ISSUE TITLE
Change patient id generation to store the length of id it's generating

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3505]
Currently the [id generation code](https://github.com/medic/medic-sentinel/blob/master/lib/ids.js#L4) always starts at 5 digits long, and then uses rules to increase that number as required.

Instead of this, we should store and retrieve the id length… somewhere[1].

This lets two things happen:
 - If a partner for some reason wants a default length they can set the initial length
 - If the rules decide that a length is finished, we won't go back to 5 on restart. This may be less confusing for people.

[1] Unfortunately, app_settings is not a good place for this, since the rules may decide to change the value, forcing a ddoc reload. We should consider either getting rid of that problem (by moving app_settings out of the ddoc), or storing it in a different meta-doc, e.g. `{_id: 'patient_id_length', length: 5}`

**Comment by sglangevin** [comment]
This is needed for a few projects that are upgrading. Adding to this iteration to see if we can get to it.

**Comment by garethbowen** [comment]
@SCdF When you say "default length" is it ok for it to still grow beyond that if necessary? It would be really good to store app_settings in a separate doc. Dashboard app settings page (which is used sometimes) expects it to be stored on the ddoc so we'd need to manage that perhaps by providing our own generic configuration page (maybe just import/export).

**Comment by SCdF** [comment]
@garethbowen yeah it will still grow if required.

In terms of storing app_settings elsewhere, we could have a look, but the more I think about it the more I'd rather just create a new marker doc, as shown in the example above. In a large part because it means we're not introducing a giant refactor with this change.

**Comment by SCdF** [comment]
PR is here: https://github.com/medic/medic-sentinel/pull/133

@mandric can you review please.

@sglangevin do you have any idea how / where we'd document this?

**Comment by sglangevin** [comment]
@SCdF what happens if an instance was using, say 7-digit IDs in v0.4 and then is upgraded to v2.x? Will the `shortcode-id-length` document be created?

For documentation, I'd put it in medic-docs in the configuration folder. I can also work with @ngamita to make sure that this is communicated well to tech leads.

**Comment by SCdF** [comment]
@sglangevin there is no migration at this stage, no. I could write a script for it, but unless we have a dozen projects with custom lengths it's going to cost more time to write it than it is to just tell people about it.

I'll look into adding something into medic-docs/configuration.

**Comment by sglangevin** [comment]
Ok, makes sense. If you could include a note in the docs about how to set this up for projects that are upgrading from v0.4 or other earlier versions of v2.x, that would be really helpful. I believe there are 2 that @ngamita mentioned that are upgrading from v0.4, but there may be others upgrading from v2.11 or other v2.x versions that would need to set this up manually.

**Comment by SCdF** [comment]
@sglangevin if you wouldn't mind taking a look at https://github.com/medic/medic-docs/pull/22 that would be really helpful :-)

**Comment by SCdF** [comment]
Merged both the code and the documentation.

**Comment by sglangevin** [comment]
@SCdF I tested this on clone-kilifikids-kaiti.app on 2.12.0-beta.5. I created a doc with id `shortcode-id-length` and set `current_length` to 6. However, when I sent in a pregnancy registration form, I got a 5-digit ID in response. Am I missing something?

**Comment by SCdF** [comment]
@sglangevin could you try restarting sentinel and seeing if that helps?

**Comment by sglangevin** [comment]
@SCdF I tried restarting sentinel and no luck. Any other ideas?

**Comment by SCdF** [comment]
Weeeeird. Let me take a look.

**Comment by SCdF** [comment]
@sglangevin looks like beta 5 is a bad build:

```
scdf at SCdF in ~/Code/Medic/medic-sentinel on 2.12.x
$ git hist -3
* 0c72050 2017-05-31 | Added minimum length constraint (HEAD -> 2.12.x, tag: 2.12.0-beta.4, tag: 2.12.0-beta.3, origin/2.12.x) [Stefan du Fresne]
* 9d95459 2017-05-30 | id generator now stores id length in a doc [Stefan du Fresne]
* e5a49ce 2017-05-19 | Bump libphonenumber for 2.12 (tag: 2.12.0-beta.2, tag: 2.12.0-beta.1) [Estelle Comment]
```

So we care about commit `0c72050`, which looks to be in beta 3 and 4, though there is no tag for 5.

```
scdf at SCdF in ~/Code/Medic/medic-webapp on master
$ git co 2.12.0-beta.5
M       api
M       sentinel
Note: checking out '2.12.0-beta.5'.
<...snip>
HEAD is now at 8d9afbef... Bump api for 2.12.0
scdf at SCdF in ~/Code/Medic/medic-webapp on (no branch)△
$ git submodule update
Submodule path 'api': checked out 'e8a61a8dafc8698d549cd679e6e72bdccd26d27c'
Submodule path 'sentinel': checked out 'e5a49ce22c5838915e39c07d15228cf2617c5ef3'
scdf at SCdF in ~/Code/Medic/medic-webapp on (no branch)△
$ cd sentinel
scdf at SCdF in ~/Code/Medic/medic-webapp/sentinel on (no branch)△
$ git hist | grep 0c72050
scdf at SCdF in ~/Code/Medic/medic-webapp/sentinel on (no branch)△
$ git hist -1
* e5a49ce 2017-05-19 | Bump libphonenumber for 2.12 (HEAD, tag: 2.12.0-beta.1, origin/2.12.x) [Estelle Comment]
```

So beta 5 uses beta 1 of sentinel for some reason.

We really need a script to get rid of this manual process, it's kind of error prone :-/

**Comment by sglangevin** [comment]
Ah ok. I think we need beta 6 anyway. @estellecomment can you please do a new beta to fix this issue and also to include #3541?

**Comment by SCdF** [comment]
I'm going to re-close this issue and put it back to AT, hopefully this time you'll get a crack at it :-)

FWIW the reason I asked you to restart sentinel is because the length of IDs that should be generated is cached. This is an intentional performance thing. We could improve this by watching for the config file to change if it turns out to be a pain, but I figured that this is almost never going to be changed by humans. I'll add a note to the documentation about having to restart sentinel.

**Comment by sglangevin** [comment]
Retested on 2.12.0-beta.6 and it's working well. Moving to ready.
