### ISSUE TITLE
Increase our confidence in client-side generated `_id`s being unique

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3506]
Currently, in lg-testing (a clone of production), we have around 50 documents (out of 2.5 million) that look to have conflicted because of non-unique id generation. In other words, they are completely separate documents that have smushed together because the UUID they picked was the same as another document.

At the moment we are using PouchDB' standard UUID generation, as seen here: https://github.com/pouchdb/pouchdb/blob/master/packages/node_modules/pouchdb-utils/src/uuid.js

The most obvious problem (if this is indeed the issue) is that `Math.random()` is known to not be massively random. There are better libraries out there, and there is `window.crypto`.

We should consider:
 - Contributing a better UUID algorithm / use of `window.crypto` to PouchDB
 - Failing that, use a third party UUID generator we trust more (we already use node-uuid in places)
 - Failing that, change our ID generation to be scoped per user, e.g. `stefan-SOME_UUID_OR_MAYBE_MS_SINCE_1970`)

**Comment by SCdF** [comment]
I've added a PouchDB PR: https://github.com/pouchdb/pouchdb/pull/6538

I presume I'll have to make more modifications.

**Comment by SCdF** [comment]
I closed the above PR and replaced it with this one: https://github.com/pouchdb/pouchdb/pull/6565

It's currently not working in browsers, I need to work out why browserify is not doing what I'd expect it tp.

**Comment by SCdF** [comment]
I've (I think) fixed this PR and now it looks like it works everywhere. Awaiting feedback.

**Comment by SCdF** [comment]
The linked PR has been merged into PouchDB!

Next stage, waiting for a release so we can upgrade to it.

**Comment by garethbowen** [comment]
When we upgrade we have to also solve the problem that `angular-pouch` is hardcoded to use `6.0.5`. We'll either need to hack the package-lock, patch angular-pouch, or fork it to make sure we're using the right version.

I assume this is meant to be closed now as it's blocked. @SCdF Please reopen if I'm jumping the gun...

**Comment by garethbowen** [comment]
This can't be acceptance tested yet, and I don't think it's possible to acceptance test it anyway, so I'm going to move it to Ready.
