### ISSUE TITLE
Can't view contacts for restricted user

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3517]
Selecting any contact shows "No person selected" in the RHS.
Most likely bug from change to linked contacts (#2635).

`Error generating contact view model TypeError: Cannot read property 'patient_id' of undefined`
At https://github.com/medic/medic-webapp/blob/master/static/js/services/contact-view-model-generator.js#L178

`contact.doc` is undefined.

**Comment by garethbowen** [comment]
Looks good. One small comment. Over to you @estellecomment

**Comment by estellecomment** [comment]
Fixed. Thanks for the review!

**Comment by estellecomment** [comment]
AT : both admin and restricted user should be able to see contacts fully displayed in the RHS, with their reports and everything, when they click on them in the LHS (or navigate from URL).
