### ISSUE TITLE
Task summary screen looks ugly on desktop

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3521]
![task-summary](https://cloud.githubusercontent.com/assets/2064938/26659938/c4f2ee70-46c8-11e7-96b8-b889a3727a16.png)

**Comment by garethbowen** [comment]
Code review please @estellecomment !

**Comment by garethbowen** [comment]
Now it looks like...

![after](https://cloud.githubusercontent.com/assets/2064938/26660991/b33ddc74-46cf-11e7-9f21-23b6a8dafbf5.png)

**Comment by estellecomment** [comment]
LGTM, merging
