### ISSUE TITLE
CouchDB 2.0: make sure our app doesn't rely on seq  order

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3528]
Read this instructive mailing list thread: https://mail-archives.apache.org/mod_mbox/couchdb-user/201706.mbox/%3CCAB2GbkxjKMu9Z_PMQOHjL00OMkegOvhyjLpV3XHhGqo1sKW73A%40mail.gmail.com%3E

Basically, the initial number is there as a legacy trick, and if you are running CouchDB with multiple nodes there is no guarantee that the visible seq number actually increases as the change feed goes on.

We should make sure we aren't relying on that anywhere. I imagine we might be in Sentinel in certain places (such as transition management).

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by estellecomment** [comment]
that sounds pretty important to me! Scheduling.

**Comment by SCdF** [comment]
Weird it wasn't already scheduled… I guess I forgot. It's in the right project though, so I got halfway there
