### ISSUE TITLE
Reports view on person page doesn't live update

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3530]
To reproduce:
 - Have a person open, note the reports in the reports section of that page
 - Send a report in for that person
 - Note that the report doesn't appear in the reports view (though the report number against the main report tab has increased: the app clearly knows about it)
 - Refresh the screen
 - Note that it's now there.

**Comment by sglangevin** [comment]
These sorts of issues have come up several times across different parts of the app. We've been fixing them one-off as they occur, but could we do a full pass through the app and figure out what doesn't update in real time and fix everything all at once? I'd be happy to take on the task of doing a full pass through the app and listing the live update issues that are there so they can be fixed.

This is also not a critical bug for now so I'd rather we address some of the other ones that have been raised (see on scheduled & on deck columns here: https://github.com/medic/medic-webapp/projects/3).

**Comment by garethbowen** [comment]
Moving this out of the milestone as it's not a high priority compared to other bugs.

**Comment by garethbowen** [comment]
This also applies to a contacts children.

**Comment by ngaruko** [comment]
LGTM. Will close this an raise a different issue if it comes up in another part of the app as @sglangevin suggested.
