### ISSUE TITLE
The namespace-form-fields migration conflicts itself

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3534]
In the `namespace-form-fields` migration we use the `data_records` view which emits each data_record multiple times. If the same doc is returned twice in one batch the migration modifies both copies and attempts to bulk save them which fails with a conflict. It would be better to use the `doc_by_type` which only emits each doc once.

Fix this migration and check if other migrations are potentially affected by the same issue.

**Comment by garethbowen** [comment]
I've checked the other migrations and the only other one that uses the problematic view also ensures the IDs are unique, so it may not perform ideally but it shouldn't conflict.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by garethbowen** [comment]
Don't worry about merging it. I'll merge, bump submodule, backport, release, etc once it's reviewed.

**Comment by SCdF** [comment]
@garethbowen LGTM

**Comment by sglangevin** [comment]
I'm going to consider this acceptance tested during the upgrade of Kilifi Kids Kaiti this week. Please shout if that is a bad assumption.
