### ISSUE TITLE
Allow upload of forms with "meta" docs through Configurations UI

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3540]
Update the form configuration UI to allow uploading of meta style form docs rather than the old context style. This allows for more configuration, such as the icon property.

For example:

```json
{
   "icon": "survey",
   "context": {
       "person": false,
       "place": false,
       "expression": "!contact && user.parent.type != 'district_hospital'"
   }
}
```

Ref #3433

**Comment by garethbowen** [comment]
Code review please @SCdF 

This will need to be backported to 2.12.x

@sglangevin NB: I've dropped backwards compatibility so the `context` format is no longer supported - only `meta` will work in the UI.

**Comment by sglangevin** [comment]
Sounds good @garethbowen - can you make a note in the changelog so that everyone is aware?

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
@sglangevin I don't think it needs an explicit note in the changelog because the ability to upload the old context files was never released so nobody outside us alphas will notice the change. I've added it as a 2.12.0 feature in the changelog though.

**Comment by sglangevin** [comment]
Yeah, that's true. I was just wanting to make sure that everyone knows that we'll only be supporting meta files in the UI, but I can also make sure that is communicated elsewhere.

**Comment by sglangevin** [comment]
This is working well in latest alpha, moving to Ready.
