### ISSUE TITLE
Update startup text labels

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3541]
Upload startup text labels as per https://github.com/medic/medic-webapp/issues/3384#issuecomment-308028115:

* Loading app
* Fetching info (show # of docs)
* Starting app

**Comment by alxndrsn** [comment]
@sglangevin some clarifications please:

1. should text end with ellipsis, full stop or just nothing?
2. for _Fetching info_, what would an example look like?  E.g. _Fetching info (123)_?

**Comment by sglangevin** [comment]
> 1. should text end with ellipsis, full stop or just nothing?

Yes, let's keep the ellipsis as you had it.

> 2. for Fetching info, what would an example look like? E.g. Fetching info (123)?

Can we put Fetching info (123 docs)?

**Comment by garethbowen** [comment]
LGTM

**Comment by sglangevin** [comment]
Tested in 2.12.0-beta.6 and it looks good. Moving to ready.
