### ISSUE TITLE
Don't eval() user input

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3546]
Here `eval()` is being used on unsanitised user input:

https://github.com/medic/medic-webapp/blob/master/static/js/services/contact-summary.js#L53

I suspect we are committed to executing this code, but we should sandbox it if possible.

Inclusion of unused imports [`$parse`](https://docs.angularjs.org/api/ng/service/$parse) and [`$sanitize`](https://docs.angularjs.org/api/ngSanitize/service/$sanitize) suggest:

1. some thought was given to this at initial implementation time, but was not followed up
2. jshint can't detect unused angular "imports" declared as function arguments, unless they're the last one in the arg list

**Comment by alxndrsn** [comment]
It's unlikely we can replace use of `eval()` with `$parse` - the `contact-summary.js` example in e2e tests breaks the following [angular expression restrictions](https://docs.angularjs.org/guide/expression):

* uses `if`
* declares a `function`

**Comment by alxndrsn** [comment]
Looks like using [`Function()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) would be a bit safer.

**Comment by alxndrsn** [comment]
Pouch uses https://github.com/alexdavid/scope-eval/blob/master/scope_eval.coffee

**Comment by garethbowen** [comment]
Interestingly jshint fails on Function() with...

> The Function constructor is a form of eval.

Still... it can't be any worse, right?

**Comment by garethbowen** [comment]
I misattributed the commit but here's the required documentation update: https://github.com/medic/medic-docs/commit/030e70999131f57b5d67c4f11330b916d812e30f
