### ISSUE TITLE
Use alternative pagination method for running batched migrations

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3553]
In #2418 we introduced a high level `db.batch` function for running a function over all the records returned from a query in batches. This is particularly useful for migrations. For expeditiousness this has been done with the `skip` property which does work but is potentially slow on large result sets.

Refactor this to use the [startkey pattern](http://docs.couchdb.org/en/2.0.0/couchapp/views/pagination.html#paging-alternate-method) instead.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
For AT, ensure the "extract-read-status" migration works as expected.

**Comment by sglangevin** [comment]
Assigning to @ngaruko for AT.
