### ISSUE TITLE
Improve associate-records-with-people migration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3554]
Recently it took 40 minutes to complete on a relatively small instance (100k sequence).

Investigate using the doc_by_type view and using bulk updates to improve performance.

Add logging so progress is reported.

Ideally this would be included in the 2.12.0 release so the next round of upgrades can benefit from it.

**Comment by garethbowen** [comment]
Code review please @estellecomment 

If this passes we need to bump api and backport to 2.12.0.

**Comment by estellecomment** [comment]
Added it to 2.12.0 project.
Two comments in commit : https://github.com/medic/medic-api/commit/d8f7581806c77ab5d392b1b4da5eebd869e25248

**Comment by sglangevin** [comment]
Moving this to Ready for now - we can come back to it if there are any issues during the next round of upgrades.
