### ISSUE TITLE
transitions runner's `isRevSame` is assuming rev is an integer

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3557]
revs are not necessarily integers. 
The transition runner is comparing revs to figure out avoid rerunning transitions for nothing, but since `parseInt('not an integer')` is `NaN`, `isRevSame` is broken.

https://github.com/medic/medic-sentinel/blob/master/transitions/index.js#L160

**Comment by SCdF** [comment]
So this actually works, because `_rev` always *starts* with an integer:

```
> parseInt('1-ascvadsafawdss')
1
```

It is horrific, but that is Javascript for you I guess.
