### ISSUE TITLE
render patient_id field keys as links

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#356]
user should be able to click the patient id and get all patient records i.e. `href="?patient_id={{patient_id}}"`

![screen shot 2013-09-10 at 7 41 34 pm](https://f.cloud.github.com/assets/25641/1119995/3d5d09d4-1a8d-11e3-9e42-8f70e18176b3.png)

**Comment by ngaruko** [comment]
This issue was moved to ngaruko/medic-webapp#10
