### ISSUE TITLE
Sentinel can make multiple db writes to complete the transitions

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3565]
Some transitions are order dependant, for example, `update_clinics` sets the contact on the report, then `registration` uses that contact to register the patient. If the contact isn't set then [`registration` is skipped](https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L72).

This means if `registration` happens to run first it's skipped, then `update_clinics` and the other transitions run. Then the document is saved which triggers another change. This causes sentinel to check the transitions again and finally `registration` completes and the document is saved a second time.

The end result is the same but saving the document unnecessarily is a performance issue and increases the potential for db conflicts.

Find a way to make all the transitions and save the document in one go.

**Comment by garethbowen** [comment]
Two ideas we've come up with so far are...

1. Define the order transitions will be executed in to ensure that `update_clinics` is always executed before `registration` (there are bound to be other examples too).
2. Keep running the record through the transitions until nothing more changes. This is very similar to what we currently do except without the database write. This will always do one unnecessary loop to determine that it's finished.

**Comment by SCdF** [comment]
So 2. is hard to do "right" (ie deep compare etc). However, sentinel actually makes it easy, because you're supposed to pass `true` to the callback if something has changed, so we can just presume that's valid.

**Comment by SCdF** [comment]
We'd also need to write the sentinel transition metadata at the end of a "round" before we run the next one, as transitions use that to determine if the other one has run.

**Comment by dianabarsan** [comment]
Transitions were put into specific order as part of [#4201](https://github.com/medic/medic-webapp/issues/4201) (PNC Schedule not generated for SMS reports). 

As for the other suggestion, to use the `changed` parameter passed by the transition itself, some transitions return true whether or not changes were made (for example: default_responses).

**Comment by garethbowen** [comment]
Two PRs to review please @dianabarsan
