### ISSUE TITLE
App cache error not reported to user

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3568]
If there is an error with app cache the spinner runs endlessly on the page. We should report the loading error to the user, ideally with instructions on how to resolve it or at least to contact their admin.

From console:
> [...]
Application Cache Progress event (32 of 33) https://demo.dev.medicmobile.org/medic/_design/medic/_rewrite/static/img/setup-wizard-demo.png
Application Cache Error event: Failed to commit new cache to storage, would exceed quota

The error in question does not seem to be an issue in itself. I've run into this now, and before, when my disk space is running low.

**Comment by SCdF** [comment]
Someone could look into this if we can find the time. It doesn't seem like a high priority though

**Comment by garethbowen** [comment]
This will be fixed by #4713
