### ISSUE TITLE
Automatically tag medic-api and medic-sentinel when publishing medic-webapp

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3581]
Currently, we often forget to tag medic-api and medic-sentinel, because they are in a different repo. This is problematic because it becomes a pain to work out what code is in which revision (NB: you still know which version of api or sentinel were deployed with webapp due to submodules, but you cannot, for example, see which tag some code was introduced in easily).

We should change our `after_success.sh` publish script so that when it publishes a build due to a tagged build successfully running, it also tags api and sentinel with the same tag.

We knocked up quick changes to the script before, but the user travis pulls from git with does not have the credentials to tag with. So, we need to find out how to pick a user for travis to use, and how to make sure that user has the right permissions.

**Comment by garethbowen** [comment]
Now that the submodules are merged into the webapp repo this is no longer necessary - 1 tag to rule them all!
