### ISSUE TITLE
Remove local copy of bm.js when moment releases Bambara

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3588]
Spawned from https://github.com/medic/medic-webapp/issues/3496
We're using a local copy of the Bambara locale for now. Remove it when Bambara makes it into moment.js
https://github.com/moment/moment/pull/4001

**Comment by garethbowen** [comment]
moment.js 2.19.0 has been released with Bambara included - scheduling for 2.15.0.

**Comment by garethbowen** [comment]
Review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged.
