### ISSUE TITLE
Cannot log out of app

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3592]
Logged in as admin on demo.dev running 2.12.0 and cannot log out via app or futon. 

In both cases I get the following in console:
`DELETE https://_:_@demo.dev.medicmobile.org/_session 401 (Unauthorized)`

_**Edit:** As a non-admin I was able to log out._

**Comment by garethbowen** [comment]
Works for me on demo.dev as admin.

**Comment by abbyad** [comment]
I am not able to reproduce this while in incognito mode.

**Comment by abbyad** [comment]
And neither can @alxndrsn in regular chrome.

**Comment by abbyad** [comment]
Here is a screenshot to compare against if anyone is able to reproduce.

![image](https://user-images.githubusercontent.com/789512/27667983-4de7c3ca-5c4c-11e7-8671-3370ae258cde.png)

**Comment by garethbowen** [comment]
Copied from slack...

> AFAICT the app sometimes gets into a strange state where you're logged out but can still see everything in the app due to offline first. For admins this means requests like "list all the contacts" never complete because that's a remote request (it should error, but hey, whatever). For non-admins it can look perfectly fine and it's just the replication that doesn't work. Ideally you'd get kicked to the login page if this happened.
> I think it might happen if you had, say, a cookie that wasn't expired, and a session that was.

**Comment by abbyad** [comment]
The problem persisted after deleting the cookies, app cache, IndexDB, and local storage. After a 2hr break, came back and was finally redirected to the login page. 

Closing for now as I cannot recreate this scenario.
