### ISSUE TITLE
Update fonts to Noto

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3597]
* Change the font to "Noto, sans-serif" throughout the app (apart from where we use FontAwesome). Bundle Noto with the app so everyone uses the same font regardless of device, language, etc.
* Change the base font size to 16px: `body { font-size: 100%; }`
* Use rems for all font sizes.
* Use this opportunity to standardise font tags and classes. Right now we have a lot of different styles, but we should only need 5-6. The common font sizes are: 1.5rem (h1), 1.25rem (h2), 1.125rem (h3), 1rem (p), 0.875rem (p.small or something).

**Comment by garethbowen** [comment]
TODO:

- [ ] check on tecno
- [ ] make sure headers are bolded correctly

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Merged.

**Comment by sglangevin** [comment]
Pretty much everything is looking really good in the new font at the new size. I like it! A few things from AT:
1. The Reports section header on both person and place profile pages doesn't fit on one line. See screenshot below that I took on my Tecno. @amandacilek any ideas? It fits until the screen is 330px wide but then moves to 2 lines so it looks weird on Tecno Y4.
1. The FontAwesome icons on the person profile pages look really small on mobile and desktop. This might be covered by #3719 though. I think I will leave it until that other issue is done and we can AT it over there.

![screenshot_2017-09-12-03-33-43](https://user-images.githubusercontent.com/1286381/30298534-9a3269e4-9700-11e7-9f05-e13aa0753694.png)

**Comment by amandacilek** [comment]
Oh interesting, I have it as "History" in all my mockups and forgot that we sometimes call it "Reports". It doesn't seem like a bigger word but it must be slightly. I would recommend decreasing the spaces on either side of the   |   symbol (and making the new smaller spacing consistent across all headers with these date filters). If it still doesn't fit, would we be open to abbreviating months to "mo"?

**Comment by amandacilek** [comment]
![header filters](https://user-images.githubusercontent.com/26235957/30298861-dd0599ca-9701-11e7-8316-817e9feca3fc.png)

**Comment by sglangevin** [comment]
Yeah, that is surprising that Reports is longer! I'd be fine with decreasing the spacing for filters listed in the Tasks header and Reports/History header to make it fit. I think the clickable area is fine still if we do that. @garethbowen does that work for you?

**Comment by amandacilek** [comment]
Hm, although, that makes it fit at 320 but not necessarily smaller if we are still planning to allow the LHS to shrink down to 260 on small desktops when we have the two pane layout. In that case (tiny 260px width), would we be able to put the filters on a new line below Reports and align them to the left?

**Comment by sglangevin** [comment]
I don't think we need to worry about that - this is only on the RHS, so it shouldn't be smaller than 320px, right?

**Comment by amandacilek** [comment]
Yeah I just deleted my comment! Ha, yeah it should never be smaller than 320.

**Comment by sglangevin** [comment]
One other thing I noticed: I'm now able to scroll a tiny bit from left to right on Tecno. Any idea why that might be @garethbowen?

**Comment by garethbowen** [comment]
Remember this is translated so it could be even longer, eg: French is "Rapports", Indonesian is "Laporan", and Nepali is "प्रतिबेदनहरु". I'll look at reducing the spacing around the filters and also make sure it flows nicely with less vertical space if necessary.

Not sure why the horizontal scroll - it may be some measurement is still in `em`. I'll have a look.

**Comment by sglangevin** [comment]
A few more things from looking at Desktop view again:
Editing to add a few more:
1. The gray box that appears when you select the Configuration tab isn't wide enough:
![image](https://user-images.githubusercontent.com/1286381/30299159-4deca0d8-9703-11e7-986b-79fa67d1c7ab.png)
1. The green box that appears when you select the Analytics tab is so wide that it almost covers part of the word "Configuration"
![image](https://user-images.githubusercontent.com/1286381/30299211-86d0bc04-9703-11e7-9d29-db570a5e87a1.png)

Sounds like we might need to increase the spacing across the top. cc @amandacilek

**Comment by amandacilek** [comment]
Ahh translations make life so much more difficult. With the French, Rapports is indeed longer, although their word for month is shorter so it seems to even out.

The only perfect way to solve this problem then would be to abbreviate the time filters to something even shorter, or always put them on a second line below the title.
![header filters copy](https://user-images.githubusercontent.com/26235957/30299360-2f5de356-9704-11e7-8025-cca26ebfbced.png)

**Comment by amandacilek** [comment]
If it works for now to decrease the spaces around the  |  symbol, great.

If we need a more future-proof solution, I suppose the filters on a second line is better than abbreviated filters, as it keeps the click targets bigger and is more flexible (if we have other filters in future, for instance).
![screen shot 2017-09-11 at 3 28 15 pm](https://user-images.githubusercontent.com/26235957/30299761-0cfabb70-9706-11e7-9b08-f167c45b5ff5.png)

**Comment by garethbowen** [comment]
> One other thing I noticed: I'm now able to scroll a tiny bit from left to right on Tecno.

I haven't noticed any. Is it on any page in particular? In app or browser?

> The Reports section header on both person and place profile pages doesn't fit on one line. See screenshot below that I took on my Tecno.

Done in PR.

![filters](https://user-images.githubusercontent.com/2064938/30466992-a9203444-9a35-11e7-9c80-ddaa676b7bd0.png)

> The gray box that appears when you select the Configuration tab isn't wide enough.

Done in PR.

![tabs](https://user-images.githubusercontent.com/2064938/30466996-ac381fde-9a35-11e7-990f-0e3796648f3f.png)

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged. @garethbowen I also wrote some comments on the PR for my own learning / interest.

**Comment by sglangevin** [comment]
The scrolling bit was on Tecno in the app. I think it might have been related to the Reports filters being on the next line? Not sure though. It was on a contact profile page.

Anyway, this looks great. Moving to ready!

**Comment by sglangevin** [comment]
Just realized work may not be done yet - re-opening. @garethbowen let me know when it's ready for review.

**Comment by garethbowen** [comment]
Ok, well if it's gone it's gone. Maybe raise a new issue it it comes up again?
