### ISSUE TITLE
Doc hydrating for data_records uses the wrong field

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3600]
Data_records look like this : 
```
{
  type: 'data_record'
  contact: { // report sender
    _id: <id>,
    parent: { // parent place of report sender
      _id: <id>,
      parent: { // grandparent place of report sender
        <etc>
      }
    }
  }
}
```
When you hydrate them, the `contact` field is untouched, and the hydrated hierarchy is added in the `parent` field. 
(so if you minify them, you're left with two dehydrated hierarchies in `contact` and `parent`)

**Comment by garethbowen** [comment]
Unfortunately there are multiple `hydrate` methods (this will be fixed when we have a shared npm package for this stuff). Assuming you're talking about the [one in sentinel](https://github.com/medic/medic-sentinel/blob/master/lib/lineage.js) then yes it looks wrong. Good catch!

The [one in webapp](https://github.com/medic/medic-webapp/blob/master/static/js/services/lineage-model-generator.js#L44) has different handling for contacts and reports so it looks right.

**Comment by sglangevin** [comment]
@SCdF this might be the issue that you ran into.

**Comment by estellecomment** [comment]
@garethbowen please review PR : https://github.com/medic/medic-sentinel/pull/136

**Comment by garethbowen** [comment]
Back to you @estellecomment

**Comment by estellecomment** [comment]
Thanks!

**Comment by ngaruko** [comment]
Does this need AT @estellecomment ?

**Comment by estellecomment** [comment]
I guess not, you're right. Moving to ready.
