### ISSUE TITLE
Header row should always show up in the users page

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3604]
![image](https://user-images.githubusercontent.com/3198821/27785104-29da38ae-5fe5-11e7-8857-53451c8a9c95.png)
The header rows should stay in place wherever we have long lists/tables. @sglangevin  @diannakane @amandacilek

**Comment by garethbowen** [comment]
Related #2996

**Comment by sglangevin** [comment]
We're planning to redesign this page completely at some point later this year or early next year. @garethbowen if there is a quick fix as part of #2996, go for it, otherwise let's leave this until we can get to it later.

**Comment by garethbowen** [comment]
@sglangevin Good to know. Will the redesign also include the create/edit user models?

**Comment by sglangevin** [comment]
Yes!

**Comment by garethbowen** [comment]
As @sglangevin said above this page (and the whole admin app) is due for a redesign. This is a great idea but we should wait until the designers are done.
