### ISSUE TITLE
Admin party mode detection is unreliable

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3606]
```
Fatal error initialising medic-api
Error: CouchDB Admin Party Mode detected, please disable: https://github.com/medic/medic-webapp#disable-couchdb-admin-party-mode
    at ClientRequest.net.get (/home/horticulturalist/.horticulturalist/deployments/medic-api/md5-Pz5Uh+qWOAqD6gMrnZylbw==/server.js:749:16)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:564:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:453:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
```

```
$ curl -X PUT localhost:5984/medic/asdfasdf --data {}
[info] [<0.294.0>] 127.0.0.1 - - PUT /medic/asdfasdf 403
{"error":"forbidden","reason":"You must be logged in to edit documents"}
```

**Comment by alxndrsn** [comment]
This will occur when admin party is disabled but:
```
require_valid_user = true
```

**Comment by SCdF** [comment]
@alxndrsn did you investigate this at all? What setup do you have that is different than expected? All the code is doing is checking for a 401 when you request the DB with no creds. Would be good to see what you get if you request that.

**Comment by alxndrsn** [comment]
Yeah, as per my comment above - basically I think API error message should be updated to change

> CouchDB Admin Party Mode detected

to e.g.

> CouchDB security appears to be misconfigured.  Check that Admin Party mode is disabled and `require_valid_user` is set to `true`.

This would probably also be a suitable fix for https://github.com/medic/medic-projects/issues/1886.

**Comment by mandric** [comment]
The link is also broken, maybe use this one instead? http://docs.couchdb.org/en/latest/config/auth.html#authentication-configuration

**Comment by SCdF** [comment]
@alxndrsn oh! It was entirely unclear to me that you thought the feature worked but the message was wrong. I thought you were implying that it was broken ("Admin party mode detection is unreliable").

We can change the message to whatever, sure. Also, weird that that the link doesn't work, I swear I wrote it…

**Comment by SCdF** [comment]
@estellecomment I've improved the error message and created a proper section in the README with instructions
 - https://github.com/medic/medic-webapp/pull/3611
 - https://github.com/medic/medic-api/pull/173

On Slack you said you saw this error message. Would be good to get your feedback on whether or not this makes sense.

**Comment by estellecomment** [comment]
Error message LGTM 
(I'm not sure why I got it, couldn't reproduce it, ignored)

Webapp build is failing so I'm leaving the merging to you.
