### ISSUE TITLE
Specify which forms can be downloaded using Collect

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3607]
Now that we can get blank XForms in Collect again (thanks to https://github.com/medic/medic-webapp/issues/3390) we need to specify _which_ forms can be downloaded so that users don't mistakenly download app workflow forms which may not work in Collect.

This will be helpful for any project that will use Collect while also having some in-app workflows, as is the case for some upcoming Standard deployments.

**Comment by alxndrsn** [comment]
Specify `doc.context.collect`; default to `false`.

**Comment by alxndrsn** [comment]
Implement alongside support for `forms/collect` directory in `medic-conf`.

**Comment by alxndrsn** [comment]
Duplicated at https://github.com/medic/medic-webapp/issues/3642

**Comment by sglangevin** [comment]
Moving out of 2.14 as the work for this is being done in #3642 and closing this issue as a duplicate.
