### ISSUE TITLE
Newlines in messages are not displayed in webapp UI

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3612]
Formatting eats up newlines by default, so any new lines in task messages are not displayed.
Add `white-space: pre-line` to keep newlines and collapse other whitespace. https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

In template : https://github.com/medic/medic-webapp/blob/master/templates/partials/reports_content.html
(and maybe other places?)

**Comment by browndav** [comment]
This is old enough that it's probably already superseded by conflicting design changes. Unless @amandacilek or @diannakane disagree, I'll go ahead and close.
