### ISSUE TITLE
Change time listed on Reports tab to be more fine-grained

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3613]
At some point during development of v2.x, we adjusted the time labels on reports in the Reports tab to be daily, so we'll see "today" for all reports that have come in today (as in the below screenshot).
![image](https://user-images.githubusercontent.com/1286381/27888318-443550d8-619a-11e7-87b0-d0e452d0ea63.png)

For PMs and partners who are checking instances daily to make sure that reports are coming in and the gateway is functional, it's difficult to know whether reports came in this morning or just a few minutes ago without clicking through several reports.

We'd like to change back to the granularity that we had in 0.4, where we showed minutes or hours ago if the report was submitted today, then moved on to days, months, etc.

Originally reported in https://github.com/medic/medic-projects/issues/2033

cc @christinewere @ngamita @henokgetachew @rosteve 

This will be scheduled for 2.14.

**Comment by SCdF** [comment]
I presume there is a reason that we changed it to have less granular?

Unless that reasoning no longer holds, would a solution that satisfies both situations be that the hover text over today etc shows the exact datetime (currently it just shows the date)?. Or even both the exact datetime and how many minutes / hours ago it was?

**Comment by sglangevin** [comment]
Let's find out what the reasoning for changing it was and take it from there. Your other ideas could be good options if we had a good reason for changing it. My guess is that the preference will be to see the more granular time so that users don't have to hover over each message to see the time.

**Comment by garethbowen** [comment]
This was done to fix #1947

As far as I see it, the options are:

1. Roll the change back, the times will get out of date until the item is rendered again (nav to a different tab and back, do a search, refresh the page, etc)
2. Roll the change back and reduce the existing refresh timer from 24 hours to 30 minutes or so
3. Roll the change back and implement some lightweight mechanism to update these dates every minute or two. I suspect they'll be get out of date throughout the UI so it might be a good idea to have a jquery function scan for all relative dates/days and update them if necessary.
4. Leave it as it is.

@sglangevin @SCdF Thoughts?

**Comment by sglangevin** [comment]
Thanks for the context @garethbowen. I'd be fine with 1 as a quick fix for now, though if 2 is easy and won't cause a performance hit on servers with a lot of data then we should do that. In the longer term, I'd like to do 3, but I think that can wait in the interest of keeping this issue small.

I have been wanting to do a livelist review as there are a number of small, related issues like this one that have to do with livelist not refreshing without changing tabs. I was thinking it would make sense to document all of those and fix them together, but let me know if you'd rather fix them as they come up.

**Comment by garethbowen** [comment]
Batching the issues sounds good, however this one is special. Most often the list needs to be updated because something in the database changed but with this one it's just a matter of another minute ticking by so it's a different kettle of fish from a dev perspective.

**Comment by sglangevin** [comment]
Ok, in that case, can we also make sure the sync status time is updating? That one is similar to this use case where nothing in the database changes but the time since last sync should update as time goes forward.

**Comment by alxndrsn** [comment]
@garethbowen is there a recommended path forward for this from your 4 options?

@sglangevin should this be a separate issue:

> can we also make sure the sync status time is updating?

**Comment by sglangevin** [comment]
I'd like us to pursue option 3, if it's not too much work. If we pursue that option, I think it should update relative dates/times throughout the app, which seems like it should include last sync time. We can split that into a separate issue if you think that makes more sense, though.

If option 3 is too involved, I'm fine with 1 or 2 (with a preference for 2). 

Another thought: We could also choose to show the time of the report (exact time, not relative time) if it came in today, relative day for anything in the last week, relative week for anything in the last month, and then relative month for anything beyond the month. I believe this is pretty much what we have currently, aside from showing the exact time if it came in today. Could be easier because then updating every 24 hours would work fine but might be harder to have special handling for things that happened today. @garethbowen curious to hear your thoughts on this approach.

It would look something like this (ignore updated nav, just showing this for the times/days):
![chw - 07 01 reports - main](https://user-images.githubusercontent.com/1286381/29733355-b692bfba-89ba-11e7-8d25-fa238c2bf4eb.png)

**Comment by garethbowen** [comment]
@alxndrsn @sglangevin I like your idea Sharon (let's call that option 5) - let's do it. We'll have to be careful making this change because we output relative dates throughout the UI.

We currently have two filters:

1. `relativeDate` for time and date (eg: 1 minute ago, yesterday, 3 weeks ago)
2. `relativeDay` for day only (eg: today, yesterday, 3 weeks ago)

To make the recommended change we should update the `relativeDate` filter so it outputs time if today, and relative dates if earlier or later than today, (eg: 10.16 AM, yesterday, 3 weeks ago).

Then we need to review all usages of either filter to make sure they're using the right one, eg: tasks are timeless so should use `relativeDay`, reports are not so should use `relativeDate`.

Be sure to use moment formatting for the time so it's locale sensitive (I'm not sure how to access it but it's `longDateFormat.LT` in the locale config).

**Comment by SCdF** [comment]
![image](https://user-images.githubusercontent.com/583851/31770506-1f943f80-b4d0-11e7-89f2-9ed24a387935.png)

**Comment by SCdF** [comment]
Location | Type | Change?
----|----|----
configuration_upgrade.html|relativeDate|no|
content_row_list_item.html|both|no|
header.html|relativeDate|I kind of think this should still be relative always 
messages_list.html|relativeDate|no|
missed-appointments.html|relativeDate|no|
upcoming-appointments.html|relativeDate|no|
upcoming-due-dates.html|relativeDate|no|

So `relativeDay` is only used in one place (LHS panel).

@garethbowen / @sglangevin  the only one I'm not a big fan of is that relative date for replication looks weird now.

master:
![image](https://user-images.githubusercontent.com/583851/31776504-a38fca6c-b4e3-11e7-9076-d8351c5a951b.png)
this branch:
![image](https://user-images.githubusercontent.com/583851/31776544-bfc31860-b4e3-11e7-950f-f57c60b64377.png)

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by SCdF** [comment]
Cool beans, I've used moment's locale stuff. If people want it configurable in the future we can add it, but if there is no call for it I'd rather not add more configuration for the sake of it.

Still interested in your thoughts about the two images I took above.

**Comment by garethbowen** [comment]
I'm fine with the images you took. It may look weird but it's more useful in that it won't become incorrect over time (until tomorrow). Approved and merged.

**Comment by sglangevin** [comment]
LGTM.
