### ISSUE TITLE
Exporting when filtered by report type exports more reports than are displayed in the web app

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3615]
To reproduce:
1. Go to the Reports/History tab on standard.app.medicmobile.org
2. Use the report type filter to filter by New Pregnancy
3. See that you have only New Pregnancy reports on the LHS
4. Click "Export"
5. Open your xml file in Excel
6. See that the export includes pregnancy and pregnancy visit reports (pregnancy visit reports shouldn't be there)

When a user filters by report type, only that specific type of report should be exported because the export should match what the user sees on the LHS.

Adding to the current milestone to see if we can get to this while other fixes to Export are happening.

cc @garethbowen

**Comment by garethbowen** [comment]
The problem is the current index splits on non-word characters, so "pregnancy_visit" splits to "pregnancy" and "visit" and returns for both. Working on it now.

**Comment by garethbowen** [comment]
Code review please @estellecomment

**Comment by sglangevin** [comment]
Working well in v2.13.0-beta.2. Moving to ready.
