### ISSUE TITLE
Work out a dashboard that works for us with horticulturalist

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3618]
Spawned from #3582 

We continue to need dashboard even with horticulturalist, because we need the config ui.

Work out:
 - Which Dashboard we're currently shipping in MedicOS (I believe when I checked we're extracting two `dashboard.couch` files : which one gets used, what source code does that align with?)
 - From that source code, which of the below is best / easiet
   - Ship existing dashboard as is, but hack up data so it thinks it's installed via garden (b/c otherwise you can't find the config ui)
   - Rip out the config ui and put it in our own couchapp / webapp
   - Rip out everything except the config ui and hard-code it to point to medic

**Comment by SCdF** [comment]
OK I think we can probably just drop dashboard completely and use this: https://github.com/json-schema-form/angular-schema-form

Here is our schema rendered in their system: http://schemaform.io/examples/bootstrap-example.html#/1a3e926acff03706a2b64950e8e3cf41

The form seems cool, as it allows us to override formatting if we want to, but we don't have to.

So it seems pretty legit. The library is 24kb minified, and is actively developed (mostly by one guy). They also have a (not touched since Feb but still) material design fork: https://github.com/json-schema-form/angular-schema-form-material

**Comment by SCdF** [comment]
Update as I haven't posted against this ticket for awhile:
 - Performance is I think not what it could be. I think the library that we used in Dashboard was faster at least
 - However, we can easily create forms and tabulate them to reduce how long it takes to render. It would also make the configuration clearer.
 - Buggggs. Maybe this isn't supported in the spec they're following, but at `array->object->array->object` (think messages inside schedules) the code starts to break down and render things incorrectly. I'm going to raise it with them and perhaps tinker with the code and see if it's an easy fix.

Worst case we look at another library, there are quite a few.

**Comment by SCdF** [comment]
I got tricked! (sort of). This library is under active development, but against a 1.0.0 version that is currently in alpha. The version that I've been pulling down from npm is a year old, and this is where the bugs are coming from (this is also why when I played with it online with the link above things worked better).

The question now, is do we use the alpha version (and possibly contribute to its stability and release)? Or look for another library that works out of the box.

I'm going to have a look around and see if there what our options are, but I'm interested in your thoughts @alxndrsn / @mandric / @garethbowen .

**Comment by alxndrsn** [comment]
I don't have a strong opinion about this.  I had a quick look at that generated form and it was very confusing, but perhaps that's a feature of our config format.

**Comment by SCdF** [comment]
Yeah it's not the best. I think we can make it better though when we manage it ourselves:
 - When can split it into shorter sections
 - We can control what is shown via manually specifying stuff in forms. What you clicked is just it going nuts with the entire schema, which probably isn't sensible or required.
 - There probably isn't a huge reason we couldn't refactor it pretty extensively, as long as we keep the changes to something that can be expressed programatically (for migration scripts).

**Comment by garethbowen** [comment]
I'm not keen on using alpha in production and I don't really want to block this based on factors outside of our control, so unless you think they're really close to going final, or you think we should help them finish, I'd find a different package.

**Comment by garethbowen** [comment]
@SCdF We discussed this a little in the weekly iteration call, and @abbyad recently said ["never save app_settings using Dashboard"](https://github.com/medic/medic-projects/issues/2559#issuecomment-318228949).

In part this is because there are bugs in Dashboard or our kanso.json configuration which mean it doesn't always update the configuration correctly. However it's also a workflow issue - if changes are made through Dashboard or the Configuration tab then the configuration in medic-projects isn't updated which apparently makes it hard for anyone to take over from the tech lead if necessary.

We have a few options...

1. Don't allow any configuration in app
2. Don't allow configuration via a generic UI (dashboard or horti) but keep the Configuration tab
3. Replace the generic UI with a supported no-known-bugs version (as you've been doing)
4. A complete rewrite to integrate with the medic-projects repo and the command line tool, (eg: split out the Configuration tab as a separate app that imports/exports files to disk ready for committing to the repo and importing with the command line tool).

@abbyad @henokgetachew I'd love your input here - what is our ideal configuration workflow?

**Comment by henokgetachew** [comment]
IMO number 4 is the most ideal.  We have had instances in production that have been out of sync with medic-projects.  Unless we do some sort of monitoring, there is no way to be sure about them right now.  If we're not able to do that, I think we should probably make the tool only perform display/import/export but not in-place-editing-and-saving for the configuration values - I realize that makes setting of simple things such as gateway numbers etc makes complicated..

**Comment by SCdF** [comment]
Number 4 is also (unsurprisingly) the most complicated, time consuming and challenging. To do this securely (IMO) we would have to stop using medic-projects and instead have individual repos (doesn't have to be git or github, just a storage location) for each partner. Otherwise, if one server got compromised they would have access to configuration for every single partner. After getting security right, if we're going to have a UI that interacts with and has expectations against a git repo we now need to manage merging, dealing with settings that aren't applied (do you let them sit on the git server, or do they need to be applied?), and probably more things if we step back and plan this out.

2 looks like the most sensible to me in the short term, with 4 being something we think about and plan for.

**Comment by SCdF** [comment]
Talking to Richard, there are times where they make small changes quickly to test something, like changing the gateway phone number. However, he acknowledges that these changes never make it back into git, and will be lost.

Our current app settings are unfortunate in this regard, as we have all settings smushed in with all others in one large blob, which requires an app re-deployment on every change.

I am still in favour of 2. We can expand what can be easily configured to contain some specific things if they are changed a lot, and if changing them is intended to be temporary. In general though, I would like to close this ticket in favour of a larger piece of technical design that would encompass:
 - Splitting configuration up into more manageable chunks
 - Allowing the app's configuration to be updated without having to download the entire ddoc again and restart the app
 - The design and construction of a *local* tool that would allow for user-friendly editing of configuration, including the existing useful schema documentation that works off a locally checked out git repo, and understands how to push configuration to a remote server. This would give us both a friendly UI to work with, but would stop us from being able to edit config from anywhere but the git repo.

**Comment by garethbowen** [comment]
Most little things can be done via the Configuration tab (eg: "gateway phone number" is in Configuration > Settings > Basic). Anything that needs to be changed frequently should be added to the Configuration tab somewhere. This solves the dashboard corrupting the settings issue, but doesn't address the settings not being committed issue.

Closing this issue would suit the dev team, but I want to make absolutely sure that the tech leads won't be seriously impacted if dashboard app settings goes away.

@ngamita Is there anything tech leads configure in dashboard app settings that they can't do in the Configuration tab? Would it be very helpful to have a readonly display of the settings? What about a settings import/export feature to make it easy to update medic-projects?

**Comment by ngamita** [comment]
@garethbowen i agree that we can make the dashboard app settings READONLY but we should keep the export feature as we at most cases don't have the latest versions on github to work with. For the import we now all understand that the dashboard corrupts the file and are now doing this through the script. So for the near future we can work with this only problem is the versioning will still be dependent on the TL to make sure they keep the files in respective medic-projects locations. One thing that i would highly recommend is a way revert to previous working version in case someone breaks anything.

**Comment by garethbowen** [comment]
Settings import/export to be done in #3868

@SCdF I believe this can be closed now - is that right?

**Comment by SCdF** [comment]
Correct!
