### ISSUE TITLE
Hide Collect XForms from filter list in History tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3625]
For instances that use Collect, TextForms and App-workflows we will have multiple items in the History/Report tab's form filter, as seen here:
![image](https://user-images.githubusercontent.com/789512/27930674-7c7b20dc-6265-11e7-8e01-5f1391b6b4a9.png)

In the image above there are 4 delivery reports:
1) XForm used for the app workflow
2) XForm served to the Collect app (not used for parsing)
3) JSON used to parse incoming Collect forms (using our JavaRosa parser)
4) JSON used to parse incoming TextForms

It is OK to show 1, 3, and 4, since those are individual submission that we may want to (de)select in the list. We want to hide 2, the XForm that is served to Collect, because we will _never_ have a form submission that matches this form definition (because all form submissions matching this definition are actually parsed according to the corresponding JSON form, item 3 above)

A longer term solution would be to parse the form using the XForm, but a short term solution would be to remove forms from the list if they have `doc.context.filter` set to false. This value should default to `true` if absent.

Related to https://github.com/medic/medic-webapp/issues/3607

**Comment by abbyad** [comment]
In setting up standard.app to test the Collect forms the filter is completely empty and I see this error in console: 
```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: form in forms | orderBy:'name | translateFrom' track by form.code, Duplicate key: p, Duplicate value: {"code":"p","name":"New Pregnancy"}
http://errors.angularjs.org/1.6.3/ngRepeat/dupes?p0=form%20in%20forms%20%7C…de&p1=p&p2=%7B%22code%22%3A%22p%22%2C%22name%22%3A%22New%20Pregnancy%22%7D
```

This means that the effect of this issue isn't having a form in the list that wont have submissions, but rather that the list doesn't show at all if Collect forms are being used (since they reuse the same form id as the JSON forms used for TextForms).

**Comment by sglangevin** [comment]
Do we need to reuse form IDs? That sounds like something we would want to avoid.

**Comment by abbyad** [comment]
Yes and no....

**YES:** The Collect form does need a corresponding JSON form, regardless of whether that form is used by TextForms or not. 

**NO:** Technically we can hack a Collect XForm to submit a form with a different ID by specifying a prefix with a different form code. 

From an earlier conversation with @alxndrsn it would seem to me that the effort of hacking and maintaining a XForm to have a different XForm ID vs JSON ID would be greater than filtering the Collect forms from the list. Also, having different IDs would still mean you can select a form in the list that will never have results, because the Collect form will be picked up by the JSON version.

**Comment by abbyad** [comment]
Ok, turns out https://github.com/medic/medic-webapp/issues/3625#issuecomment-315182868 was an error on my part in the form config.  I had changed the filename to match the form id (as per #3342) and that left a relic on couchdb with the same internal form id. 

**This issue is now back to having a form in the list that wont have submissions**

It is therefor not _as_ high a priority, and sorry for the confusion!

**Comment by abbyad** [comment]
Just thought I'd show what it actually looks like on standard.app when configured:
![image](https://user-images.githubusercontent.com/789512/28226993-178c6766-68a6-11e7-8337-5bcaf65edb21.png)

The duplicate names in the list are the Collect + App XForms. Selecting the Collect one will never show a result. The name shown in this list is the same as in Collect so it is not practical to rename it to something you wouldn't want to click.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by ngaruko** [comment]
LGTM. Please @abbyad have a second look and let us know if that is want the UI should look like.

**Comment by abbyad** [comment]
Testing on 2.13.0-beta.2, I got a prompt to reload the app which was expected on first load since it was updated. The proper number of forms are shown here (_the Collect is submitted same as Textforms, so it is expected that form 3 from the OP is also missing_):

![image](https://user-images.githubusercontent.com/789512/29012502-0d225440-7b0a-11e7-9d66-15c2bb414c3b.png)

I then got another prompt to reload the app and a duplicate forms now shows, which matches the Collect Xform that should be hidden:
![image](https://user-images.githubusercontent.com/789512/29012583-b14a856a-7b0a-11e7-86f8-15d850cfa8b2.png)

The only other difference between the two screenshots is that in the first it appeared as though there were no records found.

Returning for further investigation, which can be done on standard.app (I was logged in as `marc` but any user should do).

**Comment by garethbowen** [comment]
@abbyad To get the form to be hidden you have to update the form's context so `{ context: { collect: true } }`. Neither of those delivery forms had collect set on their context and when I set it as above the form disappeared as expected. Does this match your expectation?

**Comment by sglangevin** [comment]
This is working well in v2.13.0-beta.3 (I didn't test beta.2). Moving to Ready.
