### ISSUE TITLE
Generate scheduled messages just-in-time so changes to contacts are reflected in yet to be sent messages

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3627]
For longer-term message schedules, data can easily become stale between the time the schedule is created and the time the scheduled messages are sent. For example, you register a pregnancy today, the EDD is 6 months from now, and messages will be going out for the next 6 months. It's likely the CHW's phone number may change or the name of the mother may be updated in the app during those 6 months. For longer-term use cases, like immunization or growth monitoring, which go on for years, the likelihood is even higher.

We should generate schedules or scheduled messages just-in-time so that they reflect any changes to contacts that may have been made between the time someone is enrolled into a schedule and the time the messages go out.

**Comment by SCdF** [comment]
So there are two things here that I can see:
 - Data gets out of date sometimes
 - Config gets out of date sometimes

The first one is probably pretty easy to solve: just don't run the message through the templater until it's time to send it.

The second one sounds like a large architectural rewrite, though I'd need to look into it in more detail. But from my understanding we'd be moving from generating all scheduled messages upon receiving a registration, to either:
 - have a couchdb view of all open registrations, create live crons from them and then reset and recalcuate if app_settings ever changes
 - have a couchdb view of all open registrations, re-write to the doc them if app_settings ever changes[1]

With that in mind, it might be worth splitting into two tickets so we can get the first part done quicker.

[1] don't like this one while we still store schedules on the same docs that might be synced to phones. I know this is for sms projects, but at some point we'll do both and this could be nasty churn.

**Comment by sglangevin** [comment]
Thanks for the feedback @SCdF. I agree that it makes sense to split this into two as the first part is the priority but the second part would be good to do in the future.

**Comment by garethbowen** [comment]
This probably also solves #1479 and #638

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by sglangevin** [comment]
@ngaruko can you AT?

**Comment by sglangevin** [comment]
@ngaruko did you intend to close this one?
