### ISSUE TITLE
Update target widget cards and targets page layout

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3629]
TO DO:
- [x] set height of widget card to 180px (gets taller if there is more text)
- [x] set width of widget card to 350px (unless screen is smaller than 400px, in which case it should be 100% of screen width)
- [x] change background color of widget cards to white
- [x] set card border to 1px #E0E0E0
- [x] line breaks can be between words or between syllables (put a hyphen on the first line and the next syllable on the next line). No line breaks in the middle of a word.
- [x] on medium and large size devices, widget cards should have 4px rounded corners 
- [x] on small devices, widget cards should have square corners and stretch the full width of the screen
- [x] on medium and large size devices, widget cards should be 50px from the top header and 30px from each other
- [x] on small devices, no space between the top header and first widget and 8px between widgets

[More information in the design spec](https://docs.google.com/document/d/1mddzTrBV3QNctYKal2eGxWV5CNOUCYFEcDIQM4NrzQk/edit).

**Comment by amandacilek** [comment]
Just noting that the only major design change here happens at the 400px breakpoint - everything else is handled though content flow. 

400px is a current breakpoint of ours and so this is all fine for now. However when we get to the nav update early next year the breakpoint may end up changing to 480px (or some other number in a similar range that we all agree on).

**Comment by garethbowen** [comment]
@SCdF Two reviews (above) please!

**Comment by SCdF** [comment]
@garethbowen LGTM, I've left you the webapp one to merge (see comment)

**Comment by sglangevin** [comment]
This LGTM on desktop and Y4. @amandacilek did you want to do a quick review before we close this one? I can give you credentials for alpha.dev which is a good place to see how it looks.
