### ISSUE TITLE
Remove boilerplate tests for transition function signatures

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3630]
Lots of our transition unit tests check that the two required functions (`filter` and `onMatch`) exist with the require number of parameters. This is boilerplate we shouldn't have to write every time. It's also fallible because new transitions authors may not bother writing them.

Create a generic test that loops over all available transitions and tests the function signature.

**Comment by garethbowen** [comment]
Code review please @mandric

**Comment by SCdF** [comment]
This causes a bug in real-world situations because the test function hook was called recursively: https://github.com/medic/medic-sentinel/blob/master/transitions/index.js#L128

**Comment by SCdF** [comment]
@garethbowen https://github.com/medic/medic-sentinel/pull/141

**Comment by garethbowen** [comment]
Thanks @SCdF ! I should have run sentinel before merging...
