### ISSUE TITLE
Performance issues with multi_form_alerts

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3631]
`sentinel/transitions/multi_form_alerts.js` needs to bulk fetch hydrated docs. Currently `sentinel/lib/lineage.js` only has single doc fetch.

Implement bulk fetch hydrated docs.
We'll need to fetch lineage from `docs_by_id_lineage` view one by one, but after than the contacts/parents to link can all be fetched in one bulk query.

(from #3416)

**Comment by estellecomment** [comment]
Additional performance issue : 
`getReportsWithinTimeWindow` queries reports_by_date` view, within the time window. On big instances, and/or with long time window, that could be a lot of reports and cause OOMs. 

Make the `getReportsWithinTimeWindow` and the report counting run on batches of reports.

**Comment by garethbowen** [comment]
@SCdF Review please good sir!

**Comment by SCdF** [comment]
Back to you @garethbowen.

Also note that you need a medic-webapp build to make sure e2e tests still pass etc.

**Comment by estellecomment** [comment]
Doesn't really need AT.
