### ISSUE TITLE
Analytics need to differentiate multi_form_alerts messages from others

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3635]
from #3416

`multi_form_alerts` messages should be tracked in analytics. Currently there's no way to tell from the `data_record` which messages are from an alert and which are other types.

Add a field to make the difference queryable by analytics.

**Comment by michaelkohn** [comment]
According to @estellecomment , the alerts will show up in the `tasks` field of the `data_record`.  From what I can tell, the only other message type we have in there are auto replies, but there may be others.  Ideally we could add a `type` field at the same level as the `state` field, which is the same as what we do for `scheduled_tasks`.

# 
![screen shot 2017-07-12 at 3 27 12 pm](https://user-images.githubusercontent.com/10096985/28142684-e9260778-6716-11e7-9ac7-8dcac2e41794.png)

#    

![screen shot 2017-07-12 at 3 30 38 pm](https://user-images.githubusercontent.com/10096985/28142793-61722216-6717-11e7-8c3f-95344ce91a81.png)

**Comment by michaelkohn** [comment]
Thinking about it some more.... I'm not sure if we will be recording any history related to these messages anywhere other than on the `data_record`, but if not, we might want to include somewhat detailed information for traceability purposes.  

- Would I be able to know which other records were counted when generating this alert?
- If I wanted to know the number of suspected measles outbreaks (for example), would I have to look through all `data_records` and search for the existence of a specific alert message text?  

I'm thinking we might want to have a high level **`type`**: _auto_reply, alert, etc.._ and a more detailed **`alert_type`**: _suspected_measles, suspected_ebola, etc..._ 

@derickl I know you did some dashboard work related to CBDS, can you think of anything else that would be useful to have in the JSON?

**Comment by derickl** [comment]
I can't come up with anything at the moment. @samkanga @katanu any thoughts on the above? What else would you love to look at around the alerts sent?

**Comment by estellecomment** [comment]
> we could add a `type` field at the same level as the state field

SG!

> which other records were counted when generating this alert

We can store an array of the counted reports' uuids in a field, yeah.

>a more detailed `alert_type`: `suspected_measles`, `suspected_ebola`, etc...

We can add an alert `name` field in the app_settings, that will get added as a `name` (or `alert_name`) field.

Three new fields, off we go!

**Comment by samkanga** [comment]
@estellecomment, it would be helpful to dis-aggregate the suspected diseases by 1) gender, and 2) by age i.e.  Birth to 2 months, above 2months but below 5 years (iCCM), and above 5 years. Separately, since the list of the suspected diseases grows over time, would it be possible to drill down on disease specific counts to get a line list of the individuals suspected to have a given condition. For example if I have two suspected cases of polio and I click on the specific polio bar, then I would get a listing of the 2 specific cases.

**Comment by michaelkohn** [comment]
@samkanga great to have some context, thanks!

> dis-aggregate the suspected diseases by 1) gender, and 2) by age  
  
I think we will be able to do this as long as we have the array of counted reports' as Estelle mentioned above.  We would need to use that array to find all the data_records that were used to trigger the alert, then get the patient information for each of those data_records, which would then give us access to all the biographical information about the person, so yes, we would be able to disaggregate by gender/age.  I suppose we could consider having an array of patient_ids as well, it would certainly make this sort of disaggregation easier/quicker, but isn't really great for  database normalization.

@samkanga regarding your questions about drilldown/clicking on the polio bar, I think those are probably questions more from the KlipFolio side of things (unless we are doing something in the app that I am not aware of).  To answer the question with KlipFolio in mind, I don't think it's possible to drill down at the touch of a bar, but there are some drilldown capabilities using tables.

**Comment by michaelkohn** [comment]
Another thing I just thought of is how we will deal with subsequent alerts.  For example... say our threshold for a particular alert is 5+ occurrences.  If a 6th occurrence happens within the given timeframe, I imagine we send another alert and our array of data records has the original 5 plus the new 6th.

@estellecomment, are my assumptions correct? And if so, is there a way to know if we are 'adding on to the existing alert' vs. triggering a new one?  That would probably be another useful piece of info to have.

**Comment by estellecomment** [comment]
> we send another alert and our array of UUIDs on the 6th data_record has the original 5 UUIDS plus the new 6th UUID (but we don't go back and update the array on the original 5th data_record that triggered it)

That's exactly right @michaelkohn .

> is there a way to know if we are 'adding on to the existing alert' vs. triggering a new one?

You can check the list of counted reports, and see if they contain the same alert with a subset of the same counted reports. The list of counted reports will be in chronological order, so the first one in the list will be the report just preceding the one you're looking at.
As the time window slides forward in time though, you may have an alert triggered that has new reports but dropped old ones (because they dropped out of the time window). In this case does it count as a repeat or not?
(all this would be easier with a diagram :D)

I can do this by code, but you could also do it in postgres I think (or is it too complicated?). It sounds like something that I'd want to do dynamically, not save it in reports. What do you think?

**Comment by estellecomment** [comment]
@garethbowen can you review https://github.com/medic/medic-sentinel/pull/144 please?

**Comment by estellecomment** [comment]
Here's an example @michaelkohn .
In this example, `threshold` is 2, and 3 reports were counted. The latest report (#3) is  `7931e34f-9731-4be1-8503-f60b728488e1`.
There were 2 phone numbers specified, so two messages added to report.
Here is the `tasks` field on the latest report:
```
"tasks": [
    {
      "type": "alert",
      "alert_name": "suspected_cholera",
      "countedReports": [
        "6b3c6cff-06c6-474d-8bc4-ab31d995ba88",
        "7931e34f-9731-4be1-8503-f60b728488e1",
        "f678dbd3-e7db-4dfb-b61f-71a217eda08b"
      ],
      "messages": [
        {
          "to": "<intl format phone>",
          "uuid": "ac28b2e3-6cfb-4c8f-a6be-3b03ce962091",
          "message": "hello alert"
        }
      ],
      "state": "pending",
      "state_history": [
        {
          "state": "pending",
          "timestamp": "2017-07-19T13:10:23.647Z"
        }
      ]
    },
    {
      "type": "alert",
      "alert_name": "suspected_cholera",
      "countedReports": [
        "6b3c6cff-06c6-474d-8bc4-ab31d995ba88",
        "7931e34f-9731-4be1-8503-f60b728488e1",
        "f678dbd3-e7db-4dfb-b61f-71a217eda08b"
      ],
      "messages": [
        {
          "to": "<another intl format phone>",
          "uuid": "cc8d886c-0083-4159-a571-e41b73fe9f2b",
          "message": "hello alert"
        }
      ],
      "state": "pending",
      "state_history": [
        {
          "state": "pending",
          "timestamp": "2017-07-19T13:10:23.649Z"
        }
      ]
    },
 <other task messages>
]
```
Note that `countedReports[0]` is the current report itself, since it was also counted towards the threshold.

If you look up `countedReports[1]`, which is the report just before the current one (`7931e34f-9731-4be1-8503-f60b728488e1`), the `countedReports` field is : 
``
      "countedReports": [
        "7931e34f-9731-4be1-8503-f60b728488e1",
        "f678dbd3-e7db-4dfb-b61f-71a217eda08b"
      ]
``
Makes sense?

**Comment by garethbowen** [comment]
Back to you @estellecomment

**Comment by estellecomment** [comment]
@garethbowen Added webapp PR : https://github.com/medic/medic-webapp/pull/3690 and made changes to sentinel PR : https://github.com/medic/medic-sentinel/pull/144
Assigning back to you since you requested changes.

**Comment by garethbowen** [comment]
Both good. Merge away!

**Comment by estellecomment** [comment]
AT for @michaelkohn, I'm guessing, so assigning

**Comment by michaelkohn** [comment]
@estellecomment can you let me know where to test this and where I can see the current config  (so I can know which forms to submit that would generate the alerts and see the new fields)? I tried to follow the github issue tree to find some documentation on how to configure the alerts and came across this https://github.com/medic/medic-webapp/blob/master/kanso.json#L398 but I wasn't sure if there was a UI somewhere that I could see the config?

**Comment by sglangevin** [comment]
You can use alpha.dev for testing as we don't have a beta out for this release yet. We may need to update alpha.dev first.

**Comment by michaelkohn** [comment]
OK.  Please let me know when I should go in and test it (ie, do you need to update alpha.dev).  I logged in (to alpha.dev) and was surprised to see no data in it, not sure if that is expected.  Am I also expected to configure the alerts myself?  Happy to give it a crack, but need some info on how to do it.

**Comment by sglangevin** [comment]
Let's look at this together this afternoon. We can also loop in the tech lead for the CBDS project for help in config and testing.

**Comment by estellecomment** [comment]
It should appear in the Dashboard app_settings page, under "Multi-form Alerts". The kanso.json file that you linked is what feeds into that page.

Note that we're going to change the config slightly, in https://github.com/medic/medic-webapp/issues/3678, you maybe wait for that to be done, I'm doing it next...

**Comment by garethbowen** [comment]
Closing for AT.

**Comment by ngaruko** [comment]
Were you able to AT this @michaelkohn ?

**Comment by michaelkohn** [comment]
@ngaruko nope, but I'll try to schedule some time with @sglangevin this week to go through it, especially now that #3678 is done as well.

**Comment by abbyad** [comment]
Here is an example of a [doc with an alert message](https://standard.app.medicmobile.org/_couch/_utils/document.html?medic/0f0ae88d16b963c067b79f950d2cdcdb):

![image](https://user-images.githubusercontent.com/789512/29689226-7846c244-88f0-11e7-9875-e3eb91c0ed60.png)

Seems to be differentiable to me. What do you think @michaelkohn?

**Comment by michaelkohn** [comment]
Yep... works for me @abbyad @ngaruko .  I was able to identify `data_records` that have an alert task and interrogate the list of counted reports.  

Here is a starter query for those interested.
```SQL
WITH tasks_CTE AS
(
	SELECT
		doc->>'_id' AS uuid,
		json_array_elements((doc->'tasks')::json) AS tasks
	FROM
		couchdb
	
	WHERE
		doc->>'type' = 'data_record'
)

SELECT
	uuid,
	tasks->>'alert_name' AS alert_name,
	tasks->>'counted_reports' AS counted_reports
FROM
	tasks_CTE

WHERE
	tasks::jsonb @>  '{"type":"alert"}'::jsonb
;
```

**Comment by sglangevin** [comment]
Thanks @michaelkohn et. al. Moving to ready.
