### ISSUE TITLE
Merge api full stack tests into webapp

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3636]
We have e2e and integration tests in api which are executed as part of the webapp build because they rely on having the full stack running. This is confusing to me because along with the webapp e2e tests this makes three different places where we're defining full stack tests. It also means sometimes they get missed when running tests locally.

There is also some code duplication caused by api tests starting api just like webapp e2e tests do. Also starting api twice takes twice as long so it slows down the build unnecessarily. Merging these together would mean api only needs to be started once.

Move api e2e and integration tests into medic-webapp. See if it makes sense to refactor them to run in protractor (just like medic-collect tests in webapp e2e currently do). Make one grunt task in webapp which can run all full stack tests in one go.

**Comment by garethbowen** [comment]
I'm not finding the time to get to this. I think it should still be done but I'm dropping it out of the iteration.

**Comment by SCdF** [comment]
@garethbowen please confirm, but I think I resolved this ticket when I merged the api e2e tests into the webapp ones

**Comment by garethbowen** [comment]
Yes correct!
