### ISSUE TITLE
Only serve collect-specific XML forms to collect

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3642]
When requests are made to `/api/v1/forms` with the header `X-OpenRosa-Version: 1.0` set, only forms with `context.collect: true` should be served.

**Comment by garethbowen** [comment]
It'd be good to add a test to the medic-collect e2e test for this: https://github.com/medic/medic-webapp/blob/master/tests/protractor/e2e/medic-collect.js

**Comment by abbyad** [comment]
For completeness here is what it looks like in Collect if you see all the forms, until this is resolved:
![image](https://user-images.githubusercontent.com/789512/28227683-103591b0-68a9-11e7-832d-1555575a48eb.png)

Notice that you have the app and Collect forms together, including the contact forms.

**Comment by estellecomment** [comment]
This is going to break existing Collect instances, make sure to notify tech leads properly...

**Comment by ngaruko** [comment]
Are we able to AT this @alxndrsn @abbyad  and to check that as @estellecomment suggested we are not 'breaking existing Collect instances'? and tech leads are notified @henokgetachew @Enock1990

**Comment by sglangevin** [comment]
It may not be a big issue because most projects aren't downloading forms from the instance. That is changing currently, though, so we'll need to write up some information for tech leads.

@ngaruko this can be tested using the Standard version of Collect that was just released. I'm responsible for writing up documentation for tech leads.

**Comment by sglangevin** [comment]
Assigning to myself to test and write documentation for tech leads.

**Comment by sglangevin** [comment]
LGTM. @alxndrsn is it possible to update medic-configurer so that it will automatically add `"collect": "true"` to the properties file of all collect forms? That would make this much easier for tech leads.

**Comment by sglangevin** [comment]
I'm closing this and marking it ready. I've also filed a feature request in the medic-configurer repo: https://github.com/medic/medic-configurer/issues/20
