### ISSUE TITLE
Stop writing remote checkpoints

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3644]
When [PouchDB 6.3.0 is released](https://github.com/pouchdb/pouchdb/issues/6579) investigate [disabling writing of remote checkpoints](https://github.com/pouchdb/pouchdb/issues/6308). 

> We checkpoint because we do not want to run entire replications from scratch every time you load your local application, a checkpoint says 'this is where we left off, start from here'.

> We write checkpoints to both the client and the server to handle the case where either gets deleted, if you know the server will never be deleted then its safe to skip writing the remote ones which is what we are talking about here, with the flag enabled we would still be writing local ones.

Make sure there's no downside first...

**Comment by alxndrsn** [comment]
Looks like a big winner.

**Comment by garethbowen** [comment]
PouchDB 6.3.2 has just been released. This reduces the chance of id conflicts, allows for the above performance improvement, and has a bunch of tweaks. Thus I'm scheduling this for 2.13.0 despite being close to our release date.

NB when upgrading we need to fix angular-pouch depending on an old (6.0.x) version of Pouch. Ideally this would be by getting a PR merged into angular-pouch, but if not either fork or patch it so the version we run in the app is the version we've defined in package.json, not whatever angular-pouch is locked to.

**Comment by garethbowen** [comment]
There are outstanding issues with the 6.3.4 release so test thoroughly and consider delaying this update to 2.14.0.

**Comment by garethbowen** [comment]
Moving to 2.14.0 to give PouchDB 6.3 time to stabalise...

**Comment by alxndrsn** [comment]
`6.3.4` is still the latest release of pouch.  Are there particular problems you were concerned about?

**Comment by garethbowen** [comment]
Nope... looking at it now.

**Comment by garethbowen** [comment]
I tested by loading a contact and then saving a change to that person and watching the network tab.

Before:

![checkpoints-before](https://user-images.githubusercontent.com/2064938/29516365-362e6aa2-86c4-11e7-918d-f1393ad6d2f8.png)

After:

![checkpoint-after](https://user-images.githubusercontent.com/2064938/29516371-3961ec80-86c4-11e7-8c7e-da9252404e3f.png)

This reduces the number of requests from 7 to 3. Reloading started the replication from the correct place proving that the local checkpoint is working.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by sglangevin** [comment]
Assigning to @ngaruko for AT.

**Comment by ngaruko** [comment]
Any clue on how to AT this @garethbowen @alxndrsn ?

**Comment by garethbowen** [comment]
@ngaruko I said how to test, and gave a couple of screenshots in this comment: https://github.com/medic/medic-webapp/issues/3644#issuecomment-323714481

**Comment by alxndrsn** [comment]
Interested to know if checkpointing _still works_ after this change.  I'll be following this thread, and investigating further.
