### ISSUE TITLE
inadvertent cached data 

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#3648]
https://github.com/medic/medic-projects/issues/2473

**Comment by garethbowen** [comment]
Assigning to @alxndrsn to continue where @mandric left off.

**Comment by alxndrsn** [comment]
I'm assigning this more widely given that I also have another **`Priority 1`** issue in progress: https://github.com/medic/medic-webapp/issues/3856

**Comment by SCdF** [comment]
Resolved, see projects issue for more detail.
