### ISSUE TITLE
Use transition.init everywhere

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3655]
We recently added an init function that gets called when the transition is loaded. This means we can do validation of configuration early rather than waiting for a change to fire the transition. I've done a quick audit to check if other transitions could benefit from this approach and found the following:

- [ ] https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L382
- [ ] https://github.com/medic/medic-sentinel/blob/master/transitions/registration.js#L252

Fix these and anywhere else you think could benefit.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
AT: A badly configured registration transition fails when sentinel boots or when the config changes, not when the transition runs.

**Comment by sglangevin** [comment]
@henokgetachew would you also be able to AT this one? Assigning to you, but feel free to reassign if needed.
