### ISSUE TITLE
Add permissions to control whether or not users see the call and message buttons on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3657]
Currently, all users see the call and message buttons on the bottom bar of any person's profile in mobile view, as in the below screenshot.

![image](https://user-images.githubusercontent.com/1286381/28207640-2ad6de2e-68aa-11e7-829c-b693482fc4c0.png)

For the upcoming UNICEF deployment, the partner needs to be able to hide the call and message buttons. We'd like to add permissions to control whether to show or hide those two buttons.

**Comment by rmhowe** [comment]
@sglangevin which types of users do the call and message icons need to be hidden for?

Also I'm assuming that the default setting should be that all users can see both of these icons?

**Comment by sglangevin** [comment]
We should have the option to hide them for any user type, though we normally only would adjust those permissions for the national manager (full access) user or the district manager (restricted to their place) user. Yes, the default should be that all users see both icons.

**Comment by rmhowe** [comment]
Ok great, do we want to hide the icons for both mobile and desktop view?

Also just checking, what's the purpose of hiding the icons? I'm assuming not to prevent users from calling/messaging because the phone number will be right there if they did want to call/message, unless this issue should also include hiding the phone number?

**Comment by sglangevin** [comment]
> Ok great, do we want to hide the icons for both mobile and desktop view?

Yes. Though I believe the message icon only shows up in mobile view currently.

> Also just checking, what's the purpose of hiding the icons?

It was something a partner asked for because they didn't want it to be easily accessible for CHWs. Whether or not the phone number displays there is configurable, so you could also choose to hide that.

**Comment by sglangevin** [comment]
Should these automatically show up on the permissions page or I need to update config? They don't seem to have appeared after upgrading beta.dev to 2.15.0-beta.1.

![image](https://user-images.githubusercontent.com/1286381/37503605-98d64890-2896-11e8-8fdf-e48c7bfbf5b7.png)

**Comment by sglangevin** [comment]
Since @rmhowe is out, assigning to @garethbowen - feel free to redistribute.

**Comment by garethbowen** [comment]
@sglangevin My guess is that your existing configuration hung around it's just not used any more. We should clean this up in a migration.

**Comment by garethbowen** [comment]
Unassigning myself so anyone can pick it up.

**Comment by rmhowe** [comment]
@sglangevin the new permissions seem to now be showing on `beta.dev`, maybe a caching issue?

**Comment by sglangevin** [comment]
Yeah - could be that or could be related to some deployment issues we've been having with gardener. Closing for now!
