### ISSUE TITLE
Update RHS floating action bar

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3676]
Design spec section: https://docs.google.com/document/d/1c-silPsrR92opiQaGU05te8MzsFnUjYCPUpsi2Vo9Vc/edit#bookmark=id.oqwnny4f639w

Just a few updates needed here to improve usability.

- [ ] Change color of bar to dark blue (#013C57) - this applies to all floating action bars on the RHS, so any bar on a person or place profile page
- [ ] Add text labels beneath all icons. H5 size (14px) bold, colored white
- [ ] When inactive, text is white at 85% opacity and icons are white at 70% opacity
- [ ] When active or on rollover, text is white at 100% opacity and icon is white at 100% opacity

**Comment by garethbowen** [comment]
@sglangevin We're not doing this any more right? Can we close it?

**Comment by sglangevin** [comment]
Yep - this one is obsolete. Closing.
