### ISSUE TITLE
Rename the multi_form_alerts transition

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3677]
It's more accurate to call it the `multi_report_alerts` transition. This will need to be changed in the transition itself, the configuration, examples, and all documentation.

**Comment by garethbowen** [comment]
Scheduling for 2.13.0 so it can be sorted before anyone starts configuring it.

**Comment by estellecomment** [comment]
(Can't think of how to name this, `✨fancy_alerts🌈`)

**Comment by estellecomment** [comment]
oooh, genius idea : `alerts` ?

**Comment by garethbowen** [comment]
I'm really struggling with this. I'm thinking about what makes this transition different to `conditional_alerts` and it's the fact that it's context aware. I'm going through a thesaurus... what about one of: `context_alerts`, `trend_alerts`, `overview_alerts`, `environment_alerts`, `landscape_alerts`?

**Comment by sglangevin** [comment]
In case it's helpful to have more votes, I liked `multi_report_alerts`. Isn't this also different from `conditional_alerts` because it looks at more than one report?

**Comment by garethbowen** [comment]
> Isn't this also different from conditional_alerts because it looks at more than one report?

That's what I meant by "context aware" - it can look at more than just the latest report and make a decision based on that additional information.

**Comment by garethbowen** [comment]
@estellecomment Let's go with "multi_report_alerts" unless you have any objections? I'll leave it for you so as not to conflict with your work in #3678

**Comment by estellecomment** [comment]
yeah, no strong feelings, wfm. Will do after 3678.

**Comment by estellecomment** [comment]
PRs : 
sentinel : https://github.com/medic/medic-sentinel/pull/149
webapp : https://github.com/medic/medic-webapp/pull/3726 (needs bumping sentinel)

**Comment by garethbowen** [comment]
One small change then merge away!
