### ISSUE TITLE
Improve batching performance of the multi_form_alerts transition

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3678]
As of #3631 the transition counts documents in batches so we don't have to load all documents from the database at the same time. Unfortunately the `recipients` field can be configured to be a script which takes the full list of matching reports to generate a list of message recipients. This means we still need to keep all matching reports in memory to send to the script.

Check with stakeholders first but I think this can be changed to a script which can be executed over the documents one at a time. The results can then be merged and made unique. This means we can retrieve a batch, process it completely, discard it and retrieve the next batch.

**Comment by garethbowen** [comment]
Scheduling in 2.13.0 so the configuration schema can be modified before anyone starts using it.

**Comment by estellecomment** [comment]
Defining the recipient per-report should not be an issue, since you can achieve the same recipients with a different config.

There's another problem though : the message text displays info from all counted reports (potentially), so we'd need all reports fed into the template. 
In practice it'll make for varied and possibly huge message length, which is bad, so we need to define better specs. Discussing on #outbreak-surv.

**Comment by estellecomment** [comment]
@garethbowen can you review https://github.com/medic/medic-sentinel/pull/148 please?

**Comment by sglangevin** [comment]
@garethbowen @estellecomment any tips on how to AT this one?

**Comment by garethbowen** [comment]
It's not easy. If you have an instance with lots of reports it'd be great to try this out with a wide date range so lots of reports are found and make sure it doesn't crash.

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by abbyad** [comment]
Reassigning to @ngaruko for AT since he'll be better equipped to have a fleshed out test environment.

**Comment by sglangevin** [comment]
@ngaruko this is needed in order for us to release v2.13.0 which we are trying to do this week. Can you AT in the next day or two please?

**Comment by ngaruko** [comment]
Apparently we need an instance with lots of reports to test this. Unfortunately `alpha.dev` has no more data and is failing to update. Will check with @henokgetachew for the update and ways to replicate or import data from `standard.app`.

**Comment by abbyad** [comment]
The [load_messages.js](https://github.com/medic/medic-webapp/blob/2.13.x/scripts/load_messages.js) script is really useful to quickly add lots of data on an instance.

**Comment by sglangevin** [comment]
@ngaruko we are still waiting on this one so that we can release 2.13.0. Can you please AT?

**Comment by sglangevin** [comment]
@ngaruko can you please AT this or assign to someone else? It is holding up the release of 2.13.0.
