### ISSUE TITLE
include character counts on message textareas in config

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#368]
would be useful for user to know how close they are to 160 characters per message sms limit.

![screen shot 2013-09-14 at 5 03 39 pm](https://f.cloud.github.com/assets/25641/1144336/9a1bade8-1d89-11e3-97d4-7357abc05ebf.png)

**Comment by abbyad** [comment]
Now that we can deal well with multipart SMS I am not sure this is as high priority, but still a nice-to-have, although perhaps now in the outgoing messages portion of the new translations portion.

**Comment by mandric** [comment]
Might be nice to know how many SMS messages will be sent out, so when you go over 160 byte limit we might display "2 messages" or something.

**Comment by abbyad** [comment]
Similar to this, issue #859 includes SMS count for outgoing messages.

**Comment by garethbowen** [comment]
These config screens have been deleted. Closing.
