### ISSUE TITLE
alpha fails to deploy

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3681]
Somehow when installing the alpha the code ends up in the wrong place in gardeners working_dir so it fails to start. 2.12.x deploys correctly so something must've changed since then.

**Comment by garethbowen** [comment]
This is blocking release so it's a priority for us.

**Comment by garethbowen** [comment]
My best guess is that our version of npm (3.10.10) can't handle org dependencies (@medic/xxx). My next step is updating npm to the latest and testing again.

**Comment by garethbowen** [comment]
Theory confirmed and alpha.dev is back up. I've worked around this by moving away from using org packages in api. This is fine for now. The proper fix is to either use a different deployment system that doesn't rely on npm in production (horticulturalist), or update medic-os to npm v5 once we're comfortable that it's stable.

@mandric Assigning to you for acceptance testing - is this acceptable for now?

**Comment by ngaruko** [comment]
@mandric ... is this deployment acceptable for now?

**Comment by mandric** [comment]
@garethbowen just wondering if there is a way to test this in travis, for example always having a travis test config that matches the nodejs and npm versions that are installed on the medic-os that we use for deployment.  So we might catch these things in CI as well.

**Comment by garethbowen** [comment]
@mandric The problem is we need npm 5 to build our app, but npm 3 to deploy our app. Once we have horti we won't need npm to deploy at all so the issue will go away. My ultimate goal is to have CI actually download the latest medic-os docker image and install the webapp into it and then run the e2e tests on that. That way we're testing the entire deployment stack (gardener/horti) as well as the code. I don't want to spend too much time here because anything we do for gardener will be thrown away once horti is done. Does that make sense?

**Comment by ngaruko** [comment]
Will move this to ready....pending the new deployment mechanism
