### ISSUE TITLE
Avoid "more than one element found for locator" in webdriver tests

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3698]
e.g. `[13:28:41] W/element - more than one element found for locator By(css selector, #delete-confirm .submit) - the first result will be used`

I don't see a use for this voluntarily (you can use `first-child` or something if you really want the first occurrence), so they're likely to be accidental. So we should weed these out completely. 

I see them happening when there's hidden elements, so when viewing the page it looks like it's a single one but it's actually several.

**Comment by estellecomment** [comment]
@garethbowen please review https://github.com/medic/medic-webapp/pull/3701

**Comment by garethbowen** [comment]
Awesome.
