### ISSUE TITLE
Sync status cut off in mobile view

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3703]
There used to be space below the sync status but now it's running into the bottom edge of the hamburger menu. Could be due to the fact that Configuration Wizard wraps to a second line. Seen on v2.12.0. I can't currently test this on latest alpha because alpha.dev has no data in it.

![image](https://user-images.githubusercontent.com/1286381/28549726-0a2a3c9a-7091-11e7-8a54-ac4d036a5907.png)

**Comment by garethbowen** [comment]
It's a bit of an unusual one because to get the sync status you need to be an offline user and to get the configuration wizard you need to be someone with the `can_configure` permission which is usually an admin. But I've made it a little wider just in case...

**Comment by ngaruko** [comment]
Rare scenario as Gareth mentioned. But @sglangevin  are you able to AT this now that we have a couple of bites of data on alpha.dev?

**Comment by sglangevin** [comment]
@garethbowen now the menu has a scrollbar in it, but only on desktop. On mobile it stretches to fit everything and looks good. Can the hamburger menu be taller on desktop to avoid the scrollbar?

![image](https://user-images.githubusercontent.com/1286381/29340930-754ca55c-81d6-11e7-8e68-1237baec6097.png)

**Comment by garethbowen** [comment]
The menu has a max height of 350px. I can change this to a max-height of 80% of the screen. If we remove the max-height altogether then there's no way to see the sync status if it's pushed below the fold. 

Does that work for you @sglangevin ?

**Comment by sglangevin** [comment]
Yeah, that should work. Let's try it.

**Comment by sglangevin** [comment]
Working well in v2.13.0-beta.7. Moving to ready.
