### ISSUE TITLE
Password Strength Validation Errors

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3704]
Related to https://github.com/medic/medic-webapp/pull/3608. When the user enters less than 8 characters (‘passwor’), they get the ‘8 characters long’ error 
![image](https://user-images.githubusercontent.com/6979995/28550066-9f60cbca-7132-11e7-96df-55ac0dc6f903.png)
. Then add one more (‘passwor2’), there is another '  password is too easy to guess’ error, with no indication of what is an acceptable level of complexity .
![image](https://user-images.githubusercontent.com/6979995/28550047-7b36fd8c-7132-11e7-97d6-0b7a34fb4f28.png)
. It would be helpful, from a user’s perspective to have the first error with all needed info to nail the password second time around (minimum combo that will work). As a bonus, are we able to validate at the front-end level and disable the the `Submit` button until the password strength is good enough?

**Comment by ngaruko** [comment]
re: #1472

**Comment by garethbowen** [comment]
The second message was recently updated to:

> The password is too easy to guess. Include at least 1 uppercase letter, 1 number, and 1 special character.

@sglangevin Can we close this as fixed now?

**Comment by sglangevin** [comment]
Yes, let's close this one. I tested to make sure that the advice I included in that message is accurate so it should be a good guide for users for now.
