### ISSUE TITLE
Disable 'Select' and 'Export' buttons when there are no reports

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3705]
When there are no reports, the two buttons are still enabled.
![image](https://user-images.githubusercontent.com/6979995/28550376-68d27282-7134-11e7-9784-255f12416d1b.png)

**Comment by garethbowen** [comment]
Back to you @wtekeu

**Comment by wtekeu** [comment]
Ready for another round of review

**Comment by ngaruko** [comment]
LGTM. Tested on `[gamma.dev](https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/)` v3.3
