### ISSUE TITLE
GET /api/v1/forms is broken if trailing slash

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3707]
`curl https://<user>:<pass>@<instance>/api/v1/forms` works.
`curl https://<user>:<pass>@<instance>/api/v1/forms/` gets `{"error":"not_found","reason":"no_db_file"}`

**Comment by ngaruko** [comment]
Any idea how to AT this @garethbowen ? 
`curl https://<user>:<pass>@<instance>/api/v1/forms/` still returns an error.
`{"error":"not_found","reason":"Database does not exist."}`  while the non-slash request works.

**Comment by garethbowen** [comment]
Yup - bug.

**Comment by newtewt** [comment]
Seeing the redirect message when curling with the slash and adding `-L` follows along the redirect getting the data as expected.
