### ISSUE TITLE
multi_form_alert messages need alert name, threshold and timewindow

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3715]
e.g. '{{alertName}} alert : more than {{numReportsThreshold}} reports in the last {{timeWindowInDays}} days'

Add alertName, numReportsThreshold, timeWindowInDays to template context.

**Comment by estellecomment** [comment]
@garethbowen can you review please?

NB For merging : merge sentinel PR, then bump sentinel in medic-webapp and commit the change to webapp PR, then commit webapp PR.

**Comment by garethbowen** [comment]
Merged. Nice one!

**Comment by abbyad** [comment]
I can get the transition to run, but with some minor issues.

The config from the [documentation](https://github.com/medic/medic-docs/blob/d49a12adf6ae6219325a979b819245dc4bb789b9/configuration/transitions.md#multi_report_alerts) fails:

```
2017-08-15T16:43:41.617Z - error: error: Validation failed for multi_report_alerts transition
error: Alert number 0, expecting fields: is_report_counted, name, num_reports_threshold, message, recipients, time_window_in_days
Alert number 0, expecting fields: is_report_counted, name, num_reports_threshold, message, recipients, time_window_in_days
Alert number 0, expecting fields: is_report_counted, name, num_reports_threshold, message, recipients, time_window_in_days
Alert number 0, expecting fields: is_report_counted, name, num_reports_threshold, message, recipients, time_window_in_days
Alert "undefined", expecting "time_window_in_days" to be an integer, eg: "time_window_in_days": "3"
Alert "undefined", expecting "num_reports_threshold" to be an integer, eg: "num_reports_threshold": "3"
error: Failed loading transition "multi_report_alerts"
```

Trying to resolve it I encounter the following:
1. The fields are in camel case, but the transition expects those fields in snake_case.
1. The settings are missing the required "name" field.
1. Uses `countedReports[0]`, but taking a hint from the kanso documentation it should use the `.0. ` notation, and with snake case as well: eg `counted_reports.0.`
1. I could not get the phone numbers (or any values) from `counted_reports` as used in the example, and it isn't clear why I would use it over new_reports. I had a bit more success changing it to `new_reports`.
1. It is not clear to me what `new_reports` is. In kanso doc it says "the counted reports which haven't been messaged about yet". Given that in this context there are no "old" reports, perhaps it should just be `reports`.
1. Must access report values using `fields`. Eg while taking into account the notation change above, instead of `{{countedReports[1].patient_id}}` it should be `{{new_reports.1.fields.patient_id}}`
1. Cannot get some values from the contact using `counted_reports` or `new_reports`, perhaps because this is a post #2635 world, or perhaps because of transition order. eg Cannot get value for `new_reports.0.contact.parent.parent.name`

**Comment by estellecomment** [comment]
Great feedback, thanks @abbyad ! On it.

**Comment by estellecomment** [comment]
Sorry, the doc in kanso.json is updated, but the one in medic-docs isn't. I'm updating it.

> 1. The fields are in camel case, but the transition expects those fields in snake_case.

updated doc

> 2. The settings are missing the required "name" field.

updated doc

> 3. Uses countedReports[0], but taking a hint from the kanso documentation it should use the .0. notation, and with snake case as well: eg counted_reports.0.

updated doc

> 4. I could not get the phone numbers (or any values) from counted_reports as used in the example, and it isn't clear why I would use it over new_reports. I had a bit more success changing it to new_reports.

updated doc, you should use new_reports. 

> 5. It is not clear to me what new_reports is. In kanso doc it says "the counted reports which haven't been messaged about yet". Given that in this context there are no "old" reports, perhaps it should just be reports.

Updated the documentation with a little timeline to explain the different types of reports. I'm hoping it helps, do let me know.

> 6. Must access report values using fields. Eg while taking into account the notation change above, instead of {{countedReports[1].patient_id}} it should be {{new_reports.1.fields.patient_id}}

You can use whatever is in the report (i.e. the `data_record` doc in the db). Maybe depending on your config, you get `patient_id` in various places...? Not sure.

> 7. Cannot get some values from the contact using counted_reports or new_reports, perhaps because this is a post #2635 world, or perhaps because of transition order. eg Cannot get value for new_reports.0.contact.parent.parent.name

Hmmm, could be several things : 
 - Does the updated documentation help, is `new_reports.0` the right var to use?
 - If the transition to associate the contact hasn't run yet, then yes it could be an issue... Does `new_reports.0.contact._id` yield an id? (Once the contact is associated by sentinel, the `parent` and `parent.parent` field should be fetched all right, even in the post #2635 world, that shouldn't be a problem...)
 - maybe check the corresponding docs in the db in futon? To check that your doc *does* have a `contact.parent.parent` once hydrated

@abbyad Assigning you the 3 small PRs could you review? It's mainly documentation : 
https://github.com/medic/medic-docs/pull/28
https://github.com/medic/medic-webapp/pull/3782
https://github.com/medic/medic-sentinel/pull/157

**Comment by abbyad** [comment]
Thanks Estelle, the timeline did in fact help, although it still took me a bit of time to wrap my head around it!

Item `7` still seems to be an issue, as you can see from the following templated message from a [submitted form](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0f0ae88d16b963c067b79f950d1d7154):
```
new_reports.1._id                                 0f0ae88d16b963c067b79f950d19e849
new_reports.1.contact._id                         db505de9-0f8b-4345-b857-8d63996cfbb6
new_reports.1.contact.name                        Alice
new_reports.1.contact.parent._id                  aea2b982-ca1c-4046-9faf-e569c25832c6
new_reports.1.contact.parent.name                 
new_reports.1.contact.parent.parent._id           7ffa1f0e-e969-4163-a180-8189a0697c54
new_reports.1.contact.parent.parent.name          
new_reports.1.contact.parent.parent.parent._id    e4f5f9fe-c44a-4d76-aa8b-47998e3e2be1
new_reports.1.contact.parent.parent.parent.name   
```

I used `1` to make sure it is not a transition ordering issue since the report is already associated to a contact. Using `0` in a [separate test](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0f0ae88d16b963c067b79f950d1d87a6) I got the same result. 

This seems to indicate an issue with hydrating the contact, and perhaps the fact that the first one is hydrated is a helpful clue.

**Comment by estellecomment** [comment]
Man, awesome bug report @abbyad, thank you :)
On it!

**Comment by estellecomment** [comment]
Fixed a hydration bug, and it's now working for me locally : 
```
[new_reports.0._id f84efeef-6b38-490a-8c0b-233b3cfd2598] 
[new_reports.0.contact._id 3c0c4575468bc9b7ce066a279b022e8e]
[new_reports.0.contact.name Test Clinic Contact]
[new_reports.0.contact.parent._id 3c0c4575468bc9b7ce066a279b02366e
[new_reports.0.contact.parent.name Test Clinic ]
[new_reports.0.contact.parent.parent._id 3c0c4575468bc9b7ce066a279b007091]
[new_reports.0.contact.parent.parent.name Test Health Center
[new_reports.0.contact.parent.parent.parent._id3c0c4575468bc9b7ce066a279b002828
[new_reports.0.contact.parent.parent.parent.name Test District ] 
------ 
[new_reports.1._id 657aff77-b3a0-4c1e-8f8b-fa844cb6103f] 
[new_reports.1.contact._id 3c0c4575468bc9b7ce066a279b022e8e]
[new_reports.1.contact.name Test Clinic Contact]
[new_reports.1.contact.parent._id 3c0c4575468bc9b7ce066a279b02366e]
[new_reports.1.contact.parent.name Test Clinic ]
[new_reports.1.contact.parent.parent._id 3c0c4575468bc9b7ce066a279b007091
[new_reports.1.contact.parent.parent.name Test Health Center]
[new_reports.1.contact.parent.parent.parent._id3c0c4575468bc9b7ce066a279b002828]
[new_reports.1.contact.parent.parent.parent.name Test District ]
```
It should fix the problem with `new_reports.1` on standard [that you reported](https://github.com/medic/medic-webapp/issues/3715#issuecomment-322881354).

The problem with `new_reports.0` is different (looks similar but it's actually using different hydration code), and I'm not reproducing it locally, so I'm not sure. Still poking at it.

**Comment by estellecomment** [comment]
Aha, it's SMS vs. xform. 
No problem with xform : https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/de748598-a13a-4a14-ab4d-5b681cdd1d6b
Problem with SMS : 
https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0f0ae88d16b963c067b79f950d1e296f

**Comment by abbyad** [comment]
Standard is still on beta 4 which doesn't include your latest fix for #3789. I'll upgrade to latest 2.13 beta (5) and retest.

**Comment by abbyad** [comment]
On 2.13.0-beta.5 it appears to hydrate well, but only for `new_reports.0`, and not `1`

From this [test report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0f0ae88d16b963c067b79f950d20fd44):
```
new_reports.0._id 0f0ae88d16b963c067b79f950d20fd44 
new_reports.0.contact._id db505de9-0f8b-4345-b857-8d63996cfbb6
new_reports.0.contact.name Alice
new_reports.0.contact.parent._id aea2b982-ca1c-4046-9faf-e569c25832c6
new_reports.0.contact.parent.name Alice&#39;s Area
new_reports.0.contact.parent.parent._id 7ffa1f0e-e969-4163-a180-8189a0697c54
new_reports.0.contact.parent.parent.name Adrian&#39;s Health Center
new_reports.0.contact.parent.parent.parent._id e4f5f9fe-c44a-4d76-aa8b-47998e3e2be1
new_reports.0.contact.parent.parent.parent.name Anthony&#39;s District
 
new_reports.1._id 0f0ae88d16b963c067b79f950d19e849 
new_reports.1.contact._id db505de9-0f8b-4345-b857-8d63996cfbb6
new_reports.1.contact.name Alice
new_reports.1.contact.parent._id aea2b982-ca1c-4046-9faf-e569c25832c6
new_reports.1.contact.parent.name 
new_reports.1.contact.parent.parent._id 7ffa1f0e-e969-4163-a180-8189a0697c54
new_reports.1.contact.parent.parent.name 
new_reports.1.contact.parent.parent.parent._id e4f5f9fe-c44a-4d76-aa8b-47998e3e2be1
new_reports.1.contact.parent.parent.parent.name 
```

(The encoding of special character will be opened in a separate issue)

**Comment by estellecomment** [comment]
All merged to master, back to AT!

**Comment by abbyad** [comment]
In [medic-docs](https://github.com/medic/medic-docs/blob/12d90bf40d016591faf90855ef87de43c1347924/configuration/transitions.md) it has the following as a recipient: `"new_report.contact.phone", // sender of each report in new_reports`

Using that for a [test report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/0f0ae88d16b963c067b79f950d2175fc) I get:
`multi_report_alerts : Could not find a phone number for "new_report.contact.phone". Message will not be sent. Error: "new_report is not defined"`

**Comment by abbyad** [comment]
This probably needs to wait for #3789.

**Comment by abbyad** [comment]
Testing on beta 7 and seems to be working well. Needs more acceptance testing to confirm that it is Ready, but no known issues yet.

**Comment by garethbowen** [comment]
@abbyad @estellecomment I have no idea what state this issue is in. Is it ready for 2.13.0 (and therefore should be closed and marked for AT), or is it open and blocking and should therefore be in "required" in the [project](https://github.com/medic/medic-webapp/projects/11)? Please update...

**Comment by estellecomment** [comment]
It's back in dev since Marc found a bug. I moved it back to the "Required" column in the project. Thanks for checking in!

**Comment by estellecomment** [comment]
Aaaaactually that bug is not from beta7, because the comment date is from before the build date for beta7. I'm pretty sure it's gone from beta7. 
So putting this back to AT.

**Comment by abbyad** [comment]
The AT for #3416 was accidentally being done here... this issue in particular has sufficiently been tested to move to Ready.

Test config:
```
  "multi_report_alerts": [
    {
      "name": "flag",
      "num_reports_threshold": 3,
      "time_window_in_days": 7,
      "is_report_counted": "function(report, latestReport) { return latestReport.contact.parent.parent._id === report.contact.parent.parent._id; }",
      "message": "{{num_counted_reports}} patients with {{alert_name}} reports in {{new_reports.0.contact.parent.parent.name}} over the last {{time_window_in_days}} days. Threshold is {{num_reports_threshold}} reports. New reports from {{#new_reports}}{{contact.parent.name}}, {{/new_reports}}since the last alert.",
      "recipients": [
        "+14169876543",
        "new_report.contact.phone",
        "new_report.contact.parent.parent.contact.phone"
      ],
      "forms": [
        "F"
      ]
    }
  ]
```
