### ISSUE TITLE
Person & place profile page UI changes

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3719]
Relevant section of design spec: https://docs.google.com/document/d/1c-silPsrR92opiQaGU05te8MzsFnUjYCPUpsi2Vo9Vc/edit#bookmark=id.8fsndpp9evtf
 
Summary of changes:
All devices (condition cards, tasks card, history card, profile info card):
- [x] Each card should contain the title so that the title appears against a white background instead of above the card
- [x] Height of header area is 45px. Bottom edge of header area has a 3px grey line (#BCBEC0). All headers are white with black text.
- [x] All rows are 70px tall, separated by 1px grey lines (#E0E0E0)
- [x] Header and row text starts 20 px from left edge
- [x] Space between all cards is 16px and grey (same grey as our normal background color)
- [x] If there is no label for a field, value should take up the full height (see example with "Belongs to" label removed in mockups)

All devices (profile info card):
- [x] Person or place icon is 60 x 60px. Located 20px from the top of card and 5px from left edge
- [ ] Value should appear on the same line as the label when there is 1 field per line on mobile or up to 2 fields per line on desktop
- [x] Move "Primary contact" label to the line below the name and put the yellow star to the left of the "Primary contact label" ([more details on spacing and size of profile info in zeplin file](https://app.zeplin.io/project/57d311edb055084578d006ec/screen/594998e64bc1358782acde64))
 
Desktop:
- [x] Increase the gutter space between the LHS and RHS to 30px (all pages will be updated to match)
- [x] 30px of gray space between the top bar and the profile card (see mockup in comments below)
- [x] Round outer four corners of all cards to 4 px (if possible, change the rounding of the RHS on the reports tab to 4pm rounding as well)
- [x] Add 1px grey border (#E6E6E6) to every card (see additional mockups in the spec linked at the top of this issue)
 
Relevant mockups:
Profile info (mobile)
![image](https://user-images.githubusercontent.com/1286381/28304420-3d8f3b32-6bb7-11e7-8405-36aebc2f86d8.png)
 
Profile info (desktop)
![image](https://user-images.githubusercontent.com/1286381/28304424-45b9a05e-6bb7-11e7-9fa4-be9627ca10ee.png)
 
Condition card (mobile)
![image](https://user-images.githubusercontent.com/1286381/28304433-4ddfe6c6-6bb7-11e7-81d8-b9fe115fc20a.png)
 
Tasks & History (mobile)
![image](https://user-images.githubusercontent.com/1286381/28304459-7c17f330-6bb7-11e7-9ce2-2fa701abc8a8.png)

**Comment by garethbowen** [comment]
NB: All the heights above are to be `min-height` allowing for the content to overflow if required.

**Comment by amandacilek** [comment]
Update to this spec based upon latest designs:

Desktop:
Increase the gutter space between the LHS and RHS to 22px (matches reports/history tab).

This is now 30px instead of 22px. So there is a 30px space between LHS and RHS content, and the RHS also has 30px buffer along the top (between RHS and page header). @SCdF

**Comment by sglangevin** [comment]
@amandacilek can we update the comment at the top of this issue so that it is accurate? I get the part about increasing the gutter space but I'm not sure what you mean by the 30px buffer on the RHS. Was the spec also updated?

**Comment by amandacilek** [comment]
This is what I mean: 
![screen shot 2017-09-11 at 10 17 17 am](https://user-images.githubusercontent.com/26235957/30287589-812b6c96-96da-11e7-8a7e-0b92187d1d7e.png)

**Comment by garethbowen** [comment]
Code review please @alxndrsn . The linked PR also fixes #3736

**Comment by sglangevin** [comment]
This looks really cool! Some feedback:

- Looks like we are missing the name of the person or place in mobile view:
![image](https://user-images.githubusercontent.com/1286381/31197043-b075b57e-a904-11e7-8e94-ac1d2f07e407.png)

- In mobile view, there should be no space between the top bar and the profile info card. Actually, this needs to be fixed on the people, tasks and history tabs so that it's consistent with the targets tab.

- The "Primary contact" label should be next to the person's name in desktop view instead of on the next line.

- I'm curious to understand why the values and labels are not next to each other in the profile section. Was that not possible to implement?

- @amandacilek @garethbowen should we remove the "Belongs to" label?

@amandacilek feel free to add any other feedback if there are additional changes we should make before moving this to ready.

**Comment by sglangevin** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
> Looks like we are missing the name of the person or place in mobile view:

Fixed.

> In mobile view, there should be no space between the top bar and the profile info card. Actually, this needs to be fixed on the people, tasks and history tabs so that it's consistent with the targets tab.

Fixed.

> The "Primary contact" label should be next to the person's name in desktop view instead of on the next line.

Done.

> I'm curious to understand why the values and labels are not next to each other in the profile section. Was that not possible to implement?

It's possible to implement but hard to control from a design perspective. If you have a very long label or a very long value you end up having heaps of line wrapping, and because the columns line up this goes on to affect all the other rows too. All the designs I've seen actually go the other way around where the two column label/value layout is used for desktop and the one column layout used for mobile for exactly this reason. 

> should we remove the "Belongs to" label?

I've made that configurable - if you don't include a `label` property in the configuration then the label won't be rendered (it used to render an empty label taking up vertical space unnecessarily).

**Comment by garethbowen** [comment]
Back to you @sglangevin

**Comment by sglangevin** [comment]
Cool, LGTM! Moving to ready.
