### ISSUE TITLE
Add a new date filter that allows for display of dates in DD Month format

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3721]
In order to make dates like EDD or next appointment date clearer to our users, we'd like to add a new date filter to be used in configurable profile cards that allows us to display dates in DD Month format (e.g. 11 December). Since we already have one called `simpleDate`, perhaps we could call this one `dayMonth`? I'm open to other naming suggestions of course, this is the best I could do off the top of my head.

**Comment by garethbowen** [comment]
This didn't make it in to 2.14.0 - moving to 2.15.0

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by ngaruko** [comment]
Just checking with this one @alxndrsn . Are you still working on it or is it ready to AT? Thanks
