### ISSUE TITLE
Change our default font size to 16px

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3722]
Design spec: https://docs.google.com/document/d/13emD5Zhh59qElEfq5VG7oMJWhSWCvmtKUMg8rttgZxI/edit#bookmark=id.2rqo6i4tujng

16px is the current standard and will help make our app easier to read across the board. 16px should be 1 rem and we can base our other sizes off of this.

**Comment by garethbowen** [comment]
@sglangevin I think this is a duplicate of #3597

**Comment by sglangevin** [comment]
Didn't realize that one included the change in font size. I'd like for that to be part of 2.14.0 if possible. I'll close this one as a duplicate.
