### ISSUE TITLE
Primary contact  is showing the UUID

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3723]
Steps to reproduce:

1. login alpha dev as admin
2. create a 'restricted' user
3. login as that user
4. primary contact shows a UUID instead of a name

![image](https://user-images.githubusercontent.com/6979995/28650222-482e14c8-72ce-11e7-980b-79d0d3bbefbd.png)

**Comment by sglangevin** [comment]
Adding to the current milestone - needs to be fixed for 2.13.0.

**Comment by garethbowen** [comment]
This is a configuration issue. The "person" isn't part of the district hierarchy so the restricted user is replicating the district but not the primary contact. To fix this, make the person be a child of the district.

**Comment by sglangevin** [comment]
@garethbowen I've just reconfirmed and the person is part of the district hierarchy so it's not a configuration issue. Check out user mission_health on alpha.dev. The associated place is Mission Health Center and the associated person is Sarah Jones (primary contact of Mission Health). I can PM you the password.

**Comment by ngaruko** [comment]
Does it have anything to to with #3598 @garethbowen ?

**Comment by garethbowen** [comment]
Code review please @mandric

**Comment by sglangevin** [comment]
Fixed in 2.13.0-beta.2. Moving to ready.
