### ISSUE TITLE
When creating users, dropdowns for place and associated contact no longer display hierarchy information

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3727]
When creating users in the UI (especially on an instance with a lot of data), it's essential to be able to see where a place or associated contact exists in the hierarchy to make sure you are selecting the correct one. I'm guessing this has to do with the linked contacts change.

Here's how it looked previously (from standard.app, v2.12.1):
![image](https://user-images.githubusercontent.com/1286381/28686511-488cc88c-72c0-11e7-8398-913d1f08826c.png)

And how it looks on alpha.dev:
![image](https://user-images.githubusercontent.com/1286381/28686522-544eede4-72c0-11e7-83bd-b27eb371ac5f.png)

**Comment by garethbowen** [comment]
This also affects other areas of the UI such as creating a new place and sending a message.

**Comment by garethbowen** [comment]
Code review please @mandric

**Comment by sglangevin** [comment]
Fixed in select2 in 2.13.0-beta.2. Moving to ready.
