### ISSUE TITLE
Message content row improvements

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3732]
Builds on the changes listed in #3731. [Full design spec](https://docs.google.com/document/d/13emD5Zhh59qElEfq5VG7oMJWhSWCvmtKUMg8rttgZxI/edit?ts=5980ade8#heading=h.bgeqr7hcjuto).

In this issue, we're simply changing the order of the content for the messages. Each message in the list should have either two or three lines (depending on whether the sender is a contact in the Medic app):
- First line: name of sender (same as before)
- Second line: first few words of the message, with ellipsis at the end as needed
- Third line: breadcrumbs for the sender (if they are a known contact)

Other changes:
- [x] Unread messages should have a horizontal blue bar at the top right of the content row (see mockup 2 below). Line is 50px long, 4px thick, and color is #007DC7.
- [x] Unread messages should have a bold, blue relative date/time on the right (see mockup 2 below). Color is #007DC7 and it's 14px and bold.

Notes:
- Font sizes and weights for the left hand side text match the standard ones described in #3731, so no changes there
- For the right hand side (timestamp), read messages have the normal gray color as in #3731

### 1 - Read message, known sender:
![image](https://user-images.githubusercontent.com/1286381/28887382-d12e644c-7771-11e7-9719-321e6cae9b43.png)

### 2 - Read message, unknown sender:
![image](https://user-images.githubusercontent.com/1286381/28888873-0901bc2a-7777-11e7-8565-f845686100cb.png)

### 3 - Unread message, known sender:
![image](https://user-images.githubusercontent.com/1286381/28888948-46ba647c-7777-11e7-848d-d1e77945c973.png)

### 4 - Unread message, unknown sender:
![image](https://user-images.githubusercontent.com/1286381/28888883-10daffec-7777-11e7-9f40-aee32131efc5.png)

**Comment by garethbowen** [comment]
@sglangevin @amandacilek Should unread reports have a yellow border in the top right too? Currently unread reports and messages are styled consistently and it'd be nice to keep the style consistent.

**Comment by amandacilek** [comment]
I was thinking unread reports would be treated identically to unread
messages (meaning the line in upper right would be blue).

Amanda Cilek | Interaction Designer
Medic Mobile <http://www.medicmobile.org/>  +1 319 530 6830
@*M*edic <http://www.twitter.com/medic>  Facebook
<https://www.facebook.com/MedicMobile>

**Comment by garethbowen** [comment]
Thanks @amandacilek . I realised it's covered in another issue, so I deleted my comment.

**Comment by sglangevin** [comment]
Looks good! Moving to ready.
