### ISSUE TITLE
Configurable profile field UI changes

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3736]
Builds on the changes listed in #3719.

Configurable profile fields (other than the ones in the contact profile section) are the only ones that do not follow the default laid out in the issue linked above:
- First line: field label, 16px (not bold)
- Second line: field value, 16px, bold

Mockup:
![image](https://user-images.githubusercontent.com/1286381/28697969-bfc79948-72f4-11e7-9c87-427e37d73c59.png)

**Comment by garethbowen** [comment]
@sglangevin Should the first line of the description reference #3719 instead of #3731 ?

**Comment by sglangevin** [comment]
Yes, sorry about that. You are right, I should have referred to #3719.

**Comment by garethbowen** [comment]
Fixed.

**Comment by sglangevin** [comment]
I realized that this issue was not written as clearly as it could have been. The intention was for this styling change to apply to the configurable condition cards on profiles (things like active pregnancy, past pregnancy, immunizations, etc.) but not to the profile card at the top of the page (the one with Medic ID, Notes, Belongs to, etc.). Can we change the styling of the profile fields back to bold labels and normal weight values?

So in the screenshot, the top section with the person icon should have bold labels and normal weight values but the Pregnancy card looks correct.

![image](https://user-images.githubusercontent.com/1286381/31197876-59235bd4-a907-11e7-91f9-d7cf089912f5.png)

**Comment by sglangevin** [comment]
Back to you @garethbowen

**Comment by garethbowen** [comment]
This has been discussed further here: https://github.com/medic/medic-webapp/issues/3731#issuecomment-334280657

**Comment by garethbowen** [comment]
@sglangevin This has been reverted as part of #3731. Returning to AT.

**Comment by sglangevin** [comment]
LGTM.
