### ISSUE TITLE
Write e2e tests against medic-api for medic-gateway endpoint

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3738]
In light of https://github.com/medic/medic-api/pull/185, we need a more clearly-defined contract between gateway and api.

**Comment by garethbowen** [comment]
This endpoint is a priority for us. Scheduling for 2.15.0

**Comment by sglangevin** [comment]
Moving to 3.0.

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by garethbowen** [comment]
No AT required.

**Comment by alxndrsn** [comment]
I have other tests written for this which are not yet passing.

**Comment by alxndrsn** [comment]
Blocked by #3019.

**Comment by alxndrsn** [comment]
Completed by #4110.
