### ISSUE TITLE
No SMS replies when reporting on people created in app, unless registration form previously submitted

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3740]
As reported in https://github.com/medic/medic-projects/issues/2397, responses are not sent for patient reports if the person is created in app, unless a registration report has already been submitted for them.

This appears to be a missed edge case for acceptance testing of https://github.com/medic/medic-webapp/issues/3401

## Observed
- Validation messages are created, no problem here.
- Response messages for registration forms are OK.
- Response messages for patient reports (`patient_reports[x].messages`) are OK if the person was created using a report (not the case when person is created in facility using app)
- Response messages for patient reports are **not** created for those created in the app UNTIL after you submit a registration form for this ID (eg a pregnancy registration form)

## Theory
The `accept_patient_reports` processes responses only if the ID is found in the `registered_patients` view, and people created in the app are not in that view unless a "registrations" report is submitted for them.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by garethbowen** [comment]
This will need to be backported to 2.12.x and 2.13.x

**Comment by SCdF** [comment]
NB: for 2.12.x I had to manually merge due to ES6 refactoring. Commit here: medic/medic-sentinel@512d460

**Comment by SCdF** [comment]
Merged and backported to 2.12.x and 2.13.x

**Comment by sglangevin** [comment]
Tested this on 2.12.2-beta.1 and it's working well. Thanks for the quick turnaround on this!
