### ISSUE TITLE
Monitor bundle size

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3741]
Our compiled JS is massive and it's really easy to inadvertently make it more massive by including a bundle that depends on lots of other bundles which are all browserified in. Bloat in our app makes life difficult for users trying to update over poor internet connections.

Find a way to make it more obvious when a change results in a larger bundle size. This shouldn't be a blocker because some changes are worth the additional file size, but we need to be aware of the tradeoff.

Consider using [this bundlesize module](https://github.com/siddharthkp/bundlesize#2-build-status) which shows a warning in travis when your branch results in larger bundles than master.

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

If this is approved I'll set up [integration with GH](https://github.com/siddharthkp/bundlesize#2-build-status) so it'll show status in PRs.

**Comment by alxndrsn** [comment]
👍

**Comment by garethbowen** [comment]
Merged and configured... let's see how it goes!
