### ISSUE TITLE
accept_patient_reports transition is clearing messages for unrelated registrations

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3742]
As described in https://github.com/medic/medic-projects/issues/2584 when accept_patient_reports queries for registrations it uses the `doc.fields.patient_id`. Usually the validations are configured to stop empty patient_ids before they get this far, but if for whatever reason the validation isn't configured then the query returns _all_ registrations in the system. The transition then goes on and clears all registrations' messages.

Make sure that if a report has no patient_id then no messages are cleared.

**Comment by garethbowen** [comment]
Code review please @SCdF 

This needs to be backported to 2.13.x and 2.12.x

**Comment by SCdF** [comment]
Merged and backported to 2.12.x and 2.13.x

**Comment by sglangevin** [comment]
Tested using the same validation that was clearing messages for the affected projects and this is working well. Moving to Ready.
