### ISSUE TITLE
Release 2.13.0-beta.1 once Sharon has deployed 2.12.2-beta.1

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3745]
Need to wait until @sglangevin has deployed because we can only have one beta.

_(Can't wait for Horticulturalist to solve this!)_

**Comment by sglangevin** [comment]
2.12.2 was released today so we can get back to building a new 2.13.0-beta. Handing it back to you, @SCdF.

**Comment by SCdF** [comment]
Done.
