### ISSUE TITLE
Horticulturalist local mode

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3747]
We want to be able to use Horticulturalist on local machines.

It should be very little effort to use. Perhaps an npm package. Perhaps checking out a repo and running a script. Someone who isn't too familiar with coding should be able to run it though.

**Comment by alxndrsn** [comment]
```sh
npm install horticulturalist
COUCH_NODE_NAME=couchdb@localhost \
  COUCH_URL=http://admin:pass@localhost:5984/medic \
  horti --local --bootstrap
```

Modify/remove env vars as required.

**Comment by sglangevin** [comment]
Assigning to @ngaruko for AT.

**Comment by ngaruko** [comment]
Any clue on how to AT this @alxndrsn? Is `npm install horticulturalist` meant to be run in a specific directory (getting error like `saveError ENOENT: no such file or directory, open '/Users/bede/package.json'` and other warnings....and further down: `horti: command not found`...

**Comment by SCdF** [comment]
@ngaruko you want to use `npm install -g horticulturalist` to make it a global command you can use and not something that installs itself into a particular directory.

**Comment by ngaruko** [comment]
LGTM. Will probably need a bit more documentation before release!

**Comment by alxndrsn** [comment]
> Will probably need a bit more documentation before release!

It would be really helpful to give clear example of what you had problems understanding about the tool.  From my point of view, "more documentation" in general is unhelpful, but if we can identify the _right_ documentation, or places where the tool can be improved to be more ergonomic, then that's really helpful feedback.
