### ISSUE TITLE
Error when viewing person profiles in Nepali or Bambara that prevents configurable profile cards from appearing

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3753]
For some reason, this only applies to Nepali and Bambara. Other languages (French, Spanish, Hindi, Swahili) are working normally.

To reproduce:
1. Log in as a full access user
1. Change your language to Nepali
1. Navigate to any person's profile page
1. See that the profile cards do not appear

Missing profile cards:
![image](https://user-images.githubusercontent.com/1286381/28897262-c23af6b2-7794-11e7-99e2-41e80babd267.png)

How it looks in English:
![image](https://user-images.githubusercontent.com/1286381/28897292-e236f858-7794-11e7-949d-e7f29f777885.png)

Console errors:
![image](https://user-images.githubusercontent.com/1286381/28897219-93c58dce-7794-11e7-9283-5d5d137184ad.png)

inbox.js detail:
![image](https://user-images.githubusercontent.com/1286381/28897225-9c01dd12-7794-11e7-8c2e-9a5bf2af2e42.png)

**Comment by sglangevin** [comment]
Not sure if this is related, but I also cannot access any actions on the profiles when I'm logged in as a user with locale set to Nepali. The action button is grayed out.

**Comment by garethbowen** [comment]
For some reason when the "contact.profile" translation is missing it's thrown an error rather than just logging a warning like usual. The workaround is to provide this translation, but I'll work out how to get it to go back to just warning. 

This may be related to #3473

**Comment by garethbowen** [comment]
I think there's a difference between `null` and empty string which might be why I had a hard time reproducing #3473 - empty string works perfectly, but `null` blows up.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
PR LGTM, merged.

**Comment by garethbowen** [comment]
Backported to 2.13.x

**Comment by sglangevin** [comment]
@garethbowen everything is working except for person profiles in Nepali. I'm not sure what the issue is.

Missing profile info:
![image](https://user-images.githubusercontent.com/1286381/29293724-ef4c46d6-8100-11e7-8375-fde0f30fd36f.png)

![image](https://user-images.githubusercontent.com/1286381/29293749-0ba0d018-8101-11e7-9409-fa1b3d4e1c1f.png)
![image](https://user-images.githubusercontent.com/1286381/29293749-0ba0d018-8101-11e7-9409-fa1b3d4e1c1f.png)

I downloaded my console log as well, in case that is useful. Let me know and I can share it.

**Comment by garethbowen** [comment]
Code review again please @SCdF 

This needs to be backported to 2.13.x and the webapp submodule updated.

**Comment by SCdF** [comment]
Merged and backported.

**Comment by sglangevin** [comment]
This is still broken for me in Chrome on desktop. Do I need to re-upload translations during AT?

**Comment by sglangevin** [comment]
On further inspection, this seems to be broken on standard.app but working on other instances (all on 2.13.0-beta.7). This points to an issue with Standard translations or config. I'm going to move this to Ready. cc @abbyad

**Comment by sglangevin** [comment]
The issue on standard.app was resolved by adding a translation for the `contact.profile` key. Not sure why that wasn't on Standard or why that was still causing issues after these fixes, but it's now working for me.
