### ISSUE TITLE
Update medic's pyxform fork inline with upstream and push relevant new features back

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3756]
1. determine what the upstream repo should be (likely https://github.com/xlsform/pyxform; possibly https://github.com/uw-ictd/pyxform)
2. understand medic's added features
3. write tests for medic-specific features into `medic-configurer`
4. rebase medic's `pyxform` onto upstream
5. share any general new features we implemented upstream (refactor as required)

**Comment by alxndrsn** [comment]
1. upstream repo: https://github.com/xlsform/pyxform
2. Medic changes:
```
* Set up console_scripts mapping for CLI module usage
* Fix to work on mac
* Fix medic specific type
* Support medic's tel type
* Don't validate; medic xpath functions not supported
* Support all medic types
* Ignore workspace folders
* Add medic specific types
* Allow non unique section names
* Merge remote-tracking branch 'refs/remotes/uw-ictd/master'
* Added reference to XForms for Medic Collect docs
* Note on default value breaking tests
* Remove build info since we aren't testing with CI
* Context for the fork
* Add SMS attributes to instance
```
3. existing `medic-configurer` form conversion tests should be sufficient

**Comment by alxndrsn** [comment]
I've published this to a new branch, `medic-conf-1.5`, and made this the default in github.

It didn't make sense to publish this to `master`, as it changes the whole tree.

**Comment by alxndrsn** [comment]
cc @abbyad

**Comment by sglangevin** [comment]
@abbyad over to you for AT.

**Comment by abbyad** [comment]
Conversions work well as tested via medic-conf 1.5.6, so good to go from an AT perspective.
