### ISSUE TITLE
When a report creates an additional doc, that doc should have a `reported_date` added automatically

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3760]
With #2912 implemented, we now have the ability to create additional documents when a form is submitted. However, these additional documents do not have a `reported_date` and a `reported_date` is required in order for them to be replicated to the server. This can be worked around by putting in a field called `reported_date` but then it has a date that is not in the correct format.

We should correct this so that these new docs get a normal `reported_date` when they are created.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by garethbowen** [comment]
Requires a backport...

**Comment by SCdF** [comment]
LGTM @garethbowen, back to you for merging / back porting

**Comment by garethbowen** [comment]
Merged, backported, ready for AT.

**Comment by sglangevin** [comment]
Working well in 2.13.0-beta.4. Moving to ready.
