### ISSUE TITLE
If primary contact of a place was deleted, the UUID is listed in the list of places

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3769]
![image](https://user-images.githubusercontent.com/1286381/29149669-904caf2e-7d2a-11e7-9aa3-05a3b6e92eeb.png)

If the primary contact was deleted, or is deleted, this should say "Primary contact: none" instead of listing the UUID.

**Comment by SCdF** [comment]
Merged and backported to 2.13.x

**Comment by sglangevin** [comment]
Working well in 2.13.0-beta.4. Moving to Ready.
