### ISSUE TITLE
Only trigger location request on startup and when starting to fill a report

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3781]
Currently we are requesting user location udpates every 5 minutes.  This is likely to be a drain on battery.  

Instead we should request updates closer to the time we need them.

# When do we need to know location?

Currently we add location to a report's metadata when it is first created.  We should trigger a request for location when the user starts to fill a form.  When the location update is received, we should then set this in the form's metadata.

This is likely to complicate the existing api (at https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/MedicAndroidJavascript.java#L99) as the code in both `medic-android` and `medic-webapp` will need to handle async callbacks.

# Web-based APIs

At this point we should also review why we're using Android-specific code for fetching location, instead of browser-based APIs.

# Extension work

In the future we may want our asynchronous responses stored in a queue to allow updating of reports with location data that arrives after the form has been submitted locally.  However, even with this feature we'll have to support forms which are missing location data completely, and it seems likely that location update requests will usually be received before a form can be fully filled, so gains from this approach may be marginal.

ref medic/medic-projects#2629

**Comment by alxndrsn** [comment]
Query: can you get a timestamp and accuracy reading for the GPS values?

**Comment by alxndrsn** [comment]
1. add `getLocation()`, `watchLocation()` and `clearWatch()` in atp

**Comment by alxndrsn** [comment]
@sglangevin @abbyad we can either continue to embed the location data inside the form model XML, or we can add it as a property to couch docs.  The latter would seem more natural to me, but might require some updates to any systems which use these data.

**Comment by sglangevin** [comment]
@michaelkohn can you weigh in here? @alxndrsn is suggesting that we put the geolocation data at the top level of the `data_record`, similar to where `reported_date` is found. I am guess that might affect analytics but not too heavily. What do you think about this idea?

**Comment by michaelkohn** [comment]
Yep that works.  As long as it is accessible from the `data_record` and in a predictable location, I'm not too concerned with specifically _where_ it is on the doc.

**Comment by sglangevin** [comment]
Cool - feel free to proceed with adding it as a property to couch docs @alxndrsn. Can you also make sure that any additional docs created by a form submission will also have this property added?
