### ISSUE TITLE
Admin (online-only) users don't get changes that occur while api is offline once it comes back online

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3783]
To reproduce:
 - Log in as an admin. Open something you can edit easily (ie a person)
 - Make a change to that person in futon. Note that it automagically updates in the webapp
 - Kill API. Make another change to that person. Boot API back up

What should happen:
Once webapp reconnects to api it should update the UI with the changes

What actually happens:
Nothing! Changes aren't seen until restart / the resource is reloaded.

NB:

This is probably not a problem the majority of the time. The big PITA is that Horticulturalist works by bringing down api, updating the ddoc and bringing it back up. This means with the current system that you don't get notified of the new ddoc, and so don't get asked to refresh.

If it is prohibitive to solve this bug we can probably solve the above problem some other way.

**Comment by garethbowen** [comment]
Back to you!

**Comment by SCdF** [comment]
Enough changes for a re-review IMO, @garethbowen !

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by ngaruko** [comment]
LGTM
