### ISSUE TITLE
Place docs have an object with fields for `doc.contact`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3785]
In 2.13 places created in the webapp should only have a UUID as the `doc.contact` field, but instead have the full contact's object embedded.

Even though stale contact fields are being embedded, they should be ignored due to #2635. **This should be confirmed**

**Comment by garethbowen** [comment]
I've confirmed that the fields are ignored and the actual contact is looked up from the database, so this is a performance improvement not a bug.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by garethbowen** [comment]
Backported to 2.13.0

**Comment by abbyad** [comment]
Good to hear that the embedded fields are not used - which means this is **no longer a blocker for 2.13**.

Just created a place on `2.13.0-beta.11` and the [doc](https://standard.app.medicmobile.org/_couch/_utils/document.html?medic/3941b453-a990-4376-b23c-609f306e7bc2)'s `contact` fields are still created:
```
{
   "_id": "3941b453-a990-4376-b23c-609f306e7bc2",
   "_rev": "1-23cbc0f0438a6e9a4bf7f89bdfbcc8f6",
   "parent": {
       "_id": "9a6741f5-304d-48a6-ac9b-0b9f6a041455"
   },
   "type": "health_center",
   "is_name_generated": "true",
   "name": "Marco's Health Center",
   "external_id": "",
   "use_cases": "",
   "vaccines": "",
   "notes": "",
   "contact": {
       "type": "person",
       "name": "Marco",
       "phone": "",
       "phone_alternate": "",
       "role": "",
       "role_other": "",
       "external_id": "",
       "notes": "",
       "meta": {
           "created_by": "admin",
           "created_by_person_uuid": "b4958f6e-6426-4c33-900a-22f8befe5897",
           "created_by_place_uuid": "9a6741f5-304d-48a6-ac9b-0b9f6a041455"
       },
       "_id": "913ff788-75b9-48b5-b3a8-deae3f510251",
       "reported_date": 1504718831022
   },
   "geolocation": "",
   "meta": {
       "created_by": "admin",
       "created_by_person_uuid": "b4958f6e-6426-4c33-900a-22f8befe5897",
       "created_by_place_uuid": "9a6741f5-304d-48a6-ac9b-0b9f6a041455"
   },
   "reported_date": 1504718831021
}
```

**Comment by garethbowen** [comment]
Another code review please @SCdF 

I'll probably backport this to `2.13.x` if it hasn't shipped yet...

**Comment by SCdF** [comment]
Merged into master, backported into 2.13.x

**Comment by sglangevin** [comment]
Assigning back to @abbyad for AT after the next beta is released.

**Comment by abbyad** [comment]
Confirming that the place's contact field only has `_id` in `2.13.0-beta.12`. Moving to Ready.
