### ISSUE TITLE
Issue with user deletion: Deletion fails if the user is found in the medic db but not the _users db

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#3788]
If a user is not found in the `_users` database but if it's found in the `medic` database, it is still listed in the users configuration page.  However, deletion of the user fails with `the object is not found in the _users database`.  I think the right behavior when the user clicks on the delete button should be that we should just delete it from the `medic` database if the user is not found in the `_users` database.

In the first place, how that state came about was if deletion was interrupted before finishing.  Regardless of how it came about however, it should not break the delete functionality.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by sglangevin** [comment]
Assigning to myself for AT.

**Comment by sglangevin** [comment]
LGTM.
