### ISSUE TITLE
`lineage.hydrateDocs` is not hydrating parents for data_records

### ISSUE THREAD

**Issue by estellecomment** [medic/medic-webapp#3789]
(discovered in AT in #3715)

`lineage.hydrateDocs` assumes that `data_records` have a `contact` and a `parent` field. They only have a `contact` field, parent places are accessed through `contact.parent`. So it's trying to hydrate following that wrong structure, which doesn't work.

**Comment by estellecomment** [comment]
@garethbowen can you review https://github.com/medic/medic-sentinel/pull/160?

**Comment by garethbowen** [comment]
Back to you @estellecomment

**Comment by abbyad** [comment]
Tested on beta 7 and seems to be working well. No known issues so moving to Ready.
