### ISSUE TITLE
Saving app_settings via Dashboard breaks the settings

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3794]
The Dashboard page for app_settings is useful for quickly looking at settings, but saving from that page introduces new JSON that breaks the configuration in weird and not immediately noticeable ways.

For instance, new reports for a patient are both accepted and rejected simultaneously.

Currently the easiest (and awesome) way to update app_settings is using medic-conf. **To prevent saves in Dashboard we should consider disabling the save button for App Settings in Dashboard.**

**Comment by garethbowen** [comment]
Disabling the save button would require a new version of Dashboard and an upgrade on all instances. This may affect other users of Dashboard (if there are any?) so I'm not 100% sure this is the right approach.

Alternatively we could do a hack via migrations to get the dashboard ddoc and modify it as required, but this doesn't feel very safe either.

I suspect this is a bug in our settings schema which would be a much easier fix - do you know specifically which item is wrong? The easiest way would be to export the working settings, then hit save without making any changes, then export the broken settings. I think if we correctly configure the `default` fields it will work correctly...

This all goes away in the medium term when Horticulturalist replaces Dashboard. We need to decide before then what features are needed (eg: viewing, updating, import, export, etc).

**Comment by abbyad** [comment]
Definitely open to other approaches! [Here](https://gist.github.com/abbyad/6e07f17f6e8871f6d10c3ee1cc1833b6/revisions) is a the app_settings, where the initial commit is the original app_settings, and the revised one how it is after saving in Dashboard, with no other known edits.

One clear problem is that in "patient_reports[].messages" the "event_type" is removed, meaning all messages go out for every report of that type. Normally the message should only go if the `event_type` matches, such as `report_accepted` or `registration_not_found`.

Other differences may not have an effect...  such as adding default empty `validations` or `message` objects if they were missing:
Eg `"validations": {},` being replaced by:
```
      "validations": {
        "join_responses": false,
        "list": [
          {
            "property": "",
            "rule": "",
            "translation_key": "",
            "message": [
              {
                "content": "",
                "locale": ""
              }
            ]
          }
        ]
      },
```
And blank `message` object being added to `messages` when absent:
```
            "message": [
              {
                "content": "",
                "locale": ""
              }
            ]
```

**Comment by garethbowen** [comment]
I have no idea why this is happening...

**Comment by SCdF** [comment]
Perhaps we should just remove dashboard (the actual couchdb database and associated couch app) from production instances? We're going to do it with 3.0 anyway, might as well do it now.

**Comment by SCdF** [comment]
Oh wait ignore me, I forgot the deployment stuff is part of the same couch app. Ignore me.

**Comment by garethbowen** [comment]
We're dropping dashboard for 3.0 so closing this as Won't Fix.
