### ISSUE TITLE
Special characters represented as character entity references in multi-report-alerts 

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3795]
As seen in https://github.com/medic/medic-webapp/issues/3715#issuecomment-323379857 special characters in the message created by the multi-report-alert transition are not encoded properly.

For instance, it the place name gets inserted as `Anthony&#39;s District`

**Comment by sglangevin** [comment]
@abbyad did you intend to add this to the list of bug fixes required for 2.13? Seems like we should probably fix this before the release, unless most messages won't be using the place name. We could use the name of the CHP instead, right?

**Comment by abbyad** [comment]
If it came up earlier it would have been nice to be in 2.13. If there is an opportunity to include it in the next patch that would be great.

**Comment by sglangevin** [comment]
Since we are holding up 2.13 for #3831 anyway, I'm going to add this bug as well. Seems like we should just fix this if it's not too much effort, especially since we have an acceptance testing environment already set up.

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

This needs to be backported to `2.13.x` (apparently...)

@abbyad I think this has been occurring in all messages for a long time because it's the default mustache behaviour. I guess HTML characters in message parameters just aren't that common...

**Comment by abbyad** [comment]
Good to know that it was occurring in all messages previously! It is much more noticeable for Standard config since it is pretty much the first time we are constructing SMS on instances where the place names are generated (eg `{{name}}'s place`). 

Will acceptance test once it lands into beta.

**Comment by alxndrsn** [comment]
@garethbowen would it make sense to submit a PR upstream to disable HTML escaping, or will moustachios just say you should be using triple-brackets (`{{{iWillNotBeEscaped}}}`)?

**Comment by garethbowen** [comment]
Believe it or not, overriding the `escape` function is the proper way of disabling escaping: https://github.com/janl/mustache.js/blob/a6420e433e5add22e350fd80a3edd5e9eff908ec/mustache.js#L97

**Comment by alxndrsn** [comment]
Surprising!  👍

**Comment by garethbowen** [comment]
Particularly frustrating because the only documentation about it is the code comment...

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by abbyad** [comment]
Works well in 2.13.0-beta.10, moving to Ready
