### ISSUE TITLE
When opening a form from a person or place profile, I get the `<` at the top left instead of the `x`

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3797]
This is a blocker for releasing 2.13.0. To reproduce, log in as any user, go to a person or place profile, and open a form from there.

When opening any form, the `x` appears initially, but then is replaced by `<`.
![image](https://user-images.githubusercontent.com/1286381/29480022-5a18a866-842a-11e7-9f3a-5aff21e32d1d.png)

Clicking on the `<` brings me to an error page:
![image](https://user-images.githubusercontent.com/1286381/29480041-7dfa370e-842a-11e7-957e-ed9ccd98cc65.png)

Relevant error messages in the console:
![image](https://user-images.githubusercontent.com/1286381/29480058-9c013e1e-842a-11e7-9f45-530d541c4456.png)

inbox.js pretty printed:
![image](https://user-images.githubusercontent.com/1286381/29480063-a831dab8-842a-11e7-84f0-fe9e976514ca.png)

**Comment by garethbowen** [comment]
Review please @estellecomment 

Needs to be backported to `2.13.x` before closing.

**Comment by estellecomment** [comment]
code lgtm.
Unit test wouldn't have helped on that one, since we would have mocked out `$scope.setSelected` that was causing the break. :/

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by sglangevin** [comment]
Working well in v2.13.0-beta.8. Moving to ready.
