### ISSUE TITLE
Error message on opening forms

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3798]
Steps to reproduce :

1. open the web app (with reports loaded)
2. Start a new form (like Reports > Submit report > Delivery report
![image](https://user-images.githubusercontent.com/6979995/29498598-e734964e-8653-11e7-8fe3-0e9b0f6429b1.png)
  OR...
People >>New District (tested on alpha.dev):
![image](https://user-images.githubusercontent.com/6979995/29498604-0829fd30-8654-11e7-8be1-4a8fb71a85ea.png)

3. The error `This field is required` is displayed before the form has been touched.

NB: 1. This not affecting users anyhow, but it would be nice to get to the bottom of it. 
        2. No errors displayed in the console

**Comment by SCdF** [comment]
I imagine this is because as part of setting up select2 we (or select2, or enketo, or something) is blurring focus from select2. I imagine this could be super hard to track donw.

**Comment by abbyad** [comment]
This is odd, but doesn't break any workflows so I suggest we leave it as is. If @SCdF had said this was easy I may have a different opinion!

Will close as won't fix for now, but can reopen if we decide to tackle this.
