### ISSUE TITLE
Find alternative for jr:choice-name or re-implement support for it

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3804]
As per https://github.com/enketo/enketo-core/issues/412, we should either find an alternative way to implement our `jr:choice-name()` calls, or write an adapter to support it properly in enketo-core.

@abbyad it would help if you can explain the current use of `jr:choice-name()` in our forms.  We have it in 83 different forms currently :slightly_smiling_face:

**Comment by abbyad** [comment]
There are a couple of ways we are using `jr:choice-name()`.

## Show or save label (not value)
Show the user the choice they made earlier in the form as part of the Summary page. Without the `jr:choice-name()` function the potential workaround is to have a calculate converting the value back to a nice label... but this is difficult to manage and would not work with multiple languages (eg in Standard).

![image](https://user-images.githubusercontent.com/789512/29529403-8b95181c-866d-11e7-98b8-09c32690481a.png)

## Build SMS
Build an outgoing SMS message within the form using values retrieved in the form, that can work in multiple languages and be edited in the form.

![image](https://user-images.githubusercontent.com/789512/29529423-9c06c8d0-866d-11e7-8a10-295e86f23aba.png)

## Summary page
![image](https://user-images.githubusercontent.com/789512/29529443-b49b2f6c-866d-11e7-82d8-16af6635843a.png)

**Comment by alxndrsn** [comment]
Thanks!  Note to self: specifically we're trying to avoid uses as per https://github.com/enketo/enketo-core/issues/412

**Comment by alxndrsn** [comment]
It sounds like this would be worth the effort of fixing with `enketo-core`'s latest release, using external overrides of functionality.  This means that we should not need to release our own version and should not need to "monkey patch" our node modules, making future upgrades much simpler.

**Comment by garethbowen** [comment]
@alxndrsn Some thoughts, back to you!

**Comment by sglangevin** [comment]
Assigning to @abbyad for AT.

**Comment by abbyad** [comment]
@alxndrsn what version is this available in? If it is only in 2.14 I will wait for a beta of that to do AT.

**Comment by alxndrsn** [comment]
Yeah, AFAIK this is 2.14 onwards.

**Comment by sglangevin** [comment]
This should be AT-ed on master. 2.14 has not yet been branched from master, so anything in master is going to be part of 2.14.

**Comment by abbyad** [comment]
Perfect, I'll test this on alpha.dev

**Comment by sglangevin** [comment]
@abbyad has this been sufficiently tested or it needs more?

**Comment by abbyad** [comment]
I have not tested yet as part of this issue, but _was_ tested with https://github.com/medic/medic-webapp/issues/3870 as part of 2.13. 

@alxndrsn, has anything changed here for 2.14?

**Comment by alxndrsn** [comment]
Should be the same for 2.14.  Probably worth checking, though!

**Comment by sglangevin** [comment]
@abbyad what is the status of AT on this issue?

**Comment by abbyad** [comment]
We should retest this on 2.14 to verify that it works as it does on 2.13. I am planning on doing that as part of my next round of AT for 2.14, likely today.

**Comment by abbyad** [comment]
Works well in 2.14. Tested with the form from https://github.com/medic/medic-webapp/issues/3281#issuecomment-289152363 but using `<h:body class="pages">` since the value is stale until page turns.
