### ISSUE TITLE
Add Horticulturalist integration tests

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3805]
We have (some) unit test coverage of horti, but we should really do integration tests as well.

There are lots of variables and different ways horti can boot:
 - Are we bootstrapping to some particular version?
 - Are we running in daemon mode or just bootstrapping
 - Do we have an existing deployment / staging deployment on startup
 - Do we already have an existing installation (extracted npm modules) that we should boot first regardless

As well as situations that probably don't matter for when we use this just with medic code, but may matter in the future (or if medic's code changes):
 - What happens if there are no npm modules to deploy
 - What happens if we add / remove an npm module between versions

To enable integration tests we should first:
 - Modify the [build server code](https://github.com/medic/medic-builds-repo) so that it can be pulled from npm, and has a command to "start", which for now is just installing the builds db (far in the future we may need a server in front of this)
 - Modify horti so you can configure an alternative build server from the hard-coded production one

Then, for the integration tests we can first:
 - Wipe / boot a fresh builds "server"
 - Push up a collection of test builds that you can switch between
 - And write tests

This will also conveniently test supporting builds of code that isn't just medic-webapp, and so will probably find bugs.

**Comment by SCdF** [comment]
Going to be fixed as part of #3993

**Comment by SCdF** [comment]
Update: I have added a lot of unit tests, but no integration tests. We need to think about how to integration test horti if we can find the time. This is no longer blocked though.

**Comment by SCdF** [comment]
@garethbowen please take a look at the linked PR.

There are **lots** more int. tests to work on. I think I'll try to do some each Friday or something to slowly build up a library of them. Anyway, this is, most importantly, the framework, and the associated work around bootstrapping our deployment infrastructure for testing.

**Comment by garethbowen** [comment]
LGTM

**Comment by SCdF** [comment]
Merged. No AT required.
