### ISSUE TITLE
Horti fails to upgrade through the ui if there is already a staged ddoc

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3806]
See: https://github.com/medic/medic-api/blob/master/controllers/upgrade.js#L61-L64 (once the branch is merged).

API needs to detect a 409 and then take the current one's rev and use that to overwrite what is already there.

**Comment by SCdF** [comment]
Going to be fixed as part of #3993

**Comment by SCdF** [comment]
This has been fixed as part of work merged and released as part of #3993. Now, whenever a deployment starts it clears out old staging data.

**Comment by ngaruko** [comment]
LGTM... Not showing behaviors described in #4156
