### ISSUE TITLE
`Delete all` disabled in mobile view 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3808]
In full screen the delete button shows only on the RHS.
In mobile view there is no RHS in select mode so it is shown disabled on the LHS
![image](https://user-images.githubusercontent.com/6979995/29591026-c95f3d6a-87f0-11e7-9859-7114621bf03f.png)

**Comment by garethbowen** [comment]
Code review please @estellecomment 

For AT ensure that not only is the button enabled when at least one record is selected but clicking it deletes the selected records - both were broken here.
