### ISSUE TITLE
Cannot obtain all of a contact's parent info in contact-summary

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3812]
In 2.13 we need to use the contact-summary to pass info to a form, such as the phone number of a CHW's supervisor. From the contact-summary we can access the `contact` and `lineage`, but cannot yet access the `parent.contact.*` field (eg `parent.parent.contact.phone`).

Related to #3413

**Comment by garethbowen** [comment]
Code review please @estellecomment 

This needs to be backported to 2.13.x

**Comment by estellecomment** [comment]
One weird test, and travis is failing (surpriiiiise), but looks good!

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by abbyad** [comment]
This works in `2.13.0-beta.9`. Moving to Ready.

We should note in [contact summary documentation](https://github.com/medic/medic-docs/blob/master/configuration/contact-summary.md) that the only way to get the fields for `parent` is by accessing the top level of `lineage[]` (eg `lineage[0]` for parent, `lineage[1]` for grandparent).  To obtain the contact for any parent place you must therefore look at `lineage[*]`. For example, the contact for a patient would be the contact of the parent place, which is `lineage[0].contact`. In all other locations the `parent` is not hydrated (ie `contact.parent`, `lineage[].parent`, `lineage[].contact.parent`).
