### ISSUE TITLE
Cannot exit a form using Cancel button

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3813]
In `2.13.0-beta.7` using the desktop mode* you cannot exit an action form by pressing the Cancel button. 

_*The cancel button is not shown in mobile mode_

**Comment by sglangevin** [comment]
Please re-test this once #3797 is available in the new beta. Hopefully that will close this one as well.

**Comment by garethbowen** [comment]
Yes this is fixed by the fix for #3797 - closing for AT.
