### ISSUE TITLE
Horti shouldn't default to starting in MedicOS mode

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3825]
If you just type `horti` it attempts to start api and sentinel with the expectation that you're on MedicOS.

Since Horti is also useful for real users, this should instead output commands, ah la most other tool.

This also means we have to change horti so that medicos is a mode you specify, instead of the default.

**Comment by alxndrsn** [comment]
PR at https://github.com/medic/horticulturalist/pull/2
