### ISSUE TITLE
Document what is hydrated for use in contact summary

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3830]
From https://github.com/medic/medic-webapp/issues/3812#issuecomment-324970951

> We should note in [contact summary documentation](https://github.com/medic/medic-docs/blob/master/configuration/contact-summary.md) that the only way to get the fields for `parent` is by accessing the top level of `lineage[]` (eg `lineage[0]` for parent, `lineage[1]` for grandparent).  To obtain the contact for any parent place you must therefore look at `lineage[*]`. For example, the contact for a patient would be the contact of the parent place, which is `lineage[0].contact`. In all other locations the `parent` is not hydrated (ie `contact.parent`, `lineage[].parent`, `lineage[].contact.parent`).

**Comment by garethbowen** [comment]
Review please @abbyad

**Comment by abbyad** [comment]
Looks great, thanks!
