### ISSUE TITLE
Contacts from a select2 are not hydrated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3831]
The contact that is returned from a `db:person` field in a form is not hydrated in 2.13.0-beta.9. Following #2635 we are using the contact-summary to populate these fields from the People tab (as per #3413), but this method cannot be used from the History tab. This means that any user trying to access a person form from the Reports/History tab will find silently broken forms. 

For example, in Standard config it would not be possible to send the message to the CHW following a patient visit because the CHW phone number would be missing:
![image](https://user-images.githubusercontent.com/789512/29731037-ce4007b2-89b0-11e7-89d8-85c86a3bfb02.png)

The same would apply to the other db field types (eg `db:clinic`)

**Comment by sglangevin** [comment]
Unfortunately this is a blocker for the 2.13.0 release as we have projects that rely on being able to fill forms from the History/Reports tab.

**Comment by garethbowen** [comment]
Code review please @estellecomment 

This needs to be backported to `2.13.x`

Another hydration issue  :(

**Comment by estellecomment** [comment]
back to you

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by abbyad** [comment]
This works well now. Moving to Ready.
