### ISSUE TITLE
Relative date in horticulturalist branches does not show absolute date on hover

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3835]
If you hover over other usages of the `relativeDate` you see the absolute date in hover text. For example, a message date:

![image](https://user-images.githubusercontent.com/583851/29820477-7a31c0de-8cbc-11e7-83aa-97338ad5ba4f.png)

However, this doesn't work on the branches section of the horticulturalist upgrade instance page.

This could be because there needs to be some extra library or class that we're missing. It seems to be something to do with Aria (an accessibility library?):

![image](https://user-images.githubusercontent.com/583851/29820891-e9598270-8cbd-11e7-8aab-5c0c89d68951.png)

(`aria-describedby` gets added when you hover in the working version, but not in the horti upgrade instance page.)

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Back to you @garethbowen
