### ISSUE TITLE
`{{patient_name}}` and `{{person.name}}` not always available

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3838]
In standard.app we are not able to get the patient's name into _some_ outgoing messages.

See this [F report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/7f203734713286725fd1cfcc1a5c3227), vs [P report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/7f203734713286725fd1cfcc1a5b9222). The name is shown in the P report's auto reply and schedule, but not in the F report's auto reply or multi-report alert.

**Comment by SCdF** [comment]
Isn't the real bug that in the F report there is an error that should stop scheduled messages from being created at all?

Sounds like the error is causing the patient to not get attached and so the scheduled messages fail. I haven't looked at the code yet though.

So, depending on your reply @abbyad:
 - We should make sure the patient is always attached regardless of errors
 - Scheduled messages shouldn't get created if forms error

**Comment by abbyad** [comment]
Could be... but I just [retested](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/7f203734713286725fd1cfcc1a5cdcfb) by removing the part that caused the error and still don't get the patient's fields.

Also, I think we already avoid sending schedule messages if there is a validation error. In this case it is the multi-report-alert that is creating those messages, and also generating the error (by trying to access a contact field that did not exist).

**Comment by abbyad** [comment]
The `transition` field has the following:
```
{
   "default_responses": {
       "last_rev": 2,
       "seq": 628,
       "ok": true
   },
   "update_clinics": {
       "last_rev": 2,
       "seq": 628,
       "ok": true
   },
   "multi_report_alerts": {
       "last_rev": 2,
       "seq": 628,
       "ok": true
   },
   "accept_patient_reports": {
       "last_rev": 3,
       "seq": 630,
       "ok": true
   }
}
```

Does that mean that the `accept_patient_reports` transition ran after the others?

**Comment by garethbowen** [comment]
> Does that mean that the accept_patient_reports transition ran after the others?

Yes that's exactly what that means. I suspect it failed its [filter function](https://github.com/medic/medic-sentinel/blob/master/transitions/accept_patient_reports.js#L146) the first time through, then the doc was saved increasing the rev from 2 to 3, and then the filter function passed the second time through.

**Comment by SCdF** [comment]
@estellecomment please review the two PRs, https://github.com/medic/medic-webapp/pull/3844 and https://github.com/medic/medic-sentinel/pull/167

Don't merge yet cause I haven't been able to test myself locally yet, but you might as well do the review.

**Comment by garethbowen** [comment]
Reviewed on behalf of @estellecomment - good to go @SCdF

**Comment by SCdF** [comment]
Update: due to a large refactor in master I have to somewhat start again on another branch

**Comment by SCdF** [comment]
@garethbowen can you please review the following PR: https://github.com/medic/medic-sentinel/pull/168

It's similar to the previous PR, except now it's against 2.13.x, which required some changes.

**Comment by SCdF** [comment]
Actually @garethbowen in retrospect there is little difference and I don't want to hold up the cycle. I'll merge it.

**Comment by sglangevin** [comment]
@abbyad assigning to you for AT.

**Comment by abbyad** [comment]
Works on `2.13.0-beta.11`, and will now only use `{{patient_name}}` throughout.
