### ISSUE TITLE
Cannot access contact field for one of the `new_reports`

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3839]
In 2.13.0-beta.10, `new_reports.contact.parent.name` and `new_report.contact.parent.parent.contact` are undefined for one of the elements in the array. This is possibly because the most recent report does not have the contact assigned before the multi-report-alert transition runs.

This was working in ~beta 7: `{{#new_reports}}{{contact.parent.name}}, {{/new_reports}}`, as well as having `new_report.contact.parent.parent.contact.phone` as a recipient.

Here is an [example report](https://standard.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/7f203734713286725fd1cfcc1a5c2364).

**Comment by abbyad** [comment]
Updated original post to include info about the recipient `new_report.contact.parent.parent.contact.phone` failing, as it is the source of the error in the test message.

**Comment by abbyad** [comment]
This could be a different symptom of https://github.com/medic/medic-webapp/issues/3838

**Comment by garethbowen** [comment]
@SCdF Can you please have a look at this one once #3838 is merged and see if it's a symptom of the same issue?

**Comment by SCdF** [comment]
Interesting that this used to work. I was thinking it was because of https://github.com/medic/medic-webapp/commit/233c69bd35dddf0e12b6df524f03636e76e3797b that was done in master but not backported. 

@abbyad can you link me to where those message templates are? I can't find them in our defaults or in standard configuration.

**Comment by SCdF** [comment]
@abbyad OIC it's inline with the `multi_report_alert` transitions.

**Comment by SCdF** [comment]
Code difference between `beta.4` and `beta.10`:

```diff
index c5114a1..a8b4442 100644
--- a/transitions/multi_report_alerts.js
+++ b/transitions/multi_report_alerts.js
@@ -85,8 +85,8 @@ const generateMessages = (alert, phones, latestReport, countedReportsIds, newRep
 // Recipients format examples:
 // [
 //    '+254777888999',
-//    'countedReport.contact.parent.parent.contact.phone',   // returns string
-//    'countedReport.contact.parent.parent.alertRecipients', // returns string array
+//    'new_report.contact.parent.parent.contact.phone',   // returns string
+//    'new_report.contact.parent.parent.alertRecipients', // returns string array
 // ]
 const getPhones = (recipients, reports) => {
   let phones = [];
@@ -114,7 +114,7 @@ const getPhonesOneReport = (recipients, report) => {
   return _.uniq(phones);
 };

-const getPhonesOneReportOneRecipientWithDuplicates = (recipient, countedReport) => {
+const getPhonesOneReportOneRecipientWithDuplicates = (recipient, newReport) => {
   if (!recipient) {
     return [];
   }
@@ -123,7 +123,7 @@ const getPhonesOneReportOneRecipientWithDuplicates = (recipient, countedReport)
     return [recipient];
   }

-  const context = { countedReport: countedReport };
+  const context = { new_report: newReport };
   try {
     const evaled = vm.runInNewContext(recipient, context);
     if (_.isString(evaled)) {
@@ -194,6 +194,12 @@ const getCountedReportsAndPhones = (alert, latestReport) => {
   return new Promise((resolve, reject) => {
     const script = vm.createScript(`(${alert.is_report_counted})(report, latestReport)`);
     let skip = 0;
+
+    if (!countReports([latestReport], latestReport, script).length) {
+      // The latest_report didn't pass the is_report_counted function, abort the transition.
+      return resolve({ countedReportsIds: [], newReports: [], phones: [] });
+    }
+
     let countedReportsIds = [ latestReport._id ];
     let newReports = [ latestReport ];
     let phones = getPhonesOneReport(alert.recipients, latestReport);
```

**Comment by SCdF** [comment]
This appears to have been fixed in the latest 2.13.x.

Your example:
![image](https://user-images.githubusercontent.com/583851/29972498-2cc046a8-8f24-11e7-80e0-db1e9a347e6b.png)
My example:
![image](https://user-images.githubusercontent.com/583851/29972509-37123fc6-8f24-11e7-81f3-d4e7733c8ffc.png)

**Comment by sglangevin** [comment]
@SCdF the second message in your example is missing the patient name. It should say "{patient_name} (28204) was flagged by Chelsea...". Do you know if the translation was changed to `person.name`?

**Comment by abbyad** [comment]
Yes, that one was changed to `person.name` for previous testing (#3838), now back to `patient_name`.

**Comment by sglangevin** [comment]
@abbyad was this already AT-ed? If so, please mark as ready. If not, can you please AT?

**Comment by abbyad** [comment]
Just AT-ed in beta 11. `{{#new_reports}}{{contact.parent.name}}, {{/new_reports}}` and `new_report.contact.parent.parent.contact.phone` work as expected again.

Moving to Ready.
