### ISSUE TITLE
Use latest translations from POEditor in 2.13 release

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3846]
Follow up to #3838, make sure that all translations used in next release use `patient_name`, and not `person.name`.

- [x] Update all translations accordingly
- [x] Pull in latest translations from POEditor into 2.13 branch before release

**Comment by abbyad** [comment]
I've also updated the Standard config labels so that they can be included by default in 2.13.

**Comment by sglangevin** [comment]
I'd like to update the translations for passwords per #1472. I'll work on that tomorrow.

**Comment by garethbowen** [comment]
@sglangevin Let me know when this is ready to go and I'll merge it in.

**Comment by sglangevin** [comment]
I've updated it! I did a bit of password testing and created a more specific translation to guide users. I do like the idea of putting in that colored widget that shows password strength in the future, though. Feel free to pull in translations for the release.

**Comment by garethbowen** [comment]
Yeah I agree about the password strength indicator - that should be included in the design review of the entire users configuration section.

**Comment by garethbowen** [comment]
Translations backported to `2.13.x`

**Comment by sglangevin** [comment]
LGTM.
