### ISSUE TITLE
Something funny's up with URLs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3849]
On my local instance, the following URLs produce different results:
```
Opens a form: http://localhost:5988/medic/_design/medic/_rewrite/#/contacts//add/clinic
Gives a 404:  http://localhost:5988/medic/_design/medic/_rewrite/#/contacts/add/clinic

**Comment by garethbowen** [comment]
It looks a bit funny but it's expected. The route is: `/contacts/:parent_id/add/:type`. If you didn't specify the parent to start from then `parent_id` is empty and you get the strange looking double slash. Without the double slash it doesn't match any route so it 404s.

**Comment by alxndrsn** [comment]
Wow.  Your explanation makes sense, but is very surprising, as I'd expect multiple slashes in URLs to get collapsed.
