### ISSUE TITLE
New contact age is off by one (day?)

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3852]
Using the standard clinic-create form, create a clinic with Primary Caregiver of age **2 years**.  When this contact is viewed, their age is listed as 23 months.

**Comment by garethbowen** [comment]
Maybe related: #986

**Comment by sglangevin** [comment]
This is a configuration issue that should have been fixed already. I just looked at the contact forms for Standard and I don't see a place where the age is collected for the primary contact of any place, so I'm not sure which form you used, @alxndrsn.

**Comment by alxndrsn** [comment]
> I'm not sure which form you used

I'm pretty sure this was with the LG KE Clinic form.

**Comment by sglangevin** [comment]
Looked at what is on Github and I would expect the LG KE Clinic form to work and the LG UG Clinic form to have the bug you have noted here. This is a configuration issue and not a webapp bug.

**Comment by garethbowen** [comment]
Closing as a configuration issue. Reopen the issue in medic-projects tagging the specific instance if it occurs again.
