### ISSUE TITLE
Cannot submit forms about patients on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3855]
web app version: 2.13.0-beta.10
android app version: 0.1.157

To reproduce, log in as a restricted user on mobile, go to any patient profile and try to fill in any form about the patient. I get the following error in the console:

![image](https://user-images.githubusercontent.com/1286381/29928756-ac5d2950-8e37-11e7-99f9-bd7c01430a8b.png)

**Comment by sglangevin** [comment]
This was seen on a Y4 on lg.dev, logged in as demo1. PM me for the password.

**Comment by sglangevin** [comment]
This bug does not exist in the most recent version of the Android app so we may be able to safely ignore it.

**Comment by garethbowen** [comment]
`array.find` is not available on our minimum supported version of Chrome. Excellent issue thanks @sglangevin !

**Comment by garethbowen** [comment]
Review please @SCdF

**Comment by garethbowen** [comment]
This needs to be backported to `2.13.x`

**Comment by garethbowen** [comment]
For AT be sure to test the duplicate issue #3854 as well.

**Comment by SCdF** [comment]
LGTM, merged

**Comment by garethbowen** [comment]
Backported.

**Comment by sglangevin** [comment]
I'm still getting an error when testing on v2.13.0-beta.11 and Android container v0.1.157. I can't get dev tools to work right now, but will look for another USB cable tomorrow and report back on what the error is.

**Comment by garethbowen** [comment]
It works for me on lg.dev as demo1. I'll have to wait for your log details to take this any further.

**Comment by sglangevin** [comment]
Ok, here is the error I got:
![image](https://user-images.githubusercontent.com/1286381/30167263-cb50f8f6-93b3-11e7-9436-b1a283657de3.png)

Seems to be a different one from before and also the other related issue (#3854) is working fine now.

**Comment by garethbowen** [comment]
Awesome... different error! _sigh_

**Comment by garethbowen** [comment]
This works in latest Chrome, but fails in Chrome 30 on the Android (no app required).

**Comment by garethbowen** [comment]
Reproduced locally on `master`.

**Comment by garethbowen** [comment]
I'm going to raise a new issue for this - it's a completely separate bug.

**Comment by sglangevin** [comment]
Ok, I'm going to close this one and move it to ready since the original error is now fixed.
