### ISSUE TITLE
Upgrading the Android container from a pre-Crosswalk version to the latest version (0.3.6) causes user to re-download all data

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3856]
During testing of the upgrade path from 0.1.157 to 0.3.6, I was not logged out but I did have to re-download all of my data. The ideal behavior would be for data to be copied over locally from the old database to the new one. Marking this as high priority as we are pushing to get all LG UG users onto a modern version of the Android container.

To test, you can use the unbranded app, which has v0.1.157 in the beta channel and v0.3.6 in the alpha channel. I'm also available to help test.

**Comment by alxndrsn** [comment]
Checkpointing may be broken in pouchdb 6.3.4 - discussion ongoing at https://pouchdb.slack.com/archives/C03FEASK8/p1504268246000065

**Comment by alxndrsn** [comment]
Could not recreate with unbranded app against lg.app.

**Comment by alxndrsn** [comment]
I can't recreate this.  With user `demo1` on `lg.dev`, I see less than 1MB of downloads after upgrading the container.  These downloads are of application data (javascript, CSS, anything else stored in the app cache).  Database contents are _not_ re-downloaded:

<img width="1009" alt="screen shot 2017-09-07 at 11 55 18" src="https://user-images.githubusercontent.com/191496/30157830-9307fd68-93c3-11e7-80e2-2316169fa081.png">

Contrast this with a first run for this user on a completely new app:
<img width="1015" alt="screen shot 2017-09-07 at 12 35 13" src="https://user-images.githubusercontent.com/191496/30159483-070a89e2-93c9-11e7-9b92-cfad0a4bd475.png">

**Comment by alxndrsn** [comment]
N.B. this may be dependent on Android version or a particular device.  @sglangevin please confirm which devices you've seen this behaviour on?  I could not recreate it on a Samsung J1 Mini.

**Comment by sglangevin** [comment]
@alxndrsn I am using a Tecno Y4, Android version 4.4.2. I believe I also saw this on my Tecno Droipad tablet, Android version 5.1. I will test again today and let you know what I find on both devices.

**Comment by alxndrsn** [comment]
@sglangevin my understanding is that you retested this on Y4 and found that _sometimes_ no data is redownloaded, and other times it is all redownloaded.  I will do repeated tests at my end to see if I can recreate the behaviour.

**Comment by alxndrsn** [comment]
# Test Results

* `v0.1.157` -> `v0.3.7`
* Tecno Y4

Testing round | Result
---|---
1 | <img width="174" alt="screen shot 2017-09-14 at 13 43 19" src="https://user-images.githubusercontent.com/191496/30428144-d8ee84d4-9952-11e7-8e5a-ba173c41ea8c.png">

**Comment by alxndrsn** [comment]
@sglangevin if you think it's worthwhile I can continue testing, but it doesn't _look_ like I can recreate this here.  If you're still concerned, please test further and provide screenshots and some more info about your environment where you see the bug.

**Comment by sglangevin** [comment]
I think it's good for now. I'm going to close this and will open a new issue if I can figure out how to reproduce it reliably. LG has agreed they are ready to update so I think it should be fine.

**Comment by alxndrsn** [comment]
Hopefully this investigation gives everyone a bit more confidence!
