### ISSUE TITLE
Favicon is not cached

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3858]
# Observed

From restricted user on standard.app:

<img width="759" alt="screen shot 2017-08-31 at 17 48 55" src="https://user-images.githubusercontent.com/191496/29932492-baed6b1e-8e74-11e7-9561-3cd5ae411916.png">

# Expected

Favicons should be cached.

-----

ref #3837

**Comment by garethbowen** [comment]
This should have been fixed by #1913

**Comment by alxndrsn** [comment]
Does appear to work today(??)  Looks like a slight problem with the regex for favicons in general, though.  Will submit a PR.
