### ISSUE TITLE
bootstrap.js and bootstrap have confusingly similar names

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3862]
For clarity we should rename `static/js/bootstrap.js` to `static/js/bootstrapper.js` or think of an even better name for it.  Currently in `static/js/app.js` we have:
```
require('bootstrap');
…
var bootstrapper = require('./bootstrap');
```

**Comment by garethbowen** [comment]
@alxndrsn I've merged the first PR but I don't think the second one is quite right so I'll leave that for you.

**Comment by alxndrsn** [comment]
PR at https://github.com/medic/medic-webapp/pull/3863
