### ISSUE TITLE
Form content is `undefined` on Chrome 30

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3880]
Error when submitting a form using Chrome30 on my Tecno...

![](https://user-images.githubusercontent.com/1286381/30167263-cb50f8f6-93b3-11e7-9436-b1a283657de3.png)

To replicate:

1. Log in as demo1 on lg.dev
2. Go to Rachel Jones
3. Click "New action" and choose "Pregnancy visit"
4. Fill in the form and submit

Originally submitted during AT of #3855

**Comment by garethbowen** [comment]
I've created a fiddle that tests the functionality: https://jsfiddle.net/8jdtjujk/4/

**Comment by garethbowen** [comment]
`outerHTML` was introduced in https://github.com/medic/medic-webapp/commit/6be83607f7701747ce48eb0937f25eee0a1eb190

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

This needs to be backported to `2.13.x`.

@sglangevin Is it worth backporting this to `2.12.x` and making a new release?

**Comment by sglangevin** [comment]
I don't think we need to. No mobile app projects are on 2.12.x currently and none will upgrade to it because they won't be upgrading before we release 2.13.x. Since we can't upgrade to specific versions other than the latest until Horti is released and that won't be released until 3.0, I think it is safe not to backport.

**Comment by alxndrsn** [comment]
Looks like MDN's documentation is incorrect - https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML claims that `outerHTML` has been available on `Element` (as opposed to `HTMLElement`) since Chrom 0.2.

**Comment by alxndrsn** [comment]
I've confirmed that `outerHTML` is not available in Chrome 30, and filed a bug against the MDN docuemntation: https://bugzilla.mozilla.org/show_bug.cgi?id=1398088

**Comment by garethbowen** [comment]
Merged and backported to `2.13.x`

**Comment by sglangevin** [comment]
@garethbowen this seems to be working in 2.13.0-beta.13. Unfortunately I found some other errors in opening forms. I'll move this one to ready and file those separately.
