### ISSUE TITLE
Show warning before starting upgrade

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3887]
Clicking "Upgrade" in the `Configuration > Upgrade Instance` UI immediately starts the upgrade which will at least take the instance offline for a while and at most be destructive and irreversible. Before starting the upgrade show a modal or separate page describing the risks, outlining some mitigating steps (testing, backups, etc), and giving the user a chance to back out of the upgrade.

**Comment by amandacilek** [comment]
+1 to adding this warning dialogue. A modal sounds like it would suffice provided we don't have too much text. If the text requires multiple paragraphs of explanation then a separate page sounds more appropriate. For now, UI styling of either should match all of our current config page styles.

What would the button options be? Something like "Continue with Upgrade" or "Cancel"? 

Please let me know if I can do anything further to help with this one.

**Comment by SCdF** [comment]
An "Are you sure" dialog is probably an uncontroversial improvement. I'm not convinced by anything more than that: the only research I've seen around dialog boxes is that people just ignore them, especially more complicated ones. I'd worry it will be more annoying than informative.

**Comment by sglangevin** [comment]
I think a simple "This action cannot be undone, make sure you have backed up your data" would suffice. I agree that anything too long is probably more complicated.

**Comment by ngaruko** [comment]
LGTM
