### ISSUE TITLE
Parent fields not available in context for Targets

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3890]
In `2.13.0-beta.13` the `user.parent` fields don't seem to be available in the `context` for targets, possibly due to #2635.

Here is an example context that we use in Standard:

`"context": "(user.parent.use_cases && user.parent.use_cases.split(' ').indexOf('imm') !== -1) || (user.parent.parent.use_cases && user.parent.parent.use_cases.split(' ').indexOf('imm') !== -1)"`

This simplified version does not work either:
`"context": "user.parent.name"`

It seems as though the fields are not hydrated, but haven't looked at the code. This may be an issue for context of forms as well, but has not yet been tested.

**Comment by garethbowen** [comment]
@estellecomment Code review please. One more lineage issue. I don't think this is quite the right place for this code but it's a slight improvement and can be refactored again when we get around to #3826

**Comment by estellecomment** [comment]
One change requested, and then merge away!

**Comment by garethbowen** [comment]
Merged and backported to `2.13.x`

**Comment by abbyad** [comment]
Seems to work well in beta 15. Will do a bit more testing then move to Ready.

**Comment by abbyad** [comment]
Works well in `2.13.0-beta.16`, moving to Ready.
