### ISSUE TITLE
SMS Schedules not being cleared in latest beta

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3893]
On `2.13.0-beta.11` (standard.app) and `13` (standard.dev) we cannot clear schedules with incoming reports. 

Clearing schedules is normally done via `registrations[].events[].clear_schedule` or `patient_reports[].silence_type`, and it is not possible to clear schedules with either in the latest beta.

**Comment by abbyad** [comment]
Updated original post to correct the instances on which we have seen this issue.

**Comment by estellecomment** [comment]
Running locally, with the full config from https://github.com/medic/medic-projects/tree/2.13.x/standard, I'm reproducing on `beta.13`, `beta.12`, `beta.11`, and not on `beta.10`.

Checking what we added in `beta.11`...

**Comment by estellecomment** [comment]
Running webapp and api at `beta.10` and sentinel at `beta.11` makes the bug happen. 

`beta.11` just added the one commit in sentinel : https://github.com/medic/medic-sentinel/commit/aa0644c1169693a36cd5c1de65a9b0630348e116

**Comment by SCdF** [comment]
This was a bad merge unfortunately, that came about due to having to manually generate the merge for 2.13.x (if you follow the commit messages you'll see what occurred).

I'll push a fix and a new beta now.

**Comment by SCdF** [comment]
@estellecomment please take a look at the commit above. To speed things up I did it inline into 2.13.x. It looks like a lot, but if you hide the whitespace you'll note it's just the wrapping changes with registrations no longer being wrapped in `.doc`. You can see the genesis of this here: https://github.com/medic/medic-sentinel/blob/2.13.x/lib/utils.js#L427-L444

**Comment by SCdF** [comment]
@abbyad When [this beta build](https://travis-ci.org/medic/medic-webapp/builds/274649650) succeeds there will be a beta 14

**Comment by abbyad** [comment]
This now works again as expected on beta 14. Thanks @estellecomment and @SCdF for debugging resolving this quickly!

**Comment by estellecomment** [comment]
lgtm!
