### ISSUE TITLE
Fix or revert single-sided checkpointing in pouch

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3898]
Due to https://github.com/pouchdb/pouchdb/issues/6730, our app will likely now run through the full changes feed on every restart.  We either need to get this fixed upstream and update our pouch version, or disable this feature.

**Comment by garethbowen** [comment]
I've confirmed this is an issue for us. For stability I'm going to turn this option off for this release and we can add it back when the PouchDB issue is resolved.

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by alxndrsn** [comment]
I confirm this is reverted.

**Comment by ngaruko** [comment]
Not sure if we should leave this open. Just as a reminder to turn the option back on when [pouchdb/pouchdb#6730](https://github.com/pouchdb/pouchdb/issues/6730) is fixed

**Comment by garethbowen** [comment]
@ngaruko If this has passed AT close it out. I'm watching the pouchdb issue and will create a new one once it's fixed and released.
