### ISSUE TITLE
Can create people born in the future with standard configuration

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3899]
...and if you do, their age appears as a positive number (instead of negative):

<img width="279" alt="screen shot 2017-09-12 at 16 10 31" src="https://user-images.githubusercontent.com/191496/30333475-f09c3f88-97d4-11e7-9cd5-4db714a6b2bd.png">

<img width="406" alt="screen shot 2017-09-12 at 16 10 37" src="https://user-images.githubusercontent.com/191496/30333474-f0762abe-97d4-11e7-83e8-c959b61ba557.png">

**Comment by abbyad** [comment]
We should put in additional constraints in the Standard contact forms to avoid this scenario. Regardless, we should also display the birthday accordingly in red, or with a negative, or both. Even if it doesn't make logical sense for a birthday to be in the future this could show up if your device clock is set back.

**Comment by ngaruko** [comment]
With this one, it seems like the above fix just shows future birthdates in red. Do we have an issue in medic-projects @abbyad to "put in additional constraints in the Standard contact forms to avoid this scenario" as you suggested above?

**Comment by ngaruko** [comment]
Thanks @garethbowen. Also, seems like the date does not go red as in [here](https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/91a6c194-55ec-4fc3-a865-55fe99fee385)

![image](https://user-images.githubusercontent.com/6979995/48686138-680d0a00-ebf5-11e8-93a0-6e51ac65ed87.png)

Am I missing anything @peter-ochieng ?

**Comment by ngaruko** [comment]
I guess this is still WIP atm. Returning...

**Comment by garethbowen** [comment]
Merged and backported to 3.3.x

**Comment by ngaruko** [comment]
LGTM - Tested on `gamma.dev` v 3.3 with [this person](https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/6c58b51d-5bfe-45bf-a95f-4cca15d806dd)
![image](https://user-images.githubusercontent.com/6979995/49185773-5f56c980-f395-11e8-8545-f2d4d71f9b38.png)
