### ISSUE TITLE
Make `user type` required (or set a default if user type is selected?)

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3904]
Steps:
1. Login as admin (Tested on `apha.dev`, Version `2.13.0-alpha.7458`)
2. Add user: skip the user type field
3. Logout as admin and login as created user
4. The app behaves erratically 

a) select language modal with no language list:
![image](https://user-images.githubusercontent.com/6979995/30355965-9d75f810-988a-11e7-8ec0-c55c4304a9e9.png)
 b)Tour modal not translated:
![image](https://user-images.githubusercontent.com/6979995/30355989-cf98a0a4-988a-11e7-9a2d-269ed8b0c715.png)

c) No navigation bar at top:
![image](https://user-images.githubusercontent.com/6979995/30356019-fb75a744-988a-11e7-9dad-cda9e65c71c7.png)

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged.
