### ISSUE TITLE
Start date for LMP constraint failing on New Pregnancy form

### ISSUE THREAD

**Issue by jillrshah** [medic/medic-webapp#3905]
In 2.13.0-beta.14, on the New Pregnancy form, in the "Start Date of Last Cycle" field, the following constraint `.<today() and ((decimal-date-time(.)+294) >= decimal-date-time(today()))` throws a validation error even though the data input satisfies constraint. 

It works in 2.12.5 but not in 2.13.0-beta.14.

Screenshot is from standard.dev, user = healthcenter

![image](https://user-images.githubusercontent.com/22451829/30356579-b9d5a1d2-9807-11e7-9459-159c35bf701f.png)

**Comment by abbyad** [comment]
Good find @jillrshah! Changing the calc to have spaces around the `<` makes it work in 2.13.0-beta.14.

# Works
`<bind constraint=". &lt; today() and ((decimal-date-time(.)+294) &gt;= decimal-date-time(today()))" jr:constraintMsg="jr:itext('/pregnancy/group_lmp/g_lmp_calendar:jr:constraintMsg')" nodeset="/pregnancy/group_lmp/g_lmp_calendar" type="date"/>`

# Doesn't Work
`<bind constraint=".&lt;today() and ((decimal-date-time(.)+294) &gt;= decimal-date-time(today()))" jr:constraintMsg="jr:itext('/pregnancy/group_lmp/g_lmp_calendar:jr:constraintMsg')" nodeset="/pregnancy/group_lmp/g_lmp_calendar" type="date"/>`

 @alxndrsn this may be related to updating to the latest Enketo?

Similar to https://github.com/medic/medic-webapp/issues/1363

We may have forms out there that would stop working with this change, so ideally we can fix this before releasing 2.13.

**Comment by abbyad** [comment]
This form is used in Standard config, and can be seen on standard.dev (2.13.0-beta.14), and release.dev (2.12.5), although a fixed version may be put on standard.dev for the sake of testing.

**Comment by alxndrsn** [comment]
Yeah, this is likely a bug in the xpath parser, although it may have been fixed in the latest beta.  I will investigate.

**Comment by abbyad** [comment]
I have temporarily "fixed" the form in standard.dev for the sake of testing. We should still make sure this is fixed upstream though.

**Comment by alxndrsn** [comment]
Yeah, this was fixed in openrosa-xpath-evaluator 1.4.1, so should be fixed in webapp master too.

**Comment by sglangevin** [comment]
This is working in 2.13.0-beta.15. Closing and moving to ready.
