### ISSUE TITLE
Form title not used in mobile view for contact forms

### ISSUE THREAD

**Issue by jillrshah** [medic/medic-webapp#3911]
In Standard.dev (in 2.13.0-beta.14): The desktop view shows the form title as "New Area," and in the mobile view, it's just a generic "New Place."

Screenshots below, healthcenter user. 

![image](https://user-images.githubusercontent.com/22451829/30410587-0a1929e8-98da-11e7-98d6-9a111e0a3ebf.png)

![image](https://user-images.githubusercontent.com/22451829/30410613-322f0f7e-98da-11e7-88ec-792f133825d8.png)

**Comment by sglangevin** [comment]
This is the expected behavior on mobile. Title moves to within the white background and the top bar says New Place. Closing.
