### ISSUE TITLE
Sentinel's fetchHydratedDoc function should use only fetch contacts that aren't already present in the lineage list

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3913]
See: https://github.com/medic/medic-sentinel/blob/master/lib/lineage.js#L74-L76

A standard structure for us is a report, with the CHW as a contact, whose parent is the CHW area, whose contact is the CHW.

In this situation we will fetch the CHW *again*, because it's a contact (we fetched it the first time as part of the parent lineage view request).

We should change the code so that before fetching contacts, filter out contacts we already have, and put them back in the contact list on the other side.

**Comment by SCdF** [comment]
Over to you @garethbowen

**Comment by garethbowen** [comment]
Merged.

**Comment by garethbowen** [comment]
For AT check that the lineage available to sentinel is still complete and correct, for example, when generating scheduled messages.
