### ISSUE TITLE
Forms appearing in Devanagari script (either Hindi or Nepali) when any language other than English is selected

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3915]
Seen on alpha.dev v2.13.0-alpha.7490 when logged in as a restricted user. I changed my language to Spanish and when I opened a new pregnancy form, it was in Devanagari script.

Not sure if this is due to any recent translation or Enketo changes, but I discovered this when attempting to AT #3459. @alxndrsn any ideas?

**Comment by garethbowen** [comment]
Looking at the [pregnancy form in standard](https://github.com/medic/medic-projects/blob/master/standard/forms/app/pregnancy.xml) there is no Spanish translations in the `itext` element, just "en", "hi", and "id". "hi" is first so my guess is that is picked as the default when the requested language isn't found.

@sglangevin I don't think this is a bug - either provide Spanish translations in the form, or change the order of the `translation` elements to change the default.

**Comment by sglangevin** [comment]
@garethbowen sorry for the delay. That makes sense to me. I had tried more than one language, but always saw Devanagari script. It must be that the languages I tried all didn't exist in the form. Closing for now and will open a new issue if I find something that appears to be a bug.
