### ISSUE TITLE
Fix "db.type() is deprecated and will be removed in a future version of PouchDB"

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3925]
The above is getting splatted into the console.

Work out why we're getting it and change our usage of PouchDB to avoid it.

**Comment by garethbowen** [comment]
This is coming from worker-pouch - I've raised an issue and submitted a PR: pouchdb-community/worker-pouch#43

**Comment by ngaruko** [comment]
Does this need any AT from QA @garethbowen ?

**Comment by garethbowen** [comment]
Yes. Make sure the issue is no longer occurring.

**Comment by ngaruko** [comment]
LGTM 
_**before**_
![image](https://user-images.githubusercontent.com/6979995/50756540-6ee4fe80-12c1-11e9-8748-e442c2de6504.png)

**_after_**
![image](https://user-images.githubusercontent.com/6979995/50756595-8b813680-12c1-11e9-9417-3d2c23c37749.png)

**Comment by sookwalinga** [comment]
Seems this issue has again resurfaced in version 4.x, I am testing on v4.2.0 and I get the same warning: "db.type() is deprecated and will be removed in a future version of PouchDB"
