### ISSUE TITLE
Non-relevant group shown in form

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#3928]
The first group of many of our forms is shown conditionally, but since the Enketo was updated in 2.13.0-beta.17 as part of #3870 that first group is being shown as disabled (greyed out) when not `relevant`. This can be seen on standard.dev and alpha.dev using any Action form accessed from the Contact profile or any Contact creation form. Relevant fields or groups on subsequent pages are handled correctly.

### _Non relevant group is shown as disabled as opposed to hidden as it should be_
![issue_0_contact](https://user-images.githubusercontent.com/789512/30644112-4ea2b0c0-9ddf-11e7-97ae-6fabaddce7cf.png)

### _Cannot go back, because the first page is not relevant... which is expected_
![issue_1_contact](https://user-images.githubusercontent.com/789512/30644195-a081888a-9ddf-11e7-86d9-91574d61352f.png)

**Comment by abbyad** [comment]
Here is a test form that has three groups, shown as three pages. The first two have relevant set to false so should _never_ show, but the first page does show as disabled. Form is also temporarily loaded [here on standard.dev](https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/add/issue:3928).

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test Issue 3928</h:title>
    <model>
      <instance>
        <issue-3928 delimiter="#" id="issue:3928" prefix="J1!issue:3928!" version="2017-09-20">
          <page1>
            <note/>
          </page1>
          <page2>
            <note/>
          </page2>
          <page3>
            <note/>
          </page3>
          <meta>
            <instanceID/>
          </meta>
        </issue-3928>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/issue-3928/page1" relevant="false()"/>
      <bind nodeset="/issue-3928/page1/note" readonly="true()" type="string"/>
      <bind nodeset="/issue-3928/page2" relevant="false()"/>
      <bind nodeset="/issue-3928/page2/note" readonly="true()" type="string"/>
      <bind nodeset="/issue-3928/page3/note" readonly="true()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/issue-3928/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/issue-3928/page1">
      <label>Page 1</label>
      <input ref="/issue-3928/page1/note">
        <label>This page should not show. In 2.13.0-beta.17 it shows as disabled.</label>
      </input>
    </group>
    <group appearance="field-list" ref="/issue-3928/page2">
      <label>Page 2</label>
      <input ref="/issue-3928/page2/note">
        <label>This page should not show.</label>
      </input>
    </group>
    <group appearance="field-list" ref="/issue-3928/page3">
      <label>Page 3</label>
      <input ref="/issue-3928/page3/note">
        <label>This page should be the first page given that the previous two pages have relevant=false()</label>
      </input>
    </group>
  </h:body>
</h:html>
```

**Comment by SCdF** [comment]
Interesting it seems to be just the first page. And is definitely a version change between this beta and the previous (it actually looked fine, and then the popup for a new version appeared…).

**Comment by SCdF** [comment]
Well for fun I tried updating enketo to the latest build to see if it would fix it: no dice. It doesn't look like we need the last enketo patch though, which is nice (though not something to screw with 2.13 over).

Side note: there is a weird line in our [GruntFile.js](https://github.com/medic/medic-webapp/blob/master/Gruntfile.js#L59):
```
        options: {
          transform: ['browserify-ngannotate'],
          alias: {
...
            '../../js/dropdown.jquery': 'bootstrap/js/dropdown', // enketo currently duplicates bootstrap's dropdown code.  working to resolve this upstream https://github.com/enketo/enketo-core/issues/454
```

Weird because the linked ticket is closed. Reading the ticket nothing was changed. So it's unclear without digging into it in detail if we need this anymore.

**Comment by garethbowen** [comment]
I've debugged the issue and found a workaround described in the linked enketo-core issue.

**Comment by alxndrsn** [comment]
This bug should now be fixed, but long-term we should aim to get a fix into enketo as per https://github.com/enketo/enketo-core/issues/459

**Comment by sglangevin** [comment]
I can AT this one, unless you guys (@alxndrsn  and @abbyad) are doing that together in person.

**Comment by abbyad** [comment]
Ya, we are doing the AT for this one here as soon as the beta completes.

**Comment by garethbowen** [comment]
Nice one!

**Comment by abbyad** [comment]
The action forms work well in beta 21, but the contact form still has non-relevant groups showing on the first page. Returning so that contact forms can be processed accordingly to hide the first page if it is not relevant.

**Comment by abbyad** [comment]
Works well for App and Contact forms in beta 22. The non-relevant pages are hidden even on first page, and was able to go through and submit the forms as expected.

Moving to Ready, and we can do more Enketo testing as part of release testing.
