### ISSUE TITLE
Create a S3 bucket for test results and screenshots

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#3940]
We sometimes have test failures on Travis but cannot figure out what went wrong since we can’t save screenshots on Travis. So, we thought we could save those (only if the test fails) on our AWS, maybe just have a bucket where we can save those screenshots for reference and debugging.  We don’t expose any AWS credentials in the code (the code needs the access id and secret key but  these encrypted and not exposed on GH or Travis).
Then we will have a report and failed screenshots 
![image](https://user-images.githubusercontent.com/6979995/31158953-1f313c98-a911-11e7-8b62-8b965d9e15ee.png)

**Comment by henokgetachew** [comment]
I created the S3 folder for you but it looks like I don't have the permissions to create the user that will be accessing it.  That means I can't give you the access key ID and secret access key.
cc: @browndav

**Comment by browndav** [comment]
Completed.
