### ISSUE TITLE
Unread reports bubble not working as expected

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3944]
Seen on alpha.dev logged in as admin. When you log in, you'll see no bubble for unread reports, but there are 5 unread reports if you look at the Reports tab.
![image](https://user-images.githubusercontent.com/1286381/31198391-fd52f42a-a908-11e7-8529-b12a3758d5cf.png)

**Comment by garethbowen** [comment]
The algorithm works by counting all the reports you can see and then subtracting all the reports you have read. In this case some documents had been deleted from the database but the meta docs weren't deleted at the same time. I've manually deleted the orphaned meta docs so alpha.dev now works as expected, but we should fix this properly. A couple of ideas come to mind...

1. Change the algorithm to use UUIDs rather than just counts so deleted read docs don't get counted as read. This would reduce performance on large instances due to the increased data, but is very reliable.
2. Use a change listener in API to listen for deletions and delete the corresponding meta docs.

**Comment by SCdF** [comment]
@garethbowen what are you referring to when you talk about meta docs here? Do you mean the `-info` documents that are created?

Ideally I'd like to move those out into an entirely separate database as they are only useful on the server side, alongside generally moving "sentinel stuff" out into a separate db. Details on #3423

**Comment by garethbowen** [comment]
@SCdF No, I'm talking about the read status docs that are in a separate `medic-user-<username>-meta` db. The `-info` docs you're talking about will also get out of sync if the parent doc is deleted which will cause a slight performance regression over time but won't cause any problems that are visible to the user as far as I can tell.

Depending on the solution it may be good to remove the `-info` docs at the same time as cleaning up the `-meta` db.

PS: Naming is hard.

**Comment by garethbowen** [comment]
Perhaps we should use a sentinel system transition to clean up info and meta docs when their parent doc has been deleted...

**Comment by garethbowen** [comment]
The problem with the sentinel system transition is it would seriously slow down sentinel on large deployments (say 1000s of offline users).

One compromise is to have a sentinel system transition to clean up the data for online users (admins) and a changes listener in the client so when a doc deletion is replicated the data is cleaned up in the users local database. The downside to this approach is running essentially the same code in two places but it may be the only workable solution. I'll give it some more thought and come back to it tomorrow.

**Comment by SCdF** [comment]
Another option I thought of while running is still having two places where the logic is expressed, but both in webapp:
 - Upon a change listener document delete, delete any read documents for the doc you just deleted
 - Upon **boot**, work through a manual consolidation process where we check existing read docs against document ids.
 
The latter logic has a couple of levels of complexity we could go for:
 - Batching, take N read doc ids and bulk HEAD (ie `!include_docs`) the DB, removing read docs that don't have corresponding docs
 - Same as above, but reduce on count, and if the count !== BATCH_SIZE do the above bullet point for those docs

**Comment by SCdF** [comment]
You could also potentially only run that sometimes (once a week or something). The major downside is that this gets worse and worse over time, especially if we ever add mark all as read.

**Comment by SCdF** [comment]
Post-run shower thoughts: no, what we discussed (in webapp in a changes listener, and in sentinel as a meta transition thing) is pretty much the right approach:
 - It's the most efficient of everything we've thought of
 - It is clearly sentinel's job, to clean up and modify data after the fact
 - If we drop sentinel ignoring deleted documents from its core loop (and move it into all the existing transition filters) it can just be another transition, though this would mean for now it would be synchronous with the rest of the transitions
 - In the future it easily fits with the "fast" style of transition that are order independent, can be run in out of order in-memory batches etc
 - In the future it easily fits with the kind of transition that could run on both the server and the client, eventually centralising the logic in one piece of code

**Comment by garethbowen** [comment]
Two PRs for review please @SCdF 

For AT:

1. Log in as an offline user (non-admin) and mark a report read
2. Log in as an admin and mark the same report read
3. Record what the read status bubble says for each user (make sure it's at least 1!)
4. Delete the doc and wait for sentinel to process the change and replication to occur
5. Ensure the read status bubble still has the same number as in (3).

**Comment by SCdF** [comment]
Back to you, buckaroo

**Comment by garethbowen** [comment]
Merged.

@SCdF I think I've made all the changes you requested - if I've missed anything let me know and I'll patch it straight into master.

**Comment by sglangevin** [comment]
AT is currently blocked because there isn't a successful build of master that includes this change and beta.dev is currently 502ing after an attempt to upgrade to 2.14.0-beta.1. Info on the medic-api error is in #support.

**Comment by sglangevin** [comment]
Ok, we got a green build in alpha and I was able to test. I have no bubble at all when logged in as a restricted user, so I can't determine what is happening there. For admin, I had 4 unread reports. I read one of them, bringing me to 3. Then I deleted the one I had just read and I ended up with 2 unread reports, even though I still have the 3 unread reports. Refreshing the page brought me back to 3 again, but it required a browser refresh, not just switching to another page and back.

We should definitely figure out why the restricted user doesn't have a count of unread reports (the indicator for unread messages is working).

Tested on 2.14.0-alpha.7798.

**Comment by garethbowen** [comment]
I've added a listener on the meta db which means admins will get their bubbles updated when their read documents are deleted not just on page refresh. There may be a little lag while sentinel processes the change.

> We should definitely figure out why the restricted user doesn't have a count of unread reports (the indicator for unread messages is working).

I tried and it worked for me. It's probably because you already have deleted read reports in your read database. To test this delete your `medic-user-<username>-meta` database from your browser and the server which will reset everything to unread.

**Comment by garethbowen** [comment]
Round two code review please @SCdF

**Comment by SCdF** [comment]
LGTM, merged

**Comment by sglangevin** [comment]
LGTM. Moving to ready.
