### ISSUE TITLE
Remove stats collection in API

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3950]
We have a small scheduled task that runs periodically to submit anonymised data to a centralised server to help us measure impact. This was added primarily for DIY where we may not know where or how our software is being used. Until DIY is rescheduled we should disable stats collection and remove the associated code. The impact measurement for all our instances is now done via the postgres analytics database.

1. Remove the `stats-submission.js` and `usage-stats.js` schedules from the `api/schedules` directory.
2. Remove the `api/scheduler.js` which has never been used for anything except this.
3. Remove the `usage_stats_by_year_month` view which is only used for this.
4. Remove the section about stats collection from the guided setup modal dialog.
5. Remove the section about stats collection from the configuration schema.
6. Remove anything else you can think of...

**Comment by SCdF** [comment]
Two PRs for you @garethbowen

**Comment by garethbowen** [comment]
Both merged, and api bumped. Nice work!

**Comment by garethbowen** [comment]
For AT: run API for 24 hours and ensure the log doesn't say anything like "Schedule "..." completed successfully".

**Comment by ngaruko** [comment]
LGTM
