### ISSUE TITLE
Add support for death reporting workflow

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3956]
This issue adds support for a death reporting and confirmation workflow involving CHWs and managers. We need to support reporting death as well as reversing a death. 

The basic workflow for reporting a death is as follows:

- CHW reports a death in the community via SMS or an app form
- This death report triggers a task for the manager in the app OR sends her an SMS notification
- This task opens a second form (death confirmation) that the manager fills out and submits OR the manager submits a death confirmation form via SMS
- If the manager confirms the death, the person's profile updates to show that they are deceased
- NOTE: The manager can also fill in the death confirmation form directly (in app or via SMS) and the person's profile updates to show that they are deceased

The basic workflow for reversing a death is as follows:

- CHW requests a correction via SMS or an app form
- This request correction form triggers a task for the manager in the app OR sends her an SMS notification
- This task opens an undo death form that the manager submits OR the manager submits an undo death form via SMS
- If the manager confirms that the death should be reversed, the person's profile updates to show that they are alive
- NOTE: The manager can also directly undo the death (in app or via SMS), which should update the profile to show that the person is alive

[Design spec is here](https://docs.google.com/document/d/1EKmOdip2cebl_BbIJNbl1kTbG3rYxaxVYmI_mL5y9M8/edit#)

Summary of UI changes (these are applied once a death is confirmed). See the design spec for more info:

- [x] person's icon changes from pink to gray (screenshot 1)
- [x] the word "Deceased" is added either next to or immediately below the person's name on their profile (screenshot 1 & 2 are mobile view, on desktop the word "Deceased" should be immediately next to the person's name, see screenshots 6 & 7)
- [x] on the family page, a new row appears at the end of the list of family members that says "View deceased" (screenshot 3)
- [x] when you click on "View deceased", you are taken to a detail page that lists the deceased family members. These are the same as the content rows on the family page except that they show the age at the time of death and have a relative date of death on the right, e.g. "Died 3 years ago" (screenshot 4)
- [x] in search, deceased people should have gray icons and show up at the bottom of the list (screenshot 5)

**Screenshot 1**
![image](https://user-images.githubusercontent.com/1286381/31474123-a1dd9d7a-aead-11e7-8af9-2b9254440edb.png)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/1286381/31474145-ba1f7318-aead-11e7-9f34-e4d8de20dbd0.png)

**Screenshot 3**
![image](https://user-images.githubusercontent.com/1286381/31474151-c3fdc010-aead-11e7-9374-404f44122a7a.png)

**Screenshot 4**
![image](https://user-images.githubusercontent.com/1286381/31474161-ce8d154e-aead-11e7-9712-7cf863a03145.png)

**Screenshot 5**
![image](https://user-images.githubusercontent.com/1286381/31474182-fd556dcc-aead-11e7-9661-aca4cee1b5ec.png)

**Screenshot 6**
![screen shot 2017-10-12 at 9 04 29 am](https://user-images.githubusercontent.com/1286381/31513301-cdd9cefe-af42-11e7-899e-5d33173e9ea7.png)

**Screenshot 7**
![screen shot 2017-10-12 at 9 04 44 am](https://user-images.githubusercontent.com/1286381/31513355-fcab46d6-af42-11e7-84b6-6e7a222868f5.png)

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by garethbowen** [comment]
## Configuration

1. Create forms for death reporting, confirmation, rejection, and undo.
1. Configure tasks and/or responses to prompt for confirmation/rejection.
1. Configure the contact summary to show the death card.
1. Update `app_settings` to have a `death_reporting` property with `mark_deceased_forms` and (optionally) `undo_deceased_forms` arrays. The arrays must contain a list of strings for all form types that should trigger that action. 
1. Enable the `death_reporting` transition.
1. When a report of one of the `mark` types is received then the transition looks the patient up using the `patient_id` in the report's fields and mark them as deceased. The undo types mark the patient as alive.

### Example app settings

```json
{
  "transitions": {
     "death_reporting": true
  },
  "death_reporting": {
    "mark_deceased_forms": [ "dc", "death-confirm" ],
    "undo_deceased_forms": [ "uc" ]
  }
}
```

**Comment by ngaruko** [comment]
A few questions came up as I was testing this feature:

1. According to the [workflow](https://docs.google.com/document/d/1EKmOdip2cebl_BbIJNbl1kTbG3rYxaxVYmI_mL5y9M8/edit#), the 'report death` is only available to CHW's not to managers, it this meant to be a configuration thing ? Amanager can still access the form (on `alpha.dev`)

**Comment by garethbowen** [comment]
The enketo forms are configurable. We don't have a concept of permissions for sms forms. @sglangevin Is this required? It could be done generically so all forms could have a permission/role required?

**Comment by sglangevin** [comment]
No, that's not required for this feature. There are actually 3 scenarios here: CHW & supervisor on Medic app, CHW on SMS and supervisor on Medic app, and CHW & supervisor on SMS. The only case where we wouldn't be fully controlling this would be the 3rd one, and I think we'd just train each set of users on the appropriate set of forms. We can come back to the issue of permissions/roles for SMS forms in the future.

**Comment by sglangevin** [comment]
Sorry for the delay here - Bede had asked me to AT a while ago and I haven't gotten to it. So I think this actually fails AT because it requires the patient to have a Medic ID. We have many projects where we aren't using Sentinel and therefore don't have Medic IDs for every patient. In those cases, we need to be able to list the UUID and have the patient's profile updated based on their UUID as opposed to the Medic ID. @garethbowen I'm assigning this back to you. Sorry it's been so long since you worked on it.

**Comment by sglangevin** [comment]
One other small point of feedback. According to the mock-up, death confirmation reports should show up on the place page for the `clinic` level place the person belongs to.

@amandacilek @diannakane what should happen to other past reports about deceased people? Should those show up on the place page? Or only the death confirmation?

**Comment by garethbowen** [comment]
@vimemo Code review please. This is a change to a sentinel transition to allow it to work with UUIDs (used in xforms) or patient shortcodes (used in sms forms). Let me know if it doesn't make sense!

**Comment by garethbowen** [comment]
Thanks @vimemo - I've fixed and merged that PR. Now I have another one for you! This one is about the reports of deceased children showing up in the households reports list.

**Comment by garethbowen** [comment]
The death_reporting transition now accepts UUIDs as well as shortcode IDs, and place contacts show reports for deceased children as well as live children. Returning to AT.

**Comment by ngaruko** [comment]
Do we need closed before 2.14 release @sglangevin ?

**Comment by sglangevin** [comment]
No - this is scheduled for 2.15 so it needs to be tested before the release of 2.15.

**Comment by sglangevin** [comment]
LGTM. Working well!
