### ISSUE TITLE
Find a better way to determine if a user is online-only

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#3960]
Currently we check for `_admin` or `national_admin` roles. This has worked ok till now however it's inflexible and leads to hard to read code.

One solution is to have an "offline" permission which defaults to being checked for all roles other than `national_admin`.

Be sure to update all code that relies on this, including the `medic/online_user_settings_by_id` view.

**Comment by garethbowen** [comment]
We recently removed a `can_access_directly` permission (#4144) which was being used for this in some situations. The problem was that because it was a permission it was configurable and setting it for district admin users didn't work. If this is done via a permission it either needs to be not editable, or we need to make it so turning it on for district admins works as expected.

**Comment by garethbowen** [comment]
While working on this I realised there's a bug with the current implementation - if a document is deleted that a user has read but the user is offline then there is a race condition to get the changes handler registered before the document is replicated.

When ATing this make sure...

1. If an offline user deletes a read document while offline the unread count is not updated. This is expected because the app should delete the doc and the "read status" doc at the same time resulting in the same number of read docs.
2. If another user deletes a document a user is read while the user is offline then when they next log in the unread count is not updated.

**Comment by garethbowen** [comment]
Code review please @vimemo - the build is failing for the same reason as `master` so I think that's ok...

**Comment by garethbowen** [comment]
This needs to be backported to `2.16.x`.

**Comment by garethbowen** [comment]
Merged and backported to `2.16.x`

**Comment by sglangevin** [comment]
@ngaruko can you do the AT that Gareth suggested? I confirmed that it's possible to create a new user role that is "online" so it seems like the main point of this issue is working. I'm not able to easily create a test scenario to make sure his point about read documents has been resolved.

**Comment by ngaruko** [comment]
LGTM. Tested on `alpha.dev`. 
1- Logged in as restricted user. Simulated the 'offline' mode. Read one of the 4 unread report. Unread Count goes down to 3 in this browser. Logged in as same user on a different device/browser. Unread count is still 4. Then I deleted the read doc with the offline user, unread count stays at 3. The other online log-in does not update.

**Comment by garethbowen** [comment]
@ngaruko Yeah that's confusing... how about this:

1. User A goes offline and reads a doc - the unread count is updated.
2. User B goes online and deletes the same doc - wait for it to sync and sentinel to run.
3. User A goes online - wait for everything to sync.
4. Check that the unread count for User A is the same as at the end of step 1.

Also, because this is fixed in 2.16.0 you need to be ATing this on beta-old.dev instead of (or as well as) alpha.dev.

**Comment by sglangevin** [comment]
@ngaruko if you're able to test this today, that would be helpful. We are pushing to get 2.16.0 released by the end of this week.

**Comment by ngaruko** [comment]
Works on `beta-old.dev`
**_User A offline_**
![image](https://user-images.githubusercontent.com/6979995/41960778-b838d022-7a44-11e8-964d-d184b3fd11c6.png)
![image](https://user-images.githubusercontent.com/6979995/41961006-53d7312c-7a45-11e8-8f75-ee6a7d14218d.png)

 **_User B online_**
![image](https://user-images.githubusercontent.com/6979995/41960794-c54c860a-7a44-11e8-9bb1-751ebbb5c4e5.png)
**_Deletes the report_**
![image](https://user-images.githubusercontent.com/6979995/41960949-2afd358a-7a45-11e8-88da-bf3d12449cd6.png)
 **_User A back online_**
![image](https://user-images.githubusercontent.com/6979995/41961129-b34f18d6-7a45-11e8-86ff-29c0adec50ad.png)
