### ISSUE TITLE
Minor updates to Enketo UI

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#3961]
This issue updates the UI for Enketo forms on mobile and desktop. These are small tweaks for now and we hope to come back and make additional changes in the future. [Design spec](https://docs.google.com/document/d/1bnbQ17I9fq1ZRbu2v9otaRpUXn_7eODe7YTYzsXQoDg/edit).

**Update form header on desktop only**:
- [x] form title is 20px bold, in black
- [x] title is left-aligned, 20px from the left edge of the form card
- [x] add a 1px grey horizontal line after to separate the form header from the form content (matches new Messages treatment)

**Update form text and spacing**:
- [x] Put a 20px buffer on the left and right sides of the form card
- [x] Form group titles should be blue, 18px, bold
- [x] If there are nested groups, the sub-title (nested group name) should be black, 18px, normal weight
- [x] 30px spacing between the group title and the first question OR between the group title and group subtitle (if there is a subtitle, which will be there if there are nested groups)
- [x] If there is a subtitle, 20px between the subtitle and the first question
- [x] 30px between answer options/user inputs and the next question
- [x] 20px spacing between the question and the answer/user input
- [x] Move the required fields asterisk out of the left margin to the right side of the text
- [x] Question for developers: Are the double chevrons sometimes seen before the section sub-titles added through styling or in configuration? If added during styling (i.e. under our control) then let’s remove them.

**Increase size of click targets**:
- [x] Increase size of radio buttons to 24px x 24px
- [x] Increase size of checkboxes to 24px x 24px
- [x] Increase vertical space between radio buttons and checkboxes to 16px
- [x] Increase the minimum height of text boxes (user input) to 45px tall and add 4px rounded corners and 1px gray border (text boxes should also have the same 20px buffer on either side that the rest of the form has)

### Screen shots for reference
**Mobile**
![mobile form half new](https://user-images.githubusercontent.com/26235957/31742832-d00cd26e-b40d-11e7-9f00-818d0a1fab08.png)

**Desktop**
![desktop form half new](https://user-images.githubusercontent.com/26235957/31742839-d592aa4c-b40d-11e7-9b3e-5070a775aa3a.png)

**Comment by amandacilek** [comment]
Note: After talking with Gareth, I've made a few updates to this spec.

Removed: Button styling. Will wait for nav update to change button styles globally.
Added: Small tweak to how we represent required fields (moving the asterisk).

**Comment by garethbowen** [comment]
@amandacilek Can you show me an example of a nested header? I'm not sure what bit this applies to:

> If there are nested groups, the sub-title (nested group name) should be black, 18px, normal weight

**Comment by amandacilek** [comment]
@garethbowen Sharon wrote "nested header" but I think what we mean is these sub-headers here. Lots of forms don't have these sub-headers but some do.

![screen shot 2017-10-26 at 9 34 36 am](https://user-images.githubusercontent.com/26235957/32065279-21796328-ba31-11e7-9643-b674339c6676.png)

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by SCdF** [comment]
Nice one!

**Comment by sglangevin** [comment]
I'll come back to this during AT, but the "nested headers" come from nested groups in the XLSform. The top-level group corresponds to section title in the mock-up and the nested group corresponds to the section subtitle in the mock-up.

**Comment by sglangevin** [comment]
LGTM. @amandacilek do you want to take a look? If you have a login to alpha.dev, the changes are visible there.

**Comment by amandacilek** [comment]
The changes look good to me except for one thing - I noticed that dropdown boxes are still something like 35px tall - can we make those the taller 45px? Not a big deal if this is hard or time consuming.

**Comment by garethbowen** [comment]
@amandacilek @sglangevin I've updated the height of the select2 fields to 45px to match the other fields. Back you to!

**Comment by sglangevin** [comment]
@garethbowen this looks correct for select2 fields, but not for single and multi-select fields with appearance "minimal". That appearance makes the field appear as a drop-down:

### select2
![image](https://user-images.githubusercontent.com/1286381/32285980-43425714-bee9-11e7-8fa9-683d24e6110c.png)

### Single-select field appearing as drop-down
![image](https://user-images.githubusercontent.com/1286381/32285958-32c4d7b8-bee9-11e7-8ea7-87a3d04a5c0f.png)

**Comment by garethbowen** [comment]
Ok, try this!

**Comment by sglangevin** [comment]
LGTM. Moving to ready.
