### ISSUE TITLE
Horticulturalist eb UI 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3965]
**Important**: This is a public repository. Anyone in the world can see what's posted here. If you are posting screenshots or log files, please **carefully examine them for** the presence of any kind of **protected health information** (PHI). Images or logs containing PHI _must_ be posted in fully-redacted form, with no visible PHI.

**Comment by garethbowen** [comment]
@SCdF I assume you created this by accident?

**Comment by SCdF** [comment]
lol, apparently!
