### ISSUE TITLE
Remove `/api/v1/messages` endpoint

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#3971]
It is reportedly buggy, and unused: https://github.com/medic/medic-webapp/issues/3400

**Comment by garethbowen** [comment]
This is [used in medic-transport](https://github.com/medic/medic-transport/blob/develop/lib/adaptor/medic-mobile.js#L668) although I'm not sure if medic-transport is still used...

**Comment by alxndrsn** [comment]
I'm fairly confident it's not used.  @browndav ?

**Comment by browndav** [comment]
Definitely not used, and the API is definitely unreliable. Pull it out IMO.

**Comment by garethbowen** [comment]
The above PR is (basically) ready for merge, but I'll schedule it for 3.0.0 so the breaking changes are released in a major.

**Comment by ngaruko** [comment]
LGTM. The only thing we need to do is remove this from the api [documentation](https://github.com/medic/medic-api#messages). Will leave this open as reminder to edit the docs, unless otherwise suggested @alxndrsn  @garethbowen ?
