### ISSUE TITLE
Build conflict scripts to aid tech leads 

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3979]
Initial stab here: https://github.com/medic/medic-webapp/tree/master/scripts/conflicts

Turns out it's much more complicated. What I want to do is outlined in the README.

**Comment by garethbowen** [comment]
@SCdF Assigning to you for triage - is this still something that we want to work on?

**Comment by SCdF** [comment]
I don't think so. I think the current level of support has been fine and I haven't seen any requirement for something more comprehensive.
