### ISSUE TITLE
Null changes feed callbacks causing stack traces

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3985]
So sometimes we have null changes feed callbacks:
![image](https://user-images.githubusercontent.com/583851/31815737-8718bd4c-b585-11e7-9ec5-cee28749377b.png)

I'm not really sure why we'd have those, that seems weird to me.

However, there is code that looks like it's supposed to gate against null callbacks, so that implies it's an expected behavour.

However, that code looks like the opposite of what it should be. I've fixed it in the following PR: https://github.com/medic/medic-webapp/pull/3984

No test changes were needed, which looks like a hole in our test coverage.

@garethbowen this is just a WIP / RFC. I'm not sure which is the bug: that there are null callbacks, or that we aren't gating against them properly. Let me know and I'll fix it in whichever direction is correct, with tests, next week.

NB: this does affect the 2.14 beta, so whatever fix we do will need to be backported to 2.14.
NB: it is also unclear if this actually causes bugs per se, or just causes an exception to be thrown. Regardless, IMO it should be fixed.

**Comment by garethbowen** [comment]
Back to you @SCdF

**Comment by garethbowen** [comment]
This was likely introduced in https://github.com/medic/medic-webapp/commit/b44a03dccf07e29a9c2801bc7bc07203e16bfb30#diff-450479d3ef39b9bb6c6d393ab68cb33e

**Comment by SCdF** [comment]
@garethbowen so the issue is here: https://github.com/medic/medic-webapp/commit/b44a03dccf07e29a9c2801bc7bc07203e16bfb30#diff-450479d3ef39b9bb6c6d393ab68cb33eL87

I remember seeing this when code reviewing, and I presumed because you explicitly changed it to this style that was intentional. However, it is causing this bug. Is just changing it back acceptable (see [PR](https://github.com/medic/medic-webapp/pull/3987)) or was that change also achieving something else?

**Comment by garethbowen** [comment]
Yeah I don't know what I was thinking. The change looks good. Maybe add a unit test that exposes it so I don't do it again?

Feel free to merge and backport, thanks!

**Comment by SCdF** [comment]
Added a test. Merged, backported to 2.14.x

**Comment by SCdF** [comment]
AT: Performing actions that cause data to change (editing a document, sending a message) after navigating around tabs (ie registering and deregistering changes listeners) should not cause errors to be dumped in the logs.

**Comment by sglangevin** [comment]
@ngaruko what is the status of AT on this issue?

**Comment by ngaruko** [comment]
LGTM
