### ISSUE TITLE
Have horticulturalist pre-warm views

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#3993]
We should update Horticulturalist so that it takes care of pre-warming views for us. This can be done transparently to users of the system, reducing deployment downtime.

Steps:
 - Remove DDOC extraction from api, and move it into horticultualist. Once it pulls a ddoc down as `medic:staged` it should also extract the other ddocs and name them similarly (ie `medic-cilent:staged` etc).
 - Go through each ddoc in parallel, and use the couchdb api to find one view (any view) and run a limit=1 query against it. If the query times out or fails, retry it. View warming is complete once all ddoc's return the single value from the selected view.
 - Somehow indicate to we're ready to do the ddoc swap (ie change a value somewhere, or use ddoc naming (like `:staged`) in a more complicated way to indicate where in the process we're up to
 - Make sure that the UI can query this days later: i.e., it doesn't require a persistent connection to learn if we're ready to initiate the ddoc swap
 - Change the front-end so that instead of one click to deploy, there are no (sometimes, see discussion) two clicks. The first gets us up to this point and may take some time, the second does the actual deploy
 - Change the horti daemon so that it deploys all extracted ddocs, and not just `medic` , and also kicks off ddoc view cleanup

Q: Should this happen in the api portion of the horti daemon portion? My vote is API, and just leave the horti daemon to manage processes and do the final last section ddoc swapping

Q: How do we want to do the two clicks? Do we want to have it so they must click twice, or that there is some way to only click once (ie just do it, view warming, deploy and all)?

**Comment by SCdF** [comment]
My proposed solution:
 - One doc to orchestrate the deployment, e.g. `horticulturalist-deployment`. This document will be followable by watching the _changes feed.
 - Two buttons on the deploy page, "Stage" and "Deploy", with hover text (and ideally UI indicators like colour difference) explaining the difference between each.
 - Two API endpoints, `stage`, `deploy`

On the backend:
 - `stage` starts the staging process async (ie it returns quickly, once it's inited the orchestration doc). Async, it pulls down the ddoc, extracts the other ddocs, and warms the views. It stores its state in the orchestration doc. Optionally, api supports looking for this at startup, understanding what stage its at and continuing (later improvement?)
 - `deploy` runs `stage` if the doc doesn't exist (ie you didn't hit stage already), and / or then changes the orchestration doc to imply deployment should happen
 - The Horti daemon watches the orchestration doc, and when it sees it should, it name-swaps the `:staged` ddocs (we could write a view to find these) to non-staged versions between stopping and restarting the services, and then deletes / resets the orchestration doc

UI:
 - Have two buttons for each release as noted above
 - Clicking the deploy button does what it does now: a throbber that is never dismissed, and you wait until you get the refresh this page dialog indicating that the deploy has finished.
 - Clicking the stage button turns the button into a throbber (or disables it, or whatever out convention is for showing something is happening), calls the `stage` api, and then waits until the next bullet point is fired (which will happen roughly as the `stage` call returns)
 - Have a watch on the orchestration doc, and use that to show staging status both at the top of the page in the status section, and also beside the release that is getting staged in the list. Also grey out the Stage button for this version, while staging is occurring.
 - Once the deploy is ready, have a deploy button at the top, say "Deploy $version", which does the fast deploy.

Bonus:
 - Code the backend properly to overriding one stage with another, with a deploy, or canceling (with a UI element to cancel a stage).
 - Support staging working over api restarts. This will probably make the above bullet point much easier, because the structure will make itr simpler (have one daemon in api that watches the orchestration document and understands what the next step is, and can change what its doing when the doc changes).

**Comment by SCdF** [comment]
Bumped priority from low to medium because there are a few tickets that this implementation will solve

**Comment by SCdF** [comment]
Also, we are going to run compaction against the DB as well, prior to running view warming.

Rough timeline would be:
 - Copy over DDOC
 - Compaction
 - Trigger view warming
 - Allow for deploy (either automatic or manual depending on if you're just staging)
 - Post deploy view compaction (to remove the now old view indexes)

**Comment by SCdF** [comment]
> The Horti daemon watches the orchestration doc

6+ months after I wrote this comment, it clicks that we can't actually do this! The Horti daemon has to do everything that is required for a deployment, otherwise bootstrapping doesn't work.

So instead, api has to just do the tiniest amount (write something somewhere implying that a deployment should take place) and the horti daemon has to do the rest

**Comment by SCdF** [comment]
@alxndrsn / @garethbowen I linked you both into three PRs, which contain stage one: moving horti over to using a build doc instead of just copying the ddoc over. It also fixes horti builds for the kanso-less world.

Naming scheme I've gone with at the moment, is `build_info` for metadata that gets built at build time, which complements our existing `deploy_info`, which gets built at deploy time.

**Comment by SCdF** [comment]
Merged. Requires horti 0.10.0

**Comment by ngaruko** [comment]
LGTM . Tested in `alpha.dev` v3.0.0
![image](https://user-images.githubusercontent.com/6979995/40695012-61187780-6413-11e8-99ba-f54d8d12f3a8.png)
