### ISSUE TITLE
Adjust the buffer space around RHS header icons

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#3997]
A few tweaks to make the layout of large 60 x 60 icons and text in the RHS more consistent between pages.

**On People page:**
- [x] Move the top person/place icon to the left, _decreasing_ the gap between the icon bounding box and the card edge from 20px to 10px.
- [ ] The text to the right of the icon (person's name, HoH) should start 75px from the card edge
![screen shot 2017-10-30 at 3 07 16 pm](https://user-images.githubusercontent.com/26235957/32198145-24e3ebd6-bd84-11e7-8bfd-0295d8f072c8.png)

**On Targets page:**
- [ ] Move the widget icon the right, _increasing_ the gap between the bounding box and the card edge from 5px to 10px.
- [x] The text to the right of the icon (widget title, timeframe) should start 75px from the card edge
![screen shot 2017-10-30 at 3 07 29 pm](https://user-images.githubusercontent.com/26235957/32198157-2c751942-bd84-11e7-8a6b-793ce173f16c.png)

**On Reports page:**
Stays as-is for now, but will be updated to match the above soon, hopefully as part of the nav update.

**Comment by garethbowen** [comment]
Done. I found the icon on the Targets page was already 10px from the card edge so I left it alone. If you still see it 5px from the edge then let me know where and I'll have another look!

**Comment by sglangevin** [comment]
@amandacilek I've updated alpha.dev - do you want to do a review?

**Comment by amandacilek** [comment]
Looks good to me!
