### ISSUE TITLE
problems with utf-8 character encodings

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#4]
the csv file that gets downloaded shows up garbled in preview (osx) but works ok in excel and other programs that "import" these files. 
http://cl.ly/2r3k2S0x1A0b1K2y1P35

tried setting the BOM but not luck http://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files

it would be nice if the characters where correctly encoded to work in osx preview.

**Comment by ngaruko** [comment]
This issue was moved to ngaruko/medic-webapp#4
