### ISSUE TITLE
Update styling for tasks due today

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4000]
If a task is due today, the word "Today" on the right-hand side of the task list should be bold and blue (#007DC7) per the mock-ups below.

### Single task
![today](https://user-images.githubusercontent.com/1286381/32250761-fc5bc9f0-be4a-11e7-82b8-c6020d014856.png)

### Task list
![tasks-duetoday](https://user-images.githubusercontent.com/1286381/32250763-fd9e6e30-be4a-11e7-8ee2-03c546ee31af.png)

**Comment by garethbowen** [comment]
Code review please @alxndrsn

**Comment by sglangevin** [comment]
LGTM.
