### ISSUE TITLE
Support patient hydration in `hydrateDocs`

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4003]
The `hydrateDocs` function in [`lineage.js`](https://github.com/medic/medic-sentinel/blob/master/lib/lineage.js) should support attaching the hydrated patient to `doc.patient` just like `fetchHydratedDoc` does.

See #3412 for original implementation

**Comment by garethbowen** [comment]
Merged! Moving to AT. AT instructions are in the PR linked above.
