### ISSUE TITLE
Target widgets don't initialize as expected

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4008]
If a target widget is based on a form that has never been submitted before, it appears blank (see screenshot). Notice the difference between the pregnancies registered widget (which shows 0) and other widgets that are blank. Pregnancies were registered in the previous month but no assessments have been done yet. The expected behavior would be for count widgets to display 0 and for percent widgets to display 0% (0 of 0).

![image](https://user-images.githubusercontent.com/1286381/32355820-4e93c160-bfee-11e7-940c-0fe767d4c6a1.png)

**Comment by SCdF** [comment]
This is also happening in master

**Comment by SCdF** [comment]
Review please @garethbowen . This needs to be backported to 2.14

**Comment by garethbowen** [comment]
Merged and backported. Nice one.

**Comment by sglangevin** [comment]
Working well in v2.14.0-beta.3.
