### ISSUE TITLE
Error executing changes callback

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4009]
Not too sure where this error is coming from, but I'm seeing it a lot on beta.dev logged in as a restricted user.

![image](https://user-images.githubusercontent.com/1286381/32356042-d2a9abd0-bfef-11e7-9e6d-848f208f4fbc.png)

**Comment by sglangevin** [comment]
It's also showing up when logged in as admin.

**Comment by SCdF** [comment]
Duplicate of #3985 

This is fixed in 2.14.x branch, but is not yet in a beta. Do you want me to cut one?

**Comment by SCdF** [comment]
Actually it costs me nothing, let's just tag it anyway: https://travis-ci.org/medic/medic-webapp/builds/296679144

**Comment by SCdF** [comment]
Actually it's costing me a lot: the e2e builds are surprisingly flaky on this branch…
