### ISSUE TITLE
When accessing a form from a task, hidden fields are showing

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4010]
Seen on beta.dev (2.14.0-beta.2) logged in as a restricted user on Chrome. To reproduce, register a pregnancy, then open the pregnancy visit form from that woman's profile. It should look like this:

![image](https://user-images.githubusercontent.com/1286381/32391732-6576aa76-c090-11e7-8e43-9354a256ff9e.png)

Close the form, go to the tasks tab, and select the pregnancy follow-up for the same woman. You'll see this:
![image](https://user-images.githubusercontent.com/1286381/32391762-7ca8b720-c090-11e7-8c57-5a9b0fc9381e.png)

I checked and didn't see anything obvious in the config that would cause this. Maybe a weird Enketo thing?

**Comment by sglangevin** [comment]
Wanted to confirm I am seeing the same behavior in v0.1.157 of the Android app on a Y4 (Chrome 30 testing).

**Comment by alxndrsn** [comment]
Added in https://github.com/medic/medic-webapp/commit/8ca9b0daf1?

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by sglangevin** [comment]
Working well in v2.14.0-beta.3.
