### ISSUE TITLE
Can scroll to the left on the Targets tab on Android

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4011]
Seen on Y4, Android app v0.1.157, webapp v2.14.0-beta.2. For some reason, there seems to be extra space on the Targets page. I couldn't reproduce this in Chrome.

![screenshot_2017-11-04-02-58-27](https://user-images.githubusercontent.com/1286381/32396270-b3a67bde-c0a1-11e7-99ad-93b5e96458f0.png)

**Comment by garethbowen** [comment]
This may be a bug with older chrome...

**Comment by SCdF** [comment]
This doesn't happen on the new crosswalk build, so it being Chrome version specific is likely

**Comment by SCdF** [comment]
@sglangevin I cannot replicate this on my Tecno Y4, in master, 2.14.x, 2.14.0-beta.2 or beta.dev (with the `sharon` user).

Is this reproducible, or did you just see it once?

**Comment by alxndrsn** [comment]
> cannot replicate this on my Tecno Y4, in master, 2.14.x, 2.14.0-beta.2 or beta.dev

@SCdF did you test this with crosswalk or non-crosswalk app?

**Comment by SCdF** [comment]
@alxndrsn I tested it on both

**Comment by sglangevin** [comment]
I've seen it once, but will test again to see if I can reproduce it.

**Comment by sglangevin** [comment]
I'm still seeing this on v2.14.0-beta.3 on my Tecno. I'm using the non-crosswalk app so it's Chrome 30.

**Comment by SCdF** [comment]
@sglangevin well that's frustrating. Can you give any more specific details? Which user, which server? How you got to the page? How reproducible it is?

Perhaps someone else ( @garethbowen / @alxndrsn ) can try to reproduce it, because I'm not able to.

**Comment by sglangevin** [comment]
beta.dev, username: sharon, happens every time. I just clicked on the Targets tab at the top of the page and was able to scroll.

**Comment by SCdF** [comment]
I have Experienced SmartLife Now™, on my Tecno Y4 (the worst one, with the case yeah?), using the android version tagged 0.1.159 (which is the same as yours but with some tasty product flavours), on beta.dev, with the user sharon.

And I still can't reproduce this. To prove my loyalty to this cause, I have produced an informative video!

![so-sorry-sharon](https://user-images.githubusercontent.com/583851/32837178-7426fed6-ca04-11e7-8b16-cf597231989b.gif)

Note me attempting to scroll to the left and right in targets!

**Comment by SCdF** [comment]
Can you, from that gif, work out what you're doing differently? Should I try to get an official build of the android app, instead of one I built myself?

**Comment by sglangevin** [comment]
@SCdF I appreciate both your dedication and the name of that file 😂 .

The only difference I can think of is that I'm using v0.1.157 that I installed from the Play Store and you're using a version you built yourself. It seems like it would be weird if those two were different though, right?

**Comment by SCdF** [comment]
@sglangevin can you link me to the play store version that you're using? Also, presumably if it's installed through the play store I won't actually be able to debug it, will I?

@garethbowen / @alxndrsn / @ngaruko can you folks spend a minute booting up the app on your phones, navigating to https://beta.dev.medicmobile.org, using the user "sharon" with a password I'll give you over slack if you don't know it, and seeing if one of you can reproduce?

**Comment by alxndrsn** [comment]
On `0.1.157`, I can scroll to the right, but only on the 2nd or third time I visited _Targets_.

**Comment by alxndrsn** [comment]
@sglangevin I can't recreate this on `0.4.0` on `beta.dev`, so I think it's fixed.

**Comment by SCdF** [comment]
We still need to either fix this for the old build, or decide that we're not going to

**Comment by alxndrsn** [comment]
As per https://github.com/medic/medic-webapp/issues/4012#issuecomment-345540594:
> @sglangevin Can we leave this as a known issue? It doesn't break the app, and the workaround is to update your app.

**Comment by sglangevin** [comment]
I'm fine with not fixing it. All LG users should be on a recent version of the Android app anyway.
