### ISSUE TITLE
Figure out how to reuse code between apps

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4021]
We have lots of code that would be useful to share between webapp, api, and/or sentinel and currently this isn't possible. We end up just copying the code around. Work out the best way to include the same library in multiple apps.

Here are some initial ideas...

1. Use published npm modules. We've already started one called `medic-api-utils` but it isn't yet used anywhere. This is well supported given that we already use node modules everywhere so it fits seamlessly into our build and deployment systems. One downside is with development overhead as any feature or bug fix that requires a change to the library will have to be committed, reviewed, and published before it can be incorporated into the app. This is the problem we wanted to avoid when we merged api and sentinel into webapp in the first place.
2. Commit the code into a new directory at the root of the medic-webapp repo. This could be done as unpublished node modules if it's easier to require the code. This has the benefit of all the code being changed and reviewed in a single commit. The build system would need to include these shared libraries when bundling each of the apps.

**Comment by SCdF** [comment]
I would vote for us to not publish npm modules unless we actually have situations where we don't think versioning is going to be 1:1. Otherwise it's just a hoop to jump through with no benefit.

**Comment by garethbowen** [comment]
This allows us to fix this: #3826

**Comment by garethbowen** [comment]
@SCdF I believe you're working on this?

**Comment by SCdF** [comment]
I am! This is actually covered by #4173, which is about to be merged, so I'm going to count this as a success!
