### ISSUE TITLE
Message sent with 'from' field empty not opening in the UI

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4024]
Steps to reproduce:
 1. Send message from the `api` (`http://admin:pass@localhost:5988/api/v1/records`) with with `from` field empty. The message get sent 
![image](https://user-images.githubusercontent.com/6979995/32581336-6ba78d4e-c54e-11e7-8298-36cf560ca58c.png)

2. In the UI, click on the message from the `message list` in the LHS,
3. Expected: message details on the RHS.
Current behavior:   `no message selected` on the RHS.
![image](https://user-images.githubusercontent.com/6979995/32581306-50bfa106-c54e-11e7-882a-46ae7a6e849c.png)

**Comment by SCdF** [comment]
This is an opportunity to work out if anyone uses this api :-)

**Comment by garethbowen** [comment]
This works for me.

@ngaruko Can you attempt to recreate it on the latest alpha and capture the console output because I bet there's an error there? If you manage to reproduce it on a server I can access (eg: alpha.dev) then I can have a look at it there.

**Comment by ngaruko** [comment]
Hi @garethbowen . This has been here for quite sometime. I just sent a message via api 
`Message sent with 'from' field empty not opening in the UI #4024`. Please have a look in `alpha.dev` UI.

**Comment by garethbowen** [comment]
There's not much in the console but what appears to be happening is because the conversation doesn't have a "from" there's no `key` to use so when the element is selected the URL doesn't change and nothing happens. I suspect this isn't a supported workflow - we should probably not accept this input, or at least just not show the message conversation in the UI.

It would be quite a lot of work to support having no `from` supplied so I don't think we should do it until we have a use case where this is needed.

@abbyad Is this API being used anywhere? If so, should we reject messages without a `from`? If not, should we just hide them in the UI?

**Comment by sglangevin** [comment]
Do real-life messages ever get sent on a mobile network without a `from`? If not, then we should reject them. @alxndrsn may have thoughts on this as well.

**Comment by garethbowen** [comment]
It looks like this was done [on purpose](https://github.com/medic/medic-webapp/commit/af113e3002f9f58f162e19f9f22a58dee244b565) to fix [a production issue](https://github.com/medic/medic-projects/issues/2480), so we'd better not just reject them...

So it comes down to what we should do in the UI... either show "unknown sender" or something on the LHS and rework the code to handle no known sender so it shows it on the RHS on select, or hide it altogether. Seeing as this has come up in production I think we should show it and handle clicking on it.

**Comment by sglangevin** [comment]
I'm a little confused why we are accepting an empty `from` field since I don't see any messages in that issue that have an empty `from`. Perhaps I am missing where that was highlighted. It seems like that issue was about empty `message` fields, which is something that could happen in real life and should be supported.

If we are going to support messages with empty `from` then 'Unknown sender' or 'No sender' could work. I agree, hiding them altogether doesn't seem like the ideal solution.

**Comment by garethbowen** [comment]
@SCdF @alxndrsn Do you remember why we want to allow messages with no sender?

**Comment by SCdF** [comment]
@garethbowen all I remember is the argument that we should accept everything from Gateway, because it's easier to debug issues in API than it is Gateway, because it's easier to get logs, deploy new versions etc. @alxndrsn will know more.

**Comment by alxndrsn** [comment]
> we should accept everything from Gateway, because it's easier to debug issues in API than it is Gateway, because it's easier to get logs, deploy new versions etc.

This is a fair representation of what I think.

Also SMS with an empty string for the "from" field is quite possible, albeit uncommon.

**Comment by garethbowen** [comment]
Alright, so we need to handle this gracefully in the UI. So yes, we should show "unknown sender" in the LHS, and when you select the message actually show the content. Scheduling.

**Comment by SCdF** [comment]
How do we feel about the UUID of the document showing up when there is no known contact?

![image](https://user-images.githubusercontent.com/583851/36543615-29001d36-17dc-11e8-8551-7579ced1f33c.png)

It's like an 11 character change to a view to get us that far.

The downside of this approach is that we don't know on the front-end that it's not a phone number, and so to show "Unknown number" in the right places. We could do some work to decide that actually it's a UUID and not a phone number, but that feels a bit janky maybe?

**Comment by SCdF** [comment]
(FYI I'm working on a better version of this, but it's a complicated section of code apparently… )

**Comment by SCdF** [comment]
OK, so I have it that it works normally for real messages:

![image](https://user-images.githubusercontent.com/583851/36548676-d1f7cb4e-17e8-11e8-82d1-19d61dc8e62c.png)

And allows you to send to unknown numbers:

![image](https://user-images.githubusercontent.com/583851/36548745-fdff8dda-17e8-11e8-8ea7-482599a752a8.png)

And allows you to view, but not send to, non-existent numbers:

![image](https://user-images.githubusercontent.com/583851/36548773-1090400c-17e9-11e8-86cb-ccae6963dfe4.png)

The code is not ideal, I imagine we could make it nicer.

**Comment by SCdF** [comment]
Back to you for review @garethbowen

**Comment by SCdF** [comment]
Acceptance testing:
 - We should correctly display and allow conversations with messages from known contacts, and messages from unknown phone numbers
 - We should correctly display messages that have no recorded phone number, though you cannot have a conversation (you don't know which ph to send your message to)
 - This has involved changing the URL structure. All existing links inside the app should still work, and old URLs will work as long as the message referred to in the URL is a contact

**Comment by ngaruko** [comment]
LGTM
