### ISSUE TITLE
Enketo: Date-time rendering is not ideal

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#4032]
The date and time components are not aligned on desktop view. This should ideally be horizontal or  stacked. 

![screen shot 2017-11-10 at 20 30 52](https://user-images.githubusercontent.com/83162/32671404-5af862a6-c658-11e7-8c4f-7d30e809c47d.png)

I've tested this on 2.12.x and alpha 2.15.x

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

This is how it now looks:

![datetime](https://user-images.githubusercontent.com/2064938/32928095-2afaa3ae-cbb5-11e7-8af5-36b263cd3cf3.png)

**Comment by ngaruko** [comment]
LGTM
