### ISSUE TITLE
Migration: enable-erlang-support is broken

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4033]
[This](https://github.com/medic/medic-webapp/blob/63fbaf97a11f26482b7849c02238c33dec4e1307/api/migrations/enable-erlang-support.js) migration is broken because of new couchdb [changes](https://github.com/apache/couchdb/commit/82635ef7f1b44cbdf98a8d6989cf505b828c3f55).  We get the following exception: 
```
  name: 'Error',
  error: 'forbidden',
  reason: 'Config section blacklisted for modification over HTTP API.',
  scope: 'couch',
  statusCode: 403,
  request: 
   { method: 'PUT',
     headers: 
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://XXXXXX:XXXXXX@localhost:5984/_config/native_query_servers/erlang',
```
and API fails to start.

**Comment by garethbowen** [comment]
The good news is that migration is no longer needed - there's a subsequent migration that undoes it. We can probably delete both, and turn erlang off manually on upgrade if it's still on anywhere.

**Comment by garethbowen** [comment]
@henokgetachew What version is this needed for?

**Comment by SCdF** [comment]
Affected versions (people with Erlang enabled who will need it disabled) are `2.7.3` -> `2.10.3`.

Simplest is to just delete these migrations and then remember to manually disabled Erlang for instances between those two versions when we upgrade them

**Comment by garethbowen** [comment]
Code review please @SCdF . Assign it back to me if you're happy and I'll backport it and check up on which instances need manual intervention...

**Comment by garethbowen** [comment]
According to #downtime these are the instances that will need manual erlang disabling on update:

- lg-testing.app.medicmobile.org: 2.8.5
- muso-mali.app.medicmobile.org: 2.8.3
- brac-ug.app.medicmobile.org: 2.8.6
- v2-test-ipd-nepal.app.medicmobile.org: 2.10.0-beta.8
- brac.dev.medicmobile.org: 2.9.0-beta.1

**Comment by SCdF** [comment]
LGTM

**Comment by garethbowen** [comment]
Merged and backported to `2.14.x`. I decided not to backport to `2.13.x` as 2.14.0 should be released soon. Any new instances and upgrades from 2.10 or earlier will hit this issue. To work around this issue...

1. Find the ID of the migration log. On new versions the ID is `migration-log`, but on old versions you need to use the `doc_by_type` view to find the doc with type `meta`.
2. Edit the doc so the `migrations` array has entries for "enable-erlang-support" and "disable-erlang-support". This tells API not to run these migrations. NB: If the `migrations` array already had "enable..." but not "disable..." you must manually disable erlang support in your couchdb.

**Comment by SCdF** [comment]
NB: this was also backported to 2.13

**Comment by henokgetachew** [comment]
@SCdF does that mean that @garethbowen's steps above should not be done for 2.13 right?

**Comment by SCdF** [comment]
If you're upgrading to 2.13.1, no.
