### ISSUE TITLE
No spacing between cards on person and place profile pages

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4034]
The spacing between cards on profile pages has disappeared.

![image](https://user-images.githubusercontent.com/1286381/32755011-26b192ce-c888-11e7-90b4-7ca3c2f99b0e.png)

It should look like this:

![image](https://user-images.githubusercontent.com/1286381/32755068-69702918-c888-11e7-983a-d6c353d6f514.png)

**Comment by garethbowen** [comment]
Caused by [this commit](https://github.com/medic/medic-webapp/commit/749d0a4900b2322a60a686ca3cdd5ae99cec127a)

**Comment by garethbowen** [comment]
I've reverted the change that caused this. Should be good to go.

**Comment by ngaruko** [comment]
LGTM

**Comment by sglangevin** [comment]
@ngaruko this should be tested when a new beta of 2.14.0 is released as it was a bug from 2.14.0 release testing. Testing on master isn't sufficient.

**Comment by sglangevin** [comment]
Tested on 2.14.0-beta.5 and it's working well.
