### ISSUE TITLE
New icons for People tab do not work out of the box

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4036]
After upgrading a fresh instance (contained no data) from 2.13.0 to 2.14.0-beta.3, there were no icons on the Configuration > Icons page and no icons appearing on the People tab. I didn't check, but it's possible there was no doc in the DB called `resources` yet. I then manually uploaded the SVG icons with the names `clinic`, `health_center`, `district_hospital` and `person` and the Configuration > Icons page looks like this:
![image](https://user-images.githubusercontent.com/1286381/32802064-c5c5783e-c933-11e7-8066-53444f423c6f.png)

People tab looks like this (note that only the district hospital icon is appearing for adding a district, health center and person and that it appears in grey in the list of contacts when it should be blue):
![image](https://user-images.githubusercontent.com/1286381/32802090-d7480900-c933-11e7-8325-df9aa0cd5214.png)

**Comment by garethbowen** [comment]
@sglangevin I have a few questions...

Which instance did you use?

Did all the icons you uploaded happen to have the same file name?

To get the colouring working the icons need to be carefully constructed. Can you try using the [ones in the repo](https://github.com/medic/medic-webapp/tree/master/api/resources)?

**Comment by sglangevin** [comment]
> Which instance did you use?

beta-test.app (a new instance that @henokgetachew set up for me to test this upgrade). 

> Did all the icons you uploaded happen to have the same file name?

No, I checked on that

> To get the colouring working the icons need to be carefully constructed. Can you try using the ones in the repo?

Good point, that will probably resolve part of the issue. I'll try that now and report back.

**Comment by sglangevin** [comment]
Actually, sorry, beta-test.app is now down, so I'll have to give that a test after the next upgrade test, which I'll be doing when we have the next beta.

**Comment by garethbowen** [comment]
@sglangevin I have no idea what happened to the migration and I can't get it to happen for me. It's _possible_ it's caused by #4037 but that doesn't seem right either. All the error cases I can think of would have resulted in api refusing to start up.

I also can't explain why changing one icon would change the others - that also works as expected for me.

This indicates that there's something funny going on with your `resources` doc but without access to the instance I can't work out what it is.

I suggest we wait for #4037 to be merged and then try again.

**Comment by sglangevin** [comment]
I agree! I'll have to re-try once the next beta comes out and see what happens. I'm thinking I didn't have a `resources` doc before I upgraded - would that have affected the migration?

**Comment by garethbowen** [comment]
If you didn't have a `resources` doc there's another migration that creates it. If for some reason that migration was skipped then the `add-contact-icons` migration would have failed and api wouldn't have started.

**Comment by sglangevin** [comment]
hmm...unsolved mystery I guess! I'll see if I can reproduce this next time and if not, I'll close this issue.

**Comment by sglangevin** [comment]
LGTM in 2.14.0-beta.5.
