### ISSUE TITLE
Contact summary card should left align every row

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4045]
As reported in https://github.com/medic/medic-projects/issues/3058, `contact-summary` cards can be out of alignment. We can specify how wide out of 12 each field should be shown, and it would be expected that each new row would be fully left aligned. 

When a field's labels wrap the added height for that field affects the next row's alignment, as seen here in the fourth row:
![image](https://user-images.githubusercontent.com/789512/32858579-f80d4ef2-ca19-11e7-9efb-5d00e97e350b.png)

**Comment by garethbowen** [comment]
@abbyad I can't reproduce this on alpha.dev. Some work was done here recently to use a different layout so it may be that this is fixed. Can you please try and reproduce on 2.15 alpha?

**Comment by abbyad** [comment]
I can't find any people on alpha.dev with the right summary card to show this... but see the same symptom [here](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/ecf784f2012581e37f62e18f9b546003) with immunizations: 
![image](https://user-images.githubusercontent.com/789512/33597813-9be53c00-d9b1-11e7-9926-8497d01ca021.png)

**Comment by garethbowen** [comment]
Nice easy one for review @SCdF 

The reason I couldn't reproduce it is because it only affects the cards and not the contact summary that I was testing on. The fix is to apply the same classes to both sections.
