### ISSUE TITLE
MedicOS boot on AWS broken when booting from an Image for some instances

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4051]
When this happens: Cloning a running instance (Both using script as well as imaging it and launching it)
OS has been updated.
Medic Core: After couchdb 1.7.1 update
AWS Error log:
```
Setting up software...
[H[J

An unrecoverable error has occurred.
The virtual machine cannot start properly at this time.
Details: Failed to extract required software from disk/image.

Please contact technical support and provide this error message.
```
This also breaks our AMI backups since we're using imaging.
It doesn't look like all instances are affected but some are.  We need to investigate what differentiates these.  @browndav any ideas?
There is an instance labeled with a 'Debug' prefix for investigation.

**Comment by garethbowen** [comment]
@henokgetachew This has been solved, hasn't it?

**Comment by henokgetachew** [comment]
Yup.  Closing.
