### ISSUE TITLE
Report page: restrict the size of icons that appear in "Submit report" list

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4063]
On the Report page, we should restrict the size of icons in the "Submit report" list so that they always display at 30 x 30px, regardless of actual upload size. Icon sizes are controlled throughout the rest of the app and icons in this particular location were overlooked but should be treated similarly.

In this screenshot (from alpha.dev) the icon for Public Health Events is too big - it should be restricted to a 30 x 30 bounding space.
![screen shot 2017-11-27 at 8 51 36 am](https://user-images.githubusercontent.com/26235957/33278547-bab535de-d350-11e7-80c8-b57215acff7f.png)

**Comment by sglangevin** [comment]
This is due to a large 60x60 icon being uploaded and used for this form. All other forms are using 30x30 icons, they aren't limited in size in this list or in the reports list. So either we should restrict the size everywhere or fix the icon being used for this form.

**Comment by amandacilek** [comment]
I'd restrict the size if it's easy to do.

Ideally I'd like the size of icons to be restricted throughout the _whole app_ so that we always have control over what size something displays at. That means someone can upload an image of a random size but it will always scale to fit the bounding container we've created for it. The bounding container is 30x30 in most places, and 60x60 on Profile pages and on Targets widgets.

**Comment by garethbowen** [comment]
Code review please @SCdF

**Comment by ngaruko** [comment]
LGTM

**Comment by garethbowen** [comment]
Backported to `2.14.x`
