### ISSUE TITLE
Medic-Conf commands should prompt for a password instead of accepting it as a parameter

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4074]
Commands can now be run like the following:
`medic-conf --instance admin:PASSWORD@INSTANCE.app`.
This means password is stored in plain text in command history.  The right behavior should be to prompt for a password from the user and not display it (i.e. using something like `read -s` or `stty -echo` more generally).

**Comment by alxndrsn** [comment]
This should be done without echoing the password to the console.

**Comment by alxndrsn** [comment]
Accepting password from env var or CLI is acceptable for `--local`.

**Comment by alxndrsn** [comment]
Fixed in `v1.10.1`.

**Comment by ngaruko** [comment]
LGTM. However, is it assumed that only a user called `admin` can do the configuration or do we have cases where a user named `otherwise` would have `admin` rights and be able to configure an instance? @henokgetachew @alxndrsn ?

**Comment by alxndrsn** [comment]
Just supporting `admin` is fine for now.
