### ISSUE TITLE
Cannot delete record

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4076]
In latest alpha (2.15.0-alpha.8513) cannot delete a report. It gives the following error:

```
inbox.js:3 Error submitting modal RangeError: Maximum call stack size exceeded
    at i (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
    at u (inbox.js:3)
(anonymous) @ inbox.js:3
r.setError @ inbox.js:3
(anonymous) @ inbox.js:3
u @ inbox.js:3
(anonymous) @ inbox.js:3
$digest @ inbox.js:3
$apply @ inbox.js:3
(anonymous) @ inbox.js:3
dispatch @ inbox.js:3
m.handle @ inbox.js:3
11:38:09.378 
```

Tested on alpha.dev

**Comment by alxndrsn** [comment]
<img width="446" alt="screen shot 2017-12-07 at 19 34 33" src="https://user-images.githubusercontent.com/191496/33732124-af493d02-db85-11e7-935a-eb76cc5d8511.png">

**Comment by alxndrsn** [comment]
Looks like a circular reference of `contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.contact.parent.` etc

**Comment by garethbowen** [comment]
Back to you @alxndrsn

**Comment by garethbowen** [comment]
@alxndrsn Are you still working on this or is it free for anyone to pick up?

**Comment by alxndrsn** [comment]
I'm mot working on this.

**Comment by garethbowen** [comment]
I think the correct solution is to minify the lineage before passing to bulkDocs to save.

**Comment by garethbowen** [comment]
Nicely done @dianabarsan
