### ISSUE TITLE
Contact pagination is broken for restricted-to-place users

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4085]
# Affects

* `2.11` (confirmed - https://github.com/medic/medic-projects/issues/3156)
* `master` (expected from reading code)

# Observed

For a restricted-to-place user who has more than 50 contacts in their area, one contact (the 50th) is missing from the Contacts list.

# Analysis

This appears to be because the `options.skip` value in https://github.com/medic/medic-webapp/blob/2.11.x/static/js/controllers/contacts.js#L87-L88 is derived from `liveList.count()`.  The LiveList contains the contact's place as well as the contacts directly attached to that place.  Instead, the value of `options.skip` should be a strict multiple of `options.limit`.

**Comment by alxndrsn** [comment]
I've pushed a potential fix, but it may require more care and perhaps testing.

**Comment by garethbowen** [comment]
I distinctly remember fixing this once before but I can't find the issue now...

**Comment by alxndrsn** [comment]
Can you remember how you fixed it? 😉

**Comment by garethbowen** [comment]
I distinctly remember a `-1` somewhere. It's possible this got removed at some point or there's another edge case somewhere. `-1` would work but you'd have to remember whether or not you had to manually add the home place.

The other way would be to always `-1`, eg: `{ skip: count - 1, limit: 51 }`. That way you'll usually get a duplicate row but it'll be merged into the live list based on ID so you won't get duplicated list items. It's slightly worse performance, but cleaner code.

**Comment by sglangevin** [comment]
@garethbowen @alxndrsn what ended up happening with this issue? Sounds like it might be causing issues finding families in Siaya (I'm guessing other projects too) which means CHWs are creating duplicate families. Can we get this one finished off and released?

**Comment by garethbowen** [comment]
Yeah. We can either use the hacky solution above or work out how to do it properly.

**Comment by SCdF** [comment]
My vote would be for Gareth's suggestion since it's easier to read, though I think either of them needs a comment to explain why it's not just limit. @garethbowen is there some kind of grander solution to this that you were considering implementing? Or did you just not instantly want to merge Alex's existing branch?

**Comment by garethbowen** [comment]
The existing branch had a bug (commented on the PR). I think the suggestion above is fine. The grander solution would be to use `startkey` instead of `skip` which would handle all sorts of edge cases gracefully  but I think would require significant changes to the Search service.
