### ISSUE TITLE
User's role changes are only reflected if they log out and in again

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4088]
To reproduce:
 - Log in as a restricted user on one device. Let's say they are a national manager
 - Log in as admin elsewhere
 - Use admin to change this user from national manager to regional manager

Note that the restricted user doesn't get any kind of notification. They keep their current permissions.

If you then reload the restricted user note they **still** keep the current permissions.

Log out the restricted user and log them back in again.

Note that note they have the correct permissions for a regional manager.

**Comment by ngaruko** [comment]
Tested in 3.0 (local)...
Observation:
When the user role changes from `National Manager` to `Regional Manager`, the user is logged out of the app and upon logging in, the role change is applied.
When changing from `Regional` to `National`, the user is still logged in (showing `regional manager's` features with console errors when navigating to `analytics/targets`) until a refresh.
```Error fetching user contact 
Error: UserCtx not found
Stack trace:
require<[428]</</</<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:200892:28
require<[427]</</<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:200806:14
require<[431]</</</<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:201130:11
processQueue@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:41766:37
scheduleProcessQueue/<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:41814:27
$digest@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:42949:15
$evalAsync/<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:43178:15
completeOutstandingRequest@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:31025:7
Browser/self.defer/timeoutId<@http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:31304:7
inbox.js:39397:16```

Another glitch here is that, when moving from national to regional manager, the `associated contact is no longer required on the form...
![image](https://user-images.githubusercontent.com/6979995/39460851-d564fc8c-4d5a-11e8-9b45-d3e6d63aa6d3.png)

**Comment by dianabarsan** [comment]
When the role is changed, the user shouldn't be getting logged out, they should be getting the same popup that informs of configuration updates. The app needs a refresh so the new user roles come to effect. 

About `UserCtx not found`, could you please tell me what your previous actions were? It seems like something is deleting your userCtx cookie.

**Comment by ngaruko** [comment]
The app works as expected on `alpha.dev`. The above behavior (logging out user on role change) is observed on my local instance. It might have do to with my environment/browser. I am closing this and raise a different issue if I (or someone) come  across this in a reproducible way.
