### ISSUE TITLE
Pull `POST /api/v1/users/{username}` authentication logic out of server.js

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4092]
Ideally server.js would just be app bootup and routing. We haven't been doing this completely in the past but we should move to it to keep the routing simple.

Traditionally code in `server.js` is where all code that needs to directly muck with `req` and `res` lives, including dealing with specific errors (using `serverUtils`). That code would call through to code in the `/controllers` directory, which uses either callbacks or promises to do logic and return results that don't directly care that they need to be written to HTTP.

The `POST /api/v1/users/{username}` endpoint now has quite a bit of logic in it, because there are multiple ways you are allowed to modify a user. We should move this somewhere else. Probably the best thing long term is to split the current controller into a service and a controller, and have the service doing the logic and the controller managing the relationship between the routing and the service (so the service doesn't care about HTTP primitives but the controller does).

**Comment by garethbowen** [comment]
AT: Ensure that the user creating and updating APIs and UIs still work as expected.

**Comment by ngaruko** [comment]
LGTM. Tested on `gamma.dev` 3.2.0
