### ISSUE TITLE
Show a useful error message when an offline user tries to change their password

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4095]
When a user tries the change their password we make a request to the remote server. This is one of the few cases where a connection is required. Give the user a helpful error message when we cannot connect to the server when changing passwords. Check for other online only features and ensure they're handled too.

**Comment by vimemo** [comment]
**Implemented in branch (4095-....):**
- Check online status before allowing the user to update password and display an informative message when user is offline.

**To be done:**
- Understand what kind of automated testing is needed for this.
- Should we also check for 404s after the user attempts to update the password? (possible scenario when the user is online before opening the update-password dialog but offline after submitting the form)
- What other features/actions require online connection?
- Do we just fill out english translations for the title/message and other languages will be added/updated by somebody else later?

**Comment by vimemo** [comment]
hi @garethbowen, please review again. Have confirmed the -1 status code and updated the code to just check for that. thanks.

**Comment by garethbowen** [comment]
@vimemo I can't see the new code anywhere. Did you commit it to the same branch?

**Comment by vimemo** [comment]
@garethbowen, I think I forgot to push. The code is in now. Thank you.
