### ISSUE TITLE
Work out if you're allowed to pass `roles` to `/api/v1/users`

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4096]
The code makes it look like you can pass roles specifically instead of type, sort of, but the existing docs don't mention it. Align docs and code, one way or another.

**Comment by garethbowen** [comment]
I fixed the documentation in #4525 - you can pass roles or a type but type is deprecated.

**Comment by ngaruko** [comment]
Closing this as it will be tested in #4525 ...
