### ISSUE TITLE
Log each valid `POST /api/v1/users/{username}` with field names

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4097]
Log who changed which user, and what fields they changed, but not the actual changes (ie don't log the password, just that it was changed).

**Comment by garethbowen** [comment]
Merged! Thanks for the contribution @kennsippell

**Comment by garethbowen** [comment]
For AT:

Ensure the API log records when someone successfully updates a user, eg:

> REQ 3ea280b0-d469-403a-9273-13edb0b8f758 - Update user 'kenn'. Setting field(s) 'fullname,known,foo'. Requested by 'admin'.

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev` v3.3 by updating a user and looking at the logs on the server
![image](https://user-images.githubusercontent.com/6979995/49187513-48ff3c80-f39a-11e8-9a0b-194b9c4acfde.png)
