### ISSUE TITLE
Filtered replication for messages

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4100]
Placeholder for https://github.com/medic/medic-projects/issues/3243

**Comment by garethbowen** [comment]
> Filtered replication for messages

Messages are filtered through replication. It sounds like they have configured the option to show these users unassigned messages. This is so they can follow up on valid messages that come in with an unknown phone number for some reason.

**Comment by henokgetachew** [comment]
I wasn't actually aware that this was configurable.  If that's the case (i.e. we can turn off replicating unassigned messages to some users) then, that actually solves this issue because that would make it something admins can change.

**Comment by garethbowen** [comment]
@henokgetachew Can we close this?

**Comment by henokgetachew** [comment]
Yup.  Closed.
