### ISSUE TITLE
Check for required npm version

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4102]
It would be helpful for new developers joining the project if a meaningful error message were given if the version of npm is too old for compatibility.  I guess it would be appropriate to check when running grunt.

**Comment by SCdF** [comment]
We have the first one, for both dev and prod:
 - https://github.com/medic/medic-webapp/blob/master/api/server.js#L776
 - https://github.com/medic/medic-webapp/blob/master/sentinel/server.js#L15

**Comment by alxndrsn** [comment]
Thanks, I'll update the ticket.

**Comment by garethbowen** [comment]
This was done as part of moving to yarn (#3032). Yarn will scream at you if you're not using the [version specified in our package.json](https://github.com/medic/medic-webapp/blob/master/package.json#L12) and the [README specifies the required version](https://github.com/medic/medic-webapp/blob/master/README.md#dependencies).

Closing. Please reopen if there's more to do.
