### ISSUE TITLE
Edits to leading/trailing whitespace in a XForm field does not get saved

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4103]
As noticed when fixing https://github.com/medic/medic-projects/issues/3244, edits to a XForm field do not stick if only leading (and/or trailing) whitespace is edited.

Some examples, with `_` representing a single space character:
1) Original doc: `My name`
1) Edit in XForm: `_My name_`
1) Resulting doc: `My name`

Also:
1) Original doc: `_My name_`
1) Edit in XForm: `My name`
1) Resulting doc: `_My name_`

In all cases a new rev of the doc is saved, but the change doesn't stick. Changing other fields does not impact this test. Tested on `2.13.0-beta.22`

**Comment by rmhowe** [comment]
@abbyad I can reproduce the first example, however I can't seem to create a person with leading whitespace in their name or phone number in order to test the second example. Is it possible when creating a new person through the webapp? Also just wondering what the usecase is for this and if we shouldn't always be trimming leading/trailing whitespace for all fields anyway?

**Comment by abbyad** [comment]
I just tested and could create a person with whitespace in standard.app which is running 2.13.0-beta.22. What version are you testing on? Did you look at the raw doc to see what the field looks like?

As for always trimming leading/trailing whitespace, that seems like a good idea. I can't think of a scenario where I wouldn't want to do that. Perhaps @derickl or @sglangevin can think of a scenario. Otherwise that may be the best approach.

**Comment by sglangevin** [comment]
I think it's safe to remove whitespace.

**Comment by rmhowe** [comment]
So after some more testing...

**2.13.5** 
- A person can be created with leading/trailing whitespace in their name/phone number
- Editing leading/trailing whitespace in their name/phone number does not save if it is the only change performed (as mentioned in the initial issue description)

**2.14.0 and above**
- A person can NOT be created with leading/trailing whitespace in their name/phone number (it is automatically stripped out)
- Editing a person (even just submitting the edit form with no changes) automatically strips out any leading/trailing whitespace in their name/phone number (including if that person was created with leading/trailing whitespace eg in 2.13.x)

I'm not entirely sure what's changed between the two versions, but it appears to no longer be an issue. Do we need to add a fix for people on 2.13.x or can it be worked around until people are upgraded to 2.14.x?

**Comment by abbyad** [comment]
Good spotting. I would think this is not worth fixing in 2.13.

**Comment by rmhowe** [comment]
So shall I mark this (and [#4104](https://github.com/medic/medic-webapp/issues/4104)?) as won't fix?

**Comment by abbyad** [comment]
That's a good idea.
