### ISSUE TITLE
Medic's XForm `tel` type accepts whitespace

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4104]
As seen in https://github.com/medic/medic-projects/issues/3244, if a `tel` field has a leading whitespace, the messages will not be sent.

Some options, in order of _my_ preference:
a) Always remove spaces in `tel` fields. _I can't think of a case where leading/trailing spaces in a phone number are useful, so this is my preferred option._
b) Have a built in validation error so that it is more apparent to the user if invalid characters are included. _This is already the case if it doesn't match a known phone number. Whitespace separating numbers **is** allowed, as is leading/trailing ones ...for now. This could be done with (a) as a precaution._
c) Add a validation in the form itself. _This would be a pain to maintain in every single form_

Note that removing the leading whitespace in an existing field cannot be done as a single form edit (as reported in https://github.com/medic/medic-webapp/issues/4103). You could edit it via db, or edit via the XForm twice: first time to remove whitespace and make another edit, save, then second edit to restore the original number.

**Comment by rmhowe** [comment]
Not an issue in v2.14.0 and above (as discussed in [#4103](https://github.com/medic/medic-webapp/issues/4103))
