### ISSUE TITLE
Denial of Service caused by medic gateway status history

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4109]
A stub for medic-project issue: https://github.com/medic/medic-projects/issues/3291

**Comment by garethbowen** [comment]
Merged.

**Comment by sglangevin** [comment]
since this was a critical production issue, should we consider backporting to 2.14.0?

**Comment by garethbowen** [comment]
We can do, although it sounds like @alxndrsn isn't 100% confident in this approach. I'm tempted to leave 2.14.0 as is to get it out the door - 2.15.0 probably won't be too far behind it...

**Comment by alxndrsn** [comment]
I'm confident that the approach works, so it's probably worth backporting.  I just think it's only _part_ of the solution, and hope that it gives us sufficient logging and monitoring notification that we know when it happens again in future and investigate :¬)

**Comment by ngaruko** [comment]
Have we backported this to 2.14.0 @garethbowen ...  @alxndrsn ?

**Comment by alxndrsn** [comment]
AFAIK we aren't backporting fixes to 2.14 any more.  I don't know if this particular issue made it in before that happened.

**Comment by abbyad** [comment]
Assigning to @henokgetachew for AT

**Comment by henokgetachew** [comment]
I'm not sure how to AT this one.  Perhaps running medic gateway on a very slow wifi could make sense.  @rosteve was the one who encountered this first.  @rosteve do you think we can try upgrading the instance that was experiencing this?

**Comment by ngaruko** [comment]
Since it is hard to reproduce / AT this in non-production environment and we haven't heard it reported in production yet, I will close this and keep an eye out in the field. Aye @henokgetachew @rosteve ?
