### ISSUE TITLE
Understand pouch checkpointing better

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4120]
I just replicated 20,000 docs to a local database.  Now pouch is spending more time than the replication took to write hundreds of checkpoints.

Investigate:

1. does it checkpoint as it goes along?  if not, why not
2. why not just write a single final checkpoint?

**Comment by alxndrsn** [comment]
Seen on PouchDB `6.1.2`.

**Comment by alxndrsn** [comment]
Fix https://github.com/medic/medic-webapp/issues/4155 before investigating further.

**Comment by alxndrsn** [comment]
Confirmed that pouch completes the batch reads, and then writes all checkpoints _afterwards_.

**Comment by alxndrsn** [comment]
Pathological checkpointing doesn't appear to happen with unfiltered changes feed direct from couchdb.  This suggests that either the bahviour is caused by the filtering-by-doc-ids, _or_ by `medic-api` returning many many more documents than pouch expects.

**Comment by alxndrsn** [comment]
In Chrome private browsing, with a fully-synched db, loads of checkpointing will be done after loading too.

**Comment by alxndrsn** [comment]
Seems to behave fine in ATP with PouchDB 6.1.2 and 6.3.4 with the following code (non-private browsing):
```
user = ?;
localDbName = ?; // re-use this to prevent re-replication every iteration
server = 'localhost';

db = new PouchDB(localDbName);

replicationPromise = db.replicate.from(`http://${user}:pass@${server}:5988/medic`, {
    doc_ids: [`org.couchdb.user:${user}`],
    timeout: 1000*60*10,
  })
  .then(() => console.log('db replication complete.'));
```

**Comment by alxndrsn** [comment]
This looks like a direct result of https://github.com/medic/medic-webapp/issues/4178 - the local database created in `bootstrapper.js` has a different `id()` than that created in `services/db.js`, and therefore uses a different checkpoint name on the server.

**Comment by alxndrsn** [comment]
Investigation complete.  I'd say that PouchDB should be handling remote checkpointing better - rather than writing 200 times in increments of 10, it should write a single checkpoint with the full progress included.  Report bug upstream before closing this ticket.

**Comment by alxndrsn** [comment]
It looks like checkpointing done in `bootstrapper.js` (from the initial sync) is stored to a different location than that in `services/db-sync.js`.  This may be because there are two different implementations of pouchdb-generate-replication-id loaded in our bundle:

<img width="517" alt="screen shot 2018-02-16 at 19 34 06" src="https://user-images.githubusercontent.com/191496/36323240-8413a336-1350-11e8-93a5-451577ef739b.png">

It's possible this is only a problem in dev; checking.

**Comment by garethbowen** [comment]
@alxndrsn The patch removes `doc_ids` from the parameters used to generate a checkpoint. Without that every time the `doc_ids` changes it starts from the beginning. This would go away when we find a way to do doc deletion [without sending all known docs as part of replication](#4172).

Possibly related: #4176 #4158

**Comment by alxndrsn** [comment]
Original has only been called since webworker was removed (721d9111e).

Fixes will need backporting.

**Comment by garethbowen** [comment]
I've merged and backported that PR. @alxndrsn Is there anything more to do on this issue?

**Comment by alxndrsn** [comment]
Yes, work to understand the current sequence of checkpointing is underway.

**Comment by alxndrsn** [comment]
After initial REMOTE->LOCAL replication, two-way sync starts.

When LOCAL->REMOTE replication starts, all docs that have _just been read_ from the remote db will then be sent _back_ to the remote DB in `_revs_diff` calls.  If there is a way we could avoid that, it would be nice.

**Comment by alxndrsn** [comment]
I think this is sufficiently understood for the time being.
