### ISSUE TITLE
Revert to "official" google-libphonenumber dependency

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4123]
To fix https://github.com/medic/medic-projects/issues/3287#issuecomment-359740107, we released our own build of `google-libphonenumber`.  When `3.0.11` is released at https://www.npmjs.com/package/google-libphonenumber, then we should revert to using it.

Blocked by ruimarinho/google-libphonenumber#144

**Comment by garethbowen** [comment]
Reopened for AT. Make sure this issue is still fixed: https://github.com/medic/medic-projects/issues/3287
