### ISSUE TITLE
Presence of an undefined element in contact-summary result object crashes all form loading

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#4125]
Tested on 2.13.X

With the following simple contact-summary definition, all app form loading fails .

```
var cards = [];
var context = {};
var fields = [];

context.lineage = [undefined];
//context.lineage = [{}, undefined];
//context.blah = [undefined];
//cards = [undefined];
//fields = [undefined];

return {
  fields: fields,
  cards: cards,
  context: context
};
```

All the commented variation in the snippet above trigger the described behaviour.

<img width="745" alt="screen shot 2018-01-23 at 21 32 27" src="https://user-images.githubusercontent.com/83162/35293514-fe6ca1de-0084-11e8-8487-723d3f8cfc73.png">
<img width="540" alt="screen shot 2018-01-23 at 21 32 36" src="https://user-images.githubusercontent.com/83162/35293515-fecc2460-0084-11e8-893e-fea6ea88100d.png">
 

cc @alxndrsn @SCdF @sglangevin

**Comment by dianabarsan** [comment]
Hi @derickl! 
What would be preferred: a meaningful human-readable error displayed instead or just fallbacks for these types of values?

**Comment by derickl** [comment]
Fallbacks would be appropriate as (I would presume), no extra checks would have to be made at the form level. @dianabarsan

**Comment by ngaruko** [comment]
Are you able to test this fix on `alpha.dev` @derickl ?
