### ISSUE TITLE
Place form(s) that worked in 2.11.X-2.12.X does not work in 2.13.X

### ISSUE THREAD

**Issue by derickl** [medic/medic-webapp#4126]
As an example, the LG place forms have a `contact` section to collect information on the place's contact. This section renders correctly in 2.11 and 2.12 but is completely ignored/empty in 2.13. Changing the section name to e.g. `contact_tt` reveals said section.

Is this expected behaviour? Is `contact` as a group name reserved/filtered in 2.13?

The behaviour is currently exhibited by `district_hospital` and `health_center` forms (for now) as should. The end result is we create places without a name and contact. Editing the place fixes the name issue. The contact has to be created and associated in a subsequent step.

cc @sglangevin @alxndrsn @abbyad

**Comment by derickl** [comment]
<img width="1408" alt="screen shot 2018-01-23 at 23 19 03" src="https://user-images.githubusercontent.com/83162/35298646-e57b040e-0093-11e8-8cd5-f7fea17405ee.png">

In < 2.13

<img width="803" alt="screen shot 2018-01-23 at 23 22 59" src="https://user-images.githubusercontent.com/83162/35298835-6e4ea7ae-0094-11e8-8989-adb6bf2a4356.png">


In 2.13.x
<img width="594" alt="screen shot 2018-01-23 at 23 21 47" src="https://user-images.githubusercontent.com/83162/35298772-405e4f84-0094-11e8-88ad-200dfec0ca85.png">

**Comment by derickl** [comment]
Seems medic-conf changed how it handles place forms to align with what is present in standard. I have an interim fix that works for all place types.

**Comment by alxndrsn** [comment]
What's the fix?

**Comment by derickl** [comment]
Including an non-empty init group should resolve this. medic-con expects it to exist:

https://github.com/medic/medic-conf/blob/43800a2fd4a4f13c1943e55129846c6b1c4508d5/src/fn/convert-contact-forms.js#L74

**Comment by alxndrsn** [comment]
If you've got a simple example form XLS and expected XML that doesn't currently work, then I can look at getting this fixed.  This stuff's a bit fiddly though, so probably hard to reliably fix without clear examples.

**Comment by derickl** [comment]
[XLS Form Sample.zip](https://github.com/medic/medic-webapp/files/1668946/XLS.Form.Sample.zip)

Without a non-empty init group, the contact group is not output in the final xml.

**Comment by alxndrsn** [comment]
Fixed in `1.11.1`.

**Comment by ngaruko** [comment]
Are you able to test this fix on `alpha.dev` @derickl ?

**Comment by derickl** [comment]
Works as expected.
