### ISSUE TITLE
Provide a configurable way to override libphonenumber validation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4127]
The libphonenumber validation function we use is very strict and is usually good but gets out of date if a new prefix is added for a carrier. When this happens we're forced to release a new version of the app with a later libphonenumber so the users can get back to work ([example production issue](https://github.com/medic/medic-projects/issues/3287)).

Consider whether we should use less strict validation, or provide a way to configure a list of regexes to be checked before invoking libphonenumber.

**Comment by alxndrsn** [comment]
Ultimately it's all just a big bundle of regexes anyway:

* https://github.com/ruimarinho/google-libphonenumber/commit/42d134393ec32ef1829d334b98c76fbbf2129661
* https://github.com/ruimarinho/google-libphonenumber/commit/19321bc67d34951d24122fe9fcdf0c5ceec7e95b
* https://github.com/ruimarinho/google-libphonenumber/commit/456b92e71bc359577581e8c739f3700a7602b083
* https://github.com/ruimarinho/google-libphonenumber/commit/f0582a97f5ab89ca98b20c33f5775beae90dc6d9
* https://github.com/ruimarinho/google-libphonenumber/commit/d65b12106100432f3141bbbecbd617e513606312

One approach would be to load `metadata.js` from config.  We would probably only need the regex for a specific country for most projects.

**Comment by SCdF** [comment]
It would be interesting to know the current value it provides. For example, what would happen if we just stopped validating phone numbers completely?

**Comment by garethbowen** [comment]
IIRC libphonenumber also provides a function which checks more fundamental aspects (length, chars, etc) rather than checking for specific carriers so that would be more future proof too.

**Comment by garethbowen** [comment]
When implementing this consider providing a configuration option to switch between full validation (`isValidNumber`) (default), partial validation (`isPossibleNumber`), and no validation. Documentation for the phone number library is here: https://github.com/googlei18n/libphonenumber#highlights-of-functionality

This would mean if a project is blocked by phone number validation they could reduce to partial validation until a new release with the updated libphonenumber is available.

**Comment by garethbowen** [comment]
@vimemo Nice one. Could you also please add documentation to the medic-docs repo about how to configure it and what the three options mean?

**Comment by vimemo** [comment]
Here is the documentation (phone_validation) to test this ticket:
[settings](https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md)

**Comment by newtewt** [comment]
This seems to be working as expected when using the messages tab to send messages directly to numbers or entering a phone number through the enketo forms. However, when in the admin console I don't see it respecting the config of none or partial on the Gateway Phone Number field. 

@vimemo I'm not so sure that the admin console is an issue but wanted to call it out.

**Comment by vimemo** [comment]
I think this should be ok. @garethbowen, do we want to validate phone numbers from the admin console?

**Comment by garethbowen** [comment]
No I think we don't want to validate numbers in the admin console - it's used for testing, and sometimes you want to test invalid numbers!

**Comment by ngaruko** [comment]
LGTM
