### ISSUE TITLE
Calculate fields associated to prepopulated select2 work differently in 2.14

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4134]
This issue is specific to the symptoms described in https://github.com/medic/medic-webapp/issues/4111#issuecomment-360304644.

Values of fields associated to a select2, like the name of a person, are cleared upon page turn -- but only if the select2 value was _prepopulated_ and the field has a `calculate`. This unfortunately is heavily used in contact and app forms when we want to create a field in the model but not have XML `input` fields. To do this we use a `calculate` field in XLSForm with `.` as the calculation (eg see all Standard forms).

We could either resolve this by making sure that these calculates aren't cleared during page turns, or by removing `calculate="."` from all forms. Although the latter is simple and works for new projects and Standard, existing mobile app users would absolutely need to get the new forms when upgrading to 2.14. Can we be sure that they do?

Here is a sample form showing this problem: [issue_4134.zip](https://github.com/medic/medic-webapp/files/1669564/issue_4134.zip). The XLS was used to generate the XML, and then `calculate="."` was removed from one field.

**Comment by alxndrsn** [comment]
> We could either resolve this by making sure that these calculates aren't cleared during page turns

Enketo calls `Form.calc.update()` on the `dataupdate` event for a field.  This will attempt to identify related fields to a particular data node, and recalculate their values.

Re-calculation on page-turn was introduced as a fix for https://github.com/medic/medic-webapp/issues/3281 / https://github.com/medic/medic-webapp/issues/3870.  I suspect our options for closing this issue are:

1. stop using jr:choice-name() in the ways that introduce https://github.com/medic/medic-webapp/issues/3281 / https://github.com/medic/medic-webapp/issues/3870
2. stop using `calculate` for values which should not be re-calculated
3. fine-tune calculation-on-page-turn calls to make them more specific

It _seems_ wrong to rely on `calculate` never being called after form load for a specific field, in which case option **`2`** would be the logical choice.

**Comment by abbyad** [comment]
Even if calculate is called several times I would have expected `calculate="."` to not change the value. That said, I also think option **`2`** is the most logical. In order to go with that option we need to:
1) remove  ` calculate="."` from all forms
1) upload all forms prior to any upgrade from 2.13 (or lower) to 2.14+
1) make sure that anyone upgrading to 2.14+ would not still have the old forms. _Is there any way to verify this remotely?_
1) make it easy to have XLSForm fields that have no calculate nor UI elements. Could be a new type (eg `data`), and/or make existing forms backwards compatible by removing ` calculate="."` via medic-conf.

**Comment by alxndrsn** [comment]
How about remove/avoid `no-calculate()` in `medic-conf`?

**Comment by abbyad** [comment]
Now that we've figure out how to use the `hidden` XLSForm question type as discussed in https://github.com/medic/medic-conf/issues/56#issuecomment-362292201, item *`4`* is resolved. The other items need to be documented as part of the release notes for 2.14. cc @sglangevin

**Comment by abbyad** [comment]
Assigned to @sglangevin to document in changes log, then close(!)

**Comment by sglangevin** [comment]
This has been added to the 2.14.0 release notes which will be shared with the release. Closing.

**Comment by abbyad** [comment]
> Values of fields associated to a select2, like the name of a person, are cleared upon page turn -- but only if the select2 value was prepopulated and the field has a calculate.

From a contact profile a hydrated contact doc is sent to the form, so the fields associated to a db-object have values regardless of the db-object. This may help to figure out what is going on.
