### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4140]
Shadow of https://github.com/medic/medic-projects/issues/3313

**Comment by SCdF** [comment]
@alxndrsn let's get this reviewed and merged. I'm also going to backport to 2.14

**Comment by SCdF** [comment]
Merged and backported into 2.14.x

**Comment by ngaruko** [comment]
I made some comments to the [medic/medic-projects#3313 ](https://github.com/medic/medic-projects/issues/3313) . Please have  a look and see if anything needs further attention @SCdF
