### ISSUE TITLE
Split the admin tab out as a new app

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4145]
Currently non-admin users have to download and run the admin only code. This is a waste of bandwidth, memory, and disk space. Split it out as a separate webapp.

It's currently a desktop-only, online-only, single page, and angularjs part of the app and that's fine for the new app too.

The app version must be kept in sync with webapp so it should either be installed as a ddoc bundled with medic-webapp (prior art is the medic-client ddoc), or it could be a node_module bundled with medic-webapp (prior art is sentinel and api).

Provide a link from the admin app to the main webapp so it's easy for admins to navigate between.

Ideally the admin navigation UI would be updated to be simpler now that it's not constrained by being consistent with the webapp but this can be done as a separate issue. The page content UI will remain largely the same.

If it looks like we won't get much of a saving or the code duplicate is going to be too high we should abort and revert back to having both in one place.

**Comment by alxndrsn** [comment]
Another view that may be removed is `medic-client/feedback`.

**Comment by garethbowen** [comment]
Code review please @alxndrsn
