### ISSUE TITLE
Disable server side checkpointing

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4146]
1. Update to the latest PouchDB. 
2. [Understand pouchdb checkpointing](https://github.com/medic/medic-webapp/issues/4120).
3. Assuming it's safe to disable server side checkpointing, [uncomment this line of code](https://github.com/medic/medic-webapp/blob/master/static/js/services/db-sync.js#L56).

This needs to be tested thoroughly to make sure we're not downloading the entire changes feed every time.

**Comment by alxndrsn** [comment]
Are we clear about the implications this may have when moving projects from Couch 1 to Couch 2?

**Comment by alxndrsn** [comment]
Possibly relevant: http://docs.couchdb.org/en/master/replication/protocol.html#find-common-ancestry

**Comment by alxndrsn** [comment]
Disabling remote checkpoints is not entirely safe.  There's a great discussion at https://github.com/pouchdb/pouchdb/issues/6308, but in short remote checkpoints will protect us from losing client-generated docs in the case of a server-side database rollback.

I propose we close this, but consider suggesting a deferred checkpoint writer.  This would also help to solve the many-deferred-checkpoints bug we have seen previously (https://github.com/medic/medic-webapp/issues/4120#issuecomment-362551859).

**Comment by garethbowen** [comment]
@alxndrsn As a compromise we could turn on remote checkpointing when replicating _to_ the server, and remove them when replicating _from_ the server. Does that make sense?

**Comment by alxndrsn** [comment]
Not really - seems to have the same problem to me.  In a rollback situation without checkpoints, you can lose some local changes, or some remote changes, or both.

**Comment by garethbowen** [comment]
I'll close this issue and leave it up to you @alxndrsn whether we raise performance improvements with PouchDB. Thanks!
