### ISSUE TITLE
Bad date/time setting notification when date is set correctly

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4149]
Getting the bad date/time setting warning from the server even though my device's time is set correctly. Seen on cic-guatemalav2.app.

![image](https://user-images.githubusercontent.com/1286381/34944874-485ce84a-fa12-11e7-8a2d-6c5e2030a313.png)

**Comment by henokgetachew** [comment]
The date is correct.  I'll leave this open to investigate what the cause was

**Comment by henokgetachew** [comment]
There is no obvious reason for why the date/time config changed.  I'm going to work on a monitoring code for it so we find out when it happens from now on.  I have created [this](https://github.com/medic/medic-webapp/issues/4159) issue to track it.
