### ISSUE TITLE
Unhelpful error message displays when trying to log in while offline

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4150]
![image](https://user-images.githubusercontent.com/1286381/34944804-17228cbc-fa12-11e7-878f-ac9f9406b734.png)

**Comment by garethbowen** [comment]
This is the same sort of issue as #4095 and probably the same fix will work. @vimemo Do you feel like fixing this one too?

**Comment by ngaruko** [comment]
LGTM-
