### ISSUE TITLE
Upgrade instance error - Horticulture

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4156]
This is probably caused by my environment but maybe we can still hand this more gracefully. Horti fails to upgrade, comes with an `Error triggering update` message on top of the page and following errors in the web console :
![image](https://user-images.githubusercontent.com/6979995/35705182-97271f48-0806-11e8-9b12-170bb76b0d73.png)

 and this in horti console:
```upgrade() Upgrading to {"namespace":"medic","application":"medic","version":"shared-lib-spike"}…
upgrade() Fetching newDdoc…
upgrade() Fetched newDdoc.
upgrade() Fetching oldDdoc…
upgrade() Fetched oldDdoc.
upgrade() Staging new ddoc as _design/medic:staged
Server error:
 { error: 'conflict',
  reason: 'Document update conflict.',
  name: 'conflict',
  status: 409,
  message: 'Document update conflict.',
  docId: '_design/medic:staged' }```

Tested on local install Version `2.14.0-beta.7`

**Comment by SCdF** [comment]
Yeah, we should just stomp over existing staged ddocs. When we do the view warming and other deployment stages we'll want to manage state somehow, and with that we can check if there is an existing staging going on and cleanly cancel it etc.

**Comment by sglangevin** [comment]
Closing in favor of #3806
