### ISSUE TITLE
initial replication includes needless doc_ids

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4158]
At https://github.com/medic/medic-webapp/blob/master/static/js/bootstrapper.js#L50 we specify the user's doc when doing initial replication.

This is also injected on the api side: https://github.com/medic/medic-webapp/blob/master/api/handlers/changes.js#L125, so should not be necessary for the client to provide.

This would also clarify use of the `doc_ids` filter param when accessing the changes feed (ref https://github.com/medic/medic-webapp/issues/4155).

**Comment by alxndrsn** [comment]
@garethbowen can you confirm whether this report is correct?  If so I think it's a minor cleanup and shouldn't have operational impact, but should clarify use of our apis.

**Comment by garethbowen** [comment]
Yes I think that's right for the initial replication. We also specify [doc_ids in the background sync](https://github.com/medic/medic-webapp/blob/master/static/js/services/db-sync.js#L57) so there could still be some confusion there but your proposed change would remove one source at least...

**Comment by alxndrsn** [comment]
This would be fixed if #4172 were resolved

**Comment by garethbowen** [comment]
Fixed in #4172
