### ISSUE TITLE
2.12.0 sending since=0 on first replication?

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4176]
As reported by @garethbowen

**Comment by alxndrsn** [comment]
Looks like it's happening in `master` too.

**Comment by alxndrsn** [comment]
This _may_ be a direct result of https://github.com/medic/medic-webapp/issues/4178.

**Comment by alxndrsn** [comment]
May alternatively be because each login session has a different checkpoint id...

**Comment by garethbowen** [comment]
> May alternatively be because each login session has a different checkpoint id...

That would do it. I wonder if PouchDB made a change to take cookies into account when looking up the checkpoint ID. NB: we also have [a patch](https://github.com/medic/medic-webapp/blob/master/static/js/modules/pouchdb-generate-replication-id-patched.js) which messes with the way PouchDB generates checkpoint IDs so they don't change every request.

**Comment by alxndrsn** [comment]
Looks like `{username}-meta` db replication also starts at zero too cc @SCdF

**Comment by SCdF** [comment]
I think at least for me, this is only happening on the meta db (tested on user `sharon` on `beta.dev`)

**Comment by garethbowen** [comment]
@alxndrsn I think this is fixed by #4212 ?

**Comment by alxndrsn** [comment]
I don't think this is occurring on `master`.
