### ISSUE TITLE
c.contact is sometimes null/undefined when passed to nools rules

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4177]
Confirm if either:
1. `c.contact` will sometimes be null, and should be protected for in `rules.nools.js`, or
2. `c.contact` should never be null, and there is a bug elsewhere

cc @binokaryg

**Comment by binokaryg** [comment]
`c.contact` is showing null in my Chrome browser only. It is showing contact information in my Firefox and @ashish's Chrome. So there might be some problem with my browser.

**Comment by alxndrsn** [comment]
@binokaryg please supply Chrome versions for both yourself and @ashish-medic

**Comment by ashish-medic** [comment]
Chrome : Version 63.0.3239.108 (Official Build) (64-bit)
OS: Ubuntu 16.04 TLS

cc @binokaryg

**Comment by binokaryg** [comment]
Chrome: Version 64.0.3282.140 (Official Build) (64-bit)
OS: Windows 10

**Comment by alxndrsn** [comment]
I'm also on Chrome 63, so perhaps it's a future bug we'll all be enjoying soon!

**Comment by binokaryg** [comment]
Tried on another laptop after updating Chrome to 64.0.3282.140. `c.contact` is intact there.

**Comment by binokaryg** [comment]
And after clearing up all browsing data since last 24 hrs from Chrome, it is working on my work laptop too. I think my cache was messed up although I had tried doing cache refresh too. I guess the issues can be closed. Sorry for the false alarm.

**Comment by alxndrsn** [comment]
👍 thanks for keeping us informed, @binokaryg.

I'd still like to know the answer to my initial question though, so I'll keep the issue open 🙂

**Comment by garethbowen** [comment]
It's valid to have a null contact, for example, not all forms are about people or places so it needs to be handled in the rules configuration. In this case it sounds like an incomplete replication...

**Comment by alxndrsn** [comment]
@binokaryg please update your `rules.nools.js` accordingly.
