### ISSUE TITLE
reporting rates support for multiple reporters to one health facility

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#418]
This feature request comes via msh/Humphrey because their analytics numbers are incorrect.  Currently our reporting rates assumes/expects a report from each reporting unit/chw/lowest level.  But in the case of MSH they have multiple reporting units that are responsible to submit a scheduled report, only one of them needs to submit it, but they all need to be registered/exist in the facilities/contacts data structure.

**Comment by abbyad** [comment]
Closing since this is no longer a requirement. It can be resurfaced as a new issue when needed since enough has changed with the way we do analytics for projects anyhow.
