### ISSUE TITLE
Improve the filtered replication algorithm

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4185]
The current algorithm has increased our replication performance significantly but has a few issues.

- [ ] In order to get notified of deletions we pass the list of IDs that PouchDB knows about. This does not scale. Find a better way to get deletion changes. More info on #4172
- [ ] Up until recently it had a timing issue where new docs could be skipped during replication if a change happened at the same time. Unfortunately the fix for this bug requires four database view requests every time the change handler fires which will hurt performance. We should find a better way of reliably getting every change. More info on #4166 
- [ ] It has no integration or e2e testing. It's a critical piece of our functionality so we need to ensure we don't regress when we make improvements.
- [ ] It is complicated and monolithic which makes it hard to read and understand and also hard to unit test for because you end up having to mock too much.

Notes:

- It may be useful to split the concept of catchup/initial replication from the continuous waiting replication. For example, for catchup replication it's highly performant to determine all the IDs a user is allowed to see and pass that to the CouchDB changes request. However with waiting replication this algorithm exposes #4166
- It may be useful to split the concept of deletions from the replication altogether as our current method of getting IDs you're allowed to see via a view means we don't know which deleted docs you _were_ allowed to see. This would be one way to solve #4172 
- Alternatively we could permanently store all the IDs you've ever been allowed to see and use that to request the changes feed.
- For waiting replication we currently make at least one changes request per longpoll request each with their own set of doc IDs. It may be more efficient to make one request for all changes including docs and run our own filter function and then respond to the relevant feeds. This would reduce load on CouchDB but add it to API.

**Comment by SCdF** [comment]
Here is my idea for how to implement this:
 - Two types of replication to consider: normal and longpoll
 - PouchDB initiates all replications like they are standard non-filtered replications from its perspective
 - We keep the current view that we have, which, given a document, emits all facilities that have access to it (and some meta types like `_all` and `_admin`)
 - API code, for normal replication:
   - API passes through the changes feed request (including `include_docs: false`), and catches it when it comes through from CouchDB. Let's called it `changesJson`
   - It gathers a list of all non-delete changes in `changesJson`, sends their `_id`s to the view, and remembers the results 
   - It gathers a list of all delete changes, and for each delete change GETs the specific `_id` and `_rev` from CouchDB, and runs that full document through a copy of the view JS in API, remembering those results
   - Those last two sets of results are combined into a list of permissions for all documents in `changesJson`, and we return a filtered changes result based on those permissions
 - API code, for longpoll replication:
   - Similar to what we already have
   - For every longpoll registration, store the res in a map with the user's context / id / facility_id
   - If there is at least one longpoll open, have a longpoll open from api -> CouchDB, with `include_docs: true` (|| don't?)
   - When this longpoll returns, run the document through the copy of the view JS in API (|| use the view unless it's a delete, in which case use the view JS in API?)
   - Walk through the registered longpolls, find ones who have permissions to see the doc (based on facility_id etc), send them this changes feed and close the connection

NB:
 - If the GET of the deleted document fails (ie compaction), then pass it down? We'd have to consider the security implications, but I think it's OK
 - We can wrap the view JS in API with a cache (or configurable size / type), which could be used to speed up these delete checks.

So in terms of performance / IO:
 - For normal replication we have **1x** view request per person per change normally, and **Nx** extra GET requests for every deleted documents
 - For longpoll replication we convert **Nx** _changes requests in **1** _changes request with `include_docs: true`
 
In terms of fixing bugs / addressing issues:
 - Correctly passes deletes back, without exposing document ids that users shouldn't know about
 - Does not suffer from delete timing issues
 - I think could be written as a standalone module with good tests, but probably any implementation could 
   
cc @alxndrsn

**Comment by garethbowen** [comment]
@SCdF This is along the right lines but there is a large performance issue in your normal replication. If a project with millions of seqs gets a new user they will do a normal replication from seq 0. The `limit` at the moment is 100 which means making a request for the first 100 changes, filters them all out, then requests the next 100. This will make initial replication to an established project impossibly slow. Is there some optimisation we can make here?

The current implementation filters by doc_id which is really fast. The only problem is we can't find the id for all relevant deleted docs.

I think we need a changes feed in API that watches for deletions and caches it somehow (perhaps in its own `api_replication` couchdb). When a "normal" replication comes in we can then get all non-deleted doc_ids they're allowed to see from the medic db, and all the deleted doc_ids they're allowed to see from the `api_replication` db, concatenate the two arrays and send the changes request to couch.

The "longpoll" implementation [I suggested here](https://github.com/medic/medic-webapp/issues/4166#issuecomment-363993286) is equivalent to what you suggest so I think we're on the same page here.

I think this solves the same problems without causing issues for initial replication.

**Comment by SCdF** [comment]
@garethbowen do you think performance would be acceptable if we did that looping on the API side? So the user sends a changes feed request for 100 docs, and api requests as many changes feed as required to fill that hundred (or run out)?

If we ignore deleting for now, then just requesting the docs from the view first and then doing a doc filtered changes request seems like a good idea. I believe that's what we're doing now right?

It is frustrating that basically deletes cause all of problems, and they are a very small part of the system.

Here are some crazy ideas to brew in your noodle:
 - Make permissions explicit not implicit, declare them in a companion file, and never delete permission companion files
 - Do the above, but only for deletes. I.e., have a `deleted_tombstone` document type that gets created on every delete, which stores the permissions around that delete for all time. 
 - a `medic_deleted` DB, which contains all deleted documents. Gets filled by watching the changes feed and copying deletes over without the `_deleted: true`. It also contains "the view", and so you query both to generate your doc ids list.
 - re-architect our system to not support "hard" deletes. Instead we have our own delete flag and we re-code our views / logic to ignore that
 - PR for CouchDB that allows you to declare that a view runs over deleted documents (there are issues here with compaction happening later etc)

**Comment by garethbowen** [comment]
> Do you think performance would be acceptable if we did that looping on the API side?

That's what I assumed we'd do anyway - I still think it would take a very long time. Say you have 10m changes, and you use a pagination of 1000 (probably ok because you're not including docs), and say we start from 0 and there are very few docs that match (it's a new user), you'll have to iterate 10,000 times in API before you can return to the user. Each iteration has to make a further request to one or more views to determine if it should be filtered out or not. I can't see this being performant. Am I missing something?

> If we ignore deleting for now, then just requesting the docs from the view first and then doing a doc filtered changes request seems like a good idea. I believe that's what we're doing now right?

Right.

> It is frustrating that basically deletes cause all of problems, and they are a very small part of the system.

Completely agree. If we can solve that some how then the existing system for updates works pretty well I think.

> Do the above, but only for deletes. I.e., have a deleted_tombstone document type that gets created on every delete, which stores the permissions around that delete for all time.

That's exactly the solution I proposed in the third paragraph in [the comment above yours](https://github.com/medic/medic-webapp/issues/4185#issuecomment-366810431).

> Re-architect our system to not support "hard" deletes. Instead we have our own delete flag and we re-code our views / logic to ignore that

I was thinking about this potentially feeding in to the purging implementation. I think it's too complicated for now...

Overall I think your suggestion #1 or #2 is the right direction. Either way, the first step is probably to write an integration test suite for what we have now so we can be confident the new algorithm doesn't break anything...

Let's talk/peer on it when we're both online some time. I think this is an excellent way forward.

**Comment by alxndrsn** [comment]
In couchdb 2.1.0+ we can increase the size of our change feed batching as per https://github.com/apache/couchdb/pull/541

**Comment by garethbowen** [comment]
Merged.

This will need extensive acceptance testing particularly:

- replication of deleted docs
- initial replication
- continuous replication
- replication depth
- security - ensure each user only gets the docs they're allowed to get

It will also be essential to test performance compared to the previous implementation on a production sized database to ensure it doesn't use significantly more memory or processor resource.

**Comment by ngaruko** [comment]
Just to double check @garethbowen : the initial replication comes with a number of 404 errors...
![image](https://user-images.githubusercontent.com/6979995/43175522-9e577d36-9013-11e8-882a-1474020424f2.png)

There a message in the end that `The above 404 is totally normal. PouchDB is just checking if a remote checkpoint exists.` Is this applicable to all the 404 errors in the console? At a glance, some of the requests that come with this error are:
```
https://alpha.dev.medicmobile.org/medic-user-bede-meta/_local/SueMxDI3UdlXdo3ZNwXiCA==?

https://alpha.dev.medicmobile.org/medic-user-bede-meta/_local/c0tJIHL56wWuUG4Ixsyvrg==?

https://alpha.dev.medicmobile.org/medic/_local/QbNzc_SlySBtr8tuaUMUcA==?
```

**Comment by garethbowen** [comment]
If they're all `_local_` docs then I think it's ok. @dianabarsan what do you think?

**Comment by ngaruko** [comment]
Apart from the console errors above, LGTM. Will close this and reopen another issue if release testing picks up any related issue.

**Comment by ngaruko** [comment]
Reopening this just in case this issue is related (while @dianabarsan is investigating: 

_I deleted a report in couchdb while still open in the UI. Back to UI, the RHS still shows the report…_


![image](https://user-images.githubusercontent.com/6979995/43190207-9f3fc72e-904c-11e8-8d95-cff4512d2774.png)

**Comment by ngaruko** [comment]
Since this behavior shows in earlier versions as well (on `beta-old`) I am tempted to close this and open a different issue. re: #4754
