### ISSUE TITLE
Update default icons to be the correct ones for Standard projects

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4194]
@amandacilek has continued to work on our library of icons and has created an icon for CHW area. She's also updated the icons for district hospital and health center/branch. Given that Standard is our default, I'd like to swap in the updated icons for district hospital and health center and replace the icon for clinic places with the CHW area icon (instead of household). Here are the links to the new files. @garethbowen Amanda said she exported them the same way she had done last time and I think you still had to make a few small changes before, so just giving you a heads up.

district hospital: https://drive.google.com/open?id=1GV0dzCo4YnA2PTWoZxScgyAsGNVKeIDk
health center: https://drive.google.com/open?id=1x4_rnN6FOuwSX4GvQQBnkbZZFXTBqjYO
clinic: https://drive.google.com/open?id=12Ts8gzyIyKBwF6bAqT5gep8emcbLDFUn

**Comment by garethbowen** [comment]
Tidied up, merged, and backported to `2.14.x`.
