### ISSUE TITLE
Confirm that bootstrapper's PouchDB is garbage collected after replication completes

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4196]

**Comment by alxndrsn** [comment]
We should either be calling `localDb.close(); remoteDb.close()` at the end of bootstrapper, or re-using the `PouchDB` objects.  Brief profiling suggests this will free about 6MB of heap, about 10% of total usage on initial replication.

**Comment by alxndrsn** [comment]
@garethbowen note that PouchDB will never completely garbage collect all event listeners: https://github.com/pouchdb/pouchdb/issues/6225

**Comment by garethbowen** [comment]
Merged and backported to `2.14.x`.

Difficult to AT - make sure initial replication and subsequent loads work as expected.
