### ISSUE TITLE
Timeouts not working correctly on Pouch 6.4.x

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4199]
Seen with:

* pouch 6.4.2, 6.4.3
* couch 1.6.1
* medic-api `master` (webapp repo); possibly on 2.12.x as well

-----

This seems to be some kind of interaction problem between PouchDB and our api (or perhaps couch).

Timeout seems to depend on `heartbeat` value:

![screen shot 2018-02-14 at 19 11 09](https://user-images.githubusercontent.com/191496/36220430-dc39c118-11ba-11e8-9cb6-3dbdc83521e7.png)

With `hearbeat: 10000` (as we have it set in `DbSyncSrv`), changes requests consistently time out in 15 seconds.

-----

It's not clear to me if this is a bug in api or couch.

**Comment by garethbowen** [comment]
@alxndrsn This is working perfectly for me for admins and restricted users (ie: no timeouts). Any ideas how to replicate this?

**Comment by alxndrsn** [comment]
@garethbowen did you manage to replicate with identical code to that above, and the same couch and medic-api versions?

**Comment by garethbowen** [comment]
It was on `master` and pouch 6.4.3 but Couch 2.1 not 1.6.

**Comment by alxndrsn** [comment]
NB this will need backporting to `2.14.x` before closing.

**Comment by garethbowen** [comment]
I still can't replicate as a restricted user using the latest alpha on alpha.dev with couchdb 1.6, however it does fail with admin. Given that admin requests are proxied directly to couchdb I think it's either a bug with PouchDB passing the wrong parameters or CouchDB not interpreting them.

**Comment by garethbowen** [comment]
Merged and backported to `2.14.x`

**Comment by ngaruko** [comment]
Does this need AT @alxndrsn @garethbowen ? If so, does `alpha.dev` combination of `couch/pouch` version for the test?

**Comment by garethbowen** [comment]
Yes it needs testing.

No `alpha.dev` is not ok because that's got 2.15.0 on it not 2.14.0.
