### ISSUE TITLE
Consider re-writing (C|P)ouchDB pagination without skip and limit

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4206]
Generally when we do pagination we use skip / limit:
 - Do a query with skip:0, limit: N
 - Do things with those N results
 - If < N results then you're done
 - Other loop, with skip = skip + N

This is really easy, and works everywhere, but it has performance problems: http://docs.couchdb.org/en/latest/ddocs/views/pagination.html

We should consider understanding this and rewriting some pagination that we do.

The most obvious places to look at fixing would the search shared library, and some migrations. Searching the code for `skip: ` is pretty illuminating.

**Comment by alxndrsn** [comment]
@SCdF I can't work out what performance problems mentioned in the linked doc are relevant to us.  The only mention of performance issues seems to be:

> The method described above performed poorly with large skip values until CouchDB 1.2.

**Comment by SCdF** [comment]
Sweet, no work to be done!

**Comment by alxndrsn** [comment]
This may still be worth considering for PouchDB.  Ref https://pouchdb.com/2014/04/14/pagination-strategies-with-pouchdb.html

**Comment by SCdF** [comment]
I wonder if this is still true with idbnext
