### ISSUE TITLE
IDs of new documents are not added to changes requests until page refresh

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4208]
To replicate:
 - Open a restricted user, watch the network. You should generate a longpoll _change request once everything is synced.
 - Create a new document. Note that a bunch of stuff happens on the network, but specifically that the first longpoll is satisfied by the document you just created, and a new longpoll is created after this.
  - Do that a few more times for good effect.
  
What should happen:
 - Every time a new longpoll request is initiated after you write a document, the id of that document should be among the ids passed

What actually happens:
 - The ids are the same each time.
 - If you refresh the longpoll that is initiated after this has the correct doc ids. 

Looking at the code this is actually obvious: we only add the doc_ids when we're instantiating the two way sync the first time.

**Comment by SCdF** [comment]
I updated the description

**Comment by alxndrsn** [comment]
I don't think this is surprising, as the list of `_doc_ids` [is generated in `DBSync`'s `getOptions()` function](https://github.com/medic/medic-webapp/blob/master/static/js/services/db-sync.js#L57), which is called _once per call to `PouchDB.replicate()`_.  [AFAICT](https://github.com/medic/medic-webapp/blob/master/static/js/services/db-sync.js#L63-L72), `.replicate()` then internally handles re-establishing the connection after a new doc is created.  (There doesn't seem to be any handling in the [`updateListener`](https://github.com/medic/medic-webapp/blob/master/static/js/controllers/inbox.js#L69-L93) which might trigger the re-generation of the `_doc_ids` list.)

**Comment by abbyad** [comment]
Redirecting to @alxndrsn to put the type Status and Priority

**Comment by alxndrsn** [comment]
I'd guess this is low priority, as:

* deleting documents that have just been created by a different user probably isn't that common.  But perhaps deletes aren't reaching all phones used in training?
* fixing it looks fiddly

Thoughts, @garethbowen @SCdF?

**Comment by SCdF** [comment]
Well I think ideally we'd fix this implicitly by redesigning the replication API so we don't have to know the ids at all, see: #4185 

If we can't fix that particular oddity in the algorithm we should look into this.

**Comment by garethbowen** [comment]
We no longer include doc ids in the request so this is fixed.
