### ISSUE TITLE
Make logged in user easily discoverable on Android

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4210]
We recently allowed Android users to log out if they have the `can_logout` permissions, as `requested by a partner who has multiple users sharing an Android tablet`. Wouldn’t be nice to have a way on the phone to know at a glance (maybe on opening the hamburger menu) which user is logged in. Not a biggie since we still can get there by going to ‘edit user profile’ in ‘user settings’ but I thought we could shorten that path. Any thoughts @sharon?
![image](https://user-images.githubusercontent.com/6979995/36405768-2eab08e4-1657-11e8-9d85-f42638798c84.png)

**Comment by sglangevin** [comment]
This is going to be fixed in 3.1.0. We don't plan to do anything related to this until the big UI refresh, so I'd recommend we close this issue as it will be coming in the future.

**Comment by ngaruko** [comment]
Thanks @sglangevin . Closing this pending v3.1.0
