### ISSUE TITLE
Export server logs not working

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4211]
Tested on local `2.15.0-alpha.9102` and `alpha.dev` version `2.15.0-alpha.9102`
To reproduce, log in as admin, go to Configurations, Import & Export, server logs, click Export
Expected: server logs download popup
Current behavior: Nothing happens for a while, no errors in console, then the app crashes with either `server error` or 
![image](https://user-images.githubusercontent.com/6979995/36405950-5b1886e4-1658-11e8-9514-3c72361b88dc.png)

with url: `https://alpha.dev.medicmobile.org/api/v1/export/logs?format=zip&locale=en` (* on alpha.dev)

Errors on local:
```1 - admin [20/Feb/2018:02:25:52 +0000] "GET /api/v1/export/logs?format=zip&locale=en HTTP/1.1" - - "http://localhost:5988/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.73 Safari/537.36"
Server error:
 Error: Log export exited with non-zero status 1
    at ChildProcess.<anonymous> (/Users/bede/.horticulturalist/deployments/medic-api/md5-KdEdCaHtkcBTO1qyCLyg==/controllers/export-data.js:283:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
::1 - admin [20/Feb/2018:02:25:52 +0000] "GET /api/v1/export/logs?format=zip&locale=en HTTP/1.1" - - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.73 Safari/537.36"
Server error:
 Error: Log export exited with non-zero status 1
    at ChildProcess.<anonymous> (/Users/bede/.horticulturalist/deployments/medic-api/md5-KdEdCaHtkcBTO1qyCLyg==/controllers/export-data.js:283:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by SCdF** [comment]
Is alpha.dev docker / horti?

I wouldn't expect this to work locally.

FWIW if we have any problems with this feature my vote would be to drop it.

**Comment by sglangevin** [comment]
I'm asking the tech leads whether or not anyone uses this in the UI or via API. So far it doesn't sound like anyone uses this in practice, but I'll come back to this issue with an update if I hear otherwise.

**Comment by garethbowen** [comment]
@sglangevin Any update on this? I just tested it on beta-old.dev and the file blew out to ~2GB before I killed the script. Currently it collects all logs together and then zips them up. If we want this feature to work it would need to compress files as it goes or filter down to files that have been written to recently to reduce the sheer volume. If it's not used or useful we should remove it ASAP (ie: 2.15). If it's potentially useful we should investigate making it work at scale soon (ie: 3.0).

**Comment by SCdF** [comment]
I'm going to reiterate my vote from Feb: drop it from the UI:
 - It's data that is medic-specific, and so being a webapp admin shouldn't give you permission to see the logs
 - It may contain PHI, and or medic-sensitive data (eg perhaps we make a mistake and expose passwords in the logs)
 - We have always supposedly supported people installing this app themselves, and we are moving to a world where partners and others will actually be doing this: this feature requires our server layout

Putting it medic-conf makes the most sense to me, it's a better audience.

**Comment by sglangevin** [comment]
All I know is that User Feedback docs are being used by our support team and we need to make sure they are available on every instance. @ngamita can you comment on whether the other logs are being used by your team? Last I checked, sever logs weren't being used (from what I recall).

**Comment by ngamita** [comment]
Yes, that's correct @sglangevin the other error logs showing on feedback page are not useful to us at all and also server logs are not being used - we're using the Feedback page to sieve issues being reported from the field - take the example of these issues coming from MoH Siaya directly from the CHVs 
![screenshot from 2018-05-02 17-44-20](https://user-images.githubusercontent.com/294861/39530079-d4262338-4e30-11e8-9f7e-f8c1dd0edadc.png)

Also we have a little dashboard for filtering only what we need and separating the noise, still work in progress though - 
![screenshot from 2018-05-02 17-46-13](https://user-images.githubusercontent.com/294861/39530229-34b3942e-4e31-11e8-8249-41a8174ebdc5.png)

**Comment by garethbowen** [comment]
@sglangevin Do you agree, therefore, that we should drop the API and UI elements? Are you ok with me adding this to `2.15.0`?

**Comment by sglangevin** [comment]
Yeah, I think we should do it. One less way to end up with an unresponsive server. I could also see leaving it and removing in 3.0 since no one uses this feature anyway so it's unlikely to cause production issues, but given the rate of upgrades doing it now might be better.

**Comment by garethbowen** [comment]
Scheduling for 3.0. We need to remove the API, UI, and the script in medic-os.

**Comment by garethbowen** [comment]
@rmhowe Please code review the [webapp PR](https://github.com/medic/medic-webapp/pull/4535) and @browndav please review the [medic-os PR](https://github.com/medic/medic-os/pull/32).

**Comment by ngaruko** [comment]
Removed from the UI in v3.0 > tested on 'alpha.dev`
![image](https://user-images.githubusercontent.com/6979995/40599706-9c6e2964-62a2-11e8-8d40-2971880b5fdd.png)
