### ISSUE TITLE
Fix pouch/tecno patch regression

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4212]
`pouchdb-adapter-idb` is included as a dependency in `medic-webapp`, but actually unused - it's included inline in the `pouchdb-browser` dependency.  This means that since changing to this lib (or perhaps: since this lib has stopped using `require()` calls), we have re-introduced #2797.

We need to:
- [x] remove direct dependency on `pouchdb-adapter-idb`
  - [x] `package.json`
  - [x] `package-lock.json`
- [x] re-implement patch so that it works on `pouchdb-browser`

**Comment by alxndrsn** [comment]
Introduced in 721d9111e965fedec85d74ac2e84f1a55537bb98, so has not been released yet.

**Comment by garethbowen** [comment]
Merged and backported (manually) to `2.14.x`.

Needs some serious AT to make sure the changes request never reverts to `since=0`.
