### ISSUE TITLE
grunt doesn't auto-push changes to medic-client

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4228]
To reproduce:
 - Have `grunt` running
 - Make a change to a medic-client view
 - Notice that grunt fires, and the DDOC gets updated
 - Notice that your view hasn't changed
 - Kill grunt and start it again
 - Notice this time it works

**Comment by garethbowen** [comment]
@SCdF I can't reproduce this. When I save a view it's compiled, attached to the medic ddoc, and the medic ddoc is uploaded. Then API notices the change and extracts the medic-client ddoc which is then replicated to the browser and an update dialog is shown. Clicking the "update" button reloads the page and uses the updated view.

Which step specifically wasn't working? Did API watches fire? Did the update dialog show in the browser? Or did the new view not get used when you refreshed?

**Comment by SCdF** [comment]
I pretty much only recall what I wrote down. It may have been that my grunt was in a weird state?

**Comment by garethbowen** [comment]
grunt watching was refactored massively in #4536 which has hopefully fixed whatever bug this was. Reopen if it happens again...
