### ISSUE TITLE
Phone number not shown when contact is not found

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4231]
The sender phone number is missing in the RHS if it is not associated to a known contact. I would expect the number to show up in the RHS even if there is no name or place associated to it.

# Unknown contact
![image](https://user-images.githubusercontent.com/789512/36554200-9222e2a4-17cc-11e8-80aa-f82ed2f902cf.png)

# Known contact
![image](https://user-images.githubusercontent.com/789512/36554212-9fd26cbc-17cc-11e8-9a2f-962c60bf2232.png)

As seen in 2.14 --^
cc @amandacilek

**Comment by abbyad** [comment]
I have run into this again in testing 2.15, and believe it is a bug now that the LHS shows the subject of the report, not the submitter. It is therefore impossible to know who sent the message at all.

![image](https://user-images.githubusercontent.com/789512/37829286-d5803f74-2e74-11e8-8946-509fb5c83e1b.png)

**Comment by dianabarsan** [comment]
Changes are underway which modify the RHS Report summary as well (see: https://github.com/medic/medic-webapp/issues/4053#issuecomment-373520150). 
Would you say that displaying "Unknown sender" along with the phone number would be ok?

**Comment by abbyad** [comment]
Yes, I think that would be ok, but not necessary. In following how it is proposed in #4053 I think it would make sense for "Sent by {submitter name}" to become "Sent by {phone number}" when the contact is unknown. Open to other suggestions though!

cc @amandacilek

**Comment by garethbowen** [comment]
#4053 is now in AT so I'm going to move this to AT too. @abbyad Please spit it back if the implementation for #4053 is insufficient in this case.

**Comment by abbyad** [comment]
Here is what it looks like now that 4053 is done, which looks to be in `2.15.0-beta.2`:

![image](https://user-images.githubusercontent.com/789512/38056654-0d08bbda-32ab-11e8-9050-f2cce278493e.png)

I think it should still show the phone number next to or instead of "Unknown sender", so sending back.

**Comment by dianabarsan** [comment]
@garethbowen I have not included the solution for this issue in #4053 as @abbyad had cc-ed Amanda for feedback. Was not sure if it was final or not.

**Comment by amandacilek** [comment]
Marc's suggestion to have it say "Sent by {phone number]" sounds fine to me. 

However, I want to make sure I understand - don't we already include a phone number sometimes, right after the first name? On the old design, when the first name was the submitter, I assume this was the submitter's phone number? Now that we've changed the first name to be the subject/patient, was that also updated to now display the subject/patient's phone number?

I'm asking about this phone number we already have:
![screen shot 2018-03-28 at 2 26 24 pm](https://user-images.githubusercontent.com/26235957/38057364-0867aa58-3294-11e8-8640-c0f98770186d.png)

It makes sense to me that the phone number right next to the subject/patient is the subject/patient's phone number. In which case, I am fine having it say "Sent by {phone number]" in the case of unknown sender.

**Comment by abbyad** [comment]
The phone number on the first line was removed with #4053, and I dont think we ever show the subject phone number. Seems as though this phone number would be on the third line with the submitter info. The question is what the label should be along with the phone number, if there is one at all.

Some options:
- {{phone_number}}
- Submitted by {{phone_number}}
- Unknown sender {{phone_number}}

@amandacilek, you may have styling recommendations too!

**Comment by amandacilek** [comment]
Marc - of the three options you list, I don't like just {{phone_number}} because then there is no context about whose phone number it is. I prefer Submitted by {{phone_number}}.

I don't know the background/history of Reports here and how it got to it's original design so @diannakane @sglangevin please jump in with your thoughts:

- I could be wrong but I'm not sure the intent of #4053 was ever to remove the phone number on the first line. I thought it was an option that was either turned on or off in configuration and my assumption was it would remain if applicable.

- So, do we want to list the subject/patient primary contact phone number on the first line next to the name? I could imagine this being useful. 

- Do we want to _always_ list the sender phone number next to the sender name? I could also imagine this being useful. Then we would either have:
       "Submitted by Janet Mwangi +123456789" or
       "Submitted by +123456789"

**Comment by sglangevin** [comment]
Many/most patients do not have a phone number, so I'm not sure that keeping that on the first line is very relevant. No patients on SMS workflows have phone numbers, for example, and most children also don't have phone numbers. That might be a significant chunk of people whom reports are sent about, so I think removing the phone number from the first line makes sense. (@amandacilek this was never configurable, it just wouldn't show a phone number if the person submitting reports did not have a phone number). Perhaps we should look at the % of people docs that have phone numbers before we decide, though I also think having 2 phone numbers in the top section is a lot.

I also think we should always list the sender phone number next to the sender name and I think the two options you presented (one for a known submitter and one for an unknown submitter) work well.

**Comment by sglangevin** [comment]
I would expect it if the submitter has a phone number in our system. I think it makes sense to include it regardless of whether its an SMS or an app form just for consistency, but I don't feel strongly about that. I think that's how we had it before we made these changes, though, isn't it?

**Comment by diannakane** [comment]
I like the submitting phone number always being there because it's common for managers to call to follow up with CHWs about a report they submitted so this provides easy access to that information. 

Have we considered: 
Submitted by: Unknown person
Phone number: +123456789

Submitted by: Janet Mwangi
Phone number: +123456789

Is it functionally easier to handle these fields separately knowing that we will be redesigning this reports view at some point in the mid-term future?

**Comment by abbyad** [comment]
I think any of these are reasonably feasible, and wouldn't block future changes. The hardest part is deciding which to use :)

Confirming that in 2.13.5 the submitter phone number is included if available, regardless of how the form was submitted.

I like the idea of being explicit with "phone number", but that adds a line to the UI which is more disruptive to the design than beneficial in my opinion.

Seems like we are all comfortable with the following for 2.15, and we can revisit this when the whole page is redesigned:

> **Submitted by Janet Mwangi** +123456789
> **Submitted by +123456789**

**Comment by dianabarsan** [comment]
Merged and backported to `2.15.x`

**Comment by abbyad** [comment]
Looks great in `2.15.0-beta.4`! Moving to Ready
