### ISSUE TITLE
Wrong date shown based on time and timezone

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4232]
Some of our Standard reports set the birth date via SMS by setting it as N "days ago". The fields shown in the Reports tab can be unexpected:

## Birth date 3 days ago shows as 4 days ago
![image](https://user-images.githubusercontent.com/789512/36556426-20ecebe6-17d3-11e8-963e-169ae1bffcee.png)

## Birth date 0 days ago shows as yesterday, and 18 hours ago
![image](https://user-images.githubusercontent.com/789512/36556416-1a08a6d0-17d3-11e8-9e44-2da1d7d2dced.png)

# Date is shown as off by one, depending on your timezone
The date is a day earlier than expected, likely due to a timezone issue (https://github.com/medic/medic-webapp/issues/488). The calculated date for the date of birth is `"birth_date":"2018-02-22T00:00:00.000Z"`, therefore we are assuming that all SMS are submitted on UTC. When seeing this date in EST (as in my case) it shows the birthday as being a day off. 

- **Should we instead save the day without the time component eg `2018-02-22` ?**

# Relative date + time is misleading
The relative date/time resolution should match the date resolution. It seems odd to say "18 hours" ago for an event that was "today". If the birth date is a day, we should only have relative we could have "today", "days/weeks/months/years ago", but not "hours ago"

**Would this automatically be resolved if the date were saved without the time component as mentioned above?**

------
There is a larger question of how to take into account timezones in message scheduling. That seems like a separate but relevant issue, and one we will run into more as we projects further away from UTC. @henokgetachew, how are we currently dealing with this now?

**Comment by abbyad** [comment]
> Would this automatically be resolved if the date were saved without the time component as mentioned above?

No, it would not. I just tested the following:

# With field as is
### `"birth_date": "2018-02-22T00:00:00.000Z"` screenshot  at ~15:45 EST on 2018-02-22
![image](https://user-images.githubusercontent.com/789512/36563381-ed546b3c-17e7-11e8-9ba2-636da1d96f8c.png)

# Stripping time 
### `"birth_date": "2018-02-22"` screenshot at 15:45 EST on 2018-02-22
![image](https://user-images.githubusercontent.com/789512/36563296-a98ff2fe-17e7-11e8-8829-74533f31cc25.png)

**Comment by SCdF** [comment]
@abbyad so we think the error is that we're not taking into account the contact's / system's tz when calculating absolute dates from relative values? It would not surprise me: this stuff is hard

**Comment by henokgetachew** [comment]
@abbyad all of the servers currently use timezone UTC.

**Comment by abbyad** [comment]
There are two display issues regardless of the server time (1 & 2, from the OP), and two other issues (3 & 4) due to the servers being on UTC:
1) **Absolute date displayed should be the same shown regardless of timezone.** From OP: _The relative date/time resolution should match the date resolution. It seems odd to say "18 hours" ago for an event that was "today". If the birth date is a day, we should only have relative we could have "today", "days/weeks/months/years ago", but not "hours ago"_
1) **Relative time resolution should not be smaller than the precision of the datetime.** From OP: _The relative date/time resolution should match the date resolution. It seems odd to say "18 hours" ago for an event that was "today". If the birth date is a day, we should only have relative we could have "today", "days/weeks/months/years ago", but not "hours ago"_
1) **SMS schedules are created on UTC time.** This means that setting a scheduled message to send at 9am would actually be sent at noon in Kenya, and 4pm in Indonesia. _This could be mitigated before because the config was project specific so the times could all be shifted. With Standard we have the same config across timezones._
1) **Relative dates could be off by one.** If a delivery is reported in Indonesia at 6:30am to have been a day ago, it will get saved as 2 days ago because the server is still on previous day. This would have undesired effects for PNC schedules which have tasks and scheduled SMS for 1, 3, and 7 days after delivery.

**Comment by abbyad** [comment]
> @abbyad so we think the error is that we're not taking into account the contact's / system's tz when calculating absolute dates from relative values? It would not surprise me: this stuff is hard

This is a factor for 1, 3, and 4 above. You are right, it is not simple! So far we have been able to avoid these issues, but likely have to deal with it now that configs are the same across Standard projects.

**Comment by SCdF** [comment]
I'm not sure I agree with 1. I think it's fine if that's how our app works, but I don't see the problem with the display date being in the correct TZ: as long as its stored in UTC we can have the display be whatever we want

**Comment by abbyad** [comment]
It may be easier to discuss on a call, but I'll try first to clarify point 1 in case we already agree. I am proposing that dates set using "days ago" should be **(a)** displayed as the same date regardless of the timezone of the logged in user, and **(b)** set relative to the project timezone. 

The events that being reported are often a birth or a visit that occurred on a particular day with no hour precision. Given that, the reason for (a) is that I think most people would expect a birthday to be displayed as the same date regardless of where in the world they log in. For (b) I think it is important that the concept of "1 day ago" create the same date throughout the whole day based on the project's timezone. (SMS reports should be assumed to be submitted on the same timezone as the project instance.)

**Comment by abbyad** [comment]
After discussing with @SCdF it seems as though 1 & 2 could be a quick fix to _display_ the proper day with appropriate relative time. Items 3 & 4 would need a timezone setting in the app, and should be accompanied with a larger review & update of dates throughout the app to make sure they all take the timezone into consideration.

**Comment by SCdF** [comment]
OK so:
 - We should work out why the DOB is displaying with a relative date time and not a relative date
 - We should really have a larger discussion about time zones, and whether we should be conscious of them.

**Comment by SCdF** [comment]
@garethbowen do you know how things like birth dates displayed in reports get relative dates generated for them? It's not clear to me from briefly looking into the code. If you don't know off hand I'll dig in more though

**Comment by garethbowen** [comment]
The reports are run through the FormatDataRecord service which hasn't been updated in years (but it has been migrated from the kujua-sms package few improvements were made). This is the line of code that determines how to format the field value: https://github.com/medic/medic-webapp/blob/master/static/js/services/format-data-record.js#L217

This has a couple of problems:

1. It doesn't know the difference between date, datetime, and dob. We could add a new field type to the form definition for `dob` or `age` so we have more context.
2. It should use the FormatDate service which has benefited from improvements like this over the last few years.

**Comment by newtewt** [comment]
@abbyad  @vimemo  @garethbowen  for this ticket what was changed? There is a lot of back n forth on different issues. Can you help clarify? 

Looking at Beta dev I'm still seeing the Days ago being 3 where the birthdate is days ago + 1. Looking at the record in couch it shows  "birth_date": "2018-07-24T00:00:00.000Z" .  However, if I look at this on my local machine I see the "birth_date":  "2018-08-04T04:00:00.000Z" but my current timezone locally is EST. 

I see that the 2nd issue seems to be corrected about 18 hours vs today/yesterday as the time statement.

**Comment by vimemo** [comment]
After a few discussions, this ticket only resolves/support issue #2 from a previous comment:
**2. Relative time resolution should not be smaller than the precision of the datetime**

**Comment by newtewt** [comment]
Thanks Victor, we are showing yesterday, today, tomorrow, and x days ago. 
![screen shot 2018-07-26 at 4 41 56 pm](https://user-images.githubusercontent.com/10531066/43287485-2b78ff16-90f3-11e8-897b-23f007835360.png)
![screen shot 2018-07-26 at 4 42 02 pm](https://user-images.githubusercontent.com/10531066/43287486-2b865472-90f3-11e8-99bc-89006eb0177f.png)
