### ISSUE TITLE
Set return_docs: false when calling changes feed

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4236]
Worth investigating if setting `return_docs: false` will improve performance.

Ref https://github.com/pouchdb/pouchdb/issues/6502

**Comment by garethbowen** [comment]
Which changes feed are you talking about? There are many cases where we need the docs...

**Comment by alxndrsn** [comment]
> There are many cases where we need the docs...

Yes indeed!  But this option prevents all docs from a changes feed being cached, and then returned in the `complete` event.  We never listen for this event.

**Comment by garethbowen** [comment]
Sorry, I misread "return_docs" for "include_docs". Good call.

**Comment by garethbowen** [comment]
Merged and backported to `2.14.x`

**Comment by garethbowen** [comment]
There's no way to AT this specifically - just make sure changes feeds still work by making changes in the local db and making sure the UI is updated automatically.

**Comment by ngaruko** [comment]
LGTM
