### ISSUE TITLE
Write a scalability testing framework

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4244]
We need to be able to determine how many users our app can support. This will help us to...

1. work out which aspects to focus on
2. prove improvements work as expected
3. test for regressions

More information is available [on drive](https://docs.google.com/document/d/1V3gOlgiKBlyRNT6c-mTcefmDVlQBbdw6NpIWiwNgNzI/edit).

**Comment by SCdF** [comment]
Apologies if this is the wrong place, but I've disabled the "should return within a reasonable time" test from https://github.com/medic/medic-webapp/blob/master/tests/protractor/e2e/api/controllers/sms-gateway.spec.js with a TODO that links it here, as what that is testing is a) flaky on travis, and b) seems like a reasonable thing that this framework would also test.

**Comment by garethbowen** [comment]
That test will be incorporated into the sms workflow component of the scalability testing script. I'll delete the e2e test.

**Comment by garethbowen** [comment]
Merged. Setting to AT. Instructions for running the script are at: https://github.com/medic/medic-webapp/blob/master/tests/scalability/README.md

**Comment by garethbowen** [comment]
@newtewt Yeah there's definitely room to improve the current solution. Passing the params from the command line is definitely a good approach, particularly if we want to execute this script in CI one day... Feel free to raise new issues for any improvements you can think of!

> Then replicated through a http call through jmeter.

This was the initial approach @ngaruko tried and it would definitely get better results, unfortunately the replication API is really complicated and multiple requests that depend on results from previous requests. Using node for this means we can just use PouchDB just like we do in the browser which handles all these request for us so it's a lot to write simpler and more robust. It also has the added advantage of accurately testing the actual replication steps rather than us reimplementing our own steps. For example, with PouchDB detects when its replicating with CouchDB v2 as opposed to CouchDB v1 and uses faster APIs, so using PouchDB in this test means we can test how much more we can scale with these new APIs.

**Comment by newtewt** [comment]
I added some links about parameterizing to the google doc for now. Closed this ticket.
