### ISSUE TITLE
API shouldn't start if audit db doesn't exist

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4245]
Currently if there's no audit DB everything will run happily until you try to do an audited action.  At which point...
```
16:56:20 api.1      |  ERROR { Error: no_db_file
```
!

**Comment by SCdF** [comment]
FWIW API creates the audit db when it boots based off a migration, so this seems like an unlikely problem to occur (in prod at least)

**Comment by alxndrsn** [comment]
In which case:

1. this is caused by me deleting migrations locally
2. it wouldn't make much sense for api to refuse to boot if the db isn't found
