### ISSUE TITLE
Place icons in the LHS action bar should be 30x30

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4247]
Place icons are quite small on mobile and hard to see. They should be 30x30 so that they are not hidden by the + sign.
![screenshot_2018-02-27-14-04-31](https://user-images.githubusercontent.com/1286381/36765508-72af02fe-1be6-11e8-9e91-15f4f36ede0d.png)

**Comment by SCdF** [comment]
@sglangevin to be clear, the problem is that if someone uses an icon (SVG, font or png?) that is too small we won't force it to be 30x30?

**Comment by sglangevin** [comment]
We've limited people to using icons that we create (right now there are 4 options). These are all SVGs and should be displayed at 30x30 in the LHS action bar. The problem is with our icons - I don't expect us to support random icons generated by people other than our product team, at least for now.

**Comment by SCdF** [comment]
@garethbowen I think I got it.

(FWIW, I also in general tried to refactor inbox.less a little, but it got nuts very quickly, and I'm *way* too unfamiliar with less to know what was going on. I'd love to pair on that actually. Three things:
 - action-container stuff should be in its own file
 - 400px and 767px are used in lots of places, they should be vars?
 - mm-icon vs icon
)

**Comment by garethbowen** [comment]
Code looks good. Happy to pair on css refactoring sometime.

**Comment by ngaruko** [comment]
LGTM
