### ISSUE TITLE
Docker: Provide additional control over the automatic bootstrapping of Horticulturalist

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#4266]
In our Docker images, Horticulturalist is automatically bootstrapped using `--medic-os --only-bootstrap` on first run, deferring to Horticulturalist's judgement re: which build of our app to install. This automated bootstrap process removes a manual step for our ops team, and is IMO useful.

However, our images do not currently provide a way to control *what* build name or type is bootstrapped by Horticulturalist, and do not provide a way to disable automatic bootstrapping. Being able to control this behavior at container launch time seems useful in many situations (e.g. to quickly test or troubleshoot using alternate alpha/beta/release/snapshot versions of our app).

Proposal:

- [x] Support a `HORTICULTURALIST_BOOTSTRAP` environment variable, intended for use with the `-e` option of `docker run`. If this variable is specified, automatically provide it on the right-hand side of `--only-bootstrap[=buildname|@type]` during the automatic first-run bootstrap.
- [x] Add a `HORTICULTURALIST_BOOTSTRAP_DISABLE` environment variable. If specified and non-empty, the automatic bootstrap process for Horticulturalist will be skipped entirely, and the `HORTICULTURALIST_BOOTSTRAP` environment variable will be ignored.

Estimated impact: 5-7 lines of additional /bin/sh code, no changes to the Horticulturalist codebase, and no change to the default first-run behavior.

Perceived benefit: Easily control what version of our app is auto-installed without adding an extra configuration or installation step.

Cc: @SCdF @garethbowen

**Comment by SCdF** [comment]
The first point sounds great, that should definitely be exposed! I think there is also a discussion to be had as to what the default should be. I think in the production docker it should definitely be the latest master, in large part because we want to push people to the latest version as much as possible. If there is already a dev flag where the docker image knows it's running in non-production mode this could actually cause it to load the latest master?

The second point I'm not so sure about. If there is no bootstrap, what would the next step of using the docker image be? You couldn't even (currently) install a new version after the fact without sshing and monkeying with horti (which I also don't think we support that well).

If we want to use the docker image for dev I *think* we'd need to either disable horti entirely, as I'm not sure what value it could provide if you're running all your own code.

**Comment by browndav** [comment]
I feel less strongly about the second option (it was by request last week), but you're right that is should probably no-op horti entirely if implemented. I'll do the first and skip the second for now unless someone objects.

**Comment by browndav** [comment]
I'm guessing you'd prefer that the default be implemented in horti (i.e. when no specific build is requested via `--only-bootstrap` or `--bootstrap`); is that done or should we file a ticket?

**Comment by SCdF** [comment]
Horti defaults right now to the latest beta build IIRC. Once there is actually a final build on there (ie once 2.14 goes gold) the intention is to change it to that.

**Comment by SCdF** [comment]
Actually I lie it apparently picks master as the default? I need to read through the code / docs again, I'm getting confused

**Comment by SCdF** [comment]
Right, so horti defaults to master, and our medicos integration defaults to beta: https://github.com/medic/horticulturalist-on-medic-os/blob/5bace22a436d2521c5424f7ac6f920a169214ff9/packages/horticulturalist/scripts/horticulturalist/env#L83

The intention is the code linked above changes to release once there is one

**Comment by browndav** [comment]
Tossing over to @henokgetachew and/or @SCdF for a quick review.

**Comment by SCdF** [comment]
@browndav looks good to me, with the proviso that these flags should be documented somewhere so we know they exist.

Also, I see you implemented the no bootstrap option. What was the use case there?

**Comment by henokgetachew** [comment]
LGTM

**Comment by ngaruko** [comment]
Does this need any AT @browndav @henokgetachew ?

**Comment by browndav** [comment]
I think we're in good shape here. It _would_ IMO be worth filing an issue centered around how to test our latest alpha on the new Docker Machine AWS infrastructure. The alpha.dev and beta.dev URLs are switched over already, and we have the old machines still available (e.g. for a manual replicate-and-crosscheck approach) if they're needed.
