### ISSUE TITLE
Misaligned default language icons

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4274]
The star to indicate default languages is misaligned:
![image](https://user-images.githubusercontent.com/789512/37118079-02eebb94-2221-11e8-9b3b-d7e5c220d11b.png)

Seen in `2.14.0-beta.16`, using Chrome at 100%.

**Comment by garethbowen** [comment]
Moved to 2.15.0 - it's not high enough priority to backport.

**Comment by ngaruko** [comment]
Looks better. Not sure if @abbyad would like it more in the center of the icons....?
![image](https://user-images.githubusercontent.com/6979995/37438261-4814a8c4-2856-11e8-926b-08ff7b6ac325.png)

**Comment by sglangevin** [comment]
This is the correct way - this is how it looked before.
