### ISSUE TITLE
Labels missing from the Outgoing Messages translation tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4286]
The `Outgoing messages` translation tab is misleading since it looks like there are no labels to translate:

![image](https://user-images.githubusercontent.com/789512/37311209-dd0dfc00-261c-11e8-871c-c95fd484dbd7.png)

This is because these fields are now translated as part of the .properties files, which only show in the `Application text` tab. 

A couple of possible options:
1) Remove the `Outgoing messages` tab altogether. _Simple, but removes existing functionality for older configs with text in app_settings._
1) Hide the tab if there are no labels that would show. _Same as 1 above, but only if there are no translations in app_settings._
1) Hide the items that don't have editable translations. _Similar to 2, but instead hide items don't have translations in app_settings_
1) Bring the appropriate labels into the Outgoing messages tab. _Preserves the functionality of editing translations for outgoing messages, and separating them from the long list of other labels_

I would think that the last option is ideal from a user perspective, if it is not substantially more effort.

**Comment by garethbowen** [comment]
I think we should implement option 2. It's simple technically and encourages configurers to use the recommended translation solution.

We should also add a warning at the top of the tab body that it's deprecated with information (a link to medic-docs maybe?) about how to migrate to the proper solution.

**Comment by Jodge** [comment]
@Gareth @abbyad It seems this has changed now. 

-  The Admin URL `translation/languages` doesn't have _Outgoing messages_ tab, so it was removed

- _Outgoing messages_ on the Admin Configuration currently fetches data from `medic_admin/message_queue`, formats and displays them.

**Comment by garethbowen** [comment]
Ahh right - I think we dropped the obsolete Outgoing Messages tab when we split out the admin app. @abbyad Can we close this?

**Comment by abbyad** [comment]
Yes, we can close as they are now included with the rest of the _Application Text_

![image](https://user-images.githubusercontent.com/789512/48636062-d48acd80-e997-11e8-9892-8082d4679f6d.png)
