### ISSUE TITLE
Everyone is a primary contact

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4288]
For some reason, every person's profile has the yellow star and says "primary contact" even if that person is not the primary contact for any place. Places also have the primary contact label on them. This label should only be displayed for people who are actually the primary contact of a place.

Examples:
I clicked on General Hospital and then Central Health Center. Notice that Central Health Center has the primary contact label. Also notice that Anjali is listed as the primary contact.
https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/3e2fc8df-eeab-4b99-887c-dc42f407a442
Then I clicked on Angelina (who wasn't the primary contact) and she has the primary contact label:
https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/82c1c868215daa278f45209ab753ff7b

**Comment by SCdF** [comment]
Fastest bug fix ever. Maybe too fast…

**Comment by garethbowen** [comment]
It looks like it was broken in [this commit](https://github.com/medic/medic-webapp/commit/2bf99bd82fa9f9268afeeceaf498521016ae997d#diff-b259c456057dd9b09be9a7f05704a0dc). I think I removed it to make sure the layout worked for deceased primary contacts.

**Comment by ngaruko** [comment]
LGTM
