### ISSUE TITLE
Form sent from `medic gateway` comes with `Unknown sender`

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4289]
Steps to reproduce:
1 - Go to `Medic-Reporter`
2 - Pick a form (I used `New Pregnancy`)
3 - Fill in required details and send
4 - Go to the web app >> Reports tab and selected the report sent

Expected : on the RHS, we should be able to see the report submitter...
But : It shows `Unknown sender`
![image](https://user-images.githubusercontent.com/6979995/37379363-1271debc-2798-11e8-9b53-57cf86511767.png)

(Tested on `alpha.dev .... version 2.15.0-alpha.9568`)

Note: This has been modified by issue [#4053](https://github.com/medic/medic-webapp/issues/4053) to show the subject of the from rather than the submitter.

**Comment by dianabarsan** [comment]
Actually, #4053 has only updated LHS (the list), it has not touched report content.

**Comment by sglangevin** [comment]
Yeah, I don't think this is a bug. You have to adjust the "Sent from" number to be a phone number that exists as a contact in Medic. I'm going to close this.
