### ISSUE TITLE
On single column pages, remove scroll within a scroll

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4294]
When on the Targets page viewing a lot of widgets that continue below the page fold, I cannot scroll the page with my mouse positioned on the far left or right side of the page in the grey background area. The page only scrolls when my mouse is positioned on top of the central content area where the widgets are. I see no reason for us to have a scroll within a scroll on this page because the content is not split up into LHS and RHS.

![screen shot 2018-03-14 at 3 42 18 pm](https://user-images.githubusercontent.com/26235957/37435278-df018fc0-279f-11e8-8a2e-878bb8b2e322.png)

**Comment by garethbowen** [comment]
This also applies to other similar pages like configuration and about.

**Comment by garethbowen** [comment]
Back to you @wtekeu

**Comment by ngaruko** [comment]
LGTM- Tested on `gamma.dev` version 3.3.x on `analytics`, `configuration` and `about` pages.
