### ISSUE TITLE
Strange black bar appears on LHS when a restricted user doesn't have permission to create places

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4300]
Seen on beta.dev, logged in as a restricted user. Notice the black horizontal line across Nancy Ross Family:
![image](https://user-images.githubusercontent.com/1286381/37492198-bc9571c2-285d-11e8-926f-343d39fc6137.png)

We should either display an empty gray bar (similar to the mobile view) or the gray bar should be completely removed on both desktop and mobile. Here is a screenshot of mobile view, for reference:
![image](https://user-images.githubusercontent.com/1286381/37492260-efaff5e6-285d-11e8-9884-703eac0db6f8.png)

**Comment by garethbowen** [comment]
Merged and backported to `2.15.x`

**Comment by ngaruko** [comment]
LGTM
