### ISSUE TITLE
Make node version requirement of v8 and above mandatory

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4305]
We have decided to make this requirement just a warning at the moment until we finish working on v3 infrastructure.  Once that's done, we need to make the switch to throwing an error and making this a hard requirement.

**Comment by SCdF** [comment]
Commit to revert once Docker is in place: https://github.com/medic/medic-webapp/commit/79347fc7654e4bba3aedf3d8fbf8a1c9df96f9cb

**Comment by garethbowen** [comment]
Reverted in https://github.com/medic/medic-webapp/commit/3910822195e68bbd81ca44f0ba32155a5ee8f7fa

**Comment by ngaruko** [comment]
Tested in local environment : 

1. Installed old version of node : 6.9.4 (the Minimum  is 8:)
2. checked out the commit where the feature was disabled ([79347fc](https://github.com/medic/medic-webapp/commit/79347fc7654e4bba3aedf3d8fbf8a1c9df96f9cb))
3. Run `yarn start`
4. Deployment successful with warnings in `sentinel`: ``` Node version 6.9.4 is not supported, minimum is 8.0.0```

5. Check out `master` and run `yarn start`...
6. Error in logs : ```Fatal error initialising medic-api
 api.1      |  >> Error: Node version 6.9.4 is not supported, minimum is 8.0.0``` and ```Fatal error intialising medic-sentinel
 sentinel.1 |  Error: Node version 6.9.4 is not supported, minimum is 8.0.0```

LGTM but i am leaving this open for now  for @henokgetachew and the `DevOps` team to test this on docker with `alpha.dev`

**Comment by henokgetachew** [comment]
LGTM.  Since this was first caught in production where the version was less than 8, I'd say it's already been AT'ed.
