### ISSUE TITLE
Write integration tests against lineage

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4306]
Looking at a lot of the current unit tests for lineage, I'm not convinced they test what they say they are testing. In general these tests are very complicated as they require correctly mocking multiple ordered DB calls. For complete correctness they should also validate that the calls are actually the right ones (ie the query provides the right params),  which no / few tests do. For this reason it's also really hard to write new tests, because you have to walk the whole codebase and work out what to mock and when.

We need to be able to write integration tests for lineage. This is only complex because lineage relies on the ddocs existing:
 - Work out how to get the current ddocs in testing. This could be as simple as the tests actually understanding where they are in the file hierarchy and calling the code that generates the ddocs (once kanso is removed), and taking the resulting files off the fs and uploading them to a local PouchDB. This sounds gross, but is OK because testing!
 - The just write mocha tests that don't mock anything, and use a local PouchDB (in-memory is fine, or write to disk)

This would actually prove the code is working, as well as making sure if we ever change these views the code continues to work against them.

**Comment by SCdF** [comment]
Blocked on #3019. Once we have gotten rid of kanso I'm happy to take a crack at this.

**Comment by rmhowe** [comment]
This should include a test for https://github.com/medic/medic-webapp/pull/4366 (ticket was completed while the tests were still in a broken state)

**Comment by alxndrsn** [comment]
Kanso has been removed, so this ticket is ready to be worked on.

**Comment by garethbowen** [comment]
We also need to add a test to ensure #4523 doesn't affect `master` but the unit testing is currently broken. @rmhowe Could you please convert the test in [this commit](https://github.com/medic/medic-webapp/commit/98a8bf70be2f79440b14bc42f39c79bffeba2c5b) into an integration test as part of this work?

**Comment by rmhowe** [comment]
@garethbowen I added the test (which required some code changes) here https://github.com/medic/medic-webapp/pull/4501/commits/e1833b370e44b0a674b64b902b54f6e57c1124d8, this should hopefully be made redundant by this PR https://github.com/medic/medic-webapp/pull/4557

**Comment by ngaruko** [comment]
I assume these are unit and integration tests and the issue does not need AT-ing @SCdF ?

**Comment by rmhowe** [comment]
@ngaruko yep sorry I just put it in AT because I wasn't sure what the process was, as long as the tests are passing (ie the build is passing, which it is) then I think it's all good
