### ISSUE TITLE
"selection.formatted.content.raw" translation missing

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4325]
The translation key for raw SMS content seems to have changed [here](https://github.com/medic/medic-webapp/commit/f1ab8b867b8316c4c2126be40827a0fcfe840906#diff-05073942b188e28786b666486b9c6ca9R68) in 2.15 to `selection.formatted.content.raw`.

We can either revert the key name or update translations. Currently [`messages-en.properties`](https://github.com/medic/medic-webapp/blob/fa054f91e1a5a4ca42cdb2c14ed90c95d419d6a8/translations/messages-en.properties) has:
`selection.doc.content.raw = Raw report content`
`report.content.raw = Raw report content`

**Comment by rmhowe** [comment]
@garethbowen it looks like this translation key was updated by accident when all of the other `selection.doc`s (referring to `$scope.selection`) were changed? In that case it seems like we should just revert the key in the template to `selection.doc.content.raw` (unless changing the key to `selection.formatted` makes more semantic sense).

**Comment by garethbowen** [comment]
@rmhowe You're absolutely right - find and replace fail. I reckon revert the key in the template.

**Comment by garethbowen** [comment]
Merged and forward ported to `master`

**Comment by abbyad** [comment]
@ngaruko, I accidentally came across this and can confirm it looks good in `2.15.0-beta.2`.
