### ISSUE TITLE
Reports incorrectly filtered if filter changes before search returns

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4331]
If you use the form type filter in the Reports tab the results can include reports that should not be there.

To reproduce:
- Select an item from the form filter, wait for the results to be updated in the LHS
- Select a different item from the form filter **and deselect the item selected first before the results return**
- See that the reports list includes reports for the selected and un-selected form types:
![image](https://user-images.githubusercontent.com/789512/37928342-8a0e67a8-310a-11e8-91b1-9e5d9bcd8d82.png)

Tested on `beta.dev` running `2.15.0-beta.1`

**Comment by abbyad** [comment]
Still experiencing this, and it is quite annoying because the search results do not match what you've clicked. It is an easy situation to get into because you can easily select or deselect another item before the search results are returned.

**Comment by abbyad** [comment]
Seen on https://standard.dev.medicmobile.org running `2.18.0-beta.1`, and can be seen on any instance with enough data for search results to return slower than you can click another (or same) item.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma.de` v3.3
