### ISSUE TITLE
Move sms-specific views into medic-sms ddoc

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4367]
`medic-sms` ddoc introduced in #4110

**Comment by alxndrsn** [comment]
It's possible that we could separate the `shortcode` indexing from `medic-client/contacts_by_reference`... but then we may end up wanting a `medic-sms-client` ddoc down the road...

**Comment by alxndrsn** [comment]
`medic-client/messages_by_contact_date` is only used in the _Messages_ view.  This would be a good candidate for a `medic-client-sms` ddoc... except that it's only used by online users, so could just go straight into `medic` ddoc.

similar candidates:
* `medic-client/registered_patients`
* `medic-client/messages_by_contact_date`

**Comment by alxndrsn** [comment]
`medic/tasks_messages` looks like a prime candidate

**Comment by alxndrsn** [comment]
The cost of having unused views in `medic-client`, on the client-side, is minimal.  So removing sms-specific views from this ddoc probably isn't worth the effort.

`medic/tasks_messages` is moved to `medic-sms/tasks_messages` in #4408.

**Comment by ngaruko** [comment]
Does this need any AT? Any idea how to AT this @alxndrsn

**Comment by ngaruko** [comment]
LGTM. 
Tested on `alpha.dev` v 3.0.0
`sms-messages` and `tasks_messages`  moved to `medic-sms` ddoc
