### ISSUE TITLE
Report RHS action bar not updated for unknown/missing contact

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4371]
When a report submitter contact has been deleted or is not accessible (f.e. for a restricted user), the RHS action bar is not loaded/updated.
The result is either a missing action bar, when no other reports have been opened prior, either an action bar with actions pointing to the previously selected report.

**Comment by ngaruko** [comment]
Tested on `alpha.dev`
1. Created a new contact -- and assigned him/her/it a phone number
![image](https://user-images.githubusercontent.com/6979995/38905350-5211520a-4304-11e8-8306-eedc53035ff3.png)
2. Sent a report from that number
![image](https://user-images.githubusercontent.com/6979995/38905408-a9046b24-4304-11e8-92dd-14ef54d5db37.png)

3. observed the report was sent  
![image](https://user-images.githubusercontent.com/6979995/38905385-8f4a6dbe-4304-11e8-86ef-1cf13ac7b06a.png)

4. deleted the created 'contact'
![image](https://user-images.githubusercontent.com/6979995/38905419-be4aaae8-4304-11e8-8cf0-86d17cea36ca.png)
  5. Back to report page (needs a refresh/reload)
Observed that the report is still showing with `unknown sender` and both actions bars showing.
![image](https://user-images.githubusercontent.com/6979995/38905548-7bb29668-4305-11e8-92de-17dae870303f.png)

Please let me know if that's what you worked and tested @dianabarsan ?

**Comment by dianabarsan** [comment]
Yes, @ngaruko , the scenario is correct. Another thing worth verifying is that the RHS action bar edits the correct report. Thanks!
