### ISSUE TITLE
Cleared scheduled messages are not visible

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4388]
When scheduled messages are cleared they disappear, but should have remained visible.

![image](https://user-images.githubusercontent.com/789512/38499785-a1cb5b04-3bd6-11e8-819d-d627bd02ae3a.png)

![image](https://user-images.githubusercontent.com/789512/38499827-c549c318-3bd6-11e8-9479-bf2dd7146c87.png)

Tested on beta.dev running `2.15.0-beta.4`.

Created as a new issue, but this could have been part of AT for https://github.com/medic/medic-webapp/issues/3627.

**Comment by SCdF** [comment]
Merged into master and backported into 2.15

**Comment by abbyad** [comment]
Seen this work well in `2.15.0-beta.8`. Moving to Ready.
