### ISSUE TITLE
Replace/move online_user_settings_by_id view with call to users db

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4403]
There is a view in the `medic` ddoc which is only used when a doc is deleted: `online_user_settings_by_id`.

This is not a frequent occurrence.

This view should either:

1. be deleted and replaced with an `allDocs()` call to the `_users` db, or
2. be moved out of the main `medic` ddoc and into e.g. `medic-sentinel` ddoc, or
3. be deleted and replaced with a call to `medic-client/doc_by_type`

**Comment by garethbowen** [comment]
This view has been deleted in [2.16.x](https://github.com/medic/medic-webapp/pull/4632/commits/32ab01e30b677151efa7321de1b8d0bf041b7b1c#diff-f67e868f449edebd4bf847800c170d36L343) and [master](https://github.com/medic/medic-webapp/pull/4624/commits/5b903e1cafe062f54412e82d938f2425f1f06697#diff-119d4f53e6e6d4c43df7135a4b57bcdeL1) as part of #3960
