### ISSUE TITLE
Some views are only used by sentinel

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4405]
Views which are currently only used by sentinel:

* `medic/reports_by_form_and_clinic`
* `medic/reports_by_form_year_month_clinic_id_reported_date`
* `medic/reports_by_form_year_week_clinic_id_reported_date`
* `medic/sent_reminders`

These could be moved into a specific `medic-sentinel` ddoc if deemed useful.

**Comment by SCdF** [comment]
There is no value in having a ddoc just for sentinel that I can think of.
