### ISSUE TITLE
Unable to access patient's CHW info from config

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4410]
As part of #3412 we should be able to access the patient's doc from transitions and scheduled messages, but that doesn't yet seem possible. This is needed to send auto replies and scheduled messages to the patient's CHW, even if the report was submitted by someone else (eg a nurse using the app or SMS). With app forms we can hardcode a CHW number, but from SMS this is not possible. Regardless, the hardcoded method is not ideal since the phone number could become stale -- the number should be determined when the message is ready to send, as per https://github.com/medic/medic-webapp/issues/3627.

Will add some sample configs to help make this clearer.

**Comment by abbyad** [comment]
Just to clarify existing terms... the "submitter" of the report is `doc.contact`, which is not necessarily the CHW. The "subject" of the report is a patient (`doc.fields.patient_id` or `doc.fields.patient_uuid`) or place. The CHW is the patient's parent place's contact. As far as I can tell there is no way to determine the CHW if they are not the submitter, which is the main problem for this issue.

Below are some sample configs that I'd expect to work. The field names used in `bool_expr` and `recipient` are used to demonstrate the concept... I am open to using different names for these (eg `subject.parent.contact.phone` could be `primary_contact.phone`). 

### Pregnancy form "P"'s `registrations`
_
```json
      "messages": [
        {
          "translation_key": "messages.p.report_accepted",
          "event_type": "report_accepted",
          "recipient": "reporting_unit"
        },
        {
          "translation_key": "messages.p.report_accepted",
          "event_type": "report_accepted",
          "recipient": "subject.parent.contact.phone",
          "bool_expr": "subject.parent.contact._id !== contact._id"
        }
      ]
```

### Visit form "V"'s `patient_reports`
_Similar to `registrations`
```json
      "messages": [
        {
          "translation_key": "messages.v.report_accepted",
          "event_type": "report_accepted",
          "recipient": "reporting_unit"
        },
        {
          "translation_key": "messages.v.report_accepted",
          "event_type": "report_accepted",
          "recipient": "subject.parent.contact.phone",
          "bool_expr": "subject.parent.contact._id !== contact._id"
        }
      ]
```

### Pregnancy form P's `schedules` (scheduled messages) 
```json
      "messages": [
        {
          "translation_key": "messages.schedule.anc.reminder",
          "group": 1,
          "offset": "12 weeks",
          "send_day": "monday",
          "send_time": "09:00",
          "recipient": "subject.parent.contact.phone"
        },
```

**Comment by garethbowen** [comment]
In 2.15.x it looks like we don't hydrate doc.patient contacts. Once this patch is fixed this sort of configuration should work...

```json
      "messages": [
        {
          "translation_key": "messages.schedule.anc.reminder",
          "group": 1,
          "offset": "12 weeks",
          "send_day": "monday",
          "send_time": "09:00",
          "recipient": "patient.parent.parent.contact.phone"
        },
```

**Comment by garethbowen** [comment]
It looks like `master` is unaffected so no forward port is required. I've copied the functional test forward to increase coverage.

**Comment by garethbowen** [comment]
For AT make sure this works on 2.15.0 (beta) and 3.0.0 (alpha) as the code is quite different between the two.

**Comment by abbyad** [comment]
Testing in `2.15.0-beta.5` and getting some weird results.

On beta.dev I am submitting `P 96738 10` from a patient's "nurse" +14165551597

## Registrations
Using `patient` is not possible and gives an error (shown below). The `registration` transition is after accept patient reports, which seems to be the one that adds `patient` to the doc.

### Config
```
      "messages": [
        {
          "translation_key": "messages.p.report_accepted",
          "event_type": "report_accepted",
          "recipient": "patient.parent.contact.phone",
          "bool_expr": "patient.parent.contact._id !== contact._id"
        }
      ]
```
### Error
```
2018-04-12T12:49:51.143Z - error:
evalmachine.<anonymous>:1
patient.parent.contact._id !== contact._id
^

2018-04-12T12:49:51.146Z - error: ReferenceError: patient is not defined
    at evalmachine.<anonymous>:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at Object.evalExpression (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/utils.js:305:8)
    at messageRelevant (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:85:20)
    at config.messages.forEach.msg (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:359:13)
    at Array.forEach (native)
    at getRegistrations (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/transitions/registration.js:358:23)
    at options.db.medic.view (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtc2VudGluZWw=/node_modules/medic-sentinel/lib/utils.js:256:7)
```
### Transitions
```json
  "transitions": {
    "default_responses": true,
    "update_clinics": true,
    "accept_patient_reports": true,
    "conditional_alerts": false,
    "update_sent_by": false,
    "registration": true,
    "update_notifications": true,
    "update_scheduled_reports": false,
    "multi_report_alerts": false,
    "update_sent_forms": false,
    "generate_patient_id_on_people": true
  },
```
## Scheduled messages
Removing the part that errors, the scheduled messages are generated, but all the following `recipient` values yield the reporting unit's phone number, [as seen here](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5a5298b0a308146efa4ab51d7473b471) ([doc](https://beta.dev.medicmobile.org/medic/5a5298b0a308146efa4ab51d7473b471)).
### Config
```json
      "messages": [
        {
          "translation_key": "messages.schedule.anc.reminder",
          "group": 1,
          "offset": "12 weeks",
          "send_day": "monday",
          "send_time": "09:00",
          "recipient": "patient.parent.contact.phone"          
        },
        {
          "translation_key": "messages.schedule.anc.followup",
          "group": 1,
          "offset": "13 weeks",
          "send_day": "monday",
          "send_time": "10:00",
          "recipient": "nonsense"
        },
        {
          "translation_key": "messages.schedule.anc.reminder",
          "group": 2,
          "offset": "24 weeks",
          "send_day": "monday",
          "send_time": "09:00",
          "recipient": "patient._id"
        },
        {
          "translation_key": "messages.schedule.anc.followup",
          "group": 2,
          "offset": "25 weeks",
          "send_day": "monday",
          "send_time": "10:00",
          "recipient": "patient.parent._id"
        },
        {
          "translation_key": "messages.schedule.anc.reminder",
          "group": 3,
          "offset": "32 weeks",
          "send_day": "monday",
          "send_time": "09:00",
          "recipient": "reporting_unit"
        },
```

**Comment by abbyad** [comment]
Just confirming that the auto replies for `patient_reports` work well, just like `registrations`

## Patient Reports

### Config
```json
      "messages": [
        {
          "translation_key": "messages.v.report_accepted",
          "event_type": "report_accepted",
          "recipient": "reporting_unit"
        },
        {
          "translation_key": "messages.generic.registration_not_found",
          "event_type": "registration_not_found",
          "recipient": "reporting_unit"
        },
        {
          "translation_key": "messages.v.report_accepted.chw_sms",
          "event_type": "report_accepted",
          "recipient": "patient.parent.contact.phone",
          "bool_expr": "doc.contact && doc.patient && doc.patient.parent && doc.patient.parent.contact && doc.patient.parent.contact._id !== doc.contact._id"
        }
      ]
```

### Result
On beta.dev with 2.15.0-beta.5 submitting `V 96738` from a patient's "nurse" +14165551597 [yields](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5a5298b0a308146efa4ab51d74767c3b):

![image](https://user-images.githubusercontent.com/789512/38704859-a87b154c-3e75-11e8-8929-2e0f1a168828.png)

**Comment by abbyad** [comment]
I am still unable to get a scheduled message to go to the CHW when [sending a SMS as a Nurse](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5a5298b0a308146efa4ab51d74795ca9).

The [getRecipient function](https://github.com/medic/medic-webapp/blob/2.15.x/sentinel/lib/message-utils.js#L74-L103) seems to be relevant here, from which I tried:

| recipient | comment|
|---|---|
|**`reporting_unit`** | sender's phone... which works, but can't be used to send to CHW when Nurse is the sender. |
|**`clinic`** | primary contact for the "clinic" in the sender's lineage. Nurses are at a higher level of the hierarchy, so this would default out. |
|**`parent`** | primary contact for the "health_center" in the sender's lineage. _You can be your own `parent` if you if you are the primary contact of a health_center, as is the case for our nurse example._|
|**`grandparent`** | primary contact for the "district_hospital" in the sender's lineage.|
|**`patient.parent.contact.phone`** | **I would expect this to get the primary contact for the patient (ie the CHW), but returns the default.**|
|**`doc.patient.parent.contact.phone`**| desperate attempt, but also returns the default.|
|**`patient.contact.phone`**| another desperate and failed attempt returning default.|

Perhaps there is another field I should be accessing, but it looks like all of the phone numbers obtained are relative to the sender (`doc.contact`), instead of being relative to the patient (the ephemeral `doc.patient`) -- which is what we want in this case.

**Comment by abbyad** [comment]
I am still struggling to get this to work. Some of the failed tests could have been from irregular contacts (eg a primary contact that did not have a parent). I have now tested with a completely new district, health center, clinic and contacts, and still cannot get a scheduled message sent to the clinic contact (eg CHW) when the report was submitted by the health center contact (eg Nurse).

A recent example report sent by a nurse can be found [here](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5a5298b0a308146efa4ab51d747bf457) ([doc](https://beta.dev.medicmobile.org/medic/5a5298b0a308146efa4ab51d747bf457)). The only recipient number that is not the same as the sender is `grandparent`.

Another example sent by a non-contact can be found [here](https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5a5298b0a308146efa4ab51d747bfad1) ([doc](https://beta.dev.medicmobile.org/medic/5a5298b0a308146efa4ab51d747bfad1)). This example is not exactly the primary use case we were designing for, and although a viable use case, is used here mainly to test when the sender is not someone in the lineage (eg sender number is not the same as `parent`). In this case we can see that the only recipient which doesn't default to the sender is `parent` and `grandparent`, meaning that **`clinic` and `clinic.contact.phone` still incorrectly default to the sender.**

**Comment by abbyad** [comment]
Now testing on `2.15.0-beta.9` and it seems to be working properly. When a nurse at the `health_center` level submits a report about a patient at the `clinic` level a scheduled SMS goes to a patient's CHW. This is done using `"recipient":"clinic.contact.phone"`.

The scheduled messages default to the sender in other scenarios that I thought would work (eg a CHW submitting about a patient in another Area), but I don't think that that is required as part of 2.15. We may choose to fix all of these `recipient` relationships when we take on https://github.com/medic/medic-webapp/issues/3639.

I will add observed behaviour in this issue as I continue to AT so that we can document accordingly.

**Comment by abbyad** [comment]
I tested on `2.15.0-beta.9` sending a report from 16 possible relationship with respect to the patient: whether the sender is in same `clinic`, `health_center`, and `district`, or not, and whether the sender is a primary contact or not. The results are listed in the table below for various `recipient` values for scheduled messages in the Reports tab. Due to #4453, these are all as `scheduled` and we can't tell if the messages would actually go to the right person. We therefore need to confirm the results once messages go to `pending`. We also need to repeat these tests in `3.0`.

Although it doesn't always work as I would have expected, it does for a person in the same `clinic` as the patient (eg the patient's CHW), and a person as the same `health_center` as the patient (eg a Nurse). **This means that it works fine our intended use, but not universally.** We can make this work universally when we revisit it as part of #3639, when we allow configuration of more hierarchy levels.

| recipient | behaviour |
|---|---|
|**`reporting_unit`** | Always the sender's phone number. |
|**`clinic`** | The primary contact for the `clinic` in the **sender's** lineage. _**Exceptions**: If there is no `clinic` in the lineage it defaults to the sender._ |
|**`parent`** | The primary contact for the `health_center` in the **sender's** lineage.  _**Exceptions**: If there is no `health_center` in the lineage it defaults to the sender. Also defaults to sender when sender's parent is a `health_center` or `district_hospital` in a different `district_hospital` than the patient AND they are not their place's primary contact._ |
|**`grandparent`** | The primary contact for the `district_hospital` in the **sender's** lineage. _**Exception**: If there is no `district_hospital` in the lineage it defaults to the sender. Also defaults to sender when sender's parent is a `health_center` or `district_hospital` in a different `district_hospital` than the patient AND they are not their place's primary contact._  |
|**`clinic.contact.phone`** | The patient's CHW's phone. **_Exceptions**: if sender is associated to a different `clinic` in the _same_ `district` will go to primary contact of the person's `clinic`. Goes to the patient's CHW if the sender is associated to a `health_center` or a `clinic` in a _different_ `district`._ |
|**`patient.phone`**| Always the phone number associated to the patient, but only if it is set before the report was received. |
|**`unknown_field`** or ` ` (blank) | Always the sender. |


**Notes for when we revisit this:**
- We should consider not defaulting to the sender. The messages that would go to them may not make sense, and may in fact be inappropriate to go to the sender.
- We should be able to access contacts for each level relative to the sender, and relative to the patient.

**Notes for further acceptance testing:**
- Set up places with contacts so that it is easy to determine their place in the hierarchy. For example, I used the last four digits to specify the district, health center, clinic, and whether or not they are a primary contact.
- Use the [load_messages.js](https://github.com/medic/medic-webapp/blob/master/scripts/load_messages.js) script to send multiple test cases. Eg:
```csv
message, from
P 90645 10, +16135551111
P 90645 10, +16135551110
P 90645 10, +16135551121
P 90645 10, +16135551120
P 90645 10, +16135551101
P 90645 10, +16135551100
P 90645 10, +16135551200
P 90645 10, +16135551211
P 90645 10, +16135552110
P 90645 10, +16135552100
P 90645 10, +16135552101
P 90645 10, +16135551001
P 90645 10, +16135551000
P 90645 10, +16135552000
P 90645 10, +16135550000
P 90645 10, +16135555555
```
- Make sure the schedule is not cleared when further reports come in so that you can test both the `scheduled` number and the actual number, since these are done by different pieces of code. 
- Use a schedule that tests various `recipient` values. Eg:
```json
    {
      "name": "ANC Reminders LMP",
      "translation_key": "schedule.anc_lmp",
      "summary": "",
      "description": "",
      "start_from": "reported_date",
      "messages": [
        {
          "message": [
            {
              "content": "This message will go to the 'reporting_unit'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "1 minutes",
          "recipient": "reporting_unit"          
        },
        {
          "message": [
            {
              "content": "This message will go to the 'clinic'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "2 minutes",
          "recipient": "clinic"
        },
        {
          "message": [
            {
              "content": "This message will go to the 'parent'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "3 minutes",
          "recipient": "parent"
        },
        {
          "message": [
            {
              "content": "This message will go to the 'grandparent'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "4 minutes",
          "recipient": "grandparent"
        },
        {
          "message": [
            {
              "content": "This message will go to the 'clinic.contact.phone'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "5 minutes",
          "recipient": "clinic.contact.phone"
        },
        {
          "message": [
            {
              "content": "This message will go to the 'patient.phone'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "6 minutes",
          "recipient": "patient.phone"
        },
        {
          "message": [
            {
              "content": "This message will go to the 'unknown_field'",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "7 minutes",
          "recipient": "unknown_field"
        },
        {
          "message": [
            {
              "content": "This message will go to the ''",
              "locale": "en"
            }
          ],
          "group": 1,
          "offset": "8 minutes",
          "recipient": ""
        }
      ]
    }
```

**Comment by abbyad** [comment]
AT blocked on https://github.com/medic/medic-webapp/issues/4453

**Comment by abbyad** [comment]
This is working well in `2.15.0-beta.11` with configuration from https://github.com/medic/medic-webapp/issues/4410#issuecomment-383096110.

@ngaruko can you AT in 3.x?

**Comment by sglangevin** [comment]
Adding a note here that we've since updated the aliases so that `clinic`, `health_center`, and `district` are now based off of the patient, not the CHW. So the config in https://github.com/medic/medic-webapp/issues/4410#issuecomment-383096110 could be updated to reflect this.
