### ISSUE TITLE
Make a shared library for message utils

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4420]
[sentinel](https://github.com/medic/medic-webapp/blob/master/sentinel/lib/message-utils.js) and [webapp](https://github.com/medic/medic-webapp/blob/master/static/js/modules/message-utils.js) have identical modules with message utilities and even a message saying they should be split out in to a shared library. Now's the time!

**Comment by alxndrsn** [comment]
Api also has a `message-utils.js`... which is very different!

**Comment by ngaruko** [comment]
do we need to AT this @garethbowen ?

**Comment by garethbowen** [comment]
Make sure messages (scheduled and replies) are correctly generated in sentinel and the UI. This includes the recipient and the message itself.

**Comment by ngaruko** [comment]
Do you think [issue raised](https://github.com/medic/medic-webapp/issues/4284#issuecomment-406601774) by @newtewt  in #4284 has anything to do with this @garethbowen ?

**Comment by garethbowen** [comment]
No I don't think so. We probably only need one issue to cover that bug so if there's nothing else wrong with this I'd vote close this issue and leave #4284 to track the bug.
