### ISSUE TITLE
Closing add contact from LHS goes to CHW area on RHS on mobile

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4444]
2.13.x, a CHW on mobile, LGU configuration.

Replicate:
 - Go to people list
- Tap add family
- Once the add family form as loaded tap the X
- Note that it's really trying to load something
- Note that now your *area* that was loading, not the default search, which is really weird and wrong

What should have happened is the contact list should have loaded again.

**Comment by sglangevin** [comment]
This is a long-time existing issue. My vote is to leave it and fix it when we do the nav update.

**Comment by SCdF** [comment]
@sglangevin can I argue for doing it or #4445 sooner? When you combine this with #4445 it means that backing out of a form that you entered via the people tab takes *minutes* to complete (on a phone), and there is no UI that lets you navigate anywhere else (you only see a throbber).

**Comment by sglangevin** [comment]
That's a good point - I'd rather do #4445 as that seems to be a more important issue in terms of the user experience. However, we could also just do whichever one is easier. Have you investigated to see which one is simpler?

**Comment by SCdF** [comment]
I haven't looked into it, I imagine neither of them should be that challenging. Presumably for #4445 we'd change it to load 10 families with a load more button that loads the rest

**Comment by sglangevin** [comment]
Adding some sort of button would involve us having to change the design of the page. Perhaps it's better to do this issue instead so that we don't land back on the CHW area page.

**Comment by rmhowe** [comment]
@SCdF @sglangevin looks like this has roughly ended up in the timeline to go in with the nav update anyway, put it in 3.1?

**Comment by SCdF** [comment]
Worst case we should definitely make sure this is done in 3.1.

**BUT**, due to the performance issues noted here https://github.com/medic/medic-webapp/issues/4444#issuecomment-384169512 I'd really like us to fix it or the other ticket before then. I have no idea if people encounter this in production much but if they do it's hella terrible.

**Comment by rmhowe** [comment]
It looks like https://github.com/medic/medic-webapp/issues/4445 is the bigger issue here so I'd say that one should be fixed first, then this issue becomes a minor UI bug for 3.1

**Comment by ngaruko** [comment]
LGTM. Tested on `gamma.dev`... v3.1.0
