### ISSUE TITLE
Loading a CHW area is really slow

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4445]
Loading a CHW area takes 10s of seconds on a reasonable phone. I imagine this is proportionate to the number of families that CHW has. It's not clear if this is just how it is, or if we're doing something inefficient.

Perhaps we shouldn't render every single family under the area in the UI straight away.

For reference:
 - loading a random family: ~2.5 seconds
 - loading their area: ~30 seconds

**Comment by kennsippell** [comment]
So this is the Application-Database interactions for loading the contacts tab: 

##*"Contacts" - Left-Panel*
1. Get org.couchdb.user:adamayo doc for the facility_id 
2. Get facility doc associated with user's facility_id 
3. Get all the contacts associated with the facility_id 
PAINT THE CONTACTS PAGE WITH SPINNERS 
4. Query(contact_by_type) for type "clinic" > Returns 40 "clinics" 
5. Get documents of all clinics (max 50 paginated) 
6. Get documents clinic's primary contact (40) 
PAINT THE LEFT PANEL 

##*"Contact-Content" - Right-Panel*

1. Get org.couchdb.user:adamayo doc for the facility_id 
If mobile, stop 
2. Query for docs_by_id_lineage for selected clinic. Returns clinic document and area doc document. 
3. Hydrate the contacts into these facility docs. Gets selected clinic contact document and area contact document.
4. Query for contacts_by_parent for the selected clinic. Gets all children's full docs.
PAINT RIGHT PANEL WITH SPINNER 
XmlForms – Queries for org.couchdb.user:adamayo doc again 
PAINT RIGHT PANEL FRAMED WITH SECTIONS AND SPINNERS 
5. Query for docs_by_id_lineage for primary contact of selected facility's area (in parallel with contact_by_parent). Returns the area contact full doc and area contact full doc.
6. Fetch document of clinic's primary contact to sort it to top
7. Fetch contacts information for all of the children.contact  (unsure what this data is used for? Empty in my scenarios) 
PAINT CHILDREN (after 4982)
8. Query reports_by_subject passing in the ids of all children. 
9. Look up the docs for all the reports 
PAINT THE REPORTS 


Things are pretty good for the left panel. Things are more complicated here and my understanding is a bit rough. That said, here are some unknown-value potential optimizations ideas:

1. We could paint the left panel between steps 5-6 and lazy load the primary contacts. Some potential value for high-doc users like Muso. I can attempt to measure this. 
1. Result for Left-panel step 3 is only used in the rare case where the clinic isn't already in the list (>50 clinics). Not a major win. 
1. Adjusting when we paint right panel seems like a big win here. Alxndrsn's #4982 
1. The data fetched in right-panel step 6 was already fetched in step 4. Can we consolidate? 
1. I'm expecting that debouncing should cancel existing loading content? If I rapidly click on 3 clinics, I see the Reports view finish 3 times. So I suspect debouncing maybe doesn't do what I expect, or isn't working as well as it could. 
1. All together, this tab is fetching org.couchdb.user:adamayo 3 times. I assume this document has very low churn and may be safe to cache UserSettings() lookups in a similar style to Settings() or Auth() lookups.

**Comment by garethbowen** [comment]
@kennsippell Good write up, thanks!

What version did you do this analysis on? There have been improvements made between the version MUSO is on and the latest and greatest, eg: #4669

Point 3: Do you mean "R9" and "R8"?

**Comment by kennsippell** [comment]
@gartehbowen This is on master. Since Muso has a concrete timeline to get 3.2. 
Yes I did! Edited in place.

**Comment by garethbowen** [comment]
I like the idea of dropping the primary contact information from the LHS and RHS but this will need to be discussed with design if this is feasible or not.

Consolidation of data fetching is another one I like. Some of these decisions were made so we could have reuse of the services but we may be able to include additional parameters to keep information from being thrown away or we may have to drop the idea of reuse in favour of performance.

I'm also wondering if we could hide the Children, Reports, and Tasks sections of the Contacts RHS in an accordion (or similar) and only fetch the data when the accordion is expanded.

I wouldn't worry too much about tablets as they're not very common in the field and they generally have a bit more grunt anyway - prioritise the phone experience for now.

**Comment by garethbowen** [comment]
@alxndrsn Did you have anything outstanding to commit against this issue, or can we close as @kennsippell suggests?
