### ISSUE TITLE
On an empty database loading the contact list crashes

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4449]
See this code: https://github.com/medic/medic-webapp/blob/da0ec7a4bce7c5d4c06bb8daa0441e3aa600b4f0/static/js/services/contact-view-model-generator.js#L177L193

`model.doc` doesn't exist yet.

This gets resolved once you add the first District Hospital or whatever.

In both master and at least as far back as 2.13.x

**Comment by SCdF** [comment]
@abbyad I think unless it turns out to be really hard we should just fix it for completeness. I don't think it's a big enough deal to backport it anywhere though

**Comment by abbyad** [comment]
@sglangevin what release/project would you like this to go to?

**Comment by sglangevin** [comment]
It doesn't sound like it's a big priority so I'd do it later, 3.1 or beyond. I don't think we should be adding anything that isn't critical to 3.0 at this point.

**Comment by garethbowen** [comment]
Agreed. Scheduled for 3.1

**Comment by kennsippell** [comment]
Is this a code quality issue or is there a crashing scenario? I've been unable to crash any of the contact/reporting views with an empty database. Steps to repro would be super helpful.

**Comment by garethbowen** [comment]
Looking through the code I don't think it should get this far if no doc is found (the line before it now throws). It would be strange if we try to build a model before anything has been selected on the LHS.

@SCdF How good is your memory?

**Comment by SCdF** [comment]
@garethbowen / @kennsippell it may be that the code has been refactored such that we can't get here anymore. The original issue is that the left hand side code would select the "first" contact (which didn't exist). It looks probable that we have refactored our way out of this situation.

We can reopen if we find it again!
