### ISSUE TITLE
Contact and Messages exports not working

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4455]
The export functionality from the Configuration pages is not working in beta.dev running `2.15.0-beta.9`. Export of contacts gives a blank json file. Export of messages or reports yields nothing, and the server becomes non-responsive. @henokgetachew can you post what you were seeing on the server?

@sglangevin, according to @SCdF this fixed in 3.0, so we need to determine if the priority can be lowered for 2.15. In the meantime it has been listed as blocking the release.

**Comment by garethbowen** [comment]
Messages is throwing this exception:

```
2018-04-24T01:13:44.198Z - info: 127.0.0.1 - - [24/Apr/2018:01:13:44 +0000] "GET /medic-user-admin-meta/_changes?include_docs=true&feed=longpoll&heartbeat=10000&since=992&limit=25 HTTP/1.0" - - "https://beta.dev.medicmobile.org/medic/_design/medic/_rewrite/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
 
2018-04-24T01:13:44.528Z - error: UNCAUGHT EXCEPTION!
 
2018-04-24T01:13:44.531Z - error: Server error:
 { Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/node_modules/express/lib/response.js:170:12)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/export-data.js:77:15
    at outputToJson (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/export-data.js:474:3)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/export-data.js:679:9
    at err (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/export-data.js:607:43)
    at hydrate (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/export-data.js:592:3)
    at getRecordsFti (/srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/services/export-data.js:607:7)
    at /srv/storage/gardener/data/working_dir/aHR0cDovL2xvY2FsaG9zdDo1OTg0L21lZGljL19kZXNpZ24vbWVkaWMvbWVkaWMtYXBp/node_modules/medic-api/controllers/fti.js:86:7
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true }
```

**Comment by garethbowen** [comment]
The exception is the same for contacts.

**Comment by garethbowen** [comment]
Code review please @SCdF 

As far as I can tell this only affects 2.15 as 2.14 has the old non-streaming code and 3.0 has only the streaming option.

**Comment by abbyad** [comment]
When I tried exporting messages on [beta-old.dev](https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/export/messages) running `2.15.0-beta.11` I got a 504, and an unresponsive server. Since the server is unresponsive I haven't yet gotten around to exporting contacts.

**Comment by garethbowen** [comment]
> And while we are on this, in the new api documentation , there is a mixture of /api/v1/ and api/v2, is that intentional @garethbowen ?

Yes. They're just numbers. They don't have to all be the same, or every time we wanted to have a new version of an API everyone would have to change all the URLs they've configured.

**Comment by garethbowen** [comment]
@abbyad Can you attach the logs please?

**Comment by garethbowen** [comment]
api eventually fails out of memory:

```
2018-05-01T02:37:58.086Z - info: 
<--- Last few GCs --->

 1204495 ms: Mark-sweep 1376.2 (1437.6) -> 1376.2 (1437.6) MB, 5141.1 / 0.0 ms [allocation failure] [GC in old space requested].
 1210611 ms: Mark-sweep 1376.2 (1437.6) -> 1376.1 (1437.6) MB, 6115.7 / 0.0 ms [allocation failure] [GC in old space requested].
 1216160 ms: Mark-sweep 1376.1 (1437.6) -> 1386.7 (1421.6) MB, 5549.6 / 0.0 ms [last resort gc].
 1221546 ms: Mark-sweep 1386.7 (1421.6) -> 1397.4 (1421.6) MB, 5385.9 / 0.0 ms [last resort gc].

 
2018-05-01T02:37:58.090Z - info: 
<--- JS stacktrace --->

==== JS stack trace =========================================

    2: arguments adaptor frame: 3->1
Security context: 0x705101ecfb51 <JS Object>
    3: InnerArrayFind(aka InnerArrayFind) [native array.js:~1215] [pc=0x7051029e8d89] (this=0x705101e04381 <undefined>,bB=0x7050f1ca8501 <JS Function contactRows.find.contactRow (SharedFunctionInfo 0x7050e580fda9)>,bC=0x705101e04381 <undefined>,w=0x7050e580f429 <JS Array[5699]>,x=5699)
    4: find [native array.js:~1227] [pc=0x7051029e8878] (this=0x7050e580f...

 
2018-05-01T02:37:58.090Z - error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 
2018-05-01T02:37:58.109Z - error:  1: node::Abort() [/srv/software/medic-core/v1.7.1/x64/bin/node]
 2: 0xe2776c [/srv/software/medic-core/v1.7.1/x64/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/srv/software/medic-core/v1.7.1/x64/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/srv/software/medic-core/v1.7.1/x64/bin/node]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/srv/software/medic-core/v1.7.1/x64/bin/node]
 6: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [/srv/software/medic-core/v1.7.1/x64/bin/node]
 7: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::CompilationInfo*) [/srv/software/medic-core/v1.7.1/x64/bin/node]
 8: v8::internal::LChunk::Codegen() [/srv/software/medic-core/v1.7.1/x64/bin/node]
 9: v8::internal::OptimizedCompileJob::GenerateCode() [/srv/software/medic-core/v1.7.1/x64/bin/node]
10: v8::internal::Compiler::FinalizeOptimizedCompileJob(v8::internal::OptimizedCompileJob*) [/srv/software/medic-core/v1.7.1/x64/bin/node]
11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/srv/software/medic-core/v1.7.1/x64/bin/node]
12: v8::internal::Runtime_TryInstallOptimizedCode(int, v8::internal::Object**, v8::internal::Isolate*) [/srv/software/medic-core/v1.7.1/x64/bin/node]
13: 0x7051026092a7
```

**Comment by garethbowen** [comment]
@abbyad It's failing at an impossible place, so I think it's literally just running out of memory. 3.0 solves this properly by implementing streaming but this would be impossible to backport without breaking api compatibility... The options I can see are:

1. Ignore this issue - it only happens when exporting loads of records, it's fixed in 3.0, and it existed in previous versions. We can mark it as a known issue and move on.
2. Limit the messages returned to the 1000 (or so) latest. This means people can't take down api but it won't be clear you're not getting everything.
3. Backport the 3.0 fix and break the existing API.
4. Do some serious work and reduce the memory usage without breaking the API.

I vote for 2. What do you think?

**Comment by sglangevin** [comment]
I also vote for 2, FWIW. Or we could do something similar to what we're doing for downloading Reports in 2.15? Not sure if that is relevant.

**Comment by garethbowen** [comment]
> Right now export of Contacts downloads a json file on beta-old.dev running 2.15.0-beta.11, but that file appears limited to 100 contacts. I've added new contacts and the redownloaded the file and it still has 100 contacts. Is it because we already implemented a limit there?

It's probably because I hacked it in while testing the solution...

**Comment by garethbowen** [comment]
There's an existing issue for exporting server logs: #4211

**Comment by garethbowen** [comment]
Merged into `2.15.x`

**Comment by ngaruko** [comment]
This seems to work on my 'local' at the moment. Please check with the instance where you saw errors @abbyad and feel free to close if it works there.

**Comment by abbyad** [comment]
Thanks guys, will test in hosted instance when this hits the next beta build.

**Comment by abbyad** [comment]
Export of reports seems to work well in 2.15.0-beta.12 on beta.dev. Export of contacts gives a 500 on beta.dev... @browndav checked and it is because it is running couch 2.1.1 and Lucene has been removed. (Similarly export of logs is not working, because of another component that was removed. All other exports seem to work)

We can do further testing on a fresh instance with Lucene, or move this to Ready given that export of Reports succeeded, export of Contacts succeeded locally for @ngaruko, and that the failure mode on a production instance even without Lucene is not catastrophic. @garethbowen do you think the latter is appropriate in this case?

**Comment by browndav** [comment]
If we need to run versions prior to 3.0 on the CouchDB 2.1.1 on the new Docker infrastructure in production due to business/cost/tenancy constraints, we should be able to branch from Medic OS `dev`, revert two PRs, and produce a `-lucene` tagged Docker image fairly trivially.

**Comment by garethbowen** [comment]
@abbyad I think this needs to be tested on the actual infrastructure we'll be deploying on (eg: CouchDB 1, non-Docker, older medic-os). You should be able to test on beta-old.dev.medicmobile.org.

**Comment by ngaruko** [comment]
It looks like the deployment of some test instances has gone quite convoluted (ie right combination of couchDB, docker, horti and good-old dashboard!). For this one, the `export` seems to work as expected on old beta but not on the new beta. Will leave this one for @abbyad to do final checks and confirm what is the desired or expected behaviour.

**Comment by browndav** [comment]
We discussed the new beta.dev issue at stand yesterday IIRC – Lucene and the log printing utility were intentionally removed in the v3.0 infrastructure via two PRs.

**Comment by abbyad** [comment]
The export of _Messages_ and _Contacts_ works on `beta-old.dev` running `2.15.0-beta.13`, as do _Reports_, _User Feedback_ and _Audit Log_. The export of _Server Logs_ gives a 502 but doesn't bring the instance down. That is expected and acceptable as discussed in https://github.com/medic/medic-webapp/issues/4211.

Moving to Ready.
