### ISSUE TITLE
Configuration app, checkboxes don't render right

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4462]
To replicate:
 - Load up the users view.
 - This should have check boxes when a user has a facility or a person.
 - Instead, it's everyone's favourite tofu box

I think other things aren't rendering right either. Everything looks slightly weird but I can't put my finger on it, and haven't done a side-by-side comparison.

**Comment by garethbowen** [comment]
It's 404ing on font awesome so that makes sense. It's probably a bug introduced by the repo refactor.

**Comment by garethbowen** [comment]
Fixed: https://github.com/medic/medic-webapp/commit/3fb390edb239b8243e91267f02e680e1e83bd9c5

**Comment by ngaruko** [comment]
Just to make sure I understand this issue, are we talking about `medic/_design/medic-admin/_rewrite/#/users`?  For a start, the whole `Medic Mobile administration console` seems to need a bit of UI touch up...(unless fonts are not rendering in my browser!)
![image](https://user-images.githubusercontent.com/6979995/39459191-d8e49f46-4d4d-11e8-9f03-d863f58901f7.png)
Then the `users` view does not seem to have any checkbox either.
![image](https://user-images.githubusercontent.com/6979995/39459315-b2e207d8-4d4e-11e8-99dd-0b63511fa613.png)
 Is this the issue you raised @SCdF ?

**Comment by SCdF** [comment]
@ngaruko this is the UI yep. The whole UI going through design is a separate conversation I'm sure, I just raised the bits that I saw were obviously broken when I used it for the first time.

**Comment by sglangevin** [comment]
Looks like the issue at hand is fixed (checkmarks are appearing). We are not doing any work on the UI for this release, that will come later.
