### ISSUE TITLE
Configuration app, horticulturalist upgrade page no longer blocks if you aren't using horti

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4463]
Previously, if you went to the upgrade page and you weren't running on a build deployed by horti it would hide that page saying you could only upgrade from horti. Now, it always shows.

This matters a little less because everyone on 3.0 will be on horti, but it will be weird for local deploys, so idk, maybe we want to keep it. At the very least we want to clean up the top part of the page so it's clear, as right now it's just a bunch of blank statements.

**Comment by garethbowen** [comment]
Possibly this is only true for development. I think the UI code is still there it's just how we're building the ddoc that's changed.

**Comment by SCdF** [comment]
This happened because some code was accidentally commit. Fixed in https://github.com/medic/medic-webapp/commit/644bbbe0be57f5339efe9f0492aeb79fa4d4d5d8
