### ISSUE TITLE
Doc conflict when converting old sentinel info docs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4465]
I'm getting unhandled promise rejections when converting old sentinel info docs stored in the medic db into new ones stored in the sentinel db.

I can't include the stacktrace because I've fixed it locally, just trust me  :grinning:

**Comment by garethbowen** [comment]
Code review please @vimemo

**Comment by ngaruko** [comment]
Do we need to AT this @garethbowen ?

**Comment by garethbowen** [comment]
@ngaruko Yes, definitely. Make sure when updating to a recent alpha that the `-info` docs are migrated correctly into the sentinel db without errors in the sentinel log.

**Comment by ngaruko** [comment]
Tested on `alpha.dev`.
`medic-sentinel` before upgrade
![image](https://user-images.githubusercontent.com/6979995/41697427-cd640840-756c-11e8-97e3-dc846a5cf98f.png)

after upgrade.
![image](https://user-images.githubusercontent.com/6979995/41697692-feb8128c-756d-11e8-84d9-552992b92822.png)

No error in the sentinel log
