### ISSUE TITLE
2.14.x release versions are not tagged in medic-api repository

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4471]

**Comment by SCdF** [comment]
Almost no releases are, in either medic-api or medic-sentinel.

**Comment by alxndrsn** [comment]
...and now they all are.  There are a couple of legacy tags which appear to be incorrect:
* `api` `2.10.3`
* `api` `2.12.1`
* `sentinel` `2.12.0-beta.5`

**Comment by garethbowen** [comment]
Not sure what to review here. I'm sure it's fine.
