### ISSUE TITLE
Date formatting causes data loss 

### ISSUE THREAD

**Issue by nomulex** [medic/medic-webapp#4474]
When the  "%b %e, %Y" date format is used, the resulting display shows a one week difference. Please see pictures below. 
![image](https://user-images.githubusercontent.com/3070004/39259046-29f81de8-48be-11e8-9e65-40a93b6be32c.png)
![image 1](https://user-images.githubusercontent.com/3070004/39259045-29b5f59e-48be-11e8-817c-d047c5b39d2d.png)

**Comment by abbyad** [comment]
Hi @nomulex, can you provide a minimal XForm showing this behaviour? That will help us reproduce the error, and eventually use it to test the fix.

**Comment by nomulex** [comment]
@abbyad  i have failed to reproduce this. I will close it for now.
