### ISSUE TITLE
Limit the size of feedback docs

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4481]
Feedback docs can be arbitrarily large because we take the last 10 logs and stringify them out, which could be debug logs from PouchDB, which could be logging that someone accessed the ddoc…

We should limit the length of each log line to something sensible.

**Comment by rmhowe** [comment]
@SCdF this sounds sensible, not sure what feedback docs are though. Low priority for 3.1?

**Comment by SCdF** [comment]
Sounds right to me.

FYI, feedback docs are generated by two things:
 - A user clicks Report Bug in the hamburger menu[1] and types some stuff in
 - A error is generated on someone's phone

[1] Why is there no emoji / symbol for the hamburger menu!?!? This is an outrage. We have ㆔ which is close, and Ⅲ which is better but the wrong way around, and you could just do ||| if you really wanted to. If you are outraged as I am contact your local unicode representative now!

**Comment by garethbowen** [comment]
Increase priority due to reports from the field.

**Comment by vimemo** [comment]
Testing instructions:
Logs can be found here:
Configuration > Import & Export > User feedback

We have user entered feedback and pouch db automated logs with the following json format:
{message:'', file:'', line:1}. This ticket limits the message in the json logs
 to 120 characters.

**Comment by ngaruko** [comment]
The `Export User Feedback` call comes back with a network error. No errors in the console but looking at the logs, it  looks like the request expect a xml rather than a json. Would that be the reason @vimago @garethbowen ?
```
[2018-07-19 00:40:40] REQ 23c9e9de-6bc5-4b2b-825b-5c2aac5aa1a1 ::ffff:10.16.19.40 - GET /api/v1/export/feedback?format=xml&locale=en HTTP/1.1
```

**Comment by vimemo** [comment]
@ngaruko, I am not sure that the actual export is part of this ticket. It was probably broken before. @SCdF, do you know if this what you intended with this ticket. The implementation limits the size of the messages (display) but never tested the actual export.

**Comment by SCdF** [comment]
@vimemo / @ngaruko that definitely sounds like another ticket, even if (IMO) this ticket caused the export to fail (which sounds massively unlikely).

My suggestion would be: close this ticket (if that's the only problem) and raise a new one about exporting. On that we can have a discussion with our users to see if anyone actually uses it (I know people use feedback but I don't think it's through that export), and based on that information either fix the export or just delete it, and have one less feature to support.

**Comment by ngaruko** [comment]
Tested in `alpha.dev` by modifying the `info` field of one of user created logs in the [feedback ](https://alpha.dev.medicmobile.org/_utils/#/database/medic/_design/medic-client/_view/feedback)view to look like 
```  "info": {
    "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
  }, ```
Back to the UI, I observed that the message was shorted to ``` {"message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq..."} ``` 
![image](https://user-images.githubusercontent.com/6979995/43617120-46c341ec-9714-11e8-875a-6ef5db238456.png)

Thanks @vimago
