### ISSUE TITLE
Does view ordering matter for re-generating views?

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4485]
Let's imagine you have a ddoc:

```json
{
  "view": {
    "foo": {"map": "foomap"},
    "bar": {"map": "barmap"},
  }
}
```

And then we change that ddoc to be:

```json
{
  "view": {
    "bar": {"map": "barmap"},
    "foo": {"map": "foomap"},
  }
}
```

I am worried that in CouchDB (and perhaps in PouchDB) this change would result in the views being regenerated.

We should test this in couch and pouch.

This is really important for us, because I've noticed that the tooling we use to generate ddocs does not appear to be consistent in its ordering, which could cause unneeded view regenerations.

**Comment by sglangevin** [comment]
@SCdF I'm not sure how to proceed with this one - any suggestions?

**Comment by SCdF** [comment]
Thanks for the reminder! Let me do it now, it should only take a few minutes to work out if it's a problem or not

**Comment by SCdF** [comment]
It matters not!
