### ISSUE TITLE
[standard] Change language setting not working

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-webapp#4490]
It's not possible to change application language setting via the settings tab
![image3344](https://user-images.githubusercontent.com/4529018/39350679-91b77cd6-4a07-11e8-9cfb-0e39af90cc7d.png)
More context in https://github.com/medic/medic-projects/issues/3795

**Comment by SCdF** [comment]
@eljhkrr can you expand on what the bug is as it's not clear from that screenshot.

Specifically, can you provide:
 - Environment details (browser version, app version etc)
 - The steps to reproduce this
 - What you would expect to happen
 - What actually happens
 - Any more thoughts you have on it, things you've tried, context for the situation etc

**Comment by christinewere** [comment]
Hi Stefan its also not working for a recently updated to 2.14.1 IMCHA instance https://github.com/medic/medic-projects/issues/3795

**Comment by abbyad** [comment]
Can you please check the logged-in user's language as well? Copying over relevant bits from https://github.com/medic/medic-projects/issues/3795#issuecomment-384972575 to have it in the public repo as well:

> [...] each logged-in user can set their own language. The default language is only used if the user does not have a language set. [...]
>
> [...] verify by checking on the `configuration/user` page, accessible via the hotdogs menu:
> ![image](https://user-images.githubusercontent.com/789512/39365309-c2dc4552-49fe-11e8-8969-c0ab9c35249a.png)
>
>
> ![image](https://user-images.githubusercontent.com/789512/39365223-8891267e-49fe-11e8-8244-354f54d39aa2.png)

**Comment by sglangevin** [comment]
Setting the default language will not change the language for the user currently logged in. You have to follow Marc's instructions above to change the language for the user who is logged in. The default language will set the language of the login page and set a default for any users created once the default language is set. You can always override the default language as you create individual users.

**Comment by SCdF** [comment]
Looks like there wasn't really an issue here.
