### ISSUE TITLE
req contains self referencing object

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#45]
When i try to jsDump a req I get an error, 'Uncaught RangeError: Maximum call stack size exceeded' http://cl.ly/0i342i3M3C1b3v1P0n0R  

There is an problem with the userCtx attr  http://cl.ly/1h0w3p0S1y3n0G353t0Y

**Comment by ngaruko** [comment]
This issue was moved to ngaruko/medic-webapp#7
