### ISSUE TITLE
`Contact is not within place`

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4502]
When creating/adding a new user in the configuration app, one can create a regional manager restricted to a place and associate that manager with a `Contact`  who is in another place.
The screenshot below is a successfully created user 
Contact is not within place
![image](https://user-images.githubusercontent.com/6979995/39497208-6d27f394-4df6-11e8-80db-771d2a3d1c0d.png)
However, if one tries to 'edit` an existing user, they are not allowed to select a contact that is not within place and no meaningful error is displayed in the UI.
![image](https://user-images.githubusercontent.com/6979995/39497285-c0c57968-4df6-11e8-87c1-d70caa5f8ac4.png)
a) Shall we enforce that feature, ie only allow selection from within selected place?
b) If so, we might need to enforce that in the user creation stage and send the error message to the user.

**Comment by garethbowen** [comment]
Code review please @dianabarsan

**Comment by ngaruko** [comment]
LGTM.
Tested on `alpha.dev` v3.0
![image](https://user-images.githubusercontent.com/6979995/40631216-9c4511d2-632e-11e8-837c-6f7e1204ad32.png)
Could be improved, from a UX perspective @garethbowen by making the `associated contact` drop-down only bring contacts for that place (  once the place is selected)
