### ISSUE TITLE
Configuration app: loader throbber doesn't work

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4504]
There are various places the loading throbber should be displaying but isn't.

Obvious ones are loading the list of upgrades on the upgrade page, the list of forms on the forms page, the list of icons on the icons page, etc.

**Comment by garethbowen** [comment]
@ngaruko If you look at the [last comment on #4505](https://github.com/medic/medic-webapp/issues/4505#issuecomment-386279029) Stefan say's he'll work on this. It looks like we don't (yet) have an issue to track it.

**Comment by ngaruko** [comment]
Thanks @garethbowen. I will close this one and reopen either #4505 or #4507 to track this.
