### ISSUE TITLE
Configuration app doesn't detect upgrades

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4505]
To replicate:
 - Be on the configuration app, e.g. http://localhost:5988/medic/_design/medic-admin/_rewrite/#/settings/basic
 - Change some code and re-push with grunt
 - OR, more importantly for production, deploy a new version with Horticulturalist: http://localhost:5988/medic/_design/medic-admin/_rewrite/#/upgrade

What should happen:
 - You should get a pop up asking you to refresh, just like the rest of the app

What actually happens:
 - Nothing.

**Comment by garethbowen** [comment]
@SCdF The admin app isn't offline-first so it should refresh as you navigate around just like a "normal" webapp. Horti is the special case where we were using the popup as a way of telling the user that the upgrade has finished. Perhaps we should do something different for that special case? I don't think the popup is particularly useful anywhere else in admin.

**Comment by SCdF** [comment]
OK. I'll add a note to my horti work to make sure I deal with this specifically for horti.

**Comment by ngaruko** [comment]
Reopening this for reasons mentioned in #4504  and #4507. Please check if this makes sense to you @SCdF ?

**Comment by SCdF** [comment]
Wait hold on, sorry for making these tickets a churn fest, but this is actually the exact opposite of what we want. 

This ticket talks about generically supporting noticing upgrades, which Gareth pointed out doesn't matter (because it's an online only website).

The two other tickets you closed are the right ones, and actually talk about two separate issues, one being refreshing once there is a deploy in the horti view, and the other being in general, loading throbbers don't work (including horti, but also in other places)
