### ISSUE TITLE
Timestamps incorrectly cleared when adding a message to an ANC reminder group

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#4511]
Webapp version: 2.15.0-beta.11
Deployment environment: Horticulturalist 0.9.1 on Docker Machine

On the latest beta of 2.15, I'm seeing what looks like incorrect UI behavior when adding a message to an existing group of ANC reminders. The bug does not appear to be present in the latest 3.0 `master` snapshot.

To reproduce, find a report with ANC reminders, then click `Add Message` on this screen: 
<img width="594" alt="screen shot 2018-05-03 at 1 27 32 pm" src="https://user-images.githubusercontent.com/763977/39601325-65ab5e7c-4ed6-11e8-87ef-f6bbb882fafd.png">

On 2.15.0-beta.11, you'll see this:
<img width="593" alt="screen shot 2018-05-03 at 1 27 39 pm" src="https://user-images.githubusercontent.com/763977/39601367-835a65da-4ed6-11e8-9d75-b944609cabf9.png">

On the latest `master` snapshot, you'll see this:
<img width="595" alt="screen shot 2018-05-03 at 1 27 01 pm" src="https://user-images.githubusercontent.com/763977/39601377-8ec24992-4ed6-11e8-9a5a-dac989bdbd81.png">

I'd expect both 2.15.0-beta and 3.0-pre to preserve the existing timestamps, rather than displaying "Invalid Date". (N.B. the above is fabricated test data and does not contain any actual PII)

**Comment by sglangevin** [comment]
Definitely a bug, though I don't know if anyone actually uses this feature. I'll investigate and see if I can find any use cases for this.

**Comment by garethbowen** [comment]
I hope this is fixed by the work done for #4787

Setting this for acceptance testing to make sure.

**Comment by ngaruko** [comment]
Done with #4787
