### ISSUE TITLE
No auto-response generated when using translation keys for notification (on/off forms)

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4513]
After updating the standard config to use translation keys for the responses to on/off forms for muting/unmuting schedules, the auto-responses are not generated. 

To reproduce, use medic-reporter to send an OFF form about a patient.

Tested on beta.dev, 2.15.0-beta.11 using the following config for the "notifications" section of app_settings:
```
"notifications": {
    "off_form": "OFF",
    "on_form": "ON",
    "confirm_deactivation": false,
    "validations": {
      "join_responses": true,
      "list": [
        {
          "property": "patient_id",
          "rule": "regex('^[0-9]{5,13}$')",
          "translation_key": "messages.generic.validation.patient_id"
        }
      ]
    },
    "messages": [
      {
        "translation_key": "messages.generic.mute_schedule",
        "event_type": "on_mute",
        "recipient": "reporting_unit"
      },
      {
        "translation_key": "messages.generic.unmute_schedule",
        "event_type": "on_unmute",
        "recipient": "reporting_unit"
      },
      {
        "translation_key": "messages.generic.registration_not_found",
        "event_type": "patient_not_found",
        "recipient": "reporting_unit"
      }
    ]
  },
```
cc @abbyad in case this could be a config error. When I revert back to using message arrays, auto-responses are generated as expected.

**Comment by garethbowen** [comment]
Code review please @dianabarsan . This needs backporting to `2.15.x` - feel free to leave this to me.

**Comment by dianabarsan** [comment]
Merged into `master`.

**Comment by garethbowen** [comment]
Backported to `2.15.x`

**Comment by sglangevin** [comment]
Working well in 2.15.0-beta.13. Moving to ready.
