### ISSUE TITLE
Sentinel cannot handle reports with `{}` in lineage

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4523]
As discovered in https://github.com/medic/medic-projects/issues/3936, sentinel cannot handle certain reports. This is a shadow ticket to resolve the project issue, and can spawn some medic-webapp issues as needed.

The current theory is that this is due to not properly handling the case where the lineage includes `"parent": {}`, but there may be other causes.

**Comment by garethbowen** [comment]
I've merged the PR from @alxndrsn into `2.14.x`. I forward ported the unit test to `2.15.x` and it passed so no code changes were necessary. Unfortunately the unit tests in `master` are currently broken so I'll leave that test to be done as part of #4306
