### ISSUE TITLE
Add ability to sort places by date last visited

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4524]
This feature makes it easier for CHWs to identify households they have not visited recently so that they can ensure every household is visited each month.

Currently, the list of places on the people tab is sorted alphabetically. This feature adds the ability to sort by the date the place was last visited. The date the place was last visited is determined by the `reported_date` of a form submitted at the place level. When places are sorted by date last visited, the place visited longest ago is at the top, with those visited most recently at the bottom. This allows the user to prioritize visits with places visited the longest ago. If the date last visited is unknown, this should be at the very top of the list, above the longest ago date known. The default sort should still be Alphabetically.

Open question for discussion: will adding this sort apply to all hierarchy levels? Or only the lowest level? Or would we be able to select which levels it would apply to?

Additional requirement: this feature is part of "universal health coverage" (UHC) mode, which is a group of features we'd like to be able to toggle on and off (either using configuration, feature flags, user permissions, or some other solution). More information about UHC mode in #4525.

UI components:
- [x] clear search icon moves next to the search box
- [x] new icon for sort is added to the right of the clear search icon (16px, fa-sort-amount-desc, same color as other icons)
- [x] clicking on the sort icon pops up a white box with 4px rounded corners and drop shadow
- [ ] the white box has title Sort this list (16px bold, 20px from the left edge)
- [ ] below the title are two options: Alphabetically and By date last visited (16px, 40px from left edge)
- [ ] whichever option is selected has a green checkmark next to it (16px, fa-check, #8EB41D)

![image](https://user-images.githubusercontent.com/1286381/39655345-edacc810-4fad-11e8-9004-f6d52161b725.png) ![image](https://user-images.githubusercontent.com/1286381/39655409-4d3185e6-4fae-11e8-98ed-00cf035cdd0b.png)

More details [in this doc](https://docs.google.com/document/d/1y5g_Oi4a-3pQbwwTwPEsWX0jF7AJML2lnH9XsVhb_yA/edit#).

Acceptance criteria:
- clicking on the sort icon pops up a white box of appropriate size/location
- sorting by date last visited sorts the list so that unknown dates are at the top, followed by the longest ago dates and then the most recent dates are at the bottom
- sorting alphabetically sorts the list alphabetically

**Comment by SCdF** [comment]
Ideally we'd be able to do this by creating a map/reduce view that pulls us the top N ids of places by type ordered by visit time, where visit time is the last time I form was created against that place. Perhaps places by type is reaching, which means we might have to just do it by visit time and then loop on getting the full docs and removing the ones that aren't at the right level (though for the restricted users 80% case the results will nearly always be relevant I think).

However
> If the date last visited is unknown, this should be at the very top of the list, above the longest ago date known.
makes it more complicated. 

Other options include writing it into the contact manually each time it changes, or storing the details in a local doc to avoid constantly rewriting documents that replicate / force view re- generation needlessly.

**Comment by SCdF** [comment]
This and https://github.com/medic/medic-webapp/issues/4526 are related and should be done together

**Comment by SCdF** [comment]
@sglangevin how should the button be displayed on desktop view? It looks really weird on large windows floated to the right:
![image](https://user-images.githubusercontent.com/583851/41237932-bd9c6db8-6d8c-11e8-8d5b-1293ab250e85.png)

**Comment by sglangevin** [comment]
@SCdF can you align it with the hamburger menu? That way it won't be in a weird spot and will scale to different screen sizes in a more sensible way.

**Comment by SCdF** [comment]
@sglangevin Won't that look so far away though? Looking at how the reset button is done right now, it's floated right in the mobile view, aligned normally on desktop. Would it make sense to do that here as well?

**Comment by sglangevin** [comment]
This was @amandacilek's suggestion - perhaps you two can sort this out. I think it's only far away on bigger desktop screens, but I get the point that it would be far from the list that it's sorting. The other thing to remember is that everything will be moving when we do the nav update, so this is a temporary solution.

**Comment by amandacilek** [comment]
If it always stays 50px away from the search reset button:
![screen shot 2018-06-12 at 10 27 41 am](https://user-images.githubusercontent.com/26235957/41306585-7372da2a-6e2b-11e8-925d-4367d14a014f.png)


If it stays aligned to the right edge of the LHS column:
![screen shot 2018-06-12 at 10 27 55 am](https://user-images.githubusercontent.com/26235957/41306573-6c219ab8-6e2b-11e8-9a70-69a69d52ec70.png)

**Comment by sglangevin** [comment]
I prefer it aligned to the right edge of the LHS column, if that is possible.

**Comment by SCdF** [comment]
AT:
 - Follow the setup instructions on #4526's AT section so you have valid data
 - Once you have this the dropdown should sort your results by the type that you click. 
 - NB: the styling is currently not what was asked for: it instead follows the existing styles used in other dropdowns. This feels more consistent to me, but if we really want to style this differently to everything else we can

**Comment by garethbowen** [comment]
@SCdF Please remember to forward port this to `master`

**Comment by SCdF** [comment]
Done!

**Comment by sglangevin** [comment]
@SCdF I haven't tested the functionality of this one just yet, but we need a permission for the sort button - right now it appears by default but it should only appear for those who have the permission. Either we have one permission for "UHC mode" that changes the people list to show date last visited and makes the sort button appear or we can have individual permissions, one for each, with a later goal of having a way to select all permissions related to "UHC mode".

**Comment by sglangevin** [comment]
Upon further investigation, this had to do with the fact that I was logged in as admin and we can't control permissions for admin from the UI (as fas as I can tell). @garethbowen any suggestions? The UHC features shouldn't be enabled by default - maybe we can just adjust it so that they are not enabled for admin by default?

**Comment by sglangevin** [comment]
@SCdF I talked with @amandacilek and we both agreed that we don't like using checkboxes for sort. Checkboxes sort of imply that you can select multiple items and with sort, you can have only one or the other. I'd like to either implement the design Amanda provided or at least change these to radio buttons so it's more clear to the user. Returning to you for the UI changes - the functionality is working as expected.

**Comment by garethbowen** [comment]
@sglangevin The solution is to not log in as a couchdb admin. Create a new online role that's able to see everything and then toggle their permissions as you like.

**Comment by garethbowen** [comment]
Code review please @dianabarsan . I'm happy to do the merge and forwardport.

It's quite difficult to get the icon to line up with at the right edge of the LHS on desktop mode with the current UI. I've made it line up on mobile/tablet but in desktop it's just beside the reset icon. This is going to change in 3.1 anyway so I thought it wasn't worth much time.

AT: make sure this works on mobile too!

![desktop](https://user-images.githubusercontent.com/2064938/41516273-db8d3494-7307-11e8-8ca1-696bba60f519.png)
![tablet](https://user-images.githubusercontent.com/2064938/41516274-dbb97f7c-7307-11e8-901b-ea1fd342b9b7.png)
![mobile](https://user-images.githubusercontent.com/2064938/41516275-dbe46de0-7307-11e8-8297-8ffcd08d49b5.png)

**Comment by garethbowen** [comment]
Merged to `2.16.x` and forward ported to `master`.

AT: Be sure to check the mobile interface not just desktop.

**Comment by ngaruko** [comment]
LGTM... 
Tested on both `beta-old.dev` and `alpha` (desktop and phone)

**Comment by garethbowen** [comment]
Moved.

**Comment by sglangevin** [comment]
Looking much better, thanks!
