### ISSUE TITLE
Make it possible to toggle universal health coverage mode on and off

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4525]
As we are developing the first few features for our universal health coverage (UHC) mode, we would like to solidify the concept of these features as a mode for our app that can be toggled on and off. If UHC mode is on, the user should have the ability to sort by date last visited (#4524) and should see the date last visited listed for each place instead of the primary contact (#4526). In the future, turning UHC mode on might include more features, or we may end up making it the default mode for our application. For now, as long as we have a way (configuration, feature flags, user permissions, etc.) to turn the features on and off, that will accomplish the goal of this ticket.

**Comment by garethbowen** [comment]
This needs to be done in a generic way so we can use it for other modes.

If possible it would be done so certain users could have the mode set so the features can be toggled on/off just for them. This would help with the innovation network deployments as it would allow one instance to server IN and non-IN users.

**Comment by sglangevin** [comment]
After further discussion, as long as we have a way to display UHC features to a subset of users on the same instance, that will satisfy what is needed for July's pilot. If we do that the same way we are limiting replication depth for supervisors, for example, that will suffice, and we can revisit this later to make it more robust.

**Comment by garethbowen** [comment]
Code review please Mr. @SCdF

**Comment by garethbowen** [comment]
This is now possible by creating a new role for UHC users and configuring specific permissions for that role. The UHC features should be developed with a role to control showing/hiding them.

**Comment by ngaruko** [comment]
Does this need a new configuration loaded to `alpha.dev` @sglangevin @garethbowen ?

**Comment by SCdF** [comment]
More AT:

Make sure that the upgrade between 2.15 and 2.16 works correctly re: permissions. There have been reports that this doesn't work transparently, both in dev and in testing, and it should.

Specifically, if you do an upgrade between the versions:
 - Admin (online) users, both logged in as the upgrade happens and not, should see a full permissions list on the permissions page that is the same as it was before. This failing would be an empty list, and requiring config upload or clearing the cache
 - Offline users should receive the upgrade, and receive any permissions changes after this, without having to clear their cache or anything like that.

**Comment by sglangevin** [comment]
Configurable roles are cool! Excited about this feature. One small UI issue: the permissions page needs to scroll to the right because if you create more roles than can fit across, it wraps in a very unfortunate way. Note that the CHW role title is below the Supervisor title and the checkboxes for CHW have wrapped to the next line. https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/configuration/authorization/permissions
![image](https://user-images.githubusercontent.com/1286381/41486502-9f453c18-7099-11e8-89ef-eb95aa965a67.png)

**Comment by sglangevin** [comment]
Assigning back to you, @garethbowen to fix the UI issue. Giving some users access to the last visit date permission worked as expected.

**Comment by garethbowen** [comment]
Wow, yeah, that's terrible! Sorry I should have seen that coming.

**Comment by garethbowen** [comment]
I've updated the UI in `2.16.x` and `master`. Instead of the roles being in columns they're now in rows which takes up much more vertical space but is potentially more useful and supports as many roles as you like. There are other more complicated ways to achieve this without using so much vertical space but I felt this was a good safe option for 2.16.0.

![new-ui](https://user-images.githubusercontent.com/2064938/41513948-eb58feaa-72f6-11e8-9c94-8f719f5d4bd1.png)

**Comment by ngaruko** [comment]
Looks better ATM. I am not sure if this is a big deal (since admins are supposed to be using a desktop) ... but the first column has a fixed width and is not responsive, making texts to overlap for smaller screens - including actually tablets depending on the length of the permission key....@garethbowen  @sglangevin
![image](https://user-images.githubusercontent.com/6979995/41631099-dd396d0a-7486-11e8-936a-bdcfa64d9cd4.png)

**Comment by sglangevin** [comment]
I find this a bit harder to navigate than the old layout but I think it will do for now - I think it's just harder to scan through the options when laid out this way for whatever reason. @ngaruko this is not supported for use on tablets, it's desktop only, so we don't need to worry too much about small screens for now.
