### ISSUE TITLE
summary label icons are misaligned

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4530]
# Environment
- Instance: standard.dev
- Browser: Firefox
- Client platform: OSX
- App: webapp
- Version: 2.15.0-beta.1

# Observed
Icons for titles in label summaries are misaligned:
<img width="737" alt="screen shot 2018-05-07 at 10 47 45" src="https://user-images.githubusercontent.com/191496/39708204-8f252cc2-51e4-11e8-93e1-585a466461eb.png">

# Expected
I'd expect the icon to be here:
<img width="737" alt="screen shot 2018-05-07 at 10 47 45 copy" src="https://user-images.githubusercontent.com/191496/39708205-8f3e8276-51e4-11e8-8885-0a046c85560c.png">

Or if it should remain on the left, it should be properly padded from the side of the colour block, and vertically centred.

**Comment by garethbowen** [comment]
Yeah this is a bit naff and should be a quick fix. I'll have a look.

**Comment by garethbowen** [comment]
Code review please @alxndrsn 

I couldn't work out how to put the icons beside the text with CSS alone it would require changes to the forms, so I just made them look decent.

![alignment](https://user-images.githubusercontent.com/2064938/40478077-361ae2aa-5f9c-11e8-83d6-146628cfc809.png)

**Comment by ngaruko** [comment]
Slightly better padding atm...(in the eye on the beholder :))
*Before*
![image](https://user-images.githubusercontent.com/6979995/40631062-aeb3227a-632c-11e8-93a7-1d210b4f90bc.png)

*After*
![image](https://user-images.githubusercontent.com/6979995/40631071-d651c494-632c-11e8-81d7-c6777797ccd5.png)
