### ISSUE TITLE
Simplify Nools definitions to a JSON file

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4531]
Current Nools definitions could possibly refactored to common code between projects, and a project-specific JSON definition file.

Investigate if this is possible by trying to refactor a few existing `rules.nools.js` files into a common JS file and associated project-specific JSON files.

Even if this is not possible for _all_ projects, using templating/imports as per https://github.com/medic/medic-conf/issues/69 would allow easy sharing of common code between projects that _do_ have common code.

Some projects are likely to require definition of custom functions, and access to these from their JSON definition files.  Account should be taken of this at some point in this separation/testing ticket.

**Comment by abbyad** [comment]
Completed as part of https://github.com/medic/medic-projects/pull/4286
