### ISSUE TITLE
[Feature Request] Ability to disable unrecognized form code autoresponse

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic-webapp#4539]
We have a project where the facility nurse engages patients via an SMS conversation to discuss symptoms being experienced by the patient each day. All of the free text responses sent in by the patient result in an unrecognized form code autoresponse being sent back to the patient. It would be great if there was a way to completely disable this autoresponse since all these unnecessary messages sent to the patient have a cost implication.
More information in https://github.com/medic/medic-projects/issues/3947

**Comment by PhilipNgari** [comment]
@eljhkrr   Is it possible to know how many auto responses of that kind we are experiencing even if its approximation for the  50 clients so far.This  will help deduce what it would look like in the main study (commencing in June/july 2018) with about 700 clients. I can see already the partner is worried of the air time cost from these auto responses. @derickl  @abbyad .This looks like a critical one.

**Comment by korirm** [comment]
@PhilipNgari The approximate cost can be arrived at as below
Average sms per day for 1 client with a suspected AE = 5 
If 50% of the clients report AE per day = 350 clients 
350 clients x 5 sms = 1750 auto-response sms
700 clients x 1 outgoing sms per day = 700 sms
700 clients x 1 auto-response per day = 700 sms
This translates to = 3150 sms per day x 17 days = 53,550 sms for the full study
17 days = 14 days of study + 1 Day 13 second message + Day 40 sms + Day 42 sms
This excludes duplicated messages which from the pilot some have been more than 6 for 1 client

cc @eljhkrr @billwambua @isaacholeman

**Comment by abbyad** [comment]
Turns out that this is already possible by disabling the `default_responses` transition.

## To disable auto-replies for unstructured messages

1. In `app_settings.json` set `transitions.default_responses` to `false`. 
```js
  "transitions": {
    "default_responses": false,
    // other transitions
  }
```
2. Upload app-settings: `medic-conf --instance project-name.app upload-app-settings`
3. SSH into the instance and restart Sentinel (`sudo svc-restart gardener`)
