### ISSUE TITLE
Move ddocs to top-level directory in medic-webapp repo

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#4556]
`/webapp/src/ddocs/` don't seem specific to `webapp`, so perhaps could live at the top-level, e.g. `/ddocs`.

**Comment by garethbowen** [comment]
Yeah... that's the one bit I couldn't decide on. I think you're right...

**Comment by garethbowen** [comment]
We need a dir for the src and for the dist or build. Maybe `/ddocs/src` and `/ddocs/dist`?

**Comment by alxndrsn** [comment]
Personally i'd prefer all generated files to have a common root, e.g. `/build`.  I find this makes it much simpler to find generated files, especially if you're not aware what files can be generated.  Bonus is it makes `.gitignore` much simpler too.

**Comment by garethbowen** [comment]
That's what I've gone for... all generated files are in `webapp/dist` right now. Most are getting dumped right into the _attachments dir of the medic ddoc ready to be built right into the compiled ddoc.

This needs to be moved too, either to `/ddocs/dist` or `/dist` (or `/build` but I prefer dist for no real reason).

**Comment by alxndrsn** [comment]
`/dist` works for me (although I do prefer `/build`, because to me it implies it's temporary).  I'd say the subdirectory `/webapp/dist` is less clear than having `/dist` at the top level..

**Comment by garethbowen** [comment]
Probably the most correct solution is to have a `/build` for all the bits and a `/dist` for the final medic ddoc rather than putting them together in the same place.

**Comment by alxndrsn** [comment]
Or just put the final ddoc in `/build/dist`.  Presumably "dist" is short for "distributable".

For comparison:
* gradle default is to put binaries in `/build/outputs`, and
* maven puts them directly in `/target`, with other build-related files in subdirectories of `/target`.

**Comment by garethbowen** [comment]
Code review please @alixemden 

This change moves `/webapp/src/ddocs` to `/ddocs` and `/webapp/dist` to `/build`.

**Comment by alxndrsn** [comment]
I know you asked the other Al*x to review this, but I went ahead and did it anyway 😝

**Comment by garethbowen** [comment]
Merged.
