### ISSUE TITLE
Horticulturalist restart behavior

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4562]
We need to work out, confirm and potentially fix restart behaviour, at least while deployed under MedicOS, but ideally locally as well.

I think this is how it works now:

Under MedicOS:
 - Horti is started by the OS, and does not automatically start any packages
 - The packages are started by the OS
 - If any of the packages die, they are restarted independently by the OS
 - If Horti dies, horti will be restarted and I *think* the packages will attempt to be started, but it should be fine because they are already started

Locally:
 - Horti is started by the user
 - Horti starts any packages itself 
 - If Horti is closed cleanly via CTRL+C Horti and any packages are killed
 - If Horti crashes / is uncleanly closed (eg kill) packages are (annoyingly) left running
 - If a package crashes it is not restarted

The one super obvious bug is if horti gets "uncleanly" terminated packages don't die, which is a massive pita because you have to grep for node processes to manually kill them.

Apart from that, two big questions come from this:
 - Are the MedicOS behaviours acceptable for production?
 - What would we want to happen locally if a package dies? Should we restart the package, kill everything, or leave it alone?

**Comment by SCdF** [comment]
@browndav can you comment on the MedicOS behaviour?

**Comment by SCdF** [comment]
@rmhowe take a look at the PR above and let mw know what you think.

This PR makes it a bit clearer where Horti's responsibilities lie compared to MedicOS, uses a lockfile correctly (so you can't run horti twice), and tries its best to close cleanly when run locally.

**Comment by ngaruko** [comment]
LGTM...
Beefore 
```.gradle
.horticulturalist
.horticulturalist.lock
.ipython
.jupyter```

After
```
.gitconfig
.gradle
.horticulturalist
.ipython
.jupyter
```
