### ISSUE TITLE
Version build info and horti upgrade doc data structures

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4564]
For forwards compatibility / so we don't get into an annoying situation 18 months from now, we should version build info (the metadata stored against the build on the builds server) and `horti-upgrade` (the metadata created by api to instruct horticulturalist to perform a deploy).

This way, if we change the structure later up to date versions of horticulturalist will be able to handle old versions, and out of date versions of horticulturalist will know that they can't.

**Comment by SCdF** [comment]
Hey @garethbowen , please take a look at the three PRs above and let me know what you think.

Versioning the `horti-deploy` deploy info I think makes a lot of sense, because the version of that doc that gets created is based on your api version not your horti version, so it's definitely an api that we need to be really clear about (we already effectively support two versions of this data structure).

Versioning the metadata on the builds server I'm not that sure about. I don't really know how that would work in practice, except that the view output could be locked down and different versions would compile into the view output in different ways (ie the view code would switch on version)? IDK. I feel like to reasonably version that we'd actually need different views or something. Or to only ever *add* data and just have defaults / support null values (for example adding change notes inline would be useful, as would metadata about no# migrations or view changes, and in the future maybe additional metadata about the app in general)

**Comment by garethbowen** [comment]
LGTM. I've left the merge to you.

I think if/when we have a v2 maybe the view map should return a value which both v1 and v2 map to. That way horti is always getting the same format. But we can cross that bridge once we know what the differences are.

**Comment by SCdF** [comment]
Merged. No AT to do specifically here.
