### ISSUE TITLE
Make horticulturalist view warming output nicer

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4567]
When deploying a new release part of the deploy log displays views being warmed:
![image](https://user-images.githubusercontent.com/583851/40421931-789e497c-5e85-11e8-9bf6-d5102b21c889.png)

Currently this output is based on an unordered list of currently active background couchdb tasks that are indexers that are indexing staged ddocs, which gets overridden completely each time (and so once the task is over it just disappears), and outputs the ddoc name and percent done.

Here is an example of the data we're working with:
```json
    {
      "type": "warm_log",
      "indexers": [
        {
          "node": "couchdb@localhost",
          "pid": "<0.13435.326>",
          "changes_done": 2424,
          "database": "shards/00000000-7fffffff/medic.1525076838",
          "design_document": "_design/:staged:medic-client",
          "indexer_pid": "<0.7826.326>",
          "progress": 82,
          "started_on": 1527075166,
          "total_changes": 2942,
          "type": "indexer",
          "updated_on": 1527075186
        },
        {
          "node": "couchdb@localhost",
          "pid": "<0.8072.326>",
          "changes_done": 2424,
          "database": "shards/80000000-ffffffff/medic.1525076838",
          "design_document": "_design/:staged:medic-client",
          "indexer_pid": "<0.9817.326>",
          "progress": 81,
          "started_on": 1527075166,
          "total_changes": 2967,
          "type": "indexer",
          "updated_on": 1527075186
        }
      ]
    },
```

We currently just output `design_document` and `progress`.

We could make this much nicer:
 - Have it sort in a way that makes sense
 - Either combine output from multiple shards / nodes (the setup in the picture has two shards on one node) into one average %, or change the output so that it's clear that you're looking at a specific node/shard combination
 - Make the code that updates `indexers` smarter, so that once an indexer disappears it marks it's progress as 100% complete instead of it just disappearing.

There are probably lots of different ways we could display this smarter. As long as it's clear what is going on and progress doesn't just disappear once complete it would be an improvement.

**Comment by ngaruko** [comment]
LGTM. Tested on `alpha.dev` by upgrading instance to master
