### ISSUE TITLE
Reduce how long horticulturalist takes node modules down for

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4568]
Horti does a lot of work in the background before it restarts api and sentinel, but there is even more we can move out from between restarts.

Take a look at the current process: https://github.com/medic/horticulturalist/blob/master/src/install/deploySteps.js

The process from stopping to starting should really just be:
 - Stop processes
 - Move staged ddocs into production locations
 - Change symlink from old node_module locations to new ones
 - Start processes

Currently we also:
 - Extract new node_modules from staged ddocs
 - Write them to disk
 - Clean up and delete old node modules from disk

The first two bullet points should be done before processes are stopped, and the last one should be done in the existing cleanup phase.

**Comment by ngaruko** [comment]
Any idea how to AT this one @SCdF @vimemo ?

**Comment by SCdF** [comment]
@ngaruko just general smoke testing to make sure horti still works.

**Comment by newtewt** [comment]
@ngaruko  @SCdF  

I installed horti locally using npm. The app launched successfully. Then went to update instance and selected the 3.0.0-beta1. The deploy starts and fails. Created a gist with the log. 

https://gist.github.com/newtewt/ce179292a37fb35b452a85b10421286b

**Comment by SCdF** [comment]
@newtewt thanks for linking the logs. Note the error: 

> Failed to perform bulk docs, you may need to increase CouchDB\'s max_http_request_size

Have you tried this yet? I've noticed that we don't actually have instructions for this in the webapp readme, which is a mistake that I will rectify now, but basically if you go to Futon / Fauxton and go to the config portion and search for this property name you'll see it, and then you want to increase it by some large amoutn.

**Comment by newtewt** [comment]
@SCdF testing this locally after the suggested change and it's working. Would that be something we would want to set as part of the horticulture install or maybe warn about it during the install? Seems like a requirement to me for the application to work correctly. 

@ngaruko  would this be something we'd want to test in beta.dev as well?

**Comment by SCdF** [comment]
> @SCdF testing this locally after the suggested change and it's working. Would that be something we would want to set as part of the horticulture install or maybe warn about it during the install? Seems like a requirement to me for the application to work correctly.

This is a tricky one. Setting that CouchDB config param is something that *medic* requires to function (not horti specifically), alongside a bunch of other stuff (`require_valid_user`, a correctly setup admin user etc). In theory Horticulturalist is so far deployment agnostic: you could (in theory) deploy any "Couch App" with it.

So one option would be to push Horti to be very medic specific, where it really only cares about catering to our very specific medic-webapp app. The other option is what we've gone with so far: Horti is at least potentially a more generic tool that we could use to deploy other things as well as medic.

**Comment by newtewt** [comment]
Closing this as it been smoke tested locally and is still working.
