### ISSUE TITLE
Update status filter on reports page

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4577]
This improvement updates the status filter to accommodate filtering by the new report statuses added in #4529. The status filter currently has sections for validity and verification, which will change to manager review and SMS validity, reflecting the new report statuses and the changed use of the red/green dot on SMS reports.

UI changes:
- [ ] validity label becomes "Manager review"
- [ ] valid and invalid are replaced by "Not reviewed", "Reviewed: errors", "Reviewed: correct"
- [ ] verification label becomes "SMS validity"
- [ ] verified and unverified are replaced by "Valid SMS" and "Invalid SMS"

Functionality:
- [ ] filtering by "Not reviewed" displays all reports (SMS and app) with no dots
- [ ] filtering by "Reviewed: errors" displays all reports (app or SMS) that were marked as having errors by a manager
- [ ] filtering by "Reviewed: correct" displays all reports (app or SMS) that were marked as correct by a manager
- [ ] filtering by "Valid SMS" displays all SMS reports that were valid when received (regardless of whether they are "Not reviewed", "Reviewed: errors", or "Reviewed: correct")
- [ ] filtering by "Invalid SMS" displays all SMS reports that were invalid when received and have red dots (applied automatically)

**Note**: below mockup is rough, use existing styling

![image](https://user-images.githubusercontent.com/1286381/40517100-7dfa8e24-5f68-11e8-9253-7939477ed0a5.png)

Acceptance criteria:
- UI changes match mockup
- filtering functionality works as outlined above

More info in [the design spec](https://docs.google.com/document/d/1lRoAVszPQVbhKFTp9ddYg0heVY39hsOXLr3P4t92_r4/edit#heading=h.q30x2mno2q4j).

**Comment by sglangevin** [comment]
@vimemo please cherry-pick these changes into the 2.16.x branch for AT in the next beta. Moving back to active work.

**Comment by sglangevin** [comment]
This is working as expected with a few side effects to the UI. The drop-downs on the reports tab are behaving a little weirdly. Sometimes they are cut off (or don't have scroll bars when it seems like they should). Interestingly, the form types filter looks correct on mobile (despite having issues on desktop) and the report status filter looks correct on desktop (despite having issues on mobile).

Example: desktop view, form types filter
![image](https://user-images.githubusercontent.com/1286381/41632638-b710b76a-73ef-11e8-87af-6f4e663c0857.png)

Example: mobile view, report status filter
![image](https://user-images.githubusercontent.com/1286381/41632660-d099a476-73ef-11e8-84e7-57a6f8ea0096.png)

Can this be improved?

**Comment by garethbowen** [comment]
This is probably due to @SCdF removing a 50px paddding. Try reintroducing this padding and it should just work: https://github.com/medic/medic-webapp/commit/a20c92bef3fb0100d49ec602a046f8ed3eaead86#diff-dbac1265fac15297ba0798a7101df924L82

**Comment by garethbowen** [comment]
Fixed.

**Comment by sglangevin** [comment]
Ok - this is better in the sense that it's no longer cut off, but now the status filter dropdown is too long on mobile and desktop. All the other dropdowns are the correct size.
Mobile:
![image](https://user-images.githubusercontent.com/1286381/41688975-3a863c9c-74a3-11e8-85f1-5ce9712c9b0c.png)
Desktop:
![image](https://user-images.githubusercontent.com/1286381/41688979-434139e0-74a3-11e8-85e2-5235414cb87f.png)

**Comment by sglangevin** [comment]
LGTM in 2.16.0-beta.6. Moving to ready.
