### ISSUE TITLE
Pregnancy reports sent via sms cannot be viewed when user language in not English

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4584]
Pregnancy reports sent via sms cannot be viewed when user language in not English.

**Steps to reproduce**:
 -Login alpha.dev as admin
- Change user language to Swahili in [edit user profile ](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/user)
 - Submit a pregnancy report via the message-test Ui in [admin console](https://alpha.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/message-test)
 - Go back [reports](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/) and observe the report has been submitted
- Click on the report in the LHS

**What should happen**:
 - The report's details should be displayed in the RHS

**What actually happens**:
 - The report UUID disappears from the[ url](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5f3104258f5bd30e159376d5da036b4a) after a few seconds
- 'No report selected' shows in the UI
-and the following errors in the console:

```
Error selecting report TypeError: u.substr is not a function
    at g (inbox.js:3)
    at Function.x.instant (inbox.js:3)
    at w (inbox.js:3)
    at inbox.js:3
    at Array.forEach (<anonymous>)
    at v (inbox.js:3)
    at inbox.js:3
    at inbox.js:3
    at inbox.js:3
    at i.$digest (inbox.js:3)
```
Report url : https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5f3104258f5bd30e159376d5da036b4a

**Environment**:

- Instance: alpha.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.0.0

**Comment by garethbowen** [comment]
I've updated the default translation (and 33 others) so they don't have `\n` any more. These will be updated next time we export translations from POE before we make the `3.0.x` branch.

**Comment by ngaruko** [comment]
LGTM. Tested in `alpha.dev` with this [report](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/5f3104258f5bd30e159376d5da038b9e)
