### ISSUE TITLE
Allow registration with age in months or years

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4597]
Incoming forms can currently specify an age in **days** or **weeks**, and set the date of birth on the doc accordingly. It would be useful for Standard deployments to be able to specify the age in **months**.

The original immunization workflow required registration of children up to 2 years old, which was feasible by specifying the age in weeks. With the [new child health workflow](https://github.com/medic/medic-projects/issues/4155) you can register children up to 5 years old for messages -- which makes registring with age in weeks quite difficult.

Age in years in not needed for Standard (yet), although could be useful for some use cases (eg registration of pregnant women).

cc @jillrshah, @ranjuts

**Comment by ranjuts** [comment]
Hmm I'm a bit confused here. We have a new person form deployed in Nepal w age specified in years. Is the limitation where you need to create a schedule based on that age? And is it not just age but any value? eg. if a form needed a value for "been under treatment for hypertension" (just giving a wild example here), that would also need to be entered in weeks or days? @abbyad

**Comment by abbyad** [comment]
@ranjuts, can you point me to the project form in question? The limitation is where you need to set the date of birth when creating the person with an SMS. Setting any "time since X" is similar, but we don't have a generic way to do that.

**Comment by ranjuts** [comment]
Its form "क" (line 59) here: https://github.com/medic/medic-projects/blob/master/moh-nepal/forms.json

**Comment by ranjuts** [comment]
we're not calculating date of birth or a schedule based on date of birth (based on this age). Its simply the absolute value for how old that person is.

**Comment by abbyad** [comment]
Thanks. Even though it is not yet using the age to _set_ the date of birth, it does seem as though it would be used. I'll rename the issue to include an age in years option.

**Comment by garethbowen** [comment]
Nice one. Ready for AT.

**Comment by newtewt** [comment]
I am able to submit reports with days, weeks, months, and years now.
