### ISSUE TITLE
Make family equity score available for family member task generation and within forms about family members

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4600]
This feature makes the family equity score available within forms about family members or for generating or updating task schedules for family members. Equity scores can be collected either during family registration or via a form filled in at the family/household level. The scores might impact the frequency at which a CHW should visit a particular household or require the CHW to follow a different pregnancy visit schedule for women in households with lower scores.

The equity score is a measure of wealth. By asking questions about housing materials, possessions, and a few other things, the survey determines which wealth quintile a family falls into. Being in a lower quintile might mean you are less likely to deliver at a health facility or less likely to seek treatment when you are sick. Using these scores to help target households is important in making sure that CHWs can provide equitable care.

Equity scores are somewhat static, but they might be re-evaluated every 6 months or so (schedule would vary by project).

Requirements:
- Equity score for the family is available in forms about all family members
- Equity score for the family can be used to determine task schedules for family members

Acceptance criteria:
- Can access equity score in person-level forms
- Can use equity score to trigger a different task schedule if the score is above/below a certain threshold

**Comment by SCdF** [comment]
> Equity score for the family can be used to determine task schedules for family members

This makes me think this has to be implemented in a sentinel transition that writes the equity score to the family contact? (which won't work offline until replicating, which is annoying)

If we didn't need this point we could calculate it live before we initiate the forms.

**Comment by rmhowe** [comment]
@sglangevin should this be the national score, the urban score, or both? Also, are quintiles needed?

**Comment by sglangevin** [comment]
Can we just have a field called `equity_score` and then the person creating the form can decide what to put in there? I'll ask to see if the quintile is needed in another field, but my guess is we'd just be able to use the equity score to infer the quintile. I've pinged @yembrick on Slack and one of us will come back with more info.

**Comment by rmhowe** [comment]
Making both available isn't a problem so I'll do that, and it sounds like the quintile can be calculated on the fly so I'll leave it out for now but it can be added in easily later if needed.

**Comment by sglangevin** [comment]
Cool, so I think the best way forward would be to store the national and urban quintiles as opposed to the raw scores. We'll need to dictate the field names for those two data points so others using this feature know how to configure their form correctly.

**Comment by rmhowe** [comment]
Ok sounds good, do you know yet what those field names will be?

**Comment by sglangevin** [comment]
Sorry - missed this comment yesterday. I think it would be fine to use `national_quintile` and `urban_quintile` and assume they are top-level fields in the form, so they'd be at `fields.national_quintile` and `fields.urban_quintile` in the JSON. If you already used something else, that's fine, just comment here with some info on how this would be configured.

**Comment by sglangevin** [comment]
Note for future: to configure this, make sure you have `doc.fields.UrbanQuintile` and `doc.fields.NationalQuintile` defined in your form.

**Comment by sglangevin** [comment]
This is working well in 2.16.0-beta.5. Moving to ready!
