### ISSUE TITLE
Make sure we can't infinitely recurse in the lineage shared library

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4604]
Due to issues like https://github.com/medic/medic-webapp/issues/4596 and https://github.com/medic/medic-webapp/issues/4487 we should make sure, however unlikely, that we have guards in place to have us cleanly throw errors if we detect that we're hitting an infinite loop.

The alternative is that the app hangs / crashes, which isn't good!

Simplest is probably just to put depth guards on potentially problematic loops and throw if the number gets outrageously high (eg > 100 or something).

**Comment by SCdF** [comment]
Upgrading this to high, just to indicate that we defo need to do it before release.

**Comment by ngaruko** [comment]
Any insight on how to AT this @SCdF ?

**Comment by SCdF** [comment]
I don't think this needs to be AT'd, since it's not a front-facing feature, but a refactoring of a library to guard against an edge case that should never come up anyway (but unfortunately sometimes does, especially in testing).

_However,_ if you want to, feel free to look at the code Robbie wrote, and see if you can come up with a data structure that would cause it to infinitely loop that isn't covered by his code. An AT style statement for this might be: "The lineage library should always either quickly succeed or quickly fail, it should never loop indefinitely"

**Comment by ngaruko** [comment]
Thanks @SCdF . LGTM. Checked on `alpha.dev` with this [doc](https://alpha.dev.medicmobile.org/_utils/#database/medic/circular-lineage-person) and verified in the [UI](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/circular-lineage-person) ... thanks to @dianabarsan .
