### ISSUE TITLE
Symbols in translations are not rendered correctly

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4618]
Symbols are not rendered correctly if they are included in translations. In this case the translation key is messages.schedule.registration.followup_anc from the Standard config.

**Steps to reproduce**:
 - Submit an N form on an instance using Standard config
 - View the form submission in the Reports tab
 - Notice that the outgoing scheduled message shows `&lt;` and `&gt;` instead of the appropriate symbols

**What should happen**:
 - Symbols should be displayed

**What actually happens**:
 - Symbol codes are displayed

Bad report here: https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/dd32e2d08c7def675f5de6ab9625280d
Good report here: https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/dd32e2d08c7def675f5de6ab9610e2bf

Given that the good report was submitted about 2 weeks ago, this bug was likely introduced in the 2.15.x branch.

Screenshot:
![image](https://user-images.githubusercontent.com/1286381/41260433-469ef9ce-6d8c-11e8-83af-3e7a18b5f99a.png)

**Environment**:
- Instance: beta-old.dev
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.15.0-beta.17

**Other**:
I tried editing the translation and resaving, which didn't work. There aren't any workaround that I know of, but if there is one, happy to test that.

**Comment by garethbowen** [comment]
Review please @dianabarsan . Feel free to leave the merge and backport to `2.15.x` and `2.16.x` to me.

**Comment by dianabarsan** [comment]
Reviewed, @garethbowen . Leaving merging and backporting to you.

**Comment by garethbowen** [comment]
Merged into `master`, `2.16.x` and `2.15.x`.

**Comment by sglangevin** [comment]
LGTM on 2.15.0-beta.18. Moving to ready!
