### ISSUE TITLE
Implement access logging in API

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4622]
In moving to Docker we have lost the nginx access log capability so we need to implement this in API. We already log when requests come in using morgan but we have no logging for the response status, size, time, etc.

Consider whether this should be combined in the same api log or logged separately.

**Comment by ngaruko** [comment]
Fixed in #4648. Logs now look like ```REQ 452a6de1-af2e-4f12-b10e-7c2893e3bf63 ::1 admin GET /api/info HTTP/1.1
RES 452a6de1-af2e-4f12-b10e-7c2893e3bf63 ::1 admin GET /api/info HTTP/1.1 200 19 0.709 ms```
as per this [comment](https://github.com/medic/medic-webapp/pull/4648#issuecomment-398266672)
