### ISSUE TITLE
Reports page can mistakenly hide fields

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4625]
A submitted report may be have fields hidden that should be shown.

**Steps to reproduce**:
 - Write a form with a hidden field whose name is the prefix to another field, or use the one included below
 - Submit that report

**What should happen**:
 - Only the specific field that is marked with `tag="hidden"` should be hidden. In this case it is the `name` field.

**What actually happens**:
 - All fields that start with the same name as the intended hidden field are hidden. In the example below `name2` is greedily hidden, and shouldn't be.

Tested on version 2.14.3

## Example XForm
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Issue: Hidden Fields</h:title>
    <model>
      <instance>
        <hidden_fields delimiter="#" id="hidden_fields" prefix="J1!hidden_fields!" version="2018-06-12 22-55">
          <name tag="hidden"/>
          <name2/>
          <another_name/>
        </hidden_fields>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/hidden_fields/name" type="string"/>
      <bind nodeset="/hidden_fields/name2" type="string"/>
      <bind nodeset="/hidden_fields/another_name" type="string"/>
    </model>
  </h:head>
  <h:body>
    <input ref="/hidden_fields/name">
      <label>name</label>
    </input>
    <input ref="/hidden_fields/name2">
      <label>name2</label>
    </input>
    <input ref="/hidden_fields/another_name">
      <label>another_name</label>
    </input>
  </h:body>
</h:html>
```

**Snippet of doc for a submitted report**
```json
{
  "hidden_fields":["name"],
  "fields":{
    "name":"i",
    "name2":"i2",
    "another_name":"i3"
  }
}
```

**Comment by sglangevin** [comment]
Just noting that this isn't a new issue - I ran into this before and asked around, only to find out that the solution was to change the name of the form field.

**Comment by abbyad** [comment]
Ah, although that seems like more of a workaround than a solution :)

Seems like we could fix this here: https://github.com/medic/medic-webapp/blob/b7a43c3cfdafc8e2a6159ac7efdcd95313b24167/webapp/src/js/services/report-view-model-generator.js#L70-L74

There may have been a good reason at some point to hide all that start with the same name, but seems as though we should compare the full field name eg `return field.label === label + '.' + h;`

**Comment by abbyad** [comment]
Awesome, thanks for the contribution!!

"Help wanted" is a good place to start, and we can make sure to have more available with that label as you burn through them :)

**Comment by garethbowen** [comment]
> I can open one or two issues/PRs against your documentation, and standard configuration if this is something you're improving.

We're definitely interested in improving the documentation so please feel free!

**Comment by newtewt** [comment]
Looks good to me
