### ISSUE TITLE
Update CHW area icon

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4635]
Please replace the existing default CHW area icon (the one that ships with medic-webapp) with this new and improved one: https://drive.google.com/open?id=1uUG70I9fIZYTMrscj-U2mxq_QOdRYSl1

**Comment by garethbowen** [comment]
Merged and forward ported.

AT: When upgrading the existing icon will be used. On fresh install this new icon will be used instead.

**Comment by sglangevin** [comment]
@ngaruko are you able to test the fresh install? I don't have a way of testing that on my end.

**Comment by sglangevin** [comment]
I have uploaded the icon onto beta-old.dev to see how it looks and unfortunately we have a slight problem:
![image](https://user-images.githubusercontent.com/1286381/41689342-03c84dd8-74a5-11e8-9f68-787a60a5285d.png)

I'm working with @amandacilek to see if we can use a mirror image instead.

**Comment by sglangevin** [comment]
Ok, we've settled on a mirror image. [New file is here](https://drive.google.com/file/d/12VeiaLuahaswtvvx4_tf79vnZlKWru31/view).

**Comment by sglangevin** [comment]
@ngaruko have you been able to test this on a fresh install? We need to move this to ready if it's working well.
