### ISSUE TITLE
Improve death reporting workflow by allowing the death confirmation form to specify the date of death

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4636]
Currently, when the `death_reporting` transition runs, it adds a `date_of_death` field to the contact doc that is equal to the `reported_date` of the death confirmation form. However, the death confirmation is likely to happen after the actual date of death. We'd like to provide a way to indicate the date of death in the death confirmation form so that the date of death that is recorded on the contact doc is the actual date of death.

@garethbowen suggested that the death confirmation form can include a field called `date_of_death` that would be saved on the contact doc. If not, the transition could fall back on the death confirmation report's `reported_date`.

**Comment by garethbowen** [comment]
Code review and documentation review please @vimago 

Feel free to leave merging and forward porting to me.

AT: The transition can now be configured with a `date_field` property which specifies the path to the field with the date. This defaults to `reported_date` but allows for users to specify the date in the death reports, eg: `fields.date_of_death`.

**Comment by garethbowen** [comment]
Merged into `2.16.x` and `master`.

**Comment by michaelkohn** [comment]
- What happens if you delete the death report, does it blank out the `date_of_death` and/or remove the field from JSON?
- If subsequent death reports are submitted, do we reject them or do we just update with the most recently submitted?
- If the `date_of_death` on the form is edited, I assume this propagates to the contact as well, but what if an earlier form was edited (ie if two were submitted, but the first one was edited)?

**Comment by garethbowen** [comment]
> What happens if you delete the death report, does it blank out the date_of_death and/or remove the field from JSON?

No the field remains. You have to use an undo report to remove the date_of_death.

> If subsequent death reports are submitted, do we reject them or do we just update with the most recently submitted?

The patient is not updated when the second report is received. Sentinel can be configured to reject duplicate death reports with an error if desired.

> If the date_of_death on the form is edited, I assume this propagates to the contact as well, but what if an earlier form was edited (ie if two were submitted, but the first one was edited)?

As with the previous question, editing won't update the date_of_death on the patient.

@sglangevin @michaelkohn Is this correct or do you think we should change the implementation?

**Comment by sglangevin** [comment]
The workflow has 2 options: report a death, supervisor/other health official confirms the death, patient is marked as deceased in our app and a date of death is added to their contact doc. OR report a death, patient is marked as deceased in our app and a date of death is added to their contact doc.

For undoing a death, there are also 2 options: request a correction, supervisor/other health official confirms it was a mistake, patient is marked as alive in our app and date of death is removed from their contact doc. OR undo the death, patient is marked as alive in our app and date of death is removed from their contact doc.

Once someone is marked as deceased by the app (i.e. has a date of death) then all actions should be disabled for that person and all tasks about them should be cleared. This will be handled in configuration for now. The only action available for a person who is deceased is "undo death" so you can't actually submit multiple death reports in that case. For SMS, it's a bit trickier, but in that case, I'd assume that the health facility staff person assigned to confirm the death would indicate the date when submitting the death confirmation form. If the CHW submitted another death report, it wouldn't change anything because the confirmation already happened.

These workflows were defined with extensive input from our regional designers and I am confident they are correct. The issue of deleting the report could be handled differently, such as having certain types of reports that can't be deleted or by adding a feature that would remove the date of death if the report were deleted (I suspect the first option would be preferred, though we'd need to confirm).

Finally, there is no intention of allowing this date of death field to be editable by anyone, so we aren't going to expose it in the "edit person" form and we won't be training anyone to remove dates of death in that way. The correct process is to request a correction and confirm that a correction is needed before marking someone as alive again. Death reporting has a specific protocol and is completely different from how pregnancies are tracked and monitored so that's why it's being handled differently.

**Comment by sglangevin** [comment]
This is working well and the docs are sufficient. Moving to ready.

**Comment by michaelkohn** [comment]
Thanks for the context @sglangevin Do we have any slide decks or demos you can share for how this workflow is supposed to work?  Or perhaps we can schedule a live demo for the team sometime?

**Comment by sglangevin** [comment]
Yeah, we can definitely do a demo. It's also covered in the release notes for 2.15.0 because that's the first release where we are supporting this workflow. There's more info in the [design spec](https://docs.google.com/document/d/1EKmOdip2cebl_BbIJNbl1kTbG3rYxaxVYmI_mL5y9M8/edit). That doc also has a link to a slide deck with more info.
