### ISSUE TITLE
Move /patches from the root to webapp/patches

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4637]
They only apply to webapp so it makes sense to move them down.

**Comment by garethbowen** [comment]
AT: Make sure the patches are still being applied to the bundled code.

**Comment by newtewt** [comment]
Hey @garethbowen  need some assistance on AT for this one.

1. Can you share some detail how to AT this one?
            // patch font-awesome to remove version attributes so appcache works
            // https://github.com/FortAwesome/Font-Awesome/issues/3286
            'patch webapp/node_modules/font-awesome/less/path.less < webapp/patches/font-awesome-remove-version-attribute.patch',

2. I'm assuming we would need to login as a user with Hindi as the language to see numerals. Where would we expect to see them in the app?
            // patch moment.js to use western arabic (european) numerals in Hindi
            'patch webapp/node_modules/moment/locale/hi.js < webapp/patches/moment-hindi-use-euro-numerals.patch',

**Comment by garethbowen** [comment]
1. Without that patch the font-awesome fonts aren't read from the appcache offline cache, and were instead requested from the server each page load. Bring up the network tab of your browser's dev tools and make sure the font-awesome fonts aren't requested on page load.
2. Yes, switch your locale to Hindi on the user settings page and refresh. Basically all dates in the app are formatted by the moment library. Without this patch the numbers are translated to Hindi characters which we don't want, so make sure all the numbers in dates are "123..." not "१२३...".

**Comment by newtewt** [comment]
These work on my local machine. Once beta.dev comes back up I'll confirm there as well.

**Comment by newtewt** [comment]
Confirmed in beta.dev the patches are still working.
