### ISSUE TITLE
Use asynchronous logging in node apps

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4644]
`console.*` synchronously blocks so is not recommended for production deployments. The express documentation [recommends using logging libraries](https://expressjs.com/en/advanced/best-practice-performance.html#do-logging-correctly) instead.

Replace all existing console invocations and implement a precommit regex check similar to the ones that exist for the webapp to ensure no new calls are added.

**Comment by newtewt** [comment]
Looks good.
