### ISSUE TITLE
Use a robots.txt file to stop spiders crawling our instances

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4645]
Making them a little harder to find if you don't know where to look.

**Comment by garethbowen** [comment]
Code review please @alxndrsn  - I can't think of any reason we'd want spiders to crawl our sites, can you?

AT: Make sure that `/robots.txt` returns:

```
User-agent: *
Disallow: /
```

**Comment by ngaruko** [comment]
LGTM...Tested on alpha.dev (with `https://alpha.dev.medicmobile.org/robots.txt`)
**_Before_** 
![image](https://user-images.githubusercontent.com/6979995/41878506-82984f90-7929-11e8-919f-f7a5f1f8cf83.png)
_**After**_
![image](https://user-images.githubusercontent.com/6979995/41878529-9f8d6e00-7929-11e8-8078-f18162813acb.png)
