### ISSUE TITLE
Action (+) menu cannot be opened on mobile

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4655]
When using the app in mobile view (on laptop Chrome or on a mobile phone), clicking on the + button from a patient profile doesn't open the action menu. If you expand your screen to desktop size, the menu appears.

**Steps to reproduce**:
 - Log in as any user on desktop or mobile
 - Make your screen mobile-sized (if on desktop). Must be <=400px (anything larger and you won't see the bug).
 - Navigate to any patient profile
 - Click on the + button

**What should happen**:
 - A menu should open that lists available actions for that patient

**What actually happens**:
 - Menu doesn't open

Patient profile on beta-old.dev: https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/38d4d96e-6363-4ea5-93c0-286b0e9d75f6

Nothing relevant in the console

**Environment**:

- Instance: beta-old.dev
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.16.0-beta.4

**Other**:
I've tested this on laptop Chrome and on my Tecno and confirmed the issue exists in both places. Perhaps a by-product of the changes made to the action bar for report review?

**Comment by garethbowen** [comment]
The problem was due to a small tweak I made to the filter dropdowns on phones which got accidentally applied to all dropdowns. Should now be fixed.
