### ISSUE TITLE
Remove gammu from the medic-os image

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4656]
Remove `gammu` and `gammu-json` packages. They're not used.

**Comment by garethbowen** [comment]
@browndav What's the state of this issue? Did you want someone to code review it?

**Comment by browndav** [comment]
Yeah, sorry, I direct-committed instead of doing a PR. A review would be appreciated, though it's mostly removals. Hopefully a quick thing.

**Comment by garethbowen** [comment]
LGTM. Thanks!
