### ISSUE TITLE
Make sure we've released the latest version of Horti

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4661]
Before 3.0 is ready to do, make sure that we've tagged (we haven't done so in the past, but we're about to release a version that will be used in production so we should) and published the latest horti changes.

**Comment by garethbowen** [comment]
@SCdF I think we discussed this before, but what version do you think we should go to? I have a preference for `1.0.0` because that indicates, to me at least, that it's ready for production use. What do you think?

**Comment by SCdF** [comment]
My reasoning / logic around incrementing horti releases so far has been:
 - 1.0.0 would indicate that it was in theory usable by a third party: stand-alone (not baked into api / webapp), not hard-coded to Medic specifically, etc
 - 1.0.0 would indicate that we will *definitely* not break backwards compatibility, as well as supporting forwards compatibility in some form (ie at least having the capacity to understand that this version is too old to pull from this build server, or support this version of a deployable)
 - And until those two things were true (right now they are not true) I was just incrementing minors / patches.
 - Or alternatively, we give up on all those goals and just tag when we go live, but that would be messaging that is contradictory to what people have asked for, and we've spent considerable energy on (ie I added namespace / application because of the above goals, why would we now not care?)

@garethbowen if you feel like that is the incorrect approach then we can change it to whatever you want. I think what I'm doing is right (obviously!) but it's not a hill I even care to get scratched on, let alone die on.

**Comment by garethbowen** [comment]
> 1.0.0 would indicate that we will definitely not break backwards compatibility, as well as supporting forwards compatibility in some form (ie at least having the capacity to understand that this version is too old to pull from this build server, or support this version of a deployable)

It means we won't break backwards compatibility without also changing the major. We can absolutely break backwards compatibility whenever we want.

> 1.0.0 would indicate that it was in theory usable by a third party: stand-alone (not baked into api / webapp), not hard-coded to Medic specifically, etc

That's interesting - I've never associated semver with genericness, for example, we semver medic-webapp but it's completely tied to our use case.

> And until those two things were true (right now they are not true)...

I think we have to start ensuring backwards compatibility now that it's going into production.

**Comment by SCdF** [comment]
We are / I am currently endeavouring to maintain backwards compat already, for sure! Arguably to an extreme that is not necessary. Forward is not there yet though (ie we've yet to explode on unknown schema versions), which I still need to do. Mostly though, it's highly baked into Medic stuff still. This is going to naturally change even without others using it: we want to allow for other build repositories so we can run a local one to run E2E tests through, allowing for different apps means we can use it for deploying other server-side tools at medic (reporter?), as well as integration tests where we want to deploy test / fake apps of different configurations.

This ticket is also (and maybe I didn't make this clear) really mostly a note that **we haven't been tagging Horti so far**, which we should start doing, as a matter of process, because it's going to prod. We should, now that I'm thinking about it, start considering release notes and the like as well!

Anyway: you know my very not-important philosophy as noted above, if you feel strongly feel free to ignore / change it, just let me know. IMO semver is really just a shared delusion anyway, we just need to make sure we're all dreaming the same 🙃

**Comment by garethbowen** [comment]
v0.12.0 has been published and tagged. I'll work with @browndav to ensure this is bundled in the medic-os image used for webapp 3.0.0+.
