### ISSUE TITLE
Upgrade to PouchDB 7.0

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4664]
Looks good but has some breaking changes which will require changes.

https://pouchdb.com/2018/06/21/pouchdb-7.0.0.html

**Comment by garethbowen** [comment]
Merged in https://github.com/medic/medic-webapp/commit/87f5dba0ba5a3f280c61b62a06fba6154a285607

**Comment by garethbowen** [comment]
AT: Make sure restricted and unrestricted users work as expected.

**Comment by ngaruko** [comment]
Restricted and unrestricted users seem to work as expected for regular use cases. Closing this and will open a different issue if some related issue pops us in the future.
