### ISSUE TITLE
Performance issues loading contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4666]
Querying the `doc_summaries_by_id` view is _really_ slow. On my Tecno with about 300 docs it takes about 4 seconds just to query the db (ignore rendering, setup, etc). PouchDB is making individual allDocs requests for each of the docs rather than one bulk get. 

I modified the GetDataRecords service to replace the view query with an allDocs request and shaved 2 seconds off the fetch time. If this change is also made for the other queries in the stack I expect to shave another 2 seconds or so off the request making it complete almost immediately.

GetDataRecords is used on the Reports tab too (and maybe other places) so performance improvements here could have broad implications.

Work out why PouchDB is doing so badly, and either fix it or implement the above workaround.

**Comment by garethbowen** [comment]
Results in milliseconds:

| | Tecno | My desktop |
|--|--|--|
| Initial | 4338 | 232 |
| Using allDocs | 906 | 35 |
| Improvement | 3432 (79%) | 197 (85%) |

**Comment by garethbowen** [comment]
Observed performance on Tecno:

| Task | master | patched |
|--|--|--|
| Searching for contacts | 5.0s | 3.6s |
| Searching for reports | 14.9s | 7.3s |
| Autocomplete contacts in an Enketo form | 2.8s | 2.5s |

**Comment by garethbowen** [comment]
Reports seems to be hitting the same underlying issue from a different place. We could workaround this one too but we've probably done enough for 2.16.0. Hopefully we can get the patch in to pouchdb and fix this throughout the app.

**Comment by garethbowen** [comment]
Code review please @dianabarsan 

Feel free to leave the merge to me.

**Comment by garethbowen** [comment]
Merged and backported.

**Comment by sglangevin** [comment]
I'm not sure how to AT this exactly - searching seemed slightly faster on the contacts tab to me but it wasn't a very scientific test. I've also been noticing that the contacts and reports tabs seem to be loading slower than in previous versions, even though the user I'm logged in as doesn't have a ton of data. That is probably a separate issue, though, and I don't think this change has caused it.

**Comment by ngaruko** [comment]
Any clue how to AT this @garethbowen ? Was it only happening on Tecno?

**Comment by ngaruko** [comment]
Feels slightly faster but I think it could be better. For some users, including `admin`, loading reports takes quite sometime (probably due to the high number of docs). Will close this atm....
