### ISSUE TITLE
Emit NODE_OPTIONS during API startup

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#4676]
Doing this proved useful for diagnostic purposes while troubleshooting an OOM issue in production, so I'm adding this issue to get a number for a branch and PR.

```diff
diff --git a/api/server.js b/api/server.js
index b8166191c..29e76f92a 100644
--- a/api/server.js
+++ b/api/server.js
@@ -22,6 +22,7 @@ const nodeVersionCheck = () => {
   if (major < MIN_MAJOR) {
     throw new Error(`Node version ${major}.${minor}.${patch} is not supported, minimum is ${MIN_MAJOR}.0.0`);
   }
+  console.log(`Node Environment Options: '${process.env.NODE_OPTIONS}'`);
   console.log(`Node Version: ${major}.${minor}.${patch} in ${process.env.NODE_ENV || 'development'} mode`);
 };
```

**Comment by ngaruko** [comment]
Getting `undefined` here (both on `alpha.dev` and `local`). Is this because it is not production or ? @browndav @garethbowen ...and is there a need to maybe do as we did on the following log where `development mode` is used as default?  :

``` [2018-07-04 03:52:29] **_Node Environment Options: 'undefined'_**
[2018-07-04 03:52:29] Node Version: 8.9.1 in development mode
[2018-07-04 03:52:30] CouchDB Version: 2.1.1
[2018-07-04 03:52:30] Extracting ddoc?~@?
[2018-07-04 03:52:30] Updating docs: appcache
[2018-07-04 03:52:30] DDoc extraction completed successfully
[2018-07-04 03:52:30] Loading configuration?~@?
[2018-07-04 03:52:30] Configuration loaded successfully
[2018-07-04 03:52:30] Merging translations?~@?
[2018-07-04 03:52:30] Translations merged successfully ```

**Comment by garethbowen** [comment]
@ngaruko That looks fine to me - it just means no node environment options are set. If I recall correctly the newest version of medic-os will set memory options which will be displayed here so you might like to test once that's released and alpha.dev is updated.

**Comment by browndav** [comment]
We can (and really should) set those options. IIRC there's an attempt to set them present in the tree but it appears to be broken. Adding to the short-term to-do list.

**Comment by newtewt** [comment]
Locally you can set those and see them in the log. I would say this is working as expected. @ngaruko can you confirm we can close this?

I am on OS X so I can pass like this.

With Yarn
NODE_OPTIONS=--abort-on-uncaught-exception yarn start
With node directly
NODE_OPTIONS=--abort-on-uncaught-exception node server.js

or set directly in an environment variable. 

export NODE_OPTIONS=--abort-on-uncaught-exception
```
09:47:32 sentinel.1   |  Node Environment Options: '--abort-on-uncaught-exception'
09:47:32 sentinel.1   |  Node Version: 8.11.3 in development mode
09:47:32 sentinel.1   |  info: startup complete.
09:47:32 sentinel.1   |  CouchDB Version: 2.1.1
09:47:33 sentinel.1   |  info: checking schedule again in 4 minutes
09:47:33 sentinel.1   |  warn: Disabled transition "update_clinics"
09:47:33 sentinel.1   |  warn: Disabled transition "registration"
09:47:33 sentinel.1   |  warn: Disabled transition "accept_patient_reports"
09:47:33 sentinel.1   |  warn: Disabled transition "generate_patient_id_on_people"
09:47:33 sentinel.1   |  warn: Disabled transition "default_responses"
09:47:33 sentinel.1   |  warn: Disabled transition "update_sent_by"
09:47:33 sentinel.1   |  warn: Disabled transition "update_sent_forms"
09:47:33 sentinel.1   |  warn: Disabled transition "death_reporting"
09:47:33 sentinel.1   |  warn: Disabled transition "conditional_alerts"
09:47:33 sentinel.1   |  warn: Disabled transition "multi_report_alerts"
09:47:33 sentinel.1   |  warn: Disabled transition "update_notifications"
09:47:33 sentinel.1   |  warn: Disabled transition "update_scheduled_reports"
09:47:33 sentinel.1   |  warn: Disabled transition "resolve_pending"
09:47:33 sentinel.1   |  info: transitions: processing enabled
09:47:33 sentinel.1   |  info: transitions: fetching changes feed, starting from 92-g1AAAACbeJzLYWBgYMpgTmEQTM4vTc5ISXLIyU9OzMnILy7JAUklMiTV____PyuDOVE5FyjAbm6UlmRpaIRNAx5j8liAJEMDkPoPNc0SbFqacZKhpRFW07IAdvYwyA
09:47:33 api.1        |  WARNING: allowing CORS requests to API!
09:47:33 api.1        |  Node Environment Options: '--abort-on-uncaught-exception'``
```

**Comment by ngaruko** [comment]
Thanks @browndav, @garethbowen  and @newtewt . Yes, these can be set on local. There is also in `.env` file created during deployment where we could set these alongside `COUCH_URL` and `COUCH_NODE_NAME`. Generally we prefer to do Acceptance testing on a non-dev instances that are closer to production environments. I will close this unless @browndav needs it open as a reminder to set them on medic-os?

**Comment by browndav** [comment]
See https://github.com/medic/medic-webapp/commit/6456b4e5c3ded32830ced308b57d53df96b5598c. If you believe this to be sufficient, I think we could close.
