### ISSUE TITLE
Dates in outgoing messages are not translated

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4681]
As reported in https://github.com/medic/medic-projects/issues/4338 by @kanikamedic the dates for outgoing SMS messages are not translated.

**Steps to reproduce**:
 - Setup instance with Standard config
 - Create a person
 - Submit a pregnancy report for that person, eg `P 12345 12`

**What should happen**:
 - The auto reply message should have the expected date in the same language as the outgoing message.

**What actually happens**:
 - The auto reply has the expected date in English, regardless of the outgoing message.
![image](https://user-images.githubusercontent.com/789512/42097966-8911deee-7b87-11e8-9feb-4dbb4018bee6.png)

Tested on `2.15.0-beta.8`, and observed on `2.14.4`, and as far back as `2.10.3` as seen in https://github.com/medic/medic-webapp/issues/3336#issue-218996761

We have a special converter for Nepali dates with `bikram_sambat_date`, but other languages use the `date` keyword:

*English*
`messages.p.report_accepted = Thank you for registering the pregnancy for {{patient_name}} ({{patient_id}}). Their EDD is {{\#date}}{{expected_date}}{{/date}}`

*Hindi*
`messages.p.report_accepted = \ {{patient_name}} ({{patient_id}}) कि गर्भावस्था को दर्ज करने के लिए धन्यवाद | उसकी डिलीवरी की अपेक्षित तारीख है {{\#date}}{{expected_date}}{{/date}}`

**Comment by ngaruko** [comment]
Tested on `alpha.dev` with Swahili, French and Hindi as outgoing message languages:
![image](https://user-images.githubusercontent.com/6979995/43238890-3a3db7f8-90e4-11e8-956c-f8fab7c082de.png)

-
![image](https://user-images.githubusercontent.com/6979995/43238929-69009b14-90e4-11e8-8c71-d1502fbfc3b5.png)
--
![image](https://user-images.githubusercontent.com/6979995/43238974-99edde8a-90e4-11e8-97bd-148c593cb85b.png)

LGTM.
