### ISSUE TITLE
Make debugging harder to leave on

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4684]
On the About page we have an option to turn on debugging. This sets a cookie which is checked on startup and if set sets angular and pouchdb to log everything. This is useful for development but should never be left on in a production environment because it slows down the app significantly and blows out feedback docs (related: #4481). I also have trouble turning it off and getting it to stay off suggesting that the cookie deletion code isn't working. We're getting [reports from the field](medic/medic-projects#4343) which indicate some users have this turned on so it's a problem in the wild.

1. Decide whether we want debugging to be sticky - perhaps it should just stay on until refresh, or maybe it should only be sticky in development mode.
2. Consider disabling debugging altogether in a production environment.
3. Work out how to make sure turning debugging off actually disables it after refresh.

**Comment by ngaruko** [comment]
LGTM. Available on [`local`](http://localhost:5988/medic/_design/medic/_rewrite/#/about), but not on [`alpha.dev`](https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/#/about). Version 3.1.0
