### ISSUE TITLE
Translation key not translated for Task in Contact page

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4690]
Tasks use translation keys as part of https://github.com/medic/medic-webapp/issues/3190, but the task in a profile page is not fully translated:

## Translation in config
`task.warning.home_birth = Home Birth`

## Task in [tasks tab](https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/tasks/)
![pasted image at 2018_07_02 06_05 pm](https://user-images.githubusercontent.com/789512/42190677-842376a2-7e2c-11e8-9fc7-6556f2953b69.png)

## Task on [person's profile](https://standard.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/5274e095-40ae-481c-b669-cb915c6765b9)
![image 2](https://user-images.githubusercontent.com/789512/42190678-84327508-7e2c-11e8-82b0-9dddc73bcddb.png)

Shown in `2.16.0-beta.7` with user `healthcenter` on standard.dev running this [Standard config](https://github.com/medic/medic-webapp/tree/3e424722bb9760d23ffab0f36b1dbcf85efc0492/config/standard) in progress for 2.16.

**Comment by garethbowen** [comment]
Code review please @dianabarsan . Needs merging and forward porting to `master`.

**Comment by dianabarsan** [comment]
Merged and forward ported to `master`.

**Comment by abbyad** [comment]
Seen to work on standard.dev running 2.16.0-beta.8:

![image](https://user-images.githubusercontent.com/789512/42230977-4c7de9e4-7eb8-11e8-8a0e-30b9f01bdcd2.png)
