### ISSUE TITLE
Family Survey fields are showing translation key

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4696]
Viewing the report on a family survey is showing the translation keys. 

**Steps to reproduce**:
Navigate to Reports 
Select a Family Survey

**What should happen**:
 User is taken to reports tab with the completed Family Survey displayed with appropriate labels in current language.

**What actually happens**:
User is taken to reports tab with the completed Family Survey and the translation keys are shown to the user. 

https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/195a7188-6d5c-471d-af8d-98c858f6df1f

Console logs: inbox.js:3 Translation for report.family_survey.meta.instanceID doesn't exist

List of keys missing. 
report.family_survey.place_id
report.family_survey.place_name
report.family_survey.use_treated_water
report.family_survey.how_water_treated
report.family_survey.LLIN
report.family_survey.latrine
report.family_survey.hand_washing_facilities
report.family_survey.access_to
report.family_survey.access_to.electricity
report.family_survey.access_to.Q1_NAT
report.family_survey.access_to.Q1_URB
report.family_survey.access_to.television
report.family_survey.access_to.Q2_NAT
report.family_survey.access_to.Q2_URB
report.family_survey.access_to.sofa
report.family_survey.access_to.Q3_NAT
report.family_survey.access_to.Q3_URB
report.family_survey.access_to.cupboard
report.family_survey.access_to.Q4_NAT
report.family_survey.access_to.Q4_URB
report.family_survey.access_to.dvd
report.family_survey.access_to.Q5_NAT
report.family_survey.access_to.Q5_URB
report.family_survey.access_to.radio
report.family_survey.access_to.Q6_NAT
report.family_survey.access_to.Q6_URB
report.family_survey.access_to.table
report.family_survey.access_to.Q7_NAT
report.family_survey.access_to.Q7_URB
report.family_survey.access_to.clock
report.family_survey.access_to.Q8_NAT
report.family_survey.access_to.Q8_URB
report.family_survey.floor
report.family_survey.Q9_NAT
report.family_survey.Q9_URB
report.family_survey.walls
report.family_survey.Q10_NAT
report.family_survey.Q10_URB
report.family_survey.roof
report.family_survey.Q11_NAT
report.family_survey.Q11_URB
report.family_survey.fuel
report.family_survey.Q12_NAT
report.family_survey.Q12_URB
report.family_survey.toilet
nofacility_bush_field
report.family_survey.Q13_NAT
report.family_survey.Q13_URB
report.family_survey.education
report.family_survey.NationalScore
report.family_survey.UrbanScore
report.family_survey.NationalQuintile
report.family_survey.UrbanQuintile
report.family_survey.b
report.family_survey.b.g_use_treated_water
report.family_survey.b.g_LLIN
report.family_survey.b.g_latrine
report.family_survey.b.g_hand_washing_facilities
report.family_survey.meta
report.family_survey.meta.instanceID

![screen shot 2018-07-03 at 1 09 34 pm](https://user-images.githubusercontent.com/10531066/42234386-5f2a0078-7ec2-11e8-8e55-caf479deea32.png)

**Environment**:

- Instance: beta-old.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.16.0-beta.7

**Other**:
Looking at the messages-en.properties file there doesn't seem to be a key value pair for anything with report.family_survey. Not 100% sure about how everything connects in the app/site just yet but figured I'd add that note.

**Comment by sglangevin** [comment]
Thanks for reporting this. Translations for these need to be added to the translations files and it just means that that wasn't done for this particular type of report. We tend not to bother with the translations when testing but we do want to make sure they exist in production. Perhaps there is a way we can warn configurers if translations are missing?

**Comment by garethbowen** [comment]
@newtewt What configuration was this using? standard?

**Comment by newtewt** [comment]
@garethbowen  I'm not sure. At that point in time it would have been what was already setup for beta-old as I'm sure I didn't understand how configs worked then. I'm thinking we can probably close this one.

**Comment by garethbowen** [comment]
Thanks Nick. Closing unless it happens again.
