### ISSUE TITLE
Renaming an Area after generating a report will not update the report names

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4697]
Renaming an area that has existing reports will not update the name of the reports in the reports table for an area. However, the name is updated when viewing reports on the reports tab or in the detail of the report.  Screenshots show the name being displayed differently based on where you are viewing the report from. 

**Steps to reproduce**:
 Navigate to an Area that has reports associated to it.
Navigate to District > Health Center > Area 
EX: Nick's District > Ohio Health > Scioto Area > New Action > Family Survey.
Click Edit 
Change Name of Area
Submit

**What should happen**:
 The area is renamed and the reports associated Area is also updated.  Could @sglangevin  or @amandacilek  way in on the actual expected behavior. 

**What actually happens**:
The area is renamed but the reports remain on the previous Area name. When clicking on the report it shows the updated Area name. 

https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/9740715e-6af9-4f1d-b299-96fe0fddd2bb

Show's the issue on the area. Where the names show differently.
![screen shot 2018-07-03 at 1 40 37 pm](https://user-images.githubusercontent.com/10531066/42235825-edd03668-7ec6-11e8-9d24-8b34cb0c4273.png)

Show's the report being displayed on the reports tab with the updated name. 
![screen shot 2018-07-03 at 1 40 45 pm](https://user-images.githubusercontent.com/10531066/42235826-ede38542-7ec6-11e8-9e9e-7218d1609ab5.png)
![screen shot 2018-07-03 at 1 40 51 pm](https://user-images.githubusercontent.com/10531066/42235827-edf429a6-7ec6-11e8-8725-ebe3e0a1bad3.png)

**Environment**:

- Instance: beta-old.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.16.0-beta.7

**Comment by amandacilek** [comment]
Hm, this sounds like a bug to me! Expected behavior as I understand it would be that the updated name replaces the old name _in all locations_ where that name appears.

**Comment by ngaruko** [comment]
This one still seem like inconsistent. The name in the report does not seem to update. Is this expected @wtekeu ?
![image](https://user-images.githubusercontent.com/6979995/51097305-e4078500-1827-11e9-9a4e-0db58e2a362a.png)

**Comment by wtekeu** [comment]
@ngaruko Please note that you have to produce a report that has the area name in its title .. something like a family survey .. I think the report that you produced is for a new pregnancy which has the person name in its title and not the area name

**Comment by ngaruko** [comment]
@wtekeu seems to work as expected. Maybe it needed a refresh. Will close this atm.
![image](https://user-images.githubusercontent.com/6979995/51163348-37e49d80-18fe-11e9-9ef5-cc746501fb68.png)
