### ISSUE TITLE
Sending an SMS to all contacts in a place doesn't work as expected

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#4708]
If you select a facility name (all contacts) in the To field of an unstructured SMS, when you send the message, an SMS is sent to the primary contact of the facility but none of the CHWs whose areas are below that facility in the hierarchy.

**Steps to reproduce**:
 - Go to the messages tab
 - Click the + (send message)
 - Search for a health facility and select the option that says [facility name] - all contacts
 - Type in a message and click send
 - Notice that messages are only sent to people who are direct descendants of the facility

**What should happen**:
 - A message should be sent to the CHW (primary contact) for each of the areas that are below the facility in the hierarchy

**What actually happens**:
 - Messages are sent to the facility primary contact and any people who are direct descendants of the facility

https://beta-old.dev.medicmobile.org/medic/_design/medic/_rewrite/#/messages/phone:+14152319901

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: beta-old.dev
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 2.16.0-beta.8

It's possible that this is a misinterpretation of how "message all" should work, but this is how projects would like to use that feature.

**Comment by ngaruko** [comment]
This still doesn't seem to work in 3.1.0 ([gamma.dev](https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/messages)). Interestingly enough the message count goes up when the message is sent to all contacts but messages are not displayed...
![image](https://user-images.githubusercontent.com/6979995/46588565-05572780-cafb-11e8-9fa8-cbb3738b79c9.png)

**Comment by garethbowen** [comment]
@vimemo Can you look at this when you get a chance?

**Comment by vimemo** [comment]
@ngaruko, the fix should be in the next 3.1 release. thank you.

**Comment by ngaruko** [comment]
Thanks @vimemo . It definitely looks better than it was before. However, the message sent to `all contacts` shows only on the main district contact and not to other contacts below the hierarchy. In the screenshots below, the `test victor-all` message was sent to `all contacts`, which means it should go to both Victor (district contact) and Gomez (HC contact under victor), but it is only sent to Victor and NOT to Gomez. 
![image](https://user-images.githubusercontent.com/6979995/47398595-38ebb000-d791-11e8-8e00-76150edffe59.png)
![image](https://user-images.githubusercontent.com/6979995/47398636-6f292f80-d791-11e8-8f85-f0c1ba5fbc46.png)

**Comment by vimemo** [comment]
hi @ngaruko, this fix should be in the next release. thank you.

**Comment by ngaruko** [comment]
Thanks @vimemo.  Messages sent to all are reaching the main contact and all contacts directly below that in the hierarchy, just to one level (when we have more than 2 levels like `District/Healthcenter/area`). Not sure if that is what is supposed to happen @garethbowen or if the message should go to all contacts deeper below in the hierarchy, not just those directly descendants of the main contact. In this scenario for example, I wonder if the expectation is for the messages sent to the 'District` contact should also go to the area's contacts, not just to health center contacts.

**Comment by garethbowen** [comment]
@ngaruko I'm fairly sure this is the expected and existing behaviour.
