### ISSUE TITLE
Error is shown when removing a users place and submitting the change

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4712]
Trying to remove a user from a place is not possible. You can only assign a user to another place. Pressing the X to remove the place then submitting will generate an error. 

**Steps to reproduce**:
Log in as an admin user
Navigate to users
Click on a user associated to a place. 
Press the x to remove the place
Click submit. 

**What should happen**:
The user data is updated and the user is removed from the place.

**What actually happens**:
Error updating user is displayed and the user is not updated. 

{"code":400,"error":"One of the following fields are required: password, known, place, type, roles, fullname, email, phone, language, contact, external_id"}

**Environment**:

- Instance: local env, https://beta-old.dev.medicmobile.org/
- Browser: Chrome
- Client platform: MacOS
- App:  admin
- Version: 3.0.0

**Comment by sglangevin** [comment]
If the user has access to data offline, then the place is a required field. Sounds like a clearer error message could help. If this was an online-only user, then a definite bug.

**Comment by newtewt** [comment]
Using the beta-old instance this was a online user per the role configuration.

**Comment by garethbowen** [comment]
Moving this up to 3.1.0 as it's ready to merge now.

**Comment by garethbowen** [comment]
Merged.

**Comment by ngaruko** [comment]
LGTM on `gamma.dev`. Do you think we need to test it on `beta` (if it still runs) @newtewt ?
