### ISSUE TITLE
Fix horticulturalist timeouts

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4719]
Horticulturalist requests, both to the build server and to the app server sometimes time out.

We already have [one hack](https://github.com/medic/horticulturalist/blob/master/src/install/index.js#L41-L85) where we fall back from a problematic bulk docs call to individual writes if needed.

However, we don't do that everywhere, and we are also suffering occasional timeouts in other requests, including bulk gets.

We should:
 - Work out how to set the default PouchDB timeout to something longer. At one point I learnt it was this: `new PouchDB(url, { ajax: { timeout: 65536 }})`, but I can no longer find any reference to that on the internet. Maybe it works, maybe it doesn't. If we do this we would also want to then *shorten* the timeout on the [view warmer](https://github.com/medic/horticulturalist/blob/master/src/install/index.js#L175-L190) so that we get UI updates more frequently (the pattern is: request a view; when it times out update progress; re-request).
 - Work out how to set request timeouts per request, and wrap all PouchDB calls
 - Decide that we're OK with Horti dying on timeout, treat it as an opportunity to restart whatever process it was doing (ie deploying). I don't really like this: it works in MedicOS because something is managing horti, but locally there is no management, and it should work in this instance.

**Comment by garethbowen** [comment]
I'd prioritise this higher than "low" - alpha.dev was down for just under 2 hours.

**Comment by browndav** [comment]
Do we know the root cause of the timeouts yet? Do we think we might be looking at a CouchDB or API perf issue underlying this, or some other failure mode?

**Comment by SCdF** [comment]
@garethbowen yep fair call, OK let's fix it before we go live, added to 3.0.0

@browndav so the two places I've seen this have both been bulk calls dealing with moving secondary ddocs around. I'm wondering if either bulk calls are scheduled differently in CouchDB or something, or if it's just that they are larger requests in general and so we're more likely to hit the 10 second limit.

What we can do really easily is the first point above (increase the timeout), I just got confused by the documentation changing to 7.0 and dropping the api I thought was right.

**Comment by garethbowen** [comment]
@SCdF Looks good. Back to you.

Yeah an integration test sounds good. This will also be tested once we have travis use horti to start up our app for e2e testing rather than dev scripts.

**Comment by SCdF** [comment]
@garethbowen great point. I think we can work this from two angles then: horticulturalist has some int. tests that always tests against medic master (pulled from our for realz builds server), and medic has its E2E tests running under the latest published horti. That way if work on horti breaks for medic we'll catch it, and if medic does something that breaks horti's expectations we'll catch that too.

**Comment by SCdF** [comment]
(no AT for this, the issue is really flaky and hard to reproduce. This is not a guarantee that we've fixed the bug, more that we've done what we can for now and we'll plug more holes as we find them)
