### ISSUE TITLE
Transfer pojo2xml to medic

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4727]
Currently only @alxndrsn can contribute or publish pojo2xml.

- Move the [GH repo](https://github.com/alxndrsn/pojo2xml) to medic
- Add the [npm package](https://www.npmjs.com/package/pojo2xml) to the medic npm org

**Comment by garethbowen** [comment]
Code merged, thanks!

Could you also add the npm package to the medic npm org? I think if you go to [the medic developers page](https://www.npmjs.com/settings/medic/teams/team/developers/access) you will be able to search for and add the pojo2xml package to our team so anyone can publish.

**Comment by alxndrsn** [comment]
Done :+1:

**Comment by garethbowen** [comment]
Perfect!
