### ISSUE TITLE
Medic-Android Target API needs to be upgraded

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4733]
The app currently targets API level 24 and will have to target at least API level 26 to ensure it's built on the latest APIs optimized for security and performance.  Starting from August 2018, new apps must target at least Android 8.0 (API level 26) and starting from Nov 2018, app updates must target Android 8.0 (API level 26).  If this affects projects on the ground using old phones, this needs to be taken care of before Nov 2018.

Here's the entire warning:
```
Target API level requirements from August 2018
Warning:

Your app currently targets API level 24 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.

From August 2018, new apps must target at least Android 8.0 (API level 26).
From November 2018, app updates must target Android 8.0 (API level 26).
```

**Comment by browndav** [comment]
If this will block Play Store publication IMO this is priority zero – critical.

**Comment by browndav** [comment]
This doesn't affect `minSdkVersion` AFAICT; I misread. I think we still have some research to do and may need to work through some issues when we bump `targetSdkVersion`, but it doesn't look like this blocks Play Store publication in any way. Reverting priority; sorry for the noise.

**Comment by browndav** [comment]
Target APIs below 26:
https://github.com/medic/medic-android/blob/master/src/main/AndroidManifest.xml#L8
https://github.com/medic/medic-gateway/blob/master/src/main/AndroidManifest.xml#L12

Play Store distribution issues are completely ruled out per documentation, but there still may be changes to make due to API or functionality changes in the new target (e.g. sleep/wake, background processes, Chromium integration/build).

**Comment by newtewt** [comment]
Would it make sense to also upgrade our project for the new gradle 3.0 plugin as part of this?

https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration

**Comment by henokgetachew** [comment]
I have taken care of this. Please reopen if any issue is found with the changes to the target API.

**Comment by henokgetachew** [comment]
Reopening as medic-gateway still needs to be upgraded.

**Comment by SCdF** [comment]
@henokgetachew did you check the bit about the app menu?
```
<!-- When upgrading targetSdkVersion, check that the app menu still
		works on newer devices. -->
```

**Comment by garethbowen** [comment]
I'll add this to 3.0.0 for AT.

**Comment by newtewt** [comment]
I have tested medic-android on a pixel 2 running 8.1.0. I don't have a device running an older version to validate it works there as well.

**Comment by newtewt** [comment]
@henokgetachew is there a android build for medic-gateway? I don't see any newer releases.

**Comment by ngaruko** [comment]
And @henokgetachew @browndav , looks like `medic-gateway` target version is 23 instead of 26 ?  https://github.com/medic/medic-gateway/blob/master/src/main/AndroidManifest.xml#L12

**Comment by henokgetachew** [comment]
>@henokgetachew is there a android build for medic-gateway? I don't see any newer releases.
I will work on the changes this week and get back to you on this.

**Comment by ngaruko** [comment]
I guess this one is still WIP. Moving it back to `Active Work` while waiting for @henokgetachew to sort it out.

**Comment by garethbowen** [comment]
I'm going to remove this from 3.0.0 because it shouldn't block the release of the webapp.

**Comment by henokgetachew** [comment]
I have created a new issue to track the medic-gateway issue [here](https://github.com/medic/medic-webapp/issues/4796) because it involves more work.  I'm moving this one to AT.

**Comment by alxndrsn** [comment]
![screenshot_2018-10-01_20-55-29](https://user-images.githubusercontent.com/191496/46309419-98083b80-c5bc-11e8-9390-596ccb974328.png)

Moved to Active Work, as build has been broken by recent changes, likely related.

**Comment by alxndrsn** [comment]
As this is no longer in AT, I assume it's been passed.
