### ISSUE TITLE
Include mRDT in a webapp release

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4743]
The mrdt work has been done in the [`mrdt`](https://github.com/medic/medic-webapp/tree/mrdt) branch for testing. For wider testing in a project we need to include it in a medic-webapp release.

**Comment by garethbowen** [comment]
For AT you'll need an updated medic-android that includes #4744 and also the 3rd party android app which takes the photos. @browndav Do we have access to this app?

**Comment by garethbowen** [comment]
Code review please @dianabarsan 

This needs backporting to `2.17.x` and `3.0.x` - feel free to leave the merging to me!

**Comment by newtewt** [comment]
Verified in 2.17 and 3.0 that images are displaying from the MRDT app
