### ISSUE TITLE
Add icon to patients who are overdue for a visit

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4747]
This issue is to be included in a quick 2.16.1 release.

We would like to add a red warning icon next to the second row of text (the date last visited) if the date last visited is over a month ago. This extra visual cue will help to draw extra attention to those families most needing a visit. 

We will use the same icon of the exclamation point inside of a red triangle that we have used elsewhere in our app to signify danger signs or high priority. Unclear if the icon currently in use is FontAwesome or custom png, but let's match what we're already using: 

If it is FontAwesome, I believe it should be fa-exclamation-triangle [ & # x f 0 7 1 ; ]. The size should be 16px.

If png, we have a new icon of this in the icon library. [https://github.com/medic/medic-projects/blob/master/icon-library/forms_tasks_targets/PNGs/icon-healthcare-warning%402x.png](url). The size should be 20x20px (smaller than our normal 30x30 size).

The icon should be positioned to the left of the date last visited text, aligned underneath the family name above (positioned 50px from the far left edge of the row). Colored red #E0381F.

![screen shot 2018-07-20 at 10 41 56 am](https://user-images.githubusercontent.com/26235957/43017029-9540a118-8c09-11e8-8f9c-90a1adf7452f.png)

**Comment by garethbowen** [comment]
Merged and forward ported to `3.0.x` and `master`.

**Comment by ngaruko** [comment]
LGTM. One caveat though: I was expecting the `33 days` to be converted into `1 month` @garethbowen ?

**Comment by ngaruko** [comment]
![image](https://user-images.githubusercontent.com/6979995/43058162-2e4cd61e-8e9a-11e8-80c5-6f9f8e0a4a6e.png)

**Comment by garethbowen** [comment]
The date is unrelated to the icon. IIRC think it switches over at 2 months.
