### ISSUE TITLE
Make People page default sort configurable (UHC mode)

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4752]
Right now the default sort for the People page list is always "Alphabetically'. What we'd like to do is make the default sort configurable. This way, projects that are prioritizing UHC mode can configure the list to sort "By date last visited" by default if they like. 

This has nothing to do with the sort options icon or menu. Users should still be able to toggle between sorting alphabetically or by date at will.

EDIT: Gareth brought up the possibility of simply defaulting all UHC projects to sort "by date last visited". I originally thought that would be fine, but now I think we should try to make it configurable. Here's why: we are now adding in counts of visits per month as well. Although we do not currently have a sort for "By number of visits this month" I can see that coming up anytime. When it does, we probably would want to give partners the choice between setting the default sort to "By date last visited" or "By number of visits this month". Why give them a choice? Because some partners have very specific goals for number of visits per month (like Muso) while others do not.

**Comment by dianabarsan** [comment]
Merged into `2.18` and forward ported to `3.0.x` and `master`.

**Comment by dianabarsan** [comment]
To enable default contact sorting to be based on last visited date, you need to configure it in `app_settings`. Add the following section:

```
"uhc": {
    "contacts_default_sort": "",
    "visit_count": {
        "month_start_date": 1,
        "visit_count_goal": 0
     }
}
```

where:

 Setting                        | Default           | Accepted values              | Description                                                                                                                             
--------------------------------|-------------------|------------------------------|------------------------------------------------------------------------------------------------------------------------------------------
 contacts_default_sort          | empty string | * | **last_visited_date**: default contact sorting will be based on last visited date *: default contact sorting will be alphabetical 
 visit_count / month_start_date | 1                 | 1-31                         | Designates the monthly date when the visit count is reset.                                                                               
 visit_count / visit_count_goal | 0                 | integer >= 0                 | Designates the monthly visit count goal.

**Comment by ngaruko** [comment]
Tested on `beta-old.dev`. Just a note for the QA team attempting to test this. One way to do it is : 

- Go to the instance settings page '/dashboard/_design/dashboard/_rewrite/settings#/apps` (like [here](https://beta-old.dev.medicmobile.org/dashboard/_design/dashboard/_rewrite/settings#/apps) for beta-old)
-Click `settings`
![image](https://user-images.githubusercontent.com/6979995/44690744-06cf1200-aab0-11e8-8531-12d595ffaf70.png)
- Click `App Settings` then `Back up`
- The settings will be downloaded 
-Go to folder/directory where the file was saved. Rename it to `app_settings.json`
- Change the `contacts_default_sort` in `uhc` to `last_visited_date ` (to set the default sort to `last visited date`). Save.
```
 "uhc": {
        "contacts_default_sort": "last_visited_date",
        "visit_count": {
            "month_start_date": 1,
            "visit_count_goal": 2
        }
    }
```
- Open terminal in the folder and run `medic-conf --instance beta-old.dev upload-app-settings`
- Back to webapp. Verify default sort changes are applied
* Same sort of process for testing #4758

**Comment by abbyad** [comment]
Thanks for the detailed notes! Using Dashboard to manage app settings can be problematic, so we've tried to use only `medic-conf`. You got around the worst of it by uploading via medic-conf, and you could also use medic-conf's `backup-app-settings` action to avoid using Dashboard altogether.

**Comment by garethbowen** [comment]
Documentation added here: https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings
