### ISSUE TITLE
Deleting error-report not replicating properly

### ISSUE THREAD

**Issue by ngaruko** [medic/medic-webapp#4754]
I deleted a report in couchdb while still open in the UI. Back to UI, the LHS still shows the report…

**Steps to reproduce**:
 -_ Login `alpha.dev` as admin (or other instance)_
 - _Create a report via sms with an invalid data: eg send sms (using admin console or otherwise): `1!C!125#Romeo` _
-_Notice that the report appears on the LHS in the UI
![image](https://user-images.githubusercontent.com/6979995/43229257-50e3c8fc-90b8-11e8-84a2-2b33612cb249.png)
 _
-_Click on the report and notice is opens in the RHS with correct error message_
![image](https://user-images.githubusercontent.com/6979995/43229432-d4da66d4-90b8-11e8-80cf-ca4e43bd5ac0.png)

_copy the report uuid, delete the doc in Futon (or maybe other non-UI ways to delete the report)_
 _Look back at the UI_

**What should happen**:
 - _the report should be completely deleted from the UI_
-_The browser should redirect to `/_design/medic/_rewrite/#/reports/`_

**What actually happens**:
 - _The report still shows in the LHS (until a manual refresh)_
-_The url still has the report id_
![image](https://user-images.githubusercontent.com/6979995/43229723-e423a21c-90b9-11e8-9bc9-d1d98b7627fa.png)
- _Error in console_
![image](https://user-images.githubusercontent.com/6979995/43229893-6bd3ef14-90ba-11e8-98ef-7b7b21176732.png)

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: _(tested alpha.dev.medicmobile.org, and beta-old)_
- Browser: _(Firefox, Chrome)_
- Client platform: _(MacOS)_
- App: _(webapp)_
- Version: _(2.16.1-beta.1, 3.1.0)_

**Other**:
_The UI `delete` works as expected in this case_

**Comment by garethbowen** [comment]
@ngaruko 
1. What user were you logged in as, admin or restricted?
2. How did you delete the doc? With the "delete" button or by editing the doc to have `_deleted: true`?

**Comment by ngaruko** [comment]
LGTM
