### ISSUE TITLE
The image upload enketo widget relies on the form name matching the xml instance element

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4755]
In the Enketo service `xmlToDocs` function we get files such as photos that were uploaded with the form submission and attach them to the report doc. The attachment is named by the xpath to the field with `user-file` as a prefix, eg: `user-file/mrdt/mrdt_image_data`. In this example the `mrdt` bit is the root element of the xform instance, eg:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>MRDT Demo</h:title>
    <model>
      <instance>
        <mrdt delimiter="#" id="mrdt_demo">
          <name/>
          <mrdt_image_data type="binary"/>
          <meta>
            <instanceID/>
          </meta>
        </mrdt>
      </instance>
      <bind nodeset="/mrdt/name" type="string"/>
      <bind nodeset="/mrdt/mrdt_image_data" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/mrdt">
      <label>Submit a photo of an MRDT test result</label>
      <input ref="/mrdt/name">
        <label>Patient name</label>
      </input>
      <input ref="/mrdt/mrdt_image_data" appearance="mrdt-verify">
        <label>MRDT image</label>
      </input>
    </group>
  </h:body>
</h:html>
```

When rendering the submitted report we call the ReportViewModelGenerator service `getFields` function which checks to see if there's an attachment with a name that matches the field. It builds the expected name by concatenating "user-file", the report's `form` field, and the name of the field it's inspecting. The report's `form` field comes from the `internalId` of the form doc that was used to submit the report. This `internalId` can be different from the instance name used originally.

We should make the code that stores the image consistent with the code that displays the image so there isn't this requirement to have the two variables match. This solution has to be backwards compatible so reports submitted with the old code will still display the image correctly.

Currently medic-conf warns but doesn't block if the two don't match so it's possible this isn't affecting anyone in production, but it did just cost me a few hours of head scratching.

**Comment by newtewt** [comment]
Submitted a form prior to this fix with image and submitted one after the fix. Both are displaying images appropriately.
