### ISSUE TITLE
Stop sending SMS to a number that send a "STOP" message

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#476]
Some countries require that no more further SMS be sent to someone that sends a STOP message. Although our SMS are not unsolicited, we may still need to comply with this regulation for India.

Note that we still want to differentiate a "STOP" from "STOP 12345", because the latter is used to mute a set of appointment notification (for patient 12345).

**Comment by abbyad** [comment]
Note that this not come up again lately, but could be an issue as we launch our Standard soon.

**Comment by garethbowen** [comment]
@abbyad Are you thinking this would be hardcoded in the app rather than a configurable form? And it would just add the phone number to a "do not send" list that would be checked before creating messages (maybe setting them to the [denied state](https://github.com/medic/medic-docs/blob/master/md/message-states.md))?

**Comment by abbyad** [comment]
Being hardcoded seems sufficient. I can't find specific info, but seems as though `STOP` is the defacto standard worldwide. Option of having other keywords may help, but we can add that later if needed. Looks like we'd add the phone number to the [`outgoing_deny_list`](https://github.com/medic/medic-webapp/blob/743a58ef43ac715d091837567ea83cd6d9300d84/kanso.json#L244-L248).

In the US the FCC requires a response to the STOP message saying the company name and a message stating that they have opted out (eg "You have opted out. You will not receive additional messages from {{company name}}"). I think it's fair to assume matching that requirement is sufficient for now.

**Comment by garethbowen** [comment]
Wait, so we're legally required to message someone when they've asked not to be messaged? Genius... Maybe it'd be easier as a configurable form (configurable form name, response messages, etc)

**Comment by garethbowen** [comment]
Ok it sounds like we should do this and it shouldn't be too hard. Scheduling.

**Comment by estellecomment** [comment]
Having the same keyword for "a patient moved to a different area so stop messaging me about them" and for "i'm not a chw any more stop messaging me altogether" sounds a bit tricky. It's likely people will use the 2nd by accident.

How do you un-stop? Is there a standard for that? START? Or just un-stop a CHW when they submit a form, assuming they want to get back in? 
If you un-stop, do we re-enable all your past schedules, or just send you messages from now on?

**Comment by estellecomment** [comment]
@abbyad @diannakane ^

**Comment by sglangevin** [comment]
@estellecomment for "a patient moved so stop messaging me about them" we have the OFF form. The reverse of OFF is ON, in case you do it by accident or a patient comes back and you want to re-start the messages.

**Comment by garethbowen** [comment]
Not a priority right now. Leaving scheduled, but removing from the iteration.
