### ISSUE TITLE
Allow child textform registrations up to 5 years old

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4762]
When moving from immunization only to integrated child health schedules the maximum age for child registrations went from 2 to 5 years old. The forms were updated but not everywhere, as seen in https://github.com/medic/medic-projects/issues/4494. The fix was temporarily made to the project config via https://github.com/medic/medic-projects/commit/a48227b1089ec31f6a87f277e08e0db105c5ce4c and needs to be brought into the Standard config.

**Comment by garethbowen** [comment]
@abbyad Which version should this be included in? I want to say 3.1.0 but need to check how standard configurations are imported now that standard is in webapp.

**Comment by abbyad** [comment]
I think we'll want this in master since that is what is referenced from the child settings ([example here](https://github.com/medic/medic-projects/blob/58f1ac4c79d21b5455e5448bf73c4872b3712f8c/cmmb-ke/settings.inherit.json#L2), and [associated package.json](https://github.com/medic/medic-projects/blob/58f1ac4c79d21b5455e5448bf73c4872b3712f8c/cmmb-ke/package.json#L10)), but open to other suggestions.

**Comment by garethbowen** [comment]
@abbyad I mean, when should the work be done? Currently it's not scheduled.

**Comment by abbyad** [comment]
Ah, in that case it should be scheduled now. 

Next round of changes for standard are being done in the [standard-for-2.16](https://github.com/medic/medic-webapp/tree/standard-for-2.16.x) branch.

**Comment by abbyad** [comment]
Updated in master and merged those changes back into the standard-for-2.16 branch.

**Comment by garethbowen** [comment]
Assigning @vimemo for code review, please. It's already been merged but it's a good chance to get more familiar with standard config.

**Comment by vimemo** [comment]
cool. it's good to be aware of this. thank you @garethbowen.

**Comment by garethbowen** [comment]
Reopening for AT

**Comment by newtewt** [comment]
I'm looking in the 2.18.x branch and the config/standard folder is not there. Would AT for this be to take from master and use against 2.18.x? @abbyad  @garethbowen

**Comment by garethbowen** [comment]
@newtewt It looks like it's in the `standard-for-2.16.x` branch for some reason. Try that one.

**Comment by abbyad** [comment]
I believe standard config was added to master recently, post 3.x split, but the config was for 2.14. In the `standard-for-2.16.x` branch we were updating the config for 2.16, but it's still in dev. We haven't updated Standard yet with the quick succession of releases, so it is fair to assume that it will be for 2.18.

**Comment by newtewt** [comment]
Used the standard config from branch standard-for-2.16.x on beta-old and able to submit forms with weeks_since_birth up to 260
