### ISSUE TITLE
Error while submitting form with file uploads

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4763]
Submitting a form which contains a file upload results in the following error:

![image](https://user-images.githubusercontent.com/35681649/43392333-0aadebaa-93fc-11e8-8a19-4669217e7dba.png)

**Comment by dianabarsan** [comment]
Merged into `2.17.x` and forward ported to `3.0.x` and `master`.

**Comment by newtewt** [comment]
Images are uploading in 2.17
