### ISSUE TITLE
Update the on/off handling to mark an individual as muted

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4768]
This request is a continuation of the request in ticket #4767. 

Full details and additional screenshots can be found in the design spec: https://docs.google.com/document/d/1we_Qu1B4x8PuAi9pxiIu4MeXtdH1kY9W29kMidHThsc/edit?usp=sharing

**Summary**
We already partially support individual muting with the On/Off form, however this mutes pre-existing SMS schedules only and does not “mark” or style the person as muted. There is some additional dev required to update our current On/Off functionality. We would like to update and replace on/off with a new full individual muting feature, and this should ideally happen at same time as family/place muting.

**How it currently works**
The individual muting that we have so far can be done via SMS or App forms, BUT mutes pre-existing SMS schedules only. This means that for subsequent pregnancies new messages will be scheduled and sent.

How it currently works with SMS: turns existing notifications for a person on or off. Mutes all outgoing messages in those schedules for that person. If you submit a new pregnancy, you would continue to get those new messages - you only turned off existing schedules, not new schedules.

How it currently works with webapp: turn notifications off, mutes existing SMS schedules, not future. You can also decide to remove/hide tasks, targets (we’re not doing this for any project right now though).

**Desired changes**
- The form should be called “Mute” instead of “On/Off” (believe this is just config)
- We should actually mark the individual as “Muted”
- We should make the UI changes to their profile to reflect the “Muted” status
- All pre-existing and future messages and tasks should be muted, until such time as the person is unmuted
- Unmuting an individual person in a muted place should also unmute the entire place and people in it (because we don’t allow unmuted individuals underneath a muted place). We should be clear about what will happen on the first page of the individual person’s “unmute” action form.

![screen shot 2018-08-01 at 1 55 23 pm](https://user-images.githubusercontent.com/26235957/43548386-9c7bfc74-9592-11e8-8576-7aaf9cf9ce84.png)

**UI changes to the family profile**
- If an individual is muted from an individual on/off form, then the greater family remains unmuted, and there is no change to that family’s appearance (family icons stays pink, no “Muted” text)
- There _should_ be a change made to the “Family Members” condition card. Any individuals that are muted within an unmuted family should be specially styled in this card so that they stand out from active unmuted family members. 
- Suggestion: The person’s name becomes grey, and instead of (or in addition to) the age on the second line, we also display the word “Muted”. See example above where Jon Bass is muted.

![screen shot 2018-08-01 at 1 55 33 pm](https://user-images.githubusercontent.com/26235957/43548399-a5a27c24-9592-11e8-8101-ad679c7dc70f.png)

**UI changes to profiles**
- The same as UI changes to muted place profiles
- The person/place icon becomes grey (#A7A9AC)
- We display the text “Muted” on the second line below the person/place name
- Any forms that were previously available on the profile remain available
- Instead of the “Mute” form, the user now sees the “Unmute” form

**Comment by amandacilek** [comment]
Updated the above description to reflect our most recent plan.

**Comment by newtewt** [comment]
Icon is showing grayed and muted is appearing under the contact as expected.

**Comment by newtewt** [comment]
@dianabarsan,  @michaelkohn  pointed out an issue with marking people as muted. When you view the profile for a muted health_center the people and areas do not show as muted. They should gray out as shown in this image. Reopening this to account for that. 

![image](https://user-images.githubusercontent.com/10531066/49252407-fb162300-f3f1-11e8-88ca-3c0938c7abeb.png)


I do see that when I'm at the district level as shown here. 
![screenshot from 2018-11-29 16-14-15](https://user-images.githubusercontent.com/10531066/49252381-e9cd1680-f3f1-11e8-9eb4-a2a432695c71.png)

**Comment by dianabarsan** [comment]
@newtewt it was on purpose that I did not display all children of a muted contact as muted, I thought it would be obvious by the fact that the parent is muted. 
But if that is the desired behavior, then sure.

**Comment by newtewt** [comment]
@dianabarsan that makes sense to me. Let's have @amandacilek  weigh in and maybe it's ok to not show that when the parent is muted.

**Comment by amandacilek** [comment]
Hey there. Firstly just to confirm, any person OR place that is muted (whether directly or because something above it is muted) has a grey icon and the word "Muted" at the top of the profile, correct?

If I'm understanding you guys correctly we're talking about these two options (see screenshot). I understand your reasoning, Diana, that it should be obvious that if the place is muted anything within is muted. However, I don't think styling the children as muted does any harm, and in fact I think it helps to reinforce the concept. If it's not too difficult my choice would be to style the children of a muted place as "muted" in the card (so option 2 here).

![screen shot 2018-11-29 at 2 43 27 pm](https://user-images.githubusercontent.com/26235957/49257007-bbe1d500-f3e5-11e8-9c4c-899dfa525f46.png)

**Comment by dianabarsan** [comment]
@newtewt @michaelkohn I've opened a PR to show all muted children as muted in the contact view page.
Is there anything else you'd want added?

**Comment by michaelkohn** [comment]
That was the only thing I saw.  All the behind the scenes stuff in the `-info` docs (and the `muted` field) worked beautifully.

**Comment by newtewt** [comment]
@dianabarsan  thanks for updating. 

@amandacilek  grey icons are at the top and the word muted underneath on profile. Now all children people and places are showing muted if top level is muted.
