### ISSUE TITLE
If during user creation associated contact is chosen, 'Place' field has to become required

### ISSUE THREAD

**Issue by IgorProtsenkoOd** [medic/medic-webapp#4772]
1. Navigate to Configuration > Users > Add user
2. Input User name
3. Pick role
4. Pick Associated contact from dropdown
5. Input Password
6. Input Confirm Password
7. Submit

Expected result:
a. Upon choosing associated contact Place has to be marked as required
b. When Place was not chosen and user click Submit button, error message appears saying 'Choose a place for associated contact'

Actual result:
a. 'Place' field is not requred.
b. When user clicks Submit button error message 'Error updating user' appears.

Version: all versions.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma.dev` v3.3
