### ISSUE TITLE
Medic Collect Security Issue

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4776]
Shadow ticket for https://github.com/medic/medic-projects/issues/4622

**Comment by garethbowen** [comment]
Code review please @vimemo

**Comment by garethbowen** [comment]
This is now merged into master of medic-collect. For AT you'll need to build the apk and push to your android phone and ensure it still works, particularly when saving forms and instances. We'll then need to update all flavours in the play store.

**Comment by ngaruko** [comment]
Can I push this to you @henokgetachew since you are more familiar with the issue?

**Comment by ngaruko** [comment]
This one works. The only outstanding issue is that it is pointing to forms on `alpha.dev`. An [issue](https://github.com/medic/medic-webapp/issues/4896) has been raised to point `gamma.dev` to `alpha.dev`
