### ISSUE TITLE
Support db-doc GET with open_revs for offline users

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4778]
PouchDB `_bulk_get` shim works by requesting each doc with a db-doc GET using `open_revs` param. This shim is only used when PouchDB determines that the remote DB doesn't support `_bulk_get` API.

**Comment by dianabarsan** [comment]
For AT, I've created a branch (`4778-no-bulk-get`) which _disables_  `_bulk_get` API endpoint for restricted users, forcing PouchDB to replicate via `db-doc:GET` requests using `open_revs` parameter.

To test, please upgrade to this branch and login with a restricted user and check that they are replicating correctly.

**Comment by ngaruko** [comment]
Is this related to #4786 in any shape or form @dianabarsan ?

**Comment by dianabarsan** [comment]
@ bede it is related in the sense that it's part of making offline users restricted to their filtered data (and #4786 is also part of that).
This issue is about covering a replication mechanism from Pouch->Couch that was not covered by the original commit.

**Comment by ngaruko** [comment]
Thanks @dianabarsan . I will leave this open, pending conclusion on how to proceed with this feature and #4786 in general

**Comment by ngaruko** [comment]
LGTM
