### ISSUE TITLE
Create a medic-android play store build for LG IN Supervisors

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4779]
To avoid performance problems we've put supervisors on their own instance. They too then, will need an android build.

The new URL is: https://lg-innovation-facility-ke.app.medicmobile.org

**Comment by benkags** [comment]
Needed before Friday, 17th August.

**Comment by henokgetachew** [comment]
This has been taken care of.  I will post the opt-in url on slack since this is public.
