### ISSUE TITLE
LHS list doesn't update "out of page" items

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4782]
Currently, LiveList and Search webapp services don't support sorting items by fields/values that are likely to change (f.e. by last visited date). 

When the list is multiple pages long and it's not entirely loaded, if an existent item receives a change that would push it lower than the current number of loaded items, the Search request will not update it - it will keep it's old sorting value until the user scrolls down and loads the page the updated item should appear on.

**Comment by ngaruko** [comment]
LGTM. Tested on `beta-old` v2.18
before
![image](https://user-images.githubusercontent.com/6979995/44392573-aa876200-a586-11e8-9bc9-22e4b5486432.png)

after 
![image](https://user-images.githubusercontent.com/6979995/44392713-f0442a80-a586-11e8-948b-e25936c9f74a.png)
