### ISSUE TITLE
On reports, "Edit" of a scheduled message not working as expected

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4787]
The current "Edit" feature on scheduled messages (accessed via Reports tab) does not seem to be working. I'm not sure how many people are currently using this feature, however, if it isn't working we should either fix it or remove it.

![screen shot 2018-08-17 at 9 41 24 am](https://user-images.githubusercontent.com/26235957/44279479-5be46b80-a206-11e8-8042-7bdb40646174.png)

I have not been able to successfully edit a message in any circumstance. Sometimes this makes sense because the message has already begun the sending process (in a "pending" or similar state). However, even when I try to edit a message that is scheduled to be sent out in the future, I am unsuccessful. I always get the same error message when I try to save my edited message "Error updating group". I've tried only editing the text, only editing the date, or editing both, and I've tried on multiple instances and logins.

![screen shot 2018-08-17 at 9 40 29 am](https://user-images.githubusercontent.com/26235957/44279442-3fe0ca00-a206-11e8-8bab-3fb7ec315b50.png)

The "+ Add Message" button never seems to work either, regardless of whether I am editing a message schedule that is in the past or one that is in the future. The app allows me to click on "+ Message", allows me to type in a message, and allows me to manually change the text of the date (but does not give me a date dropdown or validate that the date I've typed is correct), and then when I click on save I always get an error message "Error updating group".

Oddly, I also have been noticing a weird Invalid Date error on the initial message, once I've tried to add a new message with "+ Message". 

![screen shot 2018-08-17 at 10 15 39 am](https://user-images.githubusercontent.com/26235957/44279549-a665e800-a206-11e8-93c1-8ffe13149338.png)

**Comment by amandacilek** [comment]
From Stefan: I don't think the edit feature has really kept up with recent changes, specifically we now don't "compile" a message from translations until we are ready to send it, meaning you can't really "edit" messages in the same way you used to be able to.

**Comment by SCdF** [comment]
@wtekeu I think the best thing to do for now is to remove the ability for people to edit scheduled messages that need to be translated. If people request the feature in the future we can work out how we'd want that flow to work (eg editing a scheduled message compiles the translation, and then you can edit that, and then revert back to the uncompiled state etc).

So for now:
 - If the message is awaiting translation do not allow editing (disable the link I suppose)
 - Carefully read the rest of @amandacilek's bug report and make sure issues in there are all resolved as well

**Comment by ngaruko** [comment]
LGTM. All report can easily be edited where applicable. Tested on `gamma.dev` v3.3.0
