### ISSUE TITLE
Change the text that is displayed on LHS of Reports when there are no results

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4789]
The very bottom of the LHS always has some sort of statement. On the People page, this statement is "No more contacts". On the Reports page, this statement is "No more reports".

The statement changes when you've performed a search or applied filters with 0 results. On the People page, the statement changes to "No contacts found". On the Reports page, this statement says "No reports". 

Some users have found the "No reports" message to be confusing. Sometimes this text is not always accurate, as the reports are still syncing (this was raised by Isaac).

As a quick solution, suggest that we change the message for 0 results to match how we handle it on the People page. So instead of "No reports" we should say "No reports _found_" to highlight the fact that certain search criteria may be limiting the view.

![screen shot 2018-08-17 at 3 40 23 pm](https://user-images.githubusercontent.com/26235957/44291551-e55e6280-a233-11e8-84f3-2fe40c9e4991.png)

**Comment by ngaruko** [comment]
LGTM. Tested on `alpha.dev 3.1.0` 
![image](https://user-images.githubusercontent.com/6979995/44316874-43808500-a482-11e8-8ea0-ad21cfb55af8.png)
