### ISSUE TITLE
Horti versions don't show up correctly in about page

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4792]
If you deploy a version via horti, if it's a beta, branch etc it only shows the core "base" version (i.e. `3.0.0-beta.2` would show `3.0.0`).

**Steps to reproduce**:
 - Use horti to deploy a non-release version of our software.
 - Go to the about page

**What should happen**:
 - The version displayed on the about page is identical to what you deployed

**What actually happens**:
 - The version displayed on the about page is the "base" version

This is presumably because we're pulling the version from the wrong place now, and should be getting it from the horti metadata.

**Comment by dianabarsan** [comment]
Merged into `3.0.x` and forward ported to `3.1.x` and `master`

**Comment by newtewt** [comment]
@dianabarsan  Hey, I updated beta.dev with this and the about page is showing 3.0.0 instead of 3.0.0-beta.4. I'm sure I'm missing something can you help?

**Comment by dianabarsan** [comment]
Looks like Horti crashed before it could finish the upgrade and API wasn't updated. I re-upgraded and it should be fine now.

**Comment by newtewt** [comment]
Agreed, seeing the new version based on what's actually deployed. EX: 3.0.0-beta.4

**Comment by SCdF** [comment]
@newtewt / @henokgetachew so the Horti crash that Diana mentioned is, I think, fixed in later versions of horti. Would be good to get that server upgraded. Unfortunately I don't know how that works these days.
