### ISSUE TITLE
Medic-Gateway Target API needs to be upgraded

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic-webapp#4796]
The app currently targets API level 24 and will have to target at least API level 26 to ensure it's built on the latest APIs optimized for security and performance. Starting from August 2018, new apps must target at least Android 8.0 (API level 26) and starting from Nov 2018, app updates must target Android 8.0 (API level 26). If this affects projects on the ground using old phones, this needs to be taken care of before Nov 2018.
Here's the entire warning:
```
Target API level requirements from August 2018 Warning:  Your app currently targets API level 24 and must target at least API level 26 to ensure it is built on the latest APIs optimized for security and performance.  From August 2018, new apps must target at least Android 8.0 (API level 26). From November 2018, app updates must target Android 8.0 (API level 26).
```
Upgrading the target API in medic-gateway requires that the testing framework Robolectric also be updated.  That in turn affects the test coverage plugin JacocoEverywhere which needs to be either updated/replaced with something else.

**Comment by ngaruko** [comment]
I guess we could close this one @henokgetachew ?
