### ISSUE TITLE
Webapp fails to start on Ubuntu VM

### ISSUE THREAD

**Issue by rightparen** [medic/medic-webapp#4797]
I am hitting a problem trying to start the medic-webapp on an Ubuntu VM because of a 404 in the 'api' module when accessing the CouchDB docId '_design/medic'.

**Steps to reproduce**:
- Copy this zip file to the home directory of 'ubuntu@VM' in a clean AWS Ubuntu VM (or see environment section for assumptions about the VM)
[medic-scripts.zip](https://github.com/medic/medic-webapp/files/2322291/medic-scripts.zip)
- Run the following steps in the ubuntu@vm shell:
```
# This will update software, install CouchDB, set up a "medic" user
# that accepts the same ssh keys as the "ubuntu" user, clone the
# medic-webapp repo, and reboot.
sudo apt install unzip
unzip medic-scripts.zip
./medic-scripts/aws-medic-setup
```

- After the reboot, ssh to medic@vm (will accept same ssh key as ubuntu):
```
cd medic-webapp
grunt install-dependencies build-dev deploy
yarn start
```

**What should happen**:
 - medic-webapp should start.

**What actually happens**:
 - The log from the  `yarn start` command reports:

> 22:09:02 sentinel.1   |  info: Waiting for API to be ready...
> 22:09:03 api.1        |  WARNING: allowing CORS requests to API!
> 22:09:03 api.1        |  Extracting ddoc…
> 22:09:03 api.1        |  CouchDB Version: 2.2.0
> 22:09:03 api.1        |  >> Fatal error initialising medic-api
> 22:09:03 api.1        |  >> { error: 'not_found',
> 22:09:03 api.1        |  >>   reason: 'missing',
> 22:09:03 api.1        |  >>   status: 404,
> 22:09:03 api.1        |  >>   name: 'not_found',
> 22:09:03 api.1        |  >>   message: 'missing',
> 22:09:03 api.1        |  >>   docId: '_design/medic' }
> 22:09:03 api.1        |  [nodemon] app crashed - waiting for file changes before starting...

**Environment**:

The script reproduces the problem on a clean AWS Ubuntu VM.  The default AWS Ubuntu instance has the following configuration:
Linux: Ubuntu Xenial
userid: ubuntu
(blank password)
(has sudo access, i.e. in 'sudo' group)

**Other**:

During the initial deploy task, this shows up in the log:

> Running "couch-push:localhost" (couch-push) task
> Get revisions http://localhost:5984/medic...>> database does not exist
> Creating database http://localhost:5984/medic...OK
> Pushing http://localhost:5984/medic...OK
> \>> 1 database deployed

When re-running the grunt steps, the task output changes and appears to have deployed successfully:

> Running "couch-push:localhost" (couch-push) task
> Get revisions http://localhost:5984/medic...OK
> Pushing http://localhost:5984/medic...OK
> \>> 1 database deployed

However, running "yarn start" after this still results in the 404 on docId '_design/medic'.

**Comment by SCdF** [comment]
hi @rightparen,

It may be that `yarn start` doesn't work the first time due to ordering issues. It does three things: builds and pushes our application as a Couch doc called `_design/medic`; starts api; and starts sentinel.

Both api and sentinel need that design doc to at least exist before they will work properly.

Could you try first just building and pushing that ddoc without using `yarn start`? Running `yarn grunt` should do the trick.

If that works we can either modify our setup instructions, or change yarn start so it's more intelligent about how it works the first time.

**Comment by rightparen** [comment]
Hi @SCdF ,

Thanks for the guidance.  I am looking at this again and realized that one issue I was hitting was mixing up ports 5984 and 5986 (I suspect I thought the comment about "# CouchDB 2.0" applied more broadly than just the require_valid_user setting).  So my COUCH_URL was incorrect.  At this point things are running successfully--I will do some experimentation on which steps are strictly necessary and submit a PR if something in the docs should change.
