### ISSUE TITLE
Cannot get audit log

### ISSUE THREAD

**Issue by IgorProtsenkoOd** [medic/medic-webapp#4802]
**Steps to reproduce**:
1. Login as admin
2. Navigate to /medic/_design/medic-admin/_rewrite/#/export/audit-logs
3. Click Export button

**What should happen**:
Audit log is prepared and downloaded 

**What actually happens**:
App hangs on spinner, single request is sent to 
GET /api/v1/export/audit?format=xml&locale=en HTTP/1.1

- Instance: _(alpha.dev.medicmobile.org, etc)_
- Browser:  Firefox, Chrome. Latest
- Client platform: Windows
- Version: 3.2.0

**Other**:
According to Diana Barsan: 
API `auth` component was refactored to use Promises, while the Export component still expects it to use callbacks.

**Comment by SCdF** [comment]
As with all of these export issues that get raised, I'm not convinced anyone uses this export and we should drop it instead of fixing it. One less thing to maintain :-)

**Comment by abbyad** [comment]
I was asked today about export of forms with images... so there _may_ be users that use _some_ of it. Do we have any activity tracking/logging to see which endpoints do get used?

**Comment by dianabarsan** [comment]
Calling Auth with a callback instead of a pormise has been fixed. Unfortunately there is another bug caused by `compression` - where when using `res.write` method, calling `flush` method is required to actually send data.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma.dev` v3.3
