### ISSUE TITLE
Replace continuous replication

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4805]
As discussed in [this document](https://docs.google.com/document/d/159qKQwYo02Cxh3T0YidK_2D-KAtWdLEkvq8slnwdMuc/edit) replace continuous replication with periodic one-shot replication to improve server scalability, phone battery usage, network data usage, and reduce code complexity.

- [ ] Implement polling to do a bidirectional replication every 5 minutes. The specific number is up for debate but 5 minutes is a safe place to start.
- [ ] Implement #3976 so users can manually trigger a bidirectional sync.
- [ ] Investigate using [online event handlers](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine#Specification) to trigger a bidirectional sync when a user comes back online if it's been longer than the 5 minute timer above.
- [ ] Remove continuous replication code from the API changes endpoint.

**Comment by kennsippell** [comment]
@SCdF @dianabarsan Would either of you be able to give an overview of the work required for this bullet `Remove continuous replication code from the API changes endpoint`?

**Comment by SCdF** [comment]
@kennsippell I'm not sure that should actually be there honestly, because then I don't think upgrades would work? I think we need to support continuous replication in api until we're confident (or we force everyone) onto a version that no longer does it.

**Comment by SCdF** [comment]
(to be clear we should make a note to do it, but it would be in a "4.0.0" ticket or whatever)

**Comment by kennsippell** [comment]
Sounds good! I broke that piece off into a separate issue ^.  The PR above is aligned with this issue and should be sufficient to resolve the three tasks tracked here.

**Comment by garethbowen** [comment]
Kenn is working on it - I've assigned myself so nobody else picks it up.

**Comment by ngaruko** [comment]
Any clue on how to AT this @garethbowen ? Thanks.

**Comment by garethbowen** [comment]
@ngaruko In previous versions if you made a change on the server then it would get replicated to the browser almost immediately because there was a continuous connection to the server. Now it will take up to five minutes because we check once and then close the connection. So to AT:

1. Log in as a restricted user and load a specific report.
2. Check the network tab - there should be no continuous requests. Everything should eventually complete.
3. In a separate browser log in as an admin and make a change to the doc selected in 1.
4. Keep watching the network tab until you see a changes request go out. Make sure this request completes in a reasonable time. Then make sure the doc is updated with your change without having to refresh the browser.

The next checkpoint about the "sync now" button should be tested in the linked issue.

The third part about online event handlers can be tested by...

1. Disconnect the browser from the internet
2. Waiting six minutes - make sure no changes requests are sent in that time
3. Reconnect to the internet - make sure a changes request goes out soon after reconnecting.

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev` v 3.4
