### ISSUE TITLE
Fix getting registrations via querying `medic-client/registered_patients`

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4806]
When sentinel data was pulled out into it's own database (https://github.com/medic/medic-webapp/issues/3423), `medic-client/registered_patients` view started to yield no results, due to it's dependence of checking `registration` transition execution info to be present within the doc.
This view is used by Sentinel (to generate and mute messages), by API (`create-patient-contacts` migration) and Webapp to format data records ( generating `scheduled_messages` in the UI ).

**Comment by newtewt** [comment]
@dianabarsan Hey, could you lend some insight on what to AT for this. Thanks

**Comment by dianabarsan** [comment]
You've already AT-ed it with https://github.com/medic/medic-webapp/issues/4831 , 
You can also trigger it by submitting multiple shedule-generating forms for the same patient, with each one, the previous schedule should be cleared. (fe multiple pregancies). 
Also, you'd trigger this with the "OFF" and "ON" Form (schedules should be muted/unmuted). 

This fix restores a missing link between the patient and their schedule/state.

**Comment by newtewt** [comment]
Thanks, I wasn't sure based on the description. Checked with multiple pregnancies and a delivery clearing the ANC schedules.
