### ISSUE TITLE
Message/Forms are only associated for "CHW" facilities

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#482]
Incoming message or form only gets associated to a facility in the activity page if the sender is listed as a CHW in the facilities. This means that messages received from the other levels of the hierarchy are not shown as coming from a known facility.

**Comment by browndav** [comment]
Any objections to closing this, #873 and #874 in favor of #910?

**Comment by abbyad** [comment]
Works well, tested sending both messages and reports from all levels. Nice to have this restriction removed!

Moving to Ready.
