### ISSUE TITLE
"Standard" config is missing permission definitions for can_access_*

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#4821]
When using the "standard" configuration that is included in source, I was unable to use the app due to permission errors.

**Steps to reproduce**:

1. Set up a clean development environment via steps in the [README](https://github.com/medic/medic-webapp).
1. Run `medic-conf --local` for `[medic-webapp]/config/standard`
1. Login into medic-webapp

**What should happen**:
Any webappy thing at all.

**What actually happens**:
Permission error

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: webapp

**Comment by garethbowen** [comment]
I think this is fixed by https://github.com/medic/medic-webapp/commit/73c0e6ecc633beed3ed0f6ad4ce7f7d94e54c4ea - can you please pull and check again?
