### ISSUE TITLE
Error loading form "Could not evaluate:"

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4823]
Trying to process an assessment on gamma.dev with the lg-uganda Assess Patient form. When clicking on the form it presents `Error loading form. Please try again or check with an administrator.` The console log is shown before. This same form works in 2.18 site on beta-old.dev instance

**Steps to reproduce**:
Login as user nick_tim
Click the Charles Family
Click Alyssa Billson user
Click New Action
Click Assess Patient

**What should happen**:
The assess patient form is shown

**What actually happens**:
The error is displayed here. 

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/708ebee7-09c6-4153-972a-e74275ca8b69/report/assessment

Console logs in the gist.  There are a few different errors shown.

https://gist.github.com/newtewt/e7906d79b737a134963a8c1bbf3569ea

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: gamma.dev
- Browser:  Chrome, Firefox
- Client platform: MacOS
- App: webapp
- Version: 3.0.0-beta.4

**Comment by vimemo** [comment]
Please retest. The fix for this is included in #4808.
2.18 uses enketo-core 4.41.2 and 3.0.x currently uses 4.41.9.
An enketo issue was introduced in 4.41.7 and this form looks ok with 4.41.6 like the fix for #4808.

**Comment by newtewt** [comment]
Looks good. Can process those reports now.
