### ISSUE TITLE
After searching, the RHS should clear of anything you were previously looking at

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#4825]
This applies to search on both the People tab and on the Reports tab, on desktop layouts only.

What currently happens:
If I am on the People page viewing a profile for "Antoine" in the RHS, and then I conduct a search for "Amanda" (a name that does not exist on that instance) my LHS clears completely with a "No people found" message, while the RHS remains on Antoine. This is incredibly confusing.

![screen shot 2018-09-13 at 1 51 07 pm](https://user-images.githubusercontent.com/26235957/45515141-27f45b80-b75c-11e8-98dd-3ebe35614b74.png)

This happens on Reports as well. If I am viewing a report about a child "Romeo" and then I conduct a search for "Amanda", again the RHS remains on Romeo's profile.

![screen shot 2018-09-13 at 1 55 08 pm](https://user-images.githubusercontent.com/26235957/45515370-d0a2bb00-b75c-11e8-816c-d498793a8116.png)

What should happen:
After searching, the RHS should clear of anything you were previously looking at. As soon as I conduct a search, the RHS clears completely and displays the default message of "No reports selected" or "No person/place selected". If there are any matching search results, I will need to first click on something in the LHS in order to view something in the detail view on the RHS.

**Comment by ngaruko** [comment]
LGTM. Tested on `gammma.dev`, version 3.2.0
