### ISSUE TITLE
Unable to access Configuration screen on my local instance of webapp (wrong redirect URL)

### ISSUE THREAD

**Issue by wtekeu** [medic/medic-webapp#4829]
After completing the local deployment of the webapp and logging-in as admin, I was unable to access the Configuration page. Instead, I was redirected to http://localhost:5988/medic/medic-admin/_rewrite/ with the following error message: `{"error":"not_found","reason":"missing"}`

**Steps to reproduce**:
 - Setup webapp locally following readme instructions 
- Click on Configuration

**What should happen**:
 - I should be redirected to http://localhost:5988/medic/_design/medic-admin/_rewrite/

**What actually happens**:
 - Instead I am redirected to http://localhost:5988/medic/medic-admin/_rewrite/

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance:  local
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.2.0

**Other**:
To carry on, I enter the URL http://localhost:5988/medic/_design/medic-admin/_rewrite/ after logging-in

**Comment by garethbowen** [comment]
I think this is due to using a relative path to the configuration app which means if you load the app with a trailing slash you get a different URL than if you don't use the trailing slash. This was done to find the db name (the first "medic"). Find the DB name in a better way and we can use an absolute path instead: `{db-name}/_design/medic-admin/_rewrite/`

**Comment by garethbowen** [comment]
Consider extending the [Location service](https://github.com/medic/medic-webapp/blob/master/webapp/src/js/services/location.js) which already returns the path to the webapp so it also returns the path to the admin app.

**Comment by ngaruko** [comment]
I couldn't get the app to run. After login, the screen is stuck on `Loading assets` with the following warning in console. Is this related to the issue @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/46331472-a0bc4880-c674-11e8-93b9-dfddfd39f875.png)

**Comment by SCdF** [comment]
@ngaruko Gareth isn't here this week. Can you go into more detail about what you did? This is a 3.2.0 beta that you're trying? What URL is it currently trying to redirect to?
