### ISSUE TITLE
ANC SMS are not cleared when pregnancy is registered to the patient

### ISSUE THREAD

**Issue by newtewt** [medic/medic-webapp#4831]
The ANC scheduled SMS are not being cleared when a delivery is reported to the patient. 

**Steps to reproduce**:
Schedule a New Pregnancy with SMS
Verify the Scheduled SMS show on the report.
Schedule a Delivery with SMS

**What should happen**:
Look at the New Pregnancy report and the ANC SMS schedule should have been cleared. 

**What actually happens**:
Look at the New Pregnancy report and the ANC SMS schedule remains

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/a231eeca8adb84ea611c00fc4d01f66c

**Environment**:

- Instance: gamma.dev
- Browser: Chrome
- Client platform: MacOS
- App: webapp
- Version: 3.0.0

**Comment by dianabarsan** [comment]
This issue should be fixed by https://github.com/medic/medic-webapp/issues/4806 . At the moment this issue was reported, gamma.dev was running a `3.0.0-beta.4` which did not include this fix. I've created `3.0.0-beta.5` which includes the fix.

**Comment by newtewt** [comment]
Tested in Gamma.dev  and schedules are clearing.
