### ISSUE TITLE
Date picker widget is not translated for language Bamanankan (bm)

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#4832]
See #3327 for details.

After #4830 the date picker is translated for all the default Medic languages except for Bamanankan (bm). The bootstrap-datepicker library does not include a language pack for Bamanankan, so one should be created. A sample of language packs can be found at https://github.com/uxsolutions/bootstrap-datepicker/tree/master/js/locales.

**Comment by garethbowen** [comment]
Once this is done contribute it back to the bootstrap-datepicker repo so others can use and improve it.

**Comment by garethbowen** [comment]
I've copied these from [moment.js](https://github.com/moment/moment/blob/develop/locale/bm.js) as well as our [own translation file](https://github.com/medic/medic-webapp/blob/master/ddocs/medic/_attachments/translations/messages-bm.properties).

```js
{
		days: ["Kari","Ntɛnɛn","Tarata","Araba","Alamisa","Juma","Sibiri"],
		daysShort: ["Kar","Ntɛ","Tar","Ara","Ala","Jum","Sib"],
		daysMin: ["Ka","Nt","Ta","Ar","Al","Ju","Si"],
		months: ["Zanwuyekalo","Fewuruyekalo","Marisikalo","Awirilikalo","Mɛkalo","Zuwɛnkalo","Zuluyekalo","Utikalo","Sɛtanburukalo","ɔkutɔburukalo","Nowanburukalo","Desanburukalo"],
		monthsShort: ["Zan","Few","Mar","Awi","Mɛ","Zuw","Zul","Uti","Sɛt","ɔku","Now","Des"],
		today: "Bi",
		monthsTitle: "Kalow", // possibly "Kalo"?
		clear: "Ka jɔsi",
		weekStart: 1,
		format: "d/mm/yyyy"
}
```

@abbyad Who do we know who can speak Bambara and can confirm these are correct?

**Comment by abbyad** [comment]
@Fatoufall and @abdoufata should be able to connect directly someone that can confirm the translations.

Can one of you please confirm that the translations above match [these English ones](https://github.com/uxsolutions/bootstrap-datepicker/blob/7adfa40f302f66f17e0152728f1cf7c9025ed1a7/js/locales/bootstrap-datepicker.en-GB.js#L7-L16)?

**Comment by Fatoufall** [comment]
I confirmed that translations above are correct. Preffered Kalo for monthsTitle
I suppose this is a typo on format date: dd/mm/yyy

**Comment by abbyad** [comment]
Thanks for that Fatou. And yes, that does look like a typo as `format` should be `dd/mm/yyyy`

**Comment by ngaruko** [comment]
LGTM. Tested on `gamma.dev` v3.3
Before
![image](https://user-images.githubusercontent.com/6979995/48820146-8fe3a580-ed8e-11e8-9fca-d4f75076d19b.png) .    || 
![image](https://user-images.githubusercontent.com/6979995/48820165-a558cf80-ed8e-11e8-818b-dff14ced6f4e.png)


After
![image](https://user-images.githubusercontent.com/6979995/48820125-76425e00-ed8e-11e8-9085-1bcd38ed70a2.png)
![image](https://user-images.githubusercontent.com/6979995/48820138-835f4d00-ed8e-11e8-917a-2e7c52472249.png)
