### ISSUE TITLE
Move `medic-client/feedback` view into admin ddoc

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4834]
The `medic-client/feedback` view isn't used anywhere on the client so it shouldn't be shipped to the client. Move it to the `medic-admin` ddoc and update all code that references it.

I think it's only used in [api](https://github.com/medic/medic-webapp/blob/master/api/src/services/export-data.js#L68) and the [admin app](https://github.com/medic/medic-webapp/blob/master/admin/src/js/controllers/export-feedback.js#L48) but you should check to ensure I haven't missed anything.

**Comment by garethbowen** [comment]
Committed here: https://github.com/medic/medic-webapp/commit/bc687d48670274716addc2b816f70265e6880034

**Comment by garethbowen** [comment]
AT: ensure exporting feedback docs and viewing feedback in the admin app still work as expected.

**Comment by ngaruko** [comment]
The `export` function seems not to be working. I am not sure if it is due to this or if it has been like this for a while...

**Comment by ngaruko** [comment]
LGTM . Tested on `gamma.dev` v3.3.
Viewing and exporting feedback works as expected..
