### ISSUE TITLE
Font awesome icons not loading in the administration console

### ISSUE THREAD

**Issue by Jodge** [medic/medic-webapp#4837]
**Caused by**
[Uses an absolute url to link to the admin app](https://github.com/medic/medic-webapp/commit/b8a8cf746fc3705d7c9c629ae555757fb477e9a3)

**Steps to reproduce**:
 - _Login to the webapp as an **administrator**_
 - _Click on the menu bar on the top-right, from the dropdown that appears click on the **Cofiguration** menu item_
- _On the administrator console click on **Roles & permissions** menu item on the left sidebar_
- _Click on the **Roles** Tab on the main section of the page_

**What should happen**:
 - _The *fa-plus* icon should be loaded as part of the **submit** button_

**What actually happens**:
 - _The *fa-plus* icon is not being loaded as part of the **submit** button_

**Comment by garethbowen** [comment]
@Jodge You marked this for code review - have you got a PR for @dianabarsan to review? I'll leave it for you two to discuss. Thanks!

**Comment by dianabarsan** [comment]
@Jodge I see that you do have a working branch for this issue, could you please create a Pull Request? Thanks!

**Comment by dianabarsan** [comment]
@bede the URL that you tested this on has always worked. You will need to test this on a URL without a trailing slash (after `rewrite)`, fe: https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/authorization/roles .

Also, this has not been fixed on 3.0, only on 3.2 (master).

**Comment by ngaruko** [comment]
I see, thanks @dianabarsan. I updated `gamma.dev` to 3.2.0 and both urls seem to work ([with](https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite/#/authorization/roles) or [without](https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/authorization/roles) the slash
