### ISSUE TITLE
grunt watch doesn't deploy inbox.html changes

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4865]
When running `grunt watch` (or `yarn start`) changes to `webapp/src/templates/inbox.html` don't get bundled and deployed. Add a new watch configuration to monitor changes to this file and bundle and redeploy the code automatically.

**Comment by ngaruko** [comment]
Is there anything to 'AT' here @garethbowen from QA's end?

**Comment by garethbowen** [comment]
No it's all internal to the dev team - thanks!
