### ISSUE TITLE
include timezone value in settings

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#488]
Not sure if this issue exists already, but we should have a timezone setting.  

This setting should also get applied to places that use time and need a timezone.  This includes the following settings:
- schedules.messages.send_time
- schedule_morning_hours
- schedule_evening_hours

Right now these settings take a timezone parameter like '+0300' (offset from GMT) or expect GMT.  We should calculate the time based on the timezone setting by default and allow a timezone parameter to override it (since we already support it anyway).  So if you want to specify a time in GMT you would include '+0000' in your time value.  This could probably be useful in some cases where an instance of Kujua is supporting more than one timezone?

This might eventually live in concierge but for the time being it's probably a good idea to add it to the kujua settings and work out the kinks.

Moment Timezone is already included as a kanso package in Kujua and can probably be used for this http://momentjs.com/timezone/

We'd probably ask for this during initial setup and we could use the browser's timezone value as a default.

**Comment by SCdF** [comment]
@mandric please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by mandric** [comment]
Scheduling because it was [reported again](https://github.com/medic/medic-projects/issues/1613).

**Comment by rmhowe** [comment]
@sglangevin @abbyad you've both run into this issue with respect to EDD, is it something that needs to be scheduled? It seems that SMSs are sent from the server using GMT/UTC, which may lead to these dates being off by one
https://github.com/medic/medic-webapp/issues/986
https://github.com/medic/medic-projects/issues/1613

**Comment by sglangevin** [comment]
I'd say this is a nice to have. It hasn't come up lately, as far as I know.

**Comment by abbyad** [comment]
It is definitely problematic and confusing for SMS projects, but doesn't seem to cause problems for mobile app projects.

**Comment by sglangevin** [comment]
I haven't heard this come up in any of our Standard projects or in our Nepal MoH deployments recently.

**Comment by rmhowe** [comment]
Shall we close until this gets reported then?
