### ISSUE TITLE
Horticulturalist crashes when view warming

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4893]
When doing view warming, we assume that CouchDB view queries will timeout. We intend to catch these errors and retry the queries (successful queries signify that the view is warmed). 
Timeout errors are no longer marked with a `ESOCKETTIMEDOUT` code since the upgrade to PouchDB 7, result being that horti crashes when when the timeouts occur.

**Comment by dianabarsan** [comment]
Because this was blocking the upgrade process of the instance intended to host 3.0 performance tests, view warming is temporarily disabled, pending an update that deals with timeouts differently.

**Comment by garethbowen** [comment]
@dianabarsan Is this still in code review?

**Comment by dianabarsan** [comment]
No, sorry, it got merged while I was away.

**Comment by newtewt** [comment]
Hey @dianabarsan is there a good way to for a timeout to see the issue?

**Comment by dianabarsan** [comment]
Those are normal, or, at least, expected. 
When processing tombstones, it's important that the tombstone contains actual doc information (otherwise it's useless).
If the doc is deleted via Fauxton, the new deleted rev will be stripped of doc content to keep space low, so when creating the tombstone, to code tries to get the previous rev which would contain data.
The problem is that horticulturalist compacts the DB when upgrading, so those previous revs get purged, hence the 404s when trying to read the old revision.

**Comment by newtewt** [comment]
Sounds good to me. I am closing since updating is working fine to different versions locally and we have already been using this change in some of the docker instances.
