### ISSUE TITLE
Count two visits on the same day as one visit

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4897]
Following on from [UHC visit counts](#4758) if a CHW files two visit reports for the same family on the same day that should only count as one visit in the UI. In this context a day is a calendar day in the user's timezone.

This was first raised in [medic-projects](https://github.com/medic/medic-projects/issues/5154).

**Comment by garethbowen** [comment]
I think this is a reasonably easy patch to the [logic dictating whether to increment the visit count](https://github.com/medic/medic-webapp/blob/master/webapp/src/js/services/search.js#L69).

I'm thinking we should release a 2.18.1 with just this patch. @dianabarsan What do you think?

**Comment by dianabarsan** [comment]
Sure, I'm on board with that.
