### ISSUE TITLE
monitoring gateway connection

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#490]
Ok we need to find an android application that monitors the connection between smssync and kujua and notifies someone if that connection fails.  We should also have some type of graph or health status that tracks this connection inside Kujua.  We need to know if and when this connection fails.  This is the minimum monitoring we should have available.

There has to be an android app out there that takes a URL and does a GET request and makes sure 200 code is returned and alerts you via sms if not.

smssync has an issue which is promising https://github.com/ushahidi/SMSSync/issues/160 but we need something now.

**Comment by alxndrsn** [comment]
I assume this is fixed.
