### ISSUE TITLE
Contacts controllers search is clearing $stateParams when it shouldn't

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4905]
Contacts Controller `$scope.search` function is called when the controller is inited, even when on viewing contacts or adding contact actions. 
Because of https://github.com/medic/medic-webapp/commit/6d478edee76aee29504254a0666cb15bb40b8e85#diff-3eeb107d516b06788ab7c925732c1e65R267, 
the search is effectively clearing the stateParams even when it's not supposed to, resulting in weird errors:

On Contacts-Content:
![image](https://user-images.githubusercontent.com/35681649/47142282-41447680-d2cb-11e8-8a5c-1b506ef6596f.png)

On Contacts-Report:
![image](https://user-images.githubusercontent.com/35681649/47142182-07737000-d2cb-11e8-8947-abfcefb107c6.png)

**Steps to reproduce**:
- Login to a 3.2 instance
- Go to Contacts page
- Load a contact 
- Open a action form for this contact 
- Refresh the page (Ctrl + F5)
- the Form in the RHS is not loaded and URL has changed to `/#/contacts`

**What should happen**:
- You should be seeing the same page as before and URL should be the same

**What actually happens**:
- You're not loading a form in the RHS
- you are redirected to `/#/contacts`
- errors in the console

**Comment by ngaruko** [comment]
LGTM on `gamma.dev` v3.3, though we still see a couple errors in the console which might be not necessarily related to the issue... or are they @dianabarsan ?
![image](https://user-images.githubusercontent.com/6979995/49189260-2cfe9980-f3a0-11e8-97d0-7f16dc249970.png)

**Comment by dianabarsan** [comment]
@ngaruko I don't believe this is related. 

Were you, by any chance, in incognito mode when observing this error? I am getting the same error in incognito consistently, but never seeing it in non-incognito. 
I have a hunch that it might be related to some size limitation imposed in caching files in incognito mode (similar to the 100MB or so limitation of storage quota). 
To test the hunch, I added another large file (a 4MB image) to the appcache manifest to see if it results in the same failure, and it does, but only in incognito. 

![image](https://user-images.githubusercontent.com/35681649/49362219-e33ae980-f6e6-11e8-9647-998c2a1d43fd.png)

This is what happens in non-incognito:

![image](https://user-images.githubusercontent.com/35681649/49362470-8a1f8580-f6e7-11e8-908e-2b053f4c015f.png)

**Comment by ngaruko** [comment]
Thanks @dianabarsan - Closing this.
