### ISSUE TITLE
Online users constantly replicate database changes

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4924]
If an online user were to log in to a large instance their browser would be overwhelmed by a constant stream of doc updates and the app would not be useable.

Consider disabling watching changes feeds for online users and require them to refresh or navigate to get updates. This will effect some existing users who are used to having the content update automatically. Consider adding a permission to turn replication back on for small instances. Alternatively we may get away with adding a dirty flag to the UI to notify users of new changes.

**Comment by garethbowen** [comment]
@amandacilek @diannakane Do you have any thoughts about this one?

**Comment by SCdF** [comment]
@garethbowen this has already been raised: https://github.com/medic/medic-webapp/issues/4327

I'll leave it to you to decide which of those you want to keep

**Comment by garethbowen** [comment]
Ugh, thank you! I searched for ages trying to find that. I'll add some keywords to that one.

Duplicate of #4327
