### ISSUE TITLE
Add performance checking to dev workflow

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#4936]
To avoid performance setbacks, as seen in https://github.com/medic/medic-projects/issues/5242, we should include explicit performance checks prior to release. Ideally this would be automated and as close as possible to the commits/PRs to catch performance hits early enough. Worst case, we should have defined performance targets tested as part of release testing.

**Comment by garethbowen** [comment]
I think documented performance targets to be tested and recorded during release testing is definitely a good idea. Automation could be tricky but we can work on this at a later date.

**Comment by newtewt** [comment]
@abbyad  @garethbowen  @ngaruko 

Have a look and see if this is what you were thinking. I want to define the seed data details a bit more here and add a few other time checks. Currently doing an average of 3 attempts on each use case. 

https://docs.google.com/document/d/1ab_wjxsT9millrBAy3SjZxWBT8KRmBElBuwgz9XAGII/edit?pli=1#heading=h.jqsljlq9vrt8

**Comment by newtewt** [comment]
Added timings to the release testing doc and added details about the data used to create them.
