### ISSUE TITLE
Bump autoprefixer browser support

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#4955]
We use autoprefixer to add browser compatibility prefixes to css rules. We configure it in our Gruntfile to support `browsers: ['last 2 versions', 'Android >= 4.4'],` but now we're not supporting Chrome 30 we can bump this to be in line with our [supported browsers](https://github.com/medic/medic-docs/blob/master/installation/supported-software.md).

Compatibility prefixes have gone out of fashion recently as they lead to people writing browser specific css code so it's likely that once we bump the autoprefixer configuration it doesn't actually do anything. Check if any changes are actually made and if not remove the plugin altogether.

**Comment by Jodge** [comment]
@garethbowen I think by passing `last 2 versions` it will target in this case `chrome 67` and `chrome 68` i.e. `$npx browserslist` so `chrome 30` not an issue here.  It will parse the CSS files and adds vendor prefix properties and values as per [caniuse](https://caniuse.com/#info_about) database for `chrome 67` and `chrome 68`

what do you think?

**Comment by garethbowen** [comment]
Yes. The problem is the 'Android >= 4.4' bit which means add prefixes for anything not natively supported in the webview that shipped in Android 4.4 which is Chrome 30. Now that we ship a bundled version of Chrome we're not using the webview so that's no longer a constraint for us.

I haven't tested this but I suspect we want something like `browsers: ['last 2 Firefox versions', 'Chrome >= 54'],`.

But as I say above I think this configuration won't add any prefixes at all, so we should compare the input to the output and if it's doing nothing we should remove autoprefixer altogether.

**Comment by Jodge** [comment]
I see, let me test this based on those configs.

**Comment by Jodge** [comment]
@garethbowen from my finds,
this configuration `browsers: ['last 2 Firefox versions', 'Chrome >= 54']` seems to reduce `bloating` in the `css` file. i.e. we have removed `Android >= 4.4` that seemed to target `Chrome version 30`. Also it removes the `-webkit` lines of code that are no longer needed from some of the `vendor library css` that we are import to our main css. 

`browsers: ['last 2 Firefox versions', 'Chrome >= 54']` and `browsers: ['last 2 Firefox versions', 'Chrome >= 54', 'ChromeAndroid >= 54']` gives me same results, so I will keep it simple `browsers: ['last 2 Firefox versions', 'Chrome >= 54']`

Any input before I make the changes?

**Comment by garethbowen** [comment]
Sounds good. Go for it!

**Comment by newtewt** [comment]
@Jodge  anything we should check while acceptance testing this other than making sure the app still looks correct?

**Comment by Jodge** [comment]
@newtewt well the  `inbox.css` file in the `build` dir has been reduced by some fewer lines after this change i.e. some `-webkit` prefix that are no longer needed in `Chrome >= 54` are removed from the css file. Does that suffice?

**Comment by newtewt** [comment]
Thanks @Jodge  checked before and after with `grunt postcss`. Checked also on techno and browsers that everything still looks right.
