### ISSUE TITLE
The `accept_patient_reports` transition is broken

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4962]
Because of a switch from Nano to PouchDB in `accept_patient_reports` transition, `utils.getRegistrations` which expects Nano and calls `db.medic.view`, instead receives PouchDB and generates this error:

![image](https://user-images.githubusercontent.com/35681649/48074150-f3939d80-e1e8-11e8-9c34-8d7ef671f5cf.png)

**Comment by garethbowen** [comment]
Introduced in 3.2.0 development so no backport required.

**Comment by ngaruko** [comment]
LGTM. Tested on `gamma.dev` v3.3.0
