### ISSUE TITLE
Empty triggers cause sentinel to hang

### ISSUE THREAD

**Issue by SCdF** [medic/medic-webapp#4975]
If you have some empty triggers configured sentinel will hang processing it because we are failing to call a callback.

For example, if you have a section of config like so:

```json
        {
          "name": "on_create",
          "trigger": "",
          "params": "",
          "bool_expr": ""
        },
```

This will cause sentinel to hang on the next document this relates to.

**Comment by SCdF** [comment]
We need a 2.18.x and a 3.x (just 3.3.x or all of them?) release of this IMO.

**Comment by SCdF** [comment]
@garethbowen take a look at my masterful coding abilities. Wear sunglasses, the future looks bright...

**Comment by garethbowen** [comment]
@SCdF All good. Definitely backport it to `3.0.x`, `3.1.x`, and `3.2.x` because they're not released yet. I'm tempted to hold off on `2.18.x` unless someone has encountered this in production? IIRC we only have one installation on 2.18.x and they're motivated to upgrade to 3.0.0 ASAP so a 2.18.2 release probably won't get installed anywhere.

**Comment by SCdF** [comment]
Sorry I should have linked, the "production" (they are not yet live) issue is here: https://github.com/medic/medic-projects/issues/5250

However, as noted on there that may not be the whole story for them. I'm going to have a play tomorrow morning or later tonight and I can get back to you.

**Comment by garethbowen** [comment]
Assigning to 3.0.0 so it gets ATed.

**Comment by SCdF** [comment]
AT: check out [Ashish's stellar reproduction notes in the linked medic-projects ticket])(https://github.com/medic/medic-projects/issues/5250#issuecomment-437835388)

**Comment by newtewt** [comment]
I'm testing this on gamma-b.dev and seeing the `facility not found` error on the `क` form. The config is as shown below. 

Sending `क 34 NC4` from  `+16145553333` and watching the reports come in as the admin user. 

```
    {
      "form": "क",
      "events": [
        {
          "name": "on_create",
          "trigger": "add_patient_id",
          "params": "",
          "bool_expr": "doc.patient_name"
        },
        {
          "name": "on_create",
          "trigger": "assign_schedule",
          "params": "REG Reminders",
          "bool_expr": "doc.patient_name"
        }
   ```

**Comment by newtewt** [comment]
No longer seeing the facility not found error when the triggers are empty.
