### ISSUE TITLE
Weak passwords should not be used on CouchDB developer boxes

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#4979]
Quoting @alxndrsn :

> if someone guesses your couch admin password they can get root on your computer

All developers use username: `admin` and password: `pass` because the build scripts require it.

**Comment by SCdF** [comment]
@kennsippell directly below Alex saying that I clarified that this statement isn't true:

> They can't get root, they can get whatever CouchDB is running as. This is slowly being patched out, I think the next CouchDB release will get rid of it completely?

> Yeah, basically if they get admin they can:
> - change config to allow for erlang engines (in 2.3 I believe you will need to write a file instead of changing it over REST)
> - create a ddoc with a view with arbitrary erlang code in it
> - this code isn't sandboxed, and so can write to files etc
> - It's not clear what you can achieve, but I imagine quite a lot
