### ISSUE TITLE
Attempt at improving performance of UHC Contacts. 

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#4981]
UHC contacts lists relies heavily on quering views with `keys` parameter, which has a proven track record of slowness (because PouchDB would query the view database for each key separately).
Adding to the fact that for sorting by last visited date, `Search` service must intersect two whole views (`contacts_by_last_visited` and `contacts_by_type`), loading the contacts list for medium-large DBs on low end phones is incredibly slow.

Some benchmarks (results in seconds):

| UHC + visit sorting | Desktop | Nexus 5X | Tecno Y4 |  
| ---- | :----: | :----: | :----: |
| Load 50 contacts  | 1.2 | 8 | 75 |
| Load 50 contacts after home_visit form submission | 2.4 | 20 | 110 |
| Load 150 contacts after home_visit form submission | 4.5 | 30 | 195 |
| Load 150 contacts after contact edit | 3.9 | 26 | 178 |

| UHC + alpha sorting | Desktop | Nexus 5X | Tecno Y4 |  
| ---- | :----: | :----: | :----: |
| Load 50 contacts | 1 | 3.9 | 43 |
| Load 50 contacts after home_visit form submission | 1.6 | 6.9 | 56 |
| Load 150 contacts after home_visit form submission | 3.2 | 22 | 130 |
| Load 150 contacts after contact edit | 2.9 | 20 | 144 |

*All benchmarks performed using code from `master` against a local deployment, using data replicated from `muso-mali.app` restricted user (150 families, 600 persons, 4600 reports).*

**Comment by dianabarsan** [comment]
Benchmarks after patch (results in seconds): 

| UHC + visit sorting | Desktop | Nexus 5X | Tecno Y4 |  
| ---- | :----: | :----: | :----: |
| Load 50 contacts | 0.4 | 5 | 27 |
| Load 50 contacts after home_visit form submission | 1 | 14.5 | 60 |
| Load 150 contacts after home_visit form submission | 1 | 25 | 75 |
| Load 150 contacts after contact edit | 0.7 | 10 | 50 |

| UHC + alpha sorting | Desktop Chrome | Nexus 5X | Tecno Y4 |  
| ---- | :----: | :----: | :----: |
| Load 50 contacts | 0.4 | 3 | 30 |
| Load 50 contacts after home_visit form submission | 1 | 9 | 60 |
| Load 150 contacts after home_visit form submission | 1 | 9.5 | 60 |
| Load 150 contacts after contact edit | 0.8 | 8 | 60 |

_All benchmarks performed using code from master against a local deployment, using data replicated from muso-mali.app restricted user (150 families, 600 persons, 4600 reports)._

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma-b.dev` with seeded data. The app load reasonably fast enough (an in line with the above benchmarks) on both the desktop and the mobile.
