### ISSUE TITLE
Reports with scheduled tasks and deleted patients fail to load

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#5019]
When attempting to load a report that contains not-yet-generated scheduled messages about a patient that has been deleted, an error is thrown inside `message-utils` library which blocks the report from being displayed:

For example https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/8cb9904d-cc22-485a-8ef0-0c3d2a1372e2

![image](https://user-images.githubusercontent.com/35681649/48939008-92bfd100-ef1b-11e8-9c60-2a6047a1d524.png)

Same issue as https://github.com/medic/medic-webapp/issues/4899#issuecomment-440941632

**Comment by dianabarsan** [comment]
In addition, Sentinel also crashes when processing such a task message:

![image](https://user-images.githubusercontent.com/35681649/49080611-e4829700-f24c-11e8-914d-0a641b087544.png)

**Comment by ngaruko** [comment]
LGTM.
Tested on gamma.dev v3.4
