### ISSUE TITLE
Fix favicon caching

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5025]
With recent changes to how we serve the favicon we have broken the caching implemented to fix #1913 and #3858 .

The [favicon test code](https://github.com/medic/medic-webapp/blob/master/api/src/routing.js#L533) can be removed and move this line up to the [favicon route handler](https://github.com/medic/medic-webapp/blob/master/api/src/routing.js#L156):

```js
writeHeaders(req, res, [['Cache-Control', 'public, max-age=604800']]);
```

To test this
- load the login page in an incognito browser you should see a network request for `favicon.ico` - make sure it has this header
- then load the login page in a regular browser and refresh the page and ensure you only see the request being made the first time
- then log in to the app and ensure the favicon isn't loaded again - the icon URL should now be the same for the login page, webapp, and admin app so it should only be requested once

**Comment by garethbowen** [comment]
@Jodge Could you have a look at this when you get the chance?

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev`, v3.4
