### ISSUE TITLE
Deprecation warning running add-branding-doc migration

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5026]
On API startup when the add-branding-doc migration runs I'm getting a deprecation warning in the logs.  Everything starts up as expected.

**Steps to reproduce**:
- On a fresh instance, start API

**What should happen**:
- No warnings shown in the log

**What actually happens**:
 - A warning is shown in the log

```
2018-11-26 09:11:04 INFO: Running db migrations… 
2018-11-26 09:11:04 INFO: Running migration add-branding-doc... 
(node:14996) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2018-11-26 09:11:04 INFO: Migration add-branding-doc completed successfully 
2018-11-26 09:11:04 INFO: Database migrations completed successfully 
2018-11-26 09:11:04 INFO: Medic API listening on port 5988 
```

**Environment**:

- Instance: localhost
- Browser: N/A
- Client platform: Ubuntu
- App: API
- Version: head of master (3.4.0)
- Node: v10.13.0

**Comment by Jodge** [comment]
I see, this eluded me since my ubuntu was running on node `v9.x.x` but I have since upgraded to latest `v11.2.0` and been able to see the Deprecation warning.

I think https://eslint.org/docs/rules/no-buffer-constructor will also come in handy once we Switch to #5030 to prevent future occurence

**Comment by Jodge** [comment]
@garethbowen I ran a quick check on the api project and noticed that the deprecated Buffer constructor is still being used in other migration scripts. Probably a general ticket can be opened for it?

**Comment by garethbowen** [comment]
@Jodge Good idea. It could be used elsewhere too. It'd be good to get eslint in to catch these...

**Comment by ngaruko** [comment]
LGTM. Api starts with no error/warnings. Are you opening another issue to cover other areas where the buffer constructor is used as [suggested above](https://github.com/medic/medic-webapp/issues/5026#issuecomment-441574980) @Jodge ?

**Comment by Jodge** [comment]
@ngaruko for Buffer constructor deprecation warning, #5030  will handle that
