### ISSUE TITLE
Branding doesn't update on login page

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5029]
The branding (favicon, logo, and title) on the login page should match the branding in the app. Currently only the favicon matches.

Update the login page to fetch the title and logo from the branding doc rather than hardcoding them to Medic Mobile branding.

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev` 3.4 by changing `branding.title` in `couchDb` and checking if it propagates to the UI:
![image](https://user-images.githubusercontent.com/6979995/50862422-752dc480-1400-11e9-8340-d159e341a562.png)

![image](https://user-images.githubusercontent.com/6979995/50862506-aad2ad80-1400-11e9-9abf-60738f181999.png)

**Comment by garethbowen** [comment]
@ngaruko That screenshot isn't of the login page - did you check the login page?
