### ISSUE TITLE
Loading Targets tab as admin logs an Error

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5071]
**Steps to reproduce**:
 - Log in as admin
 - Click on Targets tab

**What should happen**:
 - The message "Analytics are disabled for admin users. If you need to see analytics, login as a normal user." is shown on screen.
- No errors in the console.

**What actually happens**:
 - The message "Analytics are disabled for admin users. If you need to see analytics, login as a normal user." is shown on screen.
- An error in the console.

URL: /medic/_design/medic/_rewrite/#/analytics/targets

```
Error fetching targets SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
	targets http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:193672:27
	init http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:193666:14
	processQueue http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:44052:37
	scheduleProcessQueue http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:44100:27
	digest http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:45213:15
	evalAsync http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:45533:15
	completeTask http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:47332:7
	timeoutId http://localhost:5988/medic/_design/medic/_rewrite/js/inbox.js:32928:7
 inbox.js:41674:16
```

The line corresponds to the `JSON.stringify` [call in the TargetGenerator service](https://github.com/medic/medic-webapp/blob/master/webapp/src/js/services/target-generator.js#L96).

**Environment**:

- Instance: localhost
- Browser: Firefox
- Client platform: Ubuntu
- App: webapp
- Version: master (3.4.0)

**Solution**

The problem is when you're admin you don't have a `userContact` so it's trying to stringify `null` which throws so we should wrap that in an if block.

For extra performance consider skipping the `TargetGenerator.init` altogether if the RulesEngine is disabled because it's never going to get any targets emitted.

**Comment by ngaruko** [comment]
LGTM
**_before_**
![image](https://user-images.githubusercontent.com/6979995/50757268-a2288d00-12c3-11e9-835f-98a8b185d57f.png)

**_after_**
![image](https://user-images.githubusercontent.com/6979995/50757286-b10f3f80-12c3-11e9-935a-40f6b0d4c6a3.png)
