### ISSUE TITLE
Forms still available after deleting them using medic-conf

### ISSUE THREAD

**Issue by binokaryg** [medic/medic-webapp#5078]
The forms deleted using medic-conf are still available and usable from the web app.

**Steps to reproduce**:
 - Deleted an existing form that was visible in the web app under "New Action":
`medic-conf --url http://admin:<password>@localhost:5988 delete-forms -- report_id`

It says: 
```
INFO Starting action: delete-forms…
INFO delete-forms complete.
INFO Deleted form: report_id
```
 - Checked the form in "New Action", it is still visible and usable.
 - Checked in Medic Mobile administration console - Forms: The form is not there.
- Checked in couchdb (medic-client/forms): The form is not there.

**What should happen**:
 - The deleted form should no longer be visible in the web app.

**What actually happens**:
 - The deleted form was available for use.

**Environment**:
- Instance: _(demo-cht.dev.medicmobile.org)_, also replicated in local instance
- Browser: _(Chrome)_
- Client platform: _(Windows)_
- App: _(webapp, medic-conf)_
- Version: _(3.0.0)_

**Other**:
I also tried by reloading the web app several times, logging out and in again.
The form disappeared only after clearing the site data from (Chrome) Developer Tools - Application - Clear storage - Clear site data - Reload

**Comment by garethbowen** [comment]
@binokaryg Awesome issue! Thanks for providing so much info, it really makes our job easier.

**Comment by ngaruko** [comment]
LGTM.
The deleted form disappeared after page reload. Checked with @binokaryg and we agreed that this is good enough for this issue.
Closing
