### ISSUE TITLE
Make content-security-policy more strict

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5082]
Modify [our helmet configuration](https://github.com/medic/medic-webapp/blob/master/api/src/routing.js#L113) to set a stricter `content-security-policy` header. Currently it's set to `frame-src: 'self'` which is less than the default options and deprecated in CSP v2. Read [this page](https://content-security-policy.com/) to work out what we can set.

**Comment by ngaruko** [comment]
Any clue how to AT this @garethbowen ?

**Comment by garethbowen** [comment]
Make sure the response headers enforce an adequate level of security. There are websites which can test at least the login page and make security recommendations. Read the linked page and ensure we follow their guidelines where possible.

**Comment by garethbowen** [comment]
@kennsippell Thoughts?

**Comment by kennsippell** [comment]
@garethbowen @ngaruko Looks like a regression from this change. Great catch!

I'm enroute to Mount Kenya - threw a fix together but not easy to test this right now. I'm seeing `To use this page your instance must be deployed via Horticulturalist.` I can push this through Tuesday or feel free to revert the change if this is blocking testing.

**Comment by SCdF** [comment]
@kennsippell yeah this page only displays if you used horti to deploy (if you don't use horti this page has no use to you).

You can pretend locally if you want the page to display by editing [the controller](https://github.com/medic/medic-webapp/blob/master/api/src/controllers/upgrade.js#L9-L15) and just returning some fake build info. 

(the page still won't actually allow you to perform deploys, but it will render allowing you to fix this issue)

**Comment by ngaruko** [comment]
will close this and test again once #5233 has been done

**Comment by kennsippell** [comment]
@ngaruko Yep -- I'd expect that to be fixed by this. Worth confirming once the PR merges.

**Comment by ngaruko** [comment]
I still see this error @kennsippell . But I am testing on local atm. Do you think it is a parameter that is not maybe defined on the local env and would rather work on our server? 
Firefox: ![image](https://user-images.githubusercontent.com/6979995/52612230-bcbadb00-2eed-11e9-8c5d-9dfb4d9258c4.png)

Chrome:
![image](https://user-images.githubusercontent.com/6979995/52612264-d1976e80-2eed-11e9-9f8e-3e2dee3784ba.png)
