### ISSUE TITLE
CouchDB 2.3.0 has reduced the allowed length of GET requests

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5083]
When making a view request PouchDB switches to use a POST if the URL with parameters exceeds [2000 characters](https://github.com/pouchdb/pouchdb/blob/fb2ab0afe57a51da574ee3fac0bf1bd59fdbe502/packages/node_modules/pouchdb-abstract-mapreduce/src/index.js#L262). Against CouchDB 2.2.0 GET requests this long work as expected, but in CouchDB 2.3.0 they fail at around 1370 characters.

1. Raise an issue with CouchDB to change the limit back or at least document the change.
2. Raise an issue with PouchDB to change their limit - ideally submit a PR.
3. Patch our PouchDB in webapp, api, and sentinel to have a lower limit to be removed once it's fixed properly either by Couch or Pouch.

Thanks @dianabarsan for finding this!

**Comment by dianabarsan** [comment]
The issue has been marked as a bug [by CouchDB folk](https://github.com/apache/couchdb/issues/1810) and resolving it requires updating a CouchDB dependency (`mochiweb`).

We can work around it by changing CouchDB configuration, specifically:

```
[chttpd]
server_options = [{recbuf, undefined}]    
		|
		V
server_options = [{recbuf, some_positive_integer}]
```

The value we should choose is up for debate, more details about what `recbuf` is can be found [here](http://erlang.org/doc/man/inet.html#getopts-2).
[This](https://github.com/apache/couchdb/issues/1409) is the original issue that caused this change. I'm unaware if we've had problems of the sort. 
Pre CouchDB 2.3.0, this value was defaulted to `262144` and it was part of `chttpd.socket_options`:
```
[chttpd]
socket_options = [{recbuf, 262144}, {sndbuf, 262144}, {nodelay, true}]
```

I've created a [PR #5105](https://github.com/medic/medic-webapp/pull/5105) to demo the fact that adding the config works.

**Comment by dianabarsan** [comment]
As this bug can be avoided by changing CouchDB configuration, I've opened an issue in `medic-infrastructure`.

**Comment by SCdF** [comment]
@dianabarsan this looks to also affect our Search service, and at least locally following the instructions in the infrastructure report hasn't fixed it:

![image](https://user-images.githubusercontent.com/583851/50339440-8a08ed80-050f-11e9-9566-70b23a3cf094.png)

**Comment by SCdF** [comment]
Talked to @dianabarsan , I mis-read the infra ticket and changed the wrong value. After changing that value locally everything works.

I will raise a separate ticket to have this happen for devs in Grunt
