### ISSUE TITLE
Lazy loading contact RHS sections

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#5086]
Don't block rendering the page waiting for all the content, instead each section will load with a spinner with the content being rendered when ready. 

The shifting of content within the page from spinners is concerning, but we discussed two mitigations which can be investigated:

1. when the UI shifts, attempt to adjust the scroll position to minimize the disturbance, or if that isn't possible.
2. ignore any user touch for 1 second after shifting of content above the current scroll position.

Information in the contact summary which requires reports to be loaded should be moved into condition cards.

This is "Option 2c: Loading spinners" from [this design deck](https://docs.google.com/presentation/d/1TThN7MkhEB12np2x3o7evJRz0Gqb3E69Zll68pb8X-I/edit#slide=id.g498531a5d1_0_424).

Split off from #4445

**Comment by garethbowen** [comment]
Assigning to @alxndrsn as he's already done most of the work here.

**Comment by ngaruko** [comment]
LGTM. 
However, each time one click on a contact on the LHS, there is this split-second spinner that shows and makes the UI looks a little glitchy. Maybe we should time the spinner and not attempt to show if if the contents loads within half a second... or whatever. Do you want to have a look and give your 2 cents on this @garethbowen ?

**Comment by garethbowen** [comment]
Do you mean there's a spinner on the RHS before the sections with individual spinners load? Can you share a video?

**Comment by ngaruko** [comment]
> Do you mean there's a spinner on the RHS before the sections with individual spinners load? Can you share a video?

Yes @garethbowen. There is a spinner for every item on the RHS and if the loading is fast enough, the spinner flashes for a split second.... We have our both instances back to 3.2 for Release testing. I will capture the screen once we come back to 3.4

**Comment by ngaruko** [comment]
Here is the screen recording @garethbowen . As you can see, the contacts are loading fast enough but the spinner still shows up for a split second, which looks a bit glitchy. 
[lazy loading.mov.zip](https://github.com/medic/medic-webapp/files/2702148/lazy.loading.mov.zip)

**Comment by garethbowen** [comment]
Ok, I think that's just because you have a fast computer. Can you try on a Tecno and see if it makes more sense?

**Comment by ngaruko** [comment]
Agree. Fast computer, plus local install. It doesn't show now on `gamma.dev` since we have lots of data there. So, I guess in production, with tecno and the network, this might not be an issue. So, I will close this and wait for a `field` complain in the future, if any....

**Comment by isaacholeman** [comment]
Hey @amandacilek it looks like the UX issue that @ngaruko noted above is a real issue especially for facility-based users, even if it's low priority because it won't affect our most typical low-end-Android-user. Would you make an issue and put it in the UX backlog?
