### ISSUE TITLE
E2E test failure for developers with >300 documents in _users database

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#5113]
E2E tests fail with error: 
```[11:24:03] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Closing report
[11:25:15] E/launcher - API and Sentinel should start within 60 seconds
Timed out waiting for promise to resolve after 60014ms
[11:25:15] E/launcher - TimeoutError: API and Sentinel should start within 60 seconds
Timed out waiting for promise to resolve after 60014ms
    at Timeout._onTimeout (/home/kenn/webapp/node_modules/selenium-webdriver/lib/promise.js:2159:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

With the API service spending too much time in migrations. This happens because the performance of the `extract_user_settings` migration degrades with each document in the _users document.  Tests were failing for me with ~300 docs in _users.

Running the E2E test suite creates documents in the _users database which are not always properly cleaned up. Normal development tasks may require many documents to be created in the _users database.

Tasks:
* Improve the logging in the E2E tests to include something like "If API is stuck in migrations, try cleaning up your _users database"
* It could also tell you where the logs are to check where it got up to
* It could probably even tell you whether it was API or Sentinel that got stuck

**Comment by garethbowen** [comment]
This has been made obsolete by the work on #3476
