### ISSUE TITLE
Outgoing messages columns should not wrap on smaller screens

### ISSUE THREAD

**Issue by amandacilek** [medic/medic-webapp#5221]
Currently, when the screen size is decreased, the columns on the outgoing messages page wrap so that they are underneath earlier columns. This makes for very poor usability and makes the page nearly unusable. 

The App Settings console is meant to only work on desktop screens, but it needs to at least be somewhat responsive, so that those working on smaller laptops can still use it. Recommended approach: Never wrap columns! In the case of the 15 in laptop screenshot below, we should probably just be further reducing the width of the middle "Message" column to allow room for the "Last update" column in its proper place on the right. If the screen really gets too small, the columns should stay where they are, but just fall outside the viewable area, and the viewer can scroll left and right to view everything.

Here's what it looks like on my 15 in laptop at full size. The "Last update" column is wrapping to appear underneath the "Recipient" column.
![messages-wrapping1](https://user-images.githubusercontent.com/26235957/50918555-6097ff00-13f5-11e9-91d4-ca8d2aae0068.jpg)

The problems get even worse when you go even smaller. Here, you can see that three columns, "Status", "Due", and "Last update" and their data are now all appearing below the first three columns.
![messages-wrapping2](https://user-images.githubusercontent.com/26235957/50918830-20854c00-13f6-11e9-86b4-4fc1f003968a.jpg)

**Comment by garethbowen** [comment]
My proposed changes look like this:

![screenshot_2019-01-09 app settings](https://user-images.githubusercontent.com/2064938/50937086-30289180-14d7-11e9-8d3a-345b1f25fa76.png)
![screenshot_2019-01-09 app settings 1](https://user-images.githubusercontent.com/2064938/50937089-30c12800-14d7-11e9-931e-100bcbf90a6c.png)

**Comment by garethbowen** [comment]
Merged and backported to `3.3.x`

**Comment by newtewt** [comment]
@garethbowen  do you know what limit on pagination is for the outgoing messages? Also, as a side do we have a supported resolution for the app, admin console and we don't support the admin console on phones right?

**Comment by garethbowen** [comment]
>  do you know what limit on pagination is for the outgoing messages?

I don't follow - are you talking about the pagination at the bottom of the outgoing messages screen? I don't think there is a limit - you can have as many pages as you need.

> do we have a supported resolution

The admin console is only designed to work on big screens, not tablets or phones. We haven't specified a minimum but I would say 1280 is probably appropriate.

**Comment by newtewt** [comment]
Sorry, I meant how many rows are shown per page.  

Do we show 25 outgoing messages on page 1 and then page 2 would have up to another 25

**Comment by garethbowen** [comment]
Yes I think 25 is the page limit.

**Comment by newtewt** [comment]
@garethbowen  This looks good to me. I'm currently looking at this on local server since Gamma-b is currently down for muso upgrade. I'm ok with closing since it is a styling change.

**Comment by garethbowen** [comment]
Sounds good to me!
