### ISSUE TITLE
Clarify process for running e2e tests locally

### ISSUE THREAD

**Issue by kennsippell** [medic/medic-webapp#5227]
After #3476, the process to run e2e tests locally is unclear. The API service needs to be stopped and restarted with a custom command (in a configuring where it crashes when running a test).

We should have a single command to run e2e tests locally similar to `grunt e2e`.

**Comment by garethbowen** [comment]
@kennsippell @SCdF The PR has been merged - can this now be closed?

**Comment by kennsippell** [comment]
Yep
