### ISSUE TITLE
Interrupted replication fails because of `seq_interval` changes parameter

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#5235]
CouchDB 2.0 introduced an optimization on the _changes endpoint, used by sending the `seq_interval` request parameter. 

>seq_interval (number) – When fetching changes in a batch, setting the seq_interval parameter tells CouchDB to only calculate the update seq with every Nth result returned. By setting seq_interval=<batch size> , where <batch size> is the number of results requested per batch, load can be reduced on the source CouchDB database; computing the seq value across many shards (esp. in highly-sharded databases) is expensive in a heavily loaded CouchDB cluster.

PouchDB 6.4.x has been using `seq_interval` in all replication requests and I, mistakenly, forward this parameter to the upstream `_changes` request when doing filtered replication. 

PouchDB 6.4.x batches the `_bulk_get` requests when replicating (standard batch size is 100) - so every 100 changes it will write a remote checkpointer doc. The Checkpointer doc stores the last replicated seq. When writing this checkpointer, PouchDB decides that this seq is either the seq of the last change in the batch it has just processed OR the `last_seq` received from the _changes request. 

CouchDB _changes requests with `_doc_ids` filter, `seq_interval` and `limit` (these parameters are used in our upstream changes requests) don't populate seq-s in the expected positions: every n changes from head to tail, instead every n changes from tail to head.  (If the limit parameter is removed, the seq-s are positioned correctly - unfortunately we cannot remove the limit parameter as PouchDB library forcefully tries to batch changes requests). 

This issue has been fixed in PouchDB 7.0.0 (https://github.com/pouchdb/pouchdb/issues/6809) , 
but we are still affected by this.
Affected versions are: 3.0 and upgrades from 2.x -> 3.x (devices running Pouch 6.4.x replicating from Medic API 3.x).

**Comment by garethbowen** [comment]
Merged into `3.2.x`, forward ported to `3.3.x`, and submitted a PR for review to merge into `master`.

**Comment by garethbowen** [comment]
@dianabarsan Can you please add some instructions for how to AT this one?

**Comment by dianabarsan** [comment]
To trigger the error, you'd have to replicate an offline user by using an old version of PouchDB (7.4) and connect to a new version of the app. 
This was discovered while testing upgrading from 2.18 to 3.2. 

The testing I did followed these steps:
1. Run a 2.18 instance
2. Replicate an offline user (recommended to have a significant number of documents so you have enough of a window to interrupt replication down the line - a couple of thousand or more)
3. Set the browser tab in offline mode 
4. Delete the PouchDB's Checkpointer document in CouchDB (this document ID looks like `_local/<hash>` and PouchDB requests it before requesting `_changes` - so you can find it in your network tab) - this simulates the actual switch from Couch 1.x to Couch 2.x which happens during upgrades
5. Stop the 2.18 app and run a 3.2.1 app over the same DB
6. Go back to the browser tab with your offline user and set it online again, watching the network tab. Once it starts retrying to replicate, go crazy: set it offline again, refresh the window as many times as you like, repeat etc as we are trying to simulate network interrupts. 
Keep watching the network window. 
After you are fully replicated (the `_changes` requests return no results and the network tab is quiet), check that everything is in order and the app is updated, works correctly and replication was successful.

**Comment by newtewt** [comment]
I've done the AT as described with no issues. Also did a similar test using a techno. Although, I wasn't able to delete the check pointer. Going from 2.18 to 3.2.x branch locally worked as expected. I did get logged out during the disconnect phone from wifi network > upgrade to 3.2.x > reconnect phone to wifi

**Comment by dianabarsan** [comment]
@newtewt getting logged out depends on the connection timeout set in CouchDB (couch_httpd_auth.timeout) or whether or not you removed your cookies. 
Nothing related to the upgrade should remove your cookie or remove CouchDB sessions. 
What timeout value were you using and for how long did you keep your phone offline?

**Comment by newtewt** [comment]
After chatting with @dianabarsan  we found a potential new issue with refreshing after upgrading. Waiting for her results from digging into this issue. The original issue is fixed and this may spin out another issue. 

To reproduce:

Have an instance with 2.18.
Log in as an offline user in chrome. 
Ensure replication completes.
Check the offline box in dev tools network tab.
Delete the checkpointer as described above in couchdb.
Upgrade the instance to 3.2.x. 
Once upgrade completes uncheck the offline checkbox.
Wait for the replication to occur. 
The requests for the new app-cache, settings, and medic-client all occur in the network tab. 
The modal to update is never shown.
Manually refreshing the browser pulls the updated app.

**Comment by dianabarsan** [comment]
The problem described above by @newtnewt is not related to the original problem reported by the issue.
Instead it is caused by 3 things:
1. a folder structure + ddoc rewrite path changes that were done in 3.0 that are causing our manifest to move from `/static/dist/manifest.appcache` to `/manifest.appcache`
2. How application cache works and the fact that we are not registering a listener for the `obsolete` AppCache event
3. receiving the changes that would trigger the AppCache to be updated in very quick succession 

What happens is: 
 - Webapp receives an `appcache` or/and `_design/medic-client` change, which calls `applicationCache.update()`.
 - The browser tries to get the appcache.manifest file and gets a 404. 
 - This doesn't throw an error (that we try to catch) and doesn't fire an `error` event that we listen to, instead it fires an `obsolete` event that we don't listen to - hence no update prompt.
 
Side events: 
 - The `obsolete` event does INVALIDATE the cache, so on next reload the new resources are downloaded.
 - When multiple `applicationCache.update()` calls are done in quick succession, they are debounced with the immediate style (if one request is pending, the next ones do nothing), so effectively one request is executed.
 - if the 2 changes that trigger the cache update (ddoc and appcache) are received in quick succession, only one would effectively update appcache (one request + one obsolete event).
 - In the cases when the 2 changes that trigger appcache update are received separately, the first one would trigger the obsolete event while the second one would throw an error (there is no appcache to update at this point, it had been invalidated by the obsolete event before) that we catch successfully and show the prompt.
 This is why I was not seeing this in my tests, my `appcache` and `_design/medic-client` changes were farther apart and thus triggered 2 appcache updates instead if just one, like Nick was seeing in his tests.
 - if replicated and not reloaded, the app is unusable due to the code expecting permissions to exist in `medic-client` ddoc
 
 To demonstrate, these are some detailed logs:

![image](https://user-images.githubusercontent.com/35681649/51320047-5ade9100-1a67-11e9-944e-ad54f3cea02e.png)

**Comment by newtewt** [comment]
Closing this as the original issue is fixed. Created a new issue for the one found during testing.
