### ISSUE TITLE
Downgrade PouchDB to 6.x 

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-webapp#5257]
As of version 7.0.0 PouchDB no longer batches `_all_docs` and `_bulk_get` requests during replication (see related issue https://github.com/medic/medic-webapp/issues/5076 for detailed explanation and alternative solution), instead executes these requests attempting to get all docs it has received from _changes in one single batch. 

That has proven to make it impossible to replicate large users (10k+ docs), with these users either failing replication at the first `_all_docs` request or at the next `_bulk_get` request. On top of that, PouchDB has a fallback replication algorithm for cases when it's replicating from a 1.x Couch that does not implement `_bulk_get` endpoint, which is to request every document individually via `GET`. This causes Pouch to launch a very large number of GET requests concurrently, that trigger `ERR_INSUFFICIENT_RESOURCES` errors (maybe crashing the app on the phone? This is TBD). 

The quickest fix is to downgrade PouchDB used in Webapp to 6.4.3 (the version used in 3.0 and before).

**Comment by newtewt** [comment]
Replicating on large users is working again. No crashes and seeing the doc count over 14k before switched to loading rules on phones. Saw the app load on the upgrade-muso instance with Diana"s branch as well over the weekend. In browser I am seeing the app replicate and load fine. I'm also able to upload docs to server as well. Looks good and closing.
