### ISSUE TITLE
UX updates for Translations

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#533]
Here is feedback and mockup from @diannakane 

Here they are in order of priority, perhaps also weighted by my own sense of difficulty (for # 4 in particular):

1. Put `add new language` link/button within translation page
2. Divide up translations into sections (eg web app labels, outgoing messages) to make it clearer to edit
3. Protect the text from accidental edits, force a user to click "edit" before being able to change text
4. Ability to restore the default for each language

![ux translations](https://cloud.githubusercontent.com/assets/789512/3315264/f88b543e-f6f8-11e3-8640-ccd90f87aefc.png)

**Comment by garethbowen** [comment]
Translations/languages has been updated.

**Comment by abbyad** [comment]
This was covered by https://github.com/medic/medic-webapp/issues/737. Moving to Ready
