### ISSUE TITLE
Add "Reporting Rates" back in beneath "Analytics" tab

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#543]
When I install `kujua-lite` (with or without `muvuku-webapp`) from the alpha market on the latest `medic-os`, clicking on the _Reporting Rates_ tab yields the following console error:

![x](https://cloud.githubusercontent.com/assets/763977/3406208/56db5646-fd8a-11e3-8874-7f5861827e5c.jpg)

**Comment by browndav** [comment]
Superseded by #1032.
