### ISSUE TITLE
Ability to edit message

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#557]
Currently you can only edit the message/form facility. Extend this to edit more fields of the message/form. @abbyad can provide details on which fields to allow editing on.

This may require some thought, for example, if a schedule has been created based on content which is updated, the schedule should also be updated.

**Comment by abbyad** [comment]
This is now possible for all Enketo/XML forms. I doubt that we want to extend this to JSON forms, so I am closing this as a v0.6+ feature.
