### ISSUE TITLE
Ability to manually record Visits

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#618]
Allow users to manually record a visit from the list of scheduled messages. Users can edit the reported_date and facility. Add a flag to the visit document to make it clear that the visit was manually entered, and record the date it was recorded on, and who recorded it.

**Comment by abbyad** [comment]
Checking to see if this is still needed. @garethbowen is the original requirement covered having a manager submit a form on behalf of the CHW?

**Comment by garethbowen** [comment]
@abbyad that's right.

**Comment by abbyad** [comment]
Closing since there is now an alternative way to do this, and also because it will be superseded by other upcoming changes.
