### ISSUE TITLE
Updating a CHWs number does not change the recipient phone number for scheduled messages

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#638]
CHWs often change phone numbers, either due to inactivity or change in CHW. As a result a webapp user has to go through all reports and modify the phone number for the scheduled messages. This is no longer possible in the new UI, nor is it the most effective way to do this task.

We can tackle this in a number of ways:
1) Make it possible to edit the phone number within the scheduled messages' Edit feature
2) Make an explicit "change facility's phone number" tool
3) Using the phone number from the facility list only when the message is ready to be sent so a user can implicitly edit it there.

Preference from a user perspective would be 3, 2, 1, which unfortunately likely matches the implementation complexity. 

@diannakane @garethbowen any thoughts on this?

**Comment by abbyad** [comment]
What is the status of this issue? Has it been resolved by some other refactor?

**Comment by garethbowen** [comment]
I think it remains unresolved.

**Comment by abbyad** [comment]
Just confirmed that this is still an issue with the new Contacts tab - unfortunately it did not magically go away with that refactor.

I am marking as a bug since users changing a CHWs number would expect that they would get notifications to the new number.

**Comment by sglangevin** [comment]
This fix will come with #2635.

**Comment by abbyad** [comment]
This issue still needs to be addressed because a message scheduled to go out in 6 months will (incorrectly) use the phone number at the time of registration, even if the number has changed by then.

The fix from #2635 will help here only in cases where the phone number was changed **before** the report was submitted. Scheduled SMS use the phone number of the `reporting_unit` at the time the schedule is created, or the time the contact was created if sending to the `parent` or `grandparent` (since that info never gets updated in the nested/embedded "parent" field). So even with the fix, messages would not reach the right person if their number was changed after the schedule was created.

**Comment by mandric** [comment]
Assuming using references/joins instead of embedded docs is a 3.0 feature, `medic-api` support for updating child/related contacts via bulk edit api could be a solution here.

**Comment by garethbowen** [comment]
Fixed as part of #3627 - the phone number is now resolved just before sending using the configured `recipient` and the current doc, patient, and registrations for context.
