### ISSUE TITLE
Ability to save/restore settings from the webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#650]

**Comment by abbyad** [comment]
Yes, I think this was in the context of DIY so that a user could save all the settings from the webapp interface.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by alxndrsn** [comment]
@sglangevin this may be a priority for Standard.  If not, please close the ticket.

**Comment by sglangevin** [comment]
I don't think this is a priority for Standard right now as we have a standard set of config files being used by all partners. Closing.
