### ISSUE TITLE
ANC Analytics fails with large data sets

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#657]
Currently we limit the lucene query results to 1000 for performance reasons. This works fine unless the instance has more than 1000 preganancy registrations (eg: Saving Mothers). On this instance we increased the limit to 10000 however this exposed an issue where because we append a disjunction of patient ids (`patient_id:(a OR b OR ... OR z)`) we exceeded lucenes boolean condition limit: `... too many boolean clauses","code":400}`

Find a new way to generate the analytics statistics.

**Comment by browndav** [comment]
Appears to be resolved as of `alpha.1332`, and probably way before then.
