### ISSUE TITLE
If forms are not installed properly they show as being installed.

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#664]
Forms could be uploaded directly using the app-settings API, if you upload them directly this way as an array of object literals (how we typically distribute them) they appear as installed in the forms settings interface, yet they are not installed correctly because the format required is:

```
{ 
  “P”: [Form Object],
  “D”: [Form Object]
}
```

The forms should not show as being installed correctly unless they are also in the correct format. We should display a warning or just show no forms installed.

**Comment by nice-snek** [comment]
hi frand @abbyad, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by abbyad** [comment]
Closing as we haven't seen any problems with this. @mandric, please reopen if you disagree.

**Comment by mandric** [comment]
Do we even have a forms upload interface anymore? I think validation of forms should be done during upload.  But this gets into a bigger problem of validating app settings during upload as well. We should eventually remove any direct use of couchdb api and only be using medic-api when trying to talk to the database.  There is an issue open for adding an endpoint I think that's good enough.   It's worth keeping in mind that anytime you have direct interaction from user/script to couchdb it is an issue because there is no validation of data being done, it's like giving raw access to a data store.   Basically we need tickets for every time we do that.
