### ISSUE TITLE
add API endpoint for uploading/installing forms

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#667]
It should check for correct structure of JSON. Expect array and convert into object literal with form codes as keys.  Related #664

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
@mandric was this supposed to be added to the milestone?

**Comment by mandric** [comment]
I'm not sure, but I think we need this eventually.

**Comment by garethbowen** [comment]
We'll need this eventually but shouldn't be in the milestone.

**Comment by garethbowen** [comment]
This has been superseded by medic-conf.
