### ISSUE TITLE
Outgoing message size is not limited

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#670]
We should limit outgoing messages in the UI to the practical limits, as well as show the number of SMS needed to send multipart messages.

As per @browndav's comment on long messages:
`they'll be one logical message, but split across multiple over-the-air SMSs. We support reassembly on the receive side as well. Both directions also have what should be full UTF-16 (Unicode) support. The absolute upper limit on the number of message segments is 255, with (in theory) up to 255 multipart message groups in flight at any particular time. In practice, the maximum workable number of segments is around 20-30, and would take somewhere between 30 and 60 seconds to send. Another caveat: some telco paths (e.g. T-mobile to AT&T in the US) strip out information needed for message reassembly; in those cases, each segment becomes a separate SMS entirely.`

It would be great if the max number of outgoing messages was a setting in `app_settings`. That way deployments can tweak it per country or telco (eg 10 in countries where that is seen as the maximum in practice, or 1 in the US when the header is stripped by the MNO)

**Comment by SCdF** [comment]
@estellecomment please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

**Comment by estellecomment** [comment]
@abbyad @ngamita @henokgetachew @bishwas-medic Please advise : do you know if anyone has ever complained about problems with multiple-SMS messages not being glued back together into a single message on users' phones? 
I couldn't find any issues relating to this in medic-projects.
If no one is complaining about this, I think we can close, and reopen if someone complains.

**Comment by alxndrsn** [comment]
@estellecomment iirc gateway does not currently support this, but no one has noticed

**Comment by alxndrsn** [comment]
Point of pedantry: where @browndav says:
> Both directions also have what should be full UTF-16 (Unicode) support.
he actually means `UCS-2`, which unlike `UTF-16` is fixed-width.

**Comment by bishwas-medic** [comment]
@estellecomment we have a project where we experienced the issue of multiple SMS messages not getting glued back on user's phone. Few of the users had CDMA phones and only the first part of the multipart SMS were getting delivered. GSM phones were working fine. To address this issue, we had to shorten our outgoing replies. 

We haven't seen it happening on other projects with GSM phones, so it maybe the issue with the old CDMA protocol.

**Comment by abbyad** [comment]
This is now somewhat related to https://github.com/medic/medic-webapp/issues/3059, where we want to make sure no messages are unduly truncated.

**Comment by estellecomment** [comment]
So. Here's what we know.

In favor of single-SMS length :  
 - medic-gateway doesn't support multiple-SMS messages. 
 - users' phones sometimes don't support multiple-SMS messages (if they have CDMA)
 - from https://github.com/medic/medic-webapp/issues/3059, sentinel truncates outgoing messages to single-SMS.

In favor of multiple-SMS length : 
 - from https://github.com/medic/medic-webapp/issues/3059, messages are not always fixed-length because they can include user names (or other fields) that are variable length, so we could overflow unexpectedly.
 - nurses can write notes to be sent to the CHWs, which might not fit in a single SMS (https://github.com/medic/medic-webapp/issues/3059#issuecomment-275504900)

Also:
 - right now you can write infinitely long messages from Messages tab, which is bad.


Sounds like we should 
 - add support for multi-SMS in medic-gateway and sentinel (https://github.com/medic/medic-webapp/issues/3083)
 - add a limit to number of SMS per message, and make it limit editable in app_settings (so that projects with CDMA phones could have single-SMS).
 - enforce limit in the UI and in sentinel
 - optional : add a UI for message schedules that can have warnings when you go oversize (currently, adding scheduled messages is done through app-settings, so no warnings)

**Comment by alxndrsn** [comment]
@estellecomment IIRC, sending multipart messages which originate from the webapp should work fine with medic-gateway

**Comment by garethbowen** [comment]
@abbyad Is this solved by #3095 ?

**Comment by abbyad** [comment]
Only partly... we would need to limit the send message functionality according to the new `multipart_sms_limit` setting too.

# Modal
![image](https://cloud.githubusercontent.com/assets/789512/22906968/f6b615b2-f214-11e6-8349-afc63cad92f4.png)

# Messages tab
![image](https://cloud.githubusercontent.com/assets/789512/22906997/17413b0e-f215-11e6-9548-579be95ae422.png)

**Comment by garethbowen** [comment]
Consider trimming the SMS input when calculating the number of messages.

**Comment by ngaruko** [comment]
**_Testing on `gamma.dev` 3.3._**
Maybe we need to be a little bit more intuitive in this `error/alert` message @abbyad . I mean, when the number of SMS exceeds the configured number, the user won't be able to send the message (as expected) but there is noway to know what's wrong in UI.
![image](https://user-images.githubusercontent.com/6979995/48921944-2ecae780-eede-11e8-82aa-6b5a1bb0d69f.png)

Also there seem to be some inconsistencies in this feature. Basically we have at least three ways to send messages in the UI:
1 - Go to contact, pick a name, click `Send Message`... the modal appears (same as `Send Message` from `Messages Tab`)
![image](https://user-images.githubusercontent.com/6979995/48922149-b2390880-eedf-11e8-86a6-afbace484637.png)
(that's where the message is not sent but no indication as to why)

2 - On Message Tab, pick a message. Bottom of RHS, we have a `Reply to XYZ` textbox. In here, the same message that could not be sent in 1 is sent without issues.
![image](https://user-images.githubusercontent.com/6979995/48922267-879b7f80-eee0-11e8-87e4-331c7c6385e9.png)

3 - The 3rd is the admin app, not sure if we need to worry about it for this ticket...

Your thought @abbyad @SCdF @garethbowen ?

**Comment by garethbowen** [comment]
Number 3 is fine - that's testing SMS incoming and we have no control over that.

Number 2 is a bug - it should be consistent with Number 1.

And I think you're right - once you exceed the maximum SMSes we should show a second message saying "too many messages!" or something.

Reopening for so touch up work.

**Comment by garethbowen** [comment]
@wtekeu Would you mind having another look at this when you get the chance? Thanks.

**Comment by garethbowen** [comment]
Merged and backported to `3.3.x`
