### ISSUE TITLE
In "Reports" tab, with demo data loaded: Facility and timestamp filtering produces incorrect results

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#677]
Using a clean installation of medic-webapp with preloaded demo data, I'm seeing the facility and sent_timestamp filters fail to properly limit what's visible in the inbox. For example, clicking a single facility refreshes the left pane, but the new list still contains messages associated with facilities other than the one I selected.

**Comment by browndav** [comment]
Seen working in `alpha.1332` with the latest Medic OS development snapshot. Moving to ready.
