### ISSUE TITLE
Ability to "mark all read"

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#682]
If you have a large number of unread messages and want to clear the unread marker you have to select each message individually. If you don't clear the marker it makes the feature unuseful as it won't be obvious when another unread message arrives.

Possibly we could also mark all read on first load so users start with a clean slate.

**Comment by nice-snek** [comment]
hi frand @SCdF, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by SCdF** [comment]
Wow this is old.

@sglangevin / @diannakane do you two have thoughts here? I would argue that if mark as read is an important feature to have (and equally, the badge showing how many unread you have), mark all as read would be equally important? Mark as read is about managing an inbox after all, being able to attain inbox zero is an important strategy for some.

**Comment by SCdF** [comment]
Maybe @abbyad has an opinion too!

**Comment by abbyad** [comment]
I'll just jump in to say that how read statuses are shown (if at all) is a good topic for the design team.

**Comment by garethbowen** [comment]
I'll follow up with design and work out the importance of marking read in general, and mark all read as well.

**Comment by diannakane** [comment]
@garethbowen I'm interested in your user stories for this. Generally speaking, I will bundle this issue with understanding the various states and filters needed for history tab, part of the audit of that tab we've prioritized for this quarter.

**Comment by garethbowen** [comment]
@diannakane The theory is that if you have 10000 unread messages it won't be obvious which ones are new. This would happen if you're new to a project that's been running for some time, particularly as an administrator on a SMS based project. This feature would allow the user to clear the counter.

**Comment by SCdF** [comment]
> I'll follow up with design and work out the importance of marking read in general, and mark all read as well.

I'll hand it over to you @garethbowen

**Comment by garethbowen** [comment]
I've created a design issue to track the user design: medic-design/issues/59

Once that's done we can reopen this or create a new issue to implement the design.
