### ISSUE TITLE
District admins unable to see outgoing messages to unassigned numbers

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#698]
As a district admin I created an outgoing message to a non-facility number. This message was not visible to me, unless `Allow District Admins To View Unallocated Messages` was checked.

**Comment by nice-snek** [comment]
hi frand @mandric, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by mandric** [comment]
Assining to @abbyad for further comment because this is pretty old.

**Comment by abbyad** [comment]
Could not reproduce. I imagine this was resolved through other work in the last two and a half years.
