### ISSUE TITLE
Difficult UX for sending a message to an unassigned number

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#699]
If you type a phone number manually you must click on the number from the drop down or press tab for it to be used. If you just click the message box you lose the phone number you typed in. Not a bug, but I am highlighting this because I suspect many users will have the same experience as me. 

![image](https://cloud.githubusercontent.com/assets/789512/4959924/a680115e-66bd-11e4-898e-2acea99a1c52.png)

**Comment by abbyad** [comment]
Bumping this up as it was identified as a problem during UX testing as well. We have video of a user trying to send a message but the number keeps disappearing. After at least 4 failed attempts he decides to restart the browser and the vm. Eventually he gives up.

**Comment by garethbowen** [comment]
The selected option is now added on blur, even if it's a freetext number. This should fix the issue highlighted in the video.

**Comment by garethbowen** [comment]
This is "solved" by monkey patching the blur functionality of select2. A better solution would be to upgrade to select2 4.0.0 but this isn't actually released yet. The upgrade path will require a fair effort and it's not clear that upgrading would fix the issue, but it's worth a shot.

**Comment by abbyad** [comment]
This is much better. Clicking in the number field and out of it selects the first item. Is there a way to only highlight an item once characters are being typed into the text field? Otherwise clicking in the field and out keeps selecting the first item in the dropdown, with no way to cancel the open dropdown. Sharon also experienced this same issue. We can open up a another one to tackle this new issue.

**Comment by garethbowen** [comment]
Ok, more hacks, now only selects on blur when entering custom number. Also improved styling for custom numbers.

**Comment by abbyad** [comment]
Works very well now in 0.5.0-alpha.1254, moving to Ready.
