### ISSUE TITLE
Restyle the 'configuration' interface to match the inbox visual style

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#713]
The design team is going to create a mockup of `medic-webapp`'s 'configuration' section; this mockup will bring that administrative section's visual style in line with the inbox.

This is related to #712. This issue is intended to capture the visual style changes, whereas #712 captures the structural and functional differences.

**Comment by garethbowen** [comment]
I believe this is done - it's not quite consistent but it's enough to not be jarring.
