### ISSUE TITLE
Refactor: improve medic-sentinel performance and logging

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#714]
This issue depends on #708. Once we have a plan together, we need to actually refactor and improve `medic-sentinel`. Performance is the most critical issue for the codebase, but we'd also like to improve logging and debug-ability while we're in there.

**Comment by browndav** [comment]
Moving to acceptance testing; need to test round-trip message/reminder times in real-world conditions.

**Comment by mandric** [comment]
Need more detail on what kind of testing we need to do here.
