### ISSUE TITLE
Figure out how to accept data from ODK mobile data collection tools

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#715]
Allow data sent from ODK to be received by `medic-webapp`. For the time being, we can assume that (i) the ODK form is limited to integer, numeric, string, and date/timestamp fields; (ii) we have a suitable hand-built form definition already built that matches the ODK form; and (iii) that the ODK mobile app has a mobile data connection available to it.

This is a first small step toward interoperating with existing smartphone apps. That interoperability will take some project pressure off of our next-generation form/smartphone tools and allow us to take our time and do a good job.

**Comment by browndav** [comment]
To acceptance testing.

**Comment by abbyad** [comment]
Just clarifying that we are able to receive data from medic-collect (#893), which serves the original need of this Feature Request. The requirement to accept generic ODK XForms has been moved to #885.

Moving to Ready.
