### ISSUE TITLE
Easy Setup Wizard: Animation on fold-out panes not animated

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#730]
In the easy setup wizard, it looks like the expando sections are attempting to do a slide-up/slide-down animation, but failing to animate smoothly for some reason. We should take a look at this and make the animation smooth – it may be an issue involving CSS margins (which typically don't animate well, or even at all) but I haven't looked closely yet.

**Comment by garethbowen** [comment]
@browndav Any update on this?

**Comment by browndav** [comment]
I'm seeing rotation of the arrow itself, but I'm not seeing any vertical grow/shrink or slide-up/slide-down of the element that's being hidden / shown. Let me test in an Ubuntu VM really quickly, just to see if I can get it to animate there.

**Comment by browndav** [comment]
Appears resolved; closing. Will open a new issue if anything comes up again.
