### ISSUE TITLE
Rebuild the languages (translations) configuration screens in Angular

### ISSUE THREAD

**Issue by ghost** [medic/medic-webapp#737]
Split off from #712.

We've decided to built the new "Languages" configuration section (previously called "translations" at a few points) on the new visual layer in AngularJS. This will include language management, management of the actual translation text, and bulk import/export of `.properties` files.

![e70e2eaa-8061-11e4-80e1-b0af5a58afea](https://cloud.githubusercontent.com/assets/763977/5384164/477048aa-806c-11e4-917f-d62ee9217dd9.PNG)
![e711b0e8-8061-11e4-8095-6f89cce02731](https://cloud.githubusercontent.com/assets/763977/5384159/475e1c48-806c-11e4-9223-999a1a32888e.PNG)
![e7186848-8061-11e4-94da-18569821848b](https://cloud.githubusercontent.com/assets/763977/5384162/476a80c8-806c-11e4-9359-b75414d41a2c.PNG)
![5c7caed2-8062-11e4-87e7-f64f31425cda](https://cloud.githubusercontent.com/assets/763977/5384163/476d208a-806c-11e4-8d6f-23da9aa56e05.png)
![e700b612-8061-11e4-8aac-714301bffd9e](https://cloud.githubusercontent.com/assets/763977/5384160/476167fe-806c-11e4-8729-9f8f1975fb4e.PNG)
![e70e7eaa-8061-11e4-8d91-45bb9b1f2ed5](https://cloud.githubusercontent.com/assets/763977/5384161/47652786-806c-11e4-85f0-5ae23a44aa5c.PNG)
![e70d9fb2-8061-11e4-95fe-7368a58b4626](https://cloud.githubusercontent.com/assets/763977/5384165/4784e4ae-806c-11e4-9310-77a7cd241f95.PNG)
![e71d485e-8061-11e4-9712-bfbb2d369887](https://cloud.githubusercontent.com/assets/763977/5384166/4787879a-806c-11e4-9ebb-29a8ab52bbd8.PNG)
![e70e3418-8061-11e4-961d-518b45ddf4e4](https://cloud.githubusercontent.com/assets/763977/5384167/478bbf22-806c-11e4-8622-9defc6804155.PNG)
![e7198d9a-8061-11e4-8ecd-cb7a0115c14a](https://cloud.githubusercontent.com/assets/763977/5384168/47901270-806c-11e4-9a91-7e3c29c2a817.PNG)
![e6ff3878-8061-11e4-8722-561749d6c07f](https://cloud.githubusercontent.com/assets/763977/5384169/4795521c-806c-11e4-96a0-17b9d302b2bb.PNG)
![e70cb994-8061-11e4-97d3-5ba6b25780e7](https://cloud.githubusercontent.com/assets/763977/5384170/47980a0c-806c-11e4-8d8d-5d5a117445ac.PNG)
![e71c0502-8061-11e4-90cd-a2f3ffab0dcf](https://cloud.githubusercontent.com/assets/763977/5384171/47a5cde0-806c-11e4-8a18-807a70570212.PNG)L/

**Comment by abbyad** [comment]
Looks great in v0.4.3-alpha.1181. New issues can be opened for minor UI/UX changes, if any. Moving to Ready.
