### ISSUE TITLE
In the languages configuration page: allow users to manage translations for scheduled message rules

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#739]
Split off from #712.

We agreed that it'd be nice for users to manage all translation text from a single location. This issue proposes to add a new tab for scheduled message translations, inside of the #737 user interface.

Not a part of this issue: Forms have localized text embedded in them. Should we eventually have a similar UI to manage all localized text in those?

**Comment by abbyad** [comment]
Looks good in v0.4.3-alpha.1181. Moving to Ready.
