### ISSUE TITLE
app settings editor sets default instead of clearing properties

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#741]
(via shreya)  Somehow when it sees that there are no validations, it adds the default one. 

 Workaround: instead of doing a remove or clear, go into the text boxes and clear the actual validation texts and save the config.

![pasted image at 2014_12_11 12_19 pm](https://cloud.githubusercontent.com/assets/25641/5396253/ec7af9d6-8115-11e4-8c4f-a587936a3f28.png)

**Comment by abbyad** [comment]
Still experiencing this with 0.6.0-alpha.2013

### To reproduce:

- Delete all the `Registions`, `Patient Reports`, `Schedules`
- Save `app_settings`
- Reload app_settings page.

You will notice that the deleted sections and content has been repopulated. If you save the page you will bring the default settings back in.

_After deleting the defaults:_
![image](https://cloud.githubusercontent.com/assets/789512/10234643/ffac1b3a-6863-11e5-8e2e-1c1ad73a14ca.png)

_Upon reloading the settings:_
![image](https://cloud.githubusercontent.com/assets/789512/10234654/191a693c-6864-11e5-8012-aa2d18226ae6.png)

**Comment by mandric** [comment]
On workaround is to blank the values out (replace with empty string).  If I modify kanso.json and remove defaults you still get a rendered object and object with empty values.  Here's an example of a diff where I removed the validations and messages for a registration event saved it then refreshed and saved again.  The objects get auto-populated by the editor with empty values for some reason.  So there's functionally no different between emptying/clearing the values to begin with...

```
$ json-diff ~/tmp/settings-3 ~/tmp/settings-4
 {
   settings: {
     registrations: [
       {
         validations: {
           list: [
+            {
+              property: ""
+              rule: ""
+              message: [
+                {
+                  content: ""
+                  locale: ""
+                }
+              ]
+            }
           ]
         }
         messages: [
+          {
+            message: [
+              {
+                content: ""
+                locale: ""
+              }
+            ]
+            recipient: ""
+          }
         ]
       }
       ...
     ]
   }
 }
```

**Comment by mandric** [comment]
If you're in a pinch you might try managing it manually, via the [app_settings api](https://github.com/garden20/app_settings):

```
# fetch app_settings and filter out everything except settings property
curl http://admin:secret@localhost:5984/medic/_design/medic/_rewrite/app_settings/medic | \
    jq .settings > ~/tmp/settings-v1 
cp ~/tmp/settings-v1 ~/tmp/settings-v2
```
edit ~/tmp/settings-v2
```
curl -v -d @/fullpath/to/tmp/settings-v2 -X PUT \
    -H "Content-Type: application/json" \
    http://admin:secret@localhost:5984/medic/_design/medic/_rewrite/update_settings/medic?replace=1
```

**Comment by garethbowen** [comment]
The code looks fine to me.

**Comment by abbyad** [comment]
Works well, thanks @mandric.
