### ISSUE TITLE
Stuck with blank content in Mobile view

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#747]
In rechecking my steps for #746 I came across another situation... blank report and not being able to go back or clear filters. No errors were shown in console. Switching to Messags tab and back had blank content in both the Messages and Report tabs, although the Analytics tab does load. Only way to get it back was reloading app.

![screen shot 2014-12-06 at 13 07 07](https://cloud.githubusercontent.com/assets/789512/5416664/ccc9f5fc-81ff-11e4-82b7-11fdd36cfd86.png)

**Comment by garethbowen** [comment]
I just reproduced this by clicking one record, then while transitioning, clicking another record.

**Comment by abbyad** [comment]
Not able to reproduce anymore in v0.4.3-alpha.1181, moving to Ready.
