### ISSUE TITLE
Do not autorespond to numbers on Blacklist

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#750]
Following up on #201, users and administrators need to be able to ignore/hide messages from specific numbers or ranges of numbers. This is particularly important for MNO messages, which we do not want to respond to.

First iteration may just be available in `app_settings`, but eventually we will need some design work to decide the best way to present this to users.

**Comment by mandric** [comment]
We should also support blacklisting number like "Orange" since the telecom provider can create messages originating from that string.  Also does this feature only apply to auto-responses?  What if a valid form is sent via a blacklisted from string?  I assume we need to ignore responses setup by registration configurations or any other feature.

**Comment by abbyad** [comment]
We are finding several projects that end up in message loops with the operator when the gateway is out of credit. Once credit is added, all the pending auto-replies get sent, eating up the newly added credit. 

@browndav we already have a similar feature for not sending a number to the gateway, so would it be low effort to do something similar that to avoid sending to any other number as well? 

As pointed out by @mandric, we should accept text strings as well as phone numbers.

**Comment by abbyad** [comment]
If someone jumps in to take this, a good place to start looking is how we avoid message loops with the `gateway_number` in [medic-sentinel/transitions/default_responses.js](https://github.com/medic/medic-sentinel/blob/d595ccce027b7f654bc24d3458fc6d8df311976d/transitions/default_responses.js#L32)

**Comment by mandric** [comment]
How do we plan to define a blacklist?  Could it be a comma separated list of strings in app_settings somewhere?

**Comment by mandric** [comment]
Also assuming we need this feature on all branches/releases channels.

**Comment by abbyad** [comment]
Correct, we are getting urgent requests for this from many projects so we should push this to all branches.

Having it as a comma separated field in `app_settings` only would be acceptable for now. If we can surface this to the `configuration/settings/advanced` that would be even better.

**Comment by mandric** [comment]
Should we also consider having a "whitelist" option, so you only setup responses to numbers that are in the facilities list or something?

**Comment by mandric** [comment]
Thinking the blacklisted function might behave like this:

isBlacklisted(str, from)

| string| from | returns |
| ------------ | --------| ---- |
| +123 | +123 | true
| +123 | +999 | false
| +123 | +123999999 | true
| SAFARI | SAFARICOM | true
| +123,+456,+789 | +456 | true
| +123,+456,+789 | +4569999999 | true
| SAFARI, ORANGE | ORANGE NET | true
| SAFARI, ORANGE NET | ORANGE | false
| VIVO | HABLA VIVO | false

**Comment by abbyad** [comment]
That would seem to work well @mandric.

I think that having a whitelist would be good to include as well. My understanding is that you could send to a whitelisted number, even if it is in the blacklisted list. Is that right? 

Also, are we checking if it is a valid number before sending? This would be useful to know for creating the blacklists.

**Comment by mandric** [comment]
Nope, no checking if phone numbers are valid, we just take the number the gateway passed to us in the message and use it.

**Comment by mandric** [comment]
It might be useful to put a `warnings` property on a doc or something and when the system attempts to send a message to a blacklisted number the doc is marked with a warning.  Otherwise the silent failing to add a message or response could lead to confusion.  It might be useful for the system to have a way to say: "You wanted me to send to this phone but it's blacklisted."

**Comment by mandric** [comment]
Also for the record not crazy about using the term “blacklist” but can’t think of anything else at the moment.  Maybe “deny list” or “reject list”?

**Comment by mandric** [comment]
![screen shot 2015-10-07 at 1 32 43 pm](https://cloud.githubusercontent.com/assets/25641/10344123/eab7aa58-6cf7-11e5-9850-4b11d56a7f1d.png)

**Comment by mandric** [comment]
Example of two messages where first one has a pending message and subsequent was denied after configuring Outgoing Deny List:

![screen shot 2015-10-08 at 11 38 00 am](https://cloud.githubusercontent.com/assets/25641/10369520/14539174-6db1-11e5-8851-e13d17547caf.png)

**Comment by mandric** [comment]
Ready for code review, PRs at:
https://github.com/medic/medic-sentinel/issues/73
https://github.com/medic/medic-webapp/issues/1411

**Comment by garethbowen** [comment]
One small comment added to the sentinel PR.

You should also add a translation key for "state.denied" for rendering in the UI (as screenshotted).

Everything else is all good - merge when ready.

**Comment by mandric** [comment]
Will push to rc.dev shortly for acceptance testing.

**Comment by henokgetachew** [comment]
This works as expected for messages.  Not for reports, but it appears that that's not in the requirement.

**Comment by henokgetachew** [comment]
If the "accept only forms" setting is turned on, everything is parsed as a form and operator messages are also parsed as forms.  The deny list won't work for even operator numbers then.

**Comment by mandric** [comment]
![screen shot 2015-11-11 at 7 16 19 pm](https://cloud.githubusercontent.com/assets/25641/11103337/ebb7e7b6-88a8-11e5-9ad0-d926b592f0ae.png)
![screen shot 2015-11-11 at 7 15 48 pm](https://cloud.githubusercontent.com/assets/25641/11103341/effa223a-88a8-11e5-92e8-7a394b782e1a.png)

**Comment by mandric** [comment]
Not sure if I should flag the record (add an error to it).  Currently just shows up as valid with denied messages.

**Comment by garethbowen** [comment]
Looks good. I've added one comment about style preference.

**Comment by mandric** [comment]
Henok, a new RC build should be available shortly with this update.  Let me know if you have any time to acceptance test this one again, thanks!

**Comment by mandric** [comment]
@henokgetachew or @abbyad when you get a chance please acceptance test.  Latest RC is running here: https://rc.dev.medicmobile.org/
