### ISSUE TITLE
Untranslated strings appear in tour

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#752]
In the current alpha, there are some untranslated strings present in the tour, including one heading that appears to have AngularJS directives being rendered as text. Suspect it may have just been missed in one of the localization passes.

Ping me if you can't reproduce and I'll look at it more closely.

**Comment by garethbowen** [comment]
@browndav I can't reproduce this. I've gone through a bunch of the obvious things and it all checks out. If you could remember/reproduce it and let me know which tours and which steps aren't working I can do some more investigation.

Also it'd be useful to know if this was an upgrade or a fresh install. Adding new translation keys to an installed instance may be buggy...

**Comment by browndav** [comment]
Confirmed to be working properly in alpha 1131; moving to ready.
