### ISSUE TITLE
Medic Transport: Use libphonenumber for status verification

### ISSUE THREAD

**Issue by lman817** [medic/medic-webapp#761]
@garethbowen I hear you know of a good npm module for this? ;) We just need to be able to accurately match phone numbers.

**Comment by garethbowen** [comment]
Unfortunately not an npm module but I've bundled a private kanso module for us which is at `/packages/libphonenumber`.

It might be worth packaging it as an npm module as well or instead of the kanso package.

**Comment by lman817** [comment]
Oh ok cool thanks, you can tell I'm new to node because I use npm and node module interchangeably.

**Comment by browndav** [comment]
Closing; we're going to port the status-monitoring code in to master at a later date. Currently focusing on getting the smssync driver in to the master branch for the next OS release, minimizing other changes to medic-transport that might cause regression. Will file a new issue later on to fully integrate driver status monitoring.
