### ISSUE TITLE
Medic Transport: Refactor method of storing driver state

### ISSUE THREAD

**Issue by lman817** [medic/medic-webapp#762]
Currently, driver state is attached as a property of each driver in transport. As Dave pointed out, this could go horribly wrong if a driver implementation uses a private property of the same name. I couldn't come up with an elegant solution to this in the transport, so I simply moved the responsibility of storing state to the driver objects with get_state and set_state methods added to the driver prototype. On one hand this puts more work on the driver implementation, but on the other hand it improves upon state handling, in my mind crucially, by allowing each driver implementation the flexibility to deal with its own state (while maintaining transports' status updating mechanism).

**Comment by browndav** [comment]
This isn't bad; it'd allow drivers to expose state that's derived from elsewhere (e.g. a REST API somewhere). We might do both – have a setter/getter called `state`, but also store privileged information _about_ each driver up in medic-transport, i.e. outside of the `driver` structure but indexed by driver name.

**Comment by lman817** [comment]
The issue of indexing by driver name, or at least what I ran up against, is that I wanted to support having multiple drivers of the same name.

**Comment by browndav** [comment]
Closing; we'll refile when we port status monitoring in to master.
