### ISSUE TITLE
Guided setup welcome translation not working

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#763]
![screen_shot_2015-01-08_at_6 39 51_pm](https://cloud.githubusercontent.com/assets/2064938/5673782/cc0260b6-9805-11e4-8fa3-867101163da5.png)

Users language is null.

**Comment by abbyad** [comment]
Is this the same as #752?

**Comment by garethbowen** [comment]
That one mentions the "tour" but I'm not sure exactly where.

**Comment by garethbowen** [comment]
Basically a typo. Had to modify the translation a bit so this might not automatically work on existing installs but should work on fresh installs. To fix existing installs change the translation for `Hello {{name}}` to `Hello {{fullname}}`.

**Comment by browndav** [comment]
Confirmed fixed in alpha 1131; marking as accepted.
