### ISSUE TITLE
Braces not rendering properly

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#768]
In `help/messages` the braces are showing as `{~lb}` and `{~rb}`

![image](https://cloud.githubusercontent.com/assets/789512/5675372/9e4ca350-978a-11e4-9096-351549c93421.png)

**Comment by garethbowen** [comment]
This is fixed in the default translations for the help page. Existing installs may not be updated when appying this patch as we don't overwrite translation values, but this should be fixed in new installs.
