### ISSUE TITLE
Help pages out of context

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#769]
We need to figure out how/where to show all the help pages since the context is missing:

![image](https://cloud.githubusercontent.com/assets/789512/5675382/e47980b4-978a-11e4-9e66-0fa5c3cc4b10.png)

It may make sense to have a "help" in the config menu, and a high level help page in case you get there directly from the config front page.

**Comment by garethbowen** [comment]
I've removed the dropdown altogether on help pages. You can access the top level help page from under the hotdogs menu. It doesn't make sense to me to have it in both places. What do you think @abbyad ?

**Comment by garethbowen** [comment]
This has been refactored and works ok now. Please reopen if you come up with a better solution.

**Comment by abbyad** [comment]
It looks better, although it may be useful to have a way to go to the top level help page index. We can create a new issue when we update the UX of the help pages. cc @Lesterng

Moving to Ready
