### ISSUE TITLE
Store messages locally on SMSSync driver in case transport goes down

### ISSUE THREAD

**Issue by lman817** [medic/medic-webapp#771]
If we don't deal with this somehow we could end sending duplicate messages.

**Comment by browndav** [comment]
Scenario: Message A sent to smssync, transport turned off, transport turned on, smssync acks message A, transport says "I don't have a message A outstanding", adaptor never gets a success notification, adaptor provides the message again.

**Comment by browndav** [comment]
FWIW, this is specific to this driver, it's not a general driver issue. We might fix this without storage by just blindly forwarding the smssync ACK notifications to the app, i.e. not relying on a driver-maintained history of messages it submitted to smssync. This would change the API a bit, by putting the onus on the app to ignore notifications for messages that don't match any known message in the app's outgoing queue.

Not an emergency. We're going to defer this until we get everything else transport-related cleaned up and documented and debugged.

**Comment by browndav** [comment]
Closing; we have a number of other scenarios where downtime could potentially generate a duplicate message. We'll open a new issue if we need to solve this in a general-purpose way; I suspect other web service APIs are affected.
