### ISSUE TITLE
messages export changes on 0.4.3 need docs

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#773]
Do we have any documentation on the export changes that happened from 0.4.2 -> 0.4.3?  I just did an upgrade and noticed the messages export is different, on my test instance when exporting on 0.4.3 I get 305 messages but on 0.4.2 I get 51612.  Also the URL parameters appear to have changed?  So if something was polling it that might need to be updated.  Also there appears to be no option to export in CSV, which used to be the default.  I'll investigate a bit more in the git history but if you have any tips let me know, thanks.  

Using default options here are the URLs constructed during messages export:

messages export 0.4.2:
```
$ curl http://localhost/medic/_design/medic/_rewrite/export/messages?startkey=%5B9999999999999%2C%7B%7D%5D&endkey=%5B0%5D&dh_name=&tz=360&format=csv&locale=&reduce=false  | wc -l
     51612
```

messages export 0.4.3:
```
$ curl http://localhost/medic/_design/medic/_rewrite/export/messages?startkey=%5B%22null_form%22%2C9999999999999%5D&endkey=%5B%22null_form%22%2C0%5D&tz=360&format=xml&reduce=false | wc -l
     305
```

**Comment by garethbowen** [comment]
There are now two ways to export stuff - 1) click on the hotdogs, click on export, or 2) on the Configuration > Export page. The former is simplified and has no way of changing facility, form, or file format. The latter should be functionally equivalent to 0.4.2, ie: you can still pick "CSV".

The 0.4.2 URL still works so anyone polling should be unaffected, it's just the defaults have changed.
