### ISSUE TITLE
Issues with managing scheduled groups

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#785]
Muting, editing, or scheduling refresh the page to the Messages screen.

Secondly, when adding a message via the editing modal the `to` field is blank.

**Comment by garethbowen** [comment]
Could not reproduce the first one - will keep an eye out.

Fixed the second problem.

**Comment by browndav** [comment]
Hey Milan, would you mind taking a stab at acceptance testing this? Just looking for confirmation that it's fixed in the latest development build. Thanks!

**Comment by mandric** [comment]
In the modal editing window for a scheduled group:

1) The to field is not present/editable.
2) The messages in the edit modal are not ordered in the same way as the read view (by date).
