### ISSUE TITLE
Unchecking "accept plain-text messages" appears to have no effect

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#786]
"Accept plain-text messages: 
Check this box if you want to accept regular SMS messages in addition to reports. If unchecked, an error message will be sent to anyone who submits anything other than a report."

the error message should be different when in forms only mode and submitting an unstructured message.

**Comment by browndav** [comment]
@mandric: Does this issue still exist in the latest alpha?

**Comment by mandric** [comment]
Nope, can't seem to get it to work.

**Comment by mandric** [comment]
![screen shot 2015-05-15 at 7 41 27 pm](https://cloud.githubusercontent.com/assets/25641/7663236/6776c718-fb3d-11e4-9971-416817f2c1c2.png)

![screen shot 2015-05-15 at 8 04 43 pm](https://cloud.githubusercontent.com/assets/25641/7663245/ac2f5f5a-fb3d-11e4-98b6-d2a76af212d3.png)

Expecting an error message like "only forms allowed."

**Comment by mandric** [comment]
Failed.

Accept plain-text messages

"Check this box if you want to accept regular SMS messages in addition to reports. If unchecked, an error message will be sent to anyone who submits anything other than a report."

This option toggles `forms_only_mode` boolean value on app_settings object.

## Test 1

Check Accept plain-text messages option and submit message "arrar a ra". 

### Expected behavior

Message record is created with a neutral response message.

### Observed behavior

Message record is created with no response.


## Test 2

Uncheck Accept plain-text messages option and submit message "arrar a ra". 

### Expected behavior

Invalid report record is created with error response message.

### Observed behavior

Invalid report record is created with error, but no response message.


Note there is a difference between an error message and a error response.  The responses are managed by the `default_responses` transition and needs to be enabled (start_date in the past) for error responses to get setup.
