### ISSUE TITLE
Webapp crashes whens ending messages with excessive emojis

### ISSUE THREAD

**Issue by lman817** [medic/medic-webapp#789]
To reproduce, attempt to send a message starting with 'abc' followed by 20 or so flag emojis.

**Comment by browndav** [comment]
Is there a process crashing, or are you getting an exception from the JS interpreter in the browser? Is there a stack trace and/or message handy?

**Comment by lucasstreamable** [comment]
It's 400 errors on http calls in the browser. All those hitting the couchdb redirects I believe.

**Comment by browndav** [comment]
Did you clone yourself or something?

**Comment by lman817** [comment]
haha oops, I was on my air and an old one-off account was still logged in.

**Comment by browndav** [comment]
15 days isn't all that old (well, or startups are really moving fast these days).

Can you dump the request here, and trace it down at least to medic-api to see if there's any log activity or crash happening in there?

**Comment by lman817** [comment]
Here's the chrome devtools output:

http://localhost:5984/medic/_design/medic/_rewrite/facilities.json Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:5984/medic/_design/medic/_rewrite/read_records?group=true Failed to load resource: the server responded with a status of 400 (Bad Request)
inbox.js:111552 Error fetching factilities Object
http://localhost:5984/api/auth/%2Fmedic-reporter%2F_design%2Fmedic-reporter%2F_rewrite%2F%3F_embed_mode%3D2 Failed to load resource: the server responded with a status of 404 (Object Not Found)
http://localhost:5984/medic/_design/medic/_rewrite/message_contacts?endkey=%5B%22admin%22,%7B%7D%5D&group_level=2&startkey=%5B%22admin%22%5D Failed to load resource: the server responded with a status of 400 (Bad Request)
http://localhost:5984/medic/_design/medic/_rewrite/message_contacts?descend…mit=50&reduce=false&startkey=%5B%22admin%22,%22%2B15034327734%22,%7B%7D%5D Failed to load resource: the server responded with a status of 400 (Bad Request)
inbox.js:111552 Error fetching contact Object
inbox.js:111552 Error fetching contact conversation Object
http://localhost:5984/medic/_design/medic/_rewrite/facilities.json Failed to load resource: the server responded with a status of 400 (Bad Request)

I'm not really sure where else to hunt, the API looks fine.

**Comment by browndav** [comment]
Can you try replaying the request with `curl`, and then with `curl` directly against couchdb on port 5984? Modifying the couchdb log level might reveal a reason.

**Comment by browndav** [comment]
I guess what I'm saying is this: can I assign this to you to take a stab at? Maybe give it a half-day max and if you can't get to the bottom of it, we can punt and Milan and I will help?

**Comment by lman817** [comment]
I've been trying to dig into this, webapp is just a little overwhelming to debug. At least I've isolated that deleting the message in the db fixes it, but I'll post more questions here as they come up.

**Comment by lman817** [comment]
Here's the log output:

[Wed, 04 Feb 2015 20:03:48 GMT] [error] [<0.12668.3>] attempted upload of invalid JSON (set log_level to debug to log it)
[Wed, 04 Feb 2015 20:03:48 GMT] [info] [<0.12668.3>] 127.0.0.1 - - GET /medic/_design/medic/_list/tasks_pending/tasks_pending?include_docs=true&limit=25 400
[Wed, 04 Feb 2015 20:03:53 GMT] [info] [<0.26053.2>] Starting index update for db: medic idx: _design/medic
[Wed, 04 Feb 2015 20:03:53 GMT] [info] [<0.18881.0>] OS Process #Port<0.4404> Log :: function raised exception (new TypeError("doc.sms_message is undefined", "undefined", 2)) with doc._id 1baa6dac43c2a7a92237f15cbe917a32
[Wed, 04 Feb 2015 20:03:53 GMT] [error] [emulator] Error in process <0.12928.3> with exit value: {{nocatch,{invalid_json,{{error,insufficient_data},<<256 bytes>>}}},[{ejson,nif_decode,1,[{file,"ejson.erl"},{line,59}]},{ejson,decode,1,[{file,"ejson.erl"},{line,40}]},{couch_query_servers,os_reduce,3,[{file,"couch_query_servers.erl"},{line...

**Comment by browndav** [comment]
But really, isn't every emoji excessive?

**Comment by lman817** [comment]
commenting out https://github.com/medic/medic-webapp/blob/develop/packages/kujua-sms/kujua-sms/views.js#L278 fixes the problem

**Comment by browndav** [comment]
Right, but it'll cause the reduce-not-converging-rapidly-enough error from earlier.

**Comment by lman817** [comment]
Just pushed a fix for this, I'll close when verified.

**Comment by mandric** [comment]
@browndav can we close this?

**Comment by browndav** [comment]
I actually wouldn't mind regression testing this a big, but we can close and move to acceptance testing, sure.
