### ISSUE TITLE
Facilities filtering is difficult to manage

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#793]
Difficult to find facilities or select a subset (eg all facilities in District X):
![image](https://cloud.githubusercontent.com/assets/789512/6139406/4ae257c6-b159-11e4-9478-f78a85726636.png)

It would help if we sort the list alphabetically. May help to also group by district and health facility. Any other ideas?

**Comment by garethbowen** [comment]
I think you're right and it should be grouped by parent and ordered alphabetically, with the children slightly indented.

Alternatively we could have a select2 style search but this is only needed if you have say 30+ facilities.

**Comment by abbyad** [comment]
Whatever this filter ends up looking like it will likely be reused across several tabs since Contacts, Reports and Messages tab all need a Contacts filter of some sort.

While working on the UX for the new Contacts tab (#778) we came up with a cascading Facilities filter. It is shown as a series of connected filters, but may be better as a single large filter, similar to the way start and end date are included in a single dates filter.

**Comment by abbyad** [comment]
Great, much better! Moving to Ready
