### ISSUE TITLE
empty messages are not included in messages exports

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#798]
for both the inbox-messages export and the configuration (full) export.  Pretty sure we want to include all messages.

**Comment by mandric** [comment]
Experienced this using beta release.

**Comment by wtekeu** [comment]
@garethbowen I wonder if this is still a valid issue. It does not seem possible to send an empty message from the webapp. Is this related to SMS?

**Comment by garethbowen** [comment]
The information provided in this issue isn't sufficient really... It should include an example of the doc or steps to reproduce or something.

The messages export should also include automatically generated message which could theoretically be empty so I suspect that's what's going on.

I'm happy to close this and say that the export only shows messages that may be sent - if you've incorrectly configured the app to generate empty messages that won't show up in the export.

**Comment by garethbowen** [comment]
@wtekeu Thanks for taking the time to investigate this issue fully!
