### ISSUE TITLE
Upgrade to node 0.12

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#801]
Make sure kanso, packages, api, sentinel, etc all work on node 0.12

**Comment by garethbowen** [comment]
There is a bug in felix-couchdb (used by api and sentinel), lib/couchdb.js#220 - for some reason the sockets object has keys with a '::' suffix. This module hasn't been updated in years so I'm not sure we can get a patch in. We might consider switching to nano which looks better maintained.

**Comment by garethbowen** [comment]
https://github.com/kanso/kanso-utils needs to be pushed to NPM (waiting for permissions). Then update the dependencies in the following kanso packages and publish: modules, attachments, settings, dust, properties, duality. Check for others that depend on kanso-utils.

**Comment by garethbowen** [comment]
`grunt dev` is giving this warning: https://github.com/substack/node-browserify/issues/91

Upgrading grunt-browserify to fix it gives this error: https://github.com/joeybaker/remapify/issues/24

Ignoring the warning for now.

**Comment by mandric** [comment]
I have commit access to felix-couchdb, fwiw.

**Comment by browndav** [comment]
I'll file a medic-os issue to get node updated there.

**Comment by garethbowen** [comment]
I never got access to publish kanso-utils so I just changed the package in the committed code in the various kanso packages. I think everything works except felix which has been split off to #809

**Comment by garethbowen** [comment]
We're still getting a warning in browserify but it doesn't seem to be causing any issues. All other known issues are fixed.

**Comment by abbyad** [comment]
@browndav can you move this to Ready when you are satisfied with testing?

**Comment by browndav** [comment]
Seen to be working with `alpha.1332` on the latest Medic OS development snapshot. Moving to ready.
