### ISSUE TITLE
New phone numbers in Cameroon fail validation

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#802]
Several months ago an extra digit was added to all phone numbers in Cameroon. These updated numbers are not recognized as valid in the facilities list, not sure if it has been updated in libphonenumber yet.

All cell phones are now prefixed by a 6, all landlines prefixed by a 2. For instance +23750635999 is now +237650635999 (country code is 237).

Ideally these two numbers would be seen as equivalent in the webapp. That probably can't be done in libphonenumber, but for us we can assume that all numbers in the system are mobile numbers using the prefix 6, not 2.

**Comment by browndav** [comment]
I'd think it _has_ to be done in libphonenumber. IIRC libphonenumber does number normalization; should just be a matter of patching the rule set.

**Comment by browndav** [comment]
Looks like this is already fixed upstream: https://github.com/googlei18n/libphonenumber/issues/557

**Comment by browndav** [comment]
See also: https://github.com/googlei18n/libphonenumber/pull/612

It's unclear to me if they covered the landline case correctly.

**Comment by browndav** [comment]
Nevermind; looks right: https://github.com/alecx/libphonenumber/blob/metadata-update-20150215/resources/PhoneNumberMetadata.xml#L4398

**Comment by garethbowen** [comment]
I've bumped the library which fixes the bug. Open a new ticket for the feature request if needed.

**Comment by abbyad** [comment]
Confirming that it works with the updated libphonenumber in v0.4.3. 

It's in the Release market now so skipping Ready and marking as Released.
