### ISSUE TITLE
Sort out how to keep libphonenumber up to date

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#803]
It is critical that libphonenumber is kept up to date otherwise we start rejecting valid numbers and messages à la #802.

Furthermore it's critical that all our services use the same version of libphonenumber otherwise we could fail validation in strange and poorly handled ways.

Currently medic-webapp uses a custom build of libphonenumber for kanso, and medic-transport uses a [third party package](https://www.npmjs.com/package/libphonenumber). Unfortunately this package isn't updated regularly and is currently about 6 months out of date.

Firstly get both transport and webapp using the same package, which should be an npm package as transport isn't based on kanso.

Secondly make sure the npm package can be regularly updated, either by getting commit and publish permissions, or by branching and creating our own npm package. This package should be updated as part of the release process.

**Comment by browndav** [comment]
I'm not going to merge the medic-transport libphonenumber stuff yet; not quite happy with it or the status checking yet. I think I'm going to just merge the smssync/twilio drivers in to the current master, and then break the status checking / libphonenumber refactor/merge/documentation work out to a new issue.

In other words; I'll replace libphonenumber in medic-transport with whatever we decide on for the main app (somehow).

**Comment by browndav** [comment]
I suspect we need to move medic-transport out to a gardener module for this to work. I'll take a look this week and early next.

**Comment by browndav** [comment]
Going to close this for now, as (i) the features that require libphonenumber in medic-transport aren't going to land in `master` any time soon, and (ii) we almost certainly need to repackage medic-transport to run under gardener so that its libphonenumber is easy to update. I'll create an issue for item (ii).

**Comment by garethbowen** [comment]
This doesn't just affect medic-transport - we also need to keep it up to date for webapp. Whatever solution we come up with for webapp we can easily use for transport if and when it's needed.

**Comment by mandric** [comment]
One idea: centralize the lib in webapp so the phone `from` field can still be parsed on the server side at  record creation time (in couchdb) then add an http interface to medic-api for everything else that wants to use libphonenumber?

**Comment by alxndrsn** [comment]
Looks fine for webapp, but I don't see how this fixed `medic-transport`.

**Comment by alxndrsn** [comment]
Who is maintaining the node module?

**Comment by garethbowen** [comment]
> Who is maintaining the node module?

Some guy: https://github.com/seegno/google-libphonenumber

So far it's kept well up to date.

> Looks fine for webapp, but I don't see how this fixed medic-transport.

I ignored medic-transport because as Dave said...

> (i) the features that require libphonenumber in medic-transport aren't going to land in master any time soon, and (ii) we almost certainly need to repackage medic-transport to run under gardener so that its libphonenumber is easy to update. I'll create an issue for item (ii).
