### ISSUE TITLE
Contacts tab cannot import facilities from earlier versions

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#806]
With the new Contacts page you cannot import facilities exported from previous versions - gives a `error parsing file` message.

![image](https://cloud.githubusercontent.com/assets/789512/6590158/641098b8-c782-11e4-8de9-c75ead3ea9e7.png)

**Comment by garethbowen** [comment]
This was actually caused by importing contacts with IDs that weren't found in the database. I had code to handle this but it wasn't working correctly.

**Comment by abbyad** [comment]
The import "works" in the sense that data is imported, but the imported data is not what I would have expected. The facilities are migrated over to Places only, no Persons are created. The contact name and phone number are correct but not editable unless you manually create an equivalent person.

@garethbowen is that the intended behabiour? I would have expected a Person to be created for each Place, and that Person would be populated with the `Contact name` and `Phone number` fields from the facility. 

Leaving this discussion here since it fits within the title of the issue, but we can move to a separate issue as well.

**Comment by garethbowen** [comment]
That is not the intended behabiour [sic] and I thought I tested this. The data from the demo server is quite poor (lots of blank facility names and so on). I'll try again.

**Comment by abbyad** [comment]
I had updated the demo's facility data so that there would be no blanks prior to export. I suppose it has since been overwritten.

**Comment by garethbowen** [comment]
I've tested the data following data and it looks pretty good now: https://github.com/medic/medic-data/blob/master/data/generic-anc/demos/facilities.json

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1244, moving to Ready
