### ISSUE TITLE
Clear error message when reimporting Contacts

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#807]
When you import a file in the Contacts tab and you get an error the error is still visible when you click to resubmit, which is misleading:
![image](https://cloud.githubusercontent.com/assets/789512/6590189/aa4cd184-c782-11e4-8086-a36295ec3620.png)

It should be cleared as soon as Import is clicked again - and may reappear as needed if there is another error.

**Comment by garethbowen** [comment]
This is fixed, but you might find it flashes very quickly so it's hard to test. It will be more obvious if you upload an invalid file, and then upload a valid one as should wipe the error message and then do all the work to import the file so you'll have time to see it before the dialog disappears.

**Comment by abbyad** [comment]
I see it flash as you said, but not always. I don't think it's a bug anymore, so moving to Ready. However it would be nice to have some visual clue that a new error message pops up. It may need some animation like a momentary glow when it first appears. This is something we can get @Lesterng's opinion on, and open a new issue when it is figured out.
