### ISSUE TITLE
Scroll to top when showing contact's info page

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#808]
When you open a contact in mobile mode the scrolling position of the previously viewed contact is not reset. For instance, if you scrolled to the bottom of Contact A's info, and then open Contact B it will display the bottom of that contact's page, not the top. It should show the top of the contact's info page whenever a contact's page is displayed.

**Comment by garethbowen** [comment]
This seems to only affect mobile.

**Comment by abbyad** [comment]
Reopening as I see this issue still/again in 0.5.0-alpha.1223

**Comment by abbyad** [comment]
Still an issue in mobile view. 

The full view shows top of new contact after flashing the top of the original contact. Is there a quick way to make that less jarring?

**Comment by garethbowen** [comment]
This is a different approach. It's a little hard to prove because all of these solutions have worked on my machine.

**Comment by garethbowen** [comment]
Work towards making the transition less jarring is being done in #853

**Comment by abbyad** [comment]
Works briefly in Contacts on fresh load. If you switch to Messages or Reports tab and back to Contacts tab then it fails to scroll to top of newly viewed contacts.

I am now seeing the exact same behaviour all the time in the Reports tab, opening separate issue for it.

**Comment by garethbowen** [comment]
The Reports tab bug is a dupe, so test both as part of this issue.

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1323 in mobile view using Firefox.... although seeing odd behaviour in Chrome where the whole topbar slides over when opening a report,  and it scrolls with the page too. Will characterize that more and open a new issue if necessary.

Moving to Ready.
