### ISSUE TITLE
In demo/preload data: ensure all messages ship in the 'sent' status

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#816]
Currently, when a user plugs a GSM modem in to a DIY installation, the system attempts to send all pending messages. This has the unfortunate effect of (probably) spamming some poor person in the British Virgin Islands, since we're no longer using invalid phone numbers (due to libphonenumber validation).

If we ship the demo/preload messages as `sent`, this won't happen and everyone will be happy.

**Comment by browndav** [comment]
From Slack discussion: performance is bad via callbacks route; punt. We're going to try adding a magic setting for sentinel that just automatically forces messages in to the `sent` state as part of its already-being-performed PUT. Also, we're going to pipe the CI output for medic-data to a timestamping logger utility, so that the build logs will provide some (simple) idea of where the time is going.

**Comment by browndav** [comment]
Resolved by @mandric in CI; moving to acceptance testing.

**Comment by mandric** [comment]
On current versions of medic-data builds this is fixed.
