### ISSUE TITLE
Build new results API: allow medic-transport to report transmit success/failure for individual messages

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#817]
Currently, medic-transport acknowledges transmission success only, and only for multi-message batches. This isn't ideal. A mixed success/failure within a batch leads to either duplicate or dropped messages, medic-transport potentially retries failed messages forever, and the user interface provides no visibility in to the retry count or failure status of a message. Make failure information visible via the medic-webapp message UI. Build an API that medic-transport can use to report success/failure of individual message delivery.

Bonus second phase: also provide an API to support retry counts.

**Comment by browndav** [comment]
Moving forward to iteration 2015-18. We should find a way to get this done ASAP to unblock #818 and #819.

**Comment by browndav** [comment]
Closing as finished; moving to acceptance testing. #818 should serve as most of the acceptance testing.

**Comment by alxndrsn** [comment]
@mandric @browndav Did the bonus 2nd phase get completed?

**Comment by browndav** [comment]
@alxndrsn: Sorry, late on this, but... no. There's not currently any retry functionality in medic-webapp or at the top-level of medic-transport, but retries are supported in node-gammu-json (though they remain unused).
