### ISSUE TITLE
Make medic-transport use new transmit result reporting API

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#818]
Modify medic-transport to use the new results reporting API outlined in issue #817.

**Comment by browndav** [comment]
We found some bugs in the current implementation of `_handle_transmit_timer` in `lib/adaptor/medic-mobile.js`. See https://github.com/medic/medic-transport/blob/master/lib/adaptor/medic-mobile.js#L350. These bugs will likely cease to be an issue once we're using the status-change API from #817 instead of the HTTP callbacks, but should be fixed anyway to benefit currently-deployed projects:

1. We should use `eachSeries` so that drivers don't have to do their own queueing if they're managing some sort of single-user stateful resource;
2. If all `tx_results` are failures, we shouldn't invoke the http callback;
3. If we have successful `tx_result`s and then a hard error, we should still invoke callbacks;
4. We might want to stick a couple extra sentences of documentation in `register_transmit_handler`, making it clear that the error object is for "hard" driver-can't-continue errors, and the `tx_result.status == 'failure'` error is for message-specific errors that are likely caused by the content/addressing of the message.

Another note for later:

* If delivery is successful but we can't connect to `medic-webapp`, we should do something slightly more intelligent than pretending that the message delivery failed.

**Comment by alxndrsn** [comment]
Ref:
> If we have successful `tx_results` and then a hard error, we should still invoke callbacks
This is a bit disruptive, for a couple of reasons:
1. currently if an error is returned, then all other processing stops.  Should that behaviour continue?
2. should we report the error at all if we had some successful sends?

**Comment by alxndrsn** [comment]
Have pushed fixed for points 1-4.
I think there is a slight mismatch of how the errors vs failures are used in the transmit handler.  If there is a format problem with a message, then retrying the message is not going to help.  So if medic-webapp is responding, but saying that the message has unacceptable content, then this should be handled as a more absolute failure than e.g. medic-webapp is not responding.  Is the current severity of failure really treating these two kinds of cases backwards?

**Comment by alxndrsn** [comment]
(closed in error - waiting for code review)

**Comment by garethbowen** [comment]
Assigned to @estellecomment for code review.

**Comment by estellecomment** [comment]
LGTM. I don't know this code though, so not a very deep review.

**Comment by alxndrsn** [comment]
? What am I meant to be doing with this?
