### ISSUE TITLE
Port medic-transport SMSsync driver to `master`

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#819]
There are SMSsync and Twilio drivers in the medic-transport `dev` branch, but they need minor refactoring, additional test cases, and additional testing. The updated SMSsync driver is required to support the latest version of SMSsync.

**Comment by browndav** [comment]
Edited; prioritizing SMSSync driver for now.

**Comment by abbyad** [comment]
@mandric, this will allow us to use the stock SMSsync, correct?

We had this as part of Beta 2, but can reevaluate if we are far off from having this done..

**Comment by mandric** [comment]
Yes we would not need to maintain a fork anymore.

**Comment by mandric** [comment]
We dropped SMSSync support and rewrote the gateway see https://github.com/medic/medic-gateway
