### ISSUE TITLE
Hosted services: pull list of machines to back up from EC2 tags using AWS API

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#821]
Currently we have a static list of hostnames that are backed up daily. We have backup preference information attached to EC2 instances (using tags – `Backup`, either `true` or `false`) that we really should be using instead.

Dave: Create an IAM role for backup.dev.medicmobile.org and generate appropriate keys. Grant permission to the `EC2DescribeTags` API.

Milan: Modify backup scripts to pull the hostname list from `EC2DescribeTags`, push updated backup scripts to Github.

**Comment by browndav** [comment]
Lower priority for now.

**Comment by mandric** [comment]
Ok this is setup to happen in cron now via `backups/rsnapshot-hourly`.  I didn't get to setting up notifications on failures yet.  Thinking maybe we do that as another issue, or maybe there is one already.  @browndav assigning to you for code review, see PR above.

**Comment by mandric** [comment]
Ok @browndav this should be a little closer now.  Added make style generation and install targets.  See PR above (private).

**Comment by garethbowen** [comment]
I'm guessing this is done. Reopen if necessary.

**Comment by mandric** [comment]
Just needs a code review and a merge.

**Comment by mandric** [comment]
Feel free to reassign or schedule a call if the PR is too complex/hard to understand and you'd like a walkthrough.

**Comment by browndav** [comment]
29 commits reviewed, comments inline in PR.

**Comment by mandric** [comment]
FWIW I think it's easier to use the "Files Changed" tab in the PR rather than reviewing each commit.  It makes more sense too because any commit can be overwritten by additional ones, and you want to review the net change not incremental changes right?  This is one slick thing about GH I really like... PRs.  Thanks again for the review, will get it merged in a few minutes here.

**Comment by mandric** [comment]
Ok well it seems like this issue has had its little taste of glory, merged.  @browndav feel free to follow up on the comments in the PR above and we can continue to dev on master or another branch if we prefer.

**Comment by ngaruko** [comment]
Does this issue need any AT @browndav @mandric ?

**Comment by mandric** [comment]
I don't think so @ngaruko. It's already in production and working as expected.  This is also in system territory which I don't think you need to be concerned with?  I think you can stay focused on the webapp and mostly ignore systems/devops/sysops/infrastructure development?
