### ISSUE TITLE
Test SSL on SMSSync, and move all hosted instances to SSL-only as soon as possible

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#822]
In order to convert all instances to SSL-only we need to confirm the gateway can process new messages and outgoing messages using SSL.

**Comment by browndav** [comment]
Hey @henokgetachew – would you be interested in taking this on if you have time?

**Comment by browndav** [comment]
Moving this in to the current iteration; we should get project instances to SSL-only as soon as possible.

**Comment by browndav** [comment]
@abbyad: Is this something you might be able to try out?

**Comment by mandric** [comment]
seems to be working fine on our 2.4-debug build of smssync, tested on nepal.app.

**Comment by mandric** [comment]
Thinking a doc is in order here, on 1) how to configure SMSSync (we'll probably want to change gateway user passwords as part of this) and 2) the nginx.conf changes.

**Comment by mandric** [comment]
Somehow borked this one. SSL is not fully compatible yet because the callback does not define https anywhere, see example.  I think we need to add a protocol property to that callback and then make sure SMSSync respects it.  Having a look to see if SMSSync will need a patch or not.

```
  "callback": {
    "options": {
      "host": "myproject.app.medicmobile.org",
      "port": "",
      "path": "/medic/_design/medic/_rewrite/_db/_bulk_docs",
      "method": "POST",
      "headers": {
        "Content-Type": "application/json; charset=utf-8",
        "Authorization": "Basic eTpEWdhBOERyT1QtMCm1OMUpZ2F0ZXs="
      }
    },
```

**Comment by mandric** [comment]
It looks like using port 443 in the callback might do the trick...  https://github.com/medic/SMSSync/blob/b7db2c92f4806a64812f266832750efe36a71f04/smssync/src/main/java/org/addhen/smssync/messages/ProcessMessage.java#L546

**Comment by mandric** [comment]
I think we need a SSL related header in the proxy so we know when to use port 443 in the callback.  Here's the request as seen in the couchdb list/handler: 

```
{
  "info": {
    "db_name": "medic",
    "doc_count": 104,
    "doc_del_count": 3,
    "update_seq": 343,
    "purge_seq": 4,
    "compact_running": false,
    "disk_size": 64884848,
    "data_size": 13061052,
    "instance_start_time": "1430095160295261",
    "disk_format_version": 6,
    "committed_update_seq": 343
  },
  "id": null,
  "uuid": "61865e70ff09df97dd203d455b002a7c",
  "method": "GET",
  "requested_path": [
    "medic",
    "_design",
    "medic",
    "_rewrite",
    "add"
  ],
  "path": [
    "medic",
    "_design",
    "medic",
    "_list",
    "tasks_pending",
    "tasks_pending"
  ],
  "raw_path": "/medic/_design/medic/_list/tasks_pending/tasks_pending?include_docs=true&limit=25",
  "query": {
    "include_docs": "true",
    "limit": "25"
  },
  "headers": {
    "Authorization": "Basic eTpEWdhBOERyT1QtMCm1OMUpZ2F0ZXs=",
    "Connection": "close",
    "Host": "nepal.app.medicmobile.org",
    "User-Agent": "SMSSync-Android/v2.4-DEBUG",
    "x-couchdb-requested-path": "/medic/_design/medic/_rewrite/add",
    "X-Forwarded-For": "201.6.14.5",
    "X-Real-Ip": "201.6.14.5"
  },
  "body": "undefined",
  "peer": "201.6.14.5",
  "form": {},
  "cookie": {},
  "userCtx": {
    "db": "medic",
    "name": "gateway",
    "roles": [
      "gateway",
      "kujua_gateway"
    ]
  },
  "secObj": {
    "admins": {
      "names": [],
      "roles": []
    },
    "members": {
      "names": [],
      "roles": []
    }
  }
}
```

**Comment by mandric** [comment]
Maybe a `X-Forwarded-Proto: https` or something, @browndav I'll go with this header for now, let me know if you have suggestions.

**Comment by mandric** [comment]
It looks like our build of SMSSync will need a patch, nginx returns a 400 with this error:

2015/05/20 16:54:50 [info] 28050#0: *17798 client sent plain HTTP request to HTTPS port while reading client request headers, client: 201.6.14.5, server: _, request: "POST /medic/_design/medic/_rewrite/_db/_bulk_docs HTTP/1.1", host: "myproject.app.medicmobile.org:443"

**Comment by browndav** [comment]
Will it follow an HTTP to HTTPS redirect properly?

**Comment by mandric** [comment]
Current hack for time being until we patch SMSSync is to use this nginx config which leaves a hole for the SMSSync callback: https://github.com/mandric/vm-toaster/blob/ssl-only/platform/packages/medic-core/settings/medic-core/nginx/nginx.conf

**Comment by mandric** [comment]
This is fixed in the new messages API: https://github.com/medic/medic-api/pull/69
