### ISSUE TITLE
Problems following import of Contacts from Facilities

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#826]
After importing Facilities from the demo instance I have some odd behavior:
- No Person created for each of the Facility, but still a phone number shown for the Place
- Blank names in the Place filter 
- Search inconsistencies - Contact showing up even though it doesn't belong to the Catchment Area. The Place Filter doesn't seem to work properly with the Contacts - which may or may not be related to the fact that many Contacts were created by importing Facilities from a prior version.

**Comment by garethbowen** [comment]
This looks ok now that #806 is fixed.

**Comment by abbyad** [comment]
Seems OK now in 0.5.0-alpha.1244, moving to Ready
