### ISSUE TITLE
Create new round of demo contacts

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#827]
The demo contacts JSON should be redone to match the People & Places split with the new Contacts tab.

**Comment by browndav** [comment]
Hey @mandric, do you want to look at this one while you're in the demo data?

**Comment by mandric** [comment]
Wondering if this could be handled by the medic-api migration feature...

**Comment by abbyad** [comment]
Good point @mandric. There is a small issue with the migration as mentioned in the comments on #806. The import of Facilities only creates Places, not the corresponding People as well. Once that is resolved we could possibly use the migration feature and use that export as the new demo data.

**Comment by garethbowen** [comment]
We could rely on the medic-api migration, but it would be better to ship an updated version. The data will be ready sooner if we don't do any migration, it gives us access to the fields on the Person, etc.

**Comment by garethbowen** [comment]
Not all of the current demo facilities have a name and we now rely on Contacts having names in the UI, so we should make sure this is populated also.

**Comment by abbyad** [comment]
I believe all of the demo data does have a name here: https://github.com/medic/medic-data/blob/master/data/generic-anc/demos/facilities.json

If the import works properly (#806) then we can import it once manually, then export the Contacts and keep it in medic-data.

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1244, moving to Ready
