### ISSUE TITLE
Place filtering not working properly in Contacts tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#831]
As mentioned in #826, the Places Filter doesn't to work well for Contacts, but it may be because the contacts were imported from facilities on an an older instance.

The issues seen are:
- Contacts not shown when selected: 
![screen shot 2015-03-19 at 12 28 10](https://cloud.githubusercontent.com/assets/789512/6735237/69e25ada-ce33-11e4-810e-40b10c276cf4.png)

- All contacts shown even though only one (imported) item selected. I think all the Contacts shown are the ones that were imported, not any Person created since:
![screen shot 2015-03-19 at 12 33 52](https://cloud.githubusercontent.com/assets/789512/6735392/3b8b3520-ce34-11e4-9b20-6ec03434548c.png)

**Comment by abbyad** [comment]
Both of the screenshots below show what seem to be (minor) filtering issues. 

Only sub elements of the selected Place are shown, but not the place itself. I'd expect the place itself to also be shown.
![screen shot 2015-03-24 at 23 44 30](https://cloud.githubusercontent.com/assets/789512/6818056/c7b215ba-d27f-11e4-9925-263a9c5cfdfe.png)

Immediate children are shown even if the children are unchecked in the filter. I'd expect a place to not be shown if it is unchecked.
![screen shot 2015-03-24 at 23 46 14](https://cloud.githubusercontent.com/assets/789512/6818069/fef17fde-d27f-11e4-9879-2805f4872384.png)

**Comment by garethbowen** [comment]
Fixed so if you select only Catchment Area A, then you will see Catchment Area A and any Person whose primary location is Catchment Area A, but not Place children of Catchment Area A.

**Comment by abbyad** [comment]
Works like a charm in 0.5.0-alpha.1254, moving to Ready
