### ISSUE TITLE
Cannot switch between webapp tabs

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#832]
On FF in Windows I can get into a situation where the only way to switch between webapp tabs is to close another Firefox tab that was running the webapp. Once I do that I can switch between webapp tabs again.

Marking as a bug since the user experience is severely affected, even though the issue may lie outside of the webapp.

**Comment by garethbowen** [comment]
We haven't reproduced this in over a year. Closing.

**Comment by abbyad** [comment]
I haven't been able to reproduce either, and will hopefully never see this problem again.
