### ISSUE TITLE
Add friendly HTTP 4xx and 5xx error pages

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#838]
It's be really nice if we had a more friendly and visually-appealing page for HTTP `4xx` and `5xx` errors, with a retry button in the HTTP `5xx` case.

We'd probably want to do this at the nginx level.

**Comment by abbyad** [comment]
@browdav, can you post the basic template content of these pages (message, buttons, etc) then assign to @Lesterng for the UI design of these pages?

**Comment by browndav** [comment]
See #1606 for design details. We're looking for a simple responsive page that effectively communicates "something bad happened, it's not your fault, it may be a transient failure, click below to try again".

**Comment by mandric** [comment]
Do we want to treat 4xx and 5xx differently?

**Comment by browndav** [comment]
Yeah, definitely. IMO the 5xx is the higher priority right now though, since it directly affects users if we need to update server-side. I think the 4xx pages could be identical in design, though, just with different text and possibly a different action button (e.g. "go back to the beginning" rather than retry).

**Comment by browndav** [comment]
@lesterng: Could you please comment here when you get a chance?

**Comment by browndav** [comment]
@lesterng: Any comments here?

**Comment by alxndrsn** [comment]
Hi @Lesterng @browndav it'd be nice to get the designs for this; have you two made any progress?

**Comment by browndav** [comment]
This has had no discernible progress on the design front; closing the issue as it's not currently actionable. Will prioritize instance upgrades over this, and revisit when that is settled and deployment of new configuration data is simpler.
