### ISSUE TITLE
Action buttons appeared when no contact selected

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#839]
I haven't been able to reproduce getting into this state, but was able to get the Action buttons without having a Contact selected:
![screen shot 2015-03-23 at 23 37 27](https://cloud.githubusercontent.com/assets/789512/6795425/e77f9248-d1b5-11e4-8794-bc3a8d1f7052.png)

This can lead to confusion because it is unclear what would be Deleted, if anything. Clicking the Edit button showed the Add Place modal.

**Comment by garethbowen** [comment]
I think I can reproduce this - select the contacts tab, then select it again.

**Comment by abbyad** [comment]
Ya, that does it!

**Comment by abbyad** [comment]
This doesn't seem to be a problem in the other tabs, Contacts only.

**Comment by abbyad** [comment]
Cannot reproduce anymore (0.5.0-alpha.1246), moving to Ready
