### ISSUE TITLE
Cannot scroll down to see entire Easy Setup Wizard modal

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#843]
This is on a 1920x1080 screen:

![image](https://cloud.githubusercontent.com/assets/789512/6817989/d692891c-d27e-11e4-8060-d1434df5e122.png)

**Comment by garethbowen** [comment]
I've squished things down a bit to try and get it to fit. If it still doesn't work, please let me know the window height, that is, the height in pixels available to the page which ignoring your task bar, application title, URL bar, etc.
