### ISSUE TITLE
Sample contacts need to be updated for new Contacts tab

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#844]
Similar to #827, we need to update the sample contacts shipped with DIY to match the Place/Person split in the new Contacts tab.

**Comment by abbyad** [comment]
Looks good to me, moving to Ready.

@sglangevin, just a quick note to keep an eye out for the sample contacts to make sure they display and work as expected when you install DIY.

**Comment by sglangevin** [comment]
@abbyad Will have to wait until we resolve the issue of the new beta installer getting stuck starting services.

**Comment by browndav** [comment]
I'm assuming you're talking about getting stuck on the spinner in concierge. If so, and you haven't tried it yet, can you download and boot http://dev.medicmobile.org/downloads/medic-os/20150503/medic-os-v1.1.0-20150503-x64-virtual.iso and let me know if the getting-stuck problem goes away? #901, #907, and #915  were the issues that were tracking the first-run setup problems; the problems happened primarily on builds that were preloaded with the larger `demo` dataset (3650 records).

**Comment by sglangevin** [comment]
I'm talking about the .exe that Marc sent me a few days ago - I didn't get stuck on the spinner, I got the failure page, even after retrying a few times. I can try booting that new one on vmware and see, but I was referring to the most recent DIY installer that I had installed on my PC and the PC in the office. Does that make a difference?

**Comment by sglangevin** [comment]
@browndav works fine in that version - I was getting stuck on the "waiting for services to start" step before.

**Comment by browndav** [comment]
Okay, interesting. There's a known race-condition issue with the full-text search reindexing that I'm working on resolving now; it's _possible_ that's what you were seeing. The next image will have that fix plus an automated log-retrieval feature that should make debugging stuff like this a lot easier.

**Comment by sglangevin** [comment]
Cool, sounds good.
