### ISSUE TITLE
All reports shown when filtering for `ON` reports

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#845]
![screen shot 2015-03-25 at 00 12 11](https://cloud.githubusercontent.com/assets/789512/6818311/9462a9a0-d283-11e4-9cf4-9a55928fbd91.png)

The filter url: `http://192.168.249.128/api/v1/fti/data_records?include_docs=true&index=data_records&limit=50&q=%7B%22$operands%22:%5B%7B%22type%22:%22report%22%7D,%7B%22form%22:%5B%22ON%22%5D%7D%5D%7D&schema=%7B%22errors%22:%22int%22,%22verified%22:%22boolean%22,%22reported_date%22:%22date%22%7D&sort=%5Creported_date%3Cdate%3E`

**Comment by garethbowen** [comment]
It turns out we were using the standard lucene analyzer which ignored common terms such as "ON" and "NO". I've replaced this with a "simple" analyzer which seems to work.

**Comment by abbyad** [comment]
Works in 0.5.0-alpha.1254. Moving to Ready.
