### ISSUE TITLE
Cannot send Report from webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#848]
Using the + and "Send Report" opens a blank medic-reporter dropdown and I get the following error:
![image](https://cloud.githubusercontent.com/assets/789512/6834859/2c52c4fa-d30d-11e4-803a-fef63aed2ead.png)

Using 0.5.0-alpha.1246

**Comment by browndav** [comment]
Oh, fun. This is an unintended consequence of a "clickjacking" mitigation we added at the nginx level. I'll switch it over to SAMEORIGIN so this works again.

**Comment by browndav** [comment]
https://github.com/browndav/medic-os/commit/9119549

**Comment by browndav** [comment]
I'll check out the hosted instances, just to make sure none of them are affected. I'll backport the fix to https://github.com/browndav/medic-os/tree/master also, so it's easy for us to regenerate current-production ISOs with the fix applied.

If you just want to test it out, you should be able to SSH in to the DIY VM, edit `/srv/settings/medic-core/nginx/nginx.conf` with `s/DENY/SAMEORIGIN/`, and then run `svc-restart medic-core nginx` so the changes take effect.

**Comment by browndav** [comment]
Seen to be resolved in the latest Medic OS images with `alpha.1332`. Release on its way.
