### ISSUE TITLE
Incorrect text in Select Tour modal

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#849]
![screen shot 2015-03-26 at 11 09 03 am](https://cloud.githubusercontent.com/assets/1286381/6853498/d0f9c58a-d3a8-11e4-9288-07d7853a7860.png)

Says you can view the tour by clicking the cog in the top right corner, but the cog has changed to the hamburger icon.

**Comment by garethbowen** [comment]
I've changed the default message to "You can start a tour at any time by clicking the menu icon in the top right corner of the page. Which tour would you like to run?". This won't change in upgraded apps but will show up in new installs.
