### ISSUE TITLE
Remove one level of facility hierarchy for local install users

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#857]
DIY and other local install users will only have one level of hierarchy in their systems -- a facility and catchment areas with CHWs. Hide or remove the top level (named District Hospital) of the hierarchy for these users to streamline the contacts creation process.

**Comment by browndav** [comment]
Assigning to @abbyad to indicate need for feature triage/scheduling.

**Comment by abbyad** [comment]
This is DIY specific to make contact creation easier and more manageable for instances that have two levels only:
1. Management Level (eg Hospital, NGO, Health Center)
2. CHW Level

Adding the Design label and will come back to this with some concrete recommendations.

**Comment by abbyad** [comment]
Closing as the need for this is replaced by #910+ #858, and eventually to be replaced with the refactor of our current hierarchy system.

**Comment by abbyad** [comment]
Reopening this as a placeholder for this feature request in DIY Beta 3.

**Comment by garethbowen** [comment]
This will be solved by making the hierarchy configurable in #3639
