### ISSUE TITLE
Add character or SMS count in Send Message dialogue box

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#859]
Show users how many SMS messages will be sent based on length of message AND number of people selected to receive it. Character count is optional depending on how the system handles non-Roman characters.

**Comment by browndav** [comment]
More idle comments.

Character count (the numerator) is actually the easy one. It's technically "code units"; joined glyphs and certain characters like emoji/flags will count as more than one.

The number of messages segments produced ends up being a little harder to get exactly right, due to an edge case – see https://github.com/gammu/gammu/issues/95 – and possible differences in behavior between gateways around that edge case. But it's possible.

For what it's worth, the maximum segment size is 160 characters if every character in the entire multipart message is in the GAM alphabet (http://www.developershome.com/sms/gsmAlphabet.asp), otherwise it's 70. Segments can technically be smaller without any issue. There's an 8-bit binary mode that's 140 bytes per segment, but we don't use it (yet, anyway).

**Comment by browndav** [comment]
Assigning to @abbyad to indicate need for feature triage/scheduling.

**Comment by garethbowen** [comment]
A simple character count is already shown when the user nears the single message limit.

**Comment by abbyad** [comment]
The feedback that I got from @diannakane is that it could be helpful for users to know the character limitations as soon as they start writing a message.

We have a couple of design choice to make here - do we want to show `number of characters`, `number of messages`, and/or the `expected cost`? Once we know this we can figure out the UX and then implementation. 

Leaving this open with a `Design Work Needed` tag and assigning to Dianna to answer the first question. After that I will follow up to lead the UX work. Once the design work is complete we'll post mockups here and schedule the implementation accordingly.

**Comment by diannakane** [comment]
I had left it open to either of those options because I don't understand the technical implications of counting characters vs. counting SMS, in areas where non-Roman characters complicate matters. Is there a feasibility or technical preference in the matter?

**Comment by abbyad** [comment]
It seems as though showing the cost is another level of complexity that we don't want to get into now, so the question now is ideally what do we want to show? Number of characters, number of messages, or show both?

I'll leave the technical aspect to @browndav, but I think we could ignore the "minor edge case" as it would be fine for now to show our best guess at the number of messages.

**Comment by browndav** [comment]
Yeah, if an estimate that at most underestimates by one message segment is good enough, then it's straightforward.

**Comment by abbyad** [comment]
The default SMS apps on Android (Messaging and Hangouts) show the number of characters remaining once you get to 10 chars left. After counting down to 0 it starts back at 145, or 63 if outside of the GSM alphabet, with an indicator of how many messages total (eg `145 / 2` or `63 / 2`) and goes on from there. 

We can follow that example but always showing it and add some text to clarify what the numbers mean. Does that seem OK @diannakane?

Here is a take at the wording:
`160 characters remaining to be sent as 1 SMS`
`10 characters remaining to be sent as 2 SMS`

Other suggestions, something less wordy?

**Comment by garethbowen** [comment]
Something less wordy would be good to save space. How about:

`160 characters left`
`2 SMS, 10 characters left`

**Comment by abbyad** [comment]
That seems perfect to me! 

@diannakane is this suitable for you? If so we can plan to schedule this feature request.

**Comment by browndav** [comment]
Just to add more comparisons: iOS just leaves the improper fraction, e.g. `210 / 70`, and omits the part count.

We might use some word other than `SMS` for the number of message segments, as that implies (at least to me) that the message will be seen as separate pieces on the other side.

**Comment by browndav** [comment]
On the other hand, the segments are billed separately, and that's probably what matters here. Looks reasonable as-is, I think.

**Comment by abbyad** [comment]
Related to this we have an open issue (#670) to limit the number of SMS in a multipart SMS to a practical maximum.

**Comment by garethbowen** [comment]
I've updated the messages to

`160 characters left`
`2 SMS, 10 characters left`

The messages are now shown all the time, and aren't styled like errors.

**Comment by abbyad** [comment]
Looks great in 0.5.0-alpha.1323, and works smoothly when transitioning to non GSM-alphabet characters. 

Moving to Ready, and opening separate issues for future fixes.
