### ISSUE TITLE
"Start new Conversation" (aka Send Message) from bar in the Messages Tab

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#860]
Apply the convention used for "+ Person" and "+ Place" in the Message tab. From within this tab, there is no clear way to start a new conversation; users are mistakenly writing in the "reply" box at the bottom of an existing conversation. Users do not see the high-level "+" sign as related to the tab they are working in, nor is the "+" an intuitive way to "send" a message. We want to leave the high-level "+" where it is for now, but add a button to send a new message from the top bar in the Messages tab.

**Comment by browndav** [comment]
Assigning to @abbyad to indicate need for feature triage/scheduling.

**Comment by abbyad** [comment]
Moved to Scheduled as this is low hanging fruit: easy to implement, and increases usability based on feedback.

**Comment by abbyad** [comment]
Here it is with the tooltip:

![image](https://cloud.githubusercontent.com/assets/789512/7420831/cd7d25bc-ef4d-11e4-8210-b13a3fa51087.png)

Does that look good to you @diannakane?
