### ISSUE TITLE
Add "to" field in reply box on Messages right pane

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#861]
Users are not connecting this box with the reply action. Add "to" and automatically include the phone number of the person whom the conversation is with above the reply box.

**Comment by browndav** [comment]
Assigning to @abbyad to indicate need for feature triage/scheduling.

**Comment by abbyad** [comment]
@diannakane below are some screenshots. The first screenshot shows a `To` field, and has an "add recipient" link if they want the message to go to more people. When clicked it opens the `Send Message` modal with the contents and first contact prepopulated.

Does that match what you want?

![screen shot 2015-03-30 at 09 20 00](https://cloud.githubusercontent.com/assets/789512/6897225/4527118c-d6c0-11e4-81bb-22b49d1da37b.png)

![screen shot 2015-03-30 at 09 40 17](https://cloud.githubusercontent.com/assets/789512/6897312/d0989e5c-d6c0-11e4-95b8-1cae922752ce.png)

**Comment by diannakane** [comment]
I would change "to" to "reply to" and change "add recipients" to "add others". It's going to be more important than ever that we're clear about how to "send new message" in the top bar. I can imagine someone clicking "add others" and then deleting the original person as a workaround to not knowing how to start a new conversation.

**Comment by garethbowen** [comment]
My only concern with the "to" field is how much space that bar will take up in the mobile view. We might need to reduce the height of the message field.

**Comment by garethbowen** [comment]
What if we instead used the fields placeholder to say something like "Send a message to Janet +212121211"?

This means the footer can be one line tall, but we still need room for "add recipient" and the "x of y characters" message. Ideally for this we'd do something similar to the twitter site, where when you focus on the field it expands and you get additional options.

![twitter-before](https://cloud.githubusercontent.com/assets/2064938/6904669/0538832a-d77f-11e4-8775-0bdb968c2d31.png)
![twitter-after](https://cloud.githubusercontent.com/assets/2064938/6904672/07ab92b4-d77f-11e4-901f-b80c2cba7af6.png)

**Comment by diannakane** [comment]
Sure. Instead of "what's happening" we could say "reply to [Janet]..."?

**Comment by abbyad** [comment]
That could work, although I'd be curious to get hands on feedback from users who are less web-literate.

@garethbowen does the method you show leave space for adding recipients from that Reply box (#864)? Would you put the "Add recipient" below the box where you see "Add photo" in the Twitter example?

Another option is to have the "Reply To:" only in desktop mode. @diannakane do you think the "Reply To" portion is required for mobile mode?

**Comment by garethbowen** [comment]
> Would you put the "Add recipient" below the box where you see "Add photo" in the Twitter example?
Yes.

**Comment by garethbowen** [comment]
I've styled the textarea to be akin to the twitter screenshot, and updated the placeholder. I'll continue on this after the meetup!

**Comment by abbyad** [comment]
Looks good overall! 

Returning for minor issue... after clicking "Add Recipient" in the Reply box you get an errant "To" in the modal:
![image](https://cloud.githubusercontent.com/assets/789512/7163505/63e82ea8-e368-11e4-9644-81ed752d8a7f.png)

and after clicking in and out of the To box:
![image](https://cloud.githubusercontent.com/assets/789512/7163533/8bfeda7c-e368-11e4-8f30-537d95f9ba22.png)

We could remove the "To" altogether, but I'd be in favour of having an "add recipient" permanently as soon as the first contact is selected. That would also make it clear to users that they could always add a recipient in the to box. If that is a big task we can split it off to a new issue.

**Comment by garethbowen** [comment]
I've removed the "To" placeholder when adding recipient - this was actually a symptom of a bug. I looked in to getting the placeholder to be displayed after the recipient is added and changing the placeholder to say "add recipient", and unfortunately this looks like it'll be quite difficult with select2.

If you think some text is needed it might be better to add a label for the field, say "Recipients", which is consistent with the other forms in the app.

**Comment by abbyad** [comment]
I now see the "To" only on first load, but it is gone if any other recipient is added:
![image](https://cloud.githubusercontent.com/assets/789512/7420785/602d03ec-ef4d-11e4-8081-5255c2e51749.png)

@diannakane do you want to take a look and move to Ready if it is OK with you?
