### ISSUE TITLE
Post update task does not report completion

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#863]
The webapp opens fine, so the update seems to have completed but it's not properly reported:

![image](https://cloud.githubusercontent.com/assets/789512/6897442/ba8b33f8-d6c1-11e4-85f6-a316ca6c160d.png)

This is the first time that I see this problem.

**Comment by browndav** [comment]
This might be timing-based; I've seen it happen off and on, but not recently. I'll see if I can catch it during the next QA / acceptance testing run.

**Comment by garethbowen** [comment]
Dashboard is going away so I'm closing this.
