### ISSUE TITLE
Add "add new recipients" function to reply box in Messages right pane

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#864]
We want the ability to add recipients to a reply message. When the user clicks the "add recipients" button, this open up the "Send Message" window, as if accessing it from the top-level "+" button.

**Comment by abbyad** [comment]
This has been included as part of #861. @diannakane does that match what you were thinking? If so we can close this one in favour of the other, otherwise we can keep it as two issues.

**Comment by diannakane** [comment]
Yes, looks good! Wasn't sure how granular to get when creating issues :)

**Comment by abbyad** [comment]
Posting this here for posterity and moving to Ready:
![image](https://cloud.githubusercontent.com/assets/789512/7420737/f3e87f86-ef4c-11e4-919f-00a8c9772a4f.png)
