### ISSUE TITLE
Define bug reporting workflow

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#865]
Change "report bug" to "report technical problem" -- language that is clearer to our non-technical users, and define the workflow for reporting bugs to the Medic dev team. 

Lester and I did some thinking on this back in November, categorizing the types of reasons people might want to get in touch with us. It would be great to take advantage of the "send us a SMS" or "send us an email" options that we're building into the web app for Impact reporting. 

![bug report](https://cloud.githubusercontent.com/assets/1675870/6905114/9c86e9ec-d6da-11e4-82f6-13dc1657a6bb.jpg)
![img_0391 2](https://cloud.githubusercontent.com/assets/1675870/6905115/9c87d320-d6da-11e4-9e24-2485986ddda8.JPG)

**Comment by garethbowen** [comment]
Closing as ancient.
