### ISSUE TITLE
Cannot send a message to a contact

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#867]
I've plugged in a modem to test sending messages but get an error message after entering a contact and attempting to send a message.

![screen shot 2015-03-30 at 4 32 45 pm](https://cloud.githubusercontent.com/assets/1286381/6909399/8863361c-d6fa-11e4-84b4-f74ca1e2c784.png)

**Comment by garethbowen** [comment]
This means the user with name Sharon has an invalid phone number. If you go to the Contacts tab and edit the Sharon contact and try and save the validation error should be shown.

Try entering the full international number, eg: "+1555555555". If this doesn't work, message me on Slack to work through it. If it does work then you probably need to configure your default country code so you can use local numbers in future.

**Comment by abbyad** [comment]
@sglangevin I don't see a commit on this so let us know if @garethbowen's suggestions worked.

**Comment by sglangevin** [comment]
Seems to be working fine - if I recall correctly, @garethbowen and I worked this out over Slack.
