### ISSUE TITLE
Error message for invalid phone number persists after closing the add contact modal

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#869]
After inputting an invalid phone number while creating a contact, I closed the modal by clicking the x at the top of the modal. When I then clicked add a new contact, the error message was still there, even though the modal was then blank.
![screen shot 2015-03-30 at 4 44 47 pm](https://cloud.githubusercontent.com/assets/1286381/6909555/32c3424a-d6fc-11e4-971c-42d1ecf8f9ae.png)

**Comment by abbyad** [comment]
Seems to be working fine in 0.5.0-alpha.1323. Assigning to @sglangevin for final Acceptance Testing.

**Comment by sglangevin** [comment]
Looks good
