### ISSUE TITLE
App allows user to create multiple contacts with the same name, phone number and location

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#870]
Not really a bug, but could create strange user experience, particularly when looking at your message history with a contact. Not sure what the rule should be to differentiate between unique contacts - could be phone number? Or could look at name, phone number and location and not allow for all 3 to be identical to an existing contact? Or some combination - maybe @diannakane has some thoughts?

**Comment by garethbowen** [comment]
I think the phone number should be unique otherwise you can't be sure who an incoming message from that number will be assigned to. The name should probably be unique otherwise it'll be confusing using the system. I think it's ok to have multiple contacts at a single location as we enforce that there is only one primary contact.

**Comment by browndav** [comment]
I imagine we'll run in to two people with the same given name and surname, if my name is any indication. I think you're totally right about the phone number, though.

**Comment by garethbowen** [comment]
I've added a uniqueness check on phone number, but left location and name as freetext. The system will continue to work if two contacts have the same name and I think it's ok to leave this up to the administrators to manage.

**Comment by abbyad** [comment]
@sglangevin here is a screenshot of the validation in 0.5.0-alpha.1323:

![image](https://cloud.githubusercontent.com/assets/789512/7420597/baf66478-ef4b-11e4-992e-7d93f59afd78.png)

Move it to "Ready" (and remove Acceptance Testing label) if that meets you and @diannakane's criteria for this issue.

**Comment by sglangevin** [comment]
Looks good to me - working well.
