### ISSUE TITLE
Funky scrolling behavior on the contacts tab

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#871]
Once I have 10 places/people in my contacts list, when I scroll down it keeps flashing back and forth between the loading symbol and no more contacts over and over again as long as I scroll. As this happens, the list of contacts appears to shift up when the loading symbol comes up and then back down as the "no more contacts" text appears. Once I have 11 places/people in my contacts list I don't even see the "no more contacts" text at the bottom - I just get the loading symbol and then it disappears.

**Comment by garethbowen** [comment]
This also affected the reports tab.

**Comment by abbyad** [comment]
@sglangevin can you test this again now that it has been fixed?

**Comment by sglangevin** [comment]
Looks fixed to me
