### ISSUE TITLE
Edit user profile modal is cut off

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#872]
I'm not able to scroll down in Chrome, though once I tabbed through the form it allowed me to scroll.
![screen shot 2015-03-30 at 5 03 20 pm](https://cloud.githubusercontent.com/assets/1286381/6909794/c6b1319a-d6fe-11e4-9836-3ac51ee08da5.png)

**Comment by garethbowen** [comment]
I've made a change so that large modals such as this one have a scroll bar in the middle section so the heading and buttons are always visible. If the modal is still cut off please let me know the height of the browser window as it depends on the usable space.

**Comment by sglangevin** [comment]
It's working great!

On Tue, Mar 31, 2015 at 3:25 PM, Gareth Bowen <notifications@github.com>
wrote:

> I've made a change so that large modals such as this one have a scroll bar
> in the middle section so the heading and buttons are always visible. If the
> modal is still cut off please let me know the height of the browser window
> as it depends on the usable space.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/issues/872#issuecomment-88270828>.
>



-- 
DIY Product Lead
Medic Mobile <http://www.medicmobile.org>
+1 (203) 214-2711
Skype: sharon.g.langevin

**Comment by abbyad** [comment]
Moving to Ready based on @sglangevin's glowing review
