### ISSUE TITLE
When I submit a visit confirmation form, no auto-reply is generated

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#874]
![screen shot 2015-03-30 at 5 21 28 pm](https://cloud.githubusercontent.com/assets/1286381/6909970/4dc8c902-d701-11e4-964e-4bf0e1c6c87c.png)

**Comment by garethbowen** [comment]
I suspect this is for the same reason as #873 which depends on #482 .

@sglangevin please assign this contact as the primary contact for a catchment area and retry.

**Comment by garethbowen** [comment]
This is now fixed - if the phone number resolves to any person then that person is associated even if they have no location, district, etc.

**Comment by garethbowen** [comment]
Accidentally closed the wrong issue...

**Comment by garethbowen** [comment]
I've just verified that this is also fixed. Yeeha!
