### ISSUE TITLE
Reply to person's name as well as their location

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#876]
In the reply box below, include the contact's name ("Janet") as well as her location ("Sample CHW/Sample Health Center/Sample District"). To further complicate this example, "Sample CHW" should actually be "Sample Catchment Area/Village," the place that she represents. I changed this later in Contacts to bring it in to alignment. However, the principle of this issue still applies. 
![reply to who](https://cloud.githubusercontent.com/assets/1675870/7010418/e1528b32-dc55-11e4-84dc-a1ffae4c483e.jpg)

**Comment by garethbowen** [comment]
This is a bug. It should just be "reply to Janet". It's probably based on whether the first message in the conversation is incoming out outgoing.

**Comment by garethbowen** [comment]
Fixed in new installs.

In existing installs you need to update manually a translation. On the Configuration > Languages > Application Text screen, change `Reply to {{name}}` to `Reply to {{contact}}`.

**Comment by abbyad** [comment]
Hey @diannakane, I think this has been resolved... can you please confirm and we'll move the issue to Ready?
