### ISSUE TITLE
Setup Wizard not scrolling properly

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#877]
I am using VM Fusion so I am not sure if this issue is localized to that setup process. On my screen, the setup wizard is cut off and I am unable to scroll to view or click the bottom buttons. I clicked the "x" to navigate away from this screen. 
![setup wizard scrolling bug](https://cloud.githubusercontent.com/assets/1675870/7010471/6f0bafa8-dc56-11e4-8940-4cbf88efb8f8.jpg)

**Comment by garethbowen** [comment]
This is fixed in the latest version.
