### ISSUE TITLE
wizard language selection should display language in correct alphabet

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#879]
![screen shot 2015-04-08 at 5 05 49 pm](https://cloud.githubusercontent.com/assets/25641/7058059/b6e617de-de11-11e4-9b8f-3c7d947bad66.png)

via @alxndrsn

**Comment by abbyad** [comment]
English = English
Spanish = Español
French = Français
Nepali = नेपाली (needs confirmation)
Swahili = Kiswahili

**Comment by garethbowen** [comment]
We decided to include the English version in brackets so administrators would be able to recognise the language, eg: "Français (French)".

The perfect solution would have a translation of each language name into the users language, as well as display the local name. We can add this later if needed.

**Comment by garethbowen** [comment]
I changed the defaults so this will only be obvious in a new install. In an upgrade, manually edit the language names in the configuration screen to achieve this.

> Nepali = नेपाली (needs confirmation)

If this is incorrect, file a new bug to fix it.

**Comment by mandric** [comment]
Language choices are all still in english.

Fails on fresh install of medic-os-v1.1.0-20150623-x64-virtual.iso which comes with 0.5.0-alpha.1530 and upgrade to 0.5.0-alpha.1542 still fails after reloading cache and forced refresh (shift+reload).
