### ISSUE TITLE
UX/UI Updates to Initial Setup

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#880]
@sglangevin and @diannakane will be providing mockups with mostly minor changes to improve the initial setup experience. Mockups will be posted here as they come in, and individual issues may offshot to deal with the bigger items.

**Comment by sglangevin** [comment]
Here's a link to the completed mockup: https://beta.moqups.com/joshnesbit/5YohdufDGG/view

Let me know if there are questions!

**Comment by garethbowen** [comment]
I've made all the changes to the webapp, ie: from Welcome onwards.

**Comment by browndav** [comment]
I can't seem to get in to the mockups link, even when I'm logged in to Moqups. Can someone reshare with and/or forward me a working anyone-who-has-the-url link?

Do we have all of final text/modifications/icons for the early-setup phase (i.e. concierge) ready to go by chance?

**Comment by sglangevin** [comment]
https://beta.moqups.com/joshnesbit/5YohdufDGG/view

**Comment by browndav** [comment]
Thanks, that one works.

**Comment by abbyad** [comment]
I think the last bit of this is in concierge, assigning @browndav to it. Once you are done Dave you can close and move it to Acceptance Testing.

**Comment by browndav** [comment]
@sglangevin: The mockup below has a phone number field and an e-mail address field. Do you know what the intended side-effect of setting either of these is? For example, are you envisioning they're used to create a new contact?
![mockup](https://cloud.githubusercontent.com/assets/763977/7926699/f0e889b4-088a-11e5-8bce-cdd66b113044.png)

**Comment by sglangevin** [comment]
@browndav: We wanted those to be in there for future password resetting. That way a user could have their password reset information either emailed or texted to them.

**Comment by browndav** [comment]
Okay, thanks. I don't suspect either of those password-reset options will land by DIY beta two.

Can we take care of the other show/hide password bits (adding an option to show the password while it's being entered, and one to show a password reminder on the "finished" screen) and save these two new fields for when password resetting is fully supported? I worry that collecting the data to no obvious effect will just confuse users.

**Comment by sglangevin** [comment]
Nope, not beta two, those are in beta three. I don't think it will confuse users to have those fields (I would make email optional anyway since not everyone will have one). What happens for users who upgrade from beta 2 to beta 3? I know it will be done manually, but if beta 3 has password reset, wouldn't we want everyone who might upgrade to have entered their phone number and email from the get-go?

**Comment by browndav** [comment]
The remaining portions of this issue appear to be superseded by #1016; moving this to acceptance testing.
