### ISSUE TITLE
Failed to enable disabled notifications

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#881]
Notifications were disabled with the `OFF` form, but sending `ON` did not reenable them. Expected them to be unmuted, back to `scheduled`.

![screen shot 2015-04-10 at 23 09 59](https://cloud.githubusercontent.com/assets/789512/7100012/e4ba14d2-dfd6-11e4-9c75-020f16c783bc.png)
![screen shot 2015-04-10 at 23 11 10](https://cloud.githubusercontent.com/assets/789512/7100013/e626e43a-dfd6-11e4-866a-42ce8c2e703a.png)

**Comment by garethbowen** [comment]
Also, it looks like it generates two identical replies.

**Comment by garethbowen** [comment]
@abbyad solved it - the repeated replies was a symptom of running the transition multiple times, which caused the notification mute state to be overwritten.

**Comment by abbyad** [comment]
Works well in 0.5.0-alpha.1323, moving to Ready
