### ISSUE TITLE
Show impact data (anonymous statistics) in webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#882]
This is a followup to #707 to make the anonymous _Impact Data_ information visible within the webapp. 

Our team would like to be able to contact a manager to ask them about their instance, but that could be made obselete by #772  In the long run this would also improve transparency over what data is being collected and sent.

This information should be kept for Admins so it could be shown within the Configuration > Export page.

**Comment by sglangevin** [comment]
Here's a mockup of the chart I had in mind: https://beta.moqups.com/joshnesbit/jwoySHrMUH/view

**Comment by abbyad** [comment]
From the Mockup: ![image](https://cloud.githubusercontent.com/assets/789512/7399651/33e54e98-ee85-11e4-911c-8a52c6510076.png)

**Comment by abbyad** [comment]
Moving to beta 3 and having admins go to http://medic.local/_couch/_utils/database.html?medic/_design/medic/_view/usage_stats_by_year_month to view the stats for now.

**Comment by abbyad** [comment]
Closing as obsolete.
