### ISSUE TITLE
Export logs via webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#883]
It has been difficult to get the logs from users since it requires them to access them on medic-os via SSH or SCP. It would be beneficial for our own debugging if we could have them exposed to admin users on the webapp side so that they can be downloaded and emailed when needed.

**Comment by browndav** [comment]
This is working in Medic OS `dev`, we just need to figure out how to best expose it to users and through `medic-api`. #884 is the final goal; I'll file an issue for an intermediate "download all logs" button too.

**Comment by browndav** [comment]
https://github.com/browndav/medic-os/commit/a8953054ccfcad032a6146f16ea1143a12c9efdf
