### ISSUE TITLE
Accept ODK forms submitted over HTTP

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#885]
Currently we can accept forms from Medic Collect when they are submitted over SMS. We also want to be able to accept ODK submissions sent over HTTP as this allows users that have wifi or data connection to avoid SMS costs.

We have a project waiting for this feature to roll out Medic Collect as soon as possible, so we'd also need to figure out the best way to make the feature available to them without having to wait on a larger release.

**Comment by abbyad** [comment]
Defering this until we have new forms engine.

**Comment by browndav** [comment]
Closing as ancient.
