### ISSUE TITLE
Serve ODK forms to Collect

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#886]
The ODK and Medic Collect applications can request and download forms from ODK Aggregate. We'd want medic-webapp to serve the ODK forms it has to a Collect application.

**Comment by abbyad** [comment]
Here is a description of the recommended API: https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI

**Comment by mandric** [comment]
https://www.npmjs.com/package/openrosa-formlist and supported by [simple-odk](https://github.com/digidem/simple-odk) we just need to extend to work locally or with couchdb.

**Comment by mandric** [comment]
Where would the xml forms be stored?  Would they get generated based on the JSON definitions?

**Comment by abbyad** [comment]
At this point we do not need an automated translation between the XML and JSON definition. Someone technical from our team (likely the Tech Leads with my support) would be creating the XML and JSON versions separately.

As for where they would be stored, I'm not quite sure... but we do want to be able to serve all the files associated to a report. In Collect these get stored in the `{{FormName}}-media` folder, and seem to come from the [manifest section of the xml](https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI). Since it is technical persons creating and uploading the forms it is acceptable for this iteration for the upload to require manual SSH steps.

**Comment by mandric** [comment]
We should open a different issue for supporting media on medic collect form submissions (creating attachments on records).  I don't think it has anything to do with this issue?

**Comment by abbyad** [comment]
Works well when there are forms to download, but I get an error if there are no forms. I would expect it to report that there are no forms to download.

![screenshot_2015-06-08-21-13-26](https://cloud.githubusercontent.com/assets/789512/8059112/2c8073a4-0e8c-11e5-9a09-4284fadc62a4.png)

**Comment by mandric** [comment]
Fixed in beta.
