### ISSUE TITLE
ISO image failing to launch under medic-launchpad on field laptop

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#887]
@shreyakb has reported that modems are not being picked up by her medic-os instance, which is run on VMware Player on a Windows install.

She is testing with Huawei E303F and E3531.

**Comment by browndav** [comment]
Confirmed: this is actually an image boot/reachability issue; the web application isn't reachable at all, even though medic-launchpad shows it as running.

**Comment by browndav** [comment]
Needs further analysis; removing `Bug` tag until we know where the defect is.
