### ISSUE TITLE
Allow user to set rc code for Contacts

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#891]
The RC Code was used for referring to a facility from a form submission, but this was lost in the Contacts refactor. Add this field to the add/edit forms for People and Places and make sure it still works.

**Comment by abbyad** [comment]
The RC Code is like an Internal Place ID to refer to a place, compared to the External ID which is a placeholder for IDs used by third party apps such as OpenHIE, DHIS2, or OpenMRS. 

Given its use, I think it would be clearer to use _Place ID_ or _Place Code_ instead of _RC Code_.

**Comment by abbyad** [comment]
Also, in all likelihood, the _External ID_ does not need to be visible to anyone but admins.

**Comment by garethbowen** [comment]
The RC Code is actually stored on the person, eg: clinic.contact.rc_code. Thus it's a code for a Person, not a Place. Thus I've added it to the person screens, and called it the "Person code"

**Comment by abbyad** [comment]
Seen in 0.5.0-alpha.1323, moving to Ready. 

We'll still need to test the Code field works as expected (place vs person code) when we use it for deployments and integration with 3rd party platforms (eg OpenHIE).
