### ISSUE TITLE
Merge Medic Collect SMS parser in to beta, then release it

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#892]
We need to deploy Medic Collect as part of a production project. This will require that the specialized ODK SMS parser be brought in to beta and then released. This should be a pretty straightforward backport.

**Comment by browndav** [comment]
@mandric: Can we do this merge today?

**Comment by mandric** [comment]
Don't see why not.

**Comment by abbyad** [comment]
In Release since v0.4.4
