### ISSUE TITLE
Modify Medic Collect to support submitting SMS-style form data over HTTP

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#893]
In lieu of fully completing #885 right now, modify Medic Collect to submit serialized SMS data over HTTP, to the normal medic-webapp message-addition endpoint. This will allow users to submit forms from Medic Collect using a data connection, but defer issues related to the XML-based input format that'll be better solved when we integrate Enketo (as part of the CHW mobile app).

**Comment by abbyad** [comment]
This is working well and being deployed, moving to Ready.
