### ISSUE TITLE
CouchDB crashing during gardener/medic-api/medic-sentinel startup when larger demo dataset is preloaded

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#901]
This is a tracking issue for a crash we're seeing in CouchDB on the latest Medic OS image with the latest `medic-webapp` alpha, **using the demo dataset**. I still don't know exactly what's wrong, but have a couple theories.

Here's a full set of logs showing the crash; this occurred while `concierge` was waiting for `gardener` to finish starting all of the required modules: https://gist.github.com/browndav/ebe3ed89457c99cb4fe4

Here's a mailing list message that at least appears to give some insight in to the `Index shutdown by monitor notice` message: http://mail-archives.apache.org/mod_mbox/couchdb-user/201405.mbox/%3C8DFF6362-F540-43BD-90A3-CF134BA42F67@gmail.com%3E

**Comment by browndav** [comment]
Theory #1: View generation is causing HTTP client processes to block, which causes the number of open connections to COuchDB to stack up until the Erlang process limit is reached. Then, the whole thing falls to the ground in a ball of fire.

Proposed test: On a new `medic-os` image, manually regenerate views with `curl`, and then walk theough the `concierge` setup process as usual. If this works, we can move the view generation step earlier in the process, so that it finishes before the `service` account is available.

**Comment by browndav** [comment]
The first theory checks out. View generation completes in 21 seconds using curl alone, but essentially deadlocks when it's run concurrently to gardener's first-run. Will modify concierge and push a PR before end of day tomorrow (Thursday PDT).

**Comment by browndav** [comment]
Testing the fix now; will commit once it works.

**Comment by browndav** [comment]
Closing this; it's complete. I'll open a new issue referencing this to cover the continuing performance issues and crashes we're seeing with the demo dataset post-concierge.

**Comment by browndav** [comment]
Appears to be resolved as of latest builds; assigning to @abbyad for confirmation (I'll upload builds today so you can test).

**Comment by browndav** [comment]
ISOs are up in the usual place.

**Comment by abbyad** [comment]
I haven't seen this error again. Moving to Ready.
