### ISSUE TITLE
Switching rapidly between tabs causes errors and/or unwanted UI behavior

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#902]
While the page is still loading, switching rapidly between the `Reports` and `Messages` tabs occasionally can produce an unhandled exception:

```
Error: a is undefined
[54]</</</c.isRead@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:65:23989
me.prototype.functionCall/<@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:6:10382
i/<@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:4:23869
Vb/this.$get</l.prototype.$digest@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:4:31733
Vb/this.$get</l.prototype.$apply@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1368
f@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:4:9545
r@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:4:11410
nb/</v.onload@http://172.16.201.162/medic/_design/medic/_rewrite/static/dist/inbox.js:4:11950
```

Switching back and forth rapidly between the `Contacts` and `Reports` tab, at any point in the lifetime of the page, can occasionally cause contact records to be added to the `Reports` screen:

![reports-contacts-mashup](https://cloud.githubusercontent.com/assets/763977/7285597/881d188c-e8fa-11e4-93a2-9e7c85f9518a.jpg)

**Comment by garethbowen** [comment]
This bug can manifest from any of our many ajax requests. Some fail visibly like this, some fail quietly in a corner, and some succeed but are no longer necessary.

If instead of using the angular services $http and $resource directly we implement a wrapper which tracks active requests, we can then cancel all requests when the route changes. Eg: http://stackoverflow.com/questions/23244389/angularjs-abort-all-pending-http-requests-on-route-change

**Comment by garethbowen** [comment]
I added a 5s delay in api to replicate this and managed to get an infinite loop of switching tabs. In all my years....

**Comment by garethbowen** [comment]
I refactored all our ajax calls to go through a new `HttpWrapper` service which registers the requests with a timeout that fires on route change. Unfortunately a request that hits a timeout is considered an error in angular so the callback is called with a null error message. So, this fix has stopped any unwanted behaviour in the UI but has introduced unwanted error messages in the console which will hopefully only annoy developers. If it's too annoying we can inspect the error message in the response handler before logging but I'll leave it as is for now.

This was complicated by the Inbox controller which sets up a lot of the chrome that exists on all pages (filters, permissions, translations, etc). Furthermore as route changes happen on load (to select the first message for example) these requests were always being timed out. To fix this I pass an options object down with `{ timeout: false }` to ensure these requests complete and update the $scope.

This has ended up much more complicated than hoped, but it does appear to have fixed the user facing inconsitencies.

**Comment by browndav** [comment]
Appears to be resolved in `alpha.1332`, thanks.

One observation: in the request cancellation console messages, the `message` field is null. I haven't looked closely to see if it's possible, but it'd be nice if we could get something to the effect of `cancelled` in there. No big deal, but thought it was worth mentioning.

Moving to ready.
