### ISSUE TITLE
Add "download server logs" button

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#903]
As a follow-up to #883 and logical prerequisite for #884, we want a button that an administrative user can use to download all of the server logs. This should use the mechanism created in #883, restrict access to administrators, and produce a human-readable/openable file.

**Comment by abbyad** [comment]
Can be added as `Server Logs` here on the Configuration > Export page.

![screen shot 2015-04-27 at 17 47 31](https://cloud.githubusercontent.com/assets/789512/7358762/db0b6698-ed05-11e4-9cb0-34d1f13f7cd1.png)

**Comment by garethbowen** [comment]
I've added the link to the configuration page. We just need to modify medic-api to handle: `/api/v1/export/logs?format=xml&locale=en`

**Comment by abbyad** [comment]
Depends on #905

**Comment by browndav** [comment]
I can take this one now. Looks like https://www.npmjs.com/package/zip-stream has minimal dependencies and would be usable.

**Comment by browndav** [comment]
Merged in https://github.com/medic/medic-api/commit/b8cfc66. Thanks for helping out @garethbowen – I just wanted to add a couple unit tests, which probably involves making the current code more stub-friendly in at least one spot.

**Comment by browndav** [comment]
Thanks, sorry about the style-matching fails.
