### ISSUE TITLE
Use appcache

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#904]
Implement an appcache to reduce load time, reduce data usage, and as a first step towards supporting offline mode.

**Comment by browndav** [comment]
![manifest-fetch-failure](https://cloud.githubusercontent.com/assets/763977/7441566/15549802-f0a2-11e4-8136-0bed484ff9cc.png)
I'm getting a weird appcache manifest fetch failure on stock Webkit (nightly and release) on OS X. Probably not a blocker, but I'll look in to it before moving this to ready.

**Comment by mandric** [comment]
Is there a better way than prompting the user?

**Comment by mandric** [comment]
Since we're changing the manifest.appcache file on each build (including build time in a comment) the browser should just revalidate the cached files, no?  Not sure what the purpose of the Reload feature is.

**Comment by mandric** [comment]
@browndav pointed out http://blog.jamesdbloom.com/ProblemsWithApplicationCache.html which describes the double refresh issue. Sounds like that's what the Reload feature addresses.

**Comment by garethbowen** [comment]
That's exactly the issue. It's kind of a pain but if you're offline you don't want to wait for the manifest request to timeout before realising you're offline, so the cached version is rendered immediately. Then we can't just swap out the content because the user might have interacted with the page by then, so a refresh is required. Hopefully it's not a problem in production where the app is updated less often.

We could switch it off in development but at least for now it's good to have us testing it out.
