### ISSUE TITLE
Resolve person even if not associated to a facility

### ISSUE THREAD

**Issue by abbyad** [medic/medic-webapp#910]
We need to be able to resolve the contact info for Reports sent by those not associated to places.

**Comment by garethbowen** [comment]
This is related to #482 and I think will need a significant amount of work to fix. Basically instead of assigning a message to a Place we should assign it to a Person who may or may not have a Place.

**Comment by browndav** [comment]
Somewhat hackish idea: how about force-associating any unassociated people to a default place?

**Comment by abbyad** [comment]
Works great, nice job @garethbowen. Moving to Ready.
