### ISSUE TITLE
Configuration panel: the schedules button leads to a "document is missing attachment" message

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#911]
Clicking on "schedules" in the config on the hosted alpha yields this: {"error":"not_found","reason":"Document is missing attachment"}

**Comment by browndav** [comment]
Confirmed in `alpha.1332`, scheduling for this iteration.

**Comment by garethbowen** [comment]
The problem is the URL is missing the trailing `/`. On it.

**Comment by garethbowen** [comment]
`/` is now optional.
