### ISSUE TITLE
Change "Export" in Config to "System Stats"

### ISSUE THREAD

**Issue by diannakane** [medic/medic-webapp#912]
Change the title of the "Export" button in the Config on the hosted alpha to "System Stats" so as not to confuse this with clicking "export" in the hot dogs to export data and messages.

**Comment by garethbowen** [comment]
This still seems confusing as the Export page has more than just System Stats on it. You are actually downloading the same stuff, it's just the administration view of it, so using the same label makes sense to me to keep the app consistent.

**Comment by diannakane** [comment]
I think we're confusing "export" by using it both as a verb and as a noun. I see what you mean, though.  We can guide users to the various types of exports (or ways to export) in the user guides. Issues retracted.
