### ISSUE TITLE
Exception being thrown from view – doc.sms_message is undefined

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#916]
We're getting an exception thrown from one of the `data_records` views, which is spamming the logs during reindexing and may be causing other issues:

```
[info] [<0.295.0>] OS Process #Port<0.2454> Log :: function raised exception
  (new TypeError("doc.sms_message is undefined", "undefined", 2)) with doc._id
    46ae9ee41d6b78afcb3f9eff7b012e07
```

We should find this and fix the view so it's tolerant of a non-existent `sms_message` property.

**Comment by alxndrsn** [comment]
@browndav how do I trigger re-indexing so I can see this error?

**Comment by alxndrsn** [comment]
@browndav how do I trigger re-indexing so I can see this error?

**Comment by browndav** [comment]
The brute-force way is to stop couchdb, remove the contents of `mrview`, restart couchdb, and then query the view. That'll force it to regenerate the whole thing; you should also be able to add a record and requery the view to see a partial rebuild.

**Comment by alxndrsn** [comment]
I fixed it already :p
