### ISSUE TITLE
Contrary to documentation, uploading a set of JSON forms doesn't overwrite existing forms

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#917]
Take a look at https://nepal-demo.app.medicmobile.org, which is on `alpha.1332`. Uploading a set of forms appears to overwrite the existing forms, but upon reloading it becomes apparent that the forms were merged with existing forms.

We should either update the instructions and provide a way to remove existing forms, or fix the upload behavior.

**Comment by mandric** [comment]
Could not reproduce on release, will test on alpha shortly.

**Comment by browndav** [comment]
Right, it's a new issue on alpha, it's not present in the 0.4.3 release.

**Comment by mandric** [comment]
Confirmed exists on 0.5.0-alpha.1332.
