### ISSUE TITLE
After deleting a contact, a page reload is needed for the contact to disappear from the left pane

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#919]
See screenshot below. After deleting a contact, the contact details disappear from the right pane, but the contact remains in the left pane. I'd expect it to disappear from both.

![delete-1](https://cloud.githubusercontent.com/assets/763977/7448073/d379956c-f1c4-11e4-8738-5a1ca60bfaf7.png)

After a page reload, it becomes apparent that the contact is indeed gone.

**Comment by browndav** [comment]
This was observed in `0.5.0-alpha.1332`.

**Comment by alxndrsn** [comment]
This bug also occurs when deleting Catchment Areas
