### ISSUE TITLE
Deleted contacts show up when editing a report, and reports can be edited to refer to already-deleted contacts

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#920]
Preface: this bug report assumes that deleting a contact means "this contact shouldn't be eligible for use at any point in the future".

After deleting `Aimee Achorn` from the demo dataset, I'm able to click the `Reports` tab, select a report, click `Edit`, and reassign the report to `Aimee Achorn`. I expected to see a list that _didn't_ include any deleted contacts.

![delete-2](https://cloud.githubusercontent.com/assets/763977/7448097/5a4d2626-f1c5-11e4-8e48-3256736c49ed.png)

**Comment by browndav** [comment]
This was observed in `0.5.0-alpha.1332`.

**Comment by garethbowen** [comment]
Nice catch. The problem is when a Person is updated a Place might still have that Person registered as the contact. We need to update the Place to have a null contact on delete.

**Comment by browndav** [comment]
Thanks, that was fast. I'll test.
