### ISSUE TITLE
Full-text search: Place names not full-text indexed in Reports tab

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#921]
Using the demo dataset, type `Millville` in the free-text portion of the filters bar. No results are returned.

Equivalent functionality is available via the `Places` filter, but users may expect place names to work – the people and places are closely associated in the UI, and having the free-text search work for one but not the other could be confusing. If you're looking for data from a single place and have a large number of facilities, the free-text search can also be quite a bit faster than scrolling through the list of places.

This is lower priority, but may be exceedingly easy to fix by just modifying the `couchdb-lucene` design document.

**Comment by browndav** [comment]
Forgot the most important part: the place names in the `Contact` tabs _are_ full-text indexed, which only adds to the confusion.

**Comment by browndav** [comment]
This was observed in `0.5.0-alpha.1332`.

**Comment by alxndrsn** [comment]
Clinic name added to search in #937

**Comment by browndav** [comment]
Closing; moving to acceptance testing.
