### ISSUE TITLE
After deleting a place, attempts to edit any report associated with that place throw an exception

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#924]
Deleting a place renders all records associated with that place uneditable. To reproduce using the demo dataset, delete `Aelburn`, then click the `Reports` tab, select `Fatima Fauver` (of `Aelburn`, in `Crystalbell` in `District 2`), and click `Edit`. The edit screen won't appear, and you'll get the following crash on the script console.

```
Error: a is undefined
c@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:65:8881
F<.updateSelection@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:37:26180
F<.val/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:37:27108
[53]</</</c.updateAvailableFacilities/</</<.initSelection@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:65:9200
F<.val@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:37:27021
a.fn.select2/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:39:9384
.each@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:28:29193
_.prototype.each@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:28:27167
a.fn.select2@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:39:8806
[53]</</</c.edit@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:65:13503
me.prototype.functionCall/<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:6:10382
tf[b]</<.compile/</</e@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:6:23616
Vb/this.$get</l.prototype.$eval@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1099
Vb/this.$get</l.prototype.$apply@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:5:1324
tf[b]</<.compile/</<@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:6:23666
Ma/c@http://medic.local/medic/_design/medic/_rewrite/static/dist/inbox.js:2:14980
```

This was with Firefox 37.0.2.

**Comment by alxndrsn** [comment]
@garethbowen @browndav 
What is acceptable behaviour here?
It's quite simple to fix the dialog so that the dropdown is initialised empty if the report is associated with a since-deleted place (modify `formatResult()` in the call to `Facility` in `$scope.updateAvailableFacilities()`).
This is not necessarily the correct fix though - if the place is deleted, we might still have full details of the person, and could populate the dropdown with this data.  This would feel more consistent with the behaviour when editing a Report for an existing Person/Place.
It would be harder to achieve the second option, because the `initSelection` function in the `Facility` call is passed the `id` of the place, which it fetches from some `<input>` element.  It's not clear to me where this `<input>` element is, or how it was initialised.

**Comment by garethbowen** [comment]
I'm hitting similar problems with #910 . I think allowing orphaning of contacts who have data_records will be an issue for things like permissions which can be based on the district of the contact who the record is assigned to. However, leaving the contact in a deleted Place is also problematic, and probably unexpected - if I delete a district I would not expect an incoming report to be assigned to a Contact in that district.

What about a third option where Places cannot be deleted unless they have no children, and Contacts cannot be deleted unless they have no assigned data records? We can assist users by linking them to the children and the data records respectively, but they have to reassign/delete first. It's more cumbersome for the users, but it's explicit about what's going on, it's more reliable, and no patients or contacts will fall through the cracks.

**Comment by alxndrsn** [comment]
> What about a third option where Places cannot be deleted unless they have no children, and Contacts cannot be deleted unless they have no assigned data records?

Definitely sounds logical.  UI extensions to this could then be e.g. to offer to cascade delete all the children of a place, or to re-assign records to a different contact.

**Comment by browndav** [comment]
I think restricting deletions is the way to go for this next release, and we could gradually remove that restriction as we fix the linking vs. embed issues between reports/contacts/places.

**Comment by alxndrsn** [comment]
What's the desired behaviour in the UI?  Show a red fail message in the "confirm delete" modal?
e.g.
> Could not delete place as it has other places and/or contacts associated with it.

**Comment by browndav** [comment]
I think that's the best thing to do for now.

**Comment by alxndrsn** [comment]
This bug actually no longer occurs.  I've done a review of the association updates which don't happen on deleting a contact in https://github.com/medic/medic-webapp/issues/969, but I doubt it's as high priority as this bug was.
