### ISSUE TITLE
Messages: quickly selecting a new message after a deletion leaves an empty item behind

### ISSUE THREAD

**Issue by browndav** [medic/medic-webapp#925]
If you delete the last message in a conversation, the conversation is normally removed from the left pane. However, if you quickly select another message after pressing the `Delete` button, an empty conversation remains behind. Reloading the page makes the empty conversation go away.

This was on Firefox 37; it almost certainly has to do with the request cancellation logic, but I haven't been able to look at it in any significant detail yet.

Low priority; this appears to be a relatively minor UI issue.

**Comment by alxndrsn** [comment]
@garethbowen this one's for you!
