### ISSUE TITLE
Exported data cannot be opened in Excel

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#929]
When exporting form or message data, the resulting .xml file can't be opened in Excel. Additionally, most people will not have Excel set as the default program for opening .xml files. @abbyad mentioned that .xlsx hasn't worked in the past. It would be great to come up with a solution, perhaps getting .xlsx or .xls working or doing something else that would make Windows recognize the .xml as an Excel file?

**Comment by browndav** [comment]
I tested this on a few Windows XP VMs with a couple different versions of Office, and Excel seemed to associate itself with XML files. I agree that it'd be good to find a working file extension that's (more) Excel-specific.

I take it you're getting a different application than Excel when you double-click the exported file, but it works if you open Excel specifically and use `File -> Open...`?

**Comment by sglangevin** [comment]
Yeah, the default application for opening wasn't Excel for me, but let me test this again on the Windows computers in the office. It might be that I was testing this on my Mac.
