### ISSUE TITLE
When I am adding a place, if I select a primary contact, the option to leave that field blank goes away

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#930]
If I am adding a Health Center or Catchment Area, when I open the add place modal, all fields are blank. If I select a person from the primary contact drop-down, I can no longer leave that field blank because the blank option disappears so I have to Cancel and start over. That option to leave it blank should persist.

**Comment by alxndrsn** [comment]
Fixed pending PR review by @garethbowen

**Comment by alxndrsn** [comment]
Thanks for the fix, @garethbowen
