### ISSUE TITLE
If I run the Messages tour when the currently displayed message thread doesn't have any incoming messages, tour behaves weirdly

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#933]
If the message thread on the screen doesn't have any incoming messages on it, I see the step of the tour explaining incoming message twice (first time then the next step then it comes back) and then when I click next the second time, the tour disappears even though I'm not at the end.

**Comment by mandric** [comment]
@sglangevin @abbyad not sure what branch we are using to test DIY now.  Let me know and I'll make sure this is available somewhere for acceptance testing.

**Comment by sglangevin** [comment]
@mandric last I checked we were using the new DIY branch that you had created, but I'm not sure when that will change. Maybe we can figure that out next week?

**Comment by mandric** [comment]
Ok there was some talk about DIY using alpha, I just didn't know the status of that.  And we can surely work on that next week if we need to.
