### ISSUE TITLE
Add additional stats to monthly anonymous statistics report

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#934]
SEE BELOW FOR FULL LIST!
Let's add the following:
* confirmed visits: number of confirmed visit reports submitted
* Registration activity: number of CHWs who sent a registration report this month
* Visit activity: number of CHWs who sent a visit confirmation report this month
* Flagged activity: number of CHWs who sent a danger sign report this month
* Delivered activity: number of CHWs who sent a delivery report this month
* CHW reporting activity: number of CHWs who sent in any report this month
* CHW messaging activity: number of CHWs who sent in any unstructured SMS this month
* All CHW activity: number of CHWs who sent in either a report or an unstructured SMS this month
* SMS activity: total number of unstructured SMS received this month
* Reports activity: total number of reports received this month

**Comment by sglangevin** [comment]
From this doc: https://docs.google.com/a/medicmobile.org/spreadsheets/d/11eu_f1_Q_ZRdNfB6DwQKcM6lcz3sAFQDNFLUxiHmXfU/edit#gid=0

**Comment by sglangevin** [comment]
We're putting #882 on hold for now and replacing it by making sure the monthly impact stats report includes all of the stats we wanted to see. Users will access this by viewing in couch (DIY managers will provide the URL or will check during site visits). I've updated the list of stats in the google doc, will paste the final list below too.

**Comment by sglangevin** [comment]
FULL LIST OF STATS 
(note that a few on the top list have changed from % to #)
* Registered pregnancies: number of  women registered in ANC this month
* danger signs flagged: number of danger sign reports submitted this month
* Confirmed deliveries: number women with confirmed deliveries this month
* Estimated deliveries: number of women who are estimated to have delivered based on LMP and time since registration
* # deliveries with 1+ ANC visits: number of women (confirmed and estimated deliveries) who have had one or more ANC visits
* # deliveries with 4+ ANC visits: number of women (confirmed and estimated deliveries) who have had four or more ANC visits
* # deliveries in facility: number of women (only confirmed deliveries) who delivered in a facility
* # with skilled birth attendant: number of women (only confirmed deliveries) who delivered at home with SBA

new additions	
* confirmed visits: number of confirmed visit reports submitted
* Registration activity: number of CHWs who sent a registration report this month
* Visit activity: number of CHWs who sent a visit confirmation report this month
* Flagged activity: number of CHWs who sent a danger sign report this month
* Delivered activity: number of CHWs who sent a delivery report this month
* CHW reporting activity: number of CHWs who sent in any report this month
* CHW messaging activity: number of CHWs who sent in any unstructured SMS this month
* All CHW activity: number of CHWs who sent in either a report or an unstructured SMS this month
* SMS activity: total number of unstructured SMS received this month
* Reports activity: total number of reports received this month

**Comment by garethbowen** [comment]
I've added the new fields. You can see the output here: http://stats.app.medicmobile.org/medic/_design/medic/_rewrite/#/reports/cbba00dc4535ca1e4f9c07db292da4e5

**Comment by abbyad** [comment]
Thanks @garethbowen, I'm assigning to @sglangevin for acceptance testing. Sharon, let us know if this is suitable.

**Comment by sglangevin** [comment]
Output looks good to me, moving to ready.
