### ISSUE TITLE
When I run the Reports tour from another tab (other than Reports) the reports don't load prior to the tour starting

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#941]
With no reports, the tour doesn't make much sense and it also fails to run all the way through - the user gets stuck at the Report Status explanation - pops up about 4 times and if you keep clicking next it eventually disappears.

**Comment by garethbowen** [comment]
I think I fixed this with a fix for a similar bug today, and I could get it to happen with the latest alpha. Please try again and reopen if you can get it to happen again.

I think this will also solve the problem with no reports although it won't be pretty or very usable without at least one report. The demo data should solve this for most cases.

**Comment by sglangevin** [comment]
Seems to be working now - I saw a very slight delay as reports were loading and the first step of the tour had already popped up, but I think by the time you read the first few steps, reports will have loaded and no one will get stuck.
