### ISSUE TITLE
Messages screen does not work in small screens

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#942]
In Chromium browser:

1. resize browser width < 768px
2. switch to Contacts tab
3. switch to Messages tab
4. observe that the message menu is now scrunched up in the corner, and "No Message Selected" on gray background takes up most of the screen

Expected behaviour: if no message is selected, small-screen user should just see the list of all messages.  This is the case when the page is reloaded, but not when entered from the Contacts tab.

**Comment by browndav** [comment]
FWIW, just loading https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite#/contacts/ in a super-narrow browser window then switching to messages does it too.

**Comment by garethbowen** [comment]
It's the flexbox... :anguished:

**Comment by garethbowen** [comment]
I can hack around the issue, but the messages animation behaves strangely too. I'll look into why the messages tab behaves differently to reports and contacts.

**Comment by garethbowen** [comment]
Strange. Angular autoscroll attribute must mess with the CSS rendering in Chrome. It appears like it doesn't solve the issue it was supposed to solve anyway, so removing it does the trick.
