### ISSUE TITLE
Data export: Updates to contact data only apply to new forms, old forms become inconsistent

### ISSUE THREAD

**Issue by btbonval** [medic/medic-webapp#947]
So far as I can tell, forms are filled in using static data configured by SMS phone number.

If a CHW has their name changed (perhaps the first entry had a typo, or a middle initial was added/dropped), then forms before the change hold the old name for the CHW, while new forms hold the new name for the CHW.

Similarly, if an organization or any other static field is changed, it doesn't propagate in a consistent fashion.

A relational database would help clear this up, but in the meantime, the CHW name inconsistency really messes with our ability to report on CHW activity for impact and activity metrics. The other inconsistencies might cause problems later.

**Comment by btbonval** [comment]
To quote @browndav , "what the export is doing is unintuitive"

Perhaps that would make a good title for this issue.

**Comment by browndav** [comment]
The problem that @btbonval is running in to (I think), is that the data export tool exports contact data _as it was at the time of report creation_, not as it is at the time-of-export. This is the unintuitive part; people processing the exported data are probably assuming that the contact information for each record is the most up-to-date.

**Comment by browndav** [comment]
I've renamed this so that it's clear it only applies to the data export; if there are similar issues elsewhere in the app, I'll file them separately.

**Comment by garethbowen** [comment]
Similar: #928 #842 #557

**Comment by garethbowen** [comment]
Closing as ancient.
