### ISSUE TITLE
Analytics tab shows upcoming appointment for appointment in the past

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#949]
![screen shot 2015-05-14 at 5 13 32 pm](https://cloud.githubusercontent.com/assets/1286381/7644646/e8b86066-fa5c-11e4-8e06-563ea2a42425.png)
This patient should show up on recent missed appointments because the appointment was 4 days ago but is on the upcoming appointments chart instead.

**Comment by garethbowen** [comment]
This is correct as per the spec:

> Should stay on list for XX days (currently 12 days total, 5 before, 7 after scheduled appointment) - OR until appointment confirmation received in that window

I agree it looks a bit odd. Maybe it should be called "Due Appointments" or something?

**Comment by sglangevin** [comment]
Yep, you got me there :)

So does the person go to the recent missed appointments after the 7 days? I think it's fine as long as I put that in the place where we explain the widgets.
