### ISSUE TITLE
When I updated my webapp to the latest version, all of my unstructured messages disappeared

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#951]
This includes the sample data messages - my messages tab is now empty. I updated to alpha-1365 from alpha-1352, medic-api also updated, not sure on the versions.

Once a message was sent, the messages reappeared - strange. It also could have reappeared when a message was received, both happened around the same time.

**Comment by sglangevin** [comment]
They seemed to come back once I sent a new unstructured SMS and then disappear if I went to a different tab and came back. After a few tries of that, though, I'm just getting this message for both reports and for unstructured SMS: SMS message received; it will be reviewed shortly. If you were...

**Comment by sglangevin** [comment]
![screen shot 2015-05-14 at 6 07 07 pm](https://cloud.githubusercontent.com/assets/1286381/7645058/1a84c326-fa64-11e4-9b40-60447dbf744b.png)
It's funny to see that I have unread messages but they won't display!

**Comment by browndav** [comment]
This is a regression that Alex is working on, IIRC.

**Comment by alxndrsn** [comment]
Suffering from!  But yes, I will look into this.

**Comment by alxndrsn** [comment]
This should now be fixed on `develop`.
