### ISSUE TITLE
In Analytics link the CHW name to reports

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#952]
From @sglangevin the CHW name in the ANC Analytics widgets should link to "a search in the reports tab for all reports they have submitted across all patients."

**Comment by garethbowen** [comment]
This can't be tested until #910 is merged.

**Comment by browndav** [comment]
Assigned back to @sglangevin for acceptance testing.

**Comment by sglangevin** [comment]
Looks good - moving to ready.
