### ISSUE TITLE
deleting a Catchment Area's "Contact" is not reflected in the Catchment Area's view until a page refresh is done

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#953]
# To recreate:
1. go to Contacts tab
1. select a catchent area
1. select the Contact for that area
1. delete the contact
1. select the catchment area again in the left-hand list
1. observe that the Contact field is still filled
1. refresh the page, and observe that the contact is no longer set

# Expected behaviour:
The final refresh should not be required - contact should be gone already.

**Comment by garethbowen** [comment]
Sounds like a check is required in the event handler.

**Comment by abbyad** [comment]
Assigned to @joshnesbit for acceptance testing. Let us know if you can reproduce the original issue. You can test using any 0.5 or 0.6 instance.

**Comment by joshnesbit** [comment]
As admin in Chrome on desktop, this worked as expected when deleting a primary contact for a CHP Catchment Area (health_center.field.contact).

This did not work as expected when deleting a primary contact for a Branch (district_hospital.field.contact). In the attached screenshot, Paul was deleted but still shows as a name and link to "no contact selected" – the name and link persist, even after refresh.

![screen shot 2015-09-28 at 11 55 13 am](https://cloud.githubusercontent.com/assets/377216/10145462/1dafea1e-65d8-11e5-8842-d3e859f20213.png)
