### ISSUE TITLE
Namespace report fields

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#957]
Parsed report fields are currently stored directly on the doc which means they can conflict with reserved properties. For example. a form with a `contact` field would be overwritten when sentinel assigns a contact. Refactor this so that all form fields are stored in a specific property.

For bonus points we can also store some meta data about the field such as the type and the label then we save some effort when rendering the row because we don't need to look up the configuration again.

**Comment by mandric** [comment]
For beta 2 I'm thinking I should take a look at this one, mainly in sentinel.

**Comment by abbyad** [comment]
Confirming that the form fields are in `fields` property. Moving to Ready.

**Comment by garethbowen** [comment]
Reopened so @mandric can have a look.

**Comment by browndav** [comment]
@mandric: Could you do a quick okay/not-okay check here with sentinel? If everything's okay, we can move this to `Ready`; if not, we can either mark this as `Returned` and add problem details or file separate more-specific issues.

**Comment by mandric** [comment]
not-okay.  just did a quick look at the transitions and tests in the develop branch and can see fields being used that are not in the fields property.  e.g. `transitions/update_scheduled_reports.js:_getDuplicates`.

**Comment by mandric** [comment]
Also worth noting, fixes for his should be merged into beta (testing) and alpha (develop).

**Comment by browndav** [comment]
To do: commit a work-in-progress PR today for review.
