### ISSUE TITLE
Improvements to date filtering for ANC appointments widgets

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#968]
Registrations are shown in the Upcoming Appointments widget when an appointment is due in the last 14 days or the next 5 days.
Registrations are shown in the Missed Appointments widget when an appointment is due between 14 and 23 days ago.

This was done so that for the standard configuration the appointment disappears from the missed appointments widget when the next appointment is upcoming. This should be made more flexible so it works as expected when the appointment schedule has been modified. This can be done by inspecting when the next scheduled message is due to be sent.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
This is ancient and nobody's asking for it. We're going to have to rewrite this module anyway, either to use embedded klipfolio, couch2pg enabled postgres queries, or nools targets. All of these solutions would be better in terms of configurability, acuracy, and in the case of nools, available offline too.
