### ISSUE TITLE
Update demo data to include facility structure changes

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#971]
Migrate `related_entities` to `contact`.  See https://github.com/medic/medic-webapp/issues/910

**Comment by garethbowen** [comment]
Also migrate form fields into the `fields` property.

**Comment by garethbowen** [comment]
I think this should be working now but medic-data is having a hard time getting builds to pass. Handing off to @mandric to investigate.

**Comment by mandric** [comment]
Fixed yesterday. https://travis-ci.org/medic/medic-data
