### ISSUE TITLE
Schedule configurator uses wrong field start_from date property

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#973]
Production bug, see: https://github.com/medic/projects/issues/2

**Comment by garethbowen** [comment]
If this is accepted we should either backport to testing, or push develop to testing soon.

**Comment by browndav** [comment]
Suspect we need to backport all of the way to `master` (release) as `0.4.5`. @mandric: Does that match what you're thinking this morning?

**Comment by mandric** [comment]
Pretty much was thinking port to testing and merge to master.

**Comment by browndav** [comment]
Hey Gareth, would you mind taking a stab at acceptance testing this? Just looking for confirmation that it's fixed in the latest development build, as well as confirmation that it indeed did make it in to testing/master. Thanks!

**Comment by garethbowen** [comment]
Tested and passing with
- `0.4.8-beta.1520` on `medic-os-v1.1.0-20150623-x64-virtual.iso`.
- `develop/alpha` in my dev environment.
