### ISSUE TITLE
Handle special characters in form submissions

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#974]
If I submit a comment with an exclamation mark using TextForms or Muvuku format the message doesn't get recognised as a form.

If I submit a comment with quotes using TextForms Compact format the quotes are stripped out.

**Comment by abbyad** [comment]
Any update @mandric on this issue?

**Comment by mandric** [comment]
This was ported to master/release already in 0.4.8, I forgot to include the issue number in the changelog.  

https://github.com/medic/medic-webapp/blob/develop/Changes.md#048
