### ISSUE TITLE
Select a language prompt should only set the web app language, not the language for outgoing messages

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#976]
![select language](https://cloud.githubusercontent.com/assets/1286381/7893561/fc58a8ac-0613-11e5-83d4-d791f11d7c57.JPG)
After completing setup during DIY installation, the user is prompted to select a language. This should only set the web app language, not the language for outgoing messages. If it sets both languages, then the language preference step is checked off in the configuration wizard, even if the user is going through it for the first time:
![modem setup](https://cloud.githubusercontent.com/assets/1286381/7893942/312732ca-0618-11e5-9f89-168c363d96f3.JPG)

**Comment by garethbowen** [comment]
The first prompt shouldn't even set the global web app language, it should only set the user's web app language.

**Comment by garethbowen** [comment]
The "Select a Language" dialogue was a red herring - it only sets the users language, not the system defaults for web app *or* outgoing messages. I've modified the Configuration Wizard to not set defaults on the first run through. If the user chooses not to go through the wizard then the defaults (English, English) will be used, however users that do go through the wizard won't see a green tick beside Language Preference until they explicitly choose both.
