### ISSUE TITLE
Outgoing sample messages aren't resolved to contact names

### ISSUE THREAD

**Issue by sglangevin** [medic/medic-webapp#978]
When the sample messages load, the incoming messages are resolved to contact names but the outgoing messages aren't. This results in two message threads instead of one (one for incoming, one for outgoing). This doesn't seem to affect message threads for contacts that I added on my own, only sample data. The reason why this is an issue is because when you start up the app and run the Messages tour, it doesn't run all the way through unless there is a message thread with both sent and received messages.

**Comment by garethbowen** [comment]
The same thing happened on my install. I reran the migration and everything worked as expected. I suspect the version of api you were running when the migration occurred had a bug which has since been fixed. We should test this again when an update iso is released.
