### ISSUE TITLE
/api/v1/records api should be compatible with odk collect

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#983]
pretty sure i'm parsing headers wrong in medic-api.  assert these headers work:
```
"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"
"Content-Type": "application/x-www-form-urlencoded; charset=utf-8"
"Content-Type": "application/x-www-form-urlencoded"
```

**Comment by garethbowen** [comment]
Also there are two handlers for POST to "/api/v1/records". I'm guess it was a bad merge or something...

**Comment by garethbowen** [comment]
> 2015-06-03T19:55:29.997Z - info: 127.0.0.1 - collect [03/Jun/2015:19:55:29 +0000] "POST /api/v1/rec
ords?deviceID=imei%3A351746052385302 HTTP/1.0" - - "-" "-"
> 2015-06-03T19:55:30.033Z - error: Server error: "Content type not supported."

but it works on /add ok...

**Comment by abbyad** [comment]
Still get a 500 using `/api/v1/records` on 0.5.0-alpha.1544.

![screenshot_2015-07-02-17-15-42](https://cloud.githubusercontent.com/assets/789512/8488050/259757ba-20de-11e5-815c-9677cfed14a0.png)

**Comment by mandric** [comment]
@abbyad  any chance you can grab the log entry in couch.log?

**Comment by mandric** [comment]
Or try against alpha.dev.medicmobile.org?

**Comment by mandric** [comment]
Oh nevermind @abbyad I didn't see the demo.app... above.

**Comment by mandric** [comment]
```
2015-07-02T21:09:28.391Z - info: 127.0.0.1 - - [02/Jul/2015:21:09:28 +0000] "HEAD /api/v1/records?deviceI
D=imei%3A351746052385302 HTTP/1.0" - - "-" "-"
 
2015-07-02T21:09:28.501Z - info: 127.0.0.1 - collect [02/Jul/2015:21:09:28 +0000] "HEAD /api/v1/records?d
eviceID=imei%3A351746052385302 HTTP/1.0" - - "-" "-"
 
2015-07-02T21:09:28.647Z - info: 127.0.0.1 - collect [02/Jul/2015:21:09:28 +0000] "POST /api/v1/records?d
eviceID=imei%3A351746052385302 HTTP/1.0" - - "-" "-"
 
2015-07-02T21:09:28.703Z - error: Server error: "Content type not supported."
```

**Comment by mandric** [comment]
@abbyad demo.app is running release and this fix is in develop/alpha.  We need to apply this fix to testing/beta to get it in the next release.  Re-assigning to myself...

**Comment by abbyad** [comment]
Thanks @mandric for spotting that... I was sitting looking at alpha.dev when I did those tests earlier today, so I would have been especially confused if it worked but the reports didnt come in!

Confirming that it works ...when set to the proper URL.

Moving to Ready. Is it possible to include this the next release (0.4.8) so that we can use this endpoint?

**Comment by mandric** [comment]
@abbyad I would keep the issue in Acceptance Testing or Active Work until it's ready on testing/beta.
