### ISSUE TITLE
AMREF-Escalated messages to the HEW Supervisors are missing 

### ISSUE THREAD

**Issue by katanu** [medic/medic-webapp#987]
There should be a message send to the HEW supervisor when the visit confirmation message is not send by the HEW 10 days from the appointment date for ANC and for the 10 days since birth for Birth polio and 2 weeks since appointment for the rest of the appointments

**Comment by nice-snek** [comment]
hi frand @sglangevin, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by sglangevin** [comment]
Very old issue, closing.
