### ISSUE TITLE
Remove lucene

### ISSUE THREAD

**Issue by garethbowen** [medic/medic-webapp#988]
To support offline searching we need to remove our dependency on lucene. I've jotted down [some ideas](https://gist.github.com/garethbowen/c65413a7907328433f6c/).

**Comment by garethbowen** [comment]
Update the docs to remove the lucene search tips.

**Comment by estellecomment** [comment]
Reopening after Jan 2016 meetup. 
Lucene is bloating Medic OS, because it needs java.
