### ISSUE TITLE
attempting to add empty messages causes 500 error

### ISSUE THREAD

**Issue by mandric** [medic/medic-webapp#990]
If header Content-Type is "application/x-www-form-urlencoded" and message is empty we attempt to parse JSON.  We should just pass the empty message to the parser rather than fail with 500.  This could cause the gateway sync process to be interrupted because of an empty message, since it would continuously fail POSTing that message.

**Comment by mandric** [comment]
minor review here please.

**Comment by garethbowen** [comment]
Looks good.
